### ISSUE TITLE
 bug MC-203661 is not fixed with sodium

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#1005]
### Version information

all versions

### Expected Behavior

that MC-203661 fixes the bug

### Actual Behavior

no fix

### Reproduction Steps

tinted glass

![2021-11-29_15 39 11](https://user-images.githubusercontent.com/68275908/143888336-1a5ed6f4-2043-4243-a9dc-d1abf607c991.png)

![2021-11-29_15 34 36](https://user-images.githubusercontent.com/68275908/143888274-3d259d49-9431-4b10-bf3e-1fa942cbd585.png)

### Java version

Java 16

### CPU

i5

### GPU

Intel HD graphics

**Comment by Lolothepro** [comment]
![2022-07-17_09 44 43](https://user-images.githubusercontent.com/68275908/179388991-99a947c1-b46e-4edf-8721-056bf0918067.png)

#1384

**Comment by burgerindividual** [comment]
Should be fixed with #1384

**Comment by Lolothepro** [comment]
You should also close the #1389.
