### ISSUE TITLE
Game crash after running fill command a few times

### ISSUE THREAD

**Issue by stop-x13** [jellysquid3/Sodium#1010]
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Reproduction Steps

1. enter the game
2. fill for a relatively large amount, for stone, air or anything, like /fill ~-50 ~ ~-50 ~ ~~ air
3. try a few times, the game crashes, giving a "memory access violation" error

### Crash Report file

[hs_err_pid603124.log](https://github.com/CaffeineMC/sodium-fabric/files/7633843/hs_err_pid603124.log)

### Additional information

Mod list: sodium, cloth config, mod menu and fabric api

**Comment by MeeniMc** [comment]
can't replicate with 0.4.10, probably stale
