### ISSUE TITLE
Limited to OGL 3.2 on 1.17.1 and 1.18

### ISSUE THREAD

**Issue by ShikuTeshi** [jellysquid3/Sodium#1014]
### Version information

 sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

Was expecting 500+ FPS on OGL 4.6 as I get on MC 1.16.5

### Actual Behavior

Both
MC 1.17.1 w/sodium-fabric-mc1.17.1-0.3.3+build.8
MC 1.18 w/sodium-fabric-mc1.18-0.4.0-alpha5+build.9
Fabric 12.8

Reported running with OGL 3.2 and I achieve about ~300 FPS. This is good but I also run Iris Shaders afterwards. So just to confirm it's not a visual bug but actually not using OGL 4+.

### Reproduction Steps

Managed through MultiMC.
I install versions 1.16.5, 1.17.1, and 1.18.
All get Fabric 12.8 installed through MultiMC manager.
Manually installed the latest Sodium mods for each version found here on Github.
Load a new world, set render distance to 16 and check with F3.

### Java version

Java 17.0.1

### CPU

AMD 5950X

### GPU

RTX 3090

### Additional information

I've tried going through previous reports from Google searches and have seen that it's something related to AMD and being blacklisted due to a missing function I believe. But I thought that was limited to AMD GPU's.

So in the event just having an AMD CPU but a fully capable Nvidia GPU would result in triggering the blacklist I made this report.

**Comment by jellysquid3** [comment]
Why do you think Sodium isn't using newer OpenGL features? Provide screenshots of ALT+F3 while in the same world between the affected versions.

Sodium 0.3+ operates very differently than Sodium 0.2 and older when it comes to chunk rendering. We don't refer to OpenGL versions anymore in the settings, but rather provide options for each specific feature. There is no blacklist in recent versions, and so long as you don't see anything crossed out in [Video Settings > Advanced] there is no problem.

**Comment by ShikuTeshi** [comment]
That would explain why I can see Persistent Mapping turned on when it requires 4.4 which had me confused.

1.16.5
![image](https://user-images.githubusercontent.com/15152750/144364066-859da117-c20b-43b9-94ec-5c745394609c.png)

1.17.1
![image](https://user-images.githubusercontent.com/15152750/144364306-a7d8e8b9-4552-4ee5-ac04-dab57b283c38.png)

1.18
![image](https://user-images.githubusercontent.com/15152750/144364478-4ff4ce2a-bc76-4339-b2aa-3f3f8d55044d.png)
