### ISSUE TITLE
Close button not displaying properly

### ISSUE THREAD

**Issue by efffauw** [jellysquid3/Sodium#1017]
### Version information

sodium-fabric-mc1.17.1-0.3.3+build.8

### Expected Behavior

Close button should be displayed as "close"

### Actual Behavior

Close button displayed as "sodium.option.close.button"

### Reproduction Steps

1. go to options
2. go to video settings

### Java version

Java 17

### CPU

AMD Ryzen 5 3500U

### GPU

Radeon Vega Mobile Gfx

### Additional information

![Screenshot (44)](https://user-images.githubusercontent.com/93001604/144652632-ccb523b5-8498-402f-9588-48322334660d.png)

**Comment by jellysquid3** [comment]
Looks like a problem with whatever mod you're using that changes Sodium's settings screen. This doesn't occur with Sodium by itself.
