### ISSUE TITLE
Sodium greatly degrades performance vs vanilla on Apple silicon

### ISSUE THREAD

**Issue by Nyarumi** [jellysquid3/Sodium#1018]
### Version information

0.4.0-alpha5

### Expected Behavior

Increased performance.

### Actual Behavior

Greatly decreased performance.

### Reproduction Steps

Open vanilla Minecraft and go into any world. Check performance then close game. Install Sodium 0.4.0-alpha5 on Minecraft 1.18 with the latest Fabric loader and API. Launch game and go into the same world. Observe that the performance, especially loading chunks, is notably worse.

### Java version

Azul Zulu 17.30.15 aarch64 (17.0.1+12)

### CPU

Apple M1 Max 10 Core CPU (8+2)

### GPU

Apple M1 Max 32 Core GPU

### Additional information

I used [the instructions listed here](https://gist.github.com/vortck/4ef2d8f1dd2a63689b82a5b05f7b1b37) to install Apple silicon native versions of Java and use the script provided through MultiMC. I am running the game on an external monitor at 4k native. Graphics are set to 16 chunks render distance and 12 chunks simulation distance, fancy graphics. Sodium-exclusive options have not been changed. Without Sodium I can get a fairly consistent 60 FPS with little stutter. With Sodium I get around 35-40 FPS with plenty of noticeable stutter.

**Comment by Nyarumi** [comment]
I am happy to provide more details like logs, but I am unsure what might help so I did not include them in my report.

**Comment by jellysquid3** [comment]
Can you try changing `Video Settings > Advanced > Chunk Memory Allocator` to `SWAP`? macOS on M1 is known to have problems with the default `ASYNC` option.

**Comment by rafaelsms** [comment]
Every version of Sodium works well for me (since 1.17) when Chunk memory allocator is set to SWAP. If this doesn't work for you, I suggest using the guide that I followed (linked below).

I used [this guide](https://github.com/17hoehbr/m1-multimc-hack) for installation and using Java provided from Homebrew (that defaults to OpenJDK 17, which is native to M1).

**Comment by Nyarumi** [comment]
Changing the chunk memory allocator to SWAP fixed it! Maybe there should be a note about this somewhere more obvious. Thanks!
