### ISSUE TITLE
Crashing the game with a non-default fullscreen resolution causes the resolution to persist outside of the game.

### ISSUE THREAD

**Issue by BlueManedHawk** [jellysquid3/Sodium#1019]
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Expected Behavior

When the game crashes when the fullscreen resolution is set to something other than the default resolution of the display, the game would recognize the crash and set the resolution back to normal (or just force-exit fullscreen mode) before crashing.

### Actual Behavior

When the game crashes when the fullscreen resolution is set to something other than the default resolution of the display, such a resolution persists outside of the game, requiring setting it back manually through system settings.

#### _**DANGER:  BEFORE ATTEMPTING TO REPRODUCE THIS BUG, PLEASE MAKE SURE THAT YOU UNDERSTAND HOW TO SET YOUR MONITOR'S RESOLUTION BACK TO NORMAL.  I HEREBY DISCLAIM RESPONSIBILITY FOR ANY ISSUES THAT MAY OCCUR AFTER FOLLOWING THESE INSTRUCTIONS.**_

0.  Fullscreen the game.
1.  Set the fullscreen resolution to something unusual (though you may want to avoid setting it to something _too_ unusual).
2.  Crash the game, probably through joining a game and holding `[F3]+[c]` for ten seconds.
3.  Remember to set your resolution back to normal.

### Java version

17.0.1 64-bit

### CPU

4x Intel® Core™ m3-6Y30 CPU @ 0.90 GHz

### GPU

Mesa DRI Intel® HD Graphics 515 (SKL GT2)

### Additional information

I am on an ASUS Chromebook Flip C302C (_not_ C302CA) running Gallium OS 3.1, a Linux OS, with LXDE on X11.

This issue can be worked around by using the _Not Enough Crashes_ mod.

Yes, I'm certain that this is the right issue template.  This isn't reporting a crash, but a bug that happens _when_ a crash occurs.  (I'm not sure how necessary it is for me to say that, since this is my first time contributing, ¡but better safe than sorry!)

**Comment by yum13241** [comment]
This is to be expected since when you don't set a default res, it sets your screen res, and when you quit normally, it restores back, when it crashes, it doesn't remember and you are stuck. You don't know how exclusive Fullscreen works hmm.

**Comment by BlueManedHawk** [comment]
I know, but I would expect that there would be some sort of minimal crash handler to set the resolution back when a crash happens.

**Comment by yum13241** [comment]
most apps don't do this, even the apps that aren't even remotely related to MC, like Project64. it's really how exclusive mode works.

**Comment by jellysquid3** [comment]
We don't provide a full screen resolution option in Sodium because of problems like this... so I'm not sure how you're changing it in the first place. Exclusive-mode full screen is always a terrible idea and Mojang hasn't gotten around to changing it.

If you need to change the resolution the game is rendering at, you can use something like Resolution Control to do so without modifying the resolution your game is actually rendering at.

**Comment by yum13241** [comment]
> We don't provide a full screen resolution option in Sodium because of problems like this... so I'm not sure how you're changing it in the first place. Exclusive-mode full screen is always a terrible idea and Mojang hasn't gotten around to changing it.
> 
> If you need to change the resolution the game is rendering at, you can use something like Resolution Control to do so without modifying the resolution your game is actually rendering at.

Very true.

**Comment by BlueManedHawk** [comment]
> We don't provide a full screen resolution option in Sodium[.]

Ah, dammit, did I attribute this bug to the wrong mod?  I'm sorry about that.  I'll figure out which mod is causing this and report it there.  Sorry for taking up y'all's time, and thank y'all for being patient.
