### ISSUE TITLE
random Addons for sodium

### ISSUE THREAD

**Issue by craftish37** [jellysquid3/Sodium#102]
Hi,
After used the sodium-fabric mod, I've deduce is "a verrrry best Optifine mod" it.
But, having used Optifine for a long time ago, I missed some things like :
- The advanced graphics options
- The zoom
- The features like the custom texture with a name on a item
- The custom background and loading screen

Besides this, this mod is a great step forward in the optimisation for Minecraft, and I'm impressed by your work on it :)

Hoping to give ideas for a future update, btw do it your way and if you judge this is interesting ;)
Craftish, new user of sodium/lithium/phosphore

**Comment by jaskarth** [comment]
You can find a lot of other mods to fill in the role of optifine here: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

**Comment by craftish37** [comment]
Yeah, I know there mods exists but I think a mod with all the addons is easier to have than 10 mods :)

**Comment by jaskarth** [comment]
Sodium will be staying as an optimization mod, so you will have to use those mods for those features. Thankfully they're all pretty modular and small so it won't be that bad :D

**Comment by craftish37** [comment]
You're right, but I think we've need a complete other mod :)

**Comment by LambdAurora** [comment]
Then why not make it into a modpack? In that way you won't have to download each mods separately ;)

**Comment by Madis0** [comment]
> Then why not make it into a modpack? In that way you won't have to download each mods separately ;)

[I made one](https://www.curseforge.com/minecraft/modpacks/fabulously-optimized), feel free to use and share.

Either way I suggest the OP to vote for #75 so that Sodium could eventually be a "hub" of graphics settings, even if you have to download several mods to get the features 🙂 

@craftish

**Comment by jellysquid3** [comment]
Sodium is not meant to cover every feature which Optifine and friends provide. It's an optimization mod, first and foremost. These features can be supplemented by other mods in the Fabric community.
