### ISSUE TITLE
Chunk builder option isn't avaliable.

### ISSUE THREAD

**Issue by leoNillont** [jellysquid3/Sodium#1021]
**Is your feature request related to a problem? Please describe.**
I think it's more like a missing feature, it was added on 1.18 but it isn't there on sodium
**Describe the solution you'd like**
In minecraft 1.18 there is the new option "Chunk Builder" And i can't find it in 1.18.
**Describe alternatives you've considered**
Explain why this option isn't avaliable, or add it to the settings menu.
**Additional context**

**Comment by jellysquid3** [comment]
Video Settings > Performance > Always Defer Chunk Updates
