### ISSUE TITLE
I played 1.18 and these Hapend I had Optifind (OptiFabric)

### ISSUE THREAD

**Issue by Robertpuggle** [jellysquid3/Sodium#1027]
### Version information

mc1.18

### Reproduction Steps

**I hit Play and the Fabric Icon Showed up**

### Crash Report file

**net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 (C:\Users\super\AppData\Roaming\.minecraft\mods\sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar) with any version that is compatible with:
		 - optifabric 1.12.7
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.7!
		 - Mod 'OptiFabric' (optifabric) 1.12.7 is being loaded from C:\Users\super\AppData\Roaming\.minecraft\mods\optifabric-1.12.7.jar
Inactive mods:
	 - mod 'Sodium' (sodium) 0.4.0-alpha5+build.9, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'joml' (org_joml_joml) 1.10.2, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 (C:\Users\super\AppData\Roaming\.minecraft\mods\sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar) with any version that is compatible with:
		 - optifabric 1.12.7
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.7!
		 - Mod 'OptiFabric' (optifabric) 1.12.7 is being loaded from C:\Users\super\AppData\Roaming\.minecraft\mods\optifabric-1.12.7.jar
Inactive mods:
	 - mod 'Sodium' (sodium) 0.4.0-alpha5+build.9, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	 - mod 'joml' (org_joml_joml) 1.10.2, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186)
	... 3 more**

### Additional information

**I need Help on These Version AKA (sodium-fabric-mc1.18-0.4.0-alpha5+build.9)**

**Comment by Robertpuggle** [comment]
> ### Version information
> 
> mc1.18
> ### Reproduction Steps
> 
> **I hit Play and the Fabric Icon Showed up**
> ### Crash Report file
> 
> **net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: - Replace mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 (C:\Users\super\AppData\Roaming.minecraft\mods\sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar) with any version that is compatible with: - optifabric 1.12.7 Unmet dependency listing: - Mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.7! - Mod 'OptiFabric' (optifabric) 1.12.7 is being loaded from C:\Users\super\AppData\Roaming.minecraft\mods\optifabric-1.12.7.jar Inactive mods: - mod 'Sodium' (sodium) 0.4.0-alpha5+build.9, reason: to replace - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active - mod 'joml' (org_joml_joml) 1.10.2, reason: inactive parent mod (nested jar) at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:188) at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set! A potential solution has been determined: - Replace mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 (C:\Users\super\AppData\Roaming.minecraft\mods\sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar) with any version that is compatible with: - optifabric 1.12.7 Unmet dependency listing: - Mod 'Sodium' (sodium) 0.4.0-alpha5+build.9 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.7! - Mod 'OptiFabric' (optifabric) 1.12.7 is being loaded from C:\Users\super\AppData\Roaming.minecraft\mods\optifabric-1.12.7.jar Inactive mods: - mod 'Sodium' (sodium) 0.4.0-alpha5+build.9, reason: to replace - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.3+d154e2c614, reason: newer version active - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9514, reason: newer version active - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active - mod 'joml' (org_joml_joml) 1.10.2, reason: inactive parent mod (nested jar) at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183) at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48) at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:222) at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:186) ... 3 more**
> ### Additional information
> 
> **I need Help on These Version AKA (sodium-fabric-mc1.18-0.4.0-alpha5+build.9)**

I found out Optifind MODED was Alpha/Beta

**Comment by jellysquid3** [comment]
> Mod 'Sodium' (sodium) is incompatible with mod 'OptiFabric' (optifabric)
