### ISSUE TITLE
Stained glass blocks not rendering through water

### ISSUE THREAD

**Issue by catgirldoll** [jellysquid3/Sodium#103]
### Expected Behavior
All blocks render through water as they would in the vanilla rendering engine

### Actual Behavior
Stained glass does not entirely render through water. The same is not true for normal glass or other transparent blocks

### Reproduction Steps
1. place stained glass block above or below water surface
2. observe

### Attachments

[DxDiag.txt](https://github.com/jellysquid3/sodium-fabric/files/4940905/DxDiag.txt)

![img1](https://user-images.githubusercontent.com/20545957/87841373-a854dd80-c859-11ea-8593-d5786fbd47a3.png)
![img2](https://user-images.githubusercontent.com/20545957/87841379-aee35500-c859-11ea-9107-58a5a2af091b.png)
![img3](https://user-images.githubusercontent.com/20545957/87841382-af7beb80-c859-11ea-8b4c-e3c12a263a3d.png)

### System Information

- Java Version: [1.8.0.211]
- CPU: [i7 8700K at stock]
- GPU: [GTX 1080 Ti]

**Comment by amnotbananaama** [comment]
Duplicate of #38.

**Comment by catgirldoll** [comment]
AmNotBananaAMA is right. Closing.
