### ISSUE TITLE
Not an issue, but a feature request

### ISSUE THREAD

**Issue by Lucario4LyfeYT** [jellysquid3/Sodium#1030]
Something that Minecraft needs is LOD (Level of Detail) as that would provide a-lot of performance boost even with a high render distance(especially with older systems), there are some LOD mods out there, but for older versions of Minecraft (1.12.2 and 1.16.5) and only for forge. I would love to see that implemented in sodium but I would completely understand if you can't do it due to some complexity/problem.
(I tried to keep this short and simple as not to waste your time, I have had bad experiences with writing stuff like this)

**Comment by LucilleTea** [comment]
An LOD system is planned for the future, see #924.
This system is not on the scale of FarPlaneTwo or similar, which I imagine you have in mind, but a system this extensive seems out of Sodium's scope.
