### ISSUE TITLE
(1.18) World flickering at world border

### ISSUE THREAD

**Issue by EsserGaming** [jellysquid3/Sodium#1033]
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Expected Behavior

World acting as normal.

### Actual Behavior

World flickering when at the world border.

### Reproduction Steps

1: Teleport to 300000 blocks any direction.
2: Look around
3: World flickers

### Java version

Java 17

### CPU

AMD Ryzen 2700X

### GPU

AMD RX-480

### Additional information

> **Mods installed:**
(Yes, iris is installed, but I tested without it and it still happened. I was redirected here from this issue: https://github.com/IrisShaders/Iris/issues/1066)
![Screenshot 2021-12-07 154804](https://user-images.githubusercontent.com/36900138/145141031-834b71ac-9638-4b7d-9948-a48abb10765e.png)

> **Footage of the world flickering.. You'll see that iris is enabled in this, but it has the same outcome when iris is disabled.**
http://home.esser.fun/2021-12-07%2015-49-14.mp4

**Comment by erv123** [comment]
happening to me too, i tested with only sodium

**Comment by EinfxchFinn** [comment]
Duplicate of #1006

**Comment by EsserGaming** [comment]
When the search tool doesn't work

**Comment by Gaming32** [comment]
The same thing is happening to me.

**Comment by jellysquid3** [comment]
Closing as duplicate of #1006.
