### ISSUE TITLE
Game crashes on start with fresh 1.18 install

### ISSUE THREAD

**Issue by djwillcaine** [jellysquid3/Sodium#1039]
### Version information

1.18

### Expected Behavior

Game opens

### Actual Behavior

Game fails to open

### Reproduction Steps

1. Install Minecraft 1.18 with latest launcher
2. Install Fabric
3. Install Sodium into mods folder
4. Launch game

### Java version

openjdk version "16.0.2" 2021-07-20

### CPU

AMD Ryzen 5 3600

### GPU

NVIDIA GeForce GTX 760

### Additional information

This is on a fresh windows 10 installation.

**Comment by djwillcaine** [comment]
Log: https://pastebin.com/A3JMPH5u

Culprit seems to be this line?

```
Mixin apply for mod sodium failed sodium.mixins.json:features.fast_biome_colors.MixinClientWorld
```

**Comment by jellysquid3** [comment]
You installed Sodium 0.3.3 for Minecraft 1.17 into a Minecraft 1.18 instance. You need to use the correct version (currently 0.4-alpha5) provided on our downloads page.

**Comment by djwillcaine** [comment]
That was stupid of me! Thanks haha.
