### ISSUE TITLE
The fps cap unlock is not working

### ISSUE THREAD

**Issue by zooto202** [jellysquid3/Sodium#1040]
### Version information

Sodium mc1.18-0.4.0-alpha5

### Expected Behavior

The fps should go past 60

### Actual Behavior

I get 60 fps when i set the cap to unlimited

### Reproduction Steps

GO to video setting and change the fps cap

### Java version

Java 8

### CPU

AMD Ryzen 3 2200G

### GPU

Vega Graphics 8

### Additional information

none

**Comment by jellysquid3** [comment]
You probably left V-Sync enabled. Provide a screenshot of ALT+F3.

**Comment by NopeDK** [comment]
FPS cap set to unlimited, V-Sync disabled, Twitch stream running on second monitor:
![2021-12-10_21 28 36](https://user-images.githubusercontent.com/808397/145637579-feaf133b-e870-435e-b717-72c1ee7936da.png)
Pausing stream it goes to 60 after a second or so.
![2021-12-10_21 28 49](https://user-images.githubusercontent.com/808397/145637730-7ce636fc-24dd-42f9-9218-3d0336f6839d.png)

3700x, 3080, JDK 17, 0.4.0-alpha5-build.9

**Comment by jellysquid3** [comment]
This is a problem with your graphics driver or operating system configuration, as we cannot control whether or not V-Sync is actually used (it's merely a hint the application provides, not a hard requirement.)

As I don't know how the NVIDIA drivers handle this, I'm afraid I can't really provide advice on how you might be able to fix it.
