### ISSUE TITLE
Lag spikes when placing or breaking blocks

### ISSUE THREAD

**Issue by MyJubJr** [jellysquid3/Sodium#1044]
### Version information

fabric-loader-0.12.11-1.18.1 + sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

Breaking or placing blocks, plants/flowers, torches shouldn't cause stuttering or lag spikes.

### Actual Behavior

I experience a short lag spike whenever I break or place any kind of block/item if I have "Always Defer Chunk Updates" set to disabled. However, enabling the option will remove all the mentioned lag spikes. Unfortunately, having this enabled does cause the expected visual issues which are not really desired. I'm sure it has to do with my potato pc, but the earlier 1.16 & 1.17 versions of Sodium did not present this issue. Additionally, this issue does not occur in Vanilla Minecraft as well.

### Reproduction Steps

1. Have "Always Defer Chunk Updates" disabled
2. Break or place any block/item

### Java version

Java 17.0.1

### CPU

Intel Core i7-6700HQ

### GPU

Nvidia GTX 960m

### Additional information

I only have Sodium and Mod Menu installed. I also installed the latest Nvidia driver (497.09), just to be certain that wasn't the issue.
[DxDiag.txt](https://github.com/CaffeineMC/sodium-fabric/files/7697507/DxDiag.txt)

**Comment by jellysquid3** [comment]
Changed the title since the problem is actually that _not_ having it enabled causes the problem.

**Comment by jellysquid3** [comment]
I'm going to make this the tracking issue for a few other problems because I think people are reporting the same issue with different manifestations.

**Comment by MrDiver** [comment]
Suspiciously installing Starlight fixed those random lag spikes caused by the lighting updates. I can confirm that they appear when using Sodium but they only appeared after some time on my map. So it might just be at a certain number of lighting objects that need to be processed.

(I didn't test it with phospor)

**Comment by L1ghtingBolt** [comment]
Happening to me with both phosphor or Starlight independently. Both with and without shaders. it's starting to freak me out.
I'm in latest 1.19.2

**Comment by jellysquid3** [comment]
There is no way for this issue to be resolved as there is no specific reproduction steps to cause the problem (i.e. it's just a general complaint about performance, which is completely unworkable as an issue.)  If you still need help, then please join the [community Discord server](https://caffeinemc.net/discord) for support.
