### ISSUE TITLE
game crash with sodium & iris

### ISSUE THREAD

**Issue by homogoblin28** [jellysquid3/Sodium#1047]
### Version information

sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+build.816

### Reproduction Steps

1. download sodium (sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+build.816) aswell as iris (iris-mc1.18.1-1.1.3)
2. load into a world
3. game crashes.

### Crash Report file

[crash-2021-12-12_17.43.41-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7699287/crash-2021-12-12_17.43.41-client.txt)

### Additional information

not quite sure if this is an issue with iris / sodium or even both so i'm submitting this here and also on iris

**Comment by PweSol** [comment]
Use sodium-fabric-mc1.18-0.4.0-alpha5+build.9 until an official 1.18.1 build is released.

**Comment by PweSol** [comment]
It seems like the current Iris bleeding-edge build works with sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+build.816 as well

**Comment by LucilleTea** [comment]
Yes, a mod that heavily interacts with sodium, like iris, will often need to be updated itself when sodium updates.
