### ISSUE TITLE
Sodium's options fill the entire screen unnecessarily 

### ISSUE THREAD

**Issue by DevBefell** [jellysquid3/Sodium#105]
**Is your feature request related to a problem? Please describe.**
It is inconvenient that the gui is on the top left instead of the middle.
**Describe the solution you'd like**
Make the option GUI Centered/Option to change.
**Describe alternatives you've considered**

**Additional context**

**Comment by jellysquid3** [comment]
This is a bug in Sodium's positioning code, and will be addressed.

**Comment by DevBefell** [comment]
So it is not suppose to be on the top left and it is a bug?

**Comment by douira** [comment]
Is this still relevant? This issue is 4 years old

**Comment by DevBefell** [comment]
As far as I know, I never closed as it was kinda a bug that went into a feature, it was a "bug" that was worked on but ultimately didn't make the cut, and I left this as is as if developers want to reference back, it is here.   The current versions of Sodium all have their GUI's positioned in the top right as opposed to the center so this issue is basically resolved. 
But with the discussions of GUI changes/api for third party mods using the UI it could be kept until then,  see how/when this is counted completed/resolved.

**Comment by douira** [comment]
I think this issue can be closed on account of left-alignment being a feature. There will be separate issues for ui redesigns or options apis.
