### ISSUE TITLE
End sky texture does not appear during dragon fight

### ISSUE THREAD

**Issue by racknae** [jellysquid3/Sodium#1051]
### Version information

mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

In the end, there is a skybox texture which appears when running the game normally.

### Actual Behavior

No texture is visible in the skybox while the ender dragon is present. Instead, only the fog colour is visible.

### Reproduction Steps

1. Create a new world
2. Enter the end dimension
3. Look at the sky

### Java version

Java 17.0.1 64 bit

### CPU

Intel i7 Core-7700

### GPU

NVIDIA GeForce GTX 1080

**Comment by bytzo** [comment]
This behavior may be due to the changes in #710, which prevent the sky from rendering when there is thick fog. Does killing the Ender Dragon cause the sky to render again?

**Comment by racknae** [comment]
Yes, killing the ender dragon or moving far enough away to unload it makes the sky texture reappear.

**Comment by bytzo** [comment]
Having the sky disappear while inside thick fog is intentional to fix several problems with fog occlusion and other vanilla issues. Vanilla's current behavior regarding this [has recently been confirmed as a bug](https://bugs.mojang.com/browse/MC-230905), so I think it would make sense to keep this behavior in Sodium.

**Comment by jellysquid3** [comment]
I agree that this behavior should be kept, since we'd otherwise be special casing things even more. #710 fixes a number of important graphical issues which are exaggerated by other optimizations that Sodium makes about things you shouldn't be able to see.
