### ISSUE TITLE
Cylindrical fog in 1.18 isn't present

### ISSUE THREAD

**Issue by crispyricepc** [jellysquid3/Sodium#1056]
### Version information

mc1.18.1-rc1-0.4.0-alpha5+build.816

### Expected Behavior

Fog changed in Minecraft 1.18 to be a cylinder around the player rather than a sphere

### Actual Behavior

The fog has the 1.17 behavior of being a sphere

### Reproduction Steps

1. Open a world
2. Set the render distance to 2 chunks
3. Observe fog behavior

### Java version

OpenJDK 17.0.1

### CPU

AMD Ryzen 3600

### GPU

Nvidia RTX 2070

**Comment by Demonese** [comment]
Same bug:
![image](https://user-images.githubusercontent.com/57629614/146343139-613f6490-96dd-42cb-8e1c-5da08841f1f4.png)
![image](https://user-images.githubusercontent.com/57629614/146343015-f4a986e9-186d-4268-b671-3dcf48a65c3a.png)
![image](https://user-images.githubusercontent.com/57629614/146343103-3003856f-b13e-40cf-804c-b10021ae0c13.png)
Remove Sodium Mod:
![image](https://user-images.githubusercontent.com/57629614/146343535-813ef0f2-4c54-4900-828c-714f38cde417.png)

**Comment by giorov** [comment]
Yep, just noticed this too. And no way to switch method.

**Comment by jellysquid3** [comment]
This is already fixed, just pending a release.

**Comment by Demonese** [comment]
the problem solved in latest build, nice

**Comment by crispyricepc** [comment]
Thanks for the fix
