### ISSUE TITLE
Rendering issue with Immersive Portals

### ISSUE THREAD

**Issue by Nitjsefnie** [jellysquid3/Sodium#1060]
### Version information

mc1.18.1-rc1-0.4.0-alpha5+build.813 and any newer (tested all)

### Expected Behavior

The portal to fully render

### Actual Behavior

The portal does not fully render

### Reproduction Steps

1. Install Immersive Portals and Sodium
2. Create a superflat world
3. Make a nether portal

### Java version

Java 17

### CPU

AMD Ryzen 5 2600

### GPU

NVIDIA GeForce GTX 1070

### Additional information

With Sodium mc1.18.1-rc1-0.4.0-alpha5+build.812:
![2021-12-17_05 24 29](https://user-images.githubusercontent.com/75166987/146488826-dbd2bc01-f497-419d-a8c2-e1ad8128a479.png)
![2021-12-17_05 24 32](https://user-images.githubusercontent.com/75166987/146488849-5ff7974c-9d6c-4d75-a73f-94f5f2d33f25.png)
With Sodium mc1.18.1-rc1-0.4.0-alpha5+build.816 (tested in both 1.18 and 1.18.1, same behaviour):
![2021-12-17_05 31 57](https://user-images.githubusercontent.com/75166987/146489310-081bc277-05f5-4ac7-92bb-0143bad79c4b.png)
![2021-12-17_05 32 03](https://user-images.githubusercontent.com/75166987/146489319-994b0060-b35a-41f5-ae31-f881f6e853bf.png)

**Comment by magneticflux-** [comment]
Should link to the corresponding issue: https://github.com/qouteall/ImmersivePortalsMod/issues/926

Also, please attach a full F3 screenshot and logs so we don't have to ask questions about drivers and hardware and mod versions.
