### ISSUE TITLE
Render issues on the high distance from world center

### ISSUE THREAD

**Issue by v1ed** [jellysquid3/Sodium#1061]
### Version information

mc1.18-0.4.0-alpha5build.9

### Expected Behavior

Normal rendering of the environment

### Actual Behavior

When you are at 1M+ coordinates, everything starts to flicker

### Reproduction Steps

1. Teleport on 1M+ coordinates

### Java version

Java 17.0.1 64 bit

### CPU

Intel Core i5-2500k

### GPU

Nvidia GeForce GTX 950 2GB

### Additional information

https://youtu.be/vdkx4j5iyPI

**Comment by OneYellowLemon** [comment]
Can confirm. To be more specific, it only happens when you look around, and the chunk you are currently in isn't affected.

Java version: Adoptium 17.0.1
CPU: AMD Ryzen 2700X
GPU: NVIDIA GeForce RTX 3070
Sodium build: `sodium-fabric-mc1.18-0.4.0-alpha5+build.9`

**Comment by qouteall** [comment]
I guess that it's a frustum culling related issue. Vanilla use double for frustum culling but sodium use float. Double is suitable for represent world-coordinate and float is suitable for repersenting camera-centered coordinate. https://github.com/CaffeineMC/sodium-fabric/blob/1.18.x/dev/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/graph/ChunkGraphInfo.java#L76

**Comment by OneYellowLemon** [comment]
Update: This issue has been fixed already by 29b8852f38595ec4df789301cc58e9a36681c9ab and can be closed.
