### ISSUE TITLE
Chunks Load Super Slow On M1 Macs

### ISSUE THREAD

**Issue by rootint** [jellysquid3/Sodium#1063]
### Version information

 Sodium mc1.18-0.4.0-alpha5

### Expected Behavior

Expected smooth gaming experience.

### Actual Behavior

Get massive lag spikes on chunk loading, running without the mod is faster than with it.

### Reproduction Steps

1) Any chunk loading is super slow

### Java version

Java 17

### CPU

Apple M1

### GPU

Apple M1

### Additional information

This issue started from 1.17 versions, it was buttery smooth on 1.16 and lower

**Comment by n08i40k** [comment]
![image](https://user-images.githubusercontent.com/55545594/146687893-42760d0b-ff05-401c-b908-44df4799044b.png)
Try to disable this setting.

**Comment by rootint** [comment]
Thank you for your reply
The setting was already off, and the performance is the same with it on and off. Same laggy chunk loading

**Comment by jellysquid3** [comment]
macOS computers need Video Settings > Advanced > Chunk Memory Allocator changed to "SWAP" -- that is why the option exists. The other user was one option off.

**Comment by rootint** [comment]
It helped with the issue a bit, but running with Sodium is still slower than without it. Maybe it's because of old OpenGL drivers on Apple devices. By the way, on an Intel Mac, this issue is not as bad.

**Comment by kn0wn** [comment]
Running on an 14" m1 pro with 16gb, also having slow chunk issues

**Comment by jellysquid3** [comment]
The M1 doesn't properly support OpenGL and has known performance problems with most applications. There isn't anything we can do, because Apple has decided that they don't care about open standards.
