### ISSUE TITLE
Blocks with animation are not animated (1.18.x/vertex-pulling)

### ISSUE THREAD

**Issue by KingOfTheClouds** [jellysquid3/Sodium#1064]
### Version information

mc1.18.1-rc1-0.4.0-alpha5+build.830 (1.18.x/vertex-pulling)

### Expected Behavior

Texture of blocks such as fire, water/lava, nether portal blocks, active smokers and seagrass should be animated.

### Actual Behavior

Texture of (at least) the above blocks are static (but particles seem normal). However, some blocks like magma blocks have animated textures.

### Reproduction Steps

Get blocks/buckets from Creative mode.

### Java version

Java 17

### CPU

AMD Ryzen 9 5900HX

### GPU

NVIDIA GeForce RTX 3060 Laptop

### Additional information

I understand this is an unstable build. Perhaps animated texture is still being implemented in the 1.18.x/vertex-pulling branch (I have no idea what the branch is doing), so if this issue is expected please close it.  The latest build of 1.18.x/dev (mc1.18.1-rc1-0.4.0-alpha5+build.816) doesn't have this issue.

**Comment by jellysquid3** [comment]
The 1.18.x/vertex-pulling branch was an experiment and we won't be using the work that was done there. As such, this issue can be closed since it isn't relevant any longer.
