### ISSUE TITLE
Game freezes permanently at random, block outlines randomly glitched and transparent

### ISSUE THREAD

**Issue by BigFatGandalf** [jellysquid3/Sodium#1067]
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Reproduction Steps

1. Open the game and join a server. (Unsure if happens in singleplayer.)
2. Wait a few minutes, and look around at blocks.
3. You will usually see a glitched outline if you look at certain blocks at certain, quite precise angles.
4. The game's screen will eventually freeze permanently and you'll be forced to either close the game manually or intentionally crash it using the debug setting.

### Crash Report file

[crash-2021-12-19_20.14.34-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7742182/crash-2021-12-19_20.14.34-client.txt)

### Additional information

The angles for the broken block outlines are consistent, a slight shift away from an angle will "fix" it, but moving your crosshair back to the same angle as before will cause the issue to happen again. Also, whenever the game permafreezes, you can still open chat, inventory and pause the game, and can send chat messages perfectly fine (although blindly). However, you can't interact with your inventory or any menu buttons.

**Comment by jellysquid3** [comment]
Stale issue. Seems to be caused by out-of-date graphics drivers. If you can still reproduce it in the latest version, then open a new issue.
