### ISSUE TITLE
Can I help translate this mod into Chinese (Simplified)？

### ISSUE THREAD

**Issue by linzexin022** [jellysquid3/Sodium#107]
**Is your feature request related to a problem? Please describe.**

I'm a player from China and would like to help you translate this mod into Chinese (simplified), so that those Chinese players (specially teens) who don't know English can easily understand the descriptions.

**Describe the solution you'd like**

Add a Chinese (simplified) translation! 

**Describe alternatives you've considered**

Add translations by yourself XD

**Additional context**
 
*SCREENSHOT*

**Comment by Kroppeb** [comment]
All translations are being done here: https://jellysquid.oneskyapp.com

**Comment by jellysquid3** [comment]
Please use the OneSky page linked above.
