### ISSUE TITLE
Armour Stand keeps facing South despite being placed from another direction

### ISSUE THREAD

**Issue by Galland780** [jellysquid3/Sodium#1073]
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5

### Expected Behavior

Armour Stand should face towards the player (me) and not facing South.

### Actual Behavior

It keeps facing South. For example, when I am facing North, it will immediately face South. Pretty creepy.

### Reproduction Steps

1. Place an armour stand facing any direction. the result is always the same.

### Java version

Java 17.01

### CPU

Intel Core i5-1035G1

### GPU

NVIDIA GeForce MX330

### Additional information

1. I really want to post a video of this "bug" but the video is too large.
2. I am sorry if some of the things I wrote is wrong or hard to understand.
3. The Armour Stand sometimes will change the direction it is facing towards the original direction that place for a brief few seconds.
4. I am not sure if this is a problem with Sodium but when I deleted Sodium from my mods folder, the armour stand act normal again.

**Comment by MeeniMc** [comment]
I can't reproduce with the same version.

**Comment by Galland780** [comment]
Oh really? Ah, that's unfortunate. I still have this problem but I just
ended up ignoring it in the end.

I could take some pics of it or video but I don't think I can send you
through email. Oh and also, I'm not sure if it's the source of the issue
but I think it is because of Sodium being in Alpha.

But yeah, thank you for responding. It is kinda sad that the problem I'm
having is not experienced by anyone else but again, thank you for
responding my dude!
