### ISSUE TITLE
{BUG} [Low Priority] Strikethrough Renders over Description Box

### ISSUE THREAD

**Issue by BeansBeefBroccoli** [jellysquid3/Sodium#1074]
### Version information

mc1.17.1-0.3.3+build.8

### Expected Behavior

The strikethrough shouldn't render over the description box when hovering over an option.

### Actual Behavior

The strikethrough is rendered over the description box when hovering over an option.

### Reproduction Steps

1. Launch Minecraft with Sodium on Windows 10
2. Open "Options"
3. Open "Video Settings"
4. Open "Extras"
5. Hover cursor over "Use Fast Random"
6. The strikethrough from "Reduce Resolution on macOS" should render over the description for "Use Fast Random"

### Java version

16

### CPU

AMD Ryzen 3 2200G with Radeon Vega Graphics

### GPU

AMD Radeon(TM) Vega 8 Graphics

### Additional information

I am using the [Fabulously Optimized](https://curseforge.com/minecraft/modpacks/fabulously-optimized/files/3567692) modpack, version 2.6.1 for 1.17.

Screenshots:
![strikethrough1](https://user-images.githubusercontent.com/69123018/146966368-731b79de-3a44-4153-bc6b-94c3937edfa2.jpg)
![strikethrough2](https://user-images.githubusercontent.com/69123018/146966366-9144d6b2-f063-4e50-bb09-a94038a5c507.jpg)

**Comment by LucilleTea** [comment]
This menu you are using is a replacement of Sodium's menu, from a separate mod, [Reese's Sodium Options.](https://github.com/FlashyReese/reeses-sodium-options)
You'll need to report the issue there instead, since this can't happen in Sodium's own menu.

**Comment by BeansBeefBroccoli** [comment]
Ok, thanks!
