### ISSUE TITLE
AMD FSR could be added

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#1075]
Sodium was created to increase the performance of low power PCs as well as high power PCs, and I notice that the old topics have been closed, as FSR is not officially supported by AMD but it seems to me that the RetroArch team has managed to port FSR to opengl, so I was wondering, from RetroArch's code, could you add FSR?

If this is not possible, it could always give an idea to a modder :)

**Comment by jokbon** [comment]
Bruh iam alredy using fsr in minecraft year ago

**Comment by jellysquid3** [comment]
@jokbon If you are aware of a solution that allows FSR to be used in Minecraft, then you should share that instead of making snarky responses.

**Comment by itasli** [comment]
> @jokbon If you are aware of a solution that allows FSR to be used in Minecraft, then you should share that instead of making snarky responses.

I think he refers to this program : https://store.steampowered.com/app/993090/Lossless_Scaling/

**Comment by Lolothepro** [comment]
On my PC, this software makes me lose performance

**Comment by jokbon** [comment]
https://github.com/Blinue/Magpie/releases fine

**Comment by Lolothepro** [comment]
Moreover, all programs that add FSR in this way are only Windows compatible

**Comment by sad-goldfish** [comment]
> Moreover, all programs that add FSR in this way are only Windows compatible

Gamescope should work on Linux

**Comment by jellysquid3** [comment]
Not planned. The fragment shader in Minecraft is _very_ inexpensive, and it's rarely the case that people are fragment bound either way. Even if they were, image upscaling as done via FSR is unlikely to make much of a difference, because it's hard for that to be any faster than an already very simple fragment shader.
