### ISSUE TITLE
I would like you to at shader support, I know that Iris Shaders, Compatible with sodium works, but i cant change unwanted motion blur, you i would like you to add shader support

### ISSUE THREAD

**Issue by TesterOfDoom** [jellysquid3/Sodium#1076]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DioEgizio** [comment]
wdym? Sodium is not gonna have shader support probably, it's just an optimization mod, not a shadermod, use Iris for that.
If you are talking about shader options, iris is working on it

**Comment by giorov** [comment]
yeah, in the meantime find the config file inside your shader and you can edit all the settings there by leaving the archive open and opening in a text editor.
For example, in BSL's archive, go into the shaders folder within, then lib folder, then open settings.glsl

**Comment by TesterOfDoom** [comment]
Ight, thanks!
