### ISSUE TITLE
[1.18.x/vertex-pulling branch] Shader compilation fails when joining a world

### ISSUE THREAD

**Issue by Octol1ttle** [jellysquid3/Sodium#1078]
### Version information

mc1.18.1-rc1-0.4.0-alpha5+build.830 [Latest Actions artifact from 1.18.x/vertex-pulling]

### Reproduction Steps

1. Download the artifact and put it in your `mods` folder
2. Try joining a world (in this case I tried to connect to a server)
3. Minecraft crashes!

### Crash Report file

Log file: https://paste.gg/p/anonymous/7e7bab40a9634cf9b46d94615b66423a
Crash report: https://paste.gg/p/anonymous/22d8d88bb7f54d71885c30559332f09e

### Additional information

I know this is an alpha build not designed for production use, I'm reporting this issue in case this crash isn't known about

**Comment by jellysquid3** [comment]
We're not going forward with the changes on this branch, so this issue doesn't matter. It was a short lived experiment.
