### ISSUE TITLE
1.16.5 Sodium crashing minecraft

### ISSUE THREAD

**Issue by hxlloworld** [jellysquid3/Sodium#1084]
### Version information

sodium-fabric-mc1.16.5-0.2.0+build.4

### Reproduction Steps

1. Launch the fabric version
2. It crashes

### Crash Report file

https://pastebin.com/BsSHdDCH

### Additional information

I do have other mods, I wrote them down below;
-fabric-api-0.42.0+1.16
-lambdynamiclights-fabric-1.3.4+1.16
-lithium-fabric-mc1.16.5-0.6.6
-logical_zoom-0.0.8
-modmenu-1.16.22
-phosphor-fabric-mc1.16.2-0.8.0
-smooth-chunks-1.0.0

**Comment by Pectacular** [comment]
Quoting the Smooth Chunks Curseforge page -
"Unfortunately the mod is currently incompatible with both Sodium and OptiFine as well as any other mods that heavily modify rendering code."

**Comment by ghost** [comment]
You need to remove Smooth Chunks mod aka **smooth-chunks-1.0.0** 

1. Smooth Chunks mod is currently not supported for both Optifine and Sodium
 ![image](https://user-images.githubusercontent.com/85755985/147409753-ab756b6c-3e53-4fa7-ac49-8356e6a9261d.png)
2. They officially stated that in their Curseforge page that the mod is currently not supported for sodium but is planned to support sodium in upcoming updates
