### ISSUE TITLE
flicker blocks

### ISSUE THREAD

**Issue by mrFjk** [jellysquid3/Sodium#1085]
### Version information

mc1.18-0.4.0-alpha5

### Expected Behavior

blocks should not flicker

### Actual Behavior

When I teleport to large coordinates, the blocks start to flicke. Everything is fine on small coordinates

https://user-images.githubusercontent.com/92950042/147417683-d5243c9c-de4a-4f91-8ebe-697466b9d2c9.mp4

### Reproduction Steps

1. teleport to large coordinates

### Java version

Java 17.0.1 64bit

### CPU

AMD Ryzen 7 PRO 1700X

### GPU

NVIDIA GeForce GTX 1060 3GB

**Comment by doonv** [comment]
Can confirm this happens to me too.

![image](https://user-images.githubusercontent.com/58695417/147481682-2d2fbb30-47b6-40b6-a767-05bb9ec221f3.png)

**Comment by lelumlama** [comment]
this happens to me as well https://streamable.com/fwhww8

**Comment by lostopkk** [comment]
duplicate #1006
