### ISSUE TITLE
Graphics are locked on Fast, while it displays they are on Fancy.

### ISSUE THREAD

**Issue by itsfirestorm** [jellysquid3/Sodium#1087]
So, long-story short, I was playing on an MC server with friends, when I noticed something was off with my texture pack, which made leaves more bushier, but **wasn't compatible with fast graphics.** Same thing happened with water, it showed the solid-looking fast water instead of the translucent one that should show up with fancy graphics, what's the issue?

![2021-12-28_18 32 51](https://user-images.githubusercontent.com/38797905/147592591-349a9441-f3b1-4879-9e6e-36ba51844538.png)

**Comment by ChristopherTheBoss** [comment]
Same with Iris, non-translucent water with Fancy graphics and shaders disabled.
Finding clay was impossible so I installed an Iris shader. It didn't even occur to me that the water is translucent in vanilla, I've been an absolute zombie lately.

**Comment by itsfirestorm** [comment]
I don't think it's an Iris problem, I uninstalled Iris to see if it changed anything and the water wasn't translucent.

**Comment by jLn0n** [comment]
if u have vanillatweaks resourcepack on disable the wavy water addon it might fix the problem
