### ISSUE TITLE
Game won't start unless config files are deleted

### ISSUE THREAD

**Issue by elidhan** [jellysquid3/Sodium#1088]
In the latest version for 1.18, the game freezes at the title screen if the config files exist.

When running the game after deleting the config files, everything works fine.

**Comment by jellysquid3** [comment]
Can you provide a copy of the bad config file versus the new config file? And a client log file, if you have it?

**Comment by jellysquid3** [comment]
In the future, do not circumvent the issue template or your issue will be closed as invalid. The template contains fields for necessary debugging information, which without, makes diagnosing issues most often impossible.

**Comment by MeeniMc** [comment]
In 0.4.10 (and probably before) this shows a warning screen with an option to reset the config. This is resolved.
