### ISSUE TITLE
Tooltips are not 'always on top' after installing multiple mods

### ISSUE THREAD

**Issue by Slugstur** [jellysquid3/Sodium#1091]
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Expected Behavior

Tooltips should be 'always on top'

### Actual Behavior

When showing a ToolTip they are hidden behind REI

### Reproduction Steps

After installing the mod 'Inventory Profiles Next' my tooltips are hidden behind REI. I contacted the developers and they said it is caused by Sodium. Apparently it did work in 1.17, but not in 1.18(.1)

### Java version

Java 17

### CPU

Intel core i7

### GPU

2080Ti

### Additional information

![image](https://user-images.githubusercontent.com/96501456/147814359-10da1758-f19e-49de-85f6-bb088ca63091.png)

My current mod list is quite extensive;
AdvancementInfo, AdventureZ, Applied Energistics 2, Animatica, Annotated DI, AntiGhost, Apoli, AppleSkin, AttributeFix, Auto Config v1 Updated, Awesome Dungeon, BCLib, Better Animals Plus, Better End, Better Nether, Better Third Person, Borderless Mining, Bosses of Mass Destruction (Beta), Calio, cAn i MiNe thIS bLOCk?, Capes, Custom Entity Models, Cherished Worlds, CITResewn, Clickable Advancements Mod, Client Tweaks, Cloth Config v6, Colormatic, Comforts, CompleteConfig, Conjuring, Continuity, Controlling For Fabric, Crafting Tweaks, Cull Leaves, Disable Custom Worlds Advice, Disenchanter, Deep Mob Learning: Refabricated, DML: Refabricated - Base, DML: Refabricated - Vanilla Events, DML: Refabricated - Glitch Armor, DML: Refabricated - REI Integration, MmmMmmMmmMmm, Dynamic FPS, Easy Magic, Eating Animation, Elytra Trinket, Enchanting Infuser, EnchantmentDescriptions, Enhanced Block Entities, EntityCulling-Fabric, Expanded Storage, Experience Bug Fix, Extra Origins, Fabric API, Fabric API Base, Fabric API Lookup API (v1), Fabric Biome API (v1), Fabric BlockRenderLayer Registration (v1), Fabric Command API (v1), Fabric Commands (v0), Fabric Containers (v0), Fabric Content Registries (v0), Fabric Crash Report Info (v1), Fabric Dimensions API (v1), Fabric Entity Events (v1), Fabric Events Interaction (v0), Fabric Events Lifecycle (v0), Fabric Game Rule API (v1), Fabric Item API (v1), Fabric Item Groups (v0), Fabric Key Binding API (v1), Fabric Key Bindings (v0), Fabric Language Kotlin, Fabric Lifecycle Events (v1), Fabric Loot Tables (v1), Fabric Mining Level API (v1), Fabric Mining Levels (v0), Fabric Models (v0), Fabric Networking API (v1), Fabric Networking (v0), Fabric Object Builder API (v1), Fabric Object Builders (v0), Fabric Particles (v1), Fabric Registry Sync (v0), Fabric Renderer API (v1), Fabric Renderer - Indigo, Fabric Renderer Registries (v1), Fabric Rendering Data Attachment (v1), Fabric Rendering Fluids (v1), Fabric Rendering (v0), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Screen API (v1), Fabric Screen Handler API (v1), Fabric Structure API (v1), Fabric Tag Extensions (v0), Fabric Textures (v0), Fabric Tool Attribute API (v1), Fabric Transfer API (v1), Fabric Loader, Fabrishot, Fake Player API, Falling Leaves, Farsight Mod, FastOpenResourcePacks, Fireplace Lib, Forge Config API Port, Geckolib, Gobber2, Health Overlay, Indium, Industrial Revolution, Inventory HUD +, Inventory Profiles Next, Iris, Iron Jetpacks, Item Model Fix, Jankson, Kanos Config, LambdaBetterGrass, LambDynamicLights, Language Reload, LazyDFU, LibBlockAttributes (Core), LibBlockAttributes (Fluids), LibBlockAttributes (Items), LibGui, Library Ferret, Lithium, Lovely Snails, Maelstrom Library, Magna, megane, megane-applied-energistics-2, megane-base, megane-fabric-transfer, megane-industrial-revolution, megane-lib-block-attributes, megane-runtime, megane-team-reborn-energy, megane-vanilla, megane-wireless-networks, MidnightLib, Manningham Mills, Mob Origins, Mod Menu, MoreChatHistory, MoreVillagersFabric, Mo' Structures, Nature's Compass, NinjaPhenix's Container Library, No Fade, NotEnoughAnimations, Not Enough Crashes, Origins, oωo, Patchouli, Pehkui, Pal, Pling, Pride Lib, Reach Entity Attributes, Fabric Recipe Conditions, Reese's Sodium Options, Repurposed Structures, Roughly Enough Items, Roughly Enough Resources, 3d Skin Layers, 'Slight' GUI Modifications, Smooth Boot, Sodium, Sodium Extra, SpruceUI, Starlight, Step Height Entity Attribute, Stoneholm, Stylish Effects, Energy, Textile Backup, Things, ToolStats, ToolTip Fix, Trading Post, TrashSlot, Trinket of Undying, Trinkets, Unforgiving Void, VanillaTweaks, VoidZ, WI Zoom, Wireless Networks, WMITAF, wthit, Xaero's Minimap, Xaero's World Map, You're in Grave Danger, YOSBR

**Comment by amnotbananaama** [comment]
It looks like this happens with only Inventory Profiles and REI? https://github.com/blackd/Inventory-Profiles/issues/85

**Comment by Slugstur** [comment]
Yes, I tested it as well with only those two mods (so without Sodium) and it happened. So this probably has nothing to do with Sodium. Sorry for blaming Sodium. Guess this can be closed.
