### ISSUE TITLE
Burning causes screen to glitch in Build 854.

### ISSUE THREAD

**Issue by TenthCrusadering** [jellysquid3/Sodium#1095]
### Version information

mc1.18.1-0.4.0-alpha5+build.854

### Expected Behavior

When you are burning, it should display a burning animation.

### Actual Behavior

When you are burning, a couple of glitched lines instead appear which block your vision.

![image_2022-01-02_210146](https://user-images.githubusercontent.com/96677650/147872459-4b601e07-c302-4937-a52e-ae63dd70c0af.png)

### Reproduction Steps

1. Load into a world using Build 854.
2. In the world, set yourself on fire.

### Java version

Java 17 64-bit

### CPU

Intel Core i7-8750H

### GPU

NVIDIA Geforce GTX 1050 Ti (Notebook)

### Additional information

While investigating the issue, these are some quirks I found:
- Glitch only happens on first person mode, being on third person is fine.
- Being on cinematic mode does not fix it.
- Resource packs do not patch this glitch - they vary the size and the colour of the glitched lines.
- Adding mods does not affect it (even using the build itself has the glitch in it.)

**Comment by CyberLykan** [comment]
Can confirm. I noticed it as well.

Last working build is 848.

**Comment by Cloudperry** [comment]
Its broken on an AMD gpu as well (Rx Vega 56). My gpu driver is Mesa 21.3.3.

**Comment by TenthCrusadering** [comment]
It seems to be fixed as of Build 865. Kudos.
