### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RETROSHMIAK** [jellysquid3/Sodium#1096]
### Version information

mc1.18-0.4.0-alpha5

### Expected Behavior

non flashing minecraft

### Actual Behavior

playing on a server with a new version for 1.18.1 my game is flashing

### Reproduction Steps

just log into the server

### Java version

Java 16

### CPU

AMD Radion Vega 8 

### GPU

AMD Ryzen 3 3200G with Radion Vega  Graphics

**Comment by Lolothepro** [comment]
#1006 ?

**Comment by jellysquid3** [comment]
Not enough information. We don't have the developer resources to triage issues that make no attempt to actually fill out the issue template.

Your issue is either a duplicate of #1006 or something new. If it's the latter, provide more information and ask for this issue to be re-opened.
