### ISSUE TITLE
Client crashes when joining a server

### ISSUE THREAD

**Issue by OXDHEIN** [jellysquid3/Sodium#1099]
### Version information

crashes when i join a server sometimes

### Reproduction Steps

Sometimes the client crashes when joining the server the only mods i use is sodium, fabric api
how to fix this?

**Comment by CyberLykan** [comment]
Have you tried build 848? https://github.com/CaffeineMC/sodium-fabric/actions/runs/1639863738

**Comment by jellysquid3** [comment]
You have not filled out the issue template, which means we have no information that can be used to debug/fix this problem, and as such this issue will be closed as invalid.

Either open a new issue with all the necessary information provided, or update this issue with the required information (a crash log, hardware information, versions used) and ask for this issue to be re-opened.
