### ISSUE TITLE
Smooth Lighting Level

### ISSUE THREAD

**Issue by Manamongods** [jellysquid3/Sodium#1101]
100% smooth lighting is hard on my eyes, and the "Smooth Lighting Level" setting in optifine is really nice, and I'm missing it with sodium.

It would be very nice if it was added.

**Comment by jellysquid3** [comment]
Sodium doesn't provide a kitchen sink of features, nor is it meant to be a replacement for OptiFine, which does provide the kitchen sink. It would be optimal for another mod to integrate with Sodium which enables this functionality, and there are already a few which do (see Sodium Extra, for example.)

**Comment by Manamongods** [comment]
That makes sense, although Sodium Extra doesn't seem to do this yet

**Comment by jellysquid3** [comment]
Sorry, I meant that there were mods which extend Sodium's functionality already, not that they had already implemented it. Point being that those mods would be the best place to ask for this feature to be added.

**Comment by Manamongods** [comment]
Ah, well I've now made the request
https://github.com/FlashyReese/sodium-extra-fabric/issues/125
