### ISSUE TITLE
Multithread the Rendering Engine

### ISSUE THREAD

**Issue by MayorBryce** [jellysquid3/Sodium#1102]
As the name suggests, allow more than one thread to render a frame, or render a frame on each thread. On high and low powered cpus, this would be the cherry on top for performance - all performance benefits, than quadruple or more the frames for each thread on your PC. I bring this up because I have an AMD Ryzen 7 5800h with 8 cores / 16 threads and an Nvidia RTX 3070 mobile GPU, and the entire bottleneck is the CPU - one single thread is slowing down the entire game. I have heard it cannot be done with the way Minecraft is coded, but if you could at least look into it, that would be great! Thank you.

**Comment by DioEgizio** [comment]
Uh I'm not sure if this is possible on opengl

**Comment by ThimothyXYZ123** [comment]
i dont think thats possible in minecraft unless you rewrite it

**Comment by jellysquid3** [comment]
No. It's not happening.
