### ISSUE TITLE
On-screen burning animation is broken

### ISSUE THREAD

**Issue by macross0** [jellysquid3/Sodium#1107]
### Version information

mc1.18.1-0.4.0-alpha5+build.856 (commit 6390562)

### Expected Behavior

On-screen fire animation should render properly.

### Actual Behavior

On-screen fire animation is corrupted.

### Reproduction Steps

Set yourself on fire in any way.

### Java version

GraalVM Community 21.3.0 JDK 17.0.1 64bit

### CPU

Intel Core I3-5005U

### GPU

Nvidia GeForce 920MX with 1GB VRAM and 470.86 drivers

### Additional information

Without Sodium installed:
![2022-01-06 19-42-59](https://user-images.githubusercontent.com/46577731/148428632-3e01f32b-d11a-43dc-9059-22a54ada4ddf.png)

With Sodium installed:
![2022-01-06 19-47-10](https://user-images.githubusercontent.com/46577731/148428643-c6f510b6-d7ac-40bc-903b-a94f957e820a.png)

**Comment by macross0** [comment]
My mods folder:
![image](https://user-images.githubusercontent.com/46577731/148429565-893cbc00-fb0a-45cc-9fc8-9f856a2c3949.png)

**Comment by jellysquid3** [comment]
Stop using development builds if you don't want random bugs. GitHub Actions is not meant to be a place for end users... they're CI builds, for people testing specific things.

This was already fixed in some commit since you last updated.
