### ISSUE TITLE
Crash with latest sodium from github action

### ISSUE THREAD

**Issue by keatit71** [jellysquid3/Sodium#1109]
### Version information

sodium-fabric-mc1.18.1-rc1-0.4.0-alpha5+build.846

### Reproduction Steps

Start minecraft with newest version of sodium from github actions.

### Crash Report file

[sodium error latest.log](https://github.com/CaffeineMC/sodium-fabric/files/7829661/sodium.error.latest.log)

### Additional information

tried with newest and last fabric api since i thought that may be causing it which made no difference. Oldest version of sodium github action that worked was this one https://github.com/CaffeineMC/sodium-fabric/actions/runs/1639231038

**Comment by jellysquid3** [comment]
You have incompatible mods. You are expected to know how to diagnose these problems if you are using the bleeding edge versions of our mods.
