### ISSUE TITLE
1.8.9 support pls

### ISSUE THREAD

**Issue by PumpkinXD** [jellysquid3/Sodium#111]
There's a lot players like me are still playing Minecraft 1.8.9 on some servers...

**Comment by jellysquid3** [comment]
This won't be considered. Backports are not happening.

**Comment by hYdos** [comment]
well thats sad

**Comment by valoeghese** [comment]
Beta 1.7.3 support pls

**Comment by luximus-hunter** [comment]
Backports won't happen, as stated on the mod page on curseforge, as well as in the repository's readme

**Comment by hYdos** [comment]
oh valo is here now

**Comment by luximus-hunter** [comment]
Who?

**Comment by jellysquid3** [comment]
Stop shitposting on this issue.
