### ISSUE TITLE
Sodium fails to draw chunks located at the 4 corners of finite worlds

### ISSUE THREAD

**Issue by akemin-dayo** [jellysquid3/Sodium#1111]
### Version information

Confirmed to occur on 0.4.0-alpha5+build.9 (mcje1.18.1), 0.3.3+build.8 (mcje1.17.1), and 0.2.0+build.4 (mcje1.16.5)

### Expected Behavior

All 4 corner chunks of the finite world (64x64x64 blocks, or 4x4 chunks in this example) should be visible just as they are in the vanilla renderer (and OptiFine).

![2022-01-07_17 31 17](https://user-images.githubusercontent.com/1980487/148626389-82cc0165-c735-4c11-b970-ca99a934794d.png)

![2022-01-07_17 29 10](https://user-images.githubusercontent.com/1980487/148626395-36aaf428-1cd1-4a63-a1b6-1898bfd62697.png)

### Actual Behavior

Sodium fails to render the 4 corner chunks of the finite world, drawing nothing where there should be land.

Screenshot shows an instance that has additional cosmetic mods applied to it, but this issue occurs even with _just_ Sodium and the Fabric API loaded, with nothing else.

![2022-01-07_17 32 17](https://user-images.githubusercontent.com/1980487/148626434-2a8d7745-2f7b-4d1b-a3ac-dcbdcd912e3a.png)

### Reproduction Steps

Create a small, finite world (in my example, 64x64x64 blocks, or 4x4 chunks) with a world border and join it from a client with Sodium installed.

### Java version

Java 17

### CPU

Intel Core i9-9900K

### GPU

NVIDIA GeForce RTX 2060

### Additional information

I have confirmed that this issue occurs with only Sodium and Fabric API enabled.

(The screenshots above have more cosmetic mods enabled, but that does not affect this issue.)

**Comment by jellysquid3** [comment]
The server likely isn't sending (empty) chunks around the corner, leading to Sodium not rendering those chunks because it doesn't have all the necessary data. If so, this is a bug on their side.

We probably won't do anything on our side to fix this, since it would mean that we need to aggressively rebuild chunks on the edge of the view distance as the player moves around.
