### ISSUE TITLE
Minecraft freezes on startup on Intel HD Graphics 4000 

### ISSUE THREAD

**Issue by giabao06** [jellysquid3/Sodium#1112]
### Version information

mc1.18.1-0.4.0-alpha5+rev.6390562

### Expected Behavior

Minecraft would start normally

### Actual Behavior

The game loads for a bit, then did not respond. Progress bar (on mojang studios screen) stays little, no log updates from there.

### Reproduction Steps

1. Enable any 1.18 version of sodium on Actions
2. Run the game

### Java version

Java 17

### CPU

Intel Core i5-3320M

### GPU

Intel HD Graphics 4000

### Additional information

Specific machine: ThinkPad X230. 
Seems to be a driver issue on Windows 10 since I tested with 2 of my friend's X230; all same results. No mod conflict is reported. All released 1.17 versions still works.

**Comment by Pectacular** [comment]
This is because of commit 69fb6d3616ecee7df042703ba35b21f49d0c55b2.

**Comment by giabao06** [comment]
If that was on the 1.18.x/next branch, then the dev branch builds would still work?

**Comment by Pectacular** [comment]
I guess so

**Comment by giabao06** [comment]
No luck with the dev branch, they might have merged it sometime ago. Also are there plans to backport this to previous OpenGL versions or it is just deprecated?
