### ISSUE TITLE
Stained glass layered opacity effect only visible at certain angles

### ISSUE THREAD

**Issue by Zeklandia** [jellysquid3/Sodium#1117]
### Version information

mc1.18-0.4.0-alpha5+build.9

### Expected Behavior

Alternating layers of differently colored stained glass should increase opacity with each layer, eventually becoming opaque.

### Actual Behavior

The expected fog effect works in the downward direction, partially in lateral directions, and barely in the vertical direction. It behaves weirdly at chunk and sub-chunk borders, too.

### Reproduction Steps

1. Layer alternating stained glass colors (e.g., lime, yellow, lime, yellow, etc.) in any direction
2. Look through the stained glass at one end toward the other, perpendicular to the layering

### Java version

Java 17.0.1

### CPU

AMD Ryzen 9 3000 series

### GPU

NVIDIA GeForce RTX 20 series

### Additional information

I tested the same location in vanilla and with just Sodium. Adding other mods didn't seem to affect it, including Lithium, Starlight, Iris, and Indium.

Here is the test setup I made with Sodium:
Up:
![sodium_up](https://user-images.githubusercontent.com/2998257/148674092-7bf0acf6-96dd-4c1c-8374-3d0bd6c2e6d1.png)
Down:
![sodium_down](https://user-images.githubusercontent.com/2998257/148674091-ab88fdc4-a520-47da-bc34-a3141d1d1847.png)
North:
![sodium_north](https://user-images.githubusercontent.com/2998257/148674094-fe1de11e-0f2d-494d-a433-b3034e1b682e.png)
East:
![sodium_east](https://user-images.githubusercontent.com/2998257/148674093-5412f2d8-d008-47ec-9a0e-bded19b221ef.png)
South:
![sodium_south](https://user-images.githubusercontent.com/2998257/148674096-d8b4228f-b0ef-4053-998e-d339293ea97c.png)
West:
![sodium_west](https://user-images.githubusercontent.com/2998257/148674095-a8d70a87-a076-4e1c-be6a-f2698d2eebe3.png)

And here is the same setup in vanilla 1.18.1:
Up:
![vanilla_up](https://user-images.githubusercontent.com/2998257/148674222-126d900e-6686-40c0-b61d-3000e99fd8e5.png)
Down:
![vanilla_down](https://user-images.githubusercontent.com/2998257/148674223-6700f82b-d7c7-4dbc-9055-df7600085d82.png)
North:
![vanilla_north](https://user-images.githubusercontent.com/2998257/148674216-05301368-a993-41f9-8bed-f09987174cd1.png)
East:
![vanilla_east](https://user-images.githubusercontent.com/2998257/148674220-4be2d21a-7e60-4ef9-9b4a-76d06014cace.png)
South:
![vanilla_south](https://user-images.githubusercontent.com/2998257/148674219-080a90d2-61d5-472b-93c5-9e46c3a31055.png)
West:
![vanilla_west](https://user-images.githubusercontent.com/2998257/148674218-2e700c2a-074c-4cd9-b125-39220942077a.png)

The in-game time was noon for all screenshots.

**Comment by Zeklandia** [comment]
Issue #38 seems similar, but I didn't see this specific problem mentioned in the discussions about it.

**Comment by Pectacular** [comment]
If you think this issue is similar to #38, shouldn't you mention all of this in that issue?

**Comment by Zeklandia** [comment]
I did tag the issue so that this one would get listed there. Since it's just a hunch on my part, I wanted to wait for confirmation from someone who understands how the mod works and the issue at hand.

**Comment by LucilleTea** [comment]
Issue #38 is about potentially any case where you see a translucent block through another translucent block (influenced by direction and chunk boundaries), so including this case. This is a very dramatic showcase and I appreciate your work documenting it, more examples aren't necessary from a developer's perspective though. The solution is being worked on in PR #963.
