### ISSUE TITLE
Crash when starting world

### ISSUE THREAD

**Issue by Bloofersss** [jellysquid3/Sodium#1120]
### Version information

Mc 1.18.1

### Reproduction Steps

Crash when starting world

### Crash Report file

---- Minecraft Crash Report ----
// My bad.

Time: 1/10/22, 5:58 AM
Description: Unexpected error

java.lang.RuntimeException: Shader compilation failed, see log for details
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.17)
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:47)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:73)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:220)
	at net.minecraft.client.render.WorldRenderer.renderLayer(WorldRenderer:7464)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1259)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1031)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:811)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:47)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:73)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:220)
	at net.minecraft.class_761.method_3251(class_761.java:7464)
	at net.minecraft.class_761.method_22710(class_761.java:1259)
	at net.minecraft.class_757.method_3188(class_757.java:1031)

-- Affected level --
Details:
	All players: 1 total; [class_746['IgItsmeRyan'/1, l='ClientLevel', x=-9.50, y=-60.00, z=6.32]]
	Chunk stats: 16384, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 826 game time, 826 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, assets-v0.zip, Better_grass_1.18.zip, Broken_Tools_V2_1.18.zip, Default-Dark-Mode-1.18-(v1.3.1).zip, Hunger+Preview.zip, Invisible-Item-Frame-Pack (1).zip, Item+Physics+for+1.18+(v1.3) (1).zip, Shield+Corrections+[Colored] (1).zip, Water+Improved.zip, Fabric Mods, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Linux (aarch64) version Android-10
	Java Version: 17-internal, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 325190944 bytes (310 MiB) / 796917760 bytes (760 MiB) up to 796917760 bytes (760 MiB)
	CPUs: 8
	Processor Vendor: 0x51
	Processor Name: AArch64 Processor rev 2 (aarch64)
	Identifier: 0x51 Family 8 Model 0x800 Stepping r0xap4
	Microarchitecture: unknown
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 1
	Number of logical CPUs: 8
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 4110.23
	Virtual memory used (MB): 4624.12
	Swap memory total (MB): 2252.00
	Swap memory used (MB): 1140.55
	JVM Flags: 2 total; -Xms760M -Xmx760M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4
		alternatecurrent: Alternate Current 1.1.0
		architectury: Architectury 3.2.60
		autoconfig1u: Auto Config v1 Updated 3.3.1
		betterfpsdist: Better FPS distance Mod 1.18-1.3
		chunky: Chunky 1.2.153
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.0.42
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		continuity: Continuity 1.0.3+1.18
		crowdin-translate: CrowdinTranslate 1.4+1.18
		cullleaves: Cull Leaves 2.3.2
		dark-loading-screen: Dark Loading Screen 1.6.11
		dynview: Dynamic View Mod 1.18-1.5
		enchantment_lore: Enchantment Lore 1.2.3+MC1.18-1.18.1
		enhancedblockentities: Enhanced Block Entities 0.5+1.18
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.44.0+1.18
		fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8
		fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8
		fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8
		fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8
		fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8
		fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8
		fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8
		fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8
		fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8
		fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8
		fabricloader: Fabric Loader 0.12.12
		farsight: Farsight Mod 1.18-1.5
		fastfurnace: FastFurnace 1.18-4
		ferritecore: FerriteCore 4.0.0
		fpsdisplay: FPS-Display 1.4.2+1.18
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.1.6
		lambdynlights: LambDynamicLights 2.1.0+1.17
		lazydfu: LazyDFU 0.1.2
		libzoomer: LibZoomer 0.3.0+1.17.1
		lithium: Lithium 0.7.6
		midnightlib: MidnightLib 0.2.9
		minecraft: Minecraft 1.18.1
		minecraftcapes: MinecraftCapes Mod 12.0.2
		modmenu: Mod Menu 3.0.1
		mostructures: Mo' Structures 1.3.0-pre1+1.18
		no_fog: No Fog 1.1.0+1.18
		notenoughcrashes: Not Enough Crashes 4.1.3+1.18.1
		okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_joml_joml: joml 1.10.2
		org_quiltmc_quilt-json5: quilt-json5 1.0.0
		perspectivemod: Perspective Mod Redux 0.0.5_01
		phosphor: Phosphor 0.7.2
		pride: Pride Lib 1.1.0+1.17
		replaymod: Replay Mod 1.18.1-2.6.3
		servercore-fabric: ServerCore-Fabric 1.2.6-1.18.1
		simple_utilities: Simple HUD Utilities 2.3.0
		smoothboot: Smooth Boot 1.18-1.7.0
		sodium: Sodium 0.4.0-alpha5+build.9
		spruceui: SpruceUI 3.3.0+1.17
		xaerobetterpvp: Better PVP Mod 21.22.6
	Launched Version: 1.18.1
	Backend library: LWJGL version 3.2.3 SNAPSHOT
	Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
	Window size: 1584x756
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, file/assets-v0.zip (incompatible), file/Better_grass_1.18.zip, file/Broken_Tools_V2_1.18.zip, file/Default-Dark-Mode-1.18-(v1.3.1).zip, file/Hunger+Preview.zip, file/Invisible-Item-Frame-Pack (1).zip, file/Item+Physics+for+1.18+(v1.3) (1).zip, file/Shield+Corrections+[Colored] (1).zip, file/Water+Improved.zip
	Current Language: English (US)
	CPU: 8x AArch64 Processor rev 2 (aarch64)
	Server Running: true
	Player Count: 1 / 8; [class_3222['IgItsmeRyan'/1, l='ServerLevel[Test]', x=-9.50, y=-60.00, z=6.32]]
	Data Packs: vanilla, Fabric Mods
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Sodium (sodium)

**Comment by NotAHero04** [comment]
There is one thing that you should notice:
> Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb
>
PojavLauncher (or whatever you're using to run Minecraft on mobile) uses this library, but it's so incapable.

**Comment by ghost** [comment]
> ### Version information
> Mc 1.18.1
> 
> ### Reproduction Steps
> Crash when starting world
> 
> ### Crash Report file
> ---- Minecraft Crash Report ---- // My bad.
> 
> Time: 1/10/22, 5:58 AM Description: Unexpected error
> 
> java.lang.RuntimeException: Shader compilation failed, see log for details at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.17) at me.jellysquid.mods.sodium.client.gl.shader.GlShader.(GlShader.java:34) at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22) at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:47) at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38) at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72) at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:73) at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289) at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:220) at net.minecraft.client.render.WorldRenderer.renderLayer(WorldRenderer:7464) at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1259) at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1031) at net.minecraft.client.render.GameRenderer.render(GameRenderer:811) at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117) at net.minecraft.client.MinecraftClient.run(MinecraftClient:733) at net.minecraft.client.main.Main.main(Main:238) at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:568) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> ## A detailed walkthrough of the error, its code path and all known details is as follows:
> -- Head -- Thread: Render thread Stacktrace: at me.jellysquid.mods.sodium.client.gl.shader.GlShader.(GlShader.java:34) at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:22) at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:47) at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38) at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72) at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:73) at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289) at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:220) at net.minecraft.class_761.method_3251(class_761.java:7464) at net.minecraft.class_761.method_22710(class_761.java:1259) at net.minecraft.class_757.method_3188(class_757.java:1031)
> 
> -- Affected level -- Details: All players: 1 total; [class_746['IgItsmeRyan'/1, l='ClientLevel', x=-9.50, y=-60.00, z=6.32]] Chunk stats: 16384, 0 Level dimension: minecraft:overworld Level spawn location: World: (0,-60,0), Section: (at 0,4,0 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) Level time: 826 game time, 826 day time Server brand: fabric Server type: Integrated singleplayer server Stacktrace: at net.minecraft.class_638.method_8538(class_638.java:408) at net.minecraft.class_310.method_1587(class_310.java:2402) at net.minecraft.class_310.method_1514(class_310.java:757) at net.minecraft.client.main.Main.main(Main.java:238) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:568) at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> 
> -- Last reload -- Details: Reload number: 1 Reload reason: initial Finished: Yes Packs: Default, assets-v0.zip, Better_grass_1.18.zip, Broken_Tools_V2_1.18.zip, Default-Dark-Mode-1.18-(v1.3.1).zip, Hunger+Preview.zip, Invisible-Item-Frame-Pack (1).zip, Item+Physics+for+1.18+(v1.3) (1).zip, Shield+Corrections+[Colored] (1).zip, Water+Improved.zip, Fabric Mods, replaymod_lang
> 
> -- System Details -- Details: Minecraft Version: 1.18.1 Minecraft Version ID: 1.18.1 Operating System: Linux (aarch64) version Android-10 Java Version: 17-internal, N/A Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 325190944 bytes (310 MiB) / 796917760 bytes (760 MiB) up to 796917760 bytes (760 MiB) CPUs: 8 Processor Vendor: 0x51 Processor Name: AArch64 Processor rev 2 (aarch64) Identifier: 0x51 Family 8 Model 0x800 Stepping r0xap4 Microarchitecture: unknown Frequency (GHz): -0.00 Number of physical packages: 1 Number of physical CPUs: 1 Number of logical CPUs: 8 Graphics card #0 name: unknown Graphics card #0 vendor: unknown Graphics card #0 VRAM (MB): 0.00 Graphics card #0 deviceId: unknown Graphics card #0 versionInfo: unknown Virtual memory max (MB): 4110.23 Virtual memory used (MB): 4624.12 Swap memory total (MB): 2252.00 Swap memory used (MB): 1140.55 JVM Flags: 2 total; -Xms760M -Xmx760M Fabric Mods: advanced_runtime_resource_pack: Runtime Resource Pack 0.5.4 alternatecurrent: Alternate Current 1.1.0 architectury: Architectury 3.2.60 autoconfig1u: Auto Config v1 Updated 3.3.1 betterfpsdist: Better FPS distance Mod 1.18-1.3 chunky: Chunky 1.2.153 cloth-basic-math: cloth-basic-math 0.6.0 cloth-config: Cloth Config v6 6.0.42 com_electronwill_night-config_core: core 3.6.4 com_electronwill_night-config_toml: toml 3.6.4 com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT continuity: Continuity 1.0.3+1.18 crowdin-translate: CrowdinTranslate 1.4+1.18 cullleaves: Cull Leaves 2.3.2 dark-loading-screen: Dark Loading Screen 1.6.11 dynview: Dynamic View Mod 1.18-1.5 enchantment_lore: Enchantment Lore 1.2.3+MC1.18-1.18.1 enhancedblockentities: Enhanced Block Entities 0.5+1.18 entityculling: EntityCulling-Fabric 1.3.3 fabric: Fabric API 0.44.0+1.18 fabric-api-base: Fabric API Base 0.4.1+b4f4f6cdc8 fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.4.0+16d92c47c8 fabric-biome-api-v1: Fabric Biome API (v1) 6.0.1+ded849a9c8 fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.9+3ac43d95c8 fabric-command-api-v1: Fabric Command API (v1) 1.1.6+3ac43d95c8 fabric-commands-v0: Fabric Commands (v0) 0.2.5+b4f4f6cdc8 fabric-containers-v0: Fabric Containers (v0) 0.1.18+d154e2c6c8 fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.5+6f53a73dc8 fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.8+3ac43d95c8 fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.7+43d29571c8 fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.5+6b21378ac8 fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.16+bfa23f17c8 fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.6+b4f4f6cdc8 fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.10+3ac43d95c8 fabric-item-api-v1: Fabric Item API (v1) 1.3.0+691a79b5c8 fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.3+3ac43d95c8 fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.8+c8aba2f3c8 fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.6+b4f4f6cdc8 fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.10+c15ca335c8 fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.8+3ac43d95c8 fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.3+3ac43d95c8 fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.7+b4f4f6cdc8 fabric-models-v0: Fabric Models (v0) 0.3.3+3ac43d95c8 fabric-networking-api-v1: Fabric Networking API (v1) 1.0.18+3ac43d95c8 fabric-networking-v0: Fabric Networking (v0) 0.3.5+b4f4f6cdc8 fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.0+3b82842ec8 fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.8+3ac43d95c8 fabric-particles-v1: Fabric Particles (v1) 0.2.9+526dc1acc8 fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.8.5+3ac43d95c8 fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.9+3ac43d95c8 fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.12+3ac43d95c8 fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.7+b4f4f6cdc8 fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.4+7242e9d7c8 fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.18+3ac43d95c8 fabric-rendering-v0: Fabric Rendering (v0) 1.1.9+b4f4f6cdc8 fabric-rendering-v1: Fabric Rendering (v1) 1.10.3+6b21378ac8 fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.11+3ac43d95c8 fabric-screen-api-v1: Fabric Screen API (v1) 1.0.7+3ac43d95c8 fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.11+3ac43d95c8 fabric-structure-api-v1: Fabric Structure API (v1) 2.0.8+295197a7c8 fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.5+3ac43d95c8 fabric-textures-v0: Fabric Textures (v0) 1.0.9+3ac43d95c8 fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.4+7de09f55c8 fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.5+b4f4f6cdc8 fabricloader: Fabric Loader 0.12.12 farsight: Farsight Mod 1.18-1.5 fastfurnace: FastFurnace 1.18-4 ferritecore: FerriteCore 4.0.0 fpsdisplay: FPS-Display 1.4.2+1.18 java: OpenJDK 64-Bit Server VM 17 krypton: Krypton 0.1.6 lambdynlights: LambDynamicLights 2.1.0+1.17 lazydfu: LazyDFU 0.1.2 libzoomer: LibZoomer 0.3.0+1.17.1 lithium: Lithium 0.7.6 midnightlib: MidnightLib 0.2.9 minecraft: Minecraft 1.18.1 minecraftcapes: MinecraftCapes Mod 12.0.2 modmenu: Mod Menu 3.0.1 mostructures: Mo' Structures 1.3.0-pre1+1.18 no_fog: No Fog 1.1.0+1.18 notenoughcrashes: Not Enough Crashes 4.1.3+1.18.1 okzoomer: Ok Zoomer 5.0.0-beta.3+1.17.1 omega-config: OmegaConfig 1.0.8 org_aperlambda_lambdajcommon: lambdajcommon 1.8.1 org_joml_joml: joml 1.10.2 org_quiltmc_quilt-json5: quilt-json5 1.0.0 perspectivemod: Perspective Mod Redux 0.0.5_01 phosphor: Phosphor 0.7.2 pride: Pride Lib 1.1.0+1.17 replaymod: Replay Mod 1.18.1-2.6.3 servercore-fabric: ServerCore-Fabric 1.2.6-1.18.1 simple_utilities: Simple HUD Utilities 2.3.0 smoothboot: Smooth Boot 1.18-1.7.0 sodium: Sodium 0.4.0-alpha5+build.9 spruceui: SpruceUI 3.3.0+1.17 xaerobetterpvp: Better PVP Mod 21.22.6 Launched Version: 1.18.1 Backend library: LWJGL version 3.2.3 SNAPSHOT Backend API: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.5, ptitSeb Window size: 1584x756 GL Caps: Using framebuffer using OpenGL 3.2 GL debug messages: Using VBOs: Yes Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric' Type: Integrated Server (map_client.txt) Graphics mode: fast Resource Packs: vanilla, file/assets-v0.zip (incompatible), file/Better_grass_1.18.zip, file/Broken_Tools_V2_1.18.zip, file/Default-Dark-Mode-1.18-(v1.3.1).zip, file/Hunger+Preview.zip, file/Invisible-Item-Frame-Pack (1).zip, file/Item+Physics+for+1.18+(v1.3) (1).zip, file/Shield+Corrections+[Colored] (1).zip, file/Water+Improved.zip Current Language: English (US) CPU: 8x AArch64 Processor rev 2 (aarch64) Server Running: true Player Count: 1 / 8; [class_3222['IgItsmeRyan'/1, l='ServerLevel[Test]', x=-9.50, y=-60.00, z=6.32]] Data Packs: vanilla, Fabric Mods Client Crashes Since Restart: 1 Integrated Server Crashes Since Restart: 0 Suspected Mods: Sodium (sodium)
> 
> ### Additional information
> _No response_

Pojavlauncher moment
Close this isue and
Move to https://github.com/PojavLauncherTeam/PojavLauncher/issues

**Comment by khanhduytran0** [comment]
> Pojavlauncher moment Close this isue and Move to https://github.com/PojavLauncherTeam/PojavLauncher/issues

Won’t fix. We all know that gl4es doesn’t support GL 4.5.

**Comment by jellysquid3** [comment]
Upload the full client log file, not just the crash file.

**Comment by mbrucher** [comment]
Looks like I have this as well on my old nVidia card... Any chance of fixing this?

**Comment by Errorbot1122** [comment]
any fix yet? here is my [latestlog.txt](https://github.com/CaffeineMC/sodium-fabric/files/8311763/latestlog.txt)

**Comment by pajicadvance** [comment]
Sodium does not work on Pojav Launcher as it doesn't provide an OpenGL driver.
