### ISSUE TITLE
Change release description to not list Starlight as an incompatibility

### ISSUE THREAD

**Issue by MidGame1** [jellysquid3/Sodium#1122]
**Is your feature request related to a problem? Please describe.**
Release description incorrectly describes an incompatibility with Starlight that has since been fixed on Starlight's side. Notably, starlight didn't issue a new release directly addressing this, however they have updated their jar file to address this because I can load my game with Starlight and Sodium installed.

**Describe the solution you'd like**
Just remove the line mentioning the incompatibility. (#998)

**Describe alternatives you've considered**
Alternatively, add a line that states this has been fixed.

**Additional context**
![image](https://user-images.githubusercontent.com/81443709/148820726-002a8a2e-8b59-4c3f-8cc3-3e94ba317c91.png)
![image](https://user-images.githubusercontent.com/81443709/148820770-52f043bc-9615-4c00-892c-66ee8a88269c.png)

Note: I'm not sure if feature request was the correct place for this, but it wasn't exactly a bug report either

**Comment by jellysquid3** [comment]
Should be updated for the [0.4.0-alpha5](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.18-0.4.0-alpha5) release.
