### ISSUE TITLE
Sodium laggs all of the sound when fps set uncapped

### ISSUE THREAD

**Issue by Meindo** [jellysquid3/Sodium#1123]
### Version information

Sodium mc1.17.1-0.3.3 build 8

### Expected Behavior

The sound should keep playing

### Actual Behavior

When i load a world with sodium installed sometimes it micro stutters, but when it does it laggs all the other audio on my pc. This did not used to be the case but i think i have tried everything to fix it. Temporary fix is setting the fps capped to 260 or so. Its weird that it only happens with 500+ fps but not with 200.

### Reproduction Steps

Load sodium
join a world
set fps to unlimited
enjoy lagg and weird sound

### Java version

openjdk 16

### CPU

Amd Ryzen 5 5600x

### GPU

Amd radeon rx 6600 xt with adrnl 21

### Additional information

MODS:
cloth config 
fabric api
iris starline 
logical zoom
malilib
modmenu
phosphor
sodium 0.3.3

**Comment by ThimothyXYZ123** [comment]
I think your computer got overloaded

**Comment by Meindo** [comment]
How? it never happend before with the exact pc im using. I reverted all the changes that i made like radeon adrenalin settings and it still does it. Also my pc should not get overloaded from minecraft. I dind use shaders.  Maybe it has to do something with frametimes? but im not sure. Thanks for responding tho

**Comment by DioEgizio** [comment]
It's expected behaviour I think, your computer is overloaded

**Comment by DioEgizio** [comment]
Don't use starline, it's discontinued, now iris supports shaderconfig ui in latest beta

**Comment by Meindo** [comment]
i now downloaded iris 1.1.4 and i dont know where i can find the beta. It made it less but still noticable. My pc is strong for minecraft. Also my gpu is only being used ~50% reported by taskmanager when rendering the world. I also tried to play without anything exept sodium and it still happend. I really dont think its my hardware.

**Comment by DioEgizio** [comment]
> i now downloaded iris 1.1.4 and i dont know where i can find the beta. It made it less but still noticable. My pc is strong for minecraft. Also my gpu is only being used ~50% reported by taskmanager when rendering the world. I also tried to play without anything exept sodium and it still happend. I really dont think its my hardware.

The beta is on iris discord

For the performance idk, I can't reproduce

**Comment by ThimothyXYZ123** [comment]
> i now downloaded iris 1.1.4 and i dont know where i can find the beta. It made it less but still noticable. My pc is strong for minecraft. Also my gpu is only being used ~50% reported by taskmanager when rendering the world. I also tried to play without anything exept sodium and it still happend. I really dont think its my hardware.

do you have alot of background applications? , try capping your framerates to 200 or 120 to see if it happens
