### ISSUE TITLE
No water rendering 

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1125]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha5+build.878

### Expected Behavior

water

### Actual Behavior

no water

### Reproduction Steps

1) create world
2) no water
3) despair

### Java version

Java 17.0.1

### CPU

Ryzen R5 3400G

### GPU

Vega 11

### Additional information

![2022-01-12_17 45 30](https://user-images.githubusercontent.com/78235759/149163077-c52e49e2-dbea-4e8e-9595-594d4a1c1e0a.png)
![2022-01-12_17 45 35](https://user-images.githubusercontent.com/78235759/149162764-6d247173-b6b4-4ec9-b0c6-d133d8d0a5fc.png)
![2022-01-12_17 45 43](https://user-images.githubusercontent.com/78235759/149162770-f3fadcbc-702a-4546-b38e-c7aaf0c575bf.png)

**Comment by Cloudperry** [comment]
Its a known issue that fabulous graphics are not yet working on the experimental builds. I ran into this myself and checked discord. There was this message about the 1.18-next experimental builds.

![Screenshot_20220112_213023](https://user-images.githubusercontent.com/25011618/149209118-66eb1380-161c-42d5-92db-1eafccaba8b3.png)

**Comment by MeeniMc** [comment]
This bug was present only in some alpha/pre-releases. It is resolved.
