### ISSUE TITLE
Crash on joining Hypixel (Singleplayer and other servers work fine)

### ISSUE THREAD

**Issue by NotADinosaur** [jellysquid3/Sodium#1126]
### Version information

1.18/next build 878 (latest)

### Expected Behavior

Game to not crash, like it does using 1.18/dev

### Actual Behavior

Joined the server briefly, and then game crashes

### Reproduction Steps

1: load game with sodium 1.18/next
2: join `mc.hypixel.net`

### Java version

17.0.1

### CPU

intel i7-3770

### GPU

NVIDIA GTX 760 

### Additional information

Some lobbies work and some don't. for example, bedwars lobby works and prototype lobby crashes
log:
[crash-2022-01-13_17.40.17-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7867115/crash-2022-01-13_17.40.17-client.txt)

**Comment by NotADinosaur** [comment]
it works up until build 875, 877 is when it starts having crashes

**Comment by jellysquid3** [comment]
1.18.x/next is never going to be published so this issue doesn't need to be open.
