### ISSUE TITLE
vanilla bug with stripe clouds

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1128]
### Version information

1.17.1 0.3.4

### Expected Behavior

Minecraft has had a bug with mixing between clouds for a very long time. There are stripes
Which greatly spoil the appearance of the clouds
The bug is observed with and without sodium
On minecraft versions 1.0 - 1.17 and 1.18
Most likely the bug is related to cloud rendering

### Actual Behavior

streaks between clouds

### Reproduction Steps

1. create or enter a world
2. fly up to the clouds
3. fly into the clouds
4. fly up between two clouds and look at the stripes

### Java version

Java 16

### CPU

Intel core i5 7th gen

### GPU

1050

### Additional information

![2022-01-14_09 53 50](https://user-images.githubusercontent.com/80956290/149465468-522c8ff5-ab4c-487d-aa6d-bbc05231cf3e.png)
![2022-01-14_09 54 02](https://user-images.githubusercontent.com/80956290/149465482-d5fbca35-0926-4956-8feb-1d2c7109fba8.png)
![2022-01-14_09 54 10](https://user-images.githubusercontent.com/80956290/149465485-f1c1c850-d50a-4b5f-b656-5bea529f2e52.png)
![2022-01-14_09 54 28](https://user-images.githubusercontent.com/80956290/149465487-fb74a47e-82ff-47c1-a671-f0a0dd001b53.png)
![2022-01-14_09 54 35](https://user-images.githubusercontent.com/80956290/149465500-413f88f0-6584-449e-8cc0-db853f1e9a29.png)
![2022-01-14_09 54 42](https://user-images.githubusercontent.com/80956290/149465502-353828aa-5f38-4d9d-9777-e9c923c82115.png)
![2022-01-14_09 54 00](https://user-images.githubusercontent.com/80956290/149465508-ba26c8fe-4d51-4a33-961f-22cdbc6d038d.png)
![2022-01-14_09 54 04](https://user-images.githubusercontent.com/80956290/149465513-0cc2cf2b-bce5-4ab7-9c40-541fa200662c.png)
![2022-01-14_09 54 14](https://user-images.githubusercontent.com/80956290/149465515-2e4b97ae-3319-48b1-86f2-c79c4e889269.png)
![2022-01-14_09 54 33](https://user-images.githubusercontent.com/80956290/149465516-014aa874-1ba9-40ba-b476-15fc9e4381f2.png)
![2022-01-14_09 54 38](https://user-images.githubusercontent.com/80956290/149465520-87e1774b-4437-418b-a28b-434ab0415765.png)
![2022-01-14_09 55 08](https://user-images.githubusercontent.com/80956290/149465521-bf296e3e-14dc-432b-a0c4-b98d9e1b0422.png)

**Comment by BigClarky** [comment]
I feel like this has worsened

**Comment by MeeniMc** [comment]
The new cloud renderer has fixed that issue.
