### ISSUE TITLE
Please make a forge version + make 1.8-1.15 fabric mod also so that its better for potato users

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1129]

**Comment by DioEgizio** [comment]
No. This won't happen

**Comment by DioEgizio** [comment]
Sodium is thinked for modern version of Minecraft, also jellysquid doesn't develop for forge because the core members of forge treated her badly. See the [faq](http://caffeinemc.net/faq)

**Comment by LambdAurora** [comment]
[Maintaining a mod for multiple loaders, while maintaining high standards, and not having a lot of time is very difficult. Please read the FAQ for more information on the why.](https://github.com/CaffeineMC/caffeine-meta/wiki/FAQ#where-are-the-forge-versions-of-your-mods)

Pre-1.15 engine is so widely different that you basically would need a rewrite from scratch of this mod, which means it's not worth it.
