### ISSUE TITLE
Scroll to change sliders

### ISSUE THREAD

**Issue by luximus-hunter** [jellysquid3/Sodium#113]
**Is your feature request related to a problem? Please describe.**
It's not a problem, more a convenience.

**Describe the solution you'd like**
The ability to use my scroll wheel to change the value of sliders.

**Describe alternatives you've considered**
x

**Additional context**
x

**Comment by FlashyReese** [comment]
I'm looking on how to implement this now. I'm running into an issue where the widget itself isn't registering mouse scrolled.
