### ISSUE TITLE
This Keeps happening for me when I try to run it I dont know if its the optifine or not I removed all the other mods AND it still doesn't work

### ISSUE THREAD

**Issue by TypicalTyson** [jellysquid3/Sodium#1130]
### Version information

mc1.18.1-0.4.0-alpha6

### Reproduction Steps

I removed all other mods sodium STILL doesn't work

### Crash Report file

net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.0-alpha6+build.14 (C:\Users\omkid\AppData\Roaming\.minecraft\mods\sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar) with any version that is compatible with:
		 - optifabric 1.12.10
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.4.0-alpha6+build.14 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
		 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\omkid\AppData\Roaming\.minecraft\mods\optifabric-1.12.10.jar
Inactive mods:
	 - mod 'Sodium' (sodium) 0.4.0-alpha6+build.14, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.4+7242e9d7c8, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
	 - mod 'joml' (org_joml_joml) 1.10.2, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.0-alpha6+build.14 (C:\Users\omkid\AppData\Roaming\.minecraft\mods\sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar) with any version that is compatible with:
		 - optifabric 1.12.10
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.4.0-alpha6+build.14 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.12.10!
		 - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\omkid\AppData\Roaming\.minecraft\mods\optifabric-1.12.10.jar
Inactive mods:
	 - mod 'Sodium' (sodium) 0.4.0-alpha6+build.14, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cdc8, reason: newer version active
	 - mod 'Fabric Rendering Data Attachment (v1)' (fabric-rendering-data-attachment-v1) 0.3.4+7242e9d7c8, reason: newer version active
	 - mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d95c8, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
	 - mod 'joml' (org_joml_joml) 1.10.2, reason: inactive parent mod (nested jar)
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more

### Additional information

Please help I really want to run this shader

**Comment by jellysquid3** [comment]
>  - Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\omkid\AppData\Roaming.minecraft\mods\optifabric-1.12.10.jar

OptiFine does not work when Sodium is installed. You can use Iris to use OptiFine shaders with Sodium.

**Comment by TypicalTyson** [comment]
> > * Mod 'OptiFabric' (optifabric) 1.12.10 is being loaded from C:\Users\omkid\AppData\Roaming.minecraft\mods\optifabric-1.12.10.jar
> 
> OptiFine does not work when Sodium is installed. You can use Iris to use OptiFine shaders with Sodium.

Thank you so much
