### ISSUE TITLE
Significant Lag (much worse than Vanilla) when near large bamboo farm

### ISSUE THREAD

**Issue by JavaMatrix** [jellysquid3/Sodium#1131]
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9.jar

### Expected Behavior

FPS of 30+. Vanilla runs the area with little to no lag. Optifine runs the area with improved FPS.

### Actual Behavior

FPS drops significantly, especially when bamboo is on screen or when in a chunk where bamboo is. FPS is also highly inconsistent. FPS improves drastically when checking "Always Defer Chunk Updates", but visual lag is significant.

### Reproduction Steps

1. Create a large area of bamboo (100x100 in my case)
2. Uncheck "Always Defer Chunk Updates"
3. FPS Drops significantly

### Java version

Java 17.0.1 64bit

### CPU

12x Intel(R) Core(TM) i7-8700K CPU @3.70 GHz

### GPU

GeForce GTX 1080 Ti/PCIe/SSE2 (3.20 NVIDIA 457.51)

### Additional information

Modlist:
 - Command Macros
 - Continuity
 - EnhancedSearchability
 - Indium
 - Iris
 - Item Scroller
 - Litematica
 - Logical Zoom
 - MaLiLib
 - MiniHUD
 - Mod Menu
 - Settingscommands
 - Sodium
 - Tweakeroo

Same modlist with Optifine/Optifabric instead of Lithium/Indium/Iris/Continuity shows improved FPS in the same area.

The drop is a lot less noticeable in a flat world. I'm having difficulty reproducing the extent of lag I experienced, but it is definitely noticeable in a new non-flat world. I'm happy to share the world file but it's huge. I can also take a video if needed.

I've attached a [crash log](https://1drv.ms/t/s!AjqBgKgMnkdJivt_0E9v8egk8zvmbw?e=XVxuwp) from my world with the bug happening (generated using F3+C) and the [Sodium config](https://1drv.ms/u/s!AjqBgKgMnkdJivwAQh5b8ElyIf7h7w?e=3CE8CY), in case that happens to help.

**Comment by DioEgizio** [comment]
Update sodium

**Comment by JavaMatrix** [comment]
Bug remains unchanged with sodium alpha 6.

**Comment by Vextrove** [comment]
Side note: The Fast Bamboo mod might be of use to you

**Comment by Timolino456** [comment]
> Side note: The Fast Bamboo mod might be of use to you

Since that mod seems to be only available for 1.14... if Sodium doesn't try optimizing Bamboo in any way already, maybe just copying what the Fast Bamboo mod does and adding it to Sodium could help. Although the way I know Jelly she could probably come up with something better.

**Comment by Vextrove** [comment]
> Since that mod seems to be only available for 1.14

It works in 1.14 and up, not just specifically 1.14.

**Comment by jellysquid3** [comment]
I can't reproduce this issue with Sodium 0.5, and we don't have the exact test case which caused this problem for you. We've made some changes since that _could_ have fixed a bug which is similar to this, however. If the problem still occurs with the latest version, then please ask for this issue to be re-opened, and provide a world file so we can reproduce it.
