### ISSUE TITLE
Water colouring broken

### ISSUE THREAD

**Issue by OmgDani** [jellysquid3/Sodium#1132]
### Version information

mc1.18.1-0.4.0-alpha6+build.14

### Expected Behavior

Water colour stays the same colour in the same biome and blends nicely into other biomes
![2022-01-15_00 10 23](https://user-images.githubusercontent.com/25137186/149600592-0398df96-a754-423b-8350-0b0a071fc472.png)
![2022-01-15_00 06 13](https://user-images.githubusercontent.com/25137186/149600612-2370fbd1-875f-41e0-87df-0fbcad2db467.png)

### Actual Behavior

Water colour is patchy with 0 biome blend and noticable patches of blended water withing same biome when using biome blend
![2022-01-15_00 07 16](https://user-images.githubusercontent.com/25137186/149600631-e0d92dfb-6386-4b83-a1a6-499fe49179c8.png)

### Reproduction Steps

Look at body of water in nonstandard water colour biome

### Java version

Java 17.0.1

### CPU

Ryzen 5 3600

### GPU

AMD Radeon RX 5700 XT

**Comment by Blitszy** [comment]
doesn't happen to me. Possibly your biome blend is turned down to 0

**Comment by OmgDani** [comment]
Yes biome blend is set to 0 to show what's happening with biome blend turned up it still happens but becomes diffucult to see
![huge_2022-01-14_23 47 22](https://user-images.githubusercontent.com/25137186/149673120-4af156aa-7108-4df4-8468-c6673f81d17e.png)
![huge_2022-01-14_23 48 20](https://user-images.githubusercontent.com/25137186/149673127-a9026a09-4fc2-4672-9bfa-1b05869775df.png)

**Comment by OmgDani** [comment]
Fixed with release 0.4.1
