### ISSUE TITLE
Cannot see below water

### ISSUE THREAD

**Issue by ComputerJock** [jellysquid3/Sodium#1133]
I finally got around to updating Minecraft from 1.16.5 to 1.18.1. Now with sodium the surface of water is not transparent. Disabling sodium restores the ability to see below the surface of water. If I swim in the water I can see but anywhere above the surface of the water I cannot see the bottom or any underwater structures.

I see that there are a lot of issues related to transparency so you probably already know about it. 

FYI, here is the list of mods I'm using:
  beenfo-1.18.1-fabric0.45.0-1.3.3.jar
  cloth-config-6.1.48-fabric (1.18).jar
  EntityCulling-Fabric-1.3.3 (1.18).jar
  fabric-api-0.45.2+1.18.jar
  fabric-carpet-1.18-1.4.56+v211130.jar
  litematica-fabric-1.18.0-0.9.1.jar
  lithium-fabric-mc1.18.1-0.7.7.jar
  malilib-fabric-1.18.0-0.10.0-dev.26.jar
  minihud-fabric-1.18.0-0.19.0-dev.20211204.230657.jar
  modmenu-3.0.1 (1.18).jar
  NoFog-1.18b1-Fabric.jar
  phosphor-fabric-mc1.18.x-0.8.1.jar
  sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar
  voxelmap-1.18.1-1.10.18.jar
  WI-Zoom-1.3-MC1.18.1.jar
  worldedit-mod-7.2.8 (1.18).jar
  wthit-fabric-4.4.1 (1.18).jar

BTW, config/sodium-mixins.properties states that the description of all options can be found at https://github.com/jellysquid3/sodium-fabric/wiki/Configuration-File however there is no such page that I can find.

**Comment by Endstarky** [comment]
Thats how it work, u might need sodium extra to disable fog  so u can see structutres more clearly from above the surface,

and provide screenshots if possible.

Thank You!

**Comment by LucilleTea** [comment]
This can often be caused by a resource pack, if you have any can you test without them?

**Comment by ComputerJock** [comment]
It was a resource pack: Wavy Water from Vanilla Tweaks. In addition I noticed that the Wavy Leaves resource pack no longer works -- the leaf blocks are static and do not move.

**Comment by Endstarky** [comment]
> It was a resource pack: Wavy Water from Vanilla Tweaks. In addition I noticed that the Wavy Leaves resource pack no longer works -- the leaf blocks are static and do not move.

Actually most of the shader packs of vanilla tweaks don't work with sodium.

**Comment by ComputerJock** [comment]
Is there a list of those resource packs that do not work?

I do not remember exactly but I probably came across Sodium because of a comment by Xisumavoid that Hermitcraft was using Lithium to improve performance on their server. Considering that others might also be using Lithium/Phosphor/Sodium due to the Hermitcraft reference perhaps it would be useful to point out the incompatibilities.

Alternatively, such a list could be provided to the Vanilla Tweaks folks since they already warn about a few incompatibilities among their resource packs.

Thank you for the hint about the resource packs -- my issue is resolved.

**Comment by Endstarky** [comment]
> Is there a list of those resource packs that do not work?
> 
> I do not remember exactly but I probably came across Sodium because of a comment by Xisumavoid that Hermitcraft was using Lithium to improve performance on their server. Considering that others might also be using Lithium/Phosphor/Sodium due to the Hermitcraft reference perhaps it would be useful to point out the incompatibilities.
> 
> Alternatively, such a list could be provided to the Vanilla Tweaks folks since they already warn about a few incompatibilities among their resource packs.
> 
> Thank you for the hint about the resource packs -- my issue is resolved.

Any kind of pack which modifies the shader function ingame is not compatible.
And yes lithium is just for memory and other hardware resource performance mod . 
Phosphor or Hydrogen also wouldnt be much of a problem but sodium is client sided and just for better rendering and with little video memory tweaks.

**Comment by MeeniMc** [comment]
Should rename issue 'incompatible with VT wavy water'. Not sure if there are plans to improve compatibility.

**Comment by jellysquid3** [comment]
There are no plans to fix this. Core shaders are not and never will be supported.
