### ISSUE TITLE
Game Crashed In Build #823 and Later but Build #816 doesn't(Seems mixin problem)

### ISSUE THREAD

**Issue by NewbieXvwu** [jellysquid3/Sodium#1135]
### Version information

mc1.18.1-rc1-0.4.0-alpha5+build.823 or later

### Reproduction Steps

When I'm using Sodium [build #823](https://github.com/CaffeineMC/sodium-fabric/pull/1050) or later builds,game crashed when it's starting.
However, the game can still run normally with build [#818](https://github.com/CaffeineMC/sodium-fabric/actions/runs/1565477041).
I used other mods at the same time.You can find them in my "latest.log".
Don't be surprised if my words don't conform to the grammatical norms. I am not a native speaker of English.Sorry.

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/7876273/latest.log)
Game seems doesn't spawn a crash report in "crash-reports" folder.Maybe it's because game crashed when it's still starting.

### Additional information

I discussed this problem with others. It seems that the injection of mixin has caused this problem.

**Comment by DioEgizio** [comment]
problem: architectury.mixins.json:client.MixinScreen target net.minecraft.class_437 was loaded too early


Not sodium related

**Comment by NewbieXvwu** [comment]
But if I don't use Sodium build # 823 or later,it doesn't happen
If I use Sodium build # 816,it doesn't happen too
It's a compatibility problem

**Comment by MeeniMc** [comment]
Compatibility with other mods in dev builds is never guaranteed. This is invalid.
