### ISSUE TITLE
Fire doesn't render correctly

### ISSUE THREAD

**Issue by PentaSteve** [jellysquid3/Sodium#1140]
### Version information

mc1.18.1-0.4.0-alpha5+rev.6390562 (built from latest code on github as of creating this issue)

### Expected Behavior

When I am on fire, I should see fire

### Actual Behavior

When I set myself on fire, I see this on my screen.
![2022-01-16_19 29 16](https://user-images.githubusercontent.com/53976730/149703968-d804cd35-cb7c-4f0a-8893-07e05a945751.png)

### Reproduction Steps

1. Set yourself on fire

### Java version

Java 17

### CPU

Intel Core i5-9400f

### GPU

Nvidia GTX 1070

### Additional information

Running on Arch Linux using Nvidia driver version 495.46-6

**Comment by jellysquid3** [comment]
> mc1.18.1-0.4.0-alpha5+rev.6390562 (built from latest code on github as of creating this issue)

No, it's not. Latest commit is e8b0190 from 1.18.x/next, and this bug was fixed weeks ago.

**Comment by PentaSteve** [comment]
hmm I thought I was using the latest version, apparently not
