### ISSUE TITLE
"Iris failed to load"

### ISSUE THREAD

**Issue by SansSkele76** [jellysquid3/Sodium#1143]
![2022-01-17](https://user-images.githubusercontent.com/97916398/149832522-9bee8914-4511-4719-9aae-259a79d8e312.png)
For some reason, today I started to get the above message when I try to play Minecraft. I have updated both Iris and Sodium to their most recent version and I don't know what else to do. I am using the beta version of Iris from the Discord server and have removed the other. Can someone please help me to resolve this issue?

**Comment by Pectacular** [comment]
You should put this in the iris issue tracker not in the sodium one

**Comment by DioEgizio** [comment]
Check if you're using correct sodium version

**Comment by jellysquid3** [comment]
We don't provide support for Iris, as it isn't our mod. Most likely you just aren't using the correct versions of Sodium and Iris together... make sure you read the download pages. If you still can't figure it out, you can try contacting the support team of Iris.

**Comment by KingCreeperz** [comment]
First of all. You need sodium alpha6. and if that doesn't work. Lead the sodium or iris  people to work. I made two issues for iris and sodium because idk if what is what's problem of my game
