### ISSUE TITLE
Random splotches of regular water color in non regular ocean biomes

### ISSUE THREAD

**Issue by S0urceDA** [jellysquid3/Sodium#1147]
### Version information

mc1.18.1-0.4.0-alpha6+build.14

### Expected Behavior

Smooth ocean color with no random splotches of the regular ocean color.

### Actual Behavior

The ocean is covered with random splotches of regular ocean color.

### Reproduction Steps

1. go into settings and set biome blend to none (this makes the bug much more apparent)
2. /locatebiome warm_ocean
3. observe the random splotches of the regular ocean color in the warm ocean biome.

### Java version

17.0.1

### CPU

5800x

### GPU

1080

### Additional information

The biome name is still warm_ocean even when inside one of these "splotches", As a result this bug is visual only, removing sodium completely solves the problem. Probably introduced by [c1f71f7](https://github.com/CaffeineMC/sodium-fabric/commit/c1f71f72054f2d4826b3236c8bf8c9aa41459454)
![eee](https://user-images.githubusercontent.com/61162198/149866758-90a483db-a4bc-41fd-ba42-97d470f0ce95.PNG)
Not sure if logs help with this but here they are
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/7886004/latest.log)

**Comment by PlanetSun3** [comment]
Looks like the issue is already known, and is fixed by https://github.com/CaffeineMC/sodium-fabric/commit/844784fa80a9c7d8b207d43325f9c0853bd3f920.
Closing for now as that simple change just needs to be merged into 1.18.x/dev and Jelly is already aware of it.

**Comment by S0urceDA** [comment]
Looks like the issue is already known, and is fixed by https://github.com/CaffeineMC/sodium-fabric/commit/844784fa80a9c7d8b207d43325f9c0853bd3f920.
Closing for now as that simple change just needs to be merged into 1.18.x/dev and Jelly is already aware of it.

**Comment by LucilleTea** [comment]
reopening this since the fix is not yet released, and this issue describes the problem and fix well

**Comment by S0urceDA** [comment]
Closing again as the commit has now made it into an official release. Thanks!
