### ISSUE TITLE
Better Snow and Better Grass Options

### ISSUE THREAD

**Issue by HiroWu1** [jellysquid3/Sodium#1153]
In Optifine the Better Snow and Better Grass options exists but in sodium some options like these ones are missing

The main function of them is to make snow appear with grass so that the terrain looks more smoother

**Comment by FlashyReese** [comment]
First of all, https://github.com/CaffeineMC/sodium-fabric/issues/1101#issuecomment-1006851461

Secondly,
You can use [LambdaBetterGrass](https://github.com/LambdAurora/LambdaBetterGrass) but which does require [Indium](https://github.com/comp500/Indium) for the time being.
