### ISSUE TITLE
Commit `74b9a6d` fails to start with `Namespace (named) does not match current runtime namespace (intermediary)`

### ISSUE THREAD

**Issue by 5HT2** [jellysquid3/Sodium#1154]
### Version information

1.18.x/dev- (commit 74b9a6d)

### Reproduction Steps

1. Run game.
2. Observe crash.

### Crash Report file

https://cdn.l1v.in/paste-1643262794.txt

### Additional information

Only using Fabric API and Sodium.

**Comment by magneticflux-** [comment]
Same issue as https://github.com/CaffeineMC/sodium-fabric/issues/1141

**Comment by 5HT2** [comment]
Oh. I dragged the wrong file apparently, oopsies.
