### ISSUE TITLE
instant crash

### ISSUE THREAD

**Issue by Electricurmom** [jellysquid3/Sodium#1155]
### Version information

1.18.1

### Reproduction Steps

when i put the mod in mods folder with fabric API only and nothing else it instantly crash the game when i run it(1.18.1 alpha)

### Crash Report file

dont have

### Additional information

when will this get fixed

**Comment by Kroppeb** [comment]
> ### Crash Report file
> dont have

Without a crash report it is very difficult to know what when wrong, do you have any screenshots? You could also join the discord for better/faster support.

**Comment by jellysquid3** [comment]
> when will this get fixed

When users put in 2 seconds to create a proper bug report. Closing as invalid.
