### ISSUE TITLE
Adjustable Max FPS by 1

### ISSUE THREAD

**Issue by PweSol** [jellysquid3/Sodium#1156]
Currently, we can adjust the max fps only by the step of 5. Having the ability to adjust it by 1 is much more useful. For example, it's great if you want to achieve the optimal G-Sync experience (explanation [here](https://blurbusters.com/gsync/gsync101-input-lag-tests-and-settings/5/) or [here](https://forums.blurbusters.com/viewtopic.php?f=5&t=3073)).

**Comment by zaki-hussain** [comment]
I think if you change line 98 of src/main/java/me/jellysquid/mods/sodium/client/gui/SodiumGameOptionPages.java from `.setControl(option -> new SliderControl(option, 5, 260, 5, ControlValueFormatter.fpsLimit()))` to `.setControl(option -> new SliderControl(option, 5, 260, 1, ControlValueFormatter.fpsLimit()))` the step should become 1. It's just changing the third number to whatever you want the step to be.

**Comment by PweSol** [comment]
It works! Thanks!
_Only had to disable Sodium version check in Iris to make the game launch with self-compiled builds._

**Comment by Dekamir** [comment]
I hope this becomes the default. FreeSync needs approx. 3 FPS lower than the refresh rate in order to work properly.
This would greatly help screen tearing.

**Comment by PweSol** [comment]
<del>Does anyone know how to do this on the latest version? Sodium has been changed quite significantly internally and I can't find anything similar in order to change it.</del>
It's now in src/main/java/net/caffeinemc/sodium/config/user/UserConfigCategories.java

**Comment by MeeniMc** [comment]
The rejected PR contains rationale why this issue is a wontfix.

**Comment by jellysquid3** [comment]
We are not going to change this behavior, since vanilla now enforces that the config values are within their defined ranges.
