### ISSUE TITLE
Sodium / Continuity (biome specific textures not working)

### ISSUE THREAD

**Issue by NordicFox** [jellysquid3/Sodium#1158]
### Version information

Sodium 0.4.0-alpha6+build.14

### Expected Behavior

I'm using Conquest Resource Pack which has myriad of biome specific textures. Depending on biome some textures should differ. 

### Actual Behavior

Unfortunetly biome specific textures are not working after updating Sodium.

### Reproduction Steps

**Current mod versions in use which cause this bug:**
Sodium 0.4.0-alpha6+build.14
Indium 1.0.2-alpha2+mc1.18.1
Iris 1.1.5
Continuity 1.0.3+1.18

### Java version

17.0.1

### CPU

Intel(R) Core(TM) i9-9900K

### GPU

ROX-STRIX-RTX2080TI

### Additional information

**Biome specific textures were working correctly when I used the following set of mod versions:**
Sodium 0.4.0-alpha5+build.9
Indium 1.0.2-alpha1+mc1.18
Iris 1.1.3
Continuity 1.0.3+1.18

**Comment by PweSol** [comment]
Try updating Iris to 1.2.0

**Comment by NordicFox** [comment]
> Try updating Iris to 1.2.0

Unfortunately it did not help. Screenshots below.

![2022-01-31_20 27 40](https://user-images.githubusercontent.com/17980685/151853045-3cbcdd99-ee8c-4851-81c5-ac55dd0bc8e4.png)
![2022-01-31_20 33 42](https://user-images.githubusercontent.com/17980685/151853052-e6262122-eb1d-4813-8bc7-821f0a1264e7.png)

**Comment by PepperCode1** [comment]
Continuity 1.0.3 does not support Sodium alpha 6 due to internal changes. Either update Continuity to 1.1.0 or downgrade Sodium to alpha 5.

**Comment by MeeniMc** [comment]
A resolution has been provided to the user.
