### ISSUE TITLE
Version Incompatibility with Replay Mod- Missing FREX Flawless Frames API

### ISSUE THREAD

**Issue by PixelArtPlays** [jellysquid3/Sodium#1159]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Expected Behavior

I finished setting keyframes and camera positions, creating my video using the replay mod, and normally, after I click the "Render" button and it renders the video and saves it as an mp4 to my computer.

### Actual Behavior

But when I went to render it, the button was greyed out and I got an information box when I hovered over it that said "Rendering is not supported with your Sodium version. It is missing support for the FREX Flawless Frames API. Either update to the latest version or uninstall Sodium before rendering!"

Without Sodium, obviously my game crashes, and without Sodium and Iris together, I wouldn't be able to record my playthroughs with any of my shaders or mods...And I have the most recent version, the alpha 1.18.1 version, so I was wondering if whatever Replay mod requires hasn't been implemented yet in the alpha?

It may have been silly since everything else is updated to 1.18/1.18.1, but I did even try rolling back to the last release version [sodium-fabric-mc1.17.1-0.3.4+build.13] but that also crashed my game, and the crash report advised that I update to the alpha version that I now have currently.

### Reproduction Steps

1. Download Replay mod
2. Load into a single player world while replay mod is recording.
3. Stay for a few seconds.
4. Save the recording.
5.  Go to "Replay Viewer and open that recording.
6. Press T and then, on the _bottom_ timeline, add Two Time Keyframes and Two Position Keyframes (the bare minimum to render) a few seconds apart from each other (navigate by moving the yellow slider).
7. Click on the Floppy Disk to "Save Rendering path"
8. Hover over the "Render" button.
9. You should see the same info box I did.

### Java version

Java 17.0.1

### CPU

Intel Core i7-6700K

### GPU

NVIDIA GeForce GTX 1070

### Additional information

Here's the list of the other mods I'm currently using:

continuity-1.0.3+1.18
fabric-api-0.43.1+1.18
indium-1.0.2-alpha2+mc1.18.1
iris-mc1.18.1-1.2.0-pre
lambdynamiclights-2.1.0+1.17
modmenu-3.0.1
okzoomer-5.0.0-beta.3+1.17.1
replaymod-1.18.1-2.6.3

**Comment by PixelArtPlays** [comment]
<img width="1920" alt="Replay mod Sodium Error" src="https://user-images.githubusercontent.com/98280613/151881985-a8e5cc04-71e6-4682-bce2-879bd5737f15.PNG">

**Comment by efffauw** [comment]
You need to use a forked version of Sodium in the Replay Mod website to use Sodium with Replay Mod before the official Sodium gets supported. 
![Screenshot (52)](https://user-images.githubusercontent.com/93001604/151923537-d6eb5730-7620-43ac-ab30-5a74980855f6.png)

**Comment by PixelArtPlays** [comment]
Alrighty, Thank you very much!

**Comment by efffauw** [comment]
You should probably close this issue as the FREX Render API compatibility has already been discussed in #1105
