### ISSUE TITLE
Shadowy rendering on custom grass block models in resourcepacks

### ISSUE THREAD

**Issue by Sindavar** [jellysquid3/Sodium#1160]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Expected Behavior

Normal lighting in vanilla 
![image](https://user-images.githubusercontent.com/40722515/151912692-4af10c1a-7bba-4b51-925c-a87658d08d65.png)

### Actual Behavior

bugged and shadowy lighting on inner blocks (edges work normally). Extremely dark shadows when block layers are placed against the model.
![image](https://user-images.githubusercontent.com/40722515/151912743-3f0af88f-6ddc-4d25-bb22-fda23c6d14fe.png)
![image](https://user-images.githubusercontent.com/40722515/151912757-dd1d65cd-f9c4-4885-bae3-24a163b4681c.png)
![image](https://user-images.githubusercontent.com/40722515/151913444-130616d3-2313-49de-907f-1ca4123422fd.png)

### Reproduction Steps

Load this resourcepack, you should get the same effect. Only includes custom grass block model.
[Sodium buggy grass.zip](https://github.com/CaffeineMC/sodium-fabric/files/7975933/Sodium.buggy.grass.zip)

### Java version

Java 17.01 64bit

### CPU

12x AMD Ryzen 5 2600 Six-Core Processor

### GPU

NVIDIA GeForce GTX1650

### Additional information

I'm running iris, but the issues still happen without iris loaded.

**Comment by silversquirl** [comment]
May be related to #226

**Comment by MeeniMc** [comment]
Issue still present in 0.4.10

**Comment by dophire** [comment]
Still hasn't been fixed as of September 2023.
![2023-09-25_23 33 45](https://github.com/CaffeineMC/sodium-fabric/assets/38838633/1e9a6343-d646-4e13-a84f-c36aa6bf59c0)
![2023-09-25_21 37 34](https://github.com/CaffeineMC/sodium-fabric/assets/38838633/84521dc6-8037-4664-a31a-32dac1ca0bd5)
![2023-09-26_17 39 01](https://github.com/CaffeineMC/sodium-fabric/assets/38838633/0c2a71b9-973a-4aae-8591-515152ac914b)
![2023-09-26_17 42 54](https://github.com/CaffeineMC/sodium-fabric/assets/38838633/b0f589f5-28cc-422b-a2d5-a6c36cdcf9eb)

**Comment by MeeniMc** [comment]
can't replicate in 0.6b2
