### ISSUE TITLE
The game crashes on the mojang screen in version 1.17.1

### ISSUE THREAD

**Issue by ElRichQ21** [jellysquid3/Sodium#1162]
### Version information

sodium-fabric-mc1.17.1-0.3.4+build.13

### Reproduction Steps

1.install minecraft from scratch
2.install fabric loader 0.12.12, in game version 1.17.1
3.place in the mods folder the element sodium in the version "sodium-fabric-mc1.17.1-0.3.4+build.13"
4.Start the game

### Crash Report file

[tl console.log](https://github.com/CaffeineMC/sodium-fabric/files/7992608/tl.console.log)

### Additional information

After a clean install of the game, still the problem.
Try to put more ram memory, run the game on another computer and the problem continues.
pls hel
![crashrr](https://user-images.githubusercontent.com/98922848/152300783-403723e2-3e63-4659-886f-95239fee78cf.png)
p

**Comment by GalaxyStudios16** [comment]
having the same problem. hope someone gets to answering this

**Comment by GalaxyStudios16** [comment]
try updating your drivers that worked for me. even if it says they don't need updated at least try

**Comment by NotJansel** [comment]
You are using a cracked launcher. These will not be supported in any way.

**Comment by silversquirl** [comment]
If you can reproduce this using a reputable launcher, open a new issue.
