### ISSUE TITLE
Powder snow face culling may be excessive

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#1163]
### Version information

sodium-fabric-mc1.17.1-0.3.4+build.13

### Expected Behavior

Only the outer faces of powder snow would be culled by solid blocks - the inner faces would not be, and would only be able to be culled by other powder snow blocks.

### Actual Behavior

The inner faces of powder snow are still culled against solid block faces, which goes against expected and vanilla behaviour.

### Reproduction Steps

1. Obtain powder snow
2. Place the powder snow such that it contacts a solid block face, and that this solid block face is visible from inside the powder snow
3. Enter the powder snow

### Java version

16.0.2 64-bit

### CPU

4× Intel® Core™ i3-3240 CPU @ 3.40GHz

### GPU

Intel® HD Graphics 2500

### Additional information

This results from the fix to #859, and has advantages and disadvantages; it gets rid of some Z-fighting issues, however this new behaviour differs substantially from vanilla in a way I'm not sure is desirable.
![2022-02-03_11 24 48](https://user-images.githubusercontent.com/52297970/152334848-f61e3a71-f716-4dde-b011-c4f9428a9ed3.png)

One important thing to note is that it ends up exposing the non-tinted snowy grass block top, which should never be visible in normal survival:
![2022-02-03_11 25 17](https://user-images.githubusercontent.com/52297970/152334980-eec570ee-125c-493e-82ee-28ba8c2987d5.png)

**Comment by jellysquid3** [comment]
Resolved with https://github.com/CaffeineMC/sodium-fabric/commit/c937156e37d221216f284639fc8c51b30facf91e.
