### ISSUE TITLE
Foxes use the axelots texture

### ISSUE THREAD

**Issue by Grisu-FTP** [jellysquid3/Sodium#1168]
### Version information

mc1.18.1-0.4.0-alpha6+build.14.jar

### Expected Behavior

Just use the orange texture

### Actual Behavior

Uses the pink axelotl texture and makes them look very weird and broken

### Reproduction Steps

Use a fox egg

### Java version

17.0.1 64 bit

### CPU

AMD Ryzen 2600X six core

### GPU

Nvidia Geforce RTX 2070

**Comment by silversquirl** [comment]
Can you provide a screenshot showing the issue, with Alt+F3 open?

**Comment by MeeniMc** [comment]
Probably invalid, stale
