### ISSUE TITLE
Minecraft apparantly crashed with the latest alpha Sodium build because of Glow Squids

### ISSUE THREAD

**Issue by LOLOXHD** [jellysquid3/Sodium#1169]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Reproduction Steps

I don't really know how to reproduce it.
But what anybody can try is:

1. Create a world
2. Move around the world on ground near a potential spawn area of glow squids and wait for them to spawn
3. See if your game crashes

I hope this helps on fixing the bug/crash.

### Crash Report file

_**[crash-2022-02-06_23.36.18-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8011373/crash-2022-02-06_23.36.18-client.txt)**_

I hope this helps on fixing the bug/crash.

### Additional information

I was playing normally on my fresh Hardcore world. While yes, there are stutters even with Sodium applied. But I think part of my laptop is causing them. Otherwise I just think that it is also 1.18.1, which isn't the most stable version of Minecraft at the moment.

But when the game crashed and showed me this;

**_"The game crashed whilst ticking entity
Error: java.lang.IllegalStateException: getEntry returned null for ID 14(class_1309::field_18073) for entity minecraft:glow_squid!
Exit-Code: -1"_**

I was confused.

**Comment by CookieXD** [comment]
for me it happend by a pig in a superflat world...

**Comment by jellysquid3** [comment]
Stale issue. Doesn't seem to happen anymore in recent versions. If you can still reproduce it in the latest version, then open a new issue.
