### ISSUE TITLE
Vanilla hold item render bugfix

### ISSUE THREAD

**Issue by Oberfail** [jellysquid3/Sodium#117]
**Is your feature request related to a problem? Please describe.**
The exact issue is, that hold Items often have cracks between edges. *[proof](https://prnt.sc/tkrw0a)*
There is a [Bugreport ](https://bugs.mojang.com/browse/MC-1794) at Mojangs bugtracker, but they just blame it onto faulty Nvidia drivers which is not the case. So far I ran into that problem with any video card. Intel, AMD & Nvidia.

**Describe the solution you'd like**
That bug to be fixed, since Mojang clearly does not care.

**Describe alternatives you've considered**
None. I haven't found anything that fixes that bug.

**Additional context**
I have tested it on many different system configurations and the issue is always there, even in very old minecraft versions.

**Comment by ghost** [comment]
You can make your own texture pack to fix this issue.
It's under the last tab called "Fixes":
https://vanillatweaks.net/picker/resource-packs/

**Comment by jellysquid3** [comment]
This is a rather jarring issue and is a result of precision errors in some rather nasty code where Minecraft converts item textures into quads. I'd like to address this in Sodium at some point.

**Comment by jellysquid3** [comment]
https://modrinth.com/mod/modelfix
