### ISSUE TITLE
Background tint flickers in gui

### ISSUE THREAD

**Issue by jonot-cyber** [jellysquid3/Sodium#1171]
### Version information

mc1.18.1-0.4.0-alpha6+build.14

### Expected Behavior

In the background of a gui, there is a tint that stays consistent.

### Actual Behavior

The tint randomly flickers on and off, which is very distracting

### Reproduction Steps

1. Open a chest/furnace/villager trading ui
2. Close
3. Repeat until bug occurs

### Java version

Java 17.0.2

### CPU

4x AMD Ryzen 3 3200G

### GPU

AMD Radeon RX 6600 XT

### Additional information

The bug did not show up when recorded with obs. Since the recording was at 60 fps, It might have to do with the fact that I was getting a higher framerate than that

**Comment by andrejcremoznik** [comment]
I managed to make a recording: https://drive.google.com/file/d/1XpsL3-DrH3gOe_yRI2TdRgsRGLM92qE3/view?usp=sharing
You might want to download and watch it locally as google's compression really botched it up. 

Seems to be AMD GPU/driver related as it happens on both - a Radeon RX 5700 GPU and on a Ryzen 5 4500U APU.

I noticed this the first time back on 1.16.5 when I started using sodium so it's been around for a while.

## Specs:

CPU: Ryzen 5 3600
GPU: Radeon RX 5700

Also happens on mobile Ryzen 5 4500U APU

linux 5.17.1 (bug was present on way older kernels so probably not related)
mesa 22.0.0
java: jre-openjdk 17.0.3

minecraft 1.18.2
```
dynamic-fps-2.1.0.jar
fabric-api-0.47.9+1.18.2.jar
lambdynamiclights-2.1.0+1.17.jar
litematica-fabric-1.18.2-0.11.0.jar
logical_zoom-0.0.14.jar
malilib-fabric-1.18.2-0.12.0.jar
minihud-fabric-1.18.2-0.22.0.jar
modmenu-3.1.0.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
tweakeroo-fabric-1.18.2-0.13.0.jar
```

**Comment by andrejcremoznik** [comment]
This is no longer an issue for me in 1.19+.

**Comment by MeeniMc** [comment]
both reporter confirm issue resolved in recent versions.

**Comment by jonot-cyber** [comment]
I don't have this issue anymore either
