### ISSUE TITLE
launcher wont start with the newest sodium version 1.17.1-0.3.4

### ISSUE THREAD

**Issue by CaptainSlayder** [jellysquid3/Sodium#1172]
### Version information

1.17.1-0.3.4

### Reproduction Steps

open the game

### Crash Report file

exit code 0

**Comment by Pectacular** [comment]
You must provide the latest log

**Comment by jellysquid3** [comment]
Closing as invalid as you haven't tried to fill out the issue template or provide a crash log.

Either upload a crash log and ask for this issue to be re-opened, or open a new issue yourself by filling out the template entirely.
