### ISSUE TITLE
Вылет из мира (игра с другом на локальном сервере)

### ISSUE THREAD

**Issue by GrozaMast** [jellysquid3/Sodium#1173]
### Version information

mc1.18.1-0.4.0-alpha6

### Reproduction Steps

Вылет произошел на локальном сервере. Во время исследования мира я захотел вернуться домой, но при нажатии телепортироваться у меня пошло сохранение мира и выдал следующий краш лог. В чем проблема ?

### Crash Report file

[crash-2022-02-08_20.29.37-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8026227/crash-2022-02-08_20.29.37-client.txt)

**Comment by Nekosha** [comment]
#1016

**Comment by silversquirl** [comment]
Please use English on this bugtracker.

Duplicate of #1016
