### ISSUE TITLE
Sodium Light Error Crash - "Tried to mark light data as ready for chunk but it hasn't been loaded yet"

### ISSUE THREAD

**Issue by serioos** [jellysquid3/Sodium#1177]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Reproduction Steps

I don't know how to reproduce it. I was attacking a cow when I suddenly crashed out of nowhere.
I was playing on a multiplayer server with my friend. She didn't crash.

### Crash Report file

https://pastebin.com/rXnHp44j

**Comment by Kroppeb** [comment]
Do you know if there are any mods/plugins on the server?

**Comment by Speeder323** [comment]
Seems to be the same as/ related to #1016

**Comment by serioos** [comment]
@kroppeb

Yes it is a modded server. The same mods are on it that are in my log with the exception of some of the mods that are client only.

**Comment by silversquirl** [comment]
Duplicate of #1016
