### ISSUE TITLE
link with an exe to install this mod

### ISSUE THREAD

**Issue by Titanxyt2052** [jellysquid3/Sodium#1178]
I would be very happy if there was an .exe installer instead of .jar as many computers with java installed for some reason cannot open .jar files

**Comment by jellysquid3** [comment]
You can't install Sodium by "opening" the JAR file anyways, so I have no idea what this issue is about. If you're referring to the "Fabric Installer", that comes as an EXE too.

**Comment by Titanxyt2052** [comment]
sorry, my mistake
