### ISSUE TITLE
Incompatibility with Better Fps - Render Distance

### ISSUE THREAD

**Issue by PweSol** [jellysquid3/Sodium#1182]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14.jar

### Expected Behavior

With the [Better Fps - Render Distance](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance) mod, the game should be rendering a 3d circular radius, which can also be stretched horizontally via config or video option.

### Actual Behavior

The mod stops working, and the game renders chunks in a 2d circle.

### Reproduction Steps

1. Install Sodium and Better Fps - Render Distance.
2. Enter a world and wait for the chunks to be loaded.
3. Better Fps - Render Distance doesn't do its job.

### Java version

Java 17.0.2

### CPU

AMD Ryzen 9 5950X

### GPU

GeForce RTX 3090

### Additional information

The same issue applies to 1.16 and 1.17. The only difference is the game loading in a square radius because the 2d circle radius was implemented in 1.18.

The author states in the mod's description this:
_"Should work with pretty much all mods, though I did not try all which may due to heavily changing rendering skip the modification done by this mod."_

Could it be Sodium changes or skips what this mod is trying to achieve? Or perhaps Sodium is already doing the same thing?

**Comment by ghost** [comment]
pls fast fix this issues

**Comment by ShibeTemple** [comment]
I believe it fails due to a mixin issue. Additionally, 1.18 implements a form of horizontal render distance, as mentioned in that mod's description.

**Comment by PweSol** [comment]
> I believe it fails due to a mixin issue. Additionally, 1.18 implements a form of horizontal render distance, as mentioned in that mod's description.

The mod still improves performance on 1.18. And even more on 1.16 and 1.17, where Majong hasn't implemented anything similar yet.

**Comment by PweSol** [comment]
Looks like the issue has been resolved on the other mod's end. It has also been split to [Forge](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance) and [Fabric](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance-fabric) versions respectively instead of Forge&Fabric AIO. Unfortunetely, there are no updated 1.16 and 1.17 version for Fabric yet.
