### ISSUE TITLE
"Config not yet available"

### ISSUE THREAD

**Issue by goobyq** [jellysquid3/Sodium#1183]
### Version information

mc1.18.1-0.4.0-alpha6+build.14

### Reproduction Steps

Start instance of the modpack Benchmark II

### Crash Report file

[crash-2022-02-16_21.09.31-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8085775/crash-2022-02-16_21.09.31-client.txt)

### Additional information

The only thing I changed was the Java 17 route on the GDlauncher instance.

**Comment by coderbot16** [comment]
Remove Not Enough Crashes and then see if the problem still occurs, or if the stacktrace changes.

**Comment by goobyq** [comment]
looks like it fixed, time to try and fix the other crash issues lol
[crash-2022-02-16_22.20.35-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8086073/crash-2022-02-16_22.20.35-client.txt)

**Comment by jellysquid3** [comment]
I think this is an issue with Not Enough Crashes doing something too early, but it's hard to say. Most users have reported it goes away with removing NEC.

I'm going to close it as an external issue, but we should probably improve our config loading code at some point.

**Comment by coderbot16** [comment]
Not Enough Crashes stops executing entry points once a single one fails, making it difficult to rely on them actually executing in its presence. So it ends up hiding the original crash when it breaks the initialization sequence of other mods (like Sodium). Entrypoint execution order is inconsistent (or, at best, in alphabetical order). this leads to weird issues such as this, where removing Sodium reveals another crash.
