### ISSUE TITLE
Potential optimisation regarding bamboo rendering

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#1184]
I haven't tried checking to see if the mod has fixed this issue already (wouldn't know where to start), but bamboo allegedly calls for some unnecessary calculations to be done to produce an ambient occlusion-related value which will always return a fixed value under all circumstances. If this issue is still present in modern versions and Sodium doesn't already fix it, having Sodium fix it would be advisable due to it being an optimisation mod.

The following mod fixes this issue for 1.14, and I believe RandomPatches also implements a fix for the same issue:
https://www.curseforge.com/minecraft/mc-mods/fast-bamboo

**Comment by muzikbike** [comment]
It appears #602 may have attempted to fix this issue previously, although ultimately does not appear to have been merged.

**Comment by muzikbike** [comment]
This has been reported under https://bugs.mojang.com/browse/MC-249360

**Comment by IMS212** [comment]
Added in https://github.com/CaffeineMC/sodium-fabric/commit/939bfb52c0fa78dd65aa257334cec6564aceed71.
