### ISSUE TITLE
(crash) IllegalStateException: Tried to mark light data as ready for chunk [1816, 19] but it hasn't been loaded yet

### ISSUE THREAD

**Issue by cootshk** [jellysquid3/Sodium#1186]
### Version information

Sodium 0.4.0-alpha5+build.9

### Reproduction Steps

holding tab while playing quake craft on CubeCraft server (i dont know what happened, game randomly crashed)

### Crash Report file

https://crashy.net/WjYJQrDZB3E2QCus955w

### Additional information

Not Enough Crashes identified sodium as the cause of the crash

**Comment by cardanawandra** [comment]
same issue, can be reproduce using fartherviewdistance spigot server and ferrite core

**Comment by Lolothepro** [comment]
#1016

**Comment by jellysquid3** [comment]
Closing as duplicate of #1016.
