### ISSUE TITLE
Animated textures with interpolation differ to vanilla

### ISSUE THREAD

**Issue by pau101** [jellysquid3/Sodium#1188]
### Version information

mc1.18.1-0.4.0-alpha6

### Expected Behavior

Animated textures with "interpolate" enabled to not mix the alpha channel between frames.

### Actual Behavior

The alpha channel is mixed between frames.

### Reproduction Steps

1. "texture_updates" mixin config enabled
2. Observe "interpolate" animated texture with translucency blending

### Java version

Java 17

### CPU

Intel Core i7-8700

### GPU

NVIDIA GeForce GTX 1070

### Additional information

Reproduction pack with animated apple: [sodium-issue-1188.zip](https://github.com/CaffeineMC/sodium-fabric/files/8102936/sodium-issue-1188.zip)

Without sodium translucency jumps between frames, while with sodium blended.

**Comment by FreezePhoenix** [comment]
I don't see why this would be considered a bug in Sodium. Personally, I'd expect the translucency to get blended, otherwise, you'd have one channel that jumps while the others don't. This is more likely a bug with Minecraft itself.

In fact, there is already a bug report on Mojang's bug tracker for this:

https://bugs.mojang.com/browse/MC-144761

**Comment by gudenau** [comment]
It should be possible to add a tag to the animation metadata to enable the alpha blending behavior. I do think that blending the alpha is the correct way to do this but it's likely possible to do both.

**Comment by jellysquid3** [comment]
It seems this is a bug in vanilla with how it handles the alpha channel, and while Sodium is doing the correct thing, it doesn't match vanilla... so really it's our bug.

I really don't like re-implementing bugs but we should probably fix this, since this changes some resource packs substantially.

**Comment by jellysquid3** [comment]
Butterfingers. Didn't mean to close the issue.

**Comment by TheKodeToad** [comment]
Should this be closed?

**Comment by pau101** [comment]
Yep this is resolved!
