### ISSUE TITLE
Compatibility issue with Continuity and overlays over block with tint index

### ISSUE THREAD

**Issue by xalixilax** [jellysquid3/Sodium#1189]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Expected Behavior

Both overlays should be visible at the same time. 
In this picture, I am using continuity only.
![2022-02-20_11 35 03](https://user-images.githubusercontent.com/2474569/154853663-9d01ebe5-8d26-493c-be75-c87f2c4fad90.png)
![2022-02-20_12 27 10](https://user-images.githubusercontent.com/2474569/154855702-b70e1ecc-ad28-42eb-856e-8ce45d1498c3.png)

.

### Actual Behavior

Only one of the 2 overlays get applied. 
In this picture, I added Sodium and Indium
![2022-02-20_11 33 21](https://user-images.githubusercontent.com/2474569/154853704-46caf353-b7b0-46a6-a050-1dcb464e73dc.png)
![2022-02-20_12 25 59](https://user-images.githubusercontent.com/2474569/154855707-ff671e5e-2b9a-482b-b5bf-3e89593d88da.png)

The overlays that are used are simply shadow so it is not that visible but it's there.
After trying some workaround, I realized that the issue is not double overlays but grass_block overlays that are just not rendered at all.
Same happen overlays on leaves block.

### Reproduction Steps

Simply installing Sodium and Indium break that feature that usually work with Continuity or Optifine.

### Java version

17.0.1

### CPU

i5-8600k

### GPU

GeForce GTX 1070TI

### Additional information

Sodium
Indium 1.0.2-alpha2
Continuity 1.0.3
Fabric Api 0.46.6

All with 1.18.1

The texture pack used is [xali's Enhnaced Vanilla](https://www.curseforge.com/minecraft/texture-packs/xalis-enhanced-vanilla/files) One of my pack. 
Leaves block actually have an invisible layer that is invisible by default and rendered using method=overlay_fixed in some biomes

**Comment by pajicadvance** [comment]
Seems to be working now, tested with:
MC 1.19.4
Sodium 0.4.10
Indium 1.0.15
Continuity 3.0.0-beta.2
Fabric API 0.80.0

![2023-05-10_00 06 02](https://github.com/CaffeineMC/sodium-fabric/assets/32738446/4c0dccdd-cfbf-416c-be0c-5ad9da3ce900)
![2023-05-10_00 10 04](https://github.com/CaffeineMC/sodium-fabric/assets/32738446/f033d6b9-a305-4e5a-984b-2ae1904bb89b)
