### ISSUE TITLE
Borders of bookshelves flicker when using connected texture resource pack

### ISSUE THREAD

**Issue by Yadokingu** [jellysquid3/Sodium#119]
Some (not all) borders of bookshelves flicker when using the [vanilla tweaks](https://vanillatweaks.net/picker/resource-packs/) connected textures pack for bookshelves.

![2020-07-19_22 39 25](https://user-images.githubusercontent.com/11133215/87887020-a8073e80-ca21-11ea-9187-f1bf4543bfbf.png)

**Comment by Siuolplex** [comment]
This is related to one of the toggles. Compact Vertex Rendering. And what it does. And at least in the dev branch as of now, will be broken when turned off as seen in https://github.com/jellysquid3/sodium-fabric/issues/136
The toggle does specifically mention edge use cases will result in Z-fighting (Which is the issue you appear to have.) If your using the stable branch (Which is the version you can download on CurseForge or on the downloads on here.) Then try turning off Compact Vertex Rendering.

**Comment by Yadokingu** [comment]
Yes, turning Compact Vertex Rendering off fixes the z-fighting.

**Comment by jellysquid3** [comment]
Merging into #182.
