### ISSUE TITLE
Tried to mark light data as ready for chunk [x, y] but it hasn't been loaded yet

### ISSUE THREAD

**Issue by MichaelLarces** [jellysquid3/Sodium#1197]
### Version information

mc1.18.1-0.4.0-alpha6+build.14

### Reproduction Steps

1. I was just using /locatebiome and /tp
2. The game crashes (Tried to mark light data as ready for chunk [14, 1] but it hasn't been loaded yet)

### Crash Report file

[crash-2022-02-28_14.21.01-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8155377/crash-2022-02-28_14.21.01-client.txt)

**Comment by Lolothepro** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/1016
