### ISSUE TITLE
crash on right-click

### ISSUE THREAD

**Issue by Cooliosity** [jellysquid3/Sodium#1199]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Reproduction Steps

The first crash (the one that happened at 00.42.51) happened when I right clicked a grown wheat crop to harvest it using the right-click-harvest mod. The second crash happened when I right-clicked my cauldron thingy from dehydration to refill my water canteen. I am not sure how to reproduce this, apart from just playing the game as I've been refilling my water and harvesting my wheat without any issues, apart from these two crashes.

### Crash Report file

[crash-2022-03-01_00.42.51-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8157744/crash-2022-03-01_00.42.51-client.txt)
[crash-2022-03-01_00.58.07-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8157745/crash-2022-03-01_00.58.07-client.txt)

**Comment by piuvas** [comment]
it should be noted (?) that these are notenoughcrashes logs.

**Comment by MeeniMc** [comment]
Issue is invalid,  kitchen sink modpack cause something to crash in completable futures. Not Sodium related.
