### ISSUE TITLE
Inconsistent block entity rendering 

### ISSUE THREAD

**Issue by eatmyvenom** [jellysquid3/Sodium#12]
This is essentially that occasionally block entities (shulker boxes, chests, player heads, etc) will fail to render in the world. The only indication that they exist is their collision, shadows around them, and the box drawn when they are hovered over. In my experience this has only happened consistently in 2 locations. 
1) A tower in a personal server had 3 shulker boxes that would not ever even if replaced. 
2) On hammerSMP nether roof there is a set of shulker boxes that don't render. This is also not specific to my instance as a fellow Hammer member PapiChase#0837 [had it happen](https://cdn.discordapp.com/attachments/653696157931012096/708160354127052861/2020-05-07_20.14.15.png) to him as well.

 Poke#8236 helpfully pointed out this is specifically when a subchunk with no blocks other than block entities is rendered. 

For both me and papichase, sodium was compiled against latest commit. My build was compiled and used in java 14. Papichase's build was compiled and run in java 8. 

I will include more screenshots and info soon.

**Comment by Nifty-Neutron** [comment]
This happened to me,
I was stupid and compiled the mod in java 11 and used fabric with java 8.
After running fabric in java 11(the same one I used to compile the mod) it worked.

**Comment by lenrik1589** [comment]
yeah also had the same issue, but from my observation:
1 it affects certain chunks (tile-entities continue rendering over the chunk border)
2 issue sometimes disappears and then reappears in the same chunk

**Comment by LucilleTea** [comment]
Works properly in latest commit
