### ISSUE TITLE
Emmisive item texture compatibility.

### ISSUE THREAD

**Issue by googlescientificnameforapig** [jellysquid3/Sodium#1200]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by googlescientificnameforapig** [comment]
Sodium is only compatible with emmisive entity texture mods, but not item or block textures.

**Comment by googlescientificnameforapig** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/100143295/156082054-79c492e5-d8ce-430e-83a9-54bf421ac608.png">

**Comment by googlescientificnameforapig** [comment]
using puzzle mod

**Comment by pajicadvance** [comment]
Use Continuity for emissive texture support.
