### ISSUE TITLE
incompatible with optifabric 1.12.10

### ISSUE THREAD

**Issue by GonzoStudioz** [jellysquid3/Sodium#1201]
### Version information

mc1.18.2 with fabric-loader-0.13.3-1.18.1 with optifabric 1.12.10 

### Reproduction Steps

add this mod to your mod section on the fabric mod loader (use latest version)

open Minecraft launcher

play, and the crash report will come.

### Crash Report file

no crash report to copy

**Comment by LucilleTea** [comment]
Sodium is not and can not be compatible with optifabric, you have to choose.
