### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by sungjoon-news** [jellysquid3/Sodium#1202]
this crash happens with no reason

I experience this issue especially when I tp to somewhere

here's my crash report

[crash-2022-03-01_14.07.48-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8163016/crash-2022-03-01_14.07.48-client.txt)

**Comment by Lolothepro** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/1016

**Comment by jellysquid3** [comment]
Closing as duplicate of #1016.
