### ISSUE TITLE
1.18.2 - Game fails to launch (invalid java runtime settings)

### ISSUE THREAD

**Issue by Horonelius** [jellysquid3/Sodium#1203]
### Version information

mc1.18.1-0.4.0-alpha6+build.14

### Reproduction Steps

1. Attempt to start the game.
2. Game crashes and immediately reopens launcher saying the issue may be caused by incorrect java runtime settings.

### Crash Report file

[https://gist.github.com/Horonelius/a405290db58016283f88fc20fab7b12d](url)

### Additional information

I considered this might be a simple incompatibility issue with 1.18.2, but I would then expect to see a mountain of "game broke" issues corresponding with 1.18.2, which I was unable to find.

Same issue occurs with the last 1.17.1 release as well.

**Comment by jellysquid3** [comment]
Yes, you are trying to use a version for mc1.17.1/mc1.18.1 on mc1.18.2. Wait for an updated version.
