### ISSUE TITLE
Crash from Rendering Block Entity

### ISSUE THREAD

**Issue by LunexLunertic** [jellysquid3/Sodium#1204]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

1: Make nether portal
2: fly around the nether (or overworld), go to a chunk which has data to generate a structure that has any block entity with a skeleton skull (requires a structure datapack or structure mod since they do not generate naturally)
3: crash

### Crash Report file

[crash-2022-03-02_18.48.50-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8174615/crash-2022-03-02_18.48.50-client.txt)
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/8174619/latest.log)

### Additional information

Most likely case it is an incompatibility with another rendering mod though I don't know which rendering mod causes this to happen, nonetheless I was unable to reproduce this crash with Sodium alone when I tested this and placing skeleton skulls in the nether, I do know that Repurposed Structures has stuctures such as Piglin Outposts that has these Skeleton Skulls and Wither Skulls placed down and generated. Nonetheless I will see if this only happens when I have only Sodium and a structure datapack or mod (as noted earlier in the sentence) that includes skulls generated within the nether or overworld, and will be able to conclude if it's a problem with another rendering mod.

**Comment by LunexLunertic** [comment]
After testing out Sodium with only the structure mod and its required dependency, there's nothing wrong with them together, so it's definitely another mod causing the incompatibility.

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/8174804/latest.log)

**Comment by tranlong5252** [comment]
I also have the same issue here: 
[crash-2022-03-03_11.23.04-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8174942/crash-2022-03-03_11.23.04-client.txt)

**Comment by jellysquid3** [comment]
This crash isn't coming from Sodium. It seems you have an out-of-date mod that is patching game code. I would advise you remove mods one by one until you find it.

If you can reproduce this specific crash with just Sodium, provide a new crash log and ask for the issue to be re-opened.

**Comment by LunexLunertic** [comment]
I've found the offending mod, it's an incompatibility between 3d skin layers and latest version of Sodium. I will post this promptly on their github page. 

And after testing all mods without skin layers included, it's definitely the offending mod.

Crash with Sodium and 3d skin layers:

[crash-2022-03-03_09.44.22-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8179872/crash-2022-03-03_09.44.22-client.txt)
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/8179875/latest.log)

**Comment by jellysquid3** [comment]
The problem is with the current version of 3D Skin Layers. The mod tries to access some code which has since changed in Minecraft 1.18.2 ([offending line](https://github.com/tr7zw/3d-Skin-Layers/blob/1.17/3dSkinLayers-Shared/src/main/java/dev/tr7zw/skinlayers/mixin/SkullBlockEntityRendererMixin.java#L36)). You will have to wait for the author to update the mod or downgrade to an older version of Minecraft.

**Comment by LunexLunertic** [comment]
Thank you very much for showing what went wrong, I will simply await for the author to update.

**Comment by tr7zw** [comment]
I'll get to 1.18.2 versions tomorrow hopefully, haven't had the time yet to update the mods. At least it looks like forge 1.18.2 came out 17 hours ago, so I can do them at once.
