### ISSUE TITLE
Screenshot resolutions

### ISSUE THREAD

**Issue by ryanccn** [jellysquid3/Sodium#1205]
**Is your feature request related to a problem? Please describe.**
OptiFine provides the feature of increasing the screenshot resolution, e.g. increasing it to `2x`, `4x`, etc. to provide better experience to, for instance, make wallpapers or other stuff.

**Describe the solution you'd like**
An option in the **Video Settings** that has "Screenshot Size"

**Describe alternatives you've considered**
A render resolution option? But that might not be so necessary

**Comment by ryanccn** [comment]
Would this be in the scope of Sodium? Or would be in, say, [sodium-extra](https://modrinth.com/mod/sodium-extra)

**Comment by jellysquid3** [comment]
There is already a mod called [**Fabrishot**](https://www.curseforge.com/minecraft/mc-mods/fabrishot) which has this feature. Sodium is really only meant to be an optimization mod, and if there's other mods which already add this, I don't see reason for us to reinvent the wheel.

**Comment by ryanccn** [comment]
OK, thanks!
