### ISSUE TITLE
Game crashes when opening inventory - 1.18.2

### ISSUE THREAD

**Issue by KB-Q** [jellysquid3/Sodium#1218]
[](https://user-images.githubusercontent.com/59303688/156921101-286b5fd5-023d-4835-a8e4-59786f8f3f0c.png)Game crashes when opening inventory - 1.18.2. I use fabric mods like sodium, lithium, starlight and a few others, everything updated to their latest versions.

Here's the error screen:
![image](https://user-images.githubusercontent.com/59303688/156921856-1172be77-e665-43af-b226-660898d4b884.png)

And here's the crash report:
[crash-2022-03-06_16.41.05-client.txt](https://github.com/FabricMC/fabric/files/8192433/crash-2022-03-06_16.41.05-client.txt)

**Comment by DenaryDev** [comment]
I have the same problem

**Comment by KB-Q** [comment]
I removed okzoomer, and it seems to work now. I can open my inventory and put stuff in it, no problem. I posted the same issue in FabricMC's github page as well, that's how I got this resolution. Here's the thread: https://github.com/FabricMC/fabric/issues/2046

@DenaryDev Do you also have okzoomer installed? If yes remove it and see if it works, and let us know so that we can close the issue.

**Comment by DenaryDev** [comment]
> Do you also have okzoomer installed? 

yes, i have okzoomer installed

> If yes remove it and see if it works

yes, it works without okzoomer

It looks like it's an okzoomer issue.

EnnuiL/OkZoomer#53
