### ISSUE TITLE
Crashes when i add Sodium into the mods folder

### ISSUE THREAD

**Issue by fennecthefox** [jellysquid3/Sodium#1221]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

I tried running sodium with other mods like "flesh2leather", "FabricHomes", "Origins", "Pehkui" and "vanillaexcavators". I play on a server where i need these mods but i need sodium as well because low end pc.

### Crash Report file

[2022-03-10-7.log](https://github.com/CaffeineMC/sodium-fabric/files/8222624/2022-03-10-7.log)

**Comment by fennecthefox** [comment]
P.S another friend of mine can run this perfectly

**Comment by DioEgizio** [comment]
In your log there isn't even sodium...

**Comment by DioEgizio** [comment]
Also if you have an overlay like overwolf disable it, it breaks Minecraft

**Comment by DioEgizio** [comment]
And you can't use sodium 0.4.1 on Minecraft 1.18.1, use [0.4 alpha 6](https://modrinth.com/mod/sodium/version/mc1.18.1-0.4.0-alpha6) there

**Comment by boslire** [comment]
when i open a world, after loading world, it will say saving world and crashes the game. Can u help pls
