### ISSUE TITLE
Minecraft Crashes after "Joining World...." Message

### ISSUE THREAD

**Issue by RuneLune** [jellysquid3/Sodium#1222]
### Version information

mc1.18.1-0.4.0-alpha6+build.14

### Reproduction Steps

1. Install Minecraft, Fabric loader, and Sodium mod with the versions written on top. 
2. Try to join a local world or online server. 

### Crash Report file

[Crash Report](https://github.com/CaffeineMC/sodium-fabric/files/8231927/crash-2022-03-11_12.06.29-client.txt)
[Latest Log](https://github.com/CaffeineMC/sodium-fabric/files/8231936/latest.log)

### Additional information

> Minecraft & Fabric version

fabric-loader-0.13.3-1.18.1
minecraft-1.18.1

> Java Version

jre17-arm64-20210825-release (Java 17)

> Processor

Qualcomm Snapdragon 865+ SM8250-AB Platform
Qualcomm Snapdragon X55 5G Modem

> CPU

ARM Cortex-A77 MP1 3.09 GHz
ARM Cortex-A77 MP3 2.42 GHz
ARM Cortex-A55 MP4 1.8 GHz

> GPU

Qualcomm Adreno 650 670 MHz GPU

**Comment by jellysquid3** [comment]
> 	GL debug messages: id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE in glMapBufferRange(access has undefined bits set)' x 1

We do not support Android and other mobile devices, unless they have a proper driver for OpenGL Core. Compatibility layers which expose OpenGL Core through OpenGL ES will not work.
