### ISSUE TITLE
memory leak while playing render distance 32

### ISSUE THREAD

**Issue by RedLime** [jellysquid3/Sodium#1227]
### Version information

mc1.18.2-0.4.1+build.15

### Expected Behavior

Not cause memory leak

### Actual Behavior

If the playing with a render distance 32, high memory usage occurs within 30 minutes to 1 hour and a lot of lag occurs aka memory leak.

### Reproduction Steps

1. render distance to 32
2. fly with elytra + fireworks
3. keep flying for 30 minutes to 1 hour

### Java version

Java 17

### CPU

AMD Ryzen 5 3500X

### GPU

GeForce GTX 1650

### Additional information

Heap dump: https://cloud.rococpy.com/view/577/share

**Comment by MeeniMc** [comment]
I had that and I have not seen it in a long time myself. Probably stale.
