### ISSUE TITLE
Stained glass blocks disappearing on certain angles

### ISSUE THREAD

**Issue by aaronfilarca** [jellysquid3/Sodium#1232]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

Stained glass not disappearing

### Actual Behavior

Stained glass disappearing on certain angles

### Reproduction Steps

1. Place stained glass
2. Look around until it bugs
3. If you're lucky you might be able to reproduce it

### Java version

Java 17.0.2

### CPU

AMD Ryzen 5 3500U

### GPU

AMD Radeon Vega 8

### Additional information

![2022-03-18_18 26 59](https://user-images.githubusercontent.com/69566792/158987581-fb73a603-d849-4e5a-9d02-aa2add36dac8.png)
![2022-03-18_18 27 01](https://user-images.githubusercontent.com/69566792/158987589-d1aa8977-1bc5-47e3-b325-fa5010f19bcd.png)
![image](https://user-images.githubusercontent.com/69566792/158987710-0175704c-7316-420b-b169-3e4b7bd4b806.png)

**Comment by Lolothepro** [comment]
#872 ?

**Comment by aaronfilarca** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/872
