### ISSUE TITLE
Sodium crashes the game when teleporting

### ISSUE THREAD

**Issue by redstonerti** [jellysquid3/Sodium#1233]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Reproduction Steps

We also have wayplates in our modpack, basically sometimes when we use them and teleport to and from a far away location, the game crashes. The crash report says it was from sodium so i'm posting it here. I suspect this has nothing to do with wayplates it's probably just due to the fact that we are loading in a lot of chunks.

### Crash Report file

[crash-2022-03-19_14.37.06-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8309225/crash-2022-03-19_14.37.06-client.txt)

**Comment by Lolothepro** [comment]
#1016
