### ISSUE TITLE
Unable to install Sodium on macOS, "no main manifest attribute, in sodium-fabric-mc1.18.2-0.4.1+build.15.jar"

### ISSUE THREAD

**Issue by Piipperi** [jellysquid3/Sodium#1234]
### Version information

mc1.18.2-0.4.1+build.15

### Expected Behavior

To be able to install Sodium

### Actual Behavior

Installer will not open, launching from Finder gives me a "Java Application launch failed. Check Console for possible error messages related to ”/Users/Piipperi/Downloads/sodium-fabric-mc1.18.2-0.4.1+build.15.jar”."

If launched from Terminal, I get "no main manifest attribute, in sodium-fabric-mc1.18.2-0.4.1+build.15.jar"

### Reproduction Steps

Download the latest Sodium from SourceForge, and try launching it either from Finder or Terminal

### Java version

16.0.2

### CPU

Intel Core i7-4960HQ

### GPU

AMD Radeon RX 5700 XT

### Additional information

macOS version: 12.3 (21E230)

**Comment by Timolino456** [comment]
Um, if I understood you correctly... the Sodium jar is not an installer. You have to drop it into your mods folder.

**Comment by Piipperi** [comment]
> Um, if I understood you correctly... the Sodium jar is not an installer. You have to drop it into your mods folder.

Well now I feel stupid, I thought Sodium would be a replacement for OptiFine but I guess not

**Comment by Timolino456** [comment]
> > Um, if I understood you correctly... the Sodium jar is not an installer. You have to drop it into your mods folder.
> 
> Well now I feel stupid, I thought Sodium would be a replacement for OptiFine but I guess not

What do you mean by that? You don't need installers for mods, just install the needed mod loader and drag the jar file of the mod you downloaded into the mods folder. Or use a launcher like MultiMC to make it even easier. There's not much to it.

**Comment by Piipperi** [comment]
> > > Um, if I understood you correctly... the Sodium jar is not an installer. You have to drop it into your mods folder.
> 
> > 
> 
> > Well now I feel stupid, I thought Sodium would be a replacement for OptiFine but I guess not
> 
> 
> 
> What do you mean by that? You don't need installers for mods, just install the needed mod loader and drag the jar file of the mod you downloaded into the mods folder. Or use a launcher like MultiMC to make it even easier. There's not much to it.

OptiFine can be installed just by itself, so one doesn't need a mod loader like Forge or Fabric for it. That's what I ment.

**Comment by meadowsys** [comment]
aahh, what people usually mean when they say sodium is a replacement for optifine is not that it would be 100% a drop in process (everything from installation to usage to everything else is _exactly_ 1:1 the same). what they mean is that it only replaces its ingame optimisation functionality. sodium still needs to be installed alongside with fabric and api
