### ISSUE TITLE
Replacing the .fabric folder solves the flickering when breaking blocks

### ISSUE THREAD

**Issue by wangwang-code** [jellysquid3/Sodium#1235]
#1229 
```
Minecraft 1.18.2
sodium-fabric-mc1.18.2-0.4.1+build.15
Windows 10 2004
Processor/Graphics: i3 1005G1 (Intel(R) UHD Graphics)
Driver version: 30.0.101.1191
```
Before replacing .fabric

https://user-images.githubusercontent.com/64469117/159122089-876c5beb-16aa-4604-923b-434399ba5008.mp4

After replacing .fabric

https://user-images.githubusercontent.com/64469117/159122115-6a9ee49a-ac6a-4901-9aa1-b16a6ec1410a.mp4

[.fabric](https://drive.google.com/file/d/1kBOtXNEzrotYb9cRSj4qx8baAYeMWX0I/view?usp=sharing) folder for replacement is from 1.18.1

(Google translation)

**Comment by jLn0n** [comment]
maybe outdated jar files is the culprit in .fabric/processedMods

**Comment by wangwang-code** [comment]
> maybe outdated jar files is the culprit in .fabric/processedMods

Maybe, but the flickering came back after adding some mods

**Comment by wangwang-code** [comment]
@jLn0n 
A new discovery, when the libraries in 1.18.2 are deleted and replaced with the libraries in 1.18.1, the broken block will not flicker, but restarting Minecraft once, flickering appears

**Comment by wangwang-code** [comment]
> A new discovery, when the libraries in 1.18.2 are deleted and replaced with the libraries in 1.18.1, the broken block will not flicker, but restarting Minecraft once, flickering appears

This state can be protected with dashloader
Install dashloader mod after replacing libraries (without dashloader-cache folder)
(Google translation)

**Comment by FreezePhoenix** [comment]
This appears to be an occasional bug, that only affects some launches. Unsure as to why it occurs.

**Comment by awong6687** [comment]
I have confirmed it works for some time, but does come back.  For now I just turn it off and play minecraft taking advantage of all of the other mods.

**Comment by y2k04** [comment]
Confirmed that this works

**Comment by wangwang-code** [comment]
Delete the .fabric folder and the libraries file, unzip [.minecraft.rar](https://drive.google.com/file/d/16NJp2oXB83px_jGqDOkvy8pN4slKa36a/view?usp=sharing) to the .minecraft directory, start minecraft, you will find that the flicker no longer appears when breaking blocks

(Google translation)

**Comment by awong6687** [comment]
That worked.  Thank you.

Andrew
