### ISSUE TITLE
game says saving world then crashes

### ISSUE THREAD

**Issue by boslire** [jellysquid3/Sodium#1237]
### Version information

sodium-fabric-mc1.16.1-0.1.0

### Reproduction Steps

i just open a world and it cant load, but when i removed the mod i could open worlds

### Crash Report file

[eE.txt](https://github.com/CaffeineMC/sodium-fabric/files/8314805/eE.txt)

**Comment by boslire** [comment]
[crash-2022-03-21_18.51.29-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8314847/crash-2022-03-21_18.51.29-client.txt)


there is also this

**Comment by jellysquid3** [comment]
Your config file is corrupted. Delete the file `sodium-options.json` in the `config` folder of where you installed Fabric to.
