### ISSUE TITLE
Render glitches on AMD Radeon HD 5700 Series

### ISSUE THREAD

**Issue by zptr1** [jellysquid3/Sodium#1238]
### Version information

mc1.18.2-0.4.1+build.15

### Expected Behavior

Everything works fine without any render glitches

### Actual Behavior

Random render glitches occur:

https://user-images.githubusercontent.com/43674123/159516066-57b7d4f0-bede-4ca2-9028-bb979d85549b.mp4
![javaw_5YGOLEikdF](https://user-images.githubusercontent.com/43674123/159516354-52886e99-2492-4f71-bf8f-c4a22fe0dbb7.png)
![image](https://user-images.githubusercontent.com/43674123/159516414-18e13eb6-73a7-49ae-8348-2e5181993e0a.png)

I was getting the same render issue on 1.16-, but managed to fix it by disabling a setting (forgot the name but the description said something about z-stitching). But on 1.17+, the setting was gone. I am getting the same render issues in vanilla and OptiFine too, but they are very rare.

I tried disabling every resourcepack and running minecraft with only sodium installed, I tried changing every possible setting, I tried reinstalling GPU drivers but nothing helped.

### Reproduction Steps

i dont know

### Java version

Java 17.0.1 2021-10-19 LTS

### CPU

Intel Core i5 650

### GPU

AMD Radeon HD 5700 Series

### Additional information

I've experienced this issue without any mods expect Sodium, but here's my current mod list:

```
3d Skin Layers 1.4.2
Architectury 4.1.32
AutoFish 0.9.4
Chat Heads 0.6.0
ClickThrough 0.47.10
DynamicSoundFilters 1.3.0
Fabric API 0.48.0
ModMenu 3.1.0
MouseWheelie 1.8.3
ShulkerboxTooltip 3.0.6
Xareo's Minimap 22.3.0
Xareo's World Map 1.20.3.1
Sodium 0.4.1
Indium 1.0.2
```

Resource Packs: (also tried disabling any of them)

```
Icons 1.6.2
Reimagined v1.27
```

Video Settings: (i tried changing almost every setting but none did help)

```
Fullscreen: OFF
VSync: OFF
Max Framerate: Unlimited
Graphics: Fancy
Chunk Update Threads: Default
Always Defer Chunk Updates: ON
Use Block Face Culling, Use Fog Occlusion, Use Entity Culling, Animate Only Visible Textures: ON
Chunk Memory Allocator: Async
Use Persistent Mapping: ON
CPU Render-Ahead Limit: 3 frame(s)
Allow Direct Memory Access: ON
```

**Comment by zptr1** [comment]
![image](https://user-images.githubusercontent.com/43674123/159521225-15ddacad-caa6-427a-8476-6dc7eedd8bef.png)

**Comment by andrejcremoznik** [comment]
Edit: disregard, different card

---

Chiming in as I have a 5700 too; I don't have this issue on Linux. Here's my specs working fine:

CPU
```
Vendor ID:               AuthenticAMD
  Model name:            AMD Ryzen 5 3600 6-Core Processor
    CPU family:          23
    Model:               113
```
GPU
```
2f:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] (rev c4) (prog-if 00 [VGA controller])
        Subsystem: Micro-Star International Co., Ltd. [MSI] Device 3814
        ...
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu
```
Software
```
mesa 21.3.7-2
linux 5.16.16.arch1-1
jre-openjdk 17.0.3.u3-1
```
Mods
```
dynamic-fps-2.1.0.jar
fabric-api-0.47.9+1.18.2.jar
lambdynamiclights-2.1.0+1.17.jar
litematica-fabric-1.18.2-0.11.0.jar
logical_zoom-0.0.14.jar
malilib-fabric-1.18.2-0.12.0.jar
minihud-fabric-1.18.2-0.22.0.jar
modmenu-3.1.0.jar
sodium-fabric-mc1.18.2-0.4.1+build.15.jar
tweakeroo-fabric-1.18.2-0.13.0.jar
```

**Comment by pajicadvance** [comment]
@andrejcremoznik The original report has the old HD 5700 card, you have the RX 5700.

**Comment by jellysquid3** [comment]
> I was getting the same render issue on 1.16-, but managed to fix it by disabling a setting (forgot the name but the description said something about z-stitching). But on 1.17+, the setting was gone. I am getting the same render issues in vanilla and OptiFine too, but they are very rare.

The problem is not an issue with Sodium, then. Either your graphics drivers are buggy, or your graphics card is experiencing some kind of hardware failure.
