### ISSUE TITLE
The game crashes when looking at mob heads in the newest version of sodium e.g. wither heads (block)

### ISSUE THREAD

**Issue by lxly9** [jellysquid3/Sodium#1242]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Expected Behavior

Smooth playing, summoning the wither.

### Actual Behavior

The game crashes when the head is just on screen with one single pixel.

### Reproduction Steps

1. Open World
2. place mob head -> game crashes
alternatively: look at mob head -> game crashes

### Java version

Java 17.01

### CPU

AMD Ryzen 6 2600X

### GPU

GeForce RTX 2060

### Additional information

This is my first bug submission, sorry if I did it wrong!

**Comment by jellysquid3** [comment]
We need a crash log file. You have not provided one.

**Comment by jellysquid3** [comment]
Ask for this issue to be re-opened if and when you post a crash log.
