### ISSUE TITLE
Crashing when i'm trying open game

### ISSUE THREAD

**Issue by manul694** [jellysquid3/Sodium#1243]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

I'm launching game and getting this:
![image](https://user-images.githubusercontent.com/48861382/160238382-452c9c68-e70d-4f9b-951b-83546d2f0eca.png)

java 17

### Crash Report file

log: https://pastebin.com/5J2cRjgm
Crash report didn't created

**Comment by jellysquid3** [comment]
See #899 for a solution.
