### ISSUE TITLE
[Suggestion] FPS Limiter to set a max. FPS

### ISSUE THREAD

**Issue by Eiion** [jellysquid3/Sodium#1244]
With how great the mod is I don't really need to run the game at 600 and more FPS on my main PC. Why? Well, why would I let my CPU/GPU work as hard as it can if a much lower load would do the job just as good - while saving energy and keeping the system cooler.

When thinking of my old little Thinkpad this would be even more relevant, as energy is limited with the battery capacity and since fans on laptops can get really annoying, letting the game run only as fast as needed limiting the max. FPS would be very beneficial as well.

So I'd like to suggest to add a "max. FPS" input option so if our machine is able to run the game at e.g. 150 FPS we can slow it down to maybe 60FPS (my monitor can't do more than that anyways) or even less, like 30 FPS for the 5 year old CPU in the little laptop.
If this option had a toggle to turn it on/off (or if "0" as the input would mean "unlimited FPS") that also would be nice, just to let it run as fast as possible every now and then to see how much headroom we still have (think of it as 'how many more farms/redstone machines could I build within the same area and still not slow the game down below max FPS).

Thanks for considering my suggestions and for giving us this great mod to be able to run the game even on old weak machines!

**Comment by jellysquid3** [comment]
Yes, there is no reason to run the game at that frame rate, and frankly I don't know why people do so.

However, there is already a FPS limit option. It can be found in `Video Settings > General` next to V-Sync. By default it should be set to 120 FPS, but it is ignored if V-Sync is enabled.

**Comment by Eiion** [comment]
Ah, perfect. I must've been blind when looking through the settings. Sorry. Many thanks!
