### ISSUE TITLE
Excessive frame-loss, stuttering, and freezing

### ISSUE THREAD

**Issue by cooljpeg** [jellysquid3/Sodium#1245]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

I installed Sodium, Lithium, Iris, and Phosphor to see how they compared to Optifine. I've heard that Sodium performs much better than Optifine, so I was expecting either similar or improved results.

### Actual Behavior

Whenever I fly around in Creative (or even walk around in Survival), I just get exponential frame-loss, stutters, freezes, and even crashes, even if I try and simply enter the menu to adjust settings or even Save & Quit. I was mainly testing out Render Distances from 18-24, which would average about 40 fps, and over the span of a minute or so of moving around, would drop to 20fps, then to 10fps, and then to 2fps, and then the game freezes and I have to force quit the game. I tried other Render Distances, but even 12 was giving me issues, whereas with Optifine (or even Vanilla), 12 and even up to 16 runs pretty flawlessly (around 115 fps consistently, minor stutters when loading chunks).

### Reproduction Steps

Honestly, I wish I had more precise info, but literally just running the game with Sodium (and the other mods mentioned) and moving around a bit produces these results. I have no clue what could be causing it.

### Java version

Java 17.0.2

### CPU

AMD Ryzen 7 3700X 8-Core Processor

### GPU

NVIDIA GeForce GTX 1660 SUPER

### Additional information

- fabric-api-0.48.0+1.18.2
- iris-mc1.18.2-1.2.2-build.32 (shaders were off when these issues occurred)
- lithium-fabric-mc1.18.2-0.7.9
- phosphor-fabric-mc1.18.x-0.8.1

**Comment by Kroppeb** [comment]
You mention encountering crashes? Do you have any crashlogs we can take a look at?

**Comment by cooljpeg** [comment]
Yes! Here's my most recent one:

[crash-2022-03-26_12.02.28-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8356401/crash-2022-03-26_12.02.28-client.txt)

**Comment by cooljpeg** [comment]
Yes! [Here's my most recent one](https://pastebin.com/5BHut8z8), I hope this helps. :+}

**Comment by jellysquid3** [comment]
Your client for some reason is only being given 1 GiB of memory, which isn't enough for modern versions of the game. Since you have 16 GiB of RAM available in your computer, can you try increasing the memory allocated to the game (maybe 3 GiB)? Your launcher should provide this as an option in the profile settings... somewhere.

**Comment by jellysquid3** [comment]
In the case of the standard Minecraft launcher and most others, this means finding the "Java arguments" section in your profile's settings, and adjusting the `-Xmx1G` text from `1G` to `3G`.

**Comment by cooljpeg** [comment]
Oh! Wow thank you for reminding me about that, I'm embarrassed that didn't cross my mind before 😓 Forgot to mention that I'm using MutliMC 5 as my launcher, so I just went into the settings and allocated a few more gigs to my maximum and it's running a lot better! Coasting at 145 fps pretty consistently now! :+}

Definitely still some frequent stuttering, is this normal? It's nothing unbearable, I just don't remember my game stuttering this often (about a spike every 10 seconds of moving around).

**Comment by GlitchSlayed** [comment]
The stuttering sounds a lot like a GC issue (at least most commenly) try using jvm arguments like -XX:+UseShenandoahGC -XX:+UnlockExperimentalVMOptions instead of your regular ones and see if it helps (if not revert to your og args)

**Comment by jellysquid3** [comment]
Per changes in policy on our issue tracker, we are closing issues which are general inquiries about performance issues and such. If you are experiencing performance issues and need help, then please use the [Discord server](https://caffeinemc.net/discord).
