### ISSUE TITLE
Does Sodium for 1.18.2 work on an earlier 1.18.x?

### ISSUE THREAD

**Issue by brunogenovese** [jellysquid3/Sodium#1246]
I apologize asking such a dumb question here, but I could not find a forum or Q&A location for Sodium.

I am on Java edition 1.18.1 and not ready to move to 1.18.2, but I see that sodium tends to skip versions.  Is it safe to use 1.18.2 on an earlier 1.18, or would that break things?  In other words, should I wait until all of my mods release on 1.18.2 before upgrading to 1.18.2 and install Sodium?

More generically, is that kind of thing an issue with Sodium and compatibility to other mods if Sodium only releases for a single y subversion of any given 1.x.y?  I am guessing "no problem", but I figured I'd ask before I consider using Sodium.

EDIT:  I see that in modrinth there is a 1.18.1 alpha 6 version that wasn't displayed in curseforge.  I'll use that for now.   A reply would still be welcome, but no longer as important.  Ty.

**Comment by jellysquid3** [comment]
If you look at the [Modrinth page for Sodium](https://modrinth.com/mod/sodium/versions), you can see a complete list of every released version of the mod, and what versions of the game it can run on. Each release includes the version of Minecraft it was designed for in the file name, but that does not necessarily imply what versions of the game it can run on.

In other words, per the downloads page linked above, the most recent release for MC 1.18.1 was _Sodium mc1.18.1-0.4.0-alpha6._
