### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by driftirl** [jellysquid3/Sodium#1247]
### Version information

better minecraft fabric mc: 1.18.2 forge 0.13.3

### Reproduction Steps

when adding Controller Support-1.18.2-6.1.3-Fabric.jar i get this crash on launch

### Crash Report file

[crash-2022-03-28_14.37.56-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8363333/crash-2022-03-28_14.37.56-client.txt)

**Comment by Lolothepro** [comment]
Fabric

**Comment by driftirl** [comment]
> Fabric

??

**Comment by Lolothepro** [comment]
Version Information
better minecraft fabric mc: 1.18.2 fabric 0.13.3 ✅

**Comment by jellysquid3** [comment]
NotEnoughCrashes is masking the actual error here. Remove the mod and examine the crash report it produces. This is very unlikely to be a problem with Sodium.
