### ISSUE TITLE
Weird rendering artifacts with transparency on the HUD

### ISSUE THREAD

**Issue by Leo40Git** [jellysquid3/Sodium#125]
### Expected Behavior
All boss bars should be rendered correctly.

### Actual Behavior
Only the first boss bar is rendered correctly; the second one seems to be having issues with its alpha.
![2020-07-20_19 24 53](https://user-images.githubusercontent.com/7997354/87961944-1f3ee000-cabf-11ea-8cc4-f043705cfc6d.png)
Hwyla is apparently also a victim of this issue.

### Reproduction Steps
1. `/bossbar add test1 "First Test"`
2. `/bossbar set minecraft:test1 players @a`
3. `/bossbar add test2 "Second Test"`
4. `/bossbar set minecraft:test2 style notched_6` (note: it *has* to be a "notched" style - I think this is the part that's messing up)
5. `/bossbar set minecraft:test2 players @a`

### System Information

- Java Version: AdoptOpenJDK 14.0.2.12
- CPU: Intel Core i5-8250U @ 1.80GHz
- GPU: NVidia GeForce MX150

**Comment by Leo40Git** [comment]
Just tested with 1df506f, this issue still occurs.

**Comment by mrmangohands** [comment]
Was this fixed?

**Comment by Leo40Git** [comment]
This is a vanilla bug (apparently I didn't state that before closing). Ended up [fixing it myself](https://github.com/ModsByLeo/MultiBossBarFix).
