### ISSUE TITLE
Game crashes when loading any world

### ISSUE THREAD

**Issue by Katachell** [jellysquid3/Sodium#1251]
### Version information

sodium-1.16.1-backport-fabric-0.2.0+build.17

### Reproduction Steps

1. Have sodium in a multimc instance with fabric loader (NOT fabric api) (other mods can be enabled or disabled as it makes no difference and sodium will crash the game regardless)
2. start the game
3. either create a new singleplayer world or join an existing one (havent tested multiplayer)
4. let the world loading screen hit 100%
5. the only things that load are the player hand and hotbar ui, no terrain loads, no controls work
6. immediate crash

### Crash Report file

[hs_err_pid20588.log](https://github.com/CaffeineMC/sodium-fabric/files/8344577/hs_err_pid20588.log)

I've run 2 separate instances (setup mostly the same I believe) with the same issue, sent the error file for one, but the other instance crashes in the exact same way, but doesn't give a report - yes, I checked the crash-reports folder. No idea why one gives the report and the other doesn't.

### Additional information

1. I had sodium working in an instance (1.16.1) for about a month. then i didnt change anything but one day this just started happening - the files in the folder stayed the same - and now crashes 100% of the time. 
2. even if i redownload the zip and add it to a brand new instance with nothing else, it still does the same crash
3. if i disable sodium from multimc, the instance can function again
4. i submitted a report on multimc and they looked at the log and said it was not the fault of the launcher
5. i have 2 instances set up with sodium that use different java versions, it still doesnt work in either 
6. other mods like lithium work fine so i know im installing things correctly (plus i had sodium working before)

**Comment by jellysquid3** [comment]
> backport

We don't provide backports. Whichever version of Sodium you are using does not come from us.
