### ISSUE TITLE
look weird in galaxy book2

### ISSUE THREAD

**Issue by gyhmz** [jellysquid3/Sodium#1252]
### Version information

mc1.18.2 + sodium 0.4.1 build15

### Expected Behavior

I expected  to have a better fps(the fps without sodium was too low).

### Actual Behavior

![Uploading PXL_20220331_031150490.MP~2.jpg…]()

### Reproduction Steps

I installed minecraft in my galaxybook2(hwmodded to 8g ram) ,following  the steps in this link “  https://github.com/adiantek/mc-spx  ”. Then I installed  sodium to have a better fps.

### Java version

microsoft-jdk-17.0.2.8.1-windows-aarch64

### CPU

snapdragon 850

### GPU

adreno 630

### Additional information

Windows11 22000.593  arm64

**Comment by gyhmz** [comment]
![PXL_20220331_031150490 MP~2](https://user-images.githubusercontent.com/95202722/160972802-a5be4d0d-6a75-443b-9d35-3e336ae4a721.jpg)

**Comment by ubionexd** [comment]
Your Adreno 630 is not supported by Sodium, because its only features OpenGL 3.2. Sodium requires a minimum of OpenGL 3.3, but it may be instable. For more, read the [Modrinth](https://modrinth.com/mod/sodium) page.

**Comment by gyhmz** [comment]
![Screenshot_20220401-090451_Firefox](https://user-images.githubusercontent.com/95202722/161175033-1c54e7af-1faa-4619-a2be-b7fcb52c0dd8.jpg)

I installed this, so theoretically it supports opengl 3.3

**Comment by jellysquid3** [comment]
We don't support OpenGL translation layers. They are known to be buggy and cause issues with the mod.
