### ISSUE TITLE
MC Hangs on loading screen and becomes not responding when using sodium

### ISSUE THREAD

**Issue by oie1** [jellysquid3/Sodium#1253]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Reproduction Steps

***Use MultiMC
1. Make a new 1.18.2 instance.
2. Add Fabric
3. Add Sodium mod sodium-fabric-mc1.18.2-0.4.1+build.15.jar
4. Start
5. it hangs

### Crash Report file

https://paste.ee/p/6QD0J
it says killed by user because it hangs and i waited a long time for it so yea

### Additional information

i used no other mods, i have disabled my other mods, i have disabled my texture pack and it dosent work, are there any secret dependicies i should use ???

**Comment by jellysquid3** [comment]
Duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/899. You need to update your graphics driver. See the linked issue for more information.

**Comment by oie1** [comment]
is it going to messup my graphics, im scared
@jellysquid3

**Comment by oie1** [comment]
please tell

**Comment by oie1** [comment]
ima run it
hopefully it works

**Comment by oie1** [comment]
it worked
yey
im really scared when i reboot if it works
:[[[[
