### ISSUE TITLE
when memory allocator is Async, swapping lobbies on some servers makes the world not load right

### ISSUE THREAD

**Issue by KerbCraft** [jellysquid3/Sodium#1255]
### Version information

1.18.2

### Expected Behavior

when swapping lobbies on servers for the shaders to not break

### Actual Behavior

some chunks dont load and loaded ones glitch in and out along with some odd green cubes
![2022-04-03_06 44 46](https://user-images.githubusercontent.com/97920867/161431121-5b9183de-0f03-489a-9266-f33c4186061b.png)

### Reproduction Steps

1. have sodium memory allocator set to Async, hop onto a server (Hypixel is the most glitchy for me)
2. enable shader (seems like any shader that uses Async works)
3. swap lobbies

something like this happen
![2022-04-03_06 51 08](https://user-images.githubusercontent.com/97920867/161431265-179d8d7d-b07a-42e0-a9f4-1c1ece48b426.png)
s

### Java version

Java 17.0.1

### CPU

11th Gen Intel Core i9-11900F

### GPU

NVIDIA GeForce RTX 3080

### Additional information

1. Sodium
2. Lithium
3. Phosphor
4. Iris
5. FabricLoader (0.13.3-1.18.2)

**Comment by jellysquid3** [comment]
Can you reproduce this *without* Iris? It could very well be their mod causing this.

**Comment by KerbCraft** [comment]
I can't get the shaders working without iris so I guess iris is the issue, sorry for your time
