### ISSUE TITLE
Entities and block outlines rendering through blocks sometimes.

### ISSUE THREAD

**Issue by LampOS** [jellysquid3/Sodium#1257]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Expected Behavior

The entities and block outlines should not be fully visible.

### Actual Behavior

The entities are visible, as though they are in front of the blocks. This issue is also presented with block outlines.

### Reproduction Steps

Use the mods in the mod list below

### Java version

Java 18

### CPU

Intel core i5-10400f @2,90GHz

### GPU

NVIDIA GeForce RTX 3050

### Additional information

**-Images of Issue-**
![2022-04-03_22 54 58](https://user-images.githubusercontent.com/102937417/161467582-92c63125-483e-44d0-8547-17e26e48dab3.png)
![2022-04-03_23 08 40](https://user-images.githubusercontent.com/102937417/161467585-363e602b-180b-4044-a22b-e4d67bc7e394.png)
![2022-04-03_23 08 43](https://user-images.githubusercontent.com/102937417/161467586-128ff464-951a-4487-b1fa-8dbc4c7b2580.png)
![2022-04-03_23 08 51](https://user-images.githubusercontent.com/102937417/161467593-c89dad0d-0bc7-44df-949b-72d1cccbd5d9.png)
![2022-04-03_23 09 04](https://user-images.githubusercontent.com/102937417/161467595-7cbcc98d-8e39-4aa8-bbcc-3e266cff58af.png)
![2022-04-03_23 09 20](https://user-images.githubusercontent.com/102937417/161467599-9bc16324-7b65-497b-9669-17d6d0d1fe49.png)
.

**-Mods List-**
![image](https://user-images.githubusercontent.com/102937417/161467984-5925301b-b817-46af-bab4-352f7ed8b3bb.png)

**Comment by bAdOoWindy** [comment]
maybe this bugs allow-so reduce preformance

in all item sorter
FPS just 9-10
look like entities culling not working

**Comment by hexadecimal233** [comment]
Prob a mod compatibility issue, can't reproduce

**Comment by jellysquid3** [comment]
We haven't been able to reproduce this issue, nor we have we seen any reports of it happening with just Sodium. If you can still reproduce this problem with the latest version of Sodium, then please ask for this issue to be re-opened, and try to narrow down the exact mods which cause the incompatibility (if any).
