### ISSUE TITLE
Loading Terrain... screen is longer than usual

### ISSUE THREAD

**Issue by icreatedthisaccounttoday** [jellysquid3/Sodium#1258]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

Loading Terrain... screen should be shorter

### Actual Behavior

Loading Terrain... screen is longer

### Reproduction Steps

idk

### Java version

17.0.1

### CPU

Intel(R) Pentium(R) CPU G4400

### GPU

Intel HD Graphics 510

### Additional information

I was playing on pvp legacy and everytime I join a game Loading Terrain.. screen is longer than without sodium
(even though it just slightly longer)

**Comment by Phoenix-Starlight** [comment]
This is because loading terrain screen in vanilla code has a fixed delay. There are mods such as fastload and kenny tvs force close which will change the behavior to render as soon as all the needed data is sent.

**Comment by Oyssis** [comment]
Hey its me and no how is it vanilla code if without sodium its faster?
