### ISSUE TITLE
Cloud Height Slider

### ISSUE THREAD

**Issue by NoComment1105** [jellysquid3/Sodium#126]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
A Slider within Options to raise the height of clouds

**Describe alternatives you've considered**
Optifine, how ever optic fabric be broken

**Comment by amnotbananaama** [comment]
Imo this falls under "things that can be done by other companion mods". There are 2 mods that perform this function already, that can be used along with Sodium.

https://github.com/Draylar/soaring-clouds
https://github.com/haykam821/Raised-Clouds

**Comment by NoComment1105** [comment]
Ah ok thank you
