### ISSUE TITLE
Outdated fabric install link in README.md

### ISSUE THREAD

**Issue by TheSwample** [jellysquid3/Sodium#1262]
### Version information

any

### Expected Behavior

Clicked on link named 'here' in the sentence "If you haven't installed Fabric mods before, you can find a variety of community guides for doing so [here](https://fabricmc.net/wiki/install)."
You would expect the link to take you to the fabric install page.

### Actual Behavior

The link takes you to a "This topic does not exist yet" page.

### Reproduction Steps

Click on the link in the sentence "If you haven't installed Fabric mods before, you can find a variety of community guides for doing so [here](https://fabricmc.net/wiki/install)." Or just go to https://fabricmc.net/wiki/install.

### Additional information

I believe the actual page it's supposed to bring you to is now https://fabricmc.net/wiki/player:tutorials:install

**Comment by Phoenix-Starlight** [comment]
Visiting the URL again shows that the page is still there. Can be closed now.

**Comment by DragonEggBedrockBreaking** [comment]
The [old url](https://fabricmc.net/wiki/install) is valid and the [new suggested url](https://fabricmc.net/wiki/player:tutorials:install) is not valid so no action would be necessary. Additionally, this section is no longer in the README.
