### ISSUE TITLE
ONE BLOCK AT A TIME Snapshot support

### ISSUE THREAD

**Issue by RedWideWeb** [jellysquid3/Sodium#1264]
**Is your feature request related to a problem? Please describe.**
Sodium renderer works fine on this snapshot. But there is new block called generic_item_block. It looks like white carpet but has an id and the game renders it as an item with that id.

**Describe the solution you'd like**
generic_item_block must be rendered as items that are in the id of the block

**Additional context**
That is the only thing we need in order to happily play with Sodium on this snapshot!

**Comment by jellysquid3** [comment]
Sorry. We don't support snapshot versions and tooling for it tends to be temperamental. It would take us some time to port whatever hack Mojang has put in the code for this, for what is an April Fool's joke.

**Comment by RedWideWeb** [comment]
Sodium already works with this version. I just replaced minecraft 1.18.x with minecraft 1.19.x in fabric-mod.json. Even Iris Shaders are working. The only issue is that we don’t see items on the ground because they are all white carpets with different block ID. We only request this do be implemented. Please!
![63BFC302-EDD9-4E22-9E0A-D8FAA3C94487](https://user-images.githubusercontent.com/58992150/164886852-d5037780-0ffa-43c7-a7d1-bb60e0165827.jpeg)

**Comment by RedWideWeb** [comment]
And it works great! I have like 400+ fps when on regular version I have around 30-40 fps

**Comment by RedWideWeb** [comment]
Okay @jellysquid3  I will try to do it myself can you at least tell we where do I need to look to be able to change the way a block renders and change it’s texture to an item?

**Comment by SomeoneWithBadFPS803** [comment]
> Sodium already works with this version. I just replaced minecraft 1.18.x with minecraft 1.19.x in fabric-mod.json. Even Iris Shaders are working. The only issue is that we don’t see items on the ground because they are all white carpets with different block ID. We only request this do be implemented. Please! ![63BFC302-EDD9-4E22-9E0A-D8FAA3C94487](https://user-images.githubusercontent.com/58992150/164886852-d5037780-0ffa-43c7-a7d1-bb60e0165827.jpeg)

can you please make a video tutorial

**Comment by Felix14-v2** [comment]
You can also use this mod instead:
https://modrinth.com/mod/oneblock

**Comment by ghost** [comment]
> You can also use this mod instead: https://modrinth.com/mod/oneblock

FYI, that mod is for Legacy Fabric 1.12.2/1.8.9, not "modern" Fabric

**Comment by Felix14-v2** [comment]
Oh, sorry, I missed that part somehow (ノへ￣、)
