### ISSUE TITLE
I used to run minecraft completely fine before I installed the sodium mod. When I installed it the game doesn't even launch. How do I fix this?

### ISSUE THREAD

**Issue by GCPLAYS2022** [jellysquid3/Sodium#1268]
### Version information

it crashes for me in every version. I tried playing on a different version of minecraft and it still crasshes

### Reproduction Steps

Like I said. When I installed the mod, Minecraft just doesn't want to load in.

### Crash Report file

It doesn't give me any crash report

**Comment by Kroppeb** [comment]
Could you provide a screenshot so we can get an idea of the issue. You mention it "crashes"; is there some kind of message that shows up?

**Comment by GCPLAYS2022** [comment]
There is no message that pops out. You see when I open the minecraft
launcher and run fabric, it loads up after that minecraft just doesn't
open.

**Comment by offbeat-stuff** [comment]
you should your log file named latest.log should be in %APPDATA%/.minecraft/logs/latest.log

**Comment by jellysquid3** [comment]
This issue is a likely the same as #899. Please see the instructions there on how to fix it. If that doesn't resolve your issue, please ask for this issue to be re-opened, and provide a complete description of your computer's hardware, installed graphics driver, and operating system version.
