### ISSUE TITLE
Weird graphical issue on the world surface

### ISSUE THREAD

**Issue by IotaBread** [jellysquid3/Sodium#127]
### Expected Behavior
The world should look as vanilla Minecraft.

### Actual Behavior
The world looks like if the chunks were overlapping. Only happens with `Multidraw (GL 4.3)` in the chunk renderer and in the surface of the world.

### Reproduction Steps
Not sure on how to reproduce. With just installing the mod I get the issue until I change the chunk renderer to Oneshot (GL 3.0).

### Attachments
![2020-07-20_16 20 24](https://user-images.githubusercontent.com/47987888/87979712-7b463c00-caa0-11ea-979a-e8f9157da356.png)
![2020-07-20_16 20 39](https://user-images.githubusercontent.com/47987888/87979730-826d4a00-caa0-11ea-87f3-3a6e92a29c34.png)
![2020-07-20_16 23 13](https://user-images.githubusercontent.com/47987888/87979744-88632b00-caa0-11ea-8bb7-2875189506b8.png)
![2020-07-20_16 23 24](https://user-images.githubusercontent.com/47987888/87979748-89945800-caa0-11ea-8a98-820bdb292df9.png)

### System Information
- Java Version: 1.8.0_51 64bit
- CPU: Intel(R) Celeron(R) CPU 1005M @ 1.90GHz (2 CPUs), ~1.9GHz
- GPU: Intel(R) HD Graphics

**Comment by Thathano** [comment]
Hello, I got the same issue with a system configuration similar to yours. Does the one-shot option affect the fps and the effcicacity of sodium? Anyways thanks for the solution.

**Comment by Oberfail** [comment]
its due to faulty intel drivers under windows
either use a older GL version, or use linux

**Comment by jellysquid3** [comment]
Merging this issue into #179.

**Comment by mastercraft01** [comment]
bro, what does it disable drive blacklist for?
