### ISSUE TITLE
Is there a version of sodium for 1.18.1?

### ISSUE THREAD

**Issue by CittiDaBozo** [jellysquid3/Sodium#1270]
**Is your feature request related to a problem? Please describe.**
I'm trying to get sodium on minecraft 1.18.1 because optifine doesn't want to work.

**Describe the solution you'd like**
I'd like, if possible, to make sodium available for 1.18.1.

**Describe alternatives you've considered**
I've tried to use optifine but it just didn't work out.

**Additional context**
---

**Comment by jellysquid3** [comment]
https://modrinth.com/mod/sodium/version/mc1.18.1-0.4.0-alpha6
