### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by HacoKavanah** [jellysquid3/Sodium#1271]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

1. Have Fabric API's newest version (fabric-api-0.50.0+1.18.2.jar
2. Have Architectury API's newest version (architectury-4.1.44.jar)
3.  The versions older than the ones listed above work with Sodium, the newest ones dont. I suspect Sodium to be the cause since that is the only thing it states in the crash report.

### Crash Report file

![image](https://user-images.githubusercontent.com/87395651/163063991-9b83a750-cd68-49d5-bdcf-5ff45b3609ba.png)

**Comment by jellysquid3** [comment]
Remove NotEnoughCrashes and restart the game. It is hiding the actual errors.

**Comment by HacoKavanah** [comment]
Usually NotEnoughCrashes still allows me to see the actual errors and fix the crashes. However, this time turning it off showed me that the true villain of this story was actually Botania and someone had already made an issue about it lol. Thank you for your help!
