### ISSUE TITLE
Smart chunk-load speed

### ISSUE THREAD

**Issue by i-LOVE-cplusplus** [jellysquid3/Sodium#1272]
Sodium make it considerable to play the latest version of Minecraft on my old PC.
I notice that when I am running fast in the game, and new chunks begin to being loaded into the game, my fps go from 60 to 34.
I think reduce the chunk loading speed can help the fps to go up when travelling in MC, like OptiFine.
If someone add an option and allow players to control how slow the chunk is being loaded when moving, and how fast it is when standing still, I would be very appreciate.

**Comment by offbeat-stuff** [comment]
Maybe the fps goes down because generating chunks takes a lot of processing.
Maybe use starlight for shorter hiccups

**Comment by Felix14-v2** [comment]
> use starlight for shorter hiccups

as well as C2ME

**Comment by MeeniMc** [comment]
You can change the 'chunk update threads' in the 'performance' tab of  Sodium options.

Auto will pick something that makes sense for your particular CPU, but you can set it to a low value to favor frametime stability at the expense of slow chunk building, or high (e.g. number of cores-1) if you prefer avoiding flying in an empty map at the expense of some low fps periods while loading. 

Out of topic for Sodium, but you can also use a mod like Chunky to pregenerate the map, that helps greatly when playing with a slow CPU.

**Comment by Felix14-v2** [comment]
> mod like Chunky

Chunky is great, but it can't automatically pregenerate terrain relative to the player's position.

**Comment by MeeniMc** [comment]
conversation completed. Can be closed.
