### ISSUE TITLE
[Feature Request] Please consider adding an option to remove block-breaking particles

### ISSUE THREAD

**Issue by Zorock666** [jellysquid3/Sodium#1275]
**Is your feature request related to a problem? Please describe.**
When insta-mining blocks in Minecraft, there's a lot of noise on the screen from block-breaking particles (image attached below). I believe these particles also take some performance, albeit very little.
It would be nice to have an option to turn these particles off, like all other particles in Minecraft. Why mojang doesn't allow an option for this is beyond my understanding. Please consider it?

**Describe the solution you'd like**
An in-game settings option if possible.

**Describe alternatives you've considered**
There was a resourcepack once that worked for this, but it no longer works.
I believe there's also a (very) out of date mod that allowed to do this.
It would just be nice to see in this performance mod ^^

**Additional context**
Lots of noise when insta-mining. Can't see a thing...
![2022-04-16_01 57 26](https://user-images.githubusercontent.com/38118045/163653549-fff4e496-c8f6-47a7-902f-92c0283fb442.png)

**Comment by offbeat-stuff** [comment]
Use sodium-extras it already has that feature

**Comment by Zorock666** [comment]
oohhh, yes, that works, thank you :D
