### ISSUE TITLE
Re-add Renderer Change

### ISSUE THREAD

**Issue by KennyDevT** [jellysquid3/Sodium#1276]
**Is your feature request related to a problem? Please describe.**
Yes, For some reason Minecraft switches automatically to Open GL 3.2 And is causing a lot of Lag (yes i checked if it was a driver issue its not, it says my driver is compatible with 4.6)

**Describe the solution you'd like**
Just to re-add the ability to change the renderer

**Comment by jellysquid3** [comment]
No, it's not causing lag, and there is no issue. Minecraft only asks for a *minimum* of OpenGL 3.2, hence why the graphics driver reports it using OpenGL 3.2. The game can still use features from OpenGL 4.6 if the driver supports it.
