### ISSUE TITLE
Sodium mod Lags

### ISSUE THREAD

**Issue by Dev421** [jellysquid3/Sodium#1277]
### Version information

mc1.18.2-0.4.1+build15

### Expected Behavior

I saw from YouTube that sodium is better than optifine so I installed it expecting for better fps

### Actual Behavior

For once it actually boosted my fps but whenever I move/sprint or move my camera is just start to give lag suuden fps drops make is so bad.

### Reproduction Steps

Idk how to do it i can provide my system info

### Java version

Java 17.0.1

### CPU

AMD Ryzen 3 3300u

### GPU

Radeon Vega 6

### Additional information

![IMG_20220419_204914](https://user-images.githubusercontent.com/91951341/164038173-275f8c1b-526e-4a1b-8a7d-5ad20512053b.jpg)
![IMG_20220419_205105](https://user-images.githubusercontent.com/91951341/164038830-ecd9aea5-bdd2-47f9-89c8-49095b88c205.jpg)

For others it works fine but my system have issue pls help me i too want to boost my fps

**Comment by jellysquid3** [comment]
Per changes in policy on our issue tracker, we are closing issues which are general inquiries about performance issues and such. If you are experiencing performance issues and need help, then please use the [Discord server](https://caffeinemc.net/discord).
