### ISSUE TITLE
Extend maximum render distance past 32 chunks

### ISSUE THREAD

**Issue by realchonk** [jellysquid3/Sodium#1279]
**Is your feature request related to a problem? Please describe.**
I tried extending the maximum render distance in multiple ways, but it keeps resetting itself to 32.
I tried editing the options.txt and I tried patching it myself (See below).

**Describe the solution you'd like**
I'd like the maximum render distance to be more than 32 (maybe 64?).

**Describe alternatives you've considered**
None.

**Additional context**
For some reason GitHub doesn't allow .patch files, therefore the .txt extension.
[0001-Increase-maximum-render-distance.patch.txt](https://github.com/CaffeineMC/sodium-fabric/files/8525164/0001-Increase-maximum-render-distance.patch.txt)

**Comment by jellysquid3** [comment]
The game server only supports view distances up to 32 (+1) chunks. This is a hard-coded limit, and telling the client to use a higher render distance will not work. 

Per `ThreadedAnvilChunkManager.setViewDistance(int)`...
```java
//...
	protected void setViewDistance(int watchDistance) {
		int i = MathHelper.clamp(watchDistance + 1, 3, 33);
//...
```

**Comment by RokeJulianLockhart** [comment]
> https://github.com/CaffeineMC/sodium-fabric/issues/1279#issuecomment-1104435807

@jellysquid3, is `ThreadedAnvilChunkManager.setViewDistance(int)` part of the MC codebase (if so, did you get it from the `.jar` itself) or is that a function in Sodium? I hope you don't mind me asking here - anywhere else, it would be strange to.

**Comment by douira** [comment]
It's part of Minecraft's server code.
