### ISSUE TITLE
Stained glass panes behind other stained glass panes can cause the back panes not to render

### ISSUE THREAD

**Issue by ntoskrnl4** [jellysquid3/Sodium#128]
### Expected Behavior
All stained glass panes that are rendered behind other stained glass panes should render.

### Actual Behavior
Depending on the viewing angle, sometimes stained glass panes behind other stained glass panes may not render.

### Reproduction Steps
1. Place some stained glass panes down in some fashion.
2. Move around the glass in different positions and camera orientations until some of the back ones don't render.

### System Information
- Java Version: OpenJDK 14.0.1; the bug exhibits itself with the standard 1.8.0_51 version as well.
- CPU: AMD FX-6300
- GPU: GTX 1070; driver 432.00

### Screenshots and testing
- [Where I first noticed the bug](https://cdn.discordapp.com/attachments/504486947146694668/734919103894126733/unknown.png)
- [Another example](https://cdn.discordapp.com/attachments/504486947146694668/734919296735641710/unknown.png)
- [The bug does not depend on the OpenGL API version](https://cdn.discordapp.com/attachments/504486947146694668/734919512335319091/unknown.png)
- [The vanilla game, and removing Sodium render it fine](https://cdn.discordapp.com/attachments/504486947146694668/734922570784047194/unknown.png)
- [Java version doesn't matter (notice this screenshot is taken with the default version)](https://cdn.discordapp.com/attachments/504486947146694668/734927901878911000/unknown.png)
- [Regular glass panes are not affected](https://cdn.discordapp.com/attachments/504486947146694668/734928951247503460/unknown.png)
- [Any stained glass panes trigger this bug, and the bends in the glass shapes above don't matter](https://cdn.discordapp.com/attachments/504486947146694668/734929782285795422/unknown.png)

If you need any more details let me know and I can provide them as well.

And thank you so much for your hard work with this mod, it takes the game from ~25 fps on "low" settings (for my hardware) to 150+ fps with max settings :) It's such an improvement, it takes it back to beyond 1.8/1.12 performance.

**Comment by Kroppeb** [comment]
See pinned issue #38 
This will be fixed in version 0.2

**Comment by ntoskrnl4** [comment]
Oh! My bad, I didn't see this was already an issue (it just had a different name).
