### ISSUE TITLE
Animation Distance slider

### ISSUE THREAD

**Issue by GameParrot** [jellysquid3/Sodium#1280]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
A slider to allow for animated textures farther than a certain distance (in chunks, like render and sim distance) to not be animated.

**Describe alternatives you've considered**
Don't animate textures more than 16 chunks from the player

**Additional context**
It could improve performance on high render distances if you could have a 32 render distance, but only animate textures within 16 chunks for example.

**Comment by jellysquid3** [comment]
Have you determined that animated textures are still a source of slowness in Sodium? We already disable animated textures where they can't be seen, which generally makes this a non-issue.

**Comment by GameParrot** [comment]
It could probably improve performance a little on a 32 chunk render distance. A lot of fire can definitely create lag.

**Comment by MeeniMc** [comment]
duplicate of #741
