### ISSUE TITLE
Sodium Rendering Issue 

### ISSUE THREAD

**Issue by Alkemystix** [jellysquid3/Sodium#1281]
### Version information

Sodium 1.18.2 v.0.13.3

### Expected Behavior

When rendering, usually the textures further away look fine and clear. I'm told this can be changed by altering the mipmap levels

### Actual Behavior

When rendering textures, especially further away, they appear very 'grainy' and pixellated. I'm not sure if this is standard with sodium mod or a bug, hence why I'm looking here for answers! I've attached images of what blocks look like, the settings I have at the moment, and the mods I have enabled. I've tried increasing and decreasing mipmap levels to no difference, as well as all the other settings. This is only an issue with sodium, when I revert back to optifine or vanilla it functions properly

Thanks!

### Reproduction Steps

n/a

### Java version

17.0.1 64Bit

### CPU

Intel Core i3-10100F

### GPU

NVIDIA GT 1030

### Additional information

![2022-04-21_15 49 17](https://user-images.githubusercontent.com/104152578/164485079-013fdf53-1f10-4606-b281-f578a162c5e9.png)
![2022-04-21_15 49 20](https://user-images.githubusercontent.com/104152578/164485084-f50b5f91-aac1-48e3-a615-e63f13743af6.png)
![2022-04-21_15 49 51](https://user-images.githubusercontent.com/104152578/164485091-249ebeed-58e1-4d7a-a902-e446fc48e10e.png)
![2022-04-21_15 39 58](https://user-images.githubusercontent.com/104152578/164484695-face4a73-ebad-4487-ab2e-d056882c4cdd.png)
![2022-04-21_15 40 02](https://user-images.githubusercontent.com/104152578/164484697-f91d8e43-0e0f-436b-8447-93b3649ec875.png)
![asdasfadqagsdgf](https://user-images.githubusercontent.com/104152578/164484704-b11502fc-0d6b-49ab-b2c6-8d8afe17b8fa.png)

**Comment by jellysquid3** [comment]
Can you upload a client log file? Another mod you have installed is likely including broken textures, which causes Minecraft to disable mip-mapping entirely, even if you have it enabled in your video settings.

**Comment by Alkemystix** [comment]
Log file is here:
[Log File 23.04.2022.log](https://github.com/CaffeineMC/sodium-fabric/files/8547030/Log.File.23.04.2022.log)

**Comment by Busccccc** [comment]
i had the same problem with the playlist minecraft mod fucking my graphic, remove it and its fine

**Comment by jellysquid3** [comment]
This is a problem with some mod or resource pack which is providing textures that are not a power of two in size. Nothing we can do to fix it.
