### ISSUE TITLE
Bleeding edge GitHub builds aren't being uploaded.

### ISSUE THREAD

**Issue by Xenthio** [jellysquid3/Sodium#1283]
https://github.com/CaffeineMC/sodium-fabric/actions/runs/2158301115
GitHub Actions builds are bugged
![image](https://user-images.githubusercontent.com/28588188/165009495-126dd61a-5d6f-49f8-9bb9-26f2540dfab2.png)
affects the 1.18.x/next branch

**Comment by Blobanium** [comment]
Having the same issue here
