### ISSUE TITLE
game crashing upon nether entry

### ISSUE THREAD

**Issue by sh4kyh4nds** [jellysquid3/Sodium#1284]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Reproduction Steps

With all of the matching mods I have installed, enter a nether portal, and the game crashes.

### Crash Report file

[crash-2022-04-25_21.17.57-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8561135/crash-2022-04-25_21.17.57-client.txt)

### Additional information

![image](https://user-images.githubusercontent.com/99229835/165254494-91382b3b-560f-4d4e-8496-1a5d1c550389.png)

**Comment by MeeniMc** [comment]
Looks like there is a problem with your shader, does it work with another shader? You may want to consider raising the issue with Iris, if the problem is not specific to that particular shader.

**Comment by jellysquid3** [comment]
Not a problem with Sodium, the crash is from Iris, which isn't our mod.
