### ISSUE TITLE
Crash when launching in Quilt envionment

### ISSUE THREAD

**Issue by GhostIsBeHere** [jellysquid3/Sodium#1285]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

1. Create a new Quilt instance
2. Install Quilt Standard Libraries
3. Install Sodium
4. Launch Game
5. Crash

### Crash Report file

[crash-2022-04-26_12.50.18-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8566435/crash-2022-04-26_12.50.18-client.txt)

### Additional information

Full ATLauncher log: [https://paste.atlauncher.com/view/be67d401-65e8-4a7f-a9d4-a6ee648b8ab8](https://paste.atlauncher.com/view/be67d401-65e8-4a7f-a9d4-a6ee648b8ab8)
Crashes with and without Indium/other mods

**Comment by jellysquid3** [comment]
I don't really know what Quilt is doing, and the crash log doesn't make sense to me. Does it work _without_ Sodium installed?

**Comment by GhostIsBeHere** [comment]
No. I didn't even think to check that lol. I'll close this and make an issue on the Quilt github
