### ISSUE TITLE
Underwater Grid

### ISSUE THREAD

**Issue by Sulrwin** [jellysquid3/Sodium#1286]
### Version information

mc1.18.2-0.4.1

### Expected Behavior

To see ice under the water.
![image](https://user-images.githubusercontent.com/44132594/165391627-75ed7e9e-5cf9-4969-8293-b1ac1a527af7.png)

### Actual Behavior

I can't see the ice also there is this weird grid.
![image](https://user-images.githubusercontent.com/44132594/165391455-26ec57e9-4d3c-45d7-b4e5-08dec1042a5e.png)

### Reproduction Steps

Load only FabricAPI 0.51.1 and Sodium 0.4.1
I guess if you have an Nvidia card use my global settings?
Look under water

### Java version

Java 17

### CPU

Intel Core i9-9900K

### GPU

Nvidia GTX 2070

### Additional information

![image](https://user-images.githubusercontent.com/44132594/165392099-a3db690f-b508-4e8b-98c1-e7a9716b3835.png)
![image](https://user-images.githubusercontent.com/44132594/165392190-fc521071-139f-460a-a63d-a08602ba5eca.png)
![image](https://user-images.githubusercontent.com/44132594/165392217-aa3dfc18-7586-4f54-852b-aaaa7933c01f.png)
![image](https://user-images.githubusercontent.com/44132594/165392240-d08958ff-3419-435b-b89e-c93029d056e1.png)
I've never reported anything in my 21 years of life so let me know if you need anymore information.

**Comment by Vovan-VE** [comment]
#38 gathers all of similar issues.

**Comment by alvinqwq** [comment]
same

**Comment by Neposis** [comment]
Same here

**Comment by pajicadvance** [comment]
As mentioned above, reports of this issue should be posted in #38.
