### ISSUE TITLE
UI problem when 'Reduce Resolution on macOS' is disabled

### ISSUE THREAD

**Issue by Algalish** [jellysquid3/Sodium#1287]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Expected Behavior

correct UI to be shown like this.
<img width="2231" alt="Снимок экрана 2022-04-27 в 13 55 27" src="https://user-images.githubusercontent.com/1682176/165460195-127a289f-4a20-479e-9056-cb17052c4be1.png">

### Actual Behavior

<img width="763" alt="Снимок экрана 2022-04-27 в 13 59 23" src="https://user-images.githubusercontent.com/1682176/165460597-70232ac1-80d4-4378-8c87-4cdac0237d42.png">

### Reproduction Steps

Open 'Video Settings' when 'Reduce Resolution on macOS' is disabled and you'll see this.
If GUI scale was set to 4 then you will see only a black screen. Above screenshot is when GUI scale is set to AUTO

### Java version

Java 18

### CPU

Apple M1 Max

### GPU

Apple M1 Max

**Comment by FlashyReese** [comment]
This is unrelated to Sodium, but rather, Sodium Extra & Reese's Sodium Options. This might be occurring because the game wasn't restarted when changing `Reduce Resolution on macOS`.

**Comment by Algalish** [comment]
> This is unrelated to Sodium, but rather, Sodium Extra & Reese's Sodium Options. This might be occurring because the game wasn't restarted when changing `Reduce Resolution on macOS`.

Actually its the other way around - when I change the setting and restart the game - then the GUI is permanently broken. So I needed to go to config file manually and change that back in order to change anything in 'Video Settings'

**Comment by jellysquid3** [comment]
Either way, the bug is with another mod here, not our own... so I'm going to go ahead and close this issue.
