### ISSUE TITLE
1.18.2 (Sodium Build 15) - Sodium Crashes When Rendering A Head/Skull Block Entity

### ISSUE THREAD

**Issue by BlidBear** [jellysquid3/Sodium#1288]
### Version information

mc1.18.2-0.4.1+build.15

### Reproduction Steps

1. Place a mob head (Skeleton, Wither Skeleton, Zombie, Creeper, Dragon, etc...)
2. Sodium fails to render
3. Game crashes

### Crash Report file

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 27/4/22 5:24
Description: Rendering Block Entity

java.lang.NoSuchMethodError: 'double net.minecraft.class_2338.method_10268(double, double, double, boolean)'
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at net.minecraft.client.render.block.entity.SkullBlockEntityRenderer.handler$dic000$render(SkullBlockEntityRenderer:535)
	at net.minecraft.client.render.block.entity.SkullBlockEntityRenderer.render(SkullBlockEntityRenderer)
	at net.minecraft.client.render.block.entity.SkullBlockEntityRenderer.render(SkullBlockEntityRenderer:32)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:84)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.method_23081(BlockEntityRenderDispatcher:73)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.runReported(BlockEntityRenderDispatcher:98)
	at net.minecraft.client.render.block.entity.BlockEntityRenderDispatcher.render(BlockEntityRenderDispatcher:73)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.client.render.WorldRenderer.handler$djl000$onRenderTileEntities(WorldRenderer:15293)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1359)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1034)
	at net.minecraft.client.render.GameRenderer.redirect$bpa000$redirectRenderingWorld(GameRenderer:4134)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:813)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_836.handler$dic000$render(class_836.java:535)
	at net.minecraft.class_836.method_3577(class_836.java)
	at net.minecraft.class_836.method_3569(class_836.java:32)
	at net.minecraft.class_824.method_23079(class_824.java:84)
	at net.minecraft.class_824.method_23081(class_824.java:73)
	at net.minecraft.class_824.method_3554(class_824.java:98)
	at net.minecraft.class_824.method_3555(class_824.java:73)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.class_761.handler$djl000$onRenderTileEntities(class_761.java:15293)
	at net.minecraft.class_761.method_22710(class_761.java:1359)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.redirect$bpa000$redirectRenderingWorld(class_757.java:4134)

-- Block Entity Details --
Details:
	Name: minecraft:skull // net.minecraft.class_2631
	Block: Block{minecraft:wither_skeleton_skull}[rotation=0]
	Block location: World: (-357,72,-535), Section: (at 11,8,9 in -23,4,-34; chunk contains blocks -368,-64,-544 to -353,319,-529), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
	Block: Block{minecraft:wither_skeleton_skull}[rotation=0]
	Block location: World: (-357,72,-535), Section: (at 11,8,9 in -23,4,-34; chunk contains blocks -368,-64,-544 to -353,319,-529), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
	Block Entity NBT: {}
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:98)
	at net.minecraft.class_824.method_3555(class_824.java:73)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:281)
	at net.minecraft.class_761.handler$djl000$onRenderTileEntities(class_761.java:15293)
	at net.minecraft.class_761.method_22710(class_761.java:1359)
	at net.minecraft.class_757.method_3188(class_757.java:1034)
	at net.minecraft.class_757.redirect$bpa000$redirectRenderingWorld(class_757.java:4134)
	at net.minecraft.class_757.method_3192(class_757.java:813)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['REDACTED'/128, l='ClientWorld minecraft:overworld', x=-356.68, y=72.00, z=-537.87]]
	Chunk stats: Client Chunks (ImmPtl) 416
	Level dimension: minecraft:overworld
	Level spawn location: World: (-304,73,-528), Section: (at 0,9,0 in -19,4,-33; chunk contains blocks -304,-64,-528 to -289,319,-513), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,-64,-1024 to -1,319,-513)
	Level time: 385 game time, 385 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, GENERAL Reimagined 3D.zip, BLOCKS Torches.zip, BLOCKS Ladders.zip, BLOCKS Portal Frame.zip, BLOCKS Crafting Table.zip, BLOCKS Beds.zip, BLOCKS Bedrock.zip, BLOCKS Crop.zip, BLOCKS Ender Chest.zip, BLOCKS Redstone.zip, BLOCKS Rails Reimagined.zip, BLOCKS Wood.zip, BLOCKS Beacon.zip, ITEM Armor.zip, OTHER Reimagined Colormap Fix.zip, OTHER Sounds.zip, UI Dark Mode.zip, UI Roman Numerals.zip, UI Font.zip, UI Texts.zip, ENVIRONMENT Music Discs.zip, ENVIRONMENT Rain.zip, ENVIRONMENT Sun and Moon.zip, MOB Chickens.zip, MOB Bees.zip, ITEM Blaze Rod.zip, MOB Armorstands.zip, MOB Cows.zip, MOB Foxes.zip, ENVIRONMENT.zip, MOB Ghasts.zip, MOB Paintings.zip, MOB Piglin Brute.zip, MOB Pigs.zip, MOB Pufferfish.zip, MOB Sheeps.zip, MOB Shulkers.zip, ITEM Fish.zip, Blue Storm Enchant Glint.zip, Fabric Mods, loadmyresources.hiddenpack, continuity/default, continuity/glass_pane_culling_fix, UI Icons.zip, Brewing+Guide.zip, charmonium/journeyman, VanillaTweaks_r916594.zip, Resdt2.zip, slightly-vanilla-enderman.zip, DSWG+Better+Compass+1.18.zip, weird-totem.zip, Essential (fabric_1.18.2).jar

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 877639680 bytes (836 MiB) / 2919235584 bytes (2784 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3,00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1259
	Memory slot #0 capacity (MB): 16384,00
	Memory slot #0 clockSpeed (GHz): 2,13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 43366,64
	Virtual memory used (MB): 22541,21
	Swap memory total (MB): 10752,00
	Swap memory used (MB): 35,44
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.7
		ambientenvironment: Ambient Environment 7.0+17
		amplified-nether: Amplified Nether 1.1
		appleskin: AppleSkin 2.3.0+mc1.18.1
		axesareweapons: Axes Are Weapons 1.5.1
		bclib: BCLib 1.4.3
		betterend: Better End 1.1.0
		bettermounthud: Better Mount HUD 1.1.4
		bettertaskbar: Better Taskbar 1.1
		blur: Blur (Fabric) 2.4.1
		bobby: Bobby 3.1.1
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cauldronlib: Cauldronlib 1.2.2
		cavedust: Cave Dust 1.2.0
		cem: Custom Entity Models 0.7.0
		charmonium: Charmonium 4.0.0
		chat_heads: Chat Heads 0.6.0
		chunkcopy: Chunk Copy 2.1.1
		citresewn: CITResewn 0.9.1+1.18.1
		cleardespawn: Clear Despawn 21w40a-1.1.3
		clickthrough: ClickThrough 1.18.2-fabric0.47.10-0.4
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		collective-fabric: Collective (Fabric) 3.14
		colormatic: Colormatic 3.1.1+mc.1.18.2
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_github_ramanrajarathinam_native-utils: native-utils 1.0.0
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		completeconfig: CompleteConfig 1.3.3
		continuity: Continuity 1.1.0+1.18.2
		crawl: Crawl 0.10.2
		creeperaiupdated: Creeper AI Updated 1.5.1
		crowdin-translate: CrowdinTranslate 1.4+1.18.2
		damagetilt: Damage Tilt 1.18-fabric-0.1.2
		dashloader: DashLoader 3.0.1+1.18
		dcch: DCCH 2.0+1.17
		debugify: Debugify 1.2.2
		detailab: Detail Armor Bar 2.6.2+1.18-fabric
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.3.0
		dev_quantumfusion_hyphen: hyphen 0.2.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		doubledoors-fabric: Double Doors (Fabric) 3.1
		drippyloadingscreen: Drippy Loading Screen 1.4.2
		effective: Effective 1.2.1
		enchdesc: EnchantmentDescriptions 9.0.11
		essential: Essential 2666
		essential-container: essential-container 1.0.0
		essential-loader: essential-loader 1.0.0
		expanded_trident_enchanting: Expanded Trident Enchanting 1.0.3
		extrasounds: Extra Sounds 2.2.1+1.18.2
		fabric: Fabric API 0.48.0+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.7+d7c144a860
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.3+801ec85b60
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.2+d82b939260
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.13+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.3.3+691a79b560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.10+3ac43d9560
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.1+kotlin.1.6.10
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.2+2540745460
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.0.4+d1027f7d60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.0.3+40c91ec860
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.17+d8c7b9ae60
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.2+d1027f7d60
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.14+40c91ec860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.14+cca23f9360
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+40c91ec860
		fabrichomes: FabricHomes 2.2.1
		fabricloader: Fabric Loader 0.13.3
		fallingleaves: Falling Leaves 1.10.0+1.18.2
		fancymenu: FancyMenu 2.5.2
		ferritecore: FerriteCore 4.2.0
		fiber: fiber 0.23.0-2
		firstperson: FirstpersonModel 2.1.0
		forgeconfigapiport: Forge Config API Port 3.2.0
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.35
		goosik-config: goosik-config 0.2.0
		grindenchantments: Grind Enchantments 1.6.1+1.18.2
		guicompass-fabric: GUI Compass (Fabric) 1.8
		horsebuff: HorseBuff 1.2.3
		iceberg: Iceberg 1.0.38
		imm_ptl_core: Immersive Portals Core 1.3.6
		immersive_portals: Immersive Portals 1.3.6
		indium: Indium 1.0.2+mc1.18.2
		infinitywaterbucket: Infinity Water Bucket 2.0.0
		invisframes: Invisible Frames 2.1.1
		invmove: InvMove 0.6.2
		io_github_imurx_arboard: arboard 1.0.2
		io_leangen_geantyref_geantyref: geantyref 1.3.13
		iris: Iris 1.2.2-build.32
		java: OpenJDK 64-Bit Server VM 17
		kirin: Kirin UI 1.10.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.1.9
		leaves_us_in_peace: Leaves Us In Peace 1.0.4
		legendarytooltips: Legendary Tooltips 1.2.4
		libraryferret: Library Ferret 1.0.3
		lightlevel: Light Level 3.0.0
		lithium: Lithium 0.7.9
		loadmyresources: Load My Resources 1.0.1
		logical_zoom: Logical Zoom 0.0.14
		make_bubbles_pop: Make Bubbles Pop Mod 0.0.1-1.18.2
		malilib: MaLiLib 0.11.6
		mambience: MAmbience 5.0.0+1.18.2
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.1.0
		monsters_in_the_closet: Monsters in the Closet 1.0.3+1.18
		morebannerfeatures: More Banner Features 1.1.3
		nameless_servers: Nameless Servers 1.0.0+1.17
		nethermap: Better Nether Map 2.0.2-1.18.2
		neutral_animals: Neutral Animals 1.2.0
		notenoughanimations: NotEnoughAnimations 1.4.0
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.2
		notes: Notes 1.0.10
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.10
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.10
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_joml_joml: joml 1.10.2
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		paxi: Paxi 1.18.2-Fabric-2.0
		perfectaccuracy: Perfect Accuracy 1.2
		phosphor: Phosphor 0.8.1
		pickupnotifier: Pick Up Notifier 3.1.0
		placeholder-api: Placeholder API 1.1.3+1.17.1
		plasmo_voice: Plasmo Voice 1.2.11
		presencefootsteps: Presence Footsteps 1.5.0
		profundis: Profundis 1.2.1
		puzzleslib: Puzzles Lib 3.3.1
		q_misc_util: QMiscUtil 1.3.6
		quicksand: Quicksand 1.1.0
		renameit: RenameIt 1.1.0
		resetchunks: resetchunks 1.0.0
		sakurablossoms: Sakura Blossoms 1.0.2
		satin: Satin 1.7.0
		screencopy: Screencopy 1.0.0
		secondchance: Second Chance 1.3.0
		server-hats: Server Hats 0.9
		server_translations_api: Server Translations API 1.4.10+1.18.2
		skinlayers: 3d Skin Layers 1.3.1
		sleepwarp: SleepWarp 1.1.1+1.18.2
		smoothswapping: Smooth Swapping 0.4.4
		smwyg: Show Me What You Got 1.0.1
		sneakycurses: Sneaky Curses 3.0.0
		sodium: Sodium 0.4.1+build.15
		sound_physics_remastered: Sound Physics Remastered 1.18.2-1.0.4
		soundcategories: Sound Categories 1.2.1+1.18
		subterrestrial: Subterrestrial 1.0.2
		thorium: thorium 1.0.0
		tlcosmetica: Cosmetica 0.4.0
		visuality: Visuality 0.4.2
		waterdripsound: Drip Sounds 1.18-0.3.0
		whats_that_slot: What's That Slot? 1.2.3+1.18.1
		whyamionfire: Why Am I on Fire? 1.1.2
		wildlife: Wildlife 1.18.2-1.0
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.7
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.59, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/GENERAL Reimagined 3D.zip (incompatible), file/BLOCKS Torches.zip (incompatible), file/BLOCKS Ladders.zip (incompatible), file/BLOCKS Portal Frame.zip (incompatible), file/BLOCKS Crafting Table.zip (incompatible), file/BLOCKS Beds.zip (incompatible), file/BLOCKS Bedrock.zip (incompatible), file/BLOCKS Crop.zip (incompatible), file/BLOCKS Ender Chest.zip (incompatible), file/BLOCKS Redstone.zip (incompatible), file/BLOCKS Rails Reimagined.zip (incompatible), file/BLOCKS Wood.zip, file/BLOCKS Beacon.zip, file/ITEM Armor.zip (incompatible), file/OTHER Reimagined Colormap Fix.zip (incompatible), file/OTHER Sounds.zip (incompatible), file/UI Dark Mode.zip (incompatible), file/UI Roman Numerals.zip (incompatible), file/UI Font.zip (incompatible), file/UI Texts.zip (incompatible), file/ENVIRONMENT Music Discs.zip (incompatible), file/ENVIRONMENT Rain.zip (incompatible), file/ENVIRONMENT Sun and Moon.zip, file/MOB Chickens.zip, file/MOB Bees.zip (incompatible), file/ITEM Blaze Rod.zip (incompatible), file/MOB Armorstands.zip (incompatible), file/MOB Cows.zip, file/MOB Foxes.zip (incompatible), file/ENVIRONMENT.zip (incompatible), file/MOB Ghasts.zip, file/MOB Paintings.zip (incompatible), file/MOB Piglin Brute.zip (incompatible), file/MOB Pigs.zip, file/MOB Pufferfish.zip (incompatible), file/MOB Sheeps.zip (incompatible), file/MOB Shulkers.zip (incompatible), file/ITEM Fish.zip (incompatible), file/Blue Storm Enchant Glint.zip, Fabric Mods, loadmyresources.hiddenpack, continuity/default, continuity/glass_pane_culling_fix, file/UI Icons.zip (incompatible), file/Brewing+Guide.zip, charmonium/journeyman, file/VanillaTweaks_r916594.zip, file/Resdt2.zip (incompatible), file/slightly-vanilla-enderman.zip, file/DSWG+Better+Compass+1.18.zip, file/weird-totem.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['REDACTED'/128, l='ServerWorld minecraft:overworld New Worldjghvjv', x=-356.68, y=72.00, z=-537.87]]
	Data Packs: vanilla, DropLadder.zip (incompatible), afk display v1.1.2.zip, anti enderman grief v1.1.2.zip, anti ghast grief v1.1.2.zip, armored elytra v1.0.5.zip, cauldron concrete v2.0.5.zip, graves v2.8.5.zip, larger phantoms v1.2.3.zip, loadmyresources.hiddenpack (incompatible), multiplayer sleep v2.6.2.zip, spectator conduit power v1.1.2.zip, spectator night vision v1.1.2.zip, timber v2.1.4.zip, unlock all recipes v2.0.3.zip, xp management v1.1.2.zip, Fabric Mods
	World Generation: Experimental
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Sodium (sodium)

**Comment by jellysquid3** [comment]
This crash isn't caused by Sodium. You have other out-of-date mods installed... probably "3D Skin Layers" is at fault given what I could find from a [code search](https://github.com/tr7zw/3d-Skin-Layers/blob/1.17/3dSkinLayers-Shared/src/main/java/dev/tr7zw/skinlayers/mixin/SkullBlockEntityRendererMixin.java#L36). Check to see if any updates are available, otherwise wait for the mod to be updated.
