### ISSUE TITLE
Github compiled version not culling properly?

### ISSUE THREAD

**Issue by OS-Void** [jellysquid3/Sodium#129]
### Expected Behavior
Render debug "C" are nearly at 3000, when usually hangs at 900-1200

### Actual Behavior
My FPS is suffering seems like "C" (chunks rendered) are 3x than the version in CurseForge

### Attachments
Github Compile: 
![2020-07-20_01 36 27](https://user-images.githubusercontent.com/5094754/88004626-69cb5700-cad5-11ea-994b-497a0c9b49c1.png)

CurseForge:
![2020-07-20_01 39 28](https://user-images.githubusercontent.com/5094754/88004523-2c66c980-cad5-11ea-85be-65cb4931a9f3.png)

### System Information

- Java Version: Java 14 64bit
- CPU: i7 8700K
- GPU: RTX 2080 Ti

**Comment by Miros77** [comment]
what kind of program?

**Comment by mrmangohands** [comment]
I think this is from the abandoned 1.16.x/dev branch, in any case very stale and not relevant to current development.
