### ISSUE TITLE
Better foliage features prevented from working when sodium is installed with it?

### ISSUE THREAD

**Issue by StockiesLad** [jellysquid3/Sodium#1294]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

I wanted to use better foliage with sodium, but sodium seems to completely interrupt some of its features. 

### Actual Behavior

With Sodium:
No round logs
Connected Grass textures
No Coral
No Reeds
No Algae
No netherrack vines

With Indium & Sodium:
No round logs
No Coral
Connected Grass textures Grey
Leaves not getting culled if surrounded by other blocks

As you can see, indium does fix a lot of these but I couldn't submit any issues there so I am doing it here...

### Reproduction Steps

1. Download Sodium (the version mentioned above), this  version of better foliage
https://github.com/LoganDark/BetterFoliage/releases/download/1.18.2-Fabric-2.6.6/BetterFoliage-2.6.6+77e8dcf-Fabric-1.18.2.jar,
Fabric 0.14.3, FAPI 0.51.1
2. Run
3. Go into a world and see.

### Java version

Java 17

### CPU

Ryzen 5 2600

### GPU

Gtx 1660ti

### Additional information

https://github.com/octarine-noise/BetterFoliage/pull/428
Here is the source!

**Comment by MeeniMc** [comment]
This is a mod compat issue, the mod apparently does it's own rendering for some things. Mod is not maintained anymore.
