### ISSUE TITLE
Game crash 

### ISSUE THREAD

**Issue by VanillaCqke** [jellysquid3/Sodium#1297]
### Version information

sodium-fabric-mc1.18-0.4.0-alpha5+build.9

### Reproduction Steps

1. place latest sodium in mods folder (with and without api)
2. launch game
3. crash before window opens

### Crash Report file

it does not produce a crash report
![image](https://user-images.githubusercontent.com/37249584/167062925-07944277-05c6-43af-b9ed-7d44aec56733.png)

### Additional information

I have the most recent version of java, and this only happens with the mod sodium phosphor and lithium both work fine

**Comment by amnotbananaama** [comment]
Does this crash occur with 0.4.1?

**Comment by VanillaCqke** [comment]
> Does this crash occur with 0.4.1?
yes

**Comment by MeeniMc** [comment]
not enough info to help, stale
