### ISSUE TITLE
Lower fps when not using shaders , higher fps when using shaders.

### ISSUE THREAD

**Issue by Thspooks** [jellysquid3/Sodium#1298]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

I expected sodium to optimize my game, to make it a bit smoother.
### Actual Behavior

AS title says, with sodium im having low fps when not using shaders. Im having iris, and when im turning shaders on it works much better than without shaders.  I can provide more info if needed.
Providing my modlist in case. https://pastebin.com/SwCBdtRU
### Reproduction Steps

Simply installing sodium and iris, then applying shaders to compare.

### Java version

java 17 

### CPU

i3-8100

### GPU

gtx 1050

**Comment by Thspooks** [comment]
bruh, no one ?

**Comment by StockiesLad** [comment]
Jellysquid quit modding...

**Comment by StockiesLad** [comment]
Try updating ur graphics drivers to the latest

**Comment by StockiesLad** [comment]
If the issue still persists, I'd recommend playing with the settings. Including nvidia settings to make sure vsync isn't being funny

**Comment by IMS212** [comment]
Issue pertains to Iris, closing as invalid.
