### ISSUE TITLE
Incompatibility with OptiFabric

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#13]
fabric just says that sodium breaks OptiFabric (but I'm pretty sure it can't be fixed since OptiFine and sodium change the renderer).
Thanks for your time making this amazing mod,
have a nice day.

**Comment by Heitzenberg** [comment]
You have to choose: Sodium OR Optifine, can't use both. I'd recommend Sodium of course.

**Comment by amnotbananaama** [comment]
Very clearly intended behavior, see https://github.com/jellysquid3/sodium-fabric/commit/f1d76441e2d671044d62da169e96aee4c5822dad. You're welcome to comment out that code but you won't get any technical support for what comes next. 

Is there a reason you are trying to run two different rendering mods? What features are you looking for from OptiFine. It's very likely that someone will be making a stand-alone mod that includes them.

**Comment by Nifty-Neutron** [comment]
I know...
I said that above,
just was asking.

**Comment by Nifty-Neutron** [comment]
I'll just delete the issue

**Comment by ghost** [comment]
Fast render would've been cool with sodium.

**Comment by Jarfeh** [comment]
One reason I would think of would be the ability to use shaders

**Comment by ShayBox** [comment]
Sodium is cool, but there's no way I can remove optifine, too much about it is required for me, maybe a setting or a detection of optifine to disable conflicting changes.

EDIT: Since this is basically phosphor, i'll stick to using phosphor with optifine, that and I prefer to use forge anyway.

**Comment by AMereBagatelle** [comment]
"Conflicting changes" is the hard part.  Both mods replace the same thing, and we have absolutely no idea what Optifine replaces, and therefore no idea what of Sodium's changes conflict with that.  There is logically no way to get the two to work together fully.  However, there are other mods on Fabric which replicate and/or improve on Optifine's individual features.

**Comment by lenrik1589** [comment]
> EDIT: Since this is basically phosphor...  
  
What do you mean, @ShayBox ? Sodium and Phosphor are two different mods and Phosphor only optimizes code that calculates how bright is the light at particular block is while Sodium only changes the code used to display all the blocks right way, so you can't just say "this is basically Phosphor", at least not in this context (tho you could say that if you meant that it actually is **__A__** mod).
