### ISSUE TITLE
Colored Glass Blocks Only Have Borders

### ISSUE THREAD

**Issue by DonSerrot** [jellysquid3/Sodium#130]
### Expected Behavior
Solid colored glass blocks.

### Actual Behavior
Colored glass blocks only have color on the borders.

### Reproduction Steps
Place colored glass block using build from most recent dev branch.

### Attachments
![2020-07-21_02 01 11](https://user-images.githubusercontent.com/654744/88023864-69dc4e80-caf7-11ea-9fed-593b85e09611.png)
![2020-07-21_01 59 52](https://user-images.githubusercontent.com/654744/88023869-6b0d7b80-caf7-11ea-8e52-94cce1fdbad2.png)

### System Information
- Java Version: 14.0.1 64bit
- CPU: 16x AMD Ryzen 7 1700
- GPU: GeForce GTX 970

**Comment by Kroppeb** [comment]
This and #131 might be caused by `620f5a3`?

**Comment by DonSerrot** [comment]
Most likely. The last build I compiled was on the 19th and it's been mostly README commits since then.

**Comment by jellysquid3** [comment]
Now tracked by #181.
