### ISSUE TITLE
Sodium Is Loading Invisible chunks?

### ISSUE THREAD

**Issue by Fucked3** [jellysquid3/Sodium#1300]
### Version information

1.18.1 Fabric

### Expected Behavior

I was hoping to use sodium to help with rendering and fps since opti-fabric doesn't seem to work for me.

### Actual Behavior

I loaded into my modded world prior to finding this mod and chunks were invisible and transparent, I could see grass on some loaded chunks but it was spotty all around 

### Reproduction Steps

Every time I use sodium it causes spotty load chunks that are transparent, I Checked all settings incase it was something there but nothing.
 
 I uninstalled and reinstalled to see for any changes nothing did.

I therefore reported said bug.

### Java version

Version 8 Update 333

### CPU

AMD Ryzen 5 5600X 6-Core Processor 

### GPU

Nvidia GeForce RTX 3060

### Additional information

I reinstalled took it out of mods folder solved the problems  (I do have 100 plus mods, but So far none that are already known to cause problems for sodium.

**Comment by MeeniMc** [comment]
Probably duplicate of #872

**Comment by thailangbgthainbglol-source** [comment]
just change ur uhh. Uhh .uhh I guess remove the more culling mod or just update the drivers smth?
