### ISSUE TITLE
 Method overwrite conflict

### ISSUE THREAD

**Issue by Disketaa** [jellysquid3/Sodium#1301]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

**10** second loading in Minecraft launcher.

`Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.`

![image](https://user-images.githubusercontent.com/76956762/168263920-e07f1795-e69a-464e-9368-190bc40486ed.png)

### Actual Behavior

**10** second loading in Minecraft launcher.

`Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder from mod sodium, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.`

![image](https://user-images.githubusercontent.com/76956762/168263920-e07f1795-e69a-464e-9368-190bc40486ed.png)

### Reproduction Steps

Load your minecraft

### Java version

17.0.1 64bit

### CPU

Intel(R) Pentium(R) CPU G4560 3.50GHz 4 CPUs

### GPU

Radeon RX 570 Series

**Comment by jellysquid3** [comment]
Not an issue. The log is simply saying two mods tried to modify the same code, and that only one of them won. This is expected, and is not so much a warning as it is diagnostic information.
