### ISSUE TITLE
Repeating LOD mod errors

### ISSUE THREAD

**Issue by RickGotTaken** [jellysquid3/Sodium#1303]
### Version information

DistantHorizons-1.6.3a-1.18.2.jar

### Expected Behavior

It works like normal.

### Actual Behavior

It repeatedly gave me an error.

### Reproduction Steps

1. Install version 1.6.3a of Distant Horizons.
2. Install Sodium, Mod Menu & Fabric API.
3. Launch Minecraft
4. Join a server.
5. Go to somewhere more than 32 chunks big.
6. Let the errors pile up!

### Java version

Java 17.0.1

### CPU

Intel Core i5-4590

### GPU

I don't know

### Additional information

I think tis only works on Zedar SMP
play.zedar.xyz

**Comment by NealSavage** [comment]
It basically makes my game unplayable after like 30 seconds from joining my single player world. It's a really bad bug. They gotta fix this memory leak asap
