### ISSUE TITLE
Problems in rendering clouds

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1304]
### Version information

mc1.18.2-0.4.1

### Expected Behavior

The absence of the same problems in rendering clouds as in the damn OptiFine?

### Actual Behavior

When changing the angle of view at the clouds, some kind of rendering border is observed.

### Reproduction Steps

1. Look at the clouds;
2. Slightly change the viewing angle vertically (the effect is more noticeable) or horizontally (the effect is less noticeable).

### Java version

Java 17

### CPU

Intel Core i5 3230M

### GPU

Intel HD Graphics 4000

### Additional information

![2022-05-14_22 56 24](https://user-images.githubusercontent.com/105277864/168447740-e7cca604-bdbd-4635-8ade-6134d5093aad.png)
![2022-05-14_22 56 27](https://user-images.githubusercontent.com/105277864/168447743-6586e6f9-1fe9-4083-8189-43a63698bbb3.png)
Here is a list of all the mods I play with. All mods are up to date:
![Безымянный](https://user-images.githubusercontent.com/105277864/168447790-405a3dbe-29d8-4945-a3eb-02f2a3c1a152.png)

**Comment by IMS212** [comment]
Seems like a mod issue, and account is deleted.
