### ISSUE TITLE
Option to change video settings gui to vanilla style

### ISSUE THREAD

**Issue by EltoCode** [jellysquid3/Sodium#1307]
A simple option in the config to display the new gui with the vanilla style would be nice. Just for consistency's sake.

**Comment by Ivan-Khar** [comment]
There's already mod for that
https://www.curseforge.com/minecraft/mc-mods/better-sodium-video-settings-button

**Comment by TheKodeToad** [comment]
Not quite - it doesn't have the tabbed style or extra options.

**Comment by jellysquid3** [comment]
Not being considered...

**Comment by Neebuts** [comment]
:(

**Comment by KewaiiGamer** [comment]
lots of people need this. new sodium ui fucks with my muscle memory and i find myself always having to search for specific settings using the search option. optifine and vanilla ui was peak

**Comment by jellysquid3** [comment]
We didn't change the settings menu for the sake of it. For a long time, there were severe issues with the Minecraft implementation, like the fact that some options would freeze the game for minutes at a time, depending on how far you moved the mouse. And nowadays, with there being so many different mods, there is a need for *other* people to be able to extend the settings screen, which the Minecraft implementation is simply not designed for.

**Comment by jellysquid3** [comment]
And, politely, describing OptiFine's UI as "peak design" is fucking insane.
