### ISSUE TITLE
Incorrect Render Appliedenergistics2

### ISSUE THREAD

**Issue by HiddenCirno** [jellysquid3/Sodium#1308]
### Version information

Minecraft Version 1.17.1, Fabric Version 0.14.5, Sodium Version 0.3.4 build 13

### Expected Behavior

ah, render well?

### Actual Behavior

wire,plat or anymore be a full block with Mistaked Texture(purple and black) How can I add an image here?

### Reproduction Steps

its just didn't render

### Java version

java17

### CPU

AMD R5 2600X

### GPU

RX590

**Comment by Nekosha** [comment]
See #5.
