### ISSUE TITLE
Completely Invisible Blocks With Fabulous

### ISSUE THREAD

**Issue by DonSerrot** [jellysquid3/Sodium#131]
### Expected Behavior
Semi-transparent blocks visible with Fabulous graphics.

### Actual Behavior
Semi-transparent blocks invisible with Fabulous graphics.

### Reproduction Steps
Turn on Fabulous graphics while using build most recent dev branch.

### Attachments
![2020-07-21_02 01 11](https://user-images.githubusercontent.com/654744/88024313-1b7b7f80-caf8-11ea-9b46-5e1313c7019d.png)
![2020-07-21_01 59 52](https://user-images.githubusercontent.com/654744/88024316-1cacac80-caf8-11ea-80bb-04f8d557dc19.png)
![2020-07-21_02 00 57](https://user-images.githubusercontent.com/654744/88024318-1cacac80-caf8-11ea-8645-c124c30f5c37.png)

### System Information
- Java Version: 14.0.1 64bit
- CPU: 16x AMD Ryzen 7 1700
- GPU: GeForce GTX 970

**Comment by jellysquid3** [comment]
Now tracked by #181.
