### ISSUE TITLE
Major Crash Issues Occurring Every Time I Load In

### ISSUE THREAD

**Issue by Rage-GitHub** [jellysquid3/Sodium#1310]
### Version information

sodium-fabric-mc1.18.1-0.4.0-alpha6+build.14

### Reproduction Steps

1. Load into a server
2. Idle for a few minutes
3. Notice the FPS significantly dropping
4. Observe crash

### Crash Report file

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 5/20/22, 5:48 AM
Description: Unexpected error

java.lang.RuntimeException: Failed to upload all buffers
	at Not Enough Crashes deobfuscated stack trace.(1.18.1+build.22)
	at me.jellysquid.mods.sodium.client.gl.arena.AsyncBufferArena.upload(AsyncBufferArena.java:291)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:105)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:63)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.performPendingUploads(RenderSectionManager.java:374)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:318)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:196)
	at net.minecraft.client.render.WorldRenderer.setupTerrain(WorldRenderer:15479)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1253)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1031)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:811)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$fdm000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:19546)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:760)
	at net.minecraft.client.main.Main.main(Main:238)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.arena.AsyncBufferArena.upload(AsyncBufferArena.java:291)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:105)
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:63)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.performPendingUploads(RenderSectionManager.java:374)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:318)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:196)
	at net.minecraft.class_761.method_3273(class_761.java:15479)
	at net.minecraft.class_761.method_22710(class_761.java:1253)
	at net.minecraft.class_757.method_3188(class_757.java:1031)

-- Affected level --
Details:
	All players: 1 total; [class_746['Rage_4557'/296, l='ClientLevel', x=12.53, y=89.00, z=17.57]]
	Chunk stats: 4096, 520
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,90,0), Section: (at 0,10,0 in 1,5,0; chunk contains blocks 16,-64,0 to 31,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 10489 game time, 10489 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:408)
	at net.minecraft.class_310.method_1587(class_310.java:2402)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$fdm000$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:19546)
	at net.minecraft.class_310.method_1514(class_310.java:760)
	at net.minecraft.client.main.Main.main(Main.java:238)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, minecraft/supporteatinganimation, continuity/default, continuity/glass_pane_culling_fix, MedievalMusic2.zip, EmbellishedStone-1.18-1.0.0.zip, §6§lClassic 3D v14.3.1 - 1.18.2.zip

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 926400992 bytes (883 MiB) / 3120562176 bytes (2976 MiB) up to 17951621120 bytes (17120 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3070
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2484
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1277
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 51727.25
	Virtual memory used (MB): 44992.08
	Swap memory total (MB): 19036.20
	Swap memory used (MB): 0.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx17120m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 3.0.1
		additionalentityattributes: Additionalentityattributes 1.0.0+1.18.1
		adorn: Adorn 3.3.1+1.18.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancednetherite: Advanced Netherite 1.4.1-1.18.2
		advancementplaques: Advancement Plaques 1.4.4
		advancements-enlarger: Advancements Enlarger 0.2.4
		ambientenvironment: Ambient Environment 7.0+17
		amecsapi: Amecs API 1.3.6+mc1.18-pre1
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.18.1
		apoli: Apoli 2.2.4
		appleskin: AppleSkin 2.3.0+mc1.18.1
		architectury: Architectury 3.9.57
		artifacts: Artifacts 6.0.0+fabric
		attributefix: AttributeFix 13.0.5
		automatone: Automatone 0.5.0
		backslot: BackSlot 1.2.5
		balm-fabric: Balm 2.4.3+0
		basicshields: Basic Shields [Fabric] 1.2.1-1.18.1
		bclib: BCLib 1.3.5
		beautifiedchatclient-fabric: Beautified Chat Client (Fabric) 1.0
		betteranimalsplus: Better Animals Plus 1.18.1-11.0.5
		betterdungeons: YUNG's Better Dungeons 1.18-1.0
		betterend: Better End 1.0.3
		bettermineshafts: YUNG's Better Mineshafts 1.18.1-1.0
		betternether: Better Nether 6.0.12
		betterstrongholds: YUNG's Better Strongholds 1.18.1-1.0.1
		betterthirdperson: Better Third Person 1.6.0
		bewitchment: Bewitchment 1.18-15
		bitsandchisels: BitsAndChisels 2.6.4
		blabber: Blabber 0.1.2
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.4.1
		bountiful: Bountiful 2.0.1
		byg: BYG 1.3.5.13
		bygplus: Oh The Biomes You'll Go Plus 2.0.1
		calio: Calio 1.4.2
		campchair: Camp Chair 1.0.0
		campingsticks: Camping Sticks 1.18.2-1
		cardinal-components-base: Cardinal Components API (base) 4.1.3
		cardinal-components-block: Cardinal Components API (blocks) 4.0.1
		cardinal-components-entity: Cardinal Components API (entities) 4.1.3
		cardinal-components-item: Cardinal Components API (items) 4.0.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.2
		cardinal-components-world: Cardinal Components API (worlds) 4.1.2
		carrier: Carrier 1.9.1
		chime: Chime 1.2.0-SNAPSHOT
		chimes: Chimes 1.1.1
		chubby_stuff: Chubby Stuff 1.0.1
		chunky: Chunky 1.2.164
		cleancut: CleanCut 1.18-4.0-fabric
		clienttweaks: Client Tweaks 7.1.0
		cloth-api: Cloth API 3.1.61
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-client-events-v0: Cloth Client Events v0 3.1.61
		cloth-common-events-v1: Cloth Common Events v1 3.1.61
		cloth-config: Cloth Config v6 6.2.62
		cloth-datagen-api-v1: Cloth Datagen v1 3.1.61
		cloth-scissors-api-v1: Cloth Scissors API v1 3.1.61
		cloth-utils-v1: Cloth Utils v1 3.1.61
		clumps: Clumps 8.0.0+5
		coat: Coat 1.0.0-beta.17+mc1.18-pre1
		collective-fabric: Collective (Fabric) 4.9
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		comforts: Comforts 1.0.3-1.18.1
		companion: Companion 1.2.1
		continuity: Continuity 1.1.0+1.18
		couplings: Couplings 1.7.1+1.18
		crafttweaker: CraftTweaker 9.0.81
		darkpaintings: DarkPaintings 9.0.3
		dataattributes: Data Attributes 1.1.5
		decorative_blocks: Decorative Blocks 2.0.4
		decorative_winter: Decorative Winter 2.0.0
		dehydration: Dehydration 1.2.7
		dragonloot: DragonLoot 1.0.10
		drinkbeer: Drink Beer 3.0.2
		dual_riders: DualRiders 1.0.5
		dualwielding: Dual Wielding 1.0.7
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dungeons_arise: When Dungeons Arise 2.1.49d-fabric
		eatinganimationid: Eating Animation 1.6
		ecologics: Ecologics 1.3.0
		effective: Effective 1.2
		eldritch_mobs: Eldritch Mobs 1.10.4
		enchantment_force: enchantment_force 0.1.7
		endgoblintraders: End Goblin Traders 1.4.4
		enhancedcelestials: Enhanced Celestials 2.0.6
		environmentz: EnvironmentZ 1.2.1
		equipmentcompare: Equipment Compare 1.2.12
		expandability: ExpandAbility 5.0.0
		explorerscompass: Explorer's Compass 1.18.1-2.0.3-fabric
		extraalchemy: Extra Alchemy 1.7.0
		extraorigins: Extra Origins 1.18-9
		fabric: Fabric API 0.46.6+1.18
		fabric-api-base: Fabric API Base 0.4.2+d7c144a865
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.5.3+d7c144a865
		fabric-biome-api-v1: Fabric Biome API (v1) 6.0.2+d7c144a865
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.10+3ac43d9565
		fabric-command-api-v1: Fabric Command API (v1) 1.1.7+d7c144a865
		fabric-commands-v0: Fabric Commands (v0) 0.2.6+b4f4f6cd65
		fabric-containers-v0: Fabric Containers (v0) 0.1.19+d7c144a865
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.4.9+d7c144a865
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.9+3ac43d9565
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.10+a1d9bbf565
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.6+d7c144a865
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.17+d7c144a865
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.9+d7c144a865
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.11+d7c144a865
		fabric-item-api-v1: Fabric Item API (v1) 1.3.1+691a79b565
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.7+3ac43d9565
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.9+d7c144a865
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.7+b4f4f6cd65
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.13+713c266865
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.9+d7c144a865
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.7+d7c144a865
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.12+b4f4f6cd65
		fabric-models-v0: Fabric Models (v0) 0.3.4+d7c144a865
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.19+d7c144a865
		fabric-networking-v0: Fabric Networking (v0) 0.3.6+b4f4f6cd65
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.11.5+737332ce65
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.13+d7c144a865
		fabric-particles-v1: Fabric Particles (v1) 0.2.10+526dc1ac65
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.2+ad01bfbd65
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.11+b0b66fc365
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.15+6825030165
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.10+b4f4f6cd65
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.5+d7c144a865
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.19+3ac43d9565
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.12+b4f4f6cd65
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.6+713c266865
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 1.0.2+d7c144a865
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.15+8906aafd65
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.8+d7c144a865
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.12+d7c144a865
		fabric-structure-api-v1: Fabric Structure API (v1) 2.1.3+d7c144a865
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.9+d7c144a865
		fabric-textures-v0: Fabric Textures (v0) 1.0.10+3ac43d9565
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.9+fb3b57b465
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.10+c329913d65
		fabricloader: Fabric Loader 0.14.5
		fabricshieldlib: Fabric Shield Lib 1.5.0-1.18
		fallingleaves: Falling Leaves 1.9.0+1.18.1
		fallingtree: FallingTree 3.2.1
		farmersdelight: Farmer's Delight 1.18.1-0.2.0
		farsight: Farsight Mod 1.18-1.9
		faux-custom-entity-data: Faux-Custom-Entity-Data 1.0.3
		ferritecore: FerriteCore 4.1.2
		fiber: fiber 0.23.0-2
		fiber2cloth: Fiber To Cloth 3.1.1
		firstperson: FirstpersonModel 2.1.0
		flytre_lib: FlytreLib 1.7.1
		forgeconfigapiport: Forge Config API Port 3.1.1
		friendsandfoes: Friends&Foes 1.2.5
		ftblibrary: FTB Library 1801.3.5-build.109
		ftbquests: FTB Quests 1801.3.7-build.97
		ftbteams: FTB Teams 1801.2.5-build.48
		geckolib3: Geckolib 3.0.33
		geodes: More Geodes 1.2.0
		goblintraders: Goblin Traders 1.5
		goosik-config: goosik-config 0.2.0
		graveyard: The Graveyard 1.6
		graveyard_biomes: The Graveyard Biomes 1.0
		guardvillagers: Guard Villagers Fabric 1.18.1-1.0.11
		guild: Guild 0.3.8
		harvest_scythes: Harvest Scythes 2.4.1
		homebodies_fantasy: Homebodies: Fantasy 1.0.0
		iceberg: Iceberg 1.0.38
		illuminations: Illuminations 1.10.2
		immersive_armors: Immersive Armors 1.3.3-1.18.1
		immersive_weathering: Immersive Weathering 2.1.1
		impersonate: Impersonate 2.4.1
		incantationem: Incantationem 1.1.3+1.18.1
		indium: Indium 1.0.2-alpha3+mc1.18.1
		ingredient-extension-api: Ingredient Extension API 2.0.1
		inventorysorter: Inventory Sorter 1.8.5-1.18
		iris: Iris 1.2.0-pre
		itemfilters: Item Filters 1801.2.6-build.16
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 3.0.1-1.18
		kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		kirin: Kirin UI 1.10.0-beta.2
		kyrptconfig: Kyrpt Config 1.3.9-1.18
		legendarytooltips: Legendary Tooltips 1.2.4
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.8
		locki: Locki 0.7.0
		lovely_snails: Lovely Snails 1.0.3+1.18
		mcda: MC Dungeons Armors 2.0.6
		mcdar: MC Dungeons Artifacts 1.4.8
		mcdw: MC Dungeons Weapons 4.3.2
		mcwbridges: Macaw's Bridges 2.0.3
		medievalmusic: Medieval Music Mod 1.18-1.3
		medievalorigins: Medieval Origins 1.18.x-3.3.1
		midnightlib: MidnightLib 0.3.1
		minecraft: Minecraft 1.18.1
		mm: Manningham Mills 2.3
		mobscarecrow: Mob Scarecrow 1.2.0
		modmenu: Mod Menu 3.0.1
		more-axolotls: More Axolotls 1.0.2
		moreachievements: MoreAchievements 1.0.7
		morebannerfeatures: More Banner Features 1.1.3
		morevillagers-fabric: MoreVillagersFabric 3.1.1-SNAPSHOT
		mostructures: Mo' Structures 1.3.1+1.18.1
		mousetweaks: Mouse Tweaks 2.22
		mousewheelie: Mouse Wheelie 1.8.8+mc1.18-pre5
		mythicmounts: Mythic Mounts 1.18.1-7.0
		naturescompass: Nature's Compass 1.18.1-2.0.3-fabric
		net_objecthunter_exp4j: exp4j 0.4.8
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.4+1.18.1
		npcvariety: NPC Variety 2.2.2
		omega-config: OmegaConfig 1.2.3-1.18.1
		opc: Offline Player Cache 0.0.1
		org_anarres_jcpp: jcpp 1.4.14
		org_javassist_javassist: javassist 3.28.0-GA
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		org_reflections_reflections: reflections 0.10.2
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		origins: Origins 1.3.2
		origins-classes: Origins: Classes 1.2.4
		owo: oωo 0.5.2+1.18
		patchouli: Patchouli 1.18.1-65-FABRIC
		pehkui: Pehkui 3.3.1+1.14.4-1.19
		pickupnotifier: Pick Up Notifier 3.1.0
		placeholder-api: Placeholder API 1.1.3+1.17.1
		playerabilitylib: Pal 1.5.0
		playerex: PlayerEx 3.1.4
		polymorph: Polymorph 0.0.20-1.18.2
		presencefootsteps: Presence Footsteps 1.4.0
		puzzleslib: Puzzles Lib 3.2.1
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		replanter: Replanter 1.3
		requiem: Requiem 2.0.0-beta.7
		requiem-core: Requiem-Core 2.0.0-beta.7
		requiemapi: Requiem-API 2.0.0-beta.7
		rocks: This Rocks! 1.5.2
		roughlyenoughitems: Roughly Enough Items 7.4.456
		rpgdifficulty: Rpg Difficulty 1.0.11
		satin: Satin 1.7.2
		seedfix: Seed Fix 1.0.0
		skinlayers: 3d Skin Layers 1.4.4-mc1.18.2
		skyvillages: Sky Villages 1.0.1-1.18.1-fabric
		sodium: Sodium 0.4.0-alpha6+build.14
		sound_physics_remastered: Sound Physics Remastered 1.18.1-1.0.5
		stacc: Stacc 1.2.3
		starterkit-fabric: Starter Kit (Fabric) 3.1
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		terrablender: TerraBlender 1.1.0.77
		terraform-wood-api-v1: Terraform Wood API (v1) 2.0.2
		terralith: Terralith for Fabric 2.0.12
		things: Things 0.2.15+1.18
		thonkutil: ThonkUtil 2.7.1+1.18
		thonkutil-base: ThonkUtil Base 1.5.1+31ad4eb1c8
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.2.2+befce073c8
		thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.8+526fd6e5c8
		thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.3+526fd6e5c8
		thonkutil-legacy: ThonkUtil Legacy 1.0.9+6fa117f8c8
		thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.0+aebf7ba0c8
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.3.1+befce073c8
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.8+d77526a2c8
		tinyskeletons: Tiny Skeletons 3.1.0
		towers_of_the_wild_reworked: Towers of the Wild: Reworked 2.2.0
		travelersbackpack: Traveler's Backpack 1.18.1-7.0.0
		travelerstitles: Traveler's Titles 1.18.1-1.0
		trinkets: Trinkets 3.2.0
		tweed4_annotated: tweed4_annotated 1.3.0+mc1.18-pre2
		tweed4_base: tweed4_base 1.5.0+mc1.18-pre2
		tweed4_data: tweed4_data 1.2.1+mc1.18-pre2
		tweed4_data_hjson: tweed4_data_hjson 1.1.0+mc1.18-pre2
		tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18-pre2
		tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18-pre2
		twigs: Twigs 1.1.2
		visuality: Visuality 0.4.1
		visualworkbench: Visual Workbench 3.1.0
		wandering_collector: Wandering Collector 1.1.1+mc1.18.1
		waystones: Waystones 2.4.1
		xaerominimap: Xaero's Minimap 22.3.0
		xaeroworldmap: Xaero's World Map 1.20.3.1
		yigd: You're in Grave Danger 1.2.26
		yungsapi: YUNG's API 1.18-Fabric-36
		yungsbridges: YUNG's Bridges 1.18.1-1.0
		yungsextras: YUNG's Extras 1.18.1-1.0
	Launched Version: fabric-loader-0.14.5-1.18.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3070/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.77, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.' x 2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, minecraft/supporteatinganimation, continuity/default, continuity/glass_pane_culling_fix, file/MedievalMusic2.zip, file/EmbellishedStone-1.18-1.0.0.zip, file/§6§lClassic 3D v14.3.1 - 1.18.2.zip
	Current Language: English (US)
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor 
	Client Crashes Since Restart: 2
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Minecraft (minecraft), Fabric Loader (fabricloader), Sodium (sodium), Not Enough Crashes (notenoughcrashes)

### Additional information

Crash seems consistent and keeps occurring a few seconds after loading in. Shaders are completely disabled.

**Comment by jellysquid3** [comment]
Stale issue. Probably related to a broken resource pack. Open an issue if this is still happening on the latest version.
