### ISSUE TITLE
Spectating an Enderman while it is raining cause a game crash

### ISSUE THREAD

**Issue by AsrielDewitt** [jellysquid3/Sodium#1311]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

1. Spawn an enderman
2. Go to spectator mode
3. Spetate enderman's view
4. do /weather rain
5. wait for it to crash

### Crash Report file

[crash-2022-05-21_06.55.26-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8745758/crash-2022-05-21_06.55.26-client.txt)

**Comment by amnotbananaama** [comment]
Duplicate of #1016
