### ISSUE TITLE
Age of sugarcane when viewed at certain pitch revert to 0

### ISSUE THREAD

**Issue by scutoel** [jellysquid3/Sodium#1312]
### Version information

mc1.18.2-0.4.1+build.15

### Expected Behavior

Age of lower levels of sugarcan when stacked should always display the max 15 age

### Actual Behavior

Age of lower levels are displayed as age 0

### Reproduction Steps

1. Create a texturepack to set age of sugarcan to a different model or texture, [example pack](https://www.planetminecraft.com/texture-pack/blockstates/)
2. Stack sugarcane block on top of one another 
3. View the sugar cane from top down at around 5 blocks away
4. Bottom levels will have cuts in them (displayed as age 0)

### Java version

Java 17.0.1

### CPU

AMD Ryzen 7 3700X

### GPU

NVIDIA RTX 2070 SUPER

### Additional information

https://imgur.com/a/nADabyt

**Comment by jellysquid3** [comment]
This happens when the "Texture Filtering" settings in the NVIDIA Control Panel are overridden for Minecraft.
