### ISSUE TITLE
Sodium doesn't render transparency right with Croptopia/Botania

### ISSUE THREAD

**Issue by TheAyes** [jellysquid3/Sodium#1313]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

A normal transparency.

### Actual Behavior

Crops are being rendered unmasked. At a plain color. It seems to be a random color at most. 
![image](https://user-images.githubusercontent.com/68541335/170256590-fba52443-db9b-49be-b27f-a96844cd7d49.png)
![image](https://user-images.githubusercontent.com/68541335/170256626-096bbd71-cfe2-4338-8e97-2e8dedab4c47.png)

### Reproduction Steps

1. Enable Sodium, Croptopia and/or Botania
2. Find a crop coming from either of said mods.
3. Observe.

### Java version

Java 18

### CPU

Ryzen 7 5800

### GPU

msi GTX 960

**Comment by offbeat-stuff** [comment]
Maybe you need to install indium

**Comment by TheAyes** [comment]
> Maybe you need to install indium

Indium doesn't help

**Comment by offbeat-stuff** [comment]
You should send at least a list mods you have installed.
Also maybe a log and F3 screenshot

**Comment by Pultex** [comment]
Odd this does not happen on my server with 1.18.2 of botania with sodium and Indium
maybe another mod is effecting this
![2022-12-20_13 48 37](https://user-images.githubusercontent.com/34325251/208754314-04844bb7-ff4d-43ad-9c24-bcc0709d00dd.jpg)

a list of all mods I have installed with FABRIC
https://gist.github.com/Pultex/950d36bea03ff8358a824523e2abb303

**Comment by piuvas** [comment]
i was unable to reproduce this on `sodium-fabric-mc1.19.2-0.4.4+build.18.jar` and `Botania-1.19.2-438-FABRIC.jar`

![image](https://user-images.githubusercontent.com/65043391/235807685-e6584889-ddda-4e59-bd85-492432e4bb64.png)
