### ISSUE TITLE
'Fancy' and 'Smart' Leaves Feature similar to OptiFine

### ISSUE THREAD

**Issue by rowandevving** [jellysquid3/Sodium#1315]
It is really annoying when I use a resource pack that includes 'Bushy Leaves' which use fancy graphics to add an extra bit onto the vanilla leaves, but when using sodium I cannot see the 'bushy' part as the sodium 'Fancy' leaves setting seams to be a setting very similar to OptiFine's 'Smart' Leaves setting which turns leaves into 'Fast' mode after a certain distance. I understand that this is a measure to reduce lag, but it would be nice to be able to toggle it. Alternatively, you could make the distance at which the fancy leaves begin to be 'culled' configurable so to make it slightly more bearable

![image](https://user-images.githubusercontent.com/104677625/170344970-a0580feb-869b-45eb-8b72-f79b3457ad02.png)

**Comment by jellysquid3** [comment]
Sodium isn't doing anything special here. This is a consequence of using _mip-mapping_, which Minecraft itself does. The difference is that I believe OptiFine disables mip-mapping in some scenarios (or otherwise allows it to be disabled by resource packs?)

**Comment by ghost** [comment]
if I understand you, then you offer
What would the leaves , for example , become not transparent after 16 chunks ?

If so, it will increase the fps by 4 times since the video card will not need to render visual details that are still not visible

**Comment by piuvas** [comment]
i'm fairly sure this issue was addressed in [this](https://github.com/CaffeineMC/sodium-fabric/commit/306f45287f6ec86b73f88def279e1ca20fe17770) commit and previous discussions on discord.
