### ISSUE TITLE
Fix vanilla precision issues in block models

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#1316]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

All pixel sizes should be consistent and pixels and their borders should align perfectly.

### Actual Behavior

In a few select cases, there appear to be precision loss issues in model handling which result in ever so slightly incorrect sizes for pixels, model elements and so on. Examples are given below.

### Reproduction Steps

Doors ([MC-169897](https://bugs.mojang.com/browse/MC-169897)):
- Place a door
- Position yourself at the hinge portion (the region that stays constant when the door is closed and open)
- Open and close the door and observe closely

Cauldrons, hoppers and composters ([MC-246224](https://bugs.mojang.com/browse/MC-246224)):
- Place any or all of these three blocks
- Look very closely at all of the top corners

Farmland, dirt paths ([MC-252256](https://bugs.mojang.com/browse/MC-252256)):
- Position farmland or a dirt path next to a full block
- Try to see the second row of pixels from the top on the full block beside it

### Java version

17.0.2 64bit

### CPU

4× Intel® Core™ i3-3240 CPU @ 3.40GHz

### GPU

Intel® HD Graphics 2500

### Additional information

Door (hard to tell from screenshots, so I recommend reproducing this in game):
![2022-05-27_15 51 29](https://user-images.githubusercontent.com/52297970/170725679-22d0dc2c-2173-402a-a34a-06b968b8a532.png)
![2022-05-27_15 51 30](https://user-images.githubusercontent.com/52297970/170725684-6bd55746-e7d5-4fb1-b9e8-364378e76d73.png)

Cauldron, hopper, composter:
![2022-05-27_15 52 19](https://user-images.githubusercontent.com/52297970/170725724-d8804d9d-a33f-48e6-89e8-ab1afa1d18da.png)
![2022-05-27_15 52 23](https://user-images.githubusercontent.com/52297970/170725727-0ea984dc-cec3-4f1f-bf1a-7ab8b6a25535.png)

Dirt path, farmland:
![2022-05-27_15 52 49](https://user-images.githubusercontent.com/52297970/170725783-6a179c67-982c-4813-89b3-e24624af5411.png)

These effects can likely be found in far more circumstances.

**Comment by muzikbike** [comment]
https://github.com/MehVahdJukaar/modelfix-multi fixes this issue from my testing with affected custom models. I don't know if it'd be possible to integrate this same fix into Sodium somehow, assuming that's something that even gets done with the mod?

**Comment by jellysquid3** [comment]
This should be fixed with https://github.com/CaffeineMC/sodium-fabric/commit/ea0172768a5da9907b5a5711160dc3984fafea83.
