### ISSUE TITLE
Shaders not loading

### ISSUE THREAD

**Issue by obvLX** [jellysquid3/Sodium#1317]
### Version information

mc1.18.2 -0.4.1+build.15

### Expected Behavior

I expected that the shaders will load for a cinematic shot in the smp I play in. 

### Actual Behavior

The shaders wont load

### Reproduction Steps

1. I enabled shader
2. I selected the shader
3. I pressed k to load the shader
4. pressing r to reload the shader repeatedly  in hopes it will work
 (But it didn't)

### Java version

Java 17

### CPU

Intel core i7000X

### GPU

call me stupid but I cant find it

### Additional information

If this is a bug can you devs fix it please or if its a problem please inform me?

**Comment by Lolothepro** [comment]
https://github.com/IrisShaders/Iris/issues

**Comment by Pectacular** [comment]
This is an Iris issue not a Sodium issue
