### ISSUE TITLE
Poor Text Rendering Performance on Game Versions 1.17 and Above

### ISSUE THREAD

**Issue by Tammark** [jellysquid3/Sodium#1319]
While sodium has insane performance optimizations, one thing that seems missing is optimizations for rendering of text on screen (chat, signs, nameplates, etc). Ever since the introduction of hex color support for text in game version 1.16, text rendering performance has taken a noticeable hit. However text rendering performance took a massive hit in version 1.17 with all the changes made to the rendering system. Simply opening the f3 menu on this version will cause your frames to dip on even the newest hardware.

I did my own test of this performance by creating a small mod that would display fps on the screen at all times (remember, the f3 menu is a large wall of text which would affect results) In an empty area with no text on screen (besides the fps counter added by my mod) I would get upwards of 1000fps , but as soon as the f3 menu was opened fps dropped to a mere 100. Even single lines of text would noticeably drop the fps. However, the most noticeable performance issues occur when joining a busy multiplayer spawn/hub area, with loads of signs, nameplates, moving chat and players around. Depending on the area being rendered, fps would drop to unplayable levels. The same idea would also to apply to item tooltips with lots of colored text and lore lines.

Perhaps the sodium team could look into optimizing text, either via an experimental branch or an entirely different mod.

This issue frustrates me to the point where I want to dig into the code and try to fix it myself but rendering/OpenGl stuff seems so complicated compared to older versions so its probably better to leave it to a team with more experience.

Pc hardware in case anyone asks:
Nvidia GTX 1660 Super
Intel i7-11700 
16GB Ram

**Comment by Bipbip2109** [comment]
You are so based dude, that would be really cool if they do smth about it

**Comment by outlineutils** [comment]
#1082

**Comment by piuvas** [comment]
this should probably be closed as a duplicate.
