### ISSUE TITLE
Frametime issues with Intel UHD 630

### ISSUE THREAD

**Issue by NightTakesFlight** [jellysquid3/Sodium#1321]
### Version information

mc1.18.2-0.4.1+build.15

### Expected Behavior

Stable frametimes

### Actual Behavior

Frametimes fluctuate from 2-4ms to 9-11ms, Vsync doesn't help.

### Reproduction Steps

Load into the game and walk around for a bit.

### Java version

OpenJDK 18

### CPU

Intel Core i5 8400

### GPU

Intel UHD Graphics 630

### Additional information

32GB ram 2666mhz, I am unsure why this happens.

**Comment by Phoenix-Starlight** [comment]
Think it needs to run longer for optimizations to be done by the JVM.

**Comment by jellysquid3** [comment]
Per changes in policy on our issue tracker, we are closing issues which are general inquiries about performance issues and such. If you are experiencing performance issues and need help, then please use the [Discord server](https://caffeinemc.net/discord).
