### ISSUE TITLE
Falling block crash

### ISSUE THREAD

**Issue by marklangerhacker** [jellysquid3/Sodium#1324]
### Version information

mc1.19-0.4.2+build.16

### Reproduction Steps

1.Place sand or any block that can be falling
2.Brake a block under the block that can be falling
3.The game crashes

### Crash Report file

[crash-2022-06-08_14.49.08-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8861205/crash-2022-06-08_14.49.08-client.txt)

**Comment by Funtimes909** [comment]
This looks more like an issue with continuity then sodium

**Comment by Nekosha** [comment]
You need Indium installed along side Sodium.

**Comment by FinalBossJ** [comment]
> This looks more like an issue with continuity then sodium

Can confirm, was able to replicate it consistently while having Continuity. Crashes gone as soon as I removed it.
Gotta wait for a 1.19 Indium update.
