### ISSUE TITLE
Block outline becomes transparent, showing texture gaps

### ISSUE THREAD

**Issue by chimericdream** [jellysquid3/Sodium#1326]
### Version information

mc1.18.2-0.4.1+build.15

### Expected Behavior

When targeting a block with a translucent texture over an opaque layer, the dark outline around the block should render normally.

Screenshot without Sodium installed
![2022-06-08_23 24 34](https://user-images.githubusercontent.com/198075/172764149-cb87e559-806f-46a7-a12e-593dcb998568.png)

### Actual Behavior

The outline is transparent, resulting in thin lines of blocks behind the targeted one becoming visible.

Screenshot with Sodium installed
![2022-06-08_23 22 41](https://user-images.githubusercontent.com/198075/172764182-b7d3cd21-721a-4e5a-8eb4-acd02ac24744.png)

### Reproduction Steps

Mod list:
* ARRP 0.5.7
* Fabric API 0.55.1+1.18.2
* Iris Shaders 1.18.2-1.2.5
* Minekea 1.18.2-2.8.2
* Sodium 1.18.2-0.4.1+build.15

Load a world and place any of the barrel blocks provided by the Minekea mod. Notice that when you target the block, the outline is transparent instead of solid.

### Java version

Java 17

### CPU

Ryzen 5950X

### GPU

AMD 6900XT

### Additional information

This was reported by a user of my mod, and I was able to verify that it only happens with Sodium installed. I found a couple of issues that seemed similar (such as #38 about the block translucency issue), but none that were precisely the same.

**Comment by jellysquid3** [comment]
This is not a bug with Sodium, but rather an issue with vanilla. We are unlikely to consider fixing it.

**Comment by UADominator** [comment]
Hi! I made fix. but only for 1.20.1 https://github.com/UADominator/Outline-Fixer-Minecraft-mod
