### ISSUE TITLE
Мерцание текстур  из-за мода 

### ISSUE THREAD

**Issue by Sosisk1** [jellysquid3/Sodium#1327]
### Version information

mc1.17.1-0.3.3+build.8

### Expected Behavior

.

### Actual Behavior

.

### Reproduction Steps

.

### Java version

Java 8 Update 333

### CPU

Intel  i5-1035G1 1.19 GHz

### GPU

.

### Additional information

https://youtu.be/OmiND09O0rg
В начале всё было нормально но после 100 дней начались мерцание текструр не знаю с чем это связано.

**Comment by Felix14-v2** [comment]
Откуда вы скачивали мод? Пожалуйста, используйте всегда только официальные источники! Только на них вы всегда сможете получить самую последнюю версию с исправлениями ошибок.

Что касается проблемы, похожий баг уже давно был исправлен [в версии 0.3.4](https://modrinth.com/mod/sodium/version/mc1.17.1-0.3.4) (у вас 0.3.3, build 8).

**Comment by Sosisk1** [comment]
Я сделал что вы написали но мерцание текстур так и не исчезло

**Comment by Felix14-v2** [comment]
На вашем устройстве присутствует дискретная видеокарта? Если да, попробуйте запустить игру с неё. Ошибка может возникать также из-за плохого обновления для видеодрайвера.

Также было бы неплохо увидеть диагностическую информацию. Удерживайте сочетание клавиш F3+C в течение 10 секунд, чтобы игра сгенерировала краш-репорт (Minecraft при этом вылетит). Он будет помещён в папку crash-reports в используемой игрой директории, рядом с папкой saves, screenshots и прочими. Отправьте его сюда.

**Comment by Sosisk1** [comment]
Вам нужно скинуть то что внутри папки crash-reports?

**Comment by Felix14-v2** [comment]
Да, самый последний по дате создания файл. 
Если есть желание, можем списаться в Discord (Felix14#3357), там вести общение на русском будет всё же уместнее. Это GitHub, и разработчики нас банально не смогут понять.

**Comment by Sosisk1** [comment]
Я отправил

**Comment by silversquirl** [comment]
Just for future reference, this bugtracker should be kept English only so we can understand what's going on - Google Translate can only do so much! :)

Thanks for moving the discussion elsewhere!

**Comment by Felix14-v2** [comment]
> bugtracker should be kept English only so we can understand what's going on

I understand, I'm sorry. I could answer the author of the issue in English, but it would be less effective, I think. Anyway, we found out that the problem (demonstrated [in the video](https://www.youtube.com/watch?v=OmiND09O0rg)) is still present in the newest version of Sodium (0.4.2). Should we open a new issue, or continue to supplement/replace the material in this one?

**Comment by Sosisk1** [comment]
https://youtu.be/HGFBEJT1IO8

**Comment by Sosisk1** [comment]
https://youtu.be/OinpLT16Pk4
