### ISSUE TITLE
Weird Rendering Glitch Causing Large Amount of Lag

### ISSUE THREAD

**Issue by TanCY1** [jellysquid3/Sodium#1328]
### Version information

mc1.19-0.4.2+build.16

### Expected Behavior

Minecraft should render properly without low fps

### Actual Behavior

The fps drops to 0 and a weird rendering glitch appears

### Reproduction Steps

I do not know how to replicate it

### Java version

Java 18

### CPU

Intel(R)Core(TM)2 Quad CPU     Q9500  @ 2.83GHz

### GPU

ATI Radeon HD 4300/4500 Series

### Additional information

This has only happend once on a server
![2022-06-12_22 30 59](https://user-images.githubusercontent.com/95896179/173238884-6bc54880-a7a8-4804-952d-0e4b00f3fe3f.png)

**Comment by jellysquid3** [comment]
Your graphics card is too old, is using unsupported drivers, or otherwise has a hardware fault. We can't fix issues like this.
