### ISSUE TITLE
Entitie Render distance locked at 100%

### ISSUE THREAD

**Issue by TwinShards** [jellysquid3/Sodium#133]
Hello, so i noticed that the render entitie distance setting does not change the distance at which we can see entitie.

In short words: Tested with Sodium as the only mod, Render entitie distance does not change even if you go to the minimal 50% or the maximal 500%
In Vanilla or Optifine version this setting work as intended.

Here is a video comparaison Optifine/Sodium:

https://youtu.be/Ifq5_d8OKkU

**Comment by NoComment1105** [comment]
This is an issue I discovered as well and it was fixed in a recent dev build

**Comment by TwinShards** [comment]
Thank for letting know.
