### ISSUE TITLE
User Interface and UI

### ISSUE THREAD

**Issue by iSkeptical** [jellysquid3/Sodium#1330]
This is a feature request based on just personal taste and opinion.

This may sound stupid, but I have been putting off the switch from optifine to sodium for basically 3 reasons

(1) I'm just annoyed by (imo) ugly and "unminecrafty" interface. I love how optifine sliders are vannila-ish
(2) Shader support & other features ( Ik Iris is out there but see reason (3) ) 
(3) Convenience (It's much easier to get 1 mod from 1 place)

As a solution I'd like to see at least *option* to the a layout and design of the interface to make it more vanilla at the very least

For awhile now I simply just refused to convert due to inconvenience of needing multiple mods to update and the unvanilla feel of them.

**Comment by IMS212** [comment]
We will not be merging Iris and Sodium.

As for the UI complaints; there isn’t just style reasons for this, it actually makes development easier. The Sodium GUI is much easier to develop and add to, while Vanilla’s is much worse.

**Comment by FlashyReese** [comment]
If you want the "minecraft"-y interface back, you can get [Better Sodium Video Settings Button](https://www.curseforge.com/minecraft/mc-mods/better-sodium-video-settings-button). Although the mod is not affiliated with CaffeineMC, so there is no support from CaffeineMC.
