### ISSUE TITLE
Sodium not loaded during boot

### ISSUE THREAD

**Issue by boldt** [jellysquid3/Sodium#1334]
### Version information

mc1.19-0.4.2+build.16

### Expected Behavior

Sodium shown in boot log.

### Actual Behavior

Sodium not shown in boot log.

### Reproduction Steps

TLDR: See https://github.com/boldt/sodium-fabric-1334

I have a vanilla server with fabric loader. I added lithium, phosphor and sodium to the mods folder:

```
$ ls mods/
lithium-fabric-mc1.19-0.8.0.jar
phosphor-fabric-mc1.19.x-0.8.1.jar
sodium-fabric-mc1.19-0.4.2+build.16.jar
```

During boot, it shows the fabricloader with lithium and phosphor:

```
[11:49:32] [main/INFO]: Loading 5 mods:
	- fabricloader 0.14.7
	- java 17
	- lithium 0.8.0
	- minecraft 1.19
	- phosphor 0.8.1
```

Sodium does not show up in the boot log.

### Java version

17

### CPU

Xeon(R) CPU E3-1275 v6

### GPU

n/a

### Additional information

I am using the [docker-minecraft-server](https://github.com/itzg/docker-minecraft-server) with 

```
      - TYPE=FABRIC
      - FABRIC_LAUNCHER_URL=https://meta.fabricmc.net/v2/versions/loader/1.19/0.14.7/0.11.0/server/jar
```

Here you find a MWE showing this issue: https://github.com/boldt/sodium-fabric-1334

**Comment by Ziyph** [comment]
Sodium is a client-side mod. It does nothing on the server-side.

**Comment by boldt** [comment]
On client side, it works. Thanks.
