### ISSUE TITLE
1.19.x next branch fails to build

### ISSUE THREAD

**Issue by woot000** [jellysquid3/Sodium#1336]
Building the 1.19.x/next branch with the command ```gradlew.bat build --no-daemon``` on Windows 11 gives this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':remapJar'.
> Failed to check file from zip
```

It looks like the recent GitHub Actions builds are also failing to build with the same error message

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/80956290/174193278-1e3cc2a2-f20f-4033-bd19-be5df4488a05.png)

And for what purpose do you need the latest build ?

**Comment by woot000** [comment]
Some of the recent commits appear to both further optimize processing and fix important bugs ([this commit](https://github.com/CaffeineMC/sodium-fabric/commit/65a541d4024bec32d3a6c45c2325325cf7ca09af) for example), and since they aren't in the latest release build I'd like to build Sodium for myself to take advantage of these changes.

**Comment by masmc05** [comment]
run `components:gfx-opengl:build` before `build`, this should fix this issue

**Comment by woot000** [comment]
> run `components:gfx-opengl:build` before `build`, this should fix this issue

Thanks, though I think that step should be made a bit clearer on the readme, unless this is a temporary change

**Comment by masmc05** [comment]
> > run `components:gfx-opengl:build` before `build`, this should fix this issue
> 
> Thanks, though I think that step should be made a bit clearer on the readme, unless this is a temporary change

idk, i just also tried to do it once, and from the error stacktrace understood that need to build that first
