### ISSUE TITLE
mushrooms on Mooshrooms flicker and glitch while BetterNether is enabled

### ISSUE THREAD

**Issue by RiskE80T** [jellysquid3/Sodium#1341]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16.jar

### Expected Behavior

Mushrooms should not flicker and glitch 

### Actual Behavior

my eyes started to hurt a little

https://user-images.githubusercontent.com/81003103/174430858-8be9a341-1839-4c0e-b17f-918d940f1e70.mp4

and i did try this without sodium and it was working fine, so im assuming its Sodium?

### Reproduction Steps

1. install Sodium 1.19
2. install BetterNether 1.19
3. Open World 
4. Spawn or find Mooshroom
5. Watch

### Java version

Java 17.0.3

### CPU

Intel Core i9-10900

### GPU

GeForce RTX 3060

### Additional information

using BetterNether

**Comment by ASTRELION** [comment]
I have a similar problem, but with Vanilla Tweaks resource pack (https://vanillatweaks.net/picker/resource-packs/).

https://user-images.githubusercontent.com/20118782/174699795-5c4cc497-1ce0-4eb8-879e-112bfb8ce587.mp4

Vanilla Tweaks config: [VanillaTweaks_r979419.zip](https://github.com/CaffeineMC/sodium-fabric/files/8945102/VanillaTweaks_r979419.zip)
Sodium: 1.19, 0.4.2 build 16

Occurs in both singleplayer and on servers.

**Comment by uriesk** [comment]
Same problem here, but i am only using the [StayTrue](https://www.curseforge.com/minecraft/texture-packs/stay-true) resource pack.

**Comment by uriesk** [comment]
Looks like it happens when mushrooms have multiple blockstates in your resource pack.
If you remove `assets/minecraft/blockstates/brown_mushroom.json` and `assets/minecraft/blockstates/red_mushroom.json`, it is fixed.

But then you don't get those nice random mushrooms, so a proper fix in Sodium would be nice :)
It does not happen in vanilla afterall.

**Comment by Linventor** [comment]
Something else of note - this issue also occurs with Endermen.
Same effect as with mooshrooms, just with whatever block is being held.
I also tested with falling blocks, and found that there is neither flicker nor multiple blockstates.

**Comment by IMS212** [comment]
Bug with Sodium 0.4.2, will be fixed in 0.4.3. https://github.com/CaffeineMC/sodium-fabric/commit/6b641f9e03c17736dda6fc31ca8a0d686c8ddb19
