### ISSUE TITLE
Animated blocks don't have an Animation if they don't exist, placed down.

### ISSUE THREAD

**Issue by agent-LuluDodo** [jellysquid3/Sodium#1342]
### Version information

mc1.19-0.42+build.16

### Expected Behavior

Animated blocks have an animation, even if they aren't placed down somewhere.

### Actual Behavior

Animated blocks have no animation, even if they aren't placed down somewhere.

### Reproduction Steps

1. Create a new flat world
2. Execute this command: `/summon falling_block ~ ~ ~ {BlockState:{Name:"minecraft:fire"},NoGravity:1b,Time:-32767}`
3. The falling block isn't animated
4. Set a few things on fire _(Note: some places don't work)_
5. The falling block is animated.

### Java version

Java 18.0.1.1 64bit

### CPU

AMD Ryzen 7 PRO 4750G

### GPU

NVIDIA GeForce RTX 3060 Ti

### Additional information

This doesn't happen in Vanilla.
No other mods installed.

https://user-images.githubusercontent.com/98981925/174441669-25ef39ca-b509-4bc2-9607-45d3f20ed950.mp4

**Comment by TheKodeToad** [comment]
Does the issue occur for the fire on the player model and first person?
I don't know much about sodium but this *may* help.

**Comment by agent-LuluDodo** [comment]
The fire on an entity model and in first person is animated and fixes the falling Block too!

**Comment by piuvas** [comment]
unable to reproduce on `sodium-fabric-mc1.19.4-0.4.11+build.26.jar`.

https://user-images.githubusercontent.com/65043391/235809571-7acf649a-b2b4-4ede-b0bb-5b30c0134700.mp4

**Comment by agent-LuluDodo** [comment]
**It also works for me while using 1.19.4 with sodium mc1.19.4-0.4.11+build.26.**
But sadly, the newest version for 1.19 (mc1.19.2-0.4.4+build.18) still doesn't work. 
Is support for 1.19.0-2 dropped?

**Comment by piuvas** [comment]
it is dropped. the currently supported versions are 1.19.3 and 1.19.4.
