### ISSUE TITLE
Will You Create A Port To The Quilt Mod Loader?

### ISSUE THREAD

**Issue by Commandthealien** [jellysquid3/Sodium#1344]
I have been wondering recently, with the Quilt Mod Loader gaining popularity. Will you update/make a port to the Quilt Mod Loader?

Just thought I would suggest this because the Quilt Mod Loader will eventually stop support for fabric mods if they haven't already. It will also be nice to have the choice between 2 mod loaders and not just the 1.

**Comment by mrmangohands** [comment]
Quilt does and will continue to support fabric mods for the foreseeable future, so there's not really much point in having a separate version for it. 

If it does break compatibility or quilt has something relevant on the technical side to offer a second build/a switch can be revisited then
