### ISSUE TITLE
Sodium with Enhanced Block Entities causes animated textures to flash for a second when finishing (chest and shulker lids closing, bells stop ringing, etc), caused by "Always Defer Chunk Updates" 

### ISSUE THREAD

**Issue by CalXee** [jellysquid3/Sodium#1349]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16

### Expected Behavior

The chest lid wouldn't flash

### Actual Behavior

The chest lid flashes when it closes. Turning off Always Defer Chunk Updates only makes this happen slightly less frequently.

### Reproduction Steps

1. Install Sodium and Enhanced Block Entities
2. Close a chest
3. Observe the lid vanish for a second.

### Java version

Java 17

### CPU

i7-8750H

### GPU

GTX 1050 Ti

### Additional information

The Always Defer Chunk Updates option is rather problematic in general, to the point where the Fabulously Optimized modpack disables that option by default. After talking with Foundation on discord, apparently even if you turn this option off, Sodium still skips some chunk updates which causes the flashing. I wouldn't mind if this deferring chunk update option is completely removed; at least personally, I don't notice a huge performance difference, and Sodium is really REALLY fast already.

**Comment by Funtimes909** [comment]
Can confirm I have this issue as well and it really bugs me
