### ISSUE TITLE
Add an option to toggle animations

### ISSUE THREAD

**Issue by Musahh** [jellysquid3/Sodium#1351]
**Is your feature request related to a problem? Please describe.**

So there's a type of combat called Vanilla PvP. It's used in the latest versions and is laggy so many people use sodium. It utilizes end crystals and respawn anchors which trigger the explosion animation. In order to avoid this pack makers have to erase the explosion particles.

**Describe the solution you'd like**

Just adding a animations toggle button like particles because I know for a fact a lot of people don't use animations since they don't have any advantage or disadvantage.

**Describe alternatives you've considered**
OptiFine has an option to turn of any animations the players does not want. However, sodium is better performance wise

**Additional context**

There isn't any mod that does this so I'm sure the Vanilla PvP community would be very thankful!

Edit:
I found a mod. It's called sodium extras, still hope you add the option because not a lot of people know about it.

**Comment by piuvas** [comment]
you can use [sodium-extra](https://modrinth.com/mod/sodium-extra) to toggle animations.
