### ISSUE TITLE
Rendering Block Entity

### ISSUE THREAD

**Issue by TheButterbrotMan** [jellysquid3/Sodium#1352]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

1. Download https://www.curseforge.com/minecraft/modpacks/deathdusk (2.0.10)
2. Create a world
3. Place a Maple Sign from BYG

### Crash Report file

https://bytebin.lucko.me/db4aHSedJ2

**Comment by TheButterbrotMan** [comment]
https://github.com/TheButterbrotMan/Deathdusk/issues/119

**Comment by jellysquid3** [comment]
Log file is no longer accessible and there is no reason to believe this is Sodium's fault, either.
