### ISSUE TITLE
Broken transparency on frogspawn

### ISSUE THREAD

**Issue by Helpbot3000** [jellysquid3/Sodium#1353]
### Version information

mc1.19-0.4.2

### Expected Behavior

In vanilla Minecraft, frogspawn blocks are translucent both when placed and in the inventory.

### Actual Behavior

Frogspawn blocks are fully opaque.

### Reproduction Steps

1. Obtain frogspawn
2. Look at frogspawn

### Java version

Java 17.0.3 64bit

### CPU

Ryzen 7 3700X

### GPU

GTX 1070

### Additional information

I attempted to find if this was reported yet, but I did not see anything.  I'm not sure if this is related to the other transparency issues that are present or if it's a separate issue.

**Comment by burgerindividual** [comment]
This is a known issue, it's currently not translucent as a workaround to #38. We're working on it.
