### ISSUE TITLE
Animated textures: Sodium should not require modders to implement explicit compat

### ISSUE THREAD

**Issue by Technici4n** [jellysquid3/Sodium#1354]
I implemented the following workaround to allow Modern Industrialization machine and fluid textures rendered using a Block Entity Renderer to be animated with Sodium: https://github.com/AztechMC/Modern-Industrialization/commit/3ada9dd2b69f573a3fd3f2aee8b4039cba26e22e.

However, I don't like this: I don't think it's reasonable to expect that mods will all implement similar support for Sodium. Would it not be possible to flag the contained sprite as active when a `BakedQuad` is added to a vertex consumer (at least the one used by block entity renderers)?

**Comment by jellysquid3** [comment]
> Would it not be possible to flag the contained sprite as active when a BakedQuad is added to a vertex consumer...

This is actually a pretty clever idea, and would probably solve most edge cases while removing a few other hacky mixins we're using to detect sprite usages in a given frame.
