### ISSUE TITLE
Rendering block entity/CrashReport

### ISSUE THREAD

**Issue by theOfficalKamiii** [jellysquid3/Sodium#1356]
### Version information

MCversion 1.18.2 on All of Fabric 5 v. 1.3.0

### Reproduction Steps

[crash-2022-06-22_11.39.25-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8961370/crash-2022-06-22_11.39.25-client.txt)
Gives the step but on loading into the world it would crash almost immediately.

### Crash Report file

[crash-2022-06-22_11.39.25-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8961371/crash-2022-06-22_11.39.25-client.txt)
![Minecraft client error](https://user-images.githubusercontent.com/108031588/175141292-cf6b0963-fc84-4299-9674-032f8a87f795.png)

### Additional information

This crash was persistent with 5 other people as well.

**Comment by xmadb4x** [comment]
this happened to me too, but on 1.19

**Comment by zeldaking** [comment]
same

**Comment by SolarReflect** [comment]
same thing with me

**Comment by pajicadvance** [comment]
Duplicate of #1352.
