### ISSUE TITLE
Redstone Lamp Rendering

### ISSUE THREAD

**Issue by Grochonou** [jellysquid3/Sodium#1357]
### Version information

sodium-fabric-mc1.19-0.4.2build.16

### Expected Behavior

Redstone Lamp Normal Lightning

### Actual Behavior

![2022-06-23_00 42 21](https://user-images.githubusercontent.com/44367332/175166757-209452da-3e80-4538-89bb-34f7e876ed8d.png)

As you can see i have this lightning bug with sodium, i don't know how i can fix it..

### Reproduction Steps

Just add a redstone block next to a redstone lamp with and without sodium. 

### Java version

Java 8 Update 331 (64bits)

### CPU

Ryzen 9 3900x

### GPU

Nvidia Geforce RTX 2070

**Comment by FlashyReese** [comment]
Duplicate bug of https://github.com/CaffeineMC/sodium-fabric/issues/226

**Comment by burgerguy** [comment]
For some reason, github didn't mark this as a duplicate, so I'll force it to:
Duplicate of #226
