### ISSUE TITLE
Sky problem with a Ressource pack (DokuCraft Light) with Fabulous settings

### ISSUE THREAD

**Issue by LiderKonmils** [jellysquid3/Sodium#1358]
### Version information

Minecraft 1.18.2
Fabric: 0.14.8-1.18.2
sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

To not glitch?

### Actual Behavior

The sky glitch in Fabulous settings. It dosen't do it without the ressource pack (DokuCraft Light), sodium or the Fabulous Settings. 
https://www.youtube.com/watch?v=6QR5t-xw3Lc

### Reproduction Steps

1.Install Fabric (0.14.8-1.18.2)
2.Install Sodium in mods folder
3.Install Dokucraft Light (1.18.2-Dokucraft-Light https://dokucraft.co.uk/resource-packs/light/) as ressource pack
4.Set Graphics Settings to "Fabulous"
5.Move your cursor looking at the sky (look the video provide at "Actual Behavior" section to more info).

### Java version

17.0.1 64bit

### CPU

12x Intel(r) Core(TM) i7-10750H CPU @ 2.60GHz

### GPU

Nvidia GeForce RTX 2060/Pcie/SSE2

### Additional information

https://www.youtube.com/watch?v=6QR5t-xw3Lc

**Comment by oceancubes1** [comment]
Same problem :(

**Comment by piuvas** [comment]
able to reproduce using `sodium-fabric-mc1.19.4-0.4.10+build.24.jar`.

**Comment by Felix14-v2** [comment]
Probably because of the core shaders in DokuCraft. Ask its developer for Sodium support via [Sodium Shader Support](https://github.com/DartCat25/sodium-shader-support) in this case.
