### ISSUE TITLE
Disabling "Compact Vertex Format" completely breaks block rendering

### ISSUE THREAD

**Issue by Leo40Git** [jellysquid3/Sodium#136]
### Expected Behavior
Disabling "Compact Vertex Format" should not affect block rendering (beyond the performance decrease).

### Actual Behavior
Well...
![2020-07-22_11 44 54](https://user-images.githubusercontent.com/7997354/88155786-32fa5b80-cc11-11ea-8497-2275fe9cdbcd.png)

### Reproduction Steps
1. Disable "Compact Vertex Format" in the "Advanced" tab

### System Information
- Java Version: AdoptOpenJDK 14.0.2.12
- CPU: Intel Core i5-8250U @ 1.80GHz
- GPU: NVIDIA GeForce MX150

**Comment by Riteo** [comment]
can you still reproduce this issue after a4f4e9d?

**Comment by fsharpseven** [comment]
This is fixed in `1.16.x/next`, so should this be closed?

**Comment by Leo40Git** [comment]
Guess so (though there's currently another unrelated problem with CVF in that branch).
