### ISSUE TITLE
Can't Use Texture Pack

### ISSUE THREAD

**Issue by tecboyj** [jellysquid3/Sodium#1362]
### Version information

mc1.19-0.4.2+build.16

### Expected Behavior

I opened up the recource pack settings to load a resource pack

### Actual Behavior

When I try and load my custom vanillatweaks texture pack it then goes back and it says "recourse reload failed" and it gives me the vanilla textures. The pack is attached below. this is caused by an interaction with the continuity mod also linked below
[VanillaTweaks_1.19.zip](https://github.com/CaffeineMC/sodium-fabric/files/8985995/VanillaTweaks_1.19.zip)
[continuity-2.0.0+1.19.jar.zip](https://github.com/CaffeineMC/sodium-fabric/files/8986003/continuity-2.0.0%2B1.19.jar.zip)
.

### Reproduction Steps

I tryed to load the recource pack multiple time and it failed every time while the mod was installed.

### Java version

i don't know how to check that

### CPU

ryzen 5 5600g

### GPU

AMD Radion Graphics (cpu intagrated graphics)

### Additional information

Here is the Entire Mods Folder

[mods.zip](https://github.com/CaffeineMC/sodium-fabric/files/8986005/mods.zip)

**Comment by ghost** [comment]
Seconded, I can't enable Textures at all, using BetterVanillaBuilding I also get the same issue. Loads fine once I remove Sodium

EDIT: Mine was incompatibility related, Disregard. Not caused by Sodium

**Comment by Phoenix-Starlight** [comment]
Logs, please. Also you may need indium.

**Comment by ghost** [comment]
> Logs, please. Also you may need indium.

Mine was related to Clear Skies and Colormatic, not sure about OP.

**Comment by tecboyj** [comment]
ya, I looked into it after I posted this and indium fixed it

**Comment by piuvas** [comment]
should be closed.
