### ISSUE TITLE
Renderer returning null

### ISSUE THREAD

**Issue by olillin** [jellysquid3/Sodium#1363]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16

### Reproduction Steps

Here is what happened: 
1. I was high up in the sky and the ground was out of view
2. Then I flew back down at speed
3. When the ground came back into view the game crashed

### Crash Report file

[crash-2022-06-26_17.39.15-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/8986961/crash-2022-06-26_17.39.15-client.txt)

**Comment by burgerindividual** [comment]
This is a bug with continuity, not with Sodium. I'll reopen if you can't reproduce without sodium.
