### ISSUE TITLE
I used to be able to see far away in hypixel

### ISSUE THREAD

**Issue by hfzi** [jellysquid3/Sodium#1368]
I'm playing skyblock. I used to be able to see the farthest corner when I was in a corner. It even skyrocketed on Hub maps. I could see the entire HUB. Then this stopped happening and when I started teleporting it was a problem.

My last screenshots;
<img width="960" alt="2022-06-26_23 38 34" src="https://user-images.githubusercontent.com/24457679/176373515-417c560b-b879-4bd6-b219-b803bc2edb0d.png">
<img width="1920" alt="2022-06-27_08 11 31" src="https://user-images.githubusercontent.com/24457679/176373833-2b71ccdc-1f60-4d46-8b3e-91c9f247b927.png">
<img width="1920" alt="2022-06-26_16 43 57" src="https://user-images.githubusercontent.com/24457679/176374041-0a68946e-a725-4c7d-8cdd-23ee7357ee5f.png">

I tried all the settings. I deleted and reinstalled. I deleted the maps. I played with jvm.
My PC:
- RTX 3070
- Ryzen 5600x
- 32Gb 3600MHz

Before,
- Device buffer objects:62
- Device memory: 150/363MB
but now it's lower.

old, new
![Ekran Görüntüsü (323)](https://user-images.githubusercontent.com/24457679/176375293-93078fac-1a89-46a7-ae3d-2c05df5ca5fe.jpg)

![2022-06-29_08 18 16](https://user-images.githubusercontent.com/24457679/176375472-e0329036-7fed-45d0-be96-5285ad5ef607.png)

how can i restore it. 

Thanks.

**Comment by ghost** [comment]
mod bobby bug

**Comment by hfzi** [comment]
> mod bobby bug

Thank you so much
