### ISSUE TITLE
Sodium still doesn't render water correctly, after all these years.

### ISSUE THREAD

**Issue by Obscure2020** [jellysquid3/Sodium#1369]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16.jar

### Expected Behavior

Water should look like it does in Vanilla.

### Actual Behavior

![2022-06-29_16 16 16](https://user-images.githubusercontent.com/69320464/176552135-aa228c66-6586-4f69-a32f-732f425d7a14.png)
![2022-06-29_16 16 24](https://user-images.githubusercontent.com/69320464/176552140-05b33288-aec4-4d35-b66f-816d3a6ac027.png)
![2022-06-29_16 16 19](https://user-images.githubusercontent.com/69320464/176552144-3b51b673-41c2-47c3-a7a3-6b40b5231e15.png)
![2022-06-29_16 16 21](https://user-images.githubusercontent.com/69320464/176552150-243abec7-d468-43db-87e2-84bb4a5d3cbe.png)

### Reproduction Steps

Look at running water from certain angles.

### Java version

Java 17.0.3 64bit

### CPU

Intel Core i7-10510U

### GPU

NVIDIA GeForce MX250

### Additional information

I have reported this bug before in #991.
I have now closed that issue and opened this one new, to let you guys know that this issue is _still_ present in the latest versions of Sodium and Minecraft.

**Comment by jellysquid3** [comment]
User banned from issue tracker.
