### ISSUE TITLE
Emissive support

### ISSUE THREAD

**Issue by CoCuCoH41k** [jellysquid3/Sodium#1370]
The appearance of the glow function in texture packs as in optifine, I would like to see an analogue of Visible Ores on Sodium.

Create a folder in the texture pack "sodium", and in it already "emissive.properties", and specify "suffix.emissive=_e". a glow will be superimposed on the default texture (a texture with the suffix "_e"), and with shaders of the type "BSL" it will glow.

**Comment by IMS212** [comment]
Already handled by Continuity + Indium.
