### ISSUE TITLE
Not for 1.18

### ISSUE THREAD

**Issue by KaiPollard10** [jellysquid3/Sodium#1372]
I am using CurseForge and I cant apply the mod to my profile because I play on a server that is on 1.18.1 and I tried 1.18.2 but it wont work.

**Comment by Phoenix-Starlight** [comment]
Use an older version uploaded.

**Comment by jellysquid3** [comment]
There are releases for MC 1.18, they're just marked as alpha. If you cannot use that in your modpack, add the file manually.
