### ISSUE TITLE
Sodium cannot render the resource package of the modelengine correctly

### ISSUE THREAD

**Issue by newcovid** [jellysquid3/Sodium#1376]
### Version information

mc1.18.2---sodium0.4.1+build.15

### Expected Behavior

![image](https://user-images.githubusercontent.com/96228495/177092182-1b266b49-9f62-4040-a708-46c48c17d4ae.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/96228495/177092209-fb31b6fe-fd70-4742-b788-83d1e4b2762b.png)

### Reproduction Steps

When using the server plug-in model engine, optfine behaves normally, but sodium cannot render normally

### Java version

java17.0.1   64bit

### CPU

intel i5-9300h

### GPU

NVIDIA GeForce GTX 1650

### Additional information

Although it can't render successfully without adding any modules, I still hopes that sodium can support the rendering of the model engine

**Comment by pajicadvance** [comment]
Sodium doesn't support custom entity models by itself. You can try using a mod like Entity Model Features to add support.
