### ISSUE TITLE
Full Bright Texture packs don't work with sodium

### ISSUE THREAD

**Issue by AnimishMahajan** [jellysquid3/Sodium#1377]
### Version information

fabric-loader-0.14.7-1.19

### Expected Behavior

Full Bright similar to version prior 1.19

### Actual Behavior

Full Bright texture packs do not work, when I removed sodium from my mod folder or used Vanilla minecraft it worked fine, but doesn't work with sodium.

### Reproduction Steps

**1. Adding a texture Pack** 
(I used multiple packs but achieved the same result. Use this for texting: 
https://www.curseforge.com/minecraft/texture-packs/fullbright
U can also try with the vanilla tweaks texture pack, link: https://vanillatweaks.net/picker/resource-packs/)
**2. Reloading textures**

### Java version

jdk-17.0.3.1

### CPU

11th Gen Intel Core i7 1165G7

### GPU

Intel Iris Xe Graphics

### Additional information

Other mods do not interfere in this case as I only had sodium in my mod folder and tested the texture pack.

**Comment by mikk357** [comment]
Are you sure it works on vanilla?
Judging by the structure of the resource pack, it does not look like
```
.
├── assets/minecraft/optifine/lightmap
│   ├── world-1.png
│   ├── world0.png
│   └── world1.png
├── pack.mcmeta
└── pack.png
```
\> `assets/minecraft/optifine`

**Comment by AnimishMahajan** [comment]
Yes, The texture pack in the second link(vanilla tweaks) works with vanilla minecraft but does not work with sodium.
The second texture pack(lightmap - the one your were referring to) works with mods like CIT resewn(mod) on fabric but stop when sodium is added in the mod folder. I use indium mod so that it works, all other custom textures load properly, but the fullbright stops working with sodium.

**Comment by AnimishMahajan** [comment]
Note : CIT Resewn and Indium mods were only added to test the lightmap texture pack as it requires optifine to function properly.
It worked as intended but stopped functioning when sodium was added.

**Comment by FxMorin** [comment]
I guess ill add this here: https://github.com/fxmorin/Configurable_FullBright
Seems sodium does not use the datapack resources for shaders

**Comment by jellysquid3** [comment]
Resource packs which modify "core shaders" in Minecraft will never work with Sodium, due to the fact that Sodium uses a _completely different_ shader system. We have no plans to fix it. You should try using a Fabric mod for modifying the in-game brightness instead of a resource pack, as these will generally work without issue.

**Comment by pheonix1331** [comment]
This mod works with Sodium. https://www.curseforge.com/minecraft/mc-mods/boosted-brightness

**Comment by MayCXC** [comment]
for anyone googling, this mod works with Sodium and supports custom lightmaps: https://github.com/kvverti/colormatic

**Comment by joseph123246** [comment]
on optifine go video settings then quality then turn on custom colors then load the brightness texture pack. for sodium theres not an option for this but you can install a mod called colormatic to fabric, download the version you want there is only 1.19 now but in the future there might be more versions drag into mods folder and launch your version of fabric with sodium and load your brightness resource pack it might not work with a pack like vanilla tweaks then use another full bright that corresponds with the version you using note:the pack must not be incompatible with the version you are using.
