### ISSUE TITLE
Sodium removes the line containing render distance information from the f3 debug menu

### ISSUE THREAD

**Issue by NotADinosaur** [jellysquid3/Sodium#1378]
### Version information

Minecraft 1.19 with sodium 0.4.2

### Expected Behavior

The f3 menu in vanilla
![63021256-B5C6-4002-A956-0A2B2F3B3FB3](https://user-images.githubusercontent.com/76700400/177248996-46ef6b86-98d0-4129-a509-746d2dfdeb13.jpeg)

### Actual Behavior

f3 menu with sodium
![0DB5CE1B-B85A-4C65-BF1A-A1939F0B63A8](https://user-images.githubusercontent.com/76700400/177249013-a3716381-b75f-4ccb-ac5a-790299fbce57.jpeg)

### Reproduction Steps

1: Load game without sodium
2: Look at f3 menu
3: Close game
4: Load game with sodium
5: Look at f3 menu
6: See that there is some information missing compared to vanilla

### Java version

Java 18.0.1

### CPU

intel i7-3770

### GPU

nvidia gtx 760

**Comment by jellysquid3** [comment]
This was fixed with #1868.
