### ISSUE TITLE
Sodium causing game to crash or freeze in background

### ISSUE THREAD

**Issue by tduck1equack** [jellysquid3/Sodium#1379]
### Version information

mc1.18.2-0.4.1+build.15

### Reproduction Steps

1. Put Sodium alongside Indium, Iris, Lithium, Reese's Options and Extras in 'mods' folder
2. Start the game
3. The game crashes or freezes in the background forever (unless stopped manually via Task Manager)

### Crash Report file

[crash-2022-07-06_18.27.11-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9054304/crash-2022-07-06_18.27.11-client.txt)

**Comment by pajicadvance** [comment]
Caused by Not Enough Crashes.
