### ISSUE TITLE
It isn't for Forge

### ISSUE THREAD

**Issue by imanairconditioner** [jellysquid3/Sodium#138]
This in my eyes is a big enough problem to be seen as an issue.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/36578995/88188090-60410c80-cc05-11ea-948d-87b786689e9b.png)

**Comment by jellysquid3** [comment]
It's a problem for you, not for me.

**Comment by ghost** [comment]
Issue-ception: this issue was labeled "bug" instead of "working as intended" ;p
