### ISSUE TITLE
Please add the resolution slider to the settings

### ISSUE THREAD

**Issue by naughtok** [jellysquid3/Sodium#1380]
**Is your feature request related to a problem? Please describe.**
Occasionally I get the problem where I'll update my graphics drivers or something and Minecraft will start running at 60hz again instead of my native 165hz. When that happens, tabbing in and out of Minecraft is extremally slow and there is a black screen for 5-10 seconds because it has to switch refresh rates. In order to fix this problem with Sodium installed, I have to remove Sodium and all the mods that depend on it from my mods folder, open Minecraft just to switch it from "1920x1080@60hz" to "1920x1080@165hz," and then add the mods back and relaunch Minecraft. Its kind of a pain, and I would assume to be a simple fix.
**Describe the solution you'd like**
My solution would be to just add the resolution slider to the settings, it would be nice to have.

**Comment by burgerindividual** [comment]
I'll mark this as planned for 0.5.0, but in the meantime, you can do Shift + P to bring up the vanilla menu.

**Comment by FlashyReese** [comment]
There is a PR for it, https://github.com/CaffeineMC/sodium-fabric/pull/957. Although it might be a bit out of date.

**Comment by naughtok** [comment]
> 

Oh I didn’t realize you could bring up the vanilla menu

**Comment by voltflake** [comment]
What's the status of implementing this slider? 0.5.0 was released a long time ago, maybe bump up issue priority?

**Comment by douira** [comment]
This issue and the other issue you commented on can be closed for being part of https://github.com/CaffeineMC/sodium-fabric/issues/46 which includes both of these aspects. https://github.com/CaffeineMC/sodium-fabric/issues/46 is implemented by the open PR https://github.com/CaffeineMC/sodium-fabric/pull/2296.
Edit: #46 has been closed with reasoning given in a comment there.
