### ISSUE TITLE
Sodium not providing desired fps boost.

### ISSUE THREAD

**Issue by vedshringarpure1709** [jellysquid3/Sodium#1382]
before I set up sodium, I was getting steady 50 fps. Upon setting sodium, there is a fps increase albeit a very small one, to 60 fps. Fps limiting is turned off, and even when I decrease the chunks to be loaded, it still stays at 60. Some help would be appreciated.
![image](https://user-images.githubusercontent.com/99486683/178057335-078dd742-db2a-4c22-8dfb-2e30b715e322.png)

**Comment by Creeper-banner** [comment]
sey vsync to off
