### ISSUE TITLE
Crash when joining a LAN world

### ISSUE THREAD

**Issue by Meeperty** [jellysquid3/Sodium#1385]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15.jar

### Reproduction Steps

Download Create Extra 1.0.1 from Modrinth (I used MultiMC)
Launch game
Join a LAN world

### Crash Report file

[crash-2022-07-11_11.13.45-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9086565/crash-2022-07-11_11.13.45-client.txt)

### Additional information

No errors in singleplayer

**Comment by jellysquid3** [comment]
Stale issue with no client log file. Update to the latest version of Sodium, and if you are still experiencing this, open a new issue.
