### ISSUE TITLE
Crash near y11.

### ISSUE THREAD

**Issue by Ironnoob73** [jellysquid3/Sodium#1386]
### Version information

mc1.16.5-0.2.0+build4

### Reproduction Steps

It's been around for no time, it's been working fine at first, and now it will crash when doing certain actions near the lava layer(y=11) (eg digging, skeletons falling themselves).

### Crash Report file

[crash-2022-07-15_21.03.25-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9121241/crash-2022-07-15_21.03.25-client.txt)
[crash-2022-07-15_21.06.58-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9121243/crash-2022-07-15_21.06.58-client.txt)
[crash-2022-07-15_21.15.30-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9121244/crash-2022-07-15_21.15.30-client.txt)
[crash-2022-07-15_21.21.06-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9121247/crash-2022-07-15_21.21.06-client.txt)

### Additional information

This happens on a server, and it's hard to reproduce in single-player.

**Comment by Kroppeb** [comment]
Can you check if the issue still happens without sodium or iris? Seems strange that they would be at fault here

**Comment by Ironnoob73** [comment]
> Can you check if the issue still happens without sodium or iris? Seems strange that they would be at fault here

No more crashes after removing sodium, sodium extra and iris.

**Comment by jellysquid3** [comment]
I do not see how Sodium could be causing this problem. Something must be interacting weirdly with it. If the problem still happens with the latest version of Sodium, then open a new issue.
