### ISSUE TITLE
Fog setting in lava conflict with origins mod

### ISSUE THREAD

**Issue by Flyvee** [jellysquid3/Sodium#1387]
### Version information

mc1.18.2-0.4.1+build.15

### Expected Behavior

By setting the power so that an origin can see under the lava, they should be able to see further while under the lava.

### Actual Behavior

If the fog setting is on anything except for default, then the lava vision does not work at all and the player can only a block if they are pressed against the block otherwise everything is covered in red fog.

### Reproduction Steps

1. Install the origins mod with an origin that has lava vision.
2. Set the fog setting to anything except for default.
3. Go into lava and see that you can barely see anything.

### Java version

Java 17

### CPU

Intel Core i7 860

### GPU

Nvidia RTX 2060

### Additional information

[pocket_dragon_origin_v3_1.zip](https://github.com/CaffeineMC/sodium-fabric/files/9125621/pocket_dragon_origin_v3_1.zip)
Origins
Extra Origins
Mob origins
Sodium extra
Reeses sodium options
![2022-07-16_13 06 20](https://user-images.githubusercontent.com/30793646/179352368-8a4d4eb3-7db7-4c06-8f27-a06960c8a720.png)
Fog level at default.
![2022-07-16_13 06 53](https://user-images.githubusercontent.com/30793646/179352379-237cf938-1278-4e5f-8ee7-adb3f095527f.png)
Fog level at 17

**Comment by MeeniMc** [comment]
Sodium doesn't have a fog option (beside culling control) this is presumably an issue with Sodium Extra.
