### ISSUE TITLE
Lava behind glass is darker with sodium

### ISSUE THREAD

**Issue by puppie1997** [jellysquid3/Sodium#1389]
### Version information

0.4.2

### Expected Behavior

Should be able to see lava through tinted glass
![image](https://user-images.githubusercontent.com/1692727/179437657-c6c04ed4-2361-4fee-a687-a6d4027e27f1.png)
![image](https://user-images.githubusercontent.com/1692727/179437985-ccaec948-1817-4e60-b2d8-12fdab7e94d4.png)

### Actual Behavior

The lava behind tinted glass appears much darker (almost black) with sodium.

### Reproduction Steps

install sodium and indium

### Java version

Version 8 Update 311 (or whatever goes with minecraft now)

### CPU

Ryzen 3700X

### GPU

GTX 2080S

### Additional information

I have 2 comparison pictures. I wouldnt have known the difference if my friend hadn't said theirs is brighter. The Lava should look way brighter than it is.

**Comment by Lolothepro** [comment]
#1005

**Comment by Lolothepro** [comment]
fixed

**Comment by piuvas** [comment]
should be closed as duplicate and/or fixed.
