### ISSUE TITLE
1.8.9 version

### ISSUE THREAD

**Issue by J4rdo** [jellysquid3/Sodium#139]
For online play a forge 1.8.9 version would be a very nice, as this is where I personally play the most but I am not sure if its quite possible since 1.8.9 is an entirely different version. Still would be a cool thing to look into

if forge is not an option just a non-forge version for 1.8.9 would be nice

**Comment by ghost** [comment]
1.8.9 is a vastly different version, containing an entirely diff rendering system & world system + this
![image](https://user-images.githubusercontent.com/36578995/88189040-9cc13800-cc06-11ea-84b1-19e0149220b4.png)

**Comment by jellysquid3** [comment]
It's not being considered. Please try to search before opening issues.
