### ISSUE TITLE
Running issues

### ISSUE THREAD

**Issue by gavinthestupo** [jellysquid3/Sodium#1394]
For some reason, sodium is set to run with the mc launcher, and when i try to open it with java, it won't work

**Comment by Oyssis** [comment]
What does "it won't work" means

**Comment by jellysquid3** [comment]
We aren't going to drill for information from users who skip through the issue templates and fail to provide even the most basic of information regarding their problem. This isn't a chat box -- open a new issue, fill out the relevant template, and upload a crash log.
