### ISSUE TITLE
Water rendering issue inside tubes made of stained glass

### ISSUE THREAD

**Issue by JaehaerysWise** [jellysquid3/Sodium#1395]
### Version information

Sodium mc1.18.2-0.4.1

### Expected Behavior

Water should be visible at all angles inside the glass

### Actual Behavior

A part of the water stream is not visible when looking at a specific angle

### Reproduction Steps

Build a water tube using stained glass and place flowing water inside.
See around the tube, at a certain angle from a small distance away, a part of the water viewed is not visible

### Java version

Java 17

### CPU

AMD Ryzen 7 5800 H 

### GPU

NVIDIA GeForce RTX 3060

### Additional information

Other related mod include continuity 2.0.0 and indium 1.0.3. The first screenshot taken disabled continuity resourcepacks, the second screenshot taken enabled continuity resourcepacks
![2022-07-20_19 31 40](https://user-images.githubusercontent.com/109792039/180401646-141dc216-f79b-4d69-9f22-95661abc8ff5.png)
![2022-07-20_19 11 51](https://user-images.githubusercontent.com/109792039/180401827-18f69ab5-3d9c-405c-9a38-0fa1e8b12c58.png)

**Comment by Oyssis** [comment]
#38
