### ISSUE TITLE
Named Entities names are gibberish

### ISSUE THREAD

**Issue by Piggygeek** [jellysquid3/Sodium#1397]
### Version information

sodium-fabric-mc1.19-0.4.2build.16

### Expected Behavior

The name should be legible (it should say bob)

### Actual Behavior

It is very not
![unknown](https://user-images.githubusercontent.com/44310383/180639054-1f247ff5-a078-424b-9170-ec0e99eb8ec8.png)

### Reproduction Steps

1. Use this [ModList.zip](https://github.com/CaffeineMC/sodium-fabric/files/9175406/ModList.zip)
2. Use this [Resource Pack List.zip](https://github.com/CaffeineMC/sodium-fabric/files/9175411/Resource.Pack.List.zip)
3. Name an entity

### Java version

Java 1.19

### CPU

AMD Ryzen 7 5800X 8-Core Processor                3.80 GHz

### GPU

AMD Radeon RX 6600 XT

**Comment by jellysquid3** [comment]
Not an issue with Sodium...
