### ISSUE TITLE
1.16-Snapshots version?

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#14]
The current version doesn't work on snapshots.
I'll provide a crash report if needed.

**Comment by eatmyvenom** [comment]
This is a clearly intended behavior as it is written for 1.15. Once more development has been done jelly will start to work on porting the mod to other game versions.

**Comment by ghost** [comment]
Oh nice,
huge thanks to @jellysquid3 for the mod.

**Comment by ghost** [comment]
Actually,
someone created a 1.16 fork of the mod:
https://github.com/mrmangohands/sodium-fabric
