### ISSUE TITLE
Support OpenGL 3

### ISSUE THREAD

**Issue by FortiethSwing61** [jellysquid3/Sodium#1400]
**Is your feature request related to a problem? Please describe.**
My game crashes because it uses an old OpenGL

**Describe the solution you'd like**
Add support to OpenGL 3

**Describe alternatives you've considered**
None

**Comment by Phoenix-Starlight** [comment]
You can use GLdown mod to solve the problem, but what minecraft version are you even trying to play on? (Some minecraft versions have limitations of OpenGL 3.2+ and more modern versions will push it up)

**Comment by FortiethSwing61** [comment]
1.18.2

**Comment by IMS212** [comment]
Sodium will not support devices supporting at least 3.3 (1.18) or 4.5 (1.19).
