### ISSUE TITLE
Stars do not render within the Sodium-Lithium-Indium-Phosphor suite.

### ISSUE THREAD

**Issue by melechdaviid** [jellysquid3/Sodium#1401]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16

### Expected Behavior

The stars should render when it is night.

### Actual Behavior

But, strangely, they don't render as they should. They only appear at sunrise and sunset!
![2022-05-10_10 04 15](https://user-images.githubusercontent.com/103229195/180815902-ece95293-cbfb-4a3c-9e93-149c502d9e40.png)

This image isn't actually of the issue itself (it was VanillaTweaks's Twinkling Stars pack not working correctly with Sodium) but it illustrates the point very well. 

### Reproduction Steps

1: Install Sodium (and possibly the other mods in the set)
2: Go to an existing world and look up at night.

### Java version

Java 16

### CPU

Intel Core i7-9750H

### GPU

Nvidia GEForce RTX 2060

**Comment by melechdaviid** [comment]
Oh, and yes, I determined that it wasn't my resource pack causing the issue.

**Comment by jellysquid3** [comment]
Are you _sure_ this issue only occurs with Sodium installed? We don't touch sky rendering, so it seems unlikely that it's causing the issue.

**Comment by pajicadvance** [comment]
This report is very old and the user hasn't provided any info since, so I will assume user error.
