### ISSUE TITLE
I believe Distant Horizons has an issue working when there isnt anything there.

### ISSUE THREAD

**Issue by WyLL-Code** [jellysquid3/Sodium#1405]
### Version information

DistantHorizons-1.6.7a-1.19

### Expected Behavior

The mod should recognize that there isnt anything there and account for that

### Actual Behavior

The chat is spammed with an error message that there was difficulty building the LOD "Lodbuilder encountered an error building lod"

### Reproduction Steps

Load into a world with nothing (or play on minehut servers which is what I did)
await

### Java version

Java 16

### CPU

Intel Core i5 7200U

### GPU

Intel HD Graphics 620

**Comment by Phoenix-Starlight** [comment]
I think you're filing it at the wrong place.

**Comment by KitCatzYeet** [comment]
Oh this happens to me too how to fix?

**Comment by oeddotdev** [comment]
How do you fix this, i have the same error

**Comment by Phoenix-Starlight** [comment]
This should probably be filed against distant horizons github, not here.

**Comment by MCRcortex** [comment]
This is distant horizons issue not sodium issue, please make the report there

**Comment by LuxLego** [comment]
I have to and i cannot read chat because it is spamming
