### ISSUE TITLE
Some tile entities produce more particles when reloaded

### ISSUE THREAD

**Issue by violine1101** [jellysquid3/Sodium#141]
### Expected Behavior
Campfires consistently produce the same amount of smoke.

### Actual Behavior
Every time a campfire is reloaded, it produces more smoke. When the world is completely reloaded, the campfire again produces the appropriate amount of smoke.

Might affect other particles too, haven't tested.

### Reproduction Steps
1. Place a campfire
2. Teleport into unloaded chunks
3. Teleport back
4. Repeat steps 2 and 3
→ At some point there's a lot of smoke coming from the campfire.

When breaking the campfire and placing another campfire in the same location, the issue continues to happen.

### Attachments
Here's a video: https://youtu.be/boqgWAhorSM

### Tested versions
The bug doesn't happen in vanilla 1.16.1, but it does happen with Sodium 0.1.0-fabric.

Also happens in 620f5a3669be298244bda70cb20cf2e1df8f53b9.

I'm using fabric version 0.9.0+build.204 (latest) and Minecraft version 1.16.1.

### System Information
- Java Version: 1.8.0_51 *and* 12.0.1
- CPU: Intel Core i7-3770 @ 3.40 GHz
- GPU: GeForce GTX 1050 Ti

**Comment by jellysquid3** [comment]
I have observed this issue with campfires producing way too much smoke in Sodium before, but I'm not sure what the issue is exactly. We might be adding the same tile entitiy renderer to the global render list multiple times. Beacons might also be affected, if so.

**Comment by Zailer43** [comment]
the same thing happens with the particles of the spawners
![image](https://user-images.githubusercontent.com/63565983/88857893-759dd400-d1cd-11ea-8038-678db823b308.png)

**Comment by OS-Void** [comment]
Not sure if this is related but,  I got 24,000 hoppers with composters on top of them, the game runs smoothly. But when I unload the chunks by teleporting away 1000 blocks, and returning the game is slightly laggier, if you keep repeat leaving the area and coming back the game becomes laggier and laggier, and I have to relog to fix the issue.

![2020-08-08_21 11 48](https://user-images.githubusercontent.com/5094754/89722980-92e95400-d9be-11ea-9146-d3fc884c8312.png)
![2020-08-08_21 13 15](https://user-images.githubusercontent.com/5094754/89722983-97157180-d9be-11ea-847c-3d5670f5e07c.png)

**Comment by 2No2Name** [comment]
After placing a single campfire in an empty world and flying back and forth a bit, the client world had 3 camp fire tile entities registed.

**Comment by 2No2Name** [comment]
It seems like the fix was simple, PR coming soon

**Comment by jellysquid3** [comment]
Merged into stable as 5af41c18.
