### ISSUE TITLE
MINECRAFT 1.19 SODIUM PROBLEM WITH WATER AND GLAS

### ISSUE THREAD

**Issue by Bobsonn** [jellysquid3/Sodium#1411]
### Version information

1.19 SODIUM

### Expected Behavior

NORMAL WATER

### Actual Behavior

![dowod 1](https://user-images.githubusercontent.com/110489967/182450272-f6d69493-caf8-49e2-b068-270d87413a94.PNG)
![dowod 2](https://user-images.githubusercontent.com/110489967/182450284-c9532777-78f4-4b3d-ac1e-50734225214c.PNG)

### Reproduction Steps

I do not know

### Java version

normal

### CPU

i5-7300hq

### GPU

nvidia gtx 1050

### Additional information

Hello, is there any patch or anything as of today that fixes the water visible in the attached screenshot? The soda versions are the latest.

![dowod 3](https://user-images.githubusercontent.com/110489967/182450792-b3a67a31-c4aa-45cb-b77c-3e677c647605.PNG)
![dowod](https://user-images.githubusercontent.com/110489967/182450803-990486fa-e7a2-465b-89ff-fb54e43922f4.PNG)

**Comment by LambdAurora** [comment]
This issue already was reported as #38. In addition to that you do not need to yell in issue titles, this is not a YouTube video.
