### ISSUE TITLE
Incompatability with memory leak fix? (reported to them, was sent here)

### ISSUE THREAD

**Issue by netcore10** [jellysquid3/Sodium#1413]
### Version information

Sodium mc1.19-0.4.2

### Expected Behavior

To launch.

### Actual Behavior

Launch crash

https://mclo.gs/SP06FcA

### Reproduction Steps

I have no idea.

### Java version

java 16

### CPU

i7 7700k

### GPU

GTX 1060 6gb

**Comment by Bluebulu998** [comment]
try fabric loader

**Comment by Bluebulu998** [comment]
![image](https://user-images.githubusercontent.com/85625300/182747693-34ce3c7c-be88-4500-b50d-f5c2b9d2e590.png)

**Comment by jellysquid3** [comment]
MemoryLeakFix is not supported and should not be used.
