### ISSUE TITLE
I can't see the custom graphs in F3

### ISSUE THREAD

**Issue by Guty18** [jellysquid3/Sodium#1415]
I used to be able to see the custom graphs in the F3 but now they don't appear, as if the mod wasn't working or they were disabled. But the video settings tab does work. 

Is there a button to turn them on? 

Thanks

**Comment by nhatsun** [comment]
i think u have to hold shift + f3 ?

**Comment by Timolino456** [comment]
You mean the fps and tps graph? That's alt + f3. The pie graph was either shift + f3 or ctrl +f3. Sodium does not change this.

**Comment by pajicadvance** [comment]
As mentioned already, Sodium doesn't modify the graphs of the alt + f3 menu, so it cannot possibly be the cause.
