### ISSUE TITLE
Sodium stopped working and freezes in loading screen after a pc crash

### ISSUE THREAD

**Issue by Krefcik** [jellysquid3/Sodium#1418]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16.jar

### Reproduction Steps

1. Put Sodium in "mods" folder
2. Start the game and join a private server 
3. Have a pc/laptop shut off while playing (in my case due to overheating laptop)
4. After turning pc/laptop on again, sodium won't work anymore, freezing on the loading screen forever

### Crash Report file

Can't receive a crash report file, due to closing the game via Task Manager
CurseForge log file:
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/9284129/latest.log)

### Additional information

java version: 17.0.4.0

Reinstalling sodium, java, minecraft itself, and upgrading java doesn't fix the issue
Older versions of Sodium stopped working as well

**Comment by jellysquid3** [comment]
See #899. It's a problem with graphics drivers. Sometimes it works, other times it doesn't.
