### ISSUE TITLE
Add it to other project

### ISSUE THREAD

**Issue by user84918342** [jellysquid3/Sodium#142]
I couldn´t find it... Sorry if it already was written anywhere?! But how coud I add this to my own mod? Changing something in build.gradle?

**Comment by Leo40Git** [comment]
Use https://jitpack.io. Ask in the Fabric Discord for more information.
Also, including something as transformative as Sodium in your mod is a really bad idea.

**Comment by user84918342** [comment]
But I guess as long as the version is also running in the IDE it should be fine

**Comment by user84918342** [comment]
Here is the answer by the way (for people in the future):

repositories {
  maven { url = "https://jitpack.io" }
}

dependencies {
  modImplementation "com.github.jellysquid3:sodium-fabric:1.16.x~dev-SNAPSHOT"
}
