### ISSUE TITLE
stuck on loading screen

### ISSUE THREAD

**Issue by 0x17s** [jellysquid3/Sodium#1423]
### Version information

mc.1.18.2-0.4.1+build.15

### Reproduction Steps

help

### Crash Report file

[tlauncher_08_16_2022_16_07_03.log](https://github.com/CaffeineMC/sodium-fabric/files/9348953/tlauncher_08_16_2022_16_07_03.log)

### Additional information

help

**Comment by Felix14-v2** [comment]
Pirated launchers are not supported. Especially such as dirty projects as fake TLauncher is.
