### ISSUE TITLE
Block Glitch

### ISSUE THREAD

**Issue by VigilantGamingYT** [jellysquid3/Sodium#1427]
### Version information

1.17.1

### Expected Behavior

to  break blocks normally like optifine

### Actual Behavior

whenever i break or place a block there is a slight issue with game it just reloads some chunks in middle of no where in like half a sec or something and i am a video creator and the holes and they doesn't feels good to have in videos its too bad can i get a fix for this bug if possible pls

### Reproduction Steps

break some blocks or place some blocks

### Java version

idk java version

### CPU

i3 10th gen

### GPU

intel uhd 

### Additional information

i cant express that thing in ss

**Comment by PhantomFran05** [comment]
Same happened to me in 1.19.2

**Comment by netflexy** [comment]
Same kind of shit

**Comment by pajicadvance** [comment]
Dupicate of #869.
