### ISSUE TITLE
A simple yet problematic crash

### ISSUE THREAD

**Issue by jaythewolfie** [jellysquid3/Sodium#1428]
### Version information

1.19

### Reproduction Steps

1: Simply break a block below a gravity affected block
2: The game crashes
![image](https://user-images.githubusercontent.com/72262057/185263092-6a5ca4ed-f234-4efe-84b1-6e07ad665791.png)

### Crash Report file

![image](https://user-images.githubusercontent.com/72262057/185263662-b0139d57-2174-4dea-b44a-3a38d27b8a83.png)
![image](https://user-images.githubusercontent.com/72262057/185264247-597f211b-2667-4975-b20e-3cc87548bc35.png)
![image](https://user-images.githubusercontent.com/72262057/185264292-95ef6713-2606-42ec-9b35-d8ef303e8046.png)
![image](https://user-images.githubusercontent.com/72262057/185264393-c03611fd-4177-4952-8959-0a3b9c4d66fc.png)
![image](https://user-images.githubusercontent.com/72262057/185264441-9bc3f9b2-ec1d-4f3e-80b3-6c323b73dcbb.png)

**Comment by PepperCode1** [comment]
Install Indium.
