### ISSUE TITLE
Minecraft crash when I open video settings

### ISSUE THREAD

**Issue by nicoschneiter** [jellysquid3/Sodium#1429]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16

### Reproduction Steps

1. Launch Minecraft
2. Click on the options
![image](https://user-images.githubusercontent.com/19336184/185284903-321b021e-e871-48f7-aa22-2608af7adcf0.png)
3. Click on Video Settings 
![image](https://user-images.githubusercontent.com/19336184/185284953-d2c863ca-6718-4fdf-8bcf-c27eae9fb400.png)
4. It shows the saving world screen 
![image](https://user-images.githubusercontent.com/19336184/185285103-ebdf866c-c997-4830-85ae-594f0490f54f.png)
5. Then it crashes and this is the error I get 
![image](https://user-images.githubusercontent.com/19336184/185285301-991fe57c-0827-4dee-8498-7dd7cffc32f7.png)

### Crash Report file

[crash-2022-08-17_20.16.16-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9367366/crash-2022-08-17_20.16.16-client.txt)

### Additional information

I may have some mods conflicting but here is the list
![image](https://user-images.githubusercontent.com/19336184/185285598-f5a0831b-1272-4638-8743-3765b548a75c.png)

**Comment by Naantam** [comment]
Ah yes, someone else who watches Xisumavoid. I'm actually getting the same or similar error.
[crash-2022-08-17_22.26.45-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9367407/crash-2022-08-17_22.26.45-client.txt)
.

**Comment by magneticflux-** [comment]
Your version of Reese's Sodium Options is for 1.16.5, not 1.19. You need to select the correct version. @FlashyReese maybe you can adjust the display on CurseForge to include this since it seems people are confused? Adding a version lock to `fabric.mod.json` would also display a pretty clear (IMO) error message about the wrong version of Minecraft being used.

**Comment by Naantam** [comment]
Oh really? https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options/download When you go here, it does not give you latest download it seems. You have to go to the recent releases instead to get latest. I guess myself and the other individual did the same derp and assumed the front page download button would give us latest and we didn't check its version. Whoops!

**Comment by Naantam** [comment]
Getting the latest from the recent releases fixed the issue on my client. Thank you @magneticflux-

**Comment by nicoschneiter** [comment]
@magneticflux- cheers man, lol it was the Xisumavoid video @Naantam

**Comment by FlashyReese** [comment]
> Your version of Reese's Sodium Options is for 1.16.5, not 1.19. You need to select the correct version. @FlashyReese maybe you can adjust the display on CurseForge to include this since it seems people are confused? Adding a version lock to `fabric.mod.json` would also display a pretty clear (IMO) error message about the wrong version of Minecraft being used.

I don't think that I can adjust the displayed version on CF manually, it just seems to use the latest upload as the version(CI publish failed for 1.16.5 hence it's on top) and I will add a version lock in the future versions to prevent this.
