### ISSUE TITLE
Sodium causes Minecraft to crash when using Java 8: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by violine1101** [jellysquid3/Sodium#143]
### Reproduction Steps
Launch current sodium dev version (1df506fd39dac56bb410725c245e6e51208ec732) with Java 8 (in my case, 1.8.0_51, the default Minecraft java version).

### Crash Report File
https://gist.github.com/violine1101/6094320e1d16691cf7943db35a1d0563

### Additional Information
Works properly with Java 12.0.1.

I should also note that while Java 8 is only installed as JRE, the Java 12 version is installed as JDK, this might also be it.

**Comment by amnotbananaama** [comment]
Duplicate of #16
