### ISSUE TITLE
1.18.2 Crash And i dont know why

### ISSUE THREAD

**Issue by FrancisUltra** [jellysquid3/Sodium#1431]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Reproduction Steps

in on the end city and building and the game suddenly crash

### Crash Report file

[crash-2022-08-20_12.10.23-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9386216/crash-2022-08-20_12.10.23-client.txt)
![2022-08-20_12 02 24](https://user-images.githubusercontent.com/107901826/185728464-1869b405-c4b8-4893-8b03-8fe14a5e39b0.png)

**Comment by Phoenix-Starlight** [comment]
Disable half the mods at a time until it works. It seems like one of the mods is making sodium crash.

**Comment by Lolothepro** [comment]
#1288
