### ISSUE TITLE
Game crashing when going into video settings on 1.19.2

### ISSUE THREAD

**Issue by Goomyeee** [jellysquid3/Sodium#1432]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16

### Reproduction Steps

1. Turn on minecraft
2. Click video settings
3. It crashes

### Crash Report file

[crash-2022-08-22_00.28.29-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9390173/crash-2022-08-22_00.28.29-client.txt)

### Additional information

i was using other mods with it if that helps (i linked screenshot)
also i tried deleting sodium-options.json but it didnt look corrupt anyway
![mods](https://user-images.githubusercontent.com/89744128/185815639-4328eb34-e5a9-4eb9-97d5-5b6ea9526df1.png)

**Comment by FlashyReese** [comment]
You literally have it highlighted in the image. Use the proper version for 1.19.2, unfortunately I can't do anything about CF displaying and download button going to the wrong version.

**Comment by Goomyeee** [comment]
Im actually so stupid how did i not see that lol

**Comment by Felix14-v2** [comment]
So, can be closed.
