### ISSUE TITLE
1.19 Sodium 0.4.2-build.16 freezes on splash screen

### ISSUE THREAD

**Issue by rayzchen** [jellysquid3/Sodium#1433]
### Version information

mc1.19-0.4.2+build.16

### Expected Behavior

Launch normally

### Actual Behavior

Freezes after loading a bit

### Reproduction Steps

Launch fabric with sodium

### Java version

Java 17

### CPU

Intel Core i5-3210M

### GPU

Intel HD Graphics 4000

**Comment by rayzchen** [comment]
Updating to 1.19.2 fixes this problem, but 1.19 does not work

**Comment by KerimPotter** [comment]
I have the same issue. The Java version, CPU and GPUs are same. But I'm using 1.19.2 and doesn't work. I didn't tested 1.19.

**Comment by KerimPotter** [comment]
When I switched my GPU to Nvidia Geforce gt620m, It's opens. @rayzchen If you have a external GPU, go to windows settings > search graphic settings. Select desktop app > browse > find javaw.exe > options > select your external GPU. I hope it solves your problem.

**Comment by pajicadvance** [comment]
Duplicate of #899.
