### ISSUE TITLE
Water not rendered when looking through some sides of stained glass.

### ISSUE THREAD

**Issue by SvatoplukCech** [jellysquid3/Sodium#1434]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16

### Expected Behavior

Water behind that stained glass should be rendered.
![image](https://user-images.githubusercontent.com/111923590/186278141-5de41325-51d0-45af-88e4-0527808c7cd0.png)

### Actual Behavior

Water behind stained glass is not rendered when you look through bottom side of the glass or through a vertical side touching air.
![Uploading image.png…]()

### Reproduction Steps

1. Make 1 block thick wall of light blue stained glass at least 3 blocks tall
2. Put water source blocks behind that wall touching the glass wall
3. Stand on the ground cca 1.5 blocks away from a corner of the wall facing towards the dry side of the wall
4. Look as shown in the photo
![image](https://user-images.githubusercontent.com/111923590/186289201-d8559f3b-cd34-4034-bb25-d63fd2f8675a.png)

### Java version

Java 17.0.3 64bit

### CPU

Intel Core i7–3610QM 2.30GHz

### GPU

NVIDIA GeForce GT 650M

### Additional information

![image](https://user-images.githubusercontent.com/111923590/186291299-3acf2d87-1fc7-405b-b90a-7d4d11918ba6.png)
There's a list of mods I used but I don't think they will interfere with anything. The only graphic mods I use is Iris and Sodium. Also I have all rendering turned off on Litematica if that matters.
Thank you so much for this amazing engine and for your work.

**Comment by IMS212** [comment]
#38
