### ISSUE TITLE
can't jojn test.2b2t.org

### ISSUE THREAD

**Issue by kdh8219** [jellysquid3/Sodium#1437]
### Version information

Sodium 0.4.1 for Minecraft 1.18.2 (+ mod menu mod)

### Expected Behavior

I can join the serevr

### Actual Behavior

I can't join the server
I think just the screen isn't showing.

### Reproduction Steps

1. multimc + 1.18.2 + Sodium 0.4.1 for Minecraft 1.18.2 (+ mod menu mod(Happens with or without))
2. join test.2b2t.org

### Java version

18.0.2(open jdk)

### CPU

i7-10750He

### GPU

gtx 1650 ti

### Additional information

[video on youtube (too big to upload to github)](https://youtu.be/LPFggNBNY6E)

**Comment by Phoenix-Starlight** [comment]
Possibly server fault, its possibly not sending chunks. Next please upload the log.

**Comment by kdh8219** [comment]
> Possibly server fault, its possibly not sending chunks. Next please upload the log.

where is the log?

**Comment by Phoenix-Starlight** [comment]
Which launcher?

**Comment by MagicJinn** [comment]
I have the exact same problem. I run a bunch of mods, and after taking out Sodium, it would join no problem. If you have Sodium installed, however, it would get stuck loading indefinitely.

I took the time to test it again myself today, and I can provide my game's log. I disabled all mods other than the Fabric API and Sodium.
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/9540983/latest.log)
![2b2t won't load](https://user-images.githubusercontent.com/72989508/189493978-ab4c57be-f153-4e64-ab84-31a0d8fe74bc.png)

**Comment by kdh8219** [comment]
> Which launcher?
> 
> On 9/9/22, kdh8219 ***@***.***> wrote:
> >> Possibly server fault, its possibly not sending chunks. Next please upload
> >> the log.
> >
> > where is the log?
> >
> > --
> > Reply to this email directly or view it on GitHub:
> > https://github.com/CaffeineMC/sodium-fabric/issues/1437#issuecomment-1242530349
> > You are receiving this because you commented.
> >
> > Message ID: ***@***.***>
> 

Multimc

**Comment by Phoenix-Starlight** [comment]
Can you upload a screenshot of what is rendered? (Assuming its just
not kicking you out with a message about your queue position)

@kdh8219
Edit Instance -> open .minecraft -> go to logs folder
Upload latest.log but you can choose to opt out if you want, since
there is already one such log of trying to join the server.

**Comment by kdh8219** [comment]
> Can you upload a screenshot of what is rendered? (Assuming its just not kicking you out with a message about your queue position) @kdh8219 Edit Instance -> open .minecraft -> go to logs folder Upload latest.log but you can choose to opt out if you want, since there is already one such log of trying to join the server.
> […](#)
> On 9/10/22, kdh8219 ***@***.***> wrote: > Which launcher? > > On 9/9/22, kdh8219 ***@***.***> wrote: > >> Possibly server fault, its possibly not sending chunks. Next please > >> upload > >> the log. > > > > where is the log? > > > > -- > > Reply to this email directly or view it on GitHub: > > [#1437 (comment)](https://github.com/CaffeineMC/sodium-fabric/issues/1437#issuecomment-1242530349) > > You are receiving this because you commented. > > > > Message ID: ***@***.***> > Multimc -- Reply to this email directly or view it on GitHub: [#1437 (comment)](https://github.com/CaffeineMC/sodium-fabric/issues/1437#issuecomment-1242825680) You are receiving this because you commented. Message ID: ***@***.***>

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/9541980/latest.log)

**Comment by kdh8219** [comment]
> Can you upload a screenshot of what is rendered? (Assuming its just
> not kicking you out with a message about your queue position)
> 
> @kdh8219
> Edit Instance -> open .minecraft -> go to logs folder
> Upload latest.log but you can choose to opt out if you want, since
> there is already one such log of trying to join the server.
> 
> On 9/10/22, kdh8219 ***@***.***> wrote:
> >> Which launcher?
> >>
> >> On 9/9/22, kdh8219 ***@***.***> wrote:
> >> >> Possibly server fault, its possibly not sending chunks. Next please
> >> >> upload
> >> >> the log.
> >> >
> >> > where is the log?
> >> >
> >> > --
> >> > Reply to this email directly or view it on GitHub:
> >> > https://github.com/CaffeineMC/sodium-fabric/issues/1437#issuecomment-1242530349
> >> > You are receiving this because you commented.
> >> >
> >> > Message ID: ***@***.***>
> >>
> >
> > Multimc
> >
> > --
> > Reply to this email directly or view it on GitHub:
> > https://github.com/CaffeineMC/sodium-fabric/issues/1437#issuecomment-1242825680
> > You are receiving this because you commented.
> >
> > Message ID: ***@***.***>
> 

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/9541980/latest.log)

**Comment by silversquirl** [comment]
Seems like you're just in a queue? You can see the chat messages at the bottom of the log.

Can you confirm this doesn't happen in vanilla?

**Comment by MagicJinn** [comment]
The problem is not nessecarily that you can't _join_ the server, but rather that it refuses to render.
I can join the server with no problems in vanilla/optifine/other mods.
![vanilla](https://user-images.githubusercontent.com/72989508/190459569-f2c09fb1-3a4a-4d84-9941-b75e7f490265.png)
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/9577265/latest.log)

**Comment by silversquirl** [comment]
Ahh so the issue is that vanilla moves from loading screen to game at a different point than Sodium. Interesting.

**Comment by MagicJinn** [comment]
That's a way you could word it, but in all my testing, I never got out of the loading terrain bit. I'll give it some more time later.

**Comment by JustZvan** [comment]
Also happens on the "main" server

**Comment by JustZvan** [comment]
Oh,
installing FastLoad will fix it

**Comment by SandSeppel** [comment]
> Oh, installing FastLoad will fix it

Got the same problem, but this isn't fixing it for me.

**Comment by JustZvan** [comment]
Yeah, for me it broke

**Comment by JustZvan** [comment]
But if you look at the console it is connected.

**Comment by jellysquid3** [comment]
I'm not going to wait multiple hours to join a server (or spend money on a priority queue) just so that I can debug/fix the issue.
