### ISSUE TITLE
Tab navigation in Video Settings

### ISSUE THREAD

**Issue by KabanFriends** [jellysquid3/Sodium#1439]
**Is your feature request related to a problem? Please describe.**
The Video Settings menu in Sodium cannot be nagivated with Tab key, whereas in vanilla Minecraft menu you can fully navigate through the options menu with Tab key.

**Describe the solution you'd like**
Pressing the Tab key should cycle through buttons and options on the screen, and enter to select.

**Comment by KabanFriends** [comment]
Related? #1633

**Comment by pajicadvance** [comment]
Fixed by PR #1633
