### ISSUE TITLE
Hitboxes and particles don't render

### ISSUE THREAD

**Issue by violine1101** [jellysquid3/Sodium#144]
### Expected Behavior
Hitboxes (of blocks, entities, and structure blocks) and particles should render.

### Actual Behavior
In the latest dev version (1df506fd39dac56bb410725c245e6e51208ec732), they don't, regardless of your settings.

### Attachments
![2020-07-22_17 22 16](https://user-images.githubusercontent.com/12451842/88195161-fc880500-cc3f-11ea-8ec7-da86b3080f53.png)

### Tested versions
The bug doesn't happen in vanilla 1.16.1 and Sodium 0.1.0-fabric.

It doesn't happen in 620f5a3669be298244bda70cb20cf2e1df8f53b9 and therefore was introduced in 1df506fd39dac56bb410725c245e6e51208ec732.

I'm using fabric version 0.9.0+build.204 (latest) and Minecraft version 1.16.1.

### System Information
- Java Version: 1.8.0_51 *and* 12.0.1
- CPU: Intel Core i7-3770 @ 3.40 GHz
- GPU: GeForce GTX 1050 Ti

**Comment by fsharpseven** [comment]
I cannot reproduce this on `1df506df` with fast or fancy graphics selected. However, this is the case with fabulous.

**Comment by mrmangohands** [comment]
From the abandoned 1.16.x/dev branch, not relevant to current development.
