### ISSUE TITLE
Movement jitter

### ISSUE THREAD

**Issue by Fabian42** [jellysquid3/Sodium#1441]
### Version information

mc1.19.2-0.4.3+build.17

### Actual Behavior

When walking or moving the camera, the entire view jitters back and forth. This did not happen with the `mc1.19-0.4.2+build.16` version. A video and my standard settings file are below. I only changed the render distance to 2 after starting the game.

Video: https://cdn.discordapp.com/attachments/173877869640941568/1013411512796336289/video.mp4
Settings: https://drive.google.com/file/d/1PYKBqIzoykUqJCmdFCHdXPmxI4CQzk91

### Java version

17.0.3 64bit

### CPU

8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

### GPU

NVIDIA GeForce GTX 1050/PCIe/SSE2

### Additional information

Other mods:
```
* boosted-brightness-2.1.2+1.19
* clear-skies-fabric-mc119-2.0.94
deathlog-0.2.10+1.19
durabilityviewer-1.19.1-fabric0.58.5-1.10.3
fabric-api-0.60.0+1.19.2
lazydfu-0.1.3
* litematica-fabric-1.19.2-0.12.4
malilib-fabric-1.19.2-0.13.0
minihud-fabric-1.19.2-0.23.3
* NoFog-1.3.1_1.16.5-1.19.2-fabric
rebind-all-the-keys-1.2.0-beta.1+1.19
```
*=These do rendering stuff, but I highly doubt that they conflict.

**Comment by Quagliada3kg** [comment]
same problem. i thought it was a screen problem, so i change screen, but nothing. then i took off and reinserted all mods one by one and only sodium from this problem

**Comment by IMS212** [comment]
Try turning off Adaptive Sync in Video Settings.

**Comment by Quagliada3kg** [comment]
or use the mc1.19-0.4.2 version

**Comment by Fabian42** [comment]
> Try turning off Adaptive Sync in Video Settings.

VSync, yes, that helps. Thanks!

**Comment by Fabian42** [comment]
What? No, it's not fixed! Sodium completely breaks VSync in the latest version!

**Comment by IMS212** [comment]
We are aware of this, a hotfix will be coming in 0.4.4.

(Meant to post this, not close.)

**Comment by PweSol** [comment]
You should also really consider changing the FPS increments from 10 to 1. There is no logical reason as to why it should by anything but 1 (or even more precise than that for power users) if it doesn't break any sodium functionality. 

Even this issue of movement jitter can be the result of limiting the FPS increments to only 10 (to a certain extend).

For the optimal VRR usage, the user should set their maximum FPS to be 3 below their monitor's refresh rate (57 FPS for 60Hz, 72 for 75, 117 for 120, etc.). While having V-Sync enabled, as AS won't kick in if it isn't enabled. Stutters and jitters can be a result of improper usage of this technology, especially on lower refresh rate monitors and older/lower quality AS implementations.

**Comment by IMS212** [comment]
It doesn’t break Sodium functionality, rather it breaks Vanilla functionality. Vanilla does validation to make sure it’s a multiple of 10. We can remove this, however we don’t think we should at the moment,

**Comment by PweSol** [comment]
> It doesn’t break Sodium functionality, rather it breaks Vanilla functionality. Vanilla does validation to make sure it’s a multiple of 10. We can remove this, however we don’t think we should at the moment,

I see, thanks for the quick reply.

I've tested multiple times running minecraft with sodium with the FPS multiple of 1, such as 57 FPS on 60Hz monitor (as I described earlier), and I haven't observed any negative impacts. The only impacts I managed to observe and measure were the expected positive results from limiting the FPS to 3 below refresh rate (as I described earlier). However, those were tests done for a short period of time. My main monitor (with which I play/test minecraft the most) is a 240Hz one, where unlimited FPS and no V-Sync is preferred (stutters are way beyond human perceivability at that point, and you get the quickest response time).

**Comment by Teh404Gal** [comment]
i think this bug is back with sodium 0.5 since before updating vsync worked perfectly making my gameplay smoother, now it makes it heavily jitter so much its nauseating, im now playing with it disabled but its still not as smooth as it was, im using an nividia 1050 mobile with driver 525 with debian linux, PRIME-d, i tried recording it but gnome's screenshare wont record without making everything jitter

**Comment by hexadecimal233** [comment]
> i think this bug is back with sodium 0.5 since before updating vsync worked perfectly making my gameplay smoother, now it makes it heavily jitter so much its nauseating, im now playing with it disabled but its still not as smooth as it was, im using an nividia 1050 mobile with driver 525 with debian linux, PRIME-d, i tried recording it but gnome's screenshare wont record without making everything jitter

You can create an new issue if the problem still exists.
