### ISSUE TITLE
Crash on world startup

### ISSUE THREAD

**Issue by jakeklong** [jellysquid3/Sodium#1443]
### Version information

MC Java v1.19.2 fabric loader v0.14.9

### Reproduction Steps

start a world. when starting a world, it gets to 100 percent and then it crashes every time.

### Crash Report file

[crash-2022-08-28_13.34.10-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9440198/crash-2022-08-28_13.34.10-client.txt)

**Comment by IMS212** [comment]
A full log is needed

**Comment by jakeklong** [comment]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-08-28 13:34:10
Description: Unexpected error

java.lang.RuntimeException: Shader compilation failed, see log for details
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:534)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:47)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:18307)
	at net.minecraft.class_761.method_22710(class_761.java:1246)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$dmo000$redirectRenderingWorld(class_757.java:3650)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.shader.GlShader.<init>(GlShader.java:34)
	at me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader.loadShader(ShaderLoader.java:534)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.createShader(ShaderChunkRenderer.java:47)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.compileProgram(ShaderChunkRenderer.java:38)
	at me.jellysquid.mods.sodium.client.render.chunk.ShaderChunkRenderer.begin(ShaderChunkRenderer.java:72)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:70)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:221)
	at net.minecraft.class_761.method_3251(class_761.java:18307)
	at net.minecraft.class_761.method_22710(class_761.java:1246)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.redirect$dmo000$redirectRenderingWorld(class_757.java:3650)

-- Affected level --
Details:
	All players: 1 total; [class_746['I_Meow_So_Hard'/254, l='ClientWorld minecraft:overworld', x=-10.50, y=84.00, z=-43.50]]
	Chunk stats: Client Chunks (ImmPtl) 5
	Level dimension: minecraft:overworld
	Level spawn location: World: (-16,89,-48), Section: (at 0,9,0 in -1,5,-3; chunk contains blocks -16,-64,-48 to -1,319,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 29 game time, 29 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, lambdabettergrass/default, Everycomp Generated Pack, Supplementaries Generated Pack, loadmyresources.hiddenpack, Stay_True_1.19.zip, continuity/glass_pane_culling_fix, continuity/default, __MoreMcmeta Internal__

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2476509600 bytes (2361 MiB) / 5905580032 bytes (5632 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 24
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor            
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2216
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37556.98
	Virtual memory used (MB): 16197.25
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionalstructures: Additional Structures 4.1.0
		adorn: Adorn 3.6.1+1.19
		another_furniture: Another Furniture 2.0.3-1.19.2
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 6.2.43
		attributefix: AttributeFix 17.1.2
		auudio: Auudio 1.0.3
		axolotlitemfix: Axolotl Item Fix 1.1.3
		badpackets: Bad Packets 0.2.0
		balm-fabric: Balm 4.5.2+0
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bclib: BCLib 2.1.0
		betteradvancements: Better Advancements 0.2.2.142
		betterend: Better End 2.1.0
		betternether: Better Nether 7.1.0
		biomemakeover: Biome Makeover 1.19.2-1.5.12
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		bookshelf: Bookshelf 16.1.4
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.2-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		bountiful: Bountiful 3.0.0
		byg: Oh The Biomes You'll Go 2.0.0.9
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		carrier: Carrier 1.11.0
		cem: Custom Entity Models 0.7.1
		charm: Charm 4.2.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0+1.19.2
		cherishedworlds: Cherished Worlds 6.0.1+1.19.2
		citresewn: CIT Resewn 1.1.1+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		cloth-config: Cloth Config v8 8.0.75
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.50
			fiber: fiber 0.23.0-2
		comforts: Comforts 6.0.0+1.19.2
			spectrelib: SpectreLib 0.8.1+1.19
		completeconfig: CompleteConfig 2.0.0
			coat: Coat 1.0.0-beta.17+mc22w17a
			completeconfig-base: completeconfig-base 2.0.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0
			completeconfig-gui-coat: completeconfig-gui-coat 2.0.0
		continuity: Continuity 2.0.1+1.19
		crawl: Crawl 0.11.0
			mm: Manningham Mills 2.3
		croptopia: Croptopia 2.1.0
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		darkpaintings: DarkPaintings 13.1.2
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.5.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
		decorative_blocks: Decorative Blocks 3.0.0
		deepslatecutting: Deepslate Cutting 1.4.0
		dragonloot: DragonLoot 1.1.2
		dungeons_arise: When Dungeons Arise 2.1.51
		easymagic: Easy Magic 4.3.2
		echoingdepths: Echoing Descent 1.0.0-1.19.2
		ecologics: Ecologics 2.1.9
		edenring: EdenRing 0.6.4
		elytraslot: Elytra Slot 6.0.0+1.19.2
		enchdesc: EnchantmentDescriptions 13.0.1
		entity_texture_features: Entity Texture Features 4.0.2
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		everycomp: Every Compat 1.19.2-2.0.4
		exlinefurniture: Exline's Furniture 2.3.0
		extended_armor_bars: Extended Armor Bars 1.2.1
		fabric-api: Fabric API 0.60.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.11+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.9+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.17+aeb40ebe90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.20+aeb40ebe90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.1+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.11+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.7+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.28+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.34+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.3+aeb40ebe90
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.1+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.5+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.8+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.30+aeb40ebe90
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.18+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.28+aeb40ebe90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.28+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.21+aeb40ebe90
			fabric-item-api-v1: Fabric Item API (v1) 1.5.7+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.28+aeb40ebe90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.20+aeb40ebe90
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.18+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.2+aeb40ebe90
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.3+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.6+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.3+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.14+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.17+aeb40ebe90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.4+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.21+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.11+aeb40ebe90
			fabric-particles-v1: Fabric Particles (v1) 1.0.10+aeb40ebe90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.24+aeb40ebe90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.10+aeb40ebe90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.12+aeb40ebe90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.20+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.14+aeb40ebe90
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.7+aeb40ebe90
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.22+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.16+aeb40ebe90
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.11+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.1+aeb40ebe90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.26+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.13+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.20+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.11+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.0+42d99c3290
		fabric-language-kotlin: Fabric Language Kotlin 1.8.3+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.0
		fabricloader: Fabric Loader 0.14.9
		fallingleaves: Falling Leaves 1.12.2+1.19.2
		fallingtree: FallingTree 3.9.2
		farmersdelight: Farmer's Delight 1.19-1.3.3
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 4.2.3
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		frame: Frame 0.26.1+1.19-fabric
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		friendsandfoes: Friends&Foes 1.5.6
		fwaystones: Fabric Waystones 3.0.3+mc1.19.2
			pinlib: PinLib 0.1.3+1.19
		galosphere: Galosphere 1.19.1-1.1.2
		geckolib3: Geckolib 3.1.17
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.5
		goblintraders: Goblin Traders 1.5.2
		goodall: Goodall 1.1.1
		iceberg: Iceberg 1.0.46
		immersive_portals: Immersive Portals 2.2.0
			imm_ptl_core: Immersive Portals Core 2.2.0
			q_misc_util: QMiscUtil 2.2.0
		indium: Indium 1.0.8+mc1.19.2
		inmis: Inmis 2.7.0-1.19
			omega-config: OmegaConfig 1.2.3-1.18.1
		iris: Iris 1.2.7
			org_anarres_jcpp: jcpp 1.4.14
		itemmodelfix: Item Model Fix 1.0.3+1.19
		jamlib: JamLib 0.4.4
		java: OpenJDK 64-Bit Server VM 17
		kambrik: Kambrik 4.0-1.19.2
		kleeslabs: KleeSlabs 12.1.0
		konkrete: Konkrete 1.5.0
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lambdabettergrass: LambdaBetterGrass 1.3.0+1.19
			spruceui: SpruceUI 4.0.0+1.19
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.8.3
		loadmyresources: Load My Resources 1.0.1
		magnumtorch: Magnum Torch 4.2.0
		mavm: More Axolotl Variants Mod 1.1.0
		mcwdoors: Macaw's Doors 1.0.7
		mcwfences: Macaw's Fences and Walls 1.0.6
		mcwlights: Macaw's Lights and Lamps 1.0.4
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.1
		mcwtrpdoors: Macaw's Trapdoors 1.0.7
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		midnightlib: MidnightLib 0.6.0
		minecraft: Minecraft 1.19.2
		modid: Creatures Of The Snow 2.4.2+1.19.2
		modmenu: Mod Menu 4.0.6
		moonlight: Moonlight 1.19.2-2.0.23
		more_babies: More Babies 0.5.4
		moremcmeta: MoreMcmeta 1.19-3.0.5
		morevillagers: More Villagers 4.0.2
		mousetweaks: Mouse Tweaks 2.22
		mvs: Vanilla Structure Mod 2.5.8
		naturalist: Naturalist 2.1.1
		naturescompass: Nature's Compass 1.19.2-2.0.4-fabric
		nears: Nears 1.2.3
		notenoughanimations: NotEnoughAnimations 1.6.1
		onsoulfire: On Soul Fire 1.19-2
		openloader: OpenLoader 15.0.1
		optigui: OptiGUI 1.1.1
			org_apache_commons_commons-text: commons-text 1.9
		oxidized: Oxidized 1.7.2
		paintings: Paintings++ 10.2.0.0
		patchouli: Patchouli 1.19.2-76-FABRIC
		polymorph: Polymorph 0.45.0+1.19.2
		puzzle: Puzzle 1.4.0-1.19
			puzzle-base: Puzzle Base 1.4.0-1.19
			puzzle-gui: Puzzle GUI 1.4.0-1.19
			puzzle-models: Puzzle Models 1.4.0-1.19
			puzzle-splashscreen: Puzzle Splash Screen 1.4.0-1.19
		puzzleslib: Puzzles Lib 4.2.4
		reeses-sodium-options: Reese's Sodium Options 1.4.7+mc1.19.2-build.59
		repurposed_structures: Repurposed Structures 6.1.1+1.19
		rightclickharvest: Right Click Harvest 3.0.1
		roughlyenoughitems: Roughly Enough Items 9.1.530
			error_notifier: Error Notifier 1.0.9
		roughlyenoughprofessions: Roughly Enough Professions 1.1.1
		roughlyenoughresources: Roughly Enough Resources 2.6.0
		skinlayers: 3d Skin Layers 1.5.1-mc1.19.1
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.3+build.17
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.9+mc1.19.2-build.60
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spirit: Spirit 2.1.12
		starlight: Starlight 1.1.1+fabric.ae22326
		starterkit-fabric: Starter Kit (Fabric) 3.7
		structory: Structory 1.0.1
		supplementaries: Supplementaries 1.19.2-2.0.15
		terrablender: TerraBlender 2.0.1.125
		thonkutil: ThonkUtil 2.15.4+1.19
			thonkutil-base: ThonkUtil Base 1.13.2+4a8c408a57
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.4.2+3eb2749857
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.1.2+8ff533c957
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.1.2+8ff533c957
			thonkutil-legacy: ThonkUtil Legacy 1.1.2+5d4263f557
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.1.3+bd4b387957
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.5.2+8ff533c957
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.2.2+8ff533c957
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.2.2+8ff533c957
		tipsmod: Tips 8.0.1
		toms_storage: Tom's Simple Storage Mod 1.3.5
		toolstats: ToolStats 12.0.2
		trinkets: Trinkets 3.4.0
		twigs: Twigs 2.0.0-beta.9+1.19-fabric
		universal_ores: Universal Ores 1.4.2
		villagernames: Villager Names 4.0.6
		visuality: Visuality 0.5.1
		voidtotem: Void Totem 2.1.0
		windchimes: Windchimes 1.2.1
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		woof: Woof 1.1.2-1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		xaerominimap: Xaero's Minimap 22.13.2
		xaeroworldmap: Xaero's World Map 1.26.6
		xp_storage: XP Storage 1.4.3+1.19
		xp_storage_trinkets: XP Storage - Trinkets 0.1+1.19
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.59, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, lambdabettergrass/default, Everycomp Generated Pack, Supplementaries Generated Pack, loadmyresources.hiddenpack (incompatible), file/Stay_True_1.19.zip, continuity/glass_pane_culling_fix, continuity/default
	Current Language: English (US)
	CPU: 24x AMD Ryzen 9 5900X 12-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['I_Meow_So_Hard'/254, l='ServerWorld minecraft:overworld New World', x=-10.50, y=84.00, z=-43.50]]
	Data Packs: vanilla, Fabric Mods, Everycomp Generated Pack, Supplementaries Generated Pack, loadmyresources.hiddenpack (incompatible)
	World Generation: Stable
[crash-2022-08-28_13.34.10-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9440377/crash-2022-08-28_13.34.10-client.txt)

**Comment by IMS212** [comment]
That's still not a full log...
We need a upload (not a copy/paste) of the file named latest.log in the logs folder.

**Comment by jakeklong** [comment]
[crash-2022-08-28_16.18.10-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9440508/crash-2022-08-28_16.18.10-client.txt)
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/9440509/latest.log)


sorry about that!

**Comment by IMS212** [comment]
Seems like an Immersive Portals conflict.

**Comment by TheSnowyChickens** [comment]
Is it possible that your bug is like this crash ?
(I can't load in a world ²)

![grafik](https://user-images.githubusercontent.com/29357962/187532651-12f421cf-c35b-4f93-9c8e-b6ad88106986.png)

**Comment by IMS212** [comment]
Update Immersive Portals.

**Comment by Giro798** [comment]
Thank you, you do not know the days that I spent with this error
