### ISSUE TITLE
Flashing light on bottom half of screen in fullscreen

### ISSUE THREAD

**Issue by AidanMcMahan** [jellysquid3/Sodium#1444]
### Version information

mc1.19.2-0.4.3+build.17

### Expected Behavior

The game should run without flashing lights on the screen

### Actual Behavior

When I opened the game. I had a red flashing on the title screen, and it changed to black when I entered a world. I only had the issue when playing in fullscreen

### Reproduction Steps

Default profile installation on fabric installer 0.11.0
All mods in folder:
fabric-api-0.60.0+1.19.2
sodium mc1.19.2-0.4.3+build.17

I attached a video of the issue. I just used my phone since I don't have any capture software.
https://www.icloud.com/photos/#05folHvJY0L9n6iU9EzV7f-rg 
Here's an icloud link to download the video

### Java version

Java 17

### CPU

AMD Ryzen 7 4700U with Radeon Graphics 2.00 GHz

### GPU

Intel UHD Graphics Integrated DirectX 12.1

### Additional information

This is my first time downloading fabric so I don't know a whole lot about it. I put the names of the mods in my folder and a video of the issue in the reproduction steps section. All I have is fabric API and sodium.

**Comment by Oyssis** [comment]
update to 0.4.4 this has been fixed

**Comment by silversquirl** [comment]
@AidanMcMahan do you still experience this issue with the latest version of Sodium?

**Comment by AidanMcMahan** [comment]
@silversquirl No it's been resolved in the latest update for me
