### ISSUE TITLE
MC-167146

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#1446]
### Version information

***

### Expected Behavior

That there is no Z Fighting

### Actual Behavior

the Ender Dragon's wings have Z-fighting

### Reproduction Steps

Install Classic Faithful
Spawn an Ender Dragon

### Java version

Java 17

### CPU

Ryzen AMD 1600

### GPU

GTX 1070

### Additional information

https://bugs.mojang.com/browse/MC-167146
Could this be fixed in Sodium?

**Comment by silversquirl** [comment]
Sodium doesn't often fix vanilla bugs unless there are performance improvements from doing so, but I'll leave this open for the maintainers to decide
