### ISSUE TITLE
Rendering does not update on servers until chunks are reloaded manually

### ISSUE THREAD

**Issue by dopadream** [jellysquid3/Sodium#1447]
### Version information

0.5.0+mc1.19.2-unstable

### Expected Behavior

When blocks are updated, such as broken, placed, moved, ect, the renderer should update to reflect this

### Actual Behavior

Blocks do not update, so if you break a block, it'll still appear until the chunk is reloaded manually for example

### Reproduction Steps

1. Join a multiplayer server (that has lithium and phosphor)
2. break, place, or move a block
3. observe in awe as the block does not update visually

### Java version

Java 18

### CPU

Intel Core i9-9900k

### GPU

RTX 2080ti

### Additional information

1.19.2 quilt with qfapi

**Comment by Phoenix-Starlight** [comment]
Upload logs please.

**Comment by dopadream** [comment]
fixed
