### ISSUE TITLE
My pc doesn’t like it???

### ISSUE THREAD

**Issue by IntrepidBlade** [jellysquid3/Sodium#1449]
I have a mid tier pc, Renee’s on Amazon and I upgraded to 20 ram. But for some reason most of the time sodium will not launch, I have no idea why. If you need the specs of the pc, this is the exact one I have but with upgraded ram. https://www.amazon.com/dp/B01CV9G1BO/ref=tsm_1_tp_tc

**Comment by Lucario4LyfeYT** [comment]
Try 2 things, upgrading your storage (from hdd to ssd) and installing a gpu (for your pc, as far as I know, it should take low profile cards
An example of a decent card thats low profile from amazon
https://a.co/d/9ibYHcG

**Comment by Lucario4LyfeYT** [comment]
You could also try updating java (what minecraft runs on) if that doesn't work, I would suspect it to be a gpu issue (which, I already suspected lol)

**Comment by IntrepidBlade** [comment]
I needed to update my graphics drives, which worked. But I do have a question. I’m play mcci now, it’s a cool server but has a bug texture pack that reduces fps, would that gpu u recommend help with my fps?

**Comment by Lucario4LyfeYT** [comment]
Yeah, it would help alot, if you get a gpu, remember to install its drivers or it wont be working at its best

**Comment by jellysquid3** [comment]
This is not a support forum... use the [Discord server](https://jellysquid.me/discord) for that. The problem was likely caused by #899, which upgrading the graphics drivers will fix.
