### ISSUE TITLE
Option to turn off biome blend smoothing

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#1450]
**Is your feature request related to a problem? Please describe.**
This is somewhat of an inconsistency.

**Describe the solution you'd like**
There should be an option somewhere in Video Settings that disables the interpolation of biome colors, much like vanilla's option to turn off smooth lighting.

**Describe alternatives you've considered**
N/A

**Additional context**
![2022-09-03_23 18 06](https://user-images.githubusercontent.com/52297970/188289350-381df60a-3007-4dc7-b1dd-5331dab4f7d4.png)

**Comment by silversquirl** [comment]
I'm not sure I understand this feature request - isn't there already a slider for biome blending that lets you turn it off? Or are you asking for an option to keep biome blending on, but make it look "blocky" like non-smooth lighting is?

**Comment by muzikbike** [comment]
The latter is what I'm looking for here.

**Comment by silversquirl** [comment]
This doesn't seem like something in Sodium's scope as vanilla doesn't have that option - maybe ask the dev of Sodium Extra?
I'll leave this open for the maintainers to make the final decision on though.

**Comment by FlashyReese** [comment]
Setting `Quality > Biome Blend` to `0` is "blocky" like non-smooth lighting.
![image](https://user-images.githubusercontent.com/30311066/188324729-97aa9349-e189-476a-8783-86a2f78d6905.png)

**Comment by silversquirl** [comment]
I think they still want biome blend, just not blended over the block faces. So a gradual transition over multiple blocks, but no blending within the blocks.

**Comment by FlashyReese** [comment]
I assume they want something like this 
![image](https://user-images.githubusercontent.com/30311066/188329232-2c5b6b15-a654-474c-99c7-2cdc1b854d93.png)

**Comment by muzikbike** [comment]
The above image is exactly what I'm requesting here, yes.

**Comment by muzikbike** [comment]
Another effect of the intra-block biome interpolation is that it seems to make the effects of the Ambient Environment mod (which varies colors within biomes) a bit harder to see, since the colors don't pop against each other quite as much.

"Vanilla", biome blending off:
![2022-09-12_23 25 15](https://user-images.githubusercontent.com/52297970/189769473-70bdd113-e421-45e7-ab7a-ca226f75e073.png)

"Vanilla", one block of biome blending:
![2022-09-12_23 24 56](https://user-images.githubusercontent.com/52297970/189769503-5e5883d0-957c-4629-8194-e714311c1ffd.png)

Ambient Environment, biome blending off (not a recommended setting, but shown here for comparison):
![2022-09-12_23 17 46](https://user-images.githubusercontent.com/52297970/189769571-05ed4da8-0c44-42c5-82b1-61b61bfe4d7d.png)

Ambient Environment, one block of biome blending:
![2022-09-12_23 21 32](https://user-images.githubusercontent.com/52297970/189769603-1feed497-f2e8-4299-9de1-ebb3218de954.png)

Ambient Environment, one block of biome blending plus Sodium's added smoothing:
![2022-09-12_23 17 37](https://user-images.githubusercontent.com/52297970/189769638-43722aac-9d38-4699-9c4c-eb6fa05e46dd.png)
