### ISSUE TITLE
BlockTextures

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [jellysquid3/Sodium#1452]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Expected Behavior

Regular minecraft

### Actual Behavior

When I break a block, for 1-2 seconds all the blocks lose their texture and only the entities are visible

### Reproduction Steps

I download fabric api and sodium, nothing else and try break blocks

### Java version

Java 18

### CPU

Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 CPUs), ~1.2GHz

### GPU

Intel(R) UHD Graphics

**Comment by Phoenix-Starlight** [comment]
Could you list your video settings?

**Comment by MIPOHBOPOHIH** [comment]
> Could you list your video settings?
![2022-09-18_16 11 31](https://user-images.githubusercontent.com/98014624/190903838-b0ae0132-3418-44cd-b368-ae7f4d914c52.png)
![2022-09-18_16 11 33](https:/
![2022-09-18_16 11 24](https://user-images.githubusercontent.com/98014624/190903844-a3cf2fc4-8886-4211-b84e-ecccdea367b2.png)
![2022-09-18_16 11 29](https://user-images.githubusercontent.com/98014624/190903847-42b928c4-968f-457d-a46c-478587f4b47b.png)
/user-images.githubusercontent.com/98014624/190903839-a4166bb6-7099-4716-9c11-8bb85b45ae50.png)

**Comment by Phoenix-Starlight** [comment]
Try getting indium, also what sort of textures are you using? If you could, link it.

**Comment by MIPOHBOPOHIH** [comment]
> Try getting indium, also what sort of textures are you using? If you could, link it.

Indium didn't help, and I don't use any texture packs
