### ISSUE TITLE
less fps

### ISSUE THREAD

**Issue by gardef** [jellysquid3/Sodium#1453]
hey i noticed while using a older version of this mod i got around 140 fps now i am around 70-90 is there any specific reason this is happening the version i was using is 0.4.2 i switched to 0.4.4 due compatibility issues with other mods

**Comment by Timolino456** [comment]
For these kinds of questions it would be better if you'd join the CaffeineMC discord server and go to the support forum there, GitHub is not really a good place for this: https://jellysquid.me/discord
