### ISSUE TITLE
Fishing Line Connected To Other Players

### ISSUE THREAD

**Issue by jcodyparker** [jellysquid3/Sodium#1454]
Fishing lines show a second line connected to other players rods. Tried using Fabric without sodium and this issue doesn't happen. 
Having this issue on 1.18, 1.19, & & 1.19.2  Not sure if other versions are also effected.

![image](https://user-images.githubusercontent.com/90956620/189551212-7578e55b-f343-4f13-9bda-eb2e0fd16fe5.png)

**Comment by ghost** [comment]
I can replicate this issue too with 1.19.

**Comment by coderbot16** [comment]
Not a Sodium issue: https://github.com/IrisShaders/Iris/issues/1055
