### ISSUE TITLE
[Feature Request] Mutithreaded servers?

### ISSUE THREAD

**Issue by Lucario4LyfeYT** [jellysquid3/Sodium#1455]
I know sodium is meant for clients, not servers, but it would be cool to see some of the features that sodium offers (mainly multithreaded chunk loading) for servers. Idk if it's possible, but that's why I'm asking

**Comment by Lucario4LyfeYT** [comment]
For servers, I mean running a server with mutlithreaded chunks

**Comment by silversquirl** [comment]
Sodium's features are purely rendering related. I expect you're talking about chunk building, not chunk loading, which is a fundamentally different thing. Trying to multithread chunk loading is incredibly difficult to get right and is not something Caffeine mods are likely to attempt.
