### ISSUE TITLE
Game Won't Start

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1456]
I recently was forced to shut down my pc during the minecraft boot up because my pc was frozen. Upon restarting my pc, I could no longer start minecraft without disabling sodium. Anyone know how to fix this?

**Comment by Desynq** [comment]
Any crash reports/logs?

**Comment by ghost** [comment]
Yeah, forgot to add earlier:
https://paste.ee/p/t3aAC

**Comment by Phoenix-Starlight** [comment]
It seems like you killed it because it hung?

**Comment by ghost** [comment]
It couldn't finish booting up, so at some point Windows killed it for not responding

**Comment by ghost** [comment]
Issue mysteriously gone? ¯\\\_(ツ)_/¯

**Comment by Baphomeem** [comment]
I have the same issue

**Comment by jellysquid3** [comment]
Probably caused by #899 (which has a fix)... but since you didn't fill out the issue template, we cannot help you further. Open a new issue with the template filled out if you still cannot get it working.
