### ISSUE TITLE
low fps when near jungle and mangrove swamps and normal swamps

### ISSUE THREAD

**Issue by aldonook** [jellysquid3/Sodium#1457]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Expected Behavior

fps should be around 60

### Actual Behavior

fps drops all the way down to 2

### Reproduction Steps

all i have to do is to look at a jungle, swamp or mangrove swamp biome for the fps to drop
it seems like vines are causing this but im not 100% sure
![2022-09-18_20 04 10](https://user-images.githubusercontent.com/107387796/190919439-3fbcb0fd-5268-4c6b-a6a4-d82ac5fc713a.png)
![2022-09-18_20 04 02](https://user-images.githubusercontent.com/107387796/190919440-9a081869-52ee-49b1-bbd1-639edb566760.png)

### Java version

1.19.2

### CPU

8x Intel(R) Core(TM) i7-8550U

### GPU

Intel(R) UHD Graphics 620

### Additional information

mods i use are:
baritone
betterAdvancements
camerautils
chesttracker
litematica
malilib
minihud
modmenu
worldedit

**Comment by Felix14-v2** [comment]
Please, try without other mods and click "0" several times to return to the main section of the debug pie and see which part of it is exerting a lot of load.

**Comment by jellysquid3** [comment]
You're using a silly "3D Vines" resource pack which is known to obliterate frame rates.

We cannot do anything about this. Vanilla Minecraft will run even more poorly. Do not use the resource pack unless you have a dedicated GPU with plenty of VRAM.
