### ISSUE TITLE
Dev branch, commit 620f5a3669b: water doesn't render on Fabulous! graphics

### ISSUE THREAD

**Issue by thedax** [jellysquid3/Sodium#146]
### Expected Behavior
Water should render when the` Fabulous!` graphics option is selected

### Actual Behavior
Water does not render

### Reproduction Steps
1. Create a world
2. Find water
3. Observe how water isn't rendered at all

### Attachments
Before 620f5a3669b:
![2020-07-22_15 50 15](https://user-images.githubusercontent.com/4482745/88222614-3a7f2c00-cc34-11ea-9be7-29ab603df309.png)

After 620f5a3669b:
![2020-07-22_15 51 18](https://user-images.githubusercontent.com/4482745/88222667-49fe7500-cc34-11ea-90cd-fe7d9c2f0b70.png)

### System Information

- Java Version: 1.8.0_252 and jdk-15-ea build 32
- CPU: AMD Ryzen 9 3900X
- GPU: Nvidia GeForce RTX 2060 (non-Super), driver 450.56.02
- OS: Gentoo Linux, kernel 5.7.9
- Commits used in this report: b909fa18255d (last working) and 620f5a3669b (the offending commit)

### List of mods used (excluding Sodium since that info is detailed one line above this):
Fabric 0.9.0+build.204
Lithium 0.5.1-SNAPSHOT (commit a7188dfccc)
Phosphor 0.6.0-SNAPSHOT (commit 50f6d6b167)
Voyager 1.0.0

### Settings used in Sodium
General:

- Render Distance: 24 chunks
- Brightness: Bright
- Clouds: On
- Fog: True
- GUI Scale: 4x
- Fullscreen: Off
- Use VSync: Off
- Max Framerate: Unlimited
- View Bobbing: On
- Attack Indicator: Crosshair

Quality:

- Graphics: Fabulous!
- Clouds Quality: Fancy
- Weather Quality: Fancy
- Particle Quality: High
- Smooth Lighting: High
- Biome Blend: 3 blocks
- Entity Distance: 200%
- Entity Shadows: On
- Vignette: Off
Mipmap Levels: 4x

Advanced:

- Chunk Renderer: Multidraw (GL 4.3)
- Use Chunk Face Culling: On
- Use Compact Vertex Format: On
- Use Fog Occlusion: On
- Use Entity Culling: On
- Use Particle Culling: On
- Animate Only Visible Textures: On
- Use Memory Instrinsics: On
- Disable Driver Blacklist: Off

### Other notes/observations

As one would expect, the issue doesn't persist with Oneshot OpenGL 2.0 mode (since the offending commit doesn't touch this), but both Oneshot 3.3 and Multidraw 4.3 are affected by this. Setting `Quality -> Graphics` to Fast or Fancy also resolves the issue. No other settings seem to make the issue any worse or better.

**Comment by Oberfail** [comment]
is a known bug thats being worked on

**Comment by thedax** [comment]
I guess I'll close this then if it's known. I didn't see any issues directly saying water wasn't rendering on its own, so I thought it might've been unrelated to the other block issues and whatnot. Sorry.
