### ISSUE TITLE
Ability to customize autosaving of worlds

### ISSUE THREAD

**Issue by DarkStarOnGitHub** [jellysquid3/Sodium#1461]
I use sodium with various other fabric mods for optimization and the game runs really well except that the world autosave feature (it's a vanilla feature) gives me painful lag spikes. Optifine has an option which lets me customize the autosave frequency.

Well, on Sodium there is no such feature (not even in Sodium Extra mod) and this feature could really fit well in sodium.

I searched for many mods but didn't find any which lets me change the autosave frequency or even disable it.

If I missed some sodium feature or a mod, please do let me know.

**Comment by silversquirl** [comment]
Sodium is a rendering optimization mod; this is out of scope. Sodium Extra implements several other OptiFine features, so perhaps they would consider adding this.
