### ISSUE TITLE
Can't load terrain

### ISSUE THREAD

**Issue by Bluscrn99** [jellysquid3/Sodium#1465]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### Reproduction Steps

**Game Crashes When Tring To Load Terrain,** _most likely a rendering error_. 

### Crash Report file

[crash-2022-09-27_17.04.44-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9659704/crash-2022-09-27_17.04.44-client.txt)

### Additional information
This may or may not be a problem with one of my mods.
_No response_

**Comment by Phoenix-Starlight** [comment]
FYI this will not probably be kept open for long unless you remove the cheat mod. Also, the log please.
