### ISSUE TITLE
X-Ray Flash

### ISSUE THREAD

**Issue by Cilla-H** [jellysquid3/Sodium#1466]
### Version information

sodium-fabric-mc1.19-0.4.2+build.16.jar

### Expected Behavior

Not randomly flash X-Rays of the land around you

### Actual Behavior

Sometimes when I place or break blocks I get like flashes of X-Ray vision 

### Reproduction Steps

1. Open Minecraft with Sodium.
2. Place or break a block.
3. Ow my eyes.

### Java version

Java 1.19.

### CPU

Core i7 10th Gen I think

### GPU

Intel Iris Plus Graphics I think

**Comment by Phoenix-Starlight** [comment]
Logs, thanks. (Of the relevant instances when this occurred)

**Comment by netflexy** [comment]
Solved
https://www.youtube.com/watch?v=HJ0p6PjoO8g

**Comment by Cilla-H** [comment]
![image](https://user-images.githubusercontent.com/106939310/194635953-3d54b5fa-4b80-4bb6-a2b0-e9f08f5f5c5f.png)

When I️ click that link from netflexy it gives me this

**Comment by netflexy** [comment]
https://youtu.be/5ekFkAU96RQ

**Comment by netflexy** [comment]
New one

**Comment by pajicadvance** [comment]
Duplicate of #869.
