### ISSUE TITLE
Parts of chunks below a certain Y level refuse to load regardless of graphics settings

### ISSUE THREAD

**Issue by Nathan22211** [jellysquid3/Sodium#1467]
### Version information

0.4.4 build 18

### Expected Behavior

Chunks should load as normal

### Actual Behavior

Portions of chunks below a certain Y level don't load

### Reproduction Steps

Not sure if it's because I'm using a CloudPC service or not, but I'm under the assumption it is, as they use NIVIDA Quadro's for their VMs

I can only recommend subscribing to Shadow's service long enough to reproduce it, just install sodium and fly around the world in creative until you see missing blocks in chunks below a certain Y level.

### Java version

Java 17 (same version as what MC 1.19 comes with)

### CPU

Xenon E5-2678 V3 with 8 virtual processors allocated

### GPU

NIVIDA Quadro P5000 with 16GB of V ram allocated

### Additional information

I can attach a screenshot in a bit, just need to log in to GitHub in my shadow. If you need others to confirm it, I'd recommend going into shadow's English-speaking discord.

**Comment by Phoenix-Starlight** [comment]
So the GPU is physically usable? (No VM drivers or anything like that)
Logs please, and yes a screenshot.

**Comment by Nathan22211** [comment]
Yeah turns out it might have actually been bedrock waters causing it. And I know the GPU is being passed through because it shows up in task manager on the shadow.

I did notice a comment saying it wasn't working in 1.19.2. That might have been what they came across or it's due to the exotic GPU
