### ISSUE TITLE
Breaking Blocks

### ISSUE THREAD

**Issue by netflexy** [jellysquid3/Sodium#1468]
### Version information

Sodium (all versions) 0.4.x

### Expected Behavior

Breaking Blocks = NOreload chunks

### Actual Behavior

Breaking Blocks = reload chunks

### Reproduction Steps

1. Breake blocks
2. All chunks update

### Java version

18

### CPU

Intel Core i5-10

### GPU

Intel UHD graphics

### Additional information

I found out, its happend, because light update.
So fix light update bug

**Comment by netflexy** [comment]
help pls

**Comment by MIPOHBOPOHIH** [comment]
i have this bug too, how u fix it?

**Comment by netflexy** [comment]
GG

**Comment by netflexy** [comment]
https://youtu.be/5ekFkAU96RQ
Solved

**Comment by MIPOHBOPOHIH** [comment]
> https://youtu.be/5ekFkAU96RQ Solved

а что если у меня не нвидиа, а Intel как встроенная видеокарта?

**Comment by netflexy** [comment]
хз

**Comment by netflexy** [comment]
тебе тогда юзать оптифайн

**Comment by MIPOHBOPOHIH** [comment]
> тебе тогда юзать оптифайн

а, так я уже, ну кайф получается

**Comment by netflexy** [comment]
или установи драйвера на опен джл

**Comment by pajicadvance** [comment]
Duplicate of #869.
