### ISSUE TITLE
Video settings menu crash

### ISSUE THREAD

**Issue by Angry-Tesseract** [jellysquid3/Sodium#147]
When you open the video settings menu and move your mouse over a setting, normally, a tool tip should appear, but instead, it crashes. This has happened twice in a row, and will probably happen every time.
Minecraft version: 20w30a
Fabric Loader: release fabric-loader-0.9.0+build.204-20w30a
Mod Version: sodium-fabric-mc1.16.1-0.1.0
No other mods are installed.
[crash-2020-07-22_13.36.34-client.txt](https://github.com/jellysquid3/sodium-fabric/files/4962592/crash-2020-07-22_13.36.34-client.txt)
[crash-2020-07-22_13.51.50-client.txt](https://github.com/jellysquid3/sodium-fabric/files/4962593/crash-2020-07-22_13.51.50-client.txt)

**Comment by jaskarth** [comment]
Sodium is not updated to 20w30a yet.

**Comment by Angry-Tesseract** [comment]
ah, it thought it was because it still loaded the game
