### ISSUE TITLE
Coincident faces compete for depth (flicker, divide into triangles)

### ISSUE THREAD

**Issue by mjtd2** [jellysquid3/Sodium#1471]
### Version information

mc1.19.2-0.4.4+build.18

### Expected Behavior

![2022-10-08_16 29 18](https://user-images.githubusercontent.com/46055460/194715324-87f4728e-18c3-40ce-bb7a-036352715f74.png)

The lower face of the block above (iron bars) consistently shows above the coincident face of the block below. (Screenshot from vanilla.)

### Actual Behavior

![2022-10-08_16 31 12](https://user-images.githubusercontent.com/46055460/194715502-12f120d2-8b9e-4189-b959-f67228f33f80.png)

The two coincident faces compete to show above one another. This results in flicker when the camera is moved.

### Reproduction Steps

1. Place iron bars above another block (in this case, upside-down quartz stairs);
2. Observe & move the camera around.

### Java version

17.0.3 64-bit

### CPU

Intel i5-6400

### GPU

AMD Radeon RX 480

### Additional information

- Also using Lithium & Phosphor.
- Connected to a realm.

**Comment by Lolothepro** [comment]
#460
