### ISSUE TITLE
Sodium Contains Sodium

### ISSUE THREAD

**Issue by chyzman** [jellysquid3/Sodium#1472]
### Version information

all

### Expected Behavior

The Splash Text "Sodium Free!" shouldn't be able to appear due to the fact that sodium contains sodium.

### Actual Behavior

I booted up Minecraft and the splash text was "Sodium Free!".

### Reproduction Steps

1. Boot up Minecraft with sodium
2. Boot up Minecraft with sodium
3. Boot up Minecraft with sodium
4. Boot up Minecraft with sodium
5. Pray
6. You might get the splash text "Sodium Free!"

### Java version

any

### CPU

any

### GPU

any

### Additional information

This isn't a Joke

**Comment by silversquirl** [comment]
Sodium free is actually a bedrock-only splash :)
