### ISSUE TITLE
Whenever I try to start a world, it crashes

### ISSUE THREAD

**Issue by michael-abr** [jellysquid3/Sodium#1474]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Reproduction Steps

I don't really know how it happened

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/9740752/latest.log)

### Additional information

everything was working fine until i tried updating sodium to version 0.4.4

**Comment by MADxingjin** [comment]
Mixin ERROR report in your log suggests one or multiple of your current replaymod and sodium 0.4.4 and immersive portals and probably iris are incompatible with the rest of them.
AT LINE 233
`[08:24:35] [Render thread/WARN]: @Redirect conflict. Skipping mixins.render.replaymod.json:MixinParticleManager from mod (unknown)->@Redirect::buildOrientedGeometry(Lnet/minecraft/class_703;Lnet/minecraft/class_4588;Lnet/minecraft/class_4184;F)V with priority 1000, already redirected by imm_ptl.mixins.json:client.particle.MixinParticleEngine from mod imm_ptl_core->@Redirect::redirectBuildGeometry(Lnet/minecraft/class_703;Lnet/minecraft/class_4588;Lnet/minecraft/class_4184;F)V with priority 1000`

AT LINE 264
` [08:24:36] [Render thread/WARN]: Mixin apply for mod (unknown) failed mixins.compat.shaders.replaymod.json:MixinShaderRenderChunk from mod (unknown) -> net.minecraft.class_846$class_851: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field rebuildFrame was not located in the target class net.minecraft.class_846$class_851. Using refmap mixins.replaymod.refmap.json`

AT LINE 297
`[08:24:37] [Render thread/WARN]: @Redirect conflict. Skipping mixins.iris.compat.sodium.json:vertex_format.MixinFluidRenderer from mod iris->@Redirect::iris$fixSidewaysInnerFaceNormal(Lme/jellysquid/mods/sodium/client/model/IndexBufferBuilder;ILme/jellysquid/mods/sodium/client/model/quad/properties/ModelQuadWinding;Lnet/minecraft/class_1920;Lnet/minecraft/class_3610;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/render/chunk/compile/buffers/ChunkModelBuilder;)V with priority 1000, already redirected by mixins.iris.compat.sodium.json:vertex_format.MixinFluidRenderer from mod iris->@Redirect::iris$fixBackwardUpFaceNormal(Lme/jellysquid/mods/sodium/client/model/IndexBufferBuilder;ILme/jellysquid/mods/sodium/client/model/quad/properties/ModelQuadWinding;Lnet/minecraft/class_1920;Lnet/minecraft/class_3610;Lnet/minecraft/class_2338;Lnet/minecraft/class_2338;Lme/jellysquid/mods/sodium/client/render/chunk/compile/buffers/ChunkModelBuilder;)V with priority 1000`

AT LINE 353
`[08:24:59] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath`

**Comment by michael-abr** [comment]
it worked, thanks

**Comment by O-J1** [comment]
> it worked, thanks

Could you please close the issue if its no longer relevant?

**Comment by jellysquid3** [comment]
Closed as resolved.
