### ISSUE TITLE
Large lag spikes occur when new chunks are being loaded in

### ISSUE THREAD

**Issue by neeleshpoli** [jellysquid3/Sodium#1475]
### Version information

mc1.19.2-0.4.4+build.18

### Expected Behavior

I expect no lag spikes when new chunks are being loaded in.

### Actual Behavior

Every once in a while, GPU usage spikes up to a 100%, causing a lag spike. Only happens when a Chunk is being loaded in with the option `Max Framerate` set to 30 or 60 FPS. This is not an issue with the chunk as the lag spikes happen inconsistently.

### Reproduction Steps

1. Make sure Max Framerate is set to 30 or 60 FPS (I am only getting these lag spikes with Max Framerate set to 30 or 60 fps). 
2. (Optional) Press F3 + g to show chunk borders. 
3. Move across Chunks and experience the lag spikes.

### Java version

Java 17.0.4.1 64 bit

### CPU

Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz

### GPU

Intel(R) UHD Graphics 620

### Additional information

No other mods are being used. I have determined that this is a problem with Sodium since I was not able to replicate this without sodium.

**Comment by jellysquid3** [comment]
Per changes in policy on our issue tracker, we are closing issues which are general inquiries about performance issues and such. If you are experiencing performance issues and need help, then please use the [Discord server](https://caffeinemc.net/discord).
