### ISSUE TITLE
Sodium doesn't allow for modifications of the Mojang screen

### ISSUE THREAD

**Issue by NVGAT** [jellysquid3/Sodium#1476]
### Version information

mc1.19.2-0.4.4+build.18

### Expected Behavior

Using a resource pack that changes the Mojang screen should modify the Mojang screen

### Actual Behavior

Using a resource pack that modifies the Mojang screen doesn't modify the Mojang screen.

### Reproduction Steps

1. Use a Mojang screen-changing resource pack
2. Launch the game

### Java version

Java 17

### CPU

Intel core i5 7300HQ

### GPU

NVIDIA GeForce GTX 1050 Mobile

**Comment by Timolino456** [comment]
That's a OptiFine texture feature as far as I'm aware, and Sodium doesn't add any of those.

**Comment by Phoenix-Starlight** [comment]
Custom Splash Screen mod?

**Comment by jellysquid3** [comment]
Minecraft removed the ability to modify the splash logo as part of an update some time ago. They do not want you doing this, and we are not going to implement custom resource pack features or workarounds.
