### ISSUE TITLE
Sodium running FAR worse than OptiFine. 

### ISSUE THREAD

**Issue by lockdot2** [jellysquid3/Sodium#1477]
### Version information

Minecraft Java 1.19, Sodium version: sodium-fabric-mc1.19.2-0.4.4+build.18

### Expected Behavior

![Screenshot (280)](https://user-images.githubusercontent.com/94180804/196748050-0da09ad6-7bff-40f2-a381-71c7f90cd774.png)
![Screenshot (285)](https://user-images.githubusercontent.com/94180804/196748124-3e52fecd-1481-4a7e-ab03-5369ad45a4c0.png)

![Screenshot (284)](https://user-images.githubusercontent.com/94180804/196748726-831399b2-2cf1-40a7-b702-4e21f4c8452e.png)

### Actual Behavior

Hello! So, my report is, on slower and older CPU's, like Phenom X6's, Core2 Quad/Duo's, Pentium D's, and CPU's along that line run WAY worse with Sodium, than they do with OptiFine.

In this case, with my Pentium D 945, 8 GB DDR2 800 MHz RAM, and a GTX 970, I get 1-6 FPS with Sodium, at 6 chunks render distance. And the CPU is pinned at 100% usage.

And with OptiFine, on the same computer, it gets 30+ FPS. And with a 30 FPS cap in place, the CPU is not maxed out. 

### Reproduction Steps

Open the game, and load into a world. 

### Java version

Java 18.

### CPU

Pentium D 945, Core2 Duo E8500, Core2 Quad Q8400, Core2 Duo P7350, Phenom II X6 1035T, Phenom X4 9750, Phenom X4 9150E, Celeron N3450, Celeron G470, i3 2120, and a few others. Sodium does run better on faster CPU's though, like a i5 3450 Sodium is better.

### GPU

RTX 3060, GTX 970, GTX 750 T. 

### Additional information

I do a bunch of benchmarks on hardware, and found Sodium isn't doing good on older CPU's, so I thought I should let you know.

If you have any questions, please message me at: lockdot1or2@gmail.com   so I see your question, as I don't check Github often. Have a great day!

**Comment by Phoenix-Starlight** [comment]
Are the video settings 'identical' accounting for Optifine's tricks like not fully rendering chunks until you zoom in? Repost with F3 debug.

**Comment by xMartin14091x** [comment]
### _I got the some issues with sodium_
### My Computer spec
 CPU Intel i7 4820K
 GPU RTX 3050 OC
RAM DDR3 32 GB **(Installed 64GB)**
### Minecraft Version 
1.19.2.
### Fabric loader 0.14.10.
CPU usage while playing: 2 Threads out of 8.
<img width="1720" alt="Debug" src="https://user-images.githubusercontent.com/60431754/197523414-3e187fc0-47e8-407f-8afa-2856c4cf25f9.png">
This clearly not normal right? **Im on 6 FPS with sodium!**
**I also install lots of mod Reply if you want.**

Thank you!

**Comment by lockdot2** [comment]
What is a F3 debug? And yes, they are identical.   Sent from Mail for Windows From: Phoenix-StarlightSent: Sunday, October 23, 2022 2:55 PMTo: CaffeineMC/sodium-fabricCc: lockdot2; AuthorSubject: Re: [CaffeineMC/sodium-fabric] Sodium running FAR worse than OptiFine. (Issue #1477) Are the video settings 'identical' accounting for Optifine's tricks like not fully rendering chunks until you zoom in? Repost with F3 debug.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Phoenix-Starlight** [comment]
F3 debug is the screen when you have pressed f3. It shows debug info/stuff relevant. Like # of chunks being rendered.
(It's outputting formatted stuff, send as plain)
@aston870 You are probably over-allocating right now, or at least defaults are doing that. Set the maximum to 16-8GB.

**Comment by jellysquid3** [comment]
This is not a support forum, and "the game runs worse" is not a bug report. Use the [Discord server](https://jellysquid.me/discord) for these kinds of inquiries.
