### ISSUE TITLE
Even more slower chunk loading on slow servers

### ISSUE THREAD

**Issue by thornySoap** [jellysquid3/Sodium#1487]
### Version information

mc1.19.2-0.4.4+build.18

### Expected Behavior

No slower chunk loading

### Actual Behavior

On slow servers where chunks get loaded very slowly Sodium makes chunk loading even slower so it is hard to play

### Reproduction Steps

1. Get on a really slow server
2. Move fast so the loading can't hold up

### Java version

17 Temurin

### CPU

Intel Core i3-4010U 1.7GHz

### GPU

Intel Corporation Haswell-ULT Integrated Graphics Controller

### Additional information

> Frame drops are from the recording software, I'm sorry

without mods

https://user-images.githubusercontent.com/115401023/198748010-583a2018-c683-4877-b2a6-97842e07620f.mp4

with only Sodium

https://user-images.githubusercontent.com/115401023/198748001-562bcefc-14d6-46ea-93a9-3dcfbed60332.mp4

**Comment by jellysquid3** [comment]
Per our new [hardware support policy](https://github.com/CaffeineMC/sodium-fabric/blob/3f12f36e58d977f417d22ea6e643a9d7aeb4f0ca/README.md#-hardware-compatibility), your graphics card does not meet the required specifications. As such, this issue is being closed as "won't fix."
