### ISSUE TITLE
Blue triangle in void

### ISSUE THREAD

**Issue by skyfallwastaken** [jellysquid3/Sodium#1490]
### Version information

0.4.4+build.18

### Expected Behavior

There should be no blue triangle in the void.

### Actual Behavior

There is a blue triangle in the void.

### Reproduction Steps

1. Go into an area where you can see the void (e.g. the end)
2. Start moving around. The triangle should also move.
3. You can also look through glass and see the same effect

### Java version

Java 18

### CPU

Intel Core i7-2600

### GPU

Intel HD Graphics 2000 (Mesa)

**Comment by jellysquid3** [comment]
What Linux distribution are you using? You might need to select the newer _Crocus_ driver for Mesa, which has better support for the OpenGL features that Sodium uses.

It should be possible to configure this by setting the environment variable `MESA_LOADER_DRIVER_OVERRIDE=crocus`.

**Comment by skyfallwastaken** [comment]
> What Linux distribution are you using?

Pop!_OS 22.04 LTS

> You might need to select the newer _Crocus_ driver for Mesa

Unfortunately, it didn't work.

Also, I just realized that the end _doesn't_ actually trigger the bug. I assumed it would (since it has the void) but it doesn't. The only place I can find the bug is Hypixel's limbo (join the lobby and spam `/` to be teleported there)

**Comment by Lolothepro** [comment]
I confirm this bug, and it happens easily with all models of graphics cards.

**Comment by Lolothepro** [comment]
![2022-10-30_15 40 52](https://user-images.githubusercontent.com/68275908/198884673-54c8e276-5ed4-4e17-97a9-6ad7422b9ce3.png)
![2022-10-30_15 40 54](https://user-images.githubusercontent.com/68275908/198884678-ab3a0d26-89a0-401b-9d61-1994ecabcc76.png)

**Comment by Lolothepro** [comment]
But it's not a Sodium bug.

**Comment by nigrum-anatis** [comment]
I had the same thing, after removing everything from my mod folder (except sodium) it was gone.

**Comment by skyfallwastaken** [comment]
Hmm... did you have a mod called "More Culling" by any chance?

**Comment by FlashyReese** [comment]
It's a vanilla bug https://bugs.mojang.com/browse/MC-230902

**Comment by jellysquid3** [comment]
Per our new [hardware support policy](https://github.com/CaffeineMC/sodium-fabric/blob/3f12f36e58d977f417d22ea6e643a9d7aeb4f0ca/README.md#-hardware-compatibility), your graphics card does not meet the required specifications. As such, this issue is being closed as "won't fix."
