### ISSUE TITLE
Unable to slide GUI scale to 3 unless fullscreen enabled and then game restarted [Sodium 0.4.4]

### ISSUE THREAD

**Issue by Konglomneshued** [jellysquid3/Sodium#1492]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Expected Behavior

I should be able to slide the GUI Scale to 3 upon a fresh launch with no custom settings applied.

### Actual Behavior

It only slides to 2 and I have to enable fullscreen and restart my game to slide it further.

### Reproduction Steps

- Pop!_OS 22.04 LTS
- MultiMC 0.6.16-3430
- Fabric loader 0.14.10
- fabric-api-0.64.0+1.19.2
- sodium-fabric-mc1.19.2-0.4.4+build.18

1. Fresh Minecraft with Fabric version and Sodium version
2. Launch
3. Mute music, omg
4. Enable fullscreen (or slider will stay capped at 2)
5. Go to video settings
6. Slide GUI scale high as it can go
7. Observe that it only slides to 2
8. Apply, done, done, quit game
9. Relaunch
10. Go to video settings
11. Hover over slider and see that it can now go to 4

### Java version

JDK 18

### CPU

Intel® Core™ i7-9750H CPU @ 2.60GHz × 12 

### GPU

NVIDIA Corporation TU116M [GeForce GTX 1660 Ti Mobile] / Mesa Intel® UHD Graphics 630 (CFL GT2)

**Comment by MeeniMc** [comment]
Issue appears resolved in 0.5.5

**Comment by allanonmage** [comment]
Issue is back in 5.13

**Comment by QazCetelic** [comment]
I'm also experiencing this issue with version `0.6.13+mc1.21.6`

**Comment by Exp-Future** [comment]
HMCL Minecraft 1.7.10 has this problem.
