### ISSUE TITLE
1.19.2 crash during startup: "Config not yet available"

### ISSUE THREAD

**Issue by KB-Q** [jellysquid3/Sodium#1493]
### Version information

1.19.2

### Reproduction Steps

1.19.2 Instance crashed during startup, using MultiMC.

Mods list: https://paste.ee/p/IMISY

### Crash Report file

https://paste.ee/p/SCJSS

**Comment by jellysquid3** [comment]
Remove Not Enough Crashes and see what the error points to. It tries to show an in-game error screen during startup, but that requires Sodium to have loaded first, which Not Enough Crashes circumvents.
