### ISSUE TITLE
Incorrect Block Entity Retrieval

### ISSUE THREAD

**Issue by Nosrick** [jellysquid3/Sodium#1495]
### Version information

1.18.2-0.4.1+build.15 / 1.19.2-0.4.4+build.18

### Expected Behavior

BlockEntity should be retrieved from the WorldSlice class when given the BlockEntity's BlockPos.

### Actual Behavior

BlockEntity retrieval returned null because X + Y of BlockPos was adjusted by -1 each.
This meant that the CrockPotBlockColourProvider could not provide colour to the block.

### Reproduction Steps

1. Take a look at my repo here: https://github.com/Nosrick/crock-pot-mod/tree/fix/issue-18
2. Run Minecraft, generate a world
3. Fetch a crock pot block from the Crock Pot creative tab and place it down
4. The body of the pot renders entirely in black, but the handles and the lid render correctly (the lid only appears when water and food are added to the pot)

### Java version

Java 17

### CPU

Intel Core i5 @ 2.50GHz

### GPU

4095MB NVIDIA GeForce GTX 1650 Ti (Acer Incorporated [ALI])

### Additional information

The original poster of the issue in my repo states that only FAPI, Sodium and Indium were used. The problem remains without Indium.

Additionally, adjusting the BlockPos before BlockEntity retrieval causes the BlockEntity to be retrieved correctly, and get its correct colour, but the body of the crock pot seems to be rendered without any lighting calculations, and is a _very_ dark (but correct) colour.

I can provide screenshots if they'd be helpful.

EDIT:
I placed a ring of crock pots 1 Y level below a crock pot elevated on another block (tried sand and a campfire), and the pot above rendered normally. Each crock pot placed in the ring brought the colour closer to its normal, with a full 8 crock pots making it the normal colour.

**Comment by jellysquid3** [comment]
This problem was fixed in Sodium 0.5.0 as part of the rework we did for biome color blending.
