### ISSUE TITLE
Patrix Resourcepack Support/Compatibility

### ISSUE THREAD

**Issue by LiberteIV** [jellysquid3/Sodium#1497]
**This is fabric+optifine+optifabric+seus+patrix**

![optifine+seus](https://user-images.githubusercontent.com/116210112/198937674-054bc142-1860-4d7d-af7a-9d742b548784.png)

**This is fabric+sodium+iris+seus+patrix**

![sodium+seus](https://user-images.githubusercontent.com/116210112/198937686-cd661090-94ef-4720-aeaf-c07dfd03bed3.png)

Clearly optifine looks way better than sodium in this case.
On patrix site https://www.patreon.com/posts/free-1-19-32x-69530757 i read this:
**For Optifine users, make sure these settings are set correctly, or else the textures/models will get messed up: "..."
For Fabric/Iris-based mods users, good luck I guess.**

Question is, does the creator of the resourcepack need to provide compatibility for sodium, or can sodium provide compatbility for the most advanced and realistic looking resourcepack out there? Why do the textures look bad with sodium, are there settings that must be changed or is the issue somewhere deeper?

**Comment by PepperCode1** [comment]
If you join the Patrix Discord, you will see that there is a list of mods and other files that can be used to obtain a nearly perfect look of Patrix without Optifine. Sodium is only a performance mod and will not be adding any Optifine resource pack features.

**Comment by LiberteIV** [comment]
> If you join the Patrix Discord, you will see that there is a list of mods and other files that can be used to obtain a nearly perfect look of Patrix without Optifine. Sodium is only a performance mod and will not be adding any Optifine resource pack features.

Thanks for the info, i'm not on discord, is this list of mods available elsewhere?
So i can make patrix look nearly as good as with optifine by using other mods, will this be compatible with sodium?
Sodium for the performance and patrix for the good look, and ofc a shader liek seus.

**Comment by Timolino456** [comment]
For OptiFine alternatives, read this list: https://lambdaurora.dev/optifine_alternatives/ (beware that some of these won't actually work with the OptiFine formats, so you'd need to pick the right ones.) Or, easier, use the Fabulously Optimized modpack - and if you want to add other mods, add them on top of the modpack. The CEM mod is not complete as of now, so if you want to use e.g. Fresh Animations, there will be issues.

**Comment by MicrolemurDev** [comment]
It looks like you are missing Continuity mod for Connected Textures. If you install that the issue should go away.
