### ISSUE TITLE
Incompatibility with Immersive Portals

### ISSUE THREAD

**Issue by Neubulae** [jellysquid3/Sodium#15]
https://github.com/qouteall/ImmersivePortalsMod/issues/254

**Comment by qouteall** [comment]
https://github.com/qouteall/ImmersivePortalsMod/issues/271

**Comment by Jarfeh** [comment]
I noticed that you've since closed the pull request under sodium for compatibility. Has the compatibility issue been resolved?

**Comment by IMS212** [comment]
This has been fixed for a long time now.
