### ISSUE TITLE
Game Crashing when changing Dimension/RenderDistance/... (Litematica Compability bug)

### ISSUE THREAD

**Issue by Kronex6** [jellysquid3/Sodium#1501]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Reproduction Steps

1. install sodium
2. install Litematic
3. start mincraft in 1.19.2 and pass throug a nether portal 

and wuala game crashes

if you remove sodium the game stops crashing but if you remove litematica the same happens its stops crashing

### Crash Report file

-none-

### Additional information

litematica needs support for sodium or reversed so its stops

**Comment by ghost** [comment]
I've been having this problem since I installed the Nvidia driver update (version 526.47).

**Comment by Whitedonrocks** [comment]
Yep same over here.

**Comment by B3cc4e** [comment]
Yea, I have the same issue and it took me like 3 days to find out what it is and find this crash report... I would love to see this fixed as well

**Comment by jurasto** [comment]
Same here.

**Comment by CTCS5** [comment]
Same issue after updated Nvidia driver version 526.47.

**Comment by jellysquid3** [comment]
This is not an issue with Litematica. The latest NVIDIA driver is broken... see #1486.
