### ISSUE TITLE
Weird behavour of minecraft in my new monitor with minecraft

### ISSUE THREAD

**Issue by MKLEGOPRO** [jellysquid3/Sodium#1504]
### Version information

fabric-language-kotlin-1.8.2+kotlin.1.7.10 (but it is a problem in any fabic version)

### Expected Behavior

I expected minecraf to work normaly in my new monitor. The monitor is 165hz and i connect to my laptop via hdmi 1.4 (witch only allows me to get 120hz on the monitor at the 1080 resolution). I set the new monitor as the main monitor in wintows and lauched minecraft to see how it would look. I launched it in the multy mc launcher and I expected for it to work normaly.

### Actual Behavior

When I tried to launch minecraft, It got stuck in the loading animation with the mojang logo.
I tried several times and it just didnt work, but when I tried to unplug the monitor, it launched minecraft normaly and if I plugged the monitor again it worked normaly at firs and I could get it on full screen. After playing for a bit I realised that my fps was lower than usual and, when I put the game on full screen on my laptop screen, I got 100 more fps than in the external monitor.

Also when I created a new instance, installed fabric and then put all the mods from the same instance where I got stuck on the loading screen, it still got stuck in the loading screen but with normal performance.

### Reproduction Steps

1. Connect a monitor to a laptop via hdmi
2. Try launching a minecraft instance you already created with fabric and sodium
3. It will get stuck in the Mojang loading screen
4. Unplug the monitor and then replug it when minecraft loades

For the part of creating a new instance
1. Create a new (not copying the instance) instance with the same mods and launch it
2. See how it has the same problem, but with better performance.

### Java version

Java 19 (special version optimiced for AMD hardware but I still got the same issue with a normal java 18 version)

### CPU

4000 series laptop AMD Ryzen 5

### GPU

AMD Radeon RX 5500 M

**Comment by verlixis** [comment]
It's most likely that the laptop switches to using integrated GPU (Radeon Vega) for Minecraft when using HDMI instead of using the dedicated GPU (RX 5500M). Type "Graphic Settings" in your Windows Search, browse for "javaw.exe" for the Java your Minecraft is using, then select "High Performance".

**Comment by MKLEGOPRO** [comment]
No, look at the screenshot
![Captura de pantalla 2022-11-22 165355](https://user-images.githubusercontent.com/117539010/203360280-37fd21b2-9fd8-434d-886e-357014d5d92e.png)

**Comment by MKLEGOPRO** [comment]
> It's most likely that the laptop switches to using integrated GPU (Radeon Vega) for Minecraft when using HDMI instead of using the dedicated GPU (RX 5500M). Type "Graphic Settings" in your Windows Search, browse for "javaw.exe" for the Java your Minecraft is using, then select "High Performance".

No, look at the screenshot
![Captura de pantalla 2022-11-22 165355](https://user-images.githubusercontent.com/117539010/203360441-4ef9e05f-9054-4209-851e-39290896e012.png)

**Comment by jellysquid3** [comment]
This is probably not an issue with Sodium. We don't control anything which you are talking about being broken. And without information about what version or whatever "special optimized JVM for AMD" (???) you were using, we'll never be able to resolve the issue.
