### ISSUE TITLE
Crash while traveling in Mangrove

### ISSUE THREAD

**Issue by NamiestOfNames** [jellysquid3/Sodium#1507]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Reproduction Steps

I was flying over a mangrove swamp biome and experienced major fps loss from 60 to 44 or something. Eventually the fps loss go worse as I progressed further into the biome, and then the game just crashed. 

### Crash Report file

[crash-2022-11-11_23.46.36-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/9994566/crash-2022-11-11_23.46.36-client.txt)

**Comment by PeculiarPineTreePlays** [comment]
I was literally about to leave a bug report here, but I see someone's already beat me to it, lol.
Here's what's happening in my case:

Client I'm using is here: [https://www.curseforge.com/minecraft/modpacks/recording-client-for-locals-mc-server](url)

It seems to be a memory leak, but the logs won't tell me which mod is causing it. For me it only seems to happen with higher render distances (using Bobby's "fake chunks"). (I'm playing on a server). Bobby dev said it's likely a graphics driver issue with Sodium.

I disabled every mod except for:
- Fabric 0.14.9
- Fabric API 0.62.0 (tried the newer version too, same thing. )
- Bobby 4.0.0
- Freecam (fabric) 1.1.6
- Mod Menu 4.0.6
- Sodium 0.4.4+build.18 (tried disabling it, but FPS was so bad I couldn't run the test properly)
- ReplayMod 2.6.8
and it still persists.

Steps to reproduce:

1. Set render distance to 24 or 32 (I tried both, more chunks = faster leak)
2. World seed = 3324100555488929243
3. TP to coordinates: -4814, -2962
4. I dug a little hole just under the surface, and flew Freecam straight up to below cloud layer (my friend tried without freecam though (in creative mode), and same thing).
5. Wait for most chunks to load in, then turn 90 degrees
6. Repeat step 5 (turning the same way every time)
7. Keep turning periodically every so often.
8. Every time you turn, MC RAM usage (in Task Manager) increases by 100-200MB, till it reaches max MC RAM (8GB allowed in my case). Then it increases beyond MC's allowed limit (up to 8.5-8.8GB or higher), then crashes.
Crash says "EXCEPTION_ACCESS_VIOLATION"

Other notes:

- I've tried with/without MemoryLeakFix mod. No difference.
- Server render limit is 10 chunks
- Happens in Survival & Creative, but I couldn't get my camera account to crash in Spectator mode.
- Using MC 1.19.2
- "Taint Fake Chunks" is disabled in Bobby settings
- My friend's MC RAM usage increased to 24GB before crash.
- My GPU: AMD Radeon HD 6950, driver series = "Crimson edition"
- My friend's GPU: AMD 6700xt with latest drivers

Additional info:
- The memory thing only happens in that one swamp. Everywhere else it stays around 4-5GB in Task Manager (despite being capped at 8GB) & doesn't seem to climb higher. But as soon as I enter the swamp it slowly increases till it's beyond the limit.
- (Staying at 10 chunks render is fine, keeps it at 3.5-4.5GB or so).
Crash log:
[hs_err_pid4992.log](https://github.com/CaffeineMC/sodium-fabric/files/10008974/hs_err_pid4992.log)



Let me know if you need any more information,
Thank you,
Robert
