### ISSUE TITLE
OptiFine cape support?

### ISSUE THREAD

**Issue by Stuntlover-TM** [jellysquid3/Sodium#1512]
**Is your feature request related to a problem? Please describe.**
I love Sodium but sometimes it's quite annoying not having my OptiFine cape showing

**Describe the solution you'd like**
Display OptiFine capes

**Describe alternatives you've considered**
Or you could also make your own cape system, I would definitely buy it ;)

**Comment by jellysquid3** [comment]
No. Why would we care that you donated to someone else?

You can use other mods if you _really_ want to see your cape.

**Comment by jellysquid3** [comment]
More importantly, we're not interested in "selling" cosmetic features. We have donations, but I don't believe that a donation is really a donation if you're getting things for reward. 

If you want to donate ex-gratia (without reward) then you can do so via the button we added to the Video Settings screen.
