### ISSUE TITLE
Sodium not increasing fps at all

### ISSUE THREAD

**Issue by Jxstin-A** [jellysquid3/Sodium#1513]
I attempted to use Sodium but I get almost the same fps I do as in vanilla Minecraft. I use optifine and I get almost 3x the amount of fps I get with sodium. I'm not sure if it's my settings or if it's my hardware but I'll list my specs below.

GPU: RTX 2060 OC edition
CPU: Ryzen 7 3700x
RAM: 16GB 3200Mhz 2x8GB
Storage: 1TB SSD

If there's anything else you need to know I'd be happy to share. I've attempted to use Sodium on 1.18.2 and 1.19.2 but no luck with fps increases. Graphics drivers are up to date as well.

**Comment by verlixis** [comment]
Just making sure, did you run Minecraft with Fabric loader and have Sodium put inside the "mods" folder?

**Comment by Jxstin-A** [comment]
Yes I am, I'm using CurseForge to load everything. First is vanilla, second is sodium, lithium and starlight, third is sodium, lithium and phosphor and last is optifine. Not increasing FPS at all is an overstatement since there is some increase but I've seen people report 3x as much fps etc...

![2022-12-15_07 53 35](https://user-images.githubusercontent.com/52510234/207883184-dcaad49c-b15a-4ef6-a160-189fb09246dd.png)
![2022-12-15_07 55 48](https://user-images.githubusercontent.com/52510234/207883436-3e2992b8-58bb-4117-8454-5adc6ec6bfbb.png)
![2022-12-15_07 58 42](https://user-images.githubusercontent.com/52510234/207883443-246c855e-bc49-42fe-bcfa-276a845bdf59.png)
![2022-12-15_08 01 26](https://user-images.githubusercontent.com/52510234/207883456-014e4eb3-3047-429c-b53d-caab7c0ca32a.png)

**Comment by Ayman-Isam** [comment]
I think that the reason might be that you already have a high fps and the people that report 3x performance usually have a low end pc

**Comment by Jxstin-A** [comment]
I’m not sure what a high end PC is considered but in these two screenshots taken by AsianHalfSquat on YouTube he’s using a GTX 1080.

![17F6773F-DB8A-43EF-AC8D-09A23B349015](https://user-images.githubusercontent.com/52510234/209193370-0353a6a9-a34d-46c4-a6ac-c29b1e705929.png)
![675D9B84-160D-46F8-B2FE-2EBA4D928177](https://user-images.githubusercontent.com/52510234/209193382-dd83e353-8138-42d2-a867-abc88e77a911.png)

Full video here:
https://youtu.be/ZUg0f6jjhQE

**Comment by Jxstin-A** [comment]
My girlfriend also experiences little to no fps boost and she’s on integrated graphics on a pretty old system. Is there a certain sweet spot of hardware that sodium has to have to boost performance?

**Comment by Ayman-Isam** [comment]
My experience for sodium is also not that different. I'm running a 5800H and a 3060 laptop and without sodium at 1440p I get 140 and with sodium I get like 190. I'm using a laptop so it might be different. But that's what I thought was normal. I tried optifine and it got me worse frames than sodium

**Comment by Ayman-Isam** [comment]
My guess would be that Sodium does not cause 3x performance all the time

**Comment by Ayman-Isam** [comment]
Just for curiosity sake, how many hz is your monitor like can your monitor actually display that many frames

**Comment by Jxstin-A** [comment]
My monitor is 165hz. It’s fine when I’m running without shaders, however when i’m using sodium + iris, optifine still performs better than sodium.

My girlfriend has a 60hz monitor and she doesn’t get up that high in fps, only with optifine.

**Comment by Ayman-Isam** [comment]
What specs does your girlfriend have? As far as I know, sodium has better performance if you have a dedicated GPU as it offloads certain tasks to the GPU

**Comment by Ayman-Isam** [comment]
Also how much ram do you have allocated to Minecraft

**Comment by Jxstin-A** [comment]
My girlfriend and I both allocate 4GB for vanilla and 6GB for modpacks. I have 6GB in those screenshots.

My girlfriend has an AMD A8-6500 APU with Radeon(tm) HD Graphics 3.50 GHz. 8GB RAM not sure if it’s DDR3 or DDR4

**Comment by jellysquid3** [comment]
There's a bug in recent versions of Sodium that is causing worse performance than expected on GPU-bound systems.

It will be resolved in a future update (probably before year 2023.)

**Comment by Jxstin-A** [comment]
My girlfriend does not have a GPU bound system and uses integrated graphics on the CPU I provided in the previous comment. She still does not get much of an FPS boost. I don’t have screenshots of that unfortunately.

**Comment by jellysquid3** [comment]
Per changes in policy on our issue tracker, we are closing issues which are general inquiries about performance issues and such. If you are experiencing performance issues and need help, then please use the [Discord server](https://caffeinemc.net/discord).

**Comment by devashish2024** [comment]
For me bruh I got nice boost in optifine (Avg. 100+fps) on this 10 years pc, and i was just exploring in vnnila minecraft, wtf I got 100fps straight in minecraft fabric (no mods, while I was coding a mod). what a logic it is (Fancy settings etc, always 100+ Fps, like equal or bit better than optifine) but fabric withjout any mods, other than my a bind mod
