### ISSUE TITLE
The mod still microstutters in fullscreen

### ISSUE THREAD

**Issue by Kryllex** [jellysquid3/Sodium#1515]
### Version information

the one from august

### Expected Behavior

the mod works

### Actual Behavior

the mod has huge fps spikes, audio crackling, mouse jumping, all at once in the form of microstutters that even make discord audio and any other audio stutter with it. Likely a CPU thing?

all of this only in fullscreen

### Reproduction Steps

1. use sodium
2. try fullscreen
3. be sad

### Java version

all of them

### CPU

5800x (all of them)

### GPU

6800xt (all of them)

### Additional information

the issue is the mod

**Comment by jellysquid3** [comment]
Banned from the issue tracker. If you want to open useless issues and give flak, that's on you.
