### ISSUE TITLE
Discord Server where?

### ISSUE THREAD

**Issue by kispintyi** [jellysquid3/Sodium#1521]
Hello! I was searching for CaffeineMC's Discord Server ("Sodium Discord") but all the invites I found are invalid and the website just drops an error message when I click to discord and verify myself, why?

**Comment by FlashyReese** [comment]
You can read all about it [here](https://jellysquid.me/discord).

**Comment by kispintyi** [comment]
Yes but I tried here and got this error:
![kép_2022-11-25_134247902](https://user-images.githubusercontent.com/116653691/203988264-0f3ff9ab-6e65-4db2-a403-e805d060f802.png)

**Comment by kispintyi** [comment]
Yes, but I tried here and got this error: 
![kép_2022-11-25_144414671](https://user-images.githubusercontent.com/116653691/203998193-c4e125cc-210f-4fcf-a11b-26a46ab82664.png)

**Comment by kispintyi** [comment]
Nevermind, now the website is working and I got the Discord Link! :)
