### ISSUE TITLE
Asynchronous Reprojection (smoother at low fps)

### ISSUE THREAD

**Issue by Aras14HD** [jellysquid3/Sodium#1526]
Asynchronous projection could improve the perceived framerate, while not actually rendering more frames, just translating/rotating (simple matrix multiplication) the last rendered frame and projecting it (probably possible at many times the refreshrate, even on very old/low end hardware).

**Describe the solution you'd like**
Pull and transform the rendered (world+entites)frame in the framebuffer (position/rotation of it need to be saved somewhere too) at the refreshrate, then apply effects (distortions/compositing) and GUI and push it to the screen.

**Additional context**
Possible options might be:
 - Number of layers
 - overdraw (to fix black borders)
 - border fix type (stretch, +blur)

Just thought that it might make sense here (after watching the LTT vid).

**Comment by burgerindividual** [comment]
This wouldn't be possible in an OpenGL context like Minecraft, so this likely won't make it to Sodium unless we someday get a Vulkan context working or something like that, which would be pretty far in the future.

![image](https://user-images.githubusercontent.com/30326913/205516885-7432f134-b5b5-48db-a8d7-94275384e11e.png)

**Comment by TheBeautyLlama** [comment]
Make request on page for Vulkanmod then
