### ISSUE TITLE
When I Have Sodium, And I Create/Generate A World In TLauncher, It Apparently Crashes.

### ISSUE THREAD

**Issue by SodiumCrashesMC1013** [jellysquid3/Sodium#1529]
### Version information

mc1.19.0-fabric-loader-0.14.11

### Expected Behavior

I Applied The Settings Of The Sodium, With this, everything normal. Then, when i execute/create a world, It Crashes...

### Actual Behavior

Loaded A World, Then It Was Loading, When It's Finished, It Says Loading World, Then, Says Saving World. Which Obviously Crashed.

### Reproduction Steps

Steps:

1. Executed Minecraft
2. Installed Sodium (also phosphor, lithium).
3. Played The World}
4. It Crashes

### Java version

Java 17

### CPU

AMD A4-5000 APU with Radeon(TM) HD graphics

### GPU

AMD Radeon HD 8330

**Comment by silversquirl** [comment]
We do not support cracked launchers. Please buy the game.
