### ISSUE TITLE
Some resource packs are broken with Sodium and MC 1.19.3

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#1530]
### Version information

Sodium 0.4.5

### Expected Behavior

![2022-12-07_18 12 43](https://user-images.githubusercontent.com/68275908/206245735-633409d3-7a01-4fb1-9f9f-65bc603cc0da.png)

### Actual Behavior

![2022-12-07_18 13 58](https://user-images.githubusercontent.com/68275908/206245857-a6fdc6d7-a03d-49cd-ac97-a21ae2fc106a.png)

### Reproduction Steps

Use Sama Faithful with Sodium

### Java version

Java 17

### CPU

Ryzen 1600

### GPU

GTX 1070

**Comment by Lolothepro** [comment]
https://user-images.githubusercontent.com/68275908/206263170-8c645a16-80f9-4ff6-a13e-21e6dee7e0a0.mp4

**Comment by ghost** [comment]
I also encountered a issue related to resource packs and Sodium. Videos are attached.

Without Sodium

https://user-images.githubusercontent.com/19875208/206300148-43035e3f-2a23-4e8d-ace1-431418e8c7f4.mp4

With Sodium

https://user-images.githubusercontent.com/19875208/206301265-99695709-9450-474d-9a7c-1b53602ee233.mp4

Keep in mind that I did not change the Magma or Prismarine block textures. Almost all animated textures are broken as of my knowledge, even ones that aren't changed by the resource pack. I got the same result with the Magma and prismarine blocks even without using the resource pack.

**Comment by Lolothepro** [comment]
fixed
