### ISSUE TITLE
Emit light when using light source as a /hat

### ISSUE THREAD

**Issue by Janeela-translate-GER-ENG** [jellysquid3/Sodium#1533]
Light sources like froglight, sea lantern, torch etc do not only emit light when placed, but also when held in hand. I am used to building while wearing a light block as a /hat, so I can build with both hands free instead of holding a light block in the offhand. I would love to see this added, because everything else is already better here and this is the only thing I am missing.

I am not even sure if this is the right place to request this, since I just followed instructions to use sodium/iris together 2 days ago, so I don't know what I'm doing please forgive me (send help lol)

**Comment by magneticflux-** [comment]
Try using https://modrinth.com/mod/lambdynamiclights

**Comment by Janeela-translate-GER-ENG** [comment]
we moved on to 1.19.3 but lambdynamiclights did not.
Just sayin.

**Comment by magneticflux-** [comment]
Great to know. Please close this issue as it is not a problem with Sodium.

**Comment by Janeela-translate-GER-ENG** [comment]
well, it's a request to add this feature to Sodium, which has to be submitted as an "issue". I used the temporary solution you provided, but since it's no longer working, I am still requesting the addition.

**Comment by magneticflux-** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/71

**Comment by LucilleTea** [comment]
Sodium doesn't add any kind of dynamic lighting, and doesn't plan to, it's out of scope as a performance mod. The idea of an item/block producing light while held, worn, or etc should be handled by a separate mod eg. lambdynamiclights, or a shaderpack with iris.
I see LDL isn't updated to 1.19.3 yet, I don't know of an alternative. There will be some shaders, but that's an overkill solution, and I don't know how many would handle hats.

**Comment by Janeela-translate-GER-ENG** [comment]
Thank you, LucilleTea.
As described in my first post, I was not sure if Sodium even is the right place to ask for this. Now I do. Cheers!
