### ISSUE TITLE
When playing no sound is heard

### ISSUE THREAD

**Issue by DostonDox** [jellysquid3/Sodium#1535]
### Version information

MC All versions i guess

### Expected Behavior

i hear sound when i play the game

### Actual Behavior

i cant hear sound, (my volume and stuff is all normal, even playing without it with the same settings I can hear sound)

### Reproduction Steps

load sodium

### Java version

Java newest

### CPU

Intel 15 10400

### GPU

RTX 2060

**Comment by piuvas** [comment]
any logs? have you checked vanilla to see if it's a sodium issue?

**Comment by jellysquid3** [comment]
We don't touch anything to do with sound. It isn't a problem with Sodium.
