### ISSUE TITLE
Frustum Culling bug on high coordinates?

### ISSUE THREAD

**Issue by haubna** [jellysquid3/Sodium#1537]
### Version information

Sodium 0.4.5-rc.2

### Expected Behavior

![2022-12-12_18 51 05](https://user-images.githubusercontent.com/7816894/207118792-80526f3b-b873-4ff8-952e-ea3eea39c020.png)

### Actual Behavior

![2022-12-12_18 52 05](https://user-images.githubusercontent.com/7816894/207118833-ad66bc62-03ee-415b-82dc-3677eb898d96.png)

### Reproduction Steps

Generate a world with the seed shown in the second screenshot. Teleport to the coordinates to see the culling issue. This behaviour is not observed in vanilla Minecraft. I am not sure if this is a bug caused by occlusion culling (like in some other issues on this github) or due to some floating point precision errors in the sodium frustum culling code on high coordinate values. Ignore the missing water. It was from another mod.

### Java version

Java 17

### CPU

Intel Core i9-13900k

### GPU

Nvidia GeForce RTX 2080 Ti

**Comment by Timolino456** [comment]
This is most likely just another case of wrong culling like you said, a new culling system that hopefully fixes this is in the works (this might still take some time).

**Comment by hexadecimal233** [comment]
Should be fixed in 0.5.0

**Comment by jellysquid3** [comment]
This is definitely fixed in Sodium 0.5.1 now.
