### ISSUE TITLE
FPS isn't boosting with Sodium

### ISSUE THREAD

**Issue by HiZzy0** [jellysquid3/Sodium#1539]
### Version information

Minecraft Fabric 1.19.2

### Expected Behavior

Hello
I've expected the FPS boost with installed Sodium, Lithium, LazyDFU, Phosphor, FerriteCore and Indium.
My F3 screen says that GPU is used Nvidia.

My laptop stats:
Processor: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz
RAM: 32 GB
GPU: Nvidia GeForce GTX 1050
GPU2: Intel HD Graphics 630
Win 10 Pro, 64 bit
Allocated GB for minecraft :  10GB
Laptop screen resolution: 3840 x 2160, 60 Hz, 4k
Playing in window mode

### Actual Behavior

I've installed only these with fabric-api-0.67.1+1.19.2. 
Now I get 40 FPS on with these all mods. 

### Reproduction Steps

Don't know what to do.. 

### Java version

Java newest

### CPU

Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz   2.80 GHz

### GPU

Nvidia GeForce GTX 1050 GPU2: Intel HD Graphics 630

**Comment by jLn0n** [comment]
tweak the settings, that might help

**Comment by ghost** [comment]
Could you try reducing the resolution? you might be having a fill rate bottleneck.

**Comment by jellysquid3** [comment]
Per changes in policy on our issue tracker, we are closing issues which are general inquiries about performance issues and such. If you are experiencing performance issues and need help, then please use the [Discord server](https://caffeinemc.net/discord).
