### ISSUE TITLE
Fails to render and then locks up on Windows dev kit 2023

### ISSUE THREAD

**Issue by yourWaifu** [jellysquid3/Sodium#1541]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Reproduction Steps

1. install prism launcher (official one doesn't work on ARM)
2. download openjdk arm64 windows https://learn.microsoft.com/en-us/java/openjdk/download
3. install fabric via prism launcher
4. install sodium and fabric api
5. launch game via prism launcher and openjdk arm64 windows
6. play a single player game
7. wait for loading screen to end
8. black screen with sound
9. black screen with no sound, probably frozen

### Crash Report file

None

### Additional information

![image](https://user-images.githubusercontent.com/16181109/207989325-71c98073-1fd1-45a6-bb77-8b1d7c4fed39.png)

**Comment by magneticflux-** [comment]
Can you try installing the official [OpenCL and OpenGL Compatibility Pack](https://devblogs.microsoft.com/directx/announcing-the-opencl-and-opengl-compatibility-pack-for-windows-10-on-arm/) from the Microsoft Store? That should use Mesa D3D12 drivers to provide OpenGL 3.3 system-wide. If Sodium still complains about the OpenGL version, it looks like a full Mesa Freedreno driver might support up to OpenGL 4.5 (instructions [here](https://github.com/pal1000/mesa-dist-win#installation-and-usage)).

**Comment by yourWaifu** [comment]
@magneticflux- OpenGL compatibility is installed by default or was already installed from what it looks like 
![image](https://user-images.githubusercontent.com/16181109/208003063-af343402-3cac-4c8c-95ca-be33d26e217e.png)
As for the Mesa Freedreno driver, I'm very unsure if that'll work for ARM64, and I don't want to mess with drivers on my dev kit to find out because I need it for work.

**Comment by magneticflux-** [comment]
I think I might be able to get something working, but let's move to [the Discord](https://jellysquid.me/discord) for more free-form discussion and to avoid cluttering the issue tracker. I'll update this issue with a solution if we find one.

Make a brief thread in \#support-forum with a link to this issue and `@magneticflux-#8806`.

**Comment by pajicadvance** [comment]
OpenGL wrappers such as the Compatibility Pack are not supported by Sodium.
