### ISSUE TITLE
World getting stuck on 100% during world creation.

### ISSUE THREAD

**Issue by theDerxu** [jellysquid3/Sodium#1544]
I know I'm running 1.19.2 fabric but currently don't have access to my pc, so I don't know the exact version, I will reply later (most likely tomorrow) with a log, a fabric version and modlist, (as it is only occurring with other mods on).

**Comment by SamAurel** [comment]
Try removing litematica

**Comment by theDerxu** [comment]
it was working with litematica until I updated a mod (not sure which mod tho)

**Comment by theDerxu** [comment]
however testing it again today seems that updating something fixed it (again idk what it was but its fixed now with curseforge updating my mods)
weird
