### ISSUE TITLE
Sodium Crashing on 1.19.3

### ISSUE THREAD

**Issue by rzpwr** [jellysquid3/Sodium#1545]
### **Version information**
sodium-fabric-mc1.19.3-0.4.6+build.20

### **Reproduction Steps**
Teleport to a player who's in a different dimension

### **Java version**
Java 17.0.5 64 bit

### **Crash Report File**
https://hastebin.com/ivazomedan.yaml

**Comment by jellysquid3** [comment]
Duplicate of #1486.
