### ISSUE TITLE
Massive memory leak - 1.19.3, AMD, Linux

### ISSUE THREAD

**Issue by andrejcremoznik** [jellysquid3/Sodium#1549]
### Version information

mc1.19.3-0.4.6+build.20

### Expected Behavior

Stable memory usage

### Actual Behavior

I have `-Xmx` set to 8GB, my total RAM is 32 GB. Game starts with about 2.5 GB loading in my base. Entering Nether bumps it up by an additional 1.5 GB and moving around gives you about 2 extra GB for every 1km. Entities in the area also seem to increase RAM usage so just waiting around with mobs spawning/despawning will eat it up. Garbage collection seems to be completely absent. Depending on what I'm doing I get through my 32 GBs in about 1 hour. Game doesn't crash.

### Reproduction Steps

Do stuff.

### Java version

openjdk 19.0.1 2022-10-18

### CPU

AMD Ryzen 5 3600

### GPU

Radeon RX 5700

### Additional information

System
```
Linux 6.1.1-arch1-1
mesa 22.3.1-1
```

Mods

Sodium was the last mod I removed when looking for the source of the leak. I also tried vanilla 1.19.3 and fabric without any mods. The culprit is definitely Sodium.

**Comment by andrejcremoznik** [comment]
I see there's been a commit https://github.com/CaffeineMC/sodium-fabric/commit/679e31be09dec98b0b95039e319f3cb744cfc792 will test

**Comment by andrejcremoznik** [comment]
Build https://github.com/CaffeineMC/sodium-fabric/actions/runs/3735810616 is fine, I'll stick with that until the next release.

**Comment by RobertRR11** [comment]
The same happens to me on Windows 10, after some time uses all my 16 GB of RAM and then fills the pagefile until my storage is full and the game crashes. I'll try the build you provided.

Edit: The provided build fixes it for me too
