### ISSUE TITLE
[culling-fixes] Game crashes when lowering the view distance

### ISSUE THREAD

**Issue by Noryea** [jellysquid3/Sodium#1550]
### Version information

from https://github.com/MCRcortex/sodium-fabric/commit/9cfdcc12a0b2d5a4f5bd61c4582558774b74e170

### Expected Behavior

When you change view distance to fewer and click "Apply", your options should change immediately.

### Actual Behavior

The game crashes.

### Reproduction Steps

1. Enter a singleplayer world
2. Change to creative mode and fly around
3. Change the view distance
4. The game crashes

### Java version

Java 17

### CPU

Intel Core i5-4590

### GPU

Geforce GTX 1050

### Additional information

[crash-2022-12-25_18.08.10-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/10299784/crash-2022-12-25_18.08.10-client.txt)

**Comment by markoloko1223** [comment]
saw some time ago that its some sort of a driver issue but it was from 2020 or 2021

**Comment by jellysquid3** [comment]
Bug reports should not be made on this issue tracker for third-party forks...
