### ISSUE TITLE
Christmas chest bug

### ISSUE THREAD

**Issue by redstonerti** [jellysquid3/Sodium#1552]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build 18

### Expected Behavior

The Christmas chests are flickering

### Actual Behavior

The Christmas chests should be solid

### Reproduction Steps

This is the first time this has happened to me and I didn't do anything to trigger it. I don't know how to reproduce it unfortunately. I have been playing with sodium and Christmas chests for a while and I didn't have this issue until now. Relogging fixed it.

### Java version

Java 17

### CPU

Ryzen 7 7700x

### GPU

GTX 1070 8GB

### Additional information

Windows 11
https://streamable.com/3l8sco

**Comment by redstonerti** [comment]
I just realised that this happened at 12:00AM today. Now the chests aren't Christmas themed, so the bug happened at the time of switching

**Comment by AMDKilla** [comment]
I'm having the same issue on regular chests

**Comment by AMDKilla** [comment]
Nevermind, it's a bug in relation to the Create mod. "/flywheel backend off" removes the glitch.

**Comment by jellysquid3** [comment]
I can't reproduce this issue, and also can't come up with any reason why it would happen. The behavior seems to be identical to vanilla when adjusting the system clock.
