### ISSUE TITLE
Lag spike bug

### ISSUE THREAD

**Issue by AdaptableRuben** [jellysquid3/Sodium#1554]
### Version information

sodium-fabric-mc1.19.3-0.4.6+build.20.jar

### Expected Behavior

The behavior I expected to happen is for the frame rate to remain stable after doing a certain task and for example in my case it would be joining/rejoining a server for a second time after I launched the game for there to be no issues

### Actual Behavior

When you rejoin a server you now constantly experience lag spikes every second which freeze the screen for a few hundreds milliseconds which makes its really frustrating to play multiplayer especially when doing PvP or Parkour because you cant see where you are going or where the player is

I started having this issue with all the versions of this mod that are compatible with 1.19.3
![2022-12-27_15 22 33](https://user-images.githubusercontent.com/59417581/209724419-9599272a-706e-4597-a1b0-205db682785a.png)

### Reproduction Steps

To reproduce this bug, its really simple
1. join any server
2. Leave the server you joined
3. join any server again
4. press alt f3 to confirm this bug

### Java version

java 17.0.3

### CPU

AMD Ryzen 5 2500U

### GPU

AMD Radeon Vega 8 graphics

### Additional information

![modlist](https://user-images.githubusercontent.com/59417581/209724661-d1ae2ee6-2459-4cc2-80f0-8943fd97057f.png)
This is the current list of mods although even removing everything except for phosphor and lithium this optimization error can still be recreated without any issue with my current setup

**Comment by jellysquid3** [comment]
Can you try upgrading to the latest version of Sodium? It fixed a memory leak which may have caused this.

**Comment by AdaptableRuben** [comment]
![2023-01-04_10 20 41](https://user-images.githubusercontent.com/59417581/210601120-3388b20a-4373-4d20-b6b4-9685364cac31.png)
looks like that is not the issue, I still have the same issue after doing the thing that causes this bug on the newest version of sodium available

**Comment by wolfeofark** [comment]
I am having the same issue. Another trigger I noticed was that it also happened when resource packs were loaded/reloaded. I thought it was because of my settings but I tried everything. I run 1.19.2 and have the following mods: 

<img width="490" alt="image" src="https://user-images.githubusercontent.com/123355510/213997646-dd2b6b27-01cf-433c-899f-f79723792de5.png">

I used to get around 130-140fps with these mods but now it's down to less than 60. I thought there was something wrong with my windows so, I did a clean install and Minecraft was back to 130-135fps. But after a few hours, it started happening again.

CPU: Ryzen 5 3500U
GPU: AMD Radeon Vega 8
Java: 19.0.2
Sodium Ver: sodium-fabric-mc1.19.2-0.4.4+build.18

**Comment by pajicadvance** [comment]
Have you tried updating your drivers? You seem to be using drivers provided by Windows Update from 2019. You should be able to get the latest driver from AMD's website.

> I am having the same issue. Another trigger I noticed was that it also happened when resource packs were loaded/reloaded. I thought it was because of my settings but I tried everything. I run 1.19.2 and have the following mods:
> 
> <img alt="image" width="490" src="https://user-images.githubusercontent.com/123355510/213997646-dd2b6b27-01cf-433c-899f-f79723792de5.png">
> 
> I used to get around 130-140fps with these mods but now it's down to less than 60. I thought there was something wrong with my windows so, I did a clean install and Minecraft was back to 130-135fps. But after a few hours, it started happening again.
> 
> CPU: Ryzen 5 3500U GPU: AMD Radeon Vega 8 Java: 19.0.2 Sodium Ver: sodium-fabric-mc1.19.2-0.4.4+build.18

You should probably check if Windows Update downgraded your drivers, that could explain why you're suddenly seeing decreased performance.

**Comment by jellysquid3** [comment]
Closing as stale since we haven't heard back and have no information to work from. Update your graphics drivers, and if the problem still happens, open a new issue.
