### ISSUE TITLE
Sodium-Fabric 0.4.7 crashes

### ISSUE THREAD

**Issue by Melissa-Bunnie** [jellysquid3/Sodium#1557]
### Version information

Sodium 0.4.7

### Reproduction Steps

put Sodium 0.4.7 into the mod folder and tried to run it got the error saying had to hide minecraft version but then iris shaders are saying got a incorrect version of Sodium installed ether had to re download or exit the game. so had to put back Sodium 0.4.6 into the mod folder to get minecraft to work again. i don't have a clue how to get the new updated version to work at all?

![Mod folder](https://user-images.githubusercontent.com/103335212/210127895-a6dabba0-de0d-4555-b902-ae7b734870b1.png)
![Error info when loading up](https://user-images.githubusercontent.com/103335212/210127904-608e8c02-30b7-4f79-bfb1-963f9e4ac703.png)
![error when loading up into minecraft](https://user-images.githubusercontent.com/103335212/210127906-c3cefc6a-54d0-4429-b4ef-8c48f72fa74d.png)

### Crash Report file

no crash report is available to give.

**Comment by RealmKebab** [comment]
install sodium 0.4.7 with iris 1.5

**Comment by Melissa-Bunnie** [comment]
thank you for letting me know and got the updated mods and it still tell me that the vers has to be hidden but it run now ty very kindly <3 happy can go back to playing mc again :3
