### ISSUE TITLE
Soduim Giving Very Low Fps And Not Stable 30-40 fps max

### ISSUE THREAD

**Issue by Jeddy01** [jellysquid3/Sodium#1558]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Expected Behavior

Giving me very high fps like 100 above fps

### Actual Behavior

![image](https://user-images.githubusercontent.com/110292685/210150525-f4b30e95-eecc-4e2d-9527-94bcfb22a302.png)
Giving me 30 to 40 fps above 

### Reproduction Steps

Please fix high fps and for low end system give more fps boost or more performance mod 

### Java version

java 17

### CPU

amd ryzen 5 3500u 

### GPU

amd radeon vega mobile gfx

### Additional information

i have lithuim and phosphor dynamic fps ferrite core induim zoomify rei continuity and cit resewn connected texture

**Comment by jellysquid3** [comment]
This is a support request, not a bug report. [Use the official Discord server to get support.](https://caffeinemc.net/discord)
