### ISSUE TITLE
Sodium 0.4.7 with iris saying "iris failed to load" "sodium is outdated"

### ISSUE THREAD

**Issue by SladeIsTaken** [jellysquid3/Sodium#1559]
### Version information

sodium 0.4.7

### Expected Behavior

The game to launch with sodium 0.4.7 and iris

### Actual Behavior

The game telling me that i have a outdated version of sodium and then telling me to download sodium 0.4.6 instead
Using sodium 0.4.6 the game simply does not load and gives me a bug saying game crashed exit code 1

### Reproduction Steps

iris-mc1.19.3-1.5.0.jar in mods folder
sodium 0.4.7 in the mods folder
fabric api in the mods folder
default mc launcher
better leafs texture pack
faithful 32x faithful texture pack

### Java version

Java 17.04

### CPU

intel core 17 11th gen

### GPU

Intel iris XE graphics

### Additional information

Fabric api (up to date)
Iris (Downloaded from curseforge website for 1.19.3)
Fabric loader (up to date)
Sodium (up to date)
sodium 0.4.7 runs fine on its own not with iris, maybe a issue with the two together
could be on iris's end
i will file a bug report on iris's page

**Comment by BaseCrunch** [comment]
having the same issue please let me know when it gets fixed!

**Comment by jellysquid3** [comment]
The problem is not Sodium. You have conflicting versions of your mods. You probably need to update Iris.
