### ISSUE TITLE
Little to no FPS boost when compared to Optifine, Fluctuating Framerate

### ISSUE THREAD

**Issue by 12Hau** [jellysquid3/Sodium#156]
Sodium Ver 0.1.0
Fabric Ver 0.6.1.45

### Expected Behavior

An FPS boost of any amount

### Actual Behavior

FPS Drop from 60-80 (Optifine) to 40-50 (Sodium), tends to fluctuate between 30 and 60 

### Reproduction Steps

1. Enter world
2. press f3, and check the FPS in the top right corner

### Attachments

![2020-07-23_10 36 03](https://user-images.githubusercontent.com/68701717/88307900-107c4700-ccd2-11ea-8f0a-2bce645628e9.png)
![2020-07-23_10 36 02](https://user-images.githubusercontent.com/68701717/88307903-1114dd80-ccd2-11ea-81e9-b874bef602b6.png)
![2020-07-23_10 35 09](https://user-images.githubusercontent.com/68701717/88307904-11ad7400-ccd2-11ea-8c6b-728a5a74c844.png
![2020-07-23_10 51 44](https://user-images.githubusercontent.com/68701717/88308561-cc3d7680-ccd2-11ea-95f7-f04624800f57.png)
![2020-07-23_10 51 45](https://user-images.githubusercontent.com/68701717/88308564-ccd60d00-ccd2-11ea-9ea5-a1ffcef0b941.png)
![2020-07-23_10 51 51](https://user-images.githubusercontent.com/68701717/88308565-cd6ea380-ccd2-11ea-9c34-3790e0fecea2.png)

### System Information
In Screenshots
- Java Version: [Don't have Java installed on my computer, just using the verison that comes with MC]
- CPU: [Intel(R) Core(TM) i5-4210U CPU]
- GPU: [Intel(R) HD Graphics 4400]

Please tell me if it's just my computer's fault, thanks!

**Comment by jellysquid3** [comment]
You didn't install Sodium. None of our indicators are present in the F3 screen. How are you installing the mod? If you're following a tutorial, could you please link it?

**Comment by 12Hau** [comment]
@jellysquid3 i went back and just realized it wasn't installed, i'll update once i do

**Comment by 12Hau** [comment]
@jellysquid3 fluctuates between 60 and 100, but i'm satisfied. I have a bad graphics card anyway. Will be closing the issue
