### ISSUE TITLE
Sodium is causing an error with my Nividia graphics card

### ISSUE THREAD

**Issue by Endrock6** [jellysquid3/Sodium#1560]
When I launched minecraft with sodium installed on the latest update (0.4.7), I got a notification telling me to restart my game. because the version of sodium I was on was not compatible with my Nividia Geforce GTX 1650 graphics driver. It said that It would hide sodium's version from the graphics card. So when I restarted Minecraft. There at the top in brackets, It says version hidden. Does anyone know of a solution to this?

Edit:
I downgraded to the previous sodium version (0.4.6) and that fixed the issue. But If I try using the new version (0.4.7) I get the same error again.

**Comment by pajicadvance** [comment]
This is not an error, this is an intentional workaround for the Sodium crashes introduced by the latest Nvidia drivers.
See https://github.com/CaffeineMC/sodium-fabric/issues/1486

**Comment by Endrock6** [comment]
I have never experienced crashes with any previous sodium versions. So this 'workaround' is more of hinderment that something helpful. I have also noticed that after the version is hidden from the driver, my games performance is decreased.

**Comment by Risusama** [comment]
I have Nvidia drivers version 516.94 and it still gave me this error. Which is pretty weird, since at issue #1486 it is said that driver 526.47 or later has the issues the workaround is intended for..

**Comment by Endrock6** [comment]
My version is 1650 and my game has never crashed because of the sodium mod. So this workaround is quite pointless for me because it seems to only effect older drivers.

**Comment by jellysquid3** [comment]
We released Sodium 0.4.8 which improves the driver detection and manages to workaround the problem without the need for a pop-up window or game restart. It's much more complicated under the hood and took a lot of time to get right, but it's less annoying for users now.

However, it does not change _which_ users will receive this workaround, and you still cannot disable the workaround via the in-game settings. If you must disable it for whatever reason, which we really don't encourage you to do, you can modify the `sodium-mixins.properties` file in your config directory, and add the following line.

`mixin.workarounds.issue1486=false`
