### ISSUE TITLE
game crashes while entering nether

### ISSUE THREAD

**Issue by Samujaxx** [jellysquid3/Sodium#1564]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Reproduction Steps

1. load game while in overworld
2. enter nether
3. game crashes
4. remove file
5. enter nether again game doesnt crash

### Crash Report file

[hs_err_pid12860.log](https://github.com/CaffeineMC/sodium-fabric/files/10363440/hs_err_pid12860.log)

**Comment by jellysquid3** [comment]
You have an old version of Sodium. Update it.

**Comment by FrozenDragon0** [comment]
Pretty big bummer that this won't be addressed for 1.19.2 considering some mods are still yet to update to 1.19.3
