### ISSUE TITLE
Sodium Crash using Shaders 1.19.2

### ISSUE THREAD

**Issue by YoImErin** [jellysquid3/Sodium#1565]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Reproduction Steps

While playing with Shaders (In this case Complimentary Reimagined, latest version and all), after some time of playing it will randomly crash, I can never tell why. It just does it after some time of playing. Flying around a bunch might have contributed?

### Crash Report file

[crash-2023-01-06_22.05.52-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/10363694/crash-2023-01-06_22.05.52-client.txt)

**Comment by EgorTelitsyn** [comment]
Same

**Comment by Lolothepro** [comment]
it seems that it is a crash of Iris
