### ISSUE TITLE
"Fast" clouds not working

### ISSUE THREAD

**Issue by Abalieno** [jellysquid3/Sodium#1566]
### Version information

sodium-fabric-mc1.19.3-0.4.8+build.22

### Expected Behavior

Clouds should have three settings: off, fancy and fast.

### Actual Behavior

With the last couple of versions clouds can be turned off, or set at their default, but the "flat" option that was always available is not present and clouds are drawn in their "fancy" way even when the option is set at "fast".

### Reproduction Steps

Set graphic settings to "fast"

### Java version

Java 17

### CPU

10900kf

### GPU

gtx 1080

**Comment by Timolino456** [comment]
This is not a bug. Sodium has rewritten cloud rendering, making it have almost no performance impact. There was no use in implementing 'fast' clouds, so the 3D clouds are the only option. It's either turned on or off.

**Comment by Abalieno** [comment]
I personally dislike 3d clouds for how they are rendered and constant pixel crawling, not for performance reasons.

But okay.

**Comment by Estecka** [comment]
@Abalieno It's actually possible to have Fast clouds, by disabling Sodium's cloud renderer and reverting to the vanilla one. This requires delving into some config files:

In `.minecraft/config/sodium-mixins.properties` add the line:
```properties
mixin.features.clouds=false
```
In `.minecraft/options.txt` find the lines called `renderClouds` and update it to:
```properties
renderClouds:"fast"
```
