### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by ninjafoxyoutuber** [jellysquid3/Sodium#157]
The fps has gotten worse from the original 137 to 40, I don't know If I'm doing something wrong or if it generally doesn't work

**Comment by steenburgh** [comment]
>I don't know If I'm doing something wrong or if it generally doesn't work

Please join [JellySquid's discord](https://jellysquid.me/discord) and ask in #tech-support - plenty of friendly people are there + can help you out. The github issue tracker is not meant to be for tech support.

**Comment by jellysquid3** [comment]
This is a question, not an issue. You should direct questions to the Discord server linked above.
