### ISSUE TITLE
[Bug] Banding distortion artifacts

### ISSUE THREAD

**Issue by Tsoccerguy3** [jellysquid3/Sodium#1574]
### Version information

sodium-fabric-mc1.19.3-0.4.8+build.22

### Expected Behavior

There should be no banding or distortion or artifacts . This did not ever happen with optifine

### Actual Behavior

See picture , Mip maps set a 4 . 

### Reproduction Steps

Nothing special just use the mod .

### Java version

Java 17

### CPU

Intel core i7-7700 3.6 GHZ 8 cores

### GPU

Nvidia GTX 1060 6 GB

### Additional information

![2023-01-12_03 39 18](https://user-images.githubusercontent.com/22108822/212019247-87980e89-43e0-40bb-b7c7-f9b69acdace5.png)

**Comment by pajicadvance** [comment]
It is possible that some textures from the resource pack you're using are breaking mipmaps. Optifine has workarounds to prevent this from happening, which explains why it's working fine there. The problematic textures should be printed in the game log, so you can remove them from the resource pack.
