### ISSUE TITLE
When pressing e to gain my inventory my game crashes

### ISSUE THREAD

**Issue by Surgey009** [jellysquid3/Sodium#1575]
### Version information

1.19.2

### Reproduction Steps

1. join a multiplaer surver(this crash only happens on servers)
2. Press e
3. it crashes

### Crash Report file

[crash-2023-01-05_13.04.21-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/10418769/crash-2023-01-05_13.04.21-client.txt)

### Additional information

4. the mods you need are better f3, cem 0.7.1_S8, Continuinity, fabric api, indium, iris, mod menu, fresh animations, not enough animations, suess renewed. Recource packs-classic 3d, beautiful+prot, crops 3d+ Rice. Even with all these mods, it doesn't crash when im accessing inventory on optifine.

**Comment by coderbot16** [comment]
Your Iris version is a buggy out-of-date version, you need to update it to fix the issue.

**Comment by Surgey009** [comment]
alright
