### ISSUE TITLE
Intel Graphics Artifacts

### ISSUE THREAD

**Issue by netflexy** [jellysquid3/Sodium#1579]
### Version information

all

### Expected Behavior

Dont have artifacts

### Actual Behavior

1-2 frames all chunks reloading, light, probably, A-Sync mode
Swap mode - all photosencitive people died in this mode, flickering chunk artifacts.
Affect only intel gpu's, on nvidia's everything is fine

### Reproduction Steps

1. Be photosencitive
2. Break/place block
3. die

### Java version

Java 17

### CPU

Intel Core i5 10-gen

### GPU

Intel UHD graphics 680 (issue on all intel gpu's)

### Additional information

Light issue, when turned off light update, fixed, but unplayable.
Please fix lightning render
thx

**Comment by pajicadvance** [comment]
Duplicate of #869.
