### ISSUE TITLE
Crash Rendering Block Entity

### ISSUE THREAD

**Issue by ClaudiusMinimus** [jellysquid3/Sodium#1580]
### Version information

Sodium 0.4.4+build.18

### Expected Behavior

Should not crash after teleport and seeing a sign

### Actual Behavior

Crashed after teleport and seeing a sign

### Reproduction Steps

1. Teleport
2. Crash

- [Formatted Crash Report](https://crashy.net/XWnt5B1y1KCyxS2Cf0Gv)
- [Raw Crash Report](https://crashy.net/XWnt5B1y1KCyxS2Cf0Gv?raw)
- [Same as above](https://crashy.net/XWnt5B1y1KCyxS2Cf0Gv), but click on Mods > Show Versions as shown below
![image](https://user-images.githubusercontent.com/17887664/213836785-4f0c90fe-f1bd-497a-b7f7-d2f0c61158b9.png)

### Java version

17.0.5

### CPU

Intel© Core™ i7-6700K CPU @ 4.00GHz × 4

### GPU

NVIDIA Corporation TU104 [GeForce RTX 2060]

**Comment by jellysquid3** [comment]
There is no reason to believe this is the fault of Sodium. The problem looks like someone is rendering text from off-thread, which mangles the shared cache in the font renderer.
