### ISSUE TITLE
Graphic artifacts on 1.19.3 sodium

### ISSUE THREAD

**Issue by stromblex** [jellysquid3/Sodium#1581]
### Version information

sodium-fabric-mc1.19.3-0.4.6+build.20

### Expected Behavior

Minecraft normal rendering

### Actual Behavior

Minecraft very strongly artifacts on sodium 1.19.3 (screenshots below)
This started after buying the RX 570 video card, it is fully functional and works fine in other games like cyberpunk 2077.
Who can help? I reinstalled Windows and drivers - nothing helped.

### Reproduction Steps

I don't know if you will have these artifacts, but they appear in any world and server.

### Java version

Java: 17.0.3

### CPU

Phenom II X4 955(3.2GHz) 95w

### GPU

RX 570 4GB

### Additional information

![image](https://user-images.githubusercontent.com/88762254/213869693-5c2bd2c6-2719-447d-982b-22ad4aef4dd4.png)
![image1](https://user-images.githubusercontent.com/88762254/213869696-60d41e3f-4f72-444c-b37b-8c4cd6f5039a.png)

**Comment by mrjasonn** [comment]
I suggest trying with the latest version of sodium for 1.19.3.

**Comment by pajicadvance** [comment]
This should not be a problem anymore starting from Sodium 0.5.0.
