### ISSUE TITLE
FPS glitch

### ISSUE THREAD

**Issue by dakemdi** [jellysquid3/Sodium#1586]
### Version information

1.19.2 fabric

### Expected Behavior

im getting 600fps but it feels like im getting 30fps how can i fix that?

### Actual Behavior

im getting 600fps but it feels like im getting 30fps 

### Reproduction Steps

a

### Java version

a

### CPU

a

### GPU

a

### Additional information

a

**Comment by TheUserCreated** [comment]
Instead of not filling out the bug report, could you include the necessary information to help? System info, java version, perhaps a screenshot of your game running with the issue and the f3 screen open?
