### ISSUE TITLE
Custom resourcepacks render rerror

### ISSUE THREAD

**Issue by z78966789** [jellysquid3/Sodium#1589]
### Version information

sodium-fabric-mc1.18.2-0.4.1+build.15

### Expected Behavior

![2023-01-27_05 58 00](https://user-images.githubusercontent.com/111133655/214961412-96074a25-f149-47e7-8d01-66da8149aeb4.png)

### Actual Behavior

![2023-01-27_05 58 52](https://user-images.githubusercontent.com/111133655/214961428-d75257de-bd34-4081-a24b-de8094188db0.png)

### Reproduction Steps

used resourcepacks: https://www.mediafire.com/file/3mc4e62da73jvsy/resourcepacks.zip

### Java version

17.0.2 64bit

### CPU

16x AMD Ryzen 7 2700X Eight-Core Processor

### GPU

NVIDIA GeForce GTX 1650

### Additional information

I just use one mod sodium, Settings default.

**Comment by z78966789** [comment]
supplement

Vanilla:
![2023-01-27_07 07 47](https://user-images.githubusercontent.com/111133655/214971151-83876abf-a6c8-48cb-8706-e563e4ae16d7.png)
sodium-fabric-mc1.19.3-0.4.8+build.22:
![2023-01-27_07 05 27](https://user-images.githubusercontent.com/111133655/214971252-ca0f3c9a-827e-4867-b8fe-7f8b5245f303.png)

**Comment by Timolino456** [comment]
Looking at the resourcepack, I'm guessing that overlay is done using Minecraft's core shaders? Sodium does not support them, neither does OptiFine. I know you can do some cool things with them, but you really shouldn't use them.

**Comment by Felix14-v2** [comment]
Since this resource pack uses core shaders, compatibility with Sodium should be provided by its author. See [this](https://github.com/CaffeineMC/sodium-fabric/issues/1700#issuecomment-1538907618)
