### ISSUE TITLE
Multidraw (GL 4.3) on future Sodium versions?

### ISSUE THREAD

**Issue by JosephG1thub** [jellysquid3/Sodium#1591]
![OpenGL](https://user-images.githubusercontent.com/123671346/215276051-ae698736-1bbf-4543-8297-48aa3c5cb3ce.png)

I know this mod is in development, but when Minecraft version 1.17 was released, it changed the traditional OpenGL to 3.2 core, and as for sodium, in version 1.16 you could choose OpenGL, so I propose to return that feature. I'm not a programmer so I don't know how hard this could be, but this helped EXTREMELY performance.

I speak Spanish, sorry if there is something misspelled, good bye.

**Comment by silversquirl** [comment]
The techniques used in the old multidraw renderer are now used by default on all systems.
