### ISSUE TITLE
doesn't improve fps at all

### ISSUE THREAD

**Issue by carter370** [jellysquid3/Sodium#1592]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18

### Expected Behavior

The mod should improve fps

### Actual Behavior

FPS did not change before and after adding mod.
Before:
![image](https://user-images.githubusercontent.com/49829952/215277274-513fad94-ddcd-4773-b957-90122d3c1bf7.png)
After:
![image](https://user-images.githubusercontent.com/49829952/215277276-8894e2cf-317b-4fe9-a650-6c7355038b80.png)

### Reproduction Steps

1. Check fps before install
2. Install mod
3. Check fps after install

### Java version

Java 17.0.3

### CPU

AMD Ryzen 5 5600X

### GPU

NVIDIA GeForce GTX 1070 Ti

### Additional information

N/A

**Comment by JosephG1thub** [comment]
Apparently you have the fps capped at 30 in game settings, you can also try disabling vsync.

**Comment by silversquirl** [comment]
Please test with uncapped FPS (can be changed in video settings - change the cap back to something sensible after testing, like 60 or 120).
If you're still having issues after that, the [CaffeineMC discord](https://jellysquid.me/discord) is probably a better place to get help.

**Comment by carter370** [comment]
![image](https://user-images.githubusercontent.com/49829952/215908322-d34e36de-d584-4dd9-893c-350161128824.png)
it work 👍
