### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by CSLjiaowo** [jellysquid3/Sodium#1593]
Hello Sodium Team, I noticed that the popular mod Sodium only has an English version! I have submitted a Chinese translation and hope you can accept it, thank you.
[zh_cn.zip](https://github.com/CaffeineMC/sodium-fabric/files/10529660/zh_cn.zip)

**Comment by TheKodeToad** [comment]
I don't know if this is up-to-date, but it seems that the translations are handled on crowdin.  I found this at https://github.com/amnotbananaama/sodium-fabric-translations#translating.

Just posting this because I think it will be a while before someone else sees this.

**Comment by Madis0** [comment]
Duplicate of #44
