### ISSUE TITLE
Sodium decreasing FPS?

### ISSUE THREAD

**Issue by Leon151101** [jellysquid3/Sodium#1595]
I recently got a new PC (4070Ti, Ryzen 5 7600X). I know with these specs I should'nt need performance mods but I installed them anyway. I noticed on average I get 500-700 FPS Vanilla but with Sodium it averages at 300-400.

On my old PC (1070Ti, Ryzen 7 2700X) Sodium helped, but also just barely (maybe +50 FPS max.)

I'm currently playing in 1.19.3 (fabric)
Sodium version: sodium-fabric-mc1.19.3-0.4.8+build.22

**Comment by TH3N3WN00B** [comment]
Can you provide more info? any other mods? what are your configs? this happens on single player or multiplayer? driver version? fabric api version? etc...

**Comment by jellysquid3** [comment]
There isn't enough information to diagnose this problem, and the issue tracker isn't the place for reporting issues to do with poor performance. Read the [known issues](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility) and use the [Discord server](https://caffeinemc.net/discord) if you are still having issues.
