### ISSUE TITLE
Error: java.lang.IllegalStateException: Config not yet available

### ISSUE THREAD

**Issue by YuneGit** [jellysquid3/Sodium#1596]
### Version information

1.19.2 Sodium 0.4.4+build.18

### Reproduction Steps

Launching the Game

### Crash Report file

[crash-2023-01-31_15.32.27-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/10547383/crash-2023-01-31_15.32.27-client.txt)

### Additional information

I've added TooManyCrashes however I'm not sure it helps

**Comment by YuneGit** [comment]
I meant "NotEnoughCrashes"* woops

**Comment by YuneGit** [comment]
I have already tried deleting the config files completely

**Comment by Timolino456** [comment]
Remove Not Enough Crashes and try again.
