### ISSUE TITLE
With sodium, it renders a blank world.

### ISSUE THREAD

**Issue by CaptainLeonidas** [jellysquid3/Sodium#1597]
Hello. This is a very odd bug I found whilst playing minecraft on the lastest relase of 1.19.3 with the updated JDK 19. With other fps boosting mods, it seems I ruled out that sodium is at fault. Here is a picture to reinforce my statement:
![2023-02-01_18 29 56](https://user-images.githubusercontent.com/110267972/216191021-db029f66-57ee-4cdd-9dfc-3ac7c05541a2.png) -thank you.

**Comment by TheUserCreated** [comment]
Can you reproduce this issue with just sodium, and a version of java that minecraft officially supports? If so, could you show a screenshot of your f3 screen with the issue occuring?

**Comment by jellysquid3** [comment]
This is not an issue with Sodium. You have some other mod which is breaking the renderer. If you believe otherwise, provide a list of mods you are using and a client log file.

**Comment by CaptainLeonidas** [comment]
Hi JellySquid.
Sorry for the late reply, got caught up with work.
Yes, it is not regarding sodium. The problem is the add-ons with it. Sodium
extra and reccees sodium settings (extra options to your great mod!) Causes
the screen to go white. I can give you screenshots tomorrow in the morning
to further analyze. Thank you boss!
