### ISSUE TITLE
anthonyhilyard iceberg renderer error?

### ISSUE THREAD

**Issue by orbittwz** [jellysquid3/Sodium#1603]
### Version information

mc1.19.3-fabric-sodium0.4.9-iris1.5.2

### Reproduction Steps

https://mclo.gs/5EGPveO
happened randomly after 5 minutes of gameplay
cull leaves mod is disabled since it causes crashes when loading a save...

### Crash Report file

https://mclo.gs/5EGPveO

**Comment by orbittwz** [comment]
oh it happened again now, when I tried to craft a pickaxe and just before it was created the game crashed.
~~also I see a weird outline on cliffside ground, dunno if that's related.~~ - OK it was a shadow so nevermind this issue.

reverting to previous versions of all related mods for now, which are Sodium, Iris and Indium.

**Comment by Timolino456** [comment]
Seems like the second report of #1602. Either disable Legendary Tooltips or downgrade Sodium for now (I recommend the former).

**Comment by orbittwz** [comment]
reverted, managed to craft the pickaxe... still checking

**Comment by orbittwz** [comment]
> Seems like the second report of #1602. Either disable Legendary Tooltips or downgrade Sodium for now (I recommend the former).

I see, but this mod is pretty nice...
Can't seem to mention the author of Legendary Tooltips here.
his nick is AHilyard

EDIT: saw you referenced this to the author, thanks!

**Comment by Timolino456** [comment]
They replied by the way: "In the meantime, you can [...] disable 3D item previews in Legendary Tooltips if you want to continue using both mods."

**Comment by orbittwz** [comment]
> They replied by the way: "In the meantime, you can [...] disable 3D item previews in Legendary Tooltips if you want to continue using both mods."

Oh, sure I can try that!
Do update when it will be fixed...

**Comment by pajicadvance** [comment]
Should now be fixed by using the latest version of Legendary Tooltips, Iceberg and Sodium.

**Comment by orbittwz** [comment]
Thank you very much! will check it soon...
