### ISSUE TITLE
Fix item models in Minecraft using Sodium

### ISSUE THREAD

**Issue by mrjasonn** [jellysquid3/Sodium#1607]
**Is your feature request related to a problem? Please describe.**
This is not sodium related, but it would be good for sodium to fix this vanilla Minecraft issue

**Describe the solution you'd like**
Fix the line holes in items such as a sword and possibly even block gaps if it won't interfere performance by a good enough amount.
Also currently using Sodium 0.4.9 for Minecraft 1.19.3

**Describe alternatives you've considered**
None

**Additional context**
[Image (vanilla issue)](https://i.imgur.com/GOYy4Bd.png)

**Comment by Timolino456** [comment]
There are already mods for this, called Item Model Fix and Model Gap Fix. The latter is updated to 1.19.3 and also fixes block gaps.

**Comment by mrjasonn** [comment]
> There are already mods for this, called Item Model Fix and Model Gap Fix. The latter is updated to 1.19.3 and also fixes block gaps.

I know, but Sodium should fix this without any other mods as it also wants to fix graphical issues/bugs in Minecraft that aren't already fixed and not just performance optimisations.

**Comment by Aculoss** [comment]
Chiselled bookshelves have the missing texture using sodium :(

**Comment by mrjasonn** [comment]
> Chiselled bookshelves have the missing texture using sodium :(

If you have that issue then just make a new issue about it.

**Comment by jellysquid3** [comment]
https://modrinth.com/mod/modelfix
