### ISSUE TITLE
Workaround for #1486 breaks compatibility with Special K

### ISSUE THREAD

**Issue by kamild1996** [jellysquid3/Sodium#1608]
### Version information

mc.1.19.3-0.4.9+build.23

### Expected Behavior

Special K gets injected on launching the game and works.

### Actual Behavior

Special K claims it's injected, but does not work in-game.

### Reproduction Steps

1. Create an empty file called "SpecialK.OpenGL32" inside the "bin" folder of the Java installation you're using to launch the game.
2. Add your launcher to the SKIF (Special K Injection Frontend) and run the launcher through it.
3. Launch Minecraft

### Java version

Java 17

### CPU

AMD Ryzen 7 3700X

### GPU

NVidia GeForce RTX 3070 Ti

### Additional information

This bug prevents Special K from being injected on Sodium 0.4.8 and above.
The workaround is to disable the workaround for #1486 by adding `mixin.workarounds=false` to `config/sodium-mixins.properties`. Special K now injects successfully, and since Special K prevents the NVIDIA driver from applying a problematic optimization, it also seems to serve as a workaround for #1486 in itself, preventing crashes (tested it myself by reloading chunks on driver 528.24).

**Comment by jellysquid3** [comment]
Commit https://github.com/CaffeineMC/sodium-fabric/commit/8ae68cfa82949a09d53b6ea066ebdba40d5674d4 fixes the issue as we no longer create an additional OpenGL context, which allows SpecialK to hook correctly.
