### ISSUE TITLE
unable to load world

### ISSUE THREAD

**Issue by jay210606** [jellysquid3/Sodium#161]
i created a new world with fabric launcher and i save it, the next day when i try to open it, it keep on showing me loading loading loading

**Comment by amnotbananaama** [comment]
Can you attach a log file, or link to a paste site from when this occurs? Additionally, can you provide the system information from the issue template? That will let us know if the issue is caused by your system being underpowered.


> ### System Information
> You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.
> 
> - Java Version: [fill me in]
> - CPU: [fill me in]
> - GPU: [fill me in]

**Comment by jellysquid3** [comment]
This issue doesn't contain any diagnostic information and nothing from the issue template. We don't have the information to help you. Please provide the relevant information above and then request for this issue to be re-opened.
