### ISSUE TITLE
FPS not going higher than 135

### ISSUE THREAD

**Issue by RetroWave1736** [jellysquid3/Sodium#1610]
### Version information

mc1.16.5-0.2.0+build.4

### Expected Behavior

My fps to be higher than what I normaly get being 210 while using optifine

### Actual Behavior

My fps being capped at 135 not allowing me to see gained fps

### Reproduction Steps

I don't know how to reproduce it, it just happens.

### Java version

Can't Find Version

### CPU

Ryzen 5 3600 6-Core Processor

### GPU

RTX 2060 EVO

### Additional information

So I want to switch from Optifine to Sodium but for some reason I can't get fps values higher than 135. I change the setting the the minimum, set fps to max, use v-sync on and off, but still no fps higher than 135. I don't see any options that are causing this nor if I know if it is a bug or intended feature. How do I fix this and if it is a bug, please fix it.

**Comment by SolDev69** [comment]
Sodium is kinda mid on 1.16.5, in some situations Optifine is actually faster. But this seems concerning, you aren't getting higher than 135fps at all?

**Comment by RetroWave1736** [comment]
I only get fps higher than 135 at some points but only by like 2 or 3 fps

**Comment by ghost** [comment]
If the hardware can physically give out more than 135FPS, then check the nVidia control panel settings, it is possible that the driver uses V-Sync for the game.
