### ISSUE TITLE
Sodium not working with optifabric

### ISSUE THREAD

**Issue by AshesTTV** [jellysquid3/Sodium#1611]
I cant use shaders with just sodium (and indium) so I tried readding optifabric to re-enable shaders and it doesn't allow it. (1.19.0)

ERROR MESSAGE:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.2+build.16 with version 0.4.2 that is compatible with:
		 - optifabric 1.13.5
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.4.2+build.16 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.5!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by pajicadvance** [comment]
They are not compatible and will never be. Use one or the another. If you want shaders with Sodium use Iris Shaders.
