### ISSUE TITLE
Custom resolution/framerate

### ISSUE THREAD

**Issue by KoopaLoveTOAST** [jellysquid3/Sodium#1613]
HI! 
I am using a 60 hertz monitor but I have a custom resolution setting that is able to squeeze 72 hertz out of it. This is generally accepted by most games but not by Minecraft 1.19.3 with sodium. When I set the game to fullscreen it automatically changes back to the 60 hertz resolution and I can not choose the other one in the settings.

If you could add a setting like that. That would be lovely :)

Also in most older versions of the game, the game just keeps the resolution that I start it with, i.e. I can play on 72 hertz. Not in the 1.19.3 with Sodium. Sodium extra also doesn't help. I've tried everything...

Other than that great work, keep it up! :)

**Comment by Calinou** [comment]
Look into using [Borderless Gaming](https://github.com/Codeusa/Borderless-Gaming) (it's free on GitHub Releases), so you can keep using windowed mode but make it look like it's fullscreen. This will allow you to keep using your custom resolution even in games that don't "see" your custom resolution.

**Comment by comp500** [comment]
On Windows this is an issue with the library Minecraft uses to create the game window, GLFW. See https://github.com/glfw/glfw/pull/2209 and https://github.com/comp500/BorderlessMining/issues/26
