### ISSUE TITLE
Clouds option tooltip refers to quality rather than presence

### ISSUE THREAD

**Issue by haykam821** [jellysquid3/Sodium#1614]
On Sodium 0.4.9 for Minecraft 1.19.3, the cloud renderer is replaced by a more performant implementation. As a result, the clouds option is now a simple checkbox rather than a toggle between fast, fancy, and off. However, the tooltip was not updated:

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/24855774/218265893-12b21da2-e13d-46b9-b631-5e61e681b326.png">

**Comment by IMS212** [comment]
Fixed in https://github.com/CaffeineMC/sodium-fabric/commit/4332be836fde48206b98b7316ebb005c1f383745.
