### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by EldraTheThird** [jellysquid3/Sodium#1616]
### Version information

mc1.16.5-0.2.0

### Expected Behavior

Works normally like when logging into the server with OptiFine, VulkanMod,...

### Actual Behavior

The screen goes dark (I mean when there's a blind effect in the game when logging into the server, everything in the game suddenly "dark" like the font, the display of the game, ...)
See pictures to understand what I mean :/

### Reproduction Steps

I don't know, when I joined the server it was already :/

### Java version

Java 8 (Eclipse Termurin)

### CPU

Intel Celeron G1840

### GPU

 Intel® HD Graphics for 4th Generation Intel® Processors (i dont know the name of this GPU :/)

### Additional information

![2023-02-12_10 52 42](https://user-images.githubusercontent.com/108326998/218292106-4cae69f7-fc94-42a9-baae-95775d5aea36.png)
![2023-02-12_10 52 47](https://user-images.githubusercontent.com/108326998/218292113-54ae856f-3108-4387-b302-4e252f2bf22b.png)
![2023-02-12_10 52 20](https://user-images.githubusercontent.com/108326998/218292114-4a3d2795-c211-440d-94df-b9c41097acd9.png)
![2023-02-12_10 52 40](https://user-images.githubusercontent.com/108326998/218292115-090bd89a-1f29-4017-932a-77c3f62eecd2.png)

**Comment by Timolino456** [comment]
Try updating your Intel drivers via the Intel website.

**Comment by EldraTheThird** [comment]
> Try updating your Intel drivers via the Intel website.

i tried and doesn't work :/ 
but I remember that there is a mod that can fix this error of Sodium (1.16x)

**Comment by jellysquid3** [comment]
Per our new [hardware support policy](https://github.com/CaffeineMC/sodium-fabric/blob/3f12f36e58d977f417d22ea6e643a9d7aeb4f0ca/README.md#-hardware-compatibility), your graphics card does not meet the required specifications. As such, this issue is being closed as "won't fix."
