### ISSUE TITLE
Missing texture

### ISSUE THREAD

**Issue by Aculoss** [jellysquid3/Sodium#1618]
### Version information

1.19.3 - 23w06a

### Expected Behavior

To see the chiselled bookshelf.

### Actual Behavior

The chiselled bookshelf has the missing texture. (Purple and black).

### Reproduction Steps

Install Sodium.
Craft a chiselled bookshelf.
Place or look in hotbar.

### Java version

17

### CPU

Intel i3

### GPU

Intel HD Graphics

**Comment by Timolino456** [comment]
I can't reproduce this. Are you using any other mods? Are your Intel drivers up to date?
![2023-02-12_11 27 24](https://user-images.githubusercontent.com/38137599/218305644-920576fe-8b0a-4930-93a2-57d5e760ffe2.png)

**Comment by jellysquid3** [comment]
There isn't enough information to diagnose this. If you are still experiencing the problem, open a new issue and follow the updated guide for reporting bugs.
