### ISSUE TITLE
Minecraft crashes not even fully loading.

### ISSUE THREAD

**Issue by Pronkill** [jellysquid3/Sodium#162]
I used fabric later, and it didn't crashed, but when I installed sodium, it crashed.
[latest.log](https://github.com/jellysquid3/sodium-fabric/files/4971592/latest.log)

**Comment by amnotbananaama** [comment]
This is not caused by Sodium, and can be closed as an external issue. You are using a version of clientcommands for 1.15.2 instead of 1.16.1. Update to the latest version of clientcommands.

**Comment by Pronkill** [comment]
ok. thanks
