### ISSUE TITLE
MiniMessage autofill command from chat

### ISSUE THREAD

**Issue by CitralFlo** [jellysquid3/Sodium#1625]
### Version information

LunarClient (1.19.3-0caf49b/master) and sodium-fabric-mc1.19.3-0.4.8+build.22

### Expected Behavior

After clicking on command sent to chat with onclick we should get autofilled minecraft command. 
In example autofilled command should be /tpaccept. 

### Actual Behavior

It didn't autofill command. Nothing happend

### Reproduction Steps

1. Use MiniMessage editor on server.
2. For example send /tpa request to player, with a autofill option for command.
3. Try clicking on message

### Java version

Java 17.0.3

### CPU

16x 11th Gen Intel(R) i7-11

### GPU

NVIDIA GeForce RTX 3060

**Comment by vLuckyyy** [comment]
On vanilla client, works perfectly, on sodium it doesn't work
https://user-images.githubusercontent.com/65517973/219225635-4b8dabf3-32de-4157-a367-c21610b7f997.mp4

**Comment by jellysquid3** [comment]
This has nothing to do with Sodium. More likely than not, it's Lunar Client doing something weird... we don't touch any GUI code which would affect this behavior.
