### ISSUE TITLE
Cells from Tech Reborn are invisible

### ISSUE THREAD

**Issue by bentterp** [jellysquid3/Sodium#163]
### Expected Behavior
The cells should be shown with their content in different colors
### Actual Behavior
Only the count in the stack is shown, and the hover text with the cell type
### Reproduction Steps
Install Tech Reborn
Create some cells
Install Sodium

### Attachments
![image](https://user-images.githubusercontent.com/5476397/88388667-42b2a500-cdb5-11ea-83a5-e35dfea017fe.png)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: 1.8.0.251]
- CPU: i7-6600U
- GPU: Intel HD Graphics 520

**Comment by amnotbananaama** [comment]
Duplicate of #5

**Comment by bentterp** [comment]
Sorry, didn't even check for duplicates. My bad
