### ISSUE TITLE
Extreme culling of chests

### ISSUE THREAD

**Issue by nshjck** [jellysquid3/Sodium#1630]
### Version information

mc1.19.3-0.4.9+build.23

### Expected Behavior

The chests would keep rendering until out of sight
![2023-02-19_18 55 59](https://user-images.githubusercontent.com/123022316/219969565-8b9f24a0-cb2f-49f2-a0af-92a04ea70192.png)

### Actual Behavior

the chests would stop rendering while still in view making part of or the whole ches tinvisible
![huge_2023-02-19_18 53 51](https://user-images.githubusercontent.com/123022316/219969571-868782d2-891a-4aad-8d43-5d18e01d015d.png)

### Reproduction Steps

place a chest and move around so near a corner and the chest will dissapear

### Java version

Java 19.0.2

### CPU

AMD Ryzen 5 4500

### GPU

NVIDIA Geforce GTX 1650 super

### Additional information

I am using fabulously optimized for performance.

**Comment by jellysquid3** [comment]
The problem is not with Sodium. You are using a modpack with a ton of different optimization mods. Probably some variant of "Entity Culling" is causing it.

If you believe otherwise, please reproduce the issue with only Sodium installed.
