### ISSUE TITLE
Crash with item rendering

### ISSUE THREAD

**Issue by milosworks** [jellysquid3/Sodium#1631]
### Version information

sodium-fabric-mc1.19.3-0.4.9+build.23

### Reproduction Steps

1. Install latest release of EMI
2. Create a new world
3. Open your inventory and change pages very fast and eventually it will crash

### Crash Report file

https://hst.sh/zucekiruhe

**Comment by Timolino456** [comment]
"Caused by: java.lang.ClassCastException: class dev.emi.emi.screen.StackBatcher$UnlitFacade$Consumer cannot be cast to class me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter"
Looks like the same problem as for #1602
