### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by Guest635109** [jellysquid3/Sodium#1632]
It doesn't have a button to change the resolution of the full screen game

For example, my minecraft has a resolution bug when I make it fullscreen, so I need the change resolution button, and maybe other people need it too

Pls, put a button to change the resolution of the game. Thx

**Comment by sonic-veemo** [comment]
Is there not a Fullscreen Resolution slider that you can get to?

**Comment by Timolino456** [comment]
Press Shift+P to get to the vanilla menu to change it or download Sodium Extra.
