### ISSUE TITLE
Chiseled bookshelves not displaying properly unless right clicked with a book

### ISSUE THREAD

**Issue by mrjasonn** [jellysquid3/Sodium#1634]
### Version information

sodium-fabric-mc1.19.3-0.4.9+build.23

### Expected Behavior

When you place down a chiseled bookshelf with already books inside, it does not display until you right click it with a book.

### Actual Behavior

When you place the chiseled bookshelf with already books inside, it does not display until you right click update it with a book.

### Reproduction Steps

1. Place a chiseled bookshelf down.
2. Put the books inside.
3. Middle click with control/ctrl held down (assuming you are using windows)
4. Place the one with the NBT data down, you won't see the books yet.
5. Right click it with a book and you will see it.

### Java version

Java 17.0.3 (bundled from Minecraft)

### CPU

Intel Core i7-8700

### GPU

Intel UHD Graphics 630

### Additional information

Windows 11 22H2
Graphics driver version 31.0.101.2115
<details>
<summary>Mods (according to the logs) look carefully</summary>
	- boostedbrightness 2.1.3
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- com_moandjiezana_toml_toml4j 0.7.2 via dynamicfps
	- dynamicfps 2.2.0
	- fabric-api 0.73.2+1.19.3
	- fabric-api-base 0.4.21+70be179c85 via fabric-api
	- fabric-api-lookup-api-v1 1.6.20+49abcf7e85 via fabric-api
	- fabric-biome-api-v1 12.1.1+b5d379b085 via fabric-api
	- fabric-block-api-v1 1.0.5+e022e5d185 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.30+c6af733c85 via fabric-api
	- fabric-client-tags-api-v1 1.0.12+1134c5b885 via fabric-api
	- fabric-command-api-v1 1.2.22+f71b366f85 via fabric-api
	- fabric-command-api-v2 2.2.1+3fc4752e85 via fabric-api
	- fabric-commands-v0 0.2.39+df3654b385 via fabric-api
	- fabric-containers-v0 0.1.47+df3654b385 via fabric-api
	- fabric-content-registries-v0 3.5.1+1d37d50285 via fabric-api
	- fabric-convention-tags-v1 1.2.2+8e4e694f85 via fabric-api
	- fabric-crash-report-info-v1 0.2.14+aeb40ebe85 via fabric-api
	- fabric-data-generation-api-v1 11.2.1+06937c4b85 via fabric-api
	- fabric-dimensions-v1 2.1.41+48349a3f85 via fabric-api
	- fabric-entity-events-v1 1.5.7+b83334a085 via fabric-api
	- fabric-events-interaction-v0 0.4.40+3baeb27a85 via fabric-api
	- fabric-events-lifecycle-v0 0.2.44+df3654b385 via fabric-api
	- fabric-game-rule-api-v1 1.0.30+99f9db8085 via fabric-api
	- fabric-item-api-v1 2.1.10+312c329485 via fabric-api
	- fabric-item-group-api-v1 2.1.12+1134c5b885 via fabric-api
	- fabric-key-binding-api-v1 1.0.31+bc01e09785 via fabric-api
	- fabric-keybindings-v0 0.2.29+df3654b385 via fabric-api
	- fabric-lifecycle-events-v1 2.2.10+23a79c8a85 via fabric-api
	- fabric-loot-api-v2 1.1.20+75e9821185 via fabric-api
	- fabric-loot-tables-v1 1.1.24+9e7660c685 via fabric-api
	- fabric-message-api-v1 5.0.14+6ede1da985 via fabric-api
	- fabric-mining-level-api-v1 2.1.31+49abcf7e85 via fabric-api
	- fabric-models-v0 0.3.27+11ba9c3b85 via fabric-api
	- fabric-networking-api-v1 1.2.17+4017a8cb85 via fabric-api
	- fabric-networking-v0 0.3.34+df3654b385 via fabric-api
	- fabric-object-builder-api-v1 5.4.1+eb2a3ba985 via fabric-api
	- fabric-particles-v1 1.0.20+f1e4495b85 via fabric-api
	- fabric-recipe-api-v1 1.0.1+5176f73d85 via fabric-api
	- fabric-registry-sync-v0 2.0.5+1134c5b885 via fabric-api
	- fabric-renderer-api-v1 2.2.1+9f179aa185 via fabric-api
	- fabric-renderer-indigo 0.7.1+9f179aa185 via fabric-api
	- fabric-renderer-registries-v1 3.2.30+df3654b385 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.25+afca2f3e85 via fabric-api
	- fabric-rendering-fluids-v1 3.0.18+f1e4495b85 via fabric-api
	- fabric-rendering-v0 1.1.33+df3654b385 via fabric-api
	- fabric-rendering-v1 1.12.1+eb2a3ba985 via fabric-api
	- fabric-resource-conditions-api-v1 2.2.3+1134c5b885 via fabric-api
	- fabric-resource-loader-v0 0.10.5+a91e48b785 via fabric-api
	- fabric-screen-api-v1 1.0.41+f1e4495b85 via fabric-api
	- fabric-screen-handler-api-v1 1.3.13+99f9db8085 via fabric-api
	- fabric-sound-api-v1 1.0.8+75e9821185 via fabric-api
	- fabric-transfer-api-v1 2.1.15+ccd377ba85 via fabric-api
	- fabric-transitive-access-wideners-v1 2.3.1+5b9a588b85 via fabric-api
	- fabricloader 0.14.14
	- io_github_douira_glsl-transformer 2.0.0-pre9 via iris
	- iris 1.5.2
	- java 17
	- lazydfu 0.1.3
	- lithium 0.10.4
	- minecraft 1.19.3
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- reeses-sodium-options 1.4.9+mc1.19.2-build.67
	- sodium 0.4.9+build.23
	- sodium-extra 0.4.17+mc1.19.3-build.95
	- starlight 1.1.1+fabric.ae22326
	- wi_zoom 1.4-MC1.19.3
</details>

**Comment by embeddedt** [comment]
I don't think this is a Sodium bug; I can reproduce it in vanilla too.
