### ISSUE TITLE
Options Problem

### ISSUE THREAD

**Issue by Symmettry** [jellysquid3/Sodium#1637]
### Version information

sodium-fabric-mc1.19.3-0.4.8+build.22

### Expected Behavior

Options: FOV Effects

### Actual Behavior

There is no "FOV Effects" option in Options ->Video Settings

### Reproduction Steps

Options -> Video Settings -> No fov effects option

### Java version

Java 19

### CPU

Intel Core i5-9400

### GPU

Nvidia GeForce GTX 1660 Ti

**Comment by jellysquid3** [comment]
It's in the Settings > Accessibility menu.

**Comment by Symmettry** [comment]
Guess im an idiot
