### ISSUE TITLE
Ability to use Shaders.

### ISSUE THREAD

**Issue by doonv** [jellysquid3/Sodium#164]
Sodium is great at optimizing performance, a little too good.

Shader Support would be great. High FPS Shaders will be awesome.

**Comment by ZtereoHYPE** [comment]
Sodium is an optimisation mod and it's currently not planned to bring shaders/connected textures/other Optifine features of that kind. You can take a look at Canvas for a possible future shader platform for fabric, but it's not compatible with sodium.

**Comment by NatoBoram** [comment]
> You can take a look at Canvas for a possible future shader platform for fabric, but it's not compatible with sodium.

https://github.com/grondag/canvas

**Comment by Tmpod** [comment]
> You can take a look at Canvas for a possible future shader platform for fabric, but it's not compatible with sodium.

Is it because of some fundamental conflict or something that can eventually be worked on? It would be really nice to have both great optimization and shaders, connected textures and all that.

**Comment by Dolphin2Point1** [comment]
its a fundamental issue, both mods replace the rendering engine. Canvas does it to add shaders, sodium does it to optimize it. You could try to combine them into 1 mod, but the process may not be worth the time, so sodium doesn't add shaders, and canvas doesn't add many optimizations.

**Comment by IMS212** [comment]
Iris may eventually be compatible with sodium, but it isn't currently and it's nowhere near complete.

**Comment by NatoBoram** [comment]
> Iris may eventually be compatible with sodium

https://github.com/IrisShaders/Iris

**Comment by fsharpseven** [comment]
Shouldn't this issue be closed?
