### ISSUE TITLE
Add Apple Silicon specific optimisations for macOS

### ISSUE THREAD

**Issue by mrjasonn** [jellysquid3/Sodium#1645]
**Is your feature request related to a problem? Please describe.**
It's not optimised enough for Apple Silicon Macs

**Describe the solution you'd like**
Add Apple Silicon specific optimisations for macOS and also some in-general optimisations for Macs
**Describe alternatives you've considered**
No alternatives

**Additional context**
No additional context

**Comment by IMS212** [comment]
M1 support will be dropped in a future Sodium release.

macOS devices have notoriously bad OpenGL drivers which are hard to support, this is not the fault of Sodium or Minecraft.

**Comment by iMonZ** [comment]
> M1 support will be dropped starting with Sodium 0.5.
> 
> macOS devices have notoriously bad OpenGL drivers which are hard to support, this is not the fault of Sodium or Minecraft.

How about 
https://github.com/xCollateral/VulkanMod
?

**Comment by TheUserCreated** [comment]
Vulkan Mod and Sodium are incompatible entirely. VulkanMod redoes the renderer in a way that makes it use vulkan, while sodium uses OpenGL like vanilla. MacOS actually doesn't officially support *either* of these anymore, but vulkan applications sometimes work on MacOS through MoltenVK. This is not an option for sodium, and compatibility in the future would have to be achieved some other way.

**Comment by iMonZ** [comment]
> Member

Actually it is. Sodium and Minecraft are using outdated Legacy Tools.
So its actually not Apples fault for not supporting dead tools.
Not supporting Metal is totally fine since of the low user base.
But not supporting Vulkan which is the official replacement of OpenGL is kinda Legacy

**Comment by jellysquid3** [comment]
We're not implementing support for Metal or Vulkan. This has been discussed to death on the issue tracker. It is not a magic bullet for performance, especially when Java makes interacting with these low-level APIs so incredibly difficult and slow.
