### ISSUE TITLE
Translating Mod

### ISSUE THREAD

**Issue by Salih-Berat** [jellysquid3/Sodium#1648]
If sodium would have multiple language support it would be really good. I am wanting translate this to turkish. But i dont lnow how to do. Can anyone help me?

**Comment by ghost** [comment]
Fork the repository, create language_code.json like [this](https://github.com/CaffeineMC/sodium-fabric/blob/1.19.3/dev/src/main/resources/assets/sodium/lang/en_us.json), translate and finally just make pull request.

**Comment by Madis0** [comment]
Duplicate of #44
