### ISSUE TITLE
sodium 0.2.0 - Quilt 1.16.3-1.16.5 support available?

### ISSUE THREAD

**Issue by vrgtics** [jellysquid3/Sodium#1649]
**Is your feature request related to a problem? Please describe.**
I try to find 1.16.5 version of sodium in your official modrinth but your mod lowest version only down to 1.18.2 - sodium 0.4.1

**Describe the solution you'd like**
I speedrun/play 1.16 but I would like to using Quilt modloader, it is great to have 1.16(.5) sodium Quilt compatible version's option back please, thanks.

**Describe alternatives you've considered**
_n/a_

**Additional context**
_n/a_

**Comment by GaucovyAero** [comment]
check curseforge

**Comment by vrgtics** [comment]
> check curseforge

nope

**Comment by Lolothepro** [comment]
Although not explicitly written, Sodium 0.2.0 is compatible with Quilt

**Comment by vrgtics** [comment]
> Although not explicitly written, Sodium 0.2.0 is compatible with Quilt

well thank you but is easy for you to say when you not keep getting crashes, either I turn off ALL options or in single draw in Performance tab in minecraft settings

NOT that once when launching the game, IT IS when enter the world any world then got crashed for no reason, I tested NOT the ram problem. So I cannot give you any syntax error log.

**Comment by Lolothepro** [comment]
> > Although not explicitly written, Sodium 0.2.0 is compatible with Quilt
> 
> well thank you but is easy for you to say when you not keep getting crashes, either I turn off ALL options or in single draw in Performance tab in minecraft settings
> 
> NOT that once when launching the game, IT IS when enter the world any world then got crashed for no reason, I tested NOT the ram problem. So I cannot give you any syntax error log.

this only happens with Quilt?

**Comment by vrgtics** [comment]
> > > Although not explicitly written, Sodium 0.2.0 is compatible with Quilt
> > 
> > 
> > well thank you but is easy for you to say when you not keep getting crashes, either I turn off ALL options or in single draw in Performance tab in minecraft settings
> > NOT that once when launching the game, IT IS when enter the world any world then got crashed for no reason, I tested NOT the ram problem. So I cannot give you any syntax error log.
> 
> this only happens with Quilt?

I was used to on fabric it has no such problem at all, I guess I will disable and reinstall sodium one more time if development didn't do anything yet

**Comment by vrgtics** [comment]
here is it, I have no idea why just reinstalling can solved the problem, but it costs me 3 days, what is the matter of first and second files. Simply it work again, I'm sorry but thanks for helping me
