### ISSUE TITLE
Surfaces becoming see-through

### ISSUE THREAD

**Issue by KappaDied** [jellysquid3/Sodium#1656]
![image](https://user-images.githubusercontent.com/107702668/223741571-bd4387ad-650f-454a-b89c-19ac21131311.png)
Hi, as seen above, sodium seems to be causing an issue where certain walls or surfaces either dont render properly or just end up entirely becoming see through when approached. The wall next to me where the bug is happening is entirely made of stone and other natural blocks so i dont believe it to be any of the transparency issues people have been experiencing.

**Comment by piuvas** [comment]
could you test this using the latest version?

**Comment by MeeniMc** [comment]
Your coordinates are very high, this could be a round-off error.

**Comment by MeeniMc** [comment]
#1665 has a better description of the same problem

**Comment by jellysquid3** [comment]
This is probably resolved by #1669?

**Comment by MeeniMc** [comment]
Bug (following replication steps in #1665) is present in 0.4.10, not present in 0.4.11, so it is resolved by #1669 but that is no longer available in a release atm.

**Comment by piuvas** [comment]
so... duplicate?

**Comment by pajicadvance** [comment]
Closing this in favor of #1665 since it has more information.
