### ISSUE TITLE
Fps Lag Issue

### ISSUE THREAD

**Issue by Clouddii** [jellysquid3/Sodium#1658]
### Version information

sodium-fabric-mc1.19.3-0.4.8+build.22

### Expected Behavior

Getting Stable FPS in all dimension

### Actual Behavior

Fps is nether are not stable 
when I am in nether the fps drops down to around 10 fps ( for context my fps in overworld is around 140 fps )
The best rea
![image_2023-03-12_011642510](https://user-images.githubusercontent.com/85314105/224508597-d70b7e67-cf62-4b76-b09f-7b0cd0b0269a.png)
![image_2023-03-12_011806595](https://user-images.githubusercontent.com/85314105/224508660-81613d7d-5e05-4cc1-9524-a7a37aa1ae45.png)

### Reproduction Steps

- use some kind of anti xray on a server
- Enter Nether Dimension
- Look at the netherack 
- Your Fps should Drop

> IMP INFO : I am using a MacOS

### Java version

Java 17.0.3

### CPU

M1, 2020

### GPU

M1, 2020

### Additional information

This Issue is happening on macos only i believe

**Comment by Clouddii** [comment]
Some Things I forgot to mention that fps get stable in a few secs but its annoying
It happens every time I load a new chunk

**Comment by ghost** [comment]
can you reproduce this regression with only sodium present

**Comment by Clouddii** [comment]
> can you reproduce this regression with only sodium present

yes I can

**Comment by piuvas** [comment]
can you reproduce this without sodium?

also, what x-ray configuration is present?

**Comment by ghost** [comment]
orebfuskator will always destroy your client performance, i advise against using it ever

**Comment by IMS212** [comment]
Please confirm this does not happen without Sodium.
