### ISSUE TITLE
Black screen and crash when loading a world

### ISSUE THREAD

**Issue by Flowergloden** [jellysquid3/Sodium#1659]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18.jar

### Reproduction Steps

1. Create a new world.
2. Enter this new world
3. The game stops at Loading the terrain and starts to flash.
4. Before long the game crashes.

### Crash Report file

https://gist.github.com/Flowergloden/aae6f09f3fd8d76d77a3722a11b89532

### Additional information

The game runs on Microsoft Surface Pro X with a Microsoft SQ1 and Jetbrains java runtime 17.0.5 and Microsoft  OpenCL™ and OpenGL® Compatibility Pack for Windows 10 on ARM. I am using Windows 11 22H2 on ARM.

**Comment by pajicadvance** [comment]
ARM configurations are usually problematic for Sodium. If you have any log files starting with `hs-err-pid` in the `.minecraft` folder, you can upload them so we can take a look.

**Comment by megaredb** [comment]
I have the same problem on Windows 10 Pro 21H2 (19044.1526), no files starting with `hs-err-pid` in the `.minecraft` folder.

**Comment by jellysquid3** [comment]
We don't support OpenGL wrappers (such as the Compatibility Pack) because they are often full of bugs and other issues. In toher words, this is not a problem with Sodium, and there is nothing for us to fix -- your graphics driver is broken.
