### ISSUE TITLE
Option to disable texture animations

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#166]
**Is your feature request related to a problem? Please describe.**
No...just a handy feature that may improve performance
**Describe the solution you'd like**
an option to disable texture animations,or maybe a whole tab listing all animated textures so you can toggle them individually(I think the second option is WAY harder to implement then the first,but don't quote me on that because I am not an expert).
**Describe alternatives you've considered**
OptiFine.
**Additional context**
This feature request was from a user(from CurseForge,if I remember correctly).

**Comment by jellysquid3** [comment]
Sodium already disables animated textures that you are not looking at in order to conserve resources. Does this not cover your use case?

**Comment by ghost** [comment]
I don't necessarily need it,
but I thought it may help people with low-end machines so no animations are played.

**Comment by jellysquid3** [comment]
This enhancement is not being considered. Sodium already provides features which largely eliminate the need to disable animated textures in the first place. The only other benefit this could have is for users wishing to disable the fire overlay and such, and given that I'm not in the business of removing vanilla features, we won't be adding extra controls to disable it.

**Comment by ghost** [comment]
No problem with that
thanks.
