### ISSUE TITLE
Causing another mod to crash?

### ISSUE THREAD

**Issue by ErrorNoInternet** [jellysquid3/Sodium#1660]
### Version information

fabric-mc1.19.3-0.4.9+build.23

### Reproduction Steps

1. Install Sodium and the InventoryProfilesNext mod
2. Use the Throw All hotkey (or spam it)
3. Game crashes

### Crash Report file

https://mclo.gs/mjPSUGo

### Additional information

Crashes when using Sodium (also tested this myself): https://github.com/blackd/Inventory-Profiles/issues/292#issuecomment-1458494489

**Comment by pajicadvance** [comment]
I have tried reproducing this issue on 1.19.3 and 1.19.4 using the latest versions of Fabric API, IPN, libIPN, Fabric Language Kotlin and Sodium for both versions to no avail. There are no exceptions in the game log either. Can you re-test and confirm if the problem is still there?

**Comment by ErrorNoInternet** [comment]
Just tested on Quilt 1.19.4, seems to be fixed!
