### ISSUE TITLE
About 3D Textures

### ISSUE THREAD

**Issue by yuuyuu6250** [jellysquid3/Sodium#1661]
I am Japanese and my English is not good. This is using deepL.

I am having trouble using 3D models in Sodium.
If it is available please let me know the settings and any additional mods.
If it's not available, I'd like to add that setting.

**Comment by MeeniMc** [comment]
Sodium only improves performance. 

If you want extra feature consider this list to pick from
https://github.com/LambdAurora/optifine_alternatives

probably you want CEM and ETF for what you are requiring. Beware that CEM doesn't work with all models.

**Comment by yuuyuu6250** [comment]
Thanks for sharing that page!
