### ISSUE TITLE
extream lag while loading jungle biome

### ISSUE THREAD

**Issue by jSdCool** [jellysquid3/Sodium#1662]
### Version information

mc1.19.3-0.4.9+build.23

### Expected Behavior

no FPS issue while loading jungle chunks

### Actual Behavior

FPS drops to unplayable levels while loading chunks that contain a jungle biome

### Reproduction Steps

1. load a new world
2. travel to a jungle

### Java version

java 17

### CPU

Ryzen 7 3800X

### GPU

Intel Arc a770

### Additional information

https://youtu.be/-CT9Z-dwKxg
the jungle visited in this video has been cut back significantly 
a fresh jungle is 10X worse

**Comment by RaptaG** [comment]
Jungles have much stuff loaded and culling is required. I suggest you try MoreCulling: https://modrinth.com/mod/moreculling

**Comment by jSdCool** [comment]
more Info:
this issue seems to happen due to a combination of sodium and the vanilla tweaks 3D vines resource pack I have

**Comment by IMS212** [comment]
3D vines resource packs are known to cause extreme lag, this is likely not related to Sodium.
