### ISSUE TITLE
Sodium 0.2.0 makes every blocks become transparent

### ISSUE THREAD

**Issue by Mygameneverworks** [jellysquid3/Sodium#1663]
### Version information

sodium-fabric-mc1.16.5-0.2.0+build.4.jar

### Expected Behavior

All textures should load normally

### Actual Behavior

All blocks become transparent, everything else is normal

### Reproduction Steps

1. Install sodium 0.2.0(fabric 0.14.17)
2. Run minecraft
3. Create new world and load it
4. Bug happens

### Java version

Java 17-int

### CPU

Don't know it didn't show up

### GPU

Don't know it didn't show up

### Additional information

![20230315_090655](https://user-images.githubusercontent.com/127911393/225192048-047cda8e-ccdd-4707-abbd-6cbc75380dee.jpg)
Only sodium 0.2.0 has the issue, 0.1.0 for minecraft 1.16.5 functions properly. I've tried with and without other mods and sodium is the  
problem

**Comment by Mygameneverworks** [comment]
Accidentally pressed close oops

**Comment by pajicadvance** [comment]
Please upload your game log located at `.minecraft/logs/latest.log`.

**Comment by Mygameneverworks** [comment]
[latestlog.txt](https://github.com/CaffeineMC/sodium-fabric/files/11002796/latestlog.txt)

**Comment by pajicadvance** [comment]
Unfortunately, the only version of Sodium that works with Pojav Launcher is 0.1. Since Pojav isn't really supported, this is unlikely to change. See https://github.com/PojavLauncherTeam/PojavLauncher/issues/1948.

**Comment by Mygameneverworks** [comment]
Well that's a bit sad though I can't do anything about so goodbye, thanks for telling me.
