### ISSUE TITLE
Sodium for 1.19.4 stops game loading

### ISSUE THREAD

**Issue by cooldroider** [jellysquid3/Sodium#1664]
### Version information

mc1.19.4-0.4.10+build.24

### Reproduction Steps

1. Install Fabric & Fabric API for 1.19.4
2. Install Sodium
3. Try to open the game.
Congrats! The loading is freezing at one point

### Crash Report file

After you close minecraft, launcher shows error code "-805306369"

### Additional information

For sure I tried to use another mod with no sodium, and game loaded properly, so the problem is not in laptop's weakness or fabric itself

**Comment by sluryishot** [comment]
i have been having the same issue.

**Comment by pajicadvance** [comment]
Please reproduce the crash again and upload the game log located in `.minecraft/logs/latest.log`.

**Comment by mrjasonn** [comment]
Please add your logs.

**Comment by IMS212** [comment]
Likely a duplicate of #899, read that for more info.
