### ISSUE TITLE
[1.19.4] See-through Text Display entities are not rendered correctly

### ISSUE THREAD

**Issue by KabanFriends** [jellysquid3/Sodium#1666]
### Version information

mc1.19.4-0.4.10+build.24

### Expected Behavior

`text_display` entities with `see_through` set to true should always render the text and its background through walls.

### Actual Behavior

Depending on the angle you look at the entity:
1. Text is sometimes not visible through walls
![image](https://user-images.githubusercontent.com/45000995/226159451-30cf8077-1ed8-4ccd-a682-2362bf4eac7d.png)

2. Text background is sometimes not visible through walls
![image](https://user-images.githubusercontent.com/45000995/226159456-fc9384b6-ab2b-4157-b7ba-ee8735e42733.png)

### Reproduction Steps

1. Spawn a see-through text display entity:
```
/summon minecraft:text_display ~ ~ ~ {text:'{"text":"Hello world!"}',billboard:"center",see_through:true}
```
2. Place blocks in front of the entity, and move around
3. See how the text or the background sometimes disappears

### Java version

Java 17

### CPU

8x Intel® Core™ i7-4770 CPU (3.40GHz)

### GPU

NVIDIA GeForce GTX 1060 (6GB, PCIe, SSE2)

**Comment by Lolothepro** [comment]
It's an Iris bug

**Comment by jellysquid3** [comment]
I can't reproduce this with just Sodium either, so it seems to be a problem unrelated to our mod.
