### ISSUE TITLE
Sodium crash. :(

### ISSUE THREAD

**Issue by aRandomMenno** [jellysquid3/Sodium#1667]
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24

### Reproduction Steps

Put sodium in your mods folder and fabric api, fabric loader v14.17 and run the game and see it crash.

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11017188/latest.log)

**Comment by mrjasonn** [comment]
This version of Sodium is for Minecraft 1.19.4 and you are using 1.19.3. Please try running with 1.19.4.
