### ISSUE TITLE
sodium freeze

### ISSUE THREAD

**Issue by mctaylors** [jellysquid3/Sodium#1671]
### Version information

0.4.9+build.23

### Reproduction Steps

1. load minecraft with only sodium
2. join single/multiplayer world

### Crash Report file

crash log was not generated because the game froze
there is only a regular log (most likely it will not help in any way)
https://gist.github.com/mctaylors/1f17d4d08cae3d0c3abd006bb7ee42b2

### Additional information

computer specs:
```
CPU: Quad-Core Intel Core 2 Q8300
GPU: AMD Radeon HD 5850
```

**Comment by mctaylors** [comment]
kinda low quality video that shows reproduction steps
https://user-images.githubusercontent.com/95250141/227236712-2e9fb18b-3649-4710-804c-b3e102fe8b56.mp4

**Comment by pajicadvance** [comment]
Check if there are any log files starting with `hs-err-pid` in your `.minecraft` folder. If there are, send the latest one.

**Comment by pajicadvance** [comment]
Additionally, this seems to be the same issue as #1646. As suggested there, try using Sodium 0.4.10 in Minecraft 1.19.4 and see if the issue persists.

**Comment by mctaylors** [comment]
somehow, sodium worked with 1.19.4
