### ISSUE TITLE
Compatibility issue 

### ISSUE THREAD

**Issue by Sputnik69** [jellysquid3/Sodium#1675]
Im pretty new to fabric and sodium, i was trying to get my optifine shaders to work with sodium. After searching how i found the mod optifabric. 

but after trying to launch the game with 1.19.3 the error message that cam up was 👍 

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Sodium' (sodium) 0.4.9+build.23 with any version that is compatible with:
		 - optifabric 1.13.24
Unmet dependency listing:
	 - Mod 'Sodium' (sodium) 0.4.9+build.23 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.13.24!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

And the way i understand is that it is reading the incompatible version as a compatibble one or vice versa.

can someone debunk this for me?

**Comment by jellysquid3** [comment]
Fabric has terrible error messages. But if you read closely, it's telling you that _any version_ of OptiFabric is incompatible with Sodium. You cannot use the two together.

If you want to use OptiFine shader packs, then install a mod like Iris Shaders (which is compatible with Sodium.)
