### ISSUE TITLE
Sodium shouldn't try to cast VertexConsumer to VertexBufferWriter without checks

### ISSUE THREAD

**Issue by Igrium** [jellysquid3/Sodium#1676]
At some point within the Sodium code, Minecraft's `VertexConsumer` is cast to a `VertexBufferWriter` without any instanceof checks. Presumably, this is handled for vanilla code using a mixin, but it crashes any third-party mods that, for whatever reason, need to implement their own `VertexConsumer` (see: [Igrium's Replay Exporter](https://github.com/Sam54123/mc-world-export/issues/39)).

Due to the nature of the issue, the only way for third-party mods to fix this on their end is to hard-depend on Sodium and implement `VertexBufferWriter` themselves, which leads to a dependency hell and is simply not viable. Is there a way to code a check and make whatever optimization Sodium is trying to enact soft-fail if the cast fails?

(Relevant crash log: https://mclo.gs/YnCg400)

**Comment by jellysquid3** [comment]
Relevant issue: https://github.com/CaffeineMC/sodium-fabric/issues/1620

**Comment by jellysquid3** [comment]
Realistically, we're stuck between implementing two versions of every code path that touches a VertexConsumer (which isn't happening) or we have to abort our code paths when we encounter something weird (which hurts performance and complicates code greatly.) The latter also don't work in all cases, since many of Sodium's internals are only written against the VertexBufferWriter implementation.

**Comment by jellysquid3** [comment]
I don't want to break mods, but I seriously can't see a way to make the terrible VertexConsumer interface any better. And the performance uplift that users get with our fast-path is **_significant_**, sometimes 50-75% faster for immediate mode rendering.

The best we can do is try to expose a public API, and allow mods to implement the `VertexBufferWriter` interface without needing to hard-depend on the rest of Sodium. We've already prepared that for the next release of Sodium... it's just a matter of making sure the API is any good before we bother other mod developers with it.

**Comment by Igrium** [comment]
That would probably work! How would one actually do that in their code?

**Comment by jellysquid3** [comment]
A pull request is currently open which fixes this problem: https://github.com/CaffeineMC/sodium-fabric/pull/1842

**Comment by jellysquid3** [comment]
Fixed in merge commit https://github.com/CaffeineMC/sodium-fabric/commit/5b574194b83ea970a72a883fee7a3b938e1ac062.
