### ISSUE TITLE
Chunks being culled overly agressively

### ISSUE THREAD

**Issue by ChildishGiant** [jellysquid3/Sodium#1678]
### Version information

mc1.19.4-0.4.10+build.24

### Expected Behavior

Chunks shouldn't go missing when in view and render range

### Actual Behavior

https://user-images.githubusercontent.com/13716824/229301550-0eadd8f2-5834-4010-b5a0-7fcf64657c84.mp4

### Reproduction Steps

For us a tunnel to the center of the earth is all it took

### Java version

Java 17.0.4.1 64 bit

### CPU

12x AMD Ryzen 5 1600X Six-Core

### GPU

AMD Radeon RX 480

**Comment by pajicadvance** [comment]
Duplicate of #872.
