### ISSUE TITLE
23w13a_or_b Snapshot support

### ISSUE THREAD

**Issue by RedWideWeb** [jellysquid3/Sodium#1680]
I know that oneBlockAtATime snapshot was a huge pain to support because of completely new way of rendering blocks.

23w13a_or_b however is just some gamerules. Looking at it - most mods should work fine.

I already have:

architectury-9.0.2-fabric.jar
BetterF3-6.0.0-Fabric-1.19.4-pre3.jar
c2me-fabric-mc23w13a_or_b-0.2.0+alpha.10.51.jar
cloth-config-11.0.97-fabric.jar
fabric-api-0.76.3+23w13a_or_b.jar
fabric-language-kotlin-1.9.3+kotlin.1.8.20.jar
InventoryProfilesNext-fabric-1.19.4-1.9.5.jar
lazydfu-0.1.3.jar
libIPN-fabric-1.19.4-2.0.4.jar
modmenu-6.1.0-rc.4.jar
RoughlyEnoughItems-11.0.599.jar

working on 23w13a_or_b version.

Please update Sodium so we can play with shaders on this amazing version!

**Comment by Lolothepro** [comment]
It has already been updated and is available on the Iris Discord.

**Comment by jellysquid3** [comment]
We are not going to port our mods to "joke versions" of the game. If we did that, it's just signing ourselves up for pain in the future. Sorry.

**Comment by RedWideWeb** [comment]
@jellysquid3 lol there is a port already in Iris Discord. You should take note and be more user friendly 😒
