### ISSUE TITLE
some mobs have broken textures

### ISSUE THREAD

**Issue by RandomUserEror** [jellysquid3/Sodium#1681]
### Version information

1.19.2

### Expected Behavior

to see all mobs look like vanilla mobs

### Actual Behavior

some mobs like cows villagers skeletens etc have this kind of looking texture where some of there appaereance has either not fully loaded or have but are mashed together in one spot.
i go over to optifine and it doesnt have the same problem, im not sure if it has something to do with fabric

### Reproduction Steps

idk how to reduce this bug

### Java version

java 19

### CPU

Intel(R) Core(TM) i5-4590 

### GPU

Radeon RX 570 Series

### Additional information

architectury-6.4.62-fabric
betterfpsdist-fabric-1.19.1-2.0
continuity-2.0.2+1.19
custom-crosshair-mod-v1.5.1-fabric-mc1.19.2
extraorigins-1.19-2
fabric-api-0.69.01.19.2
indium-1.0.9+mc1.19.2
iris-mc1.19.2-1.5.0
modmenu-4.2.0-beta.2
Origins-1.19.2-1.7.1
Pehkui-3.5.01.14.4-1.19.2
shulkerboxtooltip-fabric-3.2.2+1.19.2
simplyswords-fabric-1.36-1.19.2
sodium-fabric-mc1.19.2-0.4.4+build.18
WI-Zoom-1.4-MC1.19.2
worldedit-mod-7.2.12

**Comment by pajicadvance** [comment]
Are you using any resource packs? Try reproducing the issue with Sodium only and upload your game log located at `.minecraft/config/latest.log`.

**Comment by RandomUserEror** [comment]
i have had a loock at my recource packs and induvidually turned them on and it actually was a recource pack
https://www.curseforge.com/minecraft/texture-packs/spryzeens-health-bars

**Comment by jellysquid3** [comment]
If you are using resource packs that depend on OptiFine-only features, then you need to use install mods which provide those features (for which there is not always a suitable replacement.) Sodium is not going to implement OptiFine-specific functionality.
