### ISSUE TITLE
Tweakeroo Particles

### ISSUE THREAD

**Issue by Aculoss** [jellysquid3/Sodium#1683]
### Version information

1.19.4

### Expected Behavior

Block breaking particles turn off.

### Actual Behavior

Block breaking particles still there.

### Reproduction Steps

Install Tweakeroo and Sodium. Enable disableBlockBreakingParticles to true.

### Java version

19

### CPU

Intel i3

### GPU

Intel HD Graphics

**Comment by MeeniMc** [comment]
I had that issue w/o Sodium in the past
https://github.com/maruohon/tweakeroo/issues/110

I just retested today and this option works for me with Tweakeroo 0.16.0, Malilib 0.15.3, Sodium 0.4.10, Indium 1.0.15

**Comment by pajicadvance** [comment]
Stale and seems to be resolved with later mod updates.
