### ISSUE TITLE
[1.19.4] Chunks are not rendering properly

### ISSUE THREAD

**Issue by aking4125** [jellysquid3/Sodium#1686]
### Version information

0.4.10+Build.24

### Expected Behavior

Chunks to render normally.

### Actual Behavior

![2023-04-06_15 52 44](https://user-images.githubusercontent.com/11141831/230481026-c9528977-51bc-41ed-874c-68862cf91548.png)

### Reproduction Steps

For us, it's at random locations on a server.

### Java version

Java 17

### CPU

Ryzen 7 5800X

### GPU

Nvidia Geforce GTX 1070

### Additional information

Lithium actually just completely crashes which has been reported here: https://github.com/CaffeineMC/lithium-fabric/issues/466

[2023-04-06-7.log](https://github.com/CaffeineMC/sodium-fabric/files/11174049/2023-04-06-7.log)

**Comment by jellysquid3** [comment]
Sodium 0.4.x is no longer supported, and Sodium 0.5 changed a lot of things to hopefully prevent problems like this. Please ask for the issue to be re-opened if you are still experiencing this problem with the latest version of Sodium.
