### ISSUE TITLE
Lunar & Labymod doing weird things

### ISSUE THREAD

**Issue by dolphin-cat** [jellysquid3/Sodium#1693]
Lunar and Labymod may be breaking the lgpl license of sodium by embedding it inside their own closed source jars

**Comment by AnOpenSauceDev** [comment]
Lunar Client **does comply with the license to the extent legally necessary.** The [source code can be found here](https://github.com/LunarClient/), and [here, with instructions on how to find these open-source licences](https://support.lunarclient.com/support/solutions/articles/60000752051-third-party-mods) in the launcher. [labymod does have a github](https://github.com/labymod), but **I couldn't find anything on their bundling of FOSS anywhere.**

**Comment by silversquirl** [comment]
LGPL explicitly allows linking with closed source code - that's the difference between it and GPL
