### ISSUE TITLE
Game crash when loading new chunks

### ISSUE THREAD

**Issue by KB-Q** [jellysquid3/Sodium#1695]
### Version information

mc1.19.4-0.4.10+build.24

### Reproduction Steps

The game crashes as soon as I start flying into new chunks from spawn.

### Crash Report file

Crash log: https://mclo.gs/5bpYXZc

**Comment by pajicadvance** [comment]
The log seems to be spammed by what I assume are chunk loading errors by a mod that's not Sodium shortly before the game runs out of memory. See if the same issue persists after disabling C2ME.

**Comment by jellysquid3** [comment]
There's no evidence this is a problem with Sodium. If you think otherwise, please find out if it happens with just Sodium installed, or if there's some specific combination of mods which causes it.
