### ISSUE TITLE
Can't see mobs

### ISSUE THREAD

**Issue by Tench0** [jellysquid3/Sodium#1699]
### Version information

1.19.2

### Expected Behavior

As we can normally see mobs in Minecraft, all the animals , pets and zombie skeleton creeper every mob 

### Actual Behavior

But i can't see any mob in my world not even in multiplayer world's , my friends can see in the same world but i can't see any mob not even animals..

### Reproduction Steps

I don't know why it's happening so i can't say what to try ..

### Java version

Java 17

### CPU

Intel core i3

### GPU

Intel Pentium gold

### Additional information

As per I'm having some doubt on some mods they are ..
*Sodium , sodium extra , physics mod ,mob health bar mod *

**Comment by Timolino456** [comment]
Can you reproduce this with only Sodium installed? If no, try if one of the other mods is causing it.
Also try updating your Intel drivers.

**Comment by MeeniMc** [comment]
This is usually the result of using an optifine specific resource pack without CEM/CET mods. Try again without resource packs.

**Comment by jellysquid3** [comment]
There is not enough information to diagnose the problem here, and we haven't heard back in months. Closing as invalid.
