### ISSUE TITLE
Option to disable clouds

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#170]
Sodium currently offers the options of flat and 3D clouds through Fast and Fancy options respectively, but there is no option to disable them completely. I and many others prefer to play without them, as they become annoying when building at high altitudes. This could also count as a minor performance improvement. Could an option be added to remove them, change the height they render at, or both?

**Comment by ghost** [comment]
look in the general category

**Comment by ghost** [comment]
Ah, must have missed that, maybe it should be moved to either be next to the Fast/Fancy toggle or just an option within it? Splitting similar options into separate areas only causes confusion as I've just proved 😅

**Comment by thenist** [comment]
please close the issue.
