### ISSUE TITLE
Vanilla resource packs with shaders not working

### ISSUE THREAD

**Issue by DBPT210** [jellysquid3/Sodium#1700]
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24

### Expected Behavior

On Vanilla Minecraft, applying these resource packs work as intended, like the "clear lava" resource packs.

![2023-04-18_18 13 25](https://user-images.githubusercontent.com/81093222/232854305-fc196b8b-f4bb-44eb-a385-570e251606e3.png)
- Resourse Pack list

![2023-04-18_18 13 44](https://user-images.githubusercontent.com/81093222/232854405-28414f8f-ab94-4c29-aaf8-4e87ef601f6f.png)
- Lava clear

### Actual Behavior

![image](https://user-images.githubusercontent.com/81093222/232857707-62f51ec2-a02f-40d4-be72-9f9e44aef287.png)
- Resource pack list

![image](https://user-images.githubusercontent.com/81093222/232857811-e9ee8776-db7e-4779-994d-fc26733bd580.png)
- Lava does not appear clear

### Reproduction Steps

1. Apply resource pack that use a vanilla shader.
2. Test it.

### Java version

Java 17.0.3 64bit

### CPU

Intel Core i5-9600K 3.70GHz

### GPU

NVIDIA GeForce GTX 1070

**Comment by Timolino456** [comment]
Resourcepacks that use core shaders are not supported and most likely never will be.

**Comment by DBPT210** [comment]
> Resourcepacks that use core shaders are not supported and most likely never will be.

Oh i see. Maybe its part of the optimization aspect of things?
And is there any other mods that could add it back?

**Comment by piuvas** [comment]
unfortunately, there's no workaround.

**Comment by Felix14-v2** [comment]
> And is there any other mods that could add it back?



> unfortunately, there's no workaround.

Actually, there is a mod called [Sodium Shader Support](https://github.com/DartCat25/sodium-shader-support), It allows resource packs to override the Sodium shaders. However, you will have to persuade the authors of resource packs to consider adding support for Sodium through this mod.
