### ISSUE TITLE
When Changing Render Distance Game Chrashes

### ISSUE THREAD

**Issue by bebingga** [jellysquid3/Sodium#1701]
### Version information

fabric-api-0.66.0+1.19.2.jar

### Reproduction Steps

Whenever I go to change my render distance with sodium installed and click apply my game crashes

### Crash Report file

[crash report.txt](https://github.com/CaffeineMC/sodium-fabric/files/11289761/crash.report.txt)

### Additional information

The game does not crash if I change the render distance in the main menu

**Comment by Lolothepro** [comment]
use Minecraft 1.19.4

**Comment by pajicadvance** [comment]
Seems to be a duplicate of #1486.
