### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Wowtheresreallynothingtoname** [jellysquid3/Sodium#1702]
### Version information

mc1.19.4-0.4.10+build.24

### Reproduction Steps

This is a text that went through a translator.
Please understand even if the sentence is awkward.

Lasted log, not crash report

1. Move dimensions, change chunks, change resource packs, change shaders
2. It lasts about eight times.
3. If you combine all the previous actions and get 9 times, you'll get a crash

### Crash Report file

[https://drive.google.com/file/d/1vRu7Amsp9508Xta46XsTgU7XTTCXsTwI/view?usp=share_link](url)

**Comment by pajicadvance** [comment]
Please re-upload your logs, the link you provided is not working.

**Comment by pajicadvance** [comment]
So I realized recently that the provided link actually works, it's just formatted improperly. This is most likely related to #1717, and there is now a tracking issue for this at #1742.
