### ISSUE TITLE
Lighting Problems

### ISSUE THREAD

**Issue by Roboboy5741** [jellysquid3/Sodium#1703]
![Screenshot (241)](https://user-images.githubusercontent.com/57339602/233821328-87ed642f-cd1c-43fd-b17c-4dcdb1247a20.png)

when I load into any world this is what I'm faced with.

**Comment by MeeniMc** [comment]
Does the problem persist in the world after disabling Sodium? It is definitely not a Sodium issue.

In general (not Sodium related), this can happen when you load a world where you previously had modded blocks placed, without the mod that added them. The blocks will be removed, but the shade they created will remain in the world. You can fix it using 'remove cached data' from the 'edit world' screen (or launch a server once using the same-name option on the server command line). Make backups of your worlds before altering them (it is safe but you would not like being sorry would you). 

If what I said doesn't help, you will need to provide a screenshot with the f3 screen opened, and try to replicate with Sodium as the only installed mod.

**Comment by Roboboy5741** [comment]
nope i removed each mod one by one and put them back before removing the
next mod and sodium was the one that stood out (also i dont play with
modded blocks most mods i have are quality of life mods like carpet and
tweakeroo)

**Comment by pajicadvance** [comment]
Most likely related to #1881, should be fixed in upcoming update 0.5.
