### ISSUE TITLE
the game is stuck at loading terrain 

### ISSUE THREAD

**Issue by abdosami1500** [jellysquid3/Sodium#1705]
### Version information

sodium-fabric-mc1.19.3-0.4.9+build.23

### Expected Behavior

entering the world normally 

### Actual Behavior

the game is stuck at loading terrain

### Reproduction Steps

1- use the mod sodium-fabric-mc1.19.3-0.4.9+build.23
2- open the game fabric loader 
3- enter anyworld 

### Java version

version 8 update 371

### CPU

Intel Core 2 Quad Q9550 4 threads - 2.8 GHz

### GPU

ATI FirePro V4800 (FireGL) 1 GB VRAM

### Additional information

at first i used this mod pack : https://www.curseforge.com/minecraft/modpacks/boosted-fps/files 
but even after i removed every mod and only sodium left the game stuck at loading terrain 
here is the log 
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11326364/latest.log)

**Comment by abdosami1500** [comment]
![image](https://user-images.githubusercontent.com/44530940/234393096-5ba40335-f203-42a6-b733-1c7a1ea6f71a.png)
now this

**Comment by jellysquid3** [comment]
Can you try upgrading to Minecraft 1.19.4 and Sodium 0.4.10? There was a bug that was causing this problem on other AMD hardware (notably TeraScale 2...)

**Comment by jellysquid3** [comment]
Possibly related: #1646

**Comment by jellysquid3** [comment]
Per our new [hardware support policy](https://github.com/CaffeineMC/sodium-fabric/blob/3f12f36e58d977f417d22ea6e643a9d7aeb4f0ca/README.md#-hardware-compatibility), your graphics card does not meet the required specifications. As such, this issue is being closed as "won't fix."
