### ISSUE TITLE
Improve Sodium video options UI

### ISSUE THREAD

**Issue by mrjasonn** [jellysquid3/Sodium#1706]
**Is your feature request related to a problem? Please describe.**
Kind of, QoL

**Describe the solution you'd like**
Improve Sodium video options UI

**Describe alternatives you've considered**
Not applicable

**Additional context**
None

**Comment by Felix14-v2** [comment]
Already done in 3rd-party mods:
[Xander's Sodium Options](https://modrinth.com/mod/xanders-sodium-options) 
[Reese's Sodium Options](https://modrinth.com/mod/reeses-sodium-options) 
[Better Sodium Video Settings Button](https://modrinth.com/mod/better-sodium-video-settings-button)

**Comment by jellysquid3** [comment]
"Improve it" how? You've provided no details of you what you want.

**Comment by jellysquid3** [comment]
Okay... well, I'm going to close this issue, as it's completely useless as-is.

**Comment by masterflitzer** [comment]
> Already done in 3rd-party mods: [Xander's Sodium Options](https://modrinth.com/mod/xanders-sodium-options) [Reese's Sodium Options](https://modrinth.com/mod/reeses-sodium-options) [Better Sodium Video Settings Button](https://modrinth.com/mod/better-sodium-video-settings-button)

i feel like one shouldn't need another mod to fix the ui of this mod...

**Comment by TheNukeLore** [comment]
The ui of sodium isn’t inherently broken so there is nothing to “fix”

**Comment by jellysquid3** [comment]
Once again, if you can't give us any constructive feedback on how to actually improve the menu, then what do you expect us to do? These issues where people vaguely gesture that it should be "fixed" are not helpful.
