### ISSUE TITLE
Options Game Crash

### ISSUE THREAD

**Issue by OST-Gh** [jellysquid3/Sodium#1707]
### Version information

sodium-fabric-mc1.19.3-0.4.9+build.23

### Reproduction Steps

1.: Be in any menu that gives access to the Options button
2.: Hit the Options button
3.: Game Crash

### Crash Report file

[crash-2023-04-27_10.57.46-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11341692/crash-2023-04-27_10.57.46-client.txt)

**Comment by Felix14-v2** [comment]
Not a sodium bug: [options-profiles#1](https://github.com/AxolotlMaid/options-profiles/issues/1)

**Comment by OST-Gh** [comment]
oh thanks, i thought it was something sodium related
