### ISSUE TITLE
[1.19.4] Crash on startup

### ISSUE THREAD

**Issue by asodugf12** [jellysquid3/Sodium#1709]
### Version information

sodium 0.4.10+build.24

### Reproduction Steps

1. Install Sodium
2. Start the game
3. Crash

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11361191/latest.log)

**Comment by Lolothepro** [comment]
atum bug

**Comment by ghost** [comment]
atum bug
