### ISSUE TITLE
It crashed on Android and has been patched

### ISSUE THREAD

**Issue by aaaapai** [jellysquid3/Sodium#1712]
### Version information

sodium-fabric-mc1.19.3-0.4.11+build.25

### Reproduction Steps

1. Go out into the world
2. The game crashes

### Crash Report file

[latestlog.txt](https://github.com/CaffeineMC/sodium-fabric/files/11363705/latestlog.txt)
[crash-2023-05-01_13.08.09-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11363715/crash-2023-05-01_13.08.09-client.txt)

### Additional information

Version 0.4.9 will not flash back even if it is not patched, but version 0.4.11 will.

**Comment by silversquirl** [comment]
Pojav launcher is not supported as Android doesn't fully support the required version of OpenGL. The patching tool is not officially supported by us, nor by Pojav themselves, as you can see on their [mod compatibility page](https://pojavlauncherteam.github.io/MODS-UNSUPPORTED.html). YMMV

**Comment by aaaapai** [comment]
> Pojav launcher is not supported as Android doesn't fully support the required version of OpenGL. The patching tool is not officially supported by us, nor by Pojav themselves, as you can see on their [mod compatibility page](https://pojavlauncherteam.github.io/MODS-UNSUPPORTED.html). YMMV

The patch is officially provided by pojav and is only partially supported. The idea behind using sodium on Android is to disable certain functions of sodium. Since you don't support it, I will roll back to 0.4.9, feeling that there is little point in updating.

**Comment by aaaapai** [comment]
> Pojav launcher is not supported as Android doesn't fully support the required version of OpenGL. The patching tool is not officially supported by us, nor by Pojav themselves, as you can see on their [mod compatibility page](https://pojavlauncherteam.github.io/MODS-UNSUPPORTED.html). YMMV

Weirdly, virgl (opengl4.3) and angle (opengl4.6, but converted to vulkan) are not supported

**Comment by CowSheep72** [comment]
It works for me(1.19.2 0.4.4), and it also had been tested on some version by a youtuber(forgot what this version is)(edit: you used the wrong renderer use angle)
