### ISSUE TITLE
weird rendering glitch

### ISSUE THREAD

**Issue by UrSuperIdol** [jellysquid3/Sodium#1713]
When loading minecraft on the latest release of sodium all of the text turns into box characters and the game closes/crashes when joining a game, could anyone help?

![image](https://user-images.githubusercontent.com/124738280/235454810-a2a4498a-22d6-4b23-8333-1483bf47cd84.png)

**Comment by olaf294** [comment]
It is an Iris Shaders issue, try to remove Iris Shaders, it should work (had the exact same issue)

**Comment by Timolino456** [comment]
You need to update Iris. Most mods that interact with Sodium break when Sodium updates.

**Comment by ghost** [comment]
Do you use owo lib?

**Comment by UrSuperIdol** [comment]
> It is an Iris Shaders issue, try to remove Iris Shaders, it should work (had the exact same issue)

Thanks! it worked!

**Comment by Poopooracoocoo** [comment]
So since you've removed or updated Iris and this issue is fixed, can you please close your issue?

**Comment by nfxus** [comment]
I had same issue and can verify that updating Iris Shaders does indeed fix the issue.
