### ISSUE TITLE
Incompability with Wilder Wild crash

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1714]
### Version information

mc1.19.3-0.4.11

### Reproduction Steps

1. Install Wilder Wild 2.0 and Sodium 0.4.11 on 1.19.3
2. Launch the game
3. See crash on startup

### Crash Report file

[2023-05-02-2.log](https://github.com/CaffeineMC/sodium-fabric/files/11366566/2023-05-02-2.log)

**Comment by MeeniMc** [comment]
wilderwild will need updated for Sodium 0.4.11, it appears to be latching into sodium internals.

**Comment by Poopooracoocoo** [comment]
https://github.com/FrozenBlock/WilderWild/issues/240

**Comment by jellysquid3** [comment]
This isn't an issue with Sodium. Another mod is depending on internals in Sodium, which changed in a recent update. You need to wait for an update from the author.
