### ISSUE TITLE
[meta] Add graphics driver version and operating system and version to bug report and crash report templates

### ISSUE THREAD

**Issue by Poopooracoocoo** [jellysquid3/Sodium#1715]
**Is your feature request related to a problem? Please describe.**
Some issues are graphics driver version specific or OS specific and people cannot determine the cause of the issue without further information

**Describe the solution you'd like**
The template could ask for more information

**Describe alternatives you've considered**
Asking for a screenshot of F3 - if they're able to get in-game.
Asking for a screenshot of dxdiag or a dxdiag report.
Asking for logs

**Additional context**

**Comment by jellysquid3** [comment]
The bug report template already asks users to provide a DxDiag report or screenshot of the F3 screen ([reference](https://github.com/CaffeineMC/sodium-fabric/blob/1.19.3/dev/.github/ISSUE_TEMPLATE/bug_report.yml#L78-L84)). People just refuse to do it and leave the field empty, or otherwise fill it in with their best guess at the information.

**Comment by jellysquid3** [comment]
Oh. I completely misread your report.

**Comment by Poopooracoocoo** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/51363864/235509923-70321d73-3fe0-433f-b2c8-46bc96af4a2a.png">
And this text at the bottom is quite small and should be under a heading. People hardly mention what other mods they have and it's likely because of its visibility.

**Comment by jellysquid3** [comment]
I didn't realize that the issue forms were like this. I agree that the current state is really poor and that it isn't helpful to users. We'll try to improve it, though it seems like GitHub makes editing these files very annoying, as there's no way to preview how the form looks without pushing commits.

**Comment by jellysquid3** [comment]
This has been resolved with https://github.com/CaffeineMC/sodium-fabric/commit/3f12f36e58d977f417d22ea6e643a9d7aeb4f0ca.
