### ISSUE TITLE
mc1.19.4-0.4.11 causes my instance to crash entirely when joining multiplayer worlds.

### ISSUE THREAD

**Issue by bahesh** [jellysquid3/Sodium#1719]
### Version information

mc1.19.4-0.4.11

### Reproduction Steps

i don't know if it can be reproduced , please check additional info to know more.

### Crash Report file

https://mclo.gs/mU2Ge38

### Additional information

[I am sorry if its too long]
I updated sodium to the latest version yesterday [mc1.19.4-0.4.11] after i played for a while on a server , after updating all the mods , when i tried playing on a server , i joined the server , it showed encrypting , then joining the world , then saving the world and crashed. I tried a couple of times , it still kept on crashing. So i deleted the instance and made another one. It still crashed , i tried with each mods , found out sodium was causing it. i installed the previous version of sodium [and other mod that depends on it]. I use prismlauncher . Here are all the mods i use; 
![image](https://user-images.githubusercontent.com/76744429/235576326-2eece7ea-3706-4b00-82ef-d3ba2e9c4670.png)
I hope i have explained it , if you want more info , or me to replicate again , just tell me.

**Comment by bahesh** [comment]
https://mclo.gs/QBL4XhP 
Tried it again

**Comment by 0-x-2-2** [comment]
Remove the incompatible mod "cull leaves", it needs to be updated for the latest sodium version.

```
[13:43:24] [Render thread/ERROR]: Mixin apply for mod cullleaves failed cullleaves.mixins.json:MixinRegionChunkRenderer from mod cullleaves -> me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method addDrawCall in cullleaves.mixins.json:MixinRegionChunkRenderer from mod cullleaves was not located in the target class me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer. Using refmap cullleaves-common-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method addDrawCall in cullleaves.mixins.json:MixinRegionChunkRenderer from mod cullleaves was not located in the target class me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer. Using refmap cullleaves-common-refmap.json
```

**Comment by bahesh** [comment]
Oh thank you.

**Comment by bahesh** [comment]
It worked thanks a lot
