### ISSUE TITLE
Resource leak after closing singleplayer session

### ISSUE THREAD

**Issue by decors1** [jellysquid3/Sodium#172]
### Expected Behavior
Client should not get freeze!

### Actual Behavior
Client start getting freeze continuously.

### Reproduction Steps
This happened twice while running speedrun.
Probably tons of recreate world causing trouble.

1. Create New World
2. Play game for some time
3. Save and Quit to title
repeat 1-3 a lot (not sure how many time I reset but up to 50?)
4. Client start getting freeze at some point

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: [1.8.0_261]
- CPU: [Core i5 10600k]
- GPU: [GTX 1060]

**Comment by Rongmario** [comment]
How much RAM do you have assigned to your client? Also, it'll be great for you to attach a log file or a log paste so we can see if there's anything logged that contributed to this particular issue.

**Comment by decors1** [comment]
> How much RAM do you have assigned to your client? Also, it'll be great for you to attach a log file or a log paste so we can see if there's anything logged that contributed to this particular issue.

16G-RAM and basically its about 8gig left.
I gonna get log next time if that happens again.
Also I installed JRE today so gonna check what happens now.

**Comment by decors1** [comment]
Here is the log and clip.
log: [2020-07-25-6.log](https://github.com/jellysquid3/sodium-fabric/files/4976310/2020-07-25-6.log)
freeze: [https://clips.twitch.tv/VastTriangularVanillaJebaited](url)

In the log file freeze happened at 23:47:17 or so.
Also I recreated world 21 times until I restart client.
I totally forgot to check RAM stuff. :(

Thanks.

**Comment by jellysquid3** [comment]
This should be fixed with 244c04b0. Please let me know if this issue persists after the release of Sodium 0.1.1.
