### ISSUE TITLE
Crash on world load.

### ISSUE THREAD

**Issue by pank3ik** [jellysquid3/Sodium#1720]
### Version information

sodium-fabric-mc1.19.4-0.4.11+build.26

### Reproduction Steps

1. Load a world.
2. Game crashes after loading.
3. Repeat.

### Crash Report file

[crash-2023-05-02_23.40.59-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11376607/crash-2023-05-02_23.40.59-client.txt)

**Comment by piuvas** [comment]
is it happening with only sodium?

**Comment by pank3ik** [comment]
> is it happening with only sodium?

Yep, after 0.4.11 update no go

**Comment by IMS212** [comment]
We need a full log file, not just a crash report.

**Comment by KateReller** [comment]
I have experienced the same thing. [Here are my full logs.](https://mclo.gs/fRYn5cp)

**Comment by IMS212** [comment]
That crash is caused by Physics Mod not updating to support the new Sodium release.

**Comment by pank3ik** [comment]
> We need a full log file, not just a crash report.

Uhh sorry, [here](https://mclo.gs/2udJNHJ).

**Comment by aquahuskywx** [comment]
> That crash is caused by Physics Mod not updating to support the new Sodium release.

Disabled physics myself and still crashes so maybe it's not necessarily Physics' fault

**Comment by Poopooracoocoo** [comment]
Looks like https://github.com/kerudion/chunksfadein/issues/41

**Comment by Poopooracoocoo** [comment]
> > That crash is caused by Physics Mod not updating to support the new Sodium release.
> 
> Disabled physics myself and still crashes so maybe it's not necessarily Physics' fault

You could be experiencing crashes for different reasons. Check to see if you've got mods that haven't updated to be compatible with the new version.

**Comment by jellysquid3** [comment]
This isn't an issue with Sodium. Another mod is mixing into our internals and broke in a recent update to Sodium. Wait for the author to release an update.
