### ISSUE TITLE
Crash on game startup

### ISSUE THREAD

**Issue by NothingSpecific** [jellysquid3/Sodium#1722]
### Version information

0.4.11+build.26

### Reproduction Steps

1. Start game
2. Watch it crash

### Crash Report file

https://mclo.gs/b0f5QOH

### Additional information

The crash only happens when I run the latest Sodium version with Cull Leaves enabled. Disabling Cull Leaves OR downgrading Sodium to 0.4.10+build.24 fixes the issue.

**Comment by piuvas** [comment]
for a workaround, [culllessleaves](https://modrinth.com/mod/cull-less-leaves) has been recommended on discord.

also relevant: TeamMidnightDust/CullLeaves#38

**Comment by jellysquid3** [comment]
This isn't an issue with Sodium. Another mod is depending on internals in Sodium, which changed in a recent update. You need to wait for an update from the author, or use the alternative recommended above.

**Comment by NothingSpecific** [comment]
@derspyy It's worth noting Cull Less Leaves conflicts with More Culling
