### ISSUE TITLE
Crash on game startup

### ISSUE THREAD

**Issue by NothingSpecific** [jellysquid3/Sodium#1723]
### Version information

0.4.11+build.26

### Reproduction Steps

1. Start game
2. Watch it crash

### Crash Report file

https://mclo.gs/21qM6Wq

### Additional information

The crash only happens when I run the latest Sodium version with Simply No Shading enabled. Disabling Simply No Shading OR downgrading Sodium to 0.4.10+build.24 fixes the issue. Downgrading Simply No Shading fails to prevent the crash.

**Comment by jellysquid3** [comment]
This isn't an issue with Sodium. Another mod is mixing into our internals and broke in a recent update to Sodium. Wait for the author to release an update.
