### ISSUE TITLE
(possible) Physics mod incompatablilty

### ISSUE THREAD

**Issue by AlfmanOO7** [jellysquid3/Sodium#1724]
### Version information

mc1.19.4-0.4.11+build.26

### Reproduction Steps

Various causes:
Place an item frame (most replicatable)
Killing a pigman
Other unknown causes likely related to physics mod (it is mentioned in the logs/crash reports

### Crash Report file

Logs of related crashes
[2023-05-03-1.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/11379494/2023-05-03-1.log.gz)
[2023-05-03-2.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/11379493/2023-05-03-2.log.gz)
[2023-05-03-4.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/11379496/2023-05-03-4.log.gz)
[2023-05-03-5.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/11379505/2023-05-03-5.log.gz)

Crash reports of related crashes
[crash-2023-05-03_16.30.50-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11379501/crash-2023-05-03_16.30.50-client.txt)
[crash-2023-05-03_16.35.57-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11379500/crash-2023-05-03_16.35.57-client.txt)
[crash-2023-05-03_17.13.34-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11379498/crash-2023-05-03_17.13.34-client.txt)
[crash-2023-05-03_17.11.05-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11379499/crash-2023-05-03_17.11.05-client.txt)

**Comment by Lolothepro** [comment]
update Physics mod

**Comment by SuperDLOC** [comment]
For me, Physics mod will crash the game upon loading chests. Maybe it's not sodium's fault, but more testing needs to be done.

**Comment by jellysquid3** [comment]
This isn't an issue with Sodium. Another mod is depending on internals in Sodium, which changed in a recent update. Make sure any other installed mods are up-to-date, otherwise wait for an update from the author.
