### ISSUE TITLE
text crash in Sodium 0.4.11 - 1.19.4

### ISSUE THREAD

**Issue by DimTaehyeon** [jellysquid3/Sodium#1725]
![image](https://user-images.githubusercontent.com/115601857/235854728-9288203f-eade-4f43-a83c-216124017f14.png)
![image](https://user-images.githubusercontent.com/115601857/235854925-55c80d63-784f-467b-a352-730a2d95cddc.png)

Cant see text in Sodium 0.4.11 - 1.19.4
but its not problem in Sodium 0.4.10 - 1.19.4

![image](https://user-images.githubusercontent.com/115601857/235855335-9863386c-266a-4a7b-986b-aa2b4bd6bdc3.png)
I checked other mods for problems as well, and I checked that only Sodium 0.4.11 have problems

**Comment by Lolothepro** [comment]
update Iris
