### ISSUE TITLE
Static binding violation: PRIVATE @Overwrite method method_23182

### ISSUE THREAD

**Issue by vbraziel** [jellysquid3/Sodium#1726]
### Version information

sodium-fabric-mc1.19.4-0.4.11+build.26

### Expected Behavior

No warnings on game load

### Actual Behavior

[11:11:31] [Render thread/WARN]: Static binding violation: PRIVATE @Overwrite method method_23182 in sodium.mixins.json:features.item.MixinItemRenderer from mod sodium cannot reduce visibiliy of PUBLIC target method, visibility will be upgraded.

### Reproduction Steps

Every time I load the game.

### Java version

Java 17

### CPU

Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz, 2304 Mhz, 8 Core(s), 16 Logical Processor(s)

### GPU

NVIDIA Quadro RTX 3000

### Additional information

I don't think this is a big deal, but I can fix it and submit a PR if you like.

**Comment by MeeniMc** [comment]
Confirmed. This has no effect beside a couple of lines in the log.

**Comment by MeeniMc** [comment]
Issue resolved in Sodium 0.5
