### ISSUE TITLE
Terrible FPS only when using Sodium

### ISSUE THREAD

**Issue by akzzzx** [jellysquid3/Sodium#1727]
### Version information

mc1.19.4-0.4.11

### Expected Behavior

Sodium should provide the same, or a better framerate than using vanilla.

### Actual Behavior

Using sodium, I get only 100-140fps, even in superflat worlds. When I turn off sodium, I get 800-1500fps. No shaders on. I am using a decent amount of sodium "addons", such as:

Sodium Extra
Reese's Sodium Options
Lithium
Iris
Indium

These issues arised out of the blue, nothing changed prior. Disabling all of the listed mods did not change anything, only disabling the sodium mod itself fixed it. There is a huge list of mods that I am using, some of which only working with sodium. If it is needed, i will list all of them.

I also experience low GPU utilization and MSI Afterburner's On-Screen-Display does not work when using sodium. I suspect it's an issue with either windows or sodium's renderer. I have not had these issues in any other games. 

### Reproduction Steps

Load the latest version of Sodium(as of this report) on 1.19.4? I'm not sure. I don't think it has happened to anyone else.

### Java version

Java 1.7.0.3 64bit

### CPU

AMD Ryzen 9 5900X 12-Core Processor

### GPU

NVIDIA Geforce RTX 3060

### Additional information

jesus christ i'm not listing all of that, take a screenshot, contact me if you need to know the version.

Mod list: https://share.icloud.com/photos/06cCC6MxKl-4hBPxEp9sv9tiA

Kind of an unreliable way to share these images, but this is also my first time submitting a bug report on this website

**Comment by piuvas** [comment]
your modlist url is invalid.

**Comment by akzzzx** [comment]
> 

should be fixed now

**Comment by piuvas** [comment]
could you test using the regular launcher? feather client is currently unsupported.

**Comment by IMS212** [comment]
We need a log of a true Fabric install without Feather to help, if that does not have the issue contact Feather.
