### ISSUE TITLE
Random box texts pop up with no way of proceeding into the game

### ISSUE THREAD

**Issue by FanBoyHalo** [jellysquid3/Sodium#1728]
### Version information

mc1.19.4-0.4.11

### Reproduction Steps

Use Sodium version mc1.19.4-0.4.11 and start the game

### Crash Report file

![image](https://user-images.githubusercontent.com/132530223/236092661-84dc5994-a26f-4467-9734-1281f7cfcfe8.png)

### Additional information

Please help I am trying to play Mincraft 1.19.4

**Comment by Poopooracoocoo** [comment]
Do you also have Iris? Is it up to date?

**Comment by FanBoyHalo** [comment]
> Do you also have Iris? Is it up to date?

yes imma check

**Comment by FanBoyHalo** [comment]
> 

IT WORKS THXS!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Poopooracoocoo** [comment]
Please close your issue.
