### ISSUE TITLE
Lots of Artifacting 

### ISSUE THREAD

**Issue by Swoboderz** [jellysquid3/Sodium#173]
graphical artifacts on the edges of textures
turned off formatting to see if its a precision error. still had the same artifacts.
[https://i.imgur.com/iv5iVBD.jpg](url)

**Comment by Titaniumtown** [comment]
Something is wrong w/ your link. When i click on it, it directs me to https://github.com/jellysquid3/sodium-fabric/issues/url

**Comment by Swoboderz** [comment]
weird. how bout i try again
https://i.imgur.com/iv5iVBD.jpg

**Comment by Titaniumtown** [comment]
Did you try using a different chunk renderer?

**Comment by Titaniumtown** [comment]
The link works now

**Comment by Swoboderz** [comment]
a different chunk renderer? this is purely just sodium installed. so idk what you mean there

**Comment by Titaniumtown** [comment]
It's in the video settings

**Comment by Swoboderz** [comment]
oh right. the different open gl modes. yes. yes i  have

**Comment by Swoboderz** [comment]
huge amounts of artifacting

**Comment by Titaniumtown** [comment]
What OS? Make sure you are using the proprietary drivers.

**Comment by Swoboderz** [comment]
standard windows 10. up to date nvidia drivers. nothing fancy. literally everything is default

**Comment by Swoboderz** [comment]
pressed wrong button lmao

**Comment by Titaniumtown** [comment]
huh idk then (I see you clicked the wrong button lol)

**Comment by Swoboderz** [comment]
for real. i hope someone figures it out. would love to use this mod but theres so much artifacting even only about 20 blocks away it gets brutal. is it possible that Sodium uses the SSE2 instruction set and some sort of precision goes wrong in my gpu?

**Comment by Titaniumtown** [comment]
I've never had issues, idk I use a gtx 980 ti on arch linux.

**Comment by Titaniumtown** [comment]
:shrug:

**Comment by LucilleTea** [comment]
Do you have any settings overridden in your Nvidia control panel? I think people have reported this artifacting with anisotropic filtering forced on through the driver.

**Comment by Swoboderz** [comment]
let me check...
your right! it was on for some reason. even through i didnt set that... ill check now with it set to application controlled...
sure enough! your a fucking genius somehow pulling that from me just using nvidia
