### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by SafeOfArsenal** [jellysquid3/Sodium#1730]
### Version information

4.11 1.19.4

### Expected Behavior

not have my game crash

### Actual Behavior

my game crashed

### Reproduction Steps

not fully sure it happens to me a lot when trying to get in to mcci (give it about 4 attempts at most)

### Java version

Java 8

### CPU

Intel(R) Core(TM) i5-10400  CPY @ 2.90GHz

### GPU

NVIDIA GeForce GTX 1660 Super

### Additional information

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-05-04 23:15:52
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "me.jellysquid.mods.sodium.client.render.chunk.lists.ChunkRenderList.getCount()" because "this.chunkRenderList" is null
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.getVisibleChunkCount(RenderSectionManager.java:466)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.getVisibleChunkCount(SodiumWorldRenderer.java:126)
	at net.minecraft.class_761.method_3246(class_761.java:11452)
	at io.github.bumblesoftware.fastload.api.internal.abstraction.Client1182.getCompletedChunkCount(Client1182.java:252)
	at io.github.bumblesoftware.fastload.client.FLClientHandler.lambda$registerEvents$20(FLClientHandler.java:250)
	at io.github.bumblesoftware.fastload.api.external.events.AbstractEvent$StableEventArgs.recursive(AbstractEvent.java:244)
	at io.github.bumblesoftware.fastload.api.external.events.CapableEvent.lambda$fire$2(CapableEvent.java:181)
	at io.github.bumblesoftware.fastload.api.external.events.CapableEvent.iterate(CapableEvent.java:164)
	at io.github.bumblesoftware.fastload.api.external.events.CapableEvent.fire(CapableEvent.java:181)
	at io.github.bumblesoftware.fastload.api.external.events.AbstractEvent.fire(AbstractEvent.java:171)
	at net.minecraft.class_310.handler$bfj000$fastload-1193-compat$renderEvent(class_310.java:7521)
	at net.minecraft.class_310.method_1523(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.getVisibleChunkCount(RenderSectionManager.java:466)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.getVisibleChunkCount(SodiumWorldRenderer.java:126)
	at net.minecraft.class_761.method_3246(class_761.java:11452)
	at io.github.bumblesoftware.fastload.api.internal.abstraction.Client1182.getCompletedChunkCount(Client1182.java:252)
	at io.github.bumblesoftware.fastload.client.FLClientHandler.lambda$registerEvents$20(FLClientHandler.java:250)
	at io.github.bumblesoftware.fastload.api.external.events.AbstractEvent$StableEventArgs.recursive(AbstractEvent.java:244)
	at io.github.bumblesoftware.fastload.api.external.events.CapableEvent.lambda$fire$2(CapableEvent.java:181)
	at io.github.bumblesoftware.fastload.api.external.events.CapableEvent.iterate(CapableEvent.java:164)
	at io.github.bumblesoftware.fastload.api.external.events.CapableEvent.fire(CapableEvent.java:181)
	at io.github.bumblesoftware.fastload.api.external.events.AbstractEvent.fire(AbstractEvent.java:171)

-- Affected level --
Details:
	All players: 1 total; [class_746['OminousDiscovery'/1405, l='ClientLevel', x=8.50, y=65.00, z=8.50]]
	Chunk stats: 4096, 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (8,64,8), Section: (at 8,0,8 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 0 game time, 0 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, file/Itsme64's+smaller+totem+1.5.1.zip, file/LowOnFire_1.19.zip, file/§cLunar's §6Lower Shield.zip, Fabric Mods, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3959565408 bytes (3776 MiB) / 6241124352 bytes (5952 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 37494.87
	Virtual memory used (MB): 20602.73
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 144.57
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		alternate-current: Alternate Current 1.5.0
		betterbiomeblend: Better Biome Blend 1.19-1.3.6-fabric
		boostedbrightness: BoostedBrightness 2.1.4+1.19.4
		borderlessmining: Borderless Mining 1.1.7+1.19.4
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.51
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.51
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.51
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.51
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.51
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.51
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.51
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.51
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.51
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.51
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.51
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.51
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.51
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.51
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.51
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.51
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.51
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.51
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.51
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.51
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cloth-config: Cloth Config v10 10.0.96
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.2+1.19.3
		debugify: Debugify 1.19.4+2.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		entityculling: EntityCulling-Fabric 1.6.2-mc1.19.4
		fabric-api: Fabric API 0.80.0+1.19.4
			fabric-api-base: Fabric API Base 0.4.25+504944c8f4
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.26+504944c8f4
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.8+348a9c64f4
			fabric-block-api-v1: Fabric Block API (v1) 1.0.7+e022e5d1f4
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.35+c2e6f674f4
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.16+504944c8f4
			fabric-command-api-v1: Fabric Command API (v1) 1.2.28+f71b366ff4
			fabric-command-api-v2: Fabric Command API (v2) 2.2.7+504944c8f4
			fabric-commands-v0: Fabric Commands (v0) 0.2.45+df3654b3f4
			fabric-containers-v0: Fabric Containers (v0) 0.1.55+df3654b3f4
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.10+ae0966baf4
			fabric-convention-tags-v1: Fabric Convention Tags 1.4.2+9a7c5daaf4
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.16+aeb40ebef4
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.4.1+504944c8f4
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.46+7f87f8faf4
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.14+504944c8f4
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.5.0+76ba65ebf4
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.53+df3654b3f4
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.34+a1ccd7bff4
			fabric-item-api-v1: Fabric Item API (v1) 2.1.18+504944c8f4
			fabric-item-group-api-v1: Fabric Item Group API (v1) 3.0.6+043f9acff4
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.34+504944c8f4
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.32+df3654b3f4
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.16+504944c8f4
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.28+75e98211f4
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.32+9e7660c6f4
			fabric-message-api-v1: Fabric Message API (v1) 5.1.2+504944c8f4
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.40+49abcf7ef4
			fabric-models-v0: Fabric Models (v0) 0.3.31+504944c8f4
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.2+504944c8f4
			fabric-networking-v0: Fabric Networking (v0) 0.3.42+df3654b3f4
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 7.0.4+504944c8f4
			fabric-particles-v1: Fabric Particles (v1) 1.0.24+f1e4495bf4
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.9+a1ccd7bff4
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.1+504944c8f4
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.6+504944c8f4
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.1.2+81e8c576f4
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.39+df3654b3f4
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.29+afca2f3ef4
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.22+504944c8f4
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.42+df3654b3f4
			fabric-rendering-v1: Fabric Rendering (v1) 2.1.2+504944c8f4
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.2+e6c7d4eef4
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.3+1e1fb126f4
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.46+504944c8f4
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.21+504944c8f4
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.10+504944c8f4
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.1.2+504944c8f4
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 3.0.4+504944c8f4
		fabricloader: Fabric Loader 0.14.19
		fastload: Fast Load 3.4.0
			conditional-mixin: conditional mixin 0.3.2
			fastload-119-0-1-2-compat: Fastload 1.19-0-1-2 Compatibility 3.4.0
			fastload-1193-compat: Fastload 1.19.3 Compatibility 3.4.0
			fastload-1194-compat: Fastload 1.19.4 Compat 3.4.0
			fastload_fapi_forward: Fastload Fabric-api Forwarding 1.0.2
		ferritecore: FerriteCore 5.2.0
		immediatelyfast: ImmediatelyFast 1.1.12
			net_lenni0451_reflect: Reflect 1.1.0
		indium: Indium 1.0.17+mc1.19.4
		iris: Iris 1.6.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.2
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazy-language-loader: lazy-language-loader 0.3.2
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.1
		logical_zoom: Logical Zoom 0.0.19
		marlows-crystal-optimizer: Marlow's Crystal Optimizer 1.0.0
		memoryleakfix: Memory Leak Fix 1.0.0
		minecraft: Minecraft 1.19.4
		modmenu: Mod Menu 6.2.2
		moreculling: More Culling 1.19.4-0.17.0
		mousetweaks: Mouse Tweaks 2.24
		nofade: No Fade 1.18-2.0.1
		reeses-sodium-options: Reese's Sodium Options 1.5.0+mc1.19.4-build.72
		replaymod: Replay Mod 1.19.4-2.6.12
		servercore: ServerCore 1.3.5-1.19.4
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-rc.1+1.19.3
		smoothboot: Smooth Boot 1.19.4-1.7.0
		sodium: Sodium 0.4.11+build.26
		sodium-extra: Sodium Extra 0.4.19+mc1.19.3-build.101
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sspb: Sodium Shadowy Path Blocks 3.1.0
		starlight: Starlight 1.1.1+fabric.ae22326
		vmp: Very Many Players 0.2.0+beta.7.72
		worldedit: WorldEdit 7.2.14+6360-094b734
		yet_another_config_lib: YetAnotherConfigLib 2.5.0+1.19.4
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.19-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Itsme64's+smaller+totem+1.5.1.zip, file/LowOnFire_1.19.zip (incompatible), file/§cLunar's §6Lower Shield.zip (incompatible), fabric
	Current Language: en_us
	CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['OminousDiscovery'/1405, l='ServerLevel[Singleplayer]', x=9.50, y=64.00, z=-4.50]]
	Data Packs: vanilla, fabric
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by Poopooracoocoo** [comment]
for now you can revert to Fastload 3.3.8. also see https://github.com/BumbleSoftware/Fastload/issues/91
