### ISSUE TITLE
java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/render/vertex/VertexBufferWriter

### ISSUE THREAD

**Issue by makumaku1974** [jellysquid3/Sodium#1731]
### Version information

1.19.4

### Reproduction Steps

The game will crash once you load into the world or even created one.

### Crash Report file

[crash-2023-05-05_18.17.39-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11405332/crash-2023-05-05_18.17.39-client.txt)

**Comment by Poopooracoocoo** [comment]
Upgrade to Physics Mod 2.12.4

**Comment by makumaku1974** [comment]
> 

Thanks. It is working now.
