### ISSUE TITLE
Cannot invoke "me.jellysquid.mods.sodium.client.render.chunk.lists.ChunkRenderList.getCount()" because "this.chunkRenderList" is null

### ISSUE THREAD

**Issue by Paulem79** [jellysquid3/Sodium#1734]
### Version information

sodium-fabric-mc1.19.4-0.4.11+build.26

### Reproduction Steps

The sun and the sight were blinking, and the chat was not working anymore (on server)
I didn't do something special

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11414974/latest.log)
(There were commands that I made etc., I put the principal)

**Comment by Poopooracoocoo** [comment]
for now you can revert to Fastload 3.3.8. also see https://github.com/BumbleSoftware/Fastload/issues/91

**Comment by Paulem79** [comment]
okay thanks

**Comment by StockiesLad** [comment]
Strange... I use getChunkCount for fastload. Apparently sodiums modifications cause it to be  null. I'm unsure of the specifics of why that is the case and I'll need a dev to explain why that is.

**Comment by StockiesLad** [comment]
Perhaps its bc jellysquid switches the lists from java.util to fastutil?

**Comment by Paulem79** [comment]
this may be check in the source code

**Comment by IMS212** [comment]
As said above, this does seem caused by FastLoad.
