### ISSUE TITLE
Sodium 0.4.11 - 1.19.4で文字化け

### ISSUE THREAD

**Issue by hinata0209** [jellysquid3/Sodium#1735]
### Version information

mc1.19.4-0.4.11+build.26

### Expected Behavior

文字化けしない

### Actual Behavior

文字化けが起こった

### Reproduction Steps

Maincraftを起動したら起動し終わって、文字化けが起こっていた

### Java version

java 16

### CPU

Intel core i3

### GPU

Intel UHD graphics 620

### Additional information

![image](https://user-images.githubusercontent.com/132828839/236682413-fb1cabc2-be68-4768-8ea3-9da2cfd05a63.png)

**Comment by Poopooracoocoo** [comment]
Update Iris to 1.6.2. https://irisshaders.net/

Also note that Iris 1.6.2 and Sodium 0.4.11 are currently in beta.

**Comment by jellysquid3** [comment]
Update your mods. This isn't an issue with Sodium.
