### ISSUE TITLE
There is no version except for 1.16.5

### ISSUE THREAD

**Issue by retchingvulture** [jellysquid3/Sodium#1736]
### Version information

Not related

### Expected Behavior

There would be all the downloads

### Actual Behavior

I go to the download page, and there is nothing except for 1.16.5. I know there was more because I have a 1.19.2 file in one of my mods folders, and I go to files and there is a single file for 1.16.5.

### Reproduction Steps

Go to the mod page

### Java version

Not Related

### CPU

Not Related

### GPU

Not Related

**Comment by Banzobotic** [comment]
New download page is: https://modrinth.com/mod/sodium.

**Comment by jellysquid3** [comment]
Honest question; did you not read the page for CurseForge? We'd like to make the fact that the downloads have moved to Modrinth as clear as possible.

**Comment by retchingvulture** [comment]
I swear I read the page like 3 times, I did not see it

**Comment by Poopooracoocoo** [comment]
Just outta curiosity, is there anything that could be changed to make it clearer? I don't really know how you missed it... @retchingvulture

**Comment by retchingvulture** [comment]
Put it at the very top in bold large neon text: Ther downloads have moved! They are now on modrinth!
