### ISSUE TITLE
Sodium messes up rendering/wont load world

### ISSUE THREAD

**Issue by Ghosted-Alex** [jellysquid3/Sodium#1738]
### Version information

sodium-fabric-mc1.19.4-0.4.11+build.26

### Expected Behavior

Rendering to work and world load

### Actual Behavior

Gets this for buttons "[]" and trying to load a world crashes the game

### Reproduction Steps

load the game, you should get this: 
![Untitled video - Made with Clipchamp](https://user-images.githubusercontent.com/100062083/236711137-cd5c9bb4-d48a-4503-ac6b-f8b652dac7f3.gif)

if you load a world, it crashes

### Java version

Java 8 

### CPU

Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz

### GPU

NVIDIA Geforce RTX 3060 Laptop GPU

### Additional information

Sodium has this problem when you load the game, it looks like this: 
![Untitled video - Made with Clipchamp](https://user-images.githubusercontent.com/100062083/236711209-a01e8187-3b33-4c44-b768-cd986f3e733a.gif)

Here is what it says: The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1087.method_4711()" because the return value of "net.minecraft.class_773.method_3335(net.minecraft.class_2680)" is null

**Comment by Poopooracoocoo** [comment]
Hard to say anything without any kind of logs or a mod list, but chances are that your version of Iris is outdated.

For Sodium 0.4.11, you'll need Iris 1.6.2. 

But note that both are in beta.

**Comment by Ghosted-Alex** [comment]
Ok, thanks

**Comment by IMS212** [comment]
Caused by an old Iris release, as well as a mod blocking the screen that says to download a new Sodium build.
