### ISSUE TITLE
Crash when entering world

### ISSUE THREAD

**Issue by bisquickpancakemix** [jellysquid3/Sodium#1741]
### Version information

sodium-fabric-mc1.19.4-0.4.11+build.26

### Reproduction Steps

attempt to enter world, fly around in creative

### Crash Report file

[crash-2023-05-08_11.35.45-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11422592/crash-2023-05-08_11.35.45-client.txt)

**Comment by Trickstyr** [comment]
Receiving the same error, though I don't even get so far as joining in creative. I simply can't even enter the world no matter what. I initially thought it was Indium but it happens regardless if that is included or not. Sodium is completely unusable at the moment unless I go to a previous version, which, I didn't want to do as I wanted to use the newest version of iris.

**Comment by Trickstyr** [comment]
In case it helps, instead of posting a duplicate, here is my crash log, just in case there is any extra information that can be gleamed from a second log:
https://gist.github.com/Trickstyr/544e6e13a3bae7f9daf046ae42bf558a

**Comment by bisquickpancakemix** [comment]
> Receiving the same error, though I don't even get so far as joining in creative. I simply can't even enter the world no matter what. I initially thought it was Indium but it happens regardless if that is included or not. Sodium is completely unusable at the moment unless I go to a previous version, which, I didn't want to do as I wanted to use the newest version of iris.

Yeah I tried for hours to figure it out but I couldn't get it to work so I just gave up and started playing destiny lol. Maybe I can figure out the specific configuration or issue but unlikely

**Comment by jellysquid3** [comment]
The crash reports are useless... the actual error is getting lost. If this issue still happens with the latest version of Sodium, then upload a _log file_ (not a crash report) and ask for the issue to be re-opened.
