### ISSUE TITLE
[Tracking Issue] Buffer/VAO leaks in Sodium 0.4.11

### ISSUE THREAD

**Issue by IMS212** [jellysquid3/Sodium#1742]
There have been reports of VAO leaks in Sodium 0.4.11 (possibly related to #1717). I have made a special profiler that logs possible leaks, and here are the results.

All leaks are prefixed by `Buffer <id>` or `VAO <id>`, and have a stacktrace appended.
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11424271/latest.log)

**Comment by jellysquid3** [comment]
We haven't been able to find any memory leaks in Sodium since starting this investigation work, so it seems unrelated to us.
