### ISSUE TITLE
Crashing when trying to join.

### ISSUE THREAD

**Issue by FourZees** [jellysquid3/Sodium#1743]
### Version information

1.19.4

### Reproduction Steps

Basically, I can't join any worlds without the game crashing...

I'm using Fabric, combined with Iris, so I can load Sodium. Every time I try to load a world, or even create a world, it crashes right as its done loading it just crashes and I get the usual crash screen back onto the mc loader. I've also tried loading in without Iris, if it was the cause, but still crashed.

### Crash Report file

These are the two different attempts:

Creating a new world:
[crash-2023-05-09_03.34.37-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11426705/crash-2023-05-09_03.34.37-client.txt)

Trying to load a world:
[crash-2023-05-09_03.29.02-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11426708/crash-2023-05-09_03.29.02-client.txt)

Without Iris trying to load a world:
[crash-2023-05-09_03.42.54-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11426714/crash-2023-05-09_03.42.54-client.txt)

All the mods I'm using are listed in the reports, and I'm hoping they arent interfering with it

**Comment by jellysquid3** [comment]
You need to update your mods. The problem is not with Sodium. Likely the issue is with Iceberg or Physics Mod.
