### ISSUE TITLE
i'm using sodium 0.4.9, iris 1.5.2 with fabric 0.14.19 and get these random crashes when flying

### ISSUE THREAD

**Issue by pleepish** [jellysquid3/Sodium#1744]
### Version information

sodium 0.4.9, iris 1.5.2, fabric 0.14.19

### Reproduction Steps

start flying long distances with elytra
game crashes

### Crash Report file

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-05-09 01:55:38
Description: Unexpected error

java.nio.BufferUnderflowException
	at me.jellysquid.mods.sodium.client.gl.util.MultiDrawBatch$UnsafeMultiDrawBatch.add(MultiDrawBatch.java:155)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.addDrawCall(RegionChunkRenderer.java:173)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.buildDrawBatches(RegionChunkRenderer.java:135)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:78)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:215)
	at net.minecraft.class_761.method_3251(class_761.java:13512)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:430)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:808)
	at net.minecraft.class_761.handler$bij000$iris$renderTerrainShadows(class_761.java:7509)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1085)
	at net.minecraft.class_757.method_3192(class_757.java:864)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at me.jellysquid.mods.sodium.client.gl.util.MultiDrawBatch$UnsafeMultiDrawBatch.add(MultiDrawBatch.java:155)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.addDrawCall(RegionChunkRenderer.java:173)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.buildDrawBatches(RegionChunkRenderer.java:135)
	at me.jellysquid.mods.sodium.client.render.chunk.RegionChunkRenderer.render(RegionChunkRenderer.java:78)
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.renderLayer(RenderSectionManager.java:289)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.drawChunkLayer(SodiumWorldRenderer.java:215)
	at net.minecraft.class_761.method_3251(class_761.java:13512)
	at net.minecraft.class_761.invokeRenderChunkLayer(class_761.java)
	at net.coderbot.iris.pipeline.ShadowRenderer.renderShadows(ShadowRenderer.java:430)
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.renderShadows(NewWorldRenderingPipeline.java:808)
	at net.minecraft.class_761.handler$bij000$iris$renderTerrainShadows(class_761.java:7509)
	at net.minecraft.class_761.method_22710(class_761.java:1234)
	at net.minecraft.class_757.method_3188(class_757.java:1085)

-- Affected level --
Details:
	All players: 1 total; [class_746['pleepish'/52158322, l='ClientLevel', x=-3509.78, y=160.80, z=-316.64]]
	Chunk stats: 4096, 1487 F: 548 L: 0 U: 626
	Level dimension: minecraft:overworld
	Level spawn location: World: (-9,69,14), Section: (at 7,5,14 in -1,4,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 101369161 game time, 106988023 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, resourcePack.continuity.glass_pane_culling_fix.name, resourcePack.continuity.default.name, file/VanillaTweaks_r827263.zip, file/Better+Leaves+Add-on+V2.9.1-1.19.zip, file/text shadows.zip, armorchroma/alternative-icons, file/Rainbow Break - 1.19.x Static.zip, minecraft/supporteatinganimation, file/Spring_Flowers_(1.19.3).zip, file/New_Style_Squid_(1.19.3).zip, file/More_Nether_Roots_(1.19.3).zip, file/More_Nether_Fungi_(1.19.3).zip, file/More_Hanging_Roots_(1.19.3).zip, file/More_Fungi_(1.19.3).zip, file/Cracked_Nether_Bricks_(1.19.3).zip, file/Animated_Furnaces_(1.19.3).zip, file/Fixed_Barrel_(1.19.3).zip, file/Ore Variants v2.7.zip

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 408652872 bytes (389 MiB) / 1375731712 bytes (1312 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: Rocket Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2206
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3179
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 37460.48
	Virtual memory used (MB): 20912.71
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.4.2+mc1.19.3
		architectury: Architectury 7.1.81
		armorchroma: Armor Chroma 1.2.4
		autoclicker-fabric: Auto Clicker 1.19.3-1.5.1-build.23
		bettermounthud: Better Mount HUD 1.2.1
		blanket-client-tweaks: Blanket Client-tweaks 1.1.3
		bobby: Bobby 4.0.3
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		bookshelf: Bookshelf 17.1.6
		borderlessmining: Borderless Mining 1.1.6+1.19.3
		chat_heads: Chat Heads 0.10.9
		clickthrough: ClickThrough 1.19.3-fabric0.68.1-0.4
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
			gbfabrictools: GBfabrictools 1.3.4+1.19.3
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+16
		continuity: Continuity 3.0.0-beta.2+1.19.3
		cullleaves: Cull Leaves 3.0.3
			midnightlib: MidnightLib 1.1.0
		debugify: Debugify 1.19.3+1.1
		durabilityviewer: Giselbaers Durability Viewer 1.19.3-fabric0.68.1-1.10.3
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		eatinganimationid: Eating Animation 1.9.2
		enchdesc: EnchantmentDescriptions 14.0.7
		enhancedblockentities: Enhanced Block Entities 0.8+1.19.3
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 4.1.0+1.19.3
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.3
		fabric-api: Fabric API 0.76.1+1.19.3
			fabric-api-base: Fabric API Base 0.4.21+70be179c85
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.20+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.1.2+f1c68e5885
			fabric-block-api-v1: Fabric Block API (v1) 1.0.5+e022e5d185
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.31+928d44d585
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.12+1134c5b885
			fabric-command-api-v1: Fabric Command API (v1) 1.2.23+f71b366f85
			fabric-command-api-v2: Fabric Command API (v2) 2.2.2+2961b4a085
			fabric-commands-v0: Fabric Commands (v0) 0.2.40+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.47+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.3+1d37d50285
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+521b5c5285
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.14+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.3.3+40dc7a9485
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.42+00a2eb1085
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.7+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.40+3baeb27a85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.45+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.30+99f9db8085
			fabric-item-api-v1: Fabric Item API (v1) 2.1.11+71b8257385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.14+b5470ac785
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.31+bc01e09785
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.29+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.10+23a79c8a85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.22+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.26+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.1.0+c85585f885
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.33+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.27+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.17+4017a8cb85
			fabric-networking-v0: Fabric Networking (v0) 0.3.34+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.4.3+eb2a3ba985
			fabric-particles-v1: Fabric Particles (v1) 1.0.20+f1e4495b85
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+5176f73d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.1.0+f7b4d36485
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.2.2+3a95925a85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+3a95925a85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.31+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.25+afca2f3e85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.18+f1e4495b85
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.34+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.13.0+ad17775585
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.0+e63306e085
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.1+b93ffe4d85
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.41+f1e4495b85
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.13+99f9db8085
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.8+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.15+ccd377ba85
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.3.1+40dc7a9485
		fabricloader: Fabric Loader 0.14.19
		ferritecore: FerriteCore 5.1.0
		indium: Indium 1.0.14+mc1.19.3
		iris: Iris 1.5.2
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre9
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.1
			com_velocitypowered_velocity-native: velocity-native 3.1.2-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		litematica: Litematica 0.13.2
		lithium: Lithium 0.11.1
		logical_zoom: Logical Zoom 0.0.18
		malilib: MaLiLib 0.14.0
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		minecraft: Minecraft 1.19.3
		modmenu: Mod Menu 5.1.0-beta.4
		moreculling: More Culling 1.19.3-0.17.0
			conditional-mixin: conditional mixin 0.3.2
		morecullingextra: More Culling Extra 1.1
		mousetweaks: Mouse Tweaks 2.24
		notenoughanimations: NotEnoughAnimations 1.6.3
		raised: Raised 1.2.2
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		roughlyenoughitems: Roughly Enough Items 10.0.596
			error_notifier: Error Notifier 1.0.9
		skinlayers: 3d Skin Layers 1.5.3-mc1.19.3
		sodium: Sodium 0.4.9+build.23
		sodium-extra: Sodium Extra 0.4.18+mc1.19.3-build.99
			caffeineconfig: CaffeineConfig 1.1.0+1.17
		starlight: Starlight 1.1.1+fabric.ae22326
		tooltipfix: ToolTip Fix 1.1.1-1.19.3
		worldedit: WorldEdit 7.2.13+46576cc
		xaerominimap: Xaero's Minimap 23.4.1
		yet-another-config-lib: YetAnotherConfigLib 2.2.0
	Loaded Shaderpack: ComplementaryReimagined_r2.1.zip
		Profile: Custom (+39 options changed by user)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.19-1.19.3
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3080/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.79, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, continuity:glass_pane_culling_fix, continuity:default, file/VanillaTweaks_r827263.zip (incompatible), file/Better+Leaves+Add-on+V2.9.1-1.19.zip, file/text shadows.zip (incompatible), armorchroma:alternative-icons (incompatible), file/Rainbow Break - 1.19.x Static.zip (incompatible), minecraft:supporteatinganimation, file/Spring_Flowers_(1.19.3).zip, file/New_Style_Squid_(1.19.3).zip, file/More_Nether_Roots_(1.19.3).zip, file/More_Nether_Fungi_(1.19.3).zip, file/More_Hanging_Roots_(1.19.3).zip, file/More_Fungi_(1.19.3).zip, file/Cracked_Nether_Bricks_(1.19.3).zip, file/Animated_Furnaces_(1.19.3).zip, file/Fixed_Barrel_(1.19.3).zip, file/Ore Variants v2.7.zip
	Current Language: English (US)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz

### Additional information

i don't understand what's happening and would appreciate any input.

**Comment by ghost** [comment]
this might be an issue with your current shader pack, see if it happens without shaders

**Comment by pleepish** [comment]
it doesn't happen with shaders disabled. but i am using the most recent/updated version of complementary reimagined, so i still don't see why this would be an issue.

**Comment by ghost** [comment]
not a sodium issue

**Comment by pleepish** [comment]
so then would you say it's an iris issue?

**Comment by douira** [comment]
If it only happens with shaders enabled then it's an issue iris has to deal with.

**Comment by pleepish** [comment]
> If it only happens with shaders enabled then it's an issue iris has to deal with.

okay thank you!
