### ISSUE TITLE
Latest version missing on modrinth

### ISSUE THREAD

**Issue by EthanZeigler** [jellysquid3/Sodium#1746]
### Version information

N/A

### Expected Behavior

Sodium 0.4.11 is published to modrinth

### Actual Behavior

0.4.10 is the latest version on modrinth

### Reproduction Steps

N/A

### Java version

N/A

### CPU

N/A

### GPU

N/A

### Additional information

https://modrinth.com/mod/sodium/versions

**Comment by Timolino456** [comment]
It was removed because it had problems, this is intended.

**Comment by EthanZeigler** [comment]
Sounds good, thanks. Got confused because the latest sodium extra has a dependency on the yanked version
