### ISSUE TITLE
0.4.10 | Crash when creating/opening world

### ISSUE THREAD

**Issue by Vipti** [jellysquid3/Sodium#1748]
### Version information

mc1.19.4-0.4.10+build.24.jar

### Reproduction Steps

1. Open Minecraft
2. Create New World
3. Minecraft Crashes

### Crash Report file

[crash-2023-05-10_02.35.43-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11438789/crash-2023-05-10_02.35.43-client.txt)

### Additional information

This pops up afterwards
Error: java.lang.NoClassDefFoundError: net/caffeinemc/mods/sodium/api/vertex/buffer/VertexBufferWriter

**Comment by Poopooracoocoo** [comment]
Downgrade Physics mod to 2.12.3 for compatibility with Sodium 0.4.10

**Comment by Vipti** [comment]
> Downgrade Physics mod to 2.12.3 for compatibility with Sodium 0.4.10

I'm currently using 2.12.3 but did you mean another version?

**Comment by Vipti** [comment]
> > Downgrade Physics mod to 2.12.3 for compatibility with Sodium 0.4.10
> 
> I'm currently using 2.12.3 but did you mean another version?

Ok I fixed the issue by going down to 2.12.2. Thank you

**Comment by Poopooracoocoo** [comment]
> > Downgrade Physics mod to 2.12.3 for compatibility with Sodium 0.4.10
> 
> I'm currently using 2.12.3 but did you mean another version?

It says you're using Physics Mod 2.12.4 in your crash report.
