### ISSUE TITLE
All font replaced by squares when using Sodium with Iris

### ISSUE THREAD

**Issue by TheEssketitMan** [jellysquid3/Sodium#1749]
### Version information

sodium-fabric-mc1.19.4-0.4.11+build.26

### Expected Behavior

The game should and the text should use the Minecraft font, as regular.

### Actual Behavior

After the startup window with the Mojang logo fades, al UI elements are as they should be, except all text is replaced by squares.

### Reproduction Steps

1. Install Sodium
2. Install Iris
3. Start up the game

4. There's squares in minecraft now (no way)

### Java version

Java 17

### CPU

Intel Core i7 6700

### GPU

NVIDIA GeForce GTX 1050

### Additional information
EDIT: Forgot to mention, Fabric version is 0.14.19

Other mods are: Fabric API (fabric-api-0.80.0+1.19.4)
Fixes I tried: Downloading the default Minecraft texture pack to try forcibly replacing the squares with the font, but it didn't work.

Screenshot of how it looks:
![image](https://github.com/CaffeineMC/sodium-fabric/assets/58911051/22ed06dd-5ccb-4e5f-8507-f9cd2b80997a)

**Comment by piuvas** [comment]
duplicate of #1732.

**Comment by TheEssketitMan** [comment]
> duplicate of #1732.

God dammit, I thought I searched well enough.
Well, my bad
