### ISSUE TITLE
Water not rendered properly with Intel integrated gfx

### ISSUE THREAD

**Issue by DrBlindriver** [jellysquid3/Sodium#175]
### Expected Behavior
Water should be rendered.

### Actual Behavior
Water isn't rendered.

### Reproduction Steps

1. Create a new world and find a river/warm ocean biome.

### Attachments

![2020-07-25_17 14 38](https://user-images.githubusercontent.com/19852923/88453713-08700300-ce9c-11ea-8fa2-d01cf05d723c.png)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: Java 1.8.0_251
- CPU: Intel(R) Xeon(R) CPU E3-1225 V2 @ 3.20GHz
- GPU: Intel(R) HD Graphics P4000

**Comment by ghost** [comment]
I have the same issue when I use fabulous graphics in combination with OpenGL 3.3 or 4.3.
This is since commit #620f5a3
Using fancy graphics does the trick for me.

**Comment by tipical** [comment]
Try changing the open gl version in the advanced tab, it worked for me..

**Comment by jellysquid3** [comment]
Now tracked by #181.
