### ISSUE TITLE
game crashes when i click video settings

### ISSUE THREAD

**Issue by bananaOHHHOOOOHAHAHAHAAAAHA** [jellysquid3/Sodium#1751]
### Version information

1.19.2 sodium: 0.4.4

### Reproduction Steps

1. open mc
2. go into options
3. click video settings

BOOM! crash.

### Crash Report file

https://bytebin.lucko.me/4O8usf7TI2

### Additional information

it isnt not enough crashes because i tried without it as well and it didnt work.

**Comment by Poopooracoocoo** [comment]
Do you see this without farsight? What about without C2me?

**Comment by bananaOHHHOOOOHAHAHAHAAAAHA** [comment]
ill try without but that is needed. also it worked in a different modpack with those mods. but ill try

**Comment by bananaOHHHOOOOHAHAHAHAAAAHA** [comment]
IT WORKS! although this modpack is for a server and i will lag a lot without c2me. if you have any alternatives, please inform me

**Comment by ghost** [comment]
you can disable c2me changing the view distance slider in its config

**Comment by Poopooracoocoo** [comment]
I don't know exactly what you did that stopped your crash. 

C2ME and Farsight have the same functionality of allowing render distances higher than 32. You can try disabling clientSideConfig.modifyMaxVDConfig.enabled in C2ME's config and see if it works with Farsight.

**Comment by bananaOHHHOOOOHAHAHAHAAAAHA** [comment]
it worked, but im assuming if i remove farsight itll work better. it might be better because itll just be compacted into one mod. anyways, thank you so much guys! have a good night!
