### ISSUE TITLE
mobs "glow" underwater

### ISSUE THREAD

**Issue by konnifr** [jellysquid3/Sodium#1752]
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24

### Expected Behavior

To not be able to see mobs through water fog and blocks.

### Actual Behavior

Mobs appear to glow underwater, I can see them through blocks and clearly through the underwater fog. 
[https://media.essential.gg/2b208435-a4d5-4694-a0d3-708019ac3e00](url)

### Reproduction Steps

Not 100% sure if it's caused by Sodium, but it only occurs when I have it in my mods folder. 

### Java version

17.0.3 64bit

### CPU

12x Intel(R) Core(TM) i5-1040F

### GPU

NVIDIA GeForce GTX 1660 ti

### Additional information

![image](https://github.com/CaffeineMC/sodium-fabric/assets/116983078/5d020a02-3ce3-4803-921b-966c33052341)

**Comment by konnifr** [comment]
![image](https://github.com/CaffeineMC/sodium-fabric/assets/116983078/6914e8f6-509c-47ee-9307-a36c80fed43f)
rest of mods folder

**Comment by konnifr** [comment]
messed something up with the link heres a screenshot
![image](https://github.com/CaffeineMC/sodium-fabric/assets/116983078/9b505bec-7f56-4b4c-b86c-558cee691b13)

**Comment by Phoenix-Starlight** [comment]
I'm pretty sure the fog is supposed to make entities look like that. You can see the shape but not the details.

**Comment by konnifr** [comment]
i can see them from extremely far while not being able to see anything else, and i can see all entities through blocks when i am in water, its kind of a bad screenshot but the sheep in the background is what im talking abt not the fish, ill add a better screenshot when i get home

**Comment by NasheedPog** [comment]
This happens for me as well, and even more irritating is in the nether. Can see all mobs perfectly fine through all fog

**Comment by Phoenix-Starlight** [comment]
Can you circle the offending mob in that screenshot of yours?

**Comment by pajicadvance** [comment]
Stale and most likely caused by another mod.
