### ISSUE TITLE
The game crashes when rendering gravity blocks such as sand.

### ISSUE THREAD

**Issue by XiaoLLiu617** [jellysquid3/Sodium#1753]
### Version information

mc 1.19.4  Quilt Mod Loader

### Reproduction Steps

1.Place a gravity-affected block (e.g. anvil sand, etc.).
2.Game Stutter crashes out of the game.

### Crash Report file

As a reminder, you can ignore Chinese characters within the [ ].Because the launcher gives a lot of crash log files, I'm not a real developer, please check it out, thank you.
[worldeditcui.debug.log](https://github.com/CaffeineMC/sodium-fabric/files/11460875/worldeditcui.debug.log)
[Output before the game crashes.txt](https://github.com/CaffeineMC/sodium-fabric/files/11460877/Output.before.the.game.crashes.txt)
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11460879/latest.log)
[crash-2023-05-12_15.55.36-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11460880/crash-2023-05-12_15.55.36-client.txt)

### Additional information

Hello dear Sodium developers.Let me state in advance that this English is translated using translation software, forgive me if there are any mistakes.Thank you very much and please fix the error as soon as possible.
Sodium version：sodium-fabric-mc1.19.4-0.4.10+build.24

**Comment by Octol1ttle** [comment]
Install Indium: https://modrinth.com/mod/indium/version/1.0.15+mc1.19.4

**Comment by XiaoLLiu617** [comment]
Thank you very much

> Install Indium: https://modrinth.com/mod/indium/version/1.0.15+mc1.19.4
