### ISSUE TITLE
Block breaking animations aren't showing up

### ISSUE THREAD

**Issue by IlaDiaz** [jellysquid3/Sodium#176]
### Expected Behavior
When you are standing on a block and looking exactly at that block while breaking it, the animation doesn't show up. When it should be showing up.
_Example: The Piston should extend._

### Actual Behavior
When i break a block,while standing on it and looking excatly at it the animation doesn't show up.
_Example: The Piston does not extend._

### Reproduction Steps
Provide information on how to reproduce this game crash. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear! If applicable, please provide a world file as a compressed ZIP which contains a minimally reproducible example of the issue. 

1. Place a Redstone Lamp beside a Redstone Repeater
2. Use a Lever to activate the Redstone Repeater
3. Nothing happens

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: [fill me in]
- CPU: [fill me in]
- GPU: [fill me in]

**Comment by IlaDiaz** [comment]
Sorry my English is bad. That's why I just explained it shortly.
EDIT: Also never reported a bug before.

**Comment by ghost** [comment]
this is fixed in https://github.com/jellysquid3/sodium-fabric/commit/a7f058be2f2fe66510ccbcd67fd3a03f49ac7d3a

**Comment by jellysquid3** [comment]
Merging into #182.
