### ISSUE TITLE
Cannot invoke "me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegion.getStorage(me.jellysquid.mods.sodium.client.render.chunk.terrain.TerrainRenderPass)" because "region" is null

### ISSUE THREAD

**Issue by fireurza** [jellysquid3/Sodium#1761]
### Version information

mc1.19.4-0.4.11+build.26

### Reproduction Steps

I was sitting 200 blocks above to ocean at a creeper farm.

### Crash Report file

[crash-2023-05-13_17.25.42-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11470772/crash-2023-05-13_17.25.42-client.txt)

**Comment by MeeniMc** [comment]
0.4.11 has been pulled-off

**Comment by jellysquid3** [comment]
As MeeniMc says, we yanked this version. Please downgrade to Sodium 0.4.10 if you are still experiencing it, and wait for Sodium 0.5 to be released.
