### ISSUE TITLE
Hurt Cam Remover 1.19.2

### ISSUE THREAD

**Issue by Soggyshorts** [jellysquid3/Sodium#1764]
**The Problem/issue:**
We really dislike the hurt animation from taking damage. The screen shake/tilt is annoying.

**The solution we'd like:**
A toggle option to remove the twitchy screen shake would be amazing.

**Other solutions I've tried**
I've searched as deep as page 8 on google and found a reference to sodium here: https://gaming.stackexchange.com/questions/386728/how-to-turn-off-damage-camera-shake-in-minecraft
Otherwise, just an old mod for 1,12 forge. 

Thank you for your time

**Comment by Felix14-v2** [comment]
As Octol1ttle said, Sodium is not quality-of-life mod, just a rendering engine.
Alternatively you can install [BetterHurtCam](https://modrinth.com/mod/betterhurtcam)

**Comment by lowercasebtw** [comment]
1.19.4 has a slider already built in called Damage Tilt in accessibility settings, set it to 0% for no tilt

**Comment by Soggyshorts** [comment]
> As Octol1ttle said, Sodium is not qoality-of-life mod, just a rendering engine. Alternatively you can install [BetterHurtCam](https://modrinth.com/mod/betterhurtcam)

Thank you so much, betterhurtcam works perfectly!
