### ISSUE TITLE
End gateway culling

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#1766]
Pretty similar to #280 - end gateways are basically a full opaque cube, so it'd be expected that they'd cull against each other, but that does not happen.
![2023-05-16_23 36 36](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/a5098481-fc1f-4873-b52f-adf20f4814f9)

They don't cull solid blocks next to themselves either, though I'm not sure if that's desirable or not:
![2023-05-16_23 37 01](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/adbcfc72-cb1b-48fb-bde4-3f65dc45b6e7)

Leaves don't either, and I'm not sure if that's intended:
![2023-05-16_23 41 00](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/17f0f08b-6227-431b-810c-cd6976e16bd0)

**Comment by jellysquid3** [comment]
End Gateways are weird and I don't think there's any point in trying to optimize a block that only appears very rarely.
