### ISSUE TITLE
Unrendered hole

### ISSUE THREAD

**Issue by 1QMIK** [jellysquid3/Sodium#1768]
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24

### Expected Behavior

Nothing

### Actual Behavior

Visual bug, unrendered hole

### Reproduction Steps

That's happening when I walk around the world and some holes are appearing unrendered, also they appear and disappear when I walk from different angles

### Java version

Java 17.0.3

### CPU

Intel(R) Core(TM) i7-9700F

### GPU

NVIDIA GeForce RTX 2060

### Additional information

![Screenshot_27](https://github.com/CaffeineMC/sodium-fabric/assets/108446271/b1a42937-0d34-4398-a0fc-2ae6316ec832)

![2023-05-18_20 01 27](https://github.com/CaffeineMC/sodium-fabric/assets/108446271/7025f6bb-f56a-4b6c-b705-ea0e0452fcc7)

![2023-05-17_17 05 29](https://github.com/CaffeineMC/sodium-fabric/assets/108446271/9e0c3efb-c738-4a8c-a00e-11fc3a409e41)

**Comment by MeeniMc** [comment]
Looks like #872 

I don't think there is a workaround at the moment.

**Comment by 1QMIK** [comment]
I forgot to leave screenshots of bug

**Comment by pajicadvance** [comment]
Yep, this is #872.
