### ISSUE TITLE
Current shaderpacks support

### ISSUE THREAD

**Issue by DedMaxim** [jellysquid3/Sodium#177]
**Is your feature request related to a problem? Please describe.**
Too much fps, that I can't take advantage of, so...

**Describe the solution you'd like**
...if it's possible, implement support for current shaderpacks that are made for Optifine

**Describe alternatives you've considered**
Alternatively, create support for Sodium's own shaderpacks

**Comment by ghost** [comment]
**Please read the "Common questions" section in the curseforge page,**
-it says:**"Does Sodium support Optifine shader packs? No. However, experimentation is being done and it is possible in the 
 future that Sodium could provide its own shader pack system."**
-As you can see sodium's own shader system **is possible**.

**Comment by DedMaxim** [comment]
oh, ok, did't see that... Sorry and thank you for answer

**Comment by Valleriite** [comment]
No problem,
I don't officially speak for sodium so if you want acurate info consider joining the discord server mentioned above

**Comment by ghost** [comment]
@DedMaxim 
answer edited
