### ISSUE TITLE
option sliders catch mouse clicks to the right of them

### ISSUE THREAD

**Issue by fayer3** [jellysquid3/Sodium#1770]
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24.jar

### Expected Behavior

mouse clicks beside the slider don't activate it or block clicks to other stuff (as for example the apply button)

### Actual Behavior

mouse clicks activate the slider, which make it almost impossible to apply stuff in the equality settings at auto GUI scale

### Reproduction Steps

go to the video settings
click on the empty space beside a slider
see that it gets activated

### Java version

17

### CPU

AMD Ryzen 3700X

### GPU

Nvidia RTX 4080

### Additional information

https://github.com/CaffeineMC/sodium-fabric/assets/8282299/95350e7d-055b-4fab-9d20-e93fb0355bbd

**Comment by Timolino456** [comment]
This is not the case on Sodium 0.4.9 (1.19.3), but is starting with Sodium 0.4.10 (1.19.4).

**Comment by jellysquid3** [comment]
Fixed with #1839 and https://github.com/CaffeineMC/sodium-fabric/compare/651276fdae31...89c6ffc0b493.
