### ISSUE TITLE
crashes when entering the world

### ISSUE THREAD

**Issue by Mohamed-SK** [jellysquid3/Sodium#1779]
### Version information

mc1.16.5-0.2.0

### Reproduction Steps

1- load or create world
2- enter the world
3- the game crashes

### crash report

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11580282/latest.log)

### Additional information

none

**Comment by Felix14-v2** [comment]
Please, try with the latest Sodium versions.
You can try updating graphics driver.

**Comment by jellysquid3** [comment]
Such old versions of Sodium are not supported. We are not going to fix issues with them, though I don't think this problem has anything to do with Sodium anyways...
