### ISSUE TITLE
VertexBufferWriter and VertexBufferDescription classes aren't found

### ISSUE THREAD

**Issue by vanillyn** [jellysquid3/Sodium#1783]
### Version information

mc1.19.4-0.4.11+build.26

### Reproduction Steps

Mod list: https://paste.rs/bTQdA.txt
Crash: https://paste.rs/w15xk.txt
OS: Arch Linux/6.3.3-arch1.1 x86_64
JRE: java-17-openjdk

### Crash Report file

https://mclo.gs/wxXisbJ

### Additional information

It's probably an incompatibility with Meteor client, however they haven't said anything on their side.

**Comment by Timolino456** [comment]
PvP clients are not supported, see #1758. You need to complain to [them ](https://github.com/MeteorDevelopment/meteor-client/issues)about these problems.

**Comment by pajicadvance** [comment]
As mentioned above, we don't support PvP clients, but to save you some time, I assume that you need to use Sodium 0.4.10 to fix this.

**Comment by vanillyn** [comment]
Thank you! I'll try to join their Discord, however they're saying it's supported. 
I'll try downgrading.
