### ISSUE TITLE
Crash on healthbar overflow

### ISSUE THREAD

**Issue by 0xSnowflakeXD** [jellysquid3/Sodium#1787]
### Version information

sodium-extra-0.4.18+mc1.19.4-build.100

### Reproduction Steps

1. Have both Health Boost 255 and Absorption 255
2. Crash game

### Crash Report file

https://bytebin.lucko.me/BqL3bz1KqC

**Comment by FractalGeodes** [comment]
This does not appear to be a sodium specific issue, your game is running out of usable memory. Maybe try increasing the amount of RAM you allocate (or decreasing the amount of health boost, I doubt that numbers that high would work correctly at all)

**Comment by pajicadvance** [comment]
Not Enough Crashes is mangling the crash log, we can't tell what the problem is unless you disable the mod and reproduce the crash again. Also, you're using some mods which require Indium, but you do not have it installed.

**Comment by pajicadvance** [comment]
In any case, cracked launchers are not supported.
