### ISSUE TITLE
certain smaller entity models render incorrectly

### ISSUE THREAD

**Issue by cometecti** [jellysquid3/Sodium#1788]
issue with sodium, every time i have it installed, some mob models get completely broken. but every time i UNINSTALL it, it gets fixed. i can't find any other solution to this issue. please help? fabric 1.19.4. graphics card nvidia geforce rtx 3060, drivers all up to date

no resource packs installed

all mods installed with:
![image](https://github.com/CaffeineMC/sodium-fabric/assets/94259576/ea4e3351-d9be-48fd-8c3e-1fb48b3e4a27)

screenshot examples:
![image](https://github.com/CaffeineMC/sodium-fabric/assets/94259576/3e94ed54-7cb2-46a0-bca7-b45eed7e5de9)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/94259576/49759c6f-2d30-4cac-b74a-b82b193ed8ea)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/94259576/4c850ded-2706-4d0a-8c0b-8efa46535f2a)

**Comment by FractalGeodes** [comment]
Can you try again with just sodium and see if the error still occurs?

**Comment by cometecti** [comment]
> 

trying that right now!

**Comment by cometecti** [comment]
> Can you try again with just sodium and see if the error still occurs?

tried it with just sodium, and it's all fixed it's weird!

**Comment by FractalGeodes** [comment]
If you want to still use your mods you could try and narrow down the mod that causes it by disabling half and keeping sodium and seeing if it still occurs, if not then do the other half, rinse repeat until you find the culprit
