### ISSUE TITLE
Multi-draw rendering is broken when using Intel HD Graphics 3xxx/4xxx

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#179]
It looks like these GPUs are unsupported by Intel on Windows nowadays and that their old drivers have problems when using `glMultiDrawArraysIndirect`. This leads to strange artifacts where the world seems to bunch up around the player, which is distinct from how the AMD driver fails here.

### Workaround
If you've been directed to this issue and need to work around it, open your Video Settings, click the Advanced tab, and change the Chunk Renderer to "Oneshot (GL 2.0)".

**Comment by jellysquid3** [comment]
I doubt there is anything we can do to fix this. The Mesa drivers do not appear to have this problem on Linux-based distributions, suggesting this is just some fault in the legacy Windows drivers. We will need to blacklist these GPUs in Sodium.

It is my personal opinion that people using hardware from this era should upgrade to a modern Linux distribution (such as a lightweight flavor of Ubuntu) due to the fact that the drivers are much better supported and performant there.

**Comment by Fixer-007** [comment]
I have Intel HD2500 on my desktop i5-3450 and I have this problem as well, at first it works but after entering some areas (? near/in water/flowers/grass?) textures suddenly appear near me blocking the view.

**Setting Chunk Renderer to Oneshot (GL 3.0) solves the issue it seems (but my testing was very short)**

This table may help https://feedback.wildfiregames.com/report/opengl/device/Intel(R)%20HD%20Graphics%202500

Thank you for this mod.

PS: i did test with your Demo world with 32 chunks render distance, and I got 40 fps vs 25 fps on Intel HD 2500 (GL 3) :+1:

**Comment by Yadokingu** [comment]
I tested a bit with an Intel HD Graphics 3000 and can't see any problems. 
Chunk Render is Multidraw (GL 4.3) in the settings, but seems to automatically revert to Oneshot (GL 3.0). My driver version is 9.17.10.4459 on Windows 10.
![2020-07-30_19 38 02](https://user-images.githubusercontent.com/11133215/88955686-89fcd200-d29c-11ea-86b0-6b415560d163.png)
![2020-07-30_19 38 17](https://user-images.githubusercontent.com/11133215/88955692-8bc69580-d29c-11ea-9dbc-08e265809a2f.png)
![2020-07-30_19 43 29](https://user-images.githubusercontent.com/11133215/88955977-fa0b5800-d29c-11ea-8677-d48c36648465.png)

**Comment by MarcMumb** [comment]
Any Chance to get Vulcan APi? AMD didn´t Support anymore the Old Open Gl Standard.

**Comment by amnotbananaama** [comment]
@MarcMumb in the future please make your own issue for enhancements. [There are no plans](https://discord.com/channels/602796788608401408/651120262129123330/730968218642153533)  to use Vulkan in Sodium. 

> Using Vulkan in Minecraft is not an option.

**Comment by jellysquid3** [comment]
#188 addresses and fixes this problem. Merging that pull request will close this issue.

**Comment by jellysquid3** [comment]
Closing as Sodium now blacklists these drivers with a2b25d81.
