### ISSUE TITLE
Minecraft Fabric 1.19.4 crashing when i use Physics Mod Pro

### ISSUE THREAD

**Issue by foxiergo** [jellysquid3/Sodium#1791]
### Version information

fabric-loader-0.14.21-1.19.4

### Reproduction Steps

The game crashed whilst unexpected error 
Error: java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/render/vertex/VertexBufferWriter

### Crash Report file

[crash-2023-06-01_19.09.51-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11627457/crash-2023-06-01_19.09.51-client.txt)

### Additional information

_MC crashing with this msg:_
**The game crashed whilst unexpected error 
Error: java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/render/vertex/VertexBufferWriter** 

I am using the latest version of Physics Mod Pro.
But when I put doors, hatches (in the flat world) I get the game crashes. Just recently, I tried to create a normal world, hoping to see the realistic ocean, but after the message "Generate World" appeared another "Save World" and mc crashed with this error (conclusion: the ocean and physics of dynamic blocks for some reason not working) (sodium and all its addons latest version)

This is where I downloaded the [Physics Mod Pro](https://ko-fi.com/post/Physics-Mod-Pro-P5P2KPTM6) from

**Comment by pajicadvance** [comment]
Downgrade the following mods:
Sodium 0.4.11 -> 0.4.10
Indium 1.0.17 -> 1.0.15
Iceberg 1.1.10 -> 1.1.8

**Comment by pajicadvance** [comment]
Also update Iris to 1.6.3.

**Comment by foxiergo** [comment]
### **Thank you so much**
