### ISSUE TITLE
Crash when trying to go on a server. (1.19.4)

### ISSUE THREAD

**Issue by ethywith3undercores** [jellysquid3/Sodium#1798]
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24.jar

### Reproduction Steps

1. boot up Minecraft with the mod.
2. log on to a sever.
3. the game freezes for 2-5 secs.
4. game crash.

### Crash Report file

[hs_err_pid26396.log](https://github.com/CaffeineMC/sodium-fabric/files/11709388/hs_err_pid26396.log)

### Additional information

I really need help with this, I haven't been able to play Minecraft for like 3 days because I run at like 7 fps without sodium ):

thank u >3

**Comment by Poopooracoocoo** [comment]
Have you ever been able to use Sodium? Is this exclusive to multiplayer? What GPU and graphics driver version do you have? You may need to update it if it's an Intel GPU.

**Comment by ethywith3undercores** [comment]
> Have you ever been able to use Sodium? Is this exclusive to multiplayer? What GPU and graphics driver version do you have? You may need to update it if it's an Intel GPU.

yes I have in till 3 days ago, I haven't checked on single player, and I don't know how to check what gpu & graphics driver I have

**Comment by ethywith3undercores** [comment]
> Have you ever been able to use Sodium? Is this exclusive to multiplayer? What GPU and graphics driver version do you have? You may need to update it if it's an Intel GPU.
also just checked yes it still crash in single player

**Comment by pajicadvance** [comment]
Please also upload the client log after the crash occurs.

**Comment by ethywith3undercores** [comment]
> Please also upload the client log after the crash occurs.

how do I do that?

**Comment by pajicadvance** [comment]
Trigger the crash again, then upload the file `.minecraft/logs/latest.log` here.

**Comment by ethywith3undercores** [comment]
> Trigger the crash again, then upload the file `.minecraft/logs/latest.log` here.

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11713588/latest.log)

[hs_err_pid27268.log](https://github.com/CaffeineMC/sodium-fabric/files/11713589/hs_err_pid27268.log)
edit: here's the crash log to it to

**Comment by ethywith3undercores** [comment]
> Trigger the crash again, then upload the file `.minecraft/logs/latest.log` here.

have you figured it out yet?

**Comment by pajicadvance** [comment]
The game is not using your GPU for some reason, and is using the basic display driver instead. You need to figure out which GPU your system has, and install the appropriate drivers. On Windows 11:

> Check GPU from Settings
Select Settings > System. Select Display and scroll down to Related settings. Select Advanced display. Your GPU's make and model should be shown under Display information.

You can then look online for the driver for your GPU and download and install it.

**Comment by ethywith3undercores** [comment]
> The game is not using your GPU for some reason, and is using the basic display driver instead. You need to figure out which GPU your system has, and install the appropriate drivers. On Windows 11:
> 
> > Check GPU from Settings
> > Select Settings > System. Select Display and scroll down to Related settings. Select Advanced display. Your GPU's make and model should be shown under Display information.
> 
> You can then look online for the driver for your GPU and download and install it.

I just downloaded [Radeon™ RX Vega Series Drivers](https://www.amd.com/en/support/graphics/radeon-rx-vega-series) and it gave me a "code 207" It still downloaded but it's not working still :/
