### ISSUE TITLE
Optifine Cape(?)

### ISSUE THREAD

**Issue by IssueSeeker** [jellysquid3/Sodium#180]
I dont know if you are allowed to enable Optifine cape since, it is made for Optifine. But I know Badlion uses OP capes. So I just thoguht it would be cool if you guys enabled it, as it would allow me to see my and my friends capes while also getting the most FPS out of minecraft.

**Comment by npgoalkeeper** [comment]
Quoting jelly
"no. why would any other mod recognize your donation to Optifine"

**Comment by jellysquid3** [comment]
Why would another mod recognize your donation to Optifine? I'm not considering this. More likely than not, the Badlion client is just packaging Optifine.
