### ISSUE TITLE
1.19.2 Soduim Crash When loading In To Minecraft Server

### ISSUE THREAD

**Issue by Wenzile07** [jellysquid3/Sodium#1802]
### Version information

sodium-fabric-mc1.19.2-0.4.4+build.18 (9)

### Reproduction Steps

1: Add 1.19.2 Sodium Version In Mod Folder
2: Open Minecraft Laucher 
3: Click on Minecraft Server
4 : Stuck On Loading Screen for 2-6 Seconds 
5 : Game Crushes 

### Crash Report file

![](https://cdn.discordapp.com/attachments/1005780406278291468/1117135649410125954/image.png)

### Additional information

I have NotEnoughCrashes installed so I dont have to reopen Launcher again

**Comment by pajicadvance** [comment]
Disable Not Enough Crashes, reproduce the crash again, then upload the full crash log here.
