### ISSUE TITLE
Sodium crashes when trying to render the chiseled bookshelf

### ISSUE THREAD

**Issue by Harrietmarie** [jellysquid3/Sodium#1803]
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Reproduction Steps

There are multiple different ways to replicate the crash, but here is the main one:
1. Search 'chi' in the search bar
2. The chiseled bookshelf will try to render in the creative inventory
3. The game crashes
Or:
1. Scroll through the all items menu of the creative inventory or the functional blocks menu (it exists somewhere beneath paintings)
2. The game crashes when trying to render the item
Or:
1. Try crafting the chiseled bookshelf in the crafting table
2. The game crashes

### Crash Report file

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-06-11 13:26:49
Description: Rendering item

java.lang.NullPointerException: Rendering item

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_332.method_51425(class_332.java:539)

-- Item being rendered --
Details:
	Item Type: chiseled_bookshelf
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.class_332.method_51425(class_332.java:539)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51428(class_332.java:495)
	at net.minecraft.class_465.method_2385(class_465.java:249)
	at net.minecraft.class_465.method_25394(class_465.java:115)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_481.method_25394(class_481.java:722)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$dec000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:14563)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$dec000$notenoughcrashes$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:14563)
	at net.minecraft.class_310.method_1514(class_310.java:824)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (569, 250). Absolute: (1138.000000, 501.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['Shibe05'/727, l='ClientLevel', x=966.37, y=65.00, z=397.78]]
	Chunk stats: 1024, 409
	Level dimension: minecraft:the_nether
	Level spawn location: World: (-96,72,-48), Section: (at 0,8,0 in -6,4,-3; chunk contains blocks -96,-128,-48 to -81,639,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-128,-512 to -1,639,-1)
	Level time: 26458 game time, 26458 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, itemswapper:default, minecraft:supporteatinganimation

-- System Details --
Details:
	Minecraft Version: 1.20
	Minecraft Version ID: 1.20
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1787406376 bytes (1704 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.19
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a56
	Graphics card #0 versionInfo: DriverVersion=27.20.100.9664
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20521.42
	Virtual memory used (MB): 17052.52
	Swap memory total (MB): 12587.05
	Swap memory used (MB): 2784.86
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		advancementscreenshot: Advancement Screenshot 4.1
		ambientsounds: Ambient Sounds (Fabric) unspecified
		appleskin: AppleSkin 2.5.0+mc1.20
		archeologyplus: Archeology Plus 1.0.1
		architectury: Architectury 9.0.7
		auto_third_person: Auto Third Person 2.0.2
		better-suggestions: Better Suggestions 1.0.0
		betterarcheology: Better Archeology 1.0.0
		betterbookshelves: Better Bookshelves 1.0.0
		bettercrafting: Craft Better 1.20-14
		biomeinfo: BiomeInfo 1.20-13
		blockus: Blockus 2.7.1+1.20
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.0-alpha.4
		blossom: Blossom 1.0.7
		blur: Blur (Fabric) 3.1.0
			midnightlib: MidnightLib 1.4.1
			satin: Satin 1.13.0
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.10.85
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.10.85
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.10.85
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.10.85
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.10.85
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.10.85
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.10.85
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.10.85
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.10.85
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.10.85
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.10.85
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.10.85
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.10.85
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.10.85
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.10.85
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.10.85
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.10.85
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.10.85
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.85
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.10.85
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.10.85
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		cat_jam: cat_jam 1.0.2
		chat_heads: Chat Heads 0.10.15
		cherish: Cherish 1.2.0
		chunksfadein: Chunks Fade In 1.0-1.20
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cleancut: CleanCut 6.0
		cloth-config: Cloth Config v11 11.0.99
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 6.57
		completionistsindex: Completionist's Index 7.0.0
		continue: Continue 1.1.1+1.20
		creativecore: CreativeCore (Fabric) 2.10.23
			net_minecraftforge_eventbus: eventbus 6.0.3
		dashloader: DashLoader 5.0.0-beta.1+1.20.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_notalpha_taski: Taski 2.1.0
			dev_quantumfusion_hyphen: Hyphen 0.4.0-rc.3
		dehydration: Dehydration 1.3.4
		doubledoors: Double Doors 4.5
		dungeons_andtaverns_mr: Dungeons and Taverns 1-v2.1.2
		dynamiccrosshair: Dynamic Crosshair 7.0.2+1.20
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			yaclx: YetAnotherConfigLibExtensions 1.1+1.20
		dynamicfps: Dynamic FPS 2.3.0
		e4mc_minecraft: e4mc 3.2.0
			org_java-websocket_java-websocket: Java-WebSocket 1.5.3
		eatinganimationid: Eating Animation 1.9.4+1.20
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		extendedcopper: Extended Copper 1.4.1
		fabric-api: Fabric API 0.83.0+1.20
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a27
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c927
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b27
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d127
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b27
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b27
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f27
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b27
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b327
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b327
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b27
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b27
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe27
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.10+b3afc78b27
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b27
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b27
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b27
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b327
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a27
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b27
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b27
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da27
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b327
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b27
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b27
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c627
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b27
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b27
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b27
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b27
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b327
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b27
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b27
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b27
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b27
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.0.1+b3afc78b27
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.3.1+b3afc78b27
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b327
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b27
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b27
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b327
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b27
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.4+b3afc78b27
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d27
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b27
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b27
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b27
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b27
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b27
		fabric-language-kotlin: Fabric Language Kotlin 1.9.5+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		ferritecore: FerriteCore 6.0.0
		firstperson: FirstpersonModel 2.2.3
		fishontheline: Fish On The Line 3.0
		fog-looks-good-now: FogLooksGoodNow 1.2.0+1.20
		forgeconfigapiport: Forge Config API Port 7.0.0
		healingcampfire: Healing Campfire 5.1
		helditemtooltips: Held Item Tooltips 7.0.0
		horseinboat: HorseInBoat 1.1.4
		icepreventscropgrowth: Ice Prevents Crop Growth 3.0
		illagersweararmor: IllagersWearArmor 1.1.0+1.20
		interactic: Interactic 0.2.0+1.20
		inventoryprofilesnext: Inventory Profiles Next 1.10.3
		itemswapper: ItemSwapper 0.4.0-mc1.20
		jamlib: JamLib 0.6.0+1.20
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		ksyxis: Ksyxis 1.1
		libipn: libIPN 3.0.2
		linkart: Linkart 5.1.1-1.19.3
		lithium: Lithium 0.11.2
		make_bubbles_pop: Make Bubbles Pop Mod 0.1.1-1.19.4
		mcwfences: Macaw's Fences and Walls 1.0.7
		minecraft: Minecraft 1.20
		mo_glass: Mo Glass 1.6.1-MC1.20
		moonlight: Moonlight 1.20-2.5.2
		more-axolotls: More Axolotls 1.1.0
		morebannerfeatures: More Banner Features 1.2.0
		moremobvariants: More Mob Variants 1.2.1
		mousewheelie: Mouse Wheelie 1.11.1+mc1.20-pre2
			amecsapi: Amecs API 1.4.0+mc1.20-pre1
			coat: Coat 1.0.0-beta.20+mc1.20-pre1
			tweed4_annotated: tweed4_annotated 1.3.1+mc1.20-pre1
			tweed4_base: tweed4_base 1.7.1+mc1.20-pre1
			tweed4_data: tweed4_data 1.2.1+mc1.20-pre1
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc1.20-pre1
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.3+mc1.20-pre1
			tweed4_tailor_lang_json_descriptions: tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.4+mc1.20-pre1
		notenoughanimations: NotEnoughAnimations 1.6.4
		notenoughcrashes: Not Enough Crashes 4.4.3+1.20
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		presencefootsteps: Presence Footsteps 1.9.0
			kirin: Kirin UI 1.15.0
		puzzleslib: Puzzles Lib 7.0.2
		qu-enchantments: Qu Enchantments 1.3.5-1.20
			mm: Manningham Mills 2.3
		reciperemover: Recipe Remover 1.0.7
		regions_unexplored: Regions Unexplored 0.4.1+1.20
		rightclickharvest: Right Click Harvest 3.2.2+1.19.x-1.20-fabric
		rpgdifficulty: RpgDifficulty 1.3.12
		skinlayers: 3d Skin Layers 1.5.3-mc1.20
		sleepwarp: SleepWarp 2.1.0+1.20
		smoothswapping: Smooth Swapping 0.9.2
		snifferplus: Hellion's Sniffer+ 0.1.0
		sodium: Sodium 0.4.10+build.27
		sound_physics_remastered: Sound Physics Remastered 1.20-1.1.1
		spyglass-improvements: Spyglass Improvements 1.4+mc1.20+fabric
		starlight: Starlight 1.1.2+fabric.dbc156f
		stoneworks: Stoneworks 7.0.0
		terrablender: TerraBlender 3.0.0.163
		terrathundernether: Terrathunder_Nether_1.20.0_v0.1 1.0.0
		trimmable_tools: Trimmable Tools 1.0.4
		visuality: Visuality 0.7.0+1.20
		wilderwild: Wilder Wild 2.0.4-Fabric+1.20
			caffeineconfig: CaffeineConfig 1.0.0+1.17
			frozenlib: FrozenLib 1.2.4-Fabric+1.20
			nbtcrafting: NBT Crafting 2.2.3+mc1.20
		windchimes: Windchimes 1.2.3+1.20
		xaeroworldmap: Xaero's World Map 1.30.3
		xaerozoomout: XaeroZoomout 1.0.0+mc1.20
	Launched Version: fabric-loader-0.14.21-1.20
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) UHD Graphics GL version 3.2.0 - Build 27.20.100.9664, Intel
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='Error has been generated. GL error GL_INVALID_ENUM in (null): (ID: 173538523) Generic error' x 4
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric, itemswapper:default, minecraft:supporteatinganimation
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Shibe05'/727, l='ServerLevel[Test]', x=966.37, y=65.00, z=397.78]]
	Data Packs: vanilla, fabric, bundle, file/Terralith-1.20-v2.4.0.zip
	Enabled Feature Flags: minecraft:bundle, minecraft:vanilla
	World Generation: Stable
	Client Crashes Since Restart: 3
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: None

### Additional information

This issue may only exist because I'm playing with mods, not sure though. Thanks for trying to resolve this issue :)

**Comment by TheUserCreated** [comment]
The mod "Better Bookshelves" is trying to do things unsupported by sodium. Try adding the mod "CIT Respawn" and see if the crash still occurs.

**Comment by jellysquid3** [comment]
You have not installed [Indium](https://modrinth.com/mod/indium), which is probably the cause of the issue...
