### ISSUE TITLE
no transparency in CTM resourcepacks for opaque blocks using Indium and Continuity

### ISSUE THREAD

**Issue by RafaUC** [jellysquid3/Sodium#1805]
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Expected Behavior

blocks that have extra textures in their models show that decorations with transparency.
(example without sodium and indium)
![2023-06-11_21 32 15](https://github.com/CaffeineMC/sodium-fabric/assets/92828669/2e695388-296d-49fe-b26d-624cdbd5b655)
![2023-06-11_21 36 19](https://github.com/CaffeineMC/sodium-fabric/assets/92828669/6b5bee4f-a032-4df1-b6fd-9d2abb790101)

### Actual Behavior

The transparent part of the textures show black. This only happens when the block that has these model decorations is an opaque block, with leaves and no opaque blocks it works fine.
![2023-06-11_21 12 46](https://github.com/CaffeineMC/sodium-fabric/assets/92828669/8027ec9a-41e5-4f00-8a64-0dff434f6ca7)
![2023-06-11_21 38 30](https://github.com/CaffeineMC/sodium-fabric/assets/92828669/e2507c2e-9913-4ab5-b488-3c56fd0b12a3)

### Reproduction Steps

I loaded the resourcepack Faithless1.20 using Sodium, Indium and Continuity, but in some blocks that have CTM decoration the transparency doesn't work, this is easier to see in the warped forest and the end biomes.

### Java version

19.0.2

### CPU

AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G   2.70 GHz

### GPU

RADEON R7

### Additional information

minecraft 1.20
fabric loader 0.14.21
mods: 
![Screenshot_3](https://github.com/CaffeineMC/sodium-fabric/assets/92828669/3e4cd082-7194-468d-ae3f-60c54374fee6)
resourcepack: https://www.curseforge.com/minecraft/texture-packs/faithless/files/4572791

**Comment by azastral** [comment]
Not sure what is the expected behavior for ctm mods is. But I do know that Minecraft doesn't render transparency in non-transparent blocks. This resource pack gets around that by using [resource pack shaders](https://minecraft.fandom.com/wiki/Shaders) which are incompatible with Sodium.

**Comment by PepperCode1** [comment]
This pack does indeed use core shaders to make solid blocks have cutout textures and to apply emissivity to other textures. The pack author's Discord server has a patch pack that removes all model elements that utilize these features to make everything look correct while using Sodium. Of course, since some things are removed, the world may not look as fancy.
