### ISSUE TITLE
1.19.3 Sodium - missing block textures

### ISSUE THREAD

**Issue by NotAShelf** [jellysquid3/Sodium#1806]
### Version information

sodium 0.4.9+build.23

### Expected Behavior

The textures are rendered as usual.

### Actual Behavior

The world is fully blank

### Reproduction Steps

Load up Minecraft 1.19.3 with Fabric Loader 0.14.21 and Sodium sodium 0.4.9

Generate a world and load in, the world will be blank.

### Java version

Java 17.0.6 64 Bit

### CPU

AMD Ryzen 5 3600x

### GPU

AMD RX 6700 XT

### Additional information

According to [this issue](https://github.com/CaffeineMC/sodium-fabric/issues/1597), the problem is rooted from another mod. I, however, am able to reproduce with only Sodium and Fabric API installed.

**Client Logs**
https://p.frzn.dev/71v

**An overview of the issue**
![image](https://github.com/CaffeineMC/sodium-fabric/assets/62766066/bde35724-4a68-451a-8156-d7f853d44b48)

**Comment by Lolothepro** [comment]
```
[22:46:02] [Render thread/INFO]: OpenGL Vendor: Mesa
[22:46:02] [Render thread/INFO]: OpenGL Renderer: llvmpipe (LLVM 15.0.7, 256 bits)
[22:46:02] [Render thread/INFO]: OpenGL Version: 4.5 (Core Profile) Mesa 23.1.1
```
😕

**Comment by NotAShelf** [comment]
> ```
> [22:46:02] [Render thread/INFO]: OpenGL Vendor: Mesa
> [22:46:02] [Render thread/INFO]: OpenGL Renderer: llvmpipe (LLVM 15.0.7, 256 bits)
> [22:46:02] [Render thread/INFO]: OpenGL Version: 4.5 (Core Profile) Mesa 23.1.1
> ```

To my knowledge, AMDGPU is a part of the driver stack on modern Linux distributions. Am I missing something here?

**Comment by pajicadvance** [comment]
> > ```
> > [22:46:02] [Render thread/INFO]: OpenGL Vendor: Mesa
> > [22:46:02] [Render thread/INFO]: OpenGL Renderer: llvmpipe (LLVM 15.0.7, 256 bits)
> > [22:46:02] [Render thread/INFO]: OpenGL Version: 4.5 (Core Profile) Mesa 23.1.1
> > ```
> 
> To my knowledge, AMDGPU is a part of the driver stack on modern Linux distributions. Am I missing something here?

The game is not using your GPU, it's using software rendering.

**Comment by NotAShelf** [comment]
*oh*

Well that is good to know.

**Comment by NotAShelf** [comment]
Would that be something I can change in launcher settings, or does that mean my graphics stack is misconfigured?

**Comment by NotAShelf** [comment]
Well, this seems to entirely be my fault. Apologies for wasting your time.
