### ISSUE TITLE
1.20, most recent version is causing my game to crash. Class_2350

### ISSUE THREAD

**Issue by OneWhackMan** [jellysquid3/Sodium#1808]
### Version information

mc 1.20

### Reproduction Steps

So far have not seen a way to consistently reproduce the issue, I am running the most recent version of sodium along with iris, using complementary reimagined shaders. Game so far has seemed to crash at random points.

### Crash Report file

[Ihatethisfuckinggame.txt](https://github.com/CaffeineMC/sodium-fabric/files/11729010/Ihatethisfuckinggame.txt)

**Comment by pajicadvance** [comment]
Please provide a client log at the time of the crash.

**Comment by BluebirdYT** [comment]
I recently updated my NVIDIA Drivers and am also experiencing the same issue, Here are logs and the crash report. This is happening for 1.19.4 and 1.20 for me, but these are the logs from 1.20 with only sodium.
[hs_err_pid17988.log](https://github.com/CaffeineMC/sodium-fabric/files/11752266/hs_err_pid17988.log)
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11752267/latest.log)

**Comment by BluebirdYT** [comment]
Are you using any other mods?

**Comment by jellysquid3** [comment]
There are indications of memory corruption and/or CPU faults in the crash dump. Your computer may have stability issues. You should run a CPU and RAM stability test (maybe with [OCCT](https://www.ocbase.com/)) to verify that your hardware is working as expected.

**Comment by jellysquid3** [comment]
I'm pretty sure this is not an issue with Sodium, so I am going to close this issue. If you believe differently, ask for it to be re-opened.
