### ISSUE TITLE
Game crashes on Mojang Studios Loading screen while using sodium

### ISSUE THREAD

**Issue by 7seasking** [jellysquid3/Sodium#1811]
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Reproduction Steps

1. Installed sodium on 1.20.1
2. Launched it 
3. Game got stuck in Mojang Studios loading screen
4. After few seconds it was not responding

### Crash Report file

https://paste.ee/p/1B2cG

### Additional information

Ok so I think it's the issue of driver, because I saw few posts regarding same issue and they said to use latest driver which is 15.33.53.5161 , I tried installing this driver but it's not installing, my driver won't update, even though I tried installing the latest update 2-3 times. The update which I have currently is 10. Smth. Do you guys know why is it not updating ?

**Comment by suhispros** [comment]
Same thing to me but for 1.19.3+ how do i fix it

**Comment by pajicadvance** [comment]
Unfortunately, this is not something we provide support for. If you're having issues installing the driver, the Internet is your friend, and you can try contacting Intel support.

**Comment by 7seasking** [comment]
To clear things up,I had Intel HD 2500 and my driver was not updating to the latest driver shown in #899, and I was so pissed but  I fixed it very easily, hey jelly if you are reading this then type this in your own way because I'm bad at English and then pin it because this is simple but effective. People with this issue can go to device manager and in display adapters click on graphics card in your case if you are facing this problem it will be Intel, so click on Intel and then click on update driver, then click on select drivers available on my pc (don't click search online), then when it shows the list uncheck the 'show compatible drivers' and it will give a bunch of GPU drivers, in there select Intel HD 4000 and install it it will give warning but ignore it and install then restart and enjoy sodium.
