### ISSUE TITLE
Issue with the Vanilla Tweaks texture pack.

### ISSUE THREAD

**Issue by Blergonos** [jellysquid3/Sodium#1813]
### Version information

mc1.20-0.4.10+build.27, mc-1.20.1, fabric loader-0.14.21-1.20.1

### Expected Behavior

When opening the settings menu, I expect the sliders and the on-off buttons to be visible, like they always were (this is the first time I seen this issue, even with the same texture pack from vanilla tweaks). The photo is what I expect to see. Note that this photo was made when the texture pack was off.
![Sodium gltich](https://github.com/CaffeineMC/sodium-fabric/assets/129961843/5f25b41f-384c-4fb4-a7cb-87b10d841de4)

### Actual Behavior

The sliders and on-off buttons aren't visible, making it difficult to use. This photo is what happens. Note that this photo was made with the texture pack on. Before 1.20 this never happened. The second image is the mods I have installed. Note that I tried without Sodium Extra, BSVSB, and Reeses Sodium Options and this didn't fix the issues.
![sodium glitch 2](https://github.com/CaffeineMC/sodium-fabric/assets/129961843/cad39d39-8c8a-4bcc-aed7-17653b049bd9)
![sodium glitch 3](https://github.com/CaffeineMC/sodium-fabric/assets/129961843/6720f825-2105-4b29-b6d7-7fd2d17bf36a)

### Reproduction Steps

[VanillaTweaks_r654081.zip](https://github.com/CaffeineMC/sodium-fabric/files/11756989/VanillaTweaks_r654081.zip)
This is the texture pack configuration I'm using.
![sodium glitch 3](https://github.com/CaffeineMC/sodium-fabric/assets/129961843/fd1508fd-6149-4ea0-9203-0eb5914a1f7f)
And the mods I use. To recreate just install the texture pack, go into video settings, and there's the problem.

### Java version

Java 8 Update 371

### CPU

Intel Core i7 8565U 1.80Ghz 1.99Ghz

### GPU

Nvidia MX130

### Additional information

I already gave everything above that is needed, I will edit it if you need me to.

**Comment by Julienraptor01** [comment]
The reason is because this pack has core shaders, remake your pack on the website whitout the features that use core shaders

**Comment by Blergonos** [comment]
> The reason is because this pack has core shaders, remake your pack on the website whitout the features that use core shaders

Ok then. Thanks.

**Comment by jellysquid3** [comment]
The mentioned commit incorrectly references this issue, when it should have referenced #1816.

**Comment by Edenmessi107** [comment]
> The reason is because this pack has core shaders, remake your pack on the website whitout the features that use core shaders

what are the features that use core shaders I don't know

**Comment by MeeniMc** [comment]
Please join the discord if you want guidance on this.
