### ISSUE TITLE
1.20 hanging_sign crash

### ISSUE THREAD

**Issue by dueilee1** [jellysquid3/Sodium#1815]
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Reproduction Steps

Crashes if hanging_sign is detected within the render distance.
I am sorry for not being soft because I am not good at English.

### Crash Report file

[crash-2023-06-16_02.01.28-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11760737/crash-2023-06-16_02.01.28-client.txt)

**Comment by Timolino456** [comment]
Try updating More Culling.

**Comment by dueilee1** [comment]
THX!!
