### ISSUE TITLE
Game stuck on starting screen with Sodium only

### ISSUE THREAD

**Issue by GodProZEE** [jellysquid3/Sodium#1817]
### Version information

mc1.20-0.4.10+build.27

### Reproduction Steps

1. Start the game
2. The game doesn't get past the loading screen which says "Mojang".

### Crash Report file

https://mclo.gs/ryfEHCj

### Additional information

I use Sodium, Lithium, and Starlight, and after removing everything but Sodium, the error is still there so it's Sodium causing this issue.

**Comment by pajicadvance** [comment]
Duplicate of #899 . Update your Intel GPU drivers.
