### ISSUE TITLE
Incorrect cloud shading at long distances.

### ISSUE THREAD

**Issue by virgiliopita** [jellysquid3/Sodium#1818]
### Version information

mc1.20-0.4.10+build.27

### Expected Behavior

The clouds are supossed to fade to a solid colour. 
![2023-06-16_12 36 55](https://github.com/CaffeineMC/sodium-fabric/assets/104319308/56018377-346c-4949-88c8-d455671296d9)

Here I'm using this line in sodium-mixins.properties
`mixin.features.clouds=false`

### Actual Behavior

Instead they render like this

![2023-06-16_12 46 28](https://github.com/CaffeineMC/sodium-fabric/assets/104319308/d862b25f-1c8e-4040-9d80-a1f516abc8b5)

### Reproduction Steps

1. /time set 13.000
2. Look at clouds.

A "quick-fix" is discussed in here:
https://discord.com/channels/602796788608401408/1119198798669955072/1119198798669955072 

### Java version

17.0.3 64bit

### CPU

Intel Core i9-9900K

### GPU

NVIDIA GeForce RTX 2080

## Modlist:
![image](https://github.com/CaffeineMC/sodium-fabric/assets/104319308/bbbd043e-3108-4e22-a27c-6cf2f4740778)

**Comment by jLn0n** [comment]
that's intended feature of sodium I think.

**Comment by astridellensdottir** [comment]
bug report was requested from a support request on the discord server.

**Comment by jellysquid3** [comment]
The rendering of clouds has been changed in Sodium 0.5.0 so that they are affected by sunset/sunrise again. It isn't exactly identical to vanilla, but it's close enough and in my opinion looks better than vanilla.
