### ISSUE TITLE
Un fair discord ban

### ISSUE THREAD

**Issue by Danjhop4** [jellysquid3/Sodium#1821]
I have to use 3rd party discords since there no real help
And they just ban for spam 
And I have to use public chat since dm is closed

**Comment by jellysquid3** [comment]
You do not seem to understand that when people ban you, they don't want to continue talking to you. Using our Discord server to harass other people who happen to moderate servers you were banned from is **_unacceptable and child-like._**

You are not entitled to a discussion with anyone. When people show you the door, you walk out. Anything more is harassment and you will continue to be removed from every single forum you attempt to do this in.

Take the pacifier out of your mouth and grow up.
