### ISSUE TITLE
Sodium Crash on 1.16.5

### ISSUE THREAD

**Issue by SahiliBro** [jellysquid3/Sodium#1822]
### Version information

mc1.16.5-0.2.0

### Reproduction Steps

1. Minecraft Opens Perfectly
2. Create a World, Join a World or Join a Server
3. Loading Terrain
4. Just After (Loading Terrain) Says Saving World and then crash

### Crash Report file

[crash-2023-06-17_10.41.05-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11780335/crash-2023-06-17_10.41.05-client.txt)

**Comment by pajicadvance** [comment]
Sodium does not work on Pojav Launcher.
