### ISSUE TITLE
My Minecraft is crashing 

### ISSUE THREAD

**Issue by s1QE** [jellysquid3/Sodium#1826]
### Version information

sodium-fabric-mc1.16.5-0.2.0+build.4

### Reproduction Steps

I start Minecraft, go to the world / server, the world is entered and my Minecraft crashes with error 1

### Crash Report file

[crash-2023-06-18_22.36.30-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11781369/crash-2023-06-18_22.36.30-client.txt)

### Additional information

I use modium 0.1.0 from Youtuber's build along with medium extra 0.1.0 and everything works fine there. But I wanted to install shaders along with sodium and iris shaders require sodium 0.2.0

**Comment by pajicadvance** [comment]
Sodium doesn't work on Pojav Launcher.
