### ISSUE TITLE
[Modpack] Crash when trying to render Spruce Hanging Signs in multiplayer

### ISSUE THREAD

**Issue by HollyBlocky** [jellysquid3/Sodium#1828]
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Reproduction Steps

1. Join Fabric server with Sodium + Lithium
2. Render in a (Spruce) "Hanging Sign"; whether it be placing it down, or coming across one that was placed by another player

### Crash Report file

[crash-2023-06-19_11.31.31-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11789793/crash-2023-06-19_11.31.31-client.txt)

### Additional information

Quilt loader, extensively client-side modded 

Edit: they render fine in Singleplayer

**Comment by pajicadvance** [comment]
Update More Culling, the latest version resolves the problem.
