### ISSUE TITLE
FPS constantly dropping to 0 for about a second

### ISSUE THREAD

**Issue by MangekyouSasuke** [jellysquid3/Sodium#183]
I tested the mod on a survival server I oftenly play, my usual FPSs are about 15 to 30 max, usually around 20, with the mod installed the FPS I usually had went to 30 with a max of 40, but it started to go down to 0 for about a second really often, about each 4 seconds or less it went down to 0 for a second and it is really annoying. It did improve the FPS but also made them go lower, if you could do something about this I'd be really thankful, anyways, the mod is really good for better computers so good job! ^^

Btw, a friend on the same server said that he tested the mod too and he had the exact same problem.

**Comment by amnotbananaama** [comment]
Please use the issue template. Note that the GitHub Issue tracker is for bugs and is not intended as a support site. I suggest joining [JellySquid's Hideout](https://jellysquid.me/discord) and providing the following from the Bug template in `#tech-support`.

> ### Attachments
> Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.
> 
> ### System Information
> You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.
>
> - Java Version: [fill me in]
> - CPU: [fill me in]
> - GPU: [fill me in]

Screenshots of the [Profiler Graph](https://minecraft.gamepedia.com/Debug_screen#Profiler_graph) and [Frame Time Graph](https://minecraft.gamepedia.com/Debug_screen#Frame_time_graph) during normal gameplay should satisfy the above.

**Comment by jellysquid3** [comment]
This is a troubleshooting question, which are better suited for the Discord server as amnotbananaama refers to above.

**Comment by ghost** [comment]
Just a question,
Have you changed your jvm arguments?
for me ZGC caused drops that seem like yours.
