### ISSUE TITLE
Exit code 1 when running sodium it keeps crashing

### ISSUE THREAD

**Issue by uhimkia2** [jellysquid3/Sodium#1835]
### Version information

sodium-fabric-mc1.19.2-0.4.4build.18_4.jar

### Reproduction Steps

Example:
I start up the game walk around
When i switch dimensions it crashes my game

### Crash Report file

Exit code 1

### Additional information

help bro

**Comment by Timolino456** [comment]
"Exit code 1" doesn't tell us anything, you need to actually upload the crash log

**Comment by FractalGeodes** [comment]
Preferably also include information like your operating system, GPU, and possibly a mod list

**Comment by uhimkia2** [comment]
> "Exit code 1" doesn't tell us anything, you need to actually upload the crash log

my discord is (uhimkia) please add me

**Comment by uhimkia2** [comment]
uhimkia is my discord please help ill send more details there

**Comment by pajicadvance** [comment]
Upload your log here, otherwise you're not getting any help.

**Comment by uhimkia2** [comment]
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11834653/latest.log)

**Comment by pajicadvance** [comment]
Are there any log files starting with `hs_err_pid` in your `.minecraft` folder? If yes, open the latest one and send the first ~15 lines of the file, before the Summary section.

**Comment by uhimkia2** [comment]
---------------  S Y S T E M  ---------------

OS:
 Windows 11 , 64 bit Build 22621 (10.0.22621.1778)
OS uptime: 0 days 0:21 hours

CPU: total 12 (initial active 12) (6 cores per cpu, 2 threads per core) family 6 model 165 stepping 2 microcode 0xe0, cx8, cmov, fxsr, ht, mmx, 3dnowpref, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, lzcnt, tsc, tscinvbit, avx, avx2, aes, erms, clmul, bmi1, bmi2, adx, fma, vzeroupper, clflush, clflushopt

Memory: 4k page, system-wide physical 16222M (8635M free)
TotalPageFile size 22622M (AvailPageFile size 12315M)
current process WorkingSet (physical memory assigned to process): 1888M, peak: 1933M
current process commit charge ("private bytes"): 2514M, peak: 2842M

vm_info: OpenJDK 64-Bit Server VM (17.0.3+7-LTS) for windows-amd64 JRE (17.0.3+7-LTS), built on Apr 20 2022 04:24:16 by "" with MS VC++ 16.10 / 16.11 (VS2019)

END.

**Comment by pajicadvance** [comment]
Those are the *last* 15 lines - the *first* 15 lines are important.

**Comment by uhimkia2** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9dff1b540, pid=7996, tid=15468
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [nvoglv64.dll+0x191b540]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by pajicadvance** [comment]
Sodium doesn't work properly on Nvidia graphics when using the official Minecraft launcher due to a driver issue. The only solution right now is to update your graphics drivers and use a third party Minecraft launcher (we recommend Prism Launcher). See #1816 .
