### ISSUE TITLE
game crashes before the loading screen starts using Pojavlauncher

### ISSUE THREAD

**Issue by Nikitoonchik** [jellysquid3/Sodium#1836]
### Version information

sodium 0.2.0+build.4

### Reproduction Steps

Starting the game and before loading screen start the game crashes

### Crash Report file

[latestlog.txt](https://github.com/CaffeineMC/sodium-fabric/files/11839492/latestlog.txt)

### Additional information

Playing wia Pojavlauncher on the phone Samsung Galaxy A31

**Comment by Timolino456** [comment]
Pojav Launcher is not supported

**Comment by Felix14-v2** [comment]
> Playing wia Pojavlauncher

Select this in the instance settings:
![Screenshot_20230621-172523](https://github.com/CaffeineMC/sodium-fabric/assets/75726196/a02c23ab-df29-441b-bf6f-163518508893)

**Comment by Nikitoonchik** [comment]
@Felix14-v2 , i turned this renderer and now i am trying to join the world , but it crashes too, can u help? does it need Java 17 too?

**Comment by Felix14-v2** [comment]
Not here, this isn't a support forum. But I can help in discord: felix14_v2
