### ISSUE TITLE
Some Glass Panes Not Rendering Other Glass Blocks

### ISSUE THREAD

**Issue by IAmPhos548** [jellysquid3/Sodium#1837]
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Expected Behavior

Stained Glass to be rendered through other glass with air blocks in between, shown here:
![2023-06-22_16 18 25](https://github.com/CaffeineMC/sodium-fabric/assets/137447101/c784c8f0-ed96-45bc-b9d1-234db75c021b)
![2023-06-22_16 20 35](https://github.com/CaffeineMC/sodium-fabric/assets/137447101/306fd925-58fb-45fa-bc77-ed9920b9d57b)

### Actual Behavior

With ONLY Fabric API and Sodium installed, glass is partially rendered or not rendered at all through stained glass. It appears that certain colors can render through some, but not the same color:
![2023-06-22_16 19 21](https://github.com/CaffeineMC/sodium-fabric/assets/137447101/0d08260e-7f9d-4e39-ae8a-645ba563b5a2)
![2023-06-22_16 19 48](https://github.com/CaffeineMC/sodium-fabric/assets/137447101/a8ceda3b-c9ab-48fe-8ae1-405b16e6a306)

### Reproduction Steps

Place glass blocks behind other glass or glass panes with one or more air blocks in between the glass blocks

### Java version

17.0.1

### CPU

Intel 8700k

### GPU

ASUS Nvidia 1080Ti

**Comment by Lolothepro** [comment]
duplicate of #38

**Comment by IAmPhos548** [comment]
oop never saw that post, did not know was long standing issue.
