### ISSUE TITLE
My mc crashing using sodium/some addons of sodium

### ISSUE THREAD

**Issue by toolblocks** [jellysquid3/Sodium#1838]
### Version information

mc1.20-0.4.10+build.27

### Reproduction Steps

Reinstalled sodium and all addons I using for sodium (E.G. Sodium Extra, Indium, Lithium, Mod Menu, ETC)

### Crash Report file

here the link https://pastebin.com/DgFWkY4V

**Comment by jellysquid3** [comment]
The crash log is not accessible. Please upload it directly as a file to GitHub, by using the "Attach files" button, or by drag-and-dropping the file.

**Comment by icypandadgg** [comment]
same issues with me my Minecraft dose this dose yours cbrocraft idk fix  my spects are 
Processor: Intel(R) Core(TM) i3-3220 CPU @ 3.30GHz   3.30 GHz
Installed RAM	16.0 GB (15.9 GB usable)
System type	64-bit operating system, x64-based processor
and it happed after i got razor cotex


![image](https://github.com/CaffeineMC/sodium-fabric/assets/110714215/71048565-7d8f-4b70-8ad4-522fbf516f7a)

**Comment by toolblocks** [comment]
yes i too

**Comment by toolblocks** [comment]
[Log.txt](https://github.com/CaffeineMC/sodium-fabric/files/11848502/Log.txt)

**Comment by toolblocks** [comment]
here the log @jellysquid3

**Comment by Fnige** [comment]
Thats not the crash log

**Comment by pajicadvance** [comment]
Hacked clients are not supported.

**Comment by toolblocks** [comment]
this is crash log

**Comment by toolblocks** [comment]
i found it in logs folder in .minecraft
