### ISSUE TITLE
Magma block should be self-lit

### ISSUE THREAD

**Issue by LucilleTea** [jellysquid3/Sodium#184]
### Expected Behavior
Magma blocks should always be rendered at full brightness, despite not emitting that level of light.

### Actual Behavior
Magma blocks are rendered with their actual light level.

### Reproduction Steps
View magma blocks.

### Attachments
https://cdn.discordapp.com/attachments/651120262129123330/728753455392358440/unknown.png

### System Information
Has been observed on many systems.
From screenshot:
- Java Version: 1.8.0_242
- CPU: i7 6700k
- GPU: GTX 1070

**Comment by Bobronium** [comment]
Any ETA of fix for this?
