### ISSUE TITLE
my minecraft crashes and the developer is lying

### ISSUE THREAD

**Issue by s1QE** [jellysquid3/Sodium#1840]
### Version information

sodium-fabric-mc1.16.5-0.2.0+build.4

### Reproduction Steps

My Minecraft crashes when installing sodium version 2.0+ and sodium extra 2.0+, the developer answered my last report saying that sodium does not work on the pojavlauncher, but this is a lie. Sodium worked on version 0.1.0 and Sodium extra 0.1.0

### Crash Report file

[crash-2023-06-18_22.36.30-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11847634/crash-2023-06-18_22.36.30-client.txt)

**Comment by pajicadvance** [comment]
Sure, use 0.1 if it works then. The point is that we are not going to help users set up Sodium on Pojav. Pojav does not provide an OpenGL driver which Sodium requires. Any issues that you're having should be taken to the developers of Pojav and not us. Nobody is lying to you and you should keep this attitude out of our issue tracker.

**Comment by Felix14-v2** [comment]
> Pojav does not provide an OpenGL driver which Sodium requires

Isn't Angle that driver?

**Comment by Fnige** [comment]
Angle just basically translate the OpenGL shenanigans to Vulkan iirc 

Still not supported either way

**Comment by agent1243** [comment]
I can't stand the stupidity of the sodium developers
