### ISSUE TITLE
crash while trying to render moving piston with continuity (1.20)

### ISSUE THREAD

**Issue by Pietr06** [jellysquid3/Sodium#1841]
### Version information

Sodium 0.4.10+build.27

### Reproduction Steps

have both tried with only continuity and only sodium, it crashes only with both on, just join a world and power a piston

### Crash Report file

[crash-2023-06-23_17.59.52-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11850121/crash-2023-06-23_17.59.52-client.txt)

**Comment by pajicadvance** [comment]
You need to have Indium installed in order to use Continuity with Sodium: https://modrinth.com/mod/indium
