### ISSUE TITLE
incorrect display of text and freezing when starting the world in minecraft 1.20 with sodium

### ISSUE THREAD

**Issue by E1e3tr0nick** [jellysquid3/Sodium#1843]
### Version information

0.4.10

### Reproduction Steps

when I go into the game, all the text changes, and when I go to the server or to the world, the game freezes and does not respond, and when I close it, it gives an error -805306369. it seems like I read what is there, but everything is fine with me and without sodium everything starts up well, but performance suffers because of this, of course. if it helps someone then I have a nvidia video card

### Crash Report file

[crash-2023-06-24_15.09.09-server.txt](https://github.com/CaffeineMC/sodium-fabric/files/11856881/crash-2023-06-24_15.09.09-server.txt)

### Additional information

![javaw_bAIrlmrDuU](https://github.com/CaffeineMC/sodium-fabric/assets/137617250/469ef664-0f7c-4d35-adeb-588873cb2d08)

**Comment by pajicadvance** [comment]
The crash report lists "Creative Core" as the culprit. The incorrect text rendering likely isn't caused by Sodium, but some other mod.

**Comment by Flajekt** [comment]
I have the same problem with text squares. But on 1.20.1 optifabric version. And it only happens because of fabric api. I tried to instal different versions op fabric api but it stil doesn't work. So if you have any idea why that happened I would appreciate if you can help me. Thank you in advance!

**Comment by hexadecimal233** [comment]
Sodium will never support optifabric unfortunately

**Comment by Flajekt** [comment]
> Sodium will never support optifabric unfortunately

yee, I know. I don't use sodium. But this guy have the same problem as I have. I though maybe fabric api cost the issue

**Comment by Flajekt** [comment]
> I have the same problem with text squares. But on 1.20.1 optifabric version. And it only happens because of fabric api. I tried to instal different versions op fabric api but it stil doesn't work. So if you have any idea why that happened I would appreciate if you can help me. Thank you in advance!

OK, no worries. I fixed it with 0.85.0 fabric api version
