### ISSUE TITLE
Game can't start

### ISSUE THREAD

**Issue by quocnam201010** [jellysquid3/Sodium#1846]
### Version information

mc1.19.4-0.4.10+build.24

### Reproduction Steps

1. Add Sodium to \mods folder
2. Launch the game
3. the game freezes while on the loading screen.

### Crash Report file

Because the game freezes when it starts, I can't get the crash report

### Additional information

I don't know why, but after updating window, Sodium stops working. I tried reversing the update but I can't.
I hope this issue will be fixed soon, I love Sodium so much, I can't live without it.

**Comment by Felix14-v2** [comment]
> Because the game freezes when it starts, I can't get the crash report

At least Minecraft generates latest.log, upload it here. Also, what's your launcher, by the way? Debug info from it would be helpful

**Comment by Fnige** [comment]
What CPU do you have?

**Comment by mrpyrocat** [comment]
for me, it also would not start but I got this crash report:
[14:05:08] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[14:05:08] [ForkJoinPool-1-worker-1/WARN]: Mod sodium uses the version ${version} which isn't compatible with Loader's extended semantic version format (Could not parse version number component '${version}'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[14:05:08] [main/INFO]: Loading 117 mods:
	- appleskin 2.5.0+mc1.20
	- badpackets 0.4.1
	- bettercontrols 1.3.0
	- betterf3 7.0.0
	- bettermounthud 1.2.2
	- betterthirdperson 1.9.0
	- camerautils 1.20.1-1.0.4
	   |-- fabric-api-base 0.4.29+b04edc7a82
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da82
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b82
	   \-- fabric-resource-loader-v0 0.11.7+f7923f6d82
	- citresewn 1.1.3+1.20
	   \-- citresewn-defaults 1.1.3+1.20
	- cloth-api 4.0.65
	   |-- cloth-basic-math 0.6.1
	   |-- cloth-client-events-v0 4.0.65
	   |-- cloth-common-events-v1 4.0.65
	   |-- cloth-scissors-api-v1 4.0.65
	   \-- cloth-utils-v1 4.0.65
	- cloth-config 11.0.99
	   \-- cloth-basic-math 0.6.1
	- collective 6.62
	- do_a_barrel_roll 3.0.1+1.20
	   |-- cicada 0.4.0
	   \-- com_github_llamalad7_mixinextras 0.2.0-beta.6
	- enchantedtooltips 1.3.7-1.20
	   \-- kyrptconfig 1.5.6-1.20
	- essential-container 1.0.0
	   \-- essential-loader 1.2.0
	- fabric-api 0.83.1+1.20.1
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b77
	   |-- fabric-command-api-v1 1.2.32+f71b366f77
	   |-- fabric-command-api-v2 2.2.11+b3afc78b77
	   |-- fabric-commands-v0 0.2.49+df3654b377
	   |-- fabric-containers-v0 0.1.61+df3654b377
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.1.11+b3afc78b77
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b77
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b77
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.26+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c677
	   |-- fabric-message-api-v1 5.1.6+b3afc78b77
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b77
	   |-- fabric-models-v0 0.3.35+b3afc78b77
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b77
	   |-- fabric-networking-v0 0.3.48+df3654b377
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b77
	   |-- fabric-particles-v1 1.0.28+b3afc78b77
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b77
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b77
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b77
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b77
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b77
	   |-- fabric-rendering-v0 1.1.47+df3654b377
	   |-- fabric-rendering-v1 3.0.6+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b77
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b77
	- fabric-language-kotlin 1.9.5+kotlin.1.8.22
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.22
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.22
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.1
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.1
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.1
	- fabricloader 0.14.21
	- held-item-info 1.5.0
	- horsestatsvanilla 4.3.0
	   \-- libgui 8.0.0+1.20
	        |-- jankson 5.0.1+j1.2.2
	        |    \-- blue_endless_jankson 1.2.2
	        \-- libninepatch 1.2.0
	- inventoryprofilesnext 1.10.3
	- java 17
	- jei 15.2.0.22
	- libipn 3.0.2
	- litematica 0.15.0
	- lithium 0.11.2
	- malilib 0.16.0
	- minecraft 1.20.1
	- minihud 0.27.0
	- modmenu 7.0.1
	- mousetweaks 2.25
	- skinlayers 1.5.3-mc1.20
	- smoothscrollingeverywhere 3.0.3-unstable
	- sodium ${version}
	- tooltipfix 1.1.1-1.20
	- tweakeroo 0.17.0
	- wthit 8.1.1
	- yet_another_config_lib_v3 3.0.2+1.20
	   |-- com_twelvemonkeys_common_common-image 3.9.4
	   |-- com_twelvemonkeys_common_common-io 3.9.4
	   |-- com_twelvemonkeys_common_common-lang 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-core 3.9.4
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.9.4
	   \-- com_twelvemonkeys_imageio_imageio-webp 3.9.4
[14:05:09] [main/ERROR]: Uncaught exception in thread "main"
java.lang.RuntimeException: Failed to read accessWidener file from mod sodium
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:480) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: Namespace (named) does not match current runtime namespace (intermediary)
	at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285) ~[access-widener-2.1.0.jar:?]
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84) ~[access-widener-2.1.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.loadAccessWideners(FabricLoaderImpl.java:478) ~[fabric-loader-0.14.21.jar:?]
	... 3 more
hopefully thats helpful

**Comment by pajicadvance** [comment]
@mrpyrocat I responded to your issue report with a solution. Why are you posting about your issue in an unrelated report? Don't spam.

**Comment by mrpyrocat** [comment]
@pajicadvance  your solution sadly did not work instead I got this error and thought it would be related to this

**Comment by jellysquid3** [comment]
@Quocnam201010 You almost certainly have broken drivers as described by #899. Windows is known for replacing the graphics driver with a version that has major issues. If you do not think this is the issue, then re-open this issue with more information about your hardware, because we can't diagnose it without a log file & hardware info.
