### ISSUE TITLE
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'supplementaries'!

### ISSUE THREAD

**Issue by StarGarnet03** [jellysquid3/Sodium#1847]
### Version information

mc1.20-0.4.10+build27

### Reproduction Steps

I have used Curseforge, using fabric as the mod loader, to create the majority of the mod pack that I'm making, aside from sodium. Here's the list of mods:
![image](https://github.com/CaffeineMC/sodium-fabric/assets/129735169/11a3513c-2676-4e16-9dae-10470e7ad91c)

How to recreate:
1. Launch Minecraft

### Crash Report file

[crash-2023-06-26_17.59.39-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11865851/crash-2023-06-26_17.59.39-client.txt)

**Comment by Fnige** [comment]
You need indium https://modrinth.com/mod/indium
