### ISSUE TITLE
bug with pixels in blocks

### ISSUE THREAD

**Issue by disfelt** [jellysquid3/Sodium#185]
### Attachments
![2020-07-26_10 08 23](https://user-images.githubusercontent.com/68804174/88473736-17e95d80-cf29-11ea-9b3d-19b70e5d5b5c.png)
![2020-07-26_10 07 02](https://user-images.githubusercontent.com/68804174/88473737-19b32100-cf29-11ea-8963-449a240b5f31.png)

### System Information
win 10

- Java Version: [1 16 1]
- CPU: [r5 2600]
- GPU: [2060s]

**Comment by LucilleTea** [comment]
Can you check if you have anisotropic filtering force enabled in your nvidia control panel? Looks a bit like #173

**Comment by UltraVioletbruh** [comment]
> Can you check if you have anisotropic filtering force enabled in your nvidia control panel? Looks a bit like #173

**Comment by disfelt** [comment]
> Can you check if you have anisotropic filtering force enabled in your nvidia control panel? Looks a bit like #173

i tried on and off it. none of these helped

**Comment by FluffyDiscord** [comment]
same issue
OS: ubuntu 20.04
JRE: 14 x64
CPU: r7 2700
GPU: rx 5700 xt
mesa drivers

looks to me like a rounding issue (precision)

**Comment by mrmangohands** [comment]
I'm assuming this is a CVF issue, but it's seen a lot of changes since this was active. Please re-open if you can still produce this on the latest dev builds.
