### ISSUE TITLE
My sodium uses opengl 3.2 instead of 4.6 with a 7900xtx 

### ISSUE THREAD

**Issue by Studio640** [jellysquid3/Sodium#1853]
### Version information

mc1.20-0.4.10+build.27

### Expected Behavior

Hello, reading the documentation I saw that it was compatible with opengl 4.6.

### Actual Behavior

Hello, I have a 7900XTX that is up to date and compatible with opengl 4.6 and when I use sodium and look at the information in the F3 I see that it uses opengl 3.2.

Can you help me solve my problems?

### Reproduction Steps

(classic mod install)

### Java version

Java 17.0.3 (Eclipse Adoptium)

### CPU

AMD Ryzen 7 7700X 

### GPU

AMD Radeon 7900XTX

### Additional information

Mod list :
- sodium-fabric-mc1.20-0.4.10+build.27
- lithium-fabric-mc1.20.1-0.11.2
- BetterF3-7.0.0-Fabric-1.20-pre6

**Comment by pajicadvance** [comment]
This is intended behavior. The game requests an OpemGL Core 3.2 context, but this does not mean it cannot use OpenGL features from newer versions. The requested context is only a minimum requirement.
