### ISSUE TITLE
I think im Different

### ISSUE THREAD

**Issue by GreenWolf142** [jellysquid3/Sodium#1854]
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Expected Behavior

Load up Minecraft and to work prefectly fine

### Actual Behavior

My minecraft just freezed up. In the TaskManager it said Minecraft is not responding and used lot of my memory but not my processor. And my minecraft didn't showed up as "Not Responding" i waited 2 hours but still didn't loaded up. But without sodium prefectly runs.

### Reproduction Steps

Downloaded sodium
Put into the minecraft mods folder.
Started up minecraft.
Got into the Loading screen
Stucks there.

### Java version

0.14.21

### CPU

Intel Core I5-13400F

### GPU

NVIDIA RTX-2080 ti

### Additional information

Non

**Comment by pajicadvance** [comment]
Send your client log, you can find it in `.minecraft/logs/latest.log`.

**Comment by GreenWolf142** [comment]
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11895187/latest.log)


> Send your client log, you can find it in `.minecraft/logs/latest.log`.

**Comment by pajicadvance** [comment]
The game is using integrated graphics instead of using your graphics card. Make sure that your display is physically connected to the graphics card and not your motherboard.

**Comment by jellysquid3** [comment]
@GreenWolf142 I think you have problems. Are you sure you actually have an i5-13400F and RTX 2080 Ti? Your drivers appear to be modded, and they are incorrectly reporting the CPU/GPU being used. Furthermore, the driver version belongs to the HD 2500/4000, and that is known to cause your _exact_ issue as described in #899.

I strongly suspect you have been scammed and have bought a computer with incorrect hardware.

**Comment by jellysquid3** [comment]
I would ask that you join [our Discord server](https://jellysquid.me/discord) so that we can investigate this further.

**Comment by GreenWolf142** [comment]
> @GreenWolf142 I think you have problems. Are you sure you actually have an i5-13400F and RTX 2080 Ti? Your drivers appear to be modded, and they are incorrectly reporting the CPU/GPU being used. Furthermore, the driver version belongs to the HD 2500/4000, and that is known to cause your _exact_ issue as described in #899.
> 
> I strongly suspect you have been scammed and have bought a computer with incorrect hardware.

Oh, God. I didn't see that coming. Because it appears the pc of mine having those things. Appears to be fast like it should be. But if i got scammed. or a system which already coded to else, and not to Windows. Then i guess i need to handle this situation, because it's my pc i bought it. If i get more people to help me. Then the Previous owner of this pc gets scared. And i have to turn to the police.
Thank y'all for the effort trying to help me, and telling these things. 
Man, i really have to learn about computers.

**Comment by GreenWolf142** [comment]
> > @GreenWolf142 I think you have problems. Are you sure you actually have an i5-13400F and RTX 2080 Ti? Your drivers appear to be modded, and they are incorrectly reporting the CPU/GPU being used. Furthermore, the driver version belongs to the HD 2500/4000, and that is known to cause your _exact_ issue as described in #899.
> > I strongly suspect you have been scammed and have bought a computer with incorrect hardware.
> 
> Oh, God. I didn't see that coming. Because it appears the pc of mine having those things. Appears to be fast like it should be. But if i got scammed. or a system which already coded to else, and not to Windows. Then i guess i need to handle this situation, because it's my pc i bought it. If i get more people to help me. Then the Previous owner of this pc gets scared. And i have to turn to the police. Thank y'all for the effort trying to help me, and telling these things. Man, i really have to learn about computers.

But actually. Which things i need to run sodium clearly?
