### ISSUE TITLE
Mineraft wont starding with sodium an i ont understand why

### ISSUE THREAD

**Issue by crimson6900** [jellysquid3/Sodium#1857]
### Version information

mc 1.19.2

### Expected Behavior

Minecraft shut stard

### Actual Behavior

M8necraft didnt start

### Reproduction Steps

nothing like that

### Java version

16

### CPU

amd 6300 six core

### GPU

amd gtx 1070

**Comment by jellysquid3** [comment]
You have provided zero useful information and have deliberately circumvented the issue template. We're not going to help people if they force us to pull teeth in order to get any information about the problem. Please go waste someone else's time.
