### ISSUE TITLE
Game can't start.

### ISSUE THREAD

**Issue by quocnam201010** [jellysquid3/Sodium#1860]
### Version information

mc1.19.4-0.4.10+build.24

### Reproduction Steps

1. Add Sodium to \mods folder
2. Launch the game
3. The game freezes while on the loading screen.

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11932236/latest.log)

### Additional information

System Information:
OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
Processor	Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz, 2601 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Hewlett-Packard 68ICF Ver. F.42, 5/20/2013

**Comment by quocnam201010** [comment]
misclicked
edit: not again

**Comment by bytzo** [comment]
It looks like you may be affected by issue #899. As noted by https://github.com/CaffeineMC/sodium-fabric/issues/899#issuecomment-1025203807, you will need to update your graphics drivers to version 15.33.53.5161, which can be downloaded [here](https://www.intel.com/content/www/us/en/download/18606/intel-graphics-driver-for-windows-15-33.html).
