### ISSUE TITLE
Smooth lighting off causes slabs, stairs, to be lit incorrectly.

### ISSUE THREAD

**Issue by EpiphanyThoughts** [jellysquid3/Sodium#1861]
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Expected Behavior

Faces of stairs and slabs that are disconnected from light should not appear directly lit.

### Actual Behavior

Faces of stairs and slabs that are disconnected from light appear directly lit.

### Reproduction Steps

1. Conditions: superflat world, doDaylightCycle = false, set time to night.
2. Set brightness to moody. (for visualization purposes, bug is still present at all gamma levels)
3. Disable smooth lighting in Video Settings > Quality.
4. Place a light source on the ground.
5. Directly above the light source, place a 5x5 square of top slabs.
6. The top side of the slabs will appear lit at the same light level as the bottom face.

If these steps are repeated with Sodium disabled, light will be appear appropriately obstructed.

### Java version

Java 17.0.1

### CPU

Intel Core i7-9700K

### GPU

NVIDIA GeForce GTX 1050 Ti

### Additional information

![bugged behavior](https://github.com/CaffeineMC/sodium-fabric/assets/69098169/38332e12-1e01-4d12-af43-cf73f45392c1)
![expected behavior](https://github.com/CaffeineMC/sodium-fabric/assets/69098169/46ae3e8e-caa0-4d50-bb4d-415fc5cb9b91)

This behavior is not present with Smooth Lighting enabled.

**Comment by Avakining** [comment]
Can confirm.

### Version Information
sodium-fabric-mc1.20-0.4.10+build.27

### Java Version
Oracle JDK 19

### CPU
Apple M1 Max (10 CPU Cores)

### GPU
Apple M1 Max (32 GPU Cores)

**Comment by Lolothepro** [comment]
fixed with Sodium 0.5.0
