### ISSUE TITLE
If my pc is just weak for sodium?

### ISSUE THREAD

**Issue by AlexCigarettaGeza** [jellysquid3/Sodium#1863]
Sodium freezes when 1 start but one times it's loads prefectly fine!

There is my latest log here:
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/11941374/latest.log)

**Comment by pajicadvance** [comment]
Your Intel GPU drivers are outdated and won't work with Sodium (see #899). If you have a dedicated GPU, then the game is not using it. Also, hacked clients are not supported.

**Comment by AlexCigarettaGeza** [comment]
> Your Intel GPU drivers are outdated and won't work with Sodium (see #899). If you have a dedicated GPU, then the game is not using it. Also, hacked clients are not supported.

My hacked client is disabled i crash when i use it. But damn in my country GPU drivers more than 100k money i only make 10k in a month.  But thanks

**Comment by AlexCigarettaGeza** [comment]
> > Your Intel GPU drivers are outdated and won't work with Sodium (see #899). If you have a dedicated GPU, then the game is not using it. Also, hacked clients are not supported.
> 
> My hacked client is disabled i crash when i use it. But damn in my country GPU drivers more than 100k money i only make 10k in a month. But thanks

This is how to lose a 400 days hardcore minecraft world.

**Comment by jellysquid3** [comment]
Then make a backup of your world if you are worried about losing it. The problem is not Sodium, it's your currently installed graphics drivers. Upgrading your graphics drivers **does not** require any hardware modifications and can be done for free. It's just a software update, and it comes from Intel (the official manufacturer) itself.

**Comment by AlexCigarettaGeza** [comment]
> It's says my videocard is already upgraded to the best
