### ISSUE TITLE
Arbitrary OutOfMemoryError

### ISSUE THREAD

**Issue by Ethan-Pixelate** [jellysquid3/Sodium#1864]
### Version information

MC 1.19.4, Sodium 0.4.10+build.24

### Reproduction Steps

1. Open Minecraft
2. Join a server (in my case Wynncraft)
3. Select a class and enter the world
4. The game crashes
5. Sometimes it won't immediately crash, in which case, keep playing
6. The game will crash after an arbitrary amount of time, either way, it's a crash for the same reason

Chunk Render Task Executor throws a java.lang.OutOfMemoryError, usually also causing the Java Runtime to throw a fatal error (EXCEPTION_ACCESS_VIOLATION)

### Crash Report file

Minecraft log/crash file can be found here: https://paste.ee/p/hyFuV

### Additional information

I am using the Fabulously Optimized modpack, and use this instance of MultiMC to play on the Wynncraft server, which does make use of a server-wise resource pack.

Full list of mods installed:
![image](https://github.com/CaffeineMC/sodium-fabric/assets/38443498/3fed191f-936f-4f79-9efb-ddcd18ee7f43)

This happens both with multi-threaded chunks set to 0 and 16.

**Comment by astridellensdottir** [comment]
please update your video drivers. you’re using version 511.65, which was released more than a year ago.

**Comment by hexadecimal233** [comment]
Xmx is set to 1024m, you sure you can run mc with only 1 gig ram?

**Comment by jellysquid3** [comment]
There is no indication of a memory leak in Sodium... You are simply running out of memory (probably because Xmx is set too low, or there is not available RAM in the system.) 

Maybe some other mod is causing that, but we can't help debug that.
