### ISSUE TITLE
Unexplainted Lag when creating Redstone Clocks in specific chunks

### ISSUE THREAD

**Issue by Xerpyy** [jellysquid3/Sodium#1865]
### Version information

mc1.20.1 fabric0.4.21 sodium0.4.10+build.27

### Expected Behavior

Redstone clocks like this shouldn't cause lag like this.

### Actual Behavior

https://github.com/CaffeineMC/sodium-fabric/assets/81948802/5557748f-1b03-4833-b943-0ac50432af29

Unexplained lag when building certain redstone clocks. (happens with observer clock as show in the video, but also with faster repeater clocks)
-This only happens in specific chunks around my base in multiplayer
-While the video shows a more modded game, i have attempted this on a fresh install of the game, with only sodium and fabric api installed.
-Logs do not show any sort of error when reproducing this

### Reproduction Steps

1. Create any sort of fast redstone clock. (Observer clock, 1 tick repeater clock)
2. Activate the clock

### Java version

jdk 17.0.4

### CPU

AMD FX(tm)-8350 Eight-Core Processor  4.00 GHz

### GPU

Radeon RX 570 Series

### Additional information

launcher used is MultiMC. Drivers are all up to date.

**Comment by Boobies** [comment]
Cannot reproduce. Are you only getting this behavior with Sodium? You seem to have a bunch of mods installed, at the very least Sodium, Iris, ImmediatelyFast, some culling mod. You also seem to be testing this on a Paper server. So at this point, the report is hard to take seriously.

**Comment by Altirix** [comment]
If you can still reproduce this on your machine you could try capturing a spark profile for the client when there is no clock and when the clock is running, that may give some info about what is going on. https://modrinth.com/mod/spark

**Comment by Felix14-v2** [comment]
You can also download part of the server world using [this tool](https://github.com/mircokroon/minecraft-world-downloader), check this behavior in singleplayer and upload your world here, so that other people can test it as well and possibly reproduce your issue.

**Comment by burgerindividual** [comment]
Does the same issue happen when you turn on "Always Defer Chunk Updates" in the performance tab of video settings? It seems like the issue here is probably chunk building taking a very long time on your system during chunk updates.

**Comment by jellysquid3** [comment]
This problem _should_ be solved with Sodium 0.5 so long as you enable the "Always Defer Chunk Updates" option. If you can still reproduce it, then please provide a copy of the save game you are using which is affected, and ask for this issue to be re-opened.
