### ISSUE TITLE
Input Lag (Input Delay) with Sodium even if VSYNC is disabled in NVIDIA and Sodium fully

### ISSUE THREAD

**Issue by kispintyi** [jellysquid3/Sodium#1866]
### Version information

mc1.20-0.4.10+build.27

### Expected Behavior

After a while (approximately 20 minutes) there is NO input lag and NO vsync in the game automatically

### Actual Behavior

After a while (approximately 20 minutes) there IS input lag AND vsync in the game automatically

### Reproduction Steps

1. Turn off VSYNC in NVIDIA
2. Restart PC
3. Start Minecraft with Sodium
4. Join a server
5. Play for approximately 20 minutes
6. Notice vsync halfly turning on and causing input lag

### Java version

Java 17.0.3

### CPU

Intel Core I5-10400F

### GPU

NVIDIA GeForce GTX 1650

### Additional information

Sometimes the Sodium settings just bug and if I enable VSYNC in the Sodium settings it doesn't work and my fps is still above 60+fps! (I have 60Hz)!
And if it doesn't have any input lag for some reason, I don't even know how I did that but then I have a small screen tearing!

**Comment by pajicadvance** [comment]
Resolved in a support thread on our Discord server ([link](https://discord.com/channels/602796788608401408/1125876979724468244/1126167161447125072))

> The problem is NOT anything to do with Sodium. We don't modify the game to enable V-Sync or change anything that would cause increased input-lag. More likely than not you are affected by NVIDIA driver bugs which we explain here: https://modrinth.com/mod/sodium#known-issues. Which, again, cannot be solved unless you use Prism Launcher. The Vanilla Launcher and the Lunar Client will both have severe issues.

**Comment by ZIDI228** [comment]
фикс фризов при прогрузке чанков поставьте в-синк в положение включено и вручную частоту кадров на 60, должно помочь. аналогично если 144 герц монитор то в-синк и 144 кадров вручную.

fix friezes when loading chunks, set v-sync to on and manually set the frame rate to 60, it should help. similarly, if the monitor is 144 hertz, then v-sync and 144 frames manually.

修复加载块时的条纹，将垂直同步设置为打开并手动将帧速率设置为 60，这应该会有所帮助。 同样，如果显示器为 144 赫兹，则手动进行垂直同步和 144 帧。

perbaiki friezes saat memuat potongan, setel v-sync ke aktif dan atur frame rate secara manual ke 60, itu akan membantu. sama halnya, jika monitor 144 hertz, maka v-sync dan 144 frame secara manual.

corrigez les frises lors du chargement de morceaux, activez v-sync et réglez manuellement la fréquence d'images sur 60, cela devrait aider. de même, si le moniteur est de 144 hertz, puis v-sync et 144 images manuellement.

corrija los frisos al cargar fragmentos, active v-sync y configure manualmente la velocidad de fotogramas en 60, debería ayudar. del mismo modo, si el monitor es de 144 hercios, entonces v-sync y 144 fotogramas manualmente.

**Comment by ZIDI228** [comment]
фикс фризов при прогрузке чанков поставьте в-синк в положение включено и вручную частоту кадров на 60, должно помочь. аналогично если 144 герц монитор то в-синк и 144 кадров вручную.

fix friezes when loading chunks, set v-sync to on and manually set the frame rate to 60, it should help. similarly, if the monitor is 144 hertz, then v-sync and 144 frames manually.

修复加载块时的条纹，将垂直同步设置为打开并手动将帧速率设置为 60，这应该会有所帮助。 同样，如果显示器为 144 赫兹，则手动进行垂直同步和 144 帧。

perbaiki friezes saat memuat potongan, setel v-sync ke aktif dan atur frame rate secara manual ke 60, itu akan membantu. sama halnya, jika monitor 144 hertz, maka v-sync dan 144 frame secara manual.

corrigez les frises lors du chargement de morceaux, activez v-sync et réglez manuellement la fréquence d'images sur 60, cela devrait aider. de même, si le moniteur est de 144 hertz, puis v-sync et 144 images manuellement.

corrija los frisos al cargar fragmentos, active v-sync y configure manualmente la velocidad de fotogramas en 60, debería ayudar. del mismo modo, si el monitor es de 144 hercios, entonces v-sync y 144 fotogramas manualmente.
