### ISSUE TITLE
Process exited with code -1

### ISSUE THREAD

**Issue by MorgasFishy** [jellysquid3/Sodium#1869]
### Version information

1.20.1

### Reproduction Steps

Crashes on start

### Crash Report file

[crash-2023-07-06_21.48.40-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/11971308/crash-2023-07-06_21.48.40-client.txt)

**Comment by Lolothepro** [comment]
```java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'chesttracker'!```
Install Whereisit

**Comment by MorgasFishy** [comment]
aight i deleted it and now it is launching but it crashes on the main menu

**Comment by MorgasFishy** [comment]
> `java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'chesttracker'!` Install Whereisit

thanks helped
