### ISSUE TITLE
1.20/dev: Fluids are not rendered correctly

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#1870]
### Version information

***

### Expected Behavior

![image](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/7940913a-c94a-4861-9ac6-fe27c26f73e0)

### Actual Behavior

![image](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/403cb936-7d8a-4789-adb5-b2185856c716)

### Reproduction Steps

Easily reproducible in a cold biome.

### Java version

Java 17

### CPU

Ryzen 3600

### GPU

GTX 1070

**Comment by Grayray75** [comment]
Can confirm that this issue exists since 1.20 and also occurs with other blocks like beacons.
