### ISSUE TITLE
Not enough fps on a powerful computer

### ISSUE THREAD

**Issue by Vauler007** [jellysquid3/Sodium#1877]
### Version information

fabric 1.19.4

### Expected Behavior

Good afternoon! I ran into the problem of low fps on fabric with the sodium mod for optimization. On a powerful computer, fps usually outputs 600-1000. But I have some kind of problem and gives up to 100 fps. How to solve this?

### Actual Behavior

![2023-07-11_16 42 16](https://github.com/CaffeineMC/sodium-fabric/assets/134651594/4afe5cbf-88c6-41ab-9765-d58fb629dc2f)

### Reproduction Steps

I have not met such cases.

### Java version

Java 17

### CPU

AMD Ryzen 9 5950x 16-Core Processor (32 CPUs), ~3.4Ghz

### GPU

NVIDIA Geforce RTX 3080

### Additional information

![Снимок экрана 2023-07-11 164702](https://github.com/CaffeineMC/sodium-fabric/assets/134651594/b00c0787-757c-4490-82ac-38bfb50f7ee3)

Mods that I use.

**Comment by Fnige** [comment]
Im guessing you might be affected by #1830

**Comment by pajicadvance** [comment]
Deleted my previous comment because it wasn't correct. Yes, this is most likely #1830 , and changes to address this performance loss will be in the next release of Sodium.

**Comment by Vauler007** [comment]
> Удалил мой предыдущий комментарий, потому что он был неправильным. Да, это, скорее всего, #1830 , и изменения, направленные на устранение этой потери производительности, будут в следующем выпуске Sodium.

Получается только ждать когда это исправят?

**Comment by Fnige** [comment]
> Получается только ждать когда это исправят?

Надеемся, что это будет исправлено, но это может не быть возвращено
(It'll hopefully get fixed, but it might not get backported)

**Comment by Vauler007** [comment]
Thanks! The solution to download Prism Laucnher helped me
![2023-07-11_19 25 14](https://github.com/CaffeineMC/sodium-fabric/assets/134651594/977fb9ab-c6fc-4b78-acd6-e2c7b5a35adc)

**Comment by Felix14-v2** [comment]
> It'll hopefully get fixed, but it might not get backported

Iirc, CaffeineMC backports critical fixes, isn't this one critical enough?
