### ISSUE TITLE
Freezes during the fast movements in the game world

### ISSUE THREAD

**Issue by TwinFacedJanus** [jellysquid3/Sodium#1878]
### Version information

mc1.20-0.4.10+build.27

### Expected Behavior

Sodium is about to make the game run with much less effort to my iGPU, but it in fact causes short freezes.

### Actual Behavior

The game runs smoothly until I try to travel anywhere away from the nearest chunks, especially when I run by foot/on the horseback/in the minecart. Once I leave loaded chunks, the game starts skipping several frames every 3-4 seconds. It is not critical, but annoying. At the moment when the bug occurs the GPU load surges from 50-60ish to 100%, and then drops back to normal.

The bug persists on Intel Iris Xe graphics, Core i7-1260P CPU (laptop). Not a throttle, CPU is not undervolted or screwed in any other way. With Sodium disabled game runs at smooth 60FPS. Did not test it on a dGPU though.

Ready to send any log files if needed. Can also test the performance on dGPU.

### Reproduction Steps

1.Load any world
2. Run/Ride/Fly/Move rapidly into one direction
3. Then the mentioned freezes kick in.

### Java version

17.0.3.0

### CPU

Core i7-1260P

### GPU

Intel Iris Xe (96EU)

**Comment by Noryea** [comment]
Hello. I fixed this issue successfully by installing a mod called [ThreadTweak](https://modrinth.com/mod/threadtweak) and lowering the integrated server priority in its config. Could you try it on your laptop?

**Comment by jellysquid3** [comment]
Does this problem still occur with [Sodium 0.5.2](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.2)? There were a _lot_ of changes related to improving frame times...

**Comment by jellysquid3** [comment]
There is no way for this issue to be resolved as there is no specific reproduction steps to cause the problem (i.e. it's just a general complaint about performance, which is completely unworkable as an issue.)  If you still need help, then please join the [community Discord server](https://caffeinemc.net/discord) for support.
