### ISSUE TITLE
Rare/inconsistent lighting bugs in the 1.20 release

### ISSUE THREAD

**Issue by IMS212** [jellysquid3/Sodium#1881]
Before https://github.com/CaffeineMC/sodium-fabric/commit/f041f7ccba91e755858bbd4ae127e16f054f08a7#diff-1750fdaab4631fe6413eff2937cbf16223a0a6aab92faf1fca69fda49fc2fd48, this is still inconsistent, but way easier to find. After this commit, it became very rare, but supposedly there are still reports of it.

**Comment by douira** [comment]
Example of a section that is missing light. The section above is not missing light. From [this video](https://youtu.be/q9ONodtzAwU?t=863), on 1.20

<img width="1280" alt="Screenshot 2023-07-13 at 02 03 26" src="https://github.com/CaffeineMC/sodium-fabric/assets/17120022/4ca0d66e-d0ff-4776-998e-091518f8b61b">

**Comment by jellysquid3** [comment]
Possibly fixed with  5911a33?

**Comment by jellysquid3** [comment]
I'm pretty sure this is fixed, but can't be sure given we never had clear steps to reproduce it. Some people which used an earlier revision of Sodium (for testing the NVIDIA driver workarounds) were experiencing this bug, but those people reported that it stopped happening in Sodium 0.5.0-beta2.

Let's assume this is fixed given we haven't seen any user reports in the beta builds, and if we find out it's still happening after release, we'll re-open this.
