### ISSUE TITLE
Sodium not working

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#1882]
### Version information

mc1.20-0.4.10+build.27

### Expected Behavior

It should have increased the performance od the game

### Actual Behavior

The performance dropped and frequent lag spikes started to occur with stuttering 

### Reproduction Steps

Install it and check

### Java version

Java 16

### CPU

AMD Ryzen 3750H

### GPU

Nvidia GTX 1650

**Comment by Timolino456** [comment]
Sounds like a duplicate of #1830. It's NVIDIA's fault and you'll have to wait for the next version of Sodium that will have a workaround for this.

**Comment by jellysquid3** [comment]
This is not a support forum (use the [Discord server](https://caffeinemc.net/discord) for that).
