### ISSUE TITLE
A strange request

### ISSUE THREAD

**Issue by chimericdream** [jellysquid3/Sodium#1883]
**Is your feature request related to a problem? Please describe.**
As I understand it, someone uploaded an unauthorized copy of the `mc1.20-0.4.10+build.27` build to CurseForge a little while back. CF removed it and blocked future uploads of the file, as they should. However, this is now causing any modpacks which include the jar as part of their zip to be forced into manual moderation.

**Describe the solution you'd like**
I believe if a new version was pushed (with literally any change, as long as it was enough to make the SHA of the file different), that would be sufficient to stop the rejection+appeal+human review loop.

**Describe alternatives you've considered**
It's obviously a minor annoyance, especially if you are already planning another release in the near future. The alternative is just to deal with CF's system for now and accept that modpacks may take up to a couple of days to get approved instead of minutes or hours.

**Additional context**
CF is frustrating, and I can't wait until Modrinth has their own launcher to provide some real competition!

**Comment by Felix14-v2** [comment]
> CF is frustrating, and I can't wait until Modrinth has their own launcher to provide some real competition!

You already can download Modrinth App from their discord, by the way.

**Comment by Fnige** [comment]
Judging by [this](https://discord.com/channels/602796788608401408/651120262129123330/1125734849551020063), the file was uploaded by curseforge themselves to fix another issue that was popping up so uhhhhhh :catstare:

This is a major curseforge moment lol

**Comment by IMS212** [comment]
CurseForge is currently stuck in longer moderation for other reasons, this is not explicitly caused by Sodium.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/31803019/1e3f15aa-b414-41f0-9e0f-2d5b7798a880)

**Comment by chimericdream** [comment]
> CurseForge is currently stuck in longer moderation for other reasons, this is not explicitly caused by Sodium.

The current state, maybe, but the issue I'm experiencing has been going on for a couple of weeks. According to CF support, every zip file I upload which includes that specific jar is guaranteed to be rejected and require appeal+manual review.

> You already can download Modrinth App from their discord, by the way.

This is awesome, thank you!

> This is a major curseforge moment lol

Yep.

**Comment by chimericdream** [comment]
Like I said in the original post, this is more an annoyance than anything. So if the process of releasing a new version _just_ for this is not worth the effort, I completely understand. But it never hurts to ask. :-)

**Comment by tomwolfgang** [comment]
Hi, sorry for the bad experience.
CF is improving malware detection, so relatively new authors go into the manual moderation queue.

Soon this will return to the normal times.

Regarding Sodium, if you just place the mod under the mods directory and export via the CF app, it should be fine.
Otherwise, if you aren't using the app, just add the sodium project id to the manifest.json.

**Comment by chimericdream** [comment]
My project is 6.5 years old, so I don't think that's the reason it is going into moderation. I am uploading it exactly as you describe, but because it is a file version that was uploaded then removed from CF, it is automatically rejected. I then have to go through appeal+manual review. According to their support, I can expect this to happen 100% of the time as long as this specific version of Sodium is part of my pack.

This is the error I have gotten for the last several uploads of my pack over the past few weeks:

> The status of the file ... has been changed to Rejected
> 
> Notes:
> The following file versions have been removed from CurseForge:
>     overrides/mods/sodium-fabric-mc1.20-0.4.10+build.27.jar
> 
> The modpack will not be approved until these files are replaced with versions that are currently available.
> If you have any questions please contact our support team https://support.curseforge.com/.

To be clear, I am not placing _any_ blame for this on Sodium or the maintainers here. This is just another item in the "why CF is annoying" column.

**Comment by tomwolfgang** [comment]
I see - I'm from CF, can you please send the url to your project, i'll double check it.

Thanks

**Comment by tomwolfgang** [comment]
@chimericdream looks like you've got sodium added to the overrides folder - that won't work.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/1466106/94af31f0-1b47-4e74-b981-c918a515722f)

If you are exporting your modpack from the CurseForge app - try this:
- open your modpack in the app
- go to the mods folder and cut sodium and paste it outside of the mods folder (via Finder/Windows explorer)
- then paste it back in - it should auto detect it
- next - export again, this time, it should add sodium to the manifest.json file

![image](https://github.com/CaffeineMC/sodium-fabric/assets/1466106/7cccb2cb-4e88-4d4a-b84f-eda188418746)


Let me know if you just want me to try and fix and resubmit the modpack for you.

**Comment by chimericdream** [comment]
I can do that. For whatever reason, I could swear that when I tried submitting it before with Sodium in the manifest, it got rejected. Did the file get re-uploaded or restored within the last few weeks? Maybe that's the issue in my case?

**Comment by tomwolfgang** [comment]
Yes, could be the issue - we uploaded it + archived it on the 2nd of July.
We had people uploading sodium into non-sodium projects which caused confusion and support tickets.

**Comment by chimericdream** [comment]
Got it. That matches up with when I started having these issues. Thank you for your help and patience! I'll be re-submitting my pack today with an updated manifest.

(Side note: this was, ironically, _way_ faster than CurseForge's official support ticket process. I don't know if you're part of the customer service team or not, but either way I greatly appreciate your help.)

**Comment by tomwolfgang** [comment]
Sure - feel free to tag me if you have other issues or try our discord server https://discord.gg/4E4bJC2j for faster support.

I'll be on the lookout for your modpack.
