### ISSUE TITLE
sodium is failing

### ISSUE THREAD

**Issue by SirKemmy** [jellysquid3/Sodium#1884]
### Version information

sodium-fabric-mc1.16.5-0.2.0+build.4.jar

### Reproduction Steps

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12061821/latest.log)

### Crash Report file

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12061822/latest.log)

**Comment by pajicadvance** [comment]
The latest Sodium version on CurseForge is outdated and only works in Minecraft 1.16.5. You need to download Sodium for your game version manually from Modrinth: https://modrinth.com/mod/sodium and place the mod in your mods folder. Also, make sure that the rest of your mods are up to date.
