### ISSUE TITLE
Trading with villagers cause crash

### ISSUE THREAD

**Issue by Donpolloteamo** [jellysquid3/Sodium#1886]
### Version information

mc1.20-0.4.10+build.27

### Reproduction Steps

1.I right click on a villager
2:Minecraft Crash

### Crash Report file

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-07-16 14:07:18
Description: Unexpected error

java.lang.IllegalAccessError: class net.minecraft.class_1728 tried to access private field net.minecraft.class_1297.field_6002 (net.minecraft.class_1728 and net.minecraft.class_1297 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57175e74)
	at net.minecraft.class_1728.handler$den000$retraining$retrainingConstructor(class_1728.java:1026)
	at net.minecraft.class_1728.<init>(class_1728.java:57)
	at net.minecraft.class_1728.<init>(class_1728.java:37)
	at net.minecraft.class_3917.method_17434(class_3917.java:60)
	at net.minecraft.class_3929$class_3930.method_17543(class_3929.java:62)
	at net.minecraft.class_3929.method_17541(class_3929.java:51)
	at net.minecraft.class_634.method_17587(class_634.java:1197)
	at net.minecraft.class_3944.method_17591(class_3944.java:37)
	at net.minecraft.class_3944.method_11054(class_3944.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1728.handler$den000$retraining$retrainingConstructor(class_1728.java:1026)
	at net.minecraft.class_1728.<init>(class_1728.java:57)
	at net.minecraft.class_1728.<init>(class_1728.java:37)
	at net.minecraft.class_3917.method_17434(class_3917.java:60)
	at net.minecraft.class_3929$class_3930.method_17543(class_3929.java:62)
	at net.minecraft.class_3929.method_17541(class_3929.java:51)
	at net.minecraft.class_634.method_17587(class_634.java:1197)
	at net.minecraft.class_3944.method_17591(class_3944.java:37)
	at net.minecraft.class_3944.method_11054(class_3944.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
Mixins in Stacktrace:
	net.minecraft.class_1728:
		com.mrbysco.retraining.mixin.MerchantMenuAccessor (retraining.mixins.json)
		com.mrbysco.retraining.mixin.MerchantMenuMixin (retraining.mixins.json)
	net.minecraft.class_634:
		com.glisco.deathlog.mixin.ClientPlayNetworkHandlerMixin (deathlog.mixins.json)
		net.coderbot.iris.mixin.MixinClientPacketListener (mixins.iris.json)
		com.aizistral.nochatreports.common.mixins.client.MixinClientPacketListener (mixins/common/nochatreports.mixins.json)
		net.fabricmc.fabric.mixin.command.client.ClientPlayNetworkHandlerMixin (fabric-command-api-v2.client.mixins.json)
		carpet.mixins.ClientPacketListener_clientCommandMixin (carpet.mixins.json)
		net.blay09.mods.balm.mixin.ClientPacketListenerMixin (balm.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.ClientPlayNetworkHandlerMixin (fabric-lifecycle-events-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.ClientPlayNetworkHandlerMixin (fabric-networking-api-v1.client.mixins.json)
		carpet.mixins.ClientPacketListener_customPacketsMixin (carpet.mixins.json)
		net.fabricmc.fabric.mixin.client.message.ClientPlayNetworkHandlerMixin (fabric-message-api-v1.client.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.chunk_rendering.MixinClientPlayNetworkHandler (sodium.mixins.json)

-- Affected level --
Details:
	All players: 1 total; [class_746['Rodokxis27'/261, l='ClientLevel', x=-3407.70, y=68.94, z=524.61]]
	Chunk stats: 1024, 150
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,72,80), Section: (at 0,8,0 in 1,4,5; chunk contains blocks 16,-64,80 to 31,319,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 277944 game time, 415840 day time
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace:
	net.minecraft.class_638:
		me.jellysquid.mods.sodium.mixin.features.fast_biome_colors.MixinClientWorld (sodium.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.ClientWorldMixin (fabric-lifecycle-events-v1.client.mixins.json)
		me.jellysquid.mods.lithium.mixin.chunk.entity_class_groups.ClientWorldMixin (lithium.mixins.json)
		carpet.mixins.ClientLevel_tickSpeedMixin (carpet.mixins.json)
		net.coderbot.iris.mixin.vertices.block_rendering.MixinClientLevel (mixins.iris.vertexformat.json)
		dev.lambdaurora.lambdynlights.mixin.ClientWorldMixin (lambdynlights.mixins.json)
		com.natamus.collective.fabric.mixin.ClientLevelMixin (collective-fabric.mixins.json)
		me.jellysquid.mods.sodium.mixin.features.chunk_rendering.MixinClientWorld (sodium.mixins.json)
	net.minecraft.class_310:
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		dev.lambdaurora.lambdynlights.mixin.MinecraftClientMixin (lambdynlights.mixins.json)
		net.blay09.mods.balm.mixin.MinecraftMixin (balm.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinResourceReload (entity_texture_features-common.mixins.json)
		io.grayray75.fabric.fpsdisplay.mixin.MinecraftClientMixin (fpsdisplay.mixins.json)
		shcm.shsupercm.fabric.citresewn.defaults.mixin.types.enchantment.MinecraftClientMixin (citresewn-defaults.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		com.natamus.collective.fabric.mixin.MinecraftMixin (collective-fabric.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientAccessor (languagereload.mixins.json)
		jerozgen.languagereload.mixin.MinecraftClientMixin (languagereload.mixins.json)
		io.wispforest.owo.mixin.MinecraftClientMixin (owo.mixins.json)
		dev.lambdaurora.spruceui.mixin.MinecraftClientMixin (spruceui.mixins.json)
		dev.isxander.yacl3.mixin.MinecraftMixin (yacl.mixins.json)
		me.jellysquid.mods.sodium.mixin.core.MixinMinecraftClient (sodium.mixins.json)
		traben.entity_model_features.mixin.accessor.MinecraftClientAccessor (entity_model_features-common.mixins.json)
		carpet.mixins.Minecraft_pausedShakeMixin (carpet.mixins.json)
		squeek.appleskin.mixin.MinecraftClientMixin (appleskin.mixins.json)
		com.aizistral.nochatreports.common.mixins.client.MixinMinecraft (mixins/common/nochatreports.mixins.json)
		traben.entity_model_features.mixin.MixinResourceReload (entity_model_features-common.mixins.json)
		fuzs.forgeconfigapiport.mixin.client.MinecraftMixin (forgeconfigapiport.common.mixins.json)
		io.wispforest.owo.mixin.ui.MinecraftClientMixin (owo.mixins.json)
		net.uku3lig.betterhurtcam.mc120.mixin.MixinMinecraftClient (betterhurtcam120.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Keybinds (mixins.iris.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		com.aizistral.nochatreports.fabric.mixins.client.MixinMinecraft (mixins/fabric/nochatreports-fabric.mixins.json)
		traben.entity_texture_features.mixin.reloading.MixinMinecraftClient (entity_texture_features-common.mixins.json)
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		com.teamderpy.shouldersurfing.mixins.MixinMinecraft (shouldersurfing.mixins.json)
		carpet.mixins.MinecraftMixin (carpet.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_Images (mixins.iris.json)
		me.jellysquid.mods.sodium.mixin.workarounds.issue1486.MixinMinecraftClient (sodium.mixins.json)
		net.coderbot.iris.mixin.MixinMinecraft_PipelineManagement (mixins.iris.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Icons v.1.8.zip, file/EmbellishedStone-1.19-1.0.0, file/Fancy Glint for 1.19.zip, file/Fancy+Boss+Bars+v0.1.1, file/griddy-villagers, file/EsteSearch, file/1-20-clear-gui-dark.zip, continuity:glass_pane_culling_fix, continuity:default, file/Exclamation Powder Snow.zip, file/Chat+V.1.1.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 358859416 bytes (342 MiB) / 939524096 bytes (896 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Athlon Gold 3150U with Radeon Graphics     
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 2.39
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon(TM) Vega 3 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x15d8
	Graphics card #0 versionInfo: DriverVersion=31.0.14057.5006
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 13313.23
	Virtual memory used (MB): 6855.85
	Swap memory total (MB): 7226.40
	Swap memory used (MB): 283.13
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advancementinfo: AdvancementInfo 1.20-fabric0.83.0-1.4
		animatica: Animatica 0.6+1.20
		appleskin: AppleSkin 2.5.0+mc1.20
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
		balm-fabric: Balm 7.0.4
		betterf3: BetterF3 7.0.0
		betterhurtcam: BetterHurtCam 1.5.5
			betterhurtcam-mc120: BetterHurtCam+mc1.20 1.5.5
		carpet: Carpet Mod 1.4.112+v230608
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		collective: Collective 6.62
		continuity: Continuity 3.0.0-beta.2+1.20
		cull-less-leaves: Cull Less Leaves 1.2.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		dcch: DCCH 2.0+1.17
		deathlog: DeathLog 0.3.2+1.20
		enhancedblockentities: Enhanced Block Entities 0.9+1.20
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.7
			spruceui: SpruceUI 5.0.0+1.20
		entity_model_features: Entity Model Features 0.2.11
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		extendedbonemeal: Extended Bone Meal 3.0
		fabric-api: Fabric API 0.84.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b77
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d77
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabricloader: Fabric Loader 0.14.21
		forgeconfigapiport: Forge Config API Port 8.0.0
		fpsdisplay: FPS-Display 1.5.0+1.20
		indium: Indium 1.0.21+mc1.20.1
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.3.1+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
		languagereload: Language Reload 1.5.8+1.20.1
		lithium: Lithium 0.11.2
		logical_zoom: Logical Zoom 0.0.20
		minecraft: Minecraft 1.20.1
		mixintrace: MixinTrace 1.1.1+1.17
		modmenu: Mod Menu 7.1.0
		morechathistory: MoreChatHistory 1.1.1
		netherportalfix: NetherPortalFix 13.0.0
		no-resource-pack-warnings: No Resource Pack Warnings 1.3.0
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		pizza_napolitana: Pizza Napolitana 1.0.0
		retraining: Retraining 1.2.0
		shouldersurfing: Shoulder Surfing Reloaded 2.4.1
		shulkerboxtooltip: Shulker Box Tooltip 4.0.3+1.20
		sodium: Sodium 0.4.10+build.27
		ukulib: ukulib 0.7.0+1.20
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.0.3+1.20
			com_twelvemonkeys_common_common-image: common-image 3.9.4
			com_twelvemonkeys_common_common-io: common-io 3.9.4
			com_twelvemonkeys_common_common-lang: common-lang 3.9.4
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
	Loaded Shaderpack: (off)
	NEC status: No NEC detected
	Launched Version: fabric-loader-0.14.21-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context 23.5.2.230523, ATI Technologies Inc.
	Window size: 1360x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Icons v.1.8.zip, file/EmbellishedStone-1.19-1.0.0, file/Fancy Glint for 1.19.zip, file/Fancy+Boss+Bars+v0.1.1, file/griddy-villagers, file/EsteSearch, file/1-20-clear-gui-dark.zip, continuity:glass_pane_culling_fix, continuity:default, file/Exclamation Powder Snow.zip, file/Chat+V.1.1.zip
	Current Language: en_us
	CPU: 4x AMD Athlon Gold 3150U with Radeon Graphics

**Comment by pajicadvance** [comment]
Sodium does not modify anything regarding villagers. From the log, the possible cause of the crash is the mod "Retraining".

**Comment by Donpolloteamo** [comment]
Thanks, I didn't know that about sodium. sorry
