### ISSUE TITLE
Texture glitch with Faithless

### ISSUE THREAD

**Issue by SamuelUlep** [jellysquid3/Sodium#1888]
### Version information

sodium-fabric-mc1.20-0.4.10+build.27

### Expected Behavior

Texture works as normal without sodium.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/129558275/ca226f9b-7c2b-4605-89d0-34174ae32621)

### Actual Behavior

Texture abnormality with default settings of sodium.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/129558275/5811d927-8786-45a8-b0f8-3e1f54444a00)

### Reproduction Steps

1. Install Fabric (0.85.0-1.20.1)
2. Install Sodium in mods folder
3. Install [Faithless 1.20](https://www.curseforge.com/minecraft/texture-packs/faithless)
4. Look at melon and pumpkin blocks, and endstone

### Java version

java 18

### CPU

Intel i7-10750H

### GPU

Nvidia GeForce GTX 1650 Ti

### Additional information

From my game play I have observed that this happens only with melons, pumpkins and endstone. It used to also occur with some of the leaves with cherry trees but it seems to be gone after updating minecraft version and mods installed from 1.20 to 1.20.1.

**Comment by PepperCode1** [comment]
Faithless replaces core shaders, which is not supported by Sodium.

**Comment by SamuelUlep** [comment]
Found the fix, joining their [discord](https://linktr.ee/stitch.sprites) server, they specifically have a patch that fixes the texture glitch and texture pack glitch with other mods too.
