### ISSUE TITLE
Horizontal Line Rendering Artifacts when facing 0.0 Yaw 

### ISSUE THREAD

**Issue by Hi30MC** [jellysquid3/Sodium#1889]
### Version information

0.4.10+build27

### Expected Behavior

When facing 0.0 yaw, no rendering artifacts should be present when moving or changing pitch.

https://github.com/CaffeineMC/sodium-fabric/assets/63116788/20d69a66-55d4-4ebc-82c1-7deba51c6459

### Actual Behavior

When facing 0.0 yaw, horizontal lines are present when moving or changing pitch, not only black, but negating any color(s) present.

https://github.com/CaffeineMC/sodium-fabric/assets/63116788/7359e08a-6367-4218-aca8-c9a7aea9db25

### Reproduction Steps

1. Generate a "Redstone Ready" superflat world (not needed, but easier to see the effect of the bug)
2. Either manually or with commands, rotate the player to face 0.0 Yaw (in the video, I used Tweakeroo snapAim to do this)
3. Move forwards and backwards, or move the player's camera up and down without changing Yaw

Hopefully, one should be seeing rendering artifacts.

### Java version

17.0.7 64bit

### CPU

AMD Ryzen 5 5500

### GPU

NVIDIA GeForce GTX 1050 Ti

### Additional information

This bug, as far as I can tell, has been persistent since 1.19.3, however further testing should be performed to verify this.

While running Sodium, I am also running Lithium, Iris, Sodium Extra, and Reese's Sodium Options, but removing these mods does not affect the rendering artifact.

**Comment by jellysquid3** [comment]
This is not a problem with Sodium... Likely, you have enabled some setting in the NVIDIA Control Panel related to how texturing works, and that has broken Minecraft.

There should be an option to reset everything to default in the NVIDIA Control Panel under "Manage 3D Settings > Reset Defaults".

**Comment by Hi30MC** [comment]
After resetting driver settings, the issue persists, and the issue is only present when running sodium, and is not present when running vanilla Minecraft. Are there any other ways to fix the issue?
