### ISSUE TITLE
Whenever I switch to full screen, my game caps at 30 or 60 (cant tell) and has weird coloring. This happened when i updated my nvidia drivers

### ISSUE THREAD

**Issue by shpqt** [jellysquid3/Sodium#1890]
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24

### Expected Behavior

I expected my game to load in, when good coloring and 400+ frames, but instead it acts like i have vsync on and caps at that framerate.

### Actual Behavior

my game capped at 60 frames, and did not work in full screen

### Reproduction Steps

Updated my nvidia drivers

this issue happens on sodium, and vanilla, but it doesnt happen on other optimizers like optifine

### Java version

Java 17.0.6

### CPU

Intel Core I7 12 gen

### GPU

Rtx 3090TI

### Additional information

Whenever I tab out of the full screen on java, the screen goes black for a second

**Comment by shpqt** [comment]
Really weird thing that happens to me. And only happens in full screen

**Comment by Felix14-v2** [comment]
Any screenshots/photos and logs?

**Comment by pajicadvance** [comment]
This is most likely a driver issue. The current version of Sodium has problems with the latest versions of the NVIDIA driver. Right now we recommend using Prism Launcher or similar to work around the issue. As for the color issue, NVIDIA added color filters that can be applied in game in recent updates, so maybe you accidentally enabled that.
