### ISSUE TITLE
Isometric Renders issue w/ Sodium

### ISSUE THREAD

**Issue by RisPNG** [jellysquid3/Sodium#1892]
### Version information

mc1.20-0.4.10

### Expected Behavior

A readable settings' screen:
![javaw_YqGEchnmeq](https://github.com/CaffeineMC/sodium-fabric/assets/4275248/9fe3573f-4b32-4bc5-b0ae-2b6f63fb9500)

### Actual Behavior

A non-readable settings' screen:
![explorer_MsF6vaLOT9](https://github.com/CaffeineMC/sodium-fabric/assets/4275248/e7ff4ed8-7957-460b-88e0-5362d2c2bc29)

### Reproduction Steps

Have both Isometric Renders and Sodium installed.

### Java version

Java 17.0.3 64bit

### CPU

8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz

### GPU

GeForce GTX 1650 with Max-Q Design/PCIe/SSE2 3.2.0 NVIDIA 536.67

### Additional information

I originally posted this on Isometric Renders repository because I think it'll be easier for them to fix this incompatibility. I'm crossposting here just to let you know.

Original Post: https://github.com/gliscowo/isometric-renders/issues/71#issue-1812917091

**Comment by Noryea** [comment]
[1873-merge](https://github.com/CaffeineMC/sodium-fabric/pull/1873) fixed this bug, so it will not happen in 0.5

**Comment by RisPNG** [comment]
> [1873-merge](https://github.com/CaffeineMC/sodium-fabric/pull/1873) fixed this bug, so it will not happen in 0.5

Oh thank you for letting me know, I tried searching for Isometric Renders in the issues but couldn't find it for some reason. I should've widen my search more. Closed.
