### ISSUE TITLE
All I see instead of letters is a box. Words made of empty boxes.

### ISSUE THREAD

**Issue by CrestOTH** [jellysquid3/Sodium#1893]
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24

### Expected Behavior

I intended to launch the game and see it in English.

### Actual Behavior

Everything is made of the box language. As in if someone tried to replace every letter with an emoji, but Minecraft doesn't load emojis. 
![image](https://github.com/CaffeineMC/sodium-fabric/assets/140032137/7d5b721f-5189-4459-91f3-38f5437243e0)

### Reproduction Steps

Put sodium in the mods folder, and launch the game. I can not think of any other thing that could cause this. I tested every other mod individually.

### Java version

17

### CPU

AMD Ryzen 5 3600 6-Core Processor, 3600 Mhz, 6 Core(s), 12 Logical Processor(s)

### GPU

NVIDIA Gefore RTX 2060

**Comment by pajicadvance** [comment]
Please upload your client log, it can be found at `.minecraft/logs/latest.log`.

**Comment by astridellensdottir** [comment]
this looks like sodium+iris without indium installed. do you have indium installed?
