### ISSUE TITLE
Freezes during the fast movements

### ISSUE THREAD

**Issue by majklosik** [jellysquid3/Sodium#1895]
### Version information

sodium-fabric-mc1.19.4-0.4.10+build.24

### Expected Behavior

I expect that game should run smoothly cuz i average about 400 fps and it still is freezing and causing some lags

### Actual Behavior

So i switched to sodium yesterday and thats when the lags started occurring. I think its my gpu cuz it randomly goes up to 100% when im playing and doing something fast especially when playing crystal pvp and placing crystals and respawn anchors i even have clips of it happening that i can send.

### Reproduction Steps

1. Playing crystal pvp as usual
2. Starts to place crystals / Anchors fast
3. Game starts freezing and gpu usage starts increasing

### Java version

17.0.3

### CPU

12x Amd Ryzen 5 2600 six core processor

### GPU

Radeon RX 580 Series

### Additional information

Here are some clips
1. U can see here that even if i am just spectating it is still happening. Right after he blew the anchor u can see the lag even tho my fps are stable https://medal.tv/games/minecraft/clips/1kyBKpRDBLKSbR/d1337eew47jk?invite=cr-MSxNa2UsMTg1MTc2MzkwLA
2. Here u can see the gpu usage going high. https://medal.tv/games/minecraft/clips/1kywqeW7Xau0Zh/d1337M1oJMO9?invite=cr-MSxOWE8sMTg1MTc2MzkwLA

Its not that noticable from those clips cuz they are in 60 fps but i normally play on 144 hz so i can see the freezes very clearly while playing.
I didnt have this problem while i was playing on optifine so i dont think its bc of my pc or something

**Comment by majklosik** [comment]
I know that there is already one issue like this but that guy is using integrated gpu so i thought it would make a difference

**Comment by majklosik** [comment]
![image](https://github.com/CaffeineMC/sodium-fabric/assets/138534216/832a007e-adca-49a2-8683-566804690e04)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/138534216/cc769423-9f68-4b3f-b9a7-a8d2a3a5ee8b)
Here are my mods

**Comment by Felix14-v2** [comment]
> but i normally play on 144 hz so i can see the freezes very clearly while playing

You can record demo with Alt+F3 opened to make these lag spikes noticeable. Also I recommend you run such tests without any other mods.

**Comment by majklosik** [comment]
> ord demo with Alt+F3

Okay ill try

**Comment by majklosik** [comment]
> > but i normally play on 144 hz so i can see the freezes very clearly while playing
> 
> You can record demo with Alt+F3 opened to make these lag spikes noticeable. Also I recommend you run such tests without any other mods.

https://medal.tv/games/minecraft/clips/1kEKYT-C6_jbcz/d1337H1G0WiY?invite=cr-MSxmSHEsMTg1MTc2MzkwLA
Here is new clip with the demo now ill try if its happening if im using only sodium mod

**Comment by jellysquid3** [comment]
Try changing this setting and see if it helps:
Video Settings > Performance > Always Defer Chunk Updates

**Comment by majklosik** [comment]
https://medal.tv/games/minecraft/clips/1kERP58atiNna1/d1337nCA8h7H?invite=cr-MSxtbHYsMTg1MTc2MzkwLA
Still happening with only these mods 
![image](https://github.com/CaffeineMC/sodium-fabric/assets/138534216/a2d8d35a-4408-4db3-9d3e-7594ed8a7092)

**Comment by majklosik** [comment]
Ok ill try that

**Comment by majklosik** [comment]
Do i turn it on or off ?

**Comment by majklosik** [comment]
I turned it on and its not lagging anymore tysm for helping!
