### ISSUE TITLE
"Always Defer Chunk Updates" should be enabled by default

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#1899]
This is the default in Minecraft 1.19+ and a lot of players are complaining about the micro-stutter caused by placing blocks. Enabling this should be fairly safe, since nobody really complains about it in vanilla.

**Comment by jellysquid3** [comment]
This is slightly annoying, because the configuration file has no concept of "user left this option at default", so we have to find a way to update the option for existing config files.

**Comment by Noryea** [comment]
> This is slightly annoying, because the configuration file has no concept of "user left this option at default", so we have to find a way to update the option for existing config files.

~~Just change the name of this option to a more technical-like one such as "Allow Visual Delay", so the configuration will automatically abandon "Always Defer Chunk Updates" and enable "Allow Visual Delay" by default~~

**Comment by mrjasonn** [comment]
> This is the default in Minecraft 1.19+ and a lot of players are complaining about the micro-stutter caused by placing blocks. Enabling this should be fairly safe, since nobody really complains about it in vanilla.

Is this basically similar to how the threaded chunk builder is in vanilla? @jellysquid3

**Comment by Noryea** [comment]
> > This is the default in Minecraft 1.19+ and a lot of players are complaining about the micro-stutter caused by placing blocks. Enabling this should be fairly safe, since nobody really complains about it in vanilla.
> 
> Is this basically similar to how the threaded chunk builder is in vanilla? @jellysquid3

Not really. Threaded chunk builder(1.18+) allows the existence of brief visual holes, but Sodium does not. Instead, Sodium displays ghost blocks.

**Comment by Noryea** [comment]
> > This is the default in Minecraft 1.19+ and a lot of players are complaining about the micro-stutter caused by placing blocks. Enabling this should be fairly safe, since nobody really complains about it in vanilla.
> 
> Is this basically similar to how the threaded chunk builder is in vanilla? @jellysquid3

Yep. When plenty of chunks are being updated and you are breaking blocks at the same time, both of them led to ghost blocks
