### ISSUE TITLE
Sodium incompatible with WorldEdit?

### ISSUE THREAD

**Issue by StealWonders** [jellysquid3/Sodium#19]
Hello, I am using Sodium `v0.1.0-SNAPSHOT` on a 1.15.2 Paper (v318) server with AsyncWorldEdit 3.6.20.

When I set blocks, modify the world, and do whatever some parts of chunks don't update & some entire chunks don't update at all.

Selecting grass on the server and then executing `//set glass` yields the following result:

![2020-05-27_19 44 48](https://user-images.githubusercontent.com/6114858/83054426-af7a1f00-a052-11ea-8b4c-22cfb912d7cd.png)

If you log out and back in everything is normal (you can see the glass perfectly fine).
If it were to be possible to make Sodium compatible with mods & plugins like WorldEdit that would be amazing!

**Comment by smonnnn** [comment]
Just wondering, does reloading the chunks with f3 + a fix the issue?

**Comment by StealWonders** [comment]
> 
> 
> Just wondering, does reloading the chunks with f3 + a fix the issue?

Yes, that fixes it. I think it's just a rendering issue as if I set a huge blob of blocks and remove them again I can still fly inside (don't collide with the blocks I see) but I can see the inside of a huge block mesh.

**Comment by jellysquid3** [comment]
This issue has since been fixed with f97321e3f2a669bb94f92a3a52a54390b10fcef5.
