### ISSUE TITLE
text is just boxes (fixed)

### ISSUE THREAD

**Issue by SimonSoIv** [jellysquid3/Sodium#1908]
### Bug Description

whenever i boot up minecraft ever since i installed sodium everything is just a box instead of text 

### Reproduction Steps

idk how to fix this thats why im making this report 

### Log File

![image](https://github.com/CaffeineMC/sodium-fabric/assets/86861750/12ccdd38-e3b2-4acb-94b6-4d5a19800d1c)

### Crash Report

[crash-2023-07-24_03.34.27-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12141009/crash-2023-07-24_03.34.27-client.txt)

**Comment by Fnige** [comment]
Get https://modrinth.com/mod/indium

**Comment by SimonSoIv** [comment]
that was easy enough thanks i thought it was gonna be a lot more complicated then that
