### ISSUE TITLE
FPS boost doesn't work on MacBook Air

### ISSUE THREAD

**Issue by whyed** [jellysquid3/Sodium#191]
### Expected Behavior
A decent FPS boost

### Actual Behavior
Little to no FPS boost

### Reproduction Steps
Maximum graphics settings, Maximum smooth lighting, 8 render distance, all particles, and just looking at a plains biome.
### Attachments
Vanilla:30-45
Sodium: 30-48 fps 

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: 1.16.1
- CPU: [Intel i7]
- GPU: None, Mac doesn't use GPU's

**Comment by whyed** [comment]
Oops, meant to say 8x Intel i7.

**Comment by amnotbananaama** [comment]
The GitHub Issue tracker is for bugs and is not intended as a support site. I suggest joining [JellySquid's Hideout](https://jellysquid.me/discord) and providing screenshots of the [Profiler Graph](https://minecraft.gamepedia.com/Debug_screen#Profiler_graph) and [Frame Time Graph](https://minecraft.gamepedia.com/Debug_screen#Frame_time_graph) during normal gameplay, in the `#tech-support` channel.

**Comment by Titaniumtown** [comment]
> GPU: None, Mac doesn't use GPU's

lol what?

**Comment by Titaniumtown** [comment]
> Java Version: 1.16.1

It's asking for your java version, not minecraft version.

**Comment by EDToaster** [comment]
> 
> 
> > GPU: None, Mac doesn't use GPU's
> 
> lol what?

yea what

**Comment by Titaniumtown** [comment]
screenshot that WhyEd posted on discord (putting this here for continuity): 
![image](https://user-images.githubusercontent.com/11786225/88510782-b91bf680-cfb1-11ea-85fc-b770e72ad657.png)
