### ISSUE TITLE
[dev branch]Server chunks rendering issue caused by light update checking changes

### ISSUE THREAD

**Issue by Noryea** [jellysquid3/Sodium#1910]
### Bug Description

With Sodium from [this commit](https://github.com/CaffeineMC/sodium-fabric/commit/12ff40c3eca4924e8721cf61ce38f191b545f9e5) or earlier, the chunks in _Hypixel Prototype Game Lobby_ render normally. Since [this light update checking changes commit](https://github.com/CaffeineMC/sodium-fabric/commit/7b7f629cc5bb635a7a36ea53de0635e40042251a), however, some chunks do not render at all. You will also experience **a long waiting time** when the terrain loads.
![2023-07-25_00 58 21](https://github.com/CaffeineMC/sodium-fabric/assets/88097529/4ec39d0f-ef71-4090-bce1-3ca82dcaa522)
![2023-07-25_19 43 04](https://github.com/CaffeineMC/sodium-fabric/assets/88097529/f70d7602-22c2-4e93-b71e-58729c73ecce)

### Reproduction Steps

1. Download Sodium from [here](https://github.com/CaffeineMC/sodium-fabric/actions/runs/5570808486) or newer and install it
2. Launch the game and connect to Hypixel(mc.hypixel.net)
3. Click "Game Menu"(the compass) and then click the dropper to join in the Prototype Game Lobby
4. Wait for a while and see a terrible world
5. Check the earlier versions and find no errors

### Log File

There is actually no useful info

### Crash Report

F3+C...
[crash-2023-07-25_00.27.41-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12148170/crash-2023-07-25_00.27.41-client.txt)

**Comment by jellysquid3** [comment]
Does this still occur with 5911a33?

**Comment by Noryea** [comment]
I am glad to test

**Comment by Noryea** [comment]
now it looks like this...

https://github.com/CaffeineMC/sodium-fabric/assets/88097529/557cc6cb-41f5-4592-bbab-29ad6fe97f3c

**Comment by Noryea** [comment]
>  2023-07-29.22-40-54.mp4
F3+A doesnt help

**Comment by Noryea** [comment]
>  2023-07-29.22-40-54.mp4

F3+A doesnt help
