### ISSUE TITLE
Sky light level doesn't changing on daytime

### ISSUE THREAD

**Issue by DanieleKie** [jellysquid3/Sodium#1911]
### Bug Description

I noticed sky light level doesn't changing when daytime is changing. Its mean the light level would be 15 even at nighttime.
Its changing only if i entering into water or into cave. Looks like game thinks there always daytime.

![image](https://github.com/CaffeineMC/sodium-fabric/assets/128975833/1c121051-165d-4264-bf39-02159cfa198a)

### Reproduction Steps

Thats happens in single world and on server too, just same thing. Just everytime.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12164002/latest.log)

### Crash Report

[crash-2023-07-12_06.17.44-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12164007/crash-2023-07-12_06.17.44-client.txt)

**Comment by pajicadvance** [comment]
This is exactly how vanilla behaves, this is not an issue.
