### ISSUE TITLE
Sodium causes "Z-Fighting" with non-full blocks (Powder Snow)

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#1912]
### Bug Description

https://github.com/CaffeineMC/sodium-fabric/assets/68275908/540d40ff-45a9-452f-b5ab-3d116ebf1579

### Reproduction Steps

![2023-07-25_20 43 33](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/32d1c274-72a0-4d52-b68d-b521f4d20f2b)

![2023-07-25_20 43 38](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/8a305f50-1113-4c8b-a3a3-1bdc4d858bf7)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12164534/latest.log)

### Crash Report

[crash-2023-07-25_20.47.33-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12164549/crash-2023-07-25_20.47.33-client.txt)

**Comment by hexadecimal233** [comment]
I was having the same problem on iron bars i think
They occured sometimes but they did not occur most of the time?

**Comment by Lolothepro** [comment]
> I was having the same problem on iron bars i think They occured sometimes but they did not occur most of the time?

#460

**Comment by AMDKilla** [comment]
I'm having a similar problem with chests, but only newly placed ones. If I do anything to reload the rendering (like changing resource packs, changing graphical settings etc) it fixes the existing glitches, but new ones appear on freshly placed chests

**Comment by AMDKilla** [comment]
> I'm having a similar problem with chests, but only newly placed ones. If I do anything to reload the rendering (like changing resource packs, changing graphical settings etc) it fixes the existing glitches, but new ones appear on freshly placed chests

Nevermind, it was an issue with Flywheel included with the Create mod. "/flywheel backend off" fixes the issue

**Comment by astridellensdottir** [comment]
> I was having the same problem on iron bars i think
> They occured sometimes but they did not occur most of the time?

this (iron bar z-fighting) is likely because of a vanilla bug. https://bugs.mojang.com/browse/MC-192420

**Comment by jellysquid3** [comment]
Is this fixed with https://github.com/CaffeineMC/sodium-fabric/commit/ea0172768a5da9907b5a5711160dc3984fafea83?

**Comment by Lolothepro** [comment]
fixed!
