### ISSUE TITLE
[1.20.1] All faces of blocks that are not snow (powder) are visible when the player is in powder snow.

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#1913]
### Bug Description

Screenshots:

Sodium:
![2023-07-26_22 55 33](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/4258c7a9-3ffe-480a-8a00-1a64605b4d92)

Vanilla:
![2023-07-26_22 49 44](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/aeef5e1f-f052-4959-be13-b35e831a8e48)

### Reproduction Steps

Go into powder snow
Place a block that is not snow powder

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12177130/latest.log)

### Crash Report

[crash-2023-07-26_22.58.52-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12177131/crash-2023-07-26_22.58.52-client.txt)

**Comment by Lolothepro** [comment]
Addional information:
https://github.com/sp614x/optifine/issues/7506

**Comment by Lolothepro** [comment]
related to https://github.com/CaffeineMC/sodium-fabric/issues/859 & https://github.com/CaffeineMC/sodium-fabric/pull/892

**Comment by muzikbike** [comment]
Is this not just a complete duplicate of #1163?

**Comment by jellysquid3** [comment]
Resolved with https://github.com/CaffeineMC/sodium-fabric/commit/c937156e37d221216f284639fc8c51b30facf91e.
