### ISSUE TITLE
Pojav Launcher is not supported

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#1916]
Per our hardware support policy (as of the time of writing):

> **OpenGL Compatibility Layers**
> 
> Devices which need to use OpenGL translation layers (such as GL4ES, ANGLE, etc) are not supported and will very likely not work with Sodium. These translation layers do not implement required functionality and they suffer from underlying driver bugs which cannot be worked around.

This reasoning comes down to the fact that ANGLE, GL4ES, VirGL, etc, are much too slow at emulating the functionality that Sodium requires, and more importantly, they simply are not capable of providing certain OpenGL 4.x class functionality on top of OpenGL ES.

Zink is the exception to this rule, as it is an OpenGL-on-Vulkan translation layer which actually has access to the aforementioned functionality, but it's my understanding that _most_ Android devices are not able to use it without significant problems.

Furthermore, in Sodium 0.5, it appears that nearly every rendering backend for Pojav Launcher was broken (other than Zink) and it doesn't seem like there is any way to fix that on our side, since our new materials system _relies_ on this very basic OpenGL 3.x functionality being provided.

As such, using Sodium on Pojav Launcher is very much "at your own risk", and our team is not going to fix compatibility with broken graphics drivers. It will probably not work correctly outside of the Zink backend with very specific devices, and even then, you are more likely than not to hit serious bugs in the Vulkan driver your Android ROM provides.

**Comment by Dawimpy** [comment]
:(
