### ISSUE TITLE
Minecraft Crashes when I try to go through and end gateway

### ISSUE THREAD

**Issue by nathand2623** [jellysquid3/Sodium#1917]
### Bug Description

Finally fought the Ender Dragon in my minecraft world loaded with tons of mods, and pretty much as soon I defeat it, the game completely freezes, and so does my entire computer. I then force shut down my system, load back in. and the same thing happens again. After that I just disable all of my mods and run minecraft like that for a couple minutes. I eventually turn back on my mods, and the game run fines until I try to go through a end gateway where it completely freezes my system once again. I then thought it could be something to do with my shader pack, so I switch from Complementary Shaders to Sildur's Vibrant Shader's and same random crash.

### Reproduction Steps

Crash Report says it is a problem Rendering Block Entity, specifically an end-gateway, which would make me think it is a problem when switching between dimensions, but this has never happened in the The Nether at all. Here is a list of all of my mods.

![Screenshot from 2023-07-28 12-55-59](https://github.com/CaffeineMC/sodium-fabric/assets/140838317/7344614f-f2c1-4fad-a7cc-60068ed4a2b5)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12196588/latest.log)

### Crash Report

[crash-2023-07-28_11.58.12-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12196590/crash-2023-07-28_11.58.12-client.txt)

**Comment by nathand2623** [comment]
Little Update. I think I have narrowed the problem down to a issue between Sodium and Shader Packs. I decided I would at least try to play the game without any shaders, and absolutely zero crashes even when going through an end-gateway.

**Comment by C0WYY** [comment]
The exact same thing is happening with me when entering either the end or nether. Nothing has fixed it for me is there any other things i should try?

**Comment by FlashyReese** [comment]
This issue is not related to Sodium itself; rather, it's an incompatibility with Sodium Extra versions 0.4.21 to 0.4.22 when using beacon optimizations with Iris shaders enabled. However, this problem has been resolved since version 0.4.23 and onwards. To resolve the issue, please make sure to update your mods to the latest versions.
