### ISSUE TITLE
Minecraft Crashes when I try to open

### ISSUE THREAD

**Issue by leafotario** [jellysquid3/Sodium#192]
### Reproduction Steps
1. Start the game
2. The game doesn't open

### Crash Report File
https://gist.github.com/OLeafRead/463eae978d80bb4c13bca8f119415161

**Comment by AMereBagatelle** [comment]
It seems that you have a invalid file for Sodium.  This is simply a bug with Curseforge as I understand, it sometimes gives invalid files.

**Comment by jellysquid3** [comment]
You need to download the mod again. Your download is corrupted.
