### ISSUE TITLE
Crashes while launching, code -805306369

### ISSUE THREAD

**Issue by no-u14** [jellysquid3/Sodium#1926]
### Bug Description

Whenever I place Sodium into my mods folder, it causes my game to crash whilst on the red Mojang loading screen. The progress bar only goes about ten percent before the window stops responding. The exit code is -805306369. The suggested fix is to allocate additional memory to Minecraft. I allocated 3G instead of the default 2G, and this did not help.

My processor is Intel(R) Core(TM) i5-3337U CPU @ 1.80GHz 

### Reproduction Steps

1. Open the Minecraft Launcher.
2. Launch on "fabric-loader-1.20.1"
3. The red Mojang loading screen stops loading at ten percent. Windows will say that the application is not responding.
4. Hit the close button. A message will pop up that reads, "OpenJDK Platform Binary is not responding."
5. Select "Close program."
6. You will be returned to the Minecraft Launcher, and get the exit code -805306369.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12223429/latest.log)

### Crash Report

Since the game crashes before opening, I do not get a crash report. My crash-reports folder does not appear to exist.

![Screenshot 2023-07-31 200614](https://github.com/CaffeineMC/sodium-fabric/assets/141089031/71fa3e04-0d61-44a2-954a-f14309256a98)

![Screenshot 2023-07-31 200756](https://github.com/CaffeineMC/sodium-fabric/assets/141089031/db65f65b-8617-4250-bc27-48795dcb6837)

**Comment by jellysquid3** [comment]
> [20:06:25] [Render thread/INFO]: Launching a new process to probe the system configuration!
> [20:06:26] [Render thread/INFO]: OpenGL Vendor: Intel
> [20:06:26] [Render thread/INFO]: OpenGL Renderer: Intel(R) HD Graphics 4000
> [20:06:26] [Render thread/INFO]: OpenGL Version: 3.3.0 - Build 10.18.10.4358

You have broken graphics drivers installed. Please read #899 for instructions on how to update your drivers.

**Comment by jellysquid3** [comment]
For future reference, this is documented on our [_Driver Compatibility_](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility) page, which is also linked to on the [official Modrinth page](https://modrinth.com/mod/sodium).
