### ISSUE TITLE
Compatibility with Vulkan

### ISSUE THREAD

**Issue by Stoutscientist** [jellysquid3/Sodium#1927]
### Request Description

I understand if this would be too much work but if compatibility with VulkanMod was added it would be awesome!

https://github.com/xCollateral/VulkanMod

**Comment by pajicadvance** [comment]
No. Both mods replace Minecraft's renderer but use different backends. Asking to make them "compatible" is not even a valid request.

**Comment by err2ror** [comment]
what about 0.9.0 sodium....?

**Comment by douira** [comment]
Yes 0.9 has support for vulkan. Please stop commenting on closed issues like this.
