### ISSUE TITLE
Keyboard Delay

### ISSUE THREAD

**Issue by TZXYZMC** [jellysquid3/Sodium#1934]
### Bug Description

Ive been getting delay from sodium for a weak so please try to find a fix for me or something thanks

### Reproduction Steps

Ive been getting delay from sodium for a weak so please try to find a fix for me or something thanks

### Log File

Ive been getting delay from sodium for a weak so please try to find a fix for me or something thanks

### Crash Report

Ive been getting delay from sodium for a weak so please try to find a fix for me or something thanks

**Comment by jellysquid3** [comment]
Banned from the issue tracker for deliberate misuse of the issue template. Go annoy someone else.
