### ISSUE TITLE
Weird glitch with newest update

### ISSUE THREAD

**Issue by CalendarCat** [jellysquid3/Sodium#1935]
### Bug Description

Just updated to the newest versions of Reeses Sodium Options, Sodium Extra, and Sodium. Weird glitch happens that I've never seen before. This just happens when I boot up the game. The right option just closes game, left brings me to the Modrinth Sodium page. I'm assuming this is just due to me updating to the newer version so fast but I just wanted to let you know incase it wasn't known. This has never happened before, so I know it's most likely Sodium since it is linking me to that page. 

I love your mods, thank you for constantly updating and consistently helping mine and many others performance ingame <3 

List of mods being used: 
CIT Resewn (https://modrinth.com/mod/cit-resewn)
Fabric API (https://modrinth.com/mod/fabric-api)
Fabric Skyboxes (https://modrinth.com/mod/fabricskyboxes)
FerriteCore (https://modrinth.com/mod/ferrite-core)
Forge Config API Port (https://modrinth.com/mod/forge-config-api-port)
FPS Monitor (https://modrinth.com/mod/fps-monitor)
Iris (https://modrinth.com/mod/iris)
Lithium (https://modrinth.com/mod/lithium)
Memory Leak Fix (https://modrinth.com/mod/memoryleakfix)
Modmenu (https://modrinth.com/mod/modmenu)
Open parties and Claims (https://modrinth.com/mod/open-parties-and-claims)
Sodium (https://modrinth.com/mod/sodium)
Reeses Sodium Options (https://modrinth.com/mod/reeses-sodium-options)
Sodium Extra (https://modrinth.com/mod/sodium-extra)
Xaeros Minimap (https://modrinth.com/mod/xaeros-minimap)
Xaeros Worldmap (https://modrinth.com/mod/xaeros-world-map)

![image](https://github.com/CaffeineMC/sodium-fabric/assets/141324101/d630fa23-3eae-4c8d-8a27-2e6c1ae25b4e)

### Reproduction Steps

Just booting up the game, I am using technic launcher from my modpack. I was going to update the main pack but I always use a tester pack before updating. This is the link to the tester pack: https://www.technicpack.net/modpack/test-fabric-test.1951827 

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12265371/latest.log)

### Crash Report

Strangely enough, this does not count as a crash report so there is no way to access it. Using F3 + C does not work either.

**Comment by pajicadvance** [comment]
You cannot use Iris as it hasn't been updated to support Sodium 0.5 yet.

**Comment by CalendarCat** [comment]
Gotcha! Thank you
