### ISSUE TITLE
Game crashes when leaving the server

### ISSUE THREAD

**Issue by RealmKebab** [jellysquid3/Sodium#1936]
### Bug Description

The game directly crashes whenever you leave the server.

### Reproduction Steps

1. Play on a server with Sodium 0.5
2. Play for a bit (probably like 10 minutes)
3. Leave the server
4. Game crashes

### Log File

https://mclo.gs/gLyhjAp

### Crash Report

https://mclo.gs/71WdKTW

**Comment by jellysquid3** [comment]
Probably an issue with Dashloader... try removing it.

**Comment by RealmKebab** [comment]
> Probably an issue with Dashloader... try removing it.

Removing dashloader doesn't initiate the crash anymore.

**Comment by RealmKebab** [comment]
Created an issue at [#70](https://github.com/alphaqu/DashLoader/issues/70)
