### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Paladynee** [jellysquid3/Sodium#1937]
### Bug Description

The game crashes while starting up.

### Reproduction Steps

Start the game.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12266048/latest.log)

### Crash Report

[crash-2023-08-05_06.55.55-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12266046/crash-2023-08-05_06.55.55-client.txt)

**Comment by vogon-poetry** [comment]
Remove Dashloader and try again.

**Comment by Paladynee** [comment]
> Remove Dashloader and try again.

It booted up fine once, the crash happened when my game crashed because of a different mod (`moreculling`) and while restarting it.
I'm trying re-installing the game. Keep you posted about the Dashloader.

Update: game seems to work fine at the first launch after installing. This might be because Dashloader caches content in this launch. Next launch, Dashloader initializes and causes the crash. Thanks. Unrelated to sodium.
