### ISSUE TITLE
Crash when joing the server

### ISSUE THREAD

**Issue by sh2kcs** [jellysquid3/Sodium#1938]
### Bug Description

Minecraft crashes when joining the server

### Reproduction Steps

Go to minecraft and go to the server where the registration is in the void

### Log File

https://mclo.gs/LwY8Zsl

### Crash Report

https://mclo.gs/cTmzdpo

**Comment by Fnige** [comment]
Iirc its probably bobby

**Comment by pajicadvance** [comment]
Some of the mods you are using haven't been updated to support Sodium 0.5 yet, and you are using several mods which require Indium, which also hasn't been updated for Sodium 0.5 yet. Either downgrade to 0.4.10 or wait for the other mods to update.
