### ISSUE TITLE
Intel i9-9900K @ 3.6GHz / RTX 2070S  (549 -> 682)

### ISSUE THREAD

**Issue by BenjaminHoegh** [jellysquid3/Sodium#194]
Intel i9-9900K @ 3.6GHz / RTX 2070S  (549 -> 682)

**Comment by Oberfail** [comment]
cool story bro

**Comment by LucilleTea** [comment]
Github issues are for bugs or feature requests, if you'd like to discuss your results or diagnose performance problems please use [the Discord server](https://jellysquid.me/discord).
