### ISSUE TITLE
"this.field_3712.field_1724" and "this.renderSectionManager"  is null

### ISSUE THREAD

**Issue by Lolfaceftw** [jellysquid3/Sodium#1940]
### Bug Description

Recently updated to Sodium 0.5.0 and receiving this error

Joining on my Server:
https://mclo.gs/uOdoWL1

Joining on my World:
https://mclo.gs/zMHdu0S

### Reproduction Steps

Updated to Sodium 0.5.0 and game is crashing when loading a world or server

### Log File

[2023-08-05-4.log](https://github.com/CaffeineMC/sodium-fabric/files/12267399/2023-08-05-4.log)

### Crash Report

[crash-2023-08-05_21.48.49-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12267400/crash-2023-08-05_21.48.49-client.txt)

**Comment by pajicadvance** [comment]
Cracked launchers are not supported.
