### ISSUE TITLE
Rendering error when loading the world

### ISSUE THREAD

**Issue by Anewri32** [jellysquid3/Sodium#1941]
### Bug Description

When loading or creating a world in a Modpack, the blocks are not displayed but when removing the "Sodium" Mod and its plugins including "Iris", it is displayed correctly.

I'm currently using an Nvidia graphics card but I'm not sure if it has to do with it.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/70771409/be051b92-3551-40c2-9dd3-063c5369ca41)

### Reproduction Steps

Start minecraft and create a new world

### Log File

https://mclo.gs/tYHw5UW

### Crash Report

There is no, the game does not crash

**Comment by pajicadvance** [comment]
Does the same issue happen with only Sodium installed?

**Comment by Anewri32** [comment]
No, I tried it in a separate instance with Sodium, reese sodium options, Sodium extra and Indium, but no problems.

**Comment by james090500** [comment]
I had this same problem. It was caused by the Farsight mod. Issue here:

https://github.com/someaddons/farsight/issues/64

**Comment by Anewri32** [comment]
Confirmed, apparently the Bobby mod also fails (to be more precise, it crashes).
