### ISSUE TITLE
Crash when enterin world

### ISSUE THREAD

**Issue by AxionQc** [jellysquid3/Sodium#1942]
### Reproduction Steps

Install mods 
run game
load world

### Log File

https://mclo.gs/yBsEvBn

### Crash Report

https://mclo.gs/wLpdgv1

**Comment by Altirix** [comment]
you have incompatible mods installed. you need to wait for these to be updated.

**Comment by AxionQc** [comment]
which ones

**Comment by pajicadvance** [comment]
It appears that the log is getting spammed by errors from the mod "Hold That Chunk", please disable the mod, then upload a new log if you are still crashing.

**Comment by AxionQc** [comment]
> It appears that the log is getting spammed by errors from the mod "Hold That Chunk", please disable the mod, then upload a new log if you are still crashing.

disabled it still crashing

https://mclo.gs/rxspmwN

**Comment by AxionQc** [comment]
cull leaves was the problem
