### ISSUE TITLE
Weird bug with shadows

### ISSUE THREAD

**Issue by MbtMarco** [jellysquid3/Sodium#1943]
### Bug Description

![2023-08-05_20 45 04](https://github.com/CaffeineMC/sodium-fabric/assets/124934175/6b016cf1-62b1-4e6c-bdfc-177b2e03184f)

### Reproduction Steps

Place a block on any surface during the day.

### Log File

https://mclo.gs/435i2Qq

### Crash Report

.

**Comment by pajicadvance** [comment]
I cannot reproduce this issue with only Sodium, can you also try with Sodium only and see if it looks the same? If not, then it's most definitely caused by some other mod.

**Comment by MbtMarco** [comment]
Ok, ill try

**Comment by MbtMarco** [comment]
Thanks, Sodium is not the problem, now I have to find the mod that causes this :C

**Comment by pajicadvance** [comment]
If you figure out which mod causes it, please post it here, it would be useful info for us :)

**Comment by pajicadvance** [comment]
Seems like this is a bug in Indium: https://github.com/comp500/Indium/issues/220
According to them, it should be fixed fairly soon in an update.

**Comment by MbtMarco** [comment]
Thanks, I had found it too by trying each mod individually.
