### ISSUE TITLE
Crash when enterin world

### ISSUE THREAD

**Issue by mindryder** [jellysquid3/Sodium#1946]
### Reproduction Steps

Crash world enter

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12268231/latest.log)

### Crash Report

[crash-2023-08-06_00.16.01-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12268233/crash-2023-08-06_00.16.01-client.txt)

**Comment by pajicadvance** [comment]
Cull Leaves is incompatible with Sodium, use Cull Less Leaves instead.

**Comment by mindryder** [comment]
ty
