### ISSUE TITLE
[1.20.1] Crash with: this.uniformCache is null

### ISSUE THREAD

**Issue by Mr-Zero88** [jellysquid3/Sodium#1948]
### Bug Description

Game crashes on launch.

Was not a problem with Sodium 0.4.10.

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null
	at net.minecraft.class_5944.redirect$chb000$sodium$redirectGetUniformLocation(class_5944.java:2167)

### Reproduction Steps

Full mod list is present in latest.log.
First: Open Video Settings.
After that: Launch the game.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12268285/latest.log)

### Crash Report

[crash-2023-08-05_23.41.34-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12268284/crash-2023-08-05_23.41.34-client.txt)

**Comment by FlashyReese** [comment]
It is caused by DashLoader.
