### ISSUE TITLE
Does not work with fabritone and xrays

### ISSUE THREAD

**Issue by ytcyde** [jellysquid3/Sodium#195]
I like to use sodium on an anarchy server but sodium does not work with [fabritone](https://gitlab.com/CDAGaming/fabritone). I've already reported this to the fabritone team and im telling you this just incase you can help with it.

**Comment by amnotbananaama** [comment]
> Support is not provided for garbage third-party clients.

~~Additionally that mod is currently only available for 1.15.2.~~ Only the 1.16.1 version of Sodium is supported.

**Comment by ytcyde** [comment]
https://gitlab.com/CDAGaming/fabritone/-/jobs not true im using it on 1.16.1

**Comment by Titaniumtown** [comment]
I am getting the same issue.

**Comment by Titaniumtown** [comment]
I built fabritone from source, works w/ vanilla, but not sodium :(

**Comment by Titaniumtown** [comment]
(this is also 1.16.1 I am speaking about)

**Comment by jellysquid3** [comment]
I don't support mods designed for cheating.

**Comment by ytcyde** [comment]
fabritone isnt for cheating

**Comment by ytcyde** [comment]
xray is just also a side thing

**Comment by Titaniumtown** [comment]
> fabritone isnt for cheating

Exactly, it's a pathfinding mod with other features. Like building from schematics, mining blocks, etc.
