### ISSUE TITLE
Exit Code -1: The hell is a "jellysquid"?

### ISSUE THREAD

**Issue by Smilerr** [jellysquid3/Sodium#1950]
### Bug Description

I downloaded the newest update and now, the game crashes everytime i join a world/server (just play the game in general). And i got the exit code "-1". The crash report says this "The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.onChunkAdded(int, int)'"

What is "jellysquid.mods"? i do not have a mod with a "jelly squid" and i did not find any folder having/missing that. I do not know how to fix this problem

### Reproduction Steps

I just downloaded the new version and it started happening. it was working fine with the old version. I do have a lot of mods downloaded on minecraft but if it worked with the old version, it should work with the new version.

Attached is a video of me presenting the bug.

https://github.com/CaffeineMC/sodium-fabric/assets/141529800/a7cdde8f-6fb6-4968-aaa8-341dc62df653

### Log File

[2023-08-05-7.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/12268423/2023-08-05-7.log.gz)

### Crash Report

[crash-2022-10-23_13.40.30-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12268416/crash-2022-10-23_13.40.30-client.txt)

**Comment by pajicadvance** [comment]
Bobby needs an update to work with the latest version of Sodium, disable it for now. You also need to install [Indium](https://modrinth.com/mod/indium) for some of your other mods to work with Sodium.

**Comment by pajicadvance** [comment]
...Also, JellySquid is the name of the author of Sodium.

**Comment by Smilerr** [comment]
Thank you for the help! and thank you for clearing up what jelly squid was 😅.

**Comment by Luca296** [comment]
> Bobby needs an update to work with the latest version of Sodium, disable it for now. You also need to install [Indium](https://modrinth.com/mod/indium) for some of your other mods to work with Sodium.

Sorry but what is bobby?

**Comment by douira** [comment]
Please don't make off topic comments on year old closed issues. You can come to our discord server for support.

**Comment by Luca296** [comment]
> Please don't make off topic comments on year old closed issues. You can come to our discord server for support.

oh sorry miss read date
