### ISSUE TITLE
Dual inward stream liquids render incorrectly from certian angles

### ISSUE THREAD

**Issue by Altirix** [jellysquid3/Sodium#1952]
### Bug Description

For some reason In vanilla minecraft the shape of a 2 inward stream flowing water block is directional.

when two faces flow into eachother going into each other the resulting shape is either a V <sup>(1)</sup> or  ‾\ <sup>(2)</sup>

[1] positive, positive or negative, negative
![image](https://github.com/CaffeineMC/sodium-fabric/assets/19439141/dd6bc098-335f-40d7-89c7-f8dfecf19f30)

[2] positive, negative or negative, positive
 ![image](https://github.com/CaffeineMC/sodium-fabric/assets/19439141/4488097e-6b10-4196-aa9b-4c7b55569352)

![image](https://github.com/CaffeineMC/sodium-fabric/assets/19439141/ee4582bb-c8e5-45a4-918f-1c74474161d4)

Sodium rather than rendering just Type 1 renders Type 1 from above/out and Type 2 from below/in

![image](https://github.com/CaffeineMC/sodium-fabric/assets/19439141/835fd8a4-bdc9-4fd6-a2a6-1c1b409bd73a)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/19439141/729b3739-2501-419f-b282-643172142729)

### Reproduction Steps

Use World File
[DemoWorld.zip](https://github.com/CaffeineMC/sodium-fabric/files/12268623/DemoWorld.zip)

### Log File

N/A

### Crash Report

N/A

**Comment by MeeniMc** [comment]
is it the same as #609?

**Comment by jellysquid3** [comment]
This appears to be a duplicate of #609, yes.
