### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by mindryder** [jellysquid3/Sodium#1954]
### Reproduction Steps

something players get crash

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12269527/latest.log)

### Crash Report

[crash-2023-08-06_14.47.42-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12269529/crash-2023-08-06_14.47.42-client.txt)

**Comment by mindryder** [comment]
other player 
[latest (1).log](https://github.com/CaffeineMC/sodium-fabric/files/12269582/latest.1.log)
[crash-2023-08-06_15.19.52-client (1).txt](https://github.com/CaffeineMC/sodium-fabric/files/12269583/crash-2023-08-06_15.19.52-client.1.txt)

**Comment by pajicadvance** [comment]
The library mod Iceberg has not been updated to work with Sodium 0.5 yet. You are also using some mods which require [Indium](https://modrinth.com/mod/indium) in order to work with Sodium, but you don't have it installed.

**Comment by mindryder** [comment]
I no have mods who require indium, strange, but i have same mods with iceberg ( **iceberg** for **LegendaryTooltips-1.20.1-fabric-1.4.4** and **AdvancementPlaques-1.20.1-fabric-1.4.11.jar** ) and i dont have crash, why?

**Comment by pajicadvance** [comment]
I'm not sure. It could be that it happens only when it tries to render a specific item tooltip, maybe the one that shows the item model? In any case, it's a problem with Iceberg.

**Comment by AHilyard** [comment]
To anyone experiencing this crash, it has been fixed in the latest update of Iceberg.  This crash only affected users who also use Legendary Tooltips with the 3D preview option enabled.

**Comment by pajicadvance** [comment]
Thanks for notifying us about the update.
