### ISSUE TITLE
Game crashing when using sodium 

### ISSUE THREAD

**Issue by Pokemaster404** [jellysquid3/Sodium#1955]
### Bug Description

Everytime I load up Minecraft with sodium and I join a multiplayer world the game crashes. I've tried deleting some sodium files that was suggested on another page and it didn't work. Any have a clue?

### Reproduction Steps

Load up Minecraft with sodium 0.5.0, join mulitplayer world

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12269888/latest.log)

### Crash Report

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2023-08-06 10:53:42
Description: Unexpected error

java.lang.NoSuchMethodError: 'java.util.Collection me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.getMemoryDebugStrings()'
	at com.minenash.customhud.mod_compat.SodiumCompat.lambda$registerCompat$11(SodiumCompat.java:39)
	at com.minenash.customhud.mod_compat.CustomHudRegistry.runComplexData(CustomHudRegistry.java:45)
	at com.minenash.customhud.ComplexData.update(ComplexData.java:215)
	at com.minenash.customhud.CustomHud.onTick(CustomHud.java:107)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$blo000$fabric-lifecycle-events-v1$onEndTick(class_310.java:11522)
	at net.minecraft.class_310.method_1574(class_310.java:1957)
	at net.minecraft.class_310.method_1523(class_310.java:1181)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.minenash.customhud.mod_compat.SodiumCompat.lambda$registerCompat$11(SodiumCompat.java:39)
	at com.minenash.customhud.mod_compat.CustomHudRegistry.runComplexData(CustomHudRegistry.java:45)
	at com.minenash.customhud.ComplexData.update(ComplexData.java:215)
	at com.minenash.customhud.CustomHud.onTick(CustomHud.java:107)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at net.minecraft.class_310.handler$blo000$fabric-lifecycle-events-v1$onEndTick(class_310.java:11522)

-- Affected level --
Details:
	All players: 54 total; [class_746['Pokemaster404'/27693, l='ClientLevel', x=-6761.50, y=35.00, z=-5589.50], class_745['Macowz'/27687, l='ClientLevel', x=-6761.50, y=35.00, z=-5589.50], class_745['Squeaknight'/27589, l='ClientLevel', x=-6763.17, y=38.17, z=-5590.07], class_745['NahJitJJ'/27584, l='ClientLevel', x=-6762.66, y=34.83, z=-5589.41], class_745['Wilbina'/26776, l='ClientLevel', x=-6753.05, y=27.37, z=-5620.39], class_745['MagmalsNC'/25762, l='ClientLevel', x=-6804.31, y=35.00, z=-5576.15], class_745['Prism_DAR'/27551, l='ClientLevel', x=-6761.50, y=35.00, z=-5589.50], class_745['Sonicar'/27383, l='ClientLevel', x=-6778.65, y=35.00, z=-5599.23], class_745['TTkindboy'/27541, l='ClientLevel', x=-6792.12, y=36.00, z=-5589.47], class_745['TheRealMj_69'/27371, l='ClientLevel', x=-6778.29, y=35.35, z=-5574.97], class_745['Gnoomie'/26903, l='ClientLevel', x=-6808.28, y=35.00, z=-5583.30], class_745['Budst3r'/27482, l='ClientLevel', x=-6761.50, y=35.00, z=-5589.50], class_745['kwarkiboy'/27676, l='ClientLevel', x=-6761.50, y=35.00, z=-5589.50], class_745['Mochiii3103'/26739, l='ClientLevel', x=-6768.80, y=34.72, z=-5563.85], class_745['mlimm'/27510, l='ClientLevel', x=-6777.61, y=34.00, z=-5602.10], class_745['_Trigger__'/27682, l='ClientLevel', x=-6771.58, y=35.33, z=-5590.68], class_745['xShyl'/27271, l='ClientLevel', x=-6768.34, y=34.00, z=-5570.77], class_745['RomanRodri'/27261, l='ClientLevel', x=-6795.66, y=36.00, z=-5584.57], class_745['Sheenthefirst'/27631, l='ClientLevel', x=-6761.50, y=35.00, z=-5589.50], class_745['FireBreathMan'/14019, l='ClientLevel', x=-6761.50, y=35.00, z=-5589.50], class_745['§k§7§4§b§a§9§k§b'/5358, l='ClientLevel', x=-6791.50, y=36.00, z=-5595.50], class_745['§6§1§6§n§n§o§o§l'/5376, l='ClientLevel', x=-6788.50, y=36.00, z=-5584.50], class_745['§f§1§o§5§n§8§4§4'/5377, l='ClientLevel', x=-6765.50, y=34.50, z=-5585.50], class_745['§4§3§l§a§c§b§n§b'/5415, l='ClientLevel', x=-6744.50, y=38.00, z=-5589.50], class_745['§5§5§c§o§2§r§0§2'/5417, l='ClientLevel', x=-6779.50, y=35.00, z=-5615.50], class_745['§f§k§a§l§n§2§4§e'/5445, l='ClientLevel', x=-6778.50, y=34.31, z=-5585.50], class_745['§3§0§2§a§r§n§m§d'/7730, l='ClientLevel', x=-6763.50, y=34.00, z=-5577.50], class_745['§5§0§n§c§o§c§a§l'/7736, l='ClientLevel', x=-6758.50, y=34.00, z=-5561.50], class_745['§b§c§e§m§3§o§9§9'/7773, l='ClientLevel', x=-6783.50, y=34.00, z=-5576.50], class_745['§o§f§a§7§5§d§f§b'/7778, l='ClientLevel', x=-6780.50, y=35.00, z=-5580.50], class_745['§f§o§4§b§a§a§r§l'/7787, l='ClientLevel', x=-6779.50, y=34.00, z=-5605.50], class_745['§1§m§4§d§7§k§n§1'/7788, l='ClientLevel', x=-6779.50, y=34.00, z=-5605.50], class_745['§4§o§b§k§m§9§1§n'/7789, l='ClientLevel', x=-6779.50, y=34.20, z=-5605.50], class_745['§8§o§5§r§5§d§8§3'/7790, l='ClientLevel', x=-6779.50, y=34.00, z=-5601.00], class_745['§1§8§a§3§m§8§l§d'/7795, l='ClientLevel', x=-6779.50, y=34.00, z=-5601.00], class_745['§c§d§8§1§4§o§7§e'/7800, l='ClientLevel', x=-6779.50, y=34.20, z=-5601.00], class_745['§r§2§r§d§1§1§8§f'/7801, l='ClientLevel', x=-6776.50, y=34.00, z=-5593.50], class_745['§a§f§f§9§7§l§8§6'/7802, l='ClientLevel', x=-6776.50, y=34.00, z=-5593.50], class_745['§b§f§d§3§4§l§8§1'/7803, l='ClientLevel', x=-6776.50, y=34.20, z=-5593.50], class_745['§2§r§4§b§5§2§5§m'/7804, l='ClientLevel', x=-6777.50, y=37.20, z=-5607.50], class_745['§l§9§o§8§d§l§e§5'/7805, l='ClientLevel', x=-6777.50, y=37.00, z=-5607.50], class_745['§l§3§l§c§m§1§7§6'/7806, l='ClientLevel', x=-6777.50, y=37.20, z=-5607.50], class_745['§1§3§4§m§m§c§r§4'/7807, l='ClientLevel', x=-6777.50, y=37.00, z=-5607.50], class_745['§4§b§c§7§8§a§7§0'/7808, l='ClientLevel', x=-6777.50, y=37.40, z=-5607.50], class_745['§f§l§5§n§0§m§2§4'/7809, l='ClientLevel', x=-6777.50, y=37.40, z=-5607.50], class_745['§0§m§9§e§6§k§r§o'/7810, l='ClientLevel', x=-6765.50, y=34.00, z=-5592.50], class_745['§a§k§f§e§o§8§n§d'/7811, l='ClientLevel', x=-6765.50, y=34.00, z=-5592.50], class_745['§r§1§a§l§k§b§3§8'/7812, l='ClientLevel', x=-6765.50, y=34.20, z=-5592.50], class_745['§1§6§f§3§9§7§3§6'/7813, l='ClientLevel', x=-6770.50, y=42.00, z=-5605.50], class_745['§k§a§0§d§9§2§a§o'/7814, l='ClientLevel', x=-6770.50, y=42.00, z=-5605.50], class_745['§e§2§3§3§0§5§8§7'/7815, l='ClientLevel', x=-6770.50, y=42.20, z=-5605.50], class_745['Alanmus'/27698, l='ClientLevel', x=-6762.23, y=34.97, z=-5589.52], class_745['FaridGang_'/27707, l='ClientLevel', x=-6761.50, y=35.00, z=-5589.50], class_745['masterwyatt'/26203, l='ClientLevel', x=-6805.44, y=36.97, z=-5605.98]]
	Chunk stats: 1024, 165
	Level dimension: minecraft:temp_world_3bce80e5-e68b-4b9d-b90d-fb596af54c98
	Level spawn location: World: (8,-63,8), Section: (at 8,1,8 in 0,-4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 155027 game time, 10700 day time
	Server brand: Yacht (Marina)
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: No
	Packs: vanilla, fabric, file/1-19-ore-outline (1).zip, file/Axolotl+Buckets.zip, file/FreshAnimations_v1.8.1 (1).zip, file/NoPumpkinBlur-rv1.3.zip, file/SimParticles.zip, file/The Big CIT pack, file/better-flowers-e3620.zip, file/Rainbow+XP+bar+and+ping+1.18.zip, file/Better+Hotbar+1.19.zip, file/undefined-Totem-pv9.zip, minecraft:supporteatinganimation, server, essential

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1816097632 bytes (1731 MiB) / 2684354560 bytes (2560 MiB) up to 5368709120 bytes (5120 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1650 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f95
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3640
	Graphics card #1 name: Intel(R) UHD Graphics
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x9bc4
	Graphics card #1 versionInfo: DriverVersion=26.20.100.7985
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 23851.00
	Virtual memory used (MB): 21317.45
	Swap memory total (MB): 7680.00
	Swap memory used (MB): 521.29
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		animatica: Animatica 0.6+1.20
		appleskin: AppleSkin 2.5.0+mc1.20
		architectury: Architectury 9.0.8
		autorun: AutoRun 0.5.0
		betterf3: BetterF3 7.0.1
			cloth-config: Cloth Config v11 11.1.106
				cloth-basic-math: cloth-basic-math 0.6.1
		boostedbrightness: Boosted Brightness 2.2.0
		carpet: Carpet Mod 1.4.112+v230608
		chat_heads: Chat Heads 0.10.18
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		completeconfig: CompleteConfig 2.4.0
			completeconfig-base: completeconfig-base 2.4.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.4.0
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.4.0
		controlling: Controlling For Fabric 12.0.1
		cull-less-leaves: Cull Less Leaves 1.2.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		custom-crosshair-mod: Custom Crosshair Mod 1.5.2-fabric
		custom_hud: CustomHud 3.1.0+1.20
		debugify: Debugify 1.20.1+1.1
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		eatinganimationid: Eating Animation 1.9.4+1.20
		elementa: Elementa 590
		entity_model_features: Entity Model Features 0.2.13
		entity_texture_features: Entity Texture Features 4.4.4
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		essential: Essential 13437+deploy-staging+gd2fc09762
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.0
		fabric-api: Fabric API 0.86.1+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.62+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.9+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.2.1+1e61dba177
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.52+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.10+23d9108177
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.39+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.43+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.7+3265161977
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.9+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.49+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.1+6beca84877
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.19+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.1+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.1+9386d8a777
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.1+9172968c77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.34+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.28+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.0+cdf060b277
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.9.6+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		ferritecore: FerriteCore 6.0.0
		forcecloseworldloadingscreen: kennytv's epic force close loading screen mod for Fabric 2.1.1
		healthindicators: PlayerHealthIndicators 1.1.0
		held-item-info: Held Item Info 1.5.0
		inventoryhud: Inventory HUD + 3.4.13
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.23
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.3.1+1.20.1
			pride: Pride Lib 1.2.0+1.19.4
			spruceui: SpruceUI 5.0.0+1.20
		lazydfu: LazyDFU 0.1.3
		lithium: Lithium 0.11.2
		memoryleakfix: Memory Leak Fix 1.1.1
		minecraft: Minecraft 1.20.1
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		modmenu: Mod Menu 7.1.0
		morechathistory: MoreChatHistory 1.1.1
		neat: Neat 1.20-35-FABRIC
			fiber: fiber 0.23.0-2
		no_fog: No Fog 1.3.4+1.16.5-1.20.1
		notenoughanimations: NotEnoughAnimations 1.6.4
		oldpotions: Old Potions 2.3
			com_electronwill_night-config_core: core 3.6.0
			com_electronwill_night-config_toml: toml 3.6.0
		org_jetbrains_annotations: annotations 13.0
		perspectivemod: Perspective Mod Redux 0.0.5_01
		searchables: Searchables 1.0.1
		shulkerboxtooltip: Shulker Box Tooltip 4.0.4+1.20.1
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		sodium: Sodium 0.5.0
		starlight: Starlight 1.1.2+fabric.dbc156f
		totemcounter: TotemCounter 1.3.0+mc1.20
		ukulib: ukulib 0.7.0+1.20
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		universalcraft: UniversalCraft 277
		vigilance: Vigilance 284
		xaerominimap: Xaero's Minimap 23.5.0
		xaeroworldmap: Xaero's World Map 1.30.6
		yet_another_config_lib_v3: YetAnotherConfigLib 3.0.2+1.20
			com_twelvemonkeys_common_common-image: common-image 3.9.4
			com_twelvemonkeys_common_common-io: common-io 3.9.4
			com_twelvemonkeys_common_common-lang: common-lang 3.9.4
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4
		zergatulfreecam: FreeCam 2.0.0
		zoomify: Zoomify 2.10.0
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.4.1
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
	Launched Version: fabric-loader-0.14.21-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1650 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 536.40, NVIDIA Corporation
	Window size: 1920x991
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/1-19-ore-outline (1).zip (incompatible), file/Axolotl+Buckets.zip (incompatible), file/FreshAnimations_v1.8.1 (1).zip (incompatible), file/NoPumpkinBlur-rv1.3.zip (incompatible), file/SimParticles.zip (incompatible), file/The Big CIT pack (incompatible), file/better-flowers-e3620.zip (incompatible), file/Rainbow+XP+bar+and+ping+1.18.zip (incompatible), file/Better+Hotbar+1.19.zip (incompatible), file/undefined-Totem-pv9.zip (incompatible), minecraft:supporteatinganimation
	Current Language: en_us
	CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

**Comment by pajicadvance** [comment]
The mod "Custom Hud" is trying to get some debug data from Sodium, but is not able to and crashes the game, probably because it has not been updated to support the latest version of Sodium yet. You have to disable it until it receives an update.
