### ISSUE TITLE
Game crashes after opening video settings

### ISSUE THREAD

**Issue by zatalk** [jellysquid3/Sodium#1956]
### Bug Description

Just like the title says. Whenever I click on "video settings" the game crashes.

### Reproduction Steps

- Launch the game using sodium
- Click on "video settings"
- And Crash

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12270063/latest.log)

### Crash Report

[crash-2023-08-06_19.02.05-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12270060/crash-2023-08-06_19.02.05-client.txt)

**Comment by jellysquid3** [comment]
user error. update "Reeses' Sodium Options" or remove it.
