### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by its3than** [jellysquid3/Sodium#1959]
### Reproduction Steps

Launch the game and then try and load a world

### Log File

[crash-2023-08-06_21.01.40-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12271076/crash-2023-08-06_21.01.40-client.txt)

### Crash Report

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Mixin transformation of me.jellysquid.mods.sodium.client.gl.shader.ShaderLoader failed

**Comment by pajicadvance** [comment]
Immersive Portals is currently incompatible with Sodium 0.5.
