### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Nivirog** [jellysquid3/Sodium#1962]
### Bug Description

Game just crash at start

### Reproduction Steps

I launch my minecraft, wait till it get final loading and thats it

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12284050/latest.log)

### Crash Report

[crash-2023-08-07_21.23.48-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12284075/crash-2023-08-07_21.23.48-client.txt)

**Comment by purple512** [comment]
You've got one or more mods that are incompatible with Sodium 0.5. Dashloader is suspect, try disabling that. Otherwise, you might have to experiment with a binary search to find the broken mod. It's not a Sodium problem.
