### ISSUE TITLE
Crach 1.20.1 - Chunk build failed

### ISSUE THREAD

**Issue by TRemill** [jellysquid3/Sodium#1963]
### Reproduction Steps

Random

### Log File

[latest (5).log](https://github.com/CaffeineMC/sodium-fabric/files/12284264/latest.5.log)

### Crash Report

[crash-2023-08-07_21.43.24-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12284265/crash-2023-08-07_21.43.24-client.txt)

**Comment by MeeniMc** [comment]
You have a lot of mods, and the error indicates that at least one of them is incompatible with Sodium. From the error it looks like something that creates a visible avatar on screen. 

Follow procedure described in the issue template: 
> If the issue occurs only with other mods installed, have you determined which mods exactly are causing the problem? Please do not provide your entire mod list and expect us to be able to find which mods are causing the problem. You may try using a binary search (also known as "divide and conquer") to figure out which mods are problematic.

**Comment by jellysquid3** [comment]
Doesn't appear to be caused by Sodium. And the issue template was ignored, so we aren't going to check every mod individually to see what's causing it.
