### ISSUE TITLE
Crash when leaving the Resource Pack screen

### ISSUE THREAD

**Issue by ZestyBlaze** [jellysquid3/Sodium#1965]
### Bug Description

When leaving the Resource Pack screen, the game immediately crashes. When trying to reboot the game, it will crash before reaching the main menu. When disable Sodium and mods that depend on Sodium, it will no longer crash

### Reproduction Steps

1. Load Minecraft with same mods
2. Open Resource Packs
3. Close it without applying any packs
4. Crash

### Log File

https://pastebin.com/CPdGX1My

### Crash Report

https://pastebin.com/ZyE4HtPe

**Comment by purple512** [comment]
Dashloader is currently incompatible with Sodium 0.5, disable it.

**Comment by ZestyBlaze** [comment]
Ah thank you!
