### ISSUE TITLE
LambDynamicLights and Dynamic Fullbright stopped working properly

### ISSUE THREAD

**Issue by RisPNG** [jellysquid3/Sodium#1968]
### Bug Description

Dynamic lights that change the game light level while holding any item that produces light doesn't work for LambDynamicLights. The light level slider for Dynamic Fullbright also fails to change the overall game light level. Weirdly enough entity lit up normally.

This issue is originally reported on LambDynamicLights repository: https://github.com/LambdAurora/LambDynamicLights/issues/175
but it also affects Dynamic Fullbright: https://modrinth.com/mod/dynamic-fullbright

Demo Video: https://cdn.discordapp.com/attachments/771317560405917706/1138362416598618132/16914771445772843.mp4

**Comment by MeeniMc** [comment]
This is not a bug: mods that were designed for Sodium 0.4.10 require an update on their end to be compatible with Sodium 0.5. You will have to wait that LDL updates.

**Comment by LambdAurora** [comment]
This is not something Sodium itself needs to fix. Though I am slightly annoyed at not having a reliable injection point anymore, I wish Fabric API provided a proper API for lighting stuff as now the amount of injections are at least tripled (Sodium, FRAPI, vanilla).

**Comment by RisPNG** [comment]
> This is not something Sodium itself needs to fix. Though I am slightly annoyed at not having a reliable injection point anymore, I wish Fabric API provided a proper API for lighting stuff as now the amount of injections are at least tripled (Sodium, FRAPI, vanilla).

Ah that's a bummer to hear. I hope lighting stuff soon can rely on something solid. Thanks for the feedback.
