### ISSUE TITLE
Crashes on Quilt.

### ISSUE THREAD

**Issue by MagmaSlime123** [jellysquid3/Sodium#1969]
### Bug Description

Title. Quilt seems to hate 0.5.0.

### Reproduction Steps

Use the mod on Quilt.

For some reason neither the log or report mention Sodium, but Quilt's "beacon" or telemetry hates Sodium for whatever reason. Not sure how to fix this or who to report it to, no one's helping.

https://github.com/QuiltMC/quilt-loader/issues/343

### Log File

https://mclo.gs/2i2eiZP

### Crash Report

https://mclo.gs/pFIF6P6
(Generated via Prism Launcher)

**Comment by pajicadvance** [comment]
This has nothing to do with Quilt, the cause of the crash is DashLoader
