### ISSUE TITLE
Fabritone doesn't perform actions when sodium is installed

### ISSUE THREAD

**Issue by Titaniumtown** [jellysquid3/Sodium#197]
### Expected Behavior
Fabritone makes outlines of blocks it will interact with, and then begins performing the action specified.

### Actual Behavior
Fabritone makes outlines of blocks it will interact with, but no action is performed.

### Reproduction Steps
Install fabritone and sodium. do @mine birch_log (or any other command), and observe nothing happening.

### Attachments
![2020-07-27_12 19 00](https://user-images.githubusercontent.com/11786225/88565994-5fdcb300-d003-11ea-8cbd-9a875cd9f1bc.png)

### System Information
- Java Version: openjdk 14
- CPU: Xeon x5470 (oc'd to 4ghz)
- GPU: GTX 980 ti

**Comment by amnotbananaama** [comment]
Duplicate of #195

**Comment by Titaniumtown** [comment]
yea just saw that. lol
