### ISSUE TITLE
Getting this crash

### ISSUE THREAD

**Issue by Hexy32** [jellysquid3/Sodium#1970]
### Bug Description

Game keeps crashing with the reason: 
```
The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null
```

It stops crashing when I remove a single mod, then it crashes on the next launch even if I don't add the mod back.
Doesn't matter witch mod I remove, or if I add it back and remove a different mod, the same behavior remains.

### Reproduction Steps

1. Have the Quilt loader
2. Have my mods
3. Play the game

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12296957/latest.log)

### Crash Report

[crash-2023-08-08_20.03.47-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12296960/crash-2023-08-08_20.03.47-client.txt)

**Comment by purple512** [comment]
That's caused by Dashloader, which needs to be disabled or removed until it's been updated to be compatible with Sodium 0.5.
