### ISSUE TITLE
sodium causes loading screen to freeze (1.19.2)

### ISSUE THREAD

**Issue by andres1552** [jellysquid3/Sodium#1971]
### Bug Description

Hi, this is written with google translate because my english sucks (I speak Spanish).

When I try to start it freezes on the loading screen and does not advance, I saw that the problem is sodium because when I remove it it works normal.
the day before everything was working correctly the only thing that occurs to me is that I had a power outage while I was playing and that could have damaged something.

For what it's worth, my pc has an Intel Core i5-3470 and 8Gb of ram, I don't have a dedicated graphics card.

### Reproduction Steps

I can't think of how to do this part, it's my first time doing this so I'll just leave a screenshot with the mods I have installed. Sorry for the poor quality.

![mods](https://github.com/CaffeineMC/sodium-fabric/assets/82736512/914fd55f-e8e8-4003-99b7-53e5ecf56688)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12297584/latest.log)

### Crash Report

It didn't really throw me any report, I just closed it by force and when I went to check there was no report.

**Comment by Fnige** [comment]
Known issue, follow this to fix it: https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility#4th-generation-only-intel-hd-25004000
