### ISSUE TITLE
In Sodium 0.5.0 when you go to a world other than "world" all shaders are disabled and only the default shader works.

### ISSUE THREAD

**Issue by mifjpn** [jellysquid3/Sodium#1973]
### Bug Description

Sodium 0.5.0 has issues unlike 0.4.X. Using the Multivirse portal to navigate to a world other than the default world 'World' will disable all shaders, including the latest Kappa Shader V5.2, and only the default shader will work.
CPU:i9-10900f
RAM:32GB
GPU:RX6600Xt
World
![2023-08-10_19 08 31](https://github.com/CaffeineMC/sodium-fabric/assets/7693274/a3438b5f-1899-4fbe-ac44-ccc64c3e1c2e)

other world
![2023-08-10_19 08 53](https://github.com/CaffeineMC/sodium-fabric/assets/7693274/2d2c0912-a038-4e8e-8d0e-f234314269e5)

### Reproduction Steps

1.Create fabric（Vanilla） Instance on AtLuncher.
2.Add Sodium 0.5.0,Iris sheader,Sodium extra,Reese's sodium extra,and Fablic API
3.Set Kappa V5.2 Sheder
4.Login Paper(1.20.1 #110), and Waterfall server
5.World(default) login and screen shot  first picture.
6.Move  by Multivirse potal and (which is not shading world) screen shot second pictiure.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12312983/latest.log)

### Crash Report

Not crash

**Comment by Lolothepro** [comment]
Iris bug.

**Comment by jellysquid3** [comment]
Yeah this has nothing to do with Sodium, we don't implement shader packs -- it's a problem with Iris.
