### ISSUE TITLE
My instance crashes, when i turn sodium on

### ISSUE THREAD

**Issue by SinedKadis** [jellysquid3/Sodium#1975]
### Reproduction Steps

I just started the game and while loading its crashed. If I disable sodium, its works

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12315308/latest.log)

### Crash Report

[api.mclo.gs_1_raw_eiZPTaH.txt](https://github.com/CaffeineMC/sodium-fabric/files/12315310/api.mclo.gs_1_raw_eiZPTaH.txt)

**Comment by pajicadvance** [comment]
The crash is caused by outdated mods (Iris specifically).
