### ISSUE TITLE
Certain resource/texture packs have visual issues when using sodium.

### ISSUE THREAD

**Issue by Popcorncraft** [jellysquid3/Sodium#1978]
### Bug Description

There are several cases in which textures break or cause other issues when using the Faithless texture pack and sodium together. The three cases that I know of are nether portals with sections not rendering, pumpkin blocks appearing black, and two tall flower blocks preventing the block under from rendering (I did not have any two tall flower blocks on hand at the time of making this bug report). This issue has not crashed my game yet.

### Reproduction Steps

install sodium and the faithless texture pack
![2023-08-10_18 55 43](https://github.com/CaffeineMC/sodium-fabric/assets/87677381/32648c01-6d01-4025-a75a-60f7f32cf06e)
![2023-08-10_18 55 46](https://github.com/CaffeineMC/sodium-fabric/assets/87677381/41cc40c6-5f71-4d29-8041-1485ade64d41)
![2023-08-10_18 56 16](https://github.com/CaffeineMC/sodium-fabric/assets/87677381/379e800c-6e38-4826-9f16-94730a620a5f)
![2023-08-10_18 56 28](https://github.com/CaffeineMC/sodium-fabric/assets/87677381/582c5910-fdb1-492b-a18c-e544a185ad68)
![2023-08-10_18 56 46](https://github.com/CaffeineMC/sodium-fabric/assets/87677381/861d53b2-ac61-4372-9f0f-906598487066)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12317863/latest.log)

### Crash Report

[crash-2023-08-10_19.03.21-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12317870/crash-2023-08-10_19.03.21-client.txt)

**Comment by PepperCode1** [comment]
Faithless modifies terrain core shaders, which Sodium does not support.
