### ISSUE TITLE
Crash on Sodium 0.5.0

### ISSUE THREAD

**Issue by TecEash1** [jellysquid3/Sodium#1979]
### Bug Description

After joining a world the game says 'saving world' and crashes. This also applies for servers.
This issue was not present in ``sodium-fabric-mc1.20-0.4.10+build.27``.
To update I to the newer version of sodium before hand I tried updating `sodium extra`, `reeses sodium options` and `iris` as well. Beforehand along with sodium and my other mods the mods had these versions installed:
- iris-mc1.20-1.6.4
- reeses_sodium_options-1.5.1+mc1.20-build.74
- sodium-extra-0.4.20+mc1.20-build.103

I assume my issue is to do with sodiums newer version having compatibility issues with some of my other mods. I am just not sure which ones. Any help would be much appreciated, thank you!

### Reproduction Steps

Install fabric 1.20.1 with the fabric loader 0.14.21
Install the mods listed in the log file
Run the Game

*The mods surpased the upload limit...*

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12321329/latest.log)

### Crash Report

[crash-2023-08-11_13.10.48-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12321337/crash-2023-08-11_13.10.48-client.txt)

**Comment by TecEash1** [comment]
[mods.zip](https://github.com/CaffeineMC/sodium-fabric/files/12321480/mods.zip)... Sorry I just realised that wasnt all the mods

**Comment by Fnige** [comment]
Bobby needs to be updated to fix its compatibility with sodium

**Comment by TecEash1** [comment]
O, thank you so much! Ill try that now!

**Comment by TecEash1** [comment]
I believe I had the correct version installed before unfortunately:
<img width="414" alt="image" src="https://github.com/CaffeineMC/sodium-fabric/assets/92249532/9c693215-d2ee-47c6-8e9c-5cb771b33e3c">

**Comment by Fnige** [comment]
Bobby isnt compatible with sodium 0.5.0 currently. It would need to be updated to fix that (The fix is currently to remove bobby or downgrade sodium)

**Comment by TecEash1** [comment]
o ok got it, thank you!
Hope you have a nice day!

**Comment by Altirix** [comment]
> Bobby needs to be updated to fix its compatibility with sodium

Bobby isn't updated yet. There is a PR that offers compatibility but I believe it still has the issue of some chunks getting renderer before light data is ready. Personally I'd stick to 0.4.10 until it's officially released or use 0.5.0 without Bobby. But no one stops you testing development builds, but understand they are provided without support

**Comment by TecEash1** [comment]
got it, ty! I think ill remove bobby for now. Thanks again!

**Comment by Dragonsrule3194** [comment]
I have this exact problem and I don't have that mod installed

**Comment by TecEash1** [comment]
> I have this exact problem and I don't have that mod installed

I would recommend filing a new [crash report](https://github.com/CaffeineMC/sodium-fabric/issues/new?assignees=&labels=S-needs-triage&projects=&template=bug_report.yml) and filling in the steps in it. That could help fix your issue!
