### ISSUE TITLE
Add support for multiple graphics cards

### ISSUE THREAD

**Issue by kennark** [jellysquid3/Sodium#198]
I just tried this out. On my local server I get good frames, near 60, but it only uses my integrated UHD 620 graphics.

On vanilla it automatically takes my Geforce MX150 graphics, and gets 40-60 fps

or is there any way i already can do it manually?

**Comment by ghost** [comment]
https://www.quora.com/How-do-I-make-Minecraft-use-my-Nvidia-GPU#:~:text=Select%20Manage%203D%20Settings%20on,click%20the%20Program%20Settings%20tab.

**Comment by mrmangohands** [comment]
This isn't something we can control within Sodium.
