### ISSUE TITLE
Crash when I log in a server / open a world

### ISSUE THREAD

**Issue by ItzBlueberry** [jellysquid3/Sodium#1980]
I downloaded the new sodium update and when i tried to join it would always crash.
These are the mods im using
![image](https://github.com/CaffeineMC/sodium-fabric/assets/90847592/984b947d-0b43-4d0a-a3da-43a168693410)

**Comment by pajicadvance** [comment]
Please choose the correct issue template and fill out all the required info...

**Comment by ItzBlueberry** [comment]
> Please choose the correct issue template and fill out all the required info...

dawg just is it getting fixed or nah. So i can remove the mod

**Comment by douira** [comment]
We can't help you without the required information.

**Comment by TheUserCreated** [comment]
> dawg just is it getting fixed or nah. So i can remove the mod

There's nothing to fix. The problem is almost certainly with your installed mods. Some of them aren't compatible with 0.5

**Comment by Dragonsrule3194** [comment]
well which ones are incompatible, I have the same problem and all my mods are up to date.
