### ISSUE TITLE
Jarring Jitter when looking around with sodium 0.5 on nvidia

### ISSUE THREAD

**Issue by Teh404Gal** [jellysquid3/Sodium#1981]
### Bug Description

today i updated sodium 0.5 and with it notices alot of jittering that wasnt there, for now i have downgraded to 0.4.10
this jitter is caused with vsync on and is fixed with disabling vsync, the jitter only happens when looking around and is not present when standing still/moving
im on debian linux with the nvidia 525.125.06 drivers, gnome 43
this bug might be related to the nvidia changes

### Reproduction Steps

1. update to sodium 0.5
2. enable vsync
3. look around 
4. lots of jittering

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12323620/latest.log)

### Crash Report

[crash-2023-08-11_17.44.33-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12323619/crash-2023-08-11_17.44.33-client.txt)

**Comment by sydist** [comment]
Couldn't reproduce on Windows, NVIDIA GTX 1660 Ti and driver version 536.99

**Comment by jellysquid3** [comment]
Does this still happen with [Sodium 0.5.1](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.1)?

**Comment by jellysquid3** [comment]
I'm not fixing issues with the NVIDIA graphics driver. They have wasted too many of my hours and this issue probably has literally nothing to do with Sodium, just like all the other bugs their terribly hacked together driver has.
