### ISSUE TITLE
When i join in aserver/world, minecraft crashes

### ISSUE THREAD

**Issue by TheLogicalFounder** [jellysquid3/Sodium#1982]
### Bug Description

So, when i first installed the yupdate of the mod and joined a world, it crashed instantly. i tried to rejoin a second time but it kept only crashing MC over and over. 

i'll paste over here the error log that appeared me when it crashed itself:
<img width="373" alt="image" src="https://github.com/CaffeineMC/sodium-fabric/assets/69966423/88791b4a-cf44-4831-abf8-d81bf49afa90">

### Reproduction Steps

To reproduce the bug, you have to first 

- Install the version 0.5.0 of Sodium.
- Open Minecraft with the latest version of Fabric
- Join a World
- Bug Appears

Optional steps

- Go on Sodium's Github
- Report about the bug
- Wait

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12324709/latest.log)

### Crash Report

[crash-2023-08-11_21.59.24-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12324713/crash-2023-08-11_21.59.24-client.txt)

**Comment by pajicadvance** [comment]
Update your mods.

**Comment by Dragonsrule3194** [comment]
I have the same problem, all of my mods are update to date
