### ISSUE TITLE
Minecraft chrashes at launch on Quilt

### ISSUE THREAD

**Issue by MidyGamy** [jellysquid3/Sodium#1986]
### Bug Description

My game crashes when loading the main menu 2/3 of the time

### Reproduction Steps

- Intall the 0.5.0 version of Sodium with Quilt
- Install some other mods
- Launch the game

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12326504/latest.log)

### Crash Report

[crash-2023-08-12_05.30.51-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12326503/crash-2023-08-12_05.30.51-client.txt)

**Comment by purple512** [comment]
You need to disable or remove Dashloader, it's not compatible with Sodium 0.5.

**Comment by MidyGamy** [comment]
oh ok
