### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 129

### ISSUE THREAD

**Issue by AdrielPalomo9** [jellysquid3/Sodium#1989]
### Bug Description

Hello,
We run a Minecraft server with quite a few people on it. We use your mod on our modpack and we have been experiencing the same error (java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 129) I have asked everyone in the server to send me their crash reports and I have a huge list of different peoples crashes. No matter what format we have our mods weather server side or client side we always get the same error from everybody.

We thought it would be vinery so we downgraded that, We then got supplementaries errors and downgraded that. We spoke with the people at Xeros and they say it is not them. I see a few people have this error on the issues tab but nothing that can really help us.

### Reproduction Steps

Some people say they walk around and it happens. Others say they open the map and hover over a specific area. Ultimately we really don't know how to reproduce because it just happens randomly.

### Log File

ill update with new log files as I get them.

https://mega.nz/folder/z9JVnJSS#cCdpsOhDZNGSyG8B-AT4Ew

### Crash Report

Here are a few crash reports. Ill update it with new ones soon. This is as of today.

https://mega.nz/folder/z9JVnJSS#cCdpsOhDZNGSyG8B-AT4Ew

**Comment by Octol1ttle** [comment]
These crashes do not appear to be directly related to Sodium and the stacktrace points to Minecraft code. Try installing [MixinTrace](https://modrinth.com/mod/mixintrace), with that mod you can see what mods injected their code into Minecraft's code when the game crashes. This may help you in finding the faulty mod

**Comment by MeeniMc** [comment]
This can happen when the client do not have the same modset as the server. Likelihood of this being related to Sodium is low.
