### ISSUE TITLE
EXTREMELY broken not sure whats wrong

### ISSUE THREAD

**Issue by Hawaiikilauea7** [jellysquid3/Sodium#199]
![2020-07-28_17 20 35](https://user-images.githubusercontent.com/68917354/88694205-1cb03c00-d0f8-11ea-955c-f3328f5a15c6.png)
![2020-07-28_17 21 54](https://user-images.githubusercontent.com/68917354/88694208-1de16900-d0f8-11ea-8dc3-a8b18e2771df.png)

**Comment by ghost** [comment]
you manually disabled the driver blacklist, change render backend to 2.0/3.0 instead of 4.3

**Comment by jellysquid3** [comment]
Caused by #179.
