### ISSUE TITLE
Sodium crashes Minecraft When falling blocks

### ISSUE THREAD

**Issue by EonSkii** [jellysquid3/Sodium#1990]
### Bug Description

My game crashes when i have sodium installed, and when my game renders a falling block, it crashes simply

### Reproduction Steps

Sodium 0.5.0 fcrashes when it renders a falling block

### Log File

[crash-2023-08-10_00.16.31-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12327107/crash-2023-08-10_00.16.31-client.txt)

### Crash Report

crashing

**Comment by pajicadvance** [comment]
![image](https://github.com/CaffeineMC/sodium-fabric/assets/32738446/a7b2b3db-e5c3-4871-856d-3970eb7ec57d)
