### ISSUE TITLE
Crashing on loading a world

### ISSUE THREAD

**Issue by WitherKing20** [jellysquid3/Sodium#1991]
### Bug Description

So when I load up any of my singleplayer worlds in Minecraft 1.20.1 with sodium 0.5.0 using Fabric 0.84.0 and Iris 1.6.5 the world crashes

### Reproduction Steps

Well i have the following mods installed 
- cloth-config-11.0.99-fabric
- entity_model_features_fabric_1.20-0.2.11
- entity_texture_features_fabric_1.20-4.4.4
- fabric-api-0.84.0+1.20.1
- invhud.fabric.1.20-3.4.13
- iris-mc1.20.1-1.6.5
- lambdynamiclights-2.3.1+1.20.1
- litematica-fabric-1.20.1-0.15.0
- logical_zoom-0.0.20
- malilib-fabric-1.20.1-0.16.0
- minihud-fabric-1.20.1-0.27.0
- physics-mod-pro-v155-fabric-1.20
- sodium-fabric-mc1.20.1-0.5.0
- soundphysics-fabric-1.20.1-1.1.1
 
 Minecraft Version: 1.20.1
Using the normal Minecraft Launcher

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12327113/latest.log)

### Crash Report

[crash-2023-08-12_20.05.17-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12327121/crash-2023-08-12_20.05.17-client.txt)

**Comment by pajicadvance** [comment]
Update Physics Mod Pro to the latest version (v158).
