### ISSUE TITLE
Sodium not rendering blocks when updating to 0.5.0

### ISSUE THREAD

**Issue by TheWiseMan** [jellysquid3/Sodium#1992]
### Bug Description

I have been using Sodium 0.4.10 for fabric for a few months, and it worked perfectly fine.
However, when updating to the latest version (0.5.0), none of the blocks are rendered (particles work fine).
Note: going back to 0.4.10 fixes this and renders as usual.

### Reproduction Steps

With an instance with Sodium 0.4.10 :
- Upgrade to Sodium 0.5.0, and verify that the rendering is blank
- Downgrade back to Sodium 0.4.10 to verify that everything works

### Log File

.

### Crash Report

.

**Comment by Felix14-v2** [comment]
Please, attach your latest.log file. It is impossible to determine the cause without any technical info.

**Comment by Timolino456** [comment]
You are likely using Bobby and/or Farsight. Remove the former and/or update the latter.
