### ISSUE TITLE
[ERROR: Crashes on startup] exception thrown net.minecraft.class_148: Rendering overlay

### ISSUE THREAD

**Issue by zndrmn** [jellysquid3/Sodium#1996]
### Bug Description

Crashes on startup, removing a resource pack from options.txt sometimes fixes the problem

I originally reported this to RaphiMC/ImmediatelyFast/issues/104 because removing the mod seems to fix the issue, though this could just be because the resource packs have to reload themselves.

### Reproduction Steps

It happens kinda randomly, I believe it has something to deal with resource packs and GUI's
Once it starts crashing, it'll keep crashing till I remove a resource pack from the options.txt file
Also can occur whenever a server has a resource pack that you have to use, and when you leave sometimes it'll crash and then you'll have to remove a resource pack.
I might do more testing 

### Log File

[latest.log](https://gist.github.com/zndrmn/0a881fbbb5d2959a59f573aa487f9446#file-gistfile1-txt)

### Crash Report

[crash-2023-08-12_04.19.32-client.txt](https://gist.github.com/zndrmn/8f6a9ad8e2f89dab0a5ac1074abdaaf6#file-gistfile1-txt)

**Comment by Lolothepro** [comment]
Remove dashloader

**Comment by zndrmn** [comment]
to see if the problem continues? or is dashloader known to do this now
