### ISSUE TITLE
I have a title when starts minecraft with some strange symbols 

### ISSUE THREAD

**Issue by PoPCornPlay** [jellysquid3/Sodium#1998]
### Bug Description

Hi! I updated sodium of Fabric 1.20.1 to 0.5.0 and also sodium extra, indium and Reese's Sodium options because it's support sodium 0.5.0 . BUT! when I launched minecraft [THIS](https://imgur.com/6TYI3Vo) appeared. [Here](https://imgur.com/MAaWoZK) my mod's list

### Reproduction Steps

Just [download](https://drive.google.com/file/d/1-UPIsnB4d7WzvHHyIB6b5vjRCXkSgEoM/view?usp=sharing) my modpack that a use and it this bug will appear 

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12329322/latest.log)

### Crash Report

It didn't appeared

**Comment by Fnige** [comment]
Update iris
