### ISSUE TITLE
[Reopen] Crash on load / create world (with only 6 mods)

### ISSUE THREAD

**Issue by lnminh1411** [jellysquid3/Sodium#2000]
### Bug Description

When loads up a world or create a world, Minecraft crash (likely to be Sodium)
Every single mods re-downloaded, Graphic driver on lastest version and with only 6 mods

### Reproduction Steps

Just open a world with the following mods:
fabric-api 0.86.1+1.20.1
indium 1.0.23+mc1.20.1
ocrenderfix_sodium 1.2.0
sodium 0.5.0
sodium-extra 0.5.0+mc1.20.1-build.111
sodium-shadowy-path-blocks-3.2.0

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12329731/latest.log)

### Crash Report

[crash-2023-08-13_21.35.02-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12329732/crash-2023-08-13_21.35.02-client.txt)

**Comment by Octol1ttle** [comment]
> The mod "Sodium Occlusion Culling Fix" is no longer needed starting from Sodium 0.5.

Please do not open multiple issues when the solution has already been provided to you.
