### ISSUE TITLE
Game keeps crashing whenever I load into a world

### ISSUE THREAD

**Issue by SimplyGold0** [jellysquid3/Sodium#2002]
### Bug Description

When I start loading into a world the game crashes once it says "Saving world"

### Reproduction Steps

Download most recent version of Sodium
Open Minecraft
Go to singleplayer
Load world

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12330327/latest.log)

### Crash Report

[crash-2023-08-13_13.08.35-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12330329/crash-2023-08-13_13.08.35-client.txt)

**Comment by pajicadvance** [comment]
Dropz and Rayon are not compatible with Sodium 0.5 at the moment.

**Comment by SimplyGold0** [comment]
> Dropz and Rayon are not compatible with Sodium 0.5 at the moment.

Ok, thank you
