### ISSUE TITLE
being given prompt upon launching game

### ISSUE THREAD

**Issue by ralixia** [jellysquid3/Sodium#2003]
### Bug Description

I am going to upload a lot of screenshots, so if I mention a screenshot in the bug report, please reference it.

I recently installed sodium 0.5.0 for Minecraft 1.20.1 using the latest fabric version available on Curseforge. However, upon launching the game, I am greeted with the GUI in screenshot1.png.
![screenshot1](https://github.com/CaffeineMC/sodium-fabric/assets/142132983/a7336fd3-c43e-45a0-a836-59e2ed3cea88)
Clicking the button on the left opens the download page for sodium 0.4.10.
Clicking the button on the right or hitting ESC closes the game.
F3+C is capable of crashing the game, but does not generate a crash report. (I used Curseforge for this, so maybe that's why?)

Here is the list of mods I used: 
![modslist](https://github.com/CaffeineMC/sodium-fabric/assets/142132983/4755c0b4-aa91-41df-9b69-3e9cd3adc949)

Fabric version 0.14.22

### Reproduction Steps

1. install the latest version of fabric and fabric API for Minecraft 1.20.1
2.  install every mod in the screenshot above
3. open Minecraft

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12330678/latest.log)

### Crash Report

There is no crash report in the directory because the game doesn't crash. Crashing the game with F3+C works, but doesn't generate a crash report.

**Comment by douira** [comment]
You need to update Iris
