### ISSUE TITLE
Chunks do not render properly when single fog is turned off

### ISSUE THREAD

**Issue by cloudy1552** [jellysquid3/Sodium#2006]
### Bug Description

Set single fog in the render tab off, and I can only see one chunks.

### Reproduction Steps

Just set single fog off

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12333955/latest.log)

### Crash Report

[crash-2023-08-14_19.54.36-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12333972/crash-2023-08-14_19.54.36-client.txt)

**Comment by pajicadvance** [comment]
Fixed in commit https://github.com/CaffeineMC/sodium-fabric/commit/6b02e258ca5f2faa115a634f8ada84d3f95a20cd and will be in Sodium 0.5.2.

**Comment by TyIuNnG** [comment]
![image](https://github.com/CaffeineMC/sodium-fabric/assets/92113862/cc1f6b47-94ae-4a7f-990c-bff44a14f32a)

using 0.5.2, although not 1 sub-chunk, but unlike before where you can see the whole chunk no matter what y level

**Comment by jellysquid3** [comment]
that is exactly the behavior as in vanilla.

**Comment by TyIuNnG** [comment]
hmm strange, I believe it wasn't like that before
at least for 0.4.10 I can see the terrain still with any y level
![image](https://github.com/CaffeineMC/sodium-fabric/assets/92113862/0ffb082f-af06-499e-a3d1-e01661068a49)
