### ISSUE TITLE
"Golems Galore Mod" crash 1.17.1

### ISSUE THREAD

**Issue by Mugiwara-no-Sonix** [jellysquid3/Sodium#2010]
### Bug Description

entity "Obama_Prism_Golem" crash in "Golems Galore Mod"

### Reproduction Steps

/summon golemsgalore:obama_prism_golem

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12337443/latest.log)

### Crash Report

[crash-2023-08-14_13.39.29-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12337451/crash-2023-08-14_13.39.29-client.txt)

**Comment by Timolino456** [comment]
Install Indium

**Comment by jellysquid3** [comment]
ಠ_ಠ
