### ISSUE TITLE
Ticking Entity Crash

### ISSUE THREAD

**Issue by KeriiAgain** [jellysquid3/Sodium#2013]
### Bug Description

Ticking entity causes a crash.

### Reproduction Steps

Load into world 
break block that drops item or go into creative menu and drop an item
causes crash

### Log File

[Prism Launcher version 7.2 (officia.txt](https://github.com/CaffeineMC/sodium-fabric/files/12338468/Prism.Launcher.version.7.2.officia.txt)

### Crash Report

[crash-2023-08-14_12.27.03-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12338464/crash-2023-08-14_12.27.03-client.txt)

**Comment by Lolothepro** [comment]
dropz bug
