### ISSUE TITLE
bm revelations crash on startup

### ISSUE THREAD

**Issue by Mufi432** [jellysquid3/Sodium#2015]
### Bug Description

its just crash when i start the modpack( it have nothing to do with sodium)

### Reproduction Steps

1.download the modpack
2.start it
3. it crashed

### Log File

[minecraft-exported-crash-info-2023-08-15T14-17-31.zip](https://github.com/CaffeineMC/sodium-fabric/files/12344561/minecraft-exported-crash-info-2023-08-15T14-17-31.zip)

### Crash Report

[minecraft-exported-crash-info-2023-08-15T14-17-31.zip](https://github.com/CaffeineMC/sodium-fabric/files/12344637/minecraft-exported-crash-info-2023-08-15T14-17-31.zip)

**Comment by Mufi432** [comment]
sorry for the wrong label i forgot how to  add one

**Comment by hexadecimal233** [comment]
try updating your graphics driver?

**Comment by Mufi432** [comment]
ill try

**Comment by Mufi432** [comment]
still doesnt work(i updated with ccleaner)

**Comment by pajicadvance** [comment]
Issues with Rubidium should be reported to their own issue tracker. We have nothing to do with it.
