### ISSUE TITLE
Crashing after updating to Sodium v0.5.1

### ISSUE THREAD

**Issue by TecEash1** [jellysquid3/Sodium#2017]
### Bug Description

After updating sodium to the latest version and iris to the latest version the game now appears to be crashing. I am not sure why this is.

### Reproduction Steps

Install the mods from the log file, select play.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12361148/latest.log)

### Crash Report

[crash-2023-08-16_16.42.53-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12361151/crash-2023-08-16_16.42.53-client.txt)

**Comment by Octol1ttle** [comment]
You need to update your mods, at the very least Sodium Extra.
