### ISSUE TITLE
Latest Version Crash [v0.5.2] [1.20.1] [Fabric]

### ISSUE THREAD

**Issue by EnderGirl1500** [jellysquid3/Sodium#2020]
### Bug Description

Crash on launch after updating Sodium, Indium and Iris.

### Reproduction Steps

1. Update Sodium and other related mods
2. Launch Game
3. Crash

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12374353/latest.log)

### Crash Report

[crash-2023-08-18_02.37.58-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12374354/crash-2023-08-18_02.37.58-client.txt)

**Comment by pajicadvance** [comment]
It seems like the mod Valkyrien Skies doesn't work with Sodium 0.5 and above: https://github.com/ValkyrienSkies/Valkyrien-Skies-2/issues/556. You'll have to wait for the mod author to update the mod to support the latest version of Sodium.
