### ISSUE TITLE
After updating the Sodium (from 0.5.1 to 0.5.2), the foliage of the trees shines through (fast and fancy graphics)

### ISSUE THREAD

**Issue by holdos** [jellysquid3/Sodium#2023]
### Bug Description

In foliage textures (when animating shaders), the pixel is translucent

![2023-08-18_12 56 37](https://github.com/CaffeineMC/sodium-fabric/assets/136592753/d82fc112-2bcb-437b-b88e-dc52ea7c883b)
![2023-08-18_12 56 39](https://github.com/CaffeineMC/sodium-fabric/assets/136592753/68b5d9ea-25de-4e26-9a4d-d7bbd698d9b3)
![2023-08-18_12 56 40](https://github.com/CaffeineMC/sodium-fabric/assets/136592753/d544d63a-1a79-41c7-a7aa-2c4cd596908d)

### Reproduction Steps

When the shader foliage blending setting is enabled (Complementary v4.7.2 ).
Appeared after the update of Sodium and Iris Shaders (there was nothing like this before)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12377504/latest.log)

### Crash Report

[launcher.log](https://github.com/CaffeineMC/sodium-fabric/files/12377526/launcher.log)

NVIDIA Graphics Driver v539.99 (!)
GPU: NVIDIA GeForce GTX 1050Ti
CPU: Intel(R) Core(TM) i5-3570 @ 3.40GHz
Minecraft Launcher: Legacy Launcher (LL) (https://llaun.ch/)

**Comment by MeeniMc** [comment]
I had that in the past and is caused by using waving leaves with certain shaders. That may be an issue that is more related to Iris than Sodium or even with the particular shader.

**Comment by douira** [comment]
Does this also happen when shaders are disabled (and iris is not installed)?

**Comment by holdos** [comment]
> Does this also happen when shaders are disabled (and iris is not installed)?

I checked on OptiFine, on past version of iris with solium - there was nothing like that

**Comment by douira** [comment]
Does it happen on Sodium 0.5.2 without Iris?

**Comment by ruslan29329** [comment]
> Does it happen on Sodium 0.5.2 without Iris?

How?

**Comment by holdos** [comment]
> Does it happen on Sodium 0.5.2 without Iris?

I didn't understand the question. I will answer differently:
1. I can't run shaders without iris (or don't know how)
2. When I turn shaders off everything is fine

**Comment by douira** [comment]
Then this issue is not in the right place being that this repo concerns only Sodium and not Iris. Instead it might be of interest to Iris or the shaderpack itself, you can make an issue there.

**Comment by AstreaTSS** [comment]
Well, yes, the ideal is to not have Iris running at all. If this happens in Minecraft with default textures and Sodium, it's likely a bug, but it really sounds like this is Iris's or the shader pack's fault.

**Comment by holdos** [comment]
Sorry guys. I didn't know where to write. Wanted to do better
