### ISSUE TITLE
OpenGL error when starting only with Sodium

### ISSUE THREAD

**Issue by Kolya-gfx** [jellysquid3/Sodium#2024]
### Bug Description

When launching Minecraft, the game starts, but with 1 FPS, as (if you look at the logs) a constant OpenGL error is being spammed.

A message like this was spammed 20,000 times in 5 seconds:
OpenGL debug message: id=1282, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_OPERATION error generated. Function glPopAttrib is deprecated and not available in preview contexts.

I've tried everything I can, reinstalled, updated, checked, but nothing helps. Please help, I would be grateful.
(This text is translated through ChatGPT.)

### Reproduction Steps

Minecraft 1.20.1
Version MultiMC: 0.7.0-3775
Version Fabric Loader: 0.14.22
Version Sodium: 0.5.2
In the pinned files, there are logs and crash reports, neither of which use FabricAPI and Malilib, but I tested with them for errors and the result is the same. I am providing you with their versions as well.
Version FabricAPI: 0.87.0+1.20.1
Version Malilib: 0.16.1
Version Nvidia Video card(NVIDIA GeForce GTX 1650): 536.99
Version AMD Processor(AMD Ryzen 5 3550H with Radeon vega Mobile Gfx): 23.7.2 

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12378361/latest.log)
Log MultiMC: https://paste.ee/p/PDDRL

### Crash Report

[crash-2023-08-18_13.37.51-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12378413/crash-2023-08-18_13.37.51-client.txt)

**Comment by pajicadvance** [comment]
Do you have any external applications that add in-game overlays? They are usually the culprit of this issue.

**Comment by Kolya-gfx** [comment]
> Есть ли у вас какие-либо внешние приложения, добавляющие внутриигровые оверлеи? Обычно они являются виновниками этой проблемы.


Wow! Thank you so much, the problem indeed turned out to be in one of such applications, to be precise, MSIAfterburner. Many thanks! 🧡

**Comment by Kolya-gfx** [comment]
> Do you have any external applications that add in-game overlays? They are usually the culprit of this issue.


Wow! Thank you so much, the problem indeed turned out to be in one of such applications, to be precise, MSIAfterburner. Many thanks! 🧡

**Comment by Kolya-gfx** [comment]
Thanks! 🧡
