### ISSUE TITLE
Sodium 5.2 Quilt

### ISSUE THREAD

**Issue by voidxO7** [jellysquid3/Sodium#2025]
On [Modrinth](https://modrinth.com/mod/sodium/versions?l=quilt&g=1.20.1), the following versions of Sodium show Quilt support for Minecraft 1.20.1, but Sodium 5.2 doesn't.

0.4.10
0.5.0
0.5.1

Why is this? Will it still work using the [Quilted Fabric API](https://github.com/QuiltMC/quilted-fabric-api)?

**Comment by pajicadvance** [comment]
It will work. I'm not sure why the tag is gone, probably an error on our side. We'll see about putting it back.
