### ISSUE TITLE
Stack Smashing detected with Sodium 5.2

### ISSUE THREAD

**Issue by Verdigris7** [jellysquid3/Sodium#2027]
### Bug Description

Game won't launch, says stack smashing detected.

### Reproduction Steps

Game stopped launching after updating to 5.2, the log told me to make a bug report, 5.1 works fine. I have over 200 mods installed and am using Linux Mint xfce. (Thanks to sodium and other performance mods I easily get 60 fps thank you for making this mod.)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12384776/latest.log)

### Crash Report

Crash report didn't generate.

**Comment by Fnige** [comment]
Im pretty sure this is an LWJGL/GLFW issue of which the solution is to use the system installation of GLFW **(After installing GLFW 3.3.7 or later)** or using LWJGL 3.3.2 instead of LWJGL 3.3.1
