### ISSUE TITLE
粘液块透视

### ISSUE THREAD

**Issue by typingggg** [jellysquid3/Sodium#2028]
### Request Description

假如用粘液块或蜂蜜块造一堵墙，在后面贴着再造一堵，则后面粘液块或蜂蜜块不会显示
![2023-08-20_12 42 58](https://github.com/CaffeineMC/sodium-fabric/assets/137679281/013cd453-7efb-4d39-a26e-0033556e1bd5)
![2023-08-20_12 45 50](https://github.com/CaffeineMC/sodium-fabric/assets/137679281/6452736e-b56a-4a41-9fc8-24e234d987e9)

**Comment by purple512** [comment]
Unfortunately this is a Sodium limitation with the way it handles translucency and a known issue (#38). A fix is being worked on but it's very slow going. The limitation has always existed but it got worse in version 0.5.x which is unfortunate but there's nothing that can be done about it.

Google translate: 
不幸的是，这是 Sodium 处理半透明方式的限制和一个已知问题 (#38)。 修复工作正在进行中，但进展非常缓慢。 该限制一直存在，但在 0.5.x 版本中情况变得更糟，这是不幸的，但对此无能为力。

**Comment by Noryea** [comment]
与已知的 #2018 重复，实际上需要根治的问题是 Issue #38
