### ISSUE TITLE
Sodium 5.0+ is broken on Steam Deck/AMD Linux

### ISSUE THREAD

**Issue by bonclide** [jellysquid3/Sodium#2029]
### Bug Description

When using 5.0+ on Steam Deck, the game will crash. Not sure what causes this, but I have to go to 4.0 to fix this.
I think it's referencing windows stuff, things that don't exist in Linux. You might need to fix this.

### Reproduction Steps

1.  Launch game
2. Go to mod menu or configure a mod
3. Crashed

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12389167/latest.log)

### Crash Report

[hs_err_pid299.txt](https://github.com/CaffeineMC/sodium-fabric/files/12389147/hs_err_pid299.txt)

**Comment by jellysquid3** [comment]
Why do you think Sodium is referencing "only Windows" stuff? This is caused by https://github.com/isXander/YetAnotherConfigLib/issues/101, not Sodium.
