### ISSUE TITLE
FPS Doesn't increase

### ISSUE THREAD

**Issue by WyldWaffles** [jellysquid3/Sodium#203]
I downloaded and followed correct steps but the FPS won't increase. IT seems to just hover at about 25-30 FPS

**Comment by amnotbananaama** [comment]
The GitHub Issue tracker is for bugs and is not intended as a support site. I suggest joining [JellySquid's Hideout](https://jellysquid.me/discord) and providing screenshots of the [Profiler Graph](https://minecraft.gamepedia.com/Debug_screen#Profiler_graph) and [Frame Time Graph](https://minecraft.gamepedia.com/Debug_screen#Frame_time_graph) during normal gameplay, in the `#tech-support` channel.
