### ISSUE TITLE
resource pack image transparent support

### ISSUE THREAD

**Issue by HissingRat** [jellysquid3/Sodium#2030]
### Request Description

Some images are transparent in the resource pack but have no effects in the game.
![oak_leaves](https://github.com/CaffeineMC/sodium-fabric/assets/84263094/4cf6111e-19ea-40ab-baf3-ab00376f7503)
![2023-08-21_20 34 08](https://github.com/CaffeineMC/sodium-fabric/assets/84263094/01559e46-baf9-4a9d-bf59-b81451fe36ff)

**Comment by pajicadvance** [comment]
Please use the correct issue template if you want to report a bug.
