### ISSUE TITLE
Building chunk meshes still happen in 0.5.2

### ISSUE THREAD

**Issue by MrSam7K** [jellysquid3/Sodium#2032]
### Reproduction Steps

I am not actually sure when or how it happens since it happens randomly, atleast for me. It just crashes in middle of nowhere it seems like.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12406106/latest.log)

### Crash Report

[crash-2023-08-22_10.17.20-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12406074/crash-2023-08-22_10.17.20-client.txt)

**Comment by purple512** [comment]
Some kind of compat issue with the mod Figura, as it's dying while trying to render a player head with missing fields that are added by that mod. [Here's the relevant line](https://github.com/FiguraMC/Figura/blob/ca74842ca2dcdfa53d465712d0642364be5f8268/common/src/main/java/org/figuramc/figura/mixin/render/renderers/SkullBlockRendererMixin.java#L93C8-L93C8) for anyone investigating.

Disable Figura to see if it resolves the crash.

**Comment by purple512** [comment]
Oh yeah def Figura, [here's the bug report](https://github.com/FiguraMC/Figura/issues/50) - they seem to be aware of it and looking into it.

**Comment by alekso56** [comment]
> Oh yeah def Figura, [here's the bug report](https://github.com/FiguraMC/Figura/issues/50) - they seem to be aware of it and looking into it.

That issue is closed, please [use dev builds before reopening issues.](https://github.com/FiguraMC/Figura/actions/runs/5931103227) 
(seeing as reporter here uses the release build with the bug in it)
