### ISSUE TITLE
Crash on world load

### ISSUE THREAD

**Issue by skoove** [jellysquid3/Sodium#2034]
### Bug Description

When attempting to load into a game, the game crashes with the attached log.

### Reproduction Steps

1. Launch mine craft
2. Load any world or server

### Log File

[Log](https://github.com/CaffeineMC/sodium-fabric/files/12416107/ixeCw8K.txt)

### Crash Report

[Crash report](https://github.com/CaffeineMC/sodium-fabric/files/12416124/crash-2023-08-23_16.45.33-client.txt)

**Comment by TheUserCreated** [comment]
One or more of your mods is not compatible with the version of sodium you're using. I think chunks fade in is out of date (you need 1.0.2)

**Comment by skoove** [comment]
> One or more of your mods is not compatible with the version of sodium you're using. I think chunks fade in is out of date (you need 1.0.2)

Yeah, that was it, thanks
