### ISSUE TITLE
Suggestion : Mangrove roots culling

### ISSUE THREAD

**Issue by pingouyn** [jellysquid3/Sodium#2035]
### Request Description

Hi, fps and stuttering are notoriously bad in mangrove swamp biomes.  After testing I came to the conclusion it was due to the presence of mangrove root blocks, which remains transparent regardless of what options are used in sodium.
I could be mistaking of course, so anyone with more insight on why fps suddenly drop in mangrove biomes is welcome.

As the name implies, this new feature would focus on culling mangrove root blocks in the same fashion as it's currently done for leave blocks.  Could a copy/paste of the same code be sufficient?
The configuration settings in-game could be updated to let the player decide if mangrove root blocks culling is desired (Reese's sodium option mod?).

**Comment by Aculoss** [comment]
Sure this is in Sodium Extra. I have it enabled.

**Comment by pingouyn** [comment]
Hi, I am sorry but I do not see it even when Reese's Sodium Options and Sodium Extra mods are installed.
This feature has now just been added to Cull Leaves.  Are you referring to this?
Not many players use Cull Leaves compared to Sodium; it would still benefit the community to have Mangrove Root blocks culling added imo.

**Comment by Aculoss** [comment]
Apologies.. its moreculling mod by fxmorin
