### ISSUE TITLE
Error: java.lang.NullPointerException: Cannot assign field "f_112792_" because "net.minecraft.client.Minecraft.m_91087_().f_91060_.f_109469_.f_110843_[i]" is null

### ISSUE THREAD

**Issue by Schneckchen** [jellysquid3/Sodium#2036]
### Bug Description

Every time I try to log into my world the game crashes. The weird thing is I can make a new world and the game works perfectly fine, but once I try to go into my already existing world it crashes. I tried re-installing the mods I saw on the crash report. I installed all mods in the curseforge app, so there should,'t be any incompatibilities with the versions of the mods. Is there anything I can do?

### Reproduction Steps

I open the curseforge app
I go into my minecraft profile and press on play
In the minecraft launcher, I check if the correct version is selected and then I press play
When minecraft is open, I go into Singleplayer 
I go into my world
It loads to 100%
Afterwards it says Joining World
Then Saving World 
And then it crashes

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12420479/latest.log)

### Crash Report

[crash-2023-08-23_16.36.25-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12420488/crash-2023-08-23_16.36.25-client.txt)

**Comment by Lolothepro** [comment]
Sodium does not support Forge

**Comment by MeeniMc** [comment]
you are using forge which is not supported here.

**Comment by Schneckchen** [comment]
It's odd because it worked before and I didn't download sodium

**Comment by Schneckchen** [comment]
> you are using forge which is not supported here.

I created it to be a Forge modpack, and it functions properly. The issue arises when I try to load my pre-existing world, as it consistently crashes.

**Comment by TheUserCreated** [comment]
Sodium is not a forge mod, it's a *fabric* mod. It won't run in your forge mod pack. This isn't a bug.

**Comment by Schneckchen** [comment]
How can I get rid of it?

**Comment by RealmKebab** [comment]
by removing it from your modpack

**Comment by Schneckchen** [comment]
I already tried that. I had Rubidium installed, but I removed it and it still doesn't work

**Comment by hexadecimal233** [comment]
remove oculus

**Comment by Schneckchen** [comment]
I don't have that installed either. I don't know why it says, that I have these things, but I never installed them and they are nowhere to be found
