### ISSUE TITLE
Sodium keeps crashing

### ISSUE THREAD

**Issue by InviHrzn** [jellysquid3/Sodium#2039]
### Bug Description

It keeps telling me to remove and install things like iris, indium, sodium and other stuff but it still crashes with different crash reasons

### Reproduction Steps

No way that I know to recreate

### Log File

[crash-2023-08-23_16.18.29-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12423993/crash-2023-08-23_16.18.29-client.txt)

### Crash Report

[crash-2023-08-23_16.18.29-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12423992/crash-2023-08-23_16.18.29-client.txt)

**Comment by pajicadvance** [comment]
Try updating the mod "Moving Elevators" to the latest version.
