### ISSUE TITLE
Texture moved to other blocks and chucks

### ISSUE THREAD

**Issue by kingkiller933** [jellysquid3/Sodium#204]
The blocks are inside of each other and I know there is other post for this but maybe someone could put a step by step so other people can fix it

- Java Version: 1.16.1
- CPU: 4x Intel Core i5-3320 2.60 GHz 
- GPU: Intel Hud graphics 4000

**Comment by amnotbananaama** [comment]
This sounds like a duplicate of #179. You can fix this by going to Options -> Video Settings -> Advanced and setting "Chunk Renderer" to 3.0 or 2.1. This should fix your issue.

**Comment by kingkiller933** [comment]
Thanks
