### ISSUE TITLE
when rendering stained glass which is in water,some surfaces of  stained glass miss water texture.

### ISSUE THREAD

**Issue by Yancey2023** [jellysquid3/Sodium#2040]
### Bug Description

When rendering stained glass which is in water, some surfaces of  stained glass miss water texture.

### Reproduction Steps

put stained glass into the water

### Log File

no log file

### Crash Report

no crash

**Comment by MCRcortex** [comment]
https://github.com/CaffeineMC/sodium-fabric/issues/38 translucency issue, known

**Comment by jellysquid3** [comment]
getting really tired of closing duplicates of #38
