### ISSUE TITLE
Sodium 0.5.2 1.20.1 and v-sync cause stuttering.

### ISSUE THREAD

**Issue by Nediamail05** [jellysquid3/Sodium#2041]
### Bug Description

When playing on Minecraft 1.20.1 with the latest version of Fabric (0.14.22) and Sodium (0.5.2) I experience subtle but noticeable stuttering when moving and turning.

Here are my specs:
![Specs](https://github.com/CaffeineMC/sodium-fabric/assets/72153591/ba376143-6651-444b-9070-d6a41e671db9)

I also created a support post on the Discord, same username.

### Reproduction Steps

Load up a creative world with Minecraft 1.20.1, Fabric 0.14.22, and Sodium 0.5.2. Fly around and turn the camera while moving and look at blocks below to see a stuttering effect.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12434762/latest.log)

### Crash Report

[crash-2023-08-24_21.04.32-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12434763/crash-2023-08-24_21.04.32-client.txt)

**Comment by jellysquid3** [comment]
This is not a support forum. The issue tracker is intended for bug reports and the such, but "my game runs slowly" is not any actionable issue -- it's a help request.
