### ISSUE TITLE
noticable small fps drop

### ISSUE THREAD

**Issue by Hackatoan** [jellysquid3/Sodium#205]
while playing the game i was noticing that even though i was getting a huge fps boost it would drop down by like 10 fps or so enough to where i could notice it and it looked like it was having a lag spike.

**Comment by amnotbananaama** [comment]
The GitHub Issue tracker is for bugs and is not intended as a support site. I suggest joining [JellySquid's Hideout](https://jellysquid.me/discord) and providing screenshots of the [Profiler Graph](https://minecraft.gamepedia.com/Debug_screen#Profiler_graph) and [Frame Time Graph](https://minecraft.gamepedia.com/Debug_screen#Frame_time_graph) during normal gameplay, in the `#tech-support` channel.

**Comment by Hackatoan** [comment]
i restarted and it got resolved so im gonna close it now
