### ISSUE TITLE
Sodium crashes because of something with mixin

### ISSUE THREAD

**Issue by RealmKebab** [jellysquid3/Sodium#2050]
### Bug Description

title

### Reproduction Steps

i wouldn't have any idea since this is a mixin issue and there's aton of mods

### Log File

https://mclo.gs/96sGGJ9

### Crash Report

no crash report was provided
![image](https://github.com/CaffeineMC/sodium-fabric/assets/73048123/ba7290d6-66ac-4213-a888-42f504fe917a)

**Comment by purple512** [comment]
I think this is another case of the bundled mixinextras from Memory leak fix. Disable that anyway, you don't need it.

**Comment by RealmKebab** [comment]
memoryleakfix loves breaking mods
viafabricplus, now it's sodium
