### ISSUE TITLE
my game suddenly crashes 

### ISSUE THREAD

**Issue by ANRAXXD** [jellysquid3/Sodium#2051]
### Bug Description

When I start the game everything is fine but within a few minutes my game crashes without me doing anything, it just randomly crashes and gives me this error: 

net/caffeinemc/mods/sodium/api/vertex/buffer/VertexBufferWriter

### Reproduction Steps

Start the game

Wait Few Minutes 

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12471814/latest.log)

### Crash Report

[crash-2023-08-30_00.24.38-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12471820/crash-2023-08-30_00.24.38-client.txt)

**Comment by hexadecimal233** [comment]
Physics mod is outdated, you should update them

**Comment by ANRAXXD** [comment]
> Physics mod is outdated, you should update them

I did it It stills crashing

**Comment by MeeniMc** [comment]
You have mods that are incompatible with Sodium 0.5.x, update your mods.
