### ISSUE TITLE
My game will crash every now and then

### ISSUE THREAD

**Issue by MROGAMES** [jellysquid3/Sodium#2053]
### Bug Description

So I am on 1.20 and while I am playing bedwars, pressing F3+a or just traveling dimensions, there is a chance my game crashes.

### Reproduction Steps

the crashing will happen after I join 4-7 games of bedwars, hold down F3+a or if I travel to a dimension. so, it mostly happens on the joining world screen.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12479290/latest.log)

### Crash Report

[crash_report.txt](https://github.com/CaffeineMC/sodium-fabric/files/12479295/crash_report.txt)

**Comment by Lolothepro** [comment]
Please use Minecraft 1.20.1 with Sodium 0.5.2
