### ISSUE TITLE
Weird glitches with texture pack which renders the inside of glass blocks/panes.

### ISSUE THREAD

**Issue by Nomokuto** [jellysquid3/Sodium#2055]
### Bug Description

I have a texture pack, which allows rendering the inside texture of the glass blocks/panes. On OptiFine it works just fine, but with Quilt/Sodium/Iris the inside textures often disappear (don't show always like it should).

The pack:
[Better Glass.zip](https://github.com/CaffeineMC/sodium-fabric/files/12504477/Better.Glass.zip)

### Reproduction Steps

Just install the pack.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12504478/latest.log)

### Crash Report

No crash.

**Comment by Nomokuto** [comment]
The latest version seem to fix the issue for glass blocks. Would it be possible to add it to colored glass blocks and all panes as well?

![image](https://github.com/CaffeineMC/sodium-fabric/assets/139173187/5640c5bf-494b-4410-8365-4ac76b89f6d4)

**Comment by douira** [comment]
Might be a case of https://github.com/CaffeineMC/sodium-fabric/issues/38

**Comment by Nomokuto** [comment]
Ye maybe. Idk. Tho glass block is not transparent and yet it still had the issue before I updated to the latest version today.
