### ISSUE TITLE
Crash upon loading into my world

### ISSUE THREAD

**Issue by ComradeBlue1337** [jellysquid3/Sodium#2056]
### Bug Description

This has been happening with me for a few weeks now but I only decided to report this now. Basically whenever I try to load into my main world in 1.20.1 (haven't played it for 2 months and it was last played in 1.19.4) the game simply displays "Saving world" and then closes. Leaving me confused. Upon installed the Not Enough Crashes mod in hopes that it would give me more context, the mod says that Sodium (i'm using the latest version 0.5.2) seems to be the cause, but why? It didn't use to do this before in earlier versions of Sodium.

### Reproduction Steps

1. Put the world save into the saves folder in the minecraft directory
2. Load into the world
3. Proceed to immediately crash for no reason

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12504739/latest.log)

### Crash Report

[crash-2023-09-02_18.16.47-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12504740/crash-2023-09-02_18.16.47-client.txt)

**Comment by Dbl7id** [comment]
Seems to me that you have an outdated version of Chunks Fade In. Update the mod and see if that helps.

**Comment by Dbl7id** [comment]
If it doesn't help, can you please send the log and crash logs without Not Enough Crashes.

**Comment by dbl7id** [comment]
"at net.minecraft.class_2901.md8c7986$chunksfadein$lambda$modifyApply$0$0(class_2901.java:546) ~[transformed-mod-minecraft.i0:0/:?]" 
The culprit is Chunks Fade In, try to update the mod and see if it still crashes.

**Comment by ComradeBlue1337** [comment]
> 

The author released a new update for 1.20.1 today and I updated my version to it. I then loaded up my world and the issue was fixed! Thanks for clearing up things. I thought it could've been Sodium but I guess I was wrong

I guess this issue is now solved
