### ISSUE TITLE
Crash on 1.20.1 with shaders

### ISSUE THREAD

**Issue by Fleepe** [jellysquid3/Sodium#2058]
### Bug Description

I tried to load shaders Sildur's Vibrant Shaders v1.51 High, but after a couple of seconds the game crashed, and in the logs there are a lot of errors related to the Sodium. Maybe the error is caused by the shader itself, since other shaders work with grief in half on my PC, but then the errors would be associated with Iris I think.

### Reproduction Steps

I'm not sure if anyone can reproduce this crash, maybe some mod(s) was causing it, but I have a guess that the game crashed due to the fact that it did not have enough video memory (not RAM), since this happened to me often in the past.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12506340/latest.log)

### Crash Report

[crash-2023-09-03_17.49.55-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12506339/crash-2023-09-03_17.49.55-client.txt)

**Comment by douira** [comment]
Since the error only happens with shader packs, this is an issue for Iris.
