### ISSUE TITLE
Multi-Draw renderer is not availiable on a gpu that should support it.

### ISSUE THREAD

**Issue by sixunity** [jellysquid3/Sodium#206]
### Expected Behavior
I should be able to use multidraw renderer as the gpu supports opengl 4.4 (multidraw needs 4.3)

### Actual Behavior
the best version i can select is opengl 3.0, which does not improve performance nearly as much

### Attachments

![image](https://user-images.githubusercontent.com/68563790/88789082-f5f91080-d19e-11ea-85f6-d1d5c313ac50.png)

### System Information
https://pastebin.com/wRhgWS7A

- Java Version: Version 8 Update 51
- CPU: AMD A6-3420M Overclocked to 2.7ghz
- GPU: HD 7670M 1Gb ddr3 + HD 6520G 512Mb ddr3

**Comment by LucilleTea** [comment]
Not a bug.
The multidraw renderer is intentionally blacklisted on your drivers due to #24 , which will be fixed by #188 .

**Comment by sixunity** [comment]
ok sorry, i didnt know that, thank you
