### ISSUE TITLE
Game crashes on loading of world

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2062]
### Bug Description

I try to load any world and the game crashes as soon as I am rendered into it. It is able to save before closing however.

### Reproduction Steps

Running the game.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12515048/latest.log)

### Crash Report

[crash-2023-09-04_11.25.15-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12515050/crash-2023-09-04_11.25.15-client.txt)

**Comment by Lolothepro** [comment]
Caused by mbp

```@Redirect conflict. Skipping mbp.mixins.json:compat.sodium.ChunkBuilderMeshingTaskMixin from mod mbp->@Redirect::getModelRedirect(Lnet/minecraft/class_773;Lnet/minecraft/class_2680;)Lnet/minecraft/class_1087; with priority 1000, already redirected by mixins.iris.compat.sodium.json:block_id.MixinChunkRenderRebuildTask from mod iris->@Redirect::iris$wrapGetBlockLayer(Lnet/minecraft/class_773;Lnet/minecraft/class_2680;Lme/jellysquid/mods/sodium/client/render/chunk/compile/ChunkBuildContext;)Lnet/minecraft/class_1087; with priority 1000```

**Comment by ghost** [comment]
Ahh okie thanks!
