### ISSUE TITLE
Cauldrons with water crash the game

### ISSUE THREAD

**Issue by dophire** [jellysquid3/Sodium#2065]
### Bug Description

I'm using Vanadium mod for custom colors since Colormatic hasn't been updated to 1.20.1 and I'm using Bedrock Waters color resourcepack. Everything works perfectly until I fill a cauldron with water and then the game crashes when trying to render it. It seemed like it is caused by the fact that Sodium added "Cauldron blocks no longer force the use of smooth biome color blending for the fluid contents." to 0.5.2. 

### Reproduction Steps

Use latest Sodium + Indium + Vanadium. Use a resourcepack that changes the water colors. Place a cauldron and fill it with water, the game will crash.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12557232/latest.log)

### Crash Report

[crash-2023-09-08_03.12.51-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12557225/crash-2023-09-08_03.12.51-client.txt)

**Comment by pajicadvance** [comment]
The problem is caused by Vanadium, it's an unfinished mod and it should be reported to them, not to us.
