### ISSUE TITLE
Sodium is weird with some blocks (desynchronized)

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2069]
### Bug Description

Sodium is weird with some blocks

![image](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/5b4c3cf2-0f88-4f1c-bf33-440136aa3cff)
https://cdn.discordapp.com/attachments/1148716397610946623/1150450982103285820/2023-09-10_17-21-08.mp4

### Reproduction Steps

Enter the world of debugging
Try to open/close trapdoors

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12568571/latest.log)

### Crash Report

[crash-2023-09-10_17.32.28-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12568570/crash-2023-09-10_17.32.28-client.txt)

**Comment by hexadecimal233** [comment]
I think this does not happen in regular gaming

**Comment by MeeniMc** [comment]
can't reproduce. IT is normal for the block to automatically reset to their initial state in the debug world. What is not normal is that it takes so long in your video.

**Comment by Lolothepro** [comment]
> can't reproduce. IT is normal for the block to automatically reset to their initial state in the debug world. What is not normal is that it takes so long in your video.

No, in the debug world, even when the player right-clicks, the block (or trapdoor) should not move/change.
