### ISSUE TITLE
Crash after updating to newest version

### ISSUE THREAD

**Issue by EbonDusk** [jellysquid3/Sodium#2070]
### Reproduction Steps

Upon loading into a world, I crash soon after. There's isn't anything I'm doing that can be repeated to cause it, just crashes after a few seconds.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12570099/latest.log)

### Crash Report

[crash-2023-09-10_15.49.07-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12570102/crash-2023-09-10_15.49.07-client.txt)

**Comment by Phoenix-Starlight** [comment]
Get latest version of physics mod.

**Comment by EbonDusk** [comment]
> 

Oops thought I closed this, I figured that out. Thank you though!
