### ISSUE TITLE
minor incompatibility with texture packs

### ISSUE THREAD

**Issue by Jayerd** [jellysquid3/Sodium#2072]
### Request Description

https://legacy.curseforge.com/minecraft/texture-packs/xalis-enhanced-vanilla

I use this pack but the grass connected textures (used with Continuity and CIT Resewn) does not happen everything else I think works just as fine

**Comment by MeeniMc** [comment]
You may be missing the Indium mod.

**Comment by Jayerd** [comment]
I actually have it and its a known issue (based from the comments in the packs curseforge page) and they suggest downgrading sodium to 4.9 . Would this be fixed ever?

**Comment by MeeniMc** [comment]
For reference the Xali issue tracker where this is discussed 
https://github.com/xalixilax/xali-s-Enhanced-Vanilla-16x/issues/22

**Comment by Jayerd** [comment]
thanks!! sorry for the bother !!!
