### ISSUE TITLE
GLFW crash

### ISSUE THREAD

**Issue by totchi-lagawi** [jellysquid3/Sodium#2073]
### Bug Description

When I start the game, it automatically crash, and display an error message, saying that there was an error with GLFW.
https://i.imgur.com/ob9QRwk.png

I'm on Linux, with the latest drivers installed.
I use Prism Launcher.

### Reproduction Steps

- Install Fabulously Optimized
- Start the game

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12589248/latest.log)

### Crash Report

None.

**Comment by MeeniMc** [comment]
Can you reproduce with only Sodium? Does Vanilla work?

**Comment by totchi-lagawi** [comment]
Well... It's pretty strange. I started the game without any change, and it worked perfectly...
EDIT : I updated packages (I don't know which ones) - not graphics drivers - and I worked.

Note : The bug happened only after enabling the "Settings" - "Minecraft" - "Adjustments" - "Use dedicated GPU" (I'm translating settings name)

**Comment by jellysquid3** [comment]
Your GPU drivers don't appear to be configured correctly. It seems that maybe you're using the Nouveau graphics drivers (which are essentially unusable on modern GPUs) instead of the proprietary NVIDIA driver, which cannot handle what we're asking of it during context creation.

Either way, this is not an issue with Sodium. If you still need help with resolving it, then you should join the [community Discord server](https://caffeinemc.net/discord) instead.

**Comment by totchi-lagawi** [comment]
No, I'm using the proprietary Nvidia drivers, from the Ubuntu PPA graphics drivers, so the issue do not comes from it. It's maybe a bug with the Prism Launcher option "use dedicated GPU", that do not work with Sodium.

**Comment by DragonEggBedrockBreaking** [comment]
> No, I'm using the proprietary Nvidia drivers, from the Ubuntu PPA graphics drivers, so the issue do not comes from it. It's maybe a bug with the Prism Launcher option "use dedicated GPU", that do not work with Sodium.

I successfully use PrismLauncher with a dedicated Nvidia GPU on Ubuntu, so it's definitely possible for some Nvidia GPUs. Are you sure that you a) have the correct driver for your GPU and that the driver works at all (can be tested via utilities like `glxgears -info`), b) if you're using the PrismLauncher flatpak, that you have GPU acceleration enabled (you'd need to install and use "flatseal")?

**Comment by totchi-lagawi** [comment]
Sorry for being late...
So : 
1. Yes, my driver is the correct one for my graphics card (an Nvidia RTX 3060, I forgot to say that..)
2. I'm not using the flatpak version

Also, I already said that all's work fine now. All I had to do is to upgrades some packages (however **not** the graphics driver).

So this issue is hopefully not an issue any more :D 
Thanks for the support!
