### ISSUE TITLE
Sodium 0.5.0+ breaks connected textures for biome specific blocks (like grass)

### ISSUE THREAD

**Issue by chonkyman** [jellysquid3/Sodium#2076]
### Bug Description

Sodium 0.5.0+ breaks connected textures for biome specific blocks (like grass)

### Reproduction Steps

Fabric Loader, Fabric API, Sodium, Indium, Continuity, Xali's Enhanced Vanilla

### Log File

nuh uh

### Crash Report

nuh uh

**Comment by Poopooracoocoo** [comment]
Resource packs: [Xali's Enhanced Vanilla](https://www.curseforge.com/minecraft/texture-packs/xalis-enhanced-vanilla), Continuity default resource packs
Environment: Minecraft 1.20.1. Fabric Loader 0.14.22. 
Logs: [latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12642114/latest.log)

Fabric API 0.88.1 + Continuity 3.0.0-beta.3
![2023-09-17_15 04 19](https://github.com/CaffeineMC/sodium-fabric/assets/51363864/1cfb5d61-5703-4f10-bbfd-9a33da596f73)

Fabric API 0.88.1 + Continuity 3.0.0-beta.3 + Sodium 0.5.2 + Indium 1.0.25
![2023-09-17_15 07 57](https://github.com/CaffeineMC/sodium-fabric/assets/51363864/932363c5-045a-4cdf-9b33-771fc1e5cede)

**Edit:**
> biome predicates do not work with Sodium 0.5.0 or newer, so you should uninstall Sodium during testing. This will be fixed in beta 4.

[Source](https://discord.com/channels/756612889787498627/1015029663669702767/1141349336014393384) via [Pepper's Mods Discord server](https://discord.gg/7rnTYXu). Doing a search for 'biome' in the server shows more info

**Comment by chonkyman** [comment]
> Resource packs: [Xali's Enhanced Vanilla](https://www.curseforge.com/minecraft/texture-packs/xalis-enhanced-vanilla), Continuity default resource packs Environment: Minecraft 1.20.1. Fabric Loader 0.14.22. Logs: [latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12642114/latest.log)
> 
> Fabric API 0.88.1 + Continuity 3.0.0-beta.3 ![2023-09-17_15 04 19](https://user-images.githubusercontent.com/51363864/268483878-1cfb5d61-5703-4f10-bbfd-9a33da596f73.png)
> 
> Fabric API 0.88.1 + Continuity 3.0.0-beta.3 + Sodium 0.5.2 + Indium 1.0.25 ![2023-09-17_15 07 57](https://user-images.githubusercontent.com/51363864/268483881-932363c5-045a-4cdf-9b33-771fc1e5cede.png)

yeah what this guy said

**Comment by Poopooracoocoo** [comment]
Please do not create spam. This is not a real time chat. This is an issue tracker. I suggest hiding your comment to make it easier for others to follow this issue: 
<img width="148" alt="image" src="https://github.com/CaffeineMC/sodium-fabric/assets/51363864/7d748a06-defd-4ac5-8f1e-832b5d2864d1">

**Comment by jellysquid3** [comment]
Recently, there was an addition to the Fabric API for querying biome data from the world, which I'm pretty sure Continuity is waiting on us to implement so that it doesn't have to keep hacking into Sodium's internals. That said, [we already merged their pull request](https://github.com/CaffeineMC/sodium-fabric/commit/21385865dbb6ea41f4fa4d202d84e5c6247455a0), so it's probably just a matter of us releasing a new version of the mod, and then everything will work again.
