### ISSUE TITLE
Color saturation / vibrancy slider

### ISSUE THREAD

**Issue by not-holar** [jellysquid3/Sodium#2077]
### Request Description

Minecraft looks pretty bleak and gray without shaders, i've seen questions about a saturation slider for the game for a while all over the internet. I think it would fit pretty nicely into the mod changing minecraft's rendering

**Comment by douira** [comment]
Probably out of scope. Sodium isn't a general graphics mod, but primarily a performance mod that also fixes some bugs so I doubt this would be accepted. It might be something for Sodium Extras or a separate mod altogether.
