### ISSUE TITLE
Fast leaves mod compatibility

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2079]
### Request Description

For example:
* Fast leaves:
![2023-09-17_18 04 49](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/99bab3bd-bfd2-45a7-8193-08dba9634d2e)

As you can see, Terrestria's leaves are rendered as if they were "Fancy", while the "Leaves" setting is "Fast".

* Fast graphics:
![2023-09-17_18 05 02](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/b37d5ed7-ddcb-4825-9308-6c25f11ce018)

**Comment by jellysquid3** [comment]
This is impossible to fix from our side. Mods would have to register some piece of information about their blocks which allows us to determine whether or not they should have their render layers swapped. And even then, we don't intend on keeping "Fast Graphics" around for much longer, so it will become a moot point.
