### ISSUE TITLE
sodium 0.5.3 is slower than the older versions

### ISSUE THREAD

**Issue by 256colormode** [jellysquid3/Sodium#2081]
### Request Description

so i was having sodium 0.4.11 and it was like 80 fps but when i updated it to version 0.5.3 the fps became 30-20 fps

**Comment by MeeniMc** [comment]
Please close the issue and go to the discord to ask for help https://discord.com/channels/602796788608401408/1010831567607844955. Make sure you provide a log,otherwise it is impossible to know what's going on.

**Comment by 256colormode** [comment]
> Please close the issue and go to the discord to ask for help https://discord.com/channels/602796788608401408/1010831567607844955. Make sure you provide a log,otherwise it is impossible to know what's going on.

ok but when i opened the link it didnt sent me to the server i need the server invitation link

**Comment by MeeniMc** [comment]
https://jellysquid.me/discord
