### ISSUE TITLE
Please make sodium gui consitant with the rest of minecraft gui

### ISSUE THREAD

**Issue by Shadowblitz16** [jellysquid3/Sodium#2083]
### Request Description

This gui looks ugly and inconsistant
![image](https://github.com/CaffeineMC/sodium-fabric/assets/2453707/6a1cb4df-f8d0-4205-80ac-d090c2c21354)

Can you make it look like this?
![image](https://github.com/CaffeineMC/sodium-fabric/assets/2453707/347fd440-ea29-4d29-bfe5-6e73da62118f)

It also has effects logic with the controllable mod.
You can't snap navigate with the controller.

**Comment by Lolothepro** [comment]
no

**Comment by Shadowblitz16** [comment]
> no

What? why?

**Comment by douira** [comment]
Sodium has its own GUI on purpose, this is not a bug.

**Comment by Shadowblitz16** [comment]
> Sodium has its own GUI on purpose, this is not a bug.

Why? Why can't we have the option to use the original ui?

**Comment by douira** [comment]
Somebody [has made a mod](https://modrinth.com/mod/xanders-sodium-options) that you can use that uses the default style. This issue can be closed.

**Comment by Shadowblitz16** [comment]
> Sodium has its own GUI on purpose, this is not a bug.

Is there a reason why sodium uses it's own gui?
I googled and I can't find it.

**Comment by douira** [comment]
There is unlikely to be any information about this on the public internet as it's a decision that was made by the original author. You can come to the discord and ask, or maybe somebody will feel like explaining it here (though I find that unlikely).

**Comment by FlashyReese** [comment]
![image](https://github.com/CaffeineMC/sodium-fabric/assets/30311066/68df9619-cb1b-4ed6-a330-d8145e9ca8c7)
Note: This information is from 2020, so opinions and circumstances may have changed since then.

**Comment by Shadowblitz16** [comment]
I have a better idea.

For example what if...
This mod loops though all the gui in the game including the non video settings And replaces it with this mod's gui..
Then we have the option to apply vanilla theme to it in the video settings...

Then we have... 
- It's easier for you guys to implement gui in the long run
- A performance increase for the rest of the menu's
- All the menus are consistent.
- And we can have the possibility of the vanilla or custom themes.

Everyone wins.

The only problem would be the work of translating minecraft's entire gui system to sodium gui.

**Comment by douira** [comment]
There's a resource pack that converts all the other menus to look like Sodium's. https://www.planetminecraft.com/texture-pack/sodium-gui-lite/

**Comment by douira** [comment]
as I said earlier, there's also already a mod that makes sodium's menu look like vanilla: https://modrinth.com/mod/xanders-sodium-options
between that and the texture pack I just posted it seems all your options are covered more or less.

**Comment by Shadowblitz16** [comment]
> There's a resource pack that converts all the other menus to look like Sodium's. https://www.planetminecraft.com/texture-pack/sodium-gui-lite/

This would not come with the performance benefits of sodium ui

> as I said earlier, there's also already a mod that makes sodium's menu look like vanilla: https://modrinth.com/mod/xanders-sodium-options between that and the texture pack I just posted it seems all your options are covered more or less.

Also this mod is outdated.

**Comment by Shadowblitz16** [comment]
I honestly tried to post a solution that everyone would be happy with.
It honestly feels you guys are just being stubborn and it has nothing to do with the above.

**Comment by douira** [comment]
I think you are misunderstanding that what you are suggesting is a ridiculous amount of work. Nobody has the time to do that and there's far more productive things we can work on within sodium. If you're particularly interested in this being implemented, consider writing the code yourself or paying somebody (like one of the contributors) to do it for you.

**Comment by FlashyReese** [comment]
It's an open source project you are free to contribute :P

**Comment by Shadowblitz16** [comment]
> I think you are misunderstanding that what you are suggesting is a ridiculous amount of work. Nobody has the time to do that and there's far more productive things we can work on within sodium. If you're particularly interested in this being implemented, consider writing the code yourself or paying somebody (like one of the contributors) to do it for you.

As long as it's not a won't merge and is still a possibility if someone does do it

**Comment by jellysquid3** [comment]
Nobody's being stubborn. What you ask for is unreasonable and we have technical reasons for doing it the way we have. Just because you disagree on the merit of it being "ugly" does not mean anyone is required to make changes.
