### ISSUE TITLE
(1.20.1 latest mod version) Sodium incompatibility with Create (not fixed, known)

### ISSUE THREAD

**Issue by redshadow3** [jellysquid3/Sodium#2084]
### Bug Description

Im using the latest versions of Create and Sodium but the game is crashing with fabric basically saying "0.5.3 is incompatible but you can fix that by using version 0.5.3!"

 ive looked for reports of the Create and sodium incompatibility issue but didnt find any on this version of the mod, i tried downloading the latest from Modrinth and the latest from here for 1.20.1 but it did not fix it, ive even tried removing all the other mods except the fabric API and these two and that hasnt fixed it either, i am using the custom profiles thing on curseforge to play these so maybe thats the problem?

i dont know, please dont just say that "youre wasting time on a non-existing issue" and then not explain how to fix it or where to find the instructions for fixing it, also fabric says this in the crash:

Incompatible mod set!
Mod resolution encountered an incompatible mod set!

A potential solution has been determined:
Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with version 0.5.1-d-build.1161+mc1.20.1 or later that is compatible with: Sodium 0.5.3!

Unmet dependency listing:
Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.3!

### Reproduction Steps

Take sodium-fabric-mc1.20.1-0.5.3 and create-fabric-0.5.1-d-build.1161+mc1.20.1 run minecraft fabric with them and that should replicate the issue

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12700681/latest.log)

### Crash Report

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with version 0.5.1-d-build.1161+mc1.20.1 or later that is compatible with:
		 - sodium 0.5.3
Unmet dependency listing:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by pajicadvance** [comment]
Create doesn't support Sodium 0.5.0 and above at the moment, you have to use 0.4.10.
