### ISSUE TITLE
I cannot open my resource pack on 1.20.1 version

### ISSUE THREAD

**Issue by GrostK** [jellysquid3/Sodium#2085]
### Bug Description

I cannot open my resource pack on 1.20.1 version. It just writes that failed to load a resource pack

### Reproduction Steps

Just load a resource pack

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12702552/latest.log)

### Crash Report

[crash-2023-09-22_17.59.22-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12702543/crash-2023-09-22_17.59.22-client.txt)

**Comment by Poopooracoocoo** [comment]
~~Install Indium and downgrade to Fabric API 0.89.0 for now.~~ A new version of Indium is now available.

**Comment by GrostK** [comment]
> ~Install Indium and downgrade to Fabric API 0.89.0 for now.~ A new version of Indium is now available.

oh thanks

**Comment by Poopooracoocoo** [comment]
If installing Indium fixed your issue, please close this issue.
