### ISSUE TITLE
Console is spammed with the same error and the game barely runs at 40 FPS

### ISSUE THREAD

**Issue by redstoner2019** [jellysquid3/Sodium#2088]
### Bug Description

Im having the issue that the console is spammed with the same error message and within seconds i already get the warning of there being over 100.000 lines in the console. The game barely runs aswell. Ive put a screenshot as an attatchment.

My specs are:
RTX 3060TI
i5-11400

Driver Version: 537.42

![image](https://github.com/CaffeineMC/sodium-fabric/assets/75677796/d3c00cda-992c-4f34-86e3-3fd54e664fc1)

If you need any more information regarding the issue i will provide it asap.

For the log file i quickly had to close out of the game as soon as the main menu popped up as most of the time the latest.log was already over 25MB in size by the time the main menu had loaded.

### Reproduction Steps

Have the newest Sodium Version installed (mc1.20.1-0.5.3)
Nvidia Driver Version: 537.42
Java VM args: -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12706634/latest.log)

### Crash Report

[crash-2023-09-23_16.18.36-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12706640/crash-2023-09-23_16.18.36-client.txt)

**Comment by hexadecimal233** [comment]
It's caused by RivaTuner, see #2048
