### ISSUE TITLE
Sodium is not working in pojav

### ISSUE THREAD

**Issue by Vansh28opIspro** [jellysquid3/Sodium#2094]
### Request Description

Sodium is not working in pojav 
It gives not that pojavlauncher doesn't support sodium and crashes when we load
And says Sodium,and sodium extra mod does not support 

https://github.com/CaffeineMC/sodium-fabric/assets/146235946/2392d865-d704-4451-931e-4a90e99385e2

**Comment by Felix14-v2** [comment]
Please, read carefully
https://github.com/CaffeineMC/sodium-fabric#opengl-compatibility-layers
~~and use zink~~
