### ISSUE TITLE
Not giving good fps

### ISSUE THREAD

**Issue by lgsanai** [jellysquid3/Sodium#2098]
Yes so I have a decent laptop and optifine gives me 50 60 fps in 1.19 and sodium gives me 40 50 I've seen alot of videos that it increases 200 300 fps but for me it doesn't it even lowers the fps I have 8 GB ram i5 5000 processor and windows 10 please help me I wanna play sodium with good fps please

**Comment by TheUserCreated** [comment]
If you aren't getting the performance increase you're expecting you need to provide more information, you should probably ask for support **in the support forum on discord.** Be sure to give detailed system specs, a screenshot of your f3 screen with sodium (and maybe one with optifine and vanilla for comparison),and if you know how a spark profile with sodium enabled.
