### ISSUE TITLE
Rewrite Sodium to use Vulkan API through LWJGL

### ISSUE THREAD

**Issue by td5038** [jellysquid3/Sodium#2099]
### Request Description

I think that rewriting sodium to use Vulkan **by default** will increase the performance of the mod and anything based on it greatly. OpenGL will still need to be provided for older setups, as not everyone has a GPU that supports Vulkan. We can move OpenGL to a legacy codepath that is ****only used when the GPU does NOT support Vulkan.**** I hope everyone can benefit from this, as even though Minecraft does do crappy OpenGL and the Sodium codebase optimizes it, Vulkan is just a better low-level api for graphics.

**Comment by rilakuma123** [comment]
(#1496 went into this)

**Comment by td5038** [comment]
No, don't use that dogshit Vulkan mod. You can code that up yourself

**Comment by pajicadvance** [comment]
> No, don't use that dogshit Vulkan mod. You can code that up yourself

The "Sodium in Vulkan" discussion has been had a million times, and it boils down to the conclusion that not only would a Vulkan implementation not increase performance, it would actually perform worse than the current OpenGL implementation, with some of the main reasons being that there are few options for efficient chunk multi-draw like the current implementation has, and the JNI overhead from using Vulkan would be significantly increased. I suggest that you refrain from being aggressive over matters which you know little about.
