### ISSUE TITLE
Rain and Snow Fall in Weird Patterns	

### ISSUE THREAD

**Issue by KurazhBombei** [jellysquid3/Sodium#210]
### Expected Behavior
Rain and snow particles fill terrain normally(they are on every block they should be on).

### Actual Behavior
They fill terrain by "lines" shape. Pattern of those lines, either walls, keeps same even after game reloading.

### Reproduction Steps
Just typed in "/weather thunder" and saw that.

### Attachments
[https://drive.google.com/file/d/14cISzaNY4V5P5xH4rSpDFfCyJuvIF0h1/view?usp=sharing](url)

### System Information

- Java Version: [Java 1.8.0_51 (64-bit)]
- CPU: [FX 8350]
- GPU: [RX 570 (4gb)]

**Comment by deeprobin** [comment]
I cannot reproduce this issue. Can you provide more information?

**Comment by amnotbananaama** [comment]
Closing as a considerable amount of time and code development has occurred without a response. If this is still occurring, please reply here so the issue can be reopened.
