### ISSUE TITLE
Game crashing immidently

### ISSUE THREAD

**Issue by wojtmic** [jellysquid3/Sodium#2102]
### Bug Description

I dont know exactly what happened, i just booted up my game as normal with sodium and the console said if my game crashed immediately after this point to make a report here, and well it crashed.

### Reproduction Steps

Boot up the game

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12819932/latest.log)

### Crash Report

The file is not present from today

**Comment by pajicadvance** [comment]
Do you have any log files starting with `hs_err_pid` in your `.minecraft` folder? If so, copy the first 20 lines or so (everything before the beginning of the SUMMARY section) from the latest file and send them here.

**Comment by hitheremynameisender** [comment]
help me i have the exact same error

**Comment by hitheremynameisender** [comment]
by the way i have no files starting with that

**Comment by hitheremynameisender** [comment]
please help me i want to play minecraft again. If it helps, this only started once i updated to 1.20.2

**Comment by pajicadvance** [comment]
@hitheremynameisender Open your own issue report and provide the required info.
