### ISSUE TITLE
Endless territory loading 

### ISSUE THREAD

**Issue by TerAdapter** [jellysquid3/Sodium#2103]
### Bug Description

**The game version is 1.18.2, the mod version is the latest for 1.18, when I go to the server from this version it tells me: “loading territory” and so on until I am disconnected from the server, there were no problems on 1.16.5, but there were problems on 1.18+ >:(

If there are errors in the message, I wrote it through Google translator**

### Reproduction Steps

-

### Log File

-

### Crash Report

-

**Comment by pajicadvance** [comment]
Closed as the information required by the issue template was not provided.
