### ISSUE TITLE
create mod

### ISSUE THREAD

**Issue by SmellyBozoAce** [jellysquid3/Sodium#2104]
### Bug Description

every time i open minecraft with sodium and create fabric it says it isnt compatible with the newest version

### Reproduction Steps

all i do is open minecraft with 1.20.1 newest version of create and sodium

### Log File

it doesnt have 1 for some reason

### Crash Report

doesnt have 1 of these either

**Comment by pajicadvance** [comment]
The latest version of Create doesn't support Sodium 0.5 yet. You have to use 0.4.10.

**Comment by Poopooracoocoo** [comment]
And also get Indium 1.0.21 and Fabric API 0.88.1.

**Comment by Poopooracoocoo** [comment]
It's concerning that no latest.log was generated :/
