### ISSUE TITLE
Game is crashing

### ISSUE THREAD

**Issue by Yoappian** [jellysquid3/Sodium#2105]
### Bug Description

Idk if it is Sodium that is causing my game to crash, but I do want to play in VR. So I need assistance please.

### Reproduction Steps

First I tried to launch the game normally on Desktop mode. It works, but the moment I switch to VR. It crashes and comes up with this thing called "Imu is Null" (idk what that means)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12823082/latest.log)

### Crash Report

[crash-2023-10-05_22.26.38-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12823086/crash-2023-10-05_22.26.38-client.txt)

**Comment by hexadecimal233** [comment]
your sodium is very outdated 
i think vivecraft will work on 0.5.3

**Comment by Poopooracoocoo** [comment]
Know that Sodium 0.5.3 is only for Minecraft 1.20.1 and 1.20.2.
