### ISSUE TITLE
Support for 23w13a_or_b

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2106]
### Request Description

Please add support for 23w13a_or_b I play on a server that runs on this version (because its prob the best april fools version)

**Comment by jellysquid3** [comment]
no

**Comment by Felix14-v2** [comment]
@noobnarb you can try this [unofunofficial port](https://discord.com/channels/774352792659820594/883067831485366304/1091716797398523974) by IMS published on the [Iris Discord](https://discord.gg/jQJnav2jPu) server

**Comment by ghost** [comment]
> no

why not D:

**Comment by Felix14-v2** [comment]
Because their time (and motivation) is limited. Sodium is still in alpha, so supporting outdated versions would greatly slow down the development process.

**Comment by rilakuma123** [comment]
I don't think OP expects continued support but just a single release for it.

**Comment by douira** [comment]
You can find an unofficial build of sodium on this version in Iris' discord if you search for it. You will not receive help or technical support in using it here.

**Comment by douira** [comment]
In fact, somebody already made this exact issue three days after that snapshot came out: https://github.com/CaffeineMC/sodium-fabric/issues/1680
