### ISSUE TITLE
Add fast clouds option back

### ISSUE THREAD

**Issue by eldeiibid** [jellysquid3/Sodium#2107]
### Request Description

I don't know why, but in the version 1.20.x-0.5.x of Sodium it's impossible to change between 2d and 3d clouds. You're forced to use the 3d ones. I know it does almost nothing to the performance, but I really liked how fast clouds use to look. So I ask you if you could add the "Clouds Quality" slider back, please :)

**Comment by Felix14-v2** [comment]
Vanilla fast clouds are slower than fancy clouds in Sodium, so this doesn't make any sense imo. If you want, you can disable the cloud optimization mixin entirely to restore vanilla unoptimized clouds.

**Comment by jellysquid3** [comment]
I'm not exactly sure if this is how Minecraft does it, but we should be able to emulate "fast" clouds by simply not emitting geometry for any face other than `-Y`. This would be a relatively simple pull request if someone wants to work on it.

**Comment by jellysquid3** [comment]
I'm nominating this to be worked on for Sodium 0.5.6, but it will be pushed back if time doesn't allow.

**Comment by Lolothepro** [comment]
!

**Comment by jellysquid3** [comment]
This is resolved with https://github.com/CaffeineMC/sodium-fabric/commit/e995570c361a79b86d497e69c0d764488ed43ab0. The rendering of "fast-mode" clouds is not identical to Vanilla, but looks good enough (if not better) in my opinion.

**Comment by Poopooracoocoo** [comment]
> Vanilla fast clouds are slower than fancy clouds in Sodium, so this doesn't make any sense imo. If you want, you can disable the cloud optimization mixin entirely to restore vanilla unoptimized clouds.

To do this, go to your config folder, open the sodium-mixins.properties file, then add the line `mixin.features.render.world.clouds=false`. Then save. Then open Minecraft, then go to video settings, press Shift+P, and then you can enable Fast Clouds. 

And once again, there's not really a performance benefit out of using fast clouds
