### ISSUE TITLE
MC 1.20.1 w/ sodium-fabric-mc1.20.1-0.5.3 saves to wrong Shadowplay folder

### ISSUE THREAD

**Issue by badmin-c** [jellysquid3/Sodium#2108]
### Bug Description

I am using Geforce Experience Shadowplay to record ingame video and audio. Normally the captured file would save to a folder named "Minecraft". Since I updated to Minecraft Version 1.20.1 and sodium-fabric-mc1.20.1-0.5.3 files are saved to a folder named "Base Profile". It does not happen when using Version 1.20.1 without sodium. 

Minecraft Version: 1.20.1 (Vanilla)
Fabric API version: fabric-api-0.89.3+1.20.1
Sodium Version: sodium-fabric-mc1.20.1-0.5.3

### Reproduction Steps

1. Start minecraft fabric-loader-1.20.1 while sodium-fabric-mc1.20.1-0.5.3 is in your mods folder.
2. Record a video with Shadowplay and save it
3. Look into the Shadowplay folder and find your Video in "Base Profile" instead of "Minecraft"

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12837159/latest.log)

### Crash Report

Game does not crash, so no report

**Comment by rilakuma123** [comment]
I don't think Sodium can do anything about this.
Sodium tries to hide the Minecraft window from Nvidia's crappy drivers so it doesn't apply it's optimisations. That's why Shadowplay puts recordings of Minecraft in a different folder.

**Comment by badmin-c** [comment]
I played 1.19.4 with sodium-fabric-mc1.19.4-0.4.10+build.24 for a long time and it never happened before. 
Now all of the sudden sodium cannot do anything about this?

**Comment by Poopooracoocoo** [comment]
That's because Sodium 0.5 changed its workaround to avoid being detected by NVIDIA's drivers. The old workaround required that users switch to Prism Launcher but now it works on any launcher.

**Comment by badmin-c** [comment]
OK, thank you. But i never used any other launcher than the default one

Edit: I had to read your post a second time to understand it. So now it works as expected with the default launcher, in previous versions it didn't. Got it. 

Thanks again!

**Comment by Poopooracoocoo** [comment]
I figured. That's what I'm trying to explain. Sodium's workarounds didn't fully work on 0.4.10 on Minecraft Launcher. But with Sodium 0.5, they do

also see https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility and https://github.com/CaffeineMC/sodium-fabric?tab=readme-ov-file#-hardware-compatibility
