### ISSUE TITLE
CaffeineMC is crashing my game because of my gpu or somethin

### ISSUE THREAD

**Issue by hitheremynameisender** [jellysquid3/Sodium#2111]
### Bug Description

i cant play mc on 1.20.2, 1.20.1 was fine with all these mods but once i updated like 10 of them broke, i had to disable them and then it descended into chaos with caffeinemc crashing because of workarounds.

### Reproduction Steps

3D Skin Layers
by tr7zw
1.5.6-1.20.2
Additional Entity Attributes
by DaFuqs
1.5.0+1.20.2

Allow Portal GUIs
by Blayung
1.0.2

AntiGhost
by Giselbaer
1.20-fabric0.83.0-1.1.5

AppleSkin
by squeek502
2.5.1+mc1.20.2

Architectury API
by shedaniel
10.0.8+fabric

BetterF3
by treyruffy
7.0.1
CaffeineMC+Mods-0.3.zip.disabled

Calio-1.20-1.11.0.zip

Carpet
by altrisi
1.4.119

Clock HUD
by mrmelon54
1.0.1

Cloth Config API
by shedaniel
12.0.109+fabric

Clumps
by jaredlll08
13.0.0.1

Collective
by Serilum
1.20.2-6.66-forge+fabric

Colorful Hearts
by Terrails
5.0.0

Command GUI Buttons
by MSDNicrosoft
2.1.0

Cosmetica
by eyezahhhh
1.2.5-1.20+hotfix
Custom Crosshair Mod
by Sparkless101
v1.5.3-fabric-mc1.20.2
Custom Splash Screen
by Motschen
2.1.1

CustomHud
by Minenash
3.2.0+1.20.2
DashLoader
by alphaqu
5.0.0-beta.2+1.20.0

Dashboard
by ThatGravyBoat
4.0.0

Debugify
by isxander
1.20.2+1.0

DirectionHUD
by Oth3r
1.4.2+1.20-1.20.2

Durability Viewer
by Giselbaer
1.20.2-fabric0.89.1-1.10.5

Dynamic Crosshair
by Crendgrim
7.3+1.20.2-fabric

Dynamic FPS
by juliand665
3.2.1

ESSENTIAL Mod
by SparkUniverse
1.2.2.2

Enhanced Block Entities
by FoundationGames
0.9+1.20

Entity Culling
by tr7zw
1.6.2-1.20.2

Fabric API
by modmuss50
0.90.0+1.20.2

Fabric Language Kotlin
by modmuss50
1.10.10+kotlin.1.9.10

Faithful 32x
by Faithful-Resource-Pack
1.19.4-may-2023

FerriteCore
by malte0811
6.0.0-fabric

First-person Model
by tr7zw
2.2.3-1.20.2

Forge Config API Port
by Fuzs
v9.0.0-1.20.2-Fabric

Freecam (Modrinth Edition)
by hashalite
1.2.1.1-mc1.20

Full Brightness Toggle
by Serilum
1.20.2-3.0-forge+fabric

Geckolib
by Gecko
4.2.3

Halo HUD
by Crendgrim
4.1+1.20-fabric

Iceberg
by Grend
1.1.15

Indium
by comp500
1.0.27+mc1.20.1

Iris Shaders
by coderbot
1.6.9+1.20.2

Jade 🔍
by Snownee
12.1.3

JourneyMap
by mysticdrew
1.20.2-5.9.15-fabric

Just Enough Items
by mezz
16.0.0.28

Kirin UI
1.16.0+1.20.2

Legendary Tooltips
by Grend
1.4.4

Lithium
by jellysquid3
mc1.20.2-0.12.0

MidnightControls
by Motschen
1.9.0+1.20.2

Mod Menu
by Prospector
8.0.0

ModernFix
by embeddedt
5.7.5+mc1.20.2

More Culling
by fxmorin
v0.19.0-1.20.x

MoreChatHistory
by JackFred2
mc1.19.1-1.1.1

Mouse Tweaks
by YaLTeR
1.20-2.25-fabric

No Chat Reports
by Aizistral
Fabric-1.20.2-v2.3.1

Not Enough Animations
by tr7zw
1.6.4-1.20.2

Not Enough Crashes
by natanfudge
4.4.6+1.20.2-fabric

Pehkui
by Virtuoel
3.7.8+1.14.4-1.20.1

Physics Mod
by haubna
3.0.9a

PlayerAbilityLib
by Pyrofab
1.9.0

Presence Footsteps
by Sollace
1.9.0

Prism
by Grend
1.0.5

Rangefinder HUD
by Sea_Kerman
1.2.1-1.20.2

Reese's Sodium Options
by FlashyReese
mc1.20.2-1.6.5

Rethinking Voxels
by gri573
r0.1-alpha4

Shulker Box Tooltip
by MisterPeModder
4.0.5+1.20.2-fabric

Simple HUD Utilities
by johnvictorfs
2.6.0

Simple Voice Chat
by henkelmax
fabric-1.20.2-2.4.26

Sodium
by jellysquid3
mc1.20.2-0.5.3

Sodium Extra
by FlashyReese
mc1.20.2-0.5.2

Starlight (Fabric)
by spottedleaf
1.1.2+1.20.2

TotemCounter
by uku
1.3.1+mc1.20.2

Very Many Players (Fabric)
by ishland
0.2.0+beta.7.117+1.20.2

Visuality
by PinkGoosik
0.7.1+1.20

Xray_Ultimate_1.20.1_v4.2.5.zip

YetAnotherConfigLib
by isxander
3.2.1+1.20.2-fabric

Your Options Shall Be Respected (YOSBR)
by shedaniel
0.1.2

Zoomify
by isxander
2.12.0

fast-ip-ping
by fallen-breath
mc1.20.1-v1.0.0spark
by lucko
1.10.54-fabric

ukulib
by uku
1.0.1+1.20.2

### Log File

[10:49:41] [Render thread/WARN]:
 Attempting to apply workarounds for the NVIDIA Graphics Driver...
[10:49:41] [Render thread/WARN]:
 If the game crashes immediately after this point, please make a bug report: https://github.com/CaffeineMC/sodium-fabric/issues

thats the error, here is the entire rest of the console if you need it

[11:44:43] [Render thread/INFO]:
 [Config Manager (Read)] Set property 'dot_colour' to '0/255/255/255'.
[11:44:47] [Render thread/INFO]:
 Reading config file NoChatReports/NCR-Common.json...
[11:44:47] [Render thread/INFO]:
 Reading config file NoChatReports/NCR-Client.json...
[11:44:47] [Render thread/INFO]:
 Reading config file NoChatReports/NCR-ServerPreferences.json...
[11:44:47] [Render thread/INFO]:
 Reading config file NoChatReports/NCR-Encryption.json...
[11:44:47] [Render thread/INFO]:
 Writing config file NoChatReports/NCR-Common.json...
[11:44:47] [Render thread/INFO]:
 Writing config file NoChatReports/NCR-Encryption.json...
[11:44:47] [Render thread/INFO]:
 Client initialization...
[11:44:47] [Render thread/INFO]:
 [ShulkerBoxTooltip] Could not find configuration file, creating default file
[11:44:49] [Render thread/INFO]:
 [voicechat] Compatibility version 17
[11:44:49] [Render thread/INFO]:
 [voicechat] Loading plugins
[11:44:49] [Render thread/INFO]:
 [voicechat] Loaded 0 plugin(s)
[11:44:49] [Render thread/INFO]:
 [voicechat] Initializing plugins
[11:44:49] [Render thread/INFO]:
 [voicechat] Initialized 0 plugin(s)
[11:44:50] [Render thread/INFO]:
 Registering S2C receiver with id architectury:spawn_entity_packet
[11:44:50] [Render thread/INFO]:
 Loading colorfulhearts.toml config file
[11:44:50] [Render thread/INFO]:
 Successfully loaded colorfulhearts.toml config file
[11:44:50] [Render thread/INFO]:
 Loading Description Cache
[11:44:50] [Render thread/INFO]:
 Deserializing Config from 'C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\Client\config\dynamiccrosshair.json5'
[11:44:52] [Render thread/INFO]:
 [Indigo] Different rendering plugin detected; not applying Indigo.
[11:44:52] [Render thread/INFO]:
 Deserializing Config from 'C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\Client\config\halohud.json5'
[11:44:52] [Render thread/INFO]:
 Sending ConfigManager...
[11:44:52] [Render thread/INFO]:
 Sending ConfigManager took 4.865 ms
[11:44:53] [Render thread/INFO]:
 [STDOUT]: [Mouse Tweaks] Main.initialize()
[11:44:53] [Render thread/INFO]:
 [STDOUT]: [Mouse Tweaks] Initialized.
[11:44:53] [Render thread/INFO]:
 RangefinderHUD started
[11:44:53] [Render thread/INFO]:
 Initialized successfully.
[11:44:54] [Render thread/INFO]:
 [voicechat] Using Cloth Config GUI
[11:44:54] [Render thread/INFO]:
 [voicechat] Loading Opus
[11:44:57] [Render thread/INFO]:
 Mixing client.MixinOptions from mixins/common/nochatreports.mixins.json into net.minecraft.class_315
[11:44:57] [Render thread/INFO]:
 Renaming synthetic method lambda$onlyShowSecureChat$0(Ljava/lang/Boolean;)V to md437e48$nochatreports$lambda$onlyShowSecureChat$0$2 in mixins/common/nochatreports.mixins.json:client.MixinOptions from mod nochatreports
[11:44:57] [Render thread/INFO]:
 Mixing client.MixinChatComponent from mixins/common/nochatreports.mixins.json into net.minecraft.class_338
[11:44:57] [Render thread/INFO]:
 Renaming synthetic method lambda$modifyGUIMessage$1()V to md437e48$nochatreports$lambda$modifyGUIMessage$1$0 in mixins/common/nochatreports.mixins.json:client.MixinChatComponent from mod nochatreports
[11:44:57] [Render thread/INFO]:
 Renaming synthetic method lambda$modifyGUIMessage$0(Lnet/minecraft/class_5348;Lnet/minecraft/class_2561;)V to md437e48$nochatreports$lambda$modifyGUIMessage$0$1 in mixins/common/nochatreports.mixins.json:client.MixinChatComponent from mod nochatreports
[11:44:57] [Render thread/INFO]:
 Mixing client.MixinGuiMessageTagIcon from mixins/common/nochatreports.mixins.json into net.minecraft.class_7591$class_7592
[11:44:57] [Render thread/INFO]:
 Renaming @Invoker method create(Ljava/lang/String;ILnet/minecraft/class_2960;II)Lnet/minecraft/class_7591$class_7592; to create$nochatreports_$md$437e48$0 in mixins/common/nochatreports.mixins.json:client.MixinGuiMessageTagIcon from mod nochatreports
[11:44:57] [Render thread/INFO]:
 Instantiating Mojang DFU
[11:44:59] [Render thread/INFO]:
 Backend library: LWJGL version 3.3.2-snapshot
[11:44:59] [Render thread/WARN]:
 Attempting to apply workarounds for the NVIDIA Graphics Driver...
[11:44:59] [Render thread/WARN]:
 If the game crashes immediately after this point, please make a bug report: https://github.com/CaffeineMC/sodium-fabric/issues
[11:44:59] [Render thread/INFO]:
 ... Successfully applied workarounds for the NVIDIA Graphics Driver!
[11:45:00] [Render thread/INFO]:
 OpenGL Vendor: NVIDIA Corporation
[11:45:00] [Render thread/INFO]:
 OpenGL Renderer: NVIDIA GeForce GT 1030/PCIe/SSE2
[11:45:00] [Render thread/INFO]:
 OpenGL Version: 3.2.0 NVIDIA 536.23
[11:45:00] [Datafixer Bootstrap/INFO]:
 192 Datafixer optimizations took 1461 milliseconds
[11:45:01] [Render thread/INFO]:
 ARRP register - before vanilla
[11:45:01] [Render thread/INFO]:
 ARRP register - after vanilla
[11:45:01] [Render thread/INFO]:
 ARRP register - before user
[11:45:01] [Render thread/WARN]:
 Removed resource pack minecraft:supporteatinganimation from options because it doesn't seem to exist anymore
[11:45:04] [Render thread/WARN]:
 Method overwrite conflict for getModel in fabric-model-loading-api-v1.mixins.json:BakedModelManagerMixin from mod fabric-model-loading-api-v1, previously written by foundationgames.enhancedblockentities.mixin.BakedModelManagerMixin. Skipping method.
[11:45:06] [Render thread/INFO]:
 Mixing client.MixinChatListener from mixins/common/nochatreports.mixins.json into net.minecraft.class_7594
[11:45:06] [Render thread/INFO]:
 Mixing client.MixinServerData from mixins/common/nochatreports.mixins.json into net.minecraft.class_642

### Crash Report

[crash-2023-10-08_11.55.59-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12841112/crash-2023-10-08_11.55.59-client.txt)

**Comment by hitheremynameisender** [comment]
h e l p

**Comment by pajicadvance** [comment]
You have outdated mods and mods incompatible with your game version, this has nothing to do with our mods.

**Comment by hitheremynameisender** [comment]
which ones are incompatible or outdated? I would like to play minecraft again but thanks for telling me

**Comment by Poopooracoocoo** [comment]
As your issue is not about CaffeineMC mods, I recommend that you post in the Fabric Discord or make a discussion in the Fabric repo.

**Comment by hitheremynameisender** [comment]
oki ty
