### ISSUE TITLE
Game crashes when entering a specific area of the world

### ISSUE THREAD

**Issue by TR8V** [jellysquid3/Sodium#2112]
### Bug Description

When entering a specific area of the world, the game freezes for a moment before crashing. It's an area that I believe I've explored before and used to work. I can escape the area if I open the world again with render distance set low beforehand, letting me leave the area.

### Reproduction Steps

I don't know what's causing this or how to reproduce this. 
I'd asked this question in the Quilt Discord. After checking it out, they said it looks to be caused by Sodium, and to ask here.

### Log File

https://mclo.gs/UuqZN2P

### Crash Report

https://mclo.gs/GQgyDwv

**Comment by jellysquid3** [comment]
Older versions of Sodium are not supported. This issue likely does not exist in Sodium 0.5.3.
