### ISSUE TITLE
RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!

### ISSUE THREAD

**Issue by GetSlained** [jellysquid3/Sodium#2113]
### Bug Description

i'm making my own modpack. I've fixed many issues related to the mods versions. the last change ive made was changing indium 1.0.25 to 1.0.24, and now it says this:

![Cattura di schermata (25)](https://github.com/CaffeineMC/sodium-fabric/assets/69822642/14799517-f448-406c-8e55-42b63c505d30)
 i honestly dont know what to do.

### Reproduction Steps

i just added some mods thats it

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12846121/latest.log)

### Crash Report

[crash-2023-06-03_22.41.11-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12846130/crash-2023-06-03_22.41.11-client.txt)

**Comment by MeeniMc** [comment]
Looks like the error is actually from mod memoryleakfix. Looks like this mod mixin into Sodium, and you would need to find their version that was specifically designed for Sodium 0.5.1.

**Comment by Poopooracoocoo** [comment]
As per its CurseForge page, MemoryLeakFix is no longer being updated on CurseForge as it has moved to Modrinth.

https://modrinth.com/mod/memoryleakfix/version/v1.1.2

MemoryLeakFix version 1.0.0 was very broken.
