### ISSUE TITLE
Rendering entity in world (Item Frame)

### ISSUE THREAD

**Issue by CyberSer0** [jellysquid3/Sodium#212]
### Reproduction Steps

1. Put item frame in world
2. Put a map in it
3. Play for some time
4. Turn off game/Restart computer
5. Turn game on again
6. Get into world with item frame
7. The game crashes

### Crash Report File
[GitHub Gist](https://gist.github.com/WolfArt/d37cc3ae68e02b6342bda3ebb3b27362)

### Additional Information
I use these mods:
sodium-fabric-mc1.16.1-0.1.0
fabric-api-0.16.0+build.384-1.16.1
worldedit-fabric-mc1.16.1-7.2.0-beta-02
grid-20w17a-fabric0.6.2-1.5
lambdynamiclights-fabric-1.2.2+1.16.1
darkness-mc116-1.5.43
cmdkeybind-1.4.3-1.16
dark-loading-screen-1.3.2
Mambience-2.1.0-1.16
PresenceFootsteps-r26+1.16-rc1

I tested every mod and only sodium didn't work with the world and the item frame.
Furthermore you can access the world again with sodium when you disable sodium, get into the world, destroy the item frame, enable sodium again, get into the world and then you can place the item frames

**Comment by jellysquid3** [comment]
Should be fixed with 4f8646cf.
