### ISSUE TITLE
While Crouching, aimingcross for placing blocks is wrong.

### ISSUE THREAD

**Issue by 1GodRage** [jellysquid3/Sodium#2122]
### Bug Description

I am facing a bug in Sodium, since years.
For me, sodium always had this bug.

When placing stairs or slabs while crouching, the cross-aim is on the right spot but can't place the block.

I took a video because it would be difficult to show it with words/screenshots.
 https://www.youtube.com/watch?v=jp5BglnOMIo

- It happens almost always. Rarely, it doesn't happens.
- The size of the area where the cross-aiming has no effect varies.
- I'm on windows, i had this bug thought multiple Windows computers. (win7, win10)
- I noticed this bug since i switched from Optifine to Sodium, some years ago. _(i can't tell you exactly what version)_

### Reproduction Steps

 Placing a line of stairs or slab (need to aim in a corner).

### Log File

No related.

### Crash Report

No crash.

**Comment by jellysquid3** [comment]
Sodium does not affect the raycast for selecting a block at all. Your problem must be caused by something else you have installed, but since you have decided that your log files are "not related" (even though we _explicitly_ tell you to upload them anyways), we cannot tell you what the actual problem is.

**Comment by 1GodRage** [comment]
Sorry that my message annoyed you. :'(
Seems that the problem is the "fancy" movement added by Sodium. It moves the crosshair for fanciness.
Fresh install + Sodium makes this behavior. Since years.
I hope you are right and that is me doing something wrong.

The situation is even more visible with trapdoors:
https://www.youtube.com/watch?v=wMSkwajUDgo
I will search for whatever may add this "visual movement"

**Comment by 1GodRage** [comment]
Ok, I found the problem. It's a <strike>Sodium feature</strike>: "head movement". Sadly, there is no indication about the inaccurate crosshair. :'(

**edit:** it's a native Minecraft feature! Thank you @Lolothepro

**Comment by Lolothepro** [comment]
> Ok, I found the problem. It's a **Sodium feature**: "head movement". Sadly, there is no indication about the inaccurate crosshair. :'(

It's not a Sodium feature... it's a Minecraft setting...

**Comment by 1GodRage** [comment]
You are right. I thought it was Sodium feature because there where English description instead of my native langage, and 2nd reason was Optifine delete that feature.
Sorry for the time lost for you.
But happy to have solved that absolutely annoying issue!!!
**Thank you and sorry.**

edit: 3rd and main reason: after installing Fabric + Sodium, that head movement is active again by itself!!
