### ISSUE TITLE
weird-looking bushes on y=96

### ISSUE THREAD

**Issue by Prime54601** [jellysquid3/Sodium#2123]
### Bug Description

textures of top bushes of leaves in y=95 (which means the bush is in y=96) breaks regardless of shaders or other settings on 1.20.1
note: I tried uninstalling sodium and the bug went away. There should be nothing to do with other mods.
![2023-10-14_21 34 39](https://github.com/CaffeineMC/sodium-fabric/assets/143816248/537fd94a-6d01-43ea-826f-d9c58aae7deb)

### Reproduction Steps

install any texture pack with leave bushes (e.g. stay true)
place any leaf at y=95

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/12905827/latest.log)

### Crash Report

The game didn't crash.

**Comment by Lolothepro** [comment]
I can't reproduce this bug with Sodium only

**Comment by Prime54601** [comment]
The problem is actually associated with chunksfadein mod. I didn't test it individually lol.
