### ISSUE TITLE
java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/gui/options/TextProvider

### ISSUE THREAD

**Issue by cookie1599** [jellysquid3/Sodium#2127]
### Bug Description

**Version Information
1.20.1 and Forge 47.2.0**

### Reproduction Steps

The game will crash once you open Minecraft using forge

### Log File

[crash-2023-05-05_18.17.39-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12924009/crash-2023-05-05_18.17.39-client.txt)

### Crash Report

[crash-2023-10-17_10.29.11-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/12924020/crash-2023-10-17_10.29.11-client.txt)

**Comment by rilakuma123** [comment]
Sodium is not available for Minecraft Forge. 

The first crash report is Fabric. You're using an unpublished version of Sodium. Physics Mod is incompatible with it

The second crash report seems incomplete. Looks like you're using Rubidium and Rubidium Extra. Rubidium Extra is a fork of Sodium Extra that ports it to Forge. Rubidium is a fork of Sodium that ports it to Forge. If you have issues with them or need help using them, please go to the right places
