### ISSUE TITLE
Pitcher plants are rendered slightly differently with Sodium (pixel positions are different)

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2128]
### Bug Description

Pitcher plants are rendered slightly differently with Sodium

Sodium:
![image](https://media.discordapp.net/attachments/651120262129123330/1164631053965742190/2023-10-19_20.20.24.png?ex=6543ea31&is=65317531&hm=5e60061d1cbc3e5282905a9f80873860cac6a95095f6d94435fe2326e9c4f8b2&=&width=1177&height=662)
 
Vanilla:
![image](https://media.discordapp.net/attachments/651120262129123330/1164631054607466537/2023-10-19_20.21.17.png?ex=6543ea31&is=65317531&hm=3e093125520069247e806c791b654e2a1e2ed325f038f6aab9ecc7ee5883b2f9&=&width=1177&height=662)

### Reproduction Steps

\\

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13046534/latest.log)

### Crash Report

[crash-2023-10-19_20.48.42-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13046553/crash-2023-10-19_20.48.42-client.txt)

**Comment by Fnige** [comment]
Does installing https://modrinth.com/mod/sodium-shadowy-path-blocks mostly fix the issue?

Iirc it wont fix it fully but itll be closer to vanilla

**Comment by douira** [comment]
Isn't this just wet farmland? I think the bug is referring to the minute difference in alignment of the pitcher plant's quads.

**Comment by jellysquid3** [comment]
Please annotate the exact issue you are describing. There are multiple things which differ between the images and it's not clear what you are trying to point out.

**Comment by jellysquid3** [comment]
This is not a truly fixable problem with Sodium. There will always be a very small amount of vertex imprecision when addressing cross-hatch models like this, and the compact vertex format we're using is too beneficial to justify disabling it for extremely small problems like this.

We may be able to improve the defect to the point of being imperceptible (i.e. if we use 20-bit vertex positions), but it will never be perfect.
