### ISSUE TITLE
incompatability issues with a bit more mods that this shows

### ISSUE THREAD

**Issue by RobertasJ** [jellysquid3/Sodium#213]
[crash-2020-07-30_15.19.03-client.txt](https://github.com/jellysquid3/sodium-fabric/files/5001458/crash-2020-07-30_15.19.03-client.txt)
it has incomapability issues with a mod its not this mod but this one was picked up first

**Comment by RobertasJ** [comment]
its incompatible with the sandwichable mod

**Comment by LucilleTea** [comment]
Your crash log shows an incompatibility with Immersive Portals, which is tracked in #15 
I can't tell you more about the sandwichable incompatibility unless you post a crash log for it, but it may be due to #5

**Comment by RobertasJ** [comment]
Ok

**Comment by RobertasJ** [comment]
I think it just needs to do that update to give better compatability

**Comment by RobertasJ** [comment]
Yes I think it just needs to be comparable with that api
