### ISSUE TITLE
Overlapping Text

### ISSUE THREAD

**Issue by PowerRubik** [jellysquid3/Sodium#2130]
### Bug Description

When i join a server the various stages of connection to a server (Connecting to server, Encrypting etc.) overlap with the cancel button. This however only happens when the GUI scale is at 2: when it's at 1 it shifts the text under the cancel button instead.
![2023-10-19_14 27 05](https://github.com/CaffeineMC/sodium-fabric/assets/126591243/243d9c68-3eb2-4aa0-9edd-928d99504af1)

### Reproduction Steps

1: Set GUI scale to 2

2: Join a server

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13058247/latest.log)

### Crash Report

[crash-2023-10-20_22.10.52-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13058254/crash-2023-10-20_22.10.52-client.txt)

**Comment by astridellensdottir** [comment]
Does this also happen when you start the game with only Sodium installed?

**Comment by PowerRubik** [comment]
yes, it happens even if i only use sodium

**Comment by rilakuma123** [comment]
Can you provide those logs? With just Sodium, I mean.

**Comment by MeeniMc** [comment]
Try disabling your resource packs.

**Comment by PowerRubik** [comment]
I already tried, could it have something to do with the fact that I'm on Mac?

**Comment by PowerRubik** [comment]
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13187921/latest.log)
I'm 99% sure that the one in the bug report was just with Sodium, but i generated a new one just to be sure.

**Comment by PowerRubik** [comment]
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13187939/latest.log)

**Comment by hexadecimal233** [comment]
Mac has some rendering issues as far as i know

**Comment by jellysquid3** [comment]
I don't see why Sodium would cause this issue, and I can't reproduce it on my side either. There's also no reason I could imagine as to why this issue would be platform-specific, either. Can you remove all mods (including Sodium) and check that it doesn't still happen?

**Comment by PowerRubik** [comment]
Oh didn't think of trying using vanilla, and I realized the issue still persists even without sodium. I'll close the issue (also sorry for the false report)
