### ISSUE TITLE
Sodium conflicts with other mod's render in 1.20.2

### ISSUE THREAD

**Issue by Dormant11** [jellysquid3/Sodium#2136]
### Request Description

One of my mods don't work any more because of sodium, they use to work in 1.20.1 (one of the older files). Can you please make a version of sodium without that change in 1.20.2 to let the other mod render.

**Comment by Timolino456** [comment]
Of course they can, no problem even though you have given absolutely zero information

**Comment by TheUserCreated** [comment]
You need to give more info for anyone to help. What mod is broken, what versions of each mod do you have, a copy of the game log, exactly how things are broken. The issue template tells you all this but you seem to have entirely ignored it.
