### ISSUE TITLE
Sodium stops function of custom potions

### ISSUE THREAD

**Issue by randomguy26gi** [jellysquid3/Sodium#2137]
### Bug Description

I'm a person that likes custom items. Today, I made a test potion after adding Sodium 0.5.2, and surprise, it didn't work. I then went on vanilla Minecraft, and it worked just fine. Heres the command I used if you need it: /give @p splash_potion{custom_potion_effects:[{id:glowing,duration:72000,amplifier:1}]} 1

### Reproduction Steps

It's really quite simple. Just play Minecraft with Sodium added. Then, go the GamerGeeks website. Find the bar on the left side and select "Potions/Arrows". Choose any effect you want, and enter in the duration (in ticks) and the level or amplifier (amplifier 0 is 1, 1 is 2, so on.) Copy the command, and run it in chat. The description of the potion should be "No Effects".

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13096564/latest.log)

### Crash Report

[crash-2023-10-23_21.25.48-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13098116/crash-2023-10-23_21.25.48-client.txt)
Note: This bug obviously didn't crash my game.

**Comment by douira** [comment]
I'm guessing this is just a thing affecting the glowing effect and not potions in general. Can you confirm that this is just a visual thing and not something else? Does this command work without sodium as expected? Does it work on previous version of sodium?

**Comment by pajicadvance** [comment]
I cannot reproduce this with Sodium 0.5.3. The command you provided created a potion with the description "Glowing II". The glowing effect works as intended and looks identical to the effect in vanilla.
