### ISSUE TITLE
Minecraft won't start up

### ISSUE THREAD

**Issue by noahpugz** [jellysquid3/Sodium#2138]
### Bug Description

Having issues with my minecraft starting, not sure if it has something to do with sodium or not. I have posted the logs, can anyone help me out??

### Reproduction Steps

N/A

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13133802/latest.log)

### Crash Report

[2023-10-24-7.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/13133824/2023-10-24-7.log.gz)

**Comment by pajicadvance** [comment]
This has nothing to do with Sodium, the mod Remove Reloading Screen is crashing the game.
