### ISSUE TITLE
Create Compat w/ Sodium

### ISSUE THREAD

**Issue by Xtremeone23** [jellysquid3/Sodium#2139]
### Bug Description

When loading the game with Create and Sodium, Create tells me I need version 0.5.0 or up of Sodium, and I have version 0.5.3, yet it crashes before loading the game

### Reproduction Steps

Install Create and Sodium newest fabric/quilt versions. Create = 0.5.1-d-build.1161+mc1.20.1, Sodium = 0.5.3

### Log File

file:///home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/DeckCraft/.minecraft/logs/latest.log

### Crash Report

file:///home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/DeckCraft/.minecraft/crash-reports/crash-2023-10-25_14.46.57.2177-quilt_loader.txt

**Comment by pajicadvance** [comment]
In order to use Sodium with Create, you have to use Sodium 0.4.10. Create hasn't been updated to support newer versions of Sodium.
