### ISSUE TITLE
Sodium 0.5.3 - Execution protection violation

### ISSUE THREAD

**Issue by Contrabass26** [jellysquid3/Sodium#2142]
### Bug Description

I am experiencing a crash when starting Minecraft 1.20.2 with Fabric 0.14.24 and Sodium 0.5.3. I am using the Prism Launcher (having read the list of known issues), although I experienced the same crash when using MultiMC. My graphics card is an NVIDIA GeForce GTX 1050 Ti and I have updated my graphics driver today (version 545.92). I am using Windows 10 and Java 17 from Eclipse Adoptium. Other system specifications can be provided if they would be helpful. It seems relevant to mention that I am only able to set the maximum memory allocation in Prism Launcher up to 1536 MiB, otherwise the Java test fails.

### Reproduction Steps

1. Install and open Prism Launcher
2. Create a new instance with the settings and mods described above
3. Launch the instance

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13179341/latest.log)

### Crash Report

My "crash-reports" folder has not been generated yet. I do have a crash report which was in the root ".minecraft" folder, which I believe contains a lot of the same information: [hs_err_pid2312.log](https://github.com/CaffeineMC/sodium-fabric/files/13179378/hs_err_pid2312.log)

**Comment by pajicadvance** [comment]
Did this issue start occurring only after the driver update?

**Comment by Contrabass26** [comment]
No, I did the driver update to try and fix the issue, but it didn't help.

**Comment by pajicadvance** [comment]
It seems like you're using a 32-bit installation of Java. Try using a 64-bit version instead (you should then be able to allocate more than 1536 MiB as well).

**Comment by jellysquid3** [comment]
The bug is with Sodium, as it does not like it when you use a 32-bit version of Java with a NVIDIA GPU. There is a proposed fix [here](https://github.com/CaffeineMC/sodium-fabric/commit/09494c4b208c9c76f3afd27bd11fbf2d670ea780) but is not merged.

**Comment by Contrabass26** [comment]
Aha! All working properly now - obviously still an issue but not for me. Thanks for the help.
