### ISSUE TITLE
Sodium 0.4.4 1.19.2 minecraft won't start with sodium

### ISSUE THREAD

**Issue by Azimkin** [jellysquid3/Sodium#2145]
### Bug Description

minecraft won't start with sodium

### Reproduction Steps

minecraft lag while loading

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13196009/latest.log)

### Crash Report

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13196011/latest.log)

**Comment by embeddedt** [comment]
There is no crash in this log?

**Comment by jellysquid3** [comment]
Read the [wiki page about driver compatibility.](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility).
