### ISSUE TITLE
Sodium crash upon opening video settings 

### ISSUE THREAD

**Issue by Pinemarten04** [jellysquid3/Sodium#2146]
### Bug Description

When opening video settings from any menu, the game shows saving world and crashes.

### Reproduction Steps

I open video settings and game crashes.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13222641/latest.log)

### Crash Report

[crash-2023-10-31_20.53.41-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13222649/crash-2023-10-31_20.53.41-client.txt)

**Comment by rilakuma123** [comment]
You've got both Bobby and Farsight. You'll need to pick one.

**Comment by jellysquid3** [comment]
You did not read the issue template -- your problem is nothing to do with Sodium.
