### ISSUE TITLE
Float.NaN in clouds_height of the DimensionEffects

### ISSUE THREAD

**Issue by SuperCatMaster** [jellysquid3/Sodium#2147]
### Bug Description

The End and The Nether use Float.NaN in constructor of the DimensionEffects to remove clouds. But when I tried use it in my DimensionEffects, clouds still renders.
Although in my other DimensionEffects, in which i use constant values in clouds_height, it works fine.

### Reproduction Steps

1. Register cutsom DimensionEffects via DimensionRenderingRegistry.
2. Set in registered DimensionEffects clouds_height to Float.NaN
3. Launch the game.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13224200/latest.log)

### Crash Report

[crash-2023-11-01_14.24.57-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13224201/crash-2023-11-01_14.24.57-client.txt)

**Comment by embeddedt** [comment]
This is a good catch. Vanilla explicitly checks whether cloud height is NaN and skips rendering if so. The same check needs to be added to Sodium.
