### ISSUE TITLE
My minecraft 1.20.1 crash when im joining singleplayer or multi 

### ISSUE THREAD

**Issue by kharispg** [jellysquid3/Sodium#2151]
### Bug Description

My minecraft 1.20.1 crash when im joining singleplayer or multi 

### Reproduction Steps

idk

### Log File

[tl-logger5376103861729680132.txt](https://github.com/CaffeineMC/sodium-fabric/files/13233908/tl-logger5376103861729680132.txt)

### Crash Report

[crash-2023-11-02_10.26.06-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13233902/crash-2023-11-02_10.26.06-client.txt)

**Comment by pajicadvance** [comment]
Cracked launchers are not supported.

**Comment by kharispg** [comment]
not suported what

**Comment by kharispg** [comment]
oh i forgot my minecraft not crashing when im using sodium on 1.19.4
