### ISSUE TITLE
Upload to Curseforge

### ISSUE THREAD

**Issue by At0mkern** [jellysquid3/Sodium#2152]
### Request Description

Pls upload to curseforge again. its so much easier to install mods there. its just time consuming to open the mod folder, find he download on the browser, drag it into the mod folder, install other mods that are needed to run that mod. Curseforge does all that automatically. Its making life so much easier

**Comment by TheUserCreated** [comment]
consider using a launcher that provides a better experience and isn't curseforge, like prism launcher or the new experimental [modrinth launcher.](https://modrinth.com/app)
I don't think curseforge has addressed *any* of the issues that caused sodium to stop being uploaded there, so I don't think it'll be put back up there.
