### ISSUE TITLE
Minecraft Sodium 1.16.1 Cant Change Render Distance Past 16

### ISSUE THREAD

**Issue by EsoogDrut** [jellysquid3/Sodium#2153]
Yesterday I had to reinstall MultiMC for speedrunning. I reinstalled everything and now my render distance cant go past 16

**Comment by jellysquid3** [comment]
That's a problem with your launcher configuration, not the mod. And this is not a support forum.

Make sure you're using a 64-bit version of Java. Minecraft will not allow you to use higher render distances without it.
