### ISSUE TITLE
GL_INVALID_ENUM error with Intel HD Graphics 520 card and Xaero's map mods

### ISSUE THREAD

**Issue by gammaleak** [jellysquid3/Sodium#2154]
### Bug Description

When playing on a client with a minimal mod set (see below) with Intel HD Graphics 520 (Skylake GT2), the log spams the following message multiple times per second:

`[Render thread/INFO]: OpenGL debug message: id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM in glGetIntegerv(pname=GL_TEXTURE_FREE_MEMORY_ATI)'`

This error only occurs with a combination of Sodium and Xaero's map mods. Admittedly, the problem may be with Xaero's, but the error only occurs when Sodium is also loaded.

- OS: Artix Linux (Arch Linux variant using OpenRC instead of systemd)
- Java Runtime: OpenJDK JRE 17.0.9
- Minecraft Java Edition verion 1.20.2
- Fabric Loader: 0.14.24
- Installed mods:
  - Fabric API
  - Fabric Language Kotlin
  - Sodium
  - Xaero's Minimap
  - Xaero's Worldmap

### Reproduction Steps

1. Create a new installation/instance of Minecraft Java Edition 1.20.2 with Fabric Loader version 0.14.24 on a machine with Intel HD Graphics 520
2. Install the mods used in the description above
3. Observe the log for the following message:

`[Render thread/INFO]: OpenGL debug message: id=1, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM in glGetIntegerv(pname=GL_TEXTURE_FREE_MEMORY_ATI)'`

Note: Possibly other Intel HD Graphics cards would produce the same error.

### Log File

Example log file:

[gl_texture_free_memory_ati.log](https://github.com/CaffeineMC/sodium-fabric/files/13257040/gl_texture_free_memory_ati.log)

### Crash Report

Error does not cause a crash. Manual crash log:
[crash-2023-11-04_11.08.12-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13257122/crash-2023-11-04_11.08.12-client.txt)

**Comment by jellysquid3** [comment]
The crash log is always required, even if you are not experiencing a crash. When creating an issue, this is explained and instructions are given to force a crash log (hold F3+C for 10 seconds while in-game). This file contains important information about the hardware/software configuration, so it helps us immensely if you can provide it.

**Comment by jellysquid3** [comment]
My guess as to the problem is that Xaero's Minimap is trying to use the `ATI_meminfo` OpenGL extension (for which Mesa implements in a vendor-agnostic way on most GPUs), and for some reason Sodium's changes to the OpenGL context is making it impossible to access.

You can try disabling the option `Use No Error Context` in `Video Settings > Performance` to see if it fixes the problem.

**Comment by gammaleak** [comment]
Apologies. I skimmed and should have done a better job reading. Please forgive me. I have added the crash log to the original post above.

**Comment by gammaleak** [comment]
> You can try disabling the option Use No Error Context in Video Settings > Performance to see if it fixes the problem.

Following up on this: the log continues to be filled with the error message after disabling the Use No Error Context setting.

**Comment by jellysquid3** [comment]
Since Xaero's Minimap is closed source software, it is difficult for me to debug the issue any further. I don't see any reason as to why Sodium would cause errors like this, either. You will need to report the issue to the authors of the other mod and ask them to look into it.
