### ISSUE TITLE
in some cases, water is not rendered when the player moves and changes chunk

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2157]
[This PR](https://github.com/CaffeineMC/sodium-fabric/pull/2133) fixes the bug, but not [this commit](https://github.com/CaffeineMC/sodium-fabric/commit/93a632fbec3b032627c2b03ebdaa84c7ed8fa1ee)

https://github.com/CaffeineMC/sodium-fabric/assets/68275908/b5b3a744-ab19-4f69-84ee-941dee1d73ff

[sqdfsdf.zip](https://github.com/CaffeineMC/sodium-fabric/files/13288796/sqdfsdf.zip)

**Comment by embeddedt** [comment]
The video is blank in two video players that I tried, but this might be an issue on my system.

**Comment by douira** [comment]
I can't see the video either.

**Comment by embeddedt** [comment]
Here is a video of the given test world, and a reupload of that world without the nested 7-zip archive.

https://github.com/CaffeineMC/sodium-fabric/assets/42941056/3b5fd4a2-8fd5-421b-8ba9-ef08ae61d8fb

[sqdfsdf.zip](https://github.com/CaffeineMC/sodium-fabric/files/13289783/sqdfsdf.zip)
