### ISSUE TITLE
Fluid rendering is broken with Multiconnect

### ISSUE THREAD

**Issue by Titaniumtown** [jellysquid3/Sodium#216]
### Expected Behavior
Chunks load w/o any graphical issues

### Actual Behavior
the exact opposite 

### Reproduction Steps
Just joined a 1.12.2 server w/ 1.16.1 client with sodium and multiconnect

### Attachments
![2020-07-31_01 40 19](https://user-images.githubusercontent.com/11786225/89003939-0d371b80-d2cf-11ea-982b-78486734274c.png)
![2020-07-31_01 40 28](https://user-images.githubusercontent.com/11786225/89003953-158f5680-d2cf-11ea-8ef9-51fe7ff961bf.png)

### System Information

- Java Version: 14
- CPU: X5670
- GPU: GTX 980 Ti

**Comment by Earthcomputer** [comment]
The rendering looks a little buggy but the lighting itself looks like a multiconnect issue, which I'm aware of and is on my list to fix.

**Comment by mrmangohands** [comment]
This issue is very stale and doesn't contain any info about the version used or the greater mod list, closing.
