### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Hoozuki45** [jellysquid3/Sodium#2164]
### Bug Description

I don't really know what i am doing, i'm doing this as intructed in the crash log: https://paste.ee/p/WgGIz

I download a modpack called Prominence II [FABRIC] from Cursefoge, and when running it the game simply crases and gives me the log i'm posting here

I'm running a linux mint operating system

### Reproduction Steps

I just downloaded the modpack using FTBapp and opened it on MultiMC

### Log File

[log.txt](https://github.com/CaffeineMC/sodium-fabric/files/13360934/log.txt)

### Crash Report

[hs_err_pid101059.log](https://github.com/CaffeineMC/sodium-fabric/files/13361034/hs_err_pid101059.log)

**Comment by jellysquid3** [comment]
This is not a support forum, and we have nothing to do with the modpack.
