### ISSUE TITLE
`WorldSlice#getColor` cannot be called with custom ColorResolvers

### ISSUE THREAD

**Issue by embeddedt** [jellysquid3/Sodium#2166]
### Request Description

In Sodium 0.5+, `WorldSlice#getColor` converts to a `BiomeColorSource` internally before retrieving the color, and `BiomeColorSource` is an enum that only supports GRASS, WATER, and FOLIAGE. Therefore, there is no way to pass a custom `ColorResolver` and have it work correctly with Sodium 0.5+. An example of a crash this causes (albeit with a Forge mod) can be found [here](https://gist.githubusercontent.com/Gbergz/4dc829382e4a488611cca52787c6031e/raw/c1b621f76b46ad70bc403ff242dd0e0c807f8981/gistfile1.txt).

I think the best way to solve this issue is to remove the enum, and refactor `BiomeColorCache` to look up the appropriate `ColorBuffer` based on the provided `ColorResolver` instance. If this solution sounds reasonable, I am willing to make a PR.

**Comment by jellysquid3** [comment]
For what it is worth, it isn't actually possible to use a custom `ColorResolver` in Minecraft without additional mixins. So this would be enabling functionality that isn't normally available.
