### ISSUE TITLE
Minecraft Logs told me to post a bug report 

### ISSUE THREAD

**Issue by Kastor07** [jellysquid3/Sodium#2167]
### Bug Description

When on 1.20.2 I see this in logs: 
"[21:56:32] [Render thread/WARN]:
 Attempting to apply workarounds for the NVIDIA Graphics Driver...
[21:56:32] [Render thread/WARN]:
 If the game crashes immediately after this point, please make a bug report: https://github.com/CaffeineMC/sodium-fabric/issues"

So I am making this post.
I was using Iris with it, but it said the same thing and I figured it was just Iris but it still occurs without Iris.

### Reproduction Steps

I just started my game and this occurred. I do not know what else to add, but if you need anything else I can provide it.

### Log File

[2023-11-16-7.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/13387073/2023-11-16-7.log.gz)

### Crash Report

[crash-2023-11-16_21.56.34-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13387070/crash-2023-11-16_21.56.34-client.txt)

**Comment by jellysquid3** [comment]
The message in the log file is not related to this. It only says that crashes "immediately after" could be related, but your game crashes much later on.

The actual problem is that whatever version of Enhanced Block Entities is not compatible with your installed mods.
