### ISSUE TITLE
About pojavlauncher world crash

### ISSUE THREAD

**Issue by JSGAMING1** [jellysquid3/Sodium#2179]
### Bug Description

Hi, I play Minecraft on pojavlauncher and my game crashing while loading a world. And it shows this
![Screenshot_2023-11-24-16-44-45-865_net kdt pojavlaunch debug](https://github.com/CaffeineMC/sodium-fabric/assets/140517668/721a47d6-a78d-424f-b587-3dc643f5e719)

### Reproduction Steps

Game crash

### Log File

.minecraft

### Crash Report

.minecraft

**Comment by Timolino456** [comment]
Sodium does not support Pojav

**Comment by pajicadvance** [comment]
See #1916
