### ISSUE TITLE
Sodium crashes when sodium-options.json is corrupt.

### ISSUE THREAD

**Issue by LucilleTea** [jellysquid3/Sodium#219]
### Reproduction Steps
1. Have a corrupt sodium-options.json in the config folder.
2. View sodium's settings or open a world.

### Crash Report File
https://pastebin.com/61ESLENC
https://cdn.discordapp.com/attachments/602805020861267968/737681352349974668/latest.log

### Additional Information
A sample corrupt file:
https://cdn.discordapp.com/attachments/602805020861267968/737956575867699275/sodium-options.json

**Comment by jellysquid3** [comment]
Commit https://github.com/CaffeineMC/sodium-fabric/commit/6f1762fd8844cef131056b9f24927408dd369959 might resolve this.

**Comment by jellysquid3** [comment]
Looks to be fixed in 1.16.x/next.

**Comment by silversquirl** [comment]
This is apparently happening again in 0.3.0, see #862

**Comment by RandomPersonAmogus** [comment]
Still crashing even though Ive deleted sodium-settings.json

**Comment by MeeniMc** [comment]
As of 0.4.11 (presumably earlier) a correct error screen is shown and proposes to reset the problematic option files. Issue is resolved.

**Comment by pajicadvance** [comment]
Not sure when exactly this was fixed either, but Sodium 0.4.10 now shows this screen and the game can proceed to run normally. Thanks for the bump.

![Screenshot_4](https://github.com/CaffeineMC/sodium-fabric/assets/32738446/8425b744-41e9-48da-9071-3cb1ebe8a8ba)
