### ISSUE TITLE
Game crash after "Attempting to apply workarounds for the NVIDIA Graphics Driver..."

### ISSUE THREAD

**Issue by gabriel120pro** [jellysquid3/Sodium#2193]
### Bug Description

I installed the sodium + fabric + fabric api normally, it ran and gave an error, I have never been able to run MC + Sodium because it always crashes, I even tried to use alternative launchers without solutions, the log told me that if I experienced an error to go here

### Reproduction Steps

NVIDEA GPU: GT605 - Driver version: 391.35 (Not available updates)
MultiMC Launcher
Sodium (Last version on date) + Fabric (Last version on date)
Start MC.. but crash

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13536377/latest.log)

### Crash Report

[crash-2023-12-02_09.44.44-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13536418/crash-2023-12-02_09.44.44-client.txt)

**Comment by jellysquid3** [comment]
Sodium currently does not work correctly when using a 32-bit version of Windows with a NVIDIA graphics card. This has [already been fixed](https://github.com/CaffeineMC/sodium-fabric/pull/2143) and will soon be released.

You can temporarily get around this issue by disabling the problematic code. This can be done through editing the `config/sodium-mixins.properties` file to include the following line:

```
mixin.workarounds=false
```

However, you should remove this line again when the next update of Sodium is released, as it disables all workaround handling in the mod, which you probably don't want to do permanently.
