### ISSUE TITLE
block textures disappear

### ISSUE THREAD

**Issue by heirgh** [jellysquid3/Sodium#2195]
### Bug Description

I just wanted to play with optimization, but when I went to the server, my block textures disappeared. I've been sitting for a total of 4 hours now and trying to solve this problem. It’s already dawn outside my window, but I still haven’t found a solution to this problem

![2023-12-03_08 30 41](https://github.com/CaffeineMC/sodium-fabric/assets/152760634/0fb9519d-df8f-479e-ab1c-5f232f615bf9)

### Reproduction Steps

I downloaded it through different sources, one of them was through tlauncher. I downloaded Sodium, logged in, but I don’t have any textures, it’s strange that all the mobs and some blocks still have textures

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13538007/latest.log)

### Crash Report

[crash-2023-12-03_02.57.01-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13538013/crash-2023-12-03_02.57.01-client.txt)

**Comment by embeddedt** [comment]
Sodium is not installed in both the log & crash report you provided. Are you sure these are the correct files that correspond to your screenshot?

**Comment by heirgh** [comment]
> В предоставленном вами журнале и отчете о сбое Sodium не установлен. Вы уверены, что это те файлы, которые соответствуют вашему снимку экрана?

> В предоставленном вам журнале и отчете о натрии не установлено. Вы уверены, что эти файлы соответствуют вашему снимку экрана?

Да, Я уверен. Я скачивал с десятков сайтов,  ведь на других компьютерах такого небыло

**Comment by Felix14-v2** [comment]
TL;DR This is a bug tracker, not a support center.

<details><summary>in English</summary>

> Yes, I'm sure. I downloaded it from different sites, and there wasn't such an issue on other PCs.

You should download mods ONLY from their official sources.

> different sources, one of them was through tlauncher

Piracy is not supported, so this issue already can be closed.

First of all, this is a bug tracker, but not a support center. Second, based on the log info, you don't have Sodium installed at all:
```markdown
[05:30:00] [main/INFO]: Loading 3 mods:

	- fabricloader 0.14.21
	- java 17
	- minecraft 1.20.1
```
So this isn't a problem with Sodium. Ask the server owners why their resourcepack is broken.</details>

> Да, Я уверен. Я скачивал с десятков сайтов, ведь на других компьютерах такого небыло

С каких ещё "десятков сайтов"? Скачивать надо ТОЛЬКО с официального, и ниоткуда больше.

> different sources, one of them was through tlauncher

Кажется, уже на этом можно закрывать репорт.

Во-первых, это багтрекер, а не центр поддержки. А во-вторых, судя по своим логам Sodium у тебя не установлен в принципе:
```markdown
[05:30:00] [main/INFO]: Loading 3 mods:

	- fabricloader 0.14.21
	- java 17
	- minecraft 1.20.1
```
Поэтому это не проблема Sodium. Разбирайся с владельцем сервера, почему его ресурспак теряет текстуры блоков.
