### ISSUE TITLE
Incorrect shadows

### ISSUE THREAD

**Issue by StealWonders** [jellysquid3/Sodium#22]
### Expected Behavior
Expected should be that the shadows either be darker than normal or just no shadows. 
See this screenshot:

![javaw_6H9iexObun](https://user-images.githubusercontent.com/6114858/84602044-eb9be500-ae84-11ea-9c25-60b8ce450948.jpg)

### Actual Behavior
Sodium-fabric causes the shadows of the trees and around the house to be lighter than the actual normal lighting... This looks very unrealistic :(
Screenshot:

![javaw_N7Ve4BOPqH](https://user-images.githubusercontent.com/6114858/84602072-1ab25680-ae85-11ea-9638-8d3cfbb86edd.jpg)

### Reproduction Steps
Build a tree and look at its shadows, generate a vanilla world, and look at those shadows.
This issue is with vanilla generated worlds too. Depending on biome it looks worse or less.

### System Information
- Java Version: 1.8.0_51 64bit
- CPU: Intel(R) Core(TM) i7-4790K
- GPU: GeForce GTX 1080

Enabled in the mod:
- Chunk Renderer: OpenGL 4.6

**Comment by jellysquid3** [comment]
Sodium re-implements the entire smooth lighting engine in order to improve chunk rendering performance and to fix a few graphical issues. As a result, the rendering between the two will not always be identical. 

However, it is rather difficult for me to tell the difference between these screenshots as they've been compressed heavily and the camera moves between each shot. If you're able to, cleaner images would help a lot in diagnosing this problem.

**Comment by lenrik1589** [comment]
It might not be obvious as the marking is not clear but if you look near big outline just on the inner side some blocks look de-saturated/brightened
in this area:
![sodium#22_area_selected](https://user-images.githubusercontent.com/48890625/85218056-2fb84980-b39f-11ea-86a4-6733c2f49b76.jpg)
Alot more contrast:
![sodium#22_contrast_a_bit_more_sane](https://user-images.githubusercontent.com/48890625/85218244-0ac4d600-b3a1-11ea-8d0a-288169653572.jpg)
Edge here:
![sodium#22_contrast_a_bit_more_sane_edge](https://user-images.githubusercontent.com/48890625/85218257-48c1fa00-b3a1-11ea-8f21-7ea8ee74e281.jpg)
this *should* make it a bit clearer

**Comment by StealWonders** [comment]
Sorry for the images but the issue is hardly noticeable.

No sodium:
![2020-06-21_19 21 50](https://user-images.githubusercontent.com/6114858/85231139-180bb000-b3f5-11ea-9655-070f6e1416cc.png)

With sodium:
You may be able to tell that the wall of the house is outlined by a two block wide lighter grass strip.
![2020-06-21_19 21 03](https://user-images.githubusercontent.com/6114858/85231141-1e019100-b3f5-11ea-8fea-9fe2edf0bb43.png)

Image highlighting the border of where the shadows are to make it more clear.
![ApplicationFrameHost_H7wkqAit9E](https://user-images.githubusercontent.com/6114858/85231148-3376bb00-b3f5-11ea-9093-51190c61f827.png)

Light level near the house (using Vanilla):
![javaw_XYtrrbdXjh](https://user-images.githubusercontent.com/6114858/85231167-5608d400-b3f5-11ea-950b-bedf99829fcf.png)

Light level further away from the house (using Vanilla):
![javaw_mYKfgFa0hL](https://user-images.githubusercontent.com/6114858/85231173-60c36900-b3f5-11ea-87e9-8653223753c8.png)

The light levels are the same when using sodium of course but the coloring of the grass (shadows) is brighter than normal grass which makes no sense...

**Comment by jellysquid3** [comment]
Are you using the latest revision of Sodium? There were some issues in an earlier version with the vertex encoding stage that caused weirdness like this.

**Comment by StealWonders** [comment]
> 
> 
> Are you using the latest revision of Sodium? There were some issues in an earlier version with the vertex encoding stage that caused weirdness like this.

Let me recompile. Here are some further screenshots of the issue for now:

![javaw_I1QwmFSH4n](https://user-images.githubusercontent.com/6114858/85231266-f65ef880-b3f5-11ea-860f-75ac0386ce33.png)

![javaw_qXMnOiGbu8](https://user-images.githubusercontent.com/6114858/85231268-f7902580-b3f5-11ea-8222-beacf53c8b21.png)

**Comment by StealWonders** [comment]
Issue is non-existent on the latest commit as of now. I'ma close this!
