### ISSUE TITLE
Sodium now incompatible with Iris?

### ISSUE THREAD

**Issue by AutumnalModding** [jellysquid3/Sodium#2203]
### Bug Description

Hi, I saw in the latest commit that Sodium is now incompatible with *all* Iris versions.
Is this an accidental commit? I play with shaders frequently on Fabric and would like to continue doing so.
(Presumably *some* Iris versions break, and the `*` was an accident?)

### Reproduction Steps

N/A

### Log File

N/A

### Crash Report

N/A

**Comment by jellysquid3** [comment]
It's just some (hopefully temporary) turmoil.

**Comment by AutumnalModding** [comment]
Turmoil?
Are you able to clarify, please?

**Comment by gri573** [comment]
I am not directly involved, but here's what I gathered: there was lack of communication between iris and sodium development teams, and supporting iris is a burden until that is resolved

**Comment by jellysquid3** [comment]
I'm not going to keep the `breaks` clause as it was, so it's not a concern to users any longer. But I'm still not really happy with the situation that led to it in the first place, and relations between our teams is going to probably be stretched for a while.

**Comment by AutumnalModding** [comment]
If I may ask - what lead to said relations being stretched?
