### ISSUE TITLE
[Feature Request] Option to not render blocks behind barriers

### ISSUE THREAD

**Issue by couleurm** [jellysquid3/Sodium#2208]
When playing on say, PvP servers it'd be a useful optimization setting to be able to not render the fancy map details beyond the barrier blocks

« Barrier culling »: *Do not render blocks viewed behind barriers*

**Comment by jellysquid3** [comment]
Implementing this is very non-trivial and would require dramatic changes to how occlusion culling works. Even determining what's "behind barrier blocks" is difficult because it would require us to scan the entire world to figure out what part of the map is "sealed", which is not feasible.
