### ISSUE TITLE
Weird issue with lava rendering

### ISSUE THREAD

**Issue by Titaniumtown** [jellysquid3/Sodium#221]
### Expected Behavior
Lava should look normal

### Actual Behavior
The exact opposite.

### Reproduction Steps
Random, idk how to reproduce.

### Attachments
![2020-07-31_15 23 23](https://user-images.githubusercontent.com/11786225/89069841-f2ea5580-d341-11ea-9dea-45032e1856f2.png)

### System Information

- Java Version: 14
- CPU: X5670
- GPU: GTX 980 Ti

**Comment by jellysquid3** [comment]
Closing as duplicate of #216.
