### ISSUE TITLE
The posture of the villagers lying in bed is abnormal

### ISSUE THREAD

**Issue by A0000Xz** [jellysquid3/Sodium#2211]
### Bug Description

![2023-12-16_22 46 02](https://github.com/CaffeineMC/sodium-fabric/assets/122650088/694d58be-6f7a-48e6-8990-99d978b3bd15)
![2023-12-16_22 46 09](https://github.com/CaffeineMC/sodium-fabric/assets/122650088/b3484394-16e1-4b4b-86c8-e4f0f05edce2)
Not only the villagers, but also the players lying in bed will be as shown in the picture.
At that time, I repeatedly investigated and found that this phenomenon would occur when sodium was present
Minecraft Version:1.20.4
Sodium Version:5.4 and 5.5
After verification, version 5.3 of sodium does not have this issue(1.20.1)

### Reproduction Steps

You just need to ensure that there is a version 5.4 or 5.5 sodium mod in the game（Especially 1.20.4）
Then observe the villagers and players sleeping on the bed

### Log File

not have

### Crash Report

not have

**Comment by Poopooracoocoo** [comment]
Sounds like the Fabric API bug that was just fixed

**Comment by A0000Xz** [comment]
That's true, it's a coincidence. I didn't even know that the Fabric API was updated
