### ISSUE TITLE
0.54/0.55版本的Sodium在Intel Arc显卡上崩溃

### ISSUE THREAD

**Issue by mmyddd** [jellysquid3/Sodium#2212]
### Bug Description

在我的世界1.20.3以及以后的版本使用0.54/0.55版本的Sodium时，启动器报告了游戏崩溃，当我使用包括0.53在内之前的Sodium版本时可以正常加载

### Reproduction Steps

在Intel Arc A750/A770显卡上，驱动版本为5081(在此之前的版本也会崩溃)，游戏版本1.20.4-Fabric 0.15.2，Fabric API-0.91.2，安装Sodium0.54/0.55版本，游戏会直接崩溃，并且没有Fabric的崩溃提示

### Log File

Sodium 0.54[错误报告-2023-12-19_15.52.41.zip](https://github.com/CaffeineMC/sodium-fabric/files/13712638/-2023-12-19_15.52.41.zip)
Sodium 0.55[错误报告-2023-12-19_15.53.43.zip](https://github.com/CaffeineMC/sodium-fabric/files/13712644/-2023-12-19_15.53.43.zip)

### Crash Report

[crash-2023-12-19_15.52.38-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13712670/crash-2023-12-19_15.52.38-client.txt)
[crash-2023-12-19_15.53.40-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13712671/crash-2023-12-19_15.53.40-client.txt)

**Comment by mmyddd** [comment]
然而可以安装该驱动版本的所有Intel Arc显卡上都会出现该问题

**Comment by jellysquid3** [comment]
https://github.com/CaffeineMC/sodium-fabric/wiki/Known-Issues#rtss-incompatible
