### ISSUE TITLE
Light flickers when there is a light source under carpet

### ISSUE THREAD

**Issue by mrjasonn** [jellysquid3/Sodium#2213]
### Bug Description

Light flickers when there is a light source (e.g. glowstone) under carpet
That glowstone must be surrounded by blocks
I don't know but this might affect snow layers as well?

### Reproduction Steps

1. Place glowstone surrounded by blocks
2. Put carpet on top of the glowstone
3. Observe

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13729433/latest.log)

### Crash Report

[crash report because you insisted.txt](https://github.com/CaffeineMC/sodium-fabric/files/13729427/crash.report.because.you.insisted.txt)

**Comment by mrjasonn** [comment]
Ok thanks for pointing that out I checked

**Comment by Lolothepro** [comment]
Can you send a screenshot/video as an example?

**Comment by Timolino456** [comment]
^
I can't reproduce this using only Sodium

**Comment by embeddedt** [comment]
Block light is intentionally programmed to flicker in vanilla, to my knowledge (unlike sky light).

**Comment by mrjasonn** [comment]
> Block light is intentionally programmed to flicker in vanilla, to my knowledge (unlike sky light).

I don't really see that... at least with torches

**Comment by mrjasonn** [comment]
Actually intended to flicker a little the light sources but hard to notice

**Comment by mrjasonn** [comment]
If this actually is not supposed to happen, a person that has permission to reopen this issue should or if they don't they should write a comment here if possible.
