### ISSUE TITLE
Minecraft crashes whenever I try to make a new world

### ISSUE THREAD

**Issue by SithTrooper9** [jellysquid3/Sodium#2216]
### Bug Description

Whenever I try to open a world, the game crashes and I know it has something to do with sodium, but I'm not sure how to fix it. I'm on 1.20.1 fabric btw, and I'm using sodium 0.4.10 so that it is compatible with the create mod and it's addons.

### Reproduction Steps

Simply whenever I try to open a world with my custom modpack, the game gully loads and then crashes.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13763504/latest.log)

### Crash Report

java.lang.NoClassDefFoundError: me/jellysquid/mods/sodium/client/render/chunk/map/ChunkTrackerHolder
	at farsight.compat.SodiumCompat.lambda$init$0(SodiumCompat.java:10)
	at farsight.FarsightClientChunkManager.method_16020(FarsightClientChunkManager.java:97)
	at net.minecraft.class_634.method_38539(class_634.java:773)
	at net.minecraft.class_634.method_11128(class_634.java:738)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1175)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.render.chunk.map.ChunkTrackerHolder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at farsight.compat.SodiumCompat.lambda$init$0(SodiumCompat.java:10)
	at farsight.FarsightClientChunkManager.method_16020(FarsightClientChunkManager.java:97)
	at net.minecraft.class_634.method_38539(class_634.java:773)
	at net.minecraft.class_634.method_11128(class_634.java:738)
	at net.minecraft.class_2672.method_11528(class_2672.java:45)
	at net.minecraft.class_2672.method_11054(class_2672.java:12)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 1 total; [class_746['SithTrooper9'/195, l='ClientLevel', x=6.50, y=99.65, z=-8.50]]
	Chunk stats: 1, 1
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,86,0), Section: (at 0,6,0 in 0,5,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 51 game time, 51 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, Moonlight Mods Dynamic Assets, KubeJS Resource Pack [assets]

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1250773240 bytes (1192 MiB) / 4550819840 bytes (4340 MiB) up to 5402263552 bytes (5152 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700G with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3770
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x1638
	Graphics card #1 versionInfo: DriverVersion=31.0.14052.4001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 38239.30
	Virtual memory used (MB): 29476.48
	Swap memory total (MB): 22528.00
	Swap memory used (MB): 1176.00
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx5152m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 6.0.1
			libgui: LibGui 8.0.1+1.20
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
		additionalstructures: Additional Structures 4.2.1
		adorn: Adorn 5.0.1+1.20.1
		alloy_forgery: Alloy Forgery 2.1.2+1.20
		ambientenvironment: Ambient Environment 11.0.0.1
		ambientsounds: AmbientSounds 5.3.5
		another_furniture: Another Furniture 1.20.1-3.0.1
		appleskin: AppleSkin 2.5.1+mc1.20
		aquamirae: Aquamirae 6
		aqupdgrizzly: Grizzly Bear mob 1.20-1.6.1
		architectury: Architectury 9.1.12
		artifacts: Artifacts 9.2.0
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			expandability: ExpandAbility 9.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		athena: Athena 3.1.1
		attributefix: AttributeFix 21.0.4
		azurelib: AzureLib 2.0.18
		balm-fabric: Balm 7.2.1
		barteringstation: Bartering Station 8.0.0
		bcc: BetterCompatibilityChecker 4.0.8
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		beekeeperhut: Friends&Foes - Beekeeper Hut 1.3.0
		betteradvancements: Better Advancements 0.3.2.161
		betteranimationscollection: Better Animations Collection 8.0.0
		betterarcheology: Better Archeology 1.1.1
		betterchunkloading: Better chunk loading mod 1.20.1-2.6
		bettercombat: Better Combat 1.8.3+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
		betterend: Better End 4.0.11
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.4
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		betterfpsdist: Better FPS distance Mod 1.20.1-4.0
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betternether: Better Nether 9.0.10
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		betterthirdperson: Better Third Person 1.9.0
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		bhmenu: BHMenu-Fabric 2.4.1
		bookshelf: Bookshelf 20.1.8
		bountiful: Bountiful 6.0.3+1.20.1
		brewinandchewin: Brewin And Chewin fabric-2.1.5+1.20.1
			mm: Manningham Mills 2.3
		bygonenether: Bygone Nether 1.3.2
		carryon: Carry On 2.1.2.7
		chat_heads: Chat Heads 0.10.27
		chatsigninghider: Chat Signing Hider 1.20.1-1.0.0
		chimes: Chimes 2.0.1
		chipped: Chipped 3.0.1
		chunksending: Chunksending Mod 1.20.1-2.8
		citresewn: CIT Resewn 1.1.3+1.20
			citresewn-defaults: CIT Resewn: Defaults 1.1.3+1.20
		clickadv: Clickable Advancements Mod 1.20.1-3.7
		clientcrafting: clientcrafting Mod 1.20.1-1.7
		cloth-config: Cloth Config v13 13.0.114
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 12.0.0.3
		clutter: Clutter 1.20-0.5.3
		collective: Collective 7.26
		comforts: Comforts 6.3.4+1.20.1
			spectrelib: SpectreLib 0.13.14+1.20.1
		completeconfig: CompleteConfig 2.5.0
			completeconfig-base: completeconfig-base 2.5.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.5.0
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.5.0
		connectivity: Connectivity Mod 1.20.1-4.9
		continuity: Continuity 3.0.0-beta.4+1.20.1
		controlling: Controlling For Fabric 12.0.2
		crafttweaker: CraftTweaker 14.0.27
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-1
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_common: Porting Lib Common 2.1.1127+1.20
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		createaddition: Create Crafts & Additions 0.9.0
			team_reborn_energy: Energy 2.3.0
		createbigcannons: Create Big Cannons 0.5.3-nightly-7274a6d
			ritchiesprojectilelib: Ritchie's Projectile Library 1.0.0-369e88d+1.20.1-fabric
		createdeco: Create Deco 2.0.0-fabric-1.20.1
		createoreexcavation: Create Ore Excavation 1.4.2
			chunk-storage-api-fabric: Chunk Storage Api Fabric 1.0.3
		creativecore: CreativeCore 2.11.10
			net_minecraftforge_eventbus: eventbus 6.0.3
		creeperoverhaul: Creeper Overhaul 3.0.1
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		ctov: ChoiceTheorem's Overhauled Village 3.3.6
		cull-less-leaves: Cull Less Leaves 1.3.0
		culturaldelights: Cultural Delights Fabric 0.14.11+1.20.1
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.1
		cupboard: cupboard 1.20.1-2.2
		darktimer: DarkTimer - Clear Entity Lag 1.0.6
		darkwaters: Dark Waters 0.0.22
		dawn: Dawn API 5.0.0
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.1
		decorative_blocks: Decorative Blocks 4.0.3
		deeperdarker: Deeper and Darker 1.2.5
			customportalapi: Custom Portal Api 0.0.1-beta64-1.20
		doapi: Lets Do Api 1.2.8
		dragonfight: Dragonfight Mod 1.20.1-4.1
		dungeons_arise: When Dungeons Arise 2.1.57
		dynamic_fps: Dynamic FPS 3.3.1
		ecologics: Ecologics 2.2.0
		elytraslot: Elytra Slot 6.3.0+1.20.1
		enchdesc: EnchantmentDescriptions 17.0.11
		endermanoverhaul: Enderman Overhaul 1.0.3
		entity_model_features: Entity Model Features 1.2
		entity_texture_features: Entity Texture Features 5.0
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		expanded_ecosphere: Expanded Ecosphere 3.2.3
		expandeddelight: Expanded Delight 0.3.0.2
		explorify: Explorify v1.3.0-mc1.20
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		fallingtree: FallingTree 4.3.3
		fancymenu: FancyMenu 2.14.10
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		farmersrespite: Farmer's Respite 2.3.4
		farsight: Farsight Mod 1.20.1-4.2
			org_jctools_jctools-core: jctools-core 4.0.1
		faux-custom-entity-data: Faux-Custom-Entity-Data 6.0.1
		ferritecore: FerriteCore 6.0.1
		forgeconfigapiport: Forge Config API Port 8.0.0
		formations: Formations 1.0.2
		formationsnether: Formations Nether 1.0.2
		framework: Framework 0.6.16
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			org_javassist_javassist: javassist 3.29.2-GA
		friendsandfoes: Friends&Foes 2.0.6
		fusion: Fusion 1.1.0+c
		galosphere: Galosphere 1.20.1-1.3.0
		geckolib: GeckoLib 4 4.3.1
			com_eliotlash_mclib_mclib: mclib 20
		geode_plus: Geode+ 1.2.4
			paragon: Paragon 3.0.2
				com_moandjiezana_toml_toml4j: toml4j 0.7.2
				org_yaml_snakeyaml: snakeyaml 1.27
		getittogetherdrops: Get It Together, Drops! fabric-1.20-1.3.1
		goblintraders: Goblin Traders 1.9.3
		gpumemleakfix: Gpu memory leak fix mod 1.20.1-1.8
		guardvillagers: GuardVillagers 2.0.9-1.20.1
		handcrafted: Handcrafted 3.0.5
		highlighter: Highlighter 1.1.9
		iceberg: Iceberg 1.1.18
		immediatelyfast: ImmediatelyFast 1.2.8+1.20.4
			net_lenni0451_reflect: Reflect 1.3.1
		immersive_aircraft: Immersive Aircraft 0.6.2+1.20.1
		indium: Indium 1.0.21+mc1.20.1
		inventoryhud: Inventory HUD + 3.4.18
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		irisflw: Iris Flywheel Compat 0.2.1
		itemfilters: Item Filters 2001.1.0-build.59
		jade: Jade 11.7.0
		jamlib: JamLib 0.6.1+1.20.x
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 15.2.0.27
		kambrik: Kambrik 6.1.1+1.20.1
		konkrete: Konkrete 1.7.0
		kubejs: KubeJS 2001.6.4-build.114
		lazydfu: LazyDFU 0.1.3
		limitedchunks: Limited Chunkloading Mod 1.20.1-3.8
		lithium: Lithium 0.11.2
		logprot: Logprot Mod 1.20.1-3.3
		lootintegrations: Loot integration Mod 1.20.1-3.4
		lootr: Lootr 0.7.29.75
		mavapi: More Axolotl Variants API 1.1.3
		mavm: More Axolotl Variants Mod 1.2.4
		mcwbridges: Macaw's Bridges 2.1.0
		mcwdoors: Macaw's Doors 1.1.0
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwfurnitures: Macaw's Furniture 3.2.1
		mcwlights: Macaw's Lights and Lamps 1.0.6
		mcwpaintings: Macaw's Paintings 1.0.5
		mcwpaths: Macaw's Paths and Pavings 1.0.3
		mcwtrpdoors: Macaw's Trapdoors 1.1.2
		mcwwindows: Macaw's Windows 2.2.1
		meadow: Meadow 1.3.3
		memorysettings: Memorysettings Mod 1.20.1-5.3
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		modernfix: ModernFix 5.11.1+mc1.20.1
		moonlight: Moonlight 1.20-2.8.71
		moremobvariants: More Mob Variants 1.2.2
		mousetweaks: Mouse Tweaks 2.25
		mvs: Moog's Voyager Structures 4.1.1-1.20-fabric
		mythicmetals: Mythic Metals 0.19.0+1.20-alpha
			additionalentityattributes: Additional Entity Attributes 1.4.0+1.20.0
			common-protection-api: Common Protection API 1.0.0
			mm_shedaniel: Manningham Mills (shedaniel's fork) 2.4.1
		mythicmobs: Mythic Mobs 1.20.1-fabric-1.4.5
		mythicupgrades: Mythic Upgrades 2.3.2+mc1.20.1
		naturalist: Naturalist 4.0.3
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		netherdepthsupgrade: Nether Depths Upgrade fabric-3.1.1-1.20
		netherportalfix: NetherPortalFix 13.0.1
		nethersdelight: Nether's Delight 1.0.0
			disable_custom_worlds_advice: Disable Custom Worlds Advice 4.1
		notenoughanimations: NotEnoughAnimations 1.6.4
		nyfsspiders: Nyf's Spiders 2.1.1
		obscure_api: Obscure API 16
		owo: oωo 0.11.2+1.20
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		player-animator: Player Animator 1.0.2-rc1+1.20
		polymorph: Polymorph 0.49.1+1.20.1
			cardinal-components-block: Cardinal Components API (blocks) 5.2.1
			cardinal-components-item: Cardinal Components API (items) 5.2.1
		presencefootsteps: Presence Footsteps 1.9.0
			kirin: Kirin UI 1.15.0
		puzzleslib: Puzzles Lib 8.1.11
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		railways: Create: Steam 'n' Rails 1.5.1+fabric-mc1.20.1
		recipeessentials: recipeessentials Mod 1.20.1-3.2
		reeses-sodium-options: Reese's Sodium Options 1.6.3+mc1.20.1-build.92
		repurposed_structures: Repurposed Structures 7.1.11+1.20.1-fabric
		resourcefulconfig: Resourcefulconfig 2.1.0
		resourcefullib: Resourceful Lib 2.1.20
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		respitecreators: Respite Creators 1.2.0
		rhino: Rhino 2001.2.2-build.18
		rightclickharvest: Right Click Harvest 3.2.3+1.19.x-1.20.1-fabric
		searchables: Searchables 1.0.2
		seasons: Fabric Seasons 2.3+1.20
		seasonsdelightcompat: Fabric Seasons: Delight Compat 1.0-1.3.9
		seasonsextras: Fabric Seasons: Extras 1.2-BETA+1.20
		shield_overhaul: Shield Overhaul 1.0.3
		simplyswords: Simply Swords 1.51.5-1.20.1
			spruceui: SpruceUI 5.0.0+1.20
		skinlayers: 3d Skin Layers 1.5.4-mc1.20.1
		smallships: Small Ships 2.0.0-a2.3.3
		smartbrainlib: SmartBrainLib 1.13
		smoothchunk: Smooth chunk save Mod 1.20.1-3.5
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.20+mc1.20-build.103
			caffeineconfig: CaffeineConfig 1.1.0+1.17
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.3.1
		spark: spark 1.10.53
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		starlight: Starlight 1.1.2+fabric.dbc156f
		structory: Structory 1.3.4
		structory_towers: Structory: Towers 1.0.6
		structureessentials: Structure Essentials Mod 1.20.1-3.2
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		supplementaries: Supplementaries 1.20-2.7.14
			mixinsquared: MixinSquared 0.1.1
		terrablender: TerraBlender 3.0.0.169
		terralith: Terralith 2.4.11
		toms_storage: Tom's Simple Storage Mod 1.6.5
		trimeffects: Trim Effects 1.1.0-fabric
		trinkets: Trinkets 3.7.1
		twigs: Twigs 3.1.0
		universal_ores: Universal Ores 1.5.2
		veinmining: Vein Mining 1.2.1+1.20.1
		villagernames: Villager Names 7.3
		vinery: Vinery 1.4.7
		visuality: Visuality 0.7.1+1.20
		wi_zoom: WI Zoom 1.5-MC1.20.1
		wwoo: William Wythers' Overhauled Overworld 2.0.0
		xaerominimap: Xaero's Minimap 23.9.3
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
		yungsmenutweaks: YUNG's Menu Tweaks 1.20.1-Fabric-1.0.1
	Loaded Shaderpack: ComplementaryUnbound_r5.1.1.zip
		Profile: HIGH (+0 options changed by user)
	NEC status: No NEC detected
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.15.3-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 537.70, NVIDIA Corporation
	Window size: 1024x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 5700G with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['SithTrooper9'/195, l='ServerLevel[New World]', x=6.50, y=103.00, z=-8.50]]
	Data Packs: vanilla, fabric, resources/ee_default (incompatible), resources/ee_remove_blobs (incompatible), Moonlight Mods Dynamic Assets, Supplementaries Generated Pack
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by Poopooracoocoo** [comment]
This isn't a support forum. Next time please use the Discord server.

You need to downgrade Farsight to 3.9 for it to be compatible with Sodium 0.4.10: https://www.curseforge.com/minecraft/mc-mods/farsight-fabric/files/4661436. And you need to use Iceberg 1.1.13 as it's compatible with Sodium 0.4.10. You also need to downgrade Fabric API to 0.88.1 for it to be compatible with Indium 1.0.21.

You could alternatively use Create Sodium Fix and update everything else.
