### ISSUE TITLE
Add option to disable ingame fog

### ISSUE THREAD

**Issue by outcasino** [jellysquid3/Sodium#2217]
### Request Description

Fog is already annoying in the overworld (atleast for me) and basically makes the nether unplayable in my opinion.

Seriously im at 32 render distance and this is the fog in the nether. Its unplayable.

![2023-12-19_16 49 39](https://github.com/CaffeineMC/sodium-fabric/assets/119544725/4421cb68-157f-452d-81ed-1f1b7b922854)

Optifine already has the option to turn off fog and some sodium add on mods (I think Reeses sodium options) do but I think default sodium should also. The worst thing is is that the vanilla tweaks resource pack to disable fog doesn't work with sodium so you have no choice unless you want to install one of the sodium addons which sometimes aren't updated for a while after a new minecraft release.

**Comment by jellysquid3** [comment]
We are not adding features to change how the fog effect is rendered. The fog effect is a game mechanic, and we are not altering game mechanics. If you must disable it, the existing solutions work fine, and the occasional delay of a few days for an add-on mod to update is really not a big deal.
