### ISSUE TITLE
Incompatibility with Caxton: Outlined text misrendered

### ISSUE THREAD

**Issue by bluebear94** [jellysquid3/Sodium#2218]
### Bug Description

With [Caxton](https://modrinth.com/mod/caxton) 0.5.3+1.20.4 and Sodium mc1.20.3-0.5.5, the interiors of glyphs in outlined text have the wrong colors. (For running in Sodium’s dev env, [33891cf](https://gitlab.com/Kyarei/caxton/-/commit/33891cf5d4ef9587d8ede5d9618aea088b273737) for 1.20.4 or [ffc0228](https://gitlab.com/Kyarei/caxton/-/commit/ffc02284c5064fde4ceb63ec7d6acdb40c30f114) for 1.20.2 is required).

With Caxton and Sodium:

![2023-12-24_16 41 43](https://github.com/CaffeineMC/sodium-fabric/assets/2975203/1fa732f8-6701-4635-99a2-23520890ccd4)

With Caxton alone:

![2023-12-24_17 38 03](https://github.com/CaffeineMC/sodium-fabric/assets/2975203/f673eef9-3e59-4120-888c-2a884b62d780)

I’ve traced this issue to commit fae888e. The optimized `BufferBuilder` implementation introduced by this commit seems to assume that any vertex format has at most one color component. Meanwhile, Caxton uses a custom vertex format with two color components to render outlined text (see [CaxtonVertexFormats](https://gitlab.com/Kyarei/caxton/-/blob/master/common/src/main/java/xyz/flirora/caxton/render/CaxtonVertexFormats.java?ref_type=heads), [CaxtonTextRenderLayers](https://gitlab.com/Kyarei/caxton/-/blob/master/common/src/main/java/xyz/flirora/caxton/render/CaxtonTextRenderLayers.java?ref_type=heads)).

### Reproduction Steps

1. Start Minecraft with Caxton and Sodium installed
2. Enable the bundled “Sample Font: Inter” resource pack
3. Enter a world and place a sign with glowing text

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13764527/latest.log)

### Crash Report

[crash-2023-12-25_01.47.01-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13764532/crash-2023-12-25_01.47.01-client.txt) (manually triggered)

**Comment by jellysquid3** [comment]
I really don't see how it would be possible for us to fix this. And that's a shame, because I actually have used this mod in the past to deal with Minecraft's very illegible font. Having multiple semantic elements of the same kind doesn't make a lot of sense (at least given my understanding of how you are using them), but I will have to think more about it after the holidays, and see if we can do something to not break mods like this.

**Comment by jellysquid3** [comment]
#2240 will likely be enough to fix the problem with Caxton.

**Comment by jellysquid3** [comment]
Resolved with https://github.com/CaffeineMC/sodium-fabric/commit/1cc23f168d9d08e93ed623d9c87143884dd22622.
