### ISSUE TITLE
Forced 60 hz

### ISSUE THREAD

**Issue by Jwicks10** [jellysquid3/Sodium#222]
Hello, I've recently installed the mod and everything is working out fine, however, I've noticed that the game will only run on 60hz when it's in fullscreen, the max fps is 200, and V-sync is off, So I'm really confused on what to do next. I have a 144hz monitor, and I've also noticed if I play on windowed mode it goes to 144hz, As well as this if I play on Optifine I also get 144hz and in all its just ALOT smoother, even though I have lower fps overall than I would of Sodium.

**Comment by KolonelGipa** [comment]
im having the same problem and its so frustrating my pc has a lot more frames than 144 but the hz is capped at 60 what is the point of all that fps when you cant use it on fullscreen mode

**Comment by Jwicks10** [comment]
> 
> 
> im having the same problem and its so frustrating my pc has a lot more frames than 144 but the hz is capped at 60 what is the point of all that fps when you cant use it on fullscreen mode

Yea its really frustrating, cant find anything online either

**Comment by Madis0** [comment]
As a workaround, maybe try one of those mods? 
https://www.curseforge.com/minecraft/mc-mods/borderless-mining 
https://www.curseforge.com/minecraft/mc-mods/deborder

**Comment by toto433** [comment]
Found a fix for me. Run fabric without Sodium installed -> go to video setting ingame -> **change resolution to 1920*1080@144hz** -> save & quit -> re-install sodium and run the game you should have 144 fps.

**Comment by Madis0** [comment]
You can actually access the normal graphics screen by pressing Shift+P. But per your description it seems like a graphics options parity issue, as tracked in #46.

**Comment by jellysquid3** [comment]
Closing as #46 covers the issue here.
