### ISSUE TITLE
Iris is reverting Sodium (0.5.5.) into (0.5.4.)

### ISSUE THREAD

**Issue by JayMcar** [jellysquid3/Sodium#2226]
### Bug Description

Whenever I update the Iris mod in the mods file, Sodium 0.5.5. gets turned into Sodium 0.5.4. in the .minecraft mods folder. If I try to open the game after this happens, I get a crash report telling me that Indium needs Sodium version 0.5.5. to run.

### Reproduction Steps

1. Drop Indium 1.0.28. and Sodium 0.5.5. into the .minecraft mods folder.
2. Get the universal Iris Installer version 3.0.2.
3. Open the Installer, set game version to 1.20.4, and set the Installation Type to Fabric Install.
4. This install should revert the Sodium 0.5.5. file to Sodium 0.5.4.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13789870/latest.log)

### Crash Report

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.4 with version 0.5.4 that is compatible with:
		 - indium, any version
	 - Replace mod 'Indium' (indium) 1.0.28+mc1.20.4 with any version that is compatible with:
		 - sodium, version 0.5.4
More details:
	 - Mod 'Indium' (indium) 1.0.28+mc1.20.4 requires version 0.5.5 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by pajicadvance** [comment]
This isn't a Sodium issue as the Iris installer is maintained, well, by the Iris developers. You may want to report the issue to them.

**Comment by Felix14-v2** [comment]
~~This isn't a bug in Sodium, report to the Iris installer repository~~
https://github.com/IrisShaders/Iris-Installer
