### ISSUE TITLE
Determine a backporting policy for future versions

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#2230]
Right now, Sodium does not support any version of Minecraft other than the very latest one. There are two reasons this has historically been the case:

- We thought Mojang was going to be much more aggressive in refactoring the rendering code, making backports much more painful. Unsurprisingly, this never happened, and the last few major versions have been completely uneventful for Sodium.
- Fabric never had designated "long term support" versions, so there was no guidance for what we should prioritize. With the recent planning work for a NeoForge version of Sodium, we now have a long-term support version to target.

Seeing that both of these points have changed, we should re-examine this policy, and figure out what would be the most important versions of Minecraft to target. This will also likely necessitate bringing additional hands onto our team to deal with the extra work.

**Comment by jellysquid3** [comment]
This also depends on us coming up with a versioning scheme, since we don't want to have "Sodium 0.5.5" on three different versions of the game. Unfortunately, SemVer doesn't really provide us with much option, but we could try tagging it as additional information like `0.5.5+mc1.20.4`...

**Comment by TheNukeLore** [comment]
I could see doing backports as a potentially very tricky area to tackle. Not necessarily on the development end of sodium but rather compatibility with older no longer updated mods. Even simple bug-fix backports could break mods that potentially(and commonly) hard depend on singular sodium versions.

**Comment by jellysquid3** [comment]
People can use older versions of Sodium if mods depending on internals of our code break when an update is pushed. Nobody is required to use the latest version.

**Comment by TheNukeLore** [comment]
wouldn't that majority defeat the purpose of backporting? As people would still get issues likely in large modpacks and not be able to fix them due to not being able to update sodium due to it breaking.

**Comment by jellysquid3** [comment]
This is resolved now, as we now have a designated long-term support branch, and a current branch. As of today, the long-term support version is Minecraft 1.20.1, which seems to be one of the most important versions for the modding community currently. We'll be making an effort to port backwards all changes we're making on current versions, where they're applicable.
