### ISSUE TITLE
Apply normals and base color/light values from BakedQuad data

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#2235]
Sodium currently ignores much of the data in `BakedQuad` because vanilla itself does not use it. However, some Forge mods rely on being able to specify this data from the model data. This includes:

- The normals, which affects how lighting is calculated.
- The base color, which is then mixed into the block tint and lighting color.
- The light values, which is primarily used for emissive lighting (added to the received light from the world.)

**Comment by IMS212** [comment]
Partially resolved in https://github.com/CaffeineMC/sodium-fabric/commit/353771ed1510da706b8b9401936fc21b332b07a8.
