### ISSUE TITLE
Crasher mod

### ISSUE THREAD

**Issue by joaoespanhol** [jellysquid3/Sodium#2239]
### Bug Description

log: https://mclo.gs/EHm6bkD

### Reproduction Steps

1º
open e try find rocket
See recipe
After see recipe compressed steal.
Crasher

### Log File

https://mclo.gs/EHm6bkD

### Crash Report

https://mclo.gs/EHm6bkD

**Comment by jellysquid3** [comment]
You are not using our mods.
