### ISSUE TITLE
Error rendering textures from Tech Reborn

### ISSUE THREAD

**Issue by NxD136** [jellysquid3/Sodium#224]
### Expected Behavior
Show all the proper textures for all assets from Tech Reborn.

### Actual Behavior
Most of the textures are rendered, but not all. The dev said that there was an issue on Sodium's end so here I am!

### Reproduction Steps
1. Open inventory
2. Scroll to or search for Tech Reborn items/blocks

### Attachments
**Screenshot :** ![Snag_394baec](https://user-images.githubusercontent.com/51761243/89121645-892b9200-d48e-11ea-9743-8a4b4193721a.png)
**latest log :** https://pastebin.com/Y70yuxrH

### System Information
- Java Version: [8 Update 251]
- CPU: [AMD Ryzen 5 2600]
- GPU: [NVIDIA GeForce GTX 1080 Ti]

**Comment by Leo40Git** [comment]
Duplicate of #5.
We don't have FRAPI support yet, so mods that depend on it (such as TechReborn) won't work correctly.
[It's on the roadmap for Sodium 0.2](https://github.com/jellysquid3/sodium-fabric/wiki/Roadmap).

**Comment by NxD136** [comment]
That's great, thanks for your swift reply! Is there an ETA for that version to be released? Or even just a ballpark?

**Comment by Leo40Git** [comment]
Not that I'm aware of, sadly.

**Comment by NxD136** [comment]
No problem, thanks for the info!
