### ISSUE TITLE
[1.18.2 sodium-0.4.1 bug] Render only when I aim at the destination 

### ISSUE THREAD

**Issue by 1024-byteeeee** [jellysquid3/Sodium#2245]
### Bug Description

- Render only when I aim at the destination, I tested 1.20.1, and there was no issue (both 1.18.2 and 1.20.1 were tested with only sodium installed).
- Some perspectives won't render no matter what.

---

- Game version: 1.18.2
- sodium: 0.4.1
- fabric loader: 0.14.25

### Reproduction Steps

![1](https://github.com/CaffeineMC/sodium-fabric/assets/77058327/a38e78f5-b74e-482b-8187-158fb0c8bcb4)
![2](https://github.com/CaffeineMC/sodium-fabric/assets/77058327/da5d2846-9f72-4cd4-98b7-93052e205c6e)
![3](https://github.com/CaffeineMC/sodium-fabric/assets/77058327/05667bf5-4970-41d0-9410-e0820f74ca2c)

### Log File

/

### Crash Report

/

**Comment by Timolino456** [comment]
Looks like a case of #872. This is fixed in Sodium 0.5+, but that version is not available for 1.18.2, so there's not really anything you can do if you don't want to update Minecraft.

**Comment by TheUserCreated** [comment]
This might be the culling issues sodium had in older versions. Can you copy the world file and retest with the newest version to confirm if it's still a problem?

**Comment by 1024-byteeeee** [comment]
> 这可能是钠在旧版本中存在的剔除问题。您可以复制坐标文件并使用最新版本重新测试以确认它是否仍然存在问题吗？

The latest version is fine, but I don't want to upgrade to the new game version. T ^ T

**Comment by jellysquid3** [comment]
Like has already been said, this was fixed in newer versions. We don't currently backport fixes to older versions of Minecraft.
