### ISSUE TITLE
Sodium breaks various connected texture mods

### ISSUE THREAD

**Issue by Pale-Vessel** [jellysquid3/Sodium#2246]
### Bug Description

When using Sodium, various connected texture mods fail to connect textures. This occurs when any connected texture mod - in this case, ConnectedGlass, is installed. I believe that this is unintended behaviour.
![2024-01-05_22 50 11](https://github.com/CaffeineMC/sodium-fabric/assets/150151331/b9cfded0-397f-41ea-8306-eee71ec911fb)
![2024-01-05_22 51 12](https://github.com/CaffeineMC/sodium-fabric/assets/150151331/4decc508-ed8f-4290-8d9c-156dbd76d18e)

### Reproduction Steps

1. Install Sodium
2. Install another connected texture mod, like [ConnectedGlass](https://modrinth.com/mod/connected-glass) or [ReChiseled](https://modrinth.com/mod/rechiseled)
3. Load the game and place blocks that are supposed to connect next to each other
4. Observe that they do not connect

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13847377/latest.log)

### Crash Report

[crash-2024-01-05_23.01.08-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13847373/crash-2024-01-05_23.01.08-client.txt)

**Comment by TheNukeLore** [comment]
Do you have indium installed? It’s needed for mods that use frapi when used with sodium(most connected texture mods use frapi)

**Comment by Pale-Vessel** [comment]
Installed Indium and that fixed it, thanks very much
