### ISSUE TITLE
Using certain resource packs with small textures causes white dots between blocks in distant terrain

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2248]
### Bug Description

Sodium causes white dots with certain resource packs with small-resolution textures

![2024-01-06_20 52 36](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/daefa932-fd1a-4203-ba20-cd46d1c3468a)
![2024-01-06_20 52 43](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/3afac661-ec37-475b-9356-8abe84048035)
![2024-01-06_20 52 54](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/0752a78e-e833-4356-b73e-a6608a823c48)

### Reproduction Steps

1. Generate a flat world without structures
2. Install and apply F8thful
3. See the small white dots

### Log File

https://mclo.gs/a4CUtom
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13851092/latest.log)

### Crash Report

[crash-2024-01-06_20.54.18-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13851119/crash-2024-01-06_20.54.18-client.txt)

**Comment by jellysquid3** [comment]
Is this fixed with https://github.com/CaffeineMC/sodium-fabric/commit/ea0172768a5da9907b5a5711160dc3984fafea83?

**Comment by Lolothepro** [comment]
Seems fixed, I'll reopen it if it's not fixed
