### ISSUE TITLE
Hates Quilt 0.23.0.

### ISSUE THREAD

**Issue by MagmaSlime123** [jellysquid3/Sodium#2249]
### Bug Description

Title. The mod crashes on Quilt.

### Reproduction Steps

Load this mod while using Quilt and Quilt API. (Their version of Fabric API.)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13851262/latest.log)

### Crash Report

[crash-2024-01-06_13.04.22-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13851263/crash-2024-01-06_13.04.22-client.txt)

**Comment by douira** [comment]
You also have many other mods installed that might be causing problems. Please try running it with only sodium.

**Comment by MagmaSlime123** [comment]
It seems MoreCulling is the cause. Not sure why Quilt's crash reports don't give any useful info besides mentioning a bunch off Quilt junk/errors.
