### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.render.vertex.VertexBufferWriter

### ISSUE THREAD

**Issue by Jto2332** [jellysquid3/Sodium#2255]
help!I have some problems and I can't solve them.
[游戏崩溃前的输出.txt](https://github.com/CaffeineMC/sodium-fabric/files/13888000/default.txt)

**Comment by pajicadvance** [comment]
Please use the correct issue template and provide full logs, not parts of them.

**Comment by Jto2332** [comment]
> 请使用正确的问题模板并提供完整的日志，而不是其中的一部分。

[错误报告-1-10-周三_20.49.53.zip](https://github.com/CaffeineMC/sodium-fabric/files/13888119/-1-10-._20.49.53.zip)
ok,here!

**Comment by rilakuma123** [comment]
Update Physics Mod

**Comment by rilakuma123** [comment]
What on earth is "Plain Craft Launcher 2"? By the way support requests go in the Discord server, not here.

**Comment by Jto2332** [comment]
> 更新物理模组

I have used the latest version of this mod and it still crashes.

**Comment by Jto2332** [comment]
> “Plain Craft Launcher 2”到底是什么？顺便说一句，支持请求在 Discord 服务器中，而不是在这里。

It's just a Minecraft launcher.Thank you. I will.
