### ISSUE TITLE
MSI afterburner crash

### ISSUE THREAD

**Issue by Kjdhebehe** [jellysquid3/Sodium#2256]
### Bug Description

Minecraft not starting with opened MSI afterburner and rivatuner

### Reproduction Steps

Run MSI afterburner with installed msi rivatuner

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13889397/latest.log)

### Crash Report

[crash-2024-01-10_20.03.07-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13889400/crash-2024-01-10_20.03.07-client.txt)

**Comment by Lolothepro** [comment]
RivaTuner Statistics Server (RTSS) is not compatible with Sodium, see here for more details: https://github.com/CaffeineMC/sodium-fabric/wiki/Known-Issues#rtss-incompatible
