### ISSUE TITLE
Sodium v0.5.5 crashing on Nvidia GPU

### ISSUE THREAD

**Issue by Yixuan2020** [jellysquid3/Sodium#2257]
### Bug Description

the game window appears for 1sek and disappears if the game is launched on an Nvidia GPU, the game runs fine on my laptops AMD iGPU

### Reproduction Steps

Start Minecraft with sodium v0.5.5 on a Nvidia GPU

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13890157/latest.log)

### Crash Report

[crash-2024-01-10_17.03.28-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13890160/crash-2024-01-10_17.03.28-client.txt)

**Comment by Lolothepro** [comment]
RivaTuner Statistics Server (RTSS) is not compatible with Sodium, see here for more details: https://github.com/CaffeineMC/sodium-fabric/wiki/Known-Issues#rtss-incompatible, please uninstall RTSS
