### ISSUE TITLE
Black sides of a block when using 3D textures 

### ISSUE THREAD

**Issue by allethargic** [jellysquid3/Sodium#226]
### Expected Behavior
Blocks show animation normally when using 3D textures from certain Resource Packs such as Sphax BDcraft with More 3D Blocks addon.

### Actual Behavior
Certain blocks (furnaces, for example) instead of working animation become black on all sides.

### Reproduction Steps
1. Install Sodium
2. Install Sphax BDCraft and More 3D Blocks addon
3. Place furnace and fill it with coal and ore.

### System Information

- Java Version: Latest.
- CPU: 8Gb is afforded to Minecraft.

**Comment by MeeniMc** [comment]
Confirmed, same issue here (sodium 0.1.0)

**Comment by amnotbananaama** [comment]
Confirmed, and affects latest commit as well.
![image](https://user-images.githubusercontent.com/6319658/92524535-46c54580-f1f0-11ea-8259-bbef70ae4fa1.png)

**Comment by sarim** [comment]
Not sure if this is same as #295. But here's another example, with Faithful (with Faithful 3D) resource pack, the light providing blocks become dark.

![2020-09-24_23 45 04](https://user-images.githubusercontent.com/1235888/94180778-5a470080-fec0-11ea-8996-2c115dba78d3.png)
![2020-09-24_23 45 27](https://user-images.githubusercontent.com/1235888/94180787-5e731e00-fec0-11ea-87c1-9c5189e4a316.png)

**Comment by MeeniMc** [comment]
pr #489 does NOT fix this issue. Too bad.

**Comment by YumatanGames** [comment]
Can confirm it happens with every 3D resource Pack I've tried. With every light emitting blocks.

**Comment by Motschen** [comment]
This does also occur for users of my Visual Overhaul mod.
I think it's a pretty significant issue.

**Comment by litoj** [comment]
It is also not choosing just the sides that are deeper in the block, I had a pumpkin and its full outer side was dark too:
With Sodium:
![image](https://user-images.githubusercontent.com/54900518/153142990-2afbd8a2-2545-4e70-b512-8d835944e6a1.png)
Without Sodium:
![image](https://user-images.githubusercontent.com/54900518/153142870-d548282f-8907-493f-a0d9-5e67e81e353e.png)
Source: [carved pumpkin model](https://github.com/JosefLitos/Enhanced-Faithcraft/blob/master/assets/minecraft/models/block/carved_pumpkin.json)

**Comment by XSentinelu** [comment]
Every light emitting blocks
Just sodium:
![2022-04-01_17 58 15](https://user-images.githubusercontent.com/102240838/161292654-2ba6c184-4b05-48be-a4a0-d31d3d070455.png)
Sodium with iris shaders:
![2022-04-01_17 50 05](https://user-images.githubusercontent.com/102240838/161292706-c328c826-dde2-4b12-a674-b42c8bfdc26e.png)

**Comment by Jarombean** [comment]
![2022-04-12_17 28 01](https://user-images.githubusercontent.com/93880274/163076262-0ca3675d-fbc1-4125-adfc-06b9cb4ee49f.png)
Happens to me too, Lithos+3D Addon

**Comment by litoj** [comment]
@allethargic could you change the title of the issue to 'light emitting blocks', please?

**Comment by the-pink-hacker** [comment]
My resourcepack is still having issues related to this.
![2022-07-23_04 22 56](https://user-images.githubusercontent.com/67124977/180597208-50cf4e80-9494-49f5-9203-e3f75e4b3b96.png)
![2022-07-23_04 23 04](https://user-images.githubusercontent.com/67124977/180597209-0677e9b5-f5cb-4567-9de9-cdb43ffbfb15.png)
![2022-07-23_04 25 01](https://user-images.githubusercontent.com/67124977/180597210-3e30b3a4-600b-4fb8-aa00-c1d51b9b133c.png)

**Comment by PepperCode1** [comment]
Did you test with #1384?

**Comment by TheButterbrotMan** [comment]
> Did you test with #1384?

Is there any chance that this bugfix maybe also could come to 1.18.2?

**Comment by the-pink-hacker** [comment]
> Did you test with #1384?

It did fix the issue. I don't see any other problems.
