### ISSUE TITLE
Weird sticky piston crash

### ISSUE THREAD

**Issue by Cod1ngGamer** [jellysquid3/Sodium#2261]
### Bug Description

Basically, if I power a sticky piston, the game instantly crashes. That's it. No freezing, no errors, no lag, it just instantly closes the world. Removing/disabling Sodium fixes the issue.
This reminds me of one crash that happened in very outdated versions of the game where you could get a 6-sided piston, then when it was powered, it acted like an update suppressor and instantly closed the world, so my crash might be a result of some weird code that turned the sticky piston into an update suppressor. This is just a guess, though.

Note: I'm using Modrinth as my launcher.
Modlist:
[Mod list.txt](https://github.com/CaffeineMC/sodium-fabric/files/13941906/Mod.list.txt)

### Reproduction Steps

To reproduce, all you need to do is this:
1. Make sure you have all the same mods I have installed.
2. Place a sticky piston.
3. Power it.
Boom, instant crash.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13941696/latest.log)

### Crash Report

[crash-2023-10-16_12.35.40-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13941682/crash-2023-10-16_12.35.40-client.txt)

This was the most recent crash report I could find.

**Comment by douira** [comment]
Have you tried testing this without all the other mods, or without sodium?

**Comment by Cod1ngGamer** [comment]
It works without Sodium, so I know that's where the issue is. I also forgot to mention, this is on 1.19.2

**Comment by pajicadvance** [comment]
Try installing [Indium](https://modrinth.com/mod/indium).

**Comment by Cod1ngGamer** [comment]
It worked! Thanks @pajicadvance
