### ISSUE TITLE
Game flickering black while using sodium while using VSync (165 hz)

### ISSUE THREAD

**Issue by AuroraRpg** [jellysquid3/Sodium#2262]
### Bug Description

The game screen will flicker black.

*photosensitivity warning. it does flicker*
https://github.com/CaffeineMC/sodium-fabric/assets/23438816/2eb01b55-340d-4544-9f2f-8fd9f19a0fa9

### Reproduction Steps

How to replicate this issue:

Use a RTX 4070
use multimc or prism
Use Sodium
set your framerate to something above your monitors refresh rate
Enable VSync

and boom, just like that, you're game is now flickering! better stay away from photosensitive

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13944078/latest.log)

### Crash Report

[crash-2024-01-15_19.39.35-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13944079/crash-2024-01-15_19.39.35-client.txt)

**Comment by AuroraRpg** [comment]
now my quick fix is just not using vsync. maybe i should go all out and reset my pc as i didnt reset or format my pc when i got this new gpu. i just used amd ddu

**Comment by pajicadvance** [comment]
This doesn't seem to be related to Sodium since I can get vanilla to flicker, too. It's not really possible for Sodium to cause something like this by itself, anyways. The flicker can most likely be attributed to GPU drivers and the way they present OpenGL windows.

**Comment by jellysquid3** [comment]
If anyone figures out why it's happening though, feel free to [let us know](https://caffeinemc.net/discord). We have seen people report it on both AMD and NVIDIA GPUs, so it's something shared between drivers, or a bug in Windows itself.
