### ISSUE TITLE
Resourcepack wauses compatibility warn but loads anyways

### ISSUE THREAD

**Issue by SaamariYT** [jellysquid3/Sodium#2264]
### Bug Description

sodium-fabric-mc1.20.3-0.5.5
1.20.4 
loading a resourcepack shows sodiums incompatible message yet it still loads, error in log being
[23:01:50] [Render thread/ERROR]: Resource pack 'file/VanillaTweaks 1.20.4.zip' replaces core shader 'rendertype_solid.fsh'

### Reproduction Steps

Load world
Have sodium active and up to date
load correct version (1.20.4) resourcepack

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13969171/latest.log)

### Crash Report

[crash-2024-01-17_23.09.02-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13969259/crash-2024-01-17_23.09.02-client.txt)

**Comment by jellysquid3** [comment]
This is not a bug. The resource pack is not working correctly and the warning is correct. You just don't realize that the resource pack is broken.

**Comment by SaamariYT** [comment]
broken in what way ?
vanilla tweaks never had issues with sodium and i made sure to download latest version 
it doesn't even show red in the menu
edit : it also loads perfectly fine

**Comment by jellysquid3** [comment]
VanillaTweaks is using core shaders which are not supported by Sodium, hence why you get the warning... see https://github.com/CaffeineMC/sodium-fabric/issues/1569.

Probably you have selected some tweak that is causing the problem. The list of tweaks under "Terrain" are most likely to be the issue.
