### ISSUE TITLE
Section sorting is incorrect

### ISSUE THREAD

**Issue by MeeniMc** [jellysquid3/Sodium#2266]
### Bug Description

In some rare cases, the section sorting is (still) incorrect and will cause a particular section of stained glass to not render.

![image](https://github.com/CaffeineMC/sodium-fabric/assets/68366846/caefcb98-2c00-4f00-a801-c33a1b356bee)
Bottom right section of the stained-glass wall is missing. See how the missing section boundary does not align with the stained glass block pattern. Screenshot taken with #2016, but can be replicated on commit 17a17ede

The missing section is position/angle dependent. It is not time or reload dependent (f3-a or full reload will determistically show the same missing section at the same place)

The bug is not due to #38, as it does not get fixed by Douira's translucency sorting (#2016)
The bug did not get fixed at the same time as #2234 17a17ede

### Reproduction Steps

1. gradlew runclient
2. create a new world with seed 4957284180073197783 
4. /execute in minecraft:overworld run tp @s -24.50 77.00 -53.50 117.00 2.40
3. /fill -64 63 -44 -64 100 -140 minecraft:white_stained_glass

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/13978385/latest.log)

### Crash Report

[crash-2024-01-18_10.17.13-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/13978399/crash-2024-01-18_10.17.13-client.txt)

**Comment by douira** [comment]
Screenshot at 17a17ed
![Screenshot 2024-01-18 at 15 58 10](https://github.com/CaffeineMC/sodium-fabric/assets/17120022/e5d79b29-33a5-4aa0-b0e9-2e812edb20f6)

Rotating or moving the camera makes the problem disappear quickly but not immediately.

**Comment by douira** [comment]
The boundary where the glass is correctly layered appears to be Z=-128 given the dimensions of the glass block and the fact that there's 12 broken blocks. The lower boundary is Y=64 which also points to this being a region-related issue.

**Comment by douira** [comment]
Same world but I found a case where the number of rendered sections does not change:

`/execute in minecraft:overworld run tp @s -31.94 77.00 -54.59 106.80 31.95`
![Screenshot 2024-01-19 at 03 27 13](https://github.com/CaffeineMC/sodium-fabric/assets/17120022/04273bcb-d927-45fe-8fb5-e5fc7dfda3f6)

`/execute in minecraft:overworld run tp @s -31.94 77.00 -54.59 106.95 31.80`

![Screenshot 2024-01-19 at 03 28 16](https://github.com/CaffeineMC/sodium-fabric/assets/17120022/a72df726-9c7c-43d2-82d0-269c93628431)

RD 15, FOV 70 (default). The render resolution (or at least the aspect ratio) 3768x2214 is relevant as it changes the shape of the frustum.

**Comment by jellysquid3** [comment]
As was discussed in the Discord server, nobody seems to know what's going wrong here. The problem even exists in Sodium 0.4, which uses a completely different implementation of the graph traversal code.

Likely there's something fundamentally wrong about how region sorting is handled, and this will require some significant work to properly fix.

**Comment by douira** [comment]
the new [linked PR](https://github.com/CaffeineMC/sodium-fabric/issues/2266) should fix this. Let me know if it works.

**Comment by MeeniMc** [comment]
confirm PR fixes the issue
