### ISSUE TITLE
Dynamic Handlighning

### ISSUE THREAD

**Issue by ZyberTrack** [jellysquid3/Sodium#2269]
### Request Description

Hello Dev Team,

I am already using sodium and fabric instead of optifine for quite some time. It is a really cool alternative. The only thing I am missing is the dynamic hand lightning from optifine when holding a torch (or any other light emitting item) in the right hand or left.  Could you add this please? This would be such a great feature. Also it would be great to have a zoom feature for example with C just as with optifine. However the dynamic handlight is most important for me and I think for other´s too. It is just more realistic to have light when holding light in the hand xD.

**Comment by douira** [comment]
These features are out of scope for sodium. You can find alternatives [here](https://optifine.alternatives.lambdaurora.dev/). Dynamic hand lighting can be added with [this mod](https://modrinth.com/mod/lambdynamiclights) and zooming with [this mod](https://modrinth.com/mod/logical-zoom). You can find more alternatives on modrinth by using the search function.

**Comment by astridellensdottir** [comment]
Sodium replaces and optimizes the rendering engine; it doesn’t aim to be a complete replacement for Optifine.

Dynamic lighting and zoom keys are out of scope for Sodium.

**Comment by ZyberTrack** [comment]
Alright thank you for your heads up. I will add those mods to my list!
