### ISSUE TITLE
Phantom Membrane Glitch

### ISSUE THREAD

**Issue by Blueil** [jellysquid3/Sodium#227]
When I change the phantom membrane model with resource pack when I used sodium, the texture is missing. I tried it with optifine and it's works fine. IDK Why the Phantom Membrane is glithing when I change the model, I changed the model also to the cooked porckchop but it's not glitched, check what happened with the phantom membrane.

**Comment by Kroppeb** [comment]
Could you post the resource pack in question?
And are you trying to change the model or just the texture?

**Comment by Blueil** [comment]
When I changed only the textures it not glitching.

**Comment by Kroppeb** [comment]
Minecraft doesn't allow you to change the model of entities. This is a feature optifine adds.

**Comment by Blueil** [comment]
I mean the phantom membrane item, not the mob.

**Comment by Kroppeb** [comment]
Oh, my bad

Could you provide your resource pack though?

**Comment by Blueil** [comment]
[phantom_membrane.txt](https://github.com/jellysquid3/sodium-fabric/files/5015560/phantom_membrane.txt)
This is the model, I making a datapack and I want to make it very easy to change texture so I just redirect the texture path to my namespcae id.
I know this file should be in json format but I can't provide json files here

**Comment by Blueil** [comment]
The glitch is that the texture looks like this
![2a4950f8be96530](https://user-images.githubusercontent.com/49593489/89176851-f7597d00-d592-11ea-886c-65dc2d1b5cef.png)
flat with that texture

**Comment by jellysquid3** [comment]
Does this issue occur in vanilla?

**Comment by Blueil** [comment]
No, this error does not appear in Vanila. I thought it was caused because the texture the model was aiming for was high resolution, so I reduced the resolution to 16x16 and it did not help.
Check the phantom membrane item class in the code, maybe you will found typo.

**Comment by Blueil** [comment]
And Optifine gives more fps on computers with a bad video card for example my video card.

**Comment by LucilleTea** [comment]
Could you provide a resource pack that reproduces the error with sodium?

**Comment by Blueil** [comment]
I changed the pack for works with sodium, but I will try to recreate the error

**Comment by amnotbananaama** [comment]
I cannot reproduce this error. With or without Sodium, I am able to load textures for the Phantom Membrane just fine. If you are able, please provide the texture file that caused this issue for you. I suspect there was an error somewhere, possibly with the datapack namespace or the image texture.

**Comment by amnotbananaama** [comment]
Closing after a significant period of inactivity. This is caused by something else besides Sodium, although given the limited information we've been provided it's not clear what.
