### ISSUE TITLE
texturepack wont load in sodium 5.2 1.20.1

### ISSUE THREAD

**Issue by JamingDE** [jellysquid3/Sodium#2270]
### Bug Description

When I try to load a texture pack, I receive an error message in the top right corner stating that resources could not be loaded. This only happens with texture packs that are over 2800KB in size.

### Reproduction Steps

I used the 'the-expansion-v1.6-RESOURCEPACK' (the same issue occurred with: Classic 3D, basic 3D, default HD, and a custom pack) in Minecraft version 1.20.1 with Sodium 5.2 (newer versions do not load for some reason, I will submit another bug report for that). I tried another texture pack from Vanilla Tweaks, and it loaded successfully. The pack is only 2800 KB in size, and everything else I tested that is larger does not load.
[video.zip](https://github.com/CaffeineMC/sodium-fabric/files/14002838/video.zip)
[§6§lClassic 3D v15.2 - 1.19.zip](https://github.com/CaffeineMC/sodium-fabric/files/14002841/6.lClassic.3D.v15.2.-.1.19.zip)
[the-expansion-v1.6-RESOURCEPACK.zip](https://github.com/CaffeineMC/sodium-fabric/files/14002844/the-expansion-v1.6-RESOURCEPACK.zip)
[WTF1.20.zip](https://github.com/CaffeineMC/sodium-fabric/files/14002845/WTF1.20.zip)
!!!THE TEXTUREPACKS ARE NOT MINE!!!

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14002786/latest.log)

### Crash Report

[crash-2024-01-21_22.04.00-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14002810/crash-2024-01-21_22.04.00-client.txt)

**Comment by jellysquid3** [comment]
`Caused by: net.minecraft.class_1054: Unable to fit: physicsmod:gui/parallax/general/layer_0 - size: 1920x1080 - Maybe try a lower resolution resourcepack?`

The problem is that Physics Mod (or some resource pack overriding its resources) is apparently insane. Remove it.

**Comment by jellysquid3** [comment]
Some other people have mentioned that the problem could be that another mod is including `gui/*` in the sprite atlas, since Minecraft apparently doesn't care about namespace.

You will likely need to remove your mods one by one until you find the culprit.

**Comment by JamingDE** [comment]
thanks!
it works great now. i dont use the physiks mod anymore, and i can load any
texturepack i want!
i love sodium btw :)

Am So., 21. Jan. 2024 um 23:16 Uhr schrieb JellySquid <
***@***.***>:
