### ISSUE TITLE
Crushing on versions 0.5.4 - 0.5.5 on 1.20.2 release + Fabric

### ISSUE THREAD

**Issue by gozoniy** [jellysquid3/Sodium#2274]
### Bug Description

Tested on 1.20.2 with 0.5.3 woks fine, but with 0.5.4 or 0.5.5 (without any mods) have crash before load. Also tested on 1.20.4 release, 0.5.4 and 0.5.5 crashes. 
RivaTuner is closed, installed latest nvidia drivers.

### Reproduction Steps

Starting client like usual

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14064488/latest.log)

### Crash Report

[crash-2024-01-26_18.28.47-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14064490/crash-2024-01-26_18.28.47-client.txt)

**Comment by Poopooracoocoo** [comment]
Crash report says 
> java.lang.RuntimeException: RivaTuner Statistics Server (RTSS) is not compatible with Sodium, see here for more details: https://github.com/CaffeineMC/sodium-fabric/wiki/Known-Issues#rtss-incompatible

Sodium 0.5.6 (an upcoming version which may be for 1.20.4 and 1.20.1) won't crash with RTSS 7.3.4 or newer

**Comment by gozoniy** [comment]
The reason is simple, its turned out that msi afterburner also connetcted with RTSS. I had to turn off msi afterburner as well.
