### ISSUE TITLE
Crash after finding worarounds for Nvidia Graphics Driver - problematic frame libglfw.so+0x2257b

### ISSUE THREAD

**Issue by TheTrebuchet** [jellysquid3/Sodium#2276]
### Bug Description

I truly do not understand how sodium works, it said in the log file to upload the .log here if a crash happens. It is happening consistently no matter if I install the modpack via atlauncher deb, flatpak or modrinth appimage. Is sodium completely incompatible with nvidia cards on linux? I am able to launch it on windows on the same machine.

### Reproduction Steps

1. Install atlauncher deb package on debian 12 (or flatpak version, same goes for modrinth appimage)
2. Install the latest prominence II [rpg] modpack
3. Run the modpack
4. Observe the crash

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14072065/latest.log)

### Crash Report

[edit: file removed by moderator]

**Comment by jellysquid3** [comment]
I have deleted the crash log from your issue because it contains the access token for your account. You should change your Mojang account password so that other people cannot use it to log in to your account.

**Comment by jellysquid3** [comment]
As to address the actual issue, the warning message is confusing and it's not the cause of the crash. It will be adjusted in the next release to no longer mislead users.

Have you verified that the game starts correctly _without_ Sodium installed? If you're certain it only happens with Sodium, then try modifying the config file manually (`.minecraft/config/sodium-options.json`), and change the following config option like so:

```json
"performance": {
  "use_no_error_g_l_context": false
}
```

**Comment by TheTrebuchet** [comment]
Thanks for deleting the crash report, I was just trying to follow the instructions. 

I have removed sodium, which led me to removing a couple of other sodium related mods to even get the minecraft running, but that ended up with java.lang.RuntimeException, adding just sodium results in yet another java.lang.RuntimeException.

I have reenabled all the mods, changed the option you specified and I got the same "fatal error in Java Runtime Environment" with the same "problematic frame" whatever it is. Though I guess if this is a bad place for this issue then its best to just forget about it.

**Comment by jellysquid3** [comment]
Unfortunately, I'm not sure what to suggest. It's well known that the NVIDIA Graphics Driver is very problematic under Linux, and that Minecraft has problems with Wayland compositors.

Given the problem happens _regardless_ of Sodium being installed, it's not a bug with our software, so this issue isn't actionable on our part. You could ask on our [community Discord server](https://caffeinemc.net/discord) for help, but I didn't find any threads which were similar to your issue at first glance. Maybe someone else knows what is going wrong.
