### ISSUE TITLE
Make a hotfix for Sodium 0.5.6 to fix important issue

### ISSUE THREAD

**Issue by mrjasonn** [jellysquid3/Sodium#2282]
### Request Description

Please make a hotfix for Sodium 0.5.6 to address an important issue fixed in commit 54f9f250c9ccecbcd7650e5d6f4f2c7aa6f0d95e

**Comment by TheUserCreated** [comment]
From the development channel on discord 


> I'm going to release Sodium 0.5.7 tomorrow to fix a bug or two

**Comment by jellysquid3** [comment]
The commit was already picked for both branches. It will be done tomorrow, as someone already quoted. Don't see the point in releasing an update past midnight when other regressions may be found by tomorrow morning.
