### ISSUE TITLE
Game crashes upon enabling the High Contrast resource pack

### ISSUE THREAD

**Issue by ComradeBlue1337** [jellysquid3/Sodium#2286]
### Bug Description

I just updated to the latest version of Sodium (0.5.7) and the latest version of Fabric API and now after starting up my game I was greeted with a resource pack loading error and my game simply had a dirt background screen with "Loading Minecraft" stuck on it. Upon closing and starting the game back up, the High Contrast resource pack turned itself off and the moment I turned it back on I got a crash.

### Reproduction Steps

- Start the game while using Sodium 0.5.7 and the latest version of Fabric API
- Have High Contast enabled
- The game should fail to load the resource packs as stated in the description
- Restart the game and it should then load normally
- Head to the High Contrast option in the accesibility menu or enable it through the resource pack
- The game should immediately crash upon doing the above

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14079827/latest.log)

### Crash Report

[crash-2024-01-29_02.00.13-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14079830/crash-2024-01-29_02.00.13-client.txt)

**Comment by jellysquid3** [comment]
You're using a beta version (0.95.3) of Fabric API, which Sodium doesn't seem to be able to deal with. You can workaround it by downgrading to the [current stable version](https://modrinth.com/mod/fabric-api/version/0.95.1+1.20.4) (0.95.1).

**Comment by ComradeBlue1337** [comment]
> You're using a beta version (0.95.3) of Fabric API, which Sodium doesn't seem to be able to deal with. You can workaround it by downgrading to the [current stable version](https://modrinth.com/mod/fabric-api/version/0.95.1+1.20.4) (0.95.1).

I had also noticed I made this mistake earlier aswell. I used Prism Launcher's auto-update feature so I didn't pay attention to see if it was a beta version of Fabric API. Upon downgrading my problem was immediately fixed. Sorry if I caused some confusion.

**Comment by CRD716** [comment]
The reliance on the old fabric api version makes sodium not fully compatible with 1.20.4 :(

**Comment by Felix14-v2** [comment]
> The reliance on the old fabric api version makes sodium not fully compatible with 1.20.4 :(

0.95.1 is the newest stable version of Fabric API. And Sodium doesn't require Fabric API at all, it is a standalone mod. You can use it without Fabric API.
