### ISSUE TITLE
Text in Chat and Inventory is too high

### ISSUE THREAD

**Issue by TheAllCraft** [jellysquid3/Sodium#2290]
### Bug Description

I recently startet using Sodium and I encountered an Issue where the Text ingame is placed too high. (In the Config, F3 menu and Inventory)
![2024-01-29_19 12 28](https://github.com/CaffeineMC/sodium-fabric/assets/158087048/ec1a0ea5-d058-4255-bdce-dbb3642e34f8)

### Reproduction Steps

I don't know how this issue happened. I closed and reopened Minecraft and it just happened. I didn't change anything.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14088072/latest.log)

### Crash Report

[crash-2024-01-29_19.15.47-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14088085/crash-2024-01-29_19.15.47-client.txt)

**Comment by Octol1ttle** [comment]
It appears that you're using an unofficial version of Sodium (most likely provided by LabyMod). We cannot provide support for these versions.

**Comment by TheAllCraft** [comment]
Thank you for the quick answer.
I am using the version of Sodium provided on the Modrinth site. I loaded it with the normal Minecraft Launcher now and it works.
