### ISSUE TITLE
Separate option for donation button in video settings

### ISSUE THREAD

**Issue by Madis0** [jellysquid3/Sodium#2293]
### Request Description

As of Sodium 0.5.6/0.5.7, there is no way for modpacks to disable the popup permanently, without disabling the button alongside it. Consider adding a separate option for the latter, or unbundling it from https://github.com/CaffeineMC/sodium-fabric/blob/ac8137f52acff64d8897c23a1420cb4245bd9031/src/main/java/me/jellysquid/mods/sodium/client/gui/SodiumOptionsGUI.java#L167

**Comment by embeddedt** [comment]
Why is it necessary to disable the popup? It is actually less invasive than the button, as it only appears once and then never again regardless of what action the user takes.

**Comment by jellysquid3** [comment]
Not a bug. The option is there for users who never want to hear from us, not mod pack authors who want to systemically choke our ability to earn anything from the mod.
