### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Nitrolol** [jellysquid3/Sodium#2299]
### Bug Description

I was opening minecraft then it crashed

### Reproduction Steps

well I had try to add some mods, it crashed then I reduced the number of mods down to 2 mods: Embeddium and Oculus, still crashes, the mods were:  entity_texture_feature & entity_model feature both forge for patrix, after they crashed and removed them or could be Embeddium++ & texture_embeddium_options

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14108583/latest.log)

### Crash Report

[crash-2024-01-30_23.27.40-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14108587/crash-2024-01-30_23.27.40-client.txt)

**Comment by TheUserCreated** [comment]
This is the issue tracker for sodium, the fabric mod. If you're looking for help with a forge port you should ask on the repo/ issue tracker for that forge port.

**Comment by SiverDX** [comment]
check your logs maybe before posting them

> java.lang.RuntimeException: RivaTuner Statistics Server (RTSS) is not compatible with Sodium, see here for more details: https://github.com/CaffeineMC/sodium-fabric/wiki/Known-Issues#rtss-incompatible
