### ISSUE TITLE
Compact Vertex Format causes clipping issues with waterlogged blocks 

### ISSUE THREAD

**Issue by StealWonders** [jellysquid3/Sodium#23]
### Expected Behavior
Normally water doesn't clip through water-logged blocks like stairs.
See this screenshot (vanilla):

![javaw_sK2hYAxWhU](https://user-images.githubusercontent.com/6114858/84602356-0c653a00-ae87-11ea-8e93-a4acbac3b5ae.png)

### Actual Behavior
Sodium-fabric causes these water-logged oak stairs to have water clip through them.
Screenshot:

![javaw_Ehk26mlvjf](https://user-images.githubusercontent.com/6114858/84602347-fce5f100-ae86-11ea-813d-953971b8334c.png)

### Reproduction Steps
Build what was done in the screenshots.

### System Information
- Java Version: 1.8.0_51 64bit
- CPU: Intel(R) Core(TM) i7-4790K
- GPU: GeForce GTX 1080

Enabled in the mod:
- Chunk Renderer: OpenGL 4.6

**Comment by jellysquid3** [comment]
Does this issue disappear if you use the OpenGL 3.0 renderer or disable the Compact Vertex Format option in `Video Settings > Performance`?

**Comment by StealWonders** [comment]
Turning "Use Compact Vertex Format" off fixes this issue. Tried and tested for OpenGL 3.0 & 4.6

**Comment by jellysquid3** [comment]
@StealWonders Does this issue still occur after the recent changes to Sodium? I'm not able to reproduce this problem, but there have been other user reports.

**Comment by StealWonders** [comment]
This issue is fixed with the latest build. Closing issue :-)
