### ISSUE TITLE
Please Make Forge version

### ISSUE THREAD

**Issue by lowkeyrenato** [jellysquid3/Sodium#2301]
### Request Description

I just want this mod on **Forge 1.20.1** if thats possible

**Comment by TheNukeLore** [comment]
A neoforge version is planned for the far future, https://github.com/CaffeineMC/sodium-fabric/milestone/10

**Comment by WolfBV** [comment]
@vernekotthonxdddd Probably use https://www.curseforge.com/minecraft/mc-mods/embeddium for now.

**Comment by lowkeyrenato** [comment]
> @vernekotthonxdddd Probably use https://www.curseforge.com/minecraft/mc-mods/embeddium for now.

Thank you
