### ISSUE TITLE
Armor texture packs render incorrectly

### ISSUE THREAD

**Issue by CrafterDaemon** [jellysquid3/Sodium#2302]
### Bug Description

While using Sodium and the Energy Manipulation datapack, I found that the armor renders very poorly for anyone who is using sodium. The bug is purely client-side, as if it (the datapack) is on a server, all players not using sodium render the armor correctly.
![prplr](https://github.com/CaffeineMC/sodium-fabric/assets/67595672/5f22d1ff-fa8a-47ee-bd86-98281a32ee76)
![hblehc](https://github.com/CaffeineMC/sodium-fabric/assets/67595672/b1ec73a0-a9e3-462d-b767-3e4190dcded3)

### Reproduction Steps

Download and Install Sodium
Download and Install a resource pack that modifies armor (attached is the datapack where I encountered the error)
[energy-manipulation 0.26.0 - minecraft 1.20.2 to 1.20.4.zip](https://github.com/CaffeineMC/sodium-fabric/files/14119969/energy-manipulation.0.26.0.-.minecraft.1.20.2.to.1.20.4.zip)
[xylo-s-resource-pack 0.16.0.zip](https://github.com/CaffeineMC/sodium-fabric/files/14119970/xylo-s-resource-pack.0.16.0.zip)
acquire the retextured armor (Caster armor in the datapack)
Equip and use F5, or put the armor on an armor stand.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14119983/latest.log)

### Crash Report

[crash-2024-01-31_22.32.22-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14119989/crash-2024-01-31_22.32.22-client.txt)

**Comment by CrafterDaemon** [comment]
Seems to be an Iris issue, but pops up sodium incompatibility in top corner

**Comment by CrafterDaemon** [comment]
reopening just in case

**Comment by CrafterDaemon** [comment]
Tested with another texture pack that changes chestplates to have gloves, no issues.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/67595672/f5a7fd77-0fea-4c7e-a1bd-b567fca18b4b)

**Comment by CrafterDaemon** [comment]
only happens with shaders enabled
Shader effects do not matter afaik

**Comment by MeeniMc** [comment]
you have a lot of moving parts here, you need to simplify the problem. ETF, 3D-skin layer, Iris, etc may be the root cause. 

 Try again with only Sodium, and only the resource pack of interest. If that works, do dichotomic search to find which mod breaks it.

**Comment by coderbot16** [comment]
Not a Sodium bug, it's triggered by Iris but it's not fixable. https://github.com/IrisShaders/Iris/issues/1042

See the official Iris documentation: https://github.com/IrisShaders/Iris/blob/1.18.2/docs/development/compatibility/core-shaders.md

Core shaders are not supported by Mojang and servers modify them at their own risk. Iris and Sodium each break different parts of them because they simply can't coexist well with advanced rendering mods.
