### ISSUE TITLE
Enchanted armor and enchanted item glint is red randomly

### ISSUE THREAD

**Issue by MODKILLER1001** [jellysquid3/Sodium#231]
### Expected Behavior
The default glint should stay default.

### Actual Behavior
The default glint will randomly turn red. I notice it more often after I go through portals.

### Reproduction Steps

Unknown how to reproduce, but this is my mod list, I used all these mods before (except sodium, phosphor, and lithium) and did not have this issue.

https://www.curseforge.com/minecraft/mc-mods/hwyla
https://www.curseforge.com/minecraft/mc-mods/i-am-very-smart
https://www.curseforge.com/minecraft/mc-mods/light-overlay
https://www.curseforge.com/minecraft/mc-mods/litematica
https://www.curseforge.com/minecraft/mc-mods/lithium
https://www.curseforge.com/minecraft/mc-mods/minihud
https://www.curseforge.com/minecraft/mc-mods/modmenu
https://www.curseforge.com/minecraft/mc-mods/phosphor
https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items
https://www.curseforge.com/minecraft/mc-mods/sodium
https://www.curseforge.com/minecraft/mc-mods/voxelmap
https://www.curseforge.com/minecraft/mc-mods/wi-zoom

### Attachments
https://i.imgur.com/rQpWplh.png
https://imgur.com/4QP0qXN

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: 1.8.0_231
- CPU: i5 6600k
- GPU: GTX 970

**Comment by CalXee** [comment]
For me it's green.

**Comment by squishycat92** [comment]
Can confirm, it's also an extremely faint green for me.
![image](https://user-images.githubusercontent.com/62223616/113642722-5b0ddb80-9635-11eb-94d8-faeb13cc448f.png)

Additionally, it seems to happen if the player is not holding an enchanted item. I've seen no correlation between the off-hand and the enchant glints for this bug, but if an unenchanted item is held in the main hand, the enchant glints on armor seem to come back.
![image](https://user-images.githubusercontent.com/62223616/113642807-8abce380-9635-11eb-99de-803705e76762.png)

Seems like increasing the brightness to 1200% using Boosted Brightness sometimes fixes this for some reason, although the enchant glint is still a bit faint and may still remain green.
