### ISSUE TITLE
incompatibility With some mods after update

### ISSUE THREAD

**Issue by Eyorie** [jellysquid3/Sodium#2312]
### Bug Description

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Nvidium' (nvidium) 0.2.5-beta with any version that is compatible with:
		 - sodium, version 0.5.8
	 - Replace mod 'Sodium' (sodium) 0.5.8+mc1.20.4 with version 0.5.8 that is compatible with:
		 - indium, any version
	 - Replace mod 'Indium' (indium) 1.0.28+mc1.20.4 with any version that is compatible with:
		 - sodium, version 0.5.8
More details:
	 - Mod 'Indium' (indium) 1.0.28+mc1.20.4 requires version 0.5.5 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.8+mc1.20.4!
	 - Mod 'Sodium' (sodium) 0.5.8+mc1.20.4 is incompatible with version 1.0.28 or earlier of mod 'Indium' (indium), but a matching version is present: 1.0.28+mc1.20.4!
	 - Mod 'Nvidium' (nvidium) 0.2.5-beta requires version 0.5.3, version 0.5.4 or version 0.5.5 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.8+mc1.20.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

### Reproduction Steps

Download these 3 mods and try to run the instance

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14139101/latest.log)

### Crash Report

Not Crashing but it wont start

**Comment by Felix14-v2** [comment]
Because they, well, incompatible. Please wait until these mods are updated to the latest Sodium version.
