### ISSUE TITLE
mouseClicked event handler

### ISSUE THREAD

**Issue by gbeat5002** [jellysquid3/Sodium#2315]
### Bug Description

i download mineshafts and monsters but it seems a Jenkins mod is causing the problem i tried everything from removing all Jenkin mods but it said i need sodium for my game to work

### Reproduction Steps

idk

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14151989/latest.log)

### Crash Report

[crash-2024-02-03_10.13.21-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14151993/crash-2024-02-03_10.13.21-client.txt)

**Comment by astridellensdottir** [comment]
This appears to be a log from a Forge modpack using Rubidium, an unofficial forge port of Sodium. As the Forge ports aren’t officially supported, there’s not much help we can offer.
