### ISSUE TITLE
Random chunks being invisible? 

### ISSUE THREAD

**Issue by PringoProngo** [jellysquid3/Sodium#2317]
### Bug Description

When trying to put a mod pack together I realized after I finished that when loading into a new/existing world some chunks would be gone and water and blocks under it tended to be fully transparent.

### Reproduction Steps

Download the following
- 3D Skin Layers by tr7zw 1.5.4-1.20
- AmbientSounds by creativemd 5.3.8
- AppleSkin by squeek502 2.5.0+mc1.20
- Architectury API by 9.1.12+fabric
- BCLib by quiqueck 3.0.14
- Beautify: Refabricated by Suel_ki 1.1.0+1.20
- Better Clouds by qendolin 1.3.13+1.20.1-R
- BetterEnd by quiqueck 4.0.11
- Blahaj (Fabric) - replushed by DaFuqs 0.3.2
- Botarium by 2.3.2
- CC: Tweaked by squiddev 1.109.5
- CC:C Bridge by Sammy 1.6.2b-fabric
- Couplings by HeckinChloe 1.9.4+1.20
- Create Crafts & Additions by mrh0 fabric-1.20.1-0.9.0
- Create Fabric by tropheusj 0.5.1-d-build.1161+mc1.20.1
- CreativeCore by creativemd 2.11.16
- Dark Loading Screen by A5b84 1.6.14
- Ender Dragon Fight Remastered by MrGenie151 4.3+mod
- Entity Culling by tr7zw 1.6.2-1.20
- Farmer's Delight [Fabric] by Zifiv
- FerriteCore by malte0811 6.0.1
- Handcrafted by Terrarium 3.0.5
- Indium by comp500 1.0.21+mc1.20.1
- Inventory Sorting by kyrptonaught 1.9.0-1.20
- Iris Shaders by coderbot 1.6.4+1.20
- Jade 🔍 by Snownee 11.7.0
- Just Enough Items by mezz 15.3.0.1
- LambDynamicLights by LambdAurora 2.3.2+1.20.1
- Let's Do: API by Cristelknight 1.2.8-fabric
- Let's Do: Meadow by satisfyu 1.2.0
- Light Emitting Diode by magistermaks 1.6.0
- Macaw's Bridges by sketchmacaw 2.1.0
- MidnightLib by Motschen 1.4.1-quilt
- Mod Menu by 7.2.2
- Moonlight Lib by MehVahdJukaar fabric_1.20-2.9.7
- More Beautiful Torches by lupiiin_ 2.5.2-1.20.1_fabric
- OptiFine 1.0.0
- Portfolio by Sheddmer 1.3.5-fabric
- Presence Footsteps by Sollace 1.9.1
- Quilted Fabric API (QFAPI) / Quilt Standard Libraries (QSL) by 7.5.0+0.91.0-1.20.1
- Resourceful Config by 2.1.2
- Resourceful Lib by 2.1.21
- Sodium by jellysquid3 mc1.20-0.4.10
- Sound Physics Remastered by henkelmax fabric-1.20.1-1.3.1
- Spelunkery by Ordana 1.20.1-0.3.5
- Tectonic by Apollo 2.2
- TerraBlender by Adubbz 3.0.1.4
- This Rocks! by Motschen 1.7.1
- Ube's Delight by ChefMooon 0.1.5b
- VanillaIcecreamFix by repletsin5 1.1.10-beta
- Visual Overhaul by Motschen 5.0.1-quilt
- Windchimes by hibi 1.2.4+1.20
- Xaero's Minimap by thexaero 23.9.7_Fabric_1.20
- Xaero's World Map by thexaero 1.37.8_Fabric_1.20
- YUNG's API by 1.20-Fabric-4.0.3
- YUNG's Better Strongholds by 1.20-Fabric-4.0.3
- YUNG's Extras by 1.20-Fabric-4.0.3
- YetAnotherConfigLib by isxander 3.2.1+1.20-fabric

After which just simply start up a new world and you'll quickly see the problem
![2024-02-04_03 28 22](https://github.com/CaffeineMC/sodium-fabric/assets/136867622/690f365d-a662-4435-952d-7fac159bca6c)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14156089/latest.log)

### Crash Report

[crash-2024-02-04_03.40.52-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14156097/crash-2024-02-04_03.40.52-client.txt)

**Comment by Poopooracoocoo** [comment]
This is not a support forum. Use the Discord server for that. The steps to repro section is supposed to prompt you to find a minimal setup. 

Two issues here. Since you're using Sodium 0.4.10, you need to use BetterEnd 4.0.10. Since you're using Indium 1.0.21, you need to use Fabric API 0.88.1.

**Comment by PringoProngo** [comment]
I apologize I had thought this was a general support page
Never the less what you offered seemed to have fixed the error in rendering so thank you.
