### ISSUE TITLE
screen flickering whit a dedicated gpu (its eye tiring)

### ISSUE THREAD

**Issue by gabtirel** [jellysquid3/Sodium#2318]
### Bug Description

screen flickering tho i have a dedicated gpu (rx 6600, r5 5600x) and its eye threating 

### Reproduction Steps

step 1: open minecraft
step 2: open a world
step 3: move around
and thats how it happens to me its quite annoying and idk what the heck i should do

### Log File

its just chunk rendering 

### Crash Report

my game never crashed

**Comment by Poopooracoocoo** [comment]
As the template says, you can invoke a crash manually by holding F3+C for 10s. Please provide a crash report and log.

It'll have important info like your driver version and if you have another GPU.

**Comment by gabtirel** [comment]
> As the template says, you can invoke a crash manually by holding F3+C for 10s. Please provide a crash report and log.
> 
> It'll have important info like your driver version and if you have another GPU.

i reinstalled sodium and now when i get a discord notification it just starts flickering also f3+c dosent work on my 60% keyboard and idk if i have a 2nd one

**Comment by jellysquid3** [comment]
This is a problem with Windows and certain OpenGL applications currently. Use a frame rate limit to try and mitigate it (especially V-Sync), and wait for an update from Microsoft & your graphics driver vendor.
