### ISSUE TITLE
Incompatible with Supplementaries 

### ISSUE THREAD

**Issue by CassieRoseZA** [jellysquid3/Sodium#2321]
### Bug Description

Sodium 0.5.8 Doesn't launch with Supplementaries Installed

### Reproduction Steps

add Sodium 0.5.8 on 1.20.1
add Supplementaries 
try launching the game
game crashes

### Log File

[2024-02-06-1.log](https://github.com/CaffeineMC/sodium-fabric/files/14175552/2024-02-06-1.log)

### Crash Report

n/a

**Comment by youmukonpaku1337** [comment]
#2303 exists, close this lmao
