### ISSUE TITLE
Crash when joining the world

### ISSUE THREAD

**Issue by Karashok-Leo** [jellysquid3/Sodium#2322]
### Bug Description

Crash when joining the world.

### Reproduction Steps

Save the world when the player is in the cloud, and crash when entering again.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14194897/latest.log)

### Crash Report

[crash-2024-02-07_21.58.56-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14194893/crash-2024-02-07_21.58.56-client.txt)

**Comment by Poopooracoocoo** [comment]
Can you find the smallest set of mods in which you can reproduce this issue with?

**Comment by 0-x-2-2** [comment]
Dumping the class from the mod-pack could also be helpful.

**Comment by Karashok-Leo** [comment]
I'm very sorry for misreporting this issue. I have now found that the reason for the crash is due to an old version of BadOptimizations, not sodium.
