### ISSUE TITLE
World Open Crash

### ISSUE THREAD

**Issue by Teamblertan** [jellysquid3/Sodium#2325]
### Bug Description

When I Open a world, Minecraft Crashes.

### Reproduction Steps

i dont really know how to.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14230320/latest.log)

### Crash Report

[crash-2024-02-10_21.45.35-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14230322/crash-2024-02-10_21.45.35-client.txt)

**Comment by Timolino456** [comment]
The Automining mod ([this one](https://modrinth.com/mod/automining)) is mentioned in the crash. The changelog of the version you are using mentions "Added hitbox rendering for entitys", maybe that is causing it. You can try using a previous version of it ([this one](https://modrinth.com/mod/automining/version/1.20.1_1.16.1)) or if that doesn't help, removing it.

**Comment by Teamblertan** [comment]
trying it out...

**Comment by Teamblertan** [comment]
downgrading didnt work. trying removal

**Comment by Teamblertan** [comment]
Removing The Mod Worked.
