### ISSUE TITLE
Add Fast Leaves setting

### ISSUE THREAD

**Issue by SAPET123** [jellysquid3/Sodium#233]
Please add a setting to video settings that would let you play with graphics set fast bet  your leaves would be set to fancy.
You can do that with optifine and it would be really cool in my opinion to set my leaves to fancy but everything  other would be set  to fast. If its possible please add this to the video settings

**Comment by amnotbananaama** [comment]
Sodium already does this. Leaves will always be transparent whether you have graphics set to "Fast", "Fancy" or "Fabulous". Sodium greatly improves the rendering technique of leaves, to the point that transparency is negligible.

**Comment by SAPET123** [comment]
> Sodium already does this. Leaves will always be transparent whether you have graphics set to "Fast", "Fancy" or "Fabulous". Sodium greatly improves the rendering technique of leaves, to the point that transparency is negligible.

Ok but I do I turn it on cuz I downloaded sodium this morning and when I have my graphics set to fast  the leaves are still fast  and not transparent. Was there some new update where  they have made it like that?

**Comment by LucilleTea** [comment]
I think the behaviour described by amnotbananaama may be a bug, or may be a feature, but it's only in development builds which are a bit broken currently.
Regardless of whether this request should be implemented, I do have a workaround for you.
After some brief wiki searching, I think the difference between fast/fancy is very limited, it's only: weather, clouds, leaves and maybe vignette. Since the other three options can be toggled independently in Sodium, you can simply set your graphics to fancy for the leaves then turn these other options down.

Adding a toggle for leaves would match the other settings, but seems a bit redundant, unless someone wants to use fast leaves with fabulous graphics?

**Comment by SAPET123** [comment]
Thank you for your respond. I appreciate it.

Dňa ut, 4. aug 2020, 19:17 Lucy-t <notifications@github.com> napísal(a):

**Comment by James-E-A** [comment]
> Sodium already does this. Leaves will always be transparent whether you have graphics set to "Fast", "Fancy" or "Fabulous".

I don't believe this is true.

- Minecraft `1.16.4`
- Fabric `0.11.1`
- Sodium `0.1.0`
- Multidraw (GL 4.3)
- Radeon HD 7570M
- Fedora Linux 31
- Java: `11.0.9.1+1`1(OpenJDK)
  - Also occurs on Mojang Java

![2021-01-16_10 48 37](https://user-images.githubusercontent.com/2776014/104819074-76144080-57e8-11eb-9fbb-6fcbe91f74a4.png)

Bundled JVM: ![2021-01-16_10 52 24](https://user-images.githubusercontent.com/2776014/104819170-f9ce2d00-57e8-11eb-9839-27bd67e231bf.png)

(Yes, I know the FPS are extremely low in these screenshots — they stabilize around 75–90 once the game is fully loaded)

**Comment by MrTechyyy** [comment]
For my part, I use [Cull Leaves](https://www.curseforge.com/minecraft/mc-mods/cull-leaves) to "fix" this issue, It's entirely compatible with Sodium.

**Comment by amnotbananaama** [comment]
> I don't believe this is true.

It was true at the time I made that comment, more than 5 months ago. Since then, it seems that the behavior has changed in current development builds.

Given that this functionality is available in another mod, I don't think this feature would be a good fit in Sodium at this time.

**Comment by James-E-A** [comment]
> Given that this functionality is available in another mod,

@amnotbananaama Which other mod are you referring to?

> For my part, I use Cull Leaves to "fix" this issue,

@MrTechyyy "Cull Leaves" does not provide this functionality:

- Minecraft `1.16.5`
- Fabric `0.11.1`
- Sodium `0.1.0`
- Cull Leaves `2.0.0`

![2021-01-26_14 35 06](https://user-images.githubusercontent.com/2776014/105908845-f191a100-5fe3-11eb-9e92-c4f5d16bafe8.png)

> I don't think this feature would be a good fit in Sodium at this time.

On the contrary, I believe `Leaves` would fit in perfectly, next to `Clouds` and `Weather` in the section for overriding aspects of Fast vs Fancy graphics. ([There are others](https://gaming.stackexchange.com/a/22242/64297), but Leaves is the most important QoL fix; it was the only one I really valued being able to manipulate in OptiFine)

**Comment by Rajbir98** [comment]
this feature is available in 1.17 dev but is there any way to turn off transparent leaves

**Comment by Lentern** [comment]
This can be closed now I think, they added the setting.

**Comment by MeeniMc** [comment]
Fast leaves are opaque in 0.4.11 this is resolved.
