### ISSUE TITLE
Replace mod 'Sodium' (sodium) 0.5.8+mc1.20.4 with version 0.5.8 that is compatible with:

### ISSUE THREAD

**Issue by helixxger** [jellysquid3/Sodium#2331]
### Bug Description

When starting Minecraft 1.20.4 with Optifabric 1.14.3 and Sodium 0.5.8 I get the error

Replace mod 'Sodium' (sodium) 0.5.8+mc1.20.4 with version 0.5.8 that is compatible with: optifabric 1.14.3

<html>Mod 'Sodium' (sodium) 0.5.8+mc1.20.4 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching<br>version is present: 1.14.3!</html>

### Reproduction Steps

Install sodium 0.5.8 fpr Fabric and OptiFabric 1.14.3

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14237903/latest.log)

### Crash Report

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.8+mc1.20.4 with version 0.5.8 that is compatible with:
		 - optifabric 1.14.3
More details:
	 - Mod 'Sodium' (sodium) 0.5.8+mc1.20.4 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.14.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Timolino456** [comment]
You can't use OptiFabric and Sodium together. You have to choose one (Sodium is most likely the better option).

**Comment by helixxger** [comment]
So, Sodium makes optifine Works with Fabric too?
Am 12. Feb. 2024, 12:46 +0100 schrieb Timolino456 ***@***.***>:

**Comment by asumagic** [comment]
No, Sodium is unrelated to OptiFine.

Sodium is (currently) a Fabric mod.

You can only use OptiFabric OR Sodium, not both. To try Sodium, remove OptiFabric.
