### ISSUE TITLE
1.20.1 Sodium for Forge

### ISSUE THREAD

**Issue by wolfieboy09** [jellysquid3/Sodium#2338]
### Request Description

So I am using the Create mod with other mods, and that does drop my frames quite a bit. So I do want to use Sodium for Forge 1.20.1. There is a mod that connects fabric and forge mods together, but I don't know if that will actually work

**Comment by Lolothepro** [comment]
duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/2229
Note: NeoForge mods are compatible with Forge with Minecraft 1.20.1

**Comment by wolfieboy09** [comment]
NeoForge 1.20.1 would work with Forge 1.20.1?

**Comment by Lolothepro** [comment]
yeap

**Comment by Lolothepro** [comment]
NeoForge is basically Forge in 1.20.1

**Comment by wolfieboy09** [comment]
I never knew NeoForge would work with Forge 1.20.1
