### ISSUE TITLE
game crashing when creating new world

### ISSUE THREAD

**Issue by askiezudasso** [jellysquid3/Sodium#2339]
### Bug Description

obs: I am not using pojav launcher, i'm using minecraft's official launcher

### Reproduction Steps

I simply create a new world, apparently the game loads it all but when it's actually joining in, it crashes

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14300025/latest.log)

### Crash Report

[crash-2024-02-15_14.02.06-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14300028/crash-2024-02-15_14.02.06-client.txt)

**Comment by Lolothepro** [comment]
caused by chunksfadein

**Comment by jellysquid3** [comment]
Not a problem with our mod. Something (probably Chunks Fade In) is modifying shader code which Sodium uses.
