### ISSUE TITLE
1.20.1 Random chunks not rendering

### ISSUE THREAD

**Issue by N8rtot** [jellysquid3/Sodium#2346]
### Bug Description

Bugs and holes appear in the world and fail to render, letting you xray straight through the ground. In the case of creating a new world with the mods installed, no chunks are rendered whatsoever. As I walked around and looked at these bugged chunks, I kept getting the same error wall of text
"[Chunk Render Task Executor #0/INFO]: [STDERR]: java.lang.NullPointerException"

![2024-02-18_14 30 28](https://github.com/CaffeineMC/sodium-fabric/assets/77558552/b214dae8-c7c7-4f98-840d-de3408e465e0)
![2024-02-17_20 11 15](https://github.com/CaffeineMC/sodium-fabric/assets/77558552/80beaca1-53ce-4379-a166-453086dda223)
![2024-02-18_13 54 49](https://github.com/CaffeineMC/sodium-fabric/assets/77558552/f2facff6-7cd5-4373-9938-7cd5b5911d22)

### Reproduction Steps

Run minecraft version 1.20.1 with these mods installed
Indium 1.0.21
Sodium 0.4.10
Iris 1.6.4
(Fabric API: 0.88.1)

Join or create a new singleplayer world

Find/load new chunks (chunks that have been loaded without the mod still seem to disappear at random

(NOTE): Used these very specific versions to play with create-fabric for 1.20.1, hence why so specific

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14324140/latest.log)

### Crash Report

[crash-2024-02-18_14.34.46-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14324144/crash-2024-02-18_14.34.46-client.txt)

**Comment by MeeniMc** [comment]
From the log you provided the version of better-end you are using is not compatible with the version of Sodium you are using.

**Comment by pajicadvance** [comment]
Better End is most likely the problem. The version you're using seems to be compatible with newer versions of Sodium and not the one you're currently using. You could try downgrading Better End to an older version, or update Sodium, Indium, Iris, Fabric API to their latest versions and use [Create Fabric Sodium Fix](https://modrinth.com/mod/create-fabric-sodium-fix).
