### ISSUE TITLE
Brightness slider description is wrong and misleading

### ISSUE THREAD

**Issue by EminGT** [jellysquid3/Sodium#2347]
### Bug Description

Sodium shows the following tooltip when hovering over the Brightness slider:
"Controls the brightness (gamma) of the game."

This makes no sense because Minecraft's Brightness slider has nothing to do with gamma. It's instead a slider that changes lighting intensity according to user preference.

This text should be replaced with something like this example:
"Controls the lighting intensity in darker areas of the game. Well lit areas are not affected."

### Reproduction Steps

Go to Video Settings and hover your mouse over the Brightness slider.

### Log File

-

### Crash Report

-

**Comment by Julienraptor01** [comment]
the setting is called gamma in the options.txt tho https://minecraft.wiki/w/Options.txt#:~:text=gamma

**Comment by jellysquid3** [comment]
It wasn't the intention to communicate that the brightness slider _was_ the gamma slider, but rather that it is also called gamma in some languages and within the code.

But yes, it's not a gamma slider (even if Minecraft calls it that.)  We should probably use less confusing language.
