### ISSUE TITLE
No FOV Settings

### ISSUE THREAD

**Issue by tezlm** [jellysquid3/Sodium#235]
**Is your feature request related to a problem? Please describe.**
There is no way to change the FOV in game with sodium

**Describe the solution you'd like**
An option to change the FOV, like in vanilla

**Describe alternatives you've considered**
Quit Minecraft and change the FOV in options.txt

**Additional context**
*none*

**Comment by reedrw** [comment]
![2020-08-05_19-45](https://user-images.githubusercontent.com/21069876/89474681-4c90bc80-d754-11ea-907b-e59e0f1af957.png)

**Comment by tezlm** [comment]
Oh I've been looking in the video settings...
oops

**Comment by andrew121410** [comment]
Bruh moment.
