### ISSUE TITLE
Random crash and corruption.

### ISSUE THREAD

**Issue by ClicksMatrix** [jellysquid3/Sodium#2351]
### Bug Description

Every time I go in a world and land on a block after being airborne it crashes my game and the world corrupts so bad that it crashes my game every time I try to load it.

### Reproduction Steps

1: Go on a world. 2: Jump. That's all I know. I do have other mods but the game is specifying sodium as the cause.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14353356/latest.log)

### Crash Report

[crash-2024-02-21_01.27.34-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14353352/crash-2024-02-21_01.27.34-client.txt)

**Comment by MeeniMc** [comment]
You have some sort of incompatibility with Sodium due to the mod Automining. You should see if they have an updated version that would be compatible or stop using that mod.
