### ISSUE TITLE
Apply "Smooth Lighting" to all modded fluids

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2353]
### Request Description

Currently, Sodium has a feature, which is to fix the bug MC-227302.
This is only fixed with some fluids, but some fluids from mods still have the bug.

For example, some liquids in "[The Bumblezone](https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric)" mods are still affected.

Is it possible to fix it for all fluids, even modded?

Screenshot:

Sugar Water (The Bumblezone) works:
![2024-02-22_14 42 00](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/2bfe1cc7-f277-43bd-a5fd-c6424fd7e350)

Royal Jelly (The Bumblezone) doesn't works:
![2024-02-22_14 42 17](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/47efa275-e143-440c-864e-ce556875c9ad)

Honey (The Bumblezone) doesn't works:
![2024-02-22_14 42 11](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/ab8f399f-c534-449f-b318-ff005cbb1884)

Water (Vanilla) works:
![2024-02-22_14 42 04](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/b37a3dfa-3562-4904-b562-d0fed50b4c6a)

Source: https://github.com/TelepathicGrunt/Bumblezone

**Comment by jellysquid3** [comment]
This is not possible to fix when mods emit custom geometry, as Bumblezone does for certain slow-moving fluids. They would have to implement the lighting code themselves, or otherwise rely on APIs we provide to get that functionality.
