### ISSUE TITLE
Animations for block are broken

### ISSUE THREAD

**Issue by V01DW3B** [jellysquid3/Sodium#2354]
### Bug Description

Animations are broken for blocks

### Reproduction Steps

I just opend a shest

### Log File

![2024-02-22_16 46 26](https://github.com/CaffeineMC/sodium-fabric/assets/68392877/6fc70fcb-1b61-4022-bf52-f0b2751b7ea6)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/68392877/ad10f0ef-0bef-4ec4-8e95-c75bae1aa9ad)
sorry for the blur

### Crash Report

no crash.

**Comment by Timolino456** [comment]
This is probably a problem caused by Enhanced Block Entities, not Sodium

**Comment by V01DW3B** [comment]
thanks that fixed it

**Comment by Poopooracoocoo** [comment]
instead of a log you posted screenshots of your mod folder... while helpful, that's not a log.

sodium doesn't implement the fabric rendering api. sodium 0.6 is expected to support it. 

you need to install [indium](https://modrinth.com/mod/indium)
