### ISSUE TITLE
when i use pistons the crash my game 

### ISSUE THREAD

**Issue by V01DW3B** [jellysquid3/Sodium#2356]
### Bug Description

I put a piston then used a redstone block and it crashed. I think its because of the animations.

### Reproduction Steps

I put a piston then used a redstone block and it crashed.

### Log File

![image](https://github.com/CaffeineMC/sodium-fabric/assets/68392877/4a3670b3-2349-4d72-8c4e-cb8c44adb59f)

### Crash Report

[crash-2024-02-22_17.26.20-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14375751/crash-2024-02-22_17.26.20-client.txt)

**Comment by astridellensdottir** [comment]
you need to install Indium. this is the version compatible with Sodium 0.5.3: https://modrinth.com/mod/indium/version/1.0.27+mc1.20.1
