### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Voidtfz** [jellysquid3/Sodium#2357]
### Bug Description

game crash when i create a world 

### Reproduction Steps

i try to create a world in singelplayer when i load the creation screen it crashes 

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14379060/latest.log)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/160957638/a83220b8-a7c3-4d0d-ba9d-5e4565b95e8c)

### Crash Report

[crash-2024-02-22_22.23.30-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14379062/crash-2024-02-22_22.23.30-client.txt)

**Comment by pajicadvance** [comment]
Nothing to do with Sodium, the library mod "sakuralib" is causing the crash.
