### ISSUE TITLE
a Resource pack makes Sodium crash

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2358]
### Bug Description

I found a resource pack that makes Minecraft crash with Sodium

### Reproduction Steps

Apply this resource pack 
[SodiumCrash (F_rex'ss Switch Pack).zip](https://github.com/CaffeineMC/sodium-fabric/files/14379312/SodiumCrash.F_rex.ss.Switch.Pack.zip)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14379324/latest.log)

### Crash Report

[crash-2024-02-22_22.02.58-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14379325/crash-2024-02-22_22.02.58-client.txt)

**Comment by Lolothepro** [comment]
fixed in next release

**Comment by jellysquid3** [comment]
What specifically was fixed? The shader pack, or Sodium? The crash looks as if it's on our side (unclamped values being used in biome color sampling.)

**Comment by Lolothepro** [comment]
> What specifically was fixed? The shader pack, or Sodium? The crash looks as if it's on our side (unclamped values being used in biome color sampling.)

https://github.com/CaffeineMC/sodium-fabric/commit/435a6bd7ecfa58499b64f1a73b61309070929d86

**Comment by jellysquid3** [comment]
The issue is valid then and needs to be correctly documented.
