### ISSUE TITLE
Could not find various jar files when building

### ISSUE THREAD

**Issue by Icedude907** [jellysquid3/Sodium#236]
Hi.
I've been trying to build with gradlew (windows), however the following jar files can't be found:
```
net.fabricmc.fabric-api:fabric-resource-loader-v0:0.2.5+059ea86602@net.fabricmc.yarn.1_16_1.1.16.1+build.17-v2
net.minecraft:minecraft:1.16.1-projectmapped-net.fabricmc.yarn-1.16.1+build.17-v2
net.fabricmc:fabric-loader:0.8.8+build.202@net.fabricmc.yarn.1_16_1.1.16.1+build.17-v2
```
Using OpenJDK 14.0.2

**Comment by amnotbananaama** [comment]
I cannot reproduce this error on Windows with Gradlew. Can you confirm your device can access the internet? Gradle downloads these dependencies from online, so you'll need an internet connection to download them at least once. Subsequent builds will re-use the downloaded resources. 

![](https://i.imgur.com/H3lLqim.png)

If this still occurring despite having an internet connection, can you post the full build log? You can do this by redirecting the command output to a file, eg. `gradlew build > gradlewlog.txt`. Note that this log will show your directory path (eg. `C:\Users\[username]\[sodium build folder]`), so make sure that's something you are comfortable sharing. Thanks!

**Comment by Icedude907** [comment]
Here's the output. I'm connected to the internet and I'm still getting this.
(This is from a fresh install, after deleting the .gradle folder in my user folder as well.)
[gradleOut.txt](https://github.com/jellysquid3/sodium-fabric/files/5040193/gradleOut.txt)

**Comment by Icedude907** [comment]
UPDATE:
I tried building it on the `C:/` drive (NTFS) and it built without trouble.
I was previously building this on an `A:/` (ExFAT) drive.
I'll keep the issue open for now, as this could be a problem with sodium or with gradle.

**Comment by jellysquid3** [comment]
Gradle doesn't really support building on non-NTFS volumes or network shares as far as I'm aware. I don't know the specifics of this issue, but it's outside our control.
