### ISSUE TITLE
emotecraft and sodium incompatibility on new mod version

### ISSUE THREAD

**Issue by Hawash1** [jellysquid3/Sodium#2363]
### Bug Description

On new versions of sodium when playing animations (for example, were used a set of animations spemotes) animation is not played correctly. To be more specific, the arms and legs are not bent and the second layer of the skin and objects in the hands does not chase body parts. This problem is not on versions sodium 0.5.3 and below. 

### Reproduction Steps

.

### Log File

.

### Crash Report

.

**Comment by jellysquid3** [comment]
Issue is invalid because you have failed to provide the log required log files, or any link to the project you are talking about.
