### ISSUE TITLE
No lightning in the Nether

### ISSUE THREAD

**Issue by wiloxe** [jellysquid3/Sodium#2364]
### Bug Description

When entering the Nether all I can see is black with exception to mobs, mushrooms, fires and the portal itself.
![2024-02-27_14 31 47](https://github.com/CaffeineMC/sodium-fabric/assets/4078460/f0f7f3f6-c77d-4705-8823-66b5cfdf8d54)

Fabric 0.15.7
Sodium 0.5.8 for 1.20.4
Minecraft 1.20.4

### Reproduction Steps

1. Create a world in creative
2. Make nether portal and go into the dimension
3. Experience the world that you can't see.

### Log File

Sadly latest.log is 93 MB and GitHub only accepts 25MB files max. I tried to copy over to pastebin but that crashed the page.
I've decided to upload it to google drive instead.
https://drive.google.com/file/d/1fVL5aUdvsmpVkzEbm-CEexQj5Gb36PQr/view?usp=sharing

### Crash Report

[crash-2024-02-27_14.52.27-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14420501/crash-2024-02-27_14.52.27-client.txt)

**Comment by jellysquid3** [comment]
You have some kind of overlay software installed (unrelated to our mod) which is causing problems with Minecraft.  Looking at the crash log, it seems the likely culprit is some software called "Asus GPU Tweak II OSD"... so try disabling and/or uninstalling it from your computer.
