### ISSUE TITLE
Unreported Exception thrown when trying to load into a World

### ISSUE THREAD

**Issue by LordM4x** [jellysquid3/Sodium#2367]
### Bug Description

When I try to load into a world I get an unreported Exception thrown. I am trying to run Sodium in 1.20.1 with the Distant horizons mod, api and Blendium.

### Reproduction Steps

Join a world and after it loads it just crashed before I can see anything

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14472303/latest.log)

### Crash Report

[crash-2024-03-03_09.35.08-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14472305/crash-2024-03-03_09.35.08-client.txt)

**Comment by jellysquid3** [comment]
The crash log indicates there is nothing wrong with Sodium, but rather one of your mods is hacking into it to change shader source code in a way that isn't valid. We can do nothing about this -- figure out which mod it is and report the problem to them.

**Comment by MCRcortex** [comment]
Blendium modifies the shader source
