### ISSUE TITLE
My game crash when i create a new world (Minecraft Java 1.20.1, fabric )

### ISSUE THREAD

**Issue by AngelXDShadow456** [jellysquid3/Sodium#2368]
### Bug Description

my game crash and this appears: Error: java.lang.NullPointerException: Cannot read field "field_44912" because "this.field_4015.field_1724" is null.
i notice that minecraft works correctly if i delete sodium

### Reproduction Steps

I play my modded minecraft game with 200+ mods, when i try to create a world the game crashes, try to delete mods 1 by 1 and sodium mod is the problem.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14485812/latest.log)

### Crash Report

[crash-2024-03-04_14.37.02-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14485822/crash-2024-03-04_14.37.02-client.txt)

**Comment by TheUserCreated** [comment]
You installed lots of mods without making sure they work with the version of sodium you have installed. I can't list all of them but at the very least you need to uninstall or change your version of the Shimmer mod.

**Comment by jellysquid3** [comment]
This is not a support forum. There is no issue with Sodium here -- one of your mods (Shimmer) is trying to mixin to our code and is failing.
