### ISSUE TITLE
minecraft crashes on server/world open

### ISSUE THREAD

**Issue by NoIDidntHackU** [jellysquid3/Sodium#2369]
### Bug Description

I just recently installed the new update for sodium and whenever I open a Minecraft world, the game freezes, and whenever I open a server, it crashes, I think this may have been caused my the fact that I increased the view distance in the mod called bobby for Nvidium, but I removed both bobby and nvidium, so am not sure,

### Reproduction Steps

i am not too sure, all i did was edit the config file for bobby to make the render distance over 3d in singleplayer worlds, which I was told to do by a tutorial

### Log File

[latest - Copy.log](https://github.com/CaffeineMC/sodium-fabric/files/14492967/latest.-.Copy.log)

### Crash Report

[crash-2024-03-05_19.31.39-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14492971/crash-2024-03-05_19.31.39-client.txt)

**Comment by Poopooracoocoo** [comment]
>baritone: Baritone 1.10.2
meteor-client: Meteor Client 0.5.6-1998

Expect limited to no support here

**Comment by jellysquid3** [comment]
This problem is caused by your hack clients and has nothing to do with our mods.
