### ISSUE TITLE
I was told to come here

### ISSUE THREAD

**Issue by emorydeer2** [jellysquid3/Sodium#2374]
### Bug Description

![image](https://github.com/CaffeineMC/sodium-fabric/assets/107522398/a4cd5fc8-ea2e-4f51-8c9e-8861e88d12c2)
Game crash, told to make a bug report here.

### Reproduction Steps

Launch game, wait.

### Log File

[latest.zip](https://github.com/CaffeineMC/sodium-fabric/files/14548159/latest.zip)

### Crash Report

No crash report, had to task manager game.

**Comment by IMS212** [comment]
Please try without the "Early Loading Screen" mod.

**Comment by emorydeer2** [comment]
Fixed, thanks
