### ISSUE TITLE
Bug from something, warning says to report to this github

### ISSUE THREAD

**Issue by DannyJacoby** [jellysquid3/Sodium#2376]
### Bug Description

Game crashes when joining a server

### Reproduction Steps

Join a server, and it crashes

### Log File

https://mclo.gs/vYWbamw

### Crash Report

None generated

**Comment by MeeniMc** [comment]
your error appears to be coming from a mod called 'worlds_together' and not related to Sodium. 

The other messages that list sodium indicate that some of your mods are not the correct version, they have been designed for Sodium 0.5.8 but you are running 0.5.3, you need to downgrade these mods to a version compatible with 0.5.3 (or update Sodium to 0.5.8, as well as all other mods that are currently depending on 0.5.3). 

None of these are Sodium bugs, if you need further assistance you may discuss on the discord instead.
