### ISSUE TITLE
game crashed when opening options menu

### ISSUE THREAD

**Issue by Waddly7** [jellysquid3/Sodium#2377]
### Bug Description

https://bytebin.lucko.me/av2OphvLJc

### Reproduction Steps

I just clicked the options button

### Log File

[2022-11-05-1.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/14566514/2022-11-05-1.log.gz)

### Crash Report

https://bytebin.lucko.me/av2OphvLJc

**Comment by Poopooracoocoo** [comment]
Update Reese's Sodium Options: https://modrinth.com/mod/reeses-sodium-options/version/mc1.20.4-1.7.2

**Comment by jellysquid3** [comment]
Not a bug with Sodium... you have other mods which have invalid mixins to our code. Update them.
