### ISSUE TITLE
Leaves texture using vanilla texture

### ISSUE THREAD

**Issue by nenamoree9** [jellysquid3/Sodium#2379]
### Bug Description

I am using a texture pack called Faithful 32x and the leaves texture rendered the vanilla texture.

### Reproduction Steps

Use a different texture pack

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14608585/latest.log)

### Crash Report

No crash report.

**Comment by TheNukeLore** [comment]
Make sure your resourcepack is above the "fabric" resourcepack.

**Comment by jellysquid3** [comment]
This is not a problem with Sodium. You have incorrectly applied your resource packs. Your added resource packs MUST be placed above "Fabric" and "Minecraft" in the resource packs list.
