### ISSUE TITLE
Sodium Crashing on world load & Rendering issues

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2380]
### Bug Description

Hi there, recently i installed fabric due to me wanting to install some other mods that aren't available & don't work with feather client, i installed all of the other mods that i preferred & Sodium to enhance my experience due to my PC specs being quite outdated. Once i loaded up ANY world with sodium installed. **It would crash or just hang the "Joining world..." screen.** Once i uninstalled sodium everything else seemed to run. And to note extra on some menus it would completely blank out my monitor **and force me to restart my PC (to be specific, resource packages menu, options & more)**

Specs:

**- GPU: Nvidia GeForce 1660ti
- CPU: Intel i7-9750H
- Nvidia Driver Version: 551.76**

I am unsure what's going on, as this has been occurring for the past 2 days. Some help would be appreciated!

(log files and crash report attached)

**- axis**

### Reproduction Steps

Load up fabric on 1.20.2, install Sodium into the mods folder & attempt to load a world.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14620001/latest.log)

### Crash Report

[crash-2024-03-15_12.27.29-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14620002/crash-2024-03-15_12.27.29-client.txt)

**Comment by Lolothepro** [comment]
meteor client is not supported

**Comment by jellysquid3** [comment]
Your problem is the hack client Meteor. Remove it.
