### ISSUE TITLE
Video settings are not updated correctly

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2383]
### Bug Description

Video settings are not updated correctly

### Reproduction Steps

1. Open video settings in a small window
2. Switch the game to full screen
3. Notice that the "GUI Scale" setting is always limited between 1 and 2.

https://github.com/CaffeineMC/sodium-fabric/assets/68275908/2f0de9d7-13a9-4338-ba74-fedeede40231

### Log File

https://mclo.gs/P3DpMGV

### Crash Report

https://mclo.gs/P3DpMGV

**Comment by Lolothepro** [comment]
related to https://github.com/CaffeineMC/sodium-fabric/issues/1492

**Comment by pajicadvance** [comment]
This is also how the video settings screen behaves in vanilla, so it should not be classified as a bug. It can be reopened as an enhancement request, though.

**Comment by allanonmage** [comment]
idk what you mean about this being vanilla, it's always gone to 5. I'm working on a modpack and 1.20.4 lets it go to 5, but had to back down to 1.20.1 and it's 0,1, 2. If I go to the regular video settings by using SHIFT + P, I have auto - 6 as options.

**Comment by davepusey** [comment]
Just tried it, and pajicadvance is correct.
In a vanilla (unmodded) 1.20.4 the GUI Scale option only has the following options... `Auto, 1, 2, 3, 4`

**Comment by Moulberry** [comment]
In Vanilla, the options that are available depends on your screen resolution. "Auto" just means use the largest one available. 1920×1080 gets 1, 2, 3, 4 which is probably davepusey's resolution. 2560×1440 should get up to 6 which is probably allanonmage's resolution, etc.
