### ISSUE TITLE
Mipmapping

### ISSUE THREAD

**Issue by SGFgit** [jellysquid3/Sodium#2385]
### Bug Description

Whenever I change mipmapping it changes nothing. The blurriness of blocks is still extreme and bothers the crap out of me. It looks awful to me. 
![2024-03-19_19 09 10](https://github.com/CaffeineMC/sodium-fabric/assets/104707595/dfd78bfc-7059-48bf-8490-4bb5b187ad84)
![2024-03-19_19 09 16](https://github.com/CaffeineMC/sodium-fabric/assets/104707595/fb4acf98-0f49-47d4-afbc-28d2fa92b4e5)
![2024-03-19_19 09 24](https://github.com/CaffeineMC/sodium-fabric/assets/104707595/cb56eb14-bae9-4345-b48f-cacde64b3ef7)
![2024-03-19_19 09 27](https://github.com/CaffeineMC/sodium-fabric/assets/104707595/c427c57e-9d8d-4743-9db8-e3b2a4815562)
Here you can see the mipmapping setting and the resulted change. If that blurriness is another setting please let me know.

### Reproduction Steps

Any version I have downloaded of sodium does this (No I have tested them all just the mod packs that use Sodium do this.)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14661350/latest.log)

### Crash Report

No crashing just the annoying mipmapping that looks awful to my eyes.

**Comment by jellysquid3** [comment]
> **Have you determined the minimum set of instructions to reproduce the issue?** If your problem only occurs with other mods installed, **then you should narrow down exactly which mods are causing the issue.** Please do not provide your entire list of mods to us and expect that we will be able to figure out the problem.

Unless you can narrow down which mods are interacting with Sodium to cause this problem, there is nothing we can do for you. This problem should not occur with just Sodium installed.

**Comment by SGFgit** [comment]
You'd be correct. Loaded up a version with Sodium, nvidium, and bobby and turned off mipmapping. If anything you told me something simple I should have checked myself. I'll continue to look into it. Thank you!
