### ISSUE TITLE
Some textures are bugged with sodium

### ISSUE THREAD

**Issue by Tr0llMode** [jellysquid3/Sodium#2389]
### Bug Description

![image](https://github.com/CaffeineMC/sodium-fabric/assets/88204047/00912c89-2363-4af6-b893-e1a592c26031)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/88204047/452f9f68-72ff-4765-b4f4-8edb01fc2c07)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/88204047/164fbc34-d73f-461c-8361-2373449327a8)

Some pixels are missing for some reason
Caseload (resourcepack creator) told me that its sodium fault
How can i fix this? :(

### Reproduction Steps

download this resourcepack with sodium:
[https://www.mediafire.com/file/lzgy4z9fo6v8d0e/!+Â§9Katie+Sigmond+Pack.zip/file](https://www.mediafire.com/file/lzgy4z9fo6v8d0e/!+%C3%82%C2%A79Katie+Sigmond+Pack.zip/file)

### Log File

nope

### Crash Report

nope

**Comment by Lolothepro** [comment]
not caused by Sodium.
