### ISSUE TITLE
Invisible players on a team with “seeFriendlyInvisibles” enabled will cull other translucent blocks behind them

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#239]
### Expected Behavior
I'd expect to see through the player and see the blocks behind (i.e. stained glass)

### Actual Behavior
The translucent blocks behind the invisible player will not render

### Reproduction Steps
I was playing on The Hive and saw some funky rendering. I later did some testing in SP and found that it's because of the “seeFriendlyInvisibles” team modifier thing

1. Spawn/find an entity that is obstructing a translucent block
2. /team create gamers
3. /team join gamers @e 
4. /effect give @e invisibility

### Attachments
<img width="1680" alt="Screen Shot 2020-08-06 at 13 51 33" src="https://user-images.githubusercontent.com/57548260/89565078-fe2efc80-d7eb-11ea-9d03-75329c7d4075.png">

### System Information
- Java Version: 1.8.0_252 64bit
- CPU: 12x Intel i7-8750H @ 2.20GHz
- GPU: AMD Radeon Pro 555X
(2018 Macbook Pro, base model running MacOS Mojave)

**Comment by Kroppeb** [comment]
Probably caused by #38

**Comment by ghost** [comment]
Seems like it. Should I close this issue?

**Comment by laggycomputer** [comment]
You probably should. You may also want to add a comment on that issue either referencing this one or re-explaining this behavior.

**Comment by jellysquid3** [comment]
This is unrelated to #38 and is a separate issue caused by entities being rendered _before_ the world. This causes their fully transparent fragments to be written to the depth buffer first, meaning that by the time we render the water, the GPU will never write any new fragments because they're behind the "nearest" fragment.

**Comment by Kroppeb** [comment]
Oh, my bad

**Comment by ryleu** [comment]
Does this happen the same way when you're in spectator mode looking at something invisible?

**Comment by SmajloSlovakian** [comment]
I can confirm that this is a vanilla issue and it will make particles, entities, block entities, translucent blocks and beacon beams invisible behind translucent entities, name tags of players who are crouching... there may be more. if sodium fixes this, i will be happy.
