### ISSUE TITLE
[Suggestion] Make DONATION_PROMPT_MESSAGE translatable

### ISSUE THREAD

**Issue by Kasualix** [jellysquid3/Sodium#2391]
### Request Description

https://github.com/CaffeineMC/sodium-fabric/blob/dev/src/main/java/net/caffeinemc/mods/sodium/client/gui/SodiumOptionsGUI.java#L443C9-L443C33

Or is it hardcoded for a reason?

**Comment by qznfbnj** [comment]
Like #2283?

**Comment by Kasualix** [comment]
ok
