### ISSUE TITLE
Client fails to launch (1.20.1)

### ISSUE THREAD

**Issue by ShadowFireX0** [jellysquid3/Sodium#2396]
### Bug Description

When I try to launch fabric, it closes after 2 seconds of launch. I suspect that there is an incompatability issue invilvng some other mod in my modpack. Here is my mod folder
![image](https://github.com/CaffeineMC/sodium-fabric/assets/165475391/b8411edd-0da1-4818-9585-a5eac163f053)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/165475391/285e89f3-2bc2-4640-b745-ec2a831b6e32)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/165475391/941576e9-578a-419a-a2dd-a55486c8f50f)

### Reproduction Steps

Download the latest fabric version, then download all the mods and put them into mod folder. Perform only in minecraft 1.20.1.

### Log File

[2024-03-30-6.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/14811704/2024-03-30-6.log.gz)

### Crash Report

Can't create due to game closing too early.
Hardware is Intel i5-11400f and Nvidia Geforce RTX 3050

**Comment by Poopooracoocoo** [comment]
> The Fabric Rendering API is not available. If you have Sodium, install Indium!

This issue is being tracked in issue 5. Until then, install Indium. https://modrinth.com/mod/indium/version/1.0.30+mc1.20.4
