### ISSUE TITLE
Multi-draw chunk renderer is broken on recent AMD drivers

### ISSUE THREAD

**Issue by jonab03** [jellysquid3/Sodium#24]
If you are experiencing this issue, please help us get the problem fixed with AMD's driver team by clicking [here](https://gist.github.com/Sturmlilie/0925048a09b3869ebb2b04635f3610b1) and following the listed instructions.
---

### Expected Behavior
The world renders without massive glitches.

### Actual Behavior
There are massive graphical glitches.

### Reproduction Steps

1. Load/generate any world.
2. Set chunk renderer to 'OpenGL 4.6'
3. Look at the massive glitches

### Attachments
Expected behavior. (Made with chunk renderer set to 3.0)

![Windows opengl 3 0](https://user-images.githubusercontent.com/57867790/84635712-e0cc6900-aef3-11ea-91f3-c136b19e9e9a.png)

Actual behaviour. (Made with chunk renderer set to 4.6)

![Windows opengl 4 6](https://user-images.githubusercontent.com/57867790/84635719-e32ec300-aef3-11ea-89b8-47aa8ec4b550.png)

Behaviour with mesa drivers with chunk renderer set to 4.6. (Mirrors expected behavior)

![Linux opengl 4 6](https://user-images.githubusercontent.com/57867790/84635915-2c7f1280-aef4-11ea-95cd-5d3cda411f04.png)
### System Information

- Java Version: 14.0.1, AdoptOpenJDK (hotspot)
- CPU: AMD Ryzen 5 3600 6-Core Processor
- GPU: AMD Radeon RX 5700 XT
- [Full DxDiag.txt](https://github.com/jellysquid3/sodium-fabric/files/4779017/DxDiag.txt)

**Comment by jellysquid3** [comment]
This is a widely reported issue with the newer AMD drivers on Windows, and to my best investigation it looks to not be the fault of Sodium but rather a driver issue. I'm not sure what the best channel is for reporting this issue to AMD, but if anyone has pointers, please let me know.

For future stumblers of this issue, you will need to use Sodium's OpenGL 3.0 renderer, which can be found in `Video Settings > Performance`.

We might want to blacklist these AMD drivers from using Sodium's OGL 4.6 renderer before the 0.1 release.

**Comment by Siuolplex** [comment]
It would also be helpful to link the download page to the mesa drivers for AMD users.

**Comment by jonab03** [comment]
@Siuolthepic The Mesa drivers are included in most linux distributions by default. If not they are most likely available in your package repository. They aren't available for windows.

**Comment by stefan2225** [comment]
There are apparently some OGL fixes scheduled for the next Adrenaline driver release, it may or may not fix this (although I personally think the chance is very slim considering the track record of the driver team). We'll just have to wait and see.

**Comment by jellysquid3** [comment]
Multi-draw rendering is now disabled by default on the proprietary AMD drivers. See https://github.com/jellysquid3/sodium-fabric/commit/bcbef571b7bf33db1a26d11e4e52b801b1b5c39e. I'll be keeping this issue open until the underlying problem is solved.

**Comment by jellysquid3** [comment]
Resolved with c41a0aff.

**Comment by gauntlet7649** [comment]
> Resolved with [c41a0af](https://github.com/jellysquid3/sodium-fabric/commit/c41a0aff2c74f5b2ad3c1ef2958a249746265587).

How do i apply the fix?

**Comment by Dolphin2Point1** [comment]
> > Resolved with [c41a0af](https://github.com/jellysquid3/sodium-fabric/commit/c41a0aff2c74f5b2ad3c1ef2958a249746265587).
> 
> How do i apply the fix?

compile any commit of sodium after that commit or download the experimental build in the pinned of the #testers channel on jellysquids discord

**Comment by craftplayeri2** [comment]
> > > Resolved with [c41a0af](https://github.com/jellysquid3/sodium-fabric/commit/c41a0aff2c74f5b2ad3c1ef2958a249746265587).
> > 
> > 
> > How do i apply the fix?
> 
> compile any commit of sodium after that commit or download the experimental build in the pinned of the #testers channel on jellysquids discord

I don't have the slightest knowledge of coding or compiling anything, can you link me the discord instead?
