### ISSUE TITLE
Sodium crash on world/ server join

### ISSUE THREAD

**Issue by mewnn** [jellysquid3/Sodium#2405]
### Bug Description

Not sure if it's exactly on sodium side as I use a lot of other mods, but this is the first time I face this issue. Although, I've been playing with the mods for a while. I haven't played with this modpack in 2 weeks, and some mods got updated. After this U tried today and the crash is taking place.

### Reproduction Steps

1. Using SKlauncher (never had the problem before)
2. Using mods
3. Trying to join the world
4. Crash

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14893553/latest.log)

### Crash Report

[crash-2024-04-06_15.28.35-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14893554/crash-2024-04-06_15.28.35-client.txt)

**Comment by pajicadvance** [comment]
Cracked launchers are not supported. If you own the game, reproduce the issue with a legitimate launcher.
