### ISSUE TITLE
My modded Fabric minecraft handles everything goodly in maximum settings, but for some reason it starts to cap 60 fps in Tight areas and non-iluminated ones

### ISSUE THREAD

**Issue by equa25** [jellysquid3/Sodium#2407]
### Bug Description

![Screenshot_1](https://github.com/CaffeineMC/sodium-fabric/assets/141887969/51a3bb61-04c9-4f24-8260-a73df80a713e) - My mods folder
![2024-04-07_13 04 29](https://github.com/CaffeineMC/sodium-fabric/assets/141887969/cfcb9b9d-847f-4f9e-a0c9-d21ac5f61ad9)
![2024-04-07_16 29 45](https://github.com/CaffeineMC/sodium-fabric/assets/141887969/a094cdd8-0182-4f00-a8fa-641bc0925b89)

### Reproduction Steps

 My Max Framerate is set to 200 , with 8 chunks rendering enabled alongside with graphics on Max, and my Pc that contains both: AMD Ryzen 5 1400 and Nvidia Geforce GTX 1650 (Also i installed the latest nvidia graphic) runs perferctly with those settings. When i decided to download the newest versions of Sodium, Lithium, Sodium extra, Krypton and Iris, i noticed a strange pattern of FPS stuttering to 60 whenever i enter in a very tight area or even some that has no ilumination on it, which is making me upset as i am using some Elevators, entering in Nether fortress or even mining with this troubleshooting issue. Do you know what it could be?

### Log File

e

### Crash Report

e

**Comment by pajicadvance** [comment]
Please join the [Discord server](https://jellysquid.me/discord) for support, the issue tracker is not a support forum.

**Comment by equa25** [comment]
Hello, i cant enter on this link, could you send me the server's invite pls?

Em seg., 8 de abr. de 2024, 14:30, pajic ***@***.***>
escreveu:
