### ISSUE TITLE
Shader compilation failed

### ISSUE THREAD

**Issue by h9lis** [jellysquid3/Sodium#2408]
### Bug Description

I can't connect to servers or singleplayer worlds

### Reproduction Steps

Open Game - Singlplayer/Multiplayer - Join any server/world - Game Crashes

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14907278/latest.log)

### Crash Report

[crash-2024-04-08_17.57.14-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14907291/crash-2024-04-08_17.57.14-client.txt)

**Comment by asumagic** [comment]
Can you try disabling resource packs and see if that solves the issue? Your log mentions a resource pack `tweeeeks` which overrides core shaders, which aren't supported, but I don't know if it is relevant here.

**Comment by h9lis** [comment]
By trial and error method I found out that blendium caused crash
