### ISSUE TITLE
Shulker boxes have no inside textures.

### ISSUE THREAD

**Issue by laserlemons** [jellysquid3/Sodium#241]
### Expected Behavior
Normally you can see the bottom texture of a shulker box when it opens.

### Actual Behavior
The bottom side texture of a shulker box is invisible from the inside.

### Reproduction Steps
1. Have yourself or someone else open a shulker box.
2. Look inside at the bottom while it is still open.

### Attachments
![2020-08-07_12 59 00](https://user-images.githubusercontent.com/6501298/89684011-70681580-d8ae-11ea-8321-8d57c68ab79d.png)

### System Information
- Java Version: [1.8.0_51 64 bit]
- CPU: [AMD Ryzen 3600]
- GPU: [Nvidia GTX 770]

**Comment by laserlemons** [comment]
After closer inspection it looks like there is a whole set of inside textures missing here, not just the bottom of the box.

**Comment by GunsAndChips** [comment]
I initially thought this was the case, but the bottom texture is actually rendered at the wrong height - try placing a shulker box on top of a hopper / cauldron / composter, and you can see the inside of the shulker box (but only on the inside part of the block where it's lower)

I would try edit the title but I just made my github acc to make this comment, so idk how oof

**Comment by OS-Void** [comment]
Can confirm its Sodium related issue, it gets fixed if Compact Vertex Format is disabled

**Comment by jellysquid3** [comment]
Fixed by a9a783f1.
