### ISSUE TITLE
HIgh gpu usage for sodium

### ISSUE THREAD

**Issue by adak2249** [jellysquid3/Sodium#2412]
i have i5-12000f and rtx 3060 in my computer. At first when i use sodium with fabric it consumes only 20-25% of gpu. But aftert some days when i launch minecraft with sodium and fabric my gpu goes 65-70% usage. can anyone please fix the issue

**Comment by pajicadvance** [comment]
This is not a support forum, join the [Discord server](https://jellysquid.me/discord) for help with performance issues.
