### ISSUE TITLE
New license doesn't get placed into builds

### ISSUE THREAD

**Issue by Niterux** [jellysquid3/Sodium#2413]
### Bug Description

After the license update the new license no longer gets compiled into builds because the file was changed from COPYING/COPYING.LESSER into LICENSE.md, I believe lines 92 and 93 of [build.gradle.kts](https://github.com/CaffeineMC/sodium-fabric/blob/dev/build.gradle.kts#L92-L93) are to blame. I believe this is unintentional.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/110568869/ab8cefa2-c7f6-458c-8771-7aa28e60fd4e)

### Reproduction Steps

Git clone the latest dev branch commit.
Compile Sodium with the command "gradlew build"
Notice that LICENSE.md isn't present inside the jar file

### Log File

[gamelog.txt](https://github.com/CaffeineMC/sodium-fabric/files/14934286/gamelog.txt)

### Crash Report

[crash-2024-04-10_11.25.47-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/14934292/crash-2024-04-10_11.25.47-client.txt)

**Comment by jellysquid3** [comment]
Resolved with https://github.com/CaffeineMC/sodium-fabric/commit/43bc968a777c438001c5d9ac1e0e1194b1b85ed1
