### ISSUE TITLE
WorldBorder Warning Overlay not Rendering Correctly

### ISSUE THREAD

**Issue by Dueris** [jellysquid3/Sodium#2415]
### Bug Description

When running the latest version of Sodium(0.5.8 on modrinth), the WorldBorder warning overlay doesnt get displayed at all.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/122416109/a75318a0-7bd6-488f-aca2-dc0a08a5af5a)

### Reproduction Steps

Go to the WorldBorder or set the WorldBorder warning distance a really high number, and the WorldBorder warning overlay wont display.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14950446/latest.log)

### Crash Report

No crash

**Comment by Dueris** [comment]
I have also checked all mods I have installed, Sodium does seem to be the mod causing this

**Comment by Lolothepro** [comment]
Please send a screenshot of the "Quality" tab in your graphics/video settings.

**Comment by Dueris** [comment]
Super sorry for the delay! I've been very busy irl. I'll be on my computer in abt an hour to give you the ss

**Comment by Dueris** [comment]
![image](https://github.com/CaffeineMC/sodium-fabric/assets/122416109/a6a2ea21-01d9-4779-9ceb-4e2c6b4f0a9c)

**Comment by Lolothepro** [comment]
You have disabled "Vignette"...

**Comment by jellysquid3** [comment]
Not a bug with Sodium. You disabled the option which controls this. This would be expected behavior.

**Comment by Dueris** [comment]
Ahh, I see. The description for Vigentte didn't seem to include anything abt the world border, so it didn't seem like that was the cause of it. My apologies

**Comment by Felix14-v2** [comment]
You can use [this mod](https://modrinth.com/mod/no-vignette-yes-warning) to keep the effect with vignette disabled
