### ISSUE TITLE
Sodium causes Z-fighting with big dripleafs

### ISSUE THREAD

**Issue by djmrFunnyMan** [jellysquid3/Sodium#2416]
### Bug Description

Probably definitely caused by the compact vertex format.
Big Dripleafs zfight when next to a block. Most noticable when the dripleaf is facing west or north, however it occurs even when it's facing south/east because it has 3 pixels on each side that will face either west or north instead.
![2024-04-11_21 15 43](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/ef3bf45a-738b-4543-8389-da328f1cd593)
![2024-04-11_20 43 48](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/7deac602-bdb8-4d78-8cc0-60a573a12722)

### Reproduction Steps

Place a big dripleaf and surround it with blocks. Use a debug stick to make it face either north or west and you will see the issue.

### Log File

A log file is not relevant

### Crash Report

A crash report is not relevant

**Comment by jellysquid3** [comment]
This should be fixed with https://github.com/CaffeineMC/sodium-fabric/commit/ea0172768a5da9907b5a5711160dc3984fafea83.
