### ISSUE TITLE
World border renders through blocks

### ISSUE THREAD

**Issue by djmrFunnyMan** [jellysquid3/Sodium#2417]
### Bug Description

World border renders through blocks in some situations.

### Reproduction Steps

Use spectator mode to fly outside the worldborder, and try to look straight towards the border that would be parallel to you. You should see it render through the ground.
![2024-04-12_04 26 05](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/e319536e-b8a5-4d2c-964f-79fcd51661ad)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/14953333/latest.log)

### Crash Report

Not needed (really)

**Comment by jellysquid3** [comment]
This happens in vanilla Minecraft for reasons that are beyond me. It's not a bug with Sodium.
