### ISSUE TITLE
Make custom version of the Vanilla Tweaks better fast leaves for programmer art that actually uses the original texture instead of using the oldest one available from Vanilla Tweaks

### ISSUE THREAD

**Issue by mrjasonn** [jellysquid3/Sodium#2422]
### Request Description

Please create a custom version of Vanilla Tweaks’ Better Fast Leaves for Programmer Art, using the original texture from Programmer Art to make it instead of the oldest texture for the leaves from Vanilla Tweaks. This will provide a more original and authentic look for users using Programmer Art and which most would probably appreciate.

This is something that has been improperly brought up a long time ago in the pull request that first added Better Fast Leaves for Programmer Art (#1862) that no one has done or brought up properly until now I'm bringing this up properly that this would be good to do.

**Comment by djmrFunnyMan** [comment]
this is the sodium issue tracker (wrong place)

You can contact the vanilla tweaks team through their website https://vanillatweaks.net/feedback/

**Comment by IMS212** [comment]
No, this is correct; Sodium includes textures sourced from Vanilla Tweaks.

**Comment by jellysquid3** [comment]
I've compared the textures in Sodium right now and they're identical to the programmer art resource pack, so this looks to have been resolved.
