### ISSUE TITLE
PojavLauncher support

### ISSUE THREAD

**Issue by 13Ralef** [jellysquid3/Sodium#2423]
### Request Description

Well. I'm requesting something, that is adding official PojavLauncher support, it's because of patches are boring and they reduce performance in like 90% that non-patched versions, could y'all developers add this support? I would be very grateful 🙏🏼🙏🏼

**Comment by pajicadvance** [comment]
Support for Pojav will not be added - please read the [hardware requirements](https://modrinth.com/mod/sodium#hardware-compatibility).

**Comment by 13Ralef** [comment]
> Support for Pojav will not be added - please read the [hardware requirements](https://modrinth.com/mod/sodium#hardware-compatibility).

Well.
