### ISSUE TITLE
Command Block Issues

### ISSUE THREAD

**Issue by thebriofficial** [jellysquid3/Sodium#2426]
### Bug Description

I believe this is a Sodium issue because it doesn't happen in Vanilla MC but at the same time I'm not sure.

I was on a regular world with the newest version of Sodium for 1.20.4 and the latest Fabric version for 1.20.4
I was playing around with the tp command. I did: "execute as @p at @s run tp @s ~ ~ ~ facing entity @e[limit=1,tag=SPAWNER]"
I found that when loading new chunks, Minecraft seemed to halt down to 5-10 FPS. In Vanilla MC this doesn't happen,

### Reproduction Steps

Place a Repeating Command Block with Always Active (or with an activated lever if you want)
Type this:  "execute as @p at @s run tp @s ~ ~ ~ facing entity @e[limit=1,tag=SPAWNER]" or  "execute as @p at @s run tp @s ~ ~ ~ facing entity @e[limit=1,type=armor_stand]" if the Armor Stand you spawned didn't have a tag
Move to load new chunks that haven't been visited

### Log File

[2024-04-21-3.log](https://github.com/CaffeineMC/sodium-fabric/files/15051322/2024-04-21-3.log)

### Crash Report

The latest log I have is a crash log about Zoomify

**Comment by douira** [comment]
Can't reproduce on `dev`. The log file you sent us isn't the one you used when you experienced this bug.
