### ISSUE TITLE
Lava has unnecessary gaps between it's quads

### ISSUE THREAD

**Issue by djmrFunnyMan** [jellysquid3/Sodium#2427]
### Bug Description

Sodium introduces gaps between fluid quads to prevent some intersection issues afaik? Afaik this is only supposed to affect water, but lava is also affected, which looks bad with shaders. If the gaps really aren't necessary with the lava then they should just be removed.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/56b5591d-cd23-429c-8a0b-dc3325604308)

### Reproduction Steps

Place down a lava bucket and let it flow. Use Complementary shaders with Euphoria Patches then enable lava noise to make the gaps clearly visible.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/71a3c6f8-546d-41a9-80d8-bfb67ff64d06)

### Log File

Not relevant

### Crash Report

Not relevant

**Comment by djmrFunnyMan** [comment]
(Not sure if it truly is unnecessary just going by this)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/68905776/08112e68-16c2-422d-9a44-b29336742a22)

**Comment by Lolothepro** [comment]
Isn't that caused by the shaders?

**Comment by douira** [comment]
Does this gap also exist without sodium?

**Comment by djmrFunnyMan** [comment]
yes

**Comment by douira** [comment]
Sodium could investigate fixing this, since we rewrite the fluid renderer and know if it's water, which is relevant for waterlogging whereas other fluids are not. I'm not sure if such special casing is desired or helpful.

**Comment by djmrFunnyMan** [comment]
well it's up to Jellysquid, I'd obviously prefer it to be fixed even if it is a vanilla bug

**Comment by Felix14-v2** [comment]
I'm afraid fixing that might break mods like [Towelette](https://modrinth.com/mod/towelette) (cause z-fighting)

**Comment by djmrFunnyMan** [comment]
I don't see how but also who cares it has 1k downloads

**Comment by muzikbike** [comment]
Could this be reopened in that case (or a new ticket created)? I do find this distracting and Sodium could implement an alternate solution to this if desired.
