### ISSUE TITLE
sodium 1.20.4 stuck on mojang loading screen. 

### ISSUE THREAD

**Issue by Muheet-Faisal** [jellysquid3/Sodium#2428]
### Bug Description

I usually use optifine but today i dedcided to use sodium but unfortunately it is keep sticking on loading screen after few minutes my computer shows me end-task option 

### Reproduction Steps

i am using 4 mods all of them are here 
![image](https://github.com/CaffeineMC/sodium-fabric/assets/90416858/ac16555a-4738-44fb-b760-0339dc73e1e5)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15060166/latest.log)

### Crash Report

[crash-2024-04-20_18.38.45-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/15060188/crash-2024-04-20_18.38.45-client.txt)

**Comment by asumagic** [comment]
`java.lang.RuntimeException: Mixin transformation of me.modmuss50.optifabric.mod.Text failed
`

Remove Optifabric.

**Comment by Muheet-Faisal** [comment]
this crash report is 2 days old (latest on that folder) and i am not using optifabric with sodium mod

**Comment by asumagic** [comment]
You have Ivy Bridge generation graphics, try following the steps here: https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility#gen7-graphics---ivy-bridge-haswell-and-bay-trail-2012---2013

**Comment by Muheet-Faisal** [comment]
Thanks problem solved❤️
