### ISSUE TITLE
Wolf armor item overlay does not render correctly

### ISSUE THREAD

**Issue by BluebirdDevs** [jellysquid3/Sodium#2430]
## Broken wolf armor texture
![image](https://github.com/CaffeineMC/sodium-fabric/assets/76973207/5a4b349d-88a6-4a44-a354-f3b58f3217de)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/76973207/573e3ff8-7689-4e73-bd61-fb2c51524bf4)

### fixes when you dye it
![image](https://github.com/CaffeineMC/sodium-fabric/assets/76973207/2e0df7e4-164d-4990-9ac0-153f7b6820eb)

### Reproduction Steps

use sodium in 1.20.5 and obtain the wolf armor item.
see it is broken

### Log File

not needed

### Crash Report

not needed

**Comment by Koi-MC** [comment]
+1 same issue with only Sodium installed in mods

**Comment by IMS212** [comment]
Fixed in Sodium 0.5.9 (will release soon)
