### ISSUE TITLE
Sudden crash

### ISSUE THREAD

**Issue by KozukiYOMA** [jellysquid3/Sodium#2431]
### Bug Description

When playing on the server, it crashes when entering some areas.
I sent the problem to the author of SkinLayer3D but it was not fixed.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/167823145/cf4a7211-0d22-4b43-ab26-d141b5d68fdd)

### Reproduction Steps

It crashes when entering certain areas of a certain server.
Sometimes it does not crash, so I am not sure.

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15100405/latest.log)

### Crash Report

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2024-04-25 06:08:01
Description: Rendering Block Entity

java.lang.NullPointerException: Cannot invoke "dev.tr7zw.skinlayers.api.Mesh.setPosition(float, float, float)" because "mesh" is null
	at net.minecraft.class_836.handler$dil001$skinlayers3d$renderSkull(class_836.java:1631)
	at net.minecraft.class_836.method_32161(class_836.java)
	at net.minecraft.class_836.method_3577(class_836.java:77)
	at net.minecraft.class_836.method_3569(class_836.java:33)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:369)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:308)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:271)
	at net.minecraft.class_761.handler$djm000$sodium$onRenderBlockEntities(class_761.java:10831)
	at net.minecraft.class_761.method_22710(class_761.java:1146)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_836.handler$dil001$skinlayers3d$renderSkull(class_836.java:1631)
	at net.minecraft.class_836.method_32161(class_836.java)
	at net.minecraft.class_836.method_3577(class_836.java:77)
	at net.minecraft.class_836.method_3569(class_836.java:33)
	at net.minecraft.class_824.method_23079(class_824.java:90)
	at net.minecraft.class_824.method_23081(class_824.java:79)

-- Block Entity Details --
Details:
	Name: minecraft:skull // net.minecraft.class_2631
	Block: Block{minecraft:wither_skeleton_wall_skull}[facing=west,powered=false]
	Block location: World: (239,86,-203), Section: (at 15,6,5 in 14,5,-13; chunk contains blocks 224,-64,-208 to 239,319,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block: Block{minecraft:wither_skeleton_wall_skull}[facing=west,powered=false]
	Block location: World: (239,86,-203), Section: (at 15,6,5 in 14,5,-13; chunk contains blocks 224,-64,-208 to 239,319,-193), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block Entity NBT: {}
Stacktrace:
	at net.minecraft.class_824.method_3554(class_824.java:104)
	at net.minecraft.class_824.method_3555(class_824.java:79)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntity(SodiumWorldRenderer.java:369)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:308)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderBlockEntities(SodiumWorldRenderer.java:271)
	at net.minecraft.class_761.handler$djm000$sodium$onRenderBlockEntities(class_761.java:10831)
	at net.minecraft.class_761.method_22710(class_761.java:1146)
	at net.minecraft.class_757.method_3188(class_757.java:1098)
	at net.minecraft.class_757.method_3192(class_757.java:866)
	at net.minecraft.class_310.method_1523(class_310.java:1327)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3651429912 bytes (3482 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) N95
	Identifier: Intel64 Family 6 Model 190 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 1.69
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 128.00
	Graphics card #0 deviceId: 0x46d2
	Graphics card #0 versionInfo: DriverVersion=31.0.101.5186
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 22383.51
	Virtual memory used (MB): 16558.15
	Swap memory total (MB): 14413.60
	Swap memory used (MB): 1294.14
	JVM Flags: 11 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G -Xmn512M -XX:ReservedCodeCacheSize=1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:ParallelGCThreads=4 -XX:ConcGCThreads=4 -XX:MaxGCPauseMillis=25 -XX:G1HeapRegionSize=16M
	Fabric Mods: 
		antighost: AntiGhost 1.20.4-fabric0.91.2-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		appleskin: AppleSkin 2.5.1+mc1.20.3
		badoptimizations: BadOptimizations 2.1.0
		betterf3: BetterF3 9.0.2
		bobby: Bobby 5.1.0+mc1.20.4
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.66
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.66
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.11.66
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.66
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.66
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.66
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.66
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.66
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.66
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.66
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.66
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.66
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.66
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.66
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.66
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.66
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.66
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.66
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.66
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.66
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.66
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		chat_heads: Chat Heads 0.10.32
		cicada: CICADA 0.6.2+1.20.2-and-above
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.49
		compact-chat: Compact Chat 2.1.0
		dcch: DCCH 1.2
		elementa: Elementa 629
		entityculling: EntityCulling 1.6.4
		essential: Essential 1.3.1.3+g88238d7752
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.1
		exordium: Exordium 1.2.1
		fabric-api: Fabric API 0.97.0+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.62+78d798af4f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.5+78d798af4f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.15.10
			mixinextras: MixinExtras 0.3.5
		ferritecore: FerriteCore 6.0.3
		figura: Figura 0.1.4+1.20.4
			com_github_figuramc_luaj_luaj-core: luaj-core 3.0.8-figura
			com_github_figuramc_luaj_luaj-jse: luaj-jse 3.0.8-figura
			com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		firstperson: FirstPerson 2.3.3
		fpsreducer: FPS Reducer 1.20.4-2.7
		freecam: Freecam 1.2.3
		fullbrightnesstoggle: Full Brightness Toggle 4.0
		globalization: Globalization 1.1.3
		google-chat: GoogleChat 0.7.4
		immediatelyfast: ImmediatelyFast 1.2.11+1.20.4
			net_lenni0451_reflect: Reflect 1.3.2
		indium: Indium 1.0.30+mc1.20.4
		inventoryhud: Inventory HUD + 3.4.19
		inventoryprofilesnext: Inventory Profiles Next 1.10.10
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.24
			journeymap-api-fabric: JourneyMap API 1.20.2-1.9-fabric-SNAPSHOT
		languagereload: Language Reload 1.5.10+1.20.3
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 4.0.2
		libjf: LibJF 3.14.3
			libjf-base: LibJF Base 3.14.3
			libjf-config-commands: LibJF Config Commands 3.14.3
			libjf-config-core-v2: LibJF Config 3.14.3
			libjf-config-network-v0: LibJF Config: Network 3.14.3
			libjf-config-ui-tiny: LibJF Config UI: Tiny 3.14.3
			libjf-data-manipulation-v0: LibJF Data Manipulation 3.14.3
			libjf-data-v0: LibJF Data 3.14.3
			libjf-mainhttp-v0: LibJF MainHTTP 3.14.3
			libjf-translate-v1: LibJF Translate 3.14.3
			libjf-unsafe-v0: LibJF Unsafe 3.14.3
			libjf-web-v1: LibJF Web 3.14.3
		lithium: Lithium 0.12.1
		malilib: MaLiLib 0.18.1
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.4
		minihud: MiniHUD 0.30.2
		modernfix: ModernFix 5.17.0+mc1.20.4
		modmenu: Mod Menu 9.2.0-beta.2
		morechathistory: More Chat History 1.3.0
		moreculling: More Culling 1.20.4-0.24.0
			conditional-mixin: conditional mixin 0.3.2
			mixinsquared: MixinSquared 0.1.1
		notenoughanimations: NotEnoughAnimations 1.7.2
		notenoughcrashes: Not Enough Crashes 4.4.7+1.20.4
		org_jetbrains_annotations: annotations 13.0
		petowner: Pet Owner 1.8.6-1.20.2+
			midnightlib: MidnightLib 1.5.0
		plagueschattimestamps: Plague's Chat Timestamps 1.0.2+1.20
		reeses-sodium-options: Reese's Sodium Options 1.7.2+mc1.20.4-build.102
		rrls: Remove Reloading Screen 4.0.3+mc1.20.4-fabric
		servercore: ServerCore 1.5.0+1.20.4
			fabric-permissions-api-v0: fabric-permissions-api 0.3-SNAPSHOT
			org_yaml_snakeyaml: snakeyaml 2.2
			placeholder-api: Placeholder API 2.3.0+1.20.3
			space_arim_dazzleconf_dazzleconf-core: dazzleconf-core 1.3.0-M2
			space_arim_dazzleconf_dazzleconf-ext-snakeyaml: dazzleconf-ext-snakeyaml 1.3.0-M2
		servercountryflags: Server Country Flags 1.10.1
		showmeyourskin: Show Me Your Skin! 1.9.0+1.20.4
			cardinal-components-base: Cardinal Components API (base) 5.4.0
			cardinal-components-entity: Cardinal Components API (entities) 5.4.0
		skinlayers3d: 3d-Skin-Layers 1.6.3
		sodium: Sodium 0.5.8+mc1.20.4
		sodium-extra: Sodium Extra 0.5.4+mc1.20.4-build.116
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sspb: Sodium Shadowy Path Blocks 3.2.1
		starlight: Starlight 1.1.3+fabric.f5dcd1a
		tooltipfix: ToolTip Fix 1.1.1-1.20
		universalcraft: UniversalCraft 323
		viafabricplus: ViaFabricPlus 3.1.0
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			com_vdurmont_semver4j: semver4j 3.1.0
			com_viaversion_viabackwards-common: viabackwards-common 4.10.0-24w09a-SNAPSHOT
			com_viaversion_viaversion-common: viaversion-common 4.10.0-24w09a-SNAPSHOT
			de_florianmichael_classic4j: Classic4J 2.0.2
			io_jsonwebtoken_jjwt-api: jjwt-api 0.12.5
			io_jsonwebtoken_jjwt-gson: jjwt-gson 0.12.5
			io_jsonwebtoken_jjwt-impl: jjwt-impl 0.12.5
			net_jodah_expiringmap: expiringmap 0.5.10
			net_lenni0451_commons_httpclient: httpclient 1.4.1
			net_lenni0451_mcping: MCPing 1.4.0
			net_lenni0451_mcstructs-bedrock_forms: forms 1.2.0
			net_lenni0451_mcstructs-bedrock_text: text 1.2.0
			net_raphimc_minecraftauth: MinecraftAuth 4.0.0-SNAPSHOT
			net_raphimc_viaaprilfools: ViaAprilFools 2.0.11-SNAPSHOT
			net_raphimc_viabedrock: ViaBedrock 0.0.5-SNAPSHOT
			net_raphimc_vialegacy: ViaLegacy 2.2.22-SNAPSHOT
			net_raphimc_vialoader: ViaLoader 2.2.13-SNAPSHOT
			org_cloudburstmc_netty_netty-transport-raknet: netty-transport-raknet 1.0.0.CR1-SNAPSHOT
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_lz4_lz4-pure-java: lz4-pure-java 1.8.0
		vigilance: Vigilance 295
		vmp: Very Many Players 0.2.0+beta.7.139
		yet_another_config_lib_v3: YetAnotherConfigLib 3.3.2+1.20.4
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Sodium (sodium), 3d-Skin-Layers (skinlayers3d)

**Comment by MeeniMc** [comment]
I am using current versions of Sodium and SkinLayer3D and experienced no crash, so presumably that issue is stale.

**Comment by douira** [comment]
Closed as stale
