### ISSUE TITLE
crashes the game then rendering entity in world.

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2439]
### Bug Description

**When moving the entity with the piston, minecraft crashes, and so does the light. When putting a torch on the flying sand game crashes, as well as when breaking the block where above is a flying block game crashes**

### Reproduction Steps

**Setting the flare on flying sand
Destroying the block, but gravel on top
lifting the piston
piston**

### Log File

[2024-04-29-5.log](https://github.com/CaffeineMC/sodium-fabric/files/15152960/2024-04-29-5.log)

### Crash Report

[crash-2024-04-29_22.46.18-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/15152968/crash-2024-04-29_22.46.18-client.txt)

**Comment by Lolothepro** [comment]
install Indium

**Comment by ghost** [comment]
> install Indium

Not yet on 1.20.5. Everything worked without it on other versions.

**Comment by Lolothepro** [comment]
> > install Indium
> 
> Not yet on 1.20.5. Everything worked without it on other versions.

That's impossible, this crash clearly points to the fact that Indium is missing, so you'll have to wait for the release of Indium.

**Comment by ghost** [comment]
> That's impossible, this crash clearly points to the fact that Indium is missing, so you'll have to wait for the release of Indium.

Strange that indium worked on the new version. And why can't extensions be added to sodium so there are no extensions?

**Comment by Lolothepro** [comment]
> And why can't extensions be added to sodium so there are no extensions?

https://github.com/CaffeineMC/sodium-fabric/issues/5
https://github.com/CaffeineMC/sodium-fabric/pull/1851

**Comment by ghost** [comment]
> > And why can't extensions be added to sodium so there are no extensions?
> 
> #5 #1851

Got it, and thank you for your quick response. Now I know what the problem was
