### ISSUE TITLE
Custom Clouds?

### ISSUE THREAD

**Issue by BullSh0t** [jellysquid3/Sodium#244]
Optifine had a feature for custom clouds that's provided by a few resource packs out there. Without the custom clouds feature however, nothing appears in the sky, and kinda just makes the sky look sad. It's a small feature, but I'd greatly appreciate its incorporation

**Comment by jellysquid3** [comment]
As one of our core principles: Sodium is an optimization mod, not a features mod. In the future it is possible that other Fabric mods will step up to the plate to provide this functionality, but it's not being considered for integration with Sodium.
