### ISSUE TITLE
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!

### ISSUE THREAD

**Issue by NewMarcy** [jellysquid3/Sodium#2440]
### Bug Description

![e86209e49394ab08e6fa588dd20e8d2](https://github.com/CaffeineMC/sodium-fabric/assets/139100679/06b6509f-d039-4798-8962-808080c5751d)
1.20.1 乌托邦整合包
同行五个人 只有一个人有这种情况

### Reproduction Steps

当通过pcl2启动游戏窗口时 会弹出上述报错
求助

### Log File

[PCL 启动器日志.txt](https://github.com/CaffeineMC/sodium-fabric/files/15168822/PCL.txt)

### Crash Report

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15168825/latest.log)

**Comment by pajicadvance** [comment]
The log files you sent are empty files, please resend them. As for the error in the screenshot, try installing Minecraft in a different folder that's not under the control of another application.

**Comment by NewMarcy** [comment]
[PCL 启动器日志.txt](https://github.com/CaffeineMC/sodium-fabric/files/15182274/PCL.txt)

**Comment by NewMarcy** [comment]
[Uploading PCL 启动器日志.txt…]()
[Uploading latest.log…]()

**Comment by NewMarcy** [comment]
[Uploading latest.log…]()

**Comment by NewMarcy** [comment]
对于文件的上传失败 我很抱歉 
对于上述的启动时发生的问题
已经进行尝试并得到了解决
问题来源于简体与繁体的冲突

**Comment by NewMarcy** [comment]
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15182447/latest.log)

**Comment by NewMarcy** [comment]
[PCL 启动器日志.txt](https://github.com/CaffeineMC/sodium-fabric/files/15182448/PCL.txt)
