### ISSUE TITLE
crash caused by sodium

### ISSUE THREAD

**Issue by Serrenos** [jellysquid3/Sodium#2443]
### Reproduction Steps

it crashes at world generation!

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15179467/latest.log)

### Crash Report

[crash-2024-05-01_14.10.30-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/15179475/crash-2024-05-01_14.10.30-client.txt)

**Comment by Lolothepro** [comment]
caused by extra_details-common.mixins.json:client.sodium.ChunkBuilderMeshingTaskMixin
