### ISSUE TITLE
Allow particles to have translucent textures like they previously could

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2444]
### Request Description

Up until 1.13, particles in the particles.png texture file would render any translucent pixels as actually translucent in-game. When 1.14 split particles into individual texture files, any translucent pixels were either rendered at full opacity or invisible (https://bugs.mojang.com/browse/MC-144009), which persists into the present day. I assume there's some underlying rendering bug that causes this issue. Fixing it probably wouldn't cause any performance deficits (the game already handles translucent particles for stuff like campfires anyway), especially since particles for translucent blocks were themselves incorrectly rendered opaque until that was fixed in around 1.15-1.16 or so.

These bubbles render all translucent pixels within as fully opaque, for example: 
![2024-05-01_23 47 55](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/15bea8a7-fd6a-48d8-8f39-5da211689ead)
![2024-05-01_23 53 48](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/59d31714-3479-4842-82cb-5a78916aa0ab)
![2024-05-01_23 54 13](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/9bf06b1d-38d0-4750-a228-06b5a08a06c7)
![2024-05-01_23 54 28](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/dc516650-bdc3-4555-a9ec-0a2da99ac751)
all translucent pixels within as fully opaque, for example:

**Comment by jellysquid3** [comment]
Yes. This is intentional. Particles are only rendered with binary-alpha for performance reasons, since it doesn't need additional framebuffer reads on a rendering task that is historically bound on the fragment shader. Each particle type is rendered in a separate pass, so only particle types which need actual alpha-blending will use it.
