### ISSUE TITLE
Fix visual offset in block breaking/cracking animation

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2445]
### Request Description

Vanilla issue https://bugs.mojang.com/browse/MC-167836.

Much like #1316 and related, this is one of those subpixel offset graphical issues that become impossible to unsee once you know it's there. Since this is a graphical bug, it probably fits into the scope of things to fix. 1.15's rendering changes appear to be responsible for this bug, as 1.14 and earlier remain unaffected.

![2024-05-02_00 23 36](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/9223c81f-2842-4848-b2f3-290640cd6991)
![2024-05-02_00 23 47](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/3dd3a807-4e41-4371-a187-6b0a0fcca2be)

It may also be worth investigating if the visual outline box displayed when targeting blocks is also offset in the same way - I distinctly remember a bug during 1.15's development that implied their rendering is directly connected, as both of them (alongside the end portal/gateway effect), would render severely far away from where they should have.

**Comment by douira** [comment]
have you check if this is fixed by the same commit that also fixes the other, recently closed, issue you linked? https://github.com/CaffeineMC/sodium-fabric/commit/ea0172768a5da9907b5a5711160dc3984fafea83

**Comment by muzikbike** [comment]
It actually seems as though it might have, except for occasionally a few pixels (in the window, as opposed to the textures).
![2024-05-02_02 08 59](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/079ac5aa-6faf-45e1-a22f-5a8b374ab6ac)
![2024-05-02_02 10 33](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/6a02b050-13f9-41ff-b8db-1481e02179dd)
