### ISSUE TITLE
game crashes when loading the world

### ISSUE THREAD

**Issue by eightiescrime** [jellysquid3/Sodium#2449]
### Reproduction Steps

the game crashes immediately upon loading a modded world

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15184105/latest.log)

### Crash Report

[crash-2024-05-02_08.27.02-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/15184103/crash-2024-05-02_08.27.02-client.txt)

**Comment by MCRcortex** [comment]
remove extra_details mod
