### ISSUE TITLE
Cloud Height Option and Option to turn off the custom video settings menu

### ISSUE THREAD

**Issue by luka-nedeljkov** [jellysquid3/Sodium#245]
It would be cool if we can adjust the cloud height like we can in optifine. If possible i would also like to be able to turn off the custom video settings menu because I don't really like that it is changed

**Comment by TheMadHau5** [comment]
There is another mod (compatible with sodium) that achieves the same purpose called [Soaring Clouds](https://www.curseforge.com/minecraft/mc-mods/soaring-clouds), by Draylar.

**Comment by jellysquid3** [comment]
Not liking that the video settings menu has been changed is largely useless criticism. If you have feedback on how it can be improved, feel free to open a new issue with ideas. We're not providing an option to disable it.
