### ISSUE TITLE
1.20.6 crash

### ISSUE THREAD

**Issue by vsaucing** [jellysquid3/Sodium#2450]
### Bug Description

İ have the latest version of fabric, not with any other mods, crashes.

### Reproduction Steps

launch game
crash

### Log File

[2024-05-02-2.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/15185305/2024-05-02-2.log.gz)

### Crash Report

PolyMC version: 1.2.2-d12e3df4

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [2620:1ec:46::45, 2620:1ec:bdf::45, 13.107.213.45, 13.107.246.45]

textures.minecraft.net resolves to:
    [2620:1ec:46::45, 2620:1ec:bdf::45, 13.107.246.45, 13.107.213.45]

api.mojang.com resolves to:
    [2620:1ec:46::45, 2620:1ec:bdf::45, 13.107.246.45, 13.107.213.45]

Minecraft folder is:
D:/Yeni klasör (2)/instances/1.20.6/.minecraft

Java path is:
C:/Program Files/Eclipse Adoptium/jre-21.0.3.9-hotspot/bin/javaw.exe

Checking Java version...
Java is version 21.0.3, using amd64 architecture, from Eclipse Adoptium.

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  D:/Yeni klasör (2)/instances/1.20.6/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-freetype-natives-windows-arm64/3.3.3/lwjgl-freetype-natives-windows-arm64-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-freetype-natives-windows-x86/3.3.3/lwjgl-freetype-natives-windows-x86-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-freetype-natives-windows/3.3.3/lwjgl-freetype-natives-windows-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-glfw-natives-windows-arm64/3.3.3/lwjgl-glfw-natives-windows-arm64-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.3/lwjgl-glfw-natives-windows-x86-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.3/lwjgl-glfw-natives-windows-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-glfw/3.3.3/lwjgl-glfw-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-arm64/3.3.3/lwjgl-jemalloc-natives-windows-arm64-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.3/lwjgl-jemalloc-natives-windows-x86-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.3/lwjgl-jemalloc-natives-windows-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-jemalloc/3.3.3/lwjgl-jemalloc-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-natives-windows-arm64/3.3.3/lwjgl-natives-windows-arm64-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.3/lwjgl-natives-windows-x86-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-natives-windows/3.3.3/lwjgl-natives-windows-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-openal-natives-windows-arm64/3.3.3/lwjgl-openal-natives-windows-arm64-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.3/lwjgl-openal-natives-windows-x86-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.3/lwjgl-openal-natives-windows-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-openal/3.3.3/lwjgl-openal-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-opengl-natives-windows-arm64/3.3.3/lwjgl-opengl-natives-windows-arm64-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.3/lwjgl-opengl-natives-windows-x86-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.3/lwjgl-opengl-natives-windows-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-opengl/3.3.3/lwjgl-opengl-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-stb-natives-windows-arm64/3.3.3/lwjgl-stb-natives-windows-arm64-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.3/lwjgl-stb-natives-windows-x86-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.3/lwjgl-stb-natives-windows-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-stb/3.3.3/lwjgl-stb-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-arm64/3.3.3/lwjgl-tinyfd-natives-windows-arm64-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.3/lwjgl-tinyfd-natives-windows-x86-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.3/lwjgl-tinyfd-natives-windows-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl-tinyfd/3.3.3/lwjgl-tinyfd-3.3.3.jar
  D:/Yeni klasör (2)/libraries/org/lwjgl/lwjgl/3.3.3/lwjgl-3.3.3.jar
  D:/Yeni klasör (2)/libraries/com/github/oshi/oshi-core/6.4.10/oshi-core-6.4.10.jar
  D:/Yeni klasör (2)/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  D:/Yeni klasör (2)/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  D:/Yeni klasör (2)/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar
  D:/Yeni klasör (2)/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar
  D:/Yeni klasör (2)/libraries/com/mojang/authlib/6.0.54/authlib-6.0.54.jar
  D:/Yeni klasör (2)/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  D:/Yeni klasör (2)/libraries/com/mojang/brigadier/1.2.9/brigadier-1.2.9.jar
  D:/Yeni klasör (2)/libraries/com/mojang/datafixerupper/7.0.14/datafixerupper-7.0.14.jar
  D:/Yeni klasör (2)/libraries/com/mojang/logging/1.2.7/logging-1.2.7.jar
  D:/Yeni klasör (2)/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  D:/Yeni klasör (2)/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  D:/Yeni klasör (2)/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar
  D:/Yeni klasör (2)/libraries/commons-io/commons-io/2.15.1/commons-io-2.15.1.jar
  D:/Yeni klasör (2)/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  D:/Yeni klasör (2)/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar
  D:/Yeni klasör (2)/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar
  D:/Yeni klasör (2)/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar
  D:/Yeni klasör (2)/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar
  D:/Yeni klasör (2)/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar
  D:/Yeni klasör (2)/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar
  D:/Yeni klasör (2)/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar
  D:/Yeni klasör (2)/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar
  D:/Yeni klasör (2)/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar
  D:/Yeni klasör (2)/libraries/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar
  D:/Yeni klasör (2)/libraries/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar
  D:/Yeni klasör (2)/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  D:/Yeni klasör (2)/libraries/org/apache/commons/commons-compress/1.26.0/commons-compress-1.26.0.jar
  D:/Yeni klasör (2)/libraries/org/apache/commons/commons-lang3/3.14.0/commons-lang3-3.14.0.jar
  D:/Yeni klasör (2)/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  D:/Yeni klasör (2)/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar
  D:/Yeni klasör (2)/libraries/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar
  D:/Yeni klasör (2)/libraries/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar
  D:/Yeni klasör (2)/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.22.1/log4j-slf4j2-impl-2.22.1.jar
  D:/Yeni klasör (2)/libraries/org/jcraft/jorbis/0.0.17/jorbis-0.0.17.jar
  D:/Yeni klasör (2)/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  D:/Yeni klasör (2)/libraries/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar
  D:/Yeni klasör (2)/libraries/org/slf4j/slf4j-api/2.0.9/slf4j-api-2.0.9.jar
  D:/Yeni klasör (2)/libraries/net/fabricmc/intermediary/1.20.6/intermediary-1.20.6.jar
  D:/Yeni klasör (2)/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
  D:/Yeni klasör (2)/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
  D:/Yeni klasör (2)/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
  D:/Yeni klasör (2)/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
  D:/Yeni klasör (2)/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
  D:/Yeni klasör (2)/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar
  D:/Yeni klasör (2)/libraries/net/fabricmc/fabric-loader/0.15.9/fabric-loader-0.15.9.jar
  D:/Yeni klasör (2)/libraries/com/mojang/minecraft/1.20.6/minecraft-1.20.6-client.jar

Native libraries:

Mods:
  [❌] dynamic-fps-3.4.3+minecraft-1.20.5-fabric.jar (disabled)
  [❌] entity_model_features_fabric_1.20.5-2.0.2.jar (disabled)
  [❌] entity_texture_features_fabric_1.20.5-6.0.1.jar (disabled)
  [❌] entityculling-fabric-1.6.4-mc1.20.6.jar (disabled)
  [❌] fabric-api-0.97.8+1.20.6.jar (disabled)
  [❌] ferritecore-6.1.1-fabric.jar (disabled)
  [❌] krypton-0.2.7.jar (disabled)
  [❌] lithium-fabric-mc1.20.6-0.12.3.jar (disabled)
  [❌] sodium-extra-0.5.5+mc1.20.6-build.118.jar (disabled)
  [✔️] sodium-fabric-0.5.8+mc1.20.6

Params:
  --username  --version PolyMC --gameDir D:/Yeni klasör (2)/instances/1.20.6/.minecraft --assetsDir D:/Yeni klasör (2)/assets --assetIndex 16 --uuid  --accessToken  --userType  --versionType release

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms3072m, -Xmx3072m, -Duser.language=en]

Minecraft process ID: 380

May 02, 2024 10:49:18 AM org.multimc.EntryPoint parseLine
INFO: Using onesix launcher.
[10:49:31] [main/INFO]: Loading Minecraft 1.20.6 with Fabric Loader 0.15.9
[10:49:31] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[10:49:31] [main/INFO]: Loading 10 mods:
	- fabricloader 0.15.9
	   \-- mixinextras 0.3.5
	- java 21
	- minecraft 1.20.6
	- sodium 0.5.8+mc1.20.6
	   |-- fabric-api-base 0.4.40+80f8cf51b2
	   |-- fabric-block-view-api-v2 1.0.8+80f8cf51b2
	   |-- fabric-rendering-data-attachment-v1 0.3.46+73761d2eb2
	   |-- fabric-rendering-fluids-v1 3.1.3+2c869dedb2
	   \-- fabric-resource-loader-v0 1.0.4+18de49c6b2
[10:49:31] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Yeni%20klas%c3%b6r%20(2)/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[10:49:31] [main/INFO]: Compatibility level set to JAVA_17
[10:49:32] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 0 override(s) found
[10:49:32] [main/INFO]: Searching for graphics cards...
[10:49:33] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.9.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:217) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:252) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:124) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:39) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.9.jar:?]
	... 8 more
Caused by: java.lang.RuntimeException: Unexpected registry type 3, expected REG_SZ or REG_EXPAND_SZ
	at com.sun.jna.platform.win32.Advapi32Util.registryGetStringValue(Advapi32Util.java:774) ~[jna-platform-5.14.0.jar:?]
	at com.sun.jna.platform.win32.Advapi32Util.registryGetStringValue(Advapi32Util.java:744) ~[jna-platform-5.14.0.jar:?]
	at com.sun.jna.platform.win32.Advapi32Util.registryGetStringValue(Advapi32Util.java:718) ~[jna-platform-5.14.0.jar:?]
	at oshi.hardware.platform.windows.WindowsGraphicsCard.getGraphicsCards(WindowsGraphicsCard.java:83) ~[oshi-core-6.4.10.jar:?]
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getGraphicsCards(WindowsHardwareAbstractionLayer.java:87) ~[oshi-core-6.4.10.jar:?]
	at me.jellysquid.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdaptersCrossPlatform(GraphicsAdapterProbe.java:44) ~[sodium-fabric-0.5.8+mc1.20.6.jar:?]
	at me.jellysquid.mods.sodium.client.compatibility.environment.probe.GraphicsAdapterProbe.findAdapters(GraphicsAdapterProbe.java:28) ~[sodium-fabric-0.5.8+mc1.20.6.jar:?]
	at me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:11) ~[sodium-fabric-0.5.8+mc1.20.6.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160) ~[fabric-loader-0.15.9.jar:?]
	... 8 more
İşlem şu kod ile bitti: 1.
PolyMC: Log upload triggered at: 02 May 2024 10:49:59 +0300
PolyMC: Log uploaded to: https://0x0.st/XXS_.txt
Clipboard copy at: 02 May 2024 10:50:05 +0300

**Comment by rilakuma123** [comment]
Why are you using PolyMC instead of Prism Launcher? :/

**Comment by yamayaki1** [comment]
> Why are you using PolyMC instead of Prism Launcher? :/

The crash is probably not caused by using PolyMC or any other launcher but rather invalid data in the Windows Registry.

**Comment by Felix14-v2** [comment]
> Why are you using PolyMC instead of Prism Launcher? :/

Why they shouldn't? Does any part of the report indicate the launcher's fault?

**Comment by rilakuma123** [comment]
Are you not aware of PolyMC's hostile takeover? I was expressing my concern for the original poster who may not have known to switch to Prism.

**Comment by vsaucing** [comment]
Prism is not working for me @rilakuma123

**Comment by yamayaki1** [comment]
@MuhammedEmirArtan What version of Windows are you using?

**Comment by vsaucing** [comment]
7 lmao
i know its bad but i have extended kernel

**Comment by yamayaki1** [comment]
I did some testing and the crash does not seem to be directly related to using older versions of Windows such as Windows 7.

**Comment by pajicadvance** [comment]
Just to test something out, can you install Minecraft to a different directory where the full path doesn't contain non-standard characters (ö in this case) and try again?

**Comment by jellysquid3** [comment]
This problem is now tracked with #2498.
