### ISSUE TITLE
1.20.6 Spyglass bug

### ISSUE THREAD

**Issue by frosthuuund** [jellysquid3/Sodium#2452]
### Bug Description

Spyglass zoom and unzoom with Sodium installed causing chunk unloading.

### Reproduction Steps

Install 1.20.6 and latest version of Sodium from Modrinth.
Set your ingame FOV to the "Quake Pro"
Create a new world with seed `-1399078040570737153` with Creative game mode and enabled console cheats.
Set yourself in the fly mode and execute this command `/teleport @s -11 160 -15 154.8 9.1`.
Look around and wait until all chunks in your sight radius will be loaded.
Give yourself a spyglass.
Execute `/teleport @s -11 160 -15 154.8 9.1` again.
Zoom into a spyglass and do not change your view angle in that time.
Wait 5 seconds.
Unzoom.
Observe the bug.

The chunks will be unloaded until camera angle change or a `major tick update`.
![spyglass](https://github.com/CaffeineMC/sodium-fabric/assets/168279382/8ffe6645-bd64-4721-8d62-80f4d7e09152)

### Log File

Not applicable.

### Crash Report

Not applicable.

**Comment by MeeniMc** [comment]
can replicate in 0.5.8+1.20.6, this is also present in 0.6, 0.5.8+1.20.4.

**Comment by jellysquid3** [comment]
This is probably just the result of the fact that we aren't marking the scene as needing updates when the viewport changes. Someone else may find it an easy thing to fix.

**Comment by douira** [comment]
Closed by https://github.com/CaffeineMC/sodium/pull/2617
