### ISSUE TITLE
Allow retexturing of UI elements in Sodium's video settings menu

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2453]
### Request Description

The graphics displayed in Sodium's video settings menu for things like buttons, tabs, sliders, section backgrounds and on/off toggles appear to be completely hardcoded, and not tied to any texture files. As someone developing a resource pack, this means that I can't add my own textures to make Sodium's menu fit in well with my own designs. It'd be preferable if these were controlled by texture files instead of being generated by code, such that resource packs can change them, especially given that 1.20.5 makes many previously-hardcoded vanilla graphics (scroller background, menu backgrounds, etc.) customizable via resource packs.
![2024-05-02_18 05 53](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/ac8a833c-30c3-46f4-b774-baade0c5d078)

**Comment by Felix14-v2** [comment]
> this means that I can't add my own textures to make Sodium's menu fit in well with my own designs

Actually you can do that using shaders in your resourcepack, and there are some packs that already do this. For example:
https://modrinth.com/resourcepack/modrinth-gui/gallery

**Comment by muzikbike** [comment]
Perhaps, but a way to do this intuitively with texture files rather than jumping through shader code hoops would be much more resource pack designer friendly.

**Comment by jellysquid3** [comment]
The user interface does not use texturing, rather all the graphics are composed with vectors and a predefined color scheme. We could, at most, provide a way to alter the color scheme via a special text file in the resource pack.

But really, I don't want people styling the video settings screen with resource packs. We are not allowed to brand the game in any other way than the Video Settings screen, and allowing modpacks/servers/etc to easily manipulate it is asking for trouble.
