### ISSUE TITLE
Allow fast leaves to cull the faces of other blocks

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2456]
### Request Description

Leaves now correctly cull each other in fast graphics. I remember in prior versions of vanilla that leaves would also cull other blocks such as full solid blocks, but this does not happen here. We could squeeze out just a bit more performance if logs and such were culled by the surrounding leaves in forests in fast graphics.

![2024-05-02_18 58 10](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/02ca2462-50cd-4a65-8478-4deca46e1aae)

**Comment by Lolothepro** [comment]
Note: https://bugs.mojang.com/browse/MC-179383
