### ISSUE TITLE
Cull chorus plants against chorus plants/flowers

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2458]
### Request Description

Much like #937, this is another vanilla issue Mojang seems to not want to fix for unknown reasons (https://bugs.mojang.com/browse/MC-249693).

Chorus plant blocks explicitly specify cullface for all the faces you'd expect them to, yet in practice faces are only ever culled against the end stone they grow out of - the faces between multiple plant blocks, or where the plant attaches to the flower - are always rendered regardless, which can amount to hundreds of unneeded faces being rendered. Implementing proper culling behaviour here would probably amount to a nontrivial increase in performance on generated end islands.

![2024-05-03_02 15 48](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/e54f29c5-0052-4a44-81d7-ffae90518fd8)
![2024-05-03_02 15 52](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/5070fbd3-c754-449f-a5ff-5244a02ccfa8)

**Comment by jellysquid3** [comment]
As discussed elsewhere, fixing these issues is likely not possible with reasonable resource pack/mod compatibility unless a new hidden surface elimination algorithm is implemented which works with the geometry itself (rather than comparing the code-specified cull shapes.)
