### ISSUE TITLE
Cull sugar cane against other blocks of sugar cane when using custom models with cullface

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2461]
### Request Description

The same idea as #937 and #2458, but only visible when using a custom resource pack since vanilla's sugar cane is a cross model. A test pack can be found attached to https://bugs.mojang.com/browse/MC-248964.

Since cullface is specified for the top and bottom of sugar cane in the test pack, it'd be expected that they would cull against other sugar cane blocks, but that doesn't happen. The model correctly culls against solid blocks above or below, however.

![2024-05-03_22 34 04](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/325684a5-26a6-48e1-85c2-2b103b6a1228)
![2024-05-03_22 34 19](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/9381066b-011f-41bd-9051-583c347a66c7)
![2024-05-03_22 34 28](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/71052d52-50e8-4599-95f4-fad41368f610)

**Comment by jellysquid3** [comment]
As discussed elsewhere, fixing these issues is likely not possible with reasonable resource pack/mod compatibility unless a new hidden surface elimination algorithm is implemented which works with the geometry itself (rather than comparing the code-specified cull shapes.)
