### ISSUE TITLE
Cull redstone wire against other redstone wires with custom models

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2462]
### Request Description

Another one in the #937/#2458/#2461 family, this concerns the redstone wire block (https://bugs.mojang.com/browse/MC-269449).

I have a resource pack that assigns custom models to redstone wire such that it fits the visual outline box. cullface arguments are specified for the parts of the model that connect to adjacent blocks, however for whatever reason these only cull against things such as solid blocks, and are not culled against adjacent wires, which is the majority of cases, meaning that a bunch of undesirable faces get rendered, which can't be good for performance. If there's a way to cull these faces, things would probably be better performance-wise.

![2024-05-03_22 36 06](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/f95e4187-ac35-47f2-a230-e80a4eb90268)
![2024-05-03_22 36 35](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/9c0f9d27-513f-423d-acbe-c50c42fd2921)
![2024-05-03_22 37 09](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/4efb3ad0-e6b2-4349-ada8-d5460a72206a)

**Comment by Felix14-v2** [comment]
Shouldn't all these culling issues be reported to the MoreCulling mod?

**Comment by TheNukeLore** [comment]
I don’t think sodium deals with much resource related stuff such as textures and models, that’s often left for other mods, sodium also generally only fixes graphical issues if it directly aims to optimize that area of the code

**Comment by jellysquid3** [comment]
As discussed elsewhere, fixing these issues is likely not possible with reasonable resource pack/mod compatibility unless a new hidden surface elimination algorithm is implemented which works with the geometry itself (rather than comparing the code-specified cull shapes.)
