### ISSUE TITLE
CIT (custom item texture) 

### ISSUE THREAD

**Issue by Gray-Falcon** [jellysquid3/Sodium#2465]
### Request Description

we need cit (custom item texture), optifine have it, so i think sodium should have it too, it is essential for more advanced models!

pls add it

**Comment by douira** [comment]
This is out of scope for sodium, please use the appropriate third-party mod for this feature. Sodium is not a kitchen sink mod like optifine.

**Comment by jellysquid3** [comment]
https://modrinth.com/mod/cit-resewn
