### ISSUE TITLE
[Crash] Sodium crashing the game in the End dimension

### ISSUE THREAD

**Issue by Anonyku05** [jellysquid3/Sodium#2469]
### Bug Description

The game works fine but some seconds into the End and my game suddenly crash, seems to be an issue with another mod but can't figure out wich one since i have over 200 mods

### Reproduction Steps

Have Sodium installed with another mod that is causing the issue (don't know wich one)

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15214079/latest.log)

### Crash Report

[crash-2024-05-05_17.47.11-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/15214082/crash-2024-05-05_17.47.11-client.txt)

EDIT:
Found where the issue came from, it was from a mod called fluid void fading.

**Comment by jellysquid3** [comment]
The problem is with [Fluid Void Fading](<https://modrinth.com/mod/fluidvoidfading>)... it has injected code into Sodium's renderer and their mod is accessing functions that don't exist.
