### ISSUE TITLE
Fix translucent items and experience orbs rendering over block outlines

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2475]
### Request Description

This is another translucency sorting issue which is not resolved by the Fabulous! graphics setting, whether that be in vanilla or Sodium. Mojang also doesn't appear to plan to fix this at all (https://bugs.mojang.com/browse/MC-262088).

Experience orbs and dropped translucent items will completely block the rendering of the wireframe hitbox displayed when targeting blocks. It'd be expected that the outline would remain visible through the item/orb, but this is not the case regardless of the current graphics settings. I've checked the current development build for translucency sorting as well, but since it exclusively focuses on world geometry it has no effect on entities.

Since Mojang don't appear to plan on resolving this problem, would it be within the realms of graphics issues Sodium could provide a fix for?

![2024-05-05_23 27 48](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/c4ca7381-b360-441a-b7be-27f4e086ef5d)

**Comment by mrjasonn** [comment]
I'd personally suggest just not to fix this, as Mojang has marked this problem as Plausible on the bug tracker (which means it is not definitely a bug) and they are not willing to fix this. Best to just parity with vanilla in this case in my views.
