### ISSUE TITLE
Fix particle/cloud/translucent entity rendering between two transparent world layers

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2476]
### Request Description

Here's another translucency sorting issue, exclusive to Fabulous! graphics, that persists in both vanilla and Sodium. Whether these are even within the mod's scope at this point I don't know, so do inform me if I should stop reporting things like this.

The ticket for this issue is https://bugs.mojang.com/browse/MC-186538.

For the translucent item test case, you'll want a setup like this:
![2024-05-05_23 47 41](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/0a83a32e-2d88-43b2-8bec-961dbc417f81)

Look at the item through the lighter window - you'll notice that it's barely visible.
![2024-05-05_23 47 48](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/b4c14b91-bb13-46c7-a990-21b2adb7e520)

This issue is not present when you're not looking at the item through a translucent layer.
![2024-05-05_23 47 51](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/02ec3a26-a1eb-4767-b1d7-56e41c29407a)

Disabling Fabulous! graphics also gets rid of this issue, but by replacing it with a different one:
![2024-05-05_23 48 20](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/48524680-9ef7-4876-9492-81aaabcaca46)

**Comment by TheNukeLore** [comment]
Doing something to fix this would likely require an oit solution, said solution often looks sub par compared to ground truth(what vanilla and the sodium development branches have) which cant be applied to non blocks.

**Comment by jellysquid3** [comment]
This is not possible to solve unless Fabulous mode is completely reworked to store more than one sample in the framebuffer. There are ways to accomplish this, such as with per-pixel linked lists, but the GPU requirements (both in compute and memory) are too significant... hence why it only stores one sample.

Sure, you could use other order-independent approaches, but their results are sub-par compared to what people expect, and it would make mod/hardware compatibility even harder. So it's not something we're interested in doing.
