### ISSUE TITLE
Fix world border rendering in Fabulous! graphics

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2479]
### Request Description

I have no idea why, but the world border appears to render much darker in Fabulous! graphics as opposed to Fancy graphics (https://bugs.mojang.com/browse/MC-187669). For example:
![2024-05-06_13 22 26](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/d46cda8e-0ab3-4737-b5a4-a088cdc95736)

Same spot, but Fancy graphics, which is how it should look in all modes:
![2024-05-06_13 22 38](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/56a3d1dc-46c0-4fac-9b5f-4fc1982cb4aa)

There are further issues that can be seen from outside, such as https://bugs.mojang.com/browse/MC-186241, where faces visible on top of other faces appear to additively "blend" where they intersect (see also #2474). Compare:
![2024-05-06_13 23 01](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/e379c808-c7d6-47b2-b89a-57c3128590f3)
![2024-05-06_13 23 13](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/544b9dae-79c4-413b-8841-85ae7cf303be)

Would sodium be able to fix these or would they also be out of scope?

**Comment by jellysquid3** [comment]
We do not intend to support Fabulous mode in any capacity, and will not go out of our way to fix issues with it.
