### ISSUE TITLE
Animated Paintings don't Work

### ISSUE THREAD

**Issue by ben9583** [jellysquid3/Sodium#248]
### Expected Behavior
When a painting with multiple frames from any resource pack is added and placed into the game, the series of images from the resource pack and mcmeta animation file create an animated painting.

### Actual Behavior
When you place an animated painting in game, it shows the first frame, but does not progress through and is static.

### Reproduction Steps
1. Create a vertical strip of images and save as the name of a Minecraft painting (ex: pigscene.png)
2. Create an mcmeta file with any sort of animation configuration, as shown from the Minecraft wiki, and name it to the name of the painting followed by .mcmeta (ex: pigscene.png.mcmeta)
3. Place this into a resource pack's texture/painting folder and load the resource pack in game.
4. Place paintings in game until you get to the modified painting.

### Attachments
Example Image (24 frames):
![match](https://user-images.githubusercontent.com/16968917/90039569-abd25d80-dc7b-11ea-86f6-0042fe578114.png)

Example mcmeta:
{
    "animation": {
        "frametime": 2
    }
}

Output on Vanilla:
![expected](https://user-images.githubusercontent.com/16968917/90039424-73cb1a80-dc7b-11ea-83e0-ffff915adcc9.gif)

Output on Sodium:
<img width="400" alt="actual" src="https://user-images.githubusercontent.com/16968917/90039457-82193680-dc7b-11ea-82e1-3fe492d5b602.png">

- OS: MacOS Catalina 10.15.6
- Java Version: 1.8.0_74
- CPU: Intel i9-9980HK 8-core 2.4GHz (up to 5.0GHz)
- GPU: AMD Radeon Pro 5500M 8GB VRAM

**Comment by CalXee** [comment]
Does disabling "Animate Only Visible Textures" fix this issue?

**Comment by ben9583** [comment]
@CalXee Yes, the paintings animate as normal with the option disabled.
