### ISSUE TITLE
Fix rendering order for emissive entity textures

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2480]
### Request Description

If an entity with glowing eyes (tested with endermen, spiders and phantoms - I have not checked breezes or the ender dragon yet) has the invisibility effect, their eyes will still render. An issue arises if there are entities, entity-rendered blocks, translucent world geometry or probably a few other things behind said entity, since they will render on top of the eyes despite being physically further away.

This affects all three vanilla graphics settings.

Example screenshots:
Enderman (https://bugs.mojang.com/browse/MC-218015):
![2024-05-06_13 53 59](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/25e857dd-1f60-40e3-acd8-d9534ad70be9)
![2024-05-06_13 54 18](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/5eb9aba8-243a-46c8-ad93-4c59b3d078f8)
![2024-05-06_13 55 01](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/d26214e4-ab1a-4b4a-bfd1-b45b013e6b40)

Spider (https://bugs.mojang.com/browse/MC-210734):
![2024-05-06_13 56 30](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/6684d0cd-fea9-4649-a352-1399f8a01c48)
![2024-05-06_13 56 40](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/c117bb64-843b-4960-b361-2298c5deac8f)

Phantom:
![2024-05-06_13 58 19](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/43b2498b-ec2b-4903-a3a8-50a5bf8a34bf)
![2024-05-06_13 58 21](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/b1e7285a-c9f1-470d-879d-b965fa17078d)

**Comment by mrjasonn** [comment]
I would suggest not to change this, as some Minecraft maps and Minecraft servers may rely on this to provide a good experience, and to also keep vanilla parity as it's also good to keep some things (such as this would be good) to be looking vanilla.

**Comment by TheNukeLore** [comment]
I doubt this would be in scope for sodium as it often doesn’t directly touch entity rendering for situations like this.
