### ISSUE TITLE
Sodium conflicts with Create mod

### ISSUE THREAD

**Issue by AmokDev** [jellysquid3/Sodium#2483]
### Bug Description

Sodium conflicts with create mod

https://modrinth.com/mod/create-fabric/versions

![2024-05-06_17 26 53](https://github.com/CaffeineMC/sodium-fabric/assets/114482884/e3405103-b735-4030-9d2f-dc39c0e3b075)

### Reproduction Steps

just join the game with https://modrinth.com/mod/create-fabric/versions and sodium

### Log File

https://mclo.gs/f665opQ

### Crash Report

nothing

**Comment by pajicadvance** [comment]
You don't even have Sodium installed according to the log?

**Comment by AmokDev** [comment]
> You don't even have Sodium installed according to the log?

Sorry, I copied the link to the wrong log

Here is the log with sodium  https://mclo.gs/aTIEPko

**Comment by Poopooracoocoo** [comment]
This is issue 5. Install Indium.

**Comment by AmokDev** [comment]
> This is issue 5. Install Indium.

Thanks bro, it works!!
