### ISSUE TITLE
Fix visual issues with objects behind translucent entities in Fabulous! graphics

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2484]
### Request Description

Another one of the many translucency and rendering sorting issues that don't go away in Fabulous! graphics. There's a handful of entities affected by this:

- Wither armor (https://bugs.mojang.com/browse/MC-190203):
![2024-05-07_15 37 34](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/62072e26-e2f7-4ae9-90b0-296378a20fbc)

- Charged creepers (https://bugs.mojang.com/browse/MC-190203):
![2024-05-07_15 38 10](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/87e93616-0deb-4f2a-ab1e-11008d7d00f9)
![2024-05-07_15 39 10](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/eddfe19d-cb5e-409d-9d32-20f4bc25e058)

- Breezes (https://bugs.mojang.com/browse/MC-190203):
![2024-05-07_15 41 34](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/13fa4ecc-1801-46fd-b6b7-74059a0a18ac)

- Wind charges (https://bugs.mojang.com/browse/MC-190203):
![2024-05-07_15 41 59](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/d96e38d6-29b9-4e5d-8480-8c2cf1691c2c)

- Shulker bullets (https://bugs.mojang.com/browse/MC-168653):
![2024-05-07_15 44 54](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/e9570bc8-ee62-45fe-a47e-19ddd8be06b0)

- Vexes and allays (https://bugs.mojang.com/browse/MC-262090):
![2024-05-07_15 39 41](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/538c11fe-8fc1-4ee1-829e-64087365dc8a)
![2024-05-07_15 39 56](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/4c4d3dfa-4c98-41d3-a0d1-ee831f76f72a)

**Comment by IMS212** [comment]
This is really not suitable for Sodium. Fabulous uses texture blending to fix different-draw translucency; it doesn't fix the much harder problem core to Minecraft of entities not having ordered translucent draws.

**Comment by jellysquid3** [comment]
As was already stated, Fabulous mode only fixes problems _between_ render passes, not within them. And it's impossible to actually resolve that without completely re-architecting entity rendering to use an order-independent approach, because geometry sorting can't solve all of these problems.
