### ISSUE TITLE
Don't hide the skybox in Spectator mode when inside water, lava or powder snow

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2485]
### Request Description

Sodium hides the sky and sun/moon if the camera is subject to water, lava or powder snow fog as a fix for https://bugs.mojang.com/browse/MC-152504. However, Spectator mode isn't intended to be "obscured" by things as the other game modes are - for example, you can see through blocks when inside them unlike in Creative/Survival, and fog distance is considerably increased when inside water or lava compared to other game modes. It would probably make sense to only have this hiding fix apply to creative/survival/adventure modes.

![2024-05-07_22 43 10](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/c6e73d13-3ba7-4dcc-8817-22028272eef1)
![2024-05-07_22 43 15](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/32b5c577-623e-43ff-bf5d-f16bc90a563c)
![2024-05-07_22 44 55](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/eeb41337-22dd-4654-9542-2b80617f868c)
![2024-05-07_22 45 00](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/3e1c34a6-7c89-423d-bf81-956a0cd9823a)
![2024-05-07_22 45 40](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/2f5f7657-a51f-4103-9b7c-4aa8d21c4480)
![2024-05-07_22 45 42](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/b749f274-bdd0-4eb5-8eee-c8703d35cd26)

The best fix for this would probably be to disable water, lava and powder snow fog entirely in Spectator mode - that way, there'd be no obstructions at all and you'd be able to see the sky as though you were in any other block.

**Comment by douira** [comment]
Wouldn't disabling fog make it looks significantly different?

**Comment by muzikbike** [comment]
Yes, but since the point of Spectator mode is to not have visual hindrances such as the suffocation overlay or on-fire effect displayed on screen I doubt this would actually matter.

**Comment by douira** [comment]
Vanilla's spectator also doesn't remove fog

**Comment by muzikbike** [comment]
True. I'm not picky on how this is fixed, if it's decided it should even be fixed at all.

**Comment by jellysquid3** [comment]
The entire reason this patch exists is to deal with the way that fog interacts with the skybox. Since Minecraft doesn't fully remove the fog, even in spectator mode, it doesn't make sense to change the behavior as you've requested.
