### ISSUE TITLE
Fix Z-fighting on enchanted models with coplanar intersecting faces

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2487]
### Request Description

This issue (https://bugs.mojang.com/browse/MC-262933) is much the same as #2454, and I assume could be fixed in a similar way - compute some outer shape for the model and apply the enchantment glint to that, rather than just throwing it on the textures directly.

The easiest way to reproduce this without a resource pack is to enchant a wall, then observe it from below - despite the texture being mapped identically in the area of intersection, Z-fighting arises nonetheless.

![2024-05-09_10 43 46](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/ed4bdd44-0f95-4c1b-9b3c-a2a23d6a2ccd)
![2024-05-09_10 43 54](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/e2880edc-ec34-40a4-8ad8-9ec3d780edba)
![2024-05-09_10 43 59](https://github.com/CaffeineMC/sodium-fabric/assets/52297970/7ef82438-1a9a-4d7b-ae8b-c9fa27158c97)

**Comment by jellysquid3** [comment]
Minecraft uses a VertexConsumer proxy to generate new geometry for the glint overlay, and it does this at render time so we don't have any opportunity to bake. It would probably be to slow/error prone to try and de-duplicate geometry as well. The only solution in my mind is to stop generating geometry and apply the effect directly in the shader, which the game doesn't do already _for some reason._

**Comment by jellysquid3** [comment]
I'm not going to rule this as "out of scope" quite yet, since fixing this inherently means solving a major performance issue that does appear in the real world.

But probably we should merge #2487 and #2486, since they're symptoms of the same problem (inappropriately using additional geometry.)

**Comment by jellysquid3** [comment]
Closing in favor of #2497 since the issues you have reported about enchantment glint are fundamentally the same problem.
