### ISSUE TITLE
Sodium breaks game's particle managment

### ISSUE THREAD

**Issue by frosthuuund** [jellysquid3/Sodium#2488]
### Bug Description

Sodium discounts teleport events in particle management, which causing emitting particles in unloaded chunks.

Below is the "real world" example with Terralith mod which reveals the problem.

![particle2](https://github.com/CaffeineMC/sodium-fabric/assets/168279382/789008c6-489c-4890-bda0-68882cc19cad)

With the mods that dramatically increasing the render distance this might be a big problem, since particles could be emitted from the very big distance.
![particle](https://github.com/CaffeineMC/sodium-fabric/assets/168279382/3a13a0ea-7ae3-416a-a29c-6f9c876b446a)

### Reproduction Steps

Install 1.20.6, Sodium, BetterF3 to track of particles, and Cloth Config as a dependency to BetterF3.
Set render distance to 32. 
Create a superflat world with "The Void" template.
Place a campfire in center of the stone platform.
Teleport away with command `/teleport @s ~ ~ ~1000`
With F3 you can observe that the game is processing particles, but we are far enough from the unloaded campfire.
This behavior doesn't happen when we move away from the campfire chunk.

![bug](https://github.com/CaffeineMC/sodium-fabric/assets/168279382/c8e586c7-9924-438f-9740-b1821d7e818d)

**Expected behavior:**
In this case the game should not emit new particles.

### Log File

Not applicable

### Crash Report

Not applicable

**Comment by Lolothepro** [comment]
https://bugs.mojang.com/browse/MC-265639

**Comment by frosthuuund** [comment]
Is this a real vanilla issue? Without sodium campfire won't emit new particles.
