### ISSUE TITLE
Game Doesnt Not Launch crashes

### ISSUE THREAD

**Issue by EnvixityB02** [jellysquid3/Sodium#2490]
### Bug Description

game crashes instantly after sodium tries to apply the nvidia gpu patch

### Reproduction Steps

Use Trailer Recreation Modpack On Modrinth App And Launch

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15274019/latest.log)

### Crash Report

[crash-2024-05-10_12.41.52-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/15274016/crash-2024-05-10_12.41.52-client.txt)

**Comment by Lolothepro** [comment]
`Critical injection failure: LVT in net/minecraft/class_312::method_1598(JDD)V has incompatible changes at opcode 297 in callback mixins.recording.replaymod.json:MixinMouseHelper from mod (unknown)->@Inject::handleReplayModScroll(JDDLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;DI)V.`

**Comment by EnvixityB02** [comment]
> `Critical injection failure: LVT in net/minecraft/class_312::method_1598(JDD)V has incompatible changes at opcode 297 in callback mixins.recording.replaymod.json:MixinMouseHelper from mod (unknown)->@Inject::handleReplayModScroll(JDDLorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;DI)V.`

i'll try removing replaymod ig

**Comment by EnvixityB02** [comment]
nope that didnt fix it

**Comment by Poopooracoocoo** [comment]
> nope that didnt fix it

You likely have multiple issues. Running a 1.20.1 version of ReplayMod on 1.20.2 was just the one revealed in your log and crash report. For support, please head over to the [Discord server](https://jellysquid.me/discord).

**Comment by jellysquid3** [comment]
![image](https://github.com/CaffeineMC/sodium-fabric/assets/1363084/0616e11f-4e58-4e52-b803-9d56c7b6d532)
