### ISSUE TITLE
Some textures are different between Minecraft Vanilla and Sodium with the "Tooniverse Basic" resource pack.

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2491]
### Bug Description

Some textures are different between Minecraft Vanilla and Sodium with the "Tooniverse Basic" resource pack.

ie:

Vanilla:

![2024-05-10_23 00 55](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/e3d19918-0360-4d13-85c6-974977f92a76)

Sodium:

![2024-05-10_22 59 29](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/87bc78ca-e3f6-4b5d-82ed-0503a5d599c6)

### Reproduction Steps

Install the resource pack and compare with Minecraft Vanilla

### Log File

https://mclo.gs/ZcAbiPx

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15280019/latest.log)

### Crash Report

[crash-2024-05-10_23.08.53-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/15280030/crash-2024-05-10_23.08.53-client.txt)

**Comment by muzikbike** [comment]
Do these textures contain translucent pixels that are being rendered as opaque? I know vanilla's handling of translucent pixels differs between cutout and cutout_mipped for some reason (https://bugs.mojang.com/browse/MC-264150), so there is a possibility that something being rendered invisible in vanilla is not with Sodium.

**Comment by jellysquid3** [comment]
Fixed with https://github.com/CaffeineMC/sodium-fabric/commit/4bcdf598dbf7a3300f1ef64cfbf73c7a93db4327.
