### ISSUE TITLE
Sodium Version 1.20.6 falsely states that the graphics card driver is not up to date

### ISSUE THREAD

**Issue by smallworldinMC** [jellysquid3/Sodium#2495]
### Bug Description

Graphics card driver version is up to date but still reporting errors and crashes

### Reproduction Steps

Crash after launching Minecraft version 1.20.6
 with Intel graphics driver version 15..53.33.5161

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15284772/latest.log)

### Crash Report

[游戏崩溃前的输出.txt](https://github.com/CaffeineMC/sodium-fabric/files/15284777/default.txt)

**Comment by Fnige** [comment]
Known issue, see https://github.com/CaffeineMC/sodium-fabric/issues/2432#issuecomment-2098957741 for a workaround
