### ISSUE TITLE
Fix flickering player model issue commonly seen when using elytra

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2496]
### Request Description

This should be a familiar vanilla bug to anyone who flies in third person a lot - the player model pulses in and out of existence for frames at a time (https://bugs.mojang.com/browse/MC-111516).

RandomPatches (which has been discontinued for many years) implemented a fix for this in the following commit: https://github.com/TheRandomLabs/RandomPatches/commit/e156d3b099a009e642be009861849b27c753af19

The issue appears to arise from the inverse cosine function receiving an input value above 1.0, which obviously has no real solution, causing the player model to derender in these cases. This problem could be fixed by always clamping the input value to between valid bounds.

**Comment by jellysquid3** [comment]
Sodium will not fix every rendering issue that exists, unless it just so happens to be in code we already replace. This is so out of our way that it doesn't make sense to try and fix it.

**Comment by jellysquid3** [comment]
In the future, please ask on our Discord server before opening future requests for enhancements/features. Many of the things you have opened issues for in the past week are categorically out of scope.

**Comment by MeeniMc** [comment]
A fix for this is available in mod Debugify.
