### ISSUE TITLE
Mention Indium in the wiki

### ISSUE THREAD

**Issue by xxdemiigod** [jellysquid3/Sodium#2499]
### Request Description

This is less of a problem and more so just a suggestion for the wiki itself because it was really frustrating trying to figure this out.

**Problem:** Indium isn't mentioned in the wiki or anywhere that I could find on the FAQ or bug pages. I only found it after joining the Discord server.

My game kept closing before it could even load, so I was trying to figure out what was wrong. I spent an hour searching through the entire wiki, read through the modrinth site multiple times, looked through the FAQ, and eventually had to Google what mods were compatible with Sodium. Eventually, Apex Hosting's site told me that Sodium was incompatible with the Fabric Rendering API, and I figured out that was my issue. But it also doesn't list a fix.
![Screenshot 2024-05-12 110456](https://github.com/CaffeineMC/sodium-fabric/assets/99450721/b7b8f02e-778a-4be1-94c3-c0712fc6d4d5)

I spent an hour seeing if I could find anything before joining the discord server. And only in the drop down in the support forum does it state "If you're using mods that add OptiFine features, such as Continuity for connected and emissive textures, make sure that you have Indium installed."

**What I'd like to be changed:** Could you please add the installation of Indium somewhere either in the wiki or on the main page? Or at least mention it somewhere that isn't only in the Discord? I understand that it does serve its purpose to have it in the Discord primarily, and that it's not a necessary change. But it would've saved so much time if it was somewhere online.

**Comment by mrjasonn** [comment]
Sodium 0.6 will include official support for the Fabric Rendering API anyways, which will probably release soon with Minecraft 1.21

**Comment by douira** [comment]
It's easy to add a sentence to the wiki, idk how to make a PR to the wiki though.

**Comment by Adidiii** [comment]
1.21 is out right now. Expect Sodium 0.6 to release soon.

**Comment by Useott** [comment]
> 1.21 is out right now. Expect Sodium 0.6 to release soon.

cool!

**Comment by jellysquid3** [comment]
The Modrinth page now mentions that Indium is required for Sodium 0.5 and older.
