### ISSUE TITLE
Backport fixes for fluid rendering

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2500]
### Request Description

I guess it can fix some rendering bug with some specific mods, and then, it also fixes a Sodium bug with Minecraft Vanilla.

https://github.com/CaffeineMC/sodium-fabric/commit/aba6a91bf6f31bac77a9ea617b08f05f95450460
https://github.com/CaffeineMC/sodium-fabric/commit/0a8036bfc3dd62e8de32bb5f3e9927466b367492
https://github.com/CaffeineMC/sodium-fabric/commit/bc38d5638d391d3dfd1a928f6c7981116a7510f7

**Comment by jellysquid3** [comment]
Let's make sure this gets into Sodium 0.5.11...

**Comment by IMS212** [comment]
Added in https://github.com/CaffeineMC/sodium-fabric/commit/3d4cf6a957b0065e57518a5f188c23deaaa1bf7f.
