### ISSUE TITLE
I had the game crash when I loaded a save from before I installed the mod.

### ISSUE THREAD

**Issue by legodudelol9a** [jellysquid3/Sodium#2502]
### Bug Description

This is the error message I got:

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void me.jellysquid.mods.sodium.client.render.chunk.lists.VisibleChunkCollector.visit(me.jellysquid.mods.sodium.client.render.chunk.RenderSection, boolean)'

### Reproduction Steps

Unknown.

### Log File

[2024-05-13-4.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/15301577/2024-05-13-4.log.gz)

### Crash Report

[crash-2024-05-13_20.33.25-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/15301598/crash-2024-05-13_20.33.25-client.txt)

**Comment by jellysquid3** [comment]
This is not a support forum. And you are not even using an official version of our mod. Forge ports are of lower quality and are full of issues.

**Comment by legodudelol9a** [comment]
> This is not a support forum. And you are not even using an official version of our mod. Forge ports are of lower quality and are full of issues.

Then where do I go for help?

**Comment by Phoenix-Starlight** [comment]
To their discord server.
