### ISSUE TITLE
pojavlauncher issue

### ISSUE THREAD

**Issue by KushalGamer10** [jellysquid3/Sodium#2505]
### Bug Description

we cant use sodium or sodium extra on pojav launcher

### Reproduction Steps

try to use sodium and sodium extra on pojav launcher your game will crash if you try joining servers

### Log File

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/15347077/latest.log)

### Crash Report

[crash-2024-05-17_15.43.28-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/15347080/crash-2024-05-17_15.43.28-client.txt)

**Comment by Timolino456** [comment]
Sodium cannot be used on Pojav Launcher. It simply does not work and it never will. Stop trying to make it work. There is nothing you can do.

**Comment by agent1243** [comment]
> Sódio não pode ser usado no Pojav Launcher. Ele simplesmente não funciona e nunca funcionará. Pare de tentar fazê-lo funcionar. Não há nada que você possa fazer.

You are so blind, sodium does work in pojav
