### ISSUE TITLE
When glDebugVerbosity is set to 2, an OpenGL performance warning is in the log file

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2506]
### Bug Description

When glDebugVerbosity is set to 2, a performance warning is displayed in the log file
I don't know if it's fixable

`OpenGL debug message: id=131186, source=API, type=PERFORMANCE, severity=MEDIUM, message='Buffer performance warning: Buffer object 257 (bound to GL_ELEMENT_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.'`

### Reproduction Steps

1.Create a new Minecraft instance with Sodium and launch it
2.Close the game
3.Go to options.txt and set glDebugVerbosity to 2
4.Relaunch Minecraft
5.Generate a world
6.A performance warning message is written in the log file

### Log File

[2024-05-17-5.log](https://github.com/CaffeineMC/sodium-fabric/files/15362616/2024-05-17-5.log)

### Crash Report

.

**Comment by jellysquid3** [comment]
This warning isn't specific enough to be actionable and likely isn't even a valid performance issue. We map the monotonic index buffer back into host memory (while indicating the contents should be discarded) and then completely replace the contents. The only way to be more clear about our intention to the OpenGL driver would be to use more modern functionality (which is not currently available to us) or use buffer orphaning (maybe we'd accept a pull request for that if it was shown to actually be an issue.)
