### ISSUE TITLE
Game crashing after launch in 1.15.2, game launches normally without it.

### ISSUE THREAD

**Issue by MinecraftPlayerPC** [jellysquid3/Sodium#251]
Hello,
Recently I have installed fabric on my laptop, then when I launch the game it just crashes, if I don't use the mod it works just fine.
Extra info:
yes, I don't have fabric API in the mods folder
I have java 8u45 (because of compatibility issues)
the crash log said that Fabric is preparing to load mods and it didn't say anything else.
Keep in mind that I have tried to use different builds, versions, reinstalling minecraft, nothing helps.
Specs (just in case its a compatibility problem):
Intel core i5 M520
Intel HD graphics
4GB RAM
Windows 10 1803
(yes, I updated the drivers)
Note: it could be that my iGPU is not fully supported in Windows 10, which causes issues when I try to use a program with a modern version of OpenGL.

**Comment by LucilleTea** [comment]
Sodium 0.1.0 is for Minecraft 1.16.1 only, it's not compatible with 1.15.2.
As a workaround you could look into using multiconnect.
If you want to discuss this further or need support I recommend joining [the Discord server](https://jellysquid.me/discord).

**Comment by MinecraftPlayerPC** [comment]
Somehow it worked, I tried it with 1.16.1 before and it didn't work, this time it did, I am going to close this issue.
