### ISSUE TITLE
Sodium crash

### ISSUE THREAD

**Issue by AkashGaming54** [jellysquid3/Sodium#2517]
### Bug Description

When i want to join my world or server then my minecraft crashed

### Reproduction Steps

When i want to join my world or server then my minecraft crashed

### Log File

[crash-2024-05-27_06.58.54-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/15449690/crash-2024-05-27_06.58.54-client.txt)

### Crash Report

crash-2024-05-27_06.58.54-client.txt

**Comment by Poopooracoocoo** [comment]
Your version of simply-no-shading is out of date

**Comment by Poopooracoocoo** [comment]
For Sodium 0.4.10, you must downgrade simply-no-shading to 6.0.7.

I'm not sure why you're on Sodium 0.4.10 though. 

I should also add that this is not a support forum. The Discord server is where you should go.

And a log is not the same as a crash report.

**Comment by mrjasonn** [comment]
Yeah, you should use the latest version of Sodium that is marked as stable for your Minecraft version, to prevent any issues
