### ISSUE TITLE
Weird water and leaves rendering issue on Fancy/Fabulous graphics on 1.20.1

### ISSUE THREAD

**Issue by Shayvi-del** [jellysquid3/Sodium#2524]
### Bug Description

(using Chunk by Chunk for ease of viewing)

![javaw_RRhGe3a1TH](https://github.com/CaffeineMC/sodium-fabric/assets/51413351/2f8ba926-a910-4bec-a8a5-cae4e6526b81)
![javaw_n8RCPvsr8o](https://github.com/CaffeineMC/sodium-fabric/assets/51413351/723c8a74-0e77-4d32-b407-e8ba4c722ccf)

Sodium 0.5.8 on Minecraft 1.20.1 renders the faces of water and leaves weirdly. For the leaves it is consistent but for the water it happens only for one block wide body of waters :

![image](https://github.com/CaffeineMC/sodium-fabric/assets/51413351/90b1c80a-e7c0-4fbc-ad50-9c5aeb29ddea)

I have seen people talking about issues for 4+ years with no fix, I know it might be voluntary for Fast graphics but I am currently using the Fabulous! setting :

![image](https://github.com/CaffeineMC/sodium-fabric/assets/51413351/2363a4a2-f420-46fc-ab51-526072c41463)

### Reproduction Steps

-Install Fabric API and Sodium
-Switch to Fancy or Fabulous! graphic setting

For the water:
-Create any body of water that is 1 block wide and can be infinitely long
-Look at how it renders

For the leaves:
-Grow a tree
Or
-Place several leaves block in a cubic shape for ease of viewing

### Log File

No log files to report

### Crash Report

No crash to report

**Comment by MeeniMc** [comment]
The water bug is #38 and fixed in dev.
