### ISSUE TITLE
Clouds render through terrain while picking up items

### ISSUE THREAD

**Issue by LostLuma** [jellysquid3/Sodium#2525]
### Bug Description

Picking up an item while looking at blocks that are currently covering the clouds will render the clouds in front of the blocks for a brief period of time. This happens on both the `dev` and `1.21/dev` branches.

### Reproduction Steps

- Stand in front of a mountain / under a tree
- Throw an item on the ground
- Look up at the blocks covering the clouds
- Pick up the item automatically
- See clouds for a second even though there are blocks in the way

### Log File

[latest.log](https://github.com/user-attachments/files/15525591/latest.log)

### Crash Report

[crash-2024-06-02_16.12.35-client.txt](https://github.com/user-attachments/files/15525605/crash-2024-06-02_16.12.35-client.txt)

**Comment by Lolothepro** [comment]
I can confirm

**Comment by Lolothepro** [comment]
https://github.com/CaffeineMC/sodium-fabric/assets/68275908/8d8231bf-4dd9-4819-a806-52627503e7f3

**Comment by Lolothepro** [comment]
fixed
