### ISSUE TITLE
Textures glitch out when using resource packs with sodium and waystones

### ISSUE THREAD

**Issue by Bratorsortnal** [jellysquid3/Sodium#2530]
### Bug Description

A specific texture bugs out when a resource pack is active. The texture does not have to be changed by the resource pack.
I am sure that I had the same issue without the Waystones mod. This time disabling it fixed the issue.

### Reproduction Steps

Install Waystones 10.2.2
Install Sodium 0.4.1
Run a (for example) bushy leaves resource pack, then some block's texture will glitch out

### Log File

[latest.log](https://github.com/user-attachments/files/15751255/latest.log)

### Crash Report

[crash-2024-06-09_10.43.47-client.txt](https://github.com/user-attachments/files/15751259/crash-2024-06-09_10.43.47-client.txt)

**Comment by jellysquid3** [comment]
It is kind of prudent to actually include a screenshot of the graphical glitches you are experiencing...

**Comment by Bratorsortnal** [comment]
> It is kind of prudent to actually include a screenshot of the graphical glitches you are experiencing...

Well it's sorta like alot of different vanilla textures compressed to fit in a square
I'll include the screenshot shortly

**Comment by jellysquid3** [comment]
Closing after 2 weeks of inactivity without required information. Please re-open the issue if you can still reproduce with just Waystones (and whatever dependencies) + Sodium and can provide screenshots.
