### ISSUE TITLE
Intel Graphics Driver Error

### ISSUE THREAD

**Issue by 0bsidianFox** [jellysquid3/Sodium#2533]
### Bug Description

Game crashes due to not having compatible Integrated Graphics.

Is there any way I can force it to work with my GPU?

### Reproduction Steps

1.20.5 and 1.20.6
latest fabric loader (0.15.11)

### Log File

[latest.log](https://github.com/user-attachments/files/15758180/latest.log)

### Crash Report

none, I'm using a custom launcher

**Comment by Samalando** [comment]
https://www.youtube.com/watch?v=8KAbjcctl4Y you can google this quite easily

**Comment by 0bsidianFox** [comment]
> https://www.youtube.com/watch?v=8KAbjcctl4Y you can google this quite easily

😔🤦‍♂️🙅‍♂️

**Comment by MeeniMc** [comment]
try the solutions discussed here 
https://github.com/CaffeineMC/sodium-fabric/issues/2432
