### ISSUE TITLE
Please actually fix the submitter did not read issue template label not following the Sodium issue and pull request tracker labelling scheme

### ISSUE THREAD

**Issue by mrjasonn** [jellysquid3/Sodium#2535]
### Bug Description

Please actually fix the submitter did not read issue template label not following the Sodium issue and pull request tracker labelling scheme. This **makes the issue tracker absolutely unusable** due to this simple problem. The description of it also.

### Reproduction Steps

1. Go to labels section in issue tracker
2. Search it
3. Congratulations! You will see the issue in it that makes the issue tracker very unusable.

### Log File

Not relevant

### Crash Report

Not relevant

**Comment by wahfl2** [comment]
Why did you open a duplicate issue? I don't know why your previous issue was deleted (#2531), but if it was done by anyone other than yourself, that's probably a good reason to _not_ open the exact same issue.

I also fail to see how this makes the issue tracker any less usable.

**Comment by douira** [comment]
Please stop making this type of issue, it will get you banned from the issue tracker.
