### ISSUE TITLE
Sodium seems to break parity with vanilla in how the chunks are loaded?

### ISSUE THREAD

**Issue by maskersss** [jellysquid3/Sodium#2537]
### Bug Description

In vanilla 1.21, when generating a new world, the second C counter on top left of F3 instantly jumps up to the maximum value. I expected Sodium to function the same way as vanilla, so I expected Sodium to behave the same here.
With just Sodium and Fabric installed, the second C counter is instead going up slowly as the chunks are loading when creating a new world (which allows you to more easily see the progress of chunks loading).
Clip from vanilla: https://github.com/CaffeineMC/sodium-fabric/assets/97827489/1bc39f57-2532-4486-af1c-d9152bb32190
Clip from sodium: https://github.com/CaffeineMC/sodium-fabric/assets/97827489/0f4847c9-72bf-4e6a-8266-dfbba2ba7af5

### Reproduction Steps

- Create a Fabric instance with Sodium 0.5.9 on Minecraft 1.21
- Create a new singleplayer world on 32 render distance
- Watch the second C value in top left of the F3 screen increase slowly:
![image](https://github.com/CaffeineMC/sodium-fabric/assets/97827489/512c328f-3163-4882-916c-d15f8196a7e8)

### Log File

https://mclo.gs/eC0sd2p (with Sodium installed; vanilla was tested on the same instance before i added fabric & sodium to it)

### Crash Report

https://mclo.gs/k9NQ0Jj

**Comment by jellysquid3** [comment]
This is intentional, the way that Sodium works is different from Minecraft. We're showing the "total number of loaded chunk sections" rather than "total number of chunk sections within the render distance". The former is a more useful number, anyways.
