### ISSUE TITLE
1.20.1 newest version is not compatible with indium

### ISSUE THREAD

**Issue by vinnyg0621** [jellysquid3/Sodium#2538]
### Bug Description

when starting the game, I installed the latest version of sodium **and** indium and I got this:
<img width="584" alt="Screenshot 2024-06-13 125320" src="https://github.com/CaffeineMC/sodium-fabric/assets/57818441/118bd5c3-304d-4582-a23e-9398c2ae934f">
**but**, if I downgrade and use the newest version of indium, it crashes with exit code -1.

### Reproduction Steps

Get the latest ver. of sodium,
Start Minecraft,
I will get the error message

### Log File

[latest.log](https://github.com/user-attachments/files/15828025/latest.log)

### Crash Report

https://gist.github.com/vinnyg0621/7dc2f07ff198a1742dbb65287d627021
but when I don't use 0.5.8, I get this after I enter a world:
[crash-2024-06-13_12.49.13-client.txt](https://github.com/user-attachments/files/15828013/crash-2024-06-13_12.49.13-client.txt)

**Comment by pajicadvance** [comment]
Indium needs to be updated to support Sodium 0.5.9. Stick to 0.5.8 until then.

**Comment by vinnyg0621** [comment]
i did but the world kept crashing

**Comment by vinnyg0621** [comment]
oh wait, that's with iris shaders 1.7.1
