### ISSUE TITLE
 Spawn Eggs and Potions not showing (correctly) 1.20.1

### ISSUE THREAD

**Issue by Gundal-stack** [jellysquid3/Sodium#2539]
### Bug Description

Hi there,
I got notice of this bug via my job as Moderator of the Feather Client Discord. People reached out to our support, that had this issue of the mentioned Items not showing correctly. I went to reproduce the issue and tried it without Feather Client, just with the Fabric Loader (latest version) and Sodium 0.5.9 (for 1.20.1). I also tried the version before, 0.5.8, but this issue does not appear on that version. My Drivers are up-to-date and this doesn't only happen to me.
This applies to all potions (normal, splash and lingering)
![339510737-7f63b4c2-0508-46cc-94aa-ffcfd78e47dd](https://github.com/CaffeineMC/sodium-fabric/assets/72203566/56e7adc8-1627-4704-b5cf-991361d876bb)
All spawn eggs are completely invisible (even in the tab selector)
![339511552-ccbfdbf1-fd18-486b-bb1d-af068a2018d3](https://github.com/CaffeineMC/sodium-fabric/assets/72203566/825bcea1-88ba-4a32-9a96-01df310e8c7f)
Neither of these items show (correctly) when holding them in the hand or placing in an itemframe

### Reproduction Steps

Install Fabric Loader (Version 0.15.11/Latest) for 1.20.1
Add Sodium for 1.20.1 (Version 0.5.9/Latest)
Start the game and open the inventory

### Log File

[latest.log](https://github.com/user-attachments/files/15828100/latest.log)

### Crash Report

[crash-2024-06-13_20.50.26-client.txt](https://github.com/user-attachments/files/15828099/crash-2024-06-13_20.50.26-client.txt)

**Comment by Lolothepro** [comment]
fixed in 1.20.1/backport

**Comment by IMS212** [comment]
Fixed with Sodium 0.5.10.
