### ISSUE TITLE
Sodium get crash in 1.21

### ISSUE THREAD

**Issue by GAMERGENIX1** [jellysquid3/Sodium#2542]
### Bug Description

1.21 keep crashing on pojav launcher plz fix it pojav community want that sodium pojav also

### Reproduction Steps

Just put sodium 1.21 in mods and strt the game 

### Log File

Nope

### Crash Report

Kk

**Comment by TheUserCreated** [comment]
Please see #1916 and [the hardware compatibility section of the README](https://github.com/CaffeineMC/sodium-fabric#-hardware-compatibility) , pojav is not supported and there are no plans to support it.
