### ISSUE TITLE
Sodium crashed with "Rendering entity in world" error, 1.20.1

### ISSUE THREAD

**Issue by Fork0n** [jellysquid3/Sodium#2543]
### Bug Description

Hi, while downloading mods minecraft started crashing, not enough crashes is telling that Sodium might be the issue (note: I'm just  a random kid so idk if my oppinion even counts ¯\\_(ツ)_/¯ )

### Reproduction Steps

Minecraft 1.20.1 fabric loader version 0.15.11
step 1) download my mods: https://www.mediafire.com/file/agjl7vafvc1el30/mods.zip/file (note: disabled mods are most likely to crash the game, but it I'm not 100% sure it's their fault)
step 2) load  any world
that's it

### Log File

[latest.log](https://github.com/user-attachments/files/15837382/latest.log)

### Crash Report

https://bytebin.lucko.me/gowmKalWkL

**Comment by Lolothepro** [comment]
update Sodium
Note: This issue tracker is not intended for support requests!

**Comment by Fork0n** [comment]
> update Sodium Note: This issue tracker is not intended for support requests!
Well yes it worked, BUT, the newest sodium isn't supported by Indium and Iris, so i  guess the only  way for everything to work properly is to wait until the official support
