### ISSUE TITLE
Sodium 1.21 doesn't work! :(

### ISSUE THREAD

**Issue by moonhayul2009** [jellysquid3/Sodium#2546]
### Bug Description

I downloaded fabric 1.21 and I put fabric api 1.21, sodium 1.21 in mod folder. When open minecraft and go in a world it crashes.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/78576530/bfdbf3e2-eda1-4ee0-9f1f-656a7acff501)

### Reproduction Steps

1. Open the launcher
![image](https://github.com/CaffeineMC/sodium-fabric/assets/78576530/0cd6e56a-b27b-485e-9b36-69cab4ebeda0)
2. Open Minecraft
![image](https://github.com/CaffeineMC/sodium-fabric/assets/78576530/6513d802-ea8f-4233-b7ea-e6bcf39ba41e)
3. Go into any world
![image](https://github.com/CaffeineMC/sodium-fabric/assets/78576530/fb8d8942-3a38-40e9-b143-a8107d3a60e7)
4. Loading->Saving the world->Crash
![image](https://github.com/CaffeineMC/sodium-fabric/assets/78576530/4f462efb-c6de-474f-a487-3f4e65a92eb7)
5. Can't open Crash Report
![image](https://github.com/CaffeineMC/sodium-fabric/assets/78576530/42313a36-d57b-42ce-bea4-d977e9a3bf32)

### Log File

latest.log file was created way before I open the launcher.
(It is not created...)

### Crash Report

Can't open Crash Report
![image](https://github.com/CaffeineMC/sodium-fabric/assets/78576530/42313a36-d57b-42ce-bea4-d977e9a3bf32)

**Comment by moonhayul2009** [comment]
HELP

**Comment by IMS212** [comment]
This will be fixed in the next release; a temporary fix is to delete any resource packs that modify the sky.

**Comment by moonhayul2009** [comment]
Thank you!! It works now! :D ❤️❤️❤️❤️
