### ISSUE TITLE
Flickering textures on some geometry

### ISSUE THREAD

**Issue by MrCroisan** [jellysquid3/Sodium#2548]
### Bug Description

The error only appears on Sodium

### Reproduction Steps

at an altitude of -50, this bug will appear

### Log File

![2024-06-14_19 43 21](https://github.com/CaffeineMC/sodium-fabric/assets/95076160/70e818bb-31dd-44c4-bf02-722b6d74127e)

### Crash Report

no report file

**Comment by Lolothepro** [comment]
send log file

**Comment by MrCroisan** [comment]
> отправить файл журнала

where can I get it?

**Comment by Lolothepro** [comment]
in `.minecraft/logs/latest.log`

**Comment by MrCroisan** [comment]
> в`.minecraft/logs/latest.log`

[latest.log](https://github.com/user-attachments/files/15857536/latest.log)

**Comment by jellysquid3** [comment]
This has since been fixed in newer versions of Sodium.
