### ISSUE TITLE
Minecraft freeses

### ISSUE THREAD

**Issue by DEGLE234** [jellysquid3/Sodium#2551]
### Bug Description

My minecraft keeps freezing up at around 10% loaded on startup. Yesterday was fine, but for some reason it happened again.
NOTE:
No, I don't need to update my drives
My mods are up-to-date
It only happens with sodium, everything else works just fine and loads in perfectly.

### Reproduction Steps

It only happens when I put sodium in.

### Log File

[latest.log](https://github.com/user-attachments/files/15868119/latest.log)

### Crash Report

[crash-2024-06-17_12.38.42.6928-quilt_loader.txt](https://github.com/user-attachments/files/15868297/crash-2024-06-17_12.38.42.6928-quilt_loader.txt)

**Comment by MCRcortex** [comment]
A) its not sodium B) buy the game and stop using a cracked launcher C) this is not a support forum
