### ISSUE TITLE
Falling or Moving Block Game Crash

### ISSUE THREAD

**Issue by cxianb** [jellysquid3/Sodium#2553]
### Bug Description

So when a block is moving like a flying machine or when a block is falling like gravel the game crashes.

### Reproduction Steps

create a upside L with blocks then put gravel on top, stand under the block that has gravel on top then break the block so gravel can fall then the game will instantly crash after breaking the block under the gravel.

### Log File

[latest.log](https://github.com/user-attachments/files/15875509/latest.log)

### Crash Report

The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null

**Comment by Lolothepro** [comment]
caused by FRAPI, install Indium

**Comment by cxianb** [comment]
yep that worked thank you

> caused by FRAPI, install Indium
