### ISSUE TITLE
MoltenGL implementation

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2555]
### Request Description

Sodium and other OpenGL-based renderers don't perform well on Macs because Apple doesn't fully support OpenGL.

However, MoltenGL enables OpenGL to run natively on Apple devices by leveraging the native Metal API. This can significantly improve performance on macOS devices, especially those with Apple Silicon.

This is evident from MoltenVK's use in the VulkanMod, which achieves impressive frame rates and very high view distances on Macs with Apple Silicon.

Also, incorporating MoltenGL into Iris and other optimization mods that work with Sodium, after proper collaboration between developers, could similarly result in substantial performance improvements for Minecraft shaders on macOS, leading to exceptional optimization for the game.

**Comment by jellysquid3** [comment]
MoltenGL is not free software, and licensing costs up to $19,999 USD/year. Furthermore, on macOS, it does not provide any advantage over Apple's OpenGL implementation (which provides up to OpenGL 4.1, rather than OpenGL 2.0 ES). And it is very unlikely it would perform any better.

**Comment by ghost** [comment]
Ah okay, thanks for the explanation, I thought it was free and open source like MoltenVK.
