### ISSUE TITLE
Sodium rejecting resourcepacks that aren't compatible.

### ISSUE THREAD

**Issue by istupidgirl** [jellysquid3/Sodium#2558]
### Request Description

As of 1.21, sodium seems to remove the resourcepack that it has incompatibilities with. I would like an option to disable to this, because they are some resourcepacks that it says it is incompatible with however they still work.

**Comment by Lolothepro** [comment]
Do you have an example of a resource pack?

**Comment by jellysquid3** [comment]
Sodium does not remove any resource packs. There is only the warning, nothing else.

**Comment by istupidgirl** [comment]
> Sodium does not remove any resource packs. There is only the warning, nothing else.

I'm only using sodium in this instance & it is disabling the resource pack.
https://github.com/CaffeineMC/sodium-fabric/assets/88780152/90b78d3a-0cc7-43a4-9b91-89d3d26af422

**Comment by jellysquid3** [comment]
And without a log file it is impossible to help diagnose _why_ the resource pack is not loading. But Sodium doesn't intentionally reject resource packs, and a feature request to "disable" such behavior makes no sense. More likely than not, your resource pack is just broken (likely contains core shaders.)

**Comment by istupidgirl** [comment]
> And without a log file it is impossible to help diagnose _why_ the resource pack is not loading. But Sodium doesn't intentionally reject resource packs, and a feature request to "disable" such behavior makes no sense. More likely than not, your resource pack is just broken (likely contains core shaders.)

Yeah. The resource pack was broken in 1.21. I assumed it was a new sodium feature, because it was working fine in 1.20. I should do more testing before posting
