### ISSUE TITLE
Unable to update GPU versiion

### ISSUE THREAD

**Issue by BrianWJT** [jellysquid3/Sodium#2559]
### Bug Description

I cant start minecraft cause show this error telling me i have old driver for Nvidia.

I'm currently using RTX3060

![906670d10c55c678661aaf2aa72c6da](https://github.com/CaffeineMC/sodium-fabric/assets/110806241/a765c659-5f48-466a-936e-1d136f60f7d8)

### Reproduction Steps

1, Open minecraft lancher
2. Go on play mincraft 1.21
3. and crashes

### Log File

[latest.log](https://github.com/user-attachments/files/15904100/latest.log)

### Crash Report

-

**Comment by MeeniMc** [comment]
As the error indicates, you need to install a more recent version of the nvidia driver, go to [nvidia.com/](https://www.nvidia.com/download/index.aspx?lang=en-us) to obtain it.

**Comment by jellysquid3** [comment]
Why do you think this is a bug? Update your graphics driver. You have version 531.97 but need version 536.23.
