### ISSUE TITLE
Sodium won't let me open the game

### ISSUE THREAD

**Issue by Shimukooo** [jellysquid3/Sodium#2560]
### Bug Description

I updated to the new version of Sodium, after which Minecraft started producing this error 1.20.1
![изображение_2024-06-19_230834154](https://github.com/CaffeineMC/sodium-fabric/assets/173306225/2c0bf241-7b3c-4dae-bfac-cf48a9aec9a6)

### Reproduction Steps

![изображение_2024-06-19_231023960](https://github.com/CaffeineMC/sodium-fabric/assets/173306225/09a9b647-4c25-4802-9dd9-dfa7fe189fc8)
I have these modifications in my assembly

### Log File

[latest.log](https://github.com/user-attachments/files/15905581/latest.log)

### Crash Report

![image](https://github.com/CaffeineMC/sodium-fabric/assets/173306225/1655ab42-8b9e-405a-a40e-b8df9c56f1b3)

**Comment by jellysquid3** [comment]
You have upgraded LWJGL to version 3.3.3, which is not compatible with Sodium on MC 1.20.1. The correct version is LWJGL 3.3.1. Do not upgrade the LWJGL libraries or you will have issues with mods.

**Comment by Shimukooo** [comment]
Thanks a lot
