### ISSUE TITLE
GUI to match Minecraft

### ISSUE THREAD

**Issue by nivnarna** [jellysquid3/Sodium#2562]
### Request Description

Love sodium, but wish the GUI matched Minecraft’s. It’s difficult to view and change the settings with the GUI looking different

Maybe a toggle to change between the two would be good

**Comment by Felix14-v2** [comment]
There's a mod to hide Sodium settings screen under a separate button in the vanilla one ([BSVSB](https://modrinth.com/mod/better-sodium-video-settings-button)). Also you can access the vanilla settings even without any mods by pressing Shift+P.

As far as I know, Sodium developers decided to create a separate settings screen to avoid technical problems and limitations of the vanilla buttons system, which has been broken for ages. In future Sodium will change its style to a more modern and polished look, you can find a concept in the [dev-blog channel](https://discord.com/channels/602796788608401408/1077645005042233374/1197818793943126107):

![image-2](https://github.com/CaffeineMC/sodium-fabric/assets/75726196/7ba09e80-b09a-4f2c-9eaa-3323682df863)

**Comment by jellysquid3** [comment]
Not being considered.
