### ISSUE TITLE
Entity Culling Issue with Entity Model Features

### ISSUE THREAD

**Issue by DrogoonBlizzard** [jellysquid3/Sodium#2567]
### Bug Description

NOT AN ISSUE, i found that in my unmodded version there was a drowned, that was throwing tridents, which caused it to render on the vanilla version, this is a different bug sorry for the inconvienence :(

When using a custom resource pack with cem, that remodels a trident, the trident does not render in the players hand, unless there is another trident entity on screen. im pretty sure this error is because the trident in hand is not treated as an entity, so it got culled, but when there is another trident it tries to render all tridents, which includes the one in the players hand. i have tried this without sodium and it works fine, so it is most likely a sodium issue.

### Reproduction Steps

1: Remodel a trident with Custom Entity Models
2: Hold trident in game
3: Throw trident, and it should show the trident in hand, if you look away from the trident entity the one in your hand will dissapear

### Log File

[latest.log](https://github.com/user-attachments/files/15937615/latest.log)

### Crash Report

[crash-2024-06-22_12.32.22-client.txt](https://github.com/user-attachments/files/15937611/crash-2024-06-22_12.32.22-client.txt)

**Comment by jellysquid3** [comment]
If your issue report is invalid, then please use the "Close Issue" button.
