### ISSUE TITLE
Uncaught exceptions thrown while probing for graphics adapters should not be allowed to crash the game

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#2568]
We've seen a few crashes at startup that are caused by exceptions getting thrown while enumerating graphics adapters. This is really less than ideal, because there is going to always be weird stuff we can't accommodate, so we should catch these exceptions and allow for the enumeration to fail gracefully.

When enumerating graphics adapters fails, there should also be a clear warning in the log file which indicates the exception, so that we can find these issues in the wild and fix them where possible. It should also suggest that users open a bug report with information about their hardware and driver versions.

**Comment by jellysquid3** [comment]
An example of this problem can be seen with issues #2545 and #2550. While they are both valid bug reports that need to be fixed, they unnecessarily crashed the game.

**Comment by IMS212** [comment]
Fixed in https://github.com/CaffeineMC/sodium-fabric/commit/7c53462d26e09342495a65b55e4c4e1acb02c8ff.
