### ISSUE TITLE
[BUG] Sodium messing up glow colors

### ISSUE THREAD

**Issue by ItziSpyder** [jellysquid3/Sodium#2574]
### Bug Description

I am coding a server side plugin that summons entities with a glowing affect given a color of my choice, however the colors didn't seem to work properly. At first I thought it was just a bug in my code, but I later realized the bug was with the mod sodium. Right after I have removed sodium from my mods folder, the bug fixed itself. This bug report is for sodium 0.5.9 mc1.21.

### Reproduction Steps

1. Delete sodium and launch game
2. Summon a glowing entity and make the glow any color.
3. Make sure the colors are working
4. Close game and add sodium back, then launch game
5. Observe how the color isn't what you set it to be.

### Log File

There were no errors in log.

### Crash Report

There were no crashes.

**Comment by jellysquid3** [comment]
See https://github.com/CaffeineMC/sodium-fabric/issues/2547.
