### ISSUE TITLE
Game crash with Chunk build failed and java OOM

### ISSUE THREAD

**Issue by xiao-k233** [jellysquid3/Sodium#2577]
### Bug Description

Just playing，suddenly,everything paused in a few secnds.Then,MC crashed
In many situations,no error logs.

### Reproduction Steps

Just play....

### Log File

[latest.log](https://github.com/user-attachments/files/15988914/latest.log)

### Crash Report

[crash-2024-06-26_14.21.43-client.txt](https://github.com/user-attachments/files/15988927/crash-2024-06-26_14.21.43-client.txt)
Same server,same play

**Comment by douira** [comment]
Your habt very many mods, any of which could be causing the problem. Verify that this problem happens with only sodium installed, or that it does not also happen without it. DH in particular is known to use a lot of memory.

**Comment by Gaming32** [comment]
I will note that you seem to be using 99.3% of your computer's total RAM. If a lot of this this isn't from Minecraft, you might need to close some programs.

**Comment by xiao-k233** [comment]
thanks,I will try

**Comment by jellysquid3** [comment]
Not a bug with Sodium, unless you can show there's a memory leak.
