### ISSUE TITLE
TODO: Sodium 0.6.0

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2578]
Bug already reported:

- https://github.com/CaffeineMC/sodium-fabric/issues/2233
- https://github.com/CaffeineMC/sodium-fabric/issues/2232
- https://github.com/CaffeineMC/sodium-fabric/issues/2373
- https://github.com/PepperCode1/Continuity/issues/292

Other:

- Leaves mipmapping is not correct

	![2024-06-26_19 56 44](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/bd6d4641-57cd-4432-b8d9-95efabb8916c)

	![image](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/b167ae73-60fa-4b6f-bdba-da3c23602559)

~~- Mixin crash with -Dmixin.debug.countInjections=true
Log file: [latest.log](https://github.com/user-attachments/files/15993395/latest.log)~~
	Fixed in 14054ff4f2d49be8ae195c3c90d2b0761f5fa6da

- There are some strange lines on certain modded blocks with Sodium
	with frostrealm:frost_crystal_ore

	Vanilla:

	![image](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/86c04784-7a1c-4414-8f9a-2fe88f567262)

	Sodium:

	![image](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/2e14a10d-85a1-41e4-9ebd-be47d060f5ce)

- Cloud bug when the player moves from one biome to another with Twilight Forest
	

	https://github.com/CaffeineMC/sodium-fabric/assets/68275908/9e047a97-a623-4df4-b54e-597e579edcbf

**Comment by douira** [comment]
The three mentioned sodium issues are already in the sodium 0.6 milestone.

**Comment by Lolothepro** [comment]
> The three mentioned sodium issues are already in the sodium 0.6 milestone.

It's just to relist them, to have all the bugs that need to be fixed in a single issue.

**Comment by jellysquid3** [comment]
Don't create issues like this.
