### ISSUE TITLE
Some modded blocks appear too transparent 

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2579]
### Bug Description

The leaves mipmapping is not correct.

![image](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/2a161961-55f9-4e1a-a748-7db9ff8bca86)

![image](https://github.com/CaffeineMC/sodium-fabric/assets/68275908/5b4dcbcb-b52d-4fd4-83b6-a9eee58a92f5)

### Reproduction Steps

Launch the game, and select the Vanilla resource pack as the main pack.

### Log File

[2024-06-26-6.log](https://github.com/user-attachments/files/15996505/2024-06-26-6.log)

### Crash Report

*

**Comment by douira** [comment]
IMS can't reproduce and Lolo said it could be closed
