### ISSUE TITLE
Minecraft 1.20.1 Fabric won't open with Sodium

### ISSUE THREAD

**Issue by Ben-Kenob** [jellysquid3/Sodium#2581]
### Bug Description

I am attempting to make a modpack for myself on curse forge, the only mod that isn't working is Sodium. This pack is for Minecraft 1.20.1 using the Fabric Launcher. When I launch the pack, it pulls up the Minecraft launcher like normal. But when I hit play, the Minecraft icon appears in the dock for a split second and then the game crashes. I get no crash report either.

### Reproduction Steps

Install sodium 1.20.1 fabric inside of your modpack. Use any other mods with it. Launch the pack, hit play in the Minecraft launcher and the game opens in the doc for a split second and then crashes again.

### Log File

[latest.log](https://github.com/user-attachments/files/16006927/latest.log)

### Crash Report

I did not receive a crash report

**Comment by Poopooracoocoo** [comment]
#5 Install Indium

**Comment by Ben-Kenob** [comment]
> #5 Install Indium

Thank you! That worked a treat!
