### ISSUE TITLE
Axiom causes a LWJGL version mismatch error at startup

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#2585]
Various user reports have indicated that it has become impossible to start Minecraft 1.20.1 with Sodium 0.5.11 when [Axiom 3.0.0](https://modrinth.com/mod/axiom/version/sJP1pto6) is also installed. This appears to be due to the fact that they're including parts of LWJGL's libraries inside their mod, and likely class load order at early startup causes the determined version to be wrong.

**Comment by jellysquid3** [comment]
We probably want to make sure that Sodium's error message indicates that "... other mods can also sometimes cause this issue" so that users don't tear apart their launcher for no reason.

**Comment by jellysquid3** [comment]
The question is whether this is a false error (where Sodium just thinks the version of LWJGL is different) or rather a real issue with Axiom replacing parts of LWJGL that it probably shouldn't be.

**Comment by jellysquid3** [comment]
From the log files:

```
[LWJGL] [ERROR] Incompatible Java and native library versions detected.
Possible reasons:
	a) -Djava.library.path is set to a folder containing shared libraries of an older LWJGL version.
	b) The classpath contains jar files of an older LWJGL version.
Possible solutions:
	a) Make sure to not set -Djava.library.path (it is not needed for developing with LWJGL 3) or make
	   sure the folder it points to contains the shared libraries of the correct LWJGL version.
	b) Check the classpath and make sure to only have jar files of the same LWJGL version in it.
```

So I'm guessing it's not merely version detection that is broken by Axiom. Maybe they are just including the wrong libraries for MC 1.20.1.

**Comment by Ocraftj** [comment]
Does anybody know if the supporter-only backport version of axiom 3.1.0 has this same glitch for MC 1.20.1? or is this just for version 3.0.0?

**Comment by jellysquid3** [comment]
For people running into this issue, you can use a hidden command-line option to bypass the checks in the meanwhile. Just add the following to your JVM arguments:

```
-Dsodium.checks.issue2561=false
```

How exactly you do this is going to depend on your launcher of choice. Caveat emptor.

**Comment by jellysquid3** [comment]
Making this highest priority. Too many bug reports are coming in from other users. We need to either block earlier versions of Axiom, or special case their mod.

**Comment by jellysquid3** [comment]
The author of Axiom tells me that it will likely be fixed on their end in the coming days. So I don't think we need a remediation on our end.

**Comment by jellysquid3** [comment]
Axiom 3.2.1 fixes this problem.

**Comment by jellysquid3** [comment]
Removing this from the milestone since it didn't require resolution on our side. Thanks @Moulberry.
