### ISSUE TITLE
Spectator's head model does not takes in account when doing translucency sorting.

### ISSUE THREAD

**Issue by frosthuuuund** [jellysquid3/Sodium#2587]
### Bug Description

In the title.
![image](https://github.com/CaffeineMC/sodium-fabric/assets/174178570/8d7f60a5-ef22-4b56-bd95-4ad7fc854287)

### Reproduction Steps

Clone this repo's `/dev` branch with commit `db7c77a`.
Build the cloned files.
Install your built mod.
Login in the world and switch to the spectator mode.
Switch to 3rd person view.
Make your head model in one line with water or any other translucent block.
Observe the bug.

### Log File

Not applicable.

### Crash Report

Not applicable.

**Comment by Lolothepro** [comment]
It's not a Sodium bug, it's a Vanila bug, please use the "Fabulous!" graphic setting.
Sodium translucency sorting does not affect entities
https://bugs.mojang.com/browse/MC-187783
