### ISSUE TITLE
Network Protocol Error

### ISSUE THREAD

**Issue by Wikinger8** [jellysquid3/Sodium#2589]
### Bug Description

Expected: Join the world
Mod that causes the problem: EMI

https://github.com/emilyploszaj/emi/assets/85295145/190baea7-db19-4bcc-85dc-78fc63d2643b

![image](https://github.com/emilyploszaj/emi/assets/85295145/812f63e5-9e0a-4e95-8723-040fda76e46e)

### Reproduction Steps

1. Install Quilt Loader
2. Install Sodium, JEI, EMI and Fabric Api (Tested and there is no difference between the Quilted Fabric Api and the normal Fabric Api regarding the bug)
3. Start Minecraft and try to join a server. (Sometimes it works for a few tries, so reconnect until you get the error message).
4. After you get the error once, you can join multiplayer or single player worlds and you will get the error every time you try to join.

### Log File

[latest.log](https://github.com/user-attachments/files/16117130/latest.log)
[disconnect-2024-07-06_21.33.51-client.txt](https://github.com/user-attachments/files/16117131/disconnect-2024-07-06_21.33.51-client.txt)

### Crash Report

[crash-2024-07-06_21.52.26-client.txt](https://github.com/user-attachments/files/16117157/crash-2024-07-06_21.52.26-client.txt)

**Comment by MeeniMc** [comment]
What makes you think that Sodium is involved in this? 

It looks like its a bad interaction between malformed datapack recipes and EMI, probably this should be reported to EMI/JEI rather than here.

**Comment by Wikinger8** [comment]
![image](https://github.com/CaffeineMC/sodium-fabric/assets/85295145/c1bedcde-10bc-4183-aa71-d59538a4b692)
https://github.com/emilyploszaj/emi/issues/620

The problem only occurs when Sodium is activated and they said to report it here.

**Comment by jellysquid3** [comment]
I don't see any reason this is related to Sodium. The error is pretty clear, two different threads (belonging to different mods) are modifying the same data structure in code unrelated to rendering, causing corruption & a crash. Maybe it's possible that Sodium loading the world faster is exposing a race condition in other mods, but that's not anything we can fix.
