### ISSUE TITLE
Black-stained glass blocks aren't seen behind glass panes

### ISSUE THREAD

**Issue by kazarmy** [jellysquid3/Sodium#2590]
### Bug Description

As per title, the black-stained glass block roof in the screenshot below is occluded by the glass panes (Sodium 0.5.11):

![Iris](https://github.com/CaffeineMC/sodium-fabric/assets/12002672/0a588afc-3f16-43ff-bb82-eda1875cc071)

What it should look like (OptiFine HD U I4):

![Optifine](https://github.com/CaffeineMC/sodium-fabric/assets/12002672/acbadcdf-3c94-4d79-8de0-72a56e04415a)

This problem also happens in Sodium 0.4.10 build 24 (the Sodium version for 1.19.4).

### Reproduction Steps

Set up as in first screenshot (three-block high glass panes with black-stained glass block roof).

### Log File

[latest.log](https://github.com/user-attachments/files/16118081/latest.log)

### Crash Report

[crash-2024-07-07_11.48.55-client.txt](https://github.com/user-attachments/files/16118080/crash-2024-07-07_11.48.55-client.txt)

**Comment by TheUserCreated** [comment]
Duplicate of #38 . To be fixed in 0.6

**Comment by kazarmy** [comment]
Yep, looks better with Sodium 0.6:

![Sodium_0 6 0-alpha 1](https://github.com/CaffeineMC/sodium-fabric/assets/12002672/a1f75bdf-4af7-4517-9362-521fab82ec97)

**Comment by kazarmy** [comment]
A bit curious as to why the above screenshot says `SodiumRenderer` even though the glass textures are clearly connected.

**Comment by douira** [comment]
Because you probably have Continuity installed.

**Comment by kazarmy** [comment]
I do, but doesn't it need Indium and by extension the Indium renderer?

**Comment by Lolothepro** [comment]
> I do, but doesn't it need Indium and by extension the Indium renderer?

No

**Comment by kazarmy** [comment]
> > I do, but doesn't it need Indium and by extension the Indium renderer?
> 
> No

Hmm, this is new with Sodium 0.6

**Comment by ghost** [comment]
> I do, but doesn't it need Indium and by extension the Indium renderer?

No, Sodium 0.6 has FRAPI support so Indium is not necessary anymore.
