### ISSUE TITLE
Crash when a graphics adapter is present which does not support OpenGL

### ISSUE THREAD

**Issue by D2Lx0wse** [jellysquid3/Sodium#2591]
### Bug Description

The game crashes with this error
`A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'sodium'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:160)
	... 5 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.matches(String)" because "driverName" is null
	at me.jellysquid.mods.sodium.client.compatibility.checks.PreLaunchChecks.findIntelDriverMatchingBug899(PreLaunchChecks.java:123)
	at me.jellysquid.mods.sodium.client.compatibility.checks.PreLaunchChecks.onGameInit(PreLaunchChecks.java:60)
	at me.jellysquid.mods.sodium.client.SodiumPreLaunch.onPreLaunch(SodiumPreLaunch.java:13)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 6 more
`

### Reproduction Steps

1. Download ARM64 Prism Launcher and a ARM64 build of java 21 on a snapdragon pc
2. Install minecraft 1.21 with fabric and the attached mods
![image](https://github.com/CaffeineMC/sodium-fabric/assets/92229936/9fbfe2f7-a41a-434f-8bea-01d86825f721) 
 
![image](https://github.com/CaffeineMC/sodium-fabric/assets/92229936/5fd47e7d-f50e-47ec-b10b-5e2b28f9c3a8)

3. Launch the game
4. Fabric crashes

### Log File

[latest.log](https://github.com/user-attachments/files/16120117/latest.log)

### Crash Report

The game does not produce a crash report, or gets to the main menu. Here's my specs?!?!?
![image](https://github.com/CaffeineMC/sodium-fabric/assets/92229936/06365e5f-29ea-4ae7-ab6f-338e6fa01977)
![image](https://github.com/CaffeineMC/sodium-fabric/assets/92229936/18a40bb9-9e65-41b8-bb12-44f1b12efc50)
the opengl is not the best but it say it's compatible

**Comment by jellysquid3** [comment]
Are you not using the latest version of Sodium? Please upload the _entire_ log file, not the snippet. It has critical information.

**Comment by jellysquid3** [comment]
We do not have anyone on our team who has access to these recent laptops with Qualcomm's Snapdragon chips. It will be impossible for anyone to debug this without the information that our issue template asks for.

**Comment by D2Lx0wse** [comment]
This is not a X elite laptop, as you can see in the specs, it's from 2022, also minecraft only produced the log I attached as file as it crashed so early, I tried to send all info I could

**Comment by D2Lx0wse** [comment]
![image](https://github.com/CaffeineMC/sodium-fabric/assets/92229936/264ac2b2-2121-4612-b5bb-decde180ce2c)

**Comment by jellysquid3** [comment]
Sorry. The email that was sent to me about your issue did not include the link to the log file for some reason.

**Comment by jellysquid3** [comment]
```
[19:14:16] [main/INFO]: Found graphics adapter: AdapterInfo{vendor=UNKNOWN, description='Adreno 680', adapterType=0x0000230B, openglIcdFilePath='null', openglIcdVersion=null}
```

Do the Adreno drivers _actually_ support OpenGL? It seems like they don't, and Windows is using a translation layer on top of it (OpenGL on D3D12, probably), which confuses Sodium...

**Comment by jellysquid3** [comment]
I think the graphics adapter probe in Sodium is just bugged, and it doesn't account for the possibility that a GPU may not actually support OpenGL.

Marking [these fields](https://github.com/CaffeineMC/sodium-fabric/blob/db7c77a0960c166e4177acbbabd892167fcd0271/src/main/java/net/caffeinemc/mods/sodium/client/platform/windows/api/d3dkmt/D3DKMT.java#L195-L196) as `@Nullable` and then adding null-checks where the fields are accessed would likely be enough.

**Comment by D2Lx0wse** [comment]
I have no idea, if sodium checked if the driver name string was null 
![image](https://github.com/CaffeineMC/sodium-fabric/assets/92229936/a516c59d-21b6-4434-bb88-0a82c2b150f6)
(since thats where it's erroring) could it launch? I acknowledge it'd possibly be broken cause no translation layer- oh you said it as I was typing

**Comment by ading2210** [comment]
I can confirm that this issue also occurs on the new Qualcomm Snapdragon X Elite (X1E78100) systems. 
![image](https://github.com/user-attachments/assets/0e5ec10c-c539-4fe9-ad95-16e20aba938f)

Here are my system specs:
![image](https://github.com/user-attachments/assets/7c69b599-0212-4aeb-ba5d-d54027f66260)

**Comment by ading2210** [comment]
Also, it appears that OpenGL *does* work, since vanilla 1.21 runs just fine. It appears to be using Mesa for the OpenGL translation layer as well. 

![image](https://github.com/user-attachments/assets/9b34ba2d-8e2e-40da-828a-02241d2448b1)

**Comment by asumagic** [comment]
Is there a chance that the translation layers belong in a different "virtual" adapter? I'm curious how the full virtual adapter list looks like, null exception aside. Otherwise, is there really no way to poll information on GLon12 support for the given platform?

FWIW, internally, on context creation, it does seem to make a difference between a native OpenGL driver and GLon12: https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmthk/ne-d3dkmthk-_d3dkmt_clienthint  
(Although this specific hint enum seems irrelevant for sodium.)

**Comment by ading2210** [comment]
I built the latest version of the mod using Intellij, and it somehow isn't crashing? The `driverName` is detected correctly here, but launching the game through PrismLauncher still crashes. 

![image](https://github.com/user-attachments/assets/b7527ec3-3c84-402a-910c-6962381024e5)

Regardless of this weird behavior, I believe it can be fixed easily by just checking if `driverName` is null, and continuing the loop if it is. The function that it's crashing in seems to only be for detecting Intel drivers, so this shouldn't break any existing behavior.

**Comment by jellysquid3** [comment]
I'm nominating this issue for critical prioritization so that we can make a backport exception for older versions.

**Comment by jellysquid3** [comment]
The mod crashing on new hardware platforms is not acceptable for me and this problem is likely manifesting elsewhere with drivers that don't actually support OpenGL natively.

**Comment by jellysquid3** [comment]
If you run into this issue, you can add the following entry to your JVM arguments:

```
-Dsodium.checks.issue899=false
```

This disables the broken pre-launch check and allows the game to launch (somewhat) normally.
