### ISSUE TITLE
Block rendering issue

### ISSUE THREAD

**Issue by DantUwU** [jellysquid3/Sodium#2592]
### Bug Description

I have had this issue for a long time with sodium, but never knew where to ask for help.
When I open a world, multyplayer or single player, whenever my pov sees any type of block update it glictches for a milisecond and makes one or two chuncks disappear. This is in pvp or in playing the game itself gets frustrating. The clip I attached was only with sodium mod on 1.20.1 fabric (no toher mods).
(Ps: This doesnt append when I play Minecraft with no mods)
Please, help me solve my issue.

https://github.com/CaffeineMC/sodium-fabric/assets/175077278/58c2baaa-29ae-4c3f-9d54-5035eba28766

### Reproduction Steps

I didnt see any videos or anything on this, but here's what I do:
-Open Minecraft with the sodium mod
-Load any type of world
-Place blocks and the visual glitche

### Log File

[2024-07-09-2.log.gz](https://github.com/user-attachments/files/16136724/2024-07-09-2.log.gz)

Here if necessary.

### Crash Report

[crash-2024-07-09_03.55.10-client.txt](https://github.com/user-attachments/files/16136683/crash-2024-07-09_03.55.10-client.txt)

I don't know what this heps but there you go.

**Comment by DantUwU** [comment]
sorry for any writing mistakes, didn't sleep that well

**Comment by jellysquid3** [comment]
Please read the [Driver Compatibility](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility) documentation. You have an Intel Icelake CPU with a buggy graphics driver that must be updated to fix this issue.

**Comment by DantUwU** [comment]
thanks for quick awnser, I already instaled it, but now I don't know what to do, its still flickering? I'm sorry for the incovinience

**Comment by DantUwU** [comment]
OMG forget it lol, I just needed to reset my pc, thank u so much
