### ISSUE TITLE
Text overlaps when f3 is activated

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2594]
### Request Description

![изображение](https://github.com/CaffeineMC/sodium-fabric/assets/134782072/a046b5f6-3f81-46d8-b86c-643f1cd8d589)
![изображение](https://github.com/CaffeineMC/sodium-fabric/assets/134782072/62e04074-fdb1-4773-8903-019a6f7f56b1)

I believe this is a potential issue and it would be beneficial to implement a condition in the code that disables the options "Show FPS", "Extended FPS", and "Coordinates" when the F3 function is enabled for the player.

**Comment by Felix14-v2** [comment]
These features are from the Sodium Extra mod. Please, report this bug here instead:
https://github.com/FlashyReese/sodium-extra-fabric/issues
