### ISSUE TITLE
Modrinth pages contain outdated/incorrect links

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2596]
### Bug Description

On the Modrinth page for Sodium (CurseForge is fine), the issue tracker hyperlink under "🐛 How to Report Issues", points to jellysquid3/sodium-fabric, instead of CaffeineMC/sodium-fabric. All other CaffeineMC projects appear to have up-to-date links, except the "the wiki entry" link in Lithium, though that redirects to the right CaffeineMC page, as opposed to the Sodium link.

### Reproduction Steps

Simply open the Sodium page on Modrinth and go to the "🐛 How to Report Issues" section.

![](https://i.imgur.com/Uz9LKfu.png)

### Log File

N/A

### Crash Report

N/A

**Comment by jellysquid3** [comment]
Thanks. Fixed. Apparently when I forked the repository, it broke the redirect, and people have been reporting issues to the wrong repository for a while now.
