### ISSUE TITLE
Unexpected Colisions

### ISSUE THREAD

**Issue by BcMedia** [jellysquid3/Sodium#26]
### Expected Behavior
Let it go normal

### Actual Behavior
Sometimes i get colisions from anything.

### Reproduction Steps
Simply i go moving in my wold and i get colissions with the air.

### System Information
Spigot Server 1.15.2

- Java Version: 8 update 251
- CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 CPUs), ~2.7GHz
- GPU: NVIDIA GeForce 920MX

**Comment by jellysquid3** [comment]
It looks like Sodium's chunk management class is broken on non-vanilla servers for some reason. Further investigation is required.

**Comment by jellysquid3** [comment]
Fixed with https://github.com/jellysquid3/sodium-fabric/commit/842dd3f3a9bff82aef99e1a6da9cf6a6dfeae551.
