### ISSUE TITLE
Blindness corrupts GUI

### ISSUE THREAD

**Issue by adambyle** [jellysquid3/Sodium#260]
### Expected Behavior
The blindness status effect should only blind past the 3 block radius of visible blocks

### Actual Behavior
No blocks are visible, all icons in the hotbar and inventory are colored black.

### Reproduction Steps
Give yourself the blindness status effect. (/effect give @s blindness)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: 8
- CPU: 8x Intel Core i5-1035 @ 1GHz
- GPU: Unable to locate information

**Comment by amnotbananaama** [comment]
Does <https://bugs.mojang.com/browse/MC-165208> describe your issue?

**Comment by adambyle** [comment]
Yes, it does. Thank you.
