### ISSUE TITLE
Unsupported driver without integrated graphics

### ISSUE THREAD

**Issue by PVMChannel** [jellysquid3/Sodium#2602]
### Bug Description

it says unsupported driver, the thing is that required version is `10.18.10.5161` and installed version is `43.58`
![image](https://github.com/user-attachments/assets/8c2db3e2-cd5a-490e-9c42-2e7dfa738508)
another thing is that when i go to the windows icon -> right click -> device manager, there are graphic adapters, theres my GPU and integrated graphics, if i right click on the integrated graphics and uninstall it, sodium works normally (but it reinstalls every restart)
i am not using integrated graphics, also i dont want to disable integrated graphics because i almost bricked my pc because of it
if this is a bad report then im sorry

### Reproduction Steps

i dont know how you could reproduce it

### Log File

[latest.log](https://github.com/user-attachments/files/16236833/latest.log)

### Crash Report

i dont think its needed but heres a random crash report from the folder (i dont know how i should crash the game when it doesnt start)
[crash-2024-02-15_13.08.53-client.txt](https://github.com/user-attachments/files/16236851/crash-2024-02-15_13.08.53-client.txt)

**Comment by jellysquid3** [comment]
You MUST click the "Help" button and [read the instructions](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility#windows-intel-gen7). You have Intel Gen7 graphics and the driver must be updated, even if you are not rendering with it.
