### ISSUE TITLE
Не прогрузаются блоки в мире и на серверах

### ISSUE THREAD

**Issue by Kola228pepsi1** [jellysquid3/Sodium#2603]
### Bug Description

Я установил мод и у меня пропали все блоки но у них есть текстур в инвентаре и т.д кроме в мире я играю на телефоне в pojavlauncher

https://github.com/user-attachments/assets/014ec7d0-144c-4819-9d1b-691d483f7419

 в обычном Майне без мода все норм

### Reproduction Steps

Нету

### Log File

Сбоя нет просто мод не прогрузает  текстура мира

### Crash Report

Нету

**Comment by jellysquid3** [comment]
PojavLauncher is not supported and does not work correctly.

PojavLauncher не поддерживается и работает некорректно.
