### ISSUE TITLE
Те кто играет на фабрик модс pojavlauncher

### ISSUE THREAD

**Issue by Kola228pepsi1** [jellysquid3/Sodium#2605]
### Request Description

Здравствуйте разработчики можете обновить мод sodium? для pojavlauncher
Я буду вам благодарен вы поможете не только мне но еще людям которые играют на pojavlauncher

**Comment by Felix14-v2** [comment]
Android drivers doesn't fully support OpenGL 3.3, so you can't use Sodium there. You have to wait until someone make renderer conformant to OpenGL 3.3 (which can happen in the near future).

<details> <summary>Перевод</summary>
Дайверы на Android полноценно не поддерживают OpenGL 3.3, так что Sodium с ними нормально не заработает. Придётся подождать, когда кто-нибудь напишет драйвер, соответствующий требованиям OpenGL 3.3 (что, скажу по секрету, может произойти в скором времени).
</details>
