### ISSUE TITLE
Make setting UI more like a minecraft native UI

### ISSUE THREAD

**Issue by kevin930321** [jellysquid3/Sodium#2607]
### Request Description

It would be better if the setting ui gets more minecraft style, just like optifine did.

**Comment by jellysquid3** [comment]
No, it wouldn't be.

**Comment by ghost** [comment]
> ### Request Description
> 
> It would be better if the setting ui gets more minecraft style, just like optifine did.

The current UI (especially with RSO) is much more readable and accessible. OptiFine's way of handling additional menu options feels more like Vanilla at the cost of being terrible to navigate.
