### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by CheapKitForSael** [jellysquid3/Sodium#2608]
### Bug Description

![image](https://github.com/user-attachments/assets/9c6efc6d-cceb-42eb-8995-0c82f31beac9)
![image](https://github.com/user-attachments/assets/c353226d-da1e-49b2-a5f6-8fd7a73edfe6)
My sodium advance option is like that, isnt it suppose to look like this? 
![image](https://github.com/user-attachments/assets/d76b2c40-80d1-435f-848f-200ffee4c824)
https://www.reddit.com/r/Amd/comments/l8e9d6/supercharge_your_fps_in_minecraft_java_opengl_by/

### Reproduction Steps

non

### Log File

non

### Crash Report

non

**Comment by Lolothepro** [comment]
...It's with Sodium Extra...

**Comment by Lolothepro** [comment]
also,

> This issue tracker is not intended for support requests!

**Comment by CheapKitForSael** [comment]
![image](https://github.com/user-attachments/assets/57117400-1c85-4944-a8b5-1058f62b9610)
 with no sodium extra

**Comment by CheapKitForSael** [comment]
![image](https://github.com/user-attachments/assets/a4714496-599f-42ca-8417-667591e03a12)
with no sodium extra

**Comment by Lolothepro** [comment]
Install Sodium Extra

**Comment by CheapKitForSael** [comment]
![image](https://github.com/user-attachments/assets/c49b5e5d-1334-4e5b-abb6-43e66a7d6b0b)
yea this has sodium extra

**Comment by Lolothepro** [comment]
And since you're using Minecraft 1.16.5, it's normal that there's no “Persistant Mapping” setting.

**Comment by CheapKitForSael** [comment]
its 1.20.4 tf

**Comment by Lolothepro** [comment]
and the Swap <-> Async setting no longer exists

**Comment by CheapKitForSael** [comment]
![image](https://github.com/user-attachments/assets/b3212795-af4b-4ae8-9af7-fb681464e7bb)
this is the options im missing you got it wrong

**Comment by Lolothepro** [comment]
> ![image](https://private-user-images.githubusercontent.com/175939172/349930754-b3212795-af4b-4ae8-9af7-fb681464e7bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDA5OTcsIm5iZiI6MTcyMTMwMDY5NywicGF0aCI6Ii8xNzU5MzkxNzIvMzQ5OTMwNzU0LWIzMjEyNzk1LWFmNGItNGFlOC05YWY3LWZiNjgxNDY0ZTdiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxOFQxMTA0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTE1MDZkMGI5YmZlZjdiMDFlYmQxMGZhNThlZDUyMDUzNWIxMjdlNDQ3YmM5ZmRkNTc0YWY4Nzg4OTkzY2QyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XsCClyLGir3LQmnzruobyRD7G6E3nKu6d_Kia0pLcD8) this is the options im missing you got it wrong

This is a screenshot of Sodium for Minecraft 1.16.5, not for Minecraft 1.20.4

**Comment by CheapKitForSael** [comment]
Why did they remove the chunk rendering option

**Comment by Lolothepro** [comment]
> Why did they remove the chunk rendering option

idk

**Comment by ghost** [comment]
> Why did they remove the chunk rendering option

Because it was not necessary anymore. Multidraw became the default.

**Comment by jellysquid3** [comment]
This is not a support forum. The issue template is very clear about this, yet you purposefully circumvented it. Don't do that again.
