### ISSUE TITLE
Could you add DLSS and Ray tracing support 

### ISSUE THREAD

**Issue by Thunderrock424242** [jellysquid3/Sodium#2611]
### Request Description

adding this would provide a HUGE boost of performance and I think its possible.

**Comment by jellysquid3** [comment]
Duplicate of #796, #707, #2520, #1075, etc...

There is an open issue #2362 here about implementing render scaling.

**Comment by xboct02** [comment]
The developer does not have the money to implement the algorithm of the leading company, but he can make his own compatible version.
