### ISSUE TITLE
Sodium tabs' text broken

### ISSUE THREAD

**Issue by ItsTheCandyKing** [jellysquid3/Sodium#2621]
### Bug Description

For some reason, all the text on the Sodium-made tabs are shown as the files
![image](https://github.com/user-attachments/assets/b47009a8-98b7-4bf8-8e75-ff4b6e585fef)

### Reproduction Steps

Made a Modrinth 1.21 Instance the day 1.21 came out, updated all the mods today and launched it, then went into Video Settings and bam, that's what it looked like

### Log File

Don't know, I'm sorry if this is needed to fix this, but I don't know what to look for

### Crash Report

Same for the Log File, I don't know 😢

**Comment by ghost** [comment]
.minecraft -> logs -> latest.log

Upload that to mclo.gs or pastebin and send the link here.

That said, it most likely isn't a Sodium issue but rather something caused by another mod (Language Reload maybe? Assuming you have that)

**Comment by ItsTheCandyKing** [comment]
Never mind, just re-made the instance and working all fine now. I did what you said though and yes, it worked, so thanks!
