### ISSUE TITLE
Incompatibility with Fabric API, FluidRenderHandler.getFluidColor is not called.

### ISSUE THREAD

**Issue by MehVahdJukaar** [jellysquid3/Sodium#2626]
### Bug Description

When registering a FluidRenderHandler for a fluid, say Fluids.FLOWING_WATER, sodium does not call the renderHandler .getFluidColor function to calculate its color, making sodium break this part of fabric api.

### Reproduction Steps

Install sodium (1.21 fabric latest version)
register a fluid render handler for water for example. Its getFluidSprites method will be called, prooving its been registerd correctly. The getColor call however will not

### Log File

no log as this is not a crash

### Crash Report

no log as this is not a crash

**Comment by jellysquid3** [comment]
Is this not the same issue as https://github.com/CaffeineMC/sodium-fabric/issues/2298?

**Comment by MehVahdJukaar** [comment]
oh it indeed is. Forgot i ever that that. ill close this
