### ISSUE TITLE
Shader compilation failed

### ISSUE THREAD

**Issue by tokenornottoken** [jellysquid3/Sodium#2627]
### Bug Description

Minecraft crashes with a black screen whenever I try to join single-player or multiplayer. By the way, I have Iris installed alongside Sodium.
![image](https://github.com/user-attachments/assets/f7757fe8-998f-4375-924c-a433274f3d55)

### Reproduction Steps

1. Launch Minecraft 
2. Join Singleplayer/Multiplayer game
3. Crash

### Log File

[2024-07-29-7.log.gz](https://github.com/user-attachments/files/16415658/2024-07-29-7.log.gz)

### Crash Report

[crash-2024-07-29_23.31.09-client.txt](https://github.com/user-attachments/files/16415662/crash-2024-07-29_23.31.09-client.txt)

**Comment by Lolothepro** [comment]
Iris bug

**Comment by tokenornottoken** [comment]
> Iris bug

What can I do to fix this issue, then?

**Comment by pajicadvance** [comment]
Try downloading the latest version of the shader pack you're using, if you're still getting crashes report to Iris.
