### ISSUE TITLE
detail name game crash sodium mode )

### ISSUE THREAD

**Issue by forhadopahmed** [jellysquid3/Sodium#2628]
### Request Description

**Device**: Vivo Y21A
**Android Version**: 11
**Mod**: Sodium
**App**: PojavLauncher (available on Google Play)
**Issue**: The game crashes when entering a world with the Sodium mod enabled. 

**Steps to Reproduce**:
1. Install PojavLauncher on Vivo Y21A.
2. Install Sodium mod.
3. Launch the game and enter any world with Sodium mod enabled.

**Additional Information**:
- I have updated my graphics drivers.
- I have tried reinstalling both the mod and the app.

Any help in resolving this issue would be greatly appreciated.

**Comment by ghost** [comment]
PojavLauncher is not supported

**Comment by pajicadvance** [comment]
From https://modrinth.com/mod/sodium#hardware-compatibility:

> Android devices which use OpenGL translation layers (such as GL4ES, ANGLE, etc) are not supported and will very likely not work with Sodium. These translation layers do not implement required functionality and they suffer from underlying driver bugs which cannot be worked around.
