### ISSUE TITLE
Features list

### ISSUE THREAD

**Issue by private-effort** [jellysquid3/Sodium#263]
1. Cloud height - Set the height of clouds in blocks
2. Add zoom - I think everything is clear here
3. Fog: off - https://github.com/jellysquid3/sodium-fabric/issues/262

That's all, thanks for the great modification.

**Comment by FlashyReese** [comment]
Sodium is focused on optimization only(I may be wrong, and if I am I think Jelly is more focused on optimizing the game). You can take a look [here](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754) for those mods that are compatible with Sodium.

**Comment by jellysquid3** [comment]
Echoing FlashyReese's comment here.
