### ISSUE TITLE
FullBright is not compatible

### ISSUE THREAD

**Issue by HerixLord** [jellysquid3/Sodium#2633]
### Bug Description

So I'm using a lot of resource pack when I'm mining or building to help me with those activities and one of them is fullbright how ever every time I add full bright it says error message

### Reproduction Steps

I have just added sodium and when I activate fullbright it's just not working

### Log File

[latest.log](https://github.com/user-attachments/files/16488046/latest.log)

### Crash Report

[crash-2024-08-04_17.30.51-client.txt](https://github.com/user-attachments/files/16488081/crash-2024-08-04_17.30.51-client.txt)

**Comment by Timolino456** [comment]
That's because these resource packs use core shaders to achieve this effect, which Sodium does not support for technical reasons. Use a mod that achieves the same effect, such as Gamma Utils, instead.

**Comment by jellysquid3** [comment]
See the documentation for [Resource Packs](https://github.com/CaffeineMC/sodium-fabric/wiki/Resource-Packs). We make some suggestions for full-bright mods.

**Comment by HerixLord** [comment]
Thanks for your response and I try your suggestion.

Dňa ne 4. 8. 2024, 19:22 JellySquid ***@***.***> napísal(a):
