### ISSUE TITLE
ASUS GPU Tweak III causes graphical corruption and error log spam

### ISSUE THREAD

**Issue by Neyji** [jellysquid3/Sodium#2637]
### Bug Description

My Textures keep Turning Black when i enter Water or the Nether. Entity Textures don't turn black

![2024-08-05_13 46 30](https://github.com/user-attachments/assets/b9c17b07-eedb-4e26-97a7-ba5943a81ed0)
![2024-08-05_13 46 32](https://github.com/user-attachments/assets/281dcf4d-422b-4213-880c-896282d5e36e)
![2024-08-05_13 46 47](https://github.com/user-attachments/assets/92724182-487e-4ce7-aa3f-ccd6221c46bc)
![2024-08-05_13 47 01](https://github.com/user-attachments/assets/3e51232b-81d0-42f7-b906-a1e3674de69e)

### Reproduction Steps

fabric version 1.20.4 0.15.10
I am using Sodium version mc1.20.4-0.5.8
only mod i used with this was Mod Menu
<img width="914" alt="2024-08-05 13_55_20-NVIDIA GeForce Overlay DT" src="https://github.com/user-attachments/assets/80c40dde-462f-41c8-a8d2-7a3a6fb75ff2">

### Log File

[latest.log](https://github.com/user-attachments/files/16495245/latest.log)

### Crash Report

[crash-2024-08-05_13.53.05-client.txt](https://github.com/user-attachments/files/16495256/crash-2024-08-05_13.53.05-client.txt)

**Comment by Neyji** [comment]
wait why did i add the needs triage label i didn't mean to i guess i accidentally clicked it while looking at the labels

**Comment by MCRcortex** [comment]
The label is automatically added

**Comment by MCRcortex** [comment]
Do you have RTSS installed or some other overlay program active? try removing/disabling it

**Comment by Neyji** [comment]
I have Uninstalled Both RTSS and Overwolf now but it Still is turning Textures black

**Comment by jellysquid3** [comment]
Something is injecting itself into the game and causing bugs. This is typical of overlay software and other software that renders on top of the game.

From your crash report, it looks like "ASUS GPU Tweak II" or the "Overwolf Overlay" are the most likely suspects. Please try disabling/uninstalling them and see if the issue persists.

If that still doesn't fix your problem, then upload a new crash report file (as the issue template asks above, with the mentioned software not running) so we can look into it further.

**Comment by Neyji** [comment]
Here the new Crash Report as requested without GPU Tweak and Overwolf, sadly this still didn't fix it

[crash-2024-08-05_19.09.53-client.txt](https://github.com/user-attachments/files/16500713/crash-2024-08-05_19.09.53-client.txt)

hope this helps

**Comment by jellysquid3** [comment]
Unfortunately, the log file shows that ASUS GPU Tweak II is still loaded into the game:

```
GTIII-OSD64-GL.dll:GTIII-OSD Dynamic Link Library:3.0.5.6:ASUSTeK COMPUTER INC.
GTIII-OSD64-VK.dll:GTIII-OSD Dynamic Link Library:3.0.5.6:ASUSTeK COMPUTER INC
GTIII-OSD64.dll:GTIII-OSD Dynamic Link Library(Win10OrGreater):3.0.5.6:ASUSTeK COMPUTER INC.
```

The log file complains that something is using legacy OpenGL functions, but Sodium contains no such usage of those functions. So the only explanation is that some other software on your computer is interfering with the rendering of the game.

I would recommend you uninstall the ASUS GPU Tweak III application entirely from your computer, and reboot afterwards.

**Comment by Neyji** [comment]
Huh so just turning it off didn't work but uninsalling did it so i guess case closed

Thanks for the help

**Comment by jellysquid3** [comment]
I'd still like to keep this issue open, because we can probably implement some kind of detection/workaround in Sodium to prevent this from happening to other people.

**Comment by jellysquid3** [comment]
We have had community members try to reproduce this problem and they can confirm that ASUS's GPU Tweak III is completely broken on AMD and NVIDIA GPUs, and causes crashes/corruption/log spam _even without_ Sodium installed.

**Comment by jellysquid3** [comment]
Future versions of Sodium ([commit](https://github.com/CaffeineMC/sodium-fabric/commit/1f5a13f5de154b59f7c8d93b856312da4a005f7c)) will show an error message at startup if ASUS GPU Tweak III is loaded into Minecraft, and provide instructions on how to prevent issues.
