### ISSUE TITLE
1.16.2?

### ISSUE THREAD

**Issue by TikTokdontdie** [jellysquid3/Sodium#264]
### Reproduction Steps
I know sodium is meant for 1.16.1, however, I was hoping if you know a way to get it to work with 1.16.2? Or is there an updated version on its way? Using MultiMC, I installed the latest versions of Fabric, Fabric API, as well as Sodium. The game crashes upon starting.

### Crash Report File
https://gist.github.com/TikTokdontdie/deb5efe0f0d4d357b6cd6e007a38a057

I'll continue to use 1.16.1 for now, but was just wondering if there was a 1.16.2 version on its way. Cheers <3

**Comment by FlashyReese** [comment]
There is an 1.16.2 on it's way, no ETA.

**Comment by DrBlindriver** [comment]
There seemed to be unofficial version of Sodium for 1.16.2 released [ishlandbukkit:1.16.x/dev](url)

**Comment by FishyFissh** [comment]
> There seemed to be unofficial version of Sodium for 1.16.2 released [ishlandbukkit:1.16.x/dev](url)

Yeah but it doesn't render properly. On fabulous graphics most transparent blocks just disappear, and on fancy they don't look right.

**Comment by FishyFissh** [comment]
> There seemed to be unofficial version of Sodium for 1.16.2 released [ishlandbukkit:1.16.x/dev](url)

It doesn't render properly, though.

**Comment by ThexXTURBOXx** [comment]
It renders as properly as the current dev branch for 1.16.1.
