### ISSUE TITLE
Revert use of 2.10.10.10 vertex attributes

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#2640]
[This change](https://github.com/CaffeineMC/sodium-fabric/commit/179167240edac4ccc6116d4b1f20d48ed29716e9) performs poorly on some GPUs, particularly on macOS. Let's revert it.

**Comment by douira** [comment]
Does this just require a clean revert or is there more to this? If so, I can be assigned.

**Comment by jellysquid3** [comment]
It's a clean revert, but I think actually the change has [already been rolled up](https://github.com/IMS212/sodium-fabric/blob/2da614272192b768e37532adf45aa99d5b81900f/common/src/main/resources/assets/sodium/shaders/include/chunk_vertex.glsl#L41-L46) into the multi-loader branch.

**Comment by douira** [comment]
Looks like it's not using 2.10.10.10 on that branch so if the big merge actually reverts this on dev it would just happen that way?

**Comment by jellysquid3** [comment]
Yeah. We'll just close this when the other branch is merged in.

**Comment by jellysquid3** [comment]
Resolved with https://github.com/CaffeineMC/sodium-fabric/commit/d2df1838a36abf75198440d03f8f2c08085f395b.
