### ISSUE TITLE
Change the project description on CurseForge and Modrinth to not be misleading

### ISSUE THREAD

**Issue by TelepathicGrunt** [jellysquid3/Sodium#2643]
### Request Description

Currently, Sodium project description states that it is the "fastest" and "most compatible" rendering engine there is.

![image](https://github.com/user-attachments/assets/ae2bf05f-d3b1-4958-8e41-5dc386c851b0)
![image](https://github.com/user-attachments/assets/ab2427dd-d229-4320-af0b-4b89022a2ba2)

Claims of fastest is always a very bold and risky stance to take. But the real kicker is the compatibility claim. This claim is strictly false.

Sodium requires Indium currently to actually run Fabric Rendering API. Without Indium, Sodium breaks so many mods on fabric. As a result, this claim of most compatible is false given that even Optifine has broken my mod far less times than Sodium ever has even *with* Indium. And there are other rendering optimizing mods out there as well that seems to at least try to not break the modloader's APIs.

My suggestion, remove the "most compatible" part of the mod's description as it is strictly untrue until Sodium either does 2 things:

- Jar-in-jar Indium

- Fully releases a jar onto CurseForge/Modrinth that actual implements the Fabric Rendering API.

Even then, stating "most compatible" can still be a stretch but right now, it is a problematic claim that cannot be supported with the experiences players and other modders have with Sodium.

**Comment by douira** [comment]
Will be resolved by sodium 0.6

**Comment by jellysquid3** [comment]
There will be no change to the project description.

**Comment by jellysquid3** [comment]
I'm locking this issue before it gets out of hand, since people are linking it around trying to generate completely unnecessary engagement on it.
