### ISSUE TITLE
Rename Sodium repository on GitHub

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#2647]
We're no longer just a Fabric mod. Let's update the name. But this may have some consequences. Links to the repository/etc from the mod need to be updated.

**Comment by Gaming32** [comment]
I will note that GitHub will automatically set up redirects, so not every link needs to be updated immediately.

**Comment by TheNukeLore** [comment]
Would the name just shorten down to "sodium"? Or would alternatives be considered such as "sodium-renderer"

**Comment by Ecorous** [comment]
I would suggest either `sodium-mod` or `sodium`. And yeah, github redirects should sort you out for a good while

**Comment by diaphragm-workplace** [comment]
`sodium-the-videogame-modification-not-the-element` /s

**Comment by jellysquid3** [comment]
Resolved, renamed the project to `CaffeineMC/sodium`.
