### ISSUE TITLE
Incorrectly identifying my driver version

### ISSUE THREAD

**Issue by meee57** [jellysquid3/Sodium#2652]
### Bug Description

When I try to boot up the game, I get the error "Sodium Renderer - Unsupported Driver" with the details "The game failed to start because the currently installed NVIDIA Graphics Driver is not compatible. Installed Version: 31.0.15.2897 Required Version: 536.23 (or newer) You must update your graphics card driver in order to continue.

I don't know where it's pulling this version number from, but according to my Nvidia GeForce Experience app I have version 560.61 of my driver, which is a higher number than the required version so it should be fine.

I have a decent amount of tech knowledge but I'm new to Windows so I really don't know what went wrong and why it pulled the wrong version number here.

### Reproduction Steps

Mods:
-sodium-fabric-0.5.11+mc1.21.jar
-fabric-api-0.102.0+1.21.jar

Fabric Version:
-0.15.11-1.12

Computer Specs:
Processor	13th Gen Intel(R) Core(TM) i9-13900H   2.60 GHz
Installed RAM	16.0 GB (15.6 GB usable)
Device ID	F4090D7C-EBC3-4535-9F50-F293A6B10640
Product ID	00342-21194-36735-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen and touch support with 10 touch points

Windows Version:
Edition	Windows 11 Home
Version	23H2
Installed on	‎7/‎4/‎2024
OS build	22631.3880
Experience	Windows Feature Experience Pack 1000.22700.1020.0

### Log File

No log file seems to be recorded probably because it blocked it from booting up the game to begin with

### Crash Report

I don't have a crash reports folder in my .minecraft folder for some reason so no crash report

**Comment by jellysquid3** [comment]
There is a bug in Sodium currently where the version number it gives in the message is not "useful", but it is (technically) correct. The Windows driver version 31.0.15.2897 corresponds to NVIDIA driver version 528.97.

Most likely, the GeForce Experience application is wrong, or you have other (older) drivers also installed. You should download the latest driver manually from [NVIDIA's website](https://www.nvidia.com/en-us/drivers/) and perform a clean installation to resolve the problem.

But without a log file (`.minecraft/logs/latest.log`), we can't help you further.
