### ISSUE TITLE
Water rendering behind stained glass

### ISSUE THREAD

**Issue by Zeprix** [jellysquid3/Sodium#2654]
### Bug Description

Unlike regular glass blocks, water placed behind stained glass has bugged rendering which makes the texture chopped and not visible from all sides. This sort of issue doesn't happen with lava.
![2024-08-10_17 40 38](https://github.com/user-attachments/assets/57e1d50e-8ff4-425e-b615-f754c14545a7)
![2024-08-10_17 40 49](https://github.com/user-attachments/assets/d6fb31b9-23a0-47b8-af6c-f7f975270db3)

### Reproduction Steps

Build a water column with stained glass like the pictures attached in the bug description.

### Log File

[atlauncher.log](https://github.com/user-attachments/files/16569934/atlauncher.log)

### Crash Report

[crash-2024-08-10_17.43.33-client.txt](https://github.com/user-attachments/files/16569936/crash-2024-08-10_17.43.33-client.txt)

**Comment by Lolothepro** [comment]
duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/38

**Comment by Timolino456** [comment]
Duplicate of #38, will be fixed in Sodium 0.6

**Comment by Zeprix** [comment]
Duplicate
