### ISSUE TITLE
Using Architectury's Gradle Plugin for multiplatform services

### ISSUE THREAD

**Issue by dynpatch** [jellysquid3/Sodium#2656]
### Request Description

Instead of using the Service API in [net/caffeinemc/mods/sodium/client/services](https://github.com/CaffeineMC/sodium-fabric/tree/dev/common/src/main/java/net/caffeinemc/mods/sodium/client/services), how about using [Architectury's multiplatform gradle plugin](https://github.com/architectury/architectury-plugin/)? 

It would allow common usage of `@Environment` (see https://docs.architectury.dev/plugin/introduction#things_that_are_transformed), and use the `@ExpectPlatform` mechanism (see 
https://docs.architectury.dev/plugin/expect_platform) to directly allow platform projects to provide their services implementation at compile time.

Note that the documentation repo has since been archived, but I believe the functionnality is still available.

**Comment by IMS212** [comment]
We do not wish to rely on Architectury Loom; the build script is designed with only loader-native tooling.
