### ISSUE TITLE
Z-fighting issue with waterlogged stairs.

### ISSUE THREAD

**Issue by ohhboi427** [jellysquid3/Sodium#2658]
### Bug Description

Z-fighting is occurring on waterlogged stairs. It get's worse the farther I get from the stairs.

![image](https://github.com/user-attachments/assets/b44be64a-71c8-4296-ae08-d8eb6276d0a3)

Minecraft 1.21, Sodium 0.5.11

### Reproduction Steps

Have a waterlogged stair block and get far away from it. It starts happening at around 16 blocks distance.

### Log File

[latest.log](https://github.com/user-attachments/files/16575463/latest.log)

### Crash Report

.

**Comment by Lolothepro** [comment]
duplicate of https://github.com/CaffeineMC/sodium-fabric/issues/2606
