### ISSUE TITLE
game crashes when moving tnt

### ISSUE THREAD

**Issue by gtgjtgh** [jellysquid3/Sodium#2659]
### Bug Description

when I try to break bedrock my game crashes

### Reproduction Steps

when lighting tnt and powering piston at the same time game crashes

### Log File

[latest.log](https://github.com/user-attachments/files/16589176/latest.log)

### Crash Report

[crash-2024-08-12_17.49.02-client.txt](https://github.com/user-attachments/files/16589166/crash-2024-08-12_17.49.02-client.txt)

**Comment by douira** [comment]
Install indium

**Comment by gtgjtgh** [comment]
> Install indium

thank you it solved the problem
