### ISSUE TITLE
Minecraft stuck at Mojang screen and wouldnt launch

### ISSUE THREAD

**Issue by Owchaa** [jellysquid3/Sodium#2664]
### Bug Description

This happens randomly, when i boot up my pc there is a chance whether it will launch up the game or stuck at the mojang loading screen and crash right there
![image_2024-08-13_093840838](https://github.com/user-attachments/assets/f8cfa0b3-a686-4f8f-963c-bfb82e271df2)

### Reproduction Steps

I dont really know how this happens, it would usually work when i launch optifine and restart my pc then sodium would work. But now it wouldnt

### Log File

[2024-08-13-6.log.gz](https://github.com/user-attachments/files/16593782/2024-08-13-6.log.gz)
[latest.log](https://github.com/user-attachments/files/16593783/latest.log)

### Crash Report

[crash-2024-08-09_09.40.46-client.txt](https://github.com/user-attachments/files/16593787/crash-2024-08-09_09.40.46-client.txt)

**Comment by douira** [comment]
the mod `bettershields` comes up in your crash log. Is that possibly related? Does this go away if you remove that mod?

**Comment by MCRcortex** [comment]
Try without using feather client/launcher.
Try prism or modrinth launcher instead

**Comment by Owchaa** [comment]
> the mod `bettershields` comes up in your crash log. Is that possibly related? Does this go away if you remove that mod?

ill try to remove it

**Comment by Owchaa** [comment]
> Try without using feather client/launcher. Try prism or modrinth launcher instead

i am using the minecraft launcher

**Comment by jellysquid3** [comment]
The log file points to another mod crashing, but it's probably just that you uploaded the wrong file.

More likely, from the symptoms described, you have out of date graphics drivers. Which can be verified by looking at the crash report here:

> ig7icd64.dll:OpenGL(R) Driver for Intel(R) Graphics Accelerator:10.18.10.4252:Intel Corporation

Please see our [driver compatibility page](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility#windows-intel-gen7) on how you can fix this problem, specifically under "Intel GPUs" and "Gen7 Graphics". You must use the download we provide on that page to successfully update the graphics driver.

If you still have issues, please use the [official Discord server](https://caffeinemc.net/discord) for help, as this issue tracker is not intended for support requests.

**Comment by Owchaa** [comment]
> The log file points to another mod crashing, but it's probably just that you uploaded the wrong file.
> 
> More likely, from the symptoms described, you have out of date graphics drivers. Which can be verified by looking at the crash report here:
> 
> > ig7icd64.dll:OpenGL(R) Driver for Intel(R) Graphics Accelerator:10.18.10.4252:Intel Corporation
> 
> Please see our [driver compatibility page](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility#windows-intel-gen7) on how you can fix this problem, specifically under "Intel GPUs" and "Gen7 Graphics". You must use the download we provide on that page to successfully update the graphics driver.
> 
> If you still have issues, please use the [official Discord server](https://caffeinemc.net/discord) for help, as this issue tracker is not intended for support requests.

im gonna try that rn

**Comment by Owchaa** [comment]
> The log file points to another mod crashing, but it's probably just that you uploaded the wrong file.
> 
> More likely, from the symptoms described, you have out of date graphics drivers. Which can be verified by looking at the crash report here:
> 
> > ig7icd64.dll:OpenGL(R) Driver for Intel(R) Graphics Accelerator:10.18.10.4252:Intel Corporation
> 
> Please see our [driver compatibility page](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility#windows-intel-gen7) on how you can fix this problem, specifically under "Intel GPUs" and "Gen7 Graphics". You must use the download we provide on that page to successfully update the graphics driver.
> 
> If you still have issues, please use the [official Discord server](https://caffeinemc.net/discord) for help, as this issue tracker is not intended for support requests.
[2024-08-13-7.log.gz](https://github.com/user-attachments/files/16593816/2024-08-13-7.log.gz)

[latest.log](https://github.com/user-attachments/files/16593817/latest.log)

i dont know if this is the rigth one

**Comment by Owchaa** [comment]
> The log file points to another mod crashing, but it's probably just that you uploaded the wrong file.
> 
> More likely, from the symptoms described, you have out of date graphics drivers. Which can be verified by looking at the crash report here:
> 
> > ig7icd64.dll:OpenGL(R) Driver for Intel(R) Graphics Accelerator:10.18.10.4252:Intel Corporation
> 
> Please see our [driver compatibility page](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility#windows-intel-gen7) on how you can fix this problem, specifically under "Intel GPUs" and "Gen7 Graphics". You must use the download we provide on that page to successfully update the graphics driver.
> 
> If you still have issues, please use the [official Discord server](https://caffeinemc.net/discord) for help, as this issue tracker is not intended for support requests.

updating driver works, thank you!
