### ISSUE TITLE
Anvil crash

### ISSUE THREAD

**Issue by Pedrostuck** [jellysquid3/Sodium#2665]
### Bug Description

when i try putting an anvil to fall, the game craches

### Reproduction Steps

just put an anvil on an wall

### Log File

[latest.log](https://github.com/user-attachments/files/16603230/latest.log)

### Crash Report

[crash-2024-08-13_14.23.36-client.txt](https://github.com/user-attachments/files/16603277/crash-2024-08-13_14.23.36-client.txt)

**Comment by TheUserCreated** [comment]
Install indium
