### ISSUE TITLE
1.20.1-0.6.0-alpha3: Some textures are not emissive with Sodium

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2668]
### Bug Description

Some textures are not emissive with Sodium
for example, the “Moonstone Ore” block from “Blue Skies”. 

With Sodium:
![2024-08-15_11 40 14](https://github.com/user-attachments/assets/3916ab30-4f2b-4760-93b9-9eb29bf40efe)

Without Sodium:
![2024-08-15_11 40 17](https://github.com/user-attachments/assets/b4ee8488-22db-4590-84c7-60a8b11db4c5)

### Reproduction Steps

Install Blue Skies with Sodium
Place a "Moonstone Ore"

### Log File

https://mclo.gs/nsvF8e3

### Crash Report

-

**Comment by jellysquid3** [comment]
This was probably fixed, but we are not supporting Forge 1.20 right now, and cannot verify if this specific mod was fixed.
