### ISSUE TITLE
1.16.2? game chrashes trying to use 1.16.1 on 1.16.2

### ISSUE THREAD

**Issue by Tejcina75** [jellysquid3/Sodium#267]

**Comment by FlashyReese** [comment]
There is an 1.16.2 on it's way, no ETA. You can be patient and wait for the official build or use unofficial forks like https://github.com/jellysquid3/sodium-fabric/pull/250. Just keep in mind that if you run into problems using unofficial forks Jelly's team can't help you.

**Comment by ric773** [comment]
> There is an 1.16.2 on it's way, no ETA. You can be patient and wait for the official build or use unofficial forks like #250. Just keep in mind that if you run into problems using unofficial forks Jelly's team can't help you.

how can i use the unofficial forks? i don't know much about code so i was hoping you could help me out.

**Comment by MarinaMarissa** [comment]
> > There is an 1.16.2 on it's way, no ETA. You can be patient and wait for the official build or use unofficial forks like #250. Just keep in mind that if you run into problems using unofficial forks Jelly's team can't help you.
> 
> how can i use the unofficial forks? i don't know much about code so i was hoping you could help me out.

download at: https://github.com/FlashyReese/sodium-fabric/releases
