### ISSUE TITLE
Dev missing some commits from 0.5.11

### ISSUE THREAD

**Issue by mrmangohands** [jellysquid3/Sodium#2672]
### Bug Description

It seems that dev is missing some commits from 0.5.11:
7446c9c
~~ca89a54 (This mixin is present in 1.21/stable but removed from dev, did we drop it intentionally?)~~
~~19a25aa (Same as above, Mixin removed from multiloader)~~
3030f9b

I assume the first and fourth should be cherry picked, for the others we should confirm if we really meant to drop those features.

**Comment by mrmangohands** [comment]
BillboardParticleMixin was renamed to SingleQuadParticleMixin, it looks like ca89a54 is already present in dev as part of ddecd777

**Comment by mrmangohands** [comment]
OutlineVertexConsumerMixin was renamed to EntityOutlineGeneratorMixin, 19a25aa was included in the multiloader merge

**Comment by jellysquid3** [comment]
I verified the other mentioned commits, and they appear to be applied correctly in /dev, so I'm going to close this.
