### ISSUE TITLE
Review files deleted in multiloader merge

### ISSUE THREAD

**Issue by mrmangohands** [jellysquid3/Sodium#2673]
### Bug Description

Some files were deleted in the multiloader merge, double checking we don't want them, mostly the first 2.

mixin/debug/checks/MainTargetMixin.java
mixin/core/render/chunk/LiquidBlockRendererMixin.java
client/world/biome/BiomeColorView.java (interface)
client/world/biome/BiomeColorSource.java (enum)
client/render/immediate/model/ModelPartData.java (interface)
client/model/ModelCuboidAccessor.java (accessor)

**Comment by IMS212** [comment]
These are all correct, and can be removed.

**Comment by jellysquid3** [comment]
Closing since it seems there's no problem here.
