### ISSUE TITLE
Entity shadow is not rendered

### ISSUE THREAD

**Issue by vishnu399** [jellysquid3/Sodium#268]
Entity shadow is not rendered in some cases where it is expected to be

**To reproduce**

Enter a superflat world
Place any solid block
Summon an entity over that block
`/give @p creeper_spawn_egg{EntityTag:{NoAI:1b}}`
Its shadow wont be visible from ground level
If u stand on a trapdoor the shadow would be z-fighting

![img1](https://user-images.githubusercontent.com/67385861/90507702-f2d8bb00-e173-11ea-84b6-0c6e25a8154a.png)
![img2](https://user-images.githubusercontent.com/67385861/90507734-fff5aa00-e173-11ea-8218-40fc89d0c443.png)

**Comment by FlashyReese** [comment]
This issue has been fixed, look here https://github.com/jellysquid3/sodium-fabric/issues/182#issuecomment-663884283. Just wait for the new build.
