### ISSUE TITLE
Add option to change game resolution

### ISSUE THREAD

**Issue by CeelB-2055440** [jellysquid3/Sodium#2692]
### Request Description

In vanilla Minecraft, you can change the resolution/frequency. This is important because it defaults to 1080p60, I want to change it to 1080p75 (the frequency of my monitor). However when sodium is installed, this optioin seems to disapear.

**Comment by asumagic** [comment]
See: #2642 (although I couldn't find a duplicate _open_ issue from a quick glance)

**Comment by Maneetbal** [comment]
same
