### ISSUE TITLE
Crash on Prominence 2

### ISSUE THREAD

**Issue by SamuraiDestroy** [jellysquid3/Sodium#2693]
### Bug Description

The game crashed after the console said "[Render thread/WARN] If the game crashes immediately after this point, please make a bug report: https://github.com/CaffeineMC/sodium-fabric/issues"

### Reproduction Steps

1. Install the Prominence 2 modpack on ATLauncher
2. Run the game
3. It crashes.

### Log File

[latest.log](https://github.com/user-attachments/files/16662431/latest.log)

### Crash Report

~~hs_err_pid13307.log~~ (MODERATOR EDIT: File was removed due to containing sensitive information.)

**Comment by jellysquid3** [comment]
The message in the log file is misleading and was changed in a later version of Sodium. The crash you are experiencing is unrelated to our mod and has to do with OpenGL context initialization failing, probably because of a graphics driver issue.
