### ISSUE TITLE
cannot launch game on MC 1.21 due to NV driver issue

### ISSUE THREAD

**Issue by team109** [jellysquid3/Sodium#2695]
### Bug Description

I'm using MC 1.21, fabric 0.16.2 and sodium-fabric-0.5.11+mc1.21.jar, the game cannot launch and gives this feedback:
![image](https://github.com/user-attachments/assets/ce31f356-bc2c-4fd8-95b8-31b25871b783)
the game can be launched after deleting the mod
using 4060 laptop

### Reproduction Steps

download MC 1.21 fabric 0.16.2 and newest fabric api
add the mod into the mod directory
try launch the game, fail.

### Log File

[latest.log](https://github.com/user-attachments/files/16676142/latest.log)

### Crash Report

[crash-2024-08-20_20.51.20-client.txt](https://github.com/user-attachments/files/16676153/crash-2024-08-20_20.51.20-client.txt)

**Comment by TheUserCreated** [comment]
You need to update your NVIDIA graphics driver. The log indicates you have version 528.76, but the minimum necessary version is 536.23. Please use NVIDIA's tool for updating drivers or their site and *not* windows updates for this.

**Comment by team109** [comment]
ohh sorry
