### ISSUE TITLE
Chunk/block Flickering

### ISSUE THREAD

**Issue by CuteMeShy** [jellysquid3/Sodium#2698]
### Bug Description

Every time I mine or place a block, this wierd thing happends:
https://github.com/user-attachments/assets/8b687f6e-1608-4080-ad05-7aca55840102
I tried re-installing sodium, updating to the newest versions and nothing works to fix it

### Reproduction Steps

I installed sodium and it sarted happening even before i changed anything in the sodium settings

### Log File

[latest.log](https://github.com/user-attachments/files/16687766/latest.log)

### Crash Report

The game crashed whilst manually triggered debug crash
Error: java.lang.Throwable: Manually triggered debug crash

**Comment by jellysquid3** [comment]
You have broken drivers. Read [the information for Intel Gen11 Graphics](https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility#windows-intel-gen11) to learn how to update them correctly.
