### ISSUE TITLE
Horse markings visible above horse armor

### ISSUE THREAD

**Issue by Footl0se** [jellysquid3/Sodium#2701]
### Bug Description

when a horse has any horse armor equipped, their markings show up above it, this probably isn't caused by any of my mods, as the bug disapears once Sodium and Indium are removed.
![2024-08-22_14 32 24](https://github.com/user-attachments/assets/b031fc6f-8c16-45a4-84dc-f6571929a031)
The bug also applies with texture packs
![2024-08-22_14 48 41](https://github.com/user-attachments/assets/c84f5805-293a-4b1f-96ba-e046f62ce029)

### Reproduction Steps

First, open the game using the newest versions of Sodium and Indium, find or spawn any horse, by preference the ones with the markings on their backs or with random spots, as those make viewing the bug way more noticeble

After that, simply equip any horse armor in a horse, its even easier to notice it with dyed horse armor, as it highlighte the markings/spots more.
![2024-08-22_15 31 51](https://github.com/user-attachments/assets/65df137c-b108-4869-ae0e-6e28b51368bf)

### Log File

[latest.log](https://github.com/user-attachments/files/16716573/latest.log)

### Crash Report

[crash-2024-08-22_16.04.16-client.txt](https://github.com/user-attachments/files/16716550/crash-2024-08-22_16.04.16-client.txt)

**Comment by Lolothepro** [comment]
Iris bug
