### ISSUE TITLE
More GUI scales

### ISSUE THREAD

**Issue by Footl0se** [jellysquid3/Sodium#2702]
### Request Description

Imo there should be more options of GUi scales than just the 3 we current have, as the current ones are either too small or too big in smaller monitors.

**Comment by jellysquid3** [comment]
This is not really possible. The Minecraft GUI only supports integer scaling, and it would look very bad if fractional scaling was used.

**Comment by Felix14-v2** [comment]
Actually there's an old and nowdays abandoned project for 1.12 that solves this by adding a lot of fixes to the font rendering — [Smooth Font](https://www.curseforge.com/minecraft/mc-mods/smooth-font). That's probably the most advanced font renderer in Minecraft i've ever used.
![nV2JRB0](https://github.com/user-attachments/assets/6398ec22-b131-4ea6-8a7a-378ef0093fde)

**Comment by MundM2007** [comment]
I don't think that the font is actually the Main problem but rather the item and GUI textures.

**Comment by Felix14-v2** [comment]
Essentially it may be – the font scaling doesn't work well without additional tricks. You can easily get what I mean If you install something like [Advanced UI Scaling](https://modrinth.com/mod/advanced-ui-scale) or [FractionalGUI](https://modrinth.com/mod/fractionalgui):
![image](https://github.com/user-attachments/assets/a6e05c17-cc25-4903-a64b-7f8b239ad238)
[Caxton](https://modrinth.com/mod/caxton) may help with that although.
