### ISSUE TITLE
Sodium causing custom modpack to not open Minecraft

### ISSUE THREAD

**Issue by demonickurama** [jellysquid3/Sodium#2703]
### Bug Description

I have a bunch of mods put together and sodium causes minecraft to close as its loading up, ive tested it many times, trying older versions, taking it out, its sodium thats causing this. it doesnt even give me a crash report or anything. my graphics driver is updated to the newest one. please help me.

### Reproduction Steps

im not sure, sodium just causes minecraft to close with my other mods. ive looked up a bunch and someone had a similar issue to mine but nothing helped or i already had done it.

### Log File

[latest.log](https://github.com/user-attachments/files/16723287/latest.log)

### Crash Report

no crash reports

**Comment by douira** [comment]
You need to install Indium

**Comment by demonickurama** [comment]
I did, didnt work

**Comment by douira** [comment]
The log states that indium is not installed and that you must install it. For further assistance with installing mods, please come to our discord server and open a support thread.
