### ISSUE TITLE
Some XyCraft blocks are rendered too bright/without shadow/without AO

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2706]
### Bug Description

Some XyCraft blocks are rendered too bright/without shadow/without AO

### Reproduction Steps

Place “XyCraft World: Green Xychorium Ore” block
Compare Sodium and Vanilla

Vanilla:
![2024-08-23_20 36 27](https://github.com/user-attachments/assets/79d64b09-bfbc-440d-b186-c653259fedcd)

Sodium:
![2024-08-23_20 35 01](https://github.com/user-attachments/assets/2e1ad7ac-2488-4414-9bdb-e3b35facce10)

### Log File

https://mclo.gs/qK5IZbm

### Crash Report

-

**Comment by IMS212** [comment]
This is likely fixed with https://github.com/CaffeineMC/sodium-fabric/commit/313f21f8bc67d48cc7e17b02e690bca91edf8a5b.
