### ISSUE TITLE
Rendered Entity Limit

### ISSUE THREAD

**Issue by Siuolplex** [jellysquid3/Sodium#271]
What would Rendered Entity Limit be?
Essentially, it would set a cap to the amount of entities rendered at once, possibly including things like block entities. Currently, in survival Minecraft (And other modes as well.) you might have alot of entities in a small area. My current Villager Breeder and Trading hall roughly halves my fps when I go into its area for example. Something like this, could potentially lift my fps due to not needing to render as many entities.

Of course there are some flaws.
Players could get included in this, and as such it might get chaotic to find a friend in SMP or on a server.
If your being shot at by a skeleton you cant see or some creeper suddenly appears because something is taking up your Rendered Entity Limit it wouldnt be good.
And we already have Entity Distance, which is kinda similar. 

To combat some of these flaws, something like the Particle Rendering system Where only some particles, (In this case minor entities like an arrow that hit the wall/ground or something along those lines.) will get rendered. or an Entity Priority. Which is essentially Entity filtering by Distance. Could exist.

I know this is a pretty hefty suggestion, and I could see why you might not take it. But its just an idea I have never the less.

**Comment by Madis0** [comment]
How would you prioritize one entity over another? This could be feasible for block entities like item frames, but for all it seems like a bad idea.
