### ISSUE TITLE
Entities still have translucency sorting issues

### ISSUE THREAD

**Issue by Angryfishdonut** [jellysquid3/Sodium#2710]
### Bug Description

![2024-08-23_15 32 44](https://github.com/user-attachments/assets/339f0278-d2cd-44c7-a33b-e0d0f1ecb17a)

The regular player skin should be rendering under the translucent green cubes. It is not. Also, the water behind the cubes disappears.

### Reproduction Steps

Apply the attached resource pack. Make sure to have ETF/EMF installed alongside sodium 0.6.0
[Player Model ElytrasWIP.zip](https://github.com/user-attachments/files/16733953/Player.Model.ElytrasWIP.zip)

### Log File

[latest.log](https://github.com/user-attachments/files/16733974/latest.log)

### Crash Report

Game is not crashing at all
[crash-2024-08-21_20.34.21-client.txt](https://github.com/user-attachments/files/16733985/crash-2024-08-21_20.34.21-client.txt)

**Comment by Lolothepro** [comment]
Vanilla bug, use Fabulous! gfx

**Comment by dopadream** [comment]
> Vanilla bug, use Fabulous! gfx

Didn't this not happen in vanilla with fast/fancy until after they added fabulous in 1.15?

**Comment by jellysquid3** [comment]
This is consistent with Minecraft's behavior. Use the _Fabulous!_ graphics mode.
