### ISSUE TITLE
fabric.mod.json overrides do not apply

### ISSUE THREAD

**Issue by haykam821** [jellysquid3/Sodium#2711]
When upgrading Sodium from version 0.5 to `mc1.21-0.6.0-beta.1-fabric`, any options specified through the `sodium:options` custom metadata by other mods appear to stop working. Logs indicate that no overrides are found and the affected mixins of an option remain to apply.

The following is a portion of a `fabric.mod.json` file that should apply an option but does not:

```json
{
	"custom": {
		"sodium:options": {
			"mixin.features.render.world.clouds": false
		}
	}
}
```

In version `mc1.21-0.5.11`, the following log would be printed:

```
[main/INFO] (Sodium) Loaded configuration file for Sodium: 42 options available, 1 override(s) found
[main/WARN] (Sodium) Force-disabling mixin 'features.render.world.clouds.WorldRendererMixin' as rule 'mixin.features.render.world.clouds' (added by mods [raisedclouds]) disables it and children
```

In version `mc1.21-0.6.0-beta.1-fabric`, the following log is printed:

```
[main/INFO] (Sodium) Loaded configuration file for Sodium: 43 options available, 0 override(s) found
```

Note that an invalid option (at least in 0.5) also prints a warning, indicating that this issue is not due to specifying an invalid option.

**Comment by IMS212** [comment]
This was caused by one missing line; the next beta will fix this.
