### ISSUE TITLE
Extended Drawers drawer icon rendering is broken by sodium

### ISSUE THREAD

**Issue by MattiDragon** [jellysquid3/Sodium#2713]
### Bug Description

The icons on drawers in Extended Drawers do not render when sodium (`mc1.21-0.6.0-beta.1-fabric`) is installed. This issue happens both in the config UI and in world. The relevant rendering code can be found [here](https://github.com/mattidragon/extendeddrawers/blob/32103443c3e471b7f7fbc5ba99f7b05ccdc22a71/src/client/java/io/github/mattidragon/extendeddrawers/client/renderer/AbstractDrawerBlockEntityRenderer.java#L117). I have no idea what's wrong here, but as it works with indigo it should probably also work with sodium.

### Reproduction Steps

1. Install the latest version of [extended drawers](https://modrinth.com/mod/extended-drawers/version/3.0.3+mc.1.21.1) on fabric
2. Open the game and place down a drawer
3. Sneak-click the drawer with a lock item to lock it
4. _Notice how it displays an icon_
5. Install sodium
6. Reopen the game and notice the lack of an icon

Can also be reproduced by installing modmenu and looking at the preview in the config menu under the layout group of the client tab.

### Log File

[latest.log](https://github.com/user-attachments/files/16736646/latest.log)

### Crash Report

[crash-2024-08-24_15.45.54-client.txt](https://github.com/user-attachments/files/16736657/crash-2024-08-24_15.45.54-client.txt)

**Comment by IMS212** [comment]
This specific case will be fixed by https://github.com/MattiDragon/ExtendedDrawers/pull/128.

However, investigation needs to be done as to why this isn't working...

**Comment by Noaaan** [comment]
The same issue happens with Affinity. As it uses Fabric API's Quad rendering, which for some reason breaks with Sodium 0.6.0. 
https://github.com/wisp-forest/affinity/blob/main/src/main/java/io/wispforest/affinity/client/render/blockentity/AethumFluxCacheBlockEntityRenderer.java
