### ISSUE TITLE
Chunk build failed crash

### ISSUE THREAD

**Issue by sophed** [jellysquid3/Sodium#2714]
### Bug Description

Upon joining any world, my game seems to load 2-3 chunks before crashing. This has only happened since updating to the latest `0.6.0` version of Sodium.

In case it's relevant, I'm running on Linux using Nvidia `555.58.02` drivers.

### Reproduction Steps

- Launch game
- Join any world or multiplayer server

### Log File

https://mclo.gs/32ByBHc

### Crash Report

[crash-2024-08-24_15.24.09-client.txt](https://github.com/user-attachments/files/16736947/crash-2024-08-24_15.24.09-client.txt)

**Comment by IMS212** [comment]
Caused by MoreCulling.
