### ISSUE TITLE
Animated block textures sometimes do not work

### ISSUE THREAD

**Issue by MiraculixxT** [jellysquid3/Sodium#2722]
### Bug Description

With the setting `Animate Only Visible Textures` enabled (which is default) some textures stop animating. This issue only occurs in combination with the mod [Fog](<https://modrinth.com/mod/fog>), which only start the fog rendering earlier. It does not interfere with sodium in any way and worked before 0.6.

Custom animated textures still work, **unless** Continuity is **also** installed. Then custom animated textures are also not animated anymore.

Disabling this setting continues all animations.

### Reproduction Steps

- Launch Minecraft with Sodium 0.6 and [Fog](<https://modrinth.com/mod/fog>).
- Place down fire or any other animated block
- Be sure that the setting `Animate Only Visible Textures` is active

### Log File

[latest.log](https://github.com/user-attachments/files/16752711/latest.log)

### Crash Report

[crash-2024-08-26_21.10.08-client.txt](https://github.com/user-attachments/files/16752720/crash-2024-08-26_21.10.08-client.txt)

**Comment by cobaltlol2** [comment]
I got the exact same problem

**Comment by Sternens0hn** [comment]
I also have the same problem, but I'm not running the fog mod, I'll leave the log here

[latest.log](https://github.com/user-attachments/files/16874744/latest.log)

**Comment by jellysquid3** [comment]
@Sternens0hn We cannot debug issues involving hundreds of mods. Please find the exact set of mods that cause the problem when installed alongside Sodium.

**Comment by IMB11** [comment]
> @Sternens0hn We cannot debug issues involving hundreds of mods. Please find the exact set of mods that cause the problem when installed alongside Sodium.

Fog, Fabric API, Sodium 0.6

**Comment by MeeniMc** [comment]
can reproduce
Clarification: can reproduce only when Fog mod is also loaded. Nether portal animations are not active (maybe others too).

**Comment by cranberry3148** [comment]
can reproduce with only sodium installed on latest 1.21.1

**Comment by jellysquid3** [comment]
I've not been able to create a reproduction case for this on my side. The animated textures seem to still work with the "Fog" mod installed. Furthermore, users have reported this problem can happen with no other mods installed, which is puzzling.

Right now I don't have any hypothesis as to why this is happening, or whether it's dependent on the graphics driver/etc. We need to look into it more.

**Comment by jellysquid3** [comment]
I also don't see any changes between Sodium 0.5.11 and 0.6.0 that would explain why this regressed. A bisect would likely not be helpful since the multiloader changes were squashed.

**Comment by jellysquid3** [comment]
If you find that you have been affected by this issue, please hold F3+C for 10 seconds while in-game (after it starts happening) to crash the game. Then, upload the game's log file and crash report (we need both files). This will help us figure out if there's any common thread between those who are experiencing it.

**Comment by Poopooracoocoo** [comment]
With Sodium 0.6 and Fog (and its dependencies). I created a Creative world, then right-clicked on a grass block with flint and steel and saw the issue.
Using Intel 10th gen processor graphics.
[latest.log](https://github.com/user-attachments/files/16920904/latest.log)
[crash-2024-09-08_15.05.43-client.txt](https://github.com/user-attachments/files/16920905/crash-2024-09-08_15.05.43-client.txt)

**Comment by ToBinio** [comment]
Sodium dev branch build + Fog

[latest.log](https://github.com/user-attachments/files/16921077/latest.log)
[crash-2024-09-08_08.29.12-client.txt](https://github.com/user-attachments/files/16921094/crash-2024-09-08_08.29.12-client.txt)

note:
i was not able to reproduce it when running in "dev" mode only when building a jar and using it that way
but maybe i simply did something wrong

**Comment by jellysquid3** [comment]
There has been a patch submitted ([code](https://github.com/CaffeineMC/sodium-fabric/commit/95259344b077f6aecf9141b627ce4f58b3dd6691)) which should resolve the issue. For people who were affected by this, can you see if the [nightly build](https://nightly.link/CaffeineMC/sodium-fabric/workflows/build-commit/dev/sodium-artifacts-dev.zip) works correctly now?

**Comment by MiraculixxT** [comment]
This fixes the animation bug for me with fog and continuity enabled. 

But now the game crashes when iris is also installed. I guess this is due to development currently but here is the crashlog if needed.
[crash-2024-09-09_16.52.21-client.txt](https://github.com/user-attachments/files/16932370/crash-2024-09-09_16.52.21-client.txt)

**Comment by IMB11** [comment]
Thank you @jellysquid3 :+1:

**Comment by jellysquid3** [comment]
There was also [an issue in Fog](https://github.com/IMB11/Fog/commit/d2d1bcd0d6c2b2ac6564d0e4371061d08b25c45d) that was further provoking the bug in Sodium, which has now been resolved.
