### ISSUE TITLE
Emissive Ores and other resourcepacks like this do not work properly because of Sodium

### ISSUE THREAD

**Issue by girshcatt** [jellysquid3/Sodium#2723]
### Bug Description

[Emissive Ores](https://modrinth.com/resourcepack/emissive-ores) and other resourcepacks like this do not work properly because of sodium (Works with 0.5.11 and 0.6.0)

https://github.com/user-attachments/assets/cc526a3b-a32f-4526-be68-fa7565999c17

### Reproduction Steps

1. Install Sodium and Continuity
2. Download Emissive Ores resourcepack
3. Open world and see ore glitching

### Log File

[latest.log](https://github.com/user-attachments/files/16765522/latest.log)

### Crash Report

[crash-2024-08-27_19.01.28-client.txt](https://github.com/user-attachments/files/16765551/crash-2024-08-27_19.01.28-client.txt)

**Comment by girshcatt** [comment]
I have tried MoreMcMeta Emissive Textures mod, it has no issues with Sodium, also i can use it with Continuity(for connected textures) without any problem

**Comment by girshcatt** [comment]
I found that this issue already exists on continuity's issue page, so ill close it here

**Comment by jellysquid3** [comment]
This should be fixed in Sodium 0.6.0-beta.2.
