### ISSUE TITLE
minecraft is unable to startup with sodium and other packs installed

### ISSUE THREAD

**Issue by mrbluegame** [jellysquid3/Sodium#2724]
### Bug Description

for some reason when i install sodium extra and reese sodium minecraft says its the wrong version i downloaded 3 different verison on those 3 mods and it never worked

### Reproduction Steps

Just download sodium. extra sodium and reese sodium

### Log File

[latest.log](https://github.com/user-attachments/files/16765832/latest.log)

### Crash Report

[crash-2024-08-26_20.56.46-client.txt](https://github.com/user-attachments/files/16765824/crash-2024-08-26_20.56.46-client.txt)

**Comment by douira** [comment]
You need to update both sodium extra https://modrinth.com/mod/sodium-extra/version/mc1.21.1-0.6.0-beta.1+fabric and reese's options https://modrinth.com/mod/reeses-sodium-options/version/mc1.21.1-1.8.0-beta.2+fabric to work with sodium 0.6 beta 1.

**Comment by mrbluegame** [comment]
> You need to update both sodium extra https://modrinth.com/mod/sodium-extra/version/mc1.21.1-0.6.0-beta.1+fabric and reese's options https://modrinth.com/mod/reeses-sodium-options/version/mc1.21.1-1.8.0-beta.2+fabric to work with sodium 0.6 beta 1.

i already did that i also forgot to put when i got it working with all of those mods at the same time when i click video the game just crash but now it ask me over and over to update it even though they are at the latest version

**Comment by douira** [comment]
Please come to our discord server and make a support request in the support forum.

**Comment by mrbluegame** [comment]
> Please come to our discord server and make a support request in the support forum.

what is the discord link?

**Comment by douira** [comment]
https://caffeinemc.net/discord

**Comment by mrbluegame** [comment]
> for some reason when i install sodium extra and reese sodium minecraft says its the wrong version i downloaded 3 different verison on those 3 mods and it never worked

alright i joined
