### ISSUE TITLE
Game crashes on ALT+TAB when using older Intel GPUs  

### ISSUE THREAD

**Issue by MotWnb** [jellysquid3/Sodium#2727]
### Bug Description

When playing Minecraft with the Sodium mod installed, I expected the game to continue running smoothly even when I press the Windows key while in fullscreen mode. However, when I perform these actions, the game crashes. I believe this to be a bug because pressing the Windows key while in fullscreen mode should not cause the game to crash. I am not experiencing this issue without the Sodium mod installed.
### Reproduction Steps

Install Minecraft.
Download and install the Sodium mod(0.6.0beta1).
Start Minecraft.
Press F11 to enter fullscreen mode.
Press the Windows key.
The game will crash at this point.

### Log File

[latest.log](https://github.com/user-attachments/files/16796396/latest.log)

### Crash Report

it wasn't created.But i can upload sth to help u
[hs_err_pid9824.log](https://github.com/user-attachments/files/16796416/hs_err_pid9824.log)
[LatestLaunch.txt](https://github.com/user-attachments/files/16796422/LatestLaunch.txt)(it is bat file)
[output.txt](https://github.com/user-attachments/files/16796433/output.txt)

**Comment by Felix14-v2** [comment]
What's your hardware and graphics driver version?

**Comment by MotWnb** [comment]
i7 4702mq,graphics driver version is the latest(im not at home,so idk)

**Comment by MotWnb** [comment]
- The "0.6.0beta1" version has the bug
- The "0.5.11" version is fine

**Comment by MotWnb** [comment]
20.19.15.5171

**Comment by PythonChicken123** [comment]
+1, I have the same problem and the bug only occurs when you tab out Minecraft using Alt + TAB and only occurs by using Sodium 0.6.0beta1. I also tried using the [Concertation mod](https://modrinth.com/mod/concentration) and sodium causes crash.
**Crash Reports [11 crashed sessions]:**
[hs_err_pid2232.log](https://github.com/user-attachments/files/16820218/hs_err_pid2232.log), [hs_err_pid2704.log](https://github.com/user-attachments/files/16820219/hs_err_pid2704.log), [hs_err_pid3180.log](https://github.com/user-attachments/files/16820220/hs_err_pid3180.log), [hs_err_pid4500.log](https://github.com/user-attachments/files/16820221/hs_err_pid4500.log)
[hs_err_pid6464.log](https://github.com/user-attachments/files/16820222/hs_err_pid6464.log), [hs_err_pid6628.log](https://github.com/user-attachments/files/16820223/hs_err_pid6628.log), [hs_err_pid8052.log](https://github.com/user-attachments/files/16820224/hs_err_pid8052.log), [hs_err_pid8364.log](https://github.com/user-attachments/files/16820225/hs_err_pid8364.log)
[hs_err_pid9472.log](https://github.com/user-attachments/files/16820226/hs_err_pid9472.log), [hs_err_pid9788.log](https://github.com/user-attachments/files/16820227/hs_err_pid9788.log), [hs_err_pid11260.log](https://github.com/user-attachments/files/16820228/hs_err_pid11260.log)
**Log File:**
[latest.log](https://github.com/user-attachments/files/16820296/latest.log)
**Drivers:**
![Drivers](https://github.com/user-attachments/assets/9306c04c-5424-40b1-bd4d-c85f4020ec7c)
**Additional Notes:**
Please fix this bug as soon as possible, if you need more info, you can ask for them. :)

**Comment by jellysquid3** [comment]
You can try adding the following option to the `sodium-mixins.properties` config file:

```
mixin.features.render.compositing=false
```

This should work around the crash. But we will need to implement functionality to automatically do this when Intel's broken graphics drivers are used.

**Comment by MotWnb** [comment]
Is the issue at hand that my integrated graphics processing unit (iGPU) is outdated and its drivers are unable to support certain functionalities in the new version of Sodium?

**Comment by Felix14-v2** [comment]
I think that's just a driver developers' fault, and your GPU can work properly with a different driver (Mesa or an older version of Intel's proprietary one).
