### ISSUE TITLE
[1.21.1] [neo-forge] Biome color overrides do not work with Polytone

### ISSUE THREAD

**Issue by Cixon** [jellysquid3/Sodium#2729]
### Bug Description

Polytone can make changes to biome grass and water colors; using polytone `v2.4.5` and making attempts to override say for example; `minecraft:plains` grass to _white_ and water color to _dark green_, it will not work when accompanied with Sodium `mc1.21-0.6.0-beta.1` for neoforge.

Example Resource Pack here for testing:
[example_biome_colors.zip](https://github.com/user-attachments/files/16806036/example_biome_colors.zip)

### Reproduction Steps

Tested on Neoforge 21.1.31

1.) Install Polytone
`https://modrinth.com/mod/polytone/version/23STEBmt`

2.) Install Sodium - mc1.21-0.6.0-beta.1

3.) Install example pack and use as resource pack.

4.) See bug.

### Log File

[latest.log](https://github.com/user-attachments/files/16806066/latest.log)

### Disclaimer: No crashes ever occurred, forced report(s)

Polytone - No sodium installed:
[crash-2024-08-29_15.59.12-client.txt](https://github.com/user-attachments/files/16805988/crash-2024-08-29_15.59.12-client.txt)

Polytone - Sodium installed:
[crash-2024-08-29_16.07.02-client.txt](https://github.com/user-attachments/files/16806046/crash-2024-08-29_16.07.02-client.txt)

**Comment by jellysquid3** [comment]
This seems to be due to NeoForge's patches to the Biome class... we'll probably have to rework our patches to make it behave correctly there.

**Comment by jellysquid3** [comment]
Does adding the line `mixin.features.world.biome=false` to the `sodium-mixins.properties` config file workaround the issue?

**Comment by Cixon** [comment]
> Does adding the line `mixin.features.world.biome=false` to the `sodium-mixins.properties` config file workaround the issue?

yes, this does fix it

**Comment by jellysquid3** [comment]
Should be fixed with the release of Sodium 0.6.0 Beta 2.

**Comment by Cixon** [comment]
> Should be fixed with the release of Sodium 0.6.0 Beta 2.

I appreciate you a lot! Thanks! 🤓❤️
