### ISSUE TITLE
Unshifted Screen When Using Axiom With Sodium

### ISSUE THREAD

**Issue by NathanCD12** [jellysquid3/Sodium#2730]
### Bug Description

The screen in the editor ui seems to be unshifted when using axiom with sodium

![Screenshot (892)](https://github.com/user-attachments/assets/1033ff92-d879-486b-a551-a65198948099)

### Reproduction Steps

1. Download Axiom 3.2.1 for 1.21.
2. Download Sodium 0.6.0-beta.1 for 1.21.
3. Join a world.
4. Press left shift.

### Log File

[latest.log](https://github.com/user-attachments/files/16814875/latest.log)

### Crash Report

The Game didn't crash just a forced crash

[crash-2024-08-30_16.12.55-client.txt](https://github.com/user-attachments/files/16814898/crash-2024-08-30_16.12.55-client.txt)

**Comment by jellysquid3** [comment]
As far as I know, this should be fixed in Axiom 4.0.0.
