### ISSUE TITLE
No fps boost

### ISSUE THREAD

**Issue by bobsale** [jellysquid3/Sodium#274]
Im not getting any fps boost
Specs
i5
8 gig of ram
inten hd 4600

**Comment by ZtereoHYPE** [comment]
please come on the discord server where we can actually help you troubleshoot this issue ~instead of clogging up the github issue tracker~ https://jellysquid.me/discord

**Comment by bobsale** [comment]
> please come on the discord server where we can actually help you troubleshoot this issue ~instead of clogging up the github issue tracker~ https://jellysquid.me/discord

oh thanks

**Comment by Titaniumtown** [comment]
This issue should be closed now.
