### ISSUE TITLE
Sodium Not Working with Curios API Reboots 1.21.1 Neoforge

### ISSUE THREAD

**Issue by AwesomeSavage** [jellysquid3/Sodium#2741]
### Bug Description

Sodium and any Curios API reboot for 1.21.1 Neoforge prevent Minecraft from loading when used together, due to the fabric_rendering_data_attachment_v1 contained in Sodium.

### Reproduction Steps

Download Sodium for 1.21.1 Neoforge from Curseforge and download any Curios remake/reboot for 1.21.1 Neoforge in the same pack (if you use accessories, you will likely need to also download the Curios compatability layer for for 1.21.1 Neoforge), then try to play Minecraft.

### Log File

[debug.log](https://github.com/user-attachments/files/16936761/debug.log)
[latest.log](https://github.com/user-attachments/files/16936767/latest.log)

### Crash Report

Minecraft didn't load enough to generate a crash report.

**Comment by AwesomeSavage** [comment]
I posted about this on Discord too, but when I asked for the problem to be fixed, no one responded, so I figured I'd just post it here and see if anyone cares more here.

**Comment by IMS212** [comment]
I cannot find Curios 9.1.3; where did you get it?

**Comment by jellysquid3** [comment]
This is not a bug with Sodium. The other mod is loading `net.minecraft.world.level.LevelReader` too early (before game initialization), which is not allowed. When Fabric API then tries to transform that class, it fails, because it has already been loaded. We can't do anything to fix this.

**Comment by AwesomeSavage** [comment]
In response to IMS212: That version of Curios seems to be included with every Curios reboot I could find on Curseforge for 1.21.1.

In response to Jellysquid3: I knew it was an incompatability, and I thought it was on Sodium's end due to the error listing an API inlcuded in Sodium, plus no one responded to me on the Discord server besides telling me it was an incompatability, and I only found the specific mod by disabling mods. I couldn't find anything about Curios in the logs, and I didn't know how the API it was breaking worked.

**Comment by AwesomeSavage** [comment]
But I will go to the github for the Curios reboot I am using, and post a bug there.

**Comment by kittywitch** [comment]
This has nothing to do with accessories, any of the Ars Nouveau mods, Occultism or the accessories curios layer. I am having the same problem, but I will shortly have the culprit narrowed down.

**Comment by kittywitch** [comment]
For me, it was the group of bundles developed by https://www.curseforge.com/members/serilum/ Hope that helps.
