### ISSUE TITLE
Try to fix the fps drop from mouse movements

### ISSUE THREAD

**Issue by Pan4ur** [jellysquid3/Sodium#2742]
### Request Description

I noticed that in vanilla Minecraft when you move the mouse the fps drops a lot. Here is a video: 

https://github.com/user-attachments/assets/e4718e59-51a8-4605-a94f-b7cbc9af8ec3

**Comment by asumagic** [comment]
~~This is expected, when you're standing still the renderer has much less work to do to update culling and you become CPU-limited. Your video is of vanilla minecraft; Sodium already improves upon this, and there is ongoing work to improve it further.~~

**Comment by Pan4ur** [comment]
Please look at the second half of the video, the fps changes just from mouse movements, not from camera rotation. This also happens with Sodium for Fabric

**Comment by Stupefacient** [comment]
The second frame drop is normal windows actives because your switching from rendering single a single application to multiple in boardless window mode.

> Please look at the second half of the video, the fps changes just from mouse movements, not from camera rotation. This also happens with Sodium for Fabric

**Comment by Felix14-v2** [comment]
> the fps changes just from mouse movements, not from camera rotation

Are you able to reproduce this in fullscreen with only Sodium installed? You can use F3+Esc to make the mouse cursor visible

UPD: can reproduce

**Comment by Andarwinux** [comment]
If sodium eventually implemented the DXGI swapchain, this problem could be mitigated by MPO windowed independent flip.

**Comment by jellysquid3** [comment]
We already have an issue open about using DXGI Presentation (#2361), which probably would resolve this problem.
