### ISSUE TITLE
d7f4f41 breaks the CI artifacts.

### ISSUE THREAD

**Issue by Andarwinux** [jellysquid3/Sodium#2744]
### Bug Description

sodium-artifacts-dev.zip only includes neoforge and not fabric.

### Reproduction Steps

https://github.com/CaffeineMC/sodium-fabric/actions/runs/10801739759/artifacts/1916837206

### Log File

N/A

### Crash Report

N/A

**Comment by pajicadvance** [comment]
Fixed in https://github.com/CaffeineMC/sodium-fabric/commit/e8cab346719869fd21aa9c449a256d94ee1b3f6b
