### ISSUE TITLE
Vertex ordering in entity rendering is different, breaking core shaders

### ISSUE THREAD

**Issue by ArubikU** [jellysquid3/Sodium#2745]
### Bug Description

Sodium load all the entity shaders correctly but changuing a bit the faces id`s causing some incompatibilities with "core shaders" 

Expected behavior:
![image](https://github.com/user-attachments/assets/e8f75287-d325-4a8f-85d8-2e0496128a5d)

Actual:
![image](https://github.com/user-attachments/assets/88c846b3-7e7c-4e87-b073-c97f0e3d3478)

### Reproduction Steps

[Pack for sodium example.zip](https://github.com/user-attachments/files/16985944/Pack.for.sodium.example.zip)
![example_skin](https://github.com/user-attachments/assets/bffe4aa0-0138-4727-97b4-e3296869e654)

1. Install the Resourcepack
2. Apply the example skin what add wings

In vanilla the wings will be rendered correctly in sodium fail on the read of faces
Method use in vertex to detect faces:  int face = gl_VertexID / 4 % 6;
Vanilla faces i identify:
#define BOTTOM_FACE 0
#define TOP_FACE 1
#define RIGHT_FACE 2
#define NORTH_FACE 3
#define LEFT_FACE 4
#define SOUTH_FACE 5

### Log File

[latest.log](https://github.com/user-attachments/files/16985987/latest.log)

### Crash Report

[crash-2024-09-12_17.26.57-client.txt](https://github.com/user-attachments/files/16985995/crash-2024-09-12_17.26.57-client.txt)

**Comment by douira** [comment]
I want to note that this is an issue with the entity data provided by sodium to the resource pack's core shader and not a matter of getting sodium to load a pack's terrain core shaders (since this isn't terrain). This was misunderstood in the preceding discussion on discord multiple times.

**Comment by jellysquid3** [comment]
It would probably be enough to fix this issue if the ordering of constants [here](<https://github.com/CaffeineMC/sodium-fabric/blob/888d922e3f034bf97bb1c0171e8012b22a9a1be6/common/src/main/java/net/caffeinemc/mods/sodium/client/render/immediate/model/EntityRenderer.java#L21-L27>) were changed to match Minecraft.

**Comment by jellysquid3** [comment]
However, it is possible that future versions of Sodium will discard back-facing triangles when rendering entities, and that core shaders which rely on this specific ordering will be broken once again.

We do not support core shaders and we cannot guarantee that relying on extremely specific behavior like this will continue to work.
