### ISSUE TITLE
MultiPartBakedModel quads broken with Litematica 24w34a - 24w37a+

### ISSUE THREAD

**Issue by sakura-ryoko** [jellysquid3/Sodium#2748]
### Bug Description

Using Sodium 0.6.0 Beta in Snapshot with Litematica causes either crashes or blocks to not render.  See debug reports.

### Reproduction Steps

1 - Compile Snapshot Litematica. (24w36a+ / 24w37a is current)
2 - Compile Sodium 0.6.0 DEV ( sodium-fabric-0.6.0-snapshot+mc24w37a-local )
3 - Try to load Litematics with certain blocks such as Fences or Glass.
4 - Enjoy crashing.

### Log File

(With Sodium)
[2024-09-13-2.log.gz](https://github.com/user-attachments/files/17000857/2024-09-13-2.log.gz)
[2024-09-13-3.log.gz](https://github.com/user-attachments/files/17000858/2024-09-13-3.log.gz)
[debug-2.log.gz](https://github.com/user-attachments/files/17000869/debug-2.log.gz)
[debug-1.log.gz](https://github.com/user-attachments/files/17000870/debug-1.log.gz)

(Without Sodium)
[latest.log](https://github.com/user-attachments/files/17000859/latest.log)
[debug.log](https://github.com/user-attachments/files/17000871/debug.log)

### Crash Report

[crash-2024-09-13_23.40.51-client.txt](https://github.com/user-attachments/files/17000872/crash-2024-09-13_23.40.51-client.txt)
[crash-2024-09-13_23.46.53-client.txt](https://github.com/user-attachments/files/17000873/crash-2024-09-13_23.46.53-client.txt)

**Comment by sakura-ryoko** [comment]
Just additional context:
- Litematica uses it's own `BlockModelRendererSchematic.class` ( https://github.com/sakura-ryoko/litematica/blob/11217258988caea467b987c3c5069c13fecb97c0/src/main/java/fi/dy/masa/litematica/render/schematic/BlockModelRendererSchematic.java#L70 -- point of crash)
- I tried swapping the Litematica Block Model Renderer to the Vanilla, and the crash still occurs.  ( https://github.com/sakura-ryoko/litematica/blob/11217258988caea467b987c3c5069c13fecb97c0/src/main/java/fi/dy/masa/litematica/render/schematic/WorldRendererSchematic.java#L671 )

Actual Crash Point:
Class Cast Exception at at net.minecraft.client.render.model.MultipartBakedModel.getQuads(MultipartBakedModel.java:555)

**Comment by sakura-ryoko** [comment]
Opened PR for the fix:
https://github.com/CaffeineMC/sodium-fabric/pull/2760

**Comment by IMS212** [comment]
Fixed in https://github.com/CaffeineMC/sodium-fabric/commit/80a05bf3183d8b9281e1f39d0579a0344ca5d456.
