### ISSUE TITLE
cant render water 

### ISSUE THREAD

**Issue by bunhiacxzy** [jellysquid3/Sodium#2749]
### Bug Description

i use sodium for mcsr (1.16.1) and somehow when i start world it cant render water

### Reproduction Steps

![image](https://github.com/user-attachments/assets/04653447-b583-4802-92c7-21bd2a5e6003)

### Log File

[latest.log](https://github.com/user-attachments/files/17001428/latest.log)

### Crash Report

[crash-2024-09-14_14.23.02-client.txt](https://github.com/user-attachments/files/17001435/crash-2024-09-14_14.23.02-client.txt)

**Comment by MCRcortex** [comment]
Dont use tlauncher

**Comment by bunhiacxzy** [comment]
> Dont use tlauncher

first i use legacy launcher
second this bug appear when i play in lower version and when i use sodium in 1.20.2 it isnt bug

**Comment by Samalando** [comment]
Legacy launcher and tlauncher are the same thing. Both are cracked launchers, both we can't support.

**Comment by Felix14-v2** [comment]
> Legacy launcher and tlauncher are the same thing

Absolutely not the same, but yes, piracy is not supported. @bunhiacxzy , if you want, you can try to reproduce the issue from the official Minecraft launcher with demo mode to get support here. But as far as I know older Sodium versions are not supported too, the only LTS version is 1.20.1.

**Comment by bunhiacxzy** [comment]
> Legacy launcher and tlauncher are the same thing. Both are cracked launchers, both we can't support.

guy i switch to premium launcher and it still not render water is it relative to jave install

**Comment by bunhiacxzy** [comment]
![image](https://github.com/user-attachments/assets/654d6887-3106-4896-b5f4-b81abefd58ee)
hell nah it turned into horror game
