### ISSUE TITLE
Add sodium version for minecraft snapshot.

### ISSUE THREAD

**Issue by hpndd13** [jellysquid3/Sodium#2750]
### Request Description

I accidentally discovered this mod.It has made my minecraft smoother.I was playing minecraft with this mod and felt that there was a lack of version for minecraft snapshot.But if this feature is added, the mod owner will have more work.So if this feature is not added, I am not too surprised.

**Comment by jellysquid3** [comment]
We don't currently provide releases for snapshot versions because it is a significant maintenance burden. This is not likely to change in the future.
