### ISSUE TITLE
cant render water and i dont know what to call

### ISSUE THREAD

**Issue by bunhiacxzy** [jellysquid3/Sodium#2751]
### Bug Description

![image](https://github.com/user-attachments/assets/294a51d7-2e42-4c3d-a222-7af6adf8fe48)
![image](https://github.com/user-attachments/assets/b2d2e573-217b-413a-8555-cc9b706d6813)

### Reproduction Steps

i starting world and cant render water and some time it turn to horror game

### Log File

[latest.log](https://github.com/user-attachments/files/17002360/latest.log)

### Crash Report

[crash-2024-09-14_19.14.02-client.txt](https://github.com/user-attachments/files/17002348/crash-2024-09-14_19.14.02-client.txt)

**Comment by douira** [comment]
1.16.1 is not supported. Please report this bug to the people who've provided you with this speedrunning fork of sodium instead.

**Comment by bunhiacxzy** [comment]
> 1.16.1 is not supported. Please report this bug to the people who've provided you with this speedrunning fork of sodium instead.

https://github.com/Minecraft-Java-Edition-Speedrunning/sodium

**Comment by MCRcortex** [comment]
report to that repo not here

**Comment by bunhiacxzy** [comment]
> report to that repo not here

tru
