### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by McUzi12** [jellysquid3/Sodium#2755]
### Bug Description

Every time I try and start minecraft with the new .6 beta of sodium it ends up giving me this crash log: The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: 'net.caffeinemc.mods.sodium.api.vertex.format.VertexFormatDescription net.caffeinemc.mods.sodium.api.vertex.format.VertexFormatRegistry.get(net.minecraft.class_293)'

### Reproduction Steps

Just open minecraft through curse forge while having sodium .6 beta installed 

### Log File

[2024-09-15-1.log.gz](https://github.com/user-attachments/files/17006962/2024-09-15-1.log.gz)

### Crash Report

[crash-2024-09-15_13.10.17-client.txt](https://github.com/user-attachments/files/17006963/crash-2024-09-15_13.10.17-client.txt)

**Comment by pajicadvance** [comment]
Iris is still not updated to work with beta 2.

**Comment by McUzi12** [comment]
I appreciate the help!
