### ISSUE TITLE
Can't launch MC 1.21 after update

### ISSUE THREAD

**Issue by Squtzy** [jellysquid3/Sodium#2756]
### Bug Description

After updating to latest version (0.6.0 Beta 2) my game will no longer launch. Thought new Iris update was the reason but even after reverting to the last known working Iris version my game still won't launch on the Beta 2 version of Sodium. Reverting Sodium to Beta 1 and game works again.

Adding my logs here and also screenshot of mods:
![image](https://github.com/user-attachments/assets/d4f3d902-4b32-4d98-b00e-8be6bbe9f3ad)
![image](https://github.com/user-attachments/assets/c13b8056-138d-4915-afb4-f5b38644df67)
![image](https://github.com/user-attachments/assets/5c0bc98a-ed3e-4f78-a419-992e0b226d85)

### Reproduction Steps

Update Sodium to Version 0.6.0 Beta 2
Attempt at launching game
Crash happens
Revert back to Beta 1
Launch game
Play as normal

### Log File

[latest.log](https://github.com/user-attachments/files/17007128/latest.log)

### Crash Report

[crash-2024-09-15_21.21.40-client.txt](https://github.com/user-attachments/files/17007129/crash-2024-09-15_21.21.40-client.txt)

**Comment by IMS212** [comment]
Sodium Extra is not yet compatible.
