### ISSUE TITLE
Crashes including serializer and caffeine

### ISSUE THREAD

**Issue by Riptide1997** [jellysquid3/Sodium#2757]
### Bug Description

Crashes when launching after testing found it was caused by Iris shaders mod and the creative core mod.

### Reproduction Steps

I feel as though its a compatibility thing maybe using your older core code but not 100%.

### Log File

[latest.log](https://github.com/user-attachments/files/17014416/latest.log)

### Crash Report

[crash-2024-09-16_14.42.40-client.txt](https://github.com/user-attachments/files/17014404/crash-2024-09-16_14.42.40-client.txt)

**Comment by douira** [comment]
You're using sodium beta 1 with iris beta 4. You need to update sodium to beta 2. Please come to our discord's support forum for further support requests like this.
