### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by vinnyg0621** [jellysquid3/Sodium#2759]
### Bug Description

after playing on a server with more mcmeta and the emissive textures addon I got this strange crash, and now it's not letting me play again. that means every time I try to launch it will crash on startup. and all my mods are up to date. please fix it's been over a year and a half!!!!!

### Reproduction Steps

1. go onto a world
2. hold an enchanted item
3. it will crash

### Log File

[latest.log](https://github.com/user-attachments/files/17018156/latest.log)

### Crash Report

[crash-2024-09-16_12.04.10-client.txt](https://github.com/user-attachments/files/17018161/crash-2024-09-16_12.04.10-client.txt)

**Comment by jellysquid3** [comment]
This is user error, there is no bug in our mod, and I don't know why you're complaining about this being "broken for years". You must use a compatible version of Iris (version 1.8.0-beta.4) alongside Sodium (version 0.6.0-beta.2).

**Comment by vinnyg0621** [comment]
oh darn it, i forgot to update _that_ mod :(

**Comment by vinnyg0621** [comment]
it still persists!! 😠

**Comment by MCRcortex** [comment]
ok, try only sodium, if it doesnt crash that means its working
This also isnt a support forum its an issue tracker, goto the discord if you want support

**Comment by vinnyg0621** [comment]
i'm sorry. it was actually the emissives plugin for more mc meta
