### ISSUE TITLE
Terrain vertex attribute "a_LightAndData.xy" would be set to 8 instead of 0 when light level is 0.

### ISSUE THREAD

**Issue by Tahnass** [jellysquid3/Sodium#2761]
### Bug Description

Terrain vertex attribute "a_LightAndData.xy" would be set to 8 instead of 0 when light level is 0.
This problem started to appear in version 0.6.0 beta.1 (not tested with alpha versions). 
It has no effect on vanilla rendering, but may cause some shaders to calculate block lighting incorrectly.
![2024-09-17_12 53 36](https://github.com/user-attachments/assets/e3d6f5aa-8728-4470-a073-dd83217c81c9)

### Reproduction Steps

Launch Minecraft 1.21.1 with sodium-fabric-0.6.0-beta.2 only. 
Capture a frame with RenderDoc. And randomly select a triangle with no lighting.
![0 1](https://github.com/user-attachments/assets/b62d1b4e-87c7-49a2-9721-c36a45def7d5)
![image](https://github.com/user-attachments/assets/c2414e50-4654-4a38-9d1f-a7e59eded20b)

### Log File

No useful infromation.

### Crash Report

No useful infromation.

**Comment by MCRcortex** [comment]
resource pack terrain shaders are not supported

**Comment by jellysquid3** [comment]
Sodium clamps the light map coordinates between (0.5, 0.5) and (15.5, 15.5) in the vertex data rather than in the shader code to avoid some additional instructions. So these values are to be expected for the minimum and maximum brightness levels.

**Comment by jellysquid3** [comment]
If you are authoring a shader pack with Iris and this behavior causes compatibility issues, then you should open a bug report with them. They are [copying the clamping behavior](https://github.com/IrisShaders/Iris/blob/81f2c3c15a778da48a7a5f72d38142d71bae6deb/common/src/main/java/net/irisshaders/iris/vertices/sodium/terrain/XHFPTerrainVertex.java#L71-L75), but it probably doesn't make sense for OptiFine-style shaders that expect it to work identically to Minecraft.
