### ISSUE TITLE
Sodium beta2 crashes unexpectedly

### ISSUE THREAD

**Issue by Grayish-Tiger** [jellysquid3/Sodium#2763]
### Bug Description

As soon as I run Minecraft it gives this unexpected error saying a method is missing. I have tired reinstalling Minecraft, but it didn't fix anything. If possible, can you tell me if it is a mod conflict, or it is an error in sodium. 

### Reproduction Steps

Install the mods listed in the log file on a fresh install of minecraft. 

### Log File

[latest.log](https://github.com/user-attachments/files/17038649/latest.log)

### Crash Report

[crash-2024-09-18_17.00.41-client.txt](https://github.com/user-attachments/files/17038661/crash-2024-09-18_17.00.41-client.txt)

**Comment by jellysquid3** [comment]
This is user error -- You must use the latest version of Sodium (0.6.0-beta.2) and Iris (1.8-beta.4).
