### ISSUE TITLE
Sodium only giving 30fps improvement and  extremum slow new chunk  rendering in Fabric Minecraft 1.21.1 

### ISSUE THREAD

**Issue by avocado382** [jellysquid3/Sodium#2764]
### Request Description

So I have hared that sodium is a fast rendering optimization  mod for minecraft but I only got 30fps improvement with sodium amd when i render new chunks or new terrain chunks render super slowly but on my dads pc i got 200fps improvement and chunks render super fast 

My laptop specs: intel core I5 5200U cpu                       
                            intel HD 5500 (driver date 2020) Gpu
                            8 DDR3 RAM
 My dads pc  specs : intel core i5 10 gen cpu 
                                 intel hd 630 GPU 
                                  8 DDR4 RAM 

I could use my dads pc but its his office pc and its in my dads office not at our house so can you guys pls fix this issue

**Comment by jellysquid3** [comment]
Yes. The faster computer is going to run Minecraft better. What do you expect?

**Comment by avocado382** [comment]
Bruh sodium is made for low end computers right so why is sodium not
boosting my fps and not rendering chunks fast BRUH

**Comment by ghost** [comment]
> Bruh sodium is made for low end computers right so why is sodium not boosting my fps and not rendering chunks fast BRUH

Sodium is not "made for low end computers", it's made for all computers ([with some exceptions](https://modrinth.com/mod/sodium#hardware-compatibility) but that's not the point).
A 5th gen i5 will always be slower than a 10th gen i5, there's nothing you can do about it.

**Comment by avocado382** [comment]
Chatgpt, YouTube, Google all said sodium is a good mod to boost fps but it
does not. But when i change my fullscreen resolution I get 250fps with
sodium  so I have decided to code a mod that lets you change fullscreen
resolution and not change its appearance and quality to boost fps and it
uses a feature to boost fps when the resolution is even changed and also
renders chunks faster in old hardware. The mod will be called ''MoreFast"
and I am almost done with the mod. so my problem is solved. So sorry for
wasting your time pls forgive me. But I still love your mod and it still
gives me a fps boost. You and your team did a good job with sodium :).

**Comment by avocado382** [comment]
Hi mr Rad

I am on of your fans of your mod sodium normally it gives me i get 50fps in
vanilla and with sodium i have 90-100fps i see so many creators gaining
250fps i have a laptop so i can get a new cpu or gpu and i have 8 gb ram
which is the max amount so please i am begging you guys to make sodium
boost fps and speed up chunk rendering in much weaker hardware. I could ny
a ne computer but i live in sri lanka and computers here are like 500,000
rupees so please do something to make sodium giv the best performance
possible for me and not just me other people in this world  and my mom
alwasy told me if you do good by helping others it will always come back to
you Please reply (my specs  i5 5200U cpu intel hd 5500gpu and 8 gb ddr3 ram
)

**Comment by Mine181** [comment]
Sodium can only do so much to improve performance on limited hardware, its effect will vary based on what is limiting your performance, so some may get 50 fps, some may get 200+, the sodium team tries to improve performance in every update but they cant magically make the game run at 300+ fps on any pc.

**Comment by ghost** [comment]
> Sodium can only do so much to improve performance on limited hardware, its effect will vary based on what is limiting your performance, so some may get 50 fps, some may get 200+, the sodium team tries to improve performance in every update but they cant magically make the game run at 300+ fps on any pc.

I usually get +70 improvement with sodium on pojav launcher(also works on Android with the new LTW renderer). It's 3× better than optifine in my tests. Wery thanks for the creator of sodium

**Comment by Felix14-v2** [comment]
> to make sodium boost fps and speed up chunk rendering in much weaker hardware

You can try the [experimental build](https://github.com/CaffeineMC/sodium/actions/runs/12020702137) of Sodium with improved task sheduling. It may greatly improve your FPS when loading chunks and just standing still on CPU-limited systems. Also feel free to join [Sodium Discord](https://caffeinemc.net/discord) for further support.
