### ISSUE TITLE
crash when opening video settings

### ISSUE THREAD

**Issue by MarkHarrisMedia** [jellysquid3/Sodium#2765]
### Bug Description

Open Minecraft, Enter Java Server, Open Video Settings, Crash.

### Reproduction Steps

Open Minecraft, Enter Java Server, Open Video Settings, Crash.

### Log File

[latest.log](https://github.com/user-attachments/files/17046114/latest.log)

### Crash Report

[crash-2024-09-18_11.01.31-client.txt](https://github.com/user-attachments/files/17046108/crash-2024-09-18_11.01.31-client.txt)

**Comment by MCRcortex** [comment]
Not a sodium issue, this also isnt a support forum.
You have 283 mods+libraries installed.
Try with just sodium.

**Comment by MarkHarrisMedia** [comment]
![image](https://github.com/user-attachments/assets/d3928f30-a470-417a-928e-c9a4959c7a16)

**Comment by MarkHarrisMedia** [comment]
> Not a sodium issue, this also isnt a support forum. You have 283 mods+libraries installed. Try with just sodium.

Sorry about that. Here is an update, if you're interested:
I removed Reese's sodium extras mod (reeses-sodium-options-fabric-1.8.0-beta.3+mc1.21.1.jar) and it fixed the problem.

I can now access video settings without game crashing. 
Maybe I will try a previous version tomorrow. I will keep you updated.

Running with
sodium-fabric-0.6.0-beta.2+mc1.21.1
sodium-extra-fabric-0.6.0-beta.3+mc1.21.1
