### ISSUE TITLE
Light Overlay Not Rendering In Latest Version

### ISSUE THREAD

**Issue by KenzaSheep** [jellysquid3/Sodium#2767]
### Bug Description

The light overlay function (which allows a user to see which blocks a mob is able to spawn on) within Complimentary Shaders no longer renders while using versions 0.6.0 Beta Sodium + 1.8.0 Beta Iris as Fabric mods.
Changing versions of Complimentary Shaders has no effect, but downgrading Sodium and Iris fix the issue. 

### Reproduction Steps

Using the 1.21.x Fabric launcher, and with 0.6.0 Beta Sodium (version 1 or 2) and 1.8.0 Beta Iris (version 3 or 4) placed into the mods folder, load a world with Complimentary Shaders. Open the configurations for Complimentary Shaders, click "other," and enable Light Overlay. On other versions of Iris+Sodium, a light overlay grid will appear, but no grid appears when using these versions.

### Log File

[latest.log](https://github.com/user-attachments/files/17085287/latest.log)

### Crash Report

[crash-2024-09-21_13.47.41-client.txt](https://github.com/user-attachments/files/17085284/crash-2024-09-21_13.47.41-client.txt)

**Comment by davepusey** [comment]
FYI this is fixed in the r5.3 release of Complementary Shaders
