### ISSUE TITLE
Animated fire overlay plays in pause screen

### ISSUE THREAD

**Issue by deeprobin** [jellysquid3/Sodium#277]
### Expected Behavior
The fire overlay animation should pause if you are in singleplayer and open the pause screen.

### Actual Behavior
The fire overlay animation continues while the rest of the game is paused.

### Reproduction Steps

1. Open single player world
2. Jump in lava or fire (gamemode: survival/adventure)
3. Press ESC

### Attachments
![Screenshot](https://user-images.githubusercontent.com/10373452/90966694-b2f83780-e4d5-11ea-9b4e-f3b5c9746c44.png)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: 14.0.2
- CPU: AMD Ryzen 5 3600 6-Core Processor
- GPU: NVIDIA GeForce GTX 750 Ti

**Comment by 0f-0b** [comment]
[MC-118001](https://bugs.mojang.com/browse/MC-118001).

**Comment by deeprobin** [comment]
@sjx233 Yeah but not just the blocks - the fire **overlay** is also affected

**Comment by altrisi** [comment]
Can reproduce **without** Sodium.

**Comment by amnotbananaama** [comment]
@deeprobin This occurs in Vanilla, so it is not a bug with Sodium. (See https://bugs.mojang.com/browse/MC-1940 and https://bugs.mojang.com/browse/MC-167320). I will leave this open as an enhancement, for Jelly to decide whether or not it's within the scope of Sodium to fix this Vanilla bug.

**Comment by deeprobin** [comment]
Yes, you could at least leave this issue open until Mojang fixes this bug.

**Comment by jellysquid3** [comment]
I don't think this is important enough for us to go out of our way to patch it, which is frankly non-trivial.
