### ISSUE TITLE
Crash sodium in loading world fabric

### ISSUE THREAD

**Issue by Dorian12192** [jellysquid3/Sodium#2770]
### Bug Description

Hello, in Pojav Zenith Horizon when I try to play a world with the sodium mod when it reaches 100% it kicks me out of the game, it used to work and now it doesn't anymore, is it an update or something like that? 

### Reproduction Steps

Open minecraft
Use sodium mod
Use mod menu to make the mod sodium work
Play minecraft fabric
Play a world
CRASH REPORT!

### Log File

[sodium-fabric-0.5.11+mc1.21.zip](https://github.com/user-attachments/files/17090489/sodium-fabric-0.5.11%2Bmc1.21.zip)

### Crash Report

No crash r3port here

**Comment by douira** [comment]
Pojav launcher is not supported
