### ISSUE TITLE
Mixin Loading Crash

### ISSUE THREAD

**Issue by desagas** [jellysquid3/Sodium#2775]
### Bug Description

Crash on Loading Mixin on Neoforge 21.1.62, sodium version: 0.6.0-beta 2

### Reproduction Steps

IDK, install the mods a versions listed in my modlist in the crash report, and start the game.

### Log File

Log:
[latest.log](https://github.com/user-attachments/files/17157549/latest.log)

Debug:
[debug.log](https://github.com/user-attachments/files/17157551/debug.log)

### Crash Report

Crash: 
[crash-2024-09-26_18.40.33-client.txt](https://github.com/user-attachments/files/17157548/crash-2024-09-26_18.40.33-client.txt)

**Comment by jellysquid3** [comment]
> mixins.iris.json:entity_render_context.MixinHumanoidArmorLayer **from mod iris** failed injection check

**Comment by desagas** [comment]
Maybe I read the logs wrong, but I was sure that the first part of the crash log the enabled the crash was the sodium mixin, and then referenced those where it resulted from, thus, as you did, bolding the line immediately following sodium **from mod**. I will post this on Iris as well. Thank you!
