### ISSUE TITLE
Sodium crashed 1.20.1 Fabric Modpack

### ISSUE THREAD

**Issue by D3M0N-666** [jellysquid3/Sodium#2778]
### Bug Description

I am trying to play a custom modpack with shaders. The only real option I have is Sodium. Without Sodium it works but the performance is unbearable and I cannot even try to play with shaders.
Thanks for helping

### Reproduction Steps

It happened when I was trying to join a singleplayer world with the modpack.

### Log File

https://mclo.gs/zLfuJZZ

### Crash Report

https://mclo.gs/lTWBKXQ

**Comment by pajicadvance** [comment]
The mod "Extra Details" is crashing the game, this is not a Sodium issue.
