### ISSUE TITLE
Distant Cloud Fog Coloring Issue in Sodium Mod Compared to Vanilla Minecraft

### ISSUE THREAD

**Issue by notwhitebear** [jellysquid3/Sodium#2786]
### Request Description

Hello, maintainer. I have discovered a rendering issue with the Sodium mod that differs from the vanilla version in a very specific detail. In the vanilla version, when clouds are enabled, the distant clouds are colored by fog. However, when using the Sodium mod, this coloring is altered, and the fog effect is even not visible at all. This is a very detail-oriented issue, but it is important for some of us who enjoy playing older versions or versions with OptiFine. If possible, I would like to request that you address this detail. Below are two comparison images: (The first one is from the vanilla version, and the second one is from Sodium.) 
![2024-10-01_13 06 37](https://github.com/user-attachments/assets/6ca7394d-3dd9-4c4c-a4fa-d2e76084dae0)
![2024-10-01_13 04 52](https://github.com/user-attachments/assets/e659dc2f-5cdb-4ee4-b62c-dff5593e96ad)

**Comment by Felix14-v2** [comment]
The thing is that the behavior in the first screenshot is a bug, not the intended behavior — the cloud tinting has been broken for ages. That [was fixed](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.19.3-0.4.7) in Sodium after optimizing the cloud renderer, if I remember correctly.

**Comment by EazyPaw** [comment]
I understand it’s a bug in the vanilla version. However, I personally enjoy this effect and would love to see an option in Sodium to enable or disable fog tinting for clouds.

**Comment by jellysquid3** [comment]
You can revert back to Minecraft's original cloud rendering if you don't like this effect. There isn't an option in the Video Settings menu for it, but you can add the following line of text to your `config/sodium-mixin.properties` file:

```
mixin.features.render.world.clouds=false
```
