### ISSUE TITLE
Linux + Sodium + Fabulous = Broken Cloud Rendering

### ISSUE THREAD

**Issue by RicochetYT** [jellysquid3/Sodium#279]

**Comment by RicochetYT** [comment]
Most likely related to issue #146

**Comment by jellysquid3** [comment]
This is a problem with the base game when using the Mesa drivers on Linux. Technically speaking, Minecraft's code is the culprit here, but most other drivers are able to work around the bug on their end through sheer luck. See [MC-187411](https://bugs.mojang.com/browse/MC-187411).
