### ISSUE TITLE
Sodium and Amendments are not working together.

### ISSUE THREAD

**Issue by Ladiesman287** [jellysquid3/Sodium#2790]
### Bug Description

I tried using amendments mod with sodium in 1.21 and when I try to use wall hanging lantern or carpet on stairs, the game crashes instantly. 

### Reproduction Steps

Anytime I try to use carpet on a stair or a slab it crashes, and I could never be able to load my world back.

### Log File

[Uploading 2024-09-14-4.log…]()

### Crash Report

[crash-2024-09-14_23.14.53-client.txt](https://github.com/user-attachments/files/17244359/crash-2024-09-14_23.14.53-client.txt)

**Comment by Ladiesman287** [comment]
I don't know if I could upload the reports right. This is my second time using github.

**Comment by jellysquid3** [comment]
The problem is due to Indium relying on internals of Fabric API which are not stable.

You have two solutions:
- Make sure that you are using Indium 1.0.35 and Fabric API 0.105.0.
- (or) Upgrade to Sodium 0.6.0, and remove Indium from the mods folder.

**Comment by Ladiesman287** [comment]
Thank you, I will try.
