### ISSUE TITLE
Vanilla Parity [Player render Draw calls]

### ISSUE THREAD

**Issue by ArubikU** [jellysquid3/Sodium#2791]
### Bug Description

Vanilla mc dont mix player entity or item(player heads) on one call, mixing cause issues with some core shaders that depend on vertex id of players.

### Reproduction Steps

1. Install a example pack:
For facility use, https://modrinth.com/resourcepack/magicshader
2. Summon a player with the same skin of yours (use a player modification or something)
3. one of the player will have wrong model display(my shader modify depending on vertex ids)

### Log File

[latest.log](https://github.com/user-attachments/files/17249773/latest.log)

### Crash Report

[crash-2024-10-03_15.29.32-client.txt](https://github.com/user-attachments/files/17249765/crash-2024-10-03_15.29.32-client.txt)

**Comment by jellysquid3** [comment]
This is not fixable on our end. Even without our mod, relying on the vertex IDs is extremely fragile due to how draw combining works.
