### ISSUE TITLE
Mod texture incompatibility with Amendments cauldron and Botania abstruse platform

### ISSUE THREAD

**Issue by CaylinNeko** [jellysquid3/Sodium#2794]
### Bug Description

When filling the cauldron with water or lava the entire cauldron goes invisible

https://github.com/user-attachments/assets/a34fa037-a674-496b-b583-36f3a6badfad

When using the mod alone there is no issue, but when used with sodium (Sodium-fabric-0.5.11+mc1.20.1.jar is the one currently being used) this issue is replicated. I isolated the issue to this mod and amendments, as it is not replicable outside of the combination of the two mods. 

https://github.com/user-attachments/assets/612bff71-ef0a-4f3b-b344-4acba76ee104

-----------------------------------------------------------------------------------------------------------

The same has been tested with Sodium and Botania 

https://github.com/user-attachments/assets/121dcfb1-74b4-47ee-b636-67b1dd003b03

video without sodium installed:

https://github.com/user-attachments/assets/f429a256-7809-4e82-9ab0-4fcb7ad704df

### Reproduction Steps

For the cauldron issue, obtaining a cauldron and placing it, then filling it with water, lava, milk, potions, and coloring the water with dye all result in the same bug that causes the cauldron to go invisible.

For the Abstruse platform, placing the block and right clicking it with another basic block is supposed to change the appearance of the abstruse platform to the basic block's appearance (save for a pixel of texture on each edge, which I believe is a bug on Botania's side). While using sodium, the texture does not change for the abstruse platform at all. 

Both of these were tested with Sodium and the other mods (and dependencies) alone. then tested again without sodium installed. 

The launcher being used is CurseForge

### Log File

Amendments:
[latest.log](https://github.com/user-attachments/files/17262291/latest.log)

Botania:
[latest.log](https://github.com/user-attachments/files/17262335/latest.log)

### Crash Report

Amendments:
[crash-2024-10-04_14.06.45-client.txt](https://github.com/user-attachments/files/17262297/crash-2024-10-04_14.06.45-client.txt)

Botania:
[crash-2024-10-04_14.09.17-client.txt](https://github.com/user-attachments/files/17262331/crash-2024-10-04_14.09.17-client.txt)

**Comment by jellysquid3** [comment]
You probably need to [install Indium](https://modrinth.com/mod/indium), or update to Minecraft 1.21 and Sodium 0.6.0.

**Comment by CaylinNeko** [comment]
Installing Indium fixed the issue, I appreciate the quick diagnosis. Thank you for your time!
