### ISSUE TITLE
Non-square grid like Townscaper

### ISSUE THREAD

**Issue by Monroe1701** [jellysquid3/Sodium#2798]
### Request Description

Hi, 
The game Townscaper look fantastic in part because it uses irregular quadrilaterals instead of regular ones. So distorting the boring grid to something more interesting.

Would it be possible to "distort" the chunk grid of Minecraft to be irregular instead of regular as an option? Or is this the wrong mod for this?
![Logically-rectangular-grid-of-irregular-quadrilaterals](https://github.com/user-attachments/assets/7e01b533-1ed2-4a7a-965f-2fd83bd829c4)

**Comment by jellysquid3** [comment]
Sodium won't be implementing anything like this. You might be able to modify the shaders via unsupported means to create a distortion effect.
