### ISSUE TITLE
Interesting chunkloading behavior with BungeeCord servers

### ISSUE THREAD

**Issue by Leo40Git** [jellysquid3/Sodium#28]
### Expected Behavior
When joining a BungeeCord server and jumping to the sub-server I want to be in, chunks should load in as normal.

### Actual Behavior
The only chunks that were loaded were the initial chunk radius around the area I was when I logged in.

### Reproduction Steps
1. Set up a BungeeCord server with at least 1 sub-server
2. Join the server, then join the sub-server
3. Marvel at the magic of invisible chunks!

### Attachments
![2020-06-21_16 24 50](https://user-images.githubusercontent.com/7997354/85231660-e4835280-b401-11ea-8116-ed0566aea24c.png)

### System Information
- Java Version: AdoptOpenJDK 14.0.1.7
- CPU: Intel Core i5-8250U @ 1.60GHz
- GPU: NVIDIA GeForce MX150

**Comment by Leo40Git** [comment]
![Discord_PPlPEvcImu](https://user-images.githubusercontent.com/7997354/85231739-670c1200-b402-11ea-9e95-46633fc875f1.png)
I know you already know about this, this issue is just so a duplicate won't be created.

**Comment by jellysquid3** [comment]
Related to #26.

**Comment by jellysquid3** [comment]
Fixed with 43f77f9.
