### ISSUE TITLE
Fix vanilla fast leaves improper culling

### ISSUE THREAD

**Issue by Jetsparrow** [jellysquid3/Sodium#280]
There is a long-standing performance regression in vanilla, from 1.12:
[Leaves are not culled when set to fast](https://bugs.mojang.com/browse/MC-179383) 
Specifically, even completely concealed leaves with opaque textures are not culled.
This means that fast leaves don't offer the performance benefit they should.
This can be verified by building leaves adjacent to a wall, and then going inside in spectator mode.
![2020-08-24_17 12 43](https://user-images.githubusercontent.com/37241560/91055816-d6ce9100-e62d-11ea-9d4d-770c340a5d2f.png)

Mojang seem unwilling to fix it. [The same issue was reported back in 2015 and resolved without a fix.](https://bugs.mojang.com/browse/MC-85132)

A fix would greatly improve performance on lower-end devices in forested areas.

OpenJDK; Lithium 0.5.1; Phosphor 0.6.0+build.7; Sodium 0.1.0;

These screenshots demonstrate the slowdown. All screenshots taken right after reloading graphics (f3+t)

Single biome taiga map, 24 chunks view distance, no random ticks or mob spawns. 
![2020-08-24_16 24 14](https://user-images.githubusercontent.com/37241560/91053671-d503ce00-e62b-11ea-9597-d38a4bf1239b.png)
![2020-08-24_16 24 41](https://user-images.githubusercontent.com/37241560/91053686-dcc37280-e62b-11ea-8956-f5705f4ede9c.png)
 
Same map, but with leaves replaced by stone, which provably culls properly.
![2020-08-24_16 42 18](https://user-images.githubusercontent.com/37241560/91053700-e056f980-e62b-11ea-9570-d0925e5e6852.png)
![2020-08-24_16 42 41](https://user-images.githubusercontent.com/37241560/91053706-e351ea00-e62b-11ea-94fa-82444b127e8a.png)

**Comment by Coffee-for-Cats** [comment]
I don't remember if this configuration is present in Sodium, but optine has "smart" as leaves configuration.
I think it would make this problem less significant.

**Comment by Coffee-for-Cats** [comment]
Okay, and we have this comment too: https://github.com/CaffeineMC/sodium-fabric/issues/233#issuecomment-668656707

**Comment by sh-lucas** [comment]
Transparency is probably not an issue: https://github.com/CaffeineMC/sodium-fabric/issues/233#issuecomment-668656707
However, cutting the amount of vectors would help

**Comment by MeeniMc** [comment]
issue is resolved (as of 0.4.10 and probably earlier)

**Comment by pajicadvance** [comment]
Confirmed to be fixed since Sodium 0.3.3.
