### ISSUE TITLE
A certain block crashes Minecraft 1.21.1 using Sodium 0.6 beta 3

### ISSUE THREAD

**Issue by SSavitar1290** [jellysquid3/Sodium#2803]
### Bug Description

https://www.mediafire.com/file/1udgw5n8vjobjz9/2024-10-06_06-41-10.mp4/file
this is the video for the bug (i couldn't get it under 10MB)

### Reproduction Steps

I genuinely have 0 clue as to how to replicate this. 

### Log File

https://paste.ee/p/dBEbF

### Crash Report

[crash-2024-10-06_06.31.14-client.txt](https://github.com/user-attachments/files/17268945/crash-2024-10-06_06.31.14-client.txt)

**Comment by jellysquid3** [comment]
The problem is with MoreCulling. Update your mods.
