### ISSUE TITLE
1.21 NEOFORGE VERSION DOESNT F*UCKING EXIST!?!?!?!?

### ISSUE THREAD

**Issue by Sonic3Modder** [jellysquid3/Sodium#2804]
### Request Description

Why isnt their a version for 1.21 neoforge

**Comment by Lolothepro** [comment]
https://modrinth.com/mod/sodium/version/mc1.21-0.6.0-beta.2-neoforge

**Comment by Sonic3Modder** [comment]
that 1.21.1 i need 1.21

**Comment by Sonic3Modder** [comment]
thx for tryin tho :)

**Comment by Felix14-v2** [comment]
> that 1.21.1 i need 1.21

All mods for 1.21 are compatible with 1.21.1 and vice versa.
