### ISSUE TITLE
Remove the title sodium not supported for pojav. because of new update pojav developers droped

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2807]
### Request Description

I mean this
![Screenshot_2024-10-07-22-54-14-856_net kdt pojavlaunch debug-edit](https://github.com/user-attachments/assets/b68d80c0-2cca-4ba9-b11c-03f9ba31c031)
They finally added new renderer called LTW or tiny wrapper this renderer makes sodium playable and work even in my phone (my phone is Poco f5 5G) and it's really good and the best optimization mod I ever seen
https://github.com/PojavLauncherTeam/PojavLauncher/actions/runs/11180313158
Download link
![374187883-a952e386-0bb5-42e6-b5cc-0965c13542fc](https://github.com/user-attachments/assets/8e7fb45a-d682-47fa-9e7b-4424129ce8f3)

**Comment by jellysquid3** [comment]
There are no plans to remove the notice message.

**Comment by kiokori-git** [comment]
works ≠ supported.

LTW (the new public test renderer) is there to band-aid the game-breaking visual bugs on PojavLauncher running with Sodium, even if you can now finally see the terrain, Sodium will not perform at its best job.

**Comment by Felix14-v2** [comment]
> is there to band-aid the game-breaking visual bugs

Tinywrapper has been implemented to bring the OpenGL 3.3 (and partially 4.2) support to the mobile platform. Working Sodium (and many other mods like Flywheel) is a side effect.

> if you can now finally see the terrain, Sodium will not perform at its best job

Compared to GL4ES, it performs noticeably better — 235 FPS vs 150 FPS in my test scene:
| GL4ES  | LTW |
| --- | --- |
| ![Screenshot_20240622-015828](https://github.com/user-attachments/assets/ae53378a-82c3-464f-a170-3ff68d6b62cf) | ![Screenshot_20241004-195537](https://github.com/user-attachments/assets/ead54e0a-9875-4a01-afea-b83c6c98cb50) |

So this is already +57% improvement, and now Sodium even outperforms VulkanMod (that works on native graphic):
![Screenshot_20240908-234850](https://github.com/user-attachments/assets/4f0a568f-f434-4af4-9735-b3a00da31254)

But yes, I don't think removing the message is necessary, at least until LTW release. Tinywrapper is still in alpha and has its own bugs.

**Comment by ghost** [comment]
I get it

**Comment by kiokori-git** [comment]
> > is there to band-aid the game-breaking visual bugs
> 
> Tinywrapper has been implemented to bring the OpenGL 3.3 (and partially 4.2) support to the mobile platform. Working Sodium (and many other mods like Flywheel) is a side effect.
> 
> > if you can now finally see the terrain, Sodium will not perform at its best job
> 
> Compared to GL4ES, it performs noticeably better — 235 FPS vs 150 FPS in my test scene:
> 
> GL4ES	LTW
> ![Screenshot_20240622-015828](https://github.com/user-attachments/assets/ae53378a-82c3-464f-a170-3ff68d6b62cf)	![Screenshot_20241004-195537](https://github.com/user-attachments/assets/ead54e0a-9875-4a01-afea-b83c6c98cb50)
> So this is already +57% improvement, and now Sodium even outperforms VulkanMod (that works on native graphic): ![Screenshot_20240908-234850](https://private-user-images.githubusercontent.com/75726196/374469461-4f0a568f-f434-4af4-9735-b3a00da31254.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTA1NzUsIm5iZiI6MTcyODM5MDI3NSwicGF0aCI6Ii83NTcyNjE5Ni8zNzQ0Njk0NjEtNGYwYTU2OGYtZjQzNC00YWY0LTk3MzUtYjNhMDBkYTMxMjU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEyMjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YWI5ZWVjOGViYjA3MWYwZDMwNDczOGZiOGY0ODc0Mjk0YWZkNGJlYmEzMGI4ZTJiMmEyZGE2NjQzMTM2Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yHg4_-xZ25tcyMJkI9PrwPyOa9uni4K-riTOYYFmv6o)
> 
> But yes, I don't think removing the message is necessary, at least until LTW release. Tinywrapper is still in alpha and has its own bugs.

mhm 👍

**Comment by ghost** [comment]
> > > is there to band-aid the game-breaking visual bugs
> > 
> > 
> > Tinywrapper has been implemented to bring the OpenGL 3.3 (and partially 4.2) support to the mobile platform. Working Sodium (and many other mods like Flywheel) is a side effect.
> > > if you can now finally see the terrain, Sodium will not perform at its best job
> > 
> > 
> > Compared to GL4ES, it performs noticeably better — 235 FPS vs 150 FPS in my test scene:
> > GL4ES	LTW
> > ![Screenshot_20240622-015828](https://private-user-images.githubusercontent.com/75726196/374467100-ae53378a-82c3-464f-a170-3ff68d6b62cf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTc5NTUsIm5iZiI6MTcyODQxNzY1NSwicGF0aCI6Ii83NTcyNjE5Ni8zNzQ0NjcxMDAtYWU1MzM3OGEtODJjMy00NjRmLWExNzAtM2ZmNjhkNmI2MmNmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIwMDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ODY4ZTRhMjkxOTA2ZmViOTZmYWFkOTAwZGFjYmQ0NDRmZWFmYTg3MmU2YjNjNTgxMjMzMTY2YjRlNTkwMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kujBfKUt21ilZabuKkrbxQcRke29dlc2wrlvtASpNvo)	![Screenshot_20241004-195537](https://private-user-images.githubusercontent.com/75726196/374467836-ead54e0a-9875-4a01-afea-b83c6c98cb50.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MTc5NTUsIm5iZiI6MTcyODQxNzY1NSwicGF0aCI6Ii83NTcyNjE5Ni8zNzQ0Njc4MzYtZWFkNTRlMGEtOTg3NS00YTAxLWFmZWEtYjgzYzZjOThjYjUwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIwMDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTQ4YWIzNDZkOTQxNjUzMzAxN2UwYzY3ZGRkZDIwN2RlNDc4NTM0MDE3NGM3M2U2NThkYjcwNWJmNWZmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MUSK4sBjWQrCMdqq7d9mgJG3vs3g1ZBuDTRxqtZTse0)
> > So this is already +57% improvement, and now Sodium even outperforms VulkanMod (that works on native graphic): ![Screenshot_20240908-234850](https://private-user-images.githubusercontent.com/75726196/374469461-4f0a568f-f434-4af4-9735-b3a00da31254.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTA1NzUsIm5iZiI6MTcyODM5MDI3NSwicGF0aCI6Ii83NTcyNjE5Ni8zNzQ0Njk0NjEtNGYwYTU2OGYtZjQzNC00YWY0LTk3MzUtYjNhMDBkYTMxMjU0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEyMjQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YWI5ZWVjOGViYjA3MWYwZDMwNDczOGZiOGY0ODc0Mjk0YWZkNGJlYmEzMGI4ZTJiMmEyZGE2NjQzMTM2Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yHg4_-xZ25tcyMJkI9PrwPyOa9uni4K-riTOYYFmv6o)
> > But yes, I don't think removing the message is necessary, at least until LTW release. Tinywrapper is still in alpha and has its own bugs.
> 
> mhm 👍

You can also try it
