### ISSUE TITLE
Crash with sodium

### ISSUE THREAD

**Issue by pumkinhead456** [jellysquid3/Sodium#2808]
### Bug Description

Just a crash on startup, logs are not helping, I do not know how to decipher them.

### Reproduction Steps

1. Launch the game (I am using Prism Launcher, with NeoForge 1.21.1)
2. Crash on startup.

### Log File

[debug.log](https://github.com/user-attachments/files/17296740/debug.log)
[latest.log](https://github.com/user-attachments/files/17296743/latest.log)

### Crash Report

[crash-2024-10-08_11.45.35-client.txt](https://github.com/user-attachments/files/17296744/crash-2024-10-08_11.45.35-client.txt)

**Comment by MCRcortex** [comment]
This is not a support forum, nor do you even have sodium installed
