### ISSUE TITLE
Nvidia driver is up to date, however dell gives a weird version number to it

### ISSUE THREAD

**Issue by silverace71** [jellysquid3/Sodium#2809]
### Bug Description

I cannot update the driver to 553+ because I would need admin rights to it. but the dell graphics driver are up to date.
```
[10:08:28] [main/ERROR]:
The game failed to start because the currently installed NVIDIA Graphics Driver is not compatible.
Installed version: 31.0.15.2886
Required version: 536.23 (or newer)
You must update your graphics card driver in order to continue.
For more information, please see: https://github.com/CaffeineMC/sodium-fabric/wiki/Driver-Compatibility#nvidia-gpus
```
im just wondering if there is a jvm flag I can use to disable the driver check since I know it will work. I remember seeing something like -Dsodium.check.win32.intelGen7=false. If theres something like that for Nvidia gpus then that would probably work the best.

### Reproduction Steps

have a dell optiplex, no admin rights, have a dumb driver installed through dell driver manager

### Log File

[latest.log](https://github.com/user-attachments/files/17331245/latest.log)

### Crash Report

no crash report since it wont launch

**Comment by rilakuma123** [comment]
You have version 528.86. Sodium requires 536.23 or newer. You can update your NVIDIA graphics from the NVIDIA website: https://www.nvidia.com/en-us/drivers/details/232670/

> no admin rights

Nothing we can do about that...

**Comment by jellysquid3** [comment]
There is documentation for the various bug check codes here: https://github.com/CaffeineMC/sodium-fabric/wiki/Disabling-Bug-Checks
