### ISSUE TITLE
PLEASE HELP Minecraft wont stop crashing with only a few cool mods that should all be compatable and I cant figure it out :'(

### ISSUE THREAD

**Issue by OGBLaZ1N** [jellysquid3/Sodium#2813]
### Bug Description

Whenever I get into the game i move for about 10 seconds at most (no matter how slow and carefully etc) and it crashes and just give me the below errors and ive tried and tried putting in new/old versions etc and this is just driving me nutso S.O.S. lol

### Reproduction Steps

Same as bug description just load a world and its crashed within 10 seconds MAX 

### Log File

[latest.log](https://github.com/user-attachments/files/17359089/latest.log)

### Crash Report

[crash-2024-10-13_20.20.25-client.txt](https://github.com/user-attachments/files/17359086/crash-2024-10-13_20.20.25-client.txt)

**Comment by MCRcortex** [comment]
This is not a support forum and either update or uninstall physics mod

**Comment by Poopooracoocoo** [comment]
Here's a link to the Discord server https://caffeinemc.net/discord
Make a post in the support-forum channel.

**Comment by OGBLaZ1N** [comment]
> Here's a link to the Discord server https://caffeinemc.net/discord Make a post in the support-forum channel.

This wont work for me it just says the site cant be reached...

**Comment by Poopooracoocoo** [comment]
In that case I'll try to help you. Your version of Sodium is out of date. Updating it to 0.6.0-beta.2 should work with Physics Mod 3.0.20

**Comment by OGBLaZ1N** [comment]
> In that case I'll try to help you. Your version of Sodium is out of date. Updating it to 0.6.0-beta.2 should work with Physics Mod 3.0.20

Thanks i have that one... i am about to try with a new physics mod. will let ya know if it works

**Comment by mrmangohands** [comment]
The link should be fixed now, sorry about that

**Comment by OGBLaZ1N** [comment]
Now its telling me this... 
[crash-2024-10-13_21.07.16-client.txt](https://github.com/user-attachments/files/17359163/crash-2024-10-13_21.07.16-client.txt)

**Comment by Poopooracoocoo** [comment]
You must change your Iris version to match your Sodium version. In this case, you just need the latest version of Iris.

**Comment by OGBLaZ1N** [comment]
ANOTHER ISSUE THIS IS A ENDLESS BROKEN CYCLE 
[crash-2024-10-13_21.12.00-client.txt](https://github.com/user-attachments/files/17359213/crash-2024-10-13_21.12.00-client.txt)

**Comment by Poopooracoocoo** [comment]
> Physics Mod 3.0.16

You've now downgraded your version of Physics Mod... Go back to Physics Mod 3.0.20

Now that the Discord invite works again, we should continue this there.

**Comment by OGBLaZ1N** [comment]
I think its all good now I hope but whats your name on Discord since you were so knowledgeable and quick id love to add ya for easier guidance for the both of us haha mine is OG_BLaZ1N or 965864257688334346

**Comment by OGBLaZ1N** [comment]
I made a post on Discord now please HALP xD
