### ISSUE TITLE
[NeoForge] Sodium Ignores `BakedQuad`'s `isShade()` and `hasAmbientOcclusion()`

### ISSUE THREAD

**Issue by Kneelawk** [jellysquid3/Sodium#2816]
### Bug Description

This issue is occurring with Sodium `mc1.21-0.6.0-beta.2-neoforge` which is the latest version of Sodium as of this writing.

I have a mod where my model implements `IBakedModelExtension.getQuads(...)` and returns baked quads, some of which have set their vertex light-map values to full-bright and set their `isShade()` and `hasAmbientOcclusion()` values to false.

On NeoForge, without Sodium, these quads are clearly visible as emissive. However, when Sodium is installed, these quads suddenly appear much darker, due to the effects of diffuse lighting and ambient occlusion.

Without Sodium installed:
![2024-10-16_05 57 34](https://github.com/user-attachments/assets/fb916565-730d-4cca-ad42-09f9af457fd2)

With Sodium Installed:
![2024-10-16_05 56 53](https://github.com/user-attachments/assets/ff44ee85-194e-46fc-bdc8-d616ffdff77c)

Note: I also tried emitting the same quads using the Fabric Render API instead of NeoForge's `BakedQuad`-based API and the FRAPI quads were lit properly. Only the NeoForge `BakedQuad` quads were improperly lit.

### Reproduction Steps

* Create a mod for NeoForge mod that implements `IBakedModelExtension.getQuads()` and returns a `BakedQuad` that has its light-map values set to full-brightness and its `isShade()` and `hasAmbientOcclusion()` values set to false.
* Test the mod without Sodium and observe the brightness of the quad.
* Test the mod with Sodium and observe that the quad now has diffuse lighting and ambient occlusion effects.

I have a repository that can be used to demonstrate the issue: [Kneelawk/KRender@e7c001b](https://github.com/Kneelawk/KRender/tree/e7c001b0539c56bc801e9dd1c64a6745d3260838). The issue is demonstrated using the example mod `ct_complicated` under the `examples` directory. Note that compiled libs will appear under `build/libs` under the **root directory** of the repository, not under the example's own `build` directory.

### Log File

Gist: https://gist.github.com/Kneelawk/337c5cc530f68a5405b2f55cb453786a
File: [latest.log](https://github.com/user-attachments/files/17395917/latest.log)

### Crash Report

Gist: https://gist.github.com/Kneelawk/16dd2738f44efc1705f9db2f8b976757
File: [crash-2024-10-16_05.41.44-client.txt](https://github.com/user-attachments/files/17395864/crash-2024-10-16_05.41.44-client.txt)

**Comment by douira** [comment]
Can you check if it still happens on [this build](https://github.com/CaffeineMC/sodium-fabric/actions/runs/10986511423), which follows [this commit](https://github.com/CaffeineMC/sodium-fabric/commit/313f21f8bc67d48cc7e17b02e690bca91edf8a5b) that potentially fixes the problem.

**Comment by Kneelawk** [comment]
That seems to have fixed the issue. Thank you!

![2024-10-16_08 21 29](https://github.com/user-attachments/assets/2b6d92e8-ce58-42f0-b8df-5ea63e5862d4)

Should I close the issue now or wait for the fix to be part of an actual release first?

**Comment by douira** [comment]
Thanks
