### ISSUE TITLE
Allow rendering above 32 chunks.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [jellysquid3/Sodium#2819]
### Request Description

Although the issue template states the undermentioned:

> Keep in mind that development is focused on improving performance and fixing graphical bugs, rather than implementing new features (such as resource pack features, additional graphical settings, etc.) We believe that these kinds of features or enhancements are out-of-scope for Sodium, and should be left to other standalone mods.

...Sodium's performance increases are the reason that I request this. However, it is additionally for parity with OptiFine, which provides this functionality.

> Make sure you have used the [search tool](https://github.com/CaffeineMC/sodium-fabric/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) to see if a similar request already exists. If we have previously closed a feature request, then please do not create another request.

https://github.com/CaffeineMC/sodium-fabric/issues?q=sort%3Aupdated-desc+is%3Aissue+render+above+32+chunks returns a few results, but none are relevant.

**Comment by RokeJulianLockhart** [comment]
@JaredRichardWilliam, please confirm!

**Comment by douira** [comment]
There are already four closed issues regarding this on the issue tracker:
- https://github.com/CaffeineMC/sodium-fabric/issues/1279
- https://github.com/CaffeineMC/sodium-fabric/issues/787
- https://github.com/CaffeineMC/sodium-fabric/issues/758
- https://github.com/CaffeineMC/sodium-fabric/issues/178

Regardless of merit, it should be noted that parity with optifine is not a design goal.

See the explanation for why this is not being considered here: https://github.com/CaffeineMC/sodium-fabric/issues/178#issuecomment-1951327087

**Comment by RokeJulianLockhart** [comment]
> See the explanation for why this is not being considered here: https://github.com/CaffeineMC/sodium-fabric/issues/178#issuecomment-1951327087

@douira, thanks. I've filed https://bugs.mojang.com/browse/MC-277669 since although their Jira isn't designed for FRs, I don't see any duplicates at all with https://www.google.com/search?q=site%253Abugs.mojang.com+render+above+32+chunks. Irrespective, perhaps subscribing to https://github.com/orgs/FabricMC/discussions/1587#discussion-3469726 might be of use.

Otherwise, per the answers to https://gaming.stackexchange.com/q/8711/225782, it appears in retrospect that ample mods exist which provide this - apologies.

**Comment by douira** [comment]
As discussed in the linked issue, mods that are involved in getting larger render distances to work can include [C2ME](https://modrinth.com/mod/c2me-fabric), [Bobby](https://modrinth.com/mod/bobby), [Distant Horizons](https://modrinth.com/mod/distanthorizons), [Voxy](https://modrinth.com/mod/voxy). The options provided in the StackExchange answers are extremely outdated as they are 10 years old.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/CaffeineMC/sodium-fabric/issues/2819#issuecomment-2420738564

@douira, fixed now - https://gaming.stackexchange.com/a/409811/225782. [^1] Thank you again.

[^1]: https://gaming.stackexchange.com/revisions/409811/1
