### ISSUE TITLE
It crashed with my M1 apple silicon before it even start

### ISSUE THREAD

**Issue by Psychodeus** [jellysquid3/Sodium#2820]
### Reproduction Steps

Add the distant horizon + sodium to the mods folder, and it produce this.

### Log File

https://mclo.gs/qFkoLZV

### Crash Report

[crash-2024-10-05_22.01.06-client.txt](https://github.com/user-attachments/files/17429867/crash-2024-10-05_22.01.06-client.txt)

**Comment by Poopooracoocoo** [comment]
This isn't due to a macOS arm64 incompatibility. This is due to an outdated version of Flashback.

**Comment by ghost** [comment]
> This isn't due to a macOS arm64 incompatibility. This is due to an outdated version of Flashback.

So can it be fixed?

**Comment by jellysquid3** [comment]
Yes. There is no problem with Sodium... you just have an outdated version of Flashback -- update your mods.

**Comment by ghost** [comment]
I've checked, and there is no flashback mod in my mods folder. So the reason is different.
![image](https://github.com/user-attachments/assets/b38b79d6-972c-421c-8aeb-bfa78856153b)

**Comment by douira** [comment]
Your logs indicate that you do have a wrong version of flashback installed. Please come to the discord server for support. This is not a support forum.
