### ISSUE TITLE
Add the sodium button files in the sodium.jar file so that you can change it with texture pack

### ISSUE THREAD

**Issue by 60Trees** [jellysquid3/Sodium#2821]
### Request Description

Make it so that you can extract the sodium jar files to get the sodium buttons 
![Sodium-mod-for-minecraft-04](https://github.com/user-attachments/assets/0cf09c8d-c709-4c67-b6a9-3c9dd8a5cd65)
as a resource pack so that ppl can change how it looks plz
the current menu buttons I want to change, please add this feature

**Comment by jellysquid3** [comment]
Sodium uses vector graphics to render the user interface, not textures. We are not going to change that.
