### ISSUE TITLE
Sodium Doesn't No-op on Dedicated Server

### ISSUE THREAD

**Issue by sylv256** [jellysquid3/Sodium#2822]
### Bug Description

Sodium is supposed to no-op on dedicated servers similar to its behavior on Fabric. However, it instead loads forcefully.

### Reproduction Steps

- Use Sodium `0.6.0-beta.2` in a NeoForge dedicated server

### Log File

[latest.log](https://github.com/user-attachments/files/17446824/latest.log)

### Crash Report

[2024-10-19-7.log.gz](https://github.com/user-attachments/files/17446833/2024-10-19-7.log.gz)

**Comment by Lolothepro** [comment]
https://github.com/CaffeineMC/sodium-fabric/pull/2773 is merged

**Comment by douira** [comment]
The issue shouldn't happen anymore if you use the GH Action build on the linked PR.
