### ISSUE TITLE
unable to load the mod on neoforge server 

### ISSUE THREAD

**Issue by VaporeonScripts** [jellysquid3/Sodium#2829]
### Bug Description

https://mclo.gs/gmEFB1C

### Reproduction Steps

add the mod to server

### Log File

https://mclo.gs/gmEFB1C

### Crash Report

https://mclo.gs/gmEFB1C

**Comment by Altirix** [comment]
remove the mod from the server. the server does not render the game.

https://github.com/CaffeineMC/sodium-fabric/commit/bade2280486f9548038af2de2363d0aa4346f3d4 makes it so the server will noop if its not in a client instance. 

https://github.com/CaffeineMC/sodium-fabric/issues/2822 & https://github.com/CaffeineMC/sodium-fabric/pull/2773. will probs see this in the next beta. beta 2 does not have this commit.

**Comment by VaporeonScripts** [comment]
i know, but shouldnt it skip it like all client mods?, also, ok
