### ISSUE TITLE
Game crashes when opening inventory, after some time of playing on the server

### ISSUE THREAD

**Issue by AREKKUZZERA** [jellysquid3/Sodium#2833]
### Bug Description

Minecraft crashes when opening inventory after playing on a server for a while. This doesn't happen the first time you open inventory in creative mode, but 8-10 times. I searched for information about this error myself, found that Legendary hints can cause this crash, disabled them, but it still continues.

### Reproduction Steps

Play in your world or on a server for about 10-15 minutes and open your inventory in creative several times.

### Log File

[latest.log](https://github.com/user-attachments/files/17505378/latest.log)

### Crash Report

[crash-2024-10-24_13.09.38-client.txt](https://github.com/user-attachments/files/17505385/crash-2024-10-24_13.09.38-client.txt)

**Comment by NotRyken** [comment]
@AREKKUZZERA Just FYI your `latest.log` doesn't match your crash report, it's a few minutes later and doesn't appear to show anything related. The actual corresponding log should be in an archive in the logs folder.

**Comment by AREKKUZZERA** [comment]
> @AREKKUZZERA Just FYI your `latest.log` doesn't match your crash report, it's a few minutes later and doesn't appear to show anything related. The actual corresponding log should be in an archive in the logs folder.

Sorry, but there is no earlier log, but I did not change the configuration of mods and the rest

**Comment by NotRyken** [comment]
Well, there's nothing evidently Sodium-related there so this is more of a support request than a bug report, so Discord would be the appropriate channel.

**Comment by Moistio** [comment]
Have the same issue for over a month now wondering if you have any success with fixing the error? I get the same error after some time when I press ESC, E, or T for chat. The error is always nullpointerexception

**Comment by douira** [comment]
Please come to the discord server for support requests. This is not a support forum and there doesn't seem to be a clear bug with sodium here.
