### ISSUE TITLE
Above of Sodium v0.5.9 results in LWJGL version mismatch error

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2841]
### Bug Description

 I can only launch MC `1.21.1` with Sodium `v0.5.9`, above of that complains about LWGJL version mismatch error. I do use FreeBSD and installed prism launcher with package manager.

### Reproduction Steps

1. Install Prism Launcher `v9`
2. Select Java 21
3. Install Minecraft `1.21.1` with latest Sodium Fabric
4. Get the error saying `[21:44:21] [main/ERROR]: The game failed to start because the currently active LWJGL version is not compatible.`

### Log File

[version5.9-log.txt](https://github.com/user-attachments/files/17526374/version5.9-log.txt)
[version6.0-beta2-log.txt](https://github.com/user-attachments/files/17526375/version6.0-beta2-log.txt)

### Crash Report

None.

**Comment by ghost** [comment]
I just tried latest versions of both MC and Sodium and got the same error. I was running Minecraft fine with Sodium version `0.5.9`.
[0.6.0-beta.3-mc-1.21.3.txt](https://github.com/user-attachments/files/17526497/0.6.0-beta.3-mc-1.21.3.txt)

**Comment by jellysquid3** [comment]
There is no problem with Sodium. The log file tells you what the problem is:

```
[21:37:11] [main/ERROR]: The game failed to start because the currently active LWJGL version is not compatible.

Installed version: 3.3.4-snapshot
Required version: 3.3.3

It appears you are using Prism Launcher to start the game. You can likely fix this problem by opening your instance settings and navigating to the Version section in the sidebar.

For more information, please see: https://github.com/CaffeineMC/sodium-fabric/wiki/LWJGL-Compatibility
```

**Comment by ghost** [comment]
I tried if i could do something but i couldn't.
![image](https://github.com/user-attachments/assets/5503b418-9bf6-4a6d-b0bb-28e4883eb21f)

**Comment by jellysquid3** [comment]
It might be the case that a patched version of LWJGL is being used to make the game work on (*)BSD... You can try to ask Sodium to not care so much about the version number by [disabling the bug check](https://github.com/CaffeineMC/sodium-fabric/wiki/Disabling-Bug-Checks) related to this. But the mod tends to be pretty sensitive to internal details of LWJGL, so this might not work.

**Comment by ghost** [comment]
Thanks, I disabled lwjgl version check by adding that flag to java arguments in prism launcher instance settings and both 1.21.3 and 1.21.1 ran successfully.

**Comment by KatyushaScarlet** [comment]
For someone who encounters the same problem as I did, just add the following flag to JAVA:
```
-Dsodium.checks.issue2561=false
```
This will disable the LWJGL version check for Sodium.
