### ISSUE TITLE
ATM 8 Crash after using Garden clothe

### ISSUE THREAD

**Issue by vertan1337** [jellysquid3/Sodium#2843]
### Bug Description

garden clothe

### Reproduction Steps

immersive engenering garden clothe

### Log File

sss

### Crash Report

The game crashed whilst rendering block entity
Error: java.lang.IllegalArgumentException: The class blusunrize.immersiveengineering.client.utils.TransformingVertexBuilder does not implement interface VertexBufferWriter, which is required for compatibility with Sodium (see: https://github.com/CaffeineMC/sodium-fabric/issues/1620)

**Comment by vertan1337** [comment]
pls help

**Comment by douira** [comment]
Duplicate of https://github.com/CaffeineMC/sodium/issues/2827. The issue is fixed with the next release.
