### ISSUE TITLE
PneumaticCraft Gauge rendering is broken by Sodium

### ISSUE THREAD

**Issue by MuteTiefling** [jellysquid3/Sodium#2847]
### Bug Description

https://github.com/TeamPneumatic/pnc-repressurized/issues/1363

### Reproduction Steps

Place some PNC tubes
Place 2 or more Gauges on them. 

### Log File

https://gist.github.com/MuteTiefling/94d9c22d5543d134ce50dbbb189ac770

### Crash Report

https://gist.github.com/MuteTiefling/19b0688d2ebf2d697ece4a35d854f1ee

**Comment by MuteTiefling** [comment]
Cannot reproduce without Sodium.

**Comment by Lolothepro** [comment]
try without Iris, it can be caused by Iris

**Comment by MuteTiefling** [comment]
Yeah, it is in fact Iris, sorry about that.
