### ISSUE TITLE
Non `isVanillaAdapter` item models cause a crash

### ISSUE THREAD

**Issue by SuperMartijn642** [jellysquid3/Sodium#2849]
### Bug Description

This concerns the Fabric version of Sodium for Minecraft 1.21.3 and is specifically related to the Fabric Rendering API.

Returning `false` for `FabricBakedModel#isVanillaAdapter` for an item model results in a crash when that model is rendered. Even when overriding `FabricBakedModel#emitItemQuads` to do nothing, it still results in a crash, hence it seems it is caused purely by the `FabricBakedModel#isVanillaAdapter` result.

### Reproduction Steps

Add the following snippet to the client initialization entry point:
```java
ModelLoadingPluginManager.registerPlugin(pluginContext -> {
    pluginContext.modifyModelAfterBake().register((bakedModel, modelContext) ->{
        if(modelContext.sourceModel() instanceof ItemModel itemModel && itemModel.id.equals(ResourceLocation.parse("minecraft:item/cobblestone"))){
            var forwardingBakedModel = new ForwardingBakedModel() {
                @Override
                public boolean isVanillaAdapter(){
                    return false;
                }

                public void setModel(BakedModel model){
                    this.wrapped = model;
                }
            };
            forwardingBakedModel.setModel(bakedModel);
            return forwardingBakedModel;
        }
        return bakedModel;
    });
});
```
The snippet replaces the cobblestone item model with a `ForwardingBakedModel` wrapping the original item model, but which returns `false` for `FabricBakedModel#isVanillaAdapter`. The `ForwardingBakedModel` returns the same as the original model for any other methods in `BakedModel`.

The snippet also requires an access widener entry for the `ItemModel#id` field:
`accessible field net/minecraft/client/resources/model/ItemModel id Lnet/minecraft/resources/ResourceLocation;`

With the snippet added, simply try to look at a cobblestone item and it will cause a crash.

### Log File

[latest.log](https://github.com/user-attachments/files/17556619/latest.log)
The log shows Moving Elevators as a mod as that is what I used for testing, but it is stripped down to include nothing but the snippet given.

### Crash Report

[crash-2024-10-29_13.16.50-client.txt](https://github.com/user-attachments/files/17556626/crash-2024-10-29_13.16.50-client.txt)

**Comment by jellysquid3** [comment]
@IMS212 This random `PoseStack#popStack()` in the code for [FRAPI item model integration](https://github.com/CaffeineMC/sodium/blob/f3bbc54e4dfdf2c08e7ca32c56584d1d170ebdc3/common/src/main/java/net/caffeinemc/mods/sodium/mixin/features/render/frapi/ItemRendererMixin.java#L60) seems highly suspect...

**Comment by IMS212** [comment]
Removed that. Seems to have been a leftover from 1.21.1.

**Comment by jellysquid3** [comment]
Fixed with https://github.com/CaffeineMC/sodium/commit/740107520f8710dc3e790f8a1aa502fc90d35816. The [latest nightly build](https://nightly.link/CaffeineMC/sodium/workflows/build-commit/dev/sodium-artifacts-dev.zip) contains the fix but we haven't packaged it into a release yet.

**Comment by jellysquid3** [comment]
Sodium 0.6.0-beta.5 is published and resolves this issue.
