### ISSUE TITLE
game crash when trying to go in a solo world 

### ISSUE THREAD

**Issue by aestheticccccc** [jellysquid3/Sodium#285]
I tried to reinstall fabric and sodium but nothing changed, here is the error that I get : https://pastebin.com/eJQnguW9
Minecraft is in 1.16.1 by the way

**Comment by aestheticccccc** [comment]
there is a different error now : https://pastebin.com/yH0Uycpx

**Comment by LucilleTea** [comment]
Your second error is #219 
The solution is to delete sodium-options.json from the config folder as it has been corrupted.
I'm not sure what your first error is or whether it should be gone now. The issue tracker is intended to track bugs, not for tech support, so I recommend that you [join the discord server](https://jellysquid.me/discord) if you need further support.

**Comment by aestheticccccc** [comment]
thank you very much this is working now
