### ISSUE TITLE
Face culling no longer works between blocks of different render types

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#2850]
### Bug Description

In the latest Sodium betas, cutout, cutout_mipped and translucent blocks do not get culled at all by solid blocks, which is obviously a bad thing since some faces are getting pointlessly rendered now.
![2024-10-29_13 16 04](https://github.com/user-attachments/assets/699f23a2-ffae-431a-8154-a784e9e1d3f6)
![2024-10-29_13 16 11](https://github.com/user-attachments/assets/ebed8351-1043-43e3-8ede-0ecc22961c67)

### Reproduction Steps

- Place an affected transparent block of your choice on the floor
- Enter Spectator mode
- Clip into the floor and observe

### Log File

[latest.log](https://github.com/user-attachments/files/17557369/latest.log)

### Crash Report

[crash-2024-10-29_13.20.21-client.txt](https://github.com/user-attachments/files/17557379/crash-2024-10-29_13.20.21-client.txt)

**Comment by jellysquid3** [comment]
Do you know which version this was regressed? It would be helpful to have a bisect.

**Comment by muzikbike** [comment]
The issue appears to have first arisen in beta 3 and was not present in beta 1 or 2.

**Comment by jellysquid3** [comment]
This only seems to happen in Minecraft 1.21.3, and works correctly in Minecraft 1.21.1.

**Comment by jellysquid3** [comment]
The commit https://github.com/CaffeineMC/sodium/commit/990cf64885b50d0180a243328a2c28d5c7c4cfb2 fixes this problem and will be made part of the next release.
