### ISSUE TITLE
Crash on Loading Into World - Fabric 1.21.1

### ISSUE THREAD

**Issue by iyloMC** [jellysquid3/Sodium#2851]
### Bug Description

Instant crash upon loading into a world on a Fabric 1.21.1 server. Fabric version 0.6.0-beta.4+mc1.21.1. Updated the **Fabulously** **Optimized** Modpack (6.2.1) to use Sodium version listed above, Iris 1.8.0-beta.4, Reese's Sodium Options 1.8.0-beta.4, and Sodium Extra 06.60-beta.3 (all the most recent versions), as well as added Distant Horizons 2.2.1-a-1.21.1. Controllify was disabled in order to help with another crash involving Reese's

### Reproduction Steps

Attempt to join a 1.21.1 server with the configuration above.

### Log File

https://mclo.gs/chHpC1P

### Crash Report

https://mclo.gs/t8gBa2W

**Comment by Timolino456** [comment]
> at knot/ca.fxco.moreculling.utils.CullingUtils.areLeavesOpaque(CullingUtils.java:92) ~[moreculling-1.21-0.26.0.jar:?]

Remove More Culling.

**Comment by iyloMC** [comment]
> > at knot/ca.fxco.moreculling.utils.CullingUtils.areLeavesOpaque(CullingUtils.java:92) ~[moreculling-1.21-0.26.0.jar:?]
> 
> Remove More Culling.

Thank you.
