### ISSUE TITLE
0.6.0.beta4 cause crash, 0.6.0.beta2 works fine

### ISSUE THREAD

**Issue by Horizoll** [jellysquid3/Sodium#2853]
### Bug Description

Always Check Up for UpDates, as the Title Says, New Version Crashes Upon Launch Right After Creating New World!

### Reproduction Steps

1.Launch Game
2.Create New World
3.Get Crash

### Log File

[2024-10-30-4.log.gz](https://github.com/user-attachments/files/17568770/2024-10-30-4.log.gz)

### Crash Report

[crash-2024-10-30_12.19.41-client.txt](https://github.com/user-attachments/files/17568737/crash-2024-10-30_12.19.41-client.txt)

**Comment by MCRcortex** [comment]
Remove chunksfadein

**Comment by Horizoll** [comment]
Is It Possible for This Mode to Be Compatible in Future?

**Comment by Felix14-v2** [comment]
CFI author already knows about the incompatibility, just wait for the update from his side.
