### ISSUE TITLE
Add instructions for disabling LWJGL version checks on the wiki page.

### ISSUE THREAD

**Issue by KatyushaScarlet** [jellysquid3/Sodium#2855]
### Request Description

I am playing Minecraft on a relatively rare architecture, loongarch64, and trying to use Sodium 0.6.0-beta4 to optimize the gaming experience. Since this architecture is not officially supported by LWJGL, some launchers (like HMCL) have compiled the 3.3.4-rc version of LWJGL for it.
After some searching, I found a workaround: passing a flag to Java (`-Dsodium.checks.issue2561=false`) to disable the LWJGL version check. 
Running Minecraft with an unsupported LWJGL version hasn’t caused any issues for me.
Therefore, I believe it might be necessary to add additional instructions on this [wiki page](https://github.com/CaffeineMC/sodium/wiki/LWJGL-Compatibility) to guide players facing similar issues to temporarily resolve the problem.

**Comment by KatyushaScarlet** [comment]
![Screenshot_20241030_205143](https://github.com/user-attachments/assets/3ea69e7b-62fe-4872-8893-dd1495208ba8)

**Comment by jellysquid3** [comment]
This is already documented on our Wiki.
https://github.com/CaffeineMC/sodium/wiki/Disabling-Bug-Checks
But it seems we forgot to link it to the other pages so that it is more accessible.

**Comment by KatyushaScarlet** [comment]
> This is already documented on our Wiki. https://github.com/CaffeineMC/sodium/wiki/Disabling-Bug-Checks But it seems we forgot to link it to the other pages so that it is more accessible.

Oh, sorry, I missed that.
