### ISSUE TITLE
Sodium not allowing me to load into a singeplayer world.

### ISSUE THREAD

**Issue by ChefPhasmo** [jellysquid3/Sodium#2856]
### Bug Description

I went into curseforge to ask for some help as out of no where when i updated my sodium it disallowed me to load any singleplayer worlds i had. It took me a good day to figure out as to what mod or issue was preventing me from loading into my game, until i disabled sodium and i was perfectly fine and could do everything i did before. I noticed that sodium was updated recently and II believe the new update has some issue thats conflicting with my minecraft game.

### Reproduction Steps

1. Make a new modpack with fabric 1.21.1
2. download sodium version mc1.21-0.6.0-beta.2-fabric
3. launch the game and start a world to see it works, close minecraft
4. update sodium to the most recent version which i believe is mc1.21.1-0.6.0-beta.4-fabric
5. then relaunch your game and attempt to join the world you created and you will see my issue.

### Log File

[latest.log](https://github.com/user-attachments/files/17581063/latest.log)

### Crash Report

[message (1).txt](https://github.com/user-attachments/files/17581068/message.1.txt)

**Comment by pajicadvance** [comment]
Disable Chunks Fade In.

**Comment by ChefPhasmo** [comment]
I fuckin love you dude. Thank you very much. Took curseforge discord mods a whole day before i was able to hop back on my world and you fixed it in 2 mins. Fucking legend!
