### ISSUE TITLE
Clouds are colored blue with night vision at specific rotation angles at certain times of day

### ISSUE THREAD

**Issue by MoriyaShiine** [jellysquid3/Sodium#2858]
### Bug Description

The only mod I have installed is Sodium fabric-0.6.0-beta.4+mc1.21.3, on Fabric Loader 0.16.9.

Expected behavior: clouds should be colored consistently, as they are in vanilla.

Observed behavior: clouds are colored a deep blue under these specific conditions:
- The night vision effect is active
- When the camera's rotation vector is at or around (90 , 0)
- Only at certain times of day, roughly between 12300 and 12900, with the rotation vector's allowed deviation increasing the closer it is to the median of those two times (ie at times 12300 and 12900, only very close to (90 , 0) applies, while at time 12450 clouds are affected at larger ranges further from (90 , 0) as far as (90+-30 , +-30)

https://github.com/user-attachments/assets/acaa4624-656e-4d34-aaf2-a1d9e0430f5f

### Reproduction Steps

- Load into a world
- Give yourself Night Vision
- Orient yourself to (90, 0)
- Set time to 12450 and see the clouds turn blue

### Log File

[latest.log](https://github.com/user-attachments/files/17602547/latest.log)

### Crash Report

[crash-2024-11-01_12.26.05-client.txt](https://github.com/user-attachments/files/17602545/crash-2024-11-01_12.26.05-client.txt)

**Comment by pajicadvance** [comment]
Can reproduce

**Comment by jellysquid3** [comment]
Thank you for the detailed report. This is fixed with the patch https://github.com/CaffeineMC/sodium/commit/5b3777725d356d10f819c9e00445c89820f66295, which is already available in the latest [nightly build](https://nightly.link/CaffeineMC/sodium-fabric/workflows/build-commit/dev/sodium-artifacts-dev.zip). We'll publish a new release next week with the fix.
