### ISSUE TITLE
Game crashes randomly 1.21.1, 0.6.0-beta 4

### ISSUE THREAD

**Issue by Hiranus** [jellysquid3/Sodium#2859]
### Bug Description

It's hard for me to give any details here. Minecraft just randomly closes, and it's not like it's always happening when I do some specific thing, it's just random. There is also nothing in the log, the only thing that indicates that there was a crash is hs_err_pid...log file I attached in logs section.
The only thing I can tell is that it started happening during last week or so, maybe few days.

### Reproduction Steps

Sadly, I have no idea how to reproduce this. For me, it just happens randomly.

### Log File

[hs_err_pid12764.log](https://github.com/user-attachments/files/17604070/hs_err_pid12764.log)
[latest.log](https://github.com/user-attachments/files/17604071/latest.log)

Here are few older logs.
[hs_err_pid28392.log](https://github.com/user-attachments/files/17604126/hs_err_pid28392.log)
[hs_err_pid30392.log](https://github.com/user-attachments/files/17604127/hs_err_pid30392.log)
[hs_err_pid36856.log](https://github.com/user-attachments/files/17604128/hs_err_pid36856.log)

### Crash Report

[crash-2024-11-01_22.12.12-client.txt](https://github.com/user-attachments/files/17604187/crash-2024-11-01_22.12.12-client.txt)

**Comment by jellysquid3** [comment]
These JVM crashes look random and seem to be the result of memory corruption across the game. Are you sure that your computer is stable? You may want to use a tool like [OCCT](https://www.ocbase.com/) to verify that your CPU and RAM is functioning correctly.

**Comment by jellysquid3** [comment]
That said, your log file also shows non-descript OpenGL errors:
```
[01Nov2024 21:45:04.244] [Render thread/INFO] [com.mojang.blaze3d.platform.GlDebug/]: OpenGL debug message: id=1057, source=API, type=ERROR, severity=HIGH, message='No detailed debug message due to a non-debug context'
```

Please try turning off `Use No Error Context` in `Video Settings > Performance` to see if it provides any additional diagnostic information.

**Comment by Hiranus** [comment]
> These JVM crashes look random and seem to be the result of memory corruption across the game. Are you sure that your computer is stable? You may want to use a tool like [OCCT](https://www.ocbase.com/) to verify that your CPU and RAM is functioning correctly.

I let that thing run in the past for hour or so without any issues.

**Comment by jellysquid3** [comment]
I don't see any problem with Sodium here. The crashes point to random faults in memory-hard code, and there is no pattern between any of the failures.

My only advice for you is that you check to see if any overclocking settings are enabled, such as _Precision Boost Overdrive_ or _Curve Optimizer_. We have seen many reports of similar issues to yours which have been traced back to unstable negative offsets in Curve Optimizer, which OCCT would not necessarily catch.
