### ISSUE TITLE
Crash at game start

### ISSUE THREAD

**Issue by ShummyB** [jellysquid3/Sodium#286]
### Reproduction Steps
 1. Drop the latest version of sodium mod into mods file
 2. Click on Play button using the latest profile & version of fabric launcher.

### Crash Report File
https://gist.github.com/ShummyB/deaede6273e81c7cff9d874ee3d879c1

### Additional info
I updated Windows to the latest version today.

**Comment by jellysquid3** [comment]
```
[Info: 2020-08-27 16:09:14.1005519: GameCallbacks.cpp(163)] Game/FabricLoader (main) Info Loading for game Minecraft 1.16.2
```

Sodium is not available for Minecraft 1.16.2. You will need to use Minecraft 1.16.1.
