### ISSUE TITLE
Blocks losing textures and become white and red

### ISSUE THREAD

**Issue by wiittymystic** [jellysquid3/Sodium#2860]
### Bug Description

when i go under water it turns all the blocks white, and when i enter the nether its either red and white or just white all together, sometimes itll switch for a spilt second but it gets in theway
![Screenshot (56)](https://github.com/user-attachments/assets/e78613d2-1202-45db-ac62-a20d4dc9858c)
![Screenshot (54)](https://github.com/user-attachments/assets/7153e798-9fe8-4265-8609-a8ad985e7e10)

### Reproduction Steps

i made a world with just fabric api and sodium, recorded what was happening. Its either go underwater, or enter the nether. I do have a video but it wont let me upload it.

### Log File

https://mclo.gs/U3jSbiQ

### Crash Report

https://mclo.gs/JKbOH1V

**Comment by jellysquid3** [comment]
Disable the OverWolf overlay. It is broken and is corrupting the game's state.

**Comment by wiittymystic** [comment]
im not using overwolf, im using modrith

**Comment by jellysquid3** [comment]
Your log file shows the OverWolf overlay is loaded into the game:

```
GEPPlugin64.dll:GEPPluginDLL:**.**.**.**:Overwolf LTD
OWClient.dll:Overlay:**.**.**.**:Overwolf LTD
OWExplorer.dll:Overlay:**.**.**.**:Overwolf LTD
OWUtils.dll:Overlay:**.**.**.**:Overwolf LTD
libowgameevents64.dll:Overwolf Game Events SDK:**.**.**.**:Overwolf LTD
```

If you have their broken software installed, it hacks into Minecraft even if you aren't using the launcher.

**Comment by jellysquid3** [comment]
This problem is now tracked with https://github.com/CaffeineMC/sodium/issues/2862 since too many people are reporting issues.

**Comment by rilakuma123** [comment]
Also reported in [Discord server](https://caffeinemc.net/discord): https://discord.com/channels/602796788608401408/1300160170323873874
