### ISSUE TITLE
 Rendering giant tools in hand and in inventory issue - Twilight Forest Unofficial (Fabric 1.20.1)

### ISSUE THREAD

**Issue by marlester-dev** [jellysquid3/Sodium#2861]
### Bug Description

Without Sodium (normal):
![without](https://github.com/user-attachments/assets/729e0b62-73c2-45ed-84e9-91f2ad0e7783)
![without2](https://github.com/user-attachments/assets/74f8ff4e-992f-4985-8ed1-a7af42eb2b19)
With Sodium:
![with](https://github.com/user-attachments/assets/255fe46f-ee2c-4e28-a6d9-a484acd643c6)
![with2](https://github.com/user-attachments/assets/df212d03-dfec-4bcb-9c77-a9457d30a705)

### Reproduction Steps

1. Install Fabric API, [The Twilight Forest Unofficial](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest-unofficial), Sodium and Indium
2. Log in and take the giant items out of the creative inventory
3. They are not so giant anymore in hand and in inventory

I'm the dev of the mod, so you can ask me any questions you want.
Code of the mod: https://github.com/marlester-dev/twilightforest-unofficial
Possibly because of: https://github.com/marlester-dev/twilightforest-unofficial/blob/1.20.1-fabric/src/main/java/twilightforest/mixin/ItemRendererMixin.java , https://github.com/marlester-dev/twilightforest-unofficial/blob/1.20.1-fabric/src/main/java/twilightforest/client/renderer/GiantItemRenderHelper.java , https://github.com/marlester-dev/twilightforest-unofficial/blob/1.20.1-fabric/src/main/java/twilightforest/mixin/ModelLoaderMixin.java , https://github.com/marlester-dev/twilightforest-unofficial/blob/1.20.1-fabric/src/main/java/twilightforest/client/model/TFItemLayerModel.java , https://github.com/marlester-dev/twilightforest-unofficial/blob/1.20.1-fabric/src/main/java/twilightforest/data/ItemModelGenerator.java#L78

### Log File

https://pastebin.com/n6wyCyNB

**Comment by marlester-dev** [comment]
fixed on the mod's side by using
```java
	@WrapOperation(method = "render", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/renderer/entity/ItemRenderer;renderModelLists(Lnet/minecraft/client/resources/model/BakedModel;Lnet/minecraft/world/item/ItemStack;IILcom/mojang/blaze3d/vertex/PoseStack;Lcom/mojang/blaze3d/vertex/VertexConsumer;)V"))
	private void startRenderItem(ItemRenderer instance, BakedModel model, ItemStack stack, int combinedLight, int combinedOverlay, PoseStack matrixStack, VertexConsumer buffer, Operation<Void> original) {
		if (stack.getItem() instanceof GiantItem) {
			matrixStack.pushPose();
			GiantItemRenderHelper.handle(matrixStack);
			original.call(instance, model, stack, combinedLight, combinedOverlay, matrixStack, buffer);
			matrixStack.popPose();
		} else {
			original.call(instance, model, stack, combinedLight, combinedOverlay, matrixStack, buffer);
		}
	}
```

**Comment by marlester-dev** [comment]
you may close this issue if you want

**Comment by jellysquid3** [comment]
I don't think anything needs to be done on our side here, since the best way to avoid this is by rewriting the mixin as you have.
