### ISSUE TITLE
Clouds lose their bottom face when the camera is near their bottom

### ISSUE THREAD

**Issue by haykam821** [jellysquid3/Sodium#2863]
With version 0.6.0 beta 4 on Minecraft 1.21.3 with Fabric, clouds lose their bottom face despite the camera not being inside the cloud, which causes a strange appearance when looking at clouds from outside.

<img width="1489" alt="Clouds with no bottom faces as seen from the third-person back perspective" src="https://github.com/user-attachments/assets/bd040b25-f4c6-4582-bb6f-4913aeae4599">

The following command teleports the player to a position where this issue can be seen in the first-person perspective: `/tp @s ~ 190.380001 ~`. This issue does not occur when Sodium is removed.

**Comment by douira** [comment]
I have a fix for this, I'll make a PR momentarily.
