### ISSUE TITLE
INTEL_FRAMEBUFFER_BLIT_CRASH_WHEN_UNFOCUSED

### ISSUE THREAD

**Issue by x-yingcan-x** [jellysquid3/Sodium#2872]
### Bug Description

Game crashes when  minimize the game window/tab out from fullscreen  and only when doing so, no matter anything else you do. 
Game won't crash if you just tab out but not minimize the window(when not fullscreen).

(Sorry, Discord is blocked in my region, so I don't have choice)

### Reproduction Steps

1. Install Fabric, Fabric API, sodium.
2. Launch your client.
3. Minimize the game window
4. Game crashes

### Log File

[latest.log](https://github.com/user-attachments/files/17691559/latest.log)

### Crash Report

[crash-2024-11-10_21.27.04-client.txt](https://github.com/user-attachments/files/17691573/crash-2024-11-10_21.27.04-client.txt)

**Comment by Lolothepro** [comment]
Isn't that a Minecraft Vanilla bug?

**Comment by x-yingcan-x** [comment]
last time, sodium crashes when tab out, i just thought its the same lol, my bad

**Comment by x-yingcan-x** [comment]
> Isn't that a Minecraft Vanilla bug?

btw, is there anything mod to fix this?

**Comment by Felix14-v2** [comment]
> btw, is there anything mod to fix this?

I can assume that the issue you are experiencing is a bug with the new 1.21.2 feature — automatic FPS reduction when you minimize the game window. Please, check if the crash occurs in 1.21.1. Also, please, send the hs_err_pid file, if Minecraft creates one after the crash.

**Comment by x-yingcan-x** [comment]
[hs_err_pid18436.log](https://github.com/user-attachments/files/17692389/hs_err_pid18436.log)
either AFK or minimize will crash the game and i have to choose one...
not happening on 1.21.1
maybe i should just report it

**Comment by Lolothepro** [comment]
probably https://bugs.mojang.com/browse/MC-276962

**Comment by jellysquid3** [comment]
Wait, so it is the case that Sodium implemented an optimization in the last release, found a driver bug, patched the driver bug, and then Mojang encountered the _exact same driver bug_ and hasn't fixed it?

**Comment by jellysquid3** [comment]
We already have the code to detect and workaround this. It would _probably_ not be difficult to apply it to Mojang's code as well to avoid these crashes.

**Comment by jellysquid3** [comment]
Ah... Mojang changed it so that shaders aren't compiled before the framebuffer blit function is called. So we can't fallback to shaders on broken drivers since the loading screen will need blits. This is probably why they changed the code to no longer use shaders for basic blits in the first place.
