### ISSUE TITLE
Wear error wirh sodium rei and DRAWERS STORAGE 

### ISSUE THREAD

**Issue by arkhanan** [jellysquid3/Sodium#2874]
### Bug Description

https://github.com/jaquadro/StorageDrawers/issues/1179

I put this link because i check with the moder of storage drawers and the Game crash only with a fews mods 

### Reproduction Steps

Ok , curese forge create new mod pack and instal: 
IRIS, SODIUM, EXTRA SODIUM, REESE SODIUM, REI AND DRAWERS STORAGE 

Game versión 1.21.3 , last versión fabrica 
https://github.com/jaquadro/StorageDrawers/issues/1179, in this inout name all mods 

### Log File

https://github.com/jaquadro/StorageDrawers/issues/1179

### Crash Report

https://github.com/jaquadro/StorageDrawers/issues/1179

**Comment by jellysquid3** [comment]
Does this still happen with Sodium 0.6.0-**beta.5**? (link to [Modrinth](https://modrinth.com/mod/sodium/versions).) There was a bug fixed in it which probably relates to this.

**Comment by jellysquid3** [comment]
The x-linked issue says it's fixed, so I'm closing this.
