### ISSUE TITLE
Fps Not Boosting

### ISSUE THREAD

**Issue by Alpake** [jellysquid3/Sodium#2875]
### Bug Description

I use sodium on curseforge because the normal minecraft launcher gives me worse fps, I always use a mod called Notifine which also has a bunch of others fps boost mods like lithium. But for some reason sodium doesn't work at all.

### Reproduction Steps

idk

### Log File

im dum

### Crash Report

nothing

**Comment by douira** [comment]
Please come to our [discord server](https://jellysquid.me/discord) so that we can help you with this support request.
