### ISSUE TITLE
Crash while starting playing a world when i update to sodium 0.6.0 beta 4

### ISSUE THREAD

**Issue by IcedTeaLikeMilkTea** [jellysquid3/Sodium#2876]
### Bug Description

 i cant play the world (already had or new created one),the game will be always crashed when i load the world.I think it will be a rendering issue,that sodium has something happened with other rendering mod.(bonus it is "Description: Unexpected error")

### Reproduction Steps

Minecraft Window open,single player --> select world to play --> play world --> loading terrain --> waiting --> crashed

### Log File

[latest.log](https://github.com/user-attachments/files/17750075/latest.log)

### Crash Report

[crash-2024-11-14_21.17.57-client.txt](https://github.com/user-attachments/files/17749964/crash-2024-11-14_21.17.57-client.txt)

**Comment by douira** [comment]
Remove or update more culling.
