### ISSUE TITLE
Peformance only increaces when using F3 screen

### ISSUE THREAD

**Issue by MateusL13** [jellysquid3/Sodium#2877]
### Bug Description

the game runs around 30-40 fps, but it increases when the F3 screen is open, around 70-90 fps, it started happening on 0.6.0 updates.

### Reproduction Steps

Latest Sodium 0.6.0 Beta 5 + Fabric loader 0.16.9 + Minecraft Java 1.21.3 + world = only good FPS when F3 screen is open

### Log File

[latest.log](https://github.com/user-attachments/files/17759056/latest.log)

### Crash Report

no crash.

**Comment by jellysquid3** [comment]
Per discussions on Discord, there doesn't seem to be anything we can do about this. The user reported the bug exists in Minecraft 1.21.3 without Sodium, so it is an upstream bug.

**Comment by ghost** [comment]
> Per discussions on Discord, there doesn't seem to be anything we can do about this. The user reported the bug exists in Minecraft 1.21.3 without Sodium, so it is an upstream bug.

how is this possible? minecraft more fps while on f3 sounds like a joke

**Comment by MateusL13** [comment]
> > Per discussions on Discord, there doesn't seem to be anything we can do about this. The user reported the bug exists in Minecraft 1.21.3 without Sodium, so it is an upstream bug.
> 
> how is this possible? minecraft more fps while on f3 sounds like a joke

I swear it happens, idk what's the cause of it, but I have a video, it's more easy to notice it in person.
My device is ARM, but CPU and GPU acceleration are working, OpenGL 4.6 with freedreno drivers and Ubuntu 24.04.
As I have a peculiar setup, I don't think it's worth to make a bug report to Mojang, as it also happens on Vanilla game. 
I shouldn't have bothered sodium devs 😅


https://github.com/user-attachments/assets/2d7e46a5-7178-43e3-8892-d58cc6780c7a

As soon as the F3 screen shows, the FPS raises from 20 ~ 30 to 60

**Comment by Felix14-v2** [comment]
> how is this possible? minecraft more fps while on f3 sounds like a joke

Maybe that's some kind of driver performance optimization that only applies when F3 is opened. I've seen this situation on some forums several times before, but haven't had the opportunity to investigate it.

**Comment by ghost** [comment]
> > how is this possible? minecraft more fps while on f3 sounds like a joke
> 
> Maybe that's some kind of driver performance optimization that only applies when F3 is opened. I've seen this situation on some forums several times before, but haven't had the opportunity to investigate it.

why would you GPU driver know when F3 menu is active?

**Comment by Felix14-v2** [comment]
> why would you GPU driver know when F3 menu is active?

Maybe it can detect specific OpenGL calls caused by text rendering, I don't know
