### ISSUE TITLE
Keeps not Launching

### ISSUE THREAD

**Issue by joshuanathanjavier** [jellysquid3/Sodium#288]
![Screenshot (10)](https://user-images.githubusercontent.com/57710141/91552301-2bd81300-e95e-11ea-8277-490101b21170.png)

**It keeps not launching when I use the sodium mod . Im just using optifabric , fabric api, lithium, phosphor, modmenu, and sodium.**

**Comment by ZtereoHYPE** [comment]
Optifabric and optifine aren't compatible with Sodium.

**Comment by 0f-0b** [comment]
> If you're coming from Optifine, you can generally expect a significant improvement to performance over it, but you'll be missing some small features while the Fabric community builds other free and open-source alternatives. For a quick list of replacement features (such as zoom), take a look [here](https://gist.github.com/modmuss50/deff1658c4550ca8b16cb5d40ceaa468). **Sodium and Optifine are incompatible with one another. You must pick one.**[\*](https://www.curseforge.com/minecraft/mc-mods/sodium)

**Comment by amnotbananaama** [comment]
Duplicate of #13
