### ISSUE TITLE
Unable to enter the world after updating to 0.6.0-release

### ISSUE THREAD

**Issue by kands-code** [jellysquid3/Sodium#2880]
### Bug Description

After updating to 0.6.0-release, I am unable to enter the world. However, if I downgrade to 0.6.0-beta4, I can enter normally. I am not sure if this is a compatibility issue with a specific mod or if there is another underlying problem.

### Reproduction Steps

1. Update to 0.6.0-release
2. Create a world
3. Get stuck on the "Loading World" step
4. The game crashes

### Log File

[latest.log](https://github.com/user-attachments/files/17788718/latest.log)

### Crash Report

[crash-2024-11-17_11.02.23-client.txt](https://github.com/user-attachments/files/17788719/crash-2024-11-17_11.02.23-client.txt)

**Comment by jellysquid3** [comment]
This is a bug with Iris right now on Minecraft 1.21.1, a fix will be published on their side soon.
