### ISSUE TITLE
Chunk maps during world loading/creation are noticeably darker than Vanilla 1.21.2

### ISSUE THREAD

**Issue by EnnuiL** [jellysquid3/Sodium#2881]
### Bug Description

Since Minecraft 1.21.2, Sodium's optimized chunk map is noticeably darker than Vanilla's own; it ain't rocket science, you can see it here:

Sodium:
![The world loading screen on Minecraft 1.21.3 with Sodium 0.6.0. The chunk map is darker than usual.](https://github.com/user-attachments/assets/87afa596-ee5e-4f14-9418-99ac0a7c9975)

Minecraft:
![The world loading screen on Minecraft 1.21.3 with no other mods. The chunk map looks normal.](https://github.com/user-attachments/assets/45b1cdf8-2420-4d46-b9a9-7b77caaf0d05)

### Reproduction Steps

1) Install Sodium 0.6.0 (Fabric API is optional)
2) Create or load a world (setting the `spawnChunkRadius` game rule to 32 helps)
3) See that the colors are pretty off

### Log File

[latest.log](https://github.com/user-attachments/files/17788803/latest.log)

### Crash Report

[crash-2024-11-17_00.57.53-client.txt](https://github.com/user-attachments/files/17788805/crash-2024-11-17_00.57.53-client.txt)

**Comment by jellysquid3** [comment]
Fixed with https://github.com/CaffeineMC/sodium/commit/ab2044b0b96c1a66f424371d944e45a57b6b49cf, will be published in the next release of Sodium.
