### ISSUE TITLE
Foreground cutout of clouds lags behind on "Fabulous Graphics"

### ISSUE THREAD

**Issue by Niterux** [jellysquid3/Sodium#2883]
### Bug Description

The foreground cutout of the clouds seemingly updates too slowly so you can see through them slightly when you wiggle the camera around at low fps.

https://github.com/user-attachments/assets/bc7e8277-1ce3-438f-a7ec-382486eaa7c6

ADDITIONAL NOTE:
It only seems to cut into the clouds but not the other way around, maybe 2 different cutouts are being applied?

### Reproduction Steps

1. Lower the framerate cap to 20. This isn't required but makes the bug much easier to notice. Make sure also to enable "Fabulous" settings and that clouds are enabled. High render distance also helps.
2. Load into a world and stand where the sky is visible and block(s) are in front of it.
3. Wiggle your camera around and observe that the clouds become transparent around the edges of the block(s).

### Log File

https://mclo.gs/rGjMmV2

### Crash Report

[crash-2024-11-17_13.46.45-client.txt](https://github.com/user-attachments/files/17791939/crash-2024-11-17_13.46.45-client.txt)

**Comment by jellysquid3** [comment]
This has been fixed with https://github.com/CaffeineMC/sodium/commit/a51076c2bd79bec7754e9ba4d615f2a2bb65fdc9 and will be fixed in the next release.
