### ISSUE TITLE
First person hand fazing through blocks 

### ISSUE THREAD

**Issue by Big1N** [jellysquid3/Sodium#2888]
### Bug Description

My player hand in first person is fazing through blocks which is annoying and an eye sour. I know it’s sodium because when I removed the mod which slammed by performance by doing so but when I removed sodium from my mod list the issue went away completely. My client is mostly vanilla with iris and distant horizons and other performance mods 

### Reproduction Steps

I don’t know my hand just phases through stuff when I walk 

### Log File

No crash just graphical bug

### Crash Report

No report file just picture
![image](https://github.com/user-attachments/assets/f3c6b87c-45ab-4352-95ee-8d2c4f47ffbc)
![image](https://github.com/user-attachments/assets/93fbf726-0f07-4f5b-9dbf-ba0d4c514100)

**Comment by Poopooracoocoo** [comment]
There will be a file called "latest" in your logs folder. 

And you can invoke a crash report manually by holding F3 + C. 

And this is not a support forum. The correct place would be the Discord server: https://caffeinemc.net/discord

I suspect you've got Effective and Iris. If so, you're looking at https://github.com/Ladysnake/Effective/issues/274

**Comment by Big1N** [comment]
> There will be a file called "latest" in your logs folder.
> 
> And you can invoke a crash report manually by holding F3 + C.
> 
> I suspect you've got Effective and Iris. If so, you're looking at [Ladysnake/Effective#274](https://github.com/Ladysnake/Effective/issues/274)

Bro you’re a life saver thank you so much now I can fix this. I deeply apologize for blaming sodium but in reality it’s iris. Thank you for your support and thank you dev for making an awesome mod

**Comment by Felix14-v2** [comment]
You can also replace Effective with a less... broken mod like [Particle Tweaks](https://modrinth.com/mod/particle-tweaks)
