### ISSUE TITLE
Keeps Crashing 

### ISSUE THREAD

**Issue by Big1N** [jellysquid3/Sodium#2889]
### Bug Description

Can somebody please help me identify what the issue is with sodium on crashing. I’ve been bashing my head trying to see why sodium won’t load into my world. The Minecraft game starts up just fine but when I load into a world it crashes. 
it would be greatly appreciated if someone helped me. 

### Reproduction Steps

i just tried to load in a world or create a new world and it said joining the world and then saving the world and then it crashed. 

### Log File

[latest.log](https://github.com/user-attachments/files/17880229/latest.log)

### Crash Report

[crash-2024-11-23_10.19.28-client.txt](https://github.com/user-attachments/files/17880230/crash-2024-11-23_10.19.28-client.txt)

**Comment by rilakuma123** [comment]
This isn't a bug report, it's a support request. Those belong in the Discord server. But I'd like to point out that Shimmer is likely the culprit.

**Comment by Big1N** [comment]
> This isn't a bug report, it's a support request. Those belong in the Discord server. But I'd like to point out that Shimmer is likely the culprit.

Thank you so much for the support and I really appreciate your help greatly
