### ISSUE TITLE
Sodium caps FPS to 40

### ISSUE THREAD

**Issue by intercepted16** [jellysquid3/Sodium#2890]
### Bug Description

When using Sodium, my FPS is always capped at 40, ranging from 39-41. I used only Sodium to narrow it down. There were no other mods or modifications. This was on Fabric (latest) as well.

### Reproduction Steps

1. Install the latest version of Sodium on 1.21.3
2. Launch any Minecraft world
3. Press F3 to view FPS
4. there is now 40FPS in the top left

### Log File

[latest.log](https://github.com/user-attachments/files/17892064/latest.log)

### Crash Report

[crash-2024-11-24_16.16.49-client.txt](https://github.com/user-attachments/files/17892067/crash-2024-11-24_16.16.49-client.txt)

**Comment by jellysquid3** [comment]
Contact [NVIDIA support](https://www.nvidia.com/en-us/support/) and tell them their software is not compatible with Sodium. We cannot keep fixing the mountain of issues with their graphics driver.

**Comment by Felix14-v2** [comment]
Try completely uninstalling GeForce Experience or disable all of its battery optimizations, whisper mode and other garbage. I had similar issue some time ago (60 FPS lock with 144Hz screen), maybe that's your case.
