### ISSUE TITLE
Crash loading shaders

### ISSUE THREAD

**Issue by Unleashed75** [jellysquid3/Sodium#2894]
### Bug Description

With only Fabric, Iris and Sodium installed I loaded "Mellow" shader pack.
When it tried to load the shader, it crashes Minecraft and then will not let me load any worlds, single or multiplayer.

### Reproduction Steps

With just these installed;

Fabric loader 1.21 0.16.9
fabric-api-0.102.0+1.21.jar
iris-fabric-1.8.0+mc1.21.1.jar
sodium-fabric-0.6.0-beta.2+mc1.21.1.jar

Shaderpack where the issue was found;
Mellow Shader v1.5.2.zip

Join a game and load the Mellow shader. The game will crash and will continue to crash each time you try to join a world.

To stop the crash, the shader has to be disabled or changed within the video settings.
or both shaderpack and Iris need to be disabled or removed from the system folders. After this point the game needs to reload, then closed where Iris can be reinstalled.

I am added a report here too because the log file mentions Sodium in places but I know little about all of this.
I feel it's all an Iris issue do to it being a shader related issue.

I would like to point towards the video settings having a visual issue too, where buttons are not labelled or are faded too much to see.
![image](https://github.com/user-attachments/assets/63e3aa3b-65bf-434d-ad11-c02083e60892)

Iris report
https://github.com/IrisShaders/Iris/issues/2544

### Log File

[latest.log](https://github.com/user-attachments/files/17910778/latest.log)

### Crash Report

[crash-2024-11-26_01.08.37-client.txt](https://github.com/user-attachments/files/17910779/crash-2024-11-26_01.08.37-client.txt)

**Comment by douira** [comment]
The versions of iris and sodium you're using are incompatible.

**Comment by Unleashed75** [comment]
WTH are you on about. Both are labelled for 1.21 on the Modrinth App and I have been using both for ages, with no issues till now.
Very nice of you to close this issue though

**Comment by douira** [comment]
The log you uploaded indicates that you're using incompatible versions of sodium and iris.

**Comment by Unleashed75** [comment]
They are both the latest versions showing up for 1.21 on the Modrinth app.

**Comment by Unleashed75** [comment]
Ok, you closed this, so I'll try to solve it some other way. Thanks for your time

**Comment by douira** [comment]
The version of sodium you're using in your log file `sodium 0.6.0-beta.2+mc1.21.1` is not the [latest version](https://modrinth.com/mod/sodium/version/mc1.21.1-0.6.0-fabric) of the mod. Please come to [our discord server](https://jellysquid.me/discord) to receive help with this support request. The issue tracker is not intended for support requests.

**Comment by Felix14-v2** [comment]
> They are both the latest versions showing up for 1.21 on the Modrinth app.

Some older versions of a mod can be incompatible with a new version of another mod, that's just how the world of dependencies  work. That's exactly your case.

**Comment by Unleashed75** [comment]
If I am not using the latest version of Sodium for 1.21, then it's a Sodium and Modrinth issue. I can only load what they show me.

**Comment by Felix14-v2** [comment]
Modrinth definitely shows the latest version correctly:
![image](https://github.com/user-attachments/assets/fd97236a-8c98-4660-9ee3-2b7415178170)
![image](https://github.com/user-attachments/assets/2e813b87-de7a-4094-8acb-1dd8c7f8986a)

**Comment by Poopooracoocoo** [comment]
@Felix14-v2 how do you know that wasn't just changed?

> I can only load what they show me.

@Unleashed75 That's not right. You can still download mods manually and put then in your mods folder. But it's certainly inconvenient.

**Comment by douira** [comment]
Please do not continue this support case on the issue tracker.

**Comment by jellysquid3** [comment]
Someone notified me that the metadata for Sodium 0.6.0 was incorrect and didn't include Minecraft 1.21.0, despite the manifest file in the JAR saying that it was compatible.

I've since fixed the issue, but wasn't aware this conversation was related to it.

**Comment by Unleashed75** [comment]
![image](https://github.com/user-attachments/assets/2b672cfc-807a-453d-bf04-1118b609a8c5)


It does not show up on the app, which is what I said.
There is also a bug report with Modrinth where some mods will not show up in the mods folder when manually added or have been disabled etc.

So again, if it is not on the list above. Then as far as a user is considered that is using the app, it does not exist and is a Sodium and Modrinth issue, not the client.

As far as I knew at the time of making this issue, it was more than likely a Iris bug and it was crashing my game. If it's just a version issue, then update Modrith to show the correct version.

I'm not hating on anyone fyi. I just found a issue and I talk like a jerk. I don't mean to. Thank you all for your time
