### ISSUE TITLE
No boost in FPS

### ISSUE THREAD

**Issue by Eterxnerl** [jellysquid3/Sodium#2895]
Literally, sodium is now not of any use vanilla is better i don't wanna say anything : 
My specs
Intel core i3 10th gen
Intel UHD Graphics
4gb ram
256gb SSD
Now just see these images. All of the settings are set to unlimited fps with vsync toggled off: 
Performance with sodium in fabric:
![2024-11-27_16 45 46](https://github.com/user-attachments/assets/c493005a-f82a-4883-8cbc-64bc7342c3f0)
Performance with sodium in quilt:
![2024-11-27_16 39 31](https://github.com/user-attachments/assets/754a0cd5-0344-40d8-8ec5-296985a95ae4)
Performance in vulkan mod in fabric:
![2024-11-27_17 09 57](https://github.com/user-attachments/assets/5ffe4abb-cc3a-4c78-bab3-56f89ac8c043)
Performance in Vanilla:
![2024-11-27_16 56 21](https://github.com/user-attachments/assets/32119c47-6716-4263-bff0-7777d8bf8fc7)
Performance with Optifine:
![2024-11-27_17 18 42](https://github.com/user-attachments/assets/0ea91766-b760-4050-8c23-8f9b398c1026)

**Comment by Felix14-v2** [comment]
You benchmark nothing. Sodium optimizes terrain rendering and some other processes, but there is no single chunk of terrain in your test scene. So, in fact, you measure the GUI rendering performance, which isn't modified by Sodium.

**Comment by Eterxnerl** [comment]
what???????

**Comment by pajicadvance** [comment]
Comment above was pretty clear, you're comparing performance in a scene where nothing is rendered. Compare FPS in a scene with actual terrain. In any case this is not a support forum, if you're having performance issues go to the [Discord server](https://jellysquid.me/discord) for help.

**Comment by Eterxnerl** [comment]
thanks
looking forward for better updates , btw thanks for support
