### ISSUE TITLE
Cloud renderer is broken on `dev` branch

### ISSUE THREAD

**Issue by Alexander317** [jellysquid3/Sodium#2896]
### Bug Description

The clouds are being rendered through solid blocks when picking up items from ground.

~~The issue probably only exisits on Nvidia cards (see https://discord.com/channels/602796788608401408/1285427417774559292/1311405893627281481 for more info on that)~~

### Reproduction Steps

1) Throw some items on ground
2) Pick them up
3) Observe the clouds rendering through solid blocks

https://github.com/user-attachments/assets/0e3e887e-05b5-44be-a260-914be1f55de6

### Log File

[latest.log](https://github.com/user-attachments/files/17939330/latest.log)

### Crash Report

[crash-2024-11-27_21.36.25-client.txt](https://github.com/user-attachments/files/17939352/crash-2024-11-27_21.36.25-client.txt)

**Comment by douira** [comment]
I didn't know about the dropping items part. I can reproduce it on my system (macOS, 6900 XT) too now.

**Comment by Alexander317** [comment]
> I didn't know about the dropping items part. I can reproduce it on my system (macOS, 6900 XT) too now.

ok, I fixed the bug description

**Comment by jellysquid3** [comment]
Fixed with https://github.com/CaffeineMC/sodium/commit/a69adec9d553c44a958f4dc74120e5102b60ed4c.
