### ISSUE TITLE
cuando rompo los bloques se ve fea la pantalla

### ISSUE THREAD

**Issue by Tsuba26** [jellysquid3/Sodium#2898]
### Bug Description

cuando yo rompo bloques en minecraft la pantalla aparece una parte en blan y eso no me gusta 

### Reproduction Steps

cuando yo rompo se ve feo la pantalla 

### Log File

![image](https://github.com/user-attachments/assets/39a9adc9-4922-4286-92d4-aaeb4b0a2887)

### Crash Report

y necesito por favor ayuda

**Comment by pajicadvance** [comment]
Please provide a log file

**Comment by Tsuba26** [comment]
como asi?

**Comment by pajicadvance** [comment]
https://docs.fabricmc.net/players/troubleshooting/uploading-logs
