### ISSUE TITLE
Non-animated parts of nnimated blocks flicker

### ISSUE THREAD

**Issue by douira** [jellysquid3/Sodium#2899]
The non-animated parts of the block flicker in brightness over time. Example: nether stems or command blocks.

Reproduced on [latest `dev`](https://github.com/CaffeineMC/sodium/commit/a69adec9d553c44a958f4dc74120e5102b60ed4c).

https://github.com/user-attachments/assets/a2292ba0-a534-4094-803e-cc84954dea13

**Comment by douira** [comment]
Bisected to be regressed by https://github.com/CaffeineMC/sodium-fabric/commit/c5ed67742c760f64b4879f607c926adcb093316b

**Comment by jellysquid3** [comment]
Fixed with https://github.com/CaffeineMC/sodium/commit/42ad9330d8e338f10eec7400c0722b03cc169842.
