### ISSUE TITLE
is that support 1.16.2?

### ISSUE THREAD

**Issue by Mcpe64** [jellysquid3/Sodium#290]
i should be enter the game without crash.
but the game crashed

1. use fabric loader 092,build 206 1.16.2 and use sodium and fabric api 0.19.0+build.398-1.16
2. launch game
3. game crashed

- Java Version: [build 180]
- CPU: [intel core 15 4210m]
- GPU: [hd graphics 4600]

**Comment by amnotbananaama** [comment]
Sodium 1.16.1 doesn’t support 1.16.2. You’ll need to wait for an update, which is in progress. You can follow development in the `#mod-updates-✨` channel of Jelly’s discord.
