### ISSUE TITLE
Iris 1.8.0 is not compatible with Sodium 0.6.1

### ISSUE THREAD

**Issue by tutur2000** [jellysquid3/Sodium#2901]
### Bug Description

When a Update Sodium in my ModPack it's crash "org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError" (full log here https://mclo.gs/ltm8BXt) My modpack : Radium (in modrinth, just unlock the modpack and updated sodium)

### Reproduction Steps

Install my Modpack in Modrinth (it's public) unlock it, update sodium and it's crash

### Log File

https://mclo.gs/ltm8BXt

### Crash Report

[crash-2024-12-02_21.55.21-client.txt](https://github.com/user-attachments/files/17983940/crash-2024-12-02_21.55.21-client.txt)

**Comment by jellysquid3** [comment]
Wait for Iris to update, their mod is patching into code that changed with Sodium 0.6.1.

**Comment by tutur2000** [comment]
thanks !
