### ISSUE TITLE
Game Start Crash 1.21.1 Neoforge

### ISSUE THREAD

**Issue by f0kx** [jellysquid3/Sodium#2902]
### Bug Description

Connecting to Server will crahs the Game

### Reproduction Steps

Boot up
Click on server 
Crash

### Log File

[latest.log](https://github.com/user-attachments/files/17984260/latest.log)

### Crash Report

[crash-2024-12-02_22.28.16-client.txt](https://github.com/user-attachments/files/17984253/crash-2024-12-02_22.28.16-client.txt)

**Comment by IMS212** [comment]
Iris 1.8 is not yet compatible with Sodium 0.6.1.
