### ISSUE TITLE
Frogspawn still renders incorrectly

### ISSUE THREAD

**Issue by Helpbot3000** [jellysquid3/Sodium#2903]
### Bug Description

Frogspawn is still not translucent. Instead, it is opaque.

### Reproduction Steps

Place frogspawn and observe

### Log File

N/A

### Crash Report

N/A

**Comment by jellysquid3** [comment]
Please do not ignore the issue template or your issue will be set to the lowest priority.

**Comment by jellysquid3** [comment]
Mojang disabled the translucency effect for Frogspawn according to [MC-249106](https://bugs.mojang.com/browse/MC-249106), so it rendering as opaque should be correct.

**Comment by jellysquid3** [comment]
After talking with other people, it seems like Frogspawn being opaque is intentional in Vanilla, and that Sodium isn't changing any behavior.
