### ISSUE TITLE
Incompatibility with Wurst V7.46.3

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#2904]
nOt SupPorTeD

**Comment by TheUserCreated** [comment]
Hack/Cheat clients are not supported.

**Comment by Alexander01998** [comment]
Hello, Wurst Client dev here.

I understand you probably aren't interested in fixing this bug or that doing so would violate some policy of yours. That's OK. Just letting you know that I've received the same report and am investigating it in https://github.com/Wurst-Imperium/Wurst7/issues/1088. Any additional users inquiring about this bug should be directed there so I can provide support to them. You can also see what I've discovered so far in that issue, if you are interested.

Cheers!
