### ISSUE TITLE
Name tags do not have a background

### ISSUE THREAD

**Issue by mrjasonn** [jellysquid3/Sodium#2909]
### Bug Description

Name tags do not have a background.
Picture of issue:
![2024-12-04_14 54 40](https://github.com/user-attachments/assets/c2ecf8ba-d1d6-46f2-b29b-50b065acb9c1)
Vanilla:
![2024-12-04_14 52 44](https://github.com/user-attachments/assets/be04cd11-7716-4b9c-bf94-c8903f760d96)

### Reproduction Steps

1. Spawn a mob
2. Name the mob whatever you want
3. You will see the issue

### Log File

Sodium: [https://mclo.gs/YKqwW5U](https://mclo.gs/YKqwW5U)
Vanilla: [https://mclo.gs/XAAs9vk](https://mclo.gs/XAAs9vk)

### Crash Report

[https://mclo.gs/Sx2TVVd](https://mclo.gs/Sx2TVVd)

**Comment by jellysquid3** [comment]
Fixed with https://github.com/CaffeineMC/sodium/commit/6adc89c81affb8198272410a4f692696082a5746.

**Comment by jellysquid3** [comment]
Sodium 0.6.3 was published and this problem is fixed with it.
