### ISSUE TITLE
Crash on startup, maybe mod incompatibility

### ISSUE THREAD

**Issue by chexo3** [jellysquid3/Sodium#291]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

Not applicable, crashes on startup.

### Crash Report File
[latest.log](https://gist.github.com/chexo3/d04006a05471246bef32beccc4fdb33d)

### Additional Information
Provide any additional information or context which may be relevant to the issue. If you have none to add, you can remove this section.

I think it's probably an incompatibility with another mod I have installed, but the log unfortunately did not make sense to me. I'm hoping someone with more experience can figure out what went wrong.

I can also provide a copy of the instance if requested. Or attempt to launch the game with debugging tools enabled, you'll just have to tell me what to do as I am not familiar with Java debugging tools.

**Comment by silversquirl** [comment]
Sodium does not yet support 1.16.2
