### ISSUE TITLE
The sun renders incorrectly during sunrise and sunset

### ISSUE THREAD

**Issue by PrivateYT-AG** [jellysquid3/Sodium#2910]
### Bug Description

During sunrise and sunset, the sun renders incorrectly, as the "fog" appears to be rendered above the sun. Version is 0.6.2-mc1.21.4.
![2024-12-04_16 29 26](https://github.com/user-attachments/assets/06b72267-59b6-485d-b9ba-301683906db3)
When I tested in the vanilla version, the sun renders normally.

### Reproduction Steps

Steps to reproduce:
- Set time between 12500 and 13000 or 23000 and 23500
- The sun renders incorrectly and is obstructed by "fog".

### Log File

[latest.log](https://github.com/user-attachments/files/18005804/latest.log)

### Crash Report

[crash-2024-12-04_16.40.19-client.txt](https://github.com/user-attachments/files/18005808/crash-2024-12-04_16.40.19-client.txt)

**Comment by jellysquid3** [comment]
![image](https://github.com/user-attachments/assets/ddb824d9-5437-41ee-8f7a-18c0b1a6115c)

The sun/moon seems to render correctly for me. Can you verify this problem happens with _only_ Sodium installed? There is a possibility that mods such as _ImmediatelyFast_ are causing the problem.

**Comment by PrivateYT-AG** [comment]
As I ran only using sodium, it seems to be an issue with Iris Shaders (v1.8.3+mc1.21.4).

**Comment by Felix14-v2** [comment]
Such a nice bug, IMO. I always find it weird that the sun renders under the ground level.
