### ISSUE TITLE
Space with strikethrough is not rendered correctly on 1.21.3+

### ISSUE THREAD

**Issue by xMelonekMaX** [jellysquid3/Sodium#2912]
### Bug Description

Fabric Loader + Sodium

Sodium:
![sodium](https://github.com/user-attachments/assets/ec44aa3f-77c6-410e-b152-a08f2d89aab7)

Vanilla:
![vanilla](https://github.com/user-attachments/assets/ac972657-78b7-48cd-bbd5-456a0edc423d)

### Reproduction Steps

Enter this command:
/title @s title {"text":"   >","italic":true,"strikethrough":true}

### Log File

[latest.log](https://github.com/user-attachments/files/18014121/latest.log)

### Crash Report

[crash-2024-12-04_21.56.38-client.txt](https://github.com/user-attachments/files/18014130/crash-2024-12-04_21.56.38-client.txt)

**Comment by jellysquid3** [comment]
This is caused by the same issue as https://github.com/CaffeineMC/sodium/issues/2909, which was fixed and will be published as part of Sodium 0.6.3 later today.

**Comment by jellysquid3** [comment]
Sodium 0.6.3 was published and this problem is fixed with it.
