### ISSUE TITLE
Translucency sorting uses wrong camera position

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#2918]
### Bug Description

Translucency sorting seems broken

![image](https://github.com/user-attachments/assets/b3fdabca-14c1-4280-9557-ee63266f6ae5)

![2024-12-07_13 23 23](https://github.com/user-attachments/assets/d748e078-5554-48d4-88ab-26641d619a0b)

### Reproduction Steps

with RestWorld: https://claritypack.com/restworld/RestWorld_1.21.4.zip

`/execute in minecraft:overworld run tp @s -0.80 103.29 34.34 -361.50 10.05`

### Log File

*

### Crash Report

*

**Comment by NinjaLegendmc** [comment]
This happen me too, and after testing it i found that the bug introduce at sodium 0.6.1 and still remain on 0.6.3

**Comment by Felix14-v2** [comment]
ShadowMC reported this regression between 0.6.0 and 0.6.2 some time ago:
|0.6.0|0.6.2|
|---|---|
|![image](https://github.com/user-attachments/assets/675a683e-3189-46de-be49-4d7c02a7223e)|![image](https://github.com/user-attachments/assets/86cf1225-2a42-4063-ab29-5e0e99fcef83)|

**Comment by audaki** [comment]
@jellysquid3 Is this the same bug? Found this in Sodium 0.6.x up to 0.6.3, otherwise I will open a new bug

Look at the setup:
![image](https://github.com/user-attachments/assets/6dfc1df6-dadf-40c6-ad5b-130744df9cef)

Look from the side:
![image](https://github.com/user-attachments/assets/70ad8f19-3bc2-4493-91d9-57cee194f37f)

Looks even worse with water:
![image](https://github.com/user-attachments/assets/6410c583-e5f0-4ee4-b3af-b625cd3a01cb)

**Comment by Lolothepro** [comment]
> @jellysquid3 Is this the same bug? Found this in Sodium 0.6.x up to 0.6.3, otherwise I will open a new bug
> 
> Look at the setup: ![image](https://private-user-images.githubusercontent.com/1321285/393548808-6dfc1df6-dadf-40c6-ad5b-130744df9cef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MDg1NDEsIm5iZiI6MTczMzYwODI0MSwicGF0aCI6Ii8xMzIxMjg1LzM5MzU0ODgwOC02ZGZjMWRmNi1kYWRmLTQwYzYtYWQ1Yi0xMzA3NDRkZjljZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDdUMjE1MDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjA4ZjhlMTdhNzhiZTc1ZGI4NDk5MDczZjc5NWVmMWFmNWJkODRhODZjODVmYzk5MjFiYTE2ZDM5NmQ2ZGUxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.27ybSbobb8xeITjPxFeAt-I1CISRmXMjj_6-x8LEcmM)
> 
> Look from the side: ![image](https://private-user-images.githubusercontent.com/1321285/393548822-70ad8f19-3bc2-4493-91d9-57cee194f37f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MDg1NDEsIm5iZiI6MTczMzYwODI0MSwicGF0aCI6Ii8xMzIxMjg1LzM5MzU0ODgyMi03MGFkOGYxOS0zYmMyLTQ0OTMtOTFkOS01N2NlZTE5NGYzN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDdUMjE1MDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTcwOTBmNmVkZDgzMjc0Y2ViMWJmNmJiMTIyOGIzNWYxOTAxZmNlNzE0OGEyZTBmNzQ4ZWI5MjcyNzY2YWFlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OsVZYEhdE9yAkWeadCFw-Z_GrO6RiXYnk7Yr4_VEjkc)
> 
> Looks even worse with water: ![image](https://private-user-images.githubusercontent.com/1321285/393548839-6410c583-e5f0-4ee4-b3af-b625cd3a01cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2MDg1NDEsIm5iZiI6MTczMzYwODI0MSwicGF0aCI6Ii8xMzIxMjg1LzM5MzU0ODgzOS02NDEwYzU4My1lNWYwLTRlZTQtYjNhZi1iNjI1Y2QzYTAxY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDdUMjE1MDQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGJkMTY3OGExYzMyMjc3ZDE5MjIwNGY2N2UwY2MzMjQ2Y2MxOTY4NjQ0M2Q2YmY0OWE3MzIzZWVlMDMxNWIyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Jb86vZ-1hj9JNZJCPKVM21L_Xc4YVhBpwyGTyDfzpgQ)

Probably the same bug

**Comment by jellysquid3** [comment]
@audaki You can check by downloading a [nightly version](https://nightly.link/CaffeineMC/sodium/workflows/build-commit/dev/sodium-artifacts-dev.zip) of Sodium (which includes the aforementioned patch). 

EDIT: Fixed the link.

**Comment by audaki** [comment]
@jellysquid3 Thank you, I just checked the nightly and can confirm that this situation is also fixed! 😊
