### ISSUE TITLE
Sodium lacks VT fast leaves textures for pale oaks

### ISSUE THREAD

**Issue by djmrFunnyMan** [jellysquid3/Sodium#2926]
### Bug Description

So Pale Oaks were added but sodium didn't update their fast leaves textures from Vanilla Tweaks, which results in Pale Oaks looking atrocious with fast leaves turned on.

Sodium + Updated VT Textures
![2024-12-08_16 58 19](https://github.com/user-attachments/assets/868aaef2-c637-4c0c-bad6-14d82e93c13c)

Just Sodium 0.6.3
![2024-12-08_16 58 32](https://github.com/user-attachments/assets/d7cc8b61-dd9b-4073-97b9-42f3c6194d2d)

### Reproduction Steps

Enable fast leaves in the pale garden

### Log File

Not relevant

### Crash Report

Not relevant

**Comment by jellysquid3** [comment]
Resolved with [7dc491d](https://github.com/CaffeineMC/sodium/commit/7dc491dfa2449632f706ed6995276e6c7bb96972).
