### ISSUE TITLE
Incompatible mods

### ISSUE THREAD

**Issue by Unleashed75** [jellysquid3/Sodium#2930]
### Bug Description

An issue like this has happened before.
Versions;
sodium-fabric-0.6.3+mc1.21.1
sodium-fabric-0.6.2+mc1.21.1
are not compatible with;
iris-fabric-1.8.0+mc1.21.1

Both versions of Sodium are listed to work on MC 1.21 and are the two latest versions showing up for 1.21 (at least on Modrinth App and website)
iris-fabric-1.8.0+mc1.21.1 - this is the latest version showing up for MC 1.21 too

Users need to roll back to;
sodium-fabric-0.6.1+mc1.21.1 if they want to use Iris and Sodium together on MC 1.21

It seems to be an issue where the mod is being updated for newer versions and showing as compatible for older versions by mistake.
These newer sodium mods are asking for iris 1.8.1+

Last time this sort of issue happened, it was something missed in the metadata - I've no idea what this means, just repeating what was said.

### Reproduction Steps

install the mods and test

### Log File

[latest.log](https://github.com/user-attachments/files/18063143/latest.log)

### Crash Report

If the game won't load, then there is no crash files to share...

**Comment by Poopooracoocoo** [comment]
Iris needs to change the metadata of Iris 1.8.1 to include 1.21. https://modrinth.com/mod/iris/version/1.8.1+1.21.1-fabric

You can report it to them here: https://github.com/IrisShaders/Iris/issues

**Comment by Unleashed75** [comment]
Iris 1.8.0 already works for 1.21...
You are saying that they need to make their 1.8.1 compatible for 1.21 when it's sodium that's causing an issue. Their 1.8.1 is stated to work for 1.21.1+ not 1.21+

**Comment by pajicadvance** [comment]
`sodium-fabric-0.6.3+mc1.21.1` contains the following in `fabric.mod.json`:

```
"depends": {
    "minecraft": [
      "1.21",
      "1.21.1"
    ],
...
```

It's Iris that's locking their version to 1.21.1.

**Comment by Poopooracoocoo** [comment]
This is about the metadata on Modrinth and CurseForge, not version constraints in the FMJs. 

Iris 1.8.1's MC dependency is 1.21.x in its FMJ. As 1.21 mods work on 1.21.1 and vice versa, Iris 1.8.1 just needs to be marked as being for 1.21 and 1.21.1 on Modrinth and CurseForge, instead of only 1.21.1. 

The issue is not with Sodium. 

And besides, 1.21.1 is recommended over 1.21 as discussed in your other issue.
