### ISSUE TITLE
更新新版的钠（MC1.21，钠1.21.1 or 1.21的版本）后就和一堆模组不兼容

### ISSUE THREAD

**Issue by Mengmiya1027** [jellysquid3/Sodium#2934]
### Bug Description

更新新版的钠（MC1.21，钠1.21.1 or 1.21的版本）后就和一堆模组不兼容

### Reproduction Steps

安装最新版的钠、iris、钠.扩展，启动游戏

### Log File

![屏幕截图 2024-12-15 131546](https://github.com/user-attachments/assets/ad1f9689-e6d4-4327-b906-58804f115111)

### Crash Report

![Uploading 屏幕截图 2024-12-15 131546.png…]()

**Comment by lazysixoeight** [comment]
sodium isn't compatible with iris below version 1.8.1, as well as sodium extra below 0.6.0 (assuming the translation were correct) 

钠与版本 1.8.1 以下的 iris 以及版本 0.6.0 以下的钠额外不兼容（假设翻译正确）
