### ISSUE TITLE
No Render Distance setting

### ISSUE THREAD

**Issue by shinenyugen** [jellysquid3/Sodium#2938]
### Bug Description

I dont have render distance and max shadow distance setting options. This are the mods I use![Image](https://github.com/user-attachments/assets/fe26cbbe-cf5e-40cf-865d-f867d68a18fe)
![Image](https://github.com/user-attachments/assets/69808f5d-0315-4b8f-bdf7-3e9a86a16ff9)

### Reproduction Steps

I dont know if its a bug or what but I do not even have the render distance option. I used to have it and I am using sodium extra and reeses. Counting the chunks it seems that its set at 16 chunks but I cant change it.![Image](https://github.com/user-attachments/assets/d4d86e73-4d8d-4db9-9690-160d15a8bce2)

### Log File

[latest.log](https://github.com/user-attachments/files/18153152/latest.log)

### Crash Report

[crash-2024-12-16_17.00.23-client.txt](https://github.com/user-attachments/files/18153181/crash-2024-12-16_17.00.23-client.txt)

**Comment by shinenyugen** [comment]
And this is singleplayer btw

**Comment by Poopooracoocoo** [comment]
You should test whether the issue occurs with the latest version of Sodium and of related mods. 

https://modrinth.com/mod/sodium/version/mc1.21.1-0.6.3-fabric
https://modrinth.com/mod/iris/version/1.8.1+1.21.1-fabric
https://modrinth.com/mod/sodium-extra/version/mc1.21.1-0.6.0+fabric
https://modrinth.com/mod/reeses-sodium-options/version/mc1.21.3-1.8.0+fabric

**Comment by shinenyugen** [comment]
Thank you! The sodium beta version was the issue. I updated it. Sorry for bothering!
