### ISSUE TITLE
Game crashes whenever the breaking overlay shows

### ISSUE THREAD

**Issue by TheFox580** [jellysquid3/Sodium#2944]
### Bug Description

Whenever the player tries to break a block that doesn't insta-break, the game will crash.

### Reproduction Steps

- Join a world in survival
- Try to break a block until it shows the breaking overlay (i.e. : dirt)
- The game will instantly crash

### Log File

[latest.log](https://github.com/user-attachments/files/18172270/latest.log)

### Crash Report

[crash-2024-12-17_23.55.51-client.txt](https://github.com/user-attachments/files/18172271/crash-2024-12-17_23.55.51-client.txt)

**Comment by Moulberry** [comment]
This is an issue with Sodium 0.6.4. It has been addressed in Sodium 0.6.5. Please update.

**Comment by TheFox580** [comment]
Oh yeah, it's not on the Modrinth launcher yet but it just got updated on the website, thanks!
