### ISSUE TITLE
Error displaying the water-filled bottom slab

### ISSUE THREAD

**Issue by Timokaproka** [jellysquid3/Sodium#2946]
### Bug Description

Error displaying the water-filled bottom slab
Minecraft Version: **1.21.1**
Fabric Verison: **0.16.9** 
Sodium Version: **0.6.5** 

![Image](https://github.com/user-attachments/assets/882ef3df-01c2-458f-b3a8-4a8294bc0867)
![Image](https://github.com/user-attachments/assets/c0c66144-0a56-421d-8bf6-1ec3491e0839)
![Image](https://github.com/user-attachments/assets/e78e49b6-5ded-4cc8-a153-fc100a996924)

### Reproduction Steps

1) Place the slab in the lower position
2) Fill the slab with water
3) Move away by 16-30 blocks

### Log File

[latest.log](https://github.com/user-attachments/files/18215002/latest.log)

### Crash Report

[crash-2024-12-21_01.19.51-client.txt](https://github.com/user-attachments/files/18214999/crash-2024-12-21_01.19.51-client.txt)

**Comment by Lolothepro** [comment]
Isn't this a Vanilla bug?

**Comment by MeeniMc** [comment]
#2758
