### ISSUE TITLE
Go back to the (L)GPL

### ISSUE THREAD

**Issue by souldbminerr** [jellysquid3/Sodium#2949]
### Request Description

Since sodium relicensed, nothing has happened exept further triaging in the optimization mod ecosystem. Nothing has really changed since sodium relicensed, and there has been no fabric fork getting nearly as much traction as sodium. It makes no sense to stay on Polyform, when there is no benefit to relicense to another license

**Comment by jellysquid3** [comment]
![Image](https://github.com/user-attachments/assets/1c8dc081-46a1-4a7f-8b98-9281c807f60f)

Blocked for spamming ours and many other repositories.
