### ISSUE TITLE
Inside part of full block models become dark when ambient occlusion is off

### ISSUE THREAD

**Issue by GeForceLegend** [jellysquid3/Sodium#295]
( ambientocclusion is an option of Minecraft models )

### Expected Behavior
Inside part of full block models should be bright as vanilla when ambient occlusion is off.

### Actual Behavior
Inside part of full block models become very dark when ambient occlusion is off.

### Reproduction Steps
This requires a resource pack with block models. I'll provide an example pack.
Load this resource pack with Sodium, and jukebox will become absolutely dark.
[Example.zip](https://github.com/jellysquid3/sodium-fabric/files/5177458/Example.zip)

### Attachments
This is the look with Sodium on
![2020-09-05_10 26 43](https://user-images.githubusercontent.com/41003546/92295974-62b3b780-ef62-11ea-8a8f-a28d7b7f64bd.png)

This is the look with vanilla Minecraft
![2020-09-05_10 29 04](https://user-images.githubusercontent.com/41003546/92296018-a9a1ad00-ef62-11ea-9f1f-38b28444a3ec.png)

**Comment by MeeniMc** [comment]
issue is resolved (as of 0.4.10, probably earlier)

**Comment by GeForceLegend** [comment]
Thank you to inform me that
