### ISSUE TITLE
Mine In Abyss resource pack strange line rendering issue on dev

### ISSUE THREAD

**Issue by khang06** [jellysquid3/Sodium#296]
### Expected Behavior
here's what shows on the release from curseforge (0.1.0)
![image](https://user-images.githubusercontent.com/11239786/92302105-65e57e00-ef37-11ea-82b3-bafbd889c95b.png)

### Actual Behavior
here's what shows on dev branch (f577eb2be13b93d8e584aaa7cc329680e0deaaf3)
![image](https://user-images.githubusercontent.com/11239786/92302108-6d0c8c00-ef37-11ea-8851-b34db62352a8.png)

### Reproduction Steps
1. grab a copy of the resource pack https://github.com/MineInAbyss/MineInAbyss-resourcepack/releases/tag/v1.0.15
2. look at grass, torches, the seams of some blocks, etc

notably, i can't figure out which exact json file is causing the issue. for example, deleting `/assets/minecraft/models/item/diamond_sword.json` fixes the issue, but having that be the only item doesn't make the issue appear. this makes me believe that the issue only pops up after a certain amount of models are loaded, but that's only a wild guess

edit: now that i think about it, this might be related to compact vertex format? losing precision as more stuff gets loaded makes sense
edit 2: making the uvs float instead of short fixes it. maybe have a partially packed compatibility mode for resource packs with lots of textures?

### System Information
- Java Version: 1.8.0_241
- CPU: i7 7700k/Ryzen 5 3600
- GPU: GTX 1070/GTX 1060

**Comment by MeeniMc** [comment]
Possibly related to issue #309

**Comment by LucilleTea** [comment]
This looks like the same issue as #309, which was phrased more broadly and got more activity. So I'd like to close this issue in favour of that one, thanks for the report!
Some recent (unpushed) work is at least significantly improving this situation, not sure if it's entirely resolved yet.
