### ISSUE TITLE
I launch Minecraft and the crash is instant (even before the start of the game itself)

### ISSUE THREAD

**Issue by ZomZommer** [jellysquid3/Sodium#298]
1. Install Fabric
2. I transfer the mod Sodium to the mods folder
3. I launch Minecraft and the crash is instant (even before the start of the game itself)

### Crash Report File
Please upload your crash report as a file to [GitHub Gist](https://gist.github.com/) and replace this text with a link to the uploaded report.
[latest.log](https://github.com/jellysquid3/sodium-fabric/files/5193740/latest.log)

**Comment by LucilleTea** [comment]
Sodium is not compatible with 1.16.2, it's only for 1.16.1.

If you need any tech support I recommend joining the discord server.

**Comment by ZomZommer** [comment]
> Sodium is not compatible with 1.16.2, it's only for 1.16.1.
> 
> If you need any tech support I recommend joining the discord server.

Thanks friend!
