### ISSUE TITLE
Crashed with immersive portals 1.16.1

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#299]
#Mods that i had installed
Install immersive-portals-0.27-mc1.16.1-fabric
Install modmenu-1.14.5+build.30
also install sodium-fabric-mc1.16.1-0.1.0.6-ipcompat
and install fabric-api-0.18.0+build.387-1.16.1

### Crash steps
To get the crash, launch fabric, and try yo go on video settings. The game will freeze and then crash.
 

### Crash Report File
https://pastebin.pl/view/7e590e63

**Comment by mrmangohands** [comment]
sodium and immersive portals are incompatible for the time being, see #15

**Comment by Titaniumtown** [comment]
There is a PR that seems to address this issue: #174

**Comment by ghost** [comment]
i am using a sodium version that is compatible to immersive portals it says on thier curse forg page

**Comment by Titaniumtown** [comment]
@lightningdr2009 report it to that PR then. This is an issue with that PR, not with sodium.

**Comment by ghost** [comment]
What is PR?

**Comment by jellysquid3** [comment]
You're using a modified version of Sodium that we obviously cannot provide much support for. That said, it looks like your configuration file is just incompatible or somehow corrupted. It might help to delete your existing configuration file, but if that doesn't work, you'll need to go to the author who provides the modified version of Sodium and contact them for help.
