### ISSUE TITLE
Primed TNT experiences z-fighting while using the oneshot (GL 3.3) and multidraw (GL 4.3) chunk renderers

### ISSUE THREAD

**Issue by bytzo** [jellysquid3/Sodium#300]
### Expected Behavior
When viewing primed TNT, the white flashing overlay should blend with the TNT texture (see fig. 1). This works correctly in vanilla Minecraft, [`1.16.x/stable`](https://github.com/jellysquid3/sodium-fabric/tree/1.16.x/stable) (specifically 885222a476b7054ae428031d72c0b47fa579872a), and the oneshot (GL 2.0) renderer on [`1.16.x/dev`](https://github.com/jellysquid3/sodium-fabric/tree/1.16.x/dev) (specifically f577eb2be13b93d8e584aaa7cc329680e0deaaf3).

### Actual Behavior
When viewing primed TNT, the white flashing overlay experiences z-fighting with the TNT texture (see fig. 2). This occurs using either the oneshot (GL 3.3) or multidraw (GL 4.3) renderer on [`1.16.x/dev`](https://github.com/jellysquid3/sodium-fabric/tree/1.16.x/dev) (f577eb2be13b93d8e584aaa7cc329680e0deaaf3).

### Reproduction Steps
1. Open a Minecraft world using [`1.16.x/dev`](https://github.com/jellysquid3/sodium-fabric/tree/1.16.x/dev) (f577eb2be13b93d8e584aaa7cc329680e0deaaf3).
2. Enter `/summon minecraft:tnt ~ ~ ~ {Fuse: 32767}` in the chat.
3. The white flashing overlay of the primed TNT experiences z-fighting with the TNT texture.

### Additional Notes
- Built and run using OpenJDK 14.0.2.
- Tested on Fabric Loader 0.8.8+build.202.
- Started occurring on commit 620f5a3669be298244bda70cb20cf2e1df8f53b9, which made changes to the oneshot (3.3) and multidraw (4.3) renderers.
- Does not apply to creepers.

### Attachments
![primed_tnt](https://user-images.githubusercontent.com/69266322/92816984-f4646000-f37a-11ea-8c57-a403ea740d93.png)
**Fig. 1.** The primed TNT entity's white flashing overlay blends with the TNT texture.

![primed_tnt_z_fighting](https://user-images.githubusercontent.com/69266322/92817005-f9291400-f37a-11ea-96af-fc946bb7537d.png)
**Fig. 2.** The primed TNT entity's white flashing overlay experiences z-fighting with the TNT texture.

### System Information
- Java Version: OpenJDK 14.0.2
- CPU: AMD Ryzen 7 3700x
- GPU: Nvidia GeForce RTX 2080 SUPER
- OS: Pop!_OS 20.04 LTS

**Comment by jellysquid3** [comment]
Fixed by a9a783f1.

**Comment by jellysquid3** [comment]
I closed this issue in error. This still occurs in `1.16.x/dev` right now.

**Comment by bytzo** [comment]
Closing as `1.16.x/next` does not have this issue.
