### ISSUE TITLE
Extra dark diagonal lines at block corners

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#303]
At the corners of these structures it can be seen that there are three dark diagonal rays extending outwards, instead of only one for the absolute corner. Whether the existence of them altogether is a bug I don't know, because they look kinda unsightly.

![2020-09-10_18 36 13](https://user-images.githubusercontent.com/52297970/92773749-c68c1500-f394-11ea-8ceb-ab7fb6d46c07.png)
![2020-09-10_18 36 22](https://user-images.githubusercontent.com/52297970/92773754-c7bd4200-f394-11ea-993f-b4e16d2b999f.png)
![2020-07-16_00 25 20](https://user-images.githubusercontent.com/52297970/92773764-ca1f9c00-f394-11ea-9993-88c723a7783b.png)
![2020-07-15_13 16 16](https://user-images.githubusercontent.com/52297970/92773800-d1df4080-f394-11ea-9618-640c3381117a.png)

**Comment by muzikbike** [comment]
can github register this as one of my reports already

**Comment by muzikbike** [comment]
Still present in 0.3.0:
![2021-08-28_00 24 03](https://user-images.githubusercontent.com/52297970/131197713-ffd2b3bd-e344-4b91-8bdf-6672eae24039.png)

**Comment by muzikbike** [comment]
This is now reported as https://bugs.mojang.com/browse/MC-226943.

**Comment by MeeniMc** [comment]
This should be relabeled as a vanilla issue, not a Sodium bug.

**Comment by jellysquid3** [comment]
See https://github.com/CaffeineMC/sodium-fabric/issues/905#issuecomment-1722539623.
