### ISSUE TITLE
Feature: Different projections and higher FOV

### ISSUE THREAD

**Issue by laundmo** [jellysquid3/Sodium#305]
**Problem**
I personally always feel that FOV in games is handled poorly. There are so many projections that can be used to display a higher FOV, for example my personal favourite the Panini projection. A higher FOV allows you to see more, and feel less like youre looking through a small window.

**Solution**
I would like a setting that allows for chaning the display projection, and for the FOV slider to be unlocked (possibly also with a setting) to allow for larger FOV. Projections that i would like to see supported are: Panini, Equirectangular, Mercator.

**Alternatives**
There is a mod called [Flex FOV](https://www.curseforge.com/minecraft/mc-mods/flex-fov) that already does multiple projections, but sadly that in incompatible with sodium and very performance heavy, as it renders the entire screen 6 times as a cubemap and then reprojects from that.

**Additional context**
- [Blinky](https://github.com/shaunlebron/blinky), a Quake mod that implements various projections, a list of which can be found at /game/lua-scripts/lenses
- [The General Panini Projection](https://wiki.panotools.org/The_General_Panini_Projection) 
- [Panoramic Projections](https://wiki.panotools.org/Projections)
- [In-Depth description of Panini](http://tksharpless.net/vedutismo/Pannini/)

**Comment by jellysquid3** [comment]
These enhancements are not within the scope of Sodium (which is optimization.) They would be better left to other mods.
