### ISSUE TITLE
Does not support latest version of Minecraft as stated

### ISSUE THREAD

**Issue by PQCraft** [jellysquid3/Sodium#314]
Will not work with Minecraft 1.16.3.

**Comment by amnotbananaama** [comment]
Duplicate of several other issues. From the [discord](https://jellysquid.me/discord): 
> Sodium does not work on Minecraft 1.16.2 and later, but an update is in progress. [...] **DO NOT** ask for release dates or beta releases; we'll notify you via Discord when an update is available.
