### ISSUE TITLE
Version for 1.8 - 1.12.2

### ISSUE THREAD

**Issue by PQCraft** [jellysquid3/Sodium#315]
1.8 - 1.12.2 runs faster and will help with optimizations. Most mods are supported by these versions. I do not use anything newer than 1.12.2 due to the changes made to the newer versions and something like this would be very useful for running old versions on old computers.

**Comment by amnotbananaama** [comment]
Duplicate of #111 
Please check if an existing issue already covers your question, rather than spamming the issue tracker. Thank you.

**Comment by kkaur12152-art** [comment]
https://github.com/CaffeineMC/sodium/issues/315

**Comment by kkaur12152-art** [comment]
1.8 - 1.12.2 runs faster and will help with optimizations. Most mods are supported by these versions. I do not use anything newer than 1.12.2 due to the changes made to the newer versions and something like this would be very useful for running old versions on old computers.
