### ISSUE TITLE
Loads Texture files at all angles when using Zink OpenGL to Vulkan Driver

### ISSUE THREAD

**Issue by thyTwilightGoth** [jellysquid3/Sodium#320]
### Expected Behavior
Minecraft to render normally

### Actual Behavior
Minecraft loads all textures in the game at odd angles not attached to blocks

### Reproduction Steps
launch Minecraft from Linux Console with this command:
MESA_LOADER_DRIVER_OVERRIDE=zink /opt/minecraft-launcher/minecraft-launcher

Then launch minecraft and load a world

### Attachments
![2020-09-28_18 17 09](https://user-images.githubusercontent.com/14948037/94502573-55809600-01b9-11eb-8efd-b9fcd7e7a482.png)

### System Information
Operating System: Arch Linux
KDE Plasma Version: 5.19.5
KDE Frameworks Version: 5.74.0
Qt Version: 5.15.1
Kernel Version: 5.8.10-arch1-1
OS Type: 64-bit
Processors: 16 × AMD Ryzen 7 1700 Eight-Core Processor
Memory: 31.4 GiB of RAM
Graphics Processor: Radeon RX 580 Series

- Java Version:
openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12)
OpenJDK 64-Bit Server VM (build 14.0.2+12, mixed mode)

- CPU: AMD Ryzen 7 1700
- GPU: Operating System: AMD Radeon RX 580 Series

**Comment by PhantomG27249** [comment]
What render back end is this?

**Comment by Teh404Gal** [comment]
who uses an experimental mesa opengl to vulkan converter on an opengl minecraft renderer

**Comment by Teh404Gal** [comment]
just tried it with an intel igpu  that works with vulkan
it seems to work for me

**Comment by jellysquid3** [comment]
This is a problem with Zink, not us.
