### ISSUE TITLE
Emissive Lighting (Textures)

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#321]
**Is your feature request related to a problem? Please describe.**
Optifine has that extremely useful feature called "Emessive Textures" and it would've been really cool to see it in Sodium too! 

**Additional context**
Emessive Textures are basically some glowing textures (e.g. you could see endermen eyes glowing in the darkness or diamonds in a cave,

P.S. To be honest I would rather call it "Emissive Lighting" since it makes more sense about what the feature actually does.

<details>
  <summary><bold>Example picture</bold></summary>
    <img src="https://faithful.team/content/images/size/w760h400/2020/07/Minecraft__1.16.1_-_Singleplayer_7_15_2020_4_41_01_PM.png" />
</details>

**Comment by silversquirl** [comment]
This feature is probably not a good fit for Sodium. This should be implemented in a separate Fabric mod, which Sodium would become compatible with once the Fabric Rendering API is implemented.

**Comment by jellysquid3** [comment]
Emissive lighting is a graphical feature which is outside the scope of Sodium (being primarily optimization and bug-fixing.)

**Comment by linuzzx** [comment]
Is there a way to achieve this rn? (Sodium included)

**Comment by mr-pi12** [comment]
> Is there a way to achieve this rn? (Sodium included)

You could use the connected textures mod and find an emissive resource pack with the ctm format. It should work fine with sodium.
