### ISSUE TITLE
Sodium doesn't give a FPS boost on certain CPUs/GPUs

### ISSUE THREAD

**Issue by Snagasm** [jellysquid3/Sodium#323]
Fabric Loader: 0.6.1.51
Sodium:  0.1.0

Some people said it doesn't work for them, not working for me either, so I felt like pointing it out. I get the same FPS with Sodium on that I get in normal vanilla (60-100 normally). Probably has an easy fix that I'm not aware of.

Here's my specs: It's not shown here but I also have  GeForce 820M GPU (not the best, or even decent, I know)

![Screenshot_1](https://user-images.githubusercontent.com/72129742/94665160-b6b48080-0303-11eb-803f-7f1507ab7d42.png)

**Comment by LucilleTea** [comment]
Tech support is better suited to [the Discord server](https://jellysquid.me/discord).
Performance depends on a variety of factors, so can't be considered a bug unless you're showing that sodium handles a specific thing worse than vanilla.
