### ISSUE TITLE
Video Settings does not show Distortion Effects and FOV Effects in 1.16.2-1.16.3 version of the mod

### ISSUE THREAD

**Issue by CalXee** [jellysquid3/Sodium#325]
### Expected Behavior
It shows those 2 options and lets players modify it

### Actual Behavior
Those 2 options are simply not present

Probably just an oversight since its ported directly from the 1.16.1 version.

**Comment by Mallen-git** [comment]
these options are in the accessibility options, not the video settings

**Comment by amnotbananaama** [comment]
In Vanilla, these options are also available in the Video Settings menu as well. Leaving open, it shouldn’t be too difficult to add these but I will wait for work to conclude on the refactor.

For now, you can access them in the accessibility menu, or use the `Shift + P` key combination.

**Comment by sydist** [comment]
This is a duplication of #46

**Comment by pajicadvance** [comment]
Closing this as a duplicate in favor of #46 as it covers all the missing vanilla options.
