### ISSUE TITLE
All entities ignore environment light, causing them to render very brightly even in dark areas

### ISSUE THREAD

**Issue by CalXee** [jellysquid3/Sodium#326]
### Expected Behavior
Mobs rendering dark in dark areas

### Actual Behavior
Mobs rendering very bright in dark areas
![2020-09-30_14 08 56](https://user-images.githubusercontent.com/68349758/94723431-bda0ba80-0326-11eb-95ea-5f7b3b257d5c.png)

**Comment by jellysquid3** [comment]
Fixed by 562eea53.
