### ISSUE TITLE
Add motion blur

### ISSUE THREAD

**Issue by L0um15** [jellysquid3/Sodium#328]
**Is your feature request related to a problem? Please describe.**
Its not a problem.

**Describe the solution you'd like**
I'd love to see customizable motion blur option if its possible to make camera feel smoother.

**Comment by jellysquid3** [comment]
Motion blur is a cosmetic/graphical feature that is outside the scope of Sodium, which is primarily focused on bug-fixing and optimization. This would be better left to another mod.
