### ISSUE TITLE
The video settings GUI does not use standard json translation

### ISSUE THREAD

**Issue by yezhiyi9670** [jellysquid3/Sodium#331]
### Expected Behavior

Texts in video settings GUI can be found in en_us.json.

### Actual Behavior

There's no en_us.json in the mod, making traslating impossible.

**Comment by amnotbananaama** [comment]
Translation is something that is occurring on the development branch. Localization is currently in progress, and is slated for the [0.3 release milestone](https://github.com/jellysquid3/sodium-fabric/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+0.3%22). In the meantime, translations are being crowdsourced on [OneSky](https://jellysquid.oneskyapp.com/collaboration/project?id=366422). Translations will be automatically added from the site when we're ready.

**Comment by yezhiyi9670** [comment]
OK, thanks!
