### ISSUE TITLE
[Feature] Make clouds fog and skybox consistent with terrain fog

### ISSUE THREAD

**Issue by yezhiyi9670** [jellysquid3/Sodium#332]
**Is your feature request related to a problem? Please describe.**

In vanilla, circular fog shape is not supported on non-NVIDIA GPUs because of the usage of `gl_NV_fog_distance`. This results in a linear fog start on both terrain and clouds. Also the skybox is changed to be linear-shaped in order to be consistent with the fog.

Sodium enables circular fog on terrain, but clouds fog and skybox still remain linear. This gives an inconsistent look.

![image](https://user-images.githubusercontent.com/39194383/94982516-a1428f00-056d-11eb-8be3-7bf82a90c3a1.png)

**Describe the solution you'd like**

Add circular fog to clouds. and change the skybox to the way they look while using NVIDIA cards.

**Comment by BlueToothDentist** [comment]
I've noticed this also happens with mobs and other entities such as paintings, minecarts, and signs. In versions with togglable fog, entities are still affected and often show up as blank outlines obstructing terrain.

**Comment by IMS212** [comment]
This should not be an issue on 1.17+, where everything uses spherical fog.
