### ISSUE TITLE
[Feature] Fix MC-70850, a bug related to invisible chunks

### ISSUE THREAD

**Issue by yezhiyi9670** [jellysquid3/Sodium#333]
**Is your feature request related to a problem? Please describe.**

[MC-70850](https://bugs.mojang.com/browse/MC-70850) causes invisible chunk issues in game almost randomly. Two maps demonstrating this can be found by following the link. 

**Describe the solution you'd like**

Make a full fix to this.

**Describe alternatives you've considered**

Add an option to turn off occlusion culling. The performance impact is very minor and might be nulled by Sodium's optimizations. A way of doing so can be found [here](https://github.com/yezhiyi9670/occlusion-culling-fix)(it's a Forge mod).

**Comment by CalXee** [comment]
Sounds like a good idea. I don't have a good understanding of that bug but I think it's what's causing random invisible chunks.

**Comment by fsharpseven** [comment]
I don't think giving an option to disable occlusion culling is necessarily the way to go. I tested it on my (admittedly low-end) hardware, and it produced a non-trivial performance hit (approx. 35-60 fps -> 18-39 fps).

**Comment by jellysquid3** [comment]
Disabling occlusion culling is an awful "solution" to this problem, which is that Minecraft's graph traversal method for culling chunks has bugs. Doing so would drastically explode the number of rendered chunk sections in a large number of cases.

Sodium already fixes a few problems in vanilla's chunk occlusion, but ultimately we'd want to replace occlusion culling all together with a faster and more aggressive algorithm.
