### ISSUE TITLE
Feature only version.

### ISSUE THREAD

**Issue by SemmieDev** [jellysquid3/Sodium#337]
**Is your feature request related to a problem? Please describe.**
Sodium and OptiFabric are obviously incompatible. But I would like to use both of them at ones.

**Describe the solution you'd like**
Maybe a version of Sodium that only has features that are compatible with OptiFabric?

**Describe alternatives you've considered**
A harder way of doing it is blocking OptiFine enhancements and only allowing OptiFine features. I don't even think it's possible without making your own OptiFabric.

**Comment by FlashyReese** [comment]
It's impossible since Sodium rewrites the same area of the game like OptiFine does.

Edit: If you are looking for OptiFine features, here are some alternative options for Fabric https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754
