### ISSUE TITLE
Crash 1.16.3

### ISSUE THREAD

**Issue by xhmr** [jellysquid3/Sodium#338]
### Reproduction Steps
1. Join the server.
2. It will crash when 'joining world' or after some time.

### Crash Report File
https://pastebin.com/raw/aNW4zt4W

### Additional Information
-

**Comment by SekoiaTree** [comment]
I've been joining servers pretty often with sodium, no crashes yet. Is there something special with the server? If not, can you send the IP?

**Comment by xhmr** [comment]
> I've been joining servers pretty often with sodium, no crashes yet. Is there something special with the server? If not, can you send the IP?

I'm using fabric with these mods since yesterday. Yesterday no problems but only few players, today already 3 crashes. Ip is cpvp.pl

It doesn't happen all the time, but today happened already 5 times.

**Comment by SekoiaTree** [comment]
Joined about 5 times, both centrumpvp.pl and cpvp.pl, never got any crashes. I don't know what could happen. Have you tried other servers?

**Comment by xhmr** [comment]
@SekoiaTree after removing 'thaumicspeedup-1.3.jar' from mods I didn't have any crashes. Last crash happened 3 hours ago and I player pretty actively.

**Comment by ghost** [comment]
After searching for the mod "thaumicspeedup" I found that it is a 1.12 mod, are you using it on a 1.16.3 server? 
most (if not all) 1.12 forge mods will not work with forge 1.16(I don't know if this applies to the un-official 1.12 port of fabric ),
also, forge mods don't work with fabric without the use of something like https://patchworkmc.net/ which is not fully working yet(it can only work with simple mods check the website more info)

**Comment by xhmr** [comment]
@Valleriite that's true. I was using this mod on fabric client. Thanks! :)

**Comment by ghost** [comment]
If your problem is fixed,
please close this issue.

**Comment by davidromrell** [comment]
I believe, assasin541 you are having a mixin or SpongePowered,  error like me,  can you paste in a debug or log file? the crash wont give enough info

**Comment by xhmr** [comment]
@ERRORFISH111 I didn't do anything with Sponge.
