### ISSUE TITLE
Memory leak with the mod Campanion

### ISSUE THREAD

**Issue by Leeo97one** [jellysquid3/Sodium#339]
### Expected Behavior
No memory leak when a tent schematic shows up.
See: https://github.com/TerraformersMC/Campanion/wiki/Tents#usage

### Actual Behavior
When a tent schematic is displayed, the memory usage increase until the game freeze due to an out of memory situation.

### Reproduction Steps
1. Load the mods Sodium and Campanion
2. Craft a tent in a bag (https://github.com/TerraformersMC/Campanion/wiki/Tents#small-tent-in-a-bag)
3. Equip it

### Attachments
With Sodium: https://streamable.com/xeazvl
Without Sodium: https://streamable.com/re22oq

### System Information
- Java Version: openjdk version "11.0.8" 2020-07-14
- CPU: Intel® Core™ i5-7300HQ CPU @ 2.50GHz × 4
- GPU: GeForce GTX 1050 Mobile

**Comment by Maks220v** [comment]
I think i have same issue, can you tell me is this a memory leak or what a heck is this? https://imgur.com/a/JmrjhIW

**Comment by Maks220v** [comment]
Yep, deleted sodium from mod folder and the lags are GONE

**Comment by FlashyReese** [comment]
> I think i have same issue, can you tell me is this a memory leak or what a heck is this? https://imgur.com/a/JmrjhIW

Yours doesn't look like an memory leak.

**Comment by Leeo97one** [comment]
Yeah I don't think it's the same problem. x)
You should do more troubleshooting and create a new issue.

**Comment by fsharpseven** [comment]
Campanion uses the Fabric Rendering API iirc, so until Sodium supports Fabric Rendering API you shouldn't expect it to work with Sodium.

**Comment by comp500** [comment]
It looks like this has been fixed in Campanion, see https://github.com/TerraformersMC/Campanion/pull/118.

**Comment by amnotbananaama** [comment]
Closing as an external issue, as Campanion claims to have fixed it
