### ISSUE TITLE
OpenGL MultiDraw 4.3 doesn't work with AMD Vega 8

### ISSUE THREAD

**Issue by lakejason0** [jellysquid3/Sodium#341]
### Expected Behavior
Since 4.3 is the default setup, I expected that it runs normally.

### Actual Behavior
The block renders strangely with 4.3, but 3.0 is fine.

### Reproduction Steps
Provide information on how to reproduce this game crash. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear! If applicable, please provide a world file as a compressed ZIP which contains a minimally reproducible example of the issue. 

1. Use Lenovo Xiaoxin Air 14 2019 (Ryzen 5 3500U + Vega 8)
2. Open a world
3. Renders bizarrely

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.
![2020-10-06_22 32 15](https://user-images.githubusercontent.com/36039861/95216546-c44a9880-0824-11eb-94ac-cbc7e8887fb0.png)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: 14
- CPU: Ryzen 5 3500U
- GPU: Vega 8

**Comment by jellysquid3** [comment]
> Since 4.3 is the default setup

No, it's not. You have purposefully disabled the driver blacklist as your F3 screen explains.

**Comment by lakejason0** [comment]
> > Since 4.3 is the default setup
> 
> No, it's not. You have purposefully disabled the driver blacklist as your F3 screen explains.

hmmm so it's the pre-built packs fault.
ok I get it, thanks for your help.

**Comment by Titaniumtown** [comment]
What OS is this on? Are you using the proprietary AMD drivers? I believe the opensource AMD drivers don't have this issue (correct me if I'm wrong).

**Comment by lakejason0** [comment]
it's Windows 10 19042

**Comment by Titaniumtown** [comment]
Ok nvm then, you can't really fix that issue then (afaik). The proprietary drivers suck, mesa ftw.

**Comment by ghost** [comment]
**Correct me if I am wrong.**
@lakejason0 This is a known issue with AMD drivers on windows(not sure if it happens on Linux with proprietary drivers),
it does not happen on Linux with mesa drivers as far as I know.
See:https://github.com/jellysquid3/sodium-fabric/issues/24

**Comment by lakejason0** [comment]
> **Correct me if I am wrong.**
> @lakejason0 This is a known issue with AMD drivers on windows(not sure if it happens on Linux with proprietary drivers),
> it does not happen on Linux with mesa drivers as far as I know.
> See:#24

thank you

**Comment by Titaniumtown** [comment]
> not sure if it happens on Linux with proprietary drivers

The issue does exist on Linux, but no one on linux uses the proprietary drivers because mesa exists and is way faster. Mesa FTW

**Comment by ghost** [comment]
You are welcome @lakejason0 
Forgot to mention,
there is a pull-request with a workaround this issue (https://github.com/jellysquid3/sodium-fabric/pull/188) but it has not been merged yet(I̶̶̶ ̶̶̶t̶̶̶h̶̶̶i̶̶̶n̶̶̶k̶̶̶ ̶̶̶b̶̶̶e̶̶̶c̶̶̶a̶̶̶u̶̶̶s̶̶̶e̶̶̶ ̶̶̶i̶̶̶t̶̶̶ ̶̶̶l̶̶̶o̶̶̶w̶̶̶e̶̶̶r̶̶̶e̶̶̶d̶̶̶ ̶̶̶p̶̶̶e̶̶̶r̶̶̶f̶̶̶o̶̶̶r̶̶̶m̶̶̶a̶̶̶n̶̶̶c̶̶̶e̶̶̶ ̶̶̶o̶̶̶n̶̶̶ ̶̶̶N̶̶̶v̶̶̶i̶̶̶d̶̶̶i̶̶̶a̶̶̶ ̶̶̶G̶̶̶P̶̶̶U̶̶̶s̶̶̶a̶n̶d̶ ̶a̶n̶d̶ ̶m̶a̶y̶b̶e̶ ̶s̶o̶m̶e̶ ̶i̶n̶t̶e̶l̶ ̶i̶g̶p̶u̶s̶,̶̶̶ ̶̶̶b̶̶̶u̶̶̶t̶̶̶ ̶̶̶I̶̶̶ ̶̶̶d̶̶̶o̶̶̶n̶̶̶'̶̶̶t̶̶̶ ̶̶̶k̶̶̶n̶̶̶o̶̶̶w̶̶̶ ̶̶̶f̶̶̶o̶̶̶r̶̶̶ ̶̶̶s̶̶̶u̶̶̶r̶̶̶e̶̶̶,̶̶̶ EDIT: not sure if it lowered the fps but jelly said that she will implement the patch but she's busy, read this:https://github.com/jellysquid3/sodium-fabric/pull/188#issuecomment-674321902)
@FlashyReese [has a fork of sodium](https://github.com/FlashyReese/sodium-fabric/) with the fix applied, and he has released a mod jar of it if you want to use it
**Keep in mind it is an unofficial fork with no official support provided. USE IT AT YOUR OWN RISK.**

**Comment by lakejason0** [comment]
> You are welcome @lakejason0
> Forgot to mention,
> there is a pull-request with a workaround this issue (#188) but it has not been merged yet(I think because it lowered performance on Nvidia GPUs, but I don't know for sure)
> @FlashyReese has a fork of sodium with the fix applied, and he has released a mod jar of it if you want to use it
> **Keep in mind it is an unofficial fork with no official support provided USE IT AT YOUR OWN RISK.**

oh FlashyReese, hmmm
good to know, thanks

**Comment by ghost** [comment]
I linked the fork.

**Comment by ghost** [comment]
After reading this:https://github.com/jellysquid3/sodium-fabric/pull/188#issuecomment-674321902
the fixes will be included but jellysquid is busy.

**Comment by ghost** [comment]
@lakejason0 I updated my comment,please read it:https://github.com/jellysquid3/sodium-fabric/issues/341#issuecomment-704425852

**Comment by jellysquid3** [comment]
Sodium does not enable the OpenGL 4.3 renderer on known-broken drivers unless the user specifically overrides the "Disable Driver Blacklist" option. The tracking issue for this driver problem is #24 and a workaround exists in #188.
