### ISSUE TITLE
Resolution setting

### ISSUE THREAD

**Issue by ZaFaLcoN** [jellysquid3/Sodium#342]
When i install sodium the Resolution scale settings goes **_poof_** and the **resolution setting really helps me out and i think it helps other players too personally i play at 640x480 because for me it looks better and increases the performance** so it would be good to get the resoulution setting back

**Comment by mrmangohands** [comment]
It will likely be added at some point, for now you can access the vanilla settings menu by using shift-p in the sodium one to change it.

**Comment by amnotbananaama** [comment]
Closing as a duplicate of #46, you can use the workaround that Mango listed for now.
