### ISSUE TITLE
OpenGL 3+ not supported on macOS Catalina

### ISSUE THREAD

**Issue by Ai-Ya-Ya** [jellysquid3/Sodium#343]
### Expected Behavior
My version of OpenGL is 4.1 so I should be able to switch the chunk renderer between Oneshot 2.0 and 3.0.

### Actual Behavior
The chunk renderer is stuck on OpenGL 2.0. 

### Reproduction Steps
1. macOS Catalina, MultiMC 0.6.11-1370, Minecraft 1.16.1 (mods installed: ModMenu, Fabric API, Lithium, Phosphor, Sodium, CarpetMod)
2. Go to settings and click on Chunk Renderer
3. Nothing happens, stays on Oneshot (GL 2.0)

### System Information
![image](https://user-images.githubusercontent.com/72513839/95356422-a4eb5400-0894-11eb-87da-d1eff2a9c8bc.png)

- Java Version: 1.8.0_265
- CPU: Intel Core I5, dual-core, 2.5GHz
- GPU: Intel HD Graphics 4000

**Comment by AMereBagatelle** [comment]
macOS has some technical limitations that do not allow for it to use anything higher than openGL 2.  This is a known bug that I don't believe can be solved inside Sodium.

**Comment by Ai-Ya-Ya** [comment]
Was this due to deprecating OpenGL in 10.14?

**Comment by ghost** [comment]
If it isn't a sodium issue, the bug label should be switched for something else.

**Comment by mrmangohands** [comment]
macOS only supports up to gl 2.1 when using legacy opengl features, which minecraft does

**Comment by amnotbananaama** [comment]
Closing as an external issue, Jelly explained this [here](https://git.io/JUjEl) far better than I ever can.

> Minecraft still uses parts of the fixed-function pipeline in rendering, which means that in order to use modern OpenGL features, it needs to use a compatibility profile. macOS does not support these compatibility profiles, and generally it also doesn't support any extensions which would otherwise allow us to use these newer features in older versions of OpenGL.
