### ISSUE TITLE
Loading Screen loading in Loop - Incompatibility with RSWires

### ISSUE THREAD

**Issue by RodrigoZXMota** [jellysquid3/Sodium#348]
### Expected Behavior
The game should open fine, no errors

### Actual Behavior
When loading minecraft with Sodium + RSWires all letters are replaced by squares and the game endlessly loops between Mojang Loading Screen and Menu, turning impossivle even starting a world.

### Reproduction Steps
I'm using the latest build of fabric at the time for **>1.16.2<** 

1. Install Sodium Mc.1.16.3-0.1.0.jar
2. Install RSWires rswires-4.9.1.jar
3. Error occours

### System Information

- Java Version: Latest java
- CPU: Intel i7 4770
- GPU: GTX 750 Ti
(But error happens in other pc's aswell)

**Comment by ImperatorStorm** [comment]
Sodium does not have a version for 1.16.2, retry with 1.16.3

**Comment by XArchE1** [comment]
Actually, Sodium's 1.16.3 version works just fine with 1.16.2

**Comment by jellysquid3** [comment]
RSwires depends on FRAPI support, which Sodium lacks currently. See #5.
