### ISSUE TITLE
Sodium does not change performance

### ISSUE THREAD

**Issue by bloxanne123** [jellysquid3/Sodium#349]
I installed sodium for 1.16.2, and there was no difference in my FPS. I used as many of the same setting as possible and same mods. There was a different GUI, but the performance was the same. With optifine, I get 100 fps compared to 40 ish with the stock renderer. I thought I should be getting at least 150 FPS. What's wrong? (I use Lithium, Phosphor, and mod menu, along with the fabric API). I tried using just Sodium and the fabric API, and mod menu.

**Comment by vichvich4444** [comment]
Make sure Minecraft uses dedicated GPU.

**Comment by amnotbananaama** [comment]
The GitHub Issue tracker is for bugs and is not intended as a support site. I suggest joining [JellySquid's Hideout](https://jellysquid.me/discord) and providing screenshots of the [Profiler Graph](https://minecraft.gamepedia.com/Debug_screen#Profiler_graph) and [Frame Time Graph](https://minecraft.gamepedia.com/Debug_screen#Frame_time_graph) during normal gameplay, in the `#support` channel.
