### ISSUE TITLE
Support for CBT (connected-block-textures) :3

### ISSUE THREAD

**Issue by EnanoFurtivo** [jellysquid3/Sodium#357]
- Fabric loader 0.10.1 build 209 - 1.16.3

**_Mods:_**

- fabric-api-0.24.0+build.411-1.16
- sodium-fabric-mc1.16.3-0.1.0
- [connected-block-textures-0.1.5+1.16](https://github.com/LudoCrypt/connected-block-textures/releases/tag/0.1.5-1.16) (unoficial - updated build for 1.16.3)

As stated in [**this**](https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754) optifine-replacement mods list,  **CBT** is not compatible with sodium. I tested this myself just to be sure, and that seems to be the case. Since i do not see an open nor closed ticket respecting this subject, i will make it myself.

I made this because the developer said in [**this**](https://github.com/Nuclearfarts/connected-block-textures/issues/5) ticket that the issue has to do with something on sodium's end.

There's no real reason to include this but [**here**](https://github.com/Nuclearfarts/connected-block-textures) is the repo for CBT.
Even though the dev seems to be off, there are builds that work on 1.16.3.

**Comment by EnanoFurtivo** [comment]
Nvm i just saw the ticket. Closing the issue now, I'm sorry for this. Although you should add the tag mod compatibility to it

**Comment by Redd56** [comment]
could you refrence the original ticket?

**Comment by EnanoFurtivo** [comment]
[Here](https://github.com/jellysquid3/sodium-fabric/issues/61) is the original one I think. Although it was closed aswell since an update was supposed to fix this issue. Didn't really follow up with the subject.

**Comment by amnotbananaama** [comment]
> could you refrence the original ticket?

https://github.com/jellysquid3/sodium-fabric/issues/5
