### ISSUE TITLE
Chunk face culling culls lava 

### ISSUE THREAD

**Issue by fsharpseven** [jellysquid3/Sodium#358]
## Expected Behavior
The lava is properly opaque.

_Chunk face culling off:_
![2020-10-18_19 50 42](https://user-images.githubusercontent.com/40721769/96389074-3f904080-117b-11eb-8faa-da8e07207ebb.png)

### Actual Behavior
The beacon effect and the sky are visible through the lava.

_Chunk face culling on:_
![2020-10-18_19 50 31](https://user-images.githubusercontent.com/40721769/96389073-3f904080-117b-11eb-8603-fbe13ebef543.png)

### Reproduction Steps
Build something similar to this at least 3 blocks deep (made with barrier block):
![2020-10-18_19 54 12](https://user-images.githubusercontent.com/40721769/96389140-b75e6b00-117b-11eb-8fab-96dc69cc248c.png)

1. Give yourself the Fire Resistance effect.
2. Go underneath the lava until you are under the top of the lava.
3. Move towards the back, and you should see this phenomenon.

Note: this also happens in lava falls.

### System Information
- Java Version: Java 14.0.1 (OpenJDK)
- CPU: Intel Core i5-4260U
- GPU: Intel HD Graphics 5000 (OpenGL 2.1)

**Comment by Titaniumtown** [comment]
This is a known issue iirc.

**Comment by fsharpseven** [comment]
Oh my bad, I can close it if it's a duplicate or it's known.

**Comment by fsharpseven** [comment]
It appears this was fixed after the 0.1 release.
