### ISSUE TITLE
Sand Below Cactus is not showing up

### ISSUE THREAD

**Issue by SaiCode-DEV** [jellysquid3/Sodium#359]
### Expected Behavior
Sand below a cactus should be shown

### Actual Behavior
Sand below a cactus does not show up, so you can see caves below the ground

### Reproduction Steps. 

1. Place a flat sand area with a cactus on top (or go in the desert)
2. Look carefully at the bounds of the cactus
3. You can see throu the ground

### Attachments
A Screenshot of the scene

![2020-10-19_09 53 17](https://user-images.githubusercontent.com/53049957/96417613-d3045880-11f1-11eb-822a-d815f2e67e62.png)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: i dont know, but the newest right now...
- CPU: Amd Ryzen 7 3700u
- GPU: Vega 10 graphics

**Comment by SaiCode-DEV** [comment]
By the way: this is not only for Cactus, it is also the problem with custom recurce packs with modified block models, that there isnt anything shown.

**Comment by Titaniumtown** [comment]
@SaiBot-YT Are you using proprietary AMD drivers? Because there are a bunch of issues with the proprietary drivers, mesa is both faster and more compatible than the proprietary ones. Also, you can check your java version in the F3 screen, top right hand corner.

**Comment by SaiCode-DEV** [comment]
tried to update the driver... it now still does the same and furthermore you cant really use a transparent recurce pack... tried to get a recurce pack with more transparent blocks (more than just glass) and it doest also work too. just ignores transparency... (i made a block where you can see throu from one side, like a little hole in a door, but just with a endstone. )


To sum it up: the issue is with handling transparency of blocks

**Comment by Titaniumtown** [comment]
@SaiBot-YT Could you just show your F3 screen? since you aren't providing the required info.

**Comment by jellysquid3** [comment]
@Titaniumtown This issue has nothing to do with a driver or hardware. It's a bug in Sodium.

**Comment by SaiCode-DEV** [comment]
I found another related problem: Signs are transparent (i use vanillatweaks for dark mode, but signs are not transparent when sodium is not installed. I will do further Reseach on that topic. and why it happens

**Comment by SnooComics9452** [comment]
not below only, snow layer can place side of cactus

**Comment by mrmangohands** [comment]
@amnotbananaama are you able to reproduce this? I can't seem to, even on 0.1, and no one mentioned what versions they were using

**Comment by MeeniMc** [comment]
Can't replicate and this is very old.

**Comment by pajicadvance** [comment]
Closing for now as no one seems to be able to reproduce the issue.
