### ISSUE TITLE
When breaking a block while looking straight down, breaking animation doesn't show.

### ISSUE THREAD

**Issue by Jorkles** [jellysquid3/Sodium#36]
### Expected Behavior
Block breaking animation should show.

### Actual Behavior
Replace this text with what actually happened.
Block breaking animation does not show.

### Reproduction Steps
1. Be using the 0.1.0 snapshot version of Sodium for 1.15.2
2. Look straight down at a block (second look coord at 90)
3. Observe that the block breaking animation does not play.

### Attachments
VLC was being sucky and I couldn't convert the video to something I could put on here.
Screenshot here is the best I can do.
![2020-06-26_14 27 30](https://user-images.githubusercontent.com/64293495/85902583-3a1c7e00-b7b9-11ea-8873-c50ca9063eba.png)

### System Information

- Java Version: [fill me in]
- CPU: i7 9700
- GPU: Nvidia GTX 1660 ti

**Comment by vichvich4444** [comment]
Can confirm. Also looks like clipping of breaking overlay is too big.

**Comment by jellysquid3** [comment]
This issue does not appear when the "Compact Vertex Format" is disabled, suggesting that this is being caused by imperceptible differences in the rendered chunk meshes.

**Comment by jellysquid3** [comment]
Fixed by https://github.com/jellysquid3/sodium-fabric/commit/a7f058be2f2fe66510ccbcd67fd3a03f49ac7d3a.
