### ISSUE TITLE
please update it to 1.16.2 because whenerv i load it with 1.16.1 my game crashesw

### ISSUE THREAD

**Issue by SneakySnakeySpidey** [jellysquid3/Sodium#361]

**Comment by Titaniumtown** [comment]
Could you please provide a description of the crash and logs. Plus sodium already has 1.16.3 support.

**Comment by Valleriite** [comment]
the 1.16.3 version of sodium supports 1.16.2,
please download the mod from here:https://www.curseforge.com/minecraft/mc-mods/sodium
and try again

**Comment by ghost** [comment]
The 1.16.3 version of sodium doesn't support 1.16.1
if you want to use minecraft 1.16.2 OR 1.16.3 with sodium use the 1.16.3 version of sodium
if you want to use minecraft 1.16.1 with sodium use the 1.16.1 version of sodium
downloads available here:https://www.curseforge.com/minecraft/mc-mods/sodium/files
