### ISSUE TITLE
Crash/clash with Thallium

### ISSUE THREAD

**Issue by NightOps007** [jellysquid3/Sodium#364]
https://github.com/IsaiahPatton/thallium/issues/24

**Comment by jellysquid3** [comment]
I have no interest in supporting Thallium as the mod has been nothing but trouble, [from misleading users about the true frame rate by re-presenting old frames](), [taking crazy and random stabs at trying to inflate the FPS counter by running its calculations on another thread](https://github.com/IsaiahPatton/thallium/blob/0654310359d6e9fb300915b6ebe7424bcf9fb4d7/src/main/java/thallium/fabric/mixins/old/MixinMinecraftClient.java), to [directly taking code from this very mod](https://github.com/IsaiahPatton/thallium/issues/3) under terms that violate Sodium's licensing, and deleting any and all criticism of their practices or claims.

There might be one or two micro-optimizations in Thallium, but you are certainly not missing out on anything. I have yet to see any evidence the mod is anything more than an attempt to reap ad/linkback revenue from users who do know better.

**Comment by NightOps007** [comment]
Thanks for the info.
