### ISSUE TITLE
Sodium performance

### ISSUE THREAD

**Issue by xhmr** [jellysquid3/Sodium#365]
**Is your feature request related to a problem? Please describe.**
On Minecraft 1.16.3 with Sodium and your other mods, you have low fps. Probably more fps you can get on 1.8 vanilla or 1.8 with optifine. Why does that happen? How can we fix that and make better performance?

**Describe the solution you'd like**
More fps, less lag spikes on 1.16.3.

**Describe alternatives you've considered**
No other alternatives

**Additional context**
Make 1.16.3 playable <3

**Comment by ImperatorStorm** [comment]
hardware? settings?

**Comment by xhmr** [comment]
Mods:
[hidden]
Hardware:
[hidden]
Settings:
[hidden]

**Comment by amnotbananaama** [comment]
The GitHub issue tracker is for bugs, and is not intended as a support site. I suggest joining the [discord](https://jellysquid.me/discord), and providing screenshots of the [Profiler Graph](https://minecraft.gamepedia.com/Debug_screen#Profiler_graph) and [Frame Time Graph](https://minecraft.gamepedia.com/Debug_screen#Frame_time_graph) during normal gameplay, in the `#support` channel.
