### ISSUE TITLE
Option to make lilypads render with the same rotation as in vanilla minecraft

### ISSUE THREAD

**Issue by Jeroen-45** [jellysquid3/Sodium#366]
**Is your feature request related to a problem? Please describe.**
The rotation that lilypads are rendered in is inconsistent with the vanilla version of minecraft. This, for example, makes it difficult to use lilypads for hiding (or finding) secret codes that use this location-specific rotation. I have been told this discrepancy is caused by Sodium using a different random source for randomized block rotations.

**Describe the solution you'd like**
It would be useful to have the option to disable this specific optimization.

**Describe alternatives you've considered**
A more general option to choose which random source to use would also help.

**Comment by IMS212** [comment]
Is this still an issue? With 1.19, everything uses the vanilla Random.

**Comment by Jeroen-45** [comment]
I just checked, and it appears that the lilypads are still rendered with rotations different to vanilla in 1.19.2. Perhaps interesting is that the rotations with sodium have changed from 1.18.2 to 1.19.2, while the vanilla rotations are still the same between versions. I have tested this with a superflat water world with the top layer set to lilies in both versions with and without sodium, you can view the results below:

1.18.2 Vanilla:
![1 18 2 Vanilla](https://user-images.githubusercontent.com/42911502/186500628-8bbcf4d8-c35e-44a7-a3c3-019268ab5853.png)

1.18.2 Fabric + Sodium:
![1 18 2 Fabric + Sodium](https://user-images.githubusercontent.com/42911502/186500679-9111f2d3-a0a8-4412-a258-7774d134d7b9.png)

1.19.2 Vanilla:
![1 19 2 Vanilla](https://user-images.githubusercontent.com/42911502/186500732-daf0edfb-07e7-4837-b0e2-ddd6c57c53e2.png)

1.19.2 Fabric + Sodium:
![1 19 2 Fabric + Sodium](https://user-images.githubusercontent.com/42911502/186500780-b29ebd62-f480-42a6-b668-0e3a9cb53dc2.png)

I found that the best way to view the differences is to compare a specific row or column, or to open them in an image viewer and switch back and forth.

**Comment by FlashyReese** [comment]
It appears this issue has been fixed as of https://github.com/CaffeineMC/sodium-fabric/commit/c7a584286ff99241f1f08875976e7a496829cdac.

Vanilla:
![image](https://github.com/CaffeineMC/sodium-fabric/assets/30311066/905c9c9b-44cf-4892-a31c-f58c27110740)

Sodium: 
![image](https://github.com/CaffeineMC/sodium-fabric/assets/30311066/9563d290-0ae8-47a5-8c5b-3a1601acaa96)
