### ISSUE TITLE
Less FPS and GPU usage on different server versions

### ISSUE THREAD

**Issue by xhmr** [jellysquid3/Sodium#369]
### Expected Behavior
More fps and proper usage  of GPU.

### Actual Behavior
On Minecraft 1.16.3 with Sodium and your other mods, you have low fps. Probably more fps you can get on 1.8 vanilla or 1.8 with optifine. Why does that happen? How can we fix that and make better performance? 

### Reproduction Steps
Join 1.8 server with 1.16.3. You have less gpu usage, less fps than on 1.16.3 server or singeplayer. It's around 30%, while on 1.16.3 it's up to 97%.

### Attachments
Mods:
https://share.getcloudapp.com/DOu9Pk9e
Hardware:
https://share.getcloudapp.com/xQuANOnr
Settings:
https://share.getcloudapp.com/7Ku8XjPp
https://share.getcloudapp.com/GGuryJQD
https://share.getcloudapp.com/wbuP5v6r

### System Information
Windows 10 64bit, 16gb ram

- Java Version: 1.15.0.1
- CPU: i7-4770k
- GPU: GTX 1050ti

**Comment by lenrik1589** [comment]
well duh it's 1.8 server i suppose it's just your luck (why do you even connect to 1.8 server from 1.16.3 client and expect good performance?) or server not sending expected data so that DFU has to do ton of work and slows down other threads ¯\\\_(°^°)\_/¯

**Comment by silversquirl** [comment]
@lenrik1589 OP is likely connecting to a server that is compatible with both 1.8 and 1.16 (or they're using MultiConnect, though I didn't see that in their mods list). If they're getting worse performance on a particular server that may or may not be an issue fixable in Sodium, and it may or may not be related to the server software.
Please don't dismiss issues purely based on speculation.

@assasin541 Would you be able to join [JellySquid's Discord](https://jellysquid.me/discord) to help troubleshoot this better?

**Comment by xhmr** [comment]
@vktec @lenrik1589 after some research we found out that texts like scoreboard, holograms, nicknames, chat and toolbar are lagging prety badly. That's where a lot of performance go,

**Comment by jellysquid3** [comment]
The issue tracker is not a forum for open-ended discussion, and there's nothing really in this issue that points to a specific problem. Saying "the game is slower than older versions" is not only an incredibly obvious statement but means very little.

**Comment by xhmr** [comment]
> @vktec @lenrik1589 after some research we found out that texts like scoreboard, holograms, nicknames, chat and toolbar are lagging prety badly. That's where a lot of performance go,

@jellysquid3

**Comment by xhmr** [comment]
https://github.com/jellysquid3/sodium-fabric/issues/382
