### ISSUE TITLE
Post to CurseForge

### ISSUE THREAD

**Issue by Madis0** [jellysquid3/Sodium#37]
**Is your feature request related to a problem? Please describe.**
Want to see this mod in CurseForge Minecraft mods section.

**Describe the solution you'd like**
Post the latest compiled JAR (of Discord channel). The JAR could be marked as alpha and comments could be disabled.

**Describe alternatives you've considered**
Github Releases, Jenkins, ...

**Additional context**
Posting it there helps bring awareness to people that this mod even exists, which means more bug reporting and more Patreons!

**Comment by Siuolplex** [comment]
It probably wont be right now. This is currently exclusive to people who are subscribed on patreon or people who can compile the mod. It might be a good idea to mention it on the mod pages

**Comment by jellysquid3** [comment]
This is just waiting on CurseForge to approve it now.
