### ISSUE TITLE
Lightning strike stays forever

### ISSUE THREAD

**Issue by xhmr** [jellysquid3/Sodium#371]
### Expected Behavior
Not staying lighting strike

### Actual Behavior
Probably: When you don't look at the direction of the lightning strike it stays there forever.
For sure: Sometimes lightning strike stays forever.

### Reproduction Steps
Probably: When you don't look at the direction of the lightning strike it stays there forever.
For sure: Sometimes lightning strike stays forever.

### Attachments
-

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

Windows 10 64bit, 16gb ram

Java Version: 1.15.0.1
CPU: i7-4770k
GPU: GTX 1050ti

**Comment by fsharpseven** [comment]
Do you have more information or a screenshot? I can't seem to reproduce this bug.

**Comment by ghost** [comment]
Are you using fabulous graphics?
Maybe it is causing issues.

**Comment by fsharpseven** [comment]
@Valleriite That's interesting. With fabulous graphics on, lightning bolts (and rain/particles) don't render at all. Is this a known issue?

**Comment by xhmr** [comment]
@DasBundesland maybe it have something with changing world.
@Valleriite i have fast graphics.

**Comment by ghost** [comment]
> @Valleriite That's interesting. With fabulous graphics on, lightning bolts (and rain/particles) don't render at all. Is this a known issue?

It could be a vanilla issue,-if you want-test in vanilla if it doesn't happen in it, report the bug in this issue tracker. 
Because fabulous graphics have issues with some gpus.

> @Valleriite i have fast graphics.

I don't think it is a vanilla issue but maybe it could.

**Comment by xhmr** [comment]
https://share.getcloudapp.com/Z4uyNjdN

**Comment by xhmr** [comment]
It's not vanilla issue.

**Comment by fsharpseven** [comment]
Does the lightning stay there even if you relog?

**Comment by xhmr** [comment]
No

**Comment by xhmr** [comment]
@jellysquid3 it may happen when spawned lighting is outside of view distance. Maybe it's because it's packet not real entity.

**Comment by 2No2Name** [comment]
Is this bugreport about singleplayer or servers?

**Comment by xhmr** [comment]
@2No2Name I didn't check that on singleplayer.

**Comment by MeeniMc** [comment]
can't reproduce 0.4.10, this is very old.

**Comment by pajicadvance** [comment]
Very stale issue, will reopen if someone runs into it again.
