### ISSUE TITLE
Parts of portal don't render when looking through multiple

### ISSUE THREAD

**Issue by NoComment1105** [jellysquid3/Sodium#376]
### Expected Behavior
I should see all the portal blocks

### Actual Behavior
Certain parts of the portals behind one have areas missing

### Reproduction Steps
I'm not sure if it can be reproduced but I if I look through parts are missing

1. Have many portals in front of each other
2. Look through
3. Parts missing
### Attachments
![2020-11-03_18 41 19](https://user-images.githubusercontent.com/67918617/98029187-09072680-1e07-11eb-9bed-ecc60a8d5072.png)
### System Information

- Java Version: [15.0.1]
- CPU: [Intel i5-5300U]
- GPU: [Intel HD 5500

**Comment by amnotbananaama** [comment]
Thank you for the report, this has already been reported as #38.

**Comment by NoComment1105** [comment]
Ah okay, I didnt realise they were they same, I looked through to check I wasn't duplicating but oops sorry
