### ISSUE TITLE
A certain block (even when its empty) stops getting rendered beyond a certain distance and a hole is visible instead

### ISSUE THREAD

**Issue by heyjudek** [jellysquid3/Sodium#383]
### Expected Behavior
Normally, there should not be a hole in the area surrounded with the red circle as there are solid blocks over there.
### Actual Behavior
Instead of the blocks, one sees a hole when one gets away from that area beyond a certain distance. Approaching back to that area fixes the problem. Also, destroying the block directly to the right of it also fixes the problem and everything is rendered properly from all distances. However, adding that block back will make re-create that hole from over a 

certain distance again
### Reproduction Steps
1) Once the distance between the player and that block is small enough, it gets rendered
2) Stepping away from it makes that hole visible again
3) Destroying the block directly to the right of it fixes the problem as the hole is no longer visible even from far away
4) Re-adding the block reintroduces the exact same problem. Tested with stone, cobblestone and dirt blocks.

### Attachments
![2020-11-07_22 57 08](https://user-images.githubusercontent.com/74119394/98453257-70024380-2157-11eb-9e02-6df53c1d56e9.png)
https://www.mediafire.com/file/2p3gslzbpwccygh/My_own_world.zip/file

Here's the video explanation of the problem - https://streamable.com/995yas

### System Information
![2020-11-08_00 08 32](https://user-images.githubusercontent.com/74119394/98453259-798bab80-2157-11eb-8a1e-26524d80d8d7.png)

- Java Version: 1.8.0_271 64-bit
- CPU: 4900MQ
- GPU: GTX 680M SLI

**Comment by fsharpseven** [comment]
I'm pretty sure this is a problem with Minecraft's occlusion/chunk culling algorithm. See JellySquid's comment on #333, and the bug report on Minecraft's official issue tracker ([MC-70850](https://bugs.mojang.com/browse/MC-70850)).

**Comment by magneticflux-** [comment]
Sodium doesn't use the Minecraft culling algorithm afaik. This is where the Sodium chunk culling code lives:

- `1.16.x/next`: https://github.com/jellysquid3/sodium-fabric/tree/1.16.x/next/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/cull
- `1.16.x/stable`: https://github.com/jellysquid3/sodium-fabric/blob/1.16.x/stable/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/ChunkRenderManager.java#L102

**Comment by fsharpseven** [comment]
Yes, I am aware, but I phrased my comment poorly. As Jelly explained in the comment I referred to:
"Sodium already fixes a few problems in vanilla's chunk occlusion, but ultimately we'd want to replace occlusion culling all together with a faster and more aggressive algorithm."

Sorry for any confusion :).  Also, if I'm missing something, please let me know.

**Comment by jellysquid3** [comment]
Merging this into tracking issue #1898.
