### ISSUE TITLE
Fabric Rendering API...

### ISSUE THREAD

**Issue by K0-RR** [jellysquid3/Sodium#389]
Please we are waiting for this API to be supported from ~March... I know it's rude to rush You but it feels like You don't care about this stuff and we can't play with certain mods (Campanion and Astromine for me). Maybe You can share some information about progress to cheer us up?

**Comment by WalkerKnapp** [comment]
This doesn't need to be its own issue, please just comment on #5 or in [the discord server](https://jellysquid.me/discord).

**Comment by LambdAurora** [comment]
The issue tracker is not really the place for question either.
