### ISSUE TITLE
Micro stuttering when generating/loading chunks

### ISSUE THREAD

**Issue by NjuuOwO** [jellysquid3/Sodium#391]
Edit: Baddly explained:

As you can see on screenshots, game microstutters when standing, or generating new chunks, or loading previously generated ones. I usually play on 24 render distance. Sometimes it's likely to be unplayable.
This same occurs for lower RDs like 2.

(These three screenshots were taken with all of three performance mods)
![image](https://user-images.githubusercontent.com/45913099/98833710-a59c7a80-243e-11eb-8174-3cdba7b525b0.png)
![image](https://user-images.githubusercontent.com/45913099/98833745-adf4b580-243e-11eb-84e1-6b32ae4e5169.png)

Here you can see like 4ms stutter, when doing absolutely nothing. 
![image](https://user-images.githubusercontent.com/45913099/98836699-46d90000-2442-11eb-9ff9-c9eac59847a1.png)

Of course i tried:
-Different mod setups (Sodium+Lithium/Phosphor, Sodium only, Three of them only)
-Increasing, decreasing RAM allocated.

Mods i use: 
![image](https://user-images.githubusercontent.com/45913099/98833900-e1374480-243e-11eb-9afb-5f96c2ac2bf4.png)
[For the screenshot, i used only JellySquid's ones]

**Comment by NjuuOwO** [comment]
Hmm?

**Comment by mrmangohands** [comment]
For individual support inquires please join our discord https://jellysquid.me/discord
