### ISSUE TITLE
Skybox doesn't render properly when GUI is hidden on Fabulous! graphics setting

### ISSUE THREAD

**Issue by MilkyPL** [jellysquid3/Sodium#395]
### Expected Behavior
The sky should look the same regardless of GUI state

### Actual Behavior
After hiding the GUI, the gradient on the sky disappears.

### Reproduction Steps
1. Set graphics quality to "Fabulous!"
2. Look at the horizon
3. Press F1 to hide the GUI

### Attachments
![2020-11-19_16 11 11](https://user-images.githubusercontent.com/20266576/99685345-c7bb7b80-2a82-11eb-9cce-be97aa2fa52a.png)
![2020-11-19_16 11 15](https://user-images.githubusercontent.com/20266576/99685365-cdb15c80-2a82-11eb-8480-6cf3e23d3d78.png)

### System Information
![2020-11-19_16 19 03](https://user-images.githubusercontent.com/20266576/99685536-fc2f3780-2a82-11eb-9465-b49e5de21254.png)

**Comment by MeeniMc** [comment]
Can't replicate (as of 0.4.10), probably resolved.
