### ISSUE TITLE
Vines are blue instead of green

### ISSUE THREAD

**Issue by dawidpotocki** [jellysquid3/Sodium#399]
### Expected Behavior
Vines should be green

### Actual Behavior
Vines are blue

### Reproduction Steps

1. Generate a new world with `447902` seed
2. `/tp @a -2210.7 92 3923`
3. Vine is blue

### Attachments
![image](https://user-images.githubusercontent.com/38681822/99869040-e1002b80-2c2c-11eb-87b0-4615c00afdf3.png)
![image](https://user-images.githubusercontent.com/38681822/99869165-afd42b00-2c2d-11eb-925d-d72327950712.png)

### System Information

- Java Version: OpenJDK 11.0.9
- CPU: Intel Core i5-8250U
- GPU: Intel UHD Graphics 620

**Comment by dbl7id** [comment]
This issue seems to have already been fixed in the latest commit from the [1.16.x/dev](https://github.com/jellysquid3/sodium-fabric/tree/1.16.x/dev) branch, although I don't know which one exactly.

**Comment by dbl7id** [comment]
Using the latest sodium snapshot that jelly provided in her discord, this issue no longer exists.

**Comment by dawidpotocki** [comment]
Thanks, I just tried that snapshot and indeed it's fixed, I guess I will close the issue?
