### ISSUE TITLE
Please make sodium for 1.12.2

### ISSUE THREAD

**Issue by Itssunnyk8** [jellysquid3/Sodium#406]
I have been playing on 1.12.2 servers lately and chests/hoppers can get very laggy but sodium fixes it the problem is there is no sodium for 1.12 so if u can please

**Comment by Octol1ttle** [comment]
**Will you port to Minecraft 1.15 and older? What about Minecraft 1.8.9?** No. Sodium is a modern mod designed for modern versions of Minecraft. Please stop asking.

**Comment by maityyy** [comment]
There is no Fabric Loader on this version and this version of the game has a completely different code, so this is almost a new mod. There is no motivation to do this hard work again, the more it is not paid for.
