### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by Batavay** [jellysquid3/Sodium#407]
### Expected Behavior
I expected the world to work normally

### Actual Behavior
But I create a world and after a few seconds the world breaks and textures are buggy

### Reproduction Steps
Just go into the world and wait a few seconds

### Attachments
Screenshot: 
![2020-11-26_19 27 04](https://user-images.githubusercontent.com/75087662/100374704-ba236a00-301d-11eb-8fa9-1f9fd0094e4d.png)

### System Information
- Java Version: [1.8.0_271]
- CPU: [i3 3217U ]
- GPU: [First: Intel HD Graphics 4000 Second: AMD Radeon HD 7670M]

**Comment by FlashyReese** [comment]
If you can join Jelly's [Discord](https://jellysquid.me/discord), we can assist you in #support channel. This is a known bug with Sodium 0.1.0. There is a fix for this in form of a snapshot in the discord server.

**Comment by amnotbananaama** [comment]
As said above this is a duplicate issue, please join the discord for more specific support
