### ISSUE TITLE
Exp orb's color too dark.

### ISSUE THREAD

**Issue by Lincutt** [jellysquid3/Sodium#409]
### Expected Behavior
Exp orb's color should be light green.

### Actual Behavior
Exp orb's color is dark green in sodium.

### Reproduction Steps
kill any monsters in game.

### Attachments
vanilla
![2020-11-29_01 50 19](https://user-images.githubusercontent.com/6499183/100523654-ffe25d00-31ec-11eb-8758-53053a65aa57.png)

sodium
![2020-11-29_01 57 52](https://user-images.githubusercontent.com/6499183/100523661-0bce1f00-31ed-11eb-9b56-23eb19b75bb7.png)

### System Information
- Java Version: [ 15.0.1 hotspot ]
- CPU: [ i7-5557U ]
- GPU: [ iris 6100 ]

**Comment by amnotbananaama** [comment]
Can you provide a link to the resource pack you are using please?

**Comment by Lincutt** [comment]
> Can you provide a link to the resource pack you are using please?

the resource pack is Mice Blocks A12.2
[https://miceblocks.github.io/](url)

but even use the default resource pack, the result is the same.

loaded mods:

*Sodium v0.1
Phosphor v0.6b7
Lithium v0.6 (2No2Name fork)
Hopper Optimizations v0.3
Carpet v1.4.19
Dynamic FPS v1.2.1
FastFurnace v2.3
LambDynamicLights v1.3.2
OK Zoomer v4.0.1
Mod Menu v1.14.13b19

*the vanilla pic is just without Sodium.

**Comment by Testowy-Test** [comment]
Hi, it seems to be related with smooth lighting option, setting it to low fixes it for me.

**Comment by MeeniMc** [comment]
I remember having that, but can't replicate anymore with 0.4.10. Orbs look similar to Vanilla now. Issue resolved.
