### ISSUE TITLE
Large numbers of bubble particles behind glass are not rendered but still cause lag

### ISSUE THREAD

**Issue by eodomo** [jellysquid3/Sodium#410]
### Expected Behavior
Since bubbles are not rendered behind glass blocks, there should be no lag. The game does this by default.

### Actual Behavior
If there are a lot of bubble particles nearby, the particles are not rendered but the game still lags.

### Reproduction Steps
Place a lot of soul sand in water to make bubble columns, then place glass in front of you to hide the bubble particles.

Setting particle quality to Low is a workaround, but hides particles everywhere else in the game, as well.

### Attachments
https://imgur.com/a/vZYa6ry

Left image has Particle Quality set to Low, while right image has Particle Quality set to High

### System Information
- Java Version: 1.8.0_51 64bit
- CPU: 4x Intel Core i5-4460 @ 3.2GHz
- GPU: Radeon R9 290X

**Comment by NoComment1105** [comment]
I am unable to reproduce this on the latest commit (Particle quality high).
I was able to achieve this initially after creating these bubble collums but after a few moments it returned to normal
![2021-03-17_06 19 21](https://user-images.githubusercontent.com/67918617/111423811-b872d480-86e8-11eb-8718-c92e5348fbbe.png)
