### ISSUE TITLE
Running the mod changes my graphic card

### ISSUE THREAD

**Issue by LosY966** [jellysquid3/Sodium#411]
### Expected Behavior
I have two graphic cards in my PC (a laptop), and Intel one and a NVIDIA RTX. I allways play with my PC plugged, and when this happens, automatically the RTX starts running.
### Actual Behavior
 When using this mod, it changes to the Intel graphic card, so there is no performance improvement, that is what I wanted to have a look at.

### Reproduction Steps
1. I open Minecraft Launcher
2. Choose the Fabric Loader
3. Run the game
4. Run my world
5. Still fluent, as spected, but using the wrong graphic card

### Attachments
![Captura de pantalla (29)](https://user-images.githubusercontent.com/75454944/101099149-8075d480-35c4-11eb-8919-7421128881f2.png)
![Captura de pantalla (30)](https://user-images.githubusercontent.com/75454944/101099174-88ce0f80-35c4-11eb-885b-660267947e83.png)
![Captura de pantalla (31)](https://user-images.githubusercontent.com/75454944/101099181-8bc90000-35c4-11eb-8369-9c1d1830b3c2.png)

All the versions of the mods and the launcher are the lates ones.
### System Information

- Java Version: [1.8.0_51]
- CPU: [Intel Core i7-8750H 2.20 GHz]
- GPU: [NVIDIA GeForce RTX 2060]

**Comment by yezhiyi9670** [comment]
It's not the mod's fault. Go to Settings > System > Display > Graphics Settings to select the GPU you prefer for Java.

**Comment by Teh404Gal** [comment]
the mod can't choose the graphics card set since the graphics driver is controlled by the os
try checking your os's settings or googling the how to set dgpu for a game in *os name*

**Comment by LosY966** [comment]
> the mod can't choose the graphics card set since the graphics driver is controlled by the os
> try checking your os's settings or googling the how to set dgpu for a game in _os name_

Thank you very much for your help

**Comment by LosY966** [comment]
> It's not the mod's fault. Go to Settings > System > Display > Graphics Settings to select the GPU you prefer for Java.

And thanks to you too

**Comment by skyrising** [comment]
This looks like https://github.com/FabricMC/fabric-loader/issues/280 (Nvidia has a list of games and Fabric changes the main class so Minecraft is no longer recognized)
