### ISSUE TITLE
3D Textures Incompatibility, or something like that

### ISSUE THREAD

**Issue by nando8660** [jellysquid3/Sodium#413]
### Expected Behavior
Well. There is a (Very pleasant) Resource Pack called Slight Depth. It has 3D furnaces. In vanilla, nothing much happens, except for a problem with the chains, that can be easily fixed, oh, wait, it's not about the problems with the resource pack. Ok. In vanilla, perfect, it works. 

### Actual Behavior
With Sodium, some block's lighting just becomes a mess. The furnace, dropper and dispenser, especially, they literally becomes a Dark World Possessed block. 

### Reproduction Steps
1. Download the Texture!! (Ya ya the link! https://github.com/domino54/slight-depth)
2. Download & Install Sodium!!! (So, we're in Sodium page, i think you guys need no link, right?)
3. Watch the Shadows Being take control of the furnaces in your world. Creepy.

### Attachments
The Shadows Being
![2020-12-05_21 48 38](https://user-images.githubusercontent.com/75550624/101268657-87c3ec00-3744-11eb-91c0-776a1fcf90f8.png)

Vanilla MC.
![2020-12-05_21 43 01](https://user-images.githubusercontent.com/75550624/101268660-9dd1ac80-3744-11eb-8563-7c062056bc08.png)

### System Information
This?
![image](https://user-images.githubusercontent.com/75550624/101268735-847d3000-3745-11eb-823c-fe5a228d5d7c.png)

- Java Version: [version 8, update 271 (build 1.8.0_271-b09)]
- CPU: [Sorry dude,]
- GPU: [idk]
This helps?
![image](https://user-images.githubusercontent.com/75550624/101268793-47fe0400-3746-11eb-94b5-5036c338ba3b.png)

![image](https://user-images.githubusercontent.com/75550624/101268795-4d5b4e80-3746-11eb-8444-3bbcfde9f90f.png)

I don't know if i should report this, but anyway, here it goes.

**Comment by amnotbananaama** [comment]
Thank you for the report, I believe what you're seeing is the same issue as what is reported in #226. I'm going to close this as a duplicate for now, you can follow that issue for updates on this bug.
