### ISSUE TITLE
guardian beam visual bug

### ISSUE THREAD

**Issue by lolcuslol** [jellysquid3/Sodium#415]
### Expected Behavior
Guardian beam is rendered as expected

### Actual Behavior
guardian beam is replaced by a line of bubbles

### Reproduction Steps
It happens only in some of my worlds and isn't connected to any datapack or mod because the only one i have installed is Sodium.
### Attachments

![2020-12-09_20 12 51](https://user-images.githubusercontent.com/75753130/101676120-06799b80-3a5b-11eb-9817-f9c0a533743a.png)

here is a screenshot of this glitch

**Comment by Teh404Gal** [comment]
are you using the 1.16.3 version of sodium or the discord #testers snapshot
since in the latter version 
i still see the lazer 
![2020-12-10_13 37 38](https://user-images.githubusercontent.com/62482190/101774103-efd05480-3aed-11eb-9679-e0ecc9a54e6f.png)
![2020-12-10_13 44 49](https://user-images.githubusercontent.com/62482190/101774152-feb70700-3aed-11eb-8c94-d2dd011381ab.png)

**Comment by Teh404Gal** [comment]
ignore the low fps im running the game on battery power

**Comment by lolcuslol** [comment]
Im using the 1.16.3 version from curseforge. But that can't be the problem because when i tried it in my other world it looked normal like in your screenshot. And that's why i think it's something world specific.

**Comment by Teh404Gal** [comment]
seems weird
its probably a world dependent bug
if you want you to, can send me the world or the seed for it in discord so i can check if my client also reacts the same
also last question but did you load this world in multiple version?

**Comment by lolcuslol** [comment]
Well the seed is 364819863 the world type is large biomes.
 and i can send you the world save but i dont know if discord can send files that big its about 1,1GB 
and yes i did load it in multiple versions it was originally generated in 1.16.1 but I'm not sure about that.

**Comment by Teh404Gal** [comment]
well it seems the seed its self isnt the issue
if you want you can send me the world but before you do that
click the edit button while in the world selection menu
click on optimize after a while it will finish then click make a backup
and then send me the world so i can examine it
MegaloStudio#7838

**Comment by Teh404Gal** [comment]
you can use google drive/ one drive/ nextcloud to send the world

**Comment by lolcuslol** [comment]
Ok I'll send you the google drive link as soon as i can 
And thanks for being so helpful I really appreciate it.

**Comment by mrgrim** [comment]
This is a vanilla bug related to world age: https://bugs.mojang.com/browse/MC-165595

**Comment by amnotbananaama** [comment]
Converting this issue to a feature request to fix a vanilla rendering bug. See [here](https://discord.com/channels/602796788608401408/754753337525534892/787005559697047563) for code analysis in the [discord](https://jellysquid.me/discord) (thanks to `AMereBagatelle` and `MrGrim`).

**Comment by amnotbananaama** [comment]
Closing, as the pull request to fix this issue was closed as not a good fit for Sodium
