### ISSUE TITLE
add connected textures 

### ISSUE THREAD

**Issue by Finoway** [jellysquid3/Sodium#417]
**Is your feature request related to a problem? Please describe.**
it's not a big problem but since sodium is not compatible with fabric render api which prevents to be able to find a mod that allows to do it. 

**Describe the solution you'd like**
add the connected textures compatibility on sodium.

**Additional context** 
I have a friend who would like to see to pass on fabric but he want shaders and connected textures with sodium so already have the connected textures it could allow him to make him want more (and I must say that every time I talk about sodium I get these two arguments)

thank you for reading and sorry for my English (I'm not English)

**Comment by ReperakDev** [comment]
Connected textures will never be added directly to Sodium because it is an optimization mod only. However, Sodium is fully compatible with connected textures resource packs, along with fabulous shaders.

**Comment by Finoway** [comment]
thanks for the answer @ReperakPro, I'll see to get to put everything because I see not but hey I will look when I have my computer with me

**Comment by mrmangohands** [comment]
Sodium does not support connected textures. There's another fabric mod that does, but they're currently incompatible because sodium doesn't support the fabric rendering api, see #5.

There are no plans to add this feature to sodium directly, but frapi support is on the roadmap for version 0.2.
