### ISSUE TITLE
Multiconnect integration - Blocks not rendering with protocol <1.13.2

### ISSUE THREAD

**Issue by CamperSamu** [jellysquid3/Sodium#42]
### Expected Behavior
The game world should load correctly (ignoring multiconnect issues with 1.11 and 1.10)

### Actual Behavior
No blocks are rendering/loaded when using any protocol version >1.13.2 via multiconnect mod

### Reproduction Steps
1. Install multiconnect mod
2. Join any server with any protocol version below 1.13.2
3. No blocks are rendered nor physical.

### Mod list
- Fabric API (v0.14.0 - build 371 - Minecraft 1.16.1 // v0.14.0 - build 317 - Minecraft 1.15.2)
- Multiconnect (v1.3.3 - Minecraft 1.16.1 // v1.2.9 - Minecraft 1.15.2)
- Sodium (Latest commits build 06/29/2020 - 1.16.1 // Latest commits build 06/29/2020 - 1.15.2)

### HW/SW Details
- Java Version: jdk-14.0.1
- CPU: AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
- GPU: NVIDIA GeForce GTX 1660 Ti

**Comment by jellysquid3** [comment]
Please upload a client log. The renderer is likely crashing.

**Comment by CamperSamu** [comment]
[latest.log](https://github.com/jellysquid3/sodium-fabric/files/4871868/latest.log)
I don't see any errors in the logs, probably is something different...
I tried to switch to different opengl versions too but it still doesn't work.

**Comment by Earthcomputer** [comment]
Fixed in the latest multiconnect release: 1.3.5

**Comment by jellysquid3** [comment]
The author of Multiconnect claims the issue has been fixed on their side, and as such, I'm going to go ahead with closing this issue. Please re-open it if you still experience issues after updating to the latest release of Multiconnect.
