### ISSUE TITLE
Ground texture of the iron bar is glitchy.

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#420]
### Expected Behavior
Texture of the iron bar should be look normal from any angle when placed on a block.

### Actual Behavior
When you place an iron bar on a block, its ground texture is not showing up right. If you look it from different angles, you can see that the iron bar's ground texture is intertwining with the top texture of the block it is on.

### Reproduction Steps
Just place an iron bar on an any solid block.

### Attachments
SODIUM
![1](https://user-images.githubusercontent.com/75926506/102007272-ab84c480-3d38-11eb-9f5b-00a6445ba3b5.png)
![2](https://user-images.githubusercontent.com/75926506/102007280-b6d7f000-3d38-11eb-817d-d16deefcf9c5.png)
VANILLA
![3](https://user-images.githubusercontent.com/75926506/102007285-c0615800-3d38-11eb-874d-d2b4dc66deda.png)
SODIUM SETTINGS
![4](https://user-images.githubusercontent.com/75926506/102007289-cc4d1a00-3d38-11eb-9015-d815fe916b30.png)

### System Information
- Java Version: [1.8.0_261 64bit]
- CPU: [Intel i3 4010U 1.70GHz]
- GPU: [Intel HD Graphics 4400]

**Comment by dbl7id** [comment]
This is an artifact caused by the Compact Vertex Format setting. If you hover over the toggle for it, it'll explain exactly why this happens.

**Comment by ghost** [comment]
> This is an artifact caused by the Compact Vertex Format setting. If you hover over the toggle for it, it'll explain exactly why this happens.

Thank you Dbl7id. That fixed the problem. I hope leaving Vertex Format won't kill that all good FPS boost :).
