### ISSUE TITLE
Do any of the optimization mods affect RNG?

### ISSUE THREAD

**Issue by xsrvmy** [jellysquid3/Sodium#421]
Not sure where to ask this. Is there anything in these mods (sodium, lithium, etc.) that could potentially have an impact on the RNG used for bartering or mob drops? Specifically, is there anything that optimizes away the creation of a new Random object every time a mob drops loot?

**Comment by dbl7id** [comment]
Non of Jelly's mods should modify or affect any sort of RNG. Their goal is to retain vanilla parity as much as possible, so if there's a chance that RNG was modified, that is a bug and should be reported in the appropriate issue tracker, i. e, Lithium's.

**Comment by jellysquid3** [comment]
No, there is zero chance of Sodium changing game server behaviour (such as mob drops or world generation) as it only targets client-side code. The code is available to audit if you so desire.

**Comment by 2No2Name** [comment]
There is no optimization that reuses the random objects in lithium afaik. But there are changes to how mobs detect other mobs. For example when a mob tries to interact with the nearest mob that satisfies a condition, and there are two mobs with the exact same distance, with lithium installed, lithium code can choose the mob that vanilla doesn't choose.
