### ISSUE TITLE
Fix MC-173510

### ISSUE THREAD

**Issue by SnooComics9452** [jellysquid3/Sodium#423]
i just said it at title, only this

**Comment by Teh404Gal** [comment]
sodium is a rendering engine so no for this
and im pretty sure for lithium it needs to be bug compatible with minecraft
so close thread

**Comment by Dolphin2Point1** [comment]
I'd like to add on to what teh404guy said. This mod is not only a rendering engine, (which is client side only) but its only for 1.16.4. In 1.16.4 [this issue](https://bugs.mojang.com/browse/MC-173510) seems to be patched. I don't know about this but I don't think that someone's going to update 1.15.2, let alone fix a bug that is probably serverside in a clientside rendering mod.

**Comment by Teh404Gal** [comment]
well time for someone to close the thread

**Comment by Teh404Gal** [comment]
anyone wanna close this?

**Comment by SnooComics9452** [comment]
still not fixed in 20w49a

**Comment by jellysquid3** [comment]
This has nothing to do with the game's renderer. It looks to be some problem in server code since the client ends up waiting forever for it to respond.
