### ISSUE TITLE
block breaking animation bug

### ISSUE THREAD

**Issue by vHybridv** [jellysquid3/Sodium#424]
### Expected Behavior
Block break animation to work from all viewing angles.

### Actual Behavior
The block breaking animation does not appear when looking directly down.

### Reproduction Steps
Look directly down and mine a block. The block breaking animation will not appear.

- Java Version: Fabric 1.16.3
- CPU: i5-10300H
- GPU: RTX 2060

**Comment by amnotbananaama** [comment]
Duplicate of #232. This has been fixed but no release with the fix yet

**Comment by vHybridv** [comment]
ok thanks
