### ISSUE TITLE
Game crashing when switching servers, or rejoining the same server [Sodium's ''Next'' branch, version 0.1.1-SNAPSHOT}

### ISSUE THREAD

**Issue by VanillaSylv** [jellysquid3/Sodium#430]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

There are 2 ways to trigger this
A] Join a Minecraft server, leave, rejoin it and game crashes, 
B] Join a Minecraft server, leave, join a other server and game crashes

### Crash Report File
https://gist.github.com/CheesyTheArtist/34f90f4068612f718cedc5280059e0a1

### Additional Information
If needed, my specs are:
CPU: Intel i5-9300H
GPU: Nvidia GTX 1650 Mobile
RAM: 16GBs of DDR4

**Comment by Heitzenberg** [comment]
Known issue. This is the fix: https://github.com/jellysquid3/sodium-fabric/pull/428

**Comment by jellysquid3** [comment]
This should be fixed now.
