### ISSUE TITLE
Reimplement the option to change the fog type

### ISSUE THREAD

**Issue by cavallium** [jellysquid3/Sodium#434]
**Is your feature request related to a problem? Please describe.**
Minecraft allows you to disable fog. Sodium doesn't.

**Describe the solution you'd like**
ChunkFogMode.java has already the possibility to change the fog type, in getActiveMode().
Add an option to disable fog, so that if the option is true the function returns ChunkFogMode.NONE.

**Comment by jellysquid3** [comment]
What option in Minecraft allows you to disable fog?

**Comment by cavallium** [comment]
Sorry probably it was in OptiFine

**Comment by cavallium** [comment]
By the way, changing it to none seems to work well, so it can be implemented in Sodium.

**Comment by jellysquid3** [comment]
The point of this function is that if another mod calls `glDisable(GL11.GL_FOG)` (as effectively all other fog-disabling mods do) that the `getActiveMode()` function will see the state change and return `ChunkFogMode.NONE`. There is nothing for Sodium to implement here.
