### ISSUE TITLE
Minecraft crashes with exit code 6.

### ISSUE THREAD

**Issue by JustAMinecrafter** [jellysquid3/Sodium#437]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1. Open Minecraft Launcher with sodium mod of any release (curseforge or fvs4)
2. Open video settings, press Shift + P to go to the vallina settings and make it 24 bit fullscreen resolution.
3. Then press done.
4. Go to sodium video settings and turn off fullscreen.
5. Turn on fullscreen.
6. If it does not crash, repeat step 5 and 6 three more times.

### Crash Report File
Please upload your crash report as a file to [GitHub Gist](https://gist.github.com/) and replace this text with a link to the uploaded report.

### Additional Information
Provide any additional information or context which may be relevant to the issue. If you have none to add, you can remove this section.
The log should say process crashed with code 6.

**Comment by JustAMinecrafter** [comment]
this is the link to the logs for the error and crash.

**Comment by JustAMinecrafter** [comment]
https://gist.github.com/JustAMinecrafter/5133eee58e814d2c6f4283d74ce8b70e

**Comment by Teh404Gal** [comment]
can you try to do this with not-enough-crashes installed? since i cant read 100% of vanilla crashlogs and not-enough-crashes might show if sodium is the one crashing the game or not

**Comment by JustAMinecrafter** [comment]
Is it a mod?

**Comment by JustAMinecrafter** [comment]
Nvm

**Comment by JustAMinecrafter** [comment]
Need help i installed fabric resource loder but the not enough crashes says that u need to install it still.

**Comment by JustAMinecrafter** [comment]
Wait i think is because i never put in the api my bad

**Comment by JustAMinecrafter** [comment]
The logs appears to be the same

**Comment by JustAMinecrafter** [comment]
And when the game crashes, the game literally quits and i cant continue playing even with the mod, not enough crashes.

**Comment by JustAMinecrafter** [comment]
> can you try to do this with not-enough-crashes installed? since i cant read 100% of vanilla crashlogs and not-enough-crashes might show if sodium is the one crashing the game or not
Can u test it yourself, i cant seem to play onwards even with the not enough crashes mod.

**Comment by JustAMinecrafter** [comment]
wait there is a new crash

**Comment by JustAMinecrafter** [comment]
i cant seem to reproduce it

**Comment by JustAMinecrafter** [comment]
i just join the server and it just crashes

**Comment by JustAMinecrafter** [comment]
https://gist.github.com/JustAMinecrafter/379176df3ffd6904d8de0b2cb7914da8


New crash. No idea how to reproduce.

**Comment by Teh404Gal** [comment]
are you using the latest version on curseforge or the latest git commit?

**Comment by JustAMinecrafter** [comment]
For the fullscreen bug yes.

**Comment by JustAMinecrafter** [comment]
> https://gist.github.com/JustAMinecrafter/379176df3ffd6904d8de0b2cb7914da8
> 
> New crash. No idea how to reproduce.

But for this, it is the fvs4 sodium version.

**Comment by Teh404Gal** [comment]
fsv4? if its a fork then maybe repor the bug there

**Comment by JustAMinecrafter** [comment]
this is the new version for sodium. not a fork

**Comment by JustAMinecrafter** [comment]
it is from jellysquid
https://discord.com/channels/602796788608401408/778685768041627719/791048314224771082

**Comment by jellysquid3** [comment]
These builds aren't supported on this issue tracker. Use the official Discord server to report issues.
