### ISSUE TITLE
Visible chunks under water are being culled by Fog Occlusion

### ISSUE THREAD

**Issue by CalXee** [jellysquid3/Sodium#438]
### Expected Behavior
Chunks that are visible underwater or visible while blind are not culled, since they are visible.

### Actual Behavior
Chunks far enough away are culled, causing it to look strange underwater compared to with that option disabled.

### Reproduction Steps
1. Turn Fog Occlusion on
2. Go underwater and observe. Chunks far from the player are not rendered.
3. Turn Fog Occlusion off
4. Observe again. Chunks are rendered properly.

### Attachments
![2020-12-23_12 20 43](https://user-images.githubusercontent.com/68349758/103027162-5bb9b080-4523-11eb-9bb2-083366ec824f.png)
![2020-12-23_12 20 49](https://user-images.githubusercontent.com/68349758/103027165-5c524700-4523-11eb-9fce-703bd56f8547.png)

**Comment by FlashyReese** [comment]
From my observation, it does render in after a while. It seems to be culling due the fog distance being changed when underwater.

**Comment by CalXee** [comment]
@FlashyReese 
Probably because of this.
![Screenshot 2021-04-03 105738](https://user-images.githubusercontent.com/68349758/113482239-aeccc900-946b-11eb-868a-b642ce9a653b.png)
One of the features listed in the 1.13 patch notes.
