### ISSUE TITLE
Smooth sky colour transitions.

### ISSUE THREAD

**Issue by majikdev** [jellysquid3/Sodium#440]
**Is your feature request related to a problem? Please describe.**
When moving from one biome to another, the sky colour has no transition, instead it changes it's colour instantly. The jump in sky colour is especially noticeable between biomes with different sky colours, like an ocean and a desert.

**Describe the solution you'd like**
Implementation of smooth sky colour transitions, perhaps based on the already existing biome blending.

**Comment by ZtereoHYPE** [comment]
This is actually a 1.17 feature (see https://www.minecraft.net/article/minecraft-snapshot-20w46a) and I don’t think it’s in sodium’s scope to backport minecraft features.
