### ISSUE TITLE
1.17

### ISSUE THREAD

**Issue by sunias** [jellysquid3/Sodium#443]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LambdAurora** [comment]
Snapshots are not supported.

You might be able to find a fork that has support for Snapshots, but by using a fork you will not get any official support.

**Comment by rster2002** [comment]
Are you expecting to (eventually) port it to 1.17 when the update releases as the new update has an entirely new rendering engine.

**Comment by DragonEggBedrockBreaking** [comment]
Someone is currently working on a port to 1.17. You can check the official CaffeineMC discord for progress on this. There is no ETA for sodium support. https://jellysquid.me/discord

**Comment by jellysquid3** [comment]
@rster2002 Please see #674.
