### ISSUE TITLE
Server icons are textures from the game

### ISSUE THREAD

**Issue by Businessman381** [jellysquid3/Sodium#449]
### Actual Behavior
Server icons are displayed as random textures, but usually its white square (1st screenshot). One of them like merged inventory texture with server icon (2nd&3rd screenshots). Rarely my sun become a large white square (4th screenshot).

### Reproduction Steps
Provide information on how to reproduce this game crash. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear! If applicable, please provide a world file as a compressed ZIP which contains a minimally reproducible example of the issue. 

1. Add some servers (in my case my own server and pvplegacy)
2. Refresh the server list once
3. Enter multiplayer or singleplayer game
4. Back to the server list
5. Now server icon is white or random texture. Reload game for another try.

### Attachments
[1-2 refreshes](https://imgur.com/f7SsHyg)
[many refreshes](https://imgur.com/moyprjV)
[inventory after many of refreshes](https://imgur.com/KSMlPog)
[large white sun](https://imgur.com/4zIXGEY)
[mod list](https://imgur.com/EgQveW7)

### System Information
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: [JDK 14]
- CPU: [Intel Pentium G4560]
- GPU: [GeForce GT1030]

**Comment by CalXee** [comment]
Once the server icon for pvplegacy was my skin, and when I logged into pvplegacy my skin was the server icon! Other people see my skin as the server icon too.

**Comment by fsharpseven** [comment]
I'm pretty sure this is a vanilla issue. I tested it on vanilla 1.16.4 and the same thing happened. When I tested it in a dev environment, it throws the following errors:
`[Netty Client IO #20/ERROR] (Minecraft) Invalid server icon (unknown format)`
and `OpenGL debug message, id=1281, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_VALUE error generated. Invalid texture format.` This is likely a problem with pvplegacy's server icon or vanilla's processing of it and _probably_ not a sodium issue.

**Comment by krystejj** [comment]
Hey, I had the same problem in my case, it only happened with the mcraj.pl server, the server icon changed with some random texture each time. BUT once SUN texture turned with texture of the server.
![unknown](https://user-images.githubusercontent.com/79933707/109763821-f3f2a680-7bf2-11eb-8875-8e26c3903f01.png)
Sorry for my bad english, but i am from Poland :)

**Comment by krystejj** [comment]
I forgot to add that only the server texture changed on the server list, but the sun texture was different on each server and always the same, i.e. the mcraj.pl server icon

**Comment by jellysquid3** [comment]
To my knowledge, this is a vanilla issue. But we made some changes in Sodium 0.2 to hopefully fix this. If you're still experiencing the problem, please ask for this issue to be re-opened.

**Comment by subatomic-olive** [comment]
I am still experiencing this with sodium installed.

btw here is a bug report for it [MC-229526](https://bugs.mojang.com/browse/MC-229526?attachmentSortBy=dateTime).
it is marked as a duplicate of a bigger problem
