### ISSUE TITLE
minecraft crashes when playing singleplayer and multiplayer

### ISSUE THREAD

**Issue by idkAboutLife** [jellysquid3/Sodium#455]
it used to work but it crashes suddenly

**Comment by amnotbananaama** [comment]
@idkAboutLife, it looks like you are new to GitHub, so I am trying to be patient but please do not submit one line issues like this. They don’t provide us with any information, and the issue trackers is not a support site. I would suggest joining [our official Discord server](https://jellysquid.me/discord) where we can help you better.

**Comment by idkAboutLife** [comment]
the sodium mod before was not crashing minecraft, but until yesterday while changing some settings, and when i click it it shows nothing and leaving the screen with "saving world".

tried to delete all mods but still crashes with sodium.   I hope this provides some information.

**Comment by idkAboutLife** [comment]
umm so i tried uninstall java and then re-downloading it and it worked so the issue is fixed.
