### ISSUE TITLE
Worse FPS than Vanilla

### ISSUE THREAD

**Issue by Brisebob** [jellysquid3/Sodium#457]
### Expected Behavior
Using other peoples benchmarks, I expected my system to run at a very high framerate. My system uses and Ryzen 5 3600 and an RX 5700 so it's pretty good.

### Actual Behavior
Instead, I lose around 30-50 fps (from 100 to 70 or 50). I have messed around in the video settings but nothing has been able ot raise my fps above 80 with sodium. Could this just be sodium doesn't work well with my system?

### Reproduction Steps
I am using a fresh fabric install and Sodium is the only thing installed. I have tried it with the fabric API and without.
### System Information

- Java Version: 1.8.0_251
- CPU: Ryzen 5 3600
- GPU: RX 5700

**Comment by amnotbananaama** [comment]
This is not the typical experience with Sodium, but results are obviously hardware and configuration dependent. This is ultimately a support issue, and GitHub issue trackers are not well-designed for lengthy conversations. Please join [our official Discord server](https://jellysquid.me/discord), and paste an Alt + F3 screenshot in the `#mod-support` channel.
