### ISSUE TITLE
Only animate visible textures not animating any textures when enabled

### ISSUE THREAD

**Issue by QPCrummer** [jellysquid3/Sodium#458]
### Expected Behavior
All visible textures should be animated

### Actual Behavior
No textures are animated.

### Reproduction Steps
Turn on Only Animate Visible Textures. Look at a block that has an animated texture (water or lava). Note, the only way to fix this (without coding) is to disable it in the settings. To be honest, there wasn't any performance impact when disabling it.

### Attachments
I am using the latest Next release from Github. d352852 to be exact.

### System Information
- Java Version: [15.0.1 ]
- CPU: [AMD FX 8350]
- GPU: [AMD Radeon RX 480]

**Comment by QPCrummer** [comment]
Here is a list of all mods I have: BBOR, Fabric API, Fabric Carpet, Hydrogen, Krypton, litematica, lithium, logical_zoom, malilib, mini-hud, replay mod, simpleAuth, sodium, starlight, tic-tacs, tweakaroo.

Antoher Note: I have tested with only sodium and it still happens.

**Comment by ImperatorStorm** [comment]
known issue

**Comment by Chaos02** [comment]
Still having this issue, this is my (relevant) mod list:


- Magnesium/Rubidium Dynamic Lights
Anthxny
dynamiclightsreforged-1.18.2_v1.3.3.jar

- Magnesium/Rubidium Extras
Anthxny
rubidium_extras-1.18.2_v1.3.2.jar

- Rubidium
Asek3
rubidium-0.5.6.jar

- Rubidium Extra
dimadencep
rubidium-extra-0.4.18+mc1.18.2-build.86.jar

- TexTrue's Rubidium Options
TexTrue
TextruesRubidiumOptions-1.0.5-mc1.18.2.jar

**Comment by pajicadvance** [comment]
We don't have anything to do with Rubidium. Report the issue to their own issue tracker.

**Comment by Chaos02** [comment]
ohh god damnit, completely missed the repo name, my bad!!
