### ISSUE TITLE
Crashing after startup while using 1.16/next version

### ISSUE THREAD

**Issue by Blobanium** [jellysquid3/Sodium#459]
### Reproduction Steps
1. Use the latest version of the Sodium (More precisely the 1.16/Next Branch)
2.  Start the game and Minecraft loads
3.  crashes

Video On How i reproduced
https://user-images.githubusercontent.com/45613796/103393780-77035d80-4ad9-11eb-88d5-122c4a48be02.mp4

### Crash Report File
[crash-2020-12-30_19.35.56-client.txt](https://github.com/jellysquid3/sodium-fabric/files/5756393/crash-2020-12-30_19.35.56-client.txt)

### Additional Information
Did test with just Sodium installed so it doesn't seem that there is something conflicting with the mod

GPU: AMD RX 570 by XFX (Radeon Driver 20.12.1)

Not Enough Crashes Seems to catch this crash, but kind of fails and causes it to spam the crash log folder and makes the game unresponsive. Here's a zip file containing those spammed crash logs (if u need it)
[Crash Spam logs.zip](https://github.com/jellysquid3/sodium-fabric/files/5756403/Crash.Spam.logs.zip)

tell me if there's anything else I need thanks

**Comment by jellysquid3** [comment]
Caused by #16. You're compiling from source and are using too new a version of Java.
