### ISSUE TITLE
Connected textures

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#463]
long story short sodium is not compatible with optifabric and i want connected textures
you could add connected textures to sodium to fix it as thats what i want to use optifabric for

**Comment by amnotbananaama** [comment]
Sodium itself will not be adding connected textures, but when #5 is fixed Sodium will be compatible with other mods with that functionality. (For example, [Connected Block Textures](https://github.com/Nuclearfarts/connected-block-textures)).

**Comment by itsbumble** [comment]
will sodium be compatible with optifabric ?

**Comment by ghost** [comment]
> Sodium itself will not be adding connected textures, but when #5 is fixed Sodium will be compatible with other mods with that functionality. (For example, [Connected Block Textures](https://github.com/Nuclearfarts/connected-block-textures)).

will sodium be compatible with OptiFabric ever?

**Comment by ImperatorStorm** [comment]
Sodium is inherently incompatible with Optifine and Optifabric

so, no

**Comment by ghost** [comment]
> Sodium is inherently incompatible with Optifine and Optifabric
> 
> so, no

adding support for optifine capes would be cool, thats what i miss the most

**Comment by ImperatorStorm** [comment]
that would be completely impossible and likely illegal
