### ISSUE TITLE
Can't change resolution for fullscreen

### ISSUE THREAD

**Issue by WinterIsPretty** [jellysquid3/Sodium#464]
### Expected Behavior
Visual Settings then change the resolution for fullscreen

### Actual Behavior
I'm stuck at 720x576 because that is what I use for normal Minecraft to keep fps

### Reproduction Steps
1. put mod in folder
2. open minecraft
3. no settings

### Attachments
![2021-01-01_18 06 39](https://user-images.githubusercontent.com/52920930/103448238-3849e080-4c5c-11eb-8f08-437da885d6d2.png)

### System Information

- Java Version: 1.16.4
- CPU: Intel Core i5-3470
- GPU: none

**Comment by amnotbananaama** [comment]
Duplicate of #46 

Use `Shift + P` in "Video Settings" as a workaround.

**Comment by WinterIsPretty** [comment]
I swear I looked at every post to make sure I was the only one

**Comment by ghost** [comment]
It doesn't work at all though. I set my resolution to the lowest 640x480, but the game is clearly being drawn using every single pixel on my screen, and uses the proportional GPU resources for that
