### ISSUE TITLE
When looking through the glass, the image of the water is wrong and there are obvious areas.

### ISSUE THREAD

**Issue by win2ter** [jellysquid3/Sodium#465]
### Expected Behavior
The water in the glass swimming pool should be coherent and integrated

### Actual Behavior
When I looking the pool by through the glass, the water image is wrong. 
Also, the water is split into obvious water surface.
This situation only appears in the sodium mod.
This situation may affect the viewing of swimming pools, aquariums and other building with water.

### Reproduction Steps
Just an example
1. Build a 3 height X 18 width glass swimming pool on multiple large bricks
2. Observing the pool through the glass, the integrity of the water is obviously separated by the chunks.

### Attachments
with sodium
![这里写图片描述](https://github.com/hxhwing0522/public/blob/main/image/1.png?raw=true)

with sodium (Chunk line)
![这里写图片描述](https://github.com/hxhwing0522/public/blob/main/image/2.png?raw=true)

no sodium
![这里写图片描述](https://github.com/hxhwing0522/public/blob/main/image/3.png?raw=true)

### System Information

- Java Version: [8]
- CPU: [G4560]
- GPU: [R7 240]

**Comment by Heitzenberg** [comment]
Known issue: https://github.com/jellysquid3/sodium-fabric/issues/38
