### ISSUE TITLE
My textures are weird or my GPU is dying idk tbh

### ISSUE THREAD

**Issue by nonetrix** [jellysquid3/Sodium#467]
### Expected Behavior
no weird textures

### Actual Behavior
weird textures

### Reproduction Steps
1. download a 512x512 texture pack
2. find a texture that's has the bug since not all of them do
3. go close to it since it seems to only happen when you are close to the block

### Attachments
https://imgur.com/a/rEDfIWB

### System Information
gtx 1080
AMD Ryzen 7 3700X
32065MiB of ram

- Java Version: [8]
- CPU: [AMD Ryzen 7 3700X]
- GPU: [gtx 1080]

**Comment by nonetrix** [comment]
Could be my vram committing die but doom eternal a game that uses like all my vram does not have this

**Comment by ReperakDev** [comment]
Could you confirm if this is a Sodium issue by checking if this happens in vanilla? Your issue is not very helpful.

**Comment by nonetrix** [comment]
it is the same seems to be a minecraft thing sorry I'm running the proprietary nvidia drivers as well tho
