### ISSUE TITLE
no fps improvement

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#468]
### Expected Behavior
improvement of my fps

### Actual Behavior
still around 80 fps

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.
![2021-01-05_16 16 34](https://user-images.githubusercontent.com/77013163/103665053-40af5d80-4f73-11eb-98c0-1cd8d18ef1a9.png)

**Comment by ReperakDev** [comment]
When you mention that you have no FPS improvement, what are you comparing it to? Vanilla or OptiFine? Please provide screenshots of what you are comparing it to.

**Comment by jellysquid3** [comment]
This isn't a valid bug report. Use the [Discord server](https://jellysquid.me/discord) for support.
