### ISSUE TITLE
Minecraft Versions

### ISSUE THREAD

**Issue by Diffir** [jellysquid3/Sodium#470]
I Wanna ask which versions of minecraft can this be used with this mod, only the latest version or what?

**Comment by silversquirl** [comment]
The latest stable version supports 1.16.2, 1.16.3 and 1.16.4. There is also a 1.16.1 version that shouldn't be any different.

**Comment by jellysquid3** [comment]
This issue tracker is not for questions (please use the [official Discord server for them](https://jellysquid.me/discord).) The latest releases and what versions they're compatible with can be found on both CurseForge's files section and the GitHub releases page on this repository.
