### ISSUE TITLE
when playing with modern industrialization, your mod make a lot of the items  pink with black squares

### ISSUE THREAD

**Issue by rafaelf20l** [jellysquid3/Sodium#473]
### Expected Behavior
the texture should be a pipe

### Actual Behavior
the texture is buggy

### Reproduction Steps
you just need to play sodium + modern industrialization

**Comment by ReperakDev** [comment]
Sodium does not yet support the Fabric Rendering API, which is used to create the pipe models.

**Comment by rafaelf20l** [comment]
> Sodium does not yet support the Fabric Rendering API, which is used to create the pipe models.

Ok thanks, i don't have enough hardware to play a modpack without sodium, so even in this way i wil use it lol

**Comment by amnotbananaama** [comment]
Closing as a duplicate of #5
