### ISSUE TITLE
Add support for resolution scaling

### ISSUE THREAD

**Issue by Uncle-Wade** [jellysquid3/Sodium#478]
Sodium does not have resolution scaling options in windowed mode (or fullscreen AFAIK)
I have a Macbook with a 1440p screen and integrated graphics, and need a way to turn down the render scale so that I'm not playing on a powerpoint slideshow.

In optifine you could just open the shaders menu, click internal, and set the render quality to 0.5x. Sodium has no such option
pls add

bonus points if the fix actually works with other mods that do rendering stuff (ESP, Chams, outlines, glow)

**Comment by ReperakDev** [comment]
This is an advanced graphics setting, which is not in the scope of Sodium, however you're in luck. RetiNO (https://www.curseforge.com/minecraft/mc-mods/retino) halves the resolution on retina Macs.
