### ISSUE TITLE
Water does not render

### ISSUE THREAD

**Issue by acorn5s** [jellysquid3/Sodium#480]
### Expected Behavior
Water should be normally visible whilst in-game

### Actual Behavior
Water isn't normally visible

Water has weird visibility issues

- Java Version: [Version 8 update 251
- CPU: i5 3320m
- GPU: Intel hd graphics 4000

![2021-01-16_14 23 23](https://user-images.githubusercontent.com/77536834/104813204-ff873b00-5807-11eb-82e1-00d195980f81.png)
![2021-01-16_14 23 24](https://user-images.githubusercontent.com/77536834/104813207-02822b80-5808-11eb-9aac-b1340394ab58.png)

**Comment by CalXee** [comment]
You have an iGPU, try disabling Multidraw 4.3.

**Comment by acorn5s** [comment]
Y

**Comment by acorn5s** [comment]
Yeah, it works when i change the renderer to oneshot 3.0
