### ISSUE TITLE
Is the multinational translation not updated yet?

### ISSUE THREAD

**Issue by luluxiaoyu** [jellysquid3/Sodium#482]
I saw on the onekey website that simplified Chinese has been translated
But why is it displayed in English when I use the game?

**Comment by amnotbananaama** [comment]
As you have said, many language translations are fully approved and complete. Translation support was added a while back on [the old development branch](https://github.com/jellysquid3/sodium-fabric/tree/1.16.x/dev), and if you were to place the `zh_cn.json` file from OneSky inside those builds it would display in Simplified Chinese.

Translation support is something that has yet to be added to the newer releases of Sodium. All I can do is to refer you back to the original issue, and ask for patience
