### ISSUE TITLE
Mod confilct with OptiFabric Mod. 

### ISSUE THREAD

**Issue by Triheron** [jellysquid3/Sodium#483]
Error:
```
Found conflicting mods: sodium conflicts with {optifabric @ [*]}
    Creating Empty clause ?

```
Could you fix it?

**Comment by dbl7id** [comment]
Optifine and sodium will never work together.
Both mods change how the game renders so they conflict with each other.

**Comment by LambdAurora** [comment]
Optifine and Sodium both replace the game renderer, they can't work together at all.

Also duplicate of #132.

**Comment by msufyany** [comment]
Can you make sodium and optifabric? Or texture pack
