### ISSUE TITLE
Water and Glass

### ISSUE THREAD

**Issue by linuzzx** [jellysquid3/Sodium#484]
If you place glass in water at some angles it's invisible

### Expected Behavior
You should see the glass.

### Actual Behavior
You can't see the glass

### Reproduction Steps
place a glass column in an ocean

### System Information
- Java Version: Build 1.8.0_271-b09
- CPU: AMD_A9-9425_RADEON_R5__5_COMPUTE_CORES_2C+3G
- Graphics Card: AMD Radeon(TM) R5 Graphics

**Comment by amnotbananaama** [comment]
Duplicate of #38
