### ISSUE TITLE
Improve performance of text and toolbar

### ISSUE THREAD

**Issue by xhmr** [jellysquid3/Sodium#487]
**Is your feature request related to a problem? Please describe.**
Please improve performance of text rendering: chat, scoreboard, nicknames above players, holograms, toolbar and maybe bossbar. They take a lot of fps.

**Comment by amnotbananaama** [comment]
You already made an issue about this, closing as a duplicate of #382

**Comment by xhmr** [comment]
@amnotbananaama ye, nothing changed since november...
