### ISSUE TITLE
Blocks which emit light are brighter

### ISSUE THREAD

**Issue by vichvich4444** [jellysquid3/Sodium#49]
It's looks nice, but I'll consider it a bug anyway. Doors are also affected
![2020-07-01_19 37 05](https://user-images.githubusercontent.com/26071899/86269584-409c6280-bbca-11ea-9662-4c078e95d3ff.png)

**Comment by jellysquid3** [comment]
Issue was fixed with https://github.com/jellysquid3/sodium-fabric/commit/e8d17ee8997658a415b1fbe933700b0eb9193c7b. I will be uploading a release candidate later today. If you are building from source, update your build.
