### ISSUE TITLE
Incredibly weird rendering issues

### ISSUE THREAD

**Issue by redstonerti** [jellysquid3/Sodium#491]
I took massive screenshots so you can see more clearly what the issues are because they are very small. The reason i would like this to be fixed is because a) it's a bug caused by your mod and b) this severely damages big screenshots. I am 100% certain that this is caused only by sodium as i have tried and tested with and without it. None of these issues are present without sodium.

Proof and problem 1:
Here are some trees with sodium
![image](https://user-images.githubusercontent.com/48157961/105578815-85b4fb80-5d8b-11eb-9105-0c6713778a05.png)
Here are some trees without sodium
![image](https://user-images.githubusercontent.com/48157961/105578821-8fd6fa00-5d8b-11eb-8a0f-50f21e607cca.png)
All other settings are the same.

Problem 2: blocks overlapping other blocks
![image](https://user-images.githubusercontent.com/48157961/105578873-dfb5c100-5d8b-11eb-8639-5a094384e427.png)

Problem 3: cuts and seams everywhere and the edges of blocks are visible where they shouldn't be
![image](https://user-images.githubusercontent.com/48157961/105578912-24d9f300-5d8c-11eb-93fe-938c60c41f3d.png)
you can see it here as well
![image](https://user-images.githubusercontent.com/48157961/105578949-5ce13600-5d8c-11eb-823f-67e82511f6e8.png)
and this is just a mess
![image](https://user-images.githubusercontent.com/48157961/105579019-826e3f80-5d8c-11eb-859a-75c52388eb39.png)

**Don't interpret this as an attack on your mod. I think it is an amazing mod and you are a treasure to the modding community but nonetheless, issues can't be ignored**

If you want to explore around the screenshot and see them for yourself, you can use this one, which i uploaded to gigapan
http://www.gigapan.org/gigapans/224366

Finally, these are the mods i used
![image](https://user-images.githubusercontent.com/48157961/105579030-90bc5b80-5d8c-11eb-92db-274d472e9608.png)

If you want to replicate this yourself:
download my mods from here: https://files.fm/u/qm6866k7b        (falling tree isn't included)
set your render distance to 64
set fabrishot's screenshot resolution to 16,000 x 16,000 from the mod menu (you can still see it with 8,000 x 8,000 so you can do that if you don't have enough vram)
generate a new world and go to x: 0.0 y: 1320 z:0.0
look down so that your that your facing direction in F3 is (-0.0 or 0.0 / 90.0)
and press F9

(The problems are still visible with a normal 1080p minecraft screenshot but they are very hard to spot)

my system's specs:
Minecraft: 1.16.4
Java Version: java 8
CPU: i7-7700k @4.00GHz
GPU: GTX 1070ti (6GB vram)
RAM: 32GB DDR4
On windows 10

**Comment by Kroppeb** [comment]
Mmh, maybe this is an issue with depth buffer precision?

**Comment by redstonerti** [comment]
If it is, please use java.math.BigDecimal if you're already using double and it would be nice even if you're using float just to future proof it. I don't think it would have THAT big of a performance impact. But i'm not an expert so i wouldn't know for sure
(Also, could we get a small patch just with this because if it really is as simple as changing the data type of a number it would be nice to have a fast fix? No pressure though)

**Comment by jellysquid3** [comment]
You're being rather presumptuous here based on someone else's guesses. There are almost no places in Sodium where a BigDecimal type would make sense, and they're beyond slow in comparison to any native floating point type...

Does this issue go away if you disable "Use Compact Vertex Format" or change the renderer backend to "OpenGL 3.0" in Video Settings > Advanced?

**Comment by redstonerti** [comment]
> You're being rather presumptuous here based on someone else's guesses. There are almost no places in Sodium where a BigDecimal type would make sense, and they're beyond slow in comparison to any native floating point type...

I'm sorry if you got mad at that, am just trying to be as helpful as possible ¯\\_(ツ)_/¯ I didn't know they had such a performance impact

> Does this issue go away if you disable "Use Compact Vertex Format" or change the renderer backend to "OpenGL 3.0" in Video Settings > Advanced?

No, it doesn't. I tried both at the same time, only the first and only the second solution but nothing worked. They didn't change anything

**Comment by redstonerti** [comment]
Any breakthroughs?

**Comment by Genau6502** [comment]
@redstonerti you have forge mods in your mods folder, which isn't related but still

**Comment by redstonerti** [comment]
> @redstonerti you have forge mods in your mods folder, which isn't related but still

Yeah i know, i found out later when i was having a different issue.

**Comment by phiwijo** [comment]
@redstonerti how did you even get a render distance of 64? I'm just curios ..

**Comment by ryleu** [comment]
Are these visible while playing when you don't take a screenshot, or does it only show up when you take a high resolution screenshot with fabrishot?

**Comment by redstonerti** [comment]
> Are these visible while playing when you don't take a screenshot, or does it only show up when you take a high resolution screenshot with fabrishot?

Yes these are visible while playing even on a 1080p monitor

> @redstonerti how did you even get a render distance of 64? I'm just curios ..

starlight, sodium, hydrogen, lithium, tic tacs
(you need to set the json config of tic tacs to 64 and then press SHIFT + P in game to set the slider that high)

**Comment by ryleu** [comment]
> > @redstonerti how did you even get a render distance of 64? I'm just curios ..
> 
> starlight, sodium, hydrogen, lithium, tic tacs
> (you need to set the json config of tic tacs to 64 and then press SHIFT + P in game to set the slider that high)

Does this still happen with only sodium, lithium, starlight, and hydrogen? I'm trying to see whether it's an issue with sodium + tic tacs.

You might also want to try disabling the compact vertex format, because that causes similar issues for me occasionally.

**Comment by redstonerti** [comment]
> > > @redstonerti how did you even get a render distance of 64? I'm just curios ..
> > 
> > 
> > starlight, sodium, hydrogen, lithium, tic tacs
> > (you need to set the json config of tic tacs to 64 and then press SHIFT + P in game to set the slider that high)
> 
> Does this still happen with only sodium, lithium, starlight, and hydrogen? I'm trying to see whether it's an issue with sodium + tic tacs.
I've been playing for a while with sodium and without tic tacs and i can see it on a 1080p screen regularly. The trees look very dark when they are far away.
> You might also want to try disabling the compact vertex format, because that causes similar issues for me occasionally.
I already tried all the variations. Nothing seems to help. If you scroll up a bit, jellysquid already told me to try this

**Comment by MeeniMc** [comment]
This looks like the bug that is caused by tweaking the settings in the nvidia/amd control panel to force anisotropic. Probably an invalid report (also very old) .

**Comment by jellysquid3** [comment]
I don't think Sodium was ever at fault here, and this issue is too old to really diagnose further. If you are still running into this problem on the latest version of Sodium, then open a new issue.
