### ISSUE TITLE
game crash when i open any world or settings

### ISSUE THREAD

**Issue by EricElvin** [jellysquid3/Sodium#494]
game crash whenever i open any world or any resoure pack

**Comment by Kroppeb** [comment]
Could you provide a crash report or a log file?

**Comment by EricElvin** [comment]
[crash-2021-02-22_11.59.40-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6019900/crash-2021-02-22_11.59.40-client.txt)

this is the crash report i found
soo please get it fixxed because sodium is way better than optifine i need sodium so pls fix it soon

**Comment by amnotbananaama** [comment]
Duplicate of #219. You need to delete the `sodium-options.json` file. You can find them in the `.minecraft/config` directory
