### ISSUE TITLE
Weird Bug, Blocks Appearing

### ISSUE THREAD

**Issue by EliteTVyt** [jellysquid3/Sodium#496]
https://streamable.com/es8tl5

I am having this weird glitch where blocks are just showing up and other blocks aren't there that are and the ones popping up on my screen aren't actually there

**Comment by amnotbananaama** [comment]
Please use the issue template, it exists for a reason. This is a duplicate of either #179 or #24, you haven't given enough information to determine which. You can workaround this by going to `Options` -> `Video Settings` -> `Advanced` and setting "Chunk Renderer" to 3.0 or 2.1.
