### ISSUE TITLE
Missing shadows on grass path

### ISSUE THREAD

**Issue by vichvich4444** [jellysquid3/Sodium#50]
In vanilla shadow casts from a grass block
![2020-07-01_19 45 19](https://user-images.githubusercontent.com/26071899/86270491-9ae9f300-bbcb-11ea-8a39-82dd3c70d30f.jpg)

**Comment by jellysquid3** [comment]
This is not a bug, and Sodium won't be "fixing" it. Vanilla's smooth lighting engine is actually flawed here, producing overly dark edges on grass path blocks.

**Comment by muzikbike** [comment]
Gotta say I definitely preferred the dark effect vanilla adds, a shame this won't be coming to sodium.

**Comment by JimmyCushnie** [comment]
I agree, vanilla looks way better. I don't know on what basis @jellysquid3 is claiming that the vanilla behavior is unintended. Is there a ticket on the official MC bug tracker about it?

**Comment by amnotbananaama** [comment]
> I don't know on what basis **Jellysquid** is claiming that the vanilla behavior is unintended.

“**Vanilla's smooth lighting engine is actually flawed here, producing overly dark edges on grass path blocks.**” You can also read more [here](https://discord.com/channels/602796788608401408/651120262129123330/670840939547328514) on Jelly’s discord.

> Is there a ticket on the official MC bug tracker about  it?

https://bugs.mojang.com/browse/MC-64678

This is something Jelly has already marked as will not be fixed. You are welcome to fork the project under the license terms, but you won’t get anything else accomplished on this issue.

**Comment by JimmyCushnie** [comment]
My question was not about whether Sodium will implement the vanilla behavior, I was questioning the claim that the vanilla behavior is an error. According to the very link you provided, the vanilla behavior is as Mojang intends and not a bug.

**Comment by Kroppeb** [comment]
> My question was not about whether Sodium will implement the vanilla behavior, I was questioning the claim that the vanilla behavior is an error. According to the very link you provided, the vanilla behavior is as Mojang intends and not a bug.

Mojang often marks bugs that are "won't fix" as "works as intended" so you never really know.

**Comment by JimmyCushnie** [comment]
Citation needed 🤔

**Comment by muzikbike** [comment]
> Gotta say I definitely preferred the dark effect vanilla adds, a shame this won't be coming to sodium.

I've since found out that this is probably responsible for a different bug, which is much more unsightly visually: https://bugs.mojang.com/browse/MC-11783

My view on this has since been overturned.

**Comment by noxifoxi** [comment]
I've found [Rynnavinx/sodium-shadowy-path-blocks](https://github.com/Rynnavinx/sodium-shadowy-path-blocks), a Sodium Add-On which restores the vanilla look of path blocks, with advanced settings:
![2021-12-13_16 04 13](https://user-images.githubusercontent.com/293639/145836585-421fc108-8e61-4230-8780-57d1fab041a3.png)

@jellysquid3 I'm also pretty sure that this "flawed" rendering of the lighting engine is intended, as the dirt path literally looks the same on Bedrock Edition as it does in Vanilla Java. And Bedrock uses a different rendering engine.
