### ISSUE TITLE
Chunks fail to render if linux machine is suspended to ram then woken up. 

### ISSUE THREAD

**Issue by feliscatusmeows** [jellysquid3/Sodium#501]
### Expected Behavior
I should be able to see my lovely grass blocks and my wooden structure. 

### Actual Behavior
I see just some beds and entities and random intresting shapes. No grass or normal blocks unfortunately. It appears if I modify a chunk it renders properly again. 

### Reproduction Steps
1. Install linux(I am using xubuntu 20.04 LTS with kde plasma. don't judge)
2. pause the game
3. Suspend the machine to ram. 
4. Try to resume playing

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.
![2021-01-26_20 10 52](https://user-images.githubusercontent.com/29553771/105943382-fff8b080-6015-11eb-9155-7cda5a792702.png)
![2021-01-26_20 17 43](https://user-images.githubusercontent.com/29553771/105943395-04bd6480-6016-11eb-9733-44102821db2b.png)
![2021-01-26_20 20 55](https://user-images.githubusercontent.com/29553771/105943401-05ee9180-6016-11eb-98a4-af52726b086d.png)

### System Information

- Java Version: 1.8.0_275, using 64-bit architecture

- CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
- GPU: GeForce GTX 1650 Ti with the propitiatory nvidia drivers
- 
[latest.log](https://github.com/jellysquid3/sodium-fabric/files/5877740/latest.log)

**Comment by OrangeCatUnderscore** [comment]
I got this same issue when using Ctrl+Alt+F3 and Ctrl+Alt+F1 on pop os 20.10, hitting F3+T fixes it. Could be an nvidia driver bug.

**Comment by jellysquid3** [comment]
This tends to be a problem with the proprietary NVIDIA driver and most applications when waking from suspend, as it seemingly doesn't retain any video memory. [The Arch Linux wiki even has a section for it.](https://wiki.archlinux.org/index.php/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend)

**Comment by Redd56** [comment]
im judging you

**Comment by jellysquid3** [comment]
Closing as there isn't anything we can reasonably do to work around this. The NVIDIA drivers are just acting nasty, and there exists a workaround for users affected.
