### ISSUE TITLE
Firework particles do not render on the other side of a water boundary

### ISSUE THREAD

**Issue by Genau6502** [jellysquid3/Sodium#505]
### Expected Behavior
The particles should show on the other side of the water, but probably slightly tinted

### Actual Behavior
Hard to explain, here are two clips:

https://user-images.githubusercontent.com/66269211/106357621-1d23cc80-62ff-11eb-8203-eab8ec78e728.mp4

https://user-images.githubusercontent.com/66269211/106357622-201ebd00-62ff-11eb-8a04-e0b0e39832c8.mp4

These clips were with indium on, however I have tested without indium/CBT and the issue persists

### Reproduction Steps
Use the 1.16.x/next branch of sodium and set the renderer to Oneshot GL 3.0
Load a crossbow with exploding fireworks and fire at blocks underwater.

### Attachments
Linked above

### System Information

Using oneshot Gl 3.0 because multidraw is broken for intel GPUs on 1.16.x/next
- Java Version: AdoptOpenJDK 11
- CPU: Intel Core i5-1035G1
- GPU: Intel UHD for 10th gen processors
- OS: Windows 10

**Comment by fsharpseven** [comment]
This also occurs in vanilla, at least when I tested it.

**Comment by Genau6502** [comment]
If that's the case, I'll close
