### ISSUE TITLE
How to open Anisotropic filtering

### ISSUE THREAD

**Issue by KeremArslan1** [jellysquid3/Sodium#506]
Basically my game looks awful without the anisotropic filtering. I am currently using a NVIDIA RTX 2060 Mobile. Is there any way to use anisotropic filtering with sodium.
My game without anisotropic filtering:
[Link](https://i.imgur.com/NotMeWe.png)

**Comment by jellysquid3** [comment]
No, Sodium does not support AF right now.

This issue tracker is not intended for questions and/or support inquiries. The [official Discord server](https://jellysquid.me/discord) would be a better place to ask in the future.
