### ISSUE TITLE
Grass-Dirt transition on texture looks odd from specific angles

### ISSUE THREAD

**Issue by FewerFlaws** [jellysquid3/Sodium#507]
### Expected Behavior
The texture of grass blocks should appear the same from any angle.

### Actual Behavior
At some specific angle the texture on the side of grass blocks shifts to show a harsh transition from dark green to dirt.

### Reproduction Steps
1. Run Minecraft 1.16.5 with the latest version of Sodium.
2. Find a hill where lots of grass blocks are visible.
3. Move around while viewing the grass blocks a harsh angle.  Watch the part of the texture where the grass transitions to dirt.

### Attachments
![2021-01-31_20 48 30](https://user-images.githubusercontent.com/75643699/106416580-91956300-6406-11eb-8db9-992ce859ddb8.png)
Look at the grass-dirt transition on the grass blocks in the distance.  It's most visible above the center crosshair dot (and a little to the right).  This effect is very noticeable when moving because the dark oddity follows the camera.  [Here is a video](https://drive.google.com/file/d/1NiY0IhbnGe7EAk8mjVeM5WVo6VNL7bfU/view?usp=sharing) which may help.

### System Information
- Java Version: 1.8.0_271
- CPU: Intel Core i7 - 3770
- GPU: GeForce GTX 1060 6GB

**Comment by Snivine** [comment]
that's a mipmapping problem (can be seen as far away textures are smaller) can you check if it happens in vanilla as well?

**Comment by FewerFlaws** [comment]
Yes, it does seem to happen in vanilla.  Is it beyond the scope of Sodium to fix it then?  I'm not sure where the line is with rendering engines =]

**Comment by LucilleTea** [comment]
Being a vanilla issue makes this a feature request rather than a bug report.
I tend to reduce the issue by setting mipmapping to 3 instead of 4.

**Comment by Snivine** [comment]
> Being a vanilla issue makes this a feature request rather than a bug report.
> I tend to reduce the issue by setting mipmapping to 3 instead of 4.

this is a good idea actually, try reducing it to 3 or 2

**Comment by jellysquid3** [comment]
This is fixed in Sodium 0.5, which will be released in the near future.
