### ISSUE TITLE
Sodium Config (.properties) File Points To Unavailable Wiki Page

### ISSUE THREAD

**Issue by vividiris** [jellysquid3/Sodium#509]
Similar to the Lithium mod's config file, the Sodium config file tells viewers to go to "https://github.com/jellysquid3/sodium-fabric/wiki/Configuration-File" to see the avalible options to change. This wiki page is not currently visible to the public and I wanted to know if the page was hidden while it's being modified or if the comment is unnecessary and can be removed. Not a major issue, but would be useful for learning how to modify the mod's settings.

**Comment by vividiris** [comment]
This applied to the "sodium-mixins.properties" file and appears to be used in case users need to disable game-breaking features. I don't believe this needs resolved anymore.

**Comment by amnotbananaama** [comment]
Just wanted to link this to #196 as that is the underlying issue here
