### ISSUE TITLE
Insane world flickering with multidraw (GL 4.3)

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#510]
### Expected Behavior
Normal rendering

### Actual Behavior
Insane world flickering

### Reproduction Steps
Happens in any world or server when multidraw (GL 4.3) is used. Occurs in commit [a2b25d813f88c0a5aef4369bbd1620775789d20d ](https://github.com/jellysquid3/sodium-fabric/commit/a2b25d813f88c0a5aef4369bbd1620775789d20d) and later.

### Attachments
https://user-images.githubusercontent.com/78409751/106578451-5ec99880-64f4-11eb-925d-7fb9ecfdd373.mp4

### System Information

- Java Version: 15.0.2.7 (also occurs in bundled java runtime)
- CPU: Intel(R) Core(TM) i5-1035G4 CPU @ 1.10GHz (8 CPUs), ~1.5GHz
- GPU: Intel(R) Iris(R) Plus Graphics

**Comment by dbl7id** [comment]
Most likely related to the change in Multidraw code made to workaround this issue on AMD drivers.
The only fix for now is to change your chunk renderer in the Advanced tab to Oneshot(GL 3.0) from Multidraw(4.3).

**Comment by AlexPlay1** [comment]
That's the issue with intel graphics drivers (Multidraw(4.3) is not supported)
### **_Solution:_**
**Select renderer Oneshot (GL 3.0)**

**Comment by Genau6502** [comment]
#24
