### ISSUE TITLE
FPS Not improving, like vanilla but with less stuttering

### ISSUE THREAD

**Issue by stgrunkutsie** [jellysquid3/Sodium#511]
### Expected Behavior
FPS to improve in any manner

### Actual Behavior
FPS acting like vanilla Minecraft, Just less stuttering

### Reproduction Steps
I open the Minecraft Launcher, select fabric loader, hop into any world, see that the FPS didn't improve

### Attachments
https://imgur.com/7LAvsgL

### System Information
      Time of this report: 2/2/2021, 16:29:11
             Machine name: DESKTOP-6RV0H28
               Machine Id: {F950A428-912C-49D1-91D7-38D484FA3E8E}
         Operating System: Windows 10 Pro 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
                 Language: Italian (Regional Setting: Italian)
      System Manufacturer: System manufacturer
             System Model: System Product Name
                     BIOS: 4212 (type: UEFI)
                Processor: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 CPUs), ~2.7GHz
                   Memory: 16384MB RAM
      Available OS Memory: 16328MB RAM
                Page File: 14292MB used, 4466MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, with HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.0.8
           DxDiag Version: 10.00.19041.0546 64bit Unicode

- Java Version: [1.8.0_281 64bit]
- CPU: [Intel Core i5 6400 4core 2.70GHz]
- GPU: [Radeon RX580 8GB]

**Comment by SnooComics9452** [comment]
idk, it happends to semi bad pc
i use i5 4210m, intel hd 4600 also happend

**Comment by notsatvrn** [comment]
Issue is the renderer being used is OpenGL 3.0, try switching to OpenGL 4.3.

**Comment by amnotbananaama** [comment]
This is a support issue and ultimately not suited for an issue tracker. I encourage you to join [the official discord](https://jellysquid.me/discord) for targeted troubleshooting. Please share an Alt + F3 screenshot of larger size if you can, the debug text is somewhat difficult to make out.
