### ISSUE TITLE
Game crashes when main menu buttons should appear with Hydrogen

### ISSUE THREAD

**Issue by Lentern** [jellysquid3/Sodium#512]
### Expected Behavior
The game starts normally.

### Actual Behavior
Game crashes right when the main menu buttons are supposed to appear.

### Reproduction Steps
1) Add sodium 0.1.1 Snapshot & Hydrogen 0.2 Snapshot to mods folder
2) Start Minecraft 1.16.5 Fabric
3) Wait for the game to load, you will see that it crashes when the main menu buttons would appear

### System Information

- Java Version (MC): Bundled MC executable
- Java Version: Both AdoptOpenJDK 14.0.2.12 JDK & JRE
- CPU: Intel Core i7 9700F 3 GHz
- GPU: GeForce GTX 1650
- Fabric 0.9.0 Build 204
- Sodium 0.1.1 Snapshot

[crash-2021-02-02_11.43.32-client.txt](https://github.com/jellysquid3/sodium-fabric/files/5912854/crash-2021-02-02_11.43.32-client.txt)

**Comment by Lentern** [comment]
Accidentally used the "Bug" label instead of "Crash" whoops.

**Comment by ReperakDev** [comment]
Did you compile from source? If you compiled using Java 14, it will not run on Java 8, Minecraft's bundled version.

**Comment by Lentern** [comment]
> If you compiled using Java 14, it will not run on Java 8, Minecraft's bundled version.

Changing my Java Executable appears to fix this issue, thanks!
