### ISSUE TITLE
Probably chunk caching problem

### ISSUE THREAD

**Issue by Huwng** [jellysquid3/Sodium#52]
### Expected Behavior
The world should render as a normal minecraft playthrough would be

### Actual Behavior
When go above y level 60, the game freaks out and display a bunch of random blocks if it's day time, it stops freaking out in night time but water doesnt render

### Reproduction Steps
Just make a normal world then go above y level 60

### Attachments
![2020-07-02_20 27 18](https://user-images.githubusercontent.com/55024122/86368226-25535500-bca7-11ea-8690-cfbe957c04b0.png)
![2020-07-02_20 46 27](https://user-images.githubusercontent.com/55024122/86368235-27b5af00-bca7-11ea-80bd-f9f0a40cf409.png)
![2020-07-02_20 46 38](https://user-images.githubusercontent.com/55024122/86368245-2a180900-bca7-11ea-9e40-83a38400871b.png)
![2020-07-02_20 47 20](https://user-images.githubusercontent.com/55024122/86368257-2d12f980-bca7-11ea-9c5e-38aa03b66efe.png)
![2020-07-02_20 48 23](https://user-images.githubusercontent.com/55024122/86368277-31d7ad80-bca7-11ea-81b8-1cf4060ca623.png)

### System Information

- Java Version: Java 8 with Oracle JDK 1.8.0_251
- CPU: Intel(R) Core(TM) i3-3217U CPU @ 1.80GHz (4 CPUs), ~1.8GHz
- GPU: Intel(R) HD Graphics 4000
- Other mods installed: Lithium, Phosphor

**Comment by Huwng** [comment]
issue still exists with the mod built from AdoptOpenJDK 1.8.0_252

**Comment by LucilleTea** [comment]
Does it work if you set the Chunk Renderer OpenGL setting to 2.0 or 3.0? (In video settings > advanced)

**Comment by Huwng** [comment]
> Does it work if you set the Chunk Renderer OpenGL setting to 2.0 or 3.0? (In video settings > advanced)

yea it works now, thank you

**Comment by Huwng** [comment]
Closing this issue, apparently I'm an idiot for setting the Chunk Renderer to use OpenGL 4.3 on a GPU that doesn't even support it.
Sorry for wasting anyone's time.

**Comment by jellysquid3** [comment]
Sodium will default to using this renderer because it does not know better. Your graphics card _technically_ supports all the features, it's just a victim of #24.
