### ISSUE TITLE
Fabric Trying to load Wurst?

### ISSUE THREAD

**Issue by xDParis64** [jellysquid3/Sodium#521]
You can see here that i am trying to load fabric but i only intend on playing with one mod, which is sodium, i have no intentions of playing with the wurst client, why does it say that it can't load wurst if wurst isn't even present?

![image](https://user-images.githubusercontent.com/78797641/107359417-8f996700-6acc-11eb-9fff-c763b77e26c3.png)

A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Mod 'Wurst Client' (wurst) requires version 1.15.x of mod 'Minecraft' (minecraft), but a non-matching version is present: 1.16.5!
	 - You must install version 1.15.x of 'Minecraft' (minecraft).
	 - Mod 'Minecraft' (minecraft) v1.16.5 is being loaded from the user's mod directory.
 - Mod 'Wurst Client' (wurst) requires any version of mod fabric, which is missing!
	 - You must install any version of fabric.

**Comment by 2No2Name** [comment]
Make sure your mods folder only contains the mods you want to load. Does the screenshot actually show your mods folder?

**Comment by xDParis64** [comment]
I don't have a folder called mods in both my .minecraft directory or my versions directory, that is a screenshot of my fabric loader folder. 

Just for clarification I do not have wurst installed anywhere on my machine

**Comment by 2No2Name** [comment]
Which launcher are you using?

**Comment by xDParis64** [comment]
Minecraft Launcher, most recent, would I just be able to make a folder called "mods" in my .minecraft directory?

**Comment by 2No2Name** [comment]
Yes, just follow any fabric mod install tutorial, e.g. https://www.youtube.com/watch?v=p_vA6lBazuo
If you don't have a mods folder you clearly don't have sodium installed, so this problem seems to be unrelated to sodium.

**Comment by LucilleTea** [comment]
You must have a mods folder in some kind of minecraft profile directory, whether it's the default .minecraft or a moved directory.
I don't know exactly how else wurst may load itself, since it's unsupported by us, so not sure where else to tell you to look.
Either way this seems like a problem between you, fabric, and wurst - not sodium? So it's not very suited to our issue tracker.

**Comment by xDParis64** [comment]
Yeah i followed the tutorial and just created the mods folder and all seems well now thanks, and @LucilleTea I'm not gonna lie, i though I was in the Fabric Github not Sodium, so that's on me sorry.
