### ISSUE TITLE
Insane World

### ISSUE THREAD

**Issue by Hyxer** [jellysquid3/Sodium#523]
I expected to load in the world and be able to actually play

It looked like I was stuck underground, I could only see the blocks making my environment, like grass, all over my screen, that's all I could see, I couldn't walk forward really or even break blocks. It was really weird

### Reproduction Steps
It might only be my problem, I just need help fixing it from you. I literally just log in and it does that. 

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.
![image](https://user-images.githubusercontent.com/70125373/107639814-37f92800-6c93-11eb-86ee-7a85754f597a.png)

### System Informa
[DxDiag.txt](https://github.com/CaffeineMC/sodium-fabric/files/5965334/DxDiag.txt)
tion
You can obtain this information from the in-game debug screen or through using [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe) on Windows.

- Java Version: [fill me in]
- CPU: [Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz]
- GPU: [Intel (R) HD Graphics 4000]

**Comment by LucilleTea** [comment]
This is a support request, so it's better suited to [our discord server](https://jellysquid.me/discord) than the issue tracker.
The workaround is simple though. Go to Video Settings > Advanced, then set the Chunk Renderer setting to "Oneshot (GL 3.0)"
