### ISSUE TITLE
Between Blocks (Visual Bug)

### ISSUE THREAD

**Issue by LuisAngelRomeroSanchez** [jellysquid3/Sodium#524]
### Expected Behavior
That was compatible the sodium

### Actual Behavior
When entering the world, a visual bug appears which makes me see as if I were between blocks but it is only visual because I can dare them

### Reproduction Steps
What I did was that I downloaded everything necessary to be able to play with the lithium-phosphor-sodium (I attach images from the mods folder) but when I entered I am between blocks, but I could dare them, I thought they were the texture pack, and when I removed it It was still the same, I tried to remove the phospor and the lithium but it remained the same, I also removed the API from the fabric, but neither, so what I did was remove the sodium and the bug was removed, so I knew it was because of the sodium . Sorry about the English, I speak Spanish, you do what you can :(

1. Place a Redstone Lamp beside a Redstone Repeater
2. Use a Lever to activate the Redstone Repeater
3. Nothing happens

### Attachments
https://imgur.com/a/E4hyAtH
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/5970067/latest.log)

### System Information
[DxDiag.txt](https://github.com/CaffeineMC/sodium-fabric/files/5970061/DxDiag.txt)

- Java Version: [1.8.0_281-b09]
- CPU: [Intel Celeron n2830]
- GPU: [INTEL HD GRAPHICS]

**Comment by mrmangohands** [comment]
This is a bug in intel's drivers that affects the 4.3 backend, if you change the chunk renderer to 3.0 in video settings -> advanced it should be fine

**Comment by LuisAngelRomeroSanchez** [comment]
:o thank you, so much :heart:

**Comment by LuisAngelRomeroSanchez** [comment]
Hi, I am back :(
I went in to try what they had told me, and everything worked well for me, I left minecraft, time passed and when I re-entered, it was still fine but after about 15 minutes, the same thing happened again, I tried to move the chunks but It was still the same I tried to leave and enter the world and I also did not try to leave minecraft myself but neither, I do not know if I have a solution, I hope so, but if not then it does not matter :(
[Screenshots.zip](https://github.com/CaffeineMC/sodium-fabric/files/5975267/Screenshots.zip)

**Comment by fsharpseven** [comment]
In your screenshots (specifically Screenshot_6), the chunk renderer is still set to 4.3. As MrMangoHands said, that renderer is  not supported with some intel drivers. You have to set it to the "Oneshot 3.0" renderer or the issue will persist.

**Comment by mrmangohands** [comment]
Intel GPUs are now blacklisted from using the 4.3 renderer on Windows in 1.16.x/next.
