### ISSUE TITLE
Sodium crashes when you set the render distance to 32 and go above Y=260

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#53]
### Reproduction Steps
Set the render distance to 32 and go beyond Y=260, resulting in an exception_access_violation

### Crash Report File
https://gist.github.com/Hmmarch/1f67fbbc88832d922bed796cb0b2b92c

**Comment by jellysquid3** [comment]
I incorrectly referenced this issue in the commit above -- please ignore.
