### ISSUE TITLE
Sodium 0.1.0 is incompatible with Immersive Portals 0.65 (Duplicate of #15, Closed)

### ISSUE THREAD

**Issue by Vyladence** [jellysquid3/Sodium#534]
### Reproduction Steps
1. Install Fabric 1.16.4 and its matching API File
2. Install Immersive Portals 0.65
3. Install Sodium 0.1.0
4. Launch Game, Game Crashes

**Comment by NoComment1105** [comment]
In its present state sodium iz incompatible with Immersive portals. If I remember correctly (probably don't) it requires thd fabric rendering api which sodium doesn't support at the moment, it is on the Roadmap though, no eta

**Comment by Vyladence** [comment]
> it requires the fabric rendering api which sodium doesn't support at the moment

that makes sense. thank you for the reply!

**Comment by mrmangohands** [comment]
The incompatibility is unrelated to FRAPI support, duplicate of #15
