### ISSUE TITLE
Skins containing transparent pixels look transparent instead of black

### ISSUE THREAD

**Issue by ZtereoHYPE** [jellysquid3/Sodium#535]
### Expected Behavior
Usually when a skin in vanilla has transparent pixels these look black in-game. This is useful because otherwise players could use almost fully transparent skins and be basically invisible.

### Actual Behavior
When using Sodium these pixels look transparent and not black

### Reproduction Steps
look at a player that has a transparent skin using Sodium. The transparent areas are actually transparent and not black

### Attachments
Add any relevant screenshots or videos to this issue as you feel necessary to explain the issue.

### System Information
- Java Version: OpenJDK 15
- OS: macOS (using OpenGL 2.0)
- CPU: Intel Core i5-7360U
- GPU: Intel Iris Plus 640

**Comment by silversquirl** [comment]
Can't reproduce on either 0.1.0 stable or a fresh build of 1.16.x/next. Could you send screenshots and maybe an example skin?

**Comment by ZtereoHYPE** [comment]
will try as soon as possible.

**Comment by ZtereoHYPE** [comment]
seems to be a false alarm, as I can't seem to reproduce it either anymore. Trying to figure out what the cause was...

**Comment by ZtereoHYPE** [comment]
Turns out it was PresenceFootsteps, a sound enhancing mod! who would have guessed.
