### ISSUE TITLE
Github Actions build with JDK 14, thus causing a crash with Java 8

### ISSUE THREAD

**Issue by FavoritoHJS** [jellysquid3/Sodium#536]
### Expected Behavior
Github Actions build with Java 8, so the mod can work with Java 8

### Actual Behavior
Github Actions are built with JDK 14, causing #16 to crash the game on startup.

### Reproduction Steps
1. Download the build-artifacts of the latest Sodium build
2. Extract the build .jar file (sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT.jar at the time of writing) and install it.
3. Boot up with Java 8.
4. The game should crash on the main menu.

### Attachments
[crash-2021-02-15_22.38.42-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/5985285/crash-2021-02-15_22.38.42-client.txt)
[Screenshot of Github Actions](https://user-images.githubusercontent.com/69703458/108008814-fd1f2900-6fdf-11eb-8311-e872185de754.png)

### System Information

- Java Version: 1.8.0_262, GraalVM Community
- CPU: Intel Core i5-9300H
- GPU: Nvidia Geforce GTX 1050

**Comment by Genau6502** [comment]
This is a known issue. Either compile on java 8 or run it on java 9+

**Comment by DragonEggBedrockBreaking** [comment]
2701b43 has fixed this, this should be closed now.
