### ISSUE TITLE
No textures animate with "Animate Only Visible Textures" enabled

### ISSUE THREAD

**Issue by Lentern** [jellysquid3/Sodium#537]
### Expected Behavior
Textures animate with "Animate Only Visible Textures" enabled.

### Actual Behavior
Textures don't animate with the option enabled.

### Reproduction Steps
1) Start Fabric 1.16.5
2) Make sure "Animate Only Visible Textures" is enabled
3) Look at some water, fire, etc.

Java Version: AdoptOpenJDK 11.0.10.9
CPU: Intel Core i7 9700F 3 GHz
GPU: GeForce GTX 1650
Fabric 0.11.1
Sodium 0.1.1 Snapshot

**Comment by mrmangohands** [comment]
duplicate of #458
