### ISSUE TITLE
Crashes as soon as I open a world

### ISSUE THREAD

**Issue by BDog102** [jellysquid3/Sodium#54]
I am using lithium, phosphor, logical zoom, and sodium and fabric api and it crashes the second I open the world.

**Comment by jellysquid3** [comment]
Despite the issue template asking you to upload a crash log, you have not done so or provided any other information. This information is not optional. Please update this issue with the [appropriate information](https://github.com/jellysquid3/sodium-fabric/blob/1.16.x/dev/.github/ISSUE_TEMPLATE/crash-report.md) and re-open this issue.
