### ISSUE TITLE
Bug with textures displaying the error texture when using sodium with modpack

### ISSUE THREAD

**Issue by stellarcreal** [jellysquid3/Sodium#542]
I just discovered Sodium and used it in a modpack (All Of Fabric 3) to test it.
**I have Sodium version _sodium-fabric-mc1.16.3-0.1.0_ and _AOF3 version 2.6.9_ according to CurseForge**
![image](https://user-images.githubusercontent.com/79639996/109147415-a21ecc00-776d-11eb-8696-636657907658.png)

At first I was SURPRISED of the performance increase, but then noticed that some textures were displaying the error texture.

Tried the modpack again without Sodium, everything is fine. Placing Sodium back in, same textures display the error texture.

Already checked if the models/blocks of the items display the same error texture... but nope. Models/blocks are just fine and the item texture is bugged.
![image](https://user-images.githubusercontent.com/79639996/109147106-4d7b5100-776d-11eb-9f8c-2ff636478ab0.png)
![image](https://user-images.githubusercontent.com/79639996/109147128-5409c880-776d-11eb-9e58-3534facef6dd.png)

You can see in the last image that I'm holding the bugged oak sapling, but the model itself is fine.

As I checked the error textures it seems there is no patern, just random textures appear bugged.

**Comment by NoComment1105** [comment]
Effectively a duplicate of #5 (i think)
Fabric Rendering API is not implemented in sodium at the moment. it is on the road map, no eta

**Comment by stellarcreal** [comment]
I posted this because I've read people saying that it doesn't even launch their game, but it does launch mine, it's just the textures that are bugged.

**Comment by stellarcreal** [comment]
Everything else works *super* well, the only bug is the bugged textures

**Comment by NoComment1105** [comment]
This is due to the lack of Fabric Rendering API compatability. Some mods in that mod pack use the FRAPI, and hence their textures break

**Comment by stellarcreal** [comment]
Oh okay, I really thought it was something else because I haven't seen any post that is similar to my case

**Comment by LucilleTea** [comment]
This is still caused by lack of Fabric Rendering API support, and you will likely run into more issues. Last I checked, many Applied Energistics 2 blocks would crash the game with Sodium.
For now it would be best to play AoF3 without Sodium, or you could look into using [Indium](https://github.com/comp500/Indium) to add FRAPI support to Sodium (another project, not by us).
