### ISSUE TITLE
Worldborder warning command broken

### ISSUE THREAD

**Issue by norcaldev** [jellysquid3/Sodium#548]
### Expected Behavior
The worldborder warning would appear, showing a red border around your screen.

### Actual Behavior
The worldborder warning does not appear at all.

### System Information
- Java Version: [AdoptOpenJDK 15 Hotspot]
- CPU: [i7-7700k]
- GPU: [GTX 1080 Ti]

**Comment by saadatxyz** [comment]
![image](https://user-images.githubusercontent.com/68823166/109410562-81629c00-7950-11eb-986d-5b028fc07865.png)

Works fine for me on Linux, Intel (mesa drivers), OpenJDK 15.

Could be driver specific or a Windows thing?
Switching between the different renderers didn't seem to change anything (neither did fast, fancy, or fabulous graphics).

**Comment by mrmangohands** [comment]
As mentioned on discord this happens when the vignette is off, which is vanilla behavior with fast graphics.
