### ISSUE TITLE
Doors, Lanterns, Flower Pots and possibly some more are too bright

### ISSUE THREAD

**Issue by SirBobb** [jellysquid3/Sodium#55]
### Expected Behavior
Normal Lighting on all Blocks

### Actual Behavior
Doors, Lanterns, Flower Pots are too bright (see attachment)

### Reproduction Steps
It's most present at higher light levels.
I use phosphor, sodium, fabric api, smooth scrolling and logical zoom on 1.16.1
I removed just sodium and they were all fixed

1. Place a Redstone Lamp beside a Redstone Repeater
2. Use a Lever to activate the Redstone Repeater
3. Nothing happens

### Attachments
![2020-07-03_18 49 00](https://user-images.githubusercontent.com/35657425/86487632-eb458a00-bd5e-11ea-8dd7-7b976a771ecf.png)
![2020-07-03_18 49 05](https://user-images.githubusercontent.com/35657425/86487637-ee407a80-bd5e-11ea-9d55-358f37aff049.png)
![2020-07-03_18 32 50](https://user-images.githubusercontent.com/35657425/86487643-f13b6b00-bd5e-11ea-8e8d-9b8f22211466.png)

### System Information

- Java Version: 14.0.1+7 (I followed the maximum performance settings in this post https://www.reddit.com/r/Minecraft/comments/hflrbh/i_made_a_java_1161_performance_package_for_those/)
- CPU: i5 6400
- GPU: RX 580

**Comment by jellysquid3** [comment]
You are using an old version of Sodium. This issue has since been fixed.
