### ISSUE TITLE
Fire Animation now works, But weird with Texture packs?

### ISSUE THREAD

**Issue by DrkShdX** [jellysquid3/Sodium#552]
https://user-images.githubusercontent.com/26654312/109433276-3048bb80-79d5-11eb-9e57-196490f195bd.mp4

Not complaining just reporting something I noticed
AMD Ryzen 3 3200U (mobile)
AMD Radeon Vega 3

**Comment by DragonEggBedrockBreaking** [comment]
Define "weird". From my point of view, the fire animation is normal and the particles seem to be changed by the texture pack. Do you have a comparison of what it should look like without sodium, so we can see how sodium is breaking anything/what it is breaking?

**Comment by DrkShdX** [comment]
theres two different fire animations, both at different animation speeds

**Comment by DrkShdX** [comment]
nvm its just something weird going on with my pc, restarting it fixxed it
