### ISSUE TITLE
Chunks not loading with sodium on chromebook

### ISSUE THREAD

**Issue by MinecraftBeast07** [jellysquid3/Sodium#555]
### Expected Behavior
I should be able to sign into minecraft with sodium working and be able to play the game
example should be able to see blocks and leaves

### Actual Behavior
I sign in and chunk loading is weird and I can't play the game
example I don't see blocks and leaves

### Reproduction Steps
  install fabric api and sodium in my mob folders, Start the game, log into my minecraft world, and the world is messed up that i cant do anything.

### Attachments
![Screenshot 2021-03-01 at 10 56 04 AM](https://user-images.githubusercontent.com/79859340/109522880-bec44800-7a7c-11eb-9906-146e755b10c1.png)

### System Information
Linux on a chromebook

- Java Version: [1.16.1]
- CPU: [130 for linux]
- GPU: [don't know]

**Comment by FlashyReese** [comment]
Go to `Advanced > Chunk Renderer > Oneshot 3.0` to work around this for the meanwhile.

**Comment by amnotbananaama** [comment]
Closing as a duplicate
