### ISSUE TITLE
Structure block bounding boxes

### ISSUE THREAD

**Issue by Boobies** [jellysquid3/Sodium#56]
While turning a structure block's bounding box on and off works as expected, breaking the block ought to remove the bounding box but it does not. Logging out and back on again fixes the issue (perhaps so does leaving the area but this I have not tested).

**Comment by jellysquid3** [comment]
Fixed with https://github.com/jellysquid3/sodium-fabric/commit/beaf102c3125776e86cd2f1f8554f3c32edf5b53.
