### ISSUE TITLE
Bump version?

### ISSUE THREAD

**Issue by plusls** [jellysquid3/Sodium#560]
I found that stable version is 0.1.1, but `next` version also is 0.1.1, i don't know how to write code to know which sodium version has been loaded.

I think `next` should have an another version?

**Comment by DragonEggBedrockBreaking** [comment]
> I found that stable version is 0.1.1, but `next` version also is 0.1.1, i don't know how to write code to know which sodium version has been loaded.
> 
> I think `next` should have an another version?

The latest sodium release is 0.1.0 though. Also, I believe that all development is done on 1.16.x/next now and the version on next will probably be bumped if/when 0.1.1 is released.

**Comment by Leo40Git** [comment]
`1.16.x/next` will get its version bumped when it's actually ready for release.
You can differentiate between an actual 0.1.1 build and a build of `next` by the `-SNAPSHOT` suffix in the file name.

**Comment by plusls** [comment]
But current stable branch is also 0.1.1

**Comment by plusls** [comment]
It is the same with `next` branch.
https://github.com/CaffeineMC/sodium-fabric/blob/5af41c180e63590b7797b864393ef584a746eccd/gradle.properties#L11

**Comment by DragonEggBedrockBreaking** [comment]
> But current stable branch is also 0.1.1

Probably doesn't matter for the following reasons:
- The current release is 0.1.0
- When the next release comes, if it is 0.1.1, then the next branch version will also be bumped to 0.1.2 (or maybe 0.2.0)
- On other CaffeineMC mods, the version is bumped just before a release, so maybe they were trying to get closer to that
- You probably shouldn't be developing on the stable branch anyway as all development is done on the next branch

**Comment by amnotbananaama** [comment]
Echoing DragonEggBedrockBreaking comment above. It's hard to bump the version when it's not clear what to bump to yet. Additionally I personally prefer to bump right before a release to make Git history more clear.
> i don't know how to write code to know which sodium version has been loaded.

I didn't notice this part of your initial issue. What is your use case? This might be better discussed on the [official discord](https://jellysquid.me/discord) which is much more conducive to conversation than a GitHub issue.

**Comment by plusls** [comment]
> Echoing DragonEggBedrockBreaking comment above. It's hard to bump the version when it's not clear what to bump to yet. Additionally I personally prefer to bump right before a release to make Git history more clear.
> 
> > i don't know how to write code to know which sodium version has been loaded.
> 
> I didn't notice this part of your initial issue. What is your use case? This might be better discussed on the [official discord](https://jellysquid.me/discord) which is much more conducive to conversation than a GitHub issue.

I just want to write a mod to highlight lava source, and I do it in vanilla. But I want to compact with sodium.

![image](https://user-images.githubusercontent.com/23459592/109549544-114b4600-7b09-11eb-9ee1-562b04dddc63.png)

I mixin `me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer` to check whether a block is lava source. But I found that the function sign of `me.jellysquid.mods.sodium.client.render.pipeline.FluidRenderer.render` is different between `stable` and `next` branch, so I want to write code to check the version of sodium.

**Comment by FlashyReese** [comment]
The current release is 0.1.0, stable has a version bump to 0.1.1 but it was never released. You can get a mod's metadata using something like `FabricLoader.getInstance().getModContainer("sodium")` get versions. In the future `next` will be merged into `stable`, but there is no ETA on that.
