### ISSUE TITLE
Crash on Startup, not sure what is causing it

### ISSUE THREAD

**Issue by caek08** [jellysquid3/Sodium#569]
I'm having a crash on startup using sodium with other mods. The list of mods is included in the crash report but I can't tell which one is causing it from the crash report

Crash Report:
https://gist.github.com/caek88/b8715c2ec6df2e8a84b1174d01a2fa55

**Comment by LucilleTea** [comment]
Duplicate of #15 
Sodium is incompatible with Immersive Portals.

**Comment by caek08** [comment]
Ah sad
Thanks for the quick response
