### ISSUE TITLE
Smooth Lighting has jagged edges in some directions.

### ISSUE THREAD

**Issue by TwistedZero** [jellysquid3/Sodium#57]
### Expected Behavior
The light is smooth in all directions.

### Actual Behavior
The light is smooth in two parallel directions but jagged in the other two.

### Reproduction Steps
1. Smooth Lighting should be set to Low/High and Brightness should be set to 100 for best visibility.
2. Create a Superflat world with the following preset: `minecraft:bedrock,4*minecraft:white_concrete,4*minecraft:air,4*minecraft:white_concrete;minecraft:desert`
3. Break a hole in the ceiling so that light will shine into the layer of air.
4. Observe that the edge of the light is jagged in some directions.

### Attachments
![2020-06-30_20 31 44](https://user-images.githubusercontent.com/51268715/86504156-31293f00-bdad-11ea-931b-91e7d54debf7.png)

### System Information

- Java Version: 1.8.0_222 (64-bit OpenJDK Hotspot)
- CPU: Ryzen 5 2500u
- GPU: Vega 8 Integrated Graphics

**Comment by jellysquid3** [comment]
It looks like this issue might be caused by using an older version of Sodium. I am unable to reproduce it with the latest version:
![lightanisookay](https://user-images.githubusercontent.com/1363084/86878695-1a396400-c0af-11ea-879b-1fb1a511a1a6.png)

**Comment by TwistedZero** [comment]
I still see this issue with both a self built version on the latest commit and release candidate 7 from Discord.
My self built version was compiled with Java 8 and tested on both Java 8 and Java 14 while release candidate 7 was only tested with Java 14, the issue was visible in all cases.
This issue is most visible when there is no sky light, note how there is no blue tint to the white concrete in this image: 
![2020-07-08_06 25 01](https://user-images.githubusercontent.com/51268715/86883000-1296b100-c0e9-11ea-9c7a-9affe89b5959.png)
It also happens on walls:
![2020-07-08_07 13 17](https://user-images.githubusercontent.com/51268715/86884144-0d3a6600-c0eb-11ea-92fe-8f53ab981314.png)
I have noticed that the light **is** being smoothed correctly until it gets to the edge (where both sky and block light are 0).

**Comment by TwistedZero** [comment]
I have tested release 0.1 and this issue is still present, so I have put together a test world to help reproduce it:

[Issue 57.zip](https://github.com/jellysquid3/sodium-fabric/files/4907748/Issue.57.zip)

When you enter this world you should see two large rooms, one showing the issue using sky light, the other showing it using block light.

I will update this comment to mention the latest version I have tested that still has this issue.

**Comment by fsharpseven** [comment]
Can confirm on `7aef096`. See below.

![2020-11-02_15 41 13](https://user-images.githubusercontent.com/40721769/97917125-ff57c300-1d21-11eb-8183-b197f3a8f61f.png)

**Comment by MeeniMc** [comment]
Can replicate with `gradlew runClient` on tag 0.3.2 (thus no other mods). 

The orientation of the defect is 135 degrees; 45 degrees edges are correctly averaged.

**Comment by Lolothepro** [comment]
This does not seem to happen with Minecraft 1.19.4 and Sodium 0.4.10

**Comment by Lolothepro** [comment]
I managed to reproduce it with Sodium 0.4.10, it's just harder to reproduce it with Sodium 0.4.10.

**Comment by Lolothepro** [comment]
fixed
