### ISSUE TITLE
Iron blocks have issue with compact vertex format 

### ISSUE THREAD

**Issue by Genau6502** [jellysquid3/Sodium#577]
### Expected Behavior
Comparison with CVF off:
![image](https://user-images.githubusercontent.com/66269211/111031923-cb905680-8401-11eb-8d2d-68ac899f626d.png)

### Actual Behavior
Latest commit: 
![image](https://user-images.githubusercontent.com/66269211/111031939-e19e1700-8401-11eb-87e8-e457e8ca4a70.png)
(Might need to click on to see properly)

### Reproduction Steps
Place some iron blocks with CVF on, and you will see flickering, texture stitching issues and more on them. I can't reproduce this using any other block

### Attachments
Found above ^^

### System Information

- Java Version: AdoptOpenJDK JDK 15
- CPU: Intel i5-1035G1
- GPU: Intel HD graphics (4.6.0)

Latest commit on the next branch, using OneShot GL 3.0

**Comment by FlashyReese** [comment]
Said latest commit: https://github.com/CaffeineMC/sodium-fabric/commit/2fb1d28aa61680170e44a138c296f3b5534314e0

**Comment by ZtereoHYPE** [comment]
Are you by chance using VanillaTweaks connected iron blocks?

**Comment by Genau6502** [comment]
CBT with indium, i'll check on base sodium now

**Comment by LucilleTea** [comment]
This seems like it's probably an interaction with CBT, which you mentioned? I can't imagine any reason for the texture to be capable of that otherwise.
I don't know if needing Indium + CBT necessarily puts it out of our hands, but it feels a bit distant.

**Comment by jellysquid3** [comment]
Is this still a problem in Sodium 0.3 for Minecraft 1.17? The compact vertex format is always enabled there.

**Comment by MESLewis** [comment]
Duplicate #815
