### ISSUE TITLE
Question: why isn't v0.1.1 or sth released yet?

### ISSUE THREAD

**Issue by K0-RR** [jellysquid3/Sodium#579]
The last public release was uploaded on Sep 27, 2020. Many fixes and improvements were added to the Sodium since then.

**Comment by Genau6502** [comment]
The changes still have some problems, notably multidraw being broken on intel GPUs, and that it's simply not ready yet. Be patient, and you can compile yourself if needed

**Comment by LucilleTea** [comment]
It will be ready when it's ready.
