### ISSUE TITLE
Unable to join Servers / Worlds

### ISSUE THREAD

**Issue by StealWonders** [jellysquid3/Sodium#58]
### Reproduction Steps
Basically, whenever I try to join a single-player or multiplayer world (on 1.16.1) I get the loading screen and I believe when it spawns me in so when it's about to show the 3D graphics the game crashes with the crash log below.

### Crash Report File
https://gist.github.com/StealWonders/034b1d3b2a61027f42a12924765acfd6

### Additional Information
OS: Windows 10 Home
Graphics card: GTX 1080
Java: OpenJDK (OpenJ9) 8.0.242.08 (x64)
Fabric: fabric-loader-0.8.9+build.203-1.16.1
Running: self-built branch 1.16.x/dev (d35cb02)

**Comment by Kroppeb** [comment]
Ah, you have compiled it with a Java version of at least 9. This is known to cause problems when run on java 8. 

You could use the precomputed version, make your Minecraft use a later java version or compile with java 8.

**Comment by StealWonders** [comment]
> 
> 
> Ah, you have compiled it with a Java version of at least 9. This is known to cause problems when run on java 8.
> 
> You could use the precomputed version, make your Minecraft use a later java version or compile with java 8.

That seems to have fixed it, thanks for helping :-)
I seem to have missed the warning notice in the readme.md
