### ISSUE TITLE
GitHub actions builds don't contain playable jar anymore.

### ISSUE THREAD

**Issue by K0-RR** [jellysquid3/Sodium#584]
I tried downloading several build artifacts up to 14 days in the past and they only contain sources.jar and sources-dev.jar OR sources.jar and dev.jar.

**Comment by mrmangohands** [comment]
Latest two both have all the artifacts for me

**Comment by LucilleTea** [comment]
[The latest one](https://github.com/CaffeineMC/sodium-fabric/actions/runs/652709833) contains all 4 of the normal jars, as usual.
![](https://cdn.discordapp.com/attachments/622089187809820672/820960741834096640/unknown.png)

**Comment by K0-RR** [comment]
HOW? I downloaded the same and only have these two
![image](https://user-images.githubusercontent.com/43277609/111137734-6febd780-857f-11eb-81e4-cc0be1e57ea9.png)

**Comment by K0-RR** [comment]
Seems like another issue with fuckin PeaZip...
