### ISSUE TITLE
Failing to compile.

### ISSUE THREAD

**Issue by notsatvrn** [jellysquid3/Sodium#588]
### Expected Behavior
Gradle grabs `fabric-loom` properly and continues to compile.

### Actual Behavior
Gradle appears to contact `https://jcenter.bintray.com` instead of the Fabric Maven to get `fabric-loom`, and fails.

### Reproduction Steps
Download Sodium source code, and compile with `./gradlew build`

- Java Version: Java 8
- CPU: i7-2600k
- GPU: RX 570

**Comment by notsatvrn** [comment]
Solution: remove `jcenter()` from `settings.gradle`. Compiles properly and works just fine.

**Comment by DragonEggBedrockBreaking** [comment]
> Solution: remove `jcenter()` from `settings.gradle`. Compiles properly and works just fine.

I already made a pull request to update to Loom 0.6.
