### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by LynnH177** [jellysquid3/Sodium#593]
the game crashes on launch, i am not using optifine and i made sure its not another mod but it might be a compatibility issue maybe? ill link my crash report and thank you in advance <3
https://gist.github.com/LynnH177/2408a8c409e50c35a36adc0933699dd0

**Comment by amnotbananaama** [comment]
Duplicate of #15. Sodium and Immersive Portals are currently incompatible at the moment. This is a known issue that is being worked on.
