### ISSUE TITLE
ArrayIndexOutOfBoundsException crash on Hypixel Skyblock

### ISSUE THREAD

**Issue by Leo40Git** [jellysquid3/Sodium#594]
## This issue was encountered while using a development build of Sodium!
Build is from commit 07c4cc1fd6a5b67f6fe08ee18db05d254a5051c4.

### Reproduction Steps
I triggered this crash in an area that's locked behind a skill level, so you'll need to play some Skyblock before you can replicate it. Sorry!

1. In Hypixel Skyblock, go to the Deep Caverns area
2. Get to one of the lower levels - I replicated the crash in Slimehill and initially encountered it in Obsidian Sanctuary
3. Wait - I'm unsure of what actually _triggers_ the crash, but it seems to happen around these areas
4. The game crashes

### Crash Report File
[Over here!](https://gist.github.com/Leo40Git/d254bb87fa0bdb056b67afe513f604a0)

**Comment by DragonEggBedrockBreaking** [comment]
If you go below y=0, then this is a duplicate of #587 

Can you reproduce with #589

You can download a build for that here:
https://github.com/CaffeineMC/sodium-fabric/actions/runs/660817686

**Comment by Leo40Git** [comment]
You can't go below Y=0 here, bar falling off the map (and the exception details don't line up with that case: the AIOOB is caused by trying to reference the 16th element in a 16-length array, while falling below Y=0 tries to access the element at index -1).

Will now try with that PR.

**Comment by Leo40Git** [comment]
Seems to be fixed by #589, so maybe this is a variant of #587 rather than a duplicate?

**Comment by DragonEggBedrockBreaking** [comment]
> Seems to be fixed by #589, so maybe this is a variant of #587 rather than a duplicate?

Then maybe you should post your log and scenario on #587 and close this, since they are both fixed by the same PR?

**Comment by Leo40Git** [comment]
Done.
