### ISSUE TITLE
Add FOV Effect Scale toggle

### ISSUE THREAD

**Issue by Toul-dev** [jellysquid3/Sodium#595]
In the default vanilla menu, there is a toggle option for "FOV Effects" (toggles whether pressing sprint or any effects to do with speed changes FOV scaling). Could this be added as an option in the CaffeineMC video settings? Thanks!

**Comment by jellysquid3** [comment]
Anyways, this issue is covered by #46. Please use the search function before opening new issues. We have been closing the vast majority of newly opened issues over the last few months.
