### ISSUE TITLE
Sodium does not work in full screen mode

### ISSUE THREAD

**Issue by aadit-n** [jellysquid3/Sodium#597]
### Expected Behavior
Sodium should be working when I am in full screen mode, however, it gives me only upto 160 - 200 fps which also happens to be my normal fps.

### Actual Behavior
When I disable fullscreen mode, its gives me upto 400 fps, but,I want this to work in fullscreen mode.

### Reproduction Steps
Install the sodium mod and enable full screen mode, you will notice that you get your normal fps.
Now, disable full screen, you will immediately notice that your fps has increased a lot.

### System Information
- Java Version: 1.8.0_281
- CPU: Intel Core i7 10750h laptop processor
- GPU: GTX 1650 Max-Q Laptop GPU

**Comment by comp500** [comment]
Do you have multiple monitors connected? Does the same happen without Sodium?
A screenshot of the F3 screen would also be helpful.

**Comment by aadit-n** [comment]
> Do you have multiple monitors connected? Does the same happen without Sodium?
> A screenshot of the F3 screen would also be helpful.
No, I dont have multiple monitors connected. I play on a  laptop.
No, the same doesnt happen without sodium, without sodium my fps ranges from about 100 - 180.
![2021-03-21_13 32 04](https://user-images.githubusercontent.com/81066624/111901535-e0946780-8a49-11eb-9c53-715b4c6900aa.png)
The above is a screenshot of the F3 screen in fullscreen mode.
![2021-03-21_13 33 52](https://user-images.githubusercontent.com/81066624/111901576-19344100-8a4a-11eb-8874-10b6a61e8987.png)
This is a screenshot of the F3 screen with fullscreen disabled.

**Comment by Genau6502** [comment]
Well of course it's faster with fullscreen disabled: it's running at 480p vs 1080p

**Comment by FlashyReese** [comment]
Is there any reason why you aren't using the `Multidraw (GL 4.3)` Chunk Renderer? Looks like your GPU does support it.

**Comment by magneticflux-** [comment]
> Well of course it's faster with fullscreen disabled: it's running at 480p vs 1080p

The fullscreen resolution has over 5x the number of pixels being rendered. It's no wonder the framerate decreases! 😆

**Comment by aadit-n** [comment]
So if I was to reduce my fullscreen resolution, it would work?

**Comment by jellysquid3** [comment]
This is not a bug with Sodium, and your results are expected.

Running the game in full-screen will generally reduce the game's frame rate. However, having your graphics settings set to "Fabulous" won't help either, as it becomes hugely more expensive with every increase in resolution (for an almost trivial improvement in quality.)

As such, you should either switch from Fabulous to Fancy graphics (again, sacrificing very little) or lower your full-screen resolution.
