### ISSUE TITLE
Extreme performance drop with sodium when going in and out of nether portals

### ISSUE THREAD

**Issue by Panderine** [jellysquid3/Sodium#599]
### Expected Behavior
No significant change in fps should be expected

### Actual Behavior
Total fps drop (from 700 fps to 5).

### Reproduction Steps
1. go in and out **repeatedly and fast** of a nether portal in a fresh created world. Fps drop immensely as per screenshots. Upon going in again it solves performance loss. 

Important notice: Can't seem to reproduce it with stable sodium 0.1.0

### Attachments
Screenshots and crash report
[crash-2021-03-21_06.58.05-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6177982/crash-2021-03-21_06.58.05-client.txt)
![2021-03-21_06 51 36](https://user-images.githubusercontent.com/4042199/111914722-f9088000-8a51-11eb-8d7b-29151e642a31.png)
![2021-03-21_06 35 52](https://user-images.githubusercontent.com/4042199/111914726-00c82480-8a52-11eb-8364-bc80bf372850.png)
![2021-03-21_06 32 42](https://user-images.githubusercontent.com/4042199/111914727-045bab80-8a52-11eb-9e6f-f104bcc6cc9a.png)
![2021-03-21_04 05 03](https://user-images.githubusercontent.com/4042199/111914731-09205f80-8a52-11eb-9576-bc7a4f7b824c.png)
![2021-03-21_04 05 55](https://user-images.githubusercontent.com/4042199/111914739-0d4c7d00-8a52-11eb-97dd-fda7d9c3bccd.png)

### System Information
Java 16 64bits (flags used available in crashreport)

### Next Steps
Right now I'm investigating with VisualVM to see if I could get more relevant info.

**Comment by Panderine** [comment]
f3+t fixes the issue without needing to go through the portal.

**Comment by CalXee** [comment]
In my experiences, F3+A sometimes fixes this issue. However I've managed to reproduce something at least similar to this (huge fps drop when changing dimensions) with only sodium and no lambdynamiclights.
![mods](https://user-images.githubusercontent.com/68349758/112774213-efa98580-9006-11eb-852e-f6f960a110ea.png)
Also, do you have phosphor installed?

**Comment by mrmangohands** [comment]
This issue could actually be replicated with Sodium alone, however I believe it was introduced in de545a500a31f96b5caf7f698a38902945e70f2e and fixed in abfa386b01ae6d248f35a174c2059465787fc76e (or if not there then certainly in e0142381e9bbac0957c17679cb94eca035dd134e).
