### ISSUE TITLE
Armour stands with the Marker tag do not have lighting

### ISSUE THREAD

**Issue by dvitski** [jellysquid3/Sodium#60]
### Expected Behavior
`Marker` armour stands should simply have their hitbox and/or fire animation removed.

### Actual Behavior
`Marker` armour stands do the former, but also go completely black.

### Reproduction Steps
`/summon armor_stand ~ ~ ~ {Marker:1}`

#### Vanilla
![2020-07-06_14 56 16](https://user-images.githubusercontent.com/36608902/86602087-149e2a00-bf9a-11ea-99d3-7c69205ac811.png)
#### Sodium
![2020-07-06_15 03 09](https://user-images.githubusercontent.com/36608902/86602119-1e279200-bf9a-11ea-9f40-8443ae6b4cf6.png)

### System Information
- Java Version: 1.8.0_51 64bit
- CPU: 2x Intel(R) Celeron(R) N4000 CPU @ 1.10GHz
- GPU: Intel(R) UHD Graphics 600

**Comment by Earthcomputer** [comment]
Isn't this vanilla behaviour?

**Comment by dvitski** [comment]
I've also just discovered that armour stands inside of blocks (not on fire) are fully lit
Edit: I didn't check other entities

**Comment by dvitski** [comment]
> Isn't this vanilla behaviour?

Not at all :P

**Comment by juancarloscp52** [comment]
Might be related to issue #48

**Comment by dvitski** [comment]
\*moved this comment to the main body of the issue\*
