### ISSUE TITLE
Optimise Bamboo Rendering

### ISSUE THREAD

**Issue by NoComment1105** [jellysquid3/Sodium#602]
**Is your feature request related to a problem? Please describe.**
Unfortunately im too stupid to be able to describe what happens here, so instead ill leave a link to the RandomPatches README.md
https://github.com/TheRandomLabs/RandomPatches#optimize-bamboo-rendering-client-sided

**Describe the solution you'd like**

**Describe alternatives you've considered**
Using RandomPatches but i feel this is something that sodium should implement

**Additional context**
The message thread from the Discord, contains screenshots.
https://discord.com/channels/602796788608401408/651120262129123330/823965947290320957

**Comment by DragonEggBedrockBreaking** [comment]
You can find the exact file in randompatches that implements the optimisation [here](https://github.com/TheRandomLabs/RandomPatches/blob/1.16-fabric/src/main/java/com/therandomlabs/randompatches/mixin/client/BambooBlockMixin.java), and you can find the original (1.14.2) mod which this optimisation was based on [here](https://github.com/TridentMC/FastBamboo).

**Comment by NoComment1105** [comment]
Yeah the trouble is im not smart enough to implements this properly into sodium via a PR

**Comment by DragonEggBedrockBreaking** [comment]
> Yeah the trouble is im not smart enough to implements this properly into sodium via a PR

I put the links there to help people who know what they are doing to find the code faster.

**Comment by NoComment1105** [comment]
Ah okay, makes sense

**Comment by NoComment1105** [comment]
Closing due to my testing being worthless aha 🙃

**Comment by DragonEggBedrockBreaking** [comment]
> Closing due to my testing being worthless aha 🙃

Imo, this should be kept open until it is proven that it does *not* improve anything, as if, after testing, it actually works, then this could be a nice feature request.

**Comment by DragonEggBedrockBreaking** [comment]
> Imo, this should be kept open until it is proven that it does _not_ improve anything, as if, after testing, it actually works, then this could be a nice feature request.

Ignore my comment, it has been partially, if not completely been invalidated by smth that JellySquid just posted on discord.
