### ISSUE TITLE
Invisible Kibe items

### ISSUE THREAD

**Issue by srnyx** [jellysquid3/Sodium#603]
### Expected Behavior
No item should be invisible in the inventory.

### Actual Behavior
Some of the items from Kibe are completely invisible in the inventory.
_The blocks are visible when placed._

### Reproduction Steps
1. Install [Sodium](https://www.curseforge.com/minecraft/mc-mods/sodium/files/3067101) ~~(with [Immersive Portals compatibility](https://github.com/qouteall/sodium-fabric/releases/tag/ipc1165_2)) with [Indium](https://github.com/comp500/Indium/actions/runs/658347188)~~
2. Install [Kibe](https://www.curseforge.com/minecraft/mc-mods/kibe/files/3247476)
3. Search for `Entangled` in the creative menu. The `Entangled Bag` and `Entangled Chest` are invisible (so are the `Drawbridge` and `Tank`).

### Attachments
![image](https://user-images.githubusercontent.com/25808801/112239186-65cf7600-8c1c-11eb-885a-2533fde4677e.png)

### System Information
- Java Version: Version 8 Update 281
- CPU: AMD Ryzen 5 3600 6-Core 3.6GHz
- GPU: MSI GeForce GTX™ 1660 SUPER Ventus XS 6G OC

**Comment by ImperatorStorm** [comment]
Forks are unsupported iirc

Report bug to quoteall, or test with https://github.com/CaffeineMC/sodium-fabric.

I'm guessing its a duplicate of #5

**Comment by srnyx** [comment]
> Forks are unsupported iirc
> 
> Report bug to quoteall, or test with https://github.com/CaffeineMC/sodium-fabric.
> 
> I'm guessing its a duplicate of #5

Ah, alright

**Comment by srnyx** [comment]
Tested with normal/official Sodium and the items are invisible

**Comment by comp500** [comment]
This is a duplicate of #5 (the models use the Fabric Rendering API) and I can't replicate this issue with Indium. Note that you need to use [the 1.16.x/next branch](https://github.com/CaffeineMC/sodium-fabric#bleeding-edge-builds) for Indium to work.

**Comment by srnyx** [comment]
> This is a duplicate of #5 (the models use the Fabric Rendering API) and I can't replicate this issue with Indium. Note that you need to use [the 1.16.x/next branch](https://github.com/CaffeineMC/sodium-fabric#bleeding-edge-builds) for Indium to work.

I think I accidentally had Indium disabled when I first discovered it... my apologies
