### ISSUE TITLE
Multi-Layered textures don't be rendering

### ISSUE THREAD

**Issue by arcanoren** [jellysquid3/Sodium#606]
... Like a Kibe item Entangled Bag

**Comment by dbl7id** [comment]
Next time please try to either use the provided issue templates or elaborate more on the issue that you are having.
I'm assuming that this is a duplicate of #5.

**Comment by LucilleTea** [comment]
It is, we just had this particular example come up in #603 too.

**Comment by arcanoren** [comment]
yes, is it... Sorry
