### ISSUE TITLE
Incompatible with Connected Textures mod

### ISSUE THREAD

**Issue by 5HT2** [jellysquid3/Sodium#61]
### Expected Behavior
Connected textures mod functions normally. 

### Actual Behavior
Textures do not connect. 

### Reproduction Steps
Built sodium on 20w27a via [this](https://modmuss50.me/fabric.html?&version=20w27a)

Using latest release of CBT from [here](https://github.com/Nuclearfarts/connected-block-textures/issues/)

1. Place glass
2. [Observe](https://user-images.githubusercontent.com/17222512/86619480-a43add00-bf88-11ea-95c3-d4d300e0d93e.png)

### System Information

- Operating System: 5.7.4-arch1-1
- Java Version: OpenJDK 8 latest AUR build
- CPU: Intel i7-5600U
- GPU: Integrated

### Additional Context:

I filed an issue in their repo [here](https://github.com/Nuclearfarts/connected-block-textures/issues/5) as I'm not sure which mod is at fault

**Comment by jaskarth** [comment]
Sodium does not support the Fabric Rendering API yet, so Connected Block Textures won't work.

**Comment by 5HT2** [comment]
I see. So this issue would belong here then?

**Comment by broken1arrow** [comment]
Is it build in, soo you can use something similar too clearglass (only borders show, no gitters on the glass)?

When i has try 1.16, is a pain to see so ugly vanilla glass is, so i do not want to use 1.16 before it get fixed.

And yes i use Fabric (vanilla launcher not work properly).

**Comment by 5HT2** [comment]
I'm not sure what clearglass is, and no, the mod isn't built in, as I stated in the reproduction instructions

**Comment by broken1arrow** [comment]
https://www.curseforge.com/minecraft/texture-packs/clear-glass-pack

You need optifine for this. So if some or you add something similar, it is assume :) Yes i know this is a mod (some mods work thru vanilla launcher or forge) :)

**Comment by 5HT2** [comment]
That's not a mod, that's a resource pack for glass, and you still need an external mod for it to work, such as CBT, which Sodium breaks. 

Meaning, installing that resourcepack is just as useless as not installing it.

**Comment by broken1arrow** [comment]
> 
> 
> That's not a mod, that's a resource pack for glass, and you still need an external mod for it to work, such as CBT, which Sodium breaks.
> 
> Meaning, installing that resourcepack is just as useless as not installing it.

You most have misunderstand or I use wrong worlds. 
Yes it is resourcepack, but need opfine, that I ask if you have any similar in Sodium, build in or can add in.

**Comment by 5HT2** [comment]
I'm saying that Sodium *breaks* connected texture support that other mods provide. That's why I opened a bug report.

**Comment by broken1arrow** [comment]
> 
> 
> I'm saying that Sodium _breaks_ connected texture support that other mods provide. That's why I opened a bug report.

I´m slow to day :) yes hope it get fixed soon.

**Comment by leo60228** [comment]
Sodium isn't intended to add new features like Optifine does. However, as time goes on, it should become compatible with more and more separate mods that provide those features. The resource pack you linked should work with [this mod](https://www.curseforge.com/minecraft/mc-mods/connected-block-textures), but that mod is currently incompatible with Sodium.

**Comment by smonnnn** [comment]
@leo60228 Support for the fabric rendering api (thus also for CBT) is planned for the next release (0.2) of Sodium.

**Comment by amnotbananaama** [comment]
After discussing this on discord, this issue is being merged with #5, as it has the same cause and this incompatibility will be fixed when that issue is fixed.

Thank you for the report!
