### ISSUE TITLE
Improve fog occlusion

### ISSUE THREAD

**Issue by Lentern** [jellysquid3/Sodium#612]
**Is your feature request related to a problem? Please describe.**
This could be a good fix for #438.

**Describe the solution you'd like**
Have the client detect the current render distance, and instead of un-rendering underwater chunks that are usually not visible, display a flat color (see edited image.) I used paint.net to simulate the solid color instead of black. (2nd image)

**Describe alternatives you've considered**
I haven't considered any alternatives.

**Additional context**
![Fog Occlusion On](https://user-images.githubusercontent.com/73498459/112753325-29e23b00-8fa5-11eb-844e-7bf60466f1a6.png)
![Fog Occlusion On (Edited)](https://user-images.githubusercontent.com/73498459/112753330-2c449500-8fa5-11eb-8910-7e02ed7667db.png)

**Comment by CalXee** [comment]
Could potentially also fix Blindness + Fog occlusion. I cannot find that report though.

**Comment by Alluysl** [comment]
I can confirm that blindness is broken with fog occlusion.
