### ISSUE TITLE
Does it work in snapshots?

### ISSUE THREAD

**Issue by joaotonaco** [jellysquid3/Sodium#613]
My PC isn't so good, but I want to play in the snapshots, but my PC can't, the FPS is so much low and my PC got blue screen when I was playing (Snapshot 21w11a).

**Comment by DragonEggBedrockBreaking** [comment]
> My PC isn't so good, but I want to play in the snapshots, but my PC can't, the FPS is so much low and my PC got blue screen when I was playing (Snapshot 21w11a).

Sodium does not officially support snapshots.
