### ISSUE TITLE
Can't choose refresh rate in Sodium video settings

### ISSUE THREAD

**Issue by stevenhuyn** [jellysquid3/Sodium#617]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/18359644/112988193-4baf0e00-91af-11eb-8a21-99c50dc30830.png)
If you set the refresh rate in vanilla Minecraft while in fullscreen, it appears to affect your monitor's refresh rate using sodium fullscreen too. There is no option in Sodium to set refresh rate and thus it locks you to the refresh rate you had set in vanilla.

I'm using
> fabric-api-0.28.3+1.16
> sodium-fabric-mc1.16.3-0.1.0
> Minecraft vanilla 1.16.5 to change the fullscreen resolution

I have a high hertz monitor and couldn't work out why my monitor's refresh rate was getting locked to 60 hertz when on sodium. This only happened when I went fullscreen, my refresh rate remained 165 while not fullscreen. I ended up going into vanilla and found that upping the refresh rate there carried over to sodium (when fullscreen).

To reproduce the issue:
1. Launch vanilla 1.16.5
2. Set resolution to be fullscreen but with a lower refresh rate than your monitor's setting
3. Close and exit
4. Launch Minecraft with fabric launcher profile
5. Enter a game
6. Upon going fullscreen, you should be locked to that refresh rate

**Describe the solution you'd like**
Give an option to select refresh rate, or make it automatically select the monitor's current setting. Either works.

**Describe alternatives you've considered**

**Additional context**

**Comment by CalXee** [comment]
You mean framerate? You can set different framerate limit in the sodium UI.

**Comment by CalXee** [comment]
You mean framerate? You can set different framerate limit in the sodium UI.
If you mean there's no way to change the resolution using the Sodium UI, then that is a known issue. Press shift + P while in Sodium UI to access vanilla UI for now.
If you mean with Sodium, your FPS caps at 60 despite you having a better monitor (and you set maximum FPS above 60), then you should open a bug report not a feature suggestion. Also check if you aren't using V-sync. However again, if Sodium makes V-sync cap your FPS at 60 despite you having a better monitor, then you should open a bug report.

**Comment by stevenhuyn** [comment]
Awesome thanks, yeah didn't know about the Shift + P to change resolution (where you can choose refresh rate).

I was meaning refresh rate not FPS.

**Comment by voltflake** [comment]
I don't think this issue can be closed like that. Sodium still can't select proper monitor mode and it defaults to 60hz refresh rate. This is ridiculous.

**Comment by MeeniMc** [comment]
@voltflake Please refer to tracking issue #46 to follow progress on implementation of a solution

**Comment by russandro** [comment]
> If you mean there's no way to change the resolution using the Sodium UI, then that is a known issue. Press shift + P while in Sodium UI to access vanilla UI for now.

Absurd how they didn't implement this already.

**Comment by douira** [comment]
Implemented also by PR https://github.com/CaffeineMC/sodium-fabric/pull/2642 (in its third iteration)

**Comment by jellysquid3** [comment]
The reason it's not implemented is because the fullscreen resolution option is extremely buggy and causes problems.  

There have been multiple other issues opened to address the need for render scaling and exclusive fullscreen modes: https://github.com/CaffeineMC/sodium-fabric/issues/2362, https://github.com/CaffeineMC/sodium-fabric/issues/2359, https://github.com/CaffeineMC/sodium-fabric/issues/2361, etc.

But yes, there needs to be _some_ option, and there will be a stopgap solution implemented in the near future until the other work is completed.
