### ISSUE TITLE
Custom Entity Models Feature

### ISSUE THREAD

**Issue by Bobrokus** [jellysquid3/Sodium#625]
There's a lot of **resource packs that adds custom entity models**, I'm not sure **if Sodium has this feature**, but when I tried some packs **using this feature, it broke the models**. 

**If you know some mods** that add this feature, **let me know**!

**Comment by silversquirl** [comment]
Sodium does not and will not implement custom entity models. If you find a mod that does, it will likely require Indium to work with sodium currently
