### ISSUE TITLE
Crashes on PojavLauncher (Android) after finishing loading a game

### ISSUE THREAD

**Issue by PibePlayer** [jellysquid3/Sodium#626]
Hi!
I'm trying to use Sodium in Android with PojavLauncher on a Kirin 970, without Sodium the game works without problems. The game crashes just after loading the game and starts rendering.
I'm 99% sure that the thing that crashes the game are these lines:
`0408/045529.588046:ERROR:elf_dynamic_array_reader.h(61)] tag not found
[0408/045529.603028:ERROR:elf_dynamic_array_reader.h(61)] tag not found`

But I'll upload the full crash log anyways. 
I tried both the 1.0 stable and the last build: sodium-fabric-mc1.16.4-0.1.1+build.324.jar, changing renderer to OGL2.0 also, removing all the options like memory intrinsics, etc...

[latestlog.txt](https://github.com/CaffeineMC/sodium-fabric/files/6277148/latestlog.txt)

Thank you for your time reading this :)

**Comment by PibePlayer** [comment]
Forgot to say I'm using Java 8

**Comment by silversquirl** [comment]
That log doesn't appear to have much useful information in it. Any chance you could upload a crash report?

**Comment by PibePlayer** [comment]
Thanks for the answer. Unfortunately the app doesn't make a crash report for this, so I already uploaded the only log I currently have.
I adressed this issue on the Discord of PojavLauncher and managed to have it working disabling `Compact Vertex Forrmat` and `Fog Occlusion`. Does it help the log of the working one?

**Comment by EXPress-016** [comment]
Turn off both fog occasion and use compact vertex format then select chunk renderer oneshot gl 3.0

**Comment by jellysquid3** [comment]
Per our new [hardware support policy](https://github.com/CaffeineMC/sodium-fabric/blob/3f12f36e58d977f417d22ea6e643a9d7aeb4f0ca/README.md#-hardware-compatibility), we will not be providing any support for Pojav Launcher or any other OpenGL compatibility layers. As such, this issue is being closed as "won't fix."

**Comment by agent1243** [comment]
sodium policies are shit
