### ISSUE TITLE
Crashing when going below 0

### ISSUE THREAD

**Issue by Bendimester23** [jellysquid3/Sodium#632]
### Version

> sodium-fabric-mc1.16.4-0.1.1-SNAPSHOT

### Reproduction Steps

> 1. Go under y = 0

### Crash Report File

> [crash-2021-04-14_12.03.26-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6310071/crash-2021-04-14_12.03.26-client.txt)

**Comment by DragonEggBedrockBreaking** [comment]
This has been fixed, please update your sodium version. This is also a duplicate. Please close the issue report.

**Comment by silversquirl** [comment]
Duplicate of #587
