### ISSUE TITLE
Vanilla: 323fps, Sodium: 468fps, optifine: 986fps  | mostly same settings

### ISSUE THREAD

**Issue by angryobi** [jellysquid3/Sodium#635]
I installed sodium correctly with fabric api, phosphor and lithium in the mods folder. Everybody is saying that you get more FPS with sodium but it's not happening to me. Pls help :( The reason why I need more FPS Is, that I wanna play with fabric mods and for that I need to have sodium for good fps. 

**System: **

Ryzen 5 1600x and rx vega 64 

**Screenshots: **

![image](https://user-images.githubusercontent.com/71591883/115123882-7545a300-9fbf-11eb-8b20-a90d9b540ab4.png)

![image](https://user-images.githubusercontent.com/71591883/115123888-7c6cb100-9fbf-11eb-882e-e3a0c51d9d90.png)

![image](https://user-images.githubusercontent.com/71591883/115123892-82629200-9fbf-11eb-8ddd-ac5f118420d5.png)

**Comment by jellysquid3** [comment]
This issue is not for support inquiries. Use the [official Discord server](https://jellysquid.me/discord) to get help with the mod.
