### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by aigiz010** [jellysquid3/Sodium#637]
[crash-2021-04-18_19.42.22-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6331756/crash-2021-04-18_19.42.22-client.txt)

**Comment by jellysquid3** [comment]
You're using another mod (seemingly called `Yttr`?) which is crashing the game because it's trying to patch Sodium's code and ends up finding something unexpected. You should report the crash to them instead, as there isn't anything we can really do about it.
