### ISSUE TITLE
Custom sounds from resource packs are not loaded in Sodium

### ISSUE THREAD

**Issue by IoIxD** [jellysquid3/Sodium#639]
-------------

### Version Information

sodium-fabric-mc1.16.3-0.1.0

### Expected Behavior

The custom sounds that are present in [this resource pack](https://www.dropbox.com/s/6p8h5nqp8ssy3r2/funnyfun_v21_7.zip?dl=1) are meant to play either when I do /playsound or play then with the MythicMobs plugin.

### Actual Behavior

The tab complete for /playsound does not even show them, and they do not play unless I specifically switch to Optifine. 

### Reproduction Steps

1. Download that resource pack 
2. Go into a world with the pack and Sodium loaded.
3. Do `/playsound minecraft:custom.legendoftheninja voice @p`
4. Nothing happens.

### System Information

- Java Version: 11
- CPU: 10th gen i3
- GPU: Intel Integrated Graphics
- OS: Debian 11

### Other Information

Other mods I have are:
- Starlight 0.0.3
- Phosphor 0.7.0
- Lithium 0.6.3
- LambDynamcLights 1.3.2
- Fabric API 0.28.1
- ModMenu build 19

**Comment by jellysquid3** [comment]
Sodium does not control anything regarding resource pack behavior. Are you certain this issue only happens with Sodium and Fabric Loader (not the API) installed?

**Comment by IoIxD** [comment]
Hi, I'll test it later today but I'll close this just in case I forget.
