### ISSUE TITLE
Most options cannot be disabled by "mixin...."

### ISSUE THREAD

**Issue by Earthcomputer** [jellysquid3/Sodium#64]
### Expected Behavior
If I add `mixin.buffers = false` to the sodium config, it should disable the buffers mixins.

### Actual Behavior
`mixin.buffers` is not recongized as an option. `mixin.buffers.MixinBufferBuilder` is however recognized as an option, but trying to disable that does nothing. Applies to most config options, and possibly some in lithium too.

### Reproduction Steps
I noticed this when implementing #62. Put `mixin.buffers = false` in the config options.

### Attachments
N/A

### System Information
N/A

- Java Version: [fill me in]
N/A

**Comment by jellysquid3** [comment]
Fixed with cdfc2eb74ca46759013e0f07de34ae19b28866a3.
