### ISSUE TITLE
Bleeding Edge Builds?

### ISSUE THREAD

**Issue by xEmberx** [jellysquid3/Sodium#644]
I’m sorry if this isn’t the place to ask this, but how exactly do I get my hands on the “bleeding edge” builds of sodium.  I’m not overly familiar with Github, so I might just be blind, but I don’t see said bleeding edge builds.  Again, sorry if this isn’t the place to ask, I just don’t know where else I would.

**Comment by K0-RR** [comment]
Click on the Actions tab under the repo name - https://github.com/CaffeineMC/sodium-fabric/actions (like said in the readme btw)
Choose the newest passed (with the green tick) workflow then at the bottom you can see build-artifacts. This is the archive with the jar files. You probably want the one with the shortest name.

**Comment by xEmberx** [comment]
Oh!  Thanks, I was looking in the actions tab I just,, guess I’m blind.
