### ISSUE TITLE
Add support for Better Biome Blend

### ISSUE THREAD

**Issue by AyushGuha6** [jellysquid3/Sodium#647]
The better biome blend mod allows you to set an extremely high biome blend radius from in-game and uses a faster color blending algorithm. Currently, when used with Sodium, Sodium overwrites it.

Mod link: https://www.curseforge.com/minecraft/mc-mods/better-biome-blend

**Comment by LucilleTea** [comment]
Sodium already optimizes the biome blend algorithm to be much faster, so the bulk of this mod would be redundant.
Allowing the setting to be raised further doesn't seem like a good fit for sodium itself, but this should be very simple for an external mod to add once #75 is implemented.

**Comment by misterslime** [comment]
> Sodium already optimizes the biome blend algorithm to be much faster, so the bulk of this mod would be redundant.

Isn't BBB's algorithm faster than sodium's?
