### ISSUE TITLE
Seeing under lava/water

### ISSUE THREAD

**Issue by andreasdc** [jellysquid3/Sodium#653]
![image](https://user-images.githubusercontent.com/82218780/117502265-8e6abf80-af7f-11eb-81c9-52cc530eb50f.png)

**Comment by LucilleTea** [comment]
Please describe the problem and the situation it happens in more thoroughly, and include a log file.

**Comment by andreasdc** [comment]
@LucilleTea you see only couple chunks under the lava. As you can see it doesn't look normal.

**Comment by LucilleTea** [comment]
Lava is meant to cause limited visibility, and I am getting limited visibility both with sodium and without it.
Your screenshot looks like there is too much visibility, so please provide more detail on this specific situation (world download?) so I can try to reproduce it.
Also, include a log file so I can see your mod list.

**Comment by andreasdc** [comment]
@LucilleTea I don't think it should look bugged like that.

**Comment by andreasdc** [comment]
![image](https://user-images.githubusercontent.com/82218780/117857061-aa76a580-b28c-11eb-9e98-469f6b17b428.png)
@LucilleTea

**Comment by andreasdc** [comment]
vs normal
![image](https://user-images.githubusercontent.com/82218780/117857167-c5e1b080-b28c-11eb-8df2-8cd137f42d52.png)

**Comment by LucilleTea** [comment]
Please upload a log file - found in .minecraft/logs/latest.log
I cannot diagnose this problem without more information, it does not occur for me.

**Comment by TheMadHau5** [comment]
This issue seems to be caused by sodium culling chunks, assuming fog, even though fog is disabled using another mod.
I've run into this issue myself a few times, I don't think this is sodium's fault although a fog check during the culling might help.

**Comment by andreasdc** [comment]
@TheMadHau5 I confirm that setting fog changes seeing, but for a split second when entering/leaving lava you don't see any lava.

**Comment by TheMadHau5** [comment]
That split second is probably when the camera aligns exactly with the lava's surface, this also happens on vanilla.

**Comment by LucilleTea** [comment]
So the issue is that your separate mod disabling Sodium's fog is doing it wrong? This is why I was looking for a log file. This seems to be a problem with your other mod disabling your fog.
The split second thing does happen in vanilla too.

**Comment by andreasdc** [comment]
@LucilleTea what fog mod? Sodium extra?

**Comment by LucilleTea** [comment]
Whichever mod you are using that allows you to remove fog, this is not a feature that Sodium offers.

**Comment by TheMadHau5** [comment]
It should be possible to check if fog is enabled or not before/during the culling, so that this doesn't happen. That shouldn't be too much work, would it?
