### ISSUE TITLE
Make the video settings menu look like normal Minecraft.

### ISSUE THREAD

**Issue by MaxBr5** [jellysquid3/Sodium#655]
**Is your feature request related to a problem? Please describe.**
<pre>No offense but I detest the video settings menu for it doesn't look right.</pre> 
**Describe the solution you'd like**
<pre>Make the video settings menu the normal Minecraft video settings menu.

**Comment by MaxBr5** [comment]
<pre>No alternatives, just make it look like the normal Minecraft Video Settings Menu.</pre>

**Comment by DragonEggBedrockBreaking** [comment]
On the discord server, JellySquid has explained why the video settings screen has been changed:

> **Why doesn't Sodium use the vanilla settings menu?**
> - Functionality. The existing vanilla menu updates game settings in real time as you change options, leading to huge pauses. The sliders in Minecraft are next to impossible to control on older machines. Sodium changes the entire menu to only apply the minimum number of changes once you click "Apply", and it doesn't close the GUI so you can continue inspecting the world in the background.
>
> - Clutter. The vanilla menu is a giant list of buttons. Optifine takes this a step further and removes most of the padding, turning it into an even bigger mess of buttons. It's extremely difficult to navigate for new users, and not well organized.
>
> - Accessibility. Sodium implements a lot of different controls and features which make it easier to understand what kind of option you're dealing with. From slider controls, to toggle boxes, to selection boxes. We also need to pack a lot of information in a small space, and the current layout has proven the most effective at doing so.
>
> - Extensibility. Eventually, other mods (maybe even things like resource/shader packs) will be able to add options to Sodium's menu. The vanilla GUIs are limited and don't provide much in the realm of customization, and furthermore, would require a lot of overhead that Sodium just abstracts away. We're a simple list broken into groups and categories. It's functional out of the box with minimal tinkering.
>
> - Branding. I want Sodium to stand out in the crowd and for users to be able to easily identify its presence.

**Comment by MaxBr5** [comment]
<pre>Can't you make it normal looking or make a normal looking version?
  After all, please make the buttons look like normal minecraft buttons.</pre>

**Comment by MaxBr5** [comment]
<pre>#Will_Fix_It</pre>

**Comment by LucilleTea** [comment]
The sodium video settings menu will not be removed for the reasons above. This was discussed a bit more in #414, though this quote covers it really.

**Comment by MaxBr5** [comment]
<pre>Just make a version called Potassium with the normal Minecraft menu.</pre>

**Comment by DragonEggBedrockBreaking** [comment]
> Just make a version called Potassium with the normal Minecraft menu.

Well firstly, a mod called potassium exists, so a different name needs to be used, secondly, there is no space for the new options that sodium adds, so you will basically have to edit a physical file on your drive every time you want to change a sodium specific option, and thirdly, two versions of a mod to maintain is not as easy as it seems, especially likely vastly different versions. It is difficult enough as it is for CaffeineMC to maintain four different mods. If you really need this, there is a hacky mod that is probably unstable that reverts the sodium options menu back. Search around on modrinth, you will probably easily find it.
