### ISSUE TITLE
My GPU is probably blacklisted so I can't use MultiDraw 4.3 and if I disable blacklist this happens I want to use 4.3 GL so help me please

### ISSUE THREAD

**Issue by d0pLeR** [jellysquid3/Sodium#656]
Hi ! 
My issue is:
I don't see MultiDraw GL 4.3 on my `Advanced` Settings Tab.
Why I need MultiDraw GL 4.3 is I don't have a better performance with Sodium Lithium Phosphor than OptFine
And a lot of video said Sodium is x8 better than optifine and some Reddit posts as well...
System : 
RX 570 8GB Pulse Sapphire GDDR5 256-Bit
I5-9400F 2.40 GHZ Max 4 GHZ
16 GB RAM
256 GB SSD
75 Hertz IPS Panel Samsung Monitor 1920 x 1080

Settings For MC:
Allocated 8 GB RAM
Graphic Settings:
View Distance 16 Chunks
Bright 
Clouds On Fancy
GUI Scale x3
Fullscreen
V-Sync Off
Max FPS = Unlimited
View Bobbing = Off
Graphics Quality = Fast
Weather Quality = Fast
Particle Quality = High
Smooth Lightning = High
Biome Blend 2 Block(s)
Entity Distance %100
Entity Shadows On
Vignette Off
Mipmap Levels 2x
Chunk Renderer = Oneshot GL (2.0) not 3.0 due to lower FPS
![2021-05-10_18 49 09](https://user-images.githubusercontent.com/83969409/117687404-70d86880-b1c0-11eb-9aa4-6f6242d341cb.png)
When I disable driver blacklist and open MultiDraw GL 4.3 this happens
I do want to use CaffeineMC mods
And I want to use MultiDraw GL 4.3 because everyone says more FPS more speed less lag and else
I don't know programming - coding etc.
I hope @jellysquid3 replies to me
Thank you everyone

**Comment by FlashyReese** [comment]
This issue has been fixed in the development branch which has not been released yet. You can try them following the instructions at https://github.com/CaffeineMC/sodium-fabric#bleeding-edge-builds-unstable
