### ISSUE TITLE
[Suggestion] Option for default menu formatting

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#661]
**Is your feature request related to a problem? Please describe.**
Many people, including me, probably prefer the Vanilla Minecraft settings layout. The Sodium one is quite ugly and hard to use.

**Describe the solution you'd like**
An option for disabling the custom settings menu.

**Describe alternatives you've considered**
Removing Sodium and going back to Optifine is good. Sodium gives no fps boost over OF(both around 60 fps, vanilla is 40)(I do have vSync on though for smooth gameplay)

**Comment by amnotbananaama** [comment]
Echoing [my previous response](https://github.com/CaffeineMC/sodium-fabric/issues/414#issuecomment-739527013)  about this topic (emphasis mine).
> Jelly has already written [an extensive write up](https://discord.com/channels/602796788608401408/651120262129123330/736290022734561302) in the [discord](https://jellysquid.me/discord) about why the Video Settings GUI is redesigned by Sodium. **Constructive feedback on the design, functionality, and layout of the GUI is always welcome.**

Several people have complained about the look of the Video Settings GUI, but comments like "[it looks] quite ugly" don't help us improve it.  If you (or anyone) can offer feedback on how to improve the GUI we would be happy to consider it.

Our discord server that I linked above includes several mockups and image suggestions if you'd like to look at those.

**Comment by ghost** [comment]
Sorry.  I didn't mean to be rude.
I also thought I added a message saying an option for it to look like the other menus would be good.

**Comment by ghost** [comment]
But I see now that this is a duplication of #655 as well

**Comment by ghost** [comment]
But maybe, it would be possible for the current menu to be accessible via a hotkey or ModMenu.
Then the default Video Settings menu could be vanilla styled?

**Comment by DragonEggBedrockBreaking** [comment]
> But maybe, it would be possible for the current menu to be accessible via a hotkey or ModMenu.
> Then the default Video Settings menu could be vanilla styled?

The default one is available if you press Shift + P, but most of the options there do not work and are overwritten by the ones in the sodium menu. The ones that do work are the render distance slider, and anything that is not in the sodium menu (e.g. Static FOV)
