### ISSUE TITLE
Use fancy graphics settings for nearby chunks and fast for chunks further away?

### ISSUE THREAD

**Issue by p-z-l** [jellysquid3/Sodium#662]
**Is your feature request related to a problem? Please describe.**
My computer is not very beefy and it can run on 60 fps on fast graphics and ~40fps on fancy graphics (at 20 chunks render distance). But I just absolutely hate the look of non-translucent leave blocks in the fast graphics settings. So maybe something like this may be helpful.

**Describe the solution you'd like**
Maybe use fancy graphics settings for chunks inside radius of 2 and fast for chunks outside radius of 2. And maybe disable smooth lighting or even render less vertices on client side for chunks far away to boost even more performance? I don't know if any of these is possible though, I just started learning OpenGL recently and I have no idea how Minecraft build and render chunks.

**Describe alternatives you've considered**
If the above are not possible, maybe Sodium can offer an option to only use fancy graphics for leave blocks and fast for everything else, that would be helpful too.

**Comment by K0-RR** [comment]
Something like this https://github.com/PorkStudios/FarPlaneTwo would be nice.

**Comment by p-z-l** [comment]
Yeah but probably less crazy

**Comment by Genau6502** [comment]
20 render distance is a bit excessive if you can't run it well

**Comment by Rajbir98** [comment]
my pc is super low end i am happy with 8 chunks render distance with 150 fps
