### ISSUE TITLE
Not helping FPS

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#664]
### Version Information

Sodium mc1.16.3-0.1.0 for 1.16.5

### Expected Behavior

Should boost my FPS

### Actual Behavior

FPS is staying the same as without the mod

### Reproduction Steps

It did not crash, it just doesn't help

### System Information

> - Java Version: [Fabric 1.16.5]
> - CPU: [i7-1065G7 Processor]
> - GPU: [gtx 1660 ti max-q]

### Other Information

I am using a few other mods:

Lithium mc1.16.5-0.6.4
Phosphor 0.7.2 for Minecraft 1.16.2+

**Comment by LucilleTea** [comment]
The issue tracker is for bug reports, this support issue is better suited to the [discord community](https://jellysquid.me/discord).
