### ISSUE TITLE
Chunks are never unloaded after teleporting away from an area

### ISSUE THREAD

**Issue by bytzo** [jellysquid3/Sodium#673]
### Version Information
Occurs on 1.16.x/next.

Does not occur with Sodium 0.1.0.

### Expected Behavior

When teleporting, the chunks around the player before teleporting away should be unloaded.

### Actual Behavior
The chunks around the player before teleporting away remain loaded. This can cause performance issues with garbage collection, as memory begins to quickly fill up.

### Reproduction Steps

1. Create a new world and open the debug screen. Note the amount of chunks loaded.
2. Teleport somewhere far away. ie `/tp ~500 ~ ~500`.
3. Note how the amount of chunks loaded increases. The chunks around the previous location are not unloaded.

**Comment by coderbot16** [comment]
Chunks also appear to not be unloaded when reducing render distance, it's likely that the underlying issue is the same.
