### ISSUE TITLE
Game crashes when I join a new world/server (sodium issue) (was working fine the day before)

### ISSUE THREAD

**Issue by Frostyedd** [jellysquid3/Sodium#679]
[crash-2021-06-10_17.07.56-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6631626/crash-2021-06-10_17.07.56-client.txt)

**Comment by FlashyReese** [comment]
Looks like your configuration file is corrupted, you can workaround this by deleting the config file at `.minecraft/config/sodium-options.json`

**Comment by LucilleTea** [comment]
Yes.
Anyway, duplicate of #219
