### ISSUE TITLE
Game crash when launching

### ISSUE THREAD

**Issue by Kittenboss1** [jellysquid3/Sodium#680]
My game crashes when I try to load up a 1.16.3 version of sodium, I think this is because the 1.16.3 release has for some reason been changed to 1.16.5 so it is not compatible and is very easy to get the two versions mixed up

**Comment by jellysquid3** [comment]
Provide a crash log. We have issue templates for a reason.

**Comment by jellysquid3** [comment]
Closing as invalid due to lack of any information.
