### ISSUE TITLE
Lag armor stand fully crashes game

### ISSUE THREAD

**Issue by YurniKismet** [jellysquid3/Sodium#685]
MC version: 1.16.5, Sodium version 1.10
### Reproduction Steps

So this is going to be weird, I'm an item maker anything from oppvp to lag and crash items.
When using one of my lag items on someone in game it full on crashed them, this is abnormal and after some testing we
concluded it was sodium's fault here are the steps.
> 1: run the command [here](https://pastebin.com/mpjD52h5) in a CMD block
> 2: place the armor stand
> 3: game closes with no crash report

### Crash Report File

None

**Comment by amnotbananaama** [comment]
Can you provide a log file since no crash log is available?

This sounds like #218 which has been fixed in 0.2.

EDIT: Your pastebin with the command is either private or was autoremoved for some reason

**Comment by ghost** [comment]
since no crash logs, the following user cant provide logs either. i was the one who he was testing on.

**Comment by jellysquid3** [comment]
Closing as we lack the information to properly diagnose this problem.
