### ISSUE TITLE
Setting render distance to 3 or lower in fabulous graphics makes clouds stick in place on screen

### ISSUE THREAD

**Issue by LucilleTea** [jellysquid3/Sodium#686]
### Version Information

mc1.16.5-0.2.0-rc6

### Expected Behavior

Setting the render distance to 3 or lower is meant to hide clouds.

### Actual Behavior

The separate fabulous framebuffer for clouds is not cleared, leading to the same effect as #79 

### Reproduction Steps

Enable fabulous graphics and clouds
Set your render distance higher than 3
Look at clouds
Set your render distance to 3 or 2
Move the camera

### Other Information

Screenshot from a discord report:
https://cdn.discordapp.com/attachments/778685768041627719/853454610462933012/2021-06-12_19.02.31.png

**Comment by MeeniMc** [comment]
This is resolved in (at least) 0.4.10; probably got resolved with the new cloud rendering PR.
