### ISSUE TITLE
Iris fork for sodium affects settings

### ISSUE THREAD

**Issue by BleepFTB** [jellysquid3/Sodium#688]
Sodium causes an issue with opening Video Settings when Iris is installed with the fork for sodium.
![Minecraft_ 1 16 5 14_06_2021 23_15_05](https://user-images.githubusercontent.com/84580842/121966387-78ae9e00-cd66-11eb-93db-1be37b1fec07.png)

**Comment by amnotbananaama** [comment]
We cannot accept bug reports for forks/unofficial versions of Sodium, as we have no control or insight into them. You should seek support from the authors of that fork or general mod support forums. If you can reproduce a new crash with **the official** version of Sodium, feel free to open a report
