### ISSUE TITLE
Add option to disable fog

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#69]
**Is your feature request related to a problem? Please describe.**
No,just a handy feature.
**Describe the solution you'd like**
an option in the quality tab to disable fog
**Describe alternatives you've considered**
[Carpet mod's](https://github.com/gnembon/fabric-carpet) fog off feature but due to changes that sodium does to fog it doesn't work.
**Additional context**
None.

**Comment by aydendevnova** [comment]
Yeah, the fog on AMD / Intel GPU's are half a**ed in minecraft, so the fog is only where you're looking at, so it's useless to have enabled.

Edit: this mod fixes fog on amd drivers (if you're using opengl3)

**Comment by LucilleTea** [comment]
Removing fog is considered too cheaty for sodium, so the feature was removed. You can do this with other mods (tweakeroo at least).
Sodium implements proper fog on AMD/Intel GPUs, so they have the same fog as Nvidia GPUs.

**Comment by aydendevnova** [comment]
> Removing fog is considered too cheaty for sodium, so the feature was removed. You can do this with other mods (tweakeroo at least).
> Sodium implements proper fog on AMD/Intel GPUs, so they have the same fog as Nvidia GPUs.

Yeah I actually agree with this, especially with the nether, honestly I feel this mod _needs_ to be used by Mojang, because it's insane how I can feel like I'm playing bedrock edition on java edition cause it's so smooth with this mod!

**Comment by ghost** [comment]
> Removing fog is considered too cheaty for sodium, so the feature was removed. You can do this with other mods (tweakeroo at least).
> Sodium implements proper fog on AMD/Intel GPUs, so they have the same fog as Nvidia GPUs.

sodium changed the fog I know which just broke carpet's fog off feature,are you sure that the tweakeroo option will function(haven't tried but I will do it later)
as for the cheaty part,I don't think so since it's just a visual effect,on top of that the fog takes some space off of your render distance just go to the end with a render distance of 7 or 5 you can't see some end pillars unless you move around which maybe annoying when fighting the dragon,
anyways huge thanks to @jellysquid3 and all who contributed to make this amazing mod,
truly appreciated

**Comment by ghost** [comment]
the only circumstance I may count it as cheating is when you're using max render distance (which is highly unlikely in my opinion)It may give you a little bit of advantage over others in that you can see player further away because fog isn't interrupting you.

**Comment by DonSerrot** [comment]
I've personally always seen the fog as Mojang's way to hide the ugly render distance borders and not anything more. In a multiplayer situation I don't see it having any effect because a server is going to limit the render distance anyway so fog or no fog really doesn't matter. That said, I don't PVP so I don't really have any real experience to go off there. Most survival servers I've seen have the render distance limited to 10 chunks. Even setting yourself to 16 is enough to push the fog out. I'd say giving people with lower end machines the option to get the most out a lower render distance would be exactly the kind of feature an optimization mod should have.

**Comment by ghost** [comment]
@Lucy-t 
Tweakeroo succeeded at disabling the fog,
thank you

**Comment by ghost** [comment]
Closing since it's fixed in https://github.com/jellysquid3/sodium-fabric/commit/0e992e7af370a9e666d9c3b4510c6008f1f3bf58
