### ISSUE TITLE
Fix 32-bit sound precision loss in vanila minecraft?

### ISSUE THREAD

**Issue by AggressiveCombo** [jellysquid3/Sodium#697]
There's a bug in vanilla for a long time now, where going far away from the world, sound loses precision. This also possibly causes sculk sensor losing sound detection precision where being far from the world spawn.

Somewhere in the game's files, there is used a float type for sound precision and to fix it, change it to a double.

https://bugs.mojang.com/browse/MC-191170
https://bugs.mojang.com/browse/MC-207260

Thanks! (there's also some other precision loss isues in vanilla)

**Comment by Leo40Git** [comment]
This is probably a server-side patch, meaning it doesn't fit with Sodium's client-only optimizations/fixes.

This would probably be a Lithium thing, though.

**Comment by jellysquid3** [comment]
As mentioned by Leo, this is a server-side issue. By the time the client has received any positional data it's already too late to correct the problem.
