### ISSUE TITLE
Crash when entering a world

### ISSUE THREAD

**Issue by Bonaerense** [jellysquid3/Sodium#698]
This game crash occurs like 3 seconds after entering my world. It renders my house (I left it there), when renders outside chunks it simply crashes.
Fabric version: 0.11.5
Fabric API version: 0.35.0
Minecraft version: 1.16.5
Sodium version: LATEST (0.2.0, it started happening when I updated to the latest version)
My PC specs:
OS: Windows 7 Professional 32 bits
GPU: Intel Graphics Media Accelerator 3600 series
RAM: 1 GB
CPU: Intel Atom N2600

Error log:
[hs_err_pid3896.log](https://github.com/CaffeineMC/sodium-fabric/files/6679650/hs_err_pid3896.log)

**Comment by amnotbananaama** [comment]
Can you reproduce the issue with 0.3.0?

**Comment by Bonaerense** [comment]
> Can you reproduce the issue with 0.3.0?

I'm in windows 7 32 bits, I can't play minecraft 1.17+.
Anyways, I will try to load it on 1.16.5
