### ISSUE TITLE
Potions not rendering liquid inside bottles

### ISSUE THREAD

**Issue by ArchitektRadim** [jellysquid3/Sodium#70]
### Expected Behavior
Potions show colored fluid inside the glass bottles

### Actual Behavior
Potions are being rendered as empty bottles

### Attachments
<a href="https://imgbb.com/"><img src="https://i.ibb.co/xYMX6GL/obrazek.png" alt="obrazek" border="0"></a>

### System Information
Ryzen 7 2700X
GTX 1660, driver 445.87

Java Version:
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
-XX:+UnlockExperimentalVMOptions -XX:+UseZGC

**Comment by ghost** [comment]
Actually,
On my game spawn eggs,potions,leather armour(undyed,haven't tried it with them dyed) have wrong colors 
for the leather armour it get fixed by enchanting it.

**Comment by jellysquid3** [comment]
Fixed with ad16c9f.
