### ISSUE TITLE
Unexpected Fatal Crash While Initializing Game.

### ISSUE THREAD

**Issue by VeiTheOne** [jellysquid3/Sodium#700]
### Version

I'm using 

sodium-fabric-mc1.16.3-0.1.0

### Reproduction Steps

I honestly don't know how to properly remake it, as part of me thinks it's an issue with my integrated graphics or CPU.

But all I did was load the game with Sodium, Phosphor, and Lithium, along with a bunch of other client-side mods.

Cause just about as soon as the game window loads up, it almost immediately closes on itself, and then I get the error:
**org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered**.

### Crash Report File

[crash-2021-06-19_10.30.09-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6680854/crash-2021-06-19_10.30.09-client.txt)

### Additional Information

No crash when I remove sodium but leave the others.
I've had this issue before, but was to lazy to report it.

**Comment by Kroppeb** [comment]
sodium 0.2 has been released, could you see if it's still an issue in the newest version?

**Comment by VeiTheOne** [comment]
Where's the DL location at?

Still confused about Git's layout

**Comment by amnotbananaama** [comment]
https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.16.5-0.2.0

**Comment by VeiTheOne** [comment]
I was gonna say, I just found the Release page. 😄

**Comment by VeiTheOne** [comment]
And No Crash In the Initializing phase. Thx!
