### ISSUE TITLE
Unable to render on PojavLauncher iOS

### ISSUE THREAD

**Issue by NotAHero04** [jellysquid3/Sodium#706]
### Version Information
mc1.16.5-0.2.0+build.4
### Expected Behavior
The game would render normally.
### Actual Behavior
The game can not render blocks but can render mobs.
### Reproduction Steps
1/1 Enter a world and wait for the game to render. 
### System Information
> - Java Version: 16
> - CPU: (the game says ‘unknown’, maybe pojavlauncher sucks) 2x 1.40 GHz Apple A8
> - GPU: (the game says nothing, maybe pojavlauncher sucks, again) Apple A8 GPU

### Other Information
Other mod i am using: 

antighost-1.16.5-fabric0.30.0-1.1.3
architectury-1.17.22-fabric
betterbeds-1.1.0
cloth-config-4.11.26-fabric
cullleaves-2.1.0
fabric-api-0.35.1+1.16
fabric-language-kotlin-1.6.1+kotlin.1.5.10
fast-chest-1.2+1.16
ferritecore-2.0.4-fabric
hydrogen-fabric-mc1.16.5-0.2
lambdynamiclights-fabric-1.3.4+1.16
lazydfu-0.1.2
lithium-fabric-mc1.16.5-0.6.4
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2
modmenu-1.16.9
nofade-1.16.5-1.0.1
notenoughcrashes-3.2.0-fabric
okzoomer-4.0.1+1.16.2
slight-gui-modifications-1.7.1
smoothboot-fabric-1.16.5-1.6.0
sodium-extra-0.2.6
~~starlight-forge-1.0.0-RC2-1.16.5~~ (incorrect starlight but never be loaded by fabric)

A screenshot of the bug:

https://share.icloud.com/photos/054UO1aGrIXmLhnGwaZrdKekA

Here is the configuration file:
{
  "quality": {
    "cloud_quality": "FAST",
    "weather_quality": "FANCY",
    "enable_vignette": true,
    "enable_clouds": false,
    "smooth_lighting": "LOW"
  },
  "advanced": {
    "use_vertex_array_objects": true,
    "use_chunk_multidraw": true,
    "animate_only_visible_textures": true,
    "use_entity_culling": true,
    "use_particle_culling": true,
    "use_fog_occlusion": false,
    "use_compact_vertex_format": false,
    "use_block_face_culling": true,
    "allow_direct_memory_access": true,
    "ignore_driver_blacklist": false
  },
  "notifications": {
    "hide_donation_button": false
  }
}

**Comment by clashingnoob** [comment]
Just play minecraft java on pc or play mcpe lol

**Comment by jellysquid3** [comment]
@clashingnoob Keep the nonconstructive remarks to yourself or you will be banned from this issue tracker.

**Comment by re2cc** [comment]
Sorry if I am wrong, but are you using the forge version of starlight in fabric?

**Comment by jellysquid3** [comment]
Try disabling the "Compact Vertex Format" in Video Settings > Advanced. This tends to cause problems with mobile devices, presumably due to a lack of proper support.

**Comment by NotAHero04** [comment]
Yes, i turned off compact vertex format and fog occlusion.

**Comment by NotAHero04** [comment]
I found that starlight version i used is incorrect, but it was unloaded when loading minecraft so it would not be a problem.

**Comment by NotAHero04** [comment]
A tester with Zink (OpenGL 4.6 compatibility profile) succeeded in having Sodium rendered properly. Does this version require OpenGL 3 or later? If this is true then (because I am using OpenGL 2) l will not get Sodium rendered.

**Comment by iamSlightlyWind** [comment]
Sorry for bumping this, but Compact Vertex Format doesn't seem to be an option anymore in [mc1.17.1-0.3.4](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.4), and without changing it, I still get crashes when joining a server/world. Is there a way to disable it by editing the config files in `.minecraft/config` ? Thanks!

Edit: so apparently the option is (?removed) for quite some time now, is there anything that I can do to fix this?

**Comment by Phoenix-Starlight** [comment]
1.17 does require OpenGL 3, 3.2+ @NotAHero04

**Comment by pajicadvance** [comment]
Pojav Launcher is unsupported by most versions of Sodium. The "patch" that they provide for 1.17+ versions of Sodium disable almost the entirety of the mod, and should not be considered a solution.
