### ISSUE TITLE
AMD FidelityFX Super Resolution?

### ISSUE THREAD

**Issue by JSpielz** [jellysquid3/Sodium#707]
**Is your feature request related to a problem? Please describe.**
Not necessarily related to an issue I'm having specifically, but I think everyone would agree that it would be nice to run Minecraft at higher FPS or at the same FPS with more GPU overhead. 

**Describe the solution you'd like**
AMD recently released FSR (FidelityFX Super Resolution), which is a super sampling method similar to DLSS that does not use deep learning and is able to run on most GPUs made in the past 5 years (AMD + Nvidia). From what I've heard/seen, specifically at the high quality settings, native resolutions and the upscaled FSR versions look identical but the FSR version runs at much higher frame rates. For example, in Godfall at Epic settings, native 4K ran at 70 avg fps and the Ultra setting upscaled with FSR ran at 100fps avg while looking practically identical on a 6800XT. In the same game with the same GPU, 4K FSR set to performance (1080 upscaled to 4k if I remember correctly) ran at 151 average FPS, though it did look noticeably softer than 4k, but still better than native 1080. FSR requires no special hardware, other than a not old GPU. I think it would be cool to have a toggle to turn it on/off and adjust the different modes, as long as there is a warning saying it may not work on older systems. I am not a developer so I have no idea how much work it would be or if it's even possible, but FSR is supposed to be very easy to implement according to many game developers.

Here is a pretty detailed video about FSR by Hardware Unboxed on YouTube: https://www.youtube.com/watch?v=yFZAo6xItOI&ab_channel=HardwareUnboxedHardwareUnboxed 

Again, not sure if this is possible, but I thought it was worth it to put it on your radar if you didn't already know about it.

**Comment by billw1** [comment]
[their site](https://gpuopen.com/fidelityfx-superresolution/) says that it only supports DX11, DX12 and Vulkan

**Comment by silversquirl** [comment]
To add on to billw1's comment, this means it is not usable by Sodium, since Sodium uses OpenGL, rather than DirectX or Vulkan.
