### ISSUE TITLE
Crashing when launching the game

### ISSUE THREAD

**Issue by LucasJLBraz** [jellysquid3/Sodium#708]
### Version
> Minecraft Version:  1.17
> Fabric Version: 0.11.6
> Sodium Version: sodium-fabric-mc1.16.5-0.2.0+build.4

### Reproduction Steps

> 1. Open minecraft launcher
> 2. Click Play
> 3. Crash

### Crash Report File

https://gist.github.com/Apollyion/1991a36e1c2f9b902da08bd7392daa7d

**Comment by LucilleTea** [comment]
sodium for 1.16.5 does not work on 1.17
