### ISSUE TITLE
Support for item textures with modified NBT tag

### ISSUE THREAD

**Issue by Niksette** [jellysquid3/Sodium#709]
Is it possible to modify the sodium to be able to use texture packs with renaming the NBT tag? 
For example, several options for textures for the Totem of Undying, which is named by the nickname of a certain player.

![huge_2021-06-24_09 14 58](https://user-images.githubusercontent.com/75724507/123212244-37885d80-d4cd-11eb-8623-4d71c728b60d.png)

![2021-06-24_09 16 45](https://user-images.githubusercontent.com/75724507/123212271-3fe09880-d4cd-11eb-82bd-910e1a445d89.png)

**Comment by KN13KOMETA** [comment]
I think it's a good idea.

**Comment by AydarVess** [comment]
Just take my money and create this for me

**Comment by LucilleTea** [comment]
Sodium is an optimization mod, not a kitchen sink feature mod, so this is out of scope.
In this case you are looking for Chime - though it does not support the optifine format for these resource packs, only it's own.
https://www.curseforge.com/minecraft/mc-mods/chime-fabric
https://modrinth.com/mod/chime
https://github.com/emilyalexandra/chime
