### ISSUE TITLE
Adding Dynamic Lights

### ISSUE THREAD

**Issue by AnErrupTion** [jellysquid3/Sodium#71]
**Is your feature request related to a problem? Please describe.**
No, it's just a nice and sometimes time-saving feature.

**Describe the solution you'd like**
Be able to, with a torch or any similar item, emit light without placing the torch or the similar item.

**Describe alternatives you've considered**
OptiFine, it's the only project that has this feature.

**Additional context**
None.

**Comment by jaskarth** [comment]
Dynamic lights will not be added to Sodium. Instead, you can use this mod https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights .

**Comment by AnErrupTion** [comment]
Thanks :p

**Comment by sh-lucas** [comment]
> Dynamic lights will not be added to Sodium. Instead, you can use this mod https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights .

that mod is extremely laggy and buggy. It think would be good to see it implemented in sodium

**Comment by LambdAurora** [comment]
> that mod is extremely laggy and buggy. It think would be good to see it implemented in sodium

It doesn't change the fact that it's a feature that is completely out of scope of this mod.

I'm not sure why you think it's buggy? The lag claims I can understand though, it's partially caused by either mods or the base game forcing every chunk rebuilds to be blocking, while if it's deferred it usually yields better performances.

Also, this is a closed issue.

**Comment by OttCS** [comment]
There's a couple shaderpacks that add dynamic handlights with almost no performance impact, if you're willing to download the IRIS fork of Sodium. (The IRIS fork of Sodium has a built-in feature for getting the block light value of held items)

[GravityShade](https://github.com/OttCS/GravityShade) is a great low-impact option that provides a great warm, filmic feel (and dynamic lights). If your computer is beefy, Complementary Shaders is widely accepted as one of the best shaders (which also has dynamic lights).

![GravityShade_DynamicLight](https://user-images.githubusercontent.com/76815426/148880512-6fd93eab-657e-414f-978c-537828089921.png)GravityShade Screenshot

**Comment by coderbot16** [comment]
Note that Iris is not a fork of Sodium, it's a shader mod that works with Sodium, though from the user perspective a compatible version of Sodium downloaded separately is required to use Sodium.

**Comment by BlueStarBRS** [comment]
> Dynamic lights will not be added to Sodium. Instead, you can use this mod https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights .

pls add this option it rly suck to waiting everytime so long for a update of a dynamic light mod
