### ISSUE TITLE
Game Crashed After Joining a Server

### ISSUE THREAD

**Issue by danni-boii** [jellysquid3/Sodium#712]
### Version

> sodium-fabric-mc1.16.5-0.2.0+build.4
> sodium-fabric-mc1.16.5-0.2.0+IRIS2-rev.31828aa
> sodium-fabric-mc1.16.3-0.1.0.jar

### Reproduction Steps

> Playing some old map in the single player is fine.
> But, when I tried to join the server with mods on, it would indicate to me that sodium crashed my game.
> No sure why this is happening.

### Crash Report File

[crash-2021-06-26_14.31.46-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6719667/crash-2021-06-26_14.31.46-client.txt)

### Additional Information

> I have tried all these 3 versions of sodium and the problem remains unsolved.
> I can join the server after removing sodium.

**Comment by jellysquid3** [comment]
Please upload a complete client log file from when this error occurred. It looks like the problem was not captured by the crash report.

**Comment by Youmiel** [comment]
Same issue, but this happens randomly on my computer, and joining server/moving into new chunks have chances crashing the game.<br>
#### Crash report
[crash-2021-07-01_08.14.34-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6744579/crash-2021-07-01_08.14.34-client.txt)
#### Mod list:
- amecs-1.3.4+mc.21w16a
- fabric-api-0.34.9+1.17
- fabric-carpet-1.17-1.4.40+v210608
- sodium-fabric-mc1.17-0.3.0+build.445
- notenoughcrashes-3.3.0+1.17-fabric

**Comment by jellysquid3** [comment]
@Youmiel Your issue is not related to this and was fixed in the official Sodium 0.3 release.

**Comment by jellysquid3** [comment]
Closing as required information is missing to diagnose this problem.
