### ISSUE TITLE
Frequent crashed when playing on server, probably when loading chunks

### ISSUE THREAD

**Issue by boasbakker** [jellysquid3/Sodium#713]
Version

sodium-fabric-mc1.17-0.3.0+unknown (newest 1.17-dev commit at the time of making this)
> 
Reproduction Steps

1. Join a server
2. Fly arround a little bit
3. Game crashes
This happened 8 times in one hour, and notenoughcrashes always said it was caused by sodium.\
It was not one specific chunks that always crashed my game, 3 times the game crashed when I went through the nether portal to my house, but also 4 times not.

 Crash Report File

[crash-2021-06-25_22.38.00-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6719772/crash-2021-06-25_22.38.00-client.txt)
[crash-2021-06-25_22.33.42-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6719773/crash-2021-06-25_22.33.42-client.txt)
[crash-2021-06-25_22.27.01-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6719774/crash-2021-06-25_22.27.01-client.txt)
[crash-2021-06-25_22.20.49-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6719775/crash-2021-06-25_22.20.49-client.txt)
[crash-2021-06-25_21.51.01-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6719776/crash-2021-06-25_21.51.01-client.txt)
[crash-2021-06-25_21.26.05-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6719777/crash-2021-06-25_21.26.05-client.txt)
[crash-2021-06-25_20.42.39-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6719778/crash-2021-06-25_20.42.39-client.txt)
[crash-2021-06-25_22.52.59-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6719779/crash-2021-06-25_22.52.59-client.txt)
[crash-2021-06-25_18.54.53-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6719780/crash-2021-06-25_18.54.53-client.txt)
[crash-2021-06-26_09.42.00-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6719781/crash-2021-06-26_09.42.00-client.txt)
All these crashed were caused by sodium.

**Comment by mini** [comment]
I'm experiencing this as well. Especially with nether portals but also just sprinting in the overworld
[crash-2021-06-21_19.46.17-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6720025/crash-2021-06-21_19.46.17-client.txt) (this was my earliest crash, a few days ago)
[crash-2021-06-25_19.20.44-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6720021/crash-2021-06-25_19.20.44-client.txt)
[crash-2021-06-25_19.23.40-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6720022/crash-2021-06-25_19.23.40-client.txt)

**Comment by boasbakker** [comment]
Yeah, it seams to be related to loading chunks. Flying arround also can cause it.

**Comment by mini** [comment]
oh, this seems like a duplicate issue
see #705

**Comment by boasbakker** [comment]
Oh I see, OK.
Good to see he knows about it.
