### ISSUE TITLE
Release 0.2.0 to CurseForge

### ISSUE THREAD

**Issue by leetfin** [jellysquid3/Sodium#715]
**Is your feature request related to a problem? Please describe.**
The newest release of Sodium is not available on CurseForge

**Describe the solution you'd like**
Release 0.2.0 uploaded to CurseForge

**Additional context**
I did a quick search of the issues and didn't find anything related, not sure if there's a reason that it's not there already. If there is, sorry to bother you!

Thanks for the awesome mod, it's really helpful!

**Comment by pajicadvance** [comment]
The developer is currently having problems with their CurseForge account. We don't know when it's going to be sorted out.

**Comment by amnotbananaama** [comment]
This is planned, Jelly is just having issues with her CF account at the moment. Hopefully they will be resolved soon

**Comment by leetfin** [comment]
Alright, thank you for the answer!
