### ISSUE TITLE
Blocks not stitching

### ISSUE THREAD

**Issue by SwedishAddict** [jellysquid3/Sodium#718]
Fabric version: fabric-loader-0.11.6-1.16.5
Mod version: sodium-fabric-mc1.16.3-0.1.0

Blocks not stitching, seeing sky/void on the edges of block that are further than around 10 blocks away from me.

**Comment by jellysquid3** [comment]
Provide screenshots and a client log file. There's not enough information to debug the issue otherwise.

**Comment by Kroppeb** [comment]
Consider updating to Sodium 0.2.0:
[https://modrinth.com/mod/sodium/version/YAGZ1cCS](https://modrinth.com/mod/sodium/version/YAGZ1cCS)

**Comment by SwedishAddict** [comment]
> Consider updating to Sodium 0.2.0:
> https://modrinth.com/mod/sodium/version/YAGZ1cCS

Did not help :/

**Comment by SwedishAddict** [comment]
> Provide screenshots and a client log file. There's not enough information to debug the issue otherwise.

Which log file? latest.txt or debug.txt?
Here's the screenshot https://imgur.com/s4Rtwk2

**Comment by SwedishAddict** [comment]
> Consider updating to Sodium 0.2.0:
> https://modrinth.com/mod/sodium/version/YAGZ1cCS

**Comment by LucilleTea** [comment]
To me your image looks like #173, which is caused by having settings such as anisotropic filtering forcibly enabled in your nvidia control panel. Please ensure you don't have any of these overrides.

If this is not your problem, we need much more information to do anything. This is why the issue template you deleted exists. Please provide the full information asked for by the template.

**Comment by SwedishAddict** [comment]
> To me your image looks like #173, which is caused by having settings such as anisotropic filtering forcibly enabled in your nvidia control panel. Please ensure you don't have any of these overrides.
> 
> If this is not your problem, we need much more information to do anything. This is why the issue template you deleted exists. Please provide the full information asked for by the template.

It worked, thank you :)
