### ISSUE TITLE
Wrong color of Potions

### ISSUE THREAD

**Issue by ArchitektRadim** [jellysquid3/Sodium#72]
### Expected Behavior
Potions in Minecraft should have specific colors which makes them easy to be quickly recognized

### Actual Behavior
Colors of potions are mismatched (for example Water Breathing should be blue, but it's red and Fire Resistance should be orange, but it's purple)

### Attachments
<a href="https://imgbb.com/"><img src="https://i.ibb.co/5Gjgd27/obrazek.png" alt="obrazek" border="0"></a><br /><a target='_blank' href='https://cs.imgbb.com/'></a><br />

### System Information
GTX 1660, driver 445.87

Java Version:
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
-XX:+UnlockExperimentalVMOptions -XX:+UseZGC

**Comment by jellysquid3** [comment]
Are you using the latest revision of Sodium on GitHub? This issue should already be fixed.

**Comment by ArchitektRadim** [comment]
> 
> 
> Are you using the latest revision of Sodium on GitHub? This issue should already be fixed.

**Comment by ArchitektRadim** [comment]
> 
> 
> Are you using the latest revision of Sodium on GitHub? This issue should already be fixed.

Yes, previously it wasn't rendering any colors. I recompiled the mod after it was fixed and now it behaves like this.

**Comment by Heitzenberg** [comment]
Can confirm.

**Comment by jellysquid3** [comment]
This should now definitely be fixed with ca8902c.
