### ISSUE TITLE
Cannot load fabric

### ISSUE THREAD

**Issue by CrossDeveloper09** [jellysquid3/Sodium#721]
Fabric 1.17 glitch

------------------------

1.17 Version

> Replace this text with the exact version of the mod you are using. Every part of the version is important! If you
> do not know what version you are using, look at the file name in your "mods" folder.
>
> Example: mc1.16.4-0.1.1+rev.4b3964a
> 
### Reproduction Steps

Run the game

**Comment by Leo40Git** [comment]
Sodium for 1.17 is not ready for general use.

Considering you have completely ignored the issue template, I suggest you don't use any snapshots build for 1.17 until we reach a stable release.
