### ISSUE TITLE
Subchunk culling issue

### ISSUE THREAD

**Issue by rjb3977** [jellysquid3/Sodium#722]
### Version Information

`mc1.17-0.3.0+build.458`

### Expected Behavior

The subchunk renders when visible.

### Actual Behavior

The subchunk does not render when viewed at certain angles from certain chunks with blocks in just the right places.

### Reproduction Steps

Load the attached world and fly around between the two chunks as shown in the screenshots. The subchunk containing the gold block will disappear and reappear.

I believe the example in this world is minimal. Removing any individual stone block makes the subchunk render from all angles.

[Broken Occlusion.zip](https://github.com/CaffeineMC/sodium-fabric/files/6743866/Broken.Occlusion.zip)

### System Information

- OS: `Windows 10`
- Java Version: `16.0.1`
- CPU: `Ryzen 3900X`
- GPU: `Radeon RX 5700 XT`

### Other Information
Other mods:
- `sodium-fabric-mc1.17-0.3.0+build.458`
- `lithium-fabric-mc1.17-0.7.2`
- `light-overlay-6.0.0-fabric`
- `fabric-api-0.36.0+1.17`
- `cloth-config-5.0.34-fabric`
- `architectury-2.0.16-fabric`

I originally encountered the issue in a cave. I copied the setup with world edit, reduced it as much as I could, and moved it to the center of the map. I haven't tested rotating or reflecting it.

Screenshots taken from the attached world from the same two positions using both Sodium and Vanilla:

### Sodium
![sodium 1](https://user-images.githubusercontent.com/42881603/124028069-906e5f00-d9c1-11eb-82b2-1a8b984328e7.png)
![sodium 2](https://user-images.githubusercontent.com/42881603/124028074-92382280-d9c1-11eb-8f4d-b9718d8976c1.png)

### Vanilla
![vanilla 1](https://user-images.githubusercontent.com/42881603/124028078-9401e600-d9c1-11eb-88a7-3c5deb9a50ea.png)
![vanilla 2](https://user-images.githubusercontent.com/42881603/124028085-95331300-d9c1-11eb-8a9b-80cc1dd8c7b4.png)

**Comment by rjb3977** [comment]
I realize now that the strange structure visible in the bottom right isn't actually necessary, and can be replaced with a flat wall. What matters is that the wall completely disconnects the section with the gold block from the section below the player in the second and fourth screenshots. Here's the same world with just three flat walls and the gold block.
[Broken Occlusion 2.zip](https://github.com/CaffeineMC/sodium-fabric/files/6777849/Broken.Occlusion.2.zip)

**Comment by Felix14-v2** [comment]
In addition: [Demo](https://youtu.be/x__hQV1-fCA)

**Comment by pajicadvance** [comment]
Since #872 is basically the same issue, but seems to be more active with more examples of the problem, I'll close this issue as a duplicate in favor of #872.
