### ISSUE TITLE
MultiDraw support for AMD Radeon HD 5450 videocard

### ISSUE THREAD

**Issue by Wachecheiro** [jellysquid3/Sodium#726]
I do not know if this request is well placed here I apologize in advance, I note that in "sodium-fabric-mc1.16.5-0.2.0 + build.4" the Multidraw still does not work.

I leave the description of the video according to speccy in case it helps:

	Name	2043 on AMD Radeon HD 5450
	Current Resolution	1600x900 pixels
	Work Resolution	1600x860 pixels
	State	Enabled, Primary, Output devices support, Unsafe
	Monitor Width	1600
	Monitor Height	900
	Monitor BPP	32 bits per pixel
	Monitor Frequency	60 Hz
	Device	\\.\DISPLAY1\Monitor0
ATI AMD Radeon HD 5450
	Manufacturer	ATI
	Model	AMD Radeon HD 5450
	GPU	Cedar
	Device ID	1002-68F9
	Subvendor	Dell (1028)
	Current Performance Level	Level 0
	Current GPU Clock	157 MHz
	Current Memory Clock	200 MHz
	Current Shader Clock	200 MHz
	Voltage	0.900 V
	Die Size	59 mm²
	Release Date	Feb 4, 2010
	DirectX Support	11.0
	DirectX Shader Model	5.0
	OpenGL Support	4.2
	GPU Clock	650,0 MHz
	Temperature	39 °C
	Core Voltage	0.900 V
	Driver version	15.301.1901.0
	BIOS Version	113-C09002-101
	ROPs	4
	Shaders	80 unified
	Memory Type	DDR3
	Memory	512 MB
	Bus Width	32x2 (64 bit)
	Pixel Fillrate	2,6 GPixels/s
	Bandwidth	12,8 GB/s
	Noise Level	Quiet
	Max Power Draw	20 Watts
		Count of performance levels : 3
				Level 1 - "Perf Level 0"
					GPU Clock	157 MHz
					Shader Clock	200 MHz
				Level 2 - "Perf Level 1"
					GPU Clock	400 MHz
					Shader Clock	500 MHz
				Level 3 - "Perf Level 2"
					GPU Clock	650 MHz
					Shader Clock	800 MHz

Greetings

**Comment by mrmangohands** [comment]
Your GPU doesn't support the openGL extension used for multidraw in Sodium 0.2. Sodium 0.3 for 1.17 has a different implementation which your computer may be able to run when it's released.

**Comment by Wachecheiro** [comment]
> Your GPU doesn't support the openGL extension used for multidraw in Sodium 0.2. Sodium 0.3 for 1.17 has a different implementation which your computer may be able to run when it's released.

oh.. great
