### ISSUE TITLE
Wrong color of dyed enchanted Leather armor

### ISSUE THREAD

**Issue by ArchitektRadim** [jellysquid3/Sodium#73]
### Expected Behavior
Dyed Leather armor should keep it's color after being enchanted

### Actual Behavior
Enchanted dyed Leather armor doesn't render in the right color

### Attachments
**Leather Tunic Dyed to Lime color**
<a href="https://ibb.co/Kxrwjhf"><img src="https://i.ibb.co/r2wsG0z/2020-07-09-23-44-55.png" alt="2020-07-09-23-44-55" border="0"></a>
Left - how it's supposed to look like (screenshot from Vanilla)
Right - how it looks with Sodium installed

### System Information
GTX 1660, driver 445.87

Java Version:
OpenJDK Runtime Environment AdoptOpenJDK (build 14.0.1+7)
-XX:+UnlockExperimentalVMOptions -XX:+UseZGC

**Comment by jellysquid3** [comment]
This looks fixed to me with ca8902c. When the enchanted glint was being applied, it resulted in a fallback path being used that caused BGRA colors to be interpreted as ARGB colors, causing colorization weirdness.
