### ISSUE TITLE
Cull inside of sheeps that have wool?

### ISSUE THREAD

**Issue by mse-k** [jellysquid3/Sodium#730]
latest version, not sure if it matters for a suggestion though

by inside i mean the skin of the sheep you usually see when its sheared

1. would look nicer if you happen to be inside a sheep
2. would prob save alot of rendering if your looking at a huge sheep farm, not sure though

**Comment by LambdAurora** [comment]
I'm not sure if this is in Sodium's scope, but it could be fairly easy to do in a separate mod.

**Comment by jellysquid3** [comment]
There's not much benefit to doing this, as you're (at best) eliminating a few triangles... something which any modern GPU can do millions of. Entity rendering is pretty much entirely dominated by the number of draw calls, which is fixed regardless of the geometry in most cases.
