### ISSUE TITLE
Bushy leaves culled when they are still visible

### ISSUE THREAD

**Issue by 400Ferrets** [jellysquid3/Sodium#732]
### Version: 

> - sodium-fabric-mc1.17-0.3.0+build.469

### Expected Behavior:

> - Bushy leaves from vanilla tweaks texture pack with them enabled stick around whenever you can see them

### Actual Behavior:

> - Previously mentioned bushy leaf bits on the bottoms of blocks disappear even though you can still see them

### Reproduction Steps:

1. Be using bushy leaves in vanilla tweaks texture pack
2. Locate tree
3. a couple blocks away from tree jump up and down and watch your flickering bushy leaves

### System Information:

> - Java Version: 16.0.1 64bit
> - CPU: 4x Intel(R) Xeon(R) CPU E5-1607 v2
> - GPU: AMD R9 270

### Other Information:

In attached photo the LEFT side shows screenshots using sodium, and the RIGHT side show screenshots using vanilla 1.17
![bushyleafculling](https://user-images.githubusercontent.com/68585283/124352169-5b7e2a00-dbc4-11eb-8e40-b94b951f61df.png)

used texture pack, you can also make a new one at [Vanilla Tweaks](https://vanillatweaks.net/picker/resource-packs/) make sure to select bushy leaves
[VanillaTweaks_r609822.zip](https://github.com/CaffeineMC/sodium-fabric/files/6758277/VanillaTweaks_r609822.zip)

**Comment by jellysquid3** [comment]
Does disabling "Use Block Face Culling" in Video Settings > Advanced fix this problem?

**Comment by 400Ferrets** [comment]
> Does disabling "Use Block Face Culling" in Video Settings > Advanced fix this problem?

It does not.

**Comment by pajicadvance** [comment]
Fixed in 0.5.0.
