### ISSUE TITLE
Item frames and paintings placed on stair blocks have their brightness calculated incorrectly

### ISSUE THREAD

**Issue by ggmaniack** [jellysquid3/Sodium#733]
### Version Information

> sodium-fabric-mc1.16.5-0.2.0+build.4.jar

### Issue

> Item frames and paintings placed on stair blocks have their brightness calculated incorrectly (depends on the cardinal direction).
> This is most noticeable when item frames are placed on stairs blocks that are not backlit, causing them to end up almost completely dark (but only in two cardinal directions). 

### Reproduction Steps

- Make a 3x3 base. 
- On it, build a ring of upside-down stairs, flat side facing outwards. 
- Fill in the holes so that the inside of the 3x3(x2 high) is completely dark. 
- Place Item frames and Paintings on the outer flat side of the stair blocks.

### Screenshots of issue

![2021-07-04_01 21 56](https://user-images.githubusercontent.com/506806/124369034-c2085400-dc67-11eb-98b0-6a684fde5a3b.jpg)
![2021-07-04_01 22 06](https://user-images.githubusercontent.com/506806/124369031-bfa5fa00-dc67-11eb-8c8e-6eaea8e573d4.jpg)

### System Information

![2021-07-04_01 30 18](https://user-images.githubusercontent.com/506806/124369036-c46aae00-dc67-11eb-9cce-88a11ace5482.jpg)

### Other Information

> All other Fabric mods except for Fabric API were removed during testing.

**Comment by jellysquid3** [comment]
Does setting "Smooth Lighting" to "Low" in Video Settings > Quality change anything?

**Comment by ggmaniack** [comment]
> Does setting "Smooth Lighting" to "Low" in Video Settings > Quality change anything?

@jellysquid3 Setting it to Low or Off seems to fix the issue. It's only broken on High.

**Comment by MeeniMc** [comment]
Issue is resolved in (at least) 0.4.10
