### ISSUE TITLE
1.17: Incorrect culling of powder snow

### ISSUE THREAD

**Issue by edwloef** [jellysquid3/Sodium#736]
### Version Information

0.3.0+build.469

### Expected Behavior

Powder snow faces aren't culled behind not full blocks.

### Actual Behavior

Powder snow faces are culled behind not full blocks.

### Reproduction Steps

Place a not full block that can cull faces, like a fence, next to a powder snow bucket.

### System Information

- Java Version: 16.0.1 64bit
- CPU: Intel Core i5-6300HQ
- GPU: NVidia GeForce GTX 950M
- Driver: 3.2.0 NVIDIA 465.31
- OS: Pop!_OS 21.04

### Other Information

![image](https://user-images.githubusercontent.com/75493688/124397815-765eb480-dd12-11eb-95e5-a76ca39d20fe.png)

![image](https://user-images.githubusercontent.com/75493688/124397830-8e363880-dd12-11eb-887e-a03eb5c2e443.png) (Screenshot by pwouik#7160)

**Comment by mrmangohands** [comment]
Fixed by 7aa70e59235072767ebd666a23c70bfaee13493c
