### ISSUE TITLE
Crash reports problem 1.17 

### ISSUE THREAD

**Issue by thernerd** [jellysquid3/Sodium#738]
Version: fabric-loader-0.11.3-1.17

I just went into the portal from hell to the ordinary world and got a crash, there used to be crashes sometimes, but now it crashes constantly when entering the server. 

Mods: appleskin-fabric-mc1.17-2.0.0
boosted-brightness-2.1.0
fabric-api-0.36.01.17 (1)
held-item-info-1.2.0
inventoryhud-fabric-1.17-3.3.2
malilib-fabric-1.17.0-0.10.0-dev.22+beta.1
minihud-fabric-1.17.0-0.19.0-dev.20210609.185508
modmenu-2.0.2
namepain-1.4.0fabric-1.17.x
notenoughcrashes-3.3.11.17-fabric
sodium-fabric-mc1.17-0.3.0rev.145d664-iris
Xaeros_Minimap_21.12.2_Fabric_1.17_1
xaerosworldmap_1.14.4_fabric_1.17
[crash-2021-07-05_09.51.28-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6762353/crash-2021-07-05_09.51.28-client.txt)

**Comment by Ozne-O** [comment]
@thernerd try and unload mods 1 by 1. maybe it helps

**Comment by Altirix** [comment]
Fairly certain Devs are not taking bug reports from the dev versions atm as there are more pressing issues for them to fix over compatibility. also are you running Iris? sodium-fabric-mc1.17-0.3.0rev.145d664-iris their version is modified to run shaders.

**Comment by CalXee** [comment]
Yes, for issues with the Iris fork, you should report it to the Iris fork issue tracker.
