### ISSUE TITLE
Sodium 1.17 (Question)

### ISSUE THREAD

**Issue by Sharkie124** [jellysquid3/Sodium#739]
**DO NOT INSTANTLY CLOSE THIS THREAD. THIS IS A QUESTION ABOUT 1.17 AND NOT ABOUT WHEN IT IS RELEASING.**
Hello, so 4 hours ago (when this post was created) https://github.com/CaffeineMC/sodium-fabric/issues/738 was made and it was a bug report about 1.17. Is there a way to use Sodium 1.17 in its dev version? Been waiting almost a month for 1.17 to release but it hasn't so I'm wondering if theres a way to somehow maybe compile the code and run it? I have no idea what I'm talking about, heh. Could you please let me know if there's a way to play on Sodium 1.17 in it's dev version and how? Thanks.

**Comment by Altirix** [comment]
as with any software where people are volunteering their time to work on it, it will be when it's ready. if you use dev versions there can be bugs, if you are using that version you are expected to know how firstly how to troubleshoot stuff yourself first, then submit bug reports with good info and detail. resources on how to get non-public versions is out there and readily available on this page and seeing as you havent found it you likely arent really the type of person the devs want to be using it in its current moment, id wait for a beta build it will be more stable by that point

**Comment by CalXee** [comment]
There is a reason 1.17 versions exist but isn't publicly released/you have to compile them; they are unstable, cause a handful of annoying issues, and personally for me causes performance regression compared to vanilla in a substantial number of cases.

They exist for experienced individuals to help report issues to prepare for the release in the future. Not for daily use.
