### ISSUE TITLE
Glowing optimization

### ISSUE THREAD

**Issue by Zailer43** [jellysquid3/Sodium#74]
**Is your feature request related to a problem? Please describes.**
When I play hypixel skyblock dungeons players have glowing effects and that slightly lowers the fps

**Describe the solution you'd like**
Optimizing the glowing effect

**Describe alternatives you've considered**
Buy me a pc and play at over 60 fps

**Additional context**
![2020-07-09_18 52 39](https://user-images.githubusercontent.com/63565983/87095232-be89ea80-c216-11ea-9730-c89224d92f44.png)
![2020-07-09_18 52 53](https://user-images.githubusercontent.com/63565983/87095235-c053ae00-c216-11ea-806a-907dcd8d0fc6.png)

**Comment by HitItAll** [comment]
I like your alternative option

**Comment by surfaceflinger** [comment]
Not sure on what configurations it happens exactly but it's terrible on Windows 10/11 and Intel HD 4600. And it's fine on Linux/Windows and Intel HD 4000. Looking at #801 it's bad on macOS and Radeon Pro 560 too.
Not only it drops FPS but it also creates weird cursor/camera rotation lag that looks like "throttling" and I have also noticed that OptiFine's Smooth FPS fixes rotation lag but drops fps in half when seeing something with the glow effect.

Maybe for now it would be a good idea to just implement a simple toggle that completely disables this effect?

**Comment by Zailer43** [comment]
I obtained 37% higher fps with 445 entities with glowing with https://github.com/CaffeineMC/sodium-fabric/commit/2967d1ae865832b044488b16a85846b4d9636431

**Comment by Felix14-v2** [comment]
> Maybe for now it would be a good idea to just implement a simple toggle that completely disables this effect?

Not sure, since this breaks the whole essence of the glow effect. But you can try other mods like [No Glowing](https://modrinth.com/mod/no-glowing)
