### ISSUE TITLE
Animation render distance

### ISSUE THREAD

**Issue by Lentern** [jellysquid3/Sodium#741]
**Is your feature request related to a problem? Please describe.**
It might fix some performance issues. (in the sense that it **improves** performance)

**Describe the solution you'd like**
Add an animation render distance setting. It goes from 2 chunks to your current normal render distance setting. Animations outside of the set render distance pause/reset until you move closer.

**Describe alternatives you've considered**
An option to disable animations altogether, but that was closed in #166.
A block by block animation render distance setting. This would most likely be a lot harder though.

**Comment by jellysquid3** [comment]
Do you have data that suggests animated textures are a significant issue still with all the optimizations we implement?

**Comment by Lentern** [comment]
They aren't a big performance hitter (especially with Sodium's optimizations) and this would probably only help really low-end PCs in the long run. This request can be closed if the idea isn't practical.
