### ISSUE TITLE
Minecraft 1.17.1 launch failure

### ISSUE THREAD

**Issue by eshankiyer** [jellysquid3/Sodium#742]
### Version Information
Fabric 1.17.1 build 0.74

### Expected Behavior
The game would've launches
### Actual Behavior
The game crashes with a -1 code error
### Reproduction Steps
Use the latest sodium build with fabric 1.17.1 build
### System Information
> - Java Version: GraalVM JDK (Latest preview build)
> - CPU: AMD Ryzen 4000 series
> - GPU: Integrated graphics

**Comment by LucilleTea** [comment]
This is not enough information for us to tell you anything, a log file or crash report is required.

**Comment by PseudoDistant** [comment]
I know this wouldn't be their log, but I have a similar problem.

https://paste.ubuntu.com/p/NdRm7mbxmR/

AdoptOpenJDK Java 16+36 64-bit
Arch Linux running Kernel 5.12.10-zen1 and Plasma 5.22.1
Minecraft 1.17.1 with Fabric Loader 0.11.6
AMD Ryzen 7 1700X
16GB DDR4-3000
MSI Armor Radeon RX 570

I don't know if any more information would be helpful, but I would be willing to provide more. 
:b:

**Comment by PseudoDistant** [comment]
For now if you're like me and require Sodium to play at a render distance that isn't 8, I would recommend sticking with 1.17 and using ViaFabric and ViaBackwards (if it's on 1.17.1) until the issue gets sorted.

**Comment by PseudoDistant** [comment]
Never mind, I did a bit of digging...
@Eshanepicfighter Iris's fork seems to work on 1.17.1
https://github.com/IrisShaders/sodium-fabric/tree/1.17.x/iris

**Comment by eshankiyer** [comment]
Full crash report (I installed the fabric loader 1.17.1 from the official installer): 
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/7/21, 9:52 AM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at Not Enough Crashes deobfuscated stack trace.(1.17+build.13)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:495)
	at net.minecraft.client.main.Main.main(Main:179)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onScreenshot(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in mixins.fabrishot.json:KeyboardMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabrishot-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 15 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.minecraft.class_310.<init>(class_310.java:495)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, GraalVM Community
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), GraalVM Community
	Memory: 573443872 bytes (546 MiB) / 1006632960 bytes (960 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 6
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4500U with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.37
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1636
	Graphics card #0 versionInfo: DriverVersion=27.20.22001.16006
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 22654.16
	Virtual memory used (MB): 17514.08
	Swap memory total (MB): 6912.00
	Swap memory used (MB): 266.40
	JVM Flags: 16 total; -XX:ThreadPriorityPolicy=1 -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCIProduct -XX:-UnlockExperimentalVMOptions -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+EagerJVMCI -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		adventure-platform-fabric: adventure-platform-fabric 4.1.0-SNAPSHOT
		antighost: AntiGhost 1.17.1-fabric0.36.1-1.1.4
		appleskin: AppleSkin mc1.17-2.0.0
		architectury: Architectury 2.1.20
		authme: Auth Me 1.5.0
		betterbeds: Better Beds 1.2.0
		betterdroppeditems: Better Dropped Items 1.3.0-1.17
		betterthirdperson: Better Third Person 1.5.0
		blur: Blur (Fabric) 2.1.0
		can-i-mine-this-block: cAn i MiNe thIS bLOCk? 1.1.0
		carpet: Carpet Mod 1.4.43
		carpet-extra: Carpet Extra 1.4.40
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		chunky: Chunky 1.2.93
		cleancut: CleanCut 1.17-4.0-fabric
		cloth-api: Cloth API 2.0.54
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 2.0.54
		cloth-common-events-v1: Cloth Common Events v1 2.0.54
		cloth-config2: Cloth Config v4 5.0.34
		cloth-datagen-api-v1: Cloth Datagen v1 2.0.54
		cloth-scissors-api-v1: Cloth Scissors API v1 2.0.54
		cloth-utils-v1: Cloth Utils v1 2.0.54
		cloud-v1: Cloud 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-brigadier: cloud-brigadier 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-core: cloud-core 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.5.0-SNAPSHOT
		cloud_commandframework_cloud-services: cloud-services 1.5.0-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		crowdin-translate: CrowdinTranslate 1.3+1.17
		cullleaves: Cull Leaves 2.2.0
		dynamicfps: Dynamic FPS 2.0.4
		easiervillagertrading: EasierVillagerTrading 1.17.1-fabric0.36.1-1.5.4
		fabric: Fabric API 0.36.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d013
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea813
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446313
		fabric-command-api-v1: Fabric Command API (v1) 1.1.2+6cefd57713
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa13
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446313
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b446313
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31013
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57713
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446313
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c013
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa13
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57713
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446313
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612113
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446313
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e13
		fabric-language-kotlin: Fabric Language Kotlin 1.6.2+kotlin.1.5.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446313
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446313
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa13
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446313
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.12+6cefd57713
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446313
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612113
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446313
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446313
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee13
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96913
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446313
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446313
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463d5
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b4463d5
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa13
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.0+a02b446313
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121d5
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446313
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+6cefd57713
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446313
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446313
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612113
		fabricloader: Fabric Loader 0.11.6
		fabrishot: Fabrishot 1.5.0
		fastchest: FastChest 1.2+1.17
		ferritecore: FerriteCore 3.0.0
		fiber: fiber 0.23.0-2
		gbfabrictools: GBfabrictools 1.3.4+1.17
		horseinfo: Horse Info 0.3.0-1.17
		indium: Indium 1.0.0+rev.820073e
		inventoryhud: Inventory HUD + 3.3.1
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		kubejs: KubeJS 1605.3.10-build.9999
		lambdynlights: LambDynamicLights 2.0.1+1.17
		lazydfu: LazyDFU 0.1.2
		libzoomer: LibZoomer 0.2.1+1.17
		litematica: Litematica 0.0.0-dev.20210707.011234
		lithium: Lithium 0.7.3-SNAPSHOT
		malilib: MaLiLib 0.10.0+dev.22
		megane: megane 5.0.0
		megane-base: megane-base 5.0.0
		megane-runtime: megane-runtime 5.0.0
		megane-vanilla: megane-vanilla 5.0.0+1.17
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.1
		modmenu: Mod Menu 2.0.2
		net_kyori_adventure-api: adventure-api 4.8.1
		net_kyori_adventure-key: adventure-key 4.8.1
		net_kyori_adventure-platform-api: adventure-platform-api 4.0.0-SNAPSHOT
		net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.8.0
		net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
		net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.1.0-SNAPSHOT
		net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.8.1
		net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.8.0
		net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.8.1
		net_kyori_examination-api: examination-api 1.1.0
		net_kyori_examination-string: examination-string 1.1.0
		notenoughcrashes: Not Enough Crashes 3.3.1+1.17
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_codehaus_groovy_groovy: groovy 3.0.8
		org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.8
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.0
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.1
		org_spongepowered_configurate-core: configurate-core 4.1.1
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.1
		rhino: Rhino 1605.1.1-build.23
		roughlyenoughitems: Roughly Enough Items 6.0.262-alpha
		satin: Satin 1.6.0-nightly.1.17-pre3
		seamless_loading_screen: Seamless Loading Screen 1.3.5+1.17
		slight-gui-modifications: 'Slight' GUI Modifications 2.0.0
		sodium: Sodium 0.3.0+build.480
		spark: spark ${pluginVersion}
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight 1.0.0-RC3+fabric.2b7d7ae
		tabtps-fabric: TabTPS 1.3.8
		torohealth: ToroHealth Damage Indicators 1.17-fabric-6
		voicechat: Simple Voice Chat 1.17.1-1.0.0
		wthit: wthit 3.6.1
		xaerominimap: Xaero's Minimap 21.12.5.1
		xaeroworldmap: Xaero's World Map 1.14.5.2
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.14739 Core Profile Forward-Compatible Context 21.6.2 27.20.22001.16006, ATI Technologies Inc.
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	Suspected Mods: Fabric Loader (fabricloader)

**Comment by amnotbananaama** [comment]
> sodium@0.3.0+unknown

@FarLanderCraft What build of Sodium are you using? Exact commit or filename if possible please

@Eshanepicfighter Your crash is not caused by Sodium according to your crash log. fabricshot 1.5.0 is not compatible with 1.17.1. You'll need to remove it and wait for an updated version

**Comment by eshankiyer** [comment]
I removed fabrishot and I still keep getting launch failures.

**Comment by PseudoDistant** [comment]
> > sodium@0.3.0+unknown
> 
> @FarLanderCraft What build of Sodium are you using? Exact commit or filename if possible please

Latest commit (at the time), sodium-fabric-mc1.17.1-0.3.0+unknown.jar

EDIT: At the time seems to still be now, I literally built it this morning.

**Comment by PseudoDistant** [comment]
Iris's build is running, however, and it seems to run just as smoothly. :D
(I've been meaning to try out Iris properly anyway, so this is a great excuse for me to do it lol .)

**Comment by eshankiyer** [comment]
How did you build Iris's Sodium, I am on windows but I do have the Windows Subsystem for Linux activated

**Comment by PseudoDistant** [comment]
I did modify the `fabric.mod.json` file, as well as the `gradle.properties`, but only to set everything to 1.17.1 instead of 1.17.
Even if I don't touch them, however, mainline 1.17 doesn't run.

**Comment by PseudoDistant** [comment]
> How did you build Iris's Sodium, I am on windows but I do have the Windows Subsystem for Linux activated

It's doable on Windows.
You just need to build Iris first, then put the Iris.jar file in gradle/build in the Sodium source. Then run `gradlew build`

**Comment by FarLanderCraft** [comment]
I can send you the jar I built if you'd prefer.

**Comment by eshankiyer** [comment]
So.... how the heck do u build iris

**Comment by PseudoDistant** [comment]
Download Iris's source, then run gradlew build.
Iris's 1.17 branch doesn't build on 1.17.1, but my fork does (It needed some methods renamed.)

**Comment by FarLanderCraft** [comment]
https://github.com/FarLanderCraft/Iris

Download the 1.17 branch.

**Comment by eshankiyer** [comment]
Alright... so I git clone the repository then run gradlew.build.

**Comment by PseudoDistant** [comment]
The default branch is 1.16.5, so change it to 1.17 first.
(You can also download the 1.17 branch as a zip, and build from there.)

**Comment by amnotbananaama** [comment]
This is a bug tracker for the official version of Sodium. We have no issue with forks, but this isn't the appropriate place to discuss them. Every message sent here generates an email notification *and* a notification for our issue tracker.

> I removed fabrishot and I still keep getting launch failures.
 
That is not unexpected, you have several other mods. Based on the information provided, I am going to assume you both are using the same build/commit (build 480/commit 78d34a8). 

See [this message](https://github.com/CaffeineMC/sodium-fabric/issues/742#issuecomment-875545570) for the actual issue (Mixin cannot find the field `fontRenderer` in the vanilla class `DebugHud`).

We have all the info we need at this time thank you

**Comment by FarLanderCraft** [comment]
Sorry for the last message, but this is just to make things easier if needbe.
@Eshanepicfighter If you have any issues with the build, contact me on Discord: Far#6656
or Telegram: `@FarLikesDoritos`

**Comment by jellysquid3** [comment]
We're not a fan of people linking to third-party builds of our mods on our own issue tracker, nor is this a support/installation guide forum. The README contains instructions on where bleeding-edge builds can be found. We don't publish these right now because they're not stable and/or complete.

**Comment by amnotbananaama** [comment]
Closing as 5f48737 fixes this issue
