### ISSUE TITLE
my game crash when i start

### ISSUE THREAD

**Issue by wathakate** [jellysquid3/Sodium#745]
### Version information

mc1.16.3-0.1.0

### Reproduction Steps

I start the game and crash

### Crash Report file

[crash-2021-06-25_17.06.21-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6784602/crash-2021-06-25_17.06.21-client.txt)

**Comment by amnotbananaama** [comment]
Duplicate of #15. Sodium and Immersive Portals are incompatible at this time
