### ISSUE TITLE
Texture orientation is no longer random

### ISSUE THREAD

**Issue by xpopy** [jellysquid3/Sodium#746]
### Version information

sodium-fabric-mc1.17.1-0.3.0+rev.5f48737

### Expected Behavior

The textures should be randomly oriented like vanilla 
![image](https://user-images.githubusercontent.com/3540971/125094566-ab348800-e0d3-11eb-9495-2aa0c206710e.png)

### Actual Behavior

The textures are all oriented the same way
![image](https://user-images.githubusercontent.com/3540971/125094424-88a26f00-e0d3-11eb-8fa9-37d1d35871c8.png)

### Reproduction Steps

1. Load a flat world of grass
2. Behold order

### Java version

Java 16.0.1

### CPU

Intel Core i5-4690k

### GPU

NVIDIA RTX 3070

### Additional information

GPU driver version: 471.11

I believe this worked back on 1.17, so it's probably a recent change
No other mods used.

**Comment by epic0421** [comment]
I can confirm that the same issue happens for me as well with the 1.17.1 beta2 build, even with things that I try to randomize.

**Comment by magneticflux-** [comment]
Discussed in Discord on the 8th here: https://discord.com/channels/602796788608401408/651120262129123330/862595507914539018

Fixed by https://github.com/CaffeineMC/sodium-fabric/commit/55fa7afb9cdfb57692ae0042bd93db52cb652cbd
