### ISSUE TITLE
image error when to the world

### ISSUE THREAD

**Issue by ALR2310** [jellysquid3/Sodium#749]
### Version information

mc1.16.3-0.1.0

### Expected Behavior

Please help this error of this error

### Actual Behavior

When I joined the world, everything was like the image below

![image](https://user-images.githubusercontent.com/87233160/125164138-efe71e80-e1ba-11eb-9363-459dd8bb489f.png)
![image](https://user-images.githubusercontent.com/87233160/125164151-ff666780-e1ba-11eb-8dac-69017833891a.png)
![image](https://user-images.githubusercontent.com/87233160/125164156-08efcf80-e1bb-11eb-82a4-982d0b3692ad.png)
![image](https://user-images.githubusercontent.com/87233160/125164162-13aa6480-e1bb-11eb-8ddb-81acf455f507.png)

### Reproduction Steps

When I joined the world

### Java version

8

### CPU

core i5 3230m

### GPU

intel hd 4000

**Comment by mrmangohands** [comment]
This is a driver bug, if you upgrade to Sodium 0.2 your computer will be blacklisted from using the problematic setting (the multidraw renderer).

**Comment by ALR2310** [comment]
so how to fix it?

**Comment by K0-RR** [comment]
> upgrade to Sodium 0.2
