### ISSUE TITLE
Looking straight down when Y coordinate is between 126.38001 and 126.43000 causes rendering issues

### ISSUE THREAD

**Issue by Hnaguski** [jellysquid3/Sodium#750]
### Version information

mc1.17.1-0.3.0+rev.634e886

### Expected Behavior

Rendering works when at any Y level

### Actual Behavior

Rendering breaks when looking straight down and Y level is between 126.38001 and 126.43000

### Reproduction Steps

1. Enter a world
2. `/tp @p ~ 126.38001 ~ 0 90`
3. See nothing

### Java version

Java 16

### CPU

AMD R5 3600

### GPU

AMD R9 Fury X

### Additional information

![2021-07-10_17 15 24](https://user-images.githubusercontent.com/29007712/125176574-73e0dc80-e1a2-11eb-988b-309a405ef61e.png)
![2021-07-10_17 15 18](https://user-images.githubusercontent.com/29007712/125176571-6fb4bf00-e1a2-11eb-909c-1d5ab63a05e2.png)

**Comment by mrmangohands** [comment]
Introduced by 53e363d98c1fe925b611335891cc0bdda3083668

**Comment by magneticflux-** [comment]
Some more details in the Discord: https://discord.com/channels/602796788608401408/752637878462578778/864050917821382666
