### ISSUE TITLE
Change OpenGL Chunk Renderer Version Setting (Sodium Build 501) (Feature Request, not an actual problem with Sodium)

### ISSUE THREAD

**Issue by eshankiyer** [jellysquid3/Sodium#751]
In all Sodium versions, in the advanced tab you will find a setting to change the OpenGL Chunk Renderer version. I am unable to find this menu in Sodium Build 501

Example for 1.16.5 builds
![image](https://user-images.githubusercontent.com/79593316/125179612-53834300-e1df-11eb-8428-e75a1423a83a.png)

Example for 1.17 and 1.17.1 builds
![image](https://user-images.githubusercontent.com/79593316/125179625-84fc0e80-e1df-11eb-87a6-7c1627c9ef06.png)

**Comment by mrmangohands** [comment]
The option is gone because there's only one backend as of 93a866038a52ff88fa48b3c0399ca2d2b77723d6. This isn't a regression, it's just always using the best (and only) option available.
