### ISSUE TITLE
Rendering particles not within the loaded chunks!

### ISSUE THREAD

**Issue by Endstarky** [jellysquid3/Sodium#756]
### Version information

0.3.0+build.503

### Expected Behavior

I reduced my chunks to 2 which covers half of my Mc house and other half is not loaded and in that not loaded cunks there are campfire, whose particles i can see but that shouldn't happen as that chunk is not loaded!

And I think its fix can upgrade the perfomance improvement in many regions ?
 

### Actual Behavior

The smokes are rendering from the non loaded chunk(is that suppose to happen?) 
Chunk grids are given for precise information.

![Minecraft_ 1 17 1 - Singleplayer 7_13_2021 9_47_35 PM](https://user-images.githubusercontent.com/67501470/125488562-c4ce7080-424e-4c6a-bcb0-d88feb1c532b.png)

![Minecraft_ 1 17 1 - Singleplayer 7_13_2021 9_46_20 PM](https://user-images.githubusercontent.com/67501470/125488552-d0050a2b-c7a4-42ce-b7b4-ce8b7c0e53d6.png)
![Minecraft_ 1 17 1 - Singleplayer 7_13_2021 9_48_27 PM](https://user-images.githubusercontent.com/67501470/125488559-51280ca2-84b1-43a0-af8e-2bb86b768b05.png)

### Reproduction Steps

Reduce chunks to lowest 

Then go to a chunk which makes the campfire chunk deload.

now u can see it!

### Java version

Java 16

### CPU

Intel core TM i3-7100 @ 3.90 ghz

### GPU

Intel HD graphics 630

**Comment by jellysquid3** [comment]
I actually wrote a patch a few days ago which changes particle rendering to check if a chunk is visible, rather than if the chunk was within the camera's view. It should be faster, ignoring the extra number of particles it can cull.
