### ISSUE TITLE
Cull leaves

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#757]
**Is your feature request related to a problem? Please describe.**
Leaves can be optimized when rendering. It increases FPS by 20
**Describe the solution you'd like**
An option to "cull leaves" like a separate mod can do.
**Describe alternatives you've considered**
Install a different mod, but that requires another mod.

**Additional context**
![image](https://user-images.githubusercontent.com/87130878/125500327-52813f58-f7e9-4502-9c7d-9778502a16bb.png)

**Comment by LambdAurora** [comment]
This brings quite a different visual.

And if another mod already does it I don't see why it should be in Sodium since the other mod can be used.

**Comment by silversquirl** [comment]
This significantly changes vanilla rendering, which sodium does not do. Sodium is not designed to do everything - if it can be done by another mod, that's probably a better way to do it.
