### ISSUE TITLE
i18n Support

### ISSUE THREAD

**Issue by AkarinLiu** [jellysquid3/Sodium#759]
I want to join to i18n internationalization translate, I hope CAN be has Chinese Simple language.

**Comment by amnotbananaama** [comment]
Thank you for the offer! Currently, Sodium's strings are hard-coded in English and need to be converted to translation keys. PR #717 would do that. Until that is merged, you can contribute to the `zh_cn` translation on [OneSky](https://jellysquid.oneskyapp.com/collaboration/translate/project/project/366422/language/3).

**Comment by AkarinLiu** [comment]
But I hope i18n Can be integreate to the sodium mod.
但我希望i18n能集成于sodium模组。
그러나 i18n이 나트륨 모드에 인테대큰이 될 수 있기를 바랍니다.
しかし、私はi18nがナトリウムモッズに素晴らしいことができることを願っています。
Но я надеюсь, что i18n может быть интегрируется с натриевым модом.
Mais j’espère que i18n peut être intégré au mod sodium.
Aber ich hoffe, i18n kann in den Natrium-Mod integriert werden.

Power by Microsoft Translator
由Microsoft翻译器强力驱动
Leistung durch Microsoft Translator
Puissance pilotée par Microsoft Translator
Microsoft 번역기의 강력한 드라이버입니다
Microsoftトランスレータによって強力に駆動されます
Сильно управляется переводчиком Microsoft
