### ISSUE TITLE
Entity Distance

### ISSUE THREAD

**Issue by DasherPack** [jellysquid3/Sodium#76]
The "entity distance" setting is not avaliable. Will it be available at some point?

**Comment by TheMadHau5** [comment]
AFAIK, it's already there in the latest build, but I may be seeing things.

**Comment by ghost** [comment]
> AFAIK, it's already there in the latest build, but I may be seeing things.

Yeah,
It is there

**Comment by DasherPack** [comment]
Ok, Ill check . Thanks
