### ISSUE TITLE
Selective chunk loading.

### ISSUE THREAD

**Issue by itdepends-music** [jellysquid3/Sodium#761]
If there is a tall mountain, chunks behind it do not need to be rendered if they are not visible right? This could significantly reduce the amount of chunks needed to load, especially on higher render distances.

**Comment by jellysquid3** [comment]
What you're asking for is called "occlusion culling" (the act of not rendering objects that are occluded, or hidden.) Sodium already implements this with a variation of the vanilla algorithm.
