### ISSUE TITLE
Fps not boosting

### ISSUE THREAD

**Issue by HyperCosmos** [jellysquid3/Sodium#763]
### Version information

sodium-fabric-mc1.16.3-0.1.0

### Expected Behavior

My FPS should have increased drastically. Before using sodium, I had around 40 - 50 FPS in Minecraft single world, but even after using sodium it hasn't increased at all. 

### Actual Behavior

Before using sodium, I had around 40 - 50 FPS in Minecraft single world, but even after using sodium it hasn't increased at all. 

### Reproduction Steps

Fps not increasing.

### Java version

Java 16

### CPU

Intel(R) Core(TM) i5-9300H

### GPU

NVIDIA GeForce GTX 1650

**Comment by LucilleTea** [comment]
This seems like a tech support inquiry rather than an issue, so is better suited to [our discord support channels](https://jellysquid.me/discord), not our issue tracker.
