### ISSUE TITLE
Circular light shape

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#765]
**Is your feature request related to a problem? Please describe.**
I don't like the existing light shape, it looks like an octagon.
![2021-07-17_14 30 41](https://user-images.githubusercontent.com/85982640/126036976-f46d823e-1114-49c5-a2a2-0a4df01ae460.png)

**Describe the solution you'd like**
I want the lighting to be actually circular.

**Describe alternatives you've considered**
**make it circular**

**Comment by jellysquid3** [comment]
This isn't something we can/will fix, and is an artifact of how Minecraft's lighting engine works.
