### ISSUE TITLE
I currently have Sodium build 503. I have an issue where the more chunks I explore, the larger and larger memory usage gets and it never goes down

### ISSUE THREAD

**Issue by fryman74** [jellysquid3/Sodium#767]
### Version information

1.17.1

### Expected Behavior

Normally chunks do unload from memory and the memory usage remains fair and consistent. With Sodium build 503 at least, it doesn't.

### Actual Behavior

The more chunks I explore, the bigger the memory usage gets and it stays bigger and bigger

### Reproduction Steps

I guess use any Sodium build before build 506? But I don't know if Build 506 is supposed to fix this

### Java version

The newest version of Java currently available

### CPU

Intel Pentium G4400

### GPU

Intel HD 510

### Additional information

Is this fixed in build 506? I heard somebody said build 506 fixed this but I want to know.

**Comment by LucilleTea** [comment]
This was fixed in build 506, yes.
