### ISSUE TITLE
Multidraw is not blacklisted for AMD Radeon HD 5000 series cards even though it does not work properly

### ISSUE THREAD

**Issue by yhkhoo** [jellysquid3/Sodium#768]
### Version information

sodium-fabric-mc1.16.5-0.2.0+build.487.jar

### Expected Behavior

Multidraw is blacklisted

### Actual Behavior

Multidraw is not blacklisted

### Reproduction Steps

1. Start Minecraft with sodium on a system with a Radeon HD 5000 series card 
2. Multidraw is automatically enabled

### Java version

graalvm-ce-java8-21.1.0

### CPU

intel core i3 550

### GPU

AMD Radeon HD 5450

### Additional information

mod list:
fabric-api-0.32.5+1.16.jar
lazydfu-0.1.2.jar
sodium-fabric-mc1.16.5-0.2.0+build.487.jar
screenshots:
![2021-07-17_23 39 58](https://user-images.githubusercontent.com/77189596/126042246-54382cc5-d723-4ab2-8054-7bf8f0726128.png)
![2021-07-17_23 40 05](https://user-images.githubusercontent.com/77189596/126042247-e91c88fb-ffcb-4da6-bc9a-3f018de0143e.png)

**Comment by Kroppeb** [comment]
I don't think I have seen such corruption before.

**Comment by jellysquid3** [comment]
This is no longer relevant as Sodium for Minecraft 1.16 is no longer actively developed, and newer versions for Minecraft 1.17 have since replaced the multi-draw renderer with a much more performant and compatible version which doesn't suffer from this issue.
