### ISSUE TITLE
Kelp seen through glass does not render water

### ISSUE THREAD

**Issue by tsufeki** [jellysquid3/Sodium#769]
### Version information

mc1.17.1-0.3.0+build.5

### Expected Behavior

Kelp block adjacent to and seen through glass should render as in water.

### Actual Behavior

There is no fluid visible for minecraft:kelp_plant blocks.

minecraft:kelp blocks i.e. top part of kelp are rendering water OK though.

### Reproduction Steps

1. Build water tank with glass walls.
2. Plant at least 2 high kelp plant directly next to glass wall
3. Look at the kelp from outside (through glass)
4. Water is not visible for lower kelp blocks. It is visible for kelp's top block and regular water blocks

### Java version

Java 16

### CPU

Intel Core i7-10510U

### GPU

Intel UHD Graphics (CML GT2)

### Additional information

![2021-07-18_00 37 40](https://user-images.githubusercontent.com/4078572/126051136-eb3fc4d2-ca7a-42c4-9cdb-1fe7627dbece.png)

This worked correctly in sodium 0.2.0 in 1.16

**Comment by jellysquid3** [comment]
Fixed in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1).
