### ISSUE TITLE
Culling is a bit *too* aggressive

### ISSUE THREAD

**Issue by Leo40Git** [jellysquid3/Sodium#77]
### Expected Behavior
![2020-07-10_17 45 11](https://user-images.githubusercontent.com/7997354/87167584-df654500-c2d5-11ea-8bfe-e827ae50d439.png)

### Actual Behavior
![2020-07-10_17 48 45](https://user-images.githubusercontent.com/7997354/87167536-cb214800-c2d5-11ea-8134-5ae5534c29d7.png)

### Reproduction Steps
1. Grab the "3D Doors and Trapdoors" pack from https://vanillatweaks.net/picker/resource-packs/
2. Create a doorway
3. Open the door

### System Information
- Java Version: AdoptOpenJDK 14.0.1.7 Installer
- CPU: Intel Core i5-8250U @ 1.80 GHz
- GPU: NVIDIA GeForce MX150

**Comment by MMK21Hub** [comment]
You should probably report this at <https://vanillatweaks.net/feedback>

(Except no need to do it in this case because it's a known issue 😉)

**Comment by Leo40Git** [comment]
I feel like this is an issue with Sodium and not Vanilla Tweaks, since the model works fine without Sodium.

**Comment by MMK21Hub** [comment]
Really? It looks very similar to a bug with the resource pack. Is the issue present without the planks next to the door?

![](https://cdn.discordapp.com/attachments/569603162739179522/731523849925033990/Screenshot_20200711-155311.png)

**Comment by Leo40Git** [comment]
(okay there was originally a video here but it's not being uploaded for some reason)
also
![2020-07-11_18 10 05](https://user-images.githubusercontent.com/7997354/87227294-c4143b80-c3a2-11ea-86d3-a884654bae04.png)

**Comment by Leo40Git** [comment]
fuck that's the wrong file

**Comment by Leo40Git** [comment]
https://streamable.com/7shjof 🤔

**Comment by jellysquid3** [comment]
This resource pack is broken and is setting the wrong culling face for model quads, which causes it to be batched into the wrong face of the chunk mesh and as a result not rendered when Sodium performs back face culling.
