### ISSUE TITLE
Random chunks persistently do not render at all

### ISSUE THREAD

**Issue by atomkreuzer** [jellysquid3/Sodium#771]
### Version information

mc1.17.1-0.3.0+build.5

### Expected Behavior

All chunks within render distance should render normally.

### Actual Behavior

Some chunks do not render at all, leaving see-through spaces in the world.

### Reproduction Steps

On 1.17.1, create a new world, default settings, seed name `chunk`
One should appear right next to player's spawn point, at X -130 Z 10

### Java version

Java 16.0.1 64bit

### CPU

Intel Core i5-2400

### GPU

AMD Radeon HD 5770

### Additional information

![](https://user-images.githubusercontent.com/84628426/126055474-0b425d83-f1ed-49b9-85d0-70ca7776cd62.png)
![](https://user-images.githubusercontent.com/84628426/126055476-cd1a1b10-2709-4ff3-b066-e27de980183c.png)

**Comment by jellysquid3** [comment]
Please upload a client log file. This will contain some necessary debugging information.

**Comment by jellysquid3** [comment]
Making this issue a parent of #779 for tracking.

**Comment by atomkreuzer** [comment]
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/6838016/latest.log)
https://paste.ee/p/WQTJg

**Comment by ghost** [comment]
I have this issue on a Core i7 3632QM with Radeon HD 7650M machine. It started with build [#499](https://github.com/CaffeineMC/sodium-fabric/actions/runs/1018688006) from [this commit](https://github.com/CaffeineMC/sodium-fabric/commit/634e886bbd748155ee926e335ec23c8fba905d23)
here's my [client log](https://pomf.lain.la/f/cjnmqsj2.txt) too :)

**Comment by egor951** [comment]
Some additional info: these holes are repeating every 8 chunks on both z and x axis, and on y axis it's like 64 block sections in which first 48 blocks are visible and next 16 are not, starting from y=0 and repeating 4 times all the way to the build limit

**Comment by jellysquid3** [comment]
This is now fixed in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1).
