### ISSUE TITLE
Textures do not get rendered correctly for many vanilla blocks

### ISSUE THREAD

**Issue by tajnymag** [jellysquid3/Sodium#772]
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5

### Expected Behavior

Textures to render properly for all of the vanilla blocks.

### Actual Behavior

Textures of many block do not get rendered correctly. Instead they render with a violet/black pattern.

### Reproduction Steps

1. Install Minecraft using SKLauncher and zulufx8 (clean installation of Minecraft, completely empty .minecraft folder)
2. Install Fabric loader using fabric-installer v0.7.4
3. Put fabric-api v0.37.0 to mods/ folder with sodium-fabric v0.3.0
4. Select fabric profile, launch the game
5. Load any game world. Either create new or open existing.

### Java version

Java 16.0.1

### CPU

Intel i7 3770

### GPU

Nvidia GTX 1660 TI

### Additional information

![2021-07-18_11 24 24](https://user-images.githubusercontent.com/3985946/126062234-746518b2-872e-4056-873c-7c3c17bef4d9.png)

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/6835945/latest.log)

**Comment by tajnymag** [comment]
Does not happen in vanilla launcher. Closing the issue.

**Comment by Leo40Git** [comment]
**Heads up:** SKLauncher is a _cracked launcher_.

Due to ethical and ToS-related concerns, these launchers are not supported.

**Comment by tajnymag** [comment]
> **Heads up:** SKLauncher is a _cracked launcher_.
> 
> Due to ethical and ToS-related concerns, these launchers are not supported.

Yes. That's why I also checked the official launcher and closed the issue.

**Comment by Leo40Git** [comment]
Just wanted to let people know, since "this doesn't happen with the Vanilla launcher, therefore the issue is invalid" is ambiguous at best (launchers shouldn't affect the game anyway).

**Comment by Leo40Git** [comment]
oh I just realized you created this issue
