### ISSUE TITLE
Corruption when using certain older AMD GPUs

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#779]

**Comment by Hughp135** [comment]
What? at least describe your issues

**Comment by K0-RR** [comment]
@Hughp135 Uhhh can you look at the name of the person who opened this issue XD

**Comment by MeeniMc** [comment]
I have had an instance of a missing chunk with fairly recent AMD hardware (rx 580), it happened only once in several days, so it appears to be fairly rare on thid hw, there was no message in the log, and f3-A fixed it.

**Comment by Rajbir98** [comment]
I Hope This Will Be Fixed

**Comment by Hughp135** [comment]
> @Hughp135 Uhhh can you look at the name of the person who opened this issue XD

Still doesn't hurt to follow good practises even if you're the owner of a repository.

**Comment by jellysquid3** [comment]
@Hughp135 The reason for the blank issue is because this issue has no meaning itself for the time being. It's just for tracking, to group other issues under it.

**Comment by kalinos2002** [comment]
will it be fixed?

**Comment by Rajbir98** [comment]
i have a problem if this problem is with drivers so i have a legacy device and update doesnt comes in my device so what can i do

**Comment by Rajbir98** [comment]
I Have Downloaded The Latest Build Of Sodium 529,528 I Am Suprised it Fixes The Issue For Me
Issue That Was Fix #780

**Comment by Eccentricat** [comment]
is this getting fixed?

**Comment by Rajbir98** [comment]
i think yes cause the latest dev build fixes for me it may varies for different devices
still in dev

**Comment by Eccentricat** [comment]
yeah 

> i think yes cause the latest dev build fixes for me it may varies for different devices
> still in dev

yeah it still doesnt work with me (AMD Radeon HD 7450) :(

**Comment by zycin1** [comment]
for me everything works fine once again :) 
R5 M330 (driver 15.201.1101.0)
sodium@0.3.0+build.552

**Comment by StarlingStarwing** [comment]
I think this is the issue I'm having. I have a legacy AMD driver that can't be updated any further and I get graphical glitches both with and without other mods.

![2021-08-14_19 47 14](https://user-images.githubusercontent.com/71734822/129463803-c54aca56-8abc-40c6-9140-7eed1ba5b0da.png)

**Comment by jellysquid3** [comment]
This should now be fixed in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1).
