### ISSUE TITLE
Strange squares mainly in the water

### ISSUE THREAD

**Issue by Wachecheiro** [jellysquid3/Sodium#780]
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5

### Expected Behavior

No squares

### Actual Behavior

Strange squares and apparently low fps, compared to version 1.16.5

### Reproduction Steps

Normal launch

### Java version

jre-16.0.1.9-openj9  (integrated java its the same)

### CPU

Intel Core i5 3550 @ 3.30GHz	Ivy Bridge 22nm Technology

### GPU

2043 (1600x900@60Hz) 512MB ATI AMD Radeon HD 5450 (Dell)

### Additional information

![2021-07-19_01 17 56](https://user-images.githubusercontent.com/70624279/126102868-64aab115-0ebb-401b-b59c-42fac10455df.png)
![2021-07-19_01 17 51](https://user-images.githubusercontent.com/70624279/126102876-3df2264e-6420-43ce-ad32-1e21ef24a3b3.png)

**Comment by jellysquid3** [comment]
Probably another instance of #779.

**Comment by thatshadycodeboi** [comment]
this also happens underground at sea level

**Comment by jellysquid3** [comment]
Should be fixed with d090750.
