### ISSUE TITLE
Visual Sodium Bug

### ISSUE THREAD

**Issue by kalinos2002** [jellysquid3/Sodium#788]
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5

### Expected Behavior

there are bugs that discover the world, or actually cut it out, it appears all over the world mainly near water. I'm sending the screen. https://imgur.com/DoeKOaX

### Actual Behavior

there are bugs that discover the world, or actually cut it out, it appears all over the world mainly near water. I'm sending the screen. https://imgur.com/DoeKOaX

### Reproduction Steps

there are bugs that discover the world, or actually cut it out, it appears all over the world mainly near water. I'm sending the screen. https://imgur.com/DoeKOaX

### Java version

Java 16

### CPU

intel core i7 860

### GPU

radeon hd 5870 2gb eyefinity 6 edition

### Additional information

https://imgur.com/DoeKOaX

**Comment by lostopkk** [comment]
#779

**Comment by kalinos2002** [comment]
will it be fixed? Wysłane z aplikacji Poczta dla Windows 10 Od: lostopkkWysłano: piątek, 23 lipca 2021 02:03Do: CaffeineMC/sodium-fabricDW: kalinos2002; AuthorTemat: Re: [CaffeineMC/sodium-fabric] Visual Sodium Bug (#788) #779—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lostopkk** [comment]
???

**Comment by kalinos2002** [comment]
will it be fixed?
