### ISSUE TITLE
FPS isn't as high as before

### ISSUE THREAD

**Issue by AbrasiveBoar902** [jellysquid3/Sodium#789]
### Version information

mc1.17.1+sodium-fabric-mc1.17.1-0.3.0+build.524

### Expected Behavior

When I use sodium build 524,the fps should be the same as (or higher than)build 503

### Actual Behavior

The fps of build 524 is lower than that of build 503

### Reproduction Steps

use sodium build 524 with minecraft
change it to build 503,and look at the same things
the fps of 503 is higher than 524

### Java version

JDK 16

### CPU

i7-9700

### GPU

GT 630

### Additional information

I tested it in a redstone machine with lots of moving_blocks and it happens.
My friends tested it when playing and it happens too.
Although the FPS is lower,it's much higher than vanilla minecraft (0fps with vanilla,27-29fps with b.524,31-33fps with b.503)

**Comment by Rajbir98** [comment]
I dont know whats the problem but i have a potato pc and the new sodium lags way more

**Comment by TheDevelon** [comment]
It's also creating more lag than helping improving the performance on MacOS

**Comment by Rajbir98** [comment]
Well now i am using sodium build 529 and it stablelizes my fps a bit no unnesary lag spikes
better than build 5

**Comment by mpfaff** [comment]
I haven't noticed the issue @TheDevelon mentions (sodium still improves performance compared to vanilla on macOS Catalina), but I have noticed that the performance boost is less before.

**Comment by sh-lucas** [comment]
It will probably improve when the problems subside and there is more time for refactoring

**Comment by BlueGamingCat1** [comment]
> It's also creating more lag than helping improving the performance on MacOS

Yeah, It's quite bad on MacOS now since the 1.17.1 update.

**Comment by jellysquid3** [comment]
[Sodium 0.3.1 was recently released](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1) and it fixes a lot of performance regressions and other issues that were affecting frame rates. As far as I'm concerned, the performance regressions that users are reporting in this issue have been resolved, and this issue can likely be closed now.
