### ISSUE TITLE
Sodium client can't render the 1.16+ custom biomes.

### ISSUE THREAD

**Issue by casperge** [jellysquid3/Sodium#790]
### Version information

mc1.17.1-0.3.0

### Expected Behavior

The client should render the custom colours of the leaves and grass. This is a new feature of 1.16 and can be achieved with data packs or plugins. This was tested on a server. This is how it looks like on vanilla or on any other client:
![unknown (1)](https://user-images.githubusercontent.com/30176707/126644970-e9fe7b2e-136e-4be8-afe4-d23c3a48ccac.png)

### Actual Behavior

The client doesn't understand the custom biome colours and changes everything to a weird swamp colour. This is how it looks like on sodium:
![unknown](https://user-images.githubusercontent.com/30176707/126645061-b66e4174-6358-472d-99bd-bb30e4928227.png)

### Reproduction Steps

Download a datapack containing custom biomes and run it on a server (only tested it on a server since I do it using a plugin) and you'll see.

### Java version

16

### CPU

i5-8400

### GPU

GTX1070

**Comment by FredTheNerd** [comment]
It looks like you're using cull leaves. Could that be the issue?
