### ISSUE TITLE
Optimisation: Option To Turn Certain Particles On/Off

### ISSUE THREAD

**Issue by FXbiker** [jellysquid3/Sodium#795]
Just similar to optifine, grouping particles together and giving the option to turn them on/off 

e.g. potion particles, 
animated textures (lava, water, nether portal)
along with the amount of particles shown (built into mc) : All, Decreased, Minimal
(rest in attached screenshot)

optional: option to enable/disable block breaking particles as seen in the brilliant mod: Patcher by Sk1er

(Maybe some bug fixes found in Patcher could be used in some of your other mods)

![optifine](https://user-images.githubusercontent.com/87943932/126907079-27d245b7-c032-4b2d-8080-02344f7bbe98.png)

**Comment by jellysquid3** [comment]
Do you have data to show that particles are a significant source of lag w/ Sodium? We already optimize particle rendering quite a bit.

**Comment by FXbiker** [comment]
Not at PC right now, but I can confirm that with alot of modpacks played with optifine, the particle switch is a significant factor as to why my fps is above 300 in some cases (80-120 frames without).

Will test this and provide screenshots tomorrow as I am in England.

**Comment by Rajbir98** [comment]
You Can install Sodium Extra For These Features Simple :)
https://www.curseforge.com/minecraft/mc-mods/sodium-extra

**Comment by Rajbir98** [comment]
# option to enable/disable block breaking particles as seen in the brilliant mod: Patcher by Sk1er #

This Option You Cannot Find In Sodium Extra But You Can Try To Find A Mod For Fabric Which Is Supported With Sodium

**Comment by FXbiker** [comment]
ok thank you!
