### ISSUE TITLE
Massive lag spikes when moving camera around.

### ISSUE THREAD

**Issue by irishgreencitrus** [jellysquid3/Sodium#798]
### Version information

mc1.17.1-0.3.0+build.529

### Expected Behavior

No lag spikes on moving camera, minor lag spikes acceptable if generating chunks, however I was playing on a server and tested on singleplayer too with same outcome.

### Actual Behavior

![image](https://user-images.githubusercontent.com/43090499/127052657-f74f4221-0f6e-4dff-ac43-043d93f8a011.png)
Major lagspikes on moving camera. Can easily go from 120fps -> 3fps and not recover until a few seconds

### Reproduction Steps

Join a server with this build, and move mouse quickly. You should see major lagspikes. If not try using Fast graphics, which were my settings at the time

### Java version

Java 16.0.1 64bit

### CPU

Intel Core i5-1035G4

### GPU

Intel Iris Plus Graphics

**Comment by Rajbir98** [comment]
Its 100% true

**Comment by 7765ax** [comment]
I have the same graphics card and this happens for me aswell in the latest 1.17.1 build making sodium unusable

**Comment by OwnerOfGod** [comment]
I have the same graphics card this happens to me in the latest build on 1.17.1

**Comment by amnotbananaama** [comment]
Can you (or anyone replying here) provide a comparison image with vanilla please? It would help to know if this spike is better, worse, or the same as vanilla

**Comment by ghost** [comment]
in 1.16.+ the lag spike wasn't that extreme when moving camera around, intel i3 3110m, intel hd 4000. on optifine it's lagless.

**Comment by irishgreencitrus** [comment]
> Can you (or anyone replying here) provide a comparison image with vanilla please? It would help to know if this spike is better, worse, or the same as vanilla

Sure here are the comparisons. These comparisons were taken with the same settings, on the same coordinates on the same server at the same ingame time. There are no other mods in the mods folder apart from the sodium build listed in the original post

Graphics: Fast
VSync: OFF
Max Framerate: 60
Smooth Lighting: Maximum
Clouds: Fast
Particles: Minimum 

Vanilla:
![image](https://user-images.githubusercontent.com/43090499/127325894-b772c8c7-7232-460a-99ab-228bfc2dee68.png)
Sodium:
![image](https://user-images.githubusercontent.com/43090499/127327296-aaf771c9-0832-4533-8112-42d288b8bac8.png)

As you can see Sodium performs better when standing still compared to vanilla, however moving camera creates ridiculous lag spikes

**Comment by mpfaff** [comment]
What OS are you on? I've noticed these lag spikes on macOS Big Sur (which has caused me to downgrade to Catalina), and it seems that if I hold any mouse button down while moving, the lag spikes do not occur.

**Comment by irishgreencitrus** [comment]
> What OS are you on? I've noticed these lag spikes on macOS Big Sur (which has caused me to downgrade to Catalina), and it seems that if I hold any mouse button down while moving, the lag spikes do not occur.

Windows

**Comment by jellysquid3** [comment]
This should be fixed in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1). If it isn't, please ask for this issue to be re-opened.
