### ISSUE TITLE
Blocks not appearing at all with Sodium

### ISSUE THREAD

**Issue by Eccentricat** [jellysquid3/Sodium#799]
### Version information

mc1.17.1-0.3.0+build.5

### Expected Behavior

Blocks should be visible when I load a minecraft world

### Actual Behavior

In both singleplayer and servers, blocks do not appear at all. I can move around, place blocks, break blocks, interact with chests etc. and can see all entities from mobs to minecarts. I've tried using a different fabric API downloads (I have this issue with both 0.37.0 and 0.37.1), downloading the fabric installer and installing fabric again completely and removing all other mods from my mods folder. I need Sodium for my game to run above about 12 frames per second!

### Reproduction Steps

Load up a minecraft world with my sodium and fabric versions

### Java version

java 1.17.1

### CPU

Intel Core i5-3470

### GPU

AMD Radeon HD 7450

### Additional information

Probably unimportant but my computer runs windows 7 not windows 10.

**Comment by Eccentricat** [comment]
pretty sure this is because of my graphics card and looking down jelly's already posted this issue.... hope it will be fixed my game runs like ass without goodluck :+1:

**Comment by jellysquid3** [comment]
We're not aware of issues where the world doesn't render _at all_ with an AMD GPU. Can you please provide a client log file so we can look into this and re-open the issue?
