### ISSUE TITLE
glow effect (applied by spectral arrow)

### ISSUE THREAD

**Issue by celakk1** [jellysquid3/Sodium#801]
### Version information

1.16.5

### Expected Behavior

i expected when i was looking on glow it shouldnt lag

### Actual Behavior

when i look on player or mob with a glow effect applied my game drops from 60 to 20 fps, is there's a way to disable it?

### Reproduction Steps

1. type /effect give @p glowing 1000 1
2. click 2 times F5
3. ur game lags very much

### Java version

java 8

### CPU

Intel Core I5 3,4 GHz Quad-core processor 

### GPU

Radeon Pro 560 4 GB RAM

### Additional information

<img width="449" alt="Zrzut ekranu 2021-07-27 o 10 45 49" src="https://user-images.githubusercontent.com/49827604/127124773-32a8bd09-a324-4ba6-aba3-bf624ac6039c.png">

**Comment by jellysquid3** [comment]
Does this issue only happen with Sodium? If not, this would be an enhancement, not a bug report.
