### ISSUE TITLE
Tinted glass does not render behind tinted glass

### ISSUE THREAD

**Issue by bdotsamir** [jellysquid3/Sodium#803]
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5

### Expected Behavior

The glass should render.

### Actual Behavior

It does not.

### Reproduction Steps

1. Place tinted glass in front of tinted glass
2. Observe

### Java version

OpenJDK Java 16

### CPU

Intel i7-8565U

### GPU

Intel UHD Graphics 620

### Additional information

![image](https://user-images.githubusercontent.com/26691026/127210684-ffb1a977-d089-4d6f-9c18-f21f40fd92a8.png)

![image](https://user-images.githubusercontent.com/26691026/127210715-caba3d1b-5c94-4460-8a9b-be029039742c.png)

**Comment by amnotbananaama** [comment]
Duplicate of #38
