### ISSUE TITLE
Option to remove temporary water fog introduced with 1.17 (See video)

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#805]
**VIDEO ATTACHED**
https://user-images.githubusercontent.com/75946024/127414069-702b723a-3511-4435-aba9-483fb94eca49.mp4

**Is your feature request related to a problem? Please describe.**
1.17 introduced a visual change that makes it difficult to see far away underwater when you first go underwater. Then after 5 seconds you can see far away blocks normally. This really bothers me as it essentially undos the great improvements they made to underwater visibility added in 1.13. Before 1.13 seeing underwater was really difficult and annoying. They improved it so much with 1.13, and now have thrown it into the garbage.

**Describe the solution you'd like**
An option to undo the temporary underwater visual fog effects introduced with 1.17. So I can sleep peacefully.

**Describe alternatives you've considered**
I guess that would be to stop playing the game entirely because this change makes it unplayable.

**Comment by Altirix** [comment]
use sodium extras

**Comment by CalXee** [comment]
"Makes the game unplayable"? I mean we all are allowed to have different opinions but I feel its an overreaction to stop playing a game over something as trivial as this? Just a recommendation.

Again, this isn't a good fit for Sodium itself, request it in Sodium Extras if it isn't the case already.

**Comment by jellysquid3** [comment]
While this might be an undesired feature for you, the fog serves a functional purpose (to deliberately obscure vision) and we have no interest in changing that ourselves. For situations like this, there exist other mods, and even addons to Sodium, which can disable undesired graphical effects.
