### ISSUE TITLE
Glitched fire when there's a block on top of it

### ISSUE THREAD

**Issue by giabao06** [jellysquid3/Sodium#806]
### Version information

mc1.17.1-v0.3.0+build.5

### Expected Behavior

Fire under a block should not be visible on the block above it

### Actual Behavior

A little bit of fire is rendered on the block above it (Only 2 sides have this)

### Reproduction Steps

1. Light a fire 
2. Place a block on top of it

### Java version

Java 16.0.1

### CPU

AMD Ryzen 5 3500U

### GPU

AMD Radeon Vega 8

### Additional information

Additional mods: BetterF3, Dynamic FPS, Hydrogen, Lithium, Mod Menu, Ok Zoomer, Starlight and Voxelmap

Examples:
![Example 1](https://user-images.githubusercontent.com/50602726/127489382-b13747a2-2227-4793-a065-ad8c7f4a0d35.png)
![Example 2](https://user-images.githubusercontent.com/50602726/127490275-1917b591-dc12-4371-bab5-4ffd4304e084.png)

**Comment by Altirix** [comment]
you seem to have a modified fire texture that is longer than usual. can you test with the vanilla textures

**Comment by giabao06** [comment]
> you seem to have a modified fire texture that is longer than usual. can you test with the vanilla textures

Vanilla textures is affected too, but the effect is less noticeable
![Vanilla fire](https://user-images.githubusercontent.com/50602726/127540550-7872477a-dde1-46ad-a640-08213920ce8b.png)

**Comment by jellysquid3** [comment]
This is peculiar. I think the problem is that there is a very slight slope to the side of a fire block, and this doesn't get preserved when Sodium chops down the vertex positions to save memory.

**Comment by giabao06** [comment]
Update: soul fire is also affected. Image below is captured with vanilla textures
![2021-07-30_10 40 41](https://user-images.githubusercontent.com/50602726/127596811-f10c5b06-230e-415b-9143-894aad57607e.png)

**Comment by jellysquid3** [comment]
This has been improved significantly with https://github.com/CaffeineMC/sodium-fabric/commit/a1283aae608fc00894e3043fab5569e4bd13d976 but is not perfectly fixed.

**Comment by giabao06** [comment]
Checked w/ build 661, seems to be fixed.
![2021-09-19_13 13 43](https://user-images.githubusercontent.com/50602726/133917479-35770428-8fb8-44df-ad2f-3fe218050448.png)

**Comment by jellysquid3** [comment]
Should be solved in [Sodium 0.3.3](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.3).
