### ISSUE TITLE
I can't use OpenGL Engine

### ISSUE THREAD

**Issue by YumekoCourier** [jellysquid3/Sodium#808]
### Version information

sodium-fabric-mc1.16.5-0.2.0+build.4

### Expected Behavior

Hello! I installed the mod and I have seen some guys on reddit said this mod can use OpenGL API. 
![CHunk](https://user-images.githubusercontent.com/70044919/127640514-667b80e9-f024-41ac-a15a-09ef6b13382a.png)

### Actual Behavior

But for me I can't see it at all.It just says something like "use chunk multi-draw" instead of "Chunk Renderer:Multi-Draw(GL 4.3)". How did that happen? Is that a bug or something else?
![Bug](https://user-images.githubusercontent.com/70044919/127640663-da489d98-eab9-49fd-9dfe-b0361d88be10.png)

### Reproduction Steps

I only installed this mod but it still doesn't work.I've tried reboot my device,reinstall graphic driver,but nothing happens.

### Java version

jdk 11.0.11 64 bit

### CPU

Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz

### GPU

1660ti Max-Q

**Comment by Anshumant7** [comment]
That's not a bug the options screen has just changed a little bit in sodium 0.2.0 & 0.3.0.

**Comment by YumekoCourier** [comment]
> That's not a bug the options screen has just changed a little bit in sodium 0.2.0 & 0.3.0.

but how bro

**Comment by jellysquid3** [comment]
The options are no longer referred to by their OpenGL version, and you can now instead mix-and-match their various features. You already have the "fastest" options enabled, so there's no issue.

- OpenGL 2.0: Basic renderer
- OpenGL 3.1: Basic renderer, with Vertex Array Objects 
- OpenGL 4.3: Multi-draw renderer, with Vertex Array Objects
