### ISSUE TITLE
Hopper glitch

### ISSUE THREAD

**Issue by Teslicek** [jellysquid3/Sodium#809]
### Version information

Sodium 0.3.0 1.17.1

### Expected Behavior

I expected to see blocks, when I am in a hopper, looking straight up and shifting.

### Actual Behavior

When I shift and I'm in a hopper looking straight up, I can't see any blocks.
![1](https://user-images.githubusercontent.com/87967222/127659982-3d40261b-4463-4c3d-ab02-9393d5f228d9.png)
![2](https://user-images.githubusercontent.com/87967222/127660000-1b42b6ea-d5e4-4581-85b4-2fa8b0ba6518.png)

### Reproduction Steps

Just place a hopper in a normal world at y62, go to the middle of the hopper, shift and look straight up. Everything above y62 should turn invisible. If it doesnt work, try to use toggle perspective and then everything below y62 should be invisible.

### Java version

Java 16

### CPU

i5 9300H

### GPU

GTX 1650

**Comment by jellysquid3** [comment]
This should be fixed with 4ab4588.
