### ISSUE TITLE
Dont zoom on the moon

### ISSUE THREAD

**Issue by Bipbip2109** [jellysquid3/Sodium#811]
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5

### Reproduction Steps

Hi i was just looking things with a spyglass and a render distance of 64 ( normaly no problem i have a good computer ) and i just zoomed on the moon and my game crashed after 4/5 seconds i had other mods but sodium was everywhere in the crash report with .sodium.client.render.chunk.RenderSection everywhere idk what happened.

### Crash Report file

[crashreport.log](https://github.com/CaffeineMC/sodium-fabric/files/6951174/crashreport.log)

**Comment by ReperakDev** [comment]
64 render distance? Are you using OptiFine? If you can't provide a crash report or a mod list it's not possible to help.

**Comment by Bipbip2109** [comment]
I just changed a value in the options folder

**Comment by Bipbip2109** [comment]
[hs_err_pid12692.log](https://github.com/CaffeineMC/sodium-fabric/files/6913356/hs_err_pid12692.log)

**Comment by Bipbip2109** [comment]
I found the crash report

**Comment by Altirix** [comment]
Remove your auth token from the logs!
