### ISSUE TITLE
Z-Fighting with Vanilla Tweaks Connected Textures

### ISSUE THREAD

**Issue by Janfel** [jellysquid3/Sodium#815]
### Version information

mc1.17.1-0.3.0+build.5

### Expected Behavior

There should be no Z-fighting on the edges of polished andesite/diorite/granite blocks, lapis lazuli blocks or iron blocks when using the corresponding Connected Textures resource pack from [vanillatweaks.net](https://vanillatweaks.net).

### Actual Behavior

There is Z-fighting on the outer edges of the connected texture. This looks similar to the images in #119.

### Reproduction Steps

1. Install the “Connected Polished Stones” resource pack from the “Connected Textures” tab on [vanillatweaks.net](https://vanillatweaks.net).
2. Place some polished andesite, diorite or granite.
3. Move the camera around a bit.
4. There is Z-fighting on the edges of the blocks.

### Java version

Java 16.0.2 64bit

### CPU

Intel Core i5-6600K

### GPU

NVIDIA GeForce GTX 960/PCIe/SSE2

**Comment by jellysquid3** [comment]
Should be resolved in [Sodium 0.3.3](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.3).

**Comment by MESLewis** [comment]
Not resolved in 0.3.3 for me.
Windows 10
![2021-11-24_12 20 27](https://user-images.githubusercontent.com/597053/143293875-0339ebeb-0e52-4ff1-9cfd-80c0fe66d9b1.png)
Works properly on south and east sides
![2021-11-24_12 21 02](https://user-images.githubusercontent.com/597053/143293896-ce31c32a-c3c2-463e-a14e-35d4847dcdce.png)
