### ISSUE TITLE
Weird issue relating to frame drops and stability on lower-end/older machines

### ISSUE THREAD

**Issue by FoxTheFluffy** [jellysquid3/Sodium#816]
### Version information

1.16+

### Expected Behavior

This is a bit of a long-winded explanation so I apologise ahead of time lol.

Something to do with minecraft versions 1.10+ causes most older, and some modern mid-range, machines to experience a default fps of roughly 4 (despite it running other games without issue). This has been tested on currently 8+ computers locally via people that played on our server(s). 

Installing optifine, going to the animations section/menu, and hitting the "disable all animations" button completely resolves this issue and causes minecraft to run at 30+ fps without fail. This has been tested from 1.7.10 through to 1.16 as of a month ago, and optifine still fixes this issue completely.

We tried installing sodium, and have been told it should resolve fps issues in the same way, but we are still encountering the heavy fps issues previously mentioned. Toggling various options in sodium doesn't impact it at all.

We managed to get it to run on two of our machines (fps was about 20) but then after about 5 minutes we encountered consistent freezing. Every 5 or so minutes it would freeze up for 30 seconds to 2 minutes. At this point we haven't been able to fix the issues going forward so have simply downgrade to forge-based packs with optifine and are avoiding fabric until we can fix this.

I appreciate the effort you have put in to this mod, and it is incredible and clearly works fine for most people, and I don't want to sound rude or ungrateful.

I'm not technically inclined so can't really help with stuff like that but thought I should let you know about this issue as maybe it's something you can find an answer to.

I'll include a step by step below:

1. Minecraft on its own (versions 1.10+) run at very low frames by standard.

2. Optifine being installed fixes this as when users can disable all animations (via the optifine menu) this issue is completely negated.

3. Sodium does not have the same options for this, presumably as it's setup differently, and toggling sodium options doesn't work.

4. on medium-spec older machines that worked somewhat OK and got sodium running decently the freeze-lockup issue occurred every few minutes, causing between 10 to 30 seconds of extremely low fps, occurring every 5 ish minutes.

### Actual Behavior

N/A

### Reproduction Steps

N/A

### Java version

Java 16.0.2

### CPU

Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz   3.40 GHz

### GPU

Intel(R) HD Graphics

### Additional information

I've included my computer specifications (one of the ones that could get it running with the freezing issues). I don't know about the other machine specifics as we disbanded the server a week ago, so have no contact. Hopefully the information I've included helps somewhat.

**Comment by Rajbir98** [comment]
Yeah only low-end pc users can feel the instability of fps

**Comment by jellysquid3** [comment]
Can you still reproduce this in Sodium 0.3.1?

**Comment by foxfluffybuns** [comment]
> Can you still reproduce this in Sodium 0.3.1?

Yes but I ran it past some modders I speak to and they said it is likely due to lower-end pcs not being able to handle minecraft rendering in newer versions so is likely not an issue related to sodium (the fact that sodium lets us run it at all is amazing from what I've been told). It's definitely improved a lot and happens less often though.

**Comment by ppmaks** [comment]
> Yeah only low-end pc users can feel the instability of fps

well this unfinished mod was created for low end pcs so its useless to use it

**Comment by MeeniMc** [comment]
Summary: feature request to disable animated textures. Related to #741
