### ISSUE TITLE
Rendering of resource pack models does not occur at certian angles

### ISSUE THREAD

**Issue by Altirix** [jellysquid3/Sodium#817]
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5.jar

### Expected Behavior

**Vanilla rendering**

cullleaves-2.2.0.jar
fabric-api-0.36.0+1.17.jar
![2021-08-04_14 04 10](https://user-images.githubusercontent.com/19439141/128240357-813a879a-266a-4a33-8f09-18c774298073.png)

### Actual Behavior

**Sodium rendering**

cullleaves-2.2.0.jar
fabric-api-0.36.0+1.17.jar
indium-1.0.0.jar
sodium-fabric-mc1.17.1-0.3.0+build.5.jar
![2021-08-04_14 05 12](https://user-images.githubusercontent.com/19439141/128241162-dd9fbc90-70cd-4e8e-ae72-db37aada7792.png)

### Reproduction Steps

**Version - 1.17.1**

**Required Mods:**
cullleaves-2.2.0.jar
fabric-api-0.36.0+1.17.jar
indium-1.0.0.jar
sodium-fabric-mc1.17.1-0.3.0+build.5.jar

Enable smart leaves in resource packs
observe as vanilla renders all models in view distance while sodium only renders models in the current chunk.

### Java version

Java 16

### CPU

R7 5800x

### GPU

RTX 3080

### Additional information

refers to https://github.com/TeamMidnightDust/CullLeaves/issues/11

this is the only resource pack ive noticed this behaviour on. other resource packs with models render just fine.

**Comment by Altirix** [comment]
Thinking about it. culling the leaves uses isSideInvisible which is for glass in vanilla. so maybe this is related to the translucency sorting?

**Comment by Rajbir98** [comment]
this is why I play in fast graphics

**Comment by Altirix** [comment]
turns out this is present on all packs. it seems to affect all models that fall under the conditions to trigger it. im not sure what exactly causes it but you can easily see it on the Y axis also 3rd person view.

https://cdn.discordapp.com/attachments/752637878462578778/872921788349300797/Base_Profile_2021.08.05_-_19.38.14.09.DVR.mp4

**Comment by Altirix** [comment]
#732

**Comment by MeeniMc** [comment]
still present as-of 0.4.10, related to #732

**Comment by pajicadvance** [comment]
Fixed in 0.5.0.
