### ISSUE TITLE
Both Sodiam or Sodiam from iris has flesh issue

### ISSUE THREAD

**Issue by jerry-0314** [jellysquid3/Sodium#819]
### Version information

minecraft 1.17

### Expected Behavior

It looks like you reload the chunk after break/place/block stacts change(like piston extend) a block and it cause a lot of lag.

### Actual Behavior

It looks like you reload the chunk after break/place/block stacts change(like piston extend) a block and it cause a lot of lag.

### Reproduction Steps

It looks like you reload the chunk after break/place/block stacts change(like piston extend) a block and it cause a lot of lag.

### Java version

java 8/java 16

### CPU

i5 1035G1

### GPU

intel (R) UHD graphics

### Additional information

And i wanna ask is the HopperOptimization from 2No2Name has the version for 1.17 or Lithium has the feature of it

**Comment by Rajbir98** [comment]
fix the spelling of sodium

**Comment by Altirix** [comment]
known issue with intel XE ive only seen chunk flicker being reported by intel 10th and 11th gen igpus

**Comment by Snivine** [comment]
google translator strikes again

**Comment by jellysquid3** [comment]
Closing as duplicate of #853 since I'm pretty sure this issue is describing the same problem and is much better described.
