### ISSUE TITLE
Block outline renders above entities with fabulous graphics.

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#82]
### Expected Behavior
Block outline doesn't render above entities when fabulous graphics are on.

### Actual Behavior
Block outline renders above entities when fabulous graphics are on.

### Reproduction Steps
1-Run this command `/summon minecraft:creeper ~ ~ ~ {NoAI:1b}`
2-Point at the block under the creeper
3-Notice that the block outline renders above the creeper
### Attachments
Excuse the font(it's actually just a bunch of lines forming the text)
![Gotta_love_the_custom_font](https://user-images.githubusercontent.com/63957739/87343197-661f5980-c544-11ea-8bc9-33fe3713c6b0.png)
![New Project](https://user-images.githubusercontent.com/63957739/87451974-8a3c7280-c5f8-11ea-9bbc-7b133a7e5505.png)

### System Information
- Java Version: [jre-14.0.1 hotspot-64bit from AdoptOpenJDK]
- CPU: [Intel celeron N3060]
- GPU: [Intel Hd graphics 400]
### More info
-This mechanics is present with no other mods installed
-This mechanics is present with all renderers
-I am using linux for haven't tested with windows(maybe later).

**Comment by amnotbananaama** [comment]
Cannot reproduce on latest commit. ![](https://i.imgur.com/cABv1XP.png)

* Java Version: jdk-14.0.0.36-hotspot
* CPU: Intel Core i7-5500U
* GPU: Intel HD Graphics 5500

I have all Sodium settings on the "Fast" or "Off", except for "Graphics Quality" on "Fabulous". I tried turning a bunch of options on and off, but I still couldn't reproduce the issue. Can you share your Sodium configuration?

**Comment by ghost** [comment]
I downloaded sodium from curseforge because I was too lazy to build from the latest commit.
Here is my "Options.txt" file
[options.txt](https://github.com/jellysquid3/sodium-fabric/files/4914849/options.txt)
and my "sodium-options.json" content because I can't upload it for some reason:
 

```
{
  "quality": {
    "cloud_quality": "FAST",
    "weather_quality": "FAST",
    "enable_vignette": false,
    "enable_clouds": false,
    "smooth_lighting": "OFF"
  },
  "advanced": {
    "chunk_renderer_backend": "GL43",
    "animate_only_visible_textures": true,
    "use_advanced_entity_culling": true,
    "use_particle_culling": true,
    "use_fog_occlusion": true,
    "use_compact_vertex_format": true,
    "use_chunk_face_culling": true,
    "use_memory_intrinsics": true,
    "disable_driver_blacklist": false
  }
}




```

**Comment by amnotbananaama** [comment]
I still cannot reproduce this with the options you gave above, either with the 0.1 release on CurseForge, or the latest commit.
https://i.imgur.com/uccppTl.png

That is not me saying it DOESN'T happen. Clearly something is different between our configurations that is causing you to see something that I'm not. 

Are you using any other mods with Sodium?

**Comment by ghost** [comment]
Yes I am,
will test without them later

**Comment by ghost** [comment]
here is my mod list:
fabric api (may it is causing the issue since sodium doesn't support the rendering api)
carpet mod
fast furnace and fast bench
lambdynamiclights
lithium
logical zoom
malilib
modmenu
not enough crashes
phosphor
sodium
tweakeroo

**Comment by ghost** [comment]
This mechanics is present with no other mods installed

**Comment by ghost** [comment]
That's a problem with minecraft only on mesa drivers, nothing to do with sodium.

On vanilla minecraft video settings the game will warn you about mesa graphics not being supported when trying to use fabulous graphics.

**Comment by ghost** [comment]
Oh I see,
Sorry for not saying I'm using mesa drivers,
Haven't tested with windows drivers just because I'm lazy.

**Comment by ghost** [comment]
I think I shall close the issue since it is a vanilla one
