### ISSUE TITLE
[1.17.x] Rendering Engine Problems - Sodium Lowers FPS instead of Increasing

### ISSUE THREAD

**Issue by batuhanyilmazer** [jellysquid3/Sodium#825]
### Version information

1.17+

### Expected Behavior

Sodium should increase FPS compared to Vanilla game

### Actual Behavior

Sodium decreases FPS compared to Vanilla game.

### Reproduction Steps

1. Use an old device (like mine) to play Minecraft Java Edition 1.17.1
2. Use Sodium, note FPS
3. Then play in Vanilla, and compare FPS you got.

### Java version

Java 8 (1.8.0_301)

### CPU

Intel Core i5-3340M

### GPU

Intel HD Graphics 4000

### Additional information

# Do you have an idea about why does it happen?
I am sure this happens because of rendering engine. 
# Does it happen in 1.16.x?
No, It doesn't.
# Why It Doesn't Occur On 1.16.x?
In Sodium 1.16.x, I was able to select different rendering engine. Furthermore, If I don't change default rendering engine (I am not sure but I think it was something like Multishot I guess?) in 1.16.x, I have rendering issues like blocks merge, chunks disappear etc. So I need to change Rendering Engine in 1.16.x. 
Shortly, Rendering Engine.
# How We Can Solve It?
You can bring Other Rendering Engine Options back.

**Comment by B1ue-Bandit** [comment]
I'm not smart like this person here, but I definitely have the same issue.

**Comment by QPCrummer** [comment]
@tenardie This issue is not related to the renderer. Jellysquid has merged all of 1.16.x's OGL 4.0 features into OGL 3.0. Upgrading OGL versions doesn't necessarily mean better performance, it basically just adds more features.

**Comment by Belluxx** [comment]
Same issue here. I would like to specify that FPS actually increase, but just when standing still. As soon as you move and new chunks render, you see significant lag that is not present in vanilla minecraft.

**Comment by JieningYu** [comment]
But how you use Java8 to run Minecraft 1.17.1?
*Minecraft1.17+ must use Java 16+ to run.

**Comment by batuhanyilmazer** [comment]
> But how you use Java8 to run Minecraft 1.17.1?
> *Minecraft1.17+ must use Java 16+ to run.

I think Minecraft uses Packaged JRE which is 16. But I have manually installed JRE 8 and JDK 16 on my computer.
So It does not matter.

**Comment by LucilleTea** [comment]
The separate chunk renderers being removed is intentional, they were merged. We are still investigating improvements that can be made here for some hardware.
