### ISSUE TITLE
No chunk option

### ISSUE THREAD

**Issue by thafame** [jellysquid3/Sodium#826]
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5

### Expected Behavior

I have seen guys having these options.

![image](https://user-images.githubusercontent.com/88537058/128492842-1614fb7a-fecd-4da2-b8c9-f1c9bce5a5d5.png)

### Actual Behavior

For me it looks like this...

![image](https://user-images.githubusercontent.com/88537058/128492991-ded9e13c-42c6-44bd-aabe-67827acf9d54.png)

### Reproduction Steps

I've installed sodium with the latest fabric version, restarted my device, updated my graphic drivers, nothing worked.

### Java version

Java 16.0.1 64bit

### CPU

Intel Core i7-7700HQ

### GPU

NVIDIA GeForce GTX 1060 with Max-Q Design

### Additional information

My mods folder:

![image](https://user-images.githubusercontent.com/88537058/128493587-7f5fba5b-8536-4d8a-8148-3d98bcdca1f8.png)

**Comment by LucilleTea** [comment]
This option is removed in sodium 0.3.0, you cannot make this choice.
