### ISSUE TITLE
I don't know if the bug is because of Sodium or Iris, but when used together it results in a crash 

### ISSUE THREAD

**Issue by XxRAZAxX** [jellysquid3/Sodium#828]
### Version information

mc1.16.3-0.1.0

### Reproduction Steps

click the launch button

### Crash Report file

[crash-2021-08-07_22.05.32-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/6949645/crash-2021-08-07_22.05.32-client.txt)

**Comment by jellysquid3** [comment]
> Caused by: java.lang.IllegalStateException: You do not have a compatible version of Sodium installed! You have 0.1.0 but 0.2.0+IRIS3 is expected
