### ISSUE TITLE
OpenGL Errors [Sodium & Lithium Only]

### ISSUE THREAD

**Issue by GamingInfinite** [jellysquid3/Sodium#835]
### Version information

mc1.17.1 0.3 build 5

### Expected Behavior

There aren't OpenGL errors being generated every second, thus making my game lag ever so slightly.

### Actual Behavior

The resulting log of my play session becomes 30mb after maybe a minute or 2 of playtime.
https://pastebin.com/kBQ0Gd1b

### Reproduction Steps

I literally have no clue.  I would like to note the first couple lines on the pastebin, where in a different issue referring to the Fabric Rendering API said it had support for these 3 modules of the rendering API, but nothing else, where it says that there are duplicate modules or smthn.  I've also checked that this isn't an issue with the texture pack I have installed, because I get the same results without it.

### Java version

Java 16.0.1 64-Bit

### CPU

8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.8GHz

### GPU

NVIDIA GeForce GTX 1060/PCIe/SSE2

### Additional information

I previously reported this same issue, but it was waved off as I had a bunch of other mods installed.  I currently only have Sodium 0.3build5 (literally the name of the file distro'd on modrinth) and Lithium 0.7.3, along with the most recent version of Fabric API on the most recent version of Fabric 0.11.6.

**Comment by jellysquid3** [comment]
This should be fixed in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1). If it isn't, please ask for this issue to be re-opened, and provide a new log file.
