### ISSUE TITLE
Add Lazy Chunk Loading

### ISSUE THREAD

**Issue by idkfordisco** [jellysquid3/Sodium#836]
**Is your feature request related to a problem? Please describe.**
Allow chunks to be loaded slowly remove lag spikes 

**Describe the solution you'd like**
Have a option that says Lazy Chunk Loading: with modes such as: very slow, slow, medium, fast, very fast. Whatever option selected will determine how slow chunks load 
 
**Describe alternatives you've considered**
Have a bar that says 1-5 to show how fast chunks load 

**Additional context**
It's like the optifine feature in video settings > other

**Comment by jellysquid3** [comment]
This is more or less an issue that stems from #691. Right now, we don't provide any way to limit the amount of time being spent on chunk uploads, and instead just try to keep the thread pool as busy as possible without overloading it.

I can certainly see the appeal of both allowing the user to limit the number of threads used for chunk building (as to prevent CPU overload, we shouldn't be scheduling so many threads anyways) and the amount of time we spend per-frame trying to submit task builds (to keep frame times more stable).
