### ISSUE TITLE
 Crash when entering nether portal on latest 1.17.x/dev.

### ISSUE THREAD

**Issue by Fox2Code** [jellysquid3/Sodium#841]
### Version information

mc1.17.1-0.3.0+build.567

### Reproduction Steps

1. Enter a nether portal

### Crash Report file

[crash-2021-08-17_19.32.11-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7001896/crash-2021-08-17_19.32.11-client.txt)

### Additional information

The crash happen both in single and multi player.

At the time of this issue, I use the latest git version of Sodium from the `1.17.x/dev` branch. (https://github.com/CaffeineMC/sodium-fabric/commit/de156764410113516eb65b359a0dc4aaf6d004b9)

I checked duplicates and https://github.com/CaffeineMC/sodium-fabric/issues/832 is not related to this issue.  
(Crash log show different error)

**Comment by Kroppeb** [comment]
Do you have any other mods installed?

**Comment by Mario0051** [comment]
I tested with Sodium by itself and the same crash occurs.

**Comment by Fox2Code** [comment]
After doing some test I found that this commit is at the origin of the crash: https://github.com/CaffeineMC/sodium-fabric/commit/bb33a03d705e7bf7a845445befb9a43b39bcca03
(I Tested the commit before and after)

**Comment by the-pink-hacker** [comment]
The patch suggested in #849, does fix the issue.

**Comment by Fox2Code** [comment]
@RyanGar46 Thank but the crash log if this issue is different than the one of the other issue. (The patch don't fix this issue)
While it's likely that both issues are caused by the same commit, both issues are not caused by the same piece of code.

I think it's likely that the commit probably made `RenderRegionManager` be used before being fully initialized.
NPE often happen when things are used when not initialized. Since both issue are different NPE it make sense.
I think the proposed patch don't really fix the underlying issue.

Thank for redirecting to the other issue I think I have an idea how to fix the issue now.
I think it's because `RenderRegionManager` is used before [`RenderRegionManager.createRegionArenas()`](https://github.com/CaffeineMC/sodium-fabric/blob/de156764410113516eb65b359a0dc4aaf6d004b9/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/region/RenderRegionManager.java#L175) being called.

**Comment by gniftygnome** [comment]
>  I think the proposed patch don't really fix the underlying issue.

That was my assumption as well (thus the comment the patch was likely incorrect).  I was kind of surprised adding the null check didn't just kick the crash around somewhere else.  Incidentally, prior to adding that patch, I was also seeing a sporadic crash when the game loses focus.  I didn't have time to look into it.  That may be an interaction with Dynamic FPS but it too *seems* to have stopped.  Just in case somebody reports an issue about that too.

**Comment by jellysquid3** [comment]
Fixed in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1).
