### ISSUE TITLE
Sodium cape (like optifine cape!)

### ISSUE THREAD

**Issue by AKKUKNITE** [jellysquid3/Sodium#846]
Sodium cape which is cape we can get by donating money like 5 dollars.It should only be available to players using sodium mod. It will be a cool cape which we can edit and use at go! It will be a reward for your work as there is high demands for minecraft capes! and your mods has helped many players across the world. Thank you for your time.

**Comment by silversquirl** [comment]
JellySquid has responded to similar requests on discord:

> Players who bought their capes like their capes
> Players who didn't buy capes don't like capes being inserted into an optimization mod
> Capes are purely a utensil for bragging rights. Nobody likes that until they have them.

There are no plans to add custom capes to Sodium. There are several alternative cape mods that you can download for free.
