### ISSUE TITLE
Lag on chunk loading with sodium 3.0.

### ISSUE THREAD

**Issue by AllGudNamesRGone** [jellysquid3/Sodium#851]
**Is your feature request related to a problem? Please describe.**
This feature is related to a problem with sodium in which loading chunks with sodium 3.0 gives me fps drops, some spikes while running and comes to a halt when flying around in creative however the game is buttery smooth if absolutely no chunks are being loaded.

**Describe the solution you'd like**
I'd like those fps drops to be eradicated along with providing the improvements in chunk loading.

**Describe alternatives you've considered**
An alternative could be to just strip the new improvements on chunk rendering and keep a little 'for intel sodium 3.0 version'.

**Additional context**
This doesn't happen with sodium 2.0 (why i suggested the alternative) and only happens on my integrated intel cards (intel iris xe), thanks in advance, all your mods are frickin awesome.
Using,
Fabric loader 1.17.1
Ram of 8 gigs
Mod is Sodium only.

**Comment by jellysquid3** [comment]
This should be fixed in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1). If it doesn't, please provide a client log file and ask for this issue to be re-opened.
