### ISSUE TITLE
VoxelMap rendering blur

### ISSUE THREAD

**Issue by j1g5awi** [jellysquid3/Sodium#852]
### Version information

mc1.17.1-0.3.0+build.5

### Expected Behavior

![W(RKNP@W)CV6ET9S12%J1}7](https://user-images.githubusercontent.com/50312681/130780875-7d425081-532a-429b-b55a-7026f28b1ee6.png)

### Actual Behavior

![ZARNLK A}~I@Y Z07PLQ}SV](https://user-images.githubusercontent.com/50312681/130780552-90e3adca-fa8e-4bca-a584-826f991b2307.png)

### Reproduction Steps

1.  Install VoxelMap and Sodium
2.  Create a new world
3.  Set VideoSettings... -> Quality -> Graphics to Fast or Fancy
4.  Open VoxelMap

### Java version

Java 16

### CPU

Intel Core i5-9300H

### GPU

Nvidia GTX 1660Ti

**Comment by jellysquid3** [comment]
This should be fixed in the experimental branches of Sodium 0.4 for Minecraft 1.17 based on my own testing (and it fixes a pretty significant bug which was allowing this in the first place) but that has not made it to a release version yet.
