### ISSUE TITLE
Chunks momentarily flicker when breaking blocks above y=61

### ISSUE THREAD

**Issue by MenacingPerson** [jellysquid3/Sodium#853]
### Version information

0.3.0+build.5

### Expected Behavior

I expected to have normal minecraft behaviour when breaking blocks and loading chunks.

### Actual Behavior

When breaking blocks, it makes blocks of the same type nearby flicker. This only happens in situations when there are a lot of background apps open or a lot of ram being used.

### Reproduction Steps

Open a bunch of java apps (for most memory consumption) and a few chrome tabs. Then allocate 2gb ram to minecraft. After that is done, you should be able to replicate this issue in a mountains biome with the stone block. Other blocks have some trouble with it.

### Java version

Java 16

### CPU

Intel Core i5-1035G1

### GPU

Intel® UHD Graphics Family

### Additional information

Mods are:
Lithium
Lazydfu
Fabric API
Sodium
MultiConnect

Might be related to #819.

This also happens when:
1) Loading a new world
2) Rarely when loading new chunks

**Comment by jellysquid3** [comment]
Does this still occur in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1)?

**Comment by MenacingPerson** [comment]
Yes, it is still present.

**Comment by MenacingPerson** [comment]
Additional info: it also happens while placing blocks, although if you have already placed the block on that coordinate and broken it, it won't flicker. This also seems to be the case when breaking blocks that are part of a vertical structure, although I can't be sure about that.

Edit: nevermind, it also flickers while placing.

**Comment by MenacingPerson** [comment]
Now it doesn't happen to any block below y: level 61, although i will need to confirm this further.

Edit: just confirmed that nothing flickers below Y=64-61.

Edit 2: Oh. It seems to be fixed in 0.3.2 but i will need to check more.

Edit 3: nope, still there.

Edit 4: Now it's consistently NOT happening.

**Comment by Samisaprogrammer** [comment]
Oh. It seems to be fixed in 0.3.2 but i will need to check more

**Comment by MenacingPerson** [comment]
Update: the entire chunk flickers. Some coordinates will fix their flicker (mostly) after 2-3 breaks/places, while others seem to go on infinitely.

**Comment by Samisaprogrammer** [comment]
I finally figured it out. It's tabbing out. If I tab out, it begins to flicker. Doesn't matter when. If I tab out and come back, it flickers, If I tab out when minecraft is loading, it flickers.

**Comment by jellysquid3** [comment]
We have enough confirmations of this issue so far on Intel hardware, but it's still unknown what's causing the problem.

**Comment by MenacingPerson** [comment]
There was a driver update and it seems to have fixed it for me. I will test further.

**Comment by MenacingPerson** [comment]
ok so it happened once but it seems to be happening much less.

**Comment by jellysquid3** [comment]
Merging this into #869 as it contains additional information and more user reports.
