### ISSUE TITLE
Crash when switching server, latest version 

### ISSUE THREAD

**Issue by andreasdc** [jellysquid3/Sodium#855]
### Version information

https://github.com/CaffeineMC/sodium-fabric/actions/runs/1136452635

### Reproduction Steps

Switch server

### Crash Report file

-

**Comment by andreasdc** [comment]
When I try this it crashes
https://github.com/CaffeineMC/sodium-fabric/commit/fac6e03a22de5510c0cbd0a9d10eceb4455b6601
On this it works
https://github.com/CaffeineMC/sodium-fabric/actions/runs/1062321084

**Comment by jellysquid3** [comment]
Fixed in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1).
