### ISSUE TITLE
visual issues

### ISSUE THREAD

**Issue by lordasg** [jellysquid3/Sodium#856]
### Version information

mc1.17.1 sodium-fabric-mc1.17.1-0.3.0+build.5 

### Expected Behavior

it should just load up as normal

### Actual Behavior

what actually happens is when I load up or create a new world there are
 crazy visual glitches like block textures etc

![2021-08-27_10 27 59](https://user-images.githubusercontent.com/89625757/131074931-497749a0-aabd-4eca-8f89-3eddf4e1b1de.png)

### Reproduction Steps

when I create a new world or load an old one or even a server i see massive glitches made up of block textures but when i go back to vanilla or badlion everything becomes normal

### Java version

latest 

### CPU

AMD A4-6210 APU with AMD Radeon R3 Graphics       1.80 GHz

### GPU

none

**Comment by lordasg** [comment]
update 
my gpu is
amd radeon r3 graphics

**Comment by lordasg** [comment]
![2021-08-27_11 15 29](https://user-images.githubusercontent.com/89625757/131078339-1952b23d-4a5f-48b9-bc49-45ea27bb5cb8.png)
a friend suggested to try sodium iris didnt work either

**Comment by Altirix** [comment]
this is a known issue, affects all GPUs. to my understanding some headway has been made into fixing the problem in the discord and is currently being tested. so it should be soon(tm)

**Comment by jellysquid3** [comment]
Fixed in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1).

**Comment by lordasg** [comment]
Thanks
