### ISSUE TITLE
Sodium seems to crash when using Roughly enough items ui elements

### ISSUE THREAD

**Issue by Dragon20C** [jellysquid3/Sodium#86]
### Expected Behavior
for REI to work fine and be usable

### Actual Behavior
Game freezes, sound plays in the background and sends a crash report

### Reproduction Steps
use any ui used by REI

### Attachments
The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Rendering screen

Log
[crash-2020-07-14_19.13.24-client.txt](https://github.com/jellysquid3/sodium-fabric/files/4920486/crash-2020-07-14_19.13.24-client.txt)

### System Information
Not sure if it matters but i'm also on Linux - Manjaro XFCE
- Java Version: [14]
- CPU: [R5 1600 AF]
- GPU: [GTX 1650]

**Comment by jellysquid3** [comment]
Caused by missing FRAPI support. See #5.

**Comment by Dragon20C** [comment]
@jellysquid3 oh sorry didnt know they were linked

**Comment by Miros77** [comment]
I don't have a crash

**Comment by Miros77** [comment]
[rei no crash.log](https://github.com/jellysquid3/sodium-fabric/files/4922875/rei.no.crash.log)
