### ISSUE TITLE
Game is crashing on a server

### ISSUE THREAD

**Issue by NotADinosaur** [jellysquid3/Sodium#860]
### Version information

I tried 1.17 0.3.0 and also 0.3.0-build-567

### Reproduction Steps

Anytime I join a server the game crashes. According to not enough crashes it's caused by sodium, but I have a lot of other mods so it might be mods conflicting? It also might be because of server plugins or something, so sorry if this is my fault and not sodium's problem. The server I was playing on was nucleoid.xyz but it also happened on my private server.

### Crash Report file

[crash-2021-08-27_15.54.56-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7069900/crash-2021-08-27_15.54.56-client.txt)

**Comment by jellysquid3** [comment]
Fixed in [Sodium 0.3.1](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.1).
