### ISSUE TITLE
Weird entity & entity-related blocks rendering

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#863]
### Version information

0.3.1 Release, but 0.3.2 did not fix the issue too

### Expected Behavior

I expected the regular minecraft gameplay

### Actual Behavior

I became a cheater. Entities render in such a way that I can see some of them through the walls. Same with chests, skulls and some other blocks

### Reproduction Steps

Just play with the mod. Here are some screenshots:
![2021-08-29_02 48 00](https://user-images.githubusercontent.com/76217453/131234568-99e16283-2904-4072-ac57-0cb81abf2e0c.png)
![2021-08-29_02 26 45](https://user-images.githubusercontent.com/76217453/131234572-6abf6f72-e9bc-43b3-bd53-ccd518115ae5.png)
In this picture, as you can see, players look like they're falling down from the blocks they were standing on, but in the game they were actually just standing there, doin' nothing. That's another example of the glitch where I can see entities thru blocks
![2021-08-29_02 48 02](https://user-images.githubusercontent.com/76217453/131234573-17411207-6143-4466-ba2a-ddf57345a73e.png)
![2021-08-29_02 57 12](https://user-images.githubusercontent.com/76217453/131234574-e8c2701d-7cf7-4b13-82c4-dc63933e256f.png)

And here is my F3:
![2021-08-29_03 09 07](https://user-images.githubusercontent.com/76217453/131234580-63bcba9a-4175-43a5-93e0-8585a068ff81.png)

### Java version

AdoptOpenJDK 16

### CPU

AMD Ryzen 3 3200G

### GPU

Vega 8 

### Additional information

Arch Linux

**Comment by jellysquid3** [comment]
I can't reproduce this issue, and haven't been able to find other user confirmations. Can you please provide a complete client log file, or at least a list of mods you are using? There might be an incompatibility at play.

**Comment by MeeniMc** [comment]
Looks invalid, old, stale
