### ISSUE TITLE
Guide on how to change lwjgl version from 3.2.2 to 3.2.3

### ISSUE THREAD

**Issue by eshankiyer** [jellysquid3/Sodium#864]
This is technically not a feature request , just a question. How would you change the lwjgl libraries to be 3.2.3 or the latest dev build on platforms other than arm64 mac? (e.g x64 windows). In the latest patch notes it says that 3.2.3 is supported. I would like to update lwjgl due to the increased performance in the latest dev builds.

**Comment by jellysquid3** [comment]
Questions and other inquiries are best suited for the [official Discord server](https://caffeinemc.net/discord). That said, you aren't going to see any performance improvement in upgrading LWJGL. It's only necessary for ARM64 users because Minecraft wasn't shipping a compatible version of LWJGL.
