### ISSUE TITLE
XP Orbs Transparent/Invisible instead of Green

### ISSUE THREAD

**Issue by devinpowns** [jellysquid3/Sodium#87]
### Expected Behavior

When killing a mob, xp orbs that drop should be green.

### Actual Behavior
When mob is killed, the xp orbs that drop are transparent grayish color / invisible.

### Reproduction Steps

Killing a mob will reproduce said issue.

- Java Version: 1.8.0_51 x64
- CPU: i7 4790k
- GPU: GTX 1080Ti

**Comment by ghost** [comment]
Can you give a screensot???
Minecraft 1.15 changed how xp orbs look so this may be vanilla behaviour.

**Comment by theIglooo** [comment]
> Can you give a screensot???

It only happens with smooth lighting set to high, here's a GIF showing the difference between low and high.

![GIF comparison of smooth lighting settings](https://lambda.sx/d4xa.gif)

**Comment by 3ri4nG0ld** [comment]
Indeed it happens, with Smooth Lighting at a minimum it looks smooth but at maximum the experience orbs look transparent.
Smooth Lighting minimum:
![image](https://user-images.githubusercontent.com/24411137/87561512-b87f8800-c6b4-11ea-8fc4-31c4999a3463.png)

Smooth Lighting maximun:
![image](https://user-images.githubusercontent.com/24411137/87561650-e06eeb80-c6b4-11ea-980c-81cca4009eb3.png)

Smooth Lighting off:
![image](https://user-images.githubusercontent.com/24411137/87561740-009eaa80-c6b5-11ea-8cd7-ef41b8d20538.png)

**Comment by jellysquid3** [comment]
Possibly related to #68.
