### ISSUE TITLE
artifacts on amd gpu

### ISSUE THREAD

**Issue by azuranc** [jellysquid3/Sodium#870]
### Version information

mc1.17.1-0.3.2+build.7

### Expected Behavior

Nothing to look funny.

### Actual Behavior

Triangle artifacts are appearing.

### Reproduction Steps

Fly around to find the artifacts. No problems at all in 0.3.0, but appear in 0.3.1

![2021-08-29_18 46 06](https://user-images.githubusercontent.com/89753599/131269181-5fe6c13f-1c28-4258-affa-1470a35f9e70.jpg)
![2021-08-29_18 46 53](https://user-images.githubusercontent.com/89753599/131269185-7a1aba59-766e-4176-a211-4d8be1de835e.jpg)
![2021-08-29_18 47 13](https://user-images.githubusercontent.com/89753599/131269196-589935ef-2e23-43f6-a87d-d0462c4723b0.jpg)

### Java version

16.0.1

### CPU

Core i5 4690

### GPU

AMD R9 290

### Additional information

AMD driver: 21.5.2
tested with no other mods installed

**Comment by jellysquid3** [comment]
Does changing the "Use Persistent Mapping" or "Chunk Memory Allocator" settings in Video Settings > Advanced fix anything?

**Comment by azuranc** [comment]
That's odd, seems to only happen with both async and persistent mapping enabled. Either option off or both seems fine

**Comment by LizIsTired** [comment]
I have the exact same issue with my AMD GPU

**Comment by Anoaxx** [comment]
Same here

**Comment by jellysquid3** [comment]
Once again, AMD's drivers have managed to break _something_ in Sodium. For the time being, disabling "Use Persistent Mapping" should fix it, at least until we figure out what's going on here. My guess is something with the mapping's coherency flag...

**Comment by eshankiyer** [comment]
Hey you might want to update your launcher/graphics/chipset drivers. AMD announced in one of their later graphics/chipset driver releases they (among other vulkan things) patched something in their implementation of OpenGL. Mesa on Windows could potentially be a very hacky sollution but at least Mesa has a better OpenGL implementation than AMD's

**Comment by azuranc** [comment]
sadly my gpu went legacy a few months ago, maybe somebody with a newer one can try

**Comment by eshankiyer** [comment]
Hmmmm, if its legacy, then linux's mesa might help


https://github.com/pal1000/mesa-dist-win/releases


If not, I suggest you could wait a little bit to buy a new pc. PC prices are insane right now

**Comment by jellysquid3** [comment]
You can't use Mesa's AMD driver on Windows. It's Linux-specific... please don't suggest users do advanced driver replacement with stuff that won't even solve their problem. The Mesa distribution for Windows only provides software solutions and translation layers, neither of which will perform within even 10% of the official AMD OpenGL driver on Windows right now.

**Comment by jellysquid3** [comment]
Should be solved in Sodium 0.3.3... If not, please ask for this issue to be re-opened & provide any other relevant details (hardware information, client log file, etc.)

**Comment by azuranc** [comment]
Seems fixed! Thanks for the great frame rates on amd hardware :)
