### ISSUE TITLE
Fix cauldron water not being translucent

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#876]
Water itself is translucent when placed in the world. It's reasonable to expect it to also be translucent when placed in a cauldron, and I believe it indeed was in much earlier versions, although not consistently, and is also translucent in Bedrock Edition to my knowledge.

However, in modern versions, the water in cauldrons is completely opaque for whatever reason.

Since I think this is to do with the water cauldron block not being declared as a block capable of supporting translucent textures rather than some other rendering bug, I'm not sure if this completely fits in the mod's scope, but the mod is intended to tackle graphical bugs as well, so I'd say it counts in that way.

![2021-08-30_22 57 15](https://user-images.githubusercontent.com/52297970/131411557-50308110-fd06-4f85-8e8a-0f358a5fca51.png)

**Comment by jellysquid3** [comment]
See my response [here](https://github.com/CaffeineMC/sodium-fabric/issues/877#issuecomment-913088462).

> We can't really fix this without providing a resource pack replacement and some sort of mechanism for allowing block models to provide per-quad render layers. This is because by default a block can only render on a single layer, and the tripwire hook model chooses the solid layer (which obviously doesn't support the semi-transparent string in the same model.) There are some projects for Fabric which extend the JSON model format to support this, but right now, we don't currently support those APIs.
>
> I'm also not sure this is the sort of thing we should be going out of our way to fix. While it is true that Sodium fixes some graphical issues, it mostly solves problems where assets (such as a model) aren't rendered correctly, not problems with the assets itself.

**Comment by muzikbike** [comment]
It may be worth noting that RandomPatches fixes this as well, so if Sodium ever does touch this it may be worth keeping this in mind if any compatibility issues show up.
