### ISSUE TITLE
Allow fences and walls to be culled by pressure plates

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#878]
This is a stupidly minor thing and probably not worth doing, but I'll mention it anyway just in case: currently, despite completely covering the face in question, pressure plates aren't capable of culling the top faces of fence posts and wall posts underneath them, resulting in these faces rendering even when not viewable legitimately. Many other blocks do cull fences and walls where expected, e.g. walls on top of fences culling the top of fences.

Fences should also be able to be culled by pots and lanterns.

![2021-08-30_23 07 33](https://user-images.githubusercontent.com/52297970/131412427-86cb5bb8-3a5a-4e69-93be-a0fb737c95e0.png)
![2021-08-30_23 07 43](https://user-images.githubusercontent.com/52297970/131412429-3a0ac53b-e981-4d16-9b8e-d3a2313be377.png)
![2021-08-30_23 07 46](https://user-images.githubusercontent.com/52297970/131412430-82c85cb2-afd6-44a8-ac92-990dde2584d9.png)

**Comment by jellysquid3** [comment]
This is a very small amount of geometry for some very narrow and uncommon scenario. I don't think there is any worthwhile reason to fix it, and definitely no meaningful performance impact from leaving it alone. At least, there would be more of a performance impact special-casing this than rendering a few extra block faces in a world, I imagine.
