### ISSUE TITLE
[Feature Request] Allow the Player to disable or hide Clouds

### ISSUE THREAD

**Issue by LOuroboros** [jellysquid3/Sodium#88]
Title. This is one of the many options that Optifine has, and since Sodium already allows the user to use a Fancy or a Fast solution, just like Optifine does, it would be nice to have an "OFF" option as well in order to disable or hide the Clouds.

**Comment by amnotbananaama** [comment]
This is already a feature of Sodium, in the "General" tab, the third option.
![](https://i.imgur.com/KsaaPqj.png)
Hope that helps!

**Comment by Kroppeb** [comment]
The option to disable clouds is in General

https://cdn.discordapp.com/attachments/651120262129123330/730514477971275866/unknown.png

**Comment by Kroppeb** [comment]
Also that's a Vanilla feature, Fancy/Fast/Off. Not an Optifine one, just FYI

**Comment by LOuroboros** [comment]
> 
> 
> This is already a feature of Sodium, in the "General" tab, the third option.
> ![](https://camo.githubusercontent.com/651ec73dc9fa1ab9c88aa8869ee2b3f4fd432cba/68747470733a2f2f692e696d6775722e636f6d2f4b73616150716a2e706e67)
> Hope that helps!

Ohh, okay. I totally missed it, lmao.
When I thought about disabling the Clouds, I just thought it would be toggleable on the Quality Tab.

Thanks!

**Comment by MMK21Hub** [comment]
I have to agree that it's a bit weird to have an on/off under General and the quality under Quality
