### ISSUE TITLE
Sodium attempts to biome blend Mining Dimension portal blocks for no apparent reason, causing crash.

### ISSUE THREAD

**Issue by noclueumbreon** [jellysquid3/Sodium#881]
### Version information

sodium 0.2.0.build.4

### Reproduction Steps

Install Sodium 0.2.0 build 4
Install Mining Dimensions 1.0.4
Build and light a vanilla nether mining dimension portal
Crash

### Crash Report file

[crash-2021-08-31_16.56.11-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7090728/crash-2021-08-31_16.56.11-client.txt)

### Additional information

The developer of the Mining Dimensions mod and the API causing the crash is aware of the issues- but I thought it'd be a good idea to note it here in case it's not an issue with the Mining Dimensions API. Interestingly, a brief search for the offending java file revealed nothing when looking at the source code in this github- so while I am in fact extremely undertaught in java programming, and especially fabric modding, I still have no clue why this is actually happening considering the file is apparently not a thing that exists.

Is there any documentation on how to trigger Sodium's API to stop doing something?
-7

**Comment by noclueumbreon** [comment]
Notes: It's actually the _gobber_ developer who is aware of the issues, but the Mining Dimension mod uses the exact same API as gobber. This spans multiple versions- the version of sodium I'm using is the most up to date copy I could find for 1.16.5, and the one that they were using was the 0.1.0 copy for 1.16.3(?).
The modpack that's using all of this is _really_ weird considering that the full modpack has several mods which conflict in some way with the three main performance mods (sodium, optifabric, canvas), but it almost works out that all the mods causing issues can be removed. Mining Dimensions is *necessary*, though.

I don't know what your policy on bugfixes in past versions is (which I admittedly should have looked up beforehand- sorry), but I'd greatly appreciate help with fixing this or direction on how to fix it myself.

(the original issue, on the custom portal api that mining dimensions / gobber use)
[https://github.com/kyrptonaught/customportalapi/issues/30#issue-957523407](url)

**Comment by noclueumbreon** [comment]
Looked into it again: It's because Sodium is attempting to biome blend the portal blocks. I have no clue why this is happening.

**Comment by Altirix** [comment]
Was unable to reproduce on 1.16.5 with both build 1.0.4 and 1.0.5 of mining dimensions and sodium 0.2.0 using both multi draw and one shot one thing to note tho, is the portal is darker than normal. usually older versions wont get updates

**Comment by noclueumbreon** [comment]
The portals created using Mining Dimensions are multicolored, but appear to be biome blended for some reason with other mining dimension portals and possibly the terrain. This is likely a reason the crash only happens in some places and only with some portal blocks- and why the original issue appeared to have the bug only happen "on certain seeds." Try testing using portals directly next to each other in BYG's pumpkin fields- that might bring out the bug. As of rn, I was going to start testing whether the portals are only broken due to them being lit previous to when sodium was installed and report back with findings.

**Comment by jellysquid3** [comment]
The biome blending behavior was changed in Sodium 0.5.0 and this shouldn't happen any longer.
