### ISSUE TITLE
Vanilla 1.17 changed ambient sunlight, but Sodium reverts this change.

### ISSUE THREAD

**Issue by thescyphozoa** [jellysquid3/Sodium#883]
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Expected Behavior

Ambient sunlight in 1.17 and 1.17.1 should be darker than in previous versions of Minecraft. I reported this to Mojang as a bug, but it was confirmed as "working as intended". [(my report)](https://bugs.mojang.com/browse/MC-230309) [(same issue, working as intended)](https://bugs.mojang.com/browse/MC-225088) Therefore, the behavior of Sodium should follow suit.

### Actual Behavior

Installing Sodium for 1.17 actually increases the brightness of the entire game, making it look as it did before 1.17.

Sodium 0.3.2: ![2021-09-02_14 28 38](https://user-images.githubusercontent.com/24198099/131921507-fb32a5f3-a14b-4a59-930d-c0a931c68fd0.png)
Vanilla 1.17.1: ![2021-09-02_14 29 22](https://user-images.githubusercontent.com/24198099/131921509-837180d1-89e5-4117-959c-c15bc1d67786.png)
Sodium 0.3.2: ![2021-09-02_14 45 09](https://user-images.githubusercontent.com/24198099/131921512-af9efc63-3103-4b8d-872b-645000c43d76.png)
Vanilla 1.17.1: ![2021-09-02_14 45 43](https://user-images.githubusercontent.com/24198099/131921513-5b0e260a-a9c3-4ea3-a52b-3e1b359f7d91.png)

### Reproduction Steps

1. Take a screenshot in vanilla 1.17.1, ideally using **/gamerule doDaylightCycle false** to preserve lighting conditions.
2. Load the same world in Sodium and take a screenshot from the same angle.
3. Compare brightness.

### Java version

Java 16

### CPU

AMD Ryzen 5 5600x

### GPU

Nvidia GeForce RTX 3060 Ti

### Additional information

lithium-fabric-mc1.17.1-0.7.4

**Comment by jellysquid3** [comment]
I don't actually know _why_ Sodium is brighter. There were a lot of changes in Minecraft 1.17, and looking through them hasn't revealed anything obvious. It seems more like a bug Mojang has introduced in 1.17 and simply has no willingness to debug/fix it.

If anyone has any pointers as to how we can fix this, please drop a comment.

**Comment by mrmangohands** [comment]
Figured out this is the result of a change to the shader assets made in 21w11a rather than game code

**Comment by mrmangohands** [comment]
The relevant change is the switch from texelFetch(Sampler2, UV2 / 16, 0) to minecraft_sample_lightmap(Sampler2, UV2) in the vertex shader for all block render passes (other than tripwire). The latter returns texture(Sampler2, clamp(UV2 / 256.0, vec2(0.5 / 16.0), vec2(15.5 / 16.0)))

**Comment by burgerindividual** [comment]
This has been fixed and should be included in the 0.5.0 release.
