### ISSUE TITLE
just a little question

### ISSUE THREAD

**Issue by Leanchory** [jellysquid3/Sodium#884]
can i use this in minecraft 1.8.9? version 1.16.1 says 1.16.1-0.1. I do not remember the reason why I ask this is to see if I can play skywars with this in 1.8.9 since that is where it is most worth playing skywars

Thanks

**Comment by ItsMaddieNow** [comment]
Sodium is only for 1.16+ if you want better performance on 1.8.9 try optifine, betterfps or vanillafix.
