### ISSUE TITLE
sodium not applying to game

### ISSUE THREAD

**Issue by fuidgsdgfhui** [jellysquid3/Sodium#886]
### Version information

sodium 1.17.1

### Expected Behavior

well sodium should have applyed when i downloaded it but its not giving fps and its not even applyed to my game

### Actual Behavior

i tryed to click on it it didnt give fps or apply to my game

### Reproduction Steps

 i download sodium but it dont work

### Java version

1.17.1

### CPU

core 13

### GPU

intel graphics 620

### Additional information

please help

**Comment by jellysquid3** [comment]
This issue is a support request, not a bug with our mod. Read the [guide for installing Fabric mods](https://fabricmc.net/wiki/install) first. If you still need help, you can join our [official Discord server](https://caffeinemc.net/discord).
