### ISSUE TITLE
Wavy leaves and water!

### ISSUE THREAD

**Issue by Endstarky** [jellysquid3/Sodium#889]
### Version information

1.17.1   0.3.2

### Expected Behavior

As of Vanilla tweaks wavy leaves and water are pre built vanilla features which works with vanilla and there resource pack folder doesnt contain any optifine stuff and it explains it's true!

So please make it possible to have those shading features or give a way to fix it ! 

For more details , here is my resource pack 
[VanillaTweaks_r533015.zip](https://github.com/CaffeineMC/sodium-fabric/files/7133617/VanillaTweaks_r533015.zip)

### Actual Behavior

Wavy leaves and water doesnt work!

### Reproduction Steps

I put on my resource pack , isn't that simple xD!

### Java version

Java 16

### CPU

Intel core TM i3-7100 @ 3.90 ghz

### GPU

Intel HD graphics 630

**Comment by jellysquid3** [comment]
Vanilla shader packs do not work with Sodium, and this will never change due to technical differences in how the two renderers work. At some point we may allow custom, Sodium-specific shader packs, but this is not today.

**Comment by Endstarky** [comment]
so is it not even possible to make a mod like indium which allows to support FRAPI but this mod will bring vanilla rendering in sodium!?

**Comment by Raihanul-Ameen** [comment]
There's a mod called "sodium core shader support" will it be possible to fix it with this mod?
