### ISSUE TITLE
how do I fix this error when compiling 1.15

### ISSUE THREAD

**Issue by Fern-Leaves** [jellysquid3/Sodium#890]
> Configure project :
Fabric Loom: 0.2.7-SNAPSHOT Build(jenkins #40)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\theev\Downloads\sodium-fabric-1.15.x\build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'fabric-loom', version: '0.2.7-SNAPSHOT']
> Failed to apply plugin 'fabric-loom'.
   > Configuration with name 'compile' not found.

**Comment by Anshumant7** [comment]
1.15 is no longer supported by sodium. So you probably shouldn't ask/report this on the issue tracker.

Alternatively you can use mrmangohand's fork of sodium for 1.15 and 1.16.1 here https://github.com/mrmangohands/sodium-fabric/releases

**Comment by jellysquid3** [comment]
You need to use an older version of Gradle.
