### ISSUE TITLE
java.util.concurrent.CompletionException

### ISSUE THREAD

**Issue by StartsMercury** [jellysquid3/Sodium#893]
### Version information

mc1.17.1-0.3.2+build.7

### Reproduction Steps

Theoretical Steps (Sudden crash)

1. Play for some time (few mins)
2. Maybe crash...

### Crash Report file

[crash-2021-09-11_12.25.45-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7147205/crash-2021-09-11_12.25.45-client.txt)
[crash-2021-09-11_13.42.15-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7147290/crash-2021-09-11_13.42.15-client.txt)
[crash-2021-09-11_13.54.39-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7147299/crash-2021-09-11_13.54.39-client.txt)
[crash-2021-09-11_14.01.24-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7147302/crash-2021-09-11_14.01.24-client.txt)

### Additional information

	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.4.3
		antighost: AntiGhost 1.17.1-fabric0.36.1-1.1.4
		appleskin: AppleSkin mc1.17-2.1.3
		autoconfig1u: Auto Config v1 Updated 3.3.1
		betterbeds: Better Beds 1.2.0
		clear-skies: Clear Skies 1.5.70
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config-lite: cloth-config-lite 2.0.6
		cloth-config2: Cloth Config v5 5.0.38
		clumps: Clumps fabric-1.17.1-7.0.5
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		crowdin-translate: CrowdinTranslate 1.3+1.17
		customsplashscreen: Custom Splash Screen 1.1.0
		dynamicfps: Dynamic FPS 2.0.5
		dynmus: Dynamic Music 1.3.1
		enhancedblockentities: Enhanced Block Entities 0.4.1+1.17
		entityculling: EntityCulling-Fabric 1.3.3
		fabric: Fabric API 0.40.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446313
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.2+fc40aa9d18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446313
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+fc40aa9d18
		fabric-rendering-v1: Fabric Rendering (v1) 1.8.1+fc40aa9d18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+198a96213d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.0+fc40aa9d18
		fabricloader: Fabric Loader 0.11.6
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		hydrogen: Hydrogen 0.3
		indium: Indium 1.0.0+mc1.17.1
		itemmodelfix: Item Model Fix 1.0.2+1.17
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lazydfu: LazyDFU 0.1.2
		libzoomer: LibZoomer 0.2.1+1.17
		lithium: Lithium 0.7.4
		minecraft: Minecraft 1.17.1
		minime_paperdoll: Player Mini-Me (Paper Doll) 2.0.0
		modmenu: Mod Menu 2.0.7
		musicdr: Music Duration Reducer 1.2.1
		nofade: No Fade 1.17-2.0.0
		noshades: NoShades Mod 2.2.0
		notenoughanimations: NotEnoughAnimations 1.3.0
		notenoughcrashes: Not Enough Crashes 3.4.4+1.17
		offlineskins: OfflineSkins 1.17.1-v2-fabric
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		particlerain: Particle Rain 1.4.1
		replaymod: Replay Mod 1.17.1-2.6.1
		rightclickharvest: Right Click Harvest 1.4.0
		skinlayers: 3d Skin Layers 1.0.1
		smoke_suppression: Smoke Suppression 1.0.3+MC1.17-1.17.1
		smoothboot: Smooth Boot 1.16.5-1.6.0
		sodium: Sodium 0.3.2+build.7
		sodium-extra: Sodium Extra 0.3.4
		soundphysics: Sound Physics 2.0.0
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight 1.0.0+fabric.73f6d37
		transliterationlib: TRansliterationLib 1.1.0
		worldedit: WorldEdit 7.2.6+4b2d1e7

**Comment by StartsMercury** [comment]
It was sudden, so I'm unsure of the in-game cause. Or maybe a mod conflict...
Also i was on a third party server

**Comment by jellysquid3** [comment]
Can you upload a complete client log file when the issue occurs? The crash report doesn't contain all the required information.

**Comment by StartsMercury** [comment]
no need its an issue with my mod 'noshades'.
(storing LightDataAccess then not releasing after usage, see in [here](https://github.com/StartsMercury/noshades/blob/main/src/main/java/com/github/startsmercury/noshades/mixin/sodium/FluidRendererMixin.java) and moved to [here #1](https://github.com/StartsMercury/noshades/issues/1))
