### ISSUE TITLE
Blockentity with color not rendered correctly

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#895]
### Version information

sodium-fabric-mc1.17.1-0.3.0+build.5

### Expected Behavior

![2021-09-11_21 07 31](https://user-images.githubusercontent.com/61116453/132949016-f7d0cf64-da88-4865-b981-645e108cb8f1.png)

### Actual Behavior

![2021-09-11_21 09 58](https://user-images.githubusercontent.com/61116453/132949026-7f1c6022-b6a7-49a8-be30-5adf4987fa27.png)

### Reproduction Steps

1.Install Sodium and another mod that has blockentity with a block color provider
2.The blockentity is rendered in a strange way

### Java version

Java 16

### CPU

Intel Core i5-10400F

### GPU

NVIDIA GeForce GTX 1650 SUPER

**Comment by jellysquid3** [comment]
Sodium is forcefully blending every color provider incorrectly because our logic is backwards here. This needs to be fixed on our side.

**Comment by jellysquid3** [comment]
Can you check if https://github.com/CaffeineMC/sodium-fabric/commit/634b11ed989482b9aab59ba45acc92ba31b97648 fixes the problem?

**Comment by Micalobia** [comment]
Was wondering if there was an update for this, the behavior stills seems to happen. Biome Blending turned off fixes the issue, if that helps in any way

**Comment by ghost** [comment]
> Can you check if [634b11e](https://github.com/CaffeineMC/sodium-fabric/commit/634b11ed989482b9aab59ba45acc92ba31b97648) fixes the problem?

I've ported [634b11e](https://github.com/CaffeineMC/sodium-fabric/commit/634b11ed989482b9aab59ba45acc92ba31b97648) in 1.19 and tested with my "tun" block, and can confirm it works.

This block is a block entity with an item on its inventory, then the "liquid" inside is colored with a color provider basing on the item (the content), because of that it requires the precise block position and blending its color with other ajacent blocks make no sense.
[TunBlock.java#L235](https://github.com/devpelux/terravibe/blob/4f9cfd3b6e17cbabef534ef4e541e5739a9cbe9f/src/main/java/xyz/devpelux/terravibe/block/TunBlock.java#L235)

Normal:
<img src="https://user-images.githubusercontent.com/32025549/175435467-28ba1f3f-c917-4600-be73-47fe1e181eb0.png" width="500" />

With fix:
<img src="https://user-images.githubusercontent.com/32025549/175435469-432c2ae8-c049-466d-921c-bcfe29d5db42.png" width="500" />

Test for supported blocks: (E.g Grass)
<img src="https://user-images.githubusercontent.com/32025549/175435654-208d7b3e-392b-439d-9dbb-023e38992bce.png" width="500" />

The porting is here #1360 if you are interested, I've also added a way for modders to register new blocks for smooth blending (technically the opposite of #1331 by using the experimental commit), for example if they add new leaves... and added missing 1.18 and 1.19 leaves (I don't know if there are other 1.18 missing blocks... e.g moss??).

@jellysquid3

**Comment by TelepathicGrunt** [comment]
Looks like there was some work back in June that fixed the issue but got lost. I am see this issue in 1.19.2 - 4.4.0 Sodium currently with my Incense Candle block for my Bumblezone mod. Will the fix be looked into again and ported to 1.19.2 and released?

Currently, I found another modder who had the same issue and their solution was to mixin into Sodium but I rather not have to do that
![315F955A-F461-45FD-B8ED-AF0ECD2BE9AD](https://user-images.githubusercontent.com/40846040/205440076-e5fdf076-e054-421c-93e5-07913c6c64dd.png)

**Comment by yedonbro** [comment]
https://www.curseforge.com/minecraft/mc-mods/unofficial-sodium-biome-blending-fix
YAY

**Comment by TelepathicGrunt** [comment]
Poking this to say this is still an issue in 1.19.4 Sodium

**Comment by devpelux** [comment]
# UPDATE
While waiting for this to get officially patched, I've included the fix made in commit https://github.com/CaffeineMC/sodium-fabric/commit/634b11ed989482b9aab59ba45acc92ba31b97648, ported in #1360 from 1.17, into a mod named "Sodium Blending Registry" that includes the `c:blendable` tag too.

Source code: https://github.com/devpelux/sodium-blendingregistry
Mod link: https://modrinth.com/mod/sodium-blendingregistry

The patch is for the latest version of sodium.

**Comment by ghost** [comment]
While waiting for this to get officially patched, I've included the fix made in commit https://github.com/CaffeineMC/sodium-fabric/commit/634b11ed989482b9aab59ba45acc92ba31b97648, ported in #1360 from 1.17, into a mod named "Sodium Blending Registry" that includes the `c:blendable` tag too: https://modrinth.com/mod/sodium-blendingregistry

The patch is for the latest version of sodium.

**Comment by jellysquid3** [comment]
We have a new version of the patch which fixes a lot of issues (commit https://github.com/CaffeineMC/sodium-fabric/commit/651276fdae31e74c3651377a8dcf4413d000831b). The fix will be published with Sodium 0.5, which is the upcoming release... hopefully in the next 2-3 weeks.

There was a lot of work done on the color blending stuff to fix performance/bugs, as Sodium's implementation is a little dumb (incorrectly blended all blocks, including Redstone Wire).

The issue will be closed, but kept with R-pending-release until an actual release of the mod is published with the fix.

**Comment by apexfinity** [comment]
Is Sodium Blending registry mod no longer needed?

**Comment by embeddedt** [comment]
It should not be needed with 0.5 and newer.

**Comment by apexfinity** [comment]
Thanks, feel free to mark this as closed.
