### ISSUE TITLE
Game freezes during startup with older Intel HD Graphics drivers

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#899]
### **See [this comment](https://github.com/CaffeineMC/sodium-fabric/issues/899#issuecomment-1025203807) for a solution to the problem.**

---

There is no crash log or debugging information associated with this problem, aside from the following hardware information: 
[forced-crash.txt](https://github.com/CaffeineMC/sodium-fabric/files/7149883/forced-crash.txt)

Following a bisect, the following commit was revealed to be causing the problem: https://github.com/CaffeineMC/sodium-fabric/commit/bb33a03d705e7bf7a845445befb9a43b39bcca03

My guess is that our fencing logic in MixinMinecraftClient is causing the hang, as it would be the only thing here running early enough that could cause such a problem. It seems that this is dependent on hardware, as we've only seen older Intel cards hang in this manner.

**Comment by LucilleTea** [comment]
Had another report of this on the same hardware with a slightly newer driver version (10.18.10.4358).
Updating to the latest available driver, 15.33.53.5161, reportedly fixed the problem.
[forced crash.txt](https://github.com/CaffeineMC/sodium-fabric/files/7168148/forced.crash.txt)

**Comment by jellysquid3** [comment]
This almost certainly seems like a driver bug with 10.18.10.4358, which affects those with an Baytrail or 3rd generation Intel graphics. [Another user had the affected driver](https://discord.com/channels/602796788608401408/896802064506699846/896811654170439691), and upgrading to 15.33.53.5161 (the latest available) fixed it.

**Comment by jellysquid3** [comment]
Possibly related: https://github.com/CaffeineMC/sodium-fabric/commit/ac0bec6e64697ade618aac2640ece9735bb00790

**Comment by RockStone-God** [comment]
I have intel HD 4000 graphics, could that be an issue for it hanging on loading screen?

**Comment by jellysquid3** [comment]
In every case we've seen, this is caused by out-of-date graphics drivers on Intel _Bay Trail_ and _Ivy Bridge_ CPUs, and is fixed by upgrading the driver to version 15.33.53.5161 (found [here](https://www.intel.com/content/www/us/en/download/18606/intel-graphics-driver-for-windows-15-33.html)).

<details>
<summary>
List of known affected Intel processors
</summary>

    Intel® Celeron® 1000M 
    Intel® Celeron® 1005M 
    Intel® Celeron® 1007U 
    Intel® Celeron® 1017U 
    Intel® Celeron® 1019Y 
    Intel® Celeron® 1020E 
    Intel® Celeron® 1020M 
    Intel® Celeron® 1037U 
    Intel® Celeron® 1047UE 
    Intel® Celeron® 927UE 
    Intel® Celeron® G1610 
    Intel® Celeron® G1610T 
    Intel® Celeron® G1620 
    Intel® Celeron® G1620T 
    Intel® Celeron® G1630 
    Intel® Celeron® G1820 
    Intel® Core™ i3-3110M 
    Intel® Core™ i3-3115C 
    Intel® Core™ i3-3120M 
    Intel® Core™ i3-3120ME 
    Intel® Core™ i3-3130M 
    Intel® Core™ i3-3210 
    Intel® Core™ i3-3217U 
    Intel® Core™ i3-3217UE 
    Intel® Core™ i3-3220 
    Intel® Core™ i3-3220T 
    Intel® Core™ i3-3225 
    Intel® Core™ i3-3227U 
    Intel® Core™ i3-3229Y 
    Intel® Core™ i3-3240 
    Intel® Core™ i3-3240T 
    Intel® Core™ i3-3245 
    Intel® Core™ i3-3250 
    Intel® Core™ i3-3250T 
    Intel® Core™ i5-3210M 
    Intel® Core™ i5-3210M 
    Intel® Core™ i5-3230M 
    Intel® Core™ i5-3230M 
    Intel® Core™ i5-3317U 
    Intel® Core™ i5-3320M 
    Intel® Core™ i5-3330 
    Intel® Core™ i5-3330S 
    Intel® Core™ i5-3337U 
    Intel® Core™ i5-3339Y 
    Intel® Core™ i5-3340 
    Intel® Core™ i5-3340M 
    Intel® Core™ i5-3340S 
    Intel® Core™ i5-3360M 
    Intel® Core™ i5-3380M 
    Intel® Core™ i5-3427U 
    Intel® Core™ i5-3437U 
    Intel® Core™ i5-3439Y 
    Intel® Core™ i5-3450 
    Intel® Core™ i5-3450S 
    Intel® Core™ i5-3470 
    Intel® Core™ i5-3470S 
    Intel® Core™ i5-3470T 
    Intel® Core™ i5-3475S 
    Intel® Core™ i5-3550 
    Intel® Core™ i5-3550S 
    Intel® Core™ i5-3570 
    Intel® Core™ i5-3570K 
    Intel® Core™ i5-3570S 
    Intel® Core™ i5-3570T 
    Intel® Core™ i5-3610ME 
    Intel® Core™ i7-3517U 
    Intel® Core™ i7-3517UE 
    Intel® Core™ i7-3520M 
    Intel® Core™ i7-3537U 
    Intel® Core™ i7-3540M 
    Intel® Core™ i7-3555LE 
    Intel® Core™ i7-3610QE 
    Intel® Core™ i7-3610QM 
    Intel® Core™ i7-3612QE 
    Intel® Core™ i7-3612QM 
    Intel® Core™ i7-3612QM 
    Intel® Core™ i7-3615QE 
    Intel® Core™ i7-3615QM 
    Intel® Core™ i7-3630QM 
    Intel® Core™ i7-3632QM 
    Intel® Core™ i7-3632QM 
    Intel® Core™ i7-3635QM 
    Intel® Core™ i7-3667U 
    Intel® Core™ i7-3687U 
    Intel® Core™ i7-3689Y 
    Intel® Core™ i7-3720QM 
    Intel® Core™ i7-3740QM 
    Intel® Core™ i7-3770 
    Intel® Core™ i7-3770K 
    Intel® Core™ i7-3770S 
    Intel® Core™ i7-3770T 
    Intel® Core™ i7-3820QM 
    Intel® Pentium® 2020M 
    Intel® Pentium® 2030M 
    Intel® Pentium® 2117U 
    Intel® Pentium® 2127U 
    Intel® Pentium® 2129Y 
    Intel® Pentium® A1018 
    Intel® Pentium® G2010 
    Intel® Pentium® G2020 
    Intel® Pentium® G2020T 
    Intel® Pentium® G2030 
    Intel® Pentium® G2030T 
    Intel® Pentium® G2100T 
    Intel® Pentium® G2120 
    Intel® Pentium® G2120T 
    Intel® Pentium® G2130 
    Intel® Pentium® G2140 
</details>

**Comment by jellysquid3** [comment]
[Sodium 0.5.0](https://modrinth.com/mod/sodium/version/mc1.20.1-0.5.0) will now show an error during startup if the broken the drivers are detected.

**Comment by FlossyFish63943** [comment]
JUST. FIX. IT.

**Comment by pajicadvance** [comment]
You're free to debug the broken drivers and propose a fix.
