### ISSUE TITLE
Smooth lighting for paintings

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#90]
It's been done for water, so why not these? Super noticeable and annoying for the bigger paintings.

Not sure if it'd be easy to do though since they're entities

![2020-07-15_13 09 53](https://user-images.githubusercontent.com/52297970/87608626-59dbfd80-c6f8-11ea-90fe-f20f3e969960.png)
![2020-07-15_12 59 35](https://user-images.githubusercontent.com/52297970/87608628-5b0d2a80-c6f8-11ea-9673-4e3beaf5cd6b.png)

**Comment by jellysquid3** [comment]
Does this still occur with "Smooth Lighting" set to "High" in your graphical settings?

**Comment by muzikbike** [comment]
From what i remember, yes. Might have to double check later but I'm pretty sure it had no effect.

**Comment by muzikbike** [comment]
Yes i can confirm that painting lighting is blocky on all three lighting settings

**Comment by muzikbike** [comment]
Still seems present in 1.17.1 with 0.3.0:
![2021-08-28_00 01 57](https://user-images.githubusercontent.com/52297970/131196603-d3c7c87b-0228-48a9-892b-6abfefd3baec.png)

**Comment by muzikbike** [comment]
Can this be reopened?

**Comment by LambdAurora** [comment]
Is it still present in [Sodium 0.3.1](https://modrinth.com/mod/sodium/version/80jYkEVr)?

**Comment by muzikbike** [comment]
Still present in Sodium 0.3.2 which is newer

**Comment by muzikbike** [comment]
Still awaiting reopen.

**Comment by IMS212** [comment]
As far as I am aware, this is currently impossible with 1.17+ due to them using integer coordinates.

**Comment by Felix14-v2** [comment]
As a dirty workaround :D
https://modrinth.com/mod/fast-paintings
