### ISSUE TITLE
Blocks are not displayed at all, and mobs are visible through them

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#900]
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Expected Behavior

The world must be rendered

### Actual Behavior

The world is not rendered, except for the mobs

### Reproduction Steps

Start minecraft 1.17.1 with the following modifications:
 - sodium-fabric-mc1.17.1-0.3.2+build.7
 - Fabric loader 0.11.6

Create NOT multiplayer world and play

### Java version

Java 16 (OpenJDK 1.16.1 2021-04-20 build 16.0.1+9-24)

### CPU

AMD Phenom II X4 925 Processor 2.8 GHz

### GPU

ATI Radeon HD 5800

### Additional information

https://youtu.be/uwAYKJDgBiY

**Comment by jellysquid3** [comment]
Can you please provide a client log file? It may contain information needed to debug this problem...

**Comment by ghost** [comment]
> Can you please provide a client log file? It may contain information needed to debug this problem...

[2021-09-12-1.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/7154666/2021-09-12-1.log.gz)

**Comment by F1rsi** [comment]
> Can you please provide a client log file? It may contain information needed to debug this problem...

**Comment by ghost** [comment]
How soon will you fix the bug with rendering chunks?

**Comment by jellysquid3** [comment]
It's volunteer work and depends on whether or not we can find and fix the issue. We don't/can't provide any time estimates. The crash log just points us in the right direction, it does NOT give the answer for fixing it. Given that these issues are almost always hardware/software specific, and we don't own every computer on the planet, it can take a while before someone discovers a fix (or it gets inadvertently fixed through other things.)

**Comment by ghost** [comment]
This problem started appearing with the first versions of the mod for 1.17
Now I play on version 1.16.5 and such problems do not observe

**Comment by ghost** [comment]
Please help me!!!!!
I found a good build on 1.17.1 for optimization, but it's with Sodium........
:(

**Comment by ghost** [comment]
I just tested my build on another computer and it all worked
Here are its specs:
CPU: AMD Ryzen 3500U with Radeon Vega Mobile Gfx 2.10 GHz
RAM allocated: 1.5Gb
RAM all: 6GB
Java: OpenJDK 16 or OpenJDK 17
The build itself, but I think the Sodium version is important there:
https://drive.google.com/file/d/1EfvzNaLGNwDmtRW-_QWNi4iRNt0vCNJo/view?usp=sharing

**Comment by ghost** [comment]
This problem is fixed by simply updating the drivers. I apologize for wasting your time with me. I'm so happy)))))
