### ISSUE TITLE
I cant play mc using sodium it freezes on startup when loading in the buttons of the start menu

### ISSUE THREAD

**Issue by kr1viah** [jellysquid3/Sodium#903]
### Version information

1.17.1 or 1.17

### Reproduction Steps

Startup mc
Loading in the buttons(multiplayer, single, etc.)
Freeze

### Crash Report file

I doesnt crash so yeeeaaaaaaaaa

### Additional information

(i need to close it with task mannager)

**Comment by jellysquid3** [comment]
Duplicate of #899.
