### ISSUE TITLE
Bright diagonal lines can appear in shaded areas

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#905]
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Expected Behavior

The area under this tree should darken smoothly as it progresses to the trunk.

### Actual Behavior

Four brighter lines can be seen circling the trunk, which is completely illogical - the world and geometry do not indicate that these should be present at all.

### Reproduction Steps

1. Build a setup similar to this tree over a floor where smooth lighting is easy to observe, such as white concrete. A 5x5 square above it should suffice, and a central trunk will help to accentuate these lines
2. Pain

### Java version

16

### CPU

4x Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz

### GPU

Intel(R) HD Graphics 2500

### Additional information

lithium-fabric-mc1.17.1-0.7.4

![2021-09-13_22 03 43](https://user-images.githubusercontent.com/52297970/133156619-e1dcfcc1-a701-4262-a99a-e3f5c4f9a7ef.png)

**Comment by RGFTheCoder** [comment]
I believe that this is due to how the shadows are rendered based on each vertex having a shadow value, so it cant be perfectly smooth, and will show the triangles if you look too closely. Maybe, increasing Smooth Shading if you haven't might allevieate the issue

**Comment by jellysquid3** [comment]
It's not possible to fix this issue without radical changes to how lighting works (i.e. generating a light map texture which is UV mapped to geometry, rather than using per-vertex colors.)  We are probably never going to implement that just due to how invasive it is.
