### ISSUE TITLE
Insane lag/memory leak!

### ISSUE THREAD

**Issue by Endstarky** [jellysquid3/Sodium#907]
### Version information

0.3.2+build.503

### Expected Behavior

Normal!

### Actual Behavior

my minecraft is lagging like hell fps is decent at start then starts to drop aftertime and I also face insane lag due to which i died millions of time!
These lags mostly can be seen faster when i change dimensions like nether travel.

Here is a spark report if this help :
https://spark.lucko.me/ZPfMH5b8Z1

And here is a log!
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/7167996/latest.log)

Please help me with this lag!?

### Reproduction Steps

i told ;-;.

### Java version

Java 16

### CPU

Intel core TM i3-7100 @ 3.90 ghz

### GPU

Intel HD graphics 630

### Additional information

Given log and spark report!

**Comment by jellysquid3** [comment]
Merging this into #909.

**Comment by Endstarky** [comment]
breh ok!
