### ISSUE TITLE
Chunk loading causes significant slowdowns 

### ISSUE THREAD

**Issue by jellysquid3** [jellysquid3/Sodium#909]
Right now, chunk loading uses too many threads and blocks excessively waiting for tasks to finish, causing poor frame rate stability. A lot of work to fix this has been started in Sodium 0.4, but we may want to backport these fixes to Sodium 0.3 in the meantime.

**Comment by eshankiyer** [comment]
0.3 uses around 2 gigabytes on ram with 10 allocated (Just sodium alone, no other mods)

0.4 uses around 0.75 with 12 allocated (Also just Sodium alone, no other mods)

Keep in mind that this could HIGHLY impact people with less than 4gb of ram, which is probably a significant portion of this mod users specs. (All taken with JavaVisualVM + MultiMC)

A lot of people would probably recommend getting a semi-stable version of 0.4, then backporting to 0.3

**Comment by Endstarky** [comment]
So the semi 0.4 version is of the latest beta builds?

**Comment by jellysquid3** [comment]
The relevant option from the `1.17.x/0.4-experiments` branch has now been released as part of [Sodium 0.3.3](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.3).
