### ISSUE TITLE
World renders flickers when world is loaded and rendering then stops though the game is running!

### ISSUE THREAD

**Issue by Endstarky** [jellysquid3/Sodium#911]
### Version information

0.4 experimentals(0.3.2 +build.661)

### Expected Behavior

Normal always!

### Actual Behavior

While I load my world with this version the world render started to flicker(xray, black parts) then stops rendering but the game is still running like if i even exit the world as i know where the exit button is after pressing escape the menu itself even doesn't renders!
Tho its working

Here is the log!
[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/7182601/latest.log)
.

### Reproduction Steps

just load the world.

### Java version

Java 16

### CPU

Intel core TM i3-7100 @ 3.90 ghz

### GPU

Intel HD graphics 630

### Additional information

Giben.

**Comment by MeeniMc** [comment]
Can't replicate on AMD hardware. 

You have a lot of other mods loaded at the same time; some of which are not completely stable. Can you replicate on your end using only Sodium?
