### ISSUE TITLE
Waterlogged trapdoor does not display correctly.

### ISSUE THREAD

**Issue by ZekIzLoupriora** [jellysquid3/Sodium#913]
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Expected Behavior

Water displaying correctly

### Actual Behavior

Water displaying like this:
![изображение](https://user-images.githubusercontent.com/38569354/134047921-dec9a7e7-5a6c-49df-b0bd-cb2b2cbacbb2.png)

### Reproduction Steps

1. Waterlog trapdoor

### Java version

Java 16

### CPU

Ryzen 5 3600

### GPU

Nvidia GTX 750

**Comment by thecoder-001** [comment]
Seems to be fixed after 68ca12bcbd57eddfaf47aa66492464540c2c7581.
(From latest dev build):
![2021-10-11_07 55 46](https://user-images.githubusercontent.com/25097841/136725340-623d31cc-362e-4b94-be85-c851dabd7d3e.png)

**Comment by MeeniMc** [comment]
Issue is resolved in 0.4.10 (if not earlier)

**Comment by pajicadvance** [comment]
Can confirm as fixed.

![2023-05-11_13 43 04](https://github.com/CaffeineMC/sodium-fabric/assets/32738446/dcedbd93-079b-433d-b384-8ac0569c6a9e)
