### ISSUE TITLE
Running fabric, no settings menu for sodium. Only vanilla

### ISSUE THREAD

**Issue by bworrall** [jellysquid3/Sodium#916]
### Version information

1.17.1

### Expected Behavior

The settings menu for fabric should load in with the game

### Actual Behavior

Only vanilla menu loads

### Reproduction Steps

Simply just loading up the game

### Java version

Java 16

### CPU

i7- 8565u

### GPU

Mx250

**Comment by jellysquid3** [comment]
This is a support inquiry regarding installation, not an issue with the mod.

Please use the [official Discord server](https://caffeinemc.net/discord) for support.
