### ISSUE TITLE
Sodium issue I have.

### ISSUE THREAD

**Issue by Violetou** [jellysquid3/Sodium#917]
### Version information

sodium-fabric-mc1.17.1-0,3,2+build.7

### Reproduction Steps

1. Get the new Fabric API And Installer.
2. Put the new main release of sodium into the mods file.
3. Game Crashes.

### Crash Report file

The game crashed whilst unexpected error
Error: com.google.gson.JsonSyntaxException:
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was 
STRING at line 1 column 1 path $
Exit Code: -1

### Additional information

Fabric works with other mods and no mods at all , but with only sodium it crashes.

**Comment by LambdAurora** [comment]
Your sodium config file got corrupted, please remove the file and try again.
For support inquiries [the Discord server is more suited](https://caffeinemc.net/discord).

**Comment by alexmozaidze** [comment]
Would be cool if it would detect for a corrupted config and remove it if it was corrupted
