### ISSUE TITLE
Exit Code : 0

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#922]
So i downloaded the latest Fabric installer (the fabric-loader-0.11.7-1.17.1) and i even downloaded the api and then i downloaded sodium and placed it in the mods folder like i was told. I tried to go in the game but it crashes instantly and just say "Exit code : 0"

**Comment by Altirix** [comment]
IIRC sodium does crash with exit code 0 on the first launch, something to do with there being no config file and in that first launch it creates it and crashes out. the second launch should work fine, however.

**Comment by ghost** [comment]
I got it solved. I had the wrong version, apparently its the wrong version from where I downloaded it at first, later I downloaded it from discord.
