### ISSUE TITLE
[Suggestion] Absorb or supercede existing LoD mods

### ISSUE THREAD

**Issue by jeancallisti** [jellysquid3/Sodium#924]
As a professional developer, for a long time I was wondering why Minecraft doesn't make use of LoD or [imposters](https://calcifer.org/kenneth-christiansen/ComputerScience/imposters.pdf). It seems like the _first_ thing to do to optimise render distance.

6 months ago, I noticed that two mods have emerged that do exactly that : 
- [FarPlaneTwo](https://github.com/PorkStudios/FarPlaneTwo)
- [Minecraft LoD 1.4 alpha ](https://gitlab.com/jeseibel/minecraft-lod-mod/-/releases)

However those incredible mods are still young and somewhat unstable.

Then I discovered Sodium. Sodium seems to be an absolute must-have foundation for any other optimization mod, as it's pushing in every direction simultaneously : data compression, multithreading, etc.

I came to this conclusion : You (JellyFish) should pick one of those mods (or start your own) and contribute to make the selected mod reach an acceptable level of stability. Or at least push to make it 100% compatible with Sodium.

**Comment by Altirix** [comment]
Both mods are on Forge, if you have a look at the experimental branch some work is being done to have a form of LOD on distant foliage, the branch name as it suggests is experimental and shouldn't be used for anything other than testing really, but something like this is already being looked into.

**Comment by jeancallisti** [comment]
In this case it's more about having LoD on (very) distant chunks -- the entirety of the chunk. The side facing the player being cached as a 2D image. Or only the surface-level blocks. Etc.

**Comment by jellysquid3** [comment]
We have plans to implement a basic level-of-detail system which can eliminate distant geometry without significantly impacting visual quality. This work already exists in the 0.4-experiments branch of Sodium.

**Comment by mainrs** [comment]
Is there a tracking issue or PR for this that I can subscribe to?
