### ISSUE TITLE
Minecraft with sodium installed uses more and more ram over time

### ISSUE THREAD

**Issue by boybyboy** [jellysquid3/Sodium#925]
### Version information

fabric-loader-0.11.6-1.17.1

### Expected Behavior

It to be at about 2gb of ram consistently.

### Actual Behavior

I have 2gb allocated to Minecraft but when I start with sodium it starts using more and more ram. Earlier task manger said my pc was using 17gbs of ram on my pc and when I closed Minecraft it said my pc was using 8gb but task manger said Mc was using 6gb. And several times i say Mc was gaining a Mb per second. And then I uninstalled sodium and it stop doing that but it still gains quite a bit of ram every time I log in and out of my friends server.

### Reproduction Steps

Its just happening to me and I don't know if this has happened to a lot of people. Maybe all my mods?

### Java version

java 16.0.1

### CPU

Intel Xeon CPU E5-1630 v3 @ 3.70GHz

### GPU

GeForce RTX 2060

### Additional information

ConnectedTexturesMod, Litematica, MaLiLib, Minihud, Modmenu, Nofog, indium(with sodium) and OkZoomer.

**Comment by jellysquid3** [comment]
Please provide a client log file and the version of Sodium you are using.

**Comment by boybyboy** [comment]
[2021-09-25-1.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/7271644/2021-09-25-1.log.gz)
[2021-09-26-1.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/7271645/2021-09-26-1.log.gz)
[2021-09-27-1.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/7271646/2021-09-27-1.log.gz)
[2021-09-28-1.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/7271647/2021-09-28-1.log.gz)

and I was using sodium 0.3.2+build.7

**Comment by SrPatataNegra** [comment]
Yea, this also happens to me. I have 16gb of ram, and when i play like 5-4 hours straight my task manager says that Minecraft is using  6gb of ram.

**Comment by Altirix** [comment]
just want to note that in your logs you have a server that looks to be a private server of yours. you may want to remove refences to the server ip. unsure if its related but your game is throwing loads of unprivilaged errors, maybe its silently failing to set jemalloc too?

**Comment by boybyboy** [comment]
> just want to note that in your logs you have a server that looks to be a private server of yours. you may want to remove refences to the server ip. unsure if its related but your game is throwing loads of unprivilaged errors, maybe its silently failing to set jemalloc too?

oh thank you

**Comment by jellysquid3** [comment]
Closing in favor of #953 since I think the issues are the same.
