### ISSUE TITLE
Block placing and breaking causes rendering issues.

### ISSUE THREAD

**Issue by Danie12345** [jellysquid3/Sodium#928]
### Version information

mc1.17.1-0.3.0+build.5

### Expected Behavior

Rendering should not be affected.

### Actual Behavior

Whenever blocks update, entire sections of the screen go white or transparent for a split second.
Can be activating pistons, falling blocks, chests opening, block placing/removing, etc.

Also occurs when chunks render (sometimes). Especially when going through nether portals (in and out).

The problem stops if I stop using sodium.

### Reproduction Steps

1. Install lithium (mc1.17.1-0.7.3) and sodium (mc1.17.1-0.3.0+build.5) and run game.
2. Enter any world (can be creative or survival).
3. Destroy any block.
4. Place any block.

### Java version

Java 16

### CPU

Intel(R) Core(TM) i5-1035G1

### GPU

NVIDIA GeForce MX330

### Additional information

**Current mods I use:**
fabric-api-0.36.1+1.17
fabricmod_VoxelMap-1.10.15_for_1.17.0
itemscroller-fabric-1.17.1-0.15.0-dev.20210707.005506
litematica-fabric-1.17.1-0.0.0-dev.20210707.011234
lithium-fabric-mc1.17.1-0.7.3 (**already mentioned**)
malilib-fabric-1.17.1-0.10.0-dev.23
minihud-fabric-1.17.1-0.19.0-dev.20210707.150016
modmenu-2.0.2
replaymod-1.17.1-2.6.0
sodium-fabric-mc1.17.1-0.3.0+build.5 (**already mentioned**)
tweakeroo-fabric-1.17.1-0.10.0-dev.20210707.011318
voicechat-fabric-1.17.1-1.1.9

**Video containing examples of block breaking:**
https://drive.google.com/drive/folders/1TVRSlOv1hUsiCVFIITfgQSMAi5DzmJYQ?usp=sharing

**Comment by jellysquid3** [comment]
Can you please provide a screenshot of the F3 debug screen, or a client log file? It's not clear to me which GPU is being used for Minecraft here, since you have a dual-GPU system.

**Comment by Danie12345** [comment]
![2021-10-01_13 35 42](https://user-images.githubusercontent.com/35552263/135670339-20b79914-b58d-4463-9936-6f554c5fcccf.png)

@jellysquid3

**Comment by jellysquid3** [comment]
This looks to be another case of #869 with Intel hardware. You can try working around this issue by configuring your system to use your NVIDIA graphics card for Minecraft instead of the Intel graphics card.
