### ISSUE TITLE
Kelp placed direktly behind glass won't render water through the glass blocks.

### ISSUE THREAD

**Issue by Joulanh** [jellysquid3/Sodium#932]
### Version information

mc1.17.1-0.3.2+build.7

### Expected Behavior

See kelp submerged in water behing glass.

### Actual Behavior

The Water won't render.

### Reproduction Steps

![2021-10-04_02 02 05](https://user-images.githubusercontent.com/80494384/135778050-159c0125-b0bd-4e3a-9fe9-f852e6a041b9.png)

### Java version

Java 16

### CPU

Intel Core i7-8700K

### GPU

MSI Nvidia GTX 1080Ti Gaming X

**Comment by CodeF53** [comment]
Likely a duplicate of #38

**Comment by silversquirl** [comment]
Not a duplicate of 38, but looks similar to #913

**Comment by IMS212** [comment]
Didn’t https://github.com/CaffeineMC/sodium-fabric/commit/68ca12bcbd57eddfaf47aa66492464540c2c7581 fix this? (This commit was made after 0.3.2’s release, so someone needs to test dev)

**Comment by silversquirl** [comment]
Yep, appears to be fixed in latest dev build

**Comment by jellysquid3** [comment]
Resolved in [Sodium 0.3.3](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.3).
