### ISSUE TITLE
Render bug.

### ISSUE THREAD

**Issue by snoowfall** [jellysquid3/Sodium#933]
### Version information

sodium-fabric-mc1.16.3-0.1.0

### Expected Behavior

The game should run smoothly.

### Actual Behavior

This is what happens, and I have tried downloading it again.
https://user-images.githubusercontent.com/79156445/136383961-08a2fb29-ec73-498f-ab36-254e28dc5b8a.mp4

### Reproduction Steps

I just join the game and for few seconds it is fine, but then it starts to go crazy.
No idea how to reproduce this, just install the mod and put it into mods.

### Java version

Java 1.8.0_51, but cmd says its 1.8.0_301

### CPU

Intel Core i5 3230M

### GPU

Intel HD Graphics 4000

### Additional information

Nothing. The video is up there.

**Comment by snoowfall** [comment]
Fixed by changing Multidraw to Oneshot. Closing.

**Comment by jellysquid3** [comment]
Sodium 0.1 is an old version. This problem has been fixed in newer versions. You should try downloading the latest version from https://caffeinemc.net.
