### ISSUE TITLE
Cull bamboo against bamboo

### ISSUE THREAD

**Issue by muzikbike** [jellysquid3/Sodium#937]
Vanilla bug https://bugs.mojang.com/browse/MC-238739. Another close relative of #280, #858, #859 and #878.

While bamboo's top and bottom faces cull as expected against solid blocks, when it comes to against itself, the planes are still always fully rendered, despite being completely invisible in normal gameplay.

**Comment by Altirix** [comment]
Bamboo has been registered as a nonOpaque block. not too sure why. but I've checked by hardcoding shouldDrawSides to handle it as an opaque block and it seems to work fine without any issues

**Comment by MeeniMc** [comment]
Still present in 0.4.10.

Amusingly it is also present in Vanilla 1.19.4 despite being marked as resolved in Mojang tracker. 

Issue also extends to sugar canes and chorus fruits, just as listed in 

https://bugs.mojang.com/browse/MC-248964
https://bugs.mojang.com/browse/MC-249693

**Comment by DragonEggBedrockBreaking** [comment]
> Amusingly it is also present in Vanilla 1.19.4 despite being marked as resolved in Mojang tracker. 

All three bugs in vanilla were closed as "won't fix", so Mojang has acknowledged that the bugs are still in the game.

**Comment by jellysquid3** [comment]
As discussed elsewhere, fixing these issues is likely not possible with reasonable resource pack/mod compatibility unless a new hidden surface elimination algorithm is implemented which works with the geometry itself (rather than comparing the code-specified cull shapes.)
