### ISSUE TITLE
Improving productivity without sacrificing Quality Foliage optimization

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Sodium#941]
**Is your feature request related to a problem? Please describe.**

I propose to add a Function that greatly increase the FPS On a large drawing
On weak and powerful Pc

In minecraft with the included Fancy leaves 
Due to the features of minecraft anti-aliasing
Fancy leaves is not visible in the large render
But it only lowers the FPS by 5 times

So this is what the function is
When enabled, this function
Fancy leaves  will be limited to 16 chunks (Since it is not visible beyond 16 chunks because of the same anti-aliasing, but the FPS spends heavily)

There is an option to add a slider
To change the distance to render Fancy leaves 
Thus, everyone can change the rendering distance of the Fancy foliage, depending on the PC configuration.
Small values like 12 chunks would help on weak video cards and PCs and on laptops

**Additional context**
https://www.youtube.com/watch?v=ZyTWgWRx-zU The video demonstration is clearly visible at 0:04

It can be seen that the quality of the countess does not deteriorate from this
Due to the deterioration of the quality of the foliage, the FPS grows 5 times

I apologize if I made spelling mistakes somewhere
I can provide more demonstrations of this option

**Comment by MeeniMc** [comment]
Something like this is already in the work in the experimental branch.

**Comment by ghost** [comment]
I have looked and tested the function in the experimental version

The foliage quality function makes the foliage opaque, thereby making it look much worse

The option I suggested
Optimizes foliage without compromising its quality

**Comment by MeeniMc** [comment]
This is a duplicate/variant of #662
