### ISSUE TITLE
AE2 Fluix cable has no texture

### ISSUE THREAD

**Issue by Ioandar** [jellysquid3/Sodium#946]
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7

### Expected Behavior

Render Fluix Cable from AE2 normaly

### Actual Behavior

Fluix Cable from AE2 has missing texture (purple/black checker)

### Reproduction Steps

use Sodium (fabric) 
place fluix cable

### Java version

16.01 64bit

### CPU

Intel i5-6800k 3.6GHz (noOC) 16G Memory

### GPU

GTX1050Ti

### Additional information

All other blocks from AE2 render just fine

**Comment by Jomyy** [comment]
this could be due to sodium currently not supporting the Fabric rendering API so no luck there sorry

**Comment by silversquirl** [comment]
Duplicate of #5

**Comment by Ioandar** [comment]
@silversquirl 

fyi: 
I added **[Indium](https://www.curseforge.com/minecraft/mc-mods/indium) by comp500** to my modlist and now all renders and runs fine!
maybe that can help others too?
Thanks for your great work on sodium!
cheers
