### ISSUE TITLE
Crash. Rendering error.

### ISSUE THREAD

**Issue by Anonym3310** [jellysquid3/Sodium#949]
### Version information

sodium-fabric-mc1.17.1-0.3.2build.7.jar

### Reproduction Steps

• Install PojavLauncher from GooglePlay
 • Install Minecraft 1.17.1 in PojavLauncher using this instruction: https://pojavlauncherteam.github.io/updates/117.html#known-issues
 • Install fabric in Minecraft 1.17.1
 • Install Fabric API + Sodium
 • Launch Minecraft
 • We go into a new or already created world and when we try to enter we get a crash

### Crash Report file

[Log_1](https://bytebin.lucko.me/kGJevrsaAX) 
[Log_2](https://gist.github.com/Anonym3310/9f34d75467a79134e43044e6a1098640#file-latest-log) 

### Additional information

If you have any questions related to installing and running Minecraft 1.17.1 + fabric in PojavLauncher, you can ask me in my telegram https://t.me/Anonym3310

**Comment by jellysquid3** [comment]
Pojav launcher is not supported. A compliant OpenGL 3.3 implementation is required for Sodium. It appears that your device is only using an old GLES context (likely because the hardware doesn't support it) or because it's unsupported with the OpenGL wrapper used by Pojav.

**Comment by Anonym3310** [comment]
Understood.  But at the same time Sodium works great in pojav on Minecraft version 1.16.5
