### ISSUE TITLE
Magma Cube skin doesn't in areas where it would normally be hidden by fog

### ISSUE THREAD

**Issue by NoComment1105** [jellysquid3/Sodium#95]
### Expected Behavior
I can still see the magma cubes skin

### Actual Behavior
The magma cube has a light blue tint

### Reproduction Steps
1.Turn Fog off
2. Look towards a magma cube
3. See blue

### Attachments
![2020-07-16_07 41 11](https://user-images.githubusercontent.com/67918617/87636046-fe316480-c737-11ea-8ebc-081a2be54e74.png)

### System Information
- Java Version: [1.8.0_51 64-Bit]
- CPU: [Intel i5 5300 @ 2.30 GHz]
- GPU: [Intel HD 5500]

**Comment by NoComment1105** [comment]
Was carrying on playing and it appears that it is actually all entities in the nether that don't render their skin properly

**Comment by DonSerrot** [comment]
I believe the intention was for the fog option to only remove the overworld fog. The Nether seems to have had different plans. The bug here wouldn't be that the mobs are appearing as if they are still in fog, it's that the nether fog has been removed at all.

**Comment by NoComment1105** [comment]
Oh so the bug is actually fog is removed in the nether?

**Comment by ghost** [comment]
The bug still happens in the overworld,see:
![2020-07-27_20 10 31](https://user-images.githubusercontent.com/68468004/88626428-830a6f80-d0a2-11ea-9fce-9b6b126a6a66.png)

**Comment by NoComment1105** [comment]
Ah okay. So it's just all mobs in fogged areas?

**Comment by NoComment1105** [comment]
Seeing as jelly has removed the fog off feature from sodium, is it wise to close this issue now?

**Comment by LucilleTea** [comment]
Closing this seems sensible to me, though there's the question of whether this happens when another mod removes fog (and whether that's our problem?)

**Comment by NoComment1105** [comment]
Yeah okay, I can confirm it is your problem but fog off has been removed from the `1.16.x/next` branch
