### ISSUE TITLE
breaks water shaders

### ISSUE THREAD

**Issue by rhozetta** [jellysquid3/Sodium#950]
### Version information

mc1.17.1-0.3.2+build7

### Expected Behavior

i expected to see the water wavy

[expectation](https://media.discordapp.net/attachments/890968483846840343/901266218135199774/2021-10-22_20.20.36.png)

### Actual Behavior

vanilla water shaders do not render and the water is opaque. no idea if this bugs out other shaders

[reality](https://media.discordapp.net/attachments/890968483846840343/901266228138631238/2021-10-22_20.21.35.png)

### Reproduction Steps

1. use a resource pack with shaders that effect the water (i used vanilla tweaks' wavy water)
2. look at a body of water, i just went on my world and looked at my lake. i dont know if it looks different for flowing water

### Java version

Java 16

### CPU

Intel Corporation Xeon E3-1200 v6th Gen Core

### GPU

Nvida Quadro M1200

### Additional information

might also be using Intel HD Graphics 630 because its a laptop

**Comment by jellysquid3** [comment]
Resource packs using core shaders are not supported. See https://github.com/CaffeineMC/sodium-fabric/issues/874.
