### ISSUE TITLE
Cull leaves doesn't works with the 1.17 sodiumxIris branch

### ISSUE THREAD

**Issue by Aeldit** [jellysquid3/Sodium#951]
### Version information

v0.3.2+IRIS2-unkown

### Expected Behavior

The leaves should be culled

### Actual Behavior

They are not culled

### Reproduction Steps

Launch the game with sodium and cull leaves

### Java version

16

### CPU

core i-5 8300H

### GPU

NVIDIA GTX 1050

**Comment by silversquirl** [comment]
If you can reproduce this with the normal version of Sodium, send some screenshots here showing what you expect and what you actually see, and I'll reopen the issue.
Otherwise, please report this to the [Iris fork](https://github.com/IrisShaders/sodium-fabric) of Sodium.

**Comment by Aeldit** [comment]
Ok i'll do that with the normal sodium fork. But there is no issue thing on the iris fork of sodium

**Comment by Aeldit** [comment]
yep it doesn't happend with the normal branch
