### ISSUE TITLE
[Feature Request] Anisotropic Filter + AA

### ISSUE THREAD

**Issue by NineKain** [jellysquid3/Sodium#952]
I'd love anisotropic filtering and anti aliasing for Sodium

Resolution Control mod fixes the AA problem by using supersampling, but not the aniso.

**Comment by silversquirl** [comment]
This is not in scope for Sodium, can be implemented in a separate mod

**Comment by MrBlackmidi** [comment]
> This is not in scope for Sodium, can be implemented in a separate mod

Unfortunately, that barely exists if at all (can be done via shaders but that's limited to only the gameplay (not the UI like the splash screen etc) and a mod does exist for it but it uses the least efficient antialiasing method, which is SSAA (super sampling anti aliasing)).
