### ISSUE TITLE
Memory leak on latest and 0.3.1

### ISSUE THREAD

**Issue by natopotato390** [jellysquid3/Sodium#953]
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.7 (Latest directly from Curseforge, multiple older versions tested as well)

### Expected Behavior

Ram usage to hang around the target 2gb max set in launch options.

### Actual Behavior

This issue makes playing with sodium mod for longer periods a problem
Here's minecraft's ram usage at the start:
![memory start](https://user-images.githubusercontent.com/87149753/138757549-2184a191-5709-4ce2-80ca-e645b32ef1c3.png)
Usage roughly 30 minutes later:
![memory 30min](https://user-images.githubusercontent.com/87149753/138757635-d94eb363-e32f-4249-8ed0-7bfde7065adb.png)
Doesn't matter if I don't even load into game and just sit on the menu, it does not stop climbing
Loading into an overworld or a void world doesn't make a difference 
(it does seem to climb a lot slower when on the main menu) 
Issue doesn't happen in any other client, vanilla/optifine/forge, or just fabric without sodium loaded

JVM Args: -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
(just default what minecraft launcher auto puts in there)

I tried pretty much every setting combination in the advanced tab, no difference

I also went back and tried the older 2 versions for 1.17.1, 0.3.1 had the same issues
**0.3.0 worked as normal**, game sat around the 2gb area the whole time with no noticeable increase

Nothing really different stood out, but here's client logs for each
[latest 0.3.0.log](https://github.com/CaffeineMC/sodium-fabric/files/7413087/latest.0.3.0.log)
[latest 0.3.1.log](https://github.com/CaffeineMC/sodium-fabric/files/7413088/latest.0.3.1.log)
[latest 0.3.2.log](https://github.com/CaffeineMC/sodium-fabric/files/7413089/latest.0.3.2.log)

I can absolutely provide any more debug info needed, just let me know.

### Reproduction Steps

-Running on Fabric loader 1.17.1 version 0.11.7
-Load with either Sodium 0.3.1 or 0.3.2 solely
-Opening up task manager and looking for javaw.exe in the details tab, watch the usage slowly climb.
-Being in game seems to make it climb faster (possibly, more testing needed)
-For some reason beyond my know how about this stuff the processes tab does not always show the correct full usage amount (It does however display the correct system usage %)
-Usage will continue to climb to the point of making your system bug out from all the fun things 100% ram usage causes 

### Java version

Java 16.0.1

### CPU

Ryzen 5 2600

### GPU

GTX 1660 Ti 

### Additional information

Windows 10, 16GB 2400mhz ram (2x8gb)

**Comment by okass** [comment]
yeah I noticed memory leak as well

**Comment by myunco** [comment]
yeah I noticed too

**Comment by jellysquid3** [comment]
Probably a result of the new pre-rendered frames limit in Sodium 0.3.1. It was [fixed in another branch](https://github.com/CaffeineMC/sodium-fabric/commit/ac0bec6e64697ade618aac2640ece9735bb00790#diff-32d49112ca8c65ad226a8128c3e567e8f354468efde24c10ed9dcb7980e2387c) but hasn't yet been backported.

**Comment by ssharkkky** [comment]
I noticed that too. My system went down after a long time of playing. The game used 10GB of ram at last. Btw this issue occurs in the latest version of iris too

**Comment by jellysquid3** [comment]
Should be resolved in [Sodium 0.3.3](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.3). Please ask for this issue to be re-opened if you are still experiencing a memory leak in Sodium 0.3.3.
