### ISSUE TITLE
Fog Occlusion is not working at all.

### ISSUE THREAD

**Issue by sevaedric** [jellysquid3/Sodium#969]
I installed sodium and fabric-loader properly. When I apply the setting to turn off the fog, it is still visible!
![image](https://user-images.githubusercontent.com/66696605/141698430-9031e0f9-91f7-40dd-8187-399aefbd8a85.png)
It is definitelly either a bug or my stupid mistake. 
Thanks in advance with helping me with this problem, I think Sodium is one of the most underrated and still the best projects to optimise minecraft. It should be definitelly more recognised. <3

**Comment by Altirix** [comment]
you want sodium-extras to disable the fog. you are turning off fog occlusion, which prevents the rendering of chunks hidden by the fog effect.

**Comment by silversquirl** [comment]
Sodium does not have an option to disable fog. You will need to use a third party mod to do this. Options include Sodium Extra and NoFog, but there are likely others.
