### ISSUE TITLE
blinking when wood falls with Tree Felling

### ISSUE THREAD

**Issue by Lolothepro** [jellysquid3/Sodium#982]
### Version information

0.3.2+build.7

### Expected Behavior

Let no flashing happen

### Actual Behavior

Sodium :

https://user-images.githubusercontent.com/68275908/142736592-15e09c1d-6d84-43ce-a4a8-262952046851.mp4

normal:

https://user-images.githubusercontent.com/68275908/142736605-61af0fae-1e7e-4f35-8d2b-f7f7bfc02551.mp4

### Reproduction Steps

1.Grow a tree
2.break the tree trunk

### Java version

Java 16/17

### CPU

Ryzen 1600

### GPU

GTX 1070

**Comment by Lolothepro** [comment]
If anyone can slow down the video elsewhere X)

**Comment by Heliumrich** [comment]
May be caused by the settings with **async** chunk rendering/building ?

**Comment by Lolothepro** [comment]
No, that doesn't change anything

**Comment by piuvas** [comment]
this [mod](https://modrinth.com/mod/treefelling) is not updated anymore.
