### ISSUE TITLE
Random Water bugs for latest commit as of now

### ISSUE THREAD

**Issue by TheRealJake12** [jellysquid3/Sodium#983]
### Version information

sodium-fabric-mc1.17.1-0.3.2+build.739

### Expected Behavior

water to look like water?

### Actual Behavior

![2021-11-21_02 45 35](https://user-images.githubusercontent.com/84357907/142755666-026bd0e2-7db7-4d17-ba2c-d06018711ed4.png)
![2021-11-21_02 45 38](https://user-images.githubusercontent.com/84357907/142755668-f277ff56-ba07-4519-b133-b50394f0dbe6.png)

### Reproduction Steps

I went underwater to look around and found it. 

### Java version

17

### CPU

Intel core I5 3470

### GPU

GT 730

### Additional information

Its not different biomes or smth. its prolly lighting or smth I have starlight installed idk.

**Comment by MESLewis** [comment]
![2021-11-21_16 59 48](https://user-images.githubusercontent.com/597053/142782333-4b38dbdd-c4e3-4bba-967e-170d13b38e71.png)
I cannot reproduce in the latest 1.17.x/dev or in release.

Does this happen with only sodium installed? Does it happen in the current release version? Are your graphics card drivers up to date?

**Comment by qwert0p** [comment]
I also can reproduce this, issue happens in the 1.17.x/0.4-experiments, not in the 1.17.x/dev.

**Comment by TheRealJake12** [comment]
> ![2021-11-21_16 59 48](https://user-images.githubusercontent.com/597053/142782333-4b38dbdd-c4e3-4bba-967e-170d13b38e71.png) I cannot reproduce in the latest 1.17.x/dev or in release.
> 
> Does this happen with only sodium installed? Does it happen in the current release version? Are your graphics card drivers up to date?

No my GPU drivers are hella out of date, I cant update them either as my card is dead according to NVIDIA.
I had a couple of mods installed
![image](https://user-images.githubusercontent.com/84357907/144695120-65a8bbf3-939d-4c38-862a-e2fe8dbe2f95.png)
