### ISSUE TITLE
Bugged bell animation

### ISSUE THREAD

**Issue by giabao06** [jellysquid3/Sodium#986]
### Version information

mc1.17.1-0.3.2+build.7

### Expected Behavior

The bell should move entirely (image below)
![2021-11-22_19 09 31](https://user-images.githubusercontent.com/50602726/142860379-1e2fd56c-f6af-4f09-a0c9-a802f36923d4.png)

### Actual Behavior

The still bell is still rendered (image below)
![2021-11-22_19 02 56](https://user-images.githubusercontent.com/50602726/142861362-8c3c2d19-fbbf-4e71-8c5c-90378ba705c9.png)

### Reproduction Steps

1. Place a bell
2. Power or ring it and observe

### Java version

Java 17

### CPU

AMD Ryzen 5 3500U

### GPU

AMD Ryzen Vega 8

### Additional information

Mod list:
![image](https://user-images.githubusercontent.com/50602726/142861304-8f72409a-e2a7-4d71-8536-d4d97ea3a515.png)

**Comment by K0-RR** [comment]
You are using Enhanced Block Entities so this is probably an external issue - https://github.com/FoundationGames/EnhancedBlockEntities/issues/38

**Comment by giabao06** [comment]
Oh alright, should I close this issue then?

**Comment by K0-RR** [comment]
If the issue goes away when you remove EBE then yes.

**Comment by giabao06** [comment]
I mean I tested w/ vanilla and no issues so guess I'm closing it
