### ISSUE TITLE
Minecraft cannot open, gives a 'preLaunch' error

### ISSUE THREAD

**Issue by mrphi06** [jellysquid3/Sodium#988]
### Version information

MC version: 1.17.1, Sodium version: 0.3.2+build.7

### Reproduction Steps

1. Install the same mods(?)
2. launch Minecraft on the latest fabric version (0.12.5-1.17.1)
3. Game crashes, gives error related to sodium (Although I am learning Java, I do not understand enough to understand the report)

### Crash Report file

Game log:
[2021-11-23-6.log.gz](https://github.com/CaffeineMC/sodium-fabric/files/7590325/2021-11-23-6.log.gz)

### Additional information

I think that this is all, but I will be happy to provide more information.
Also, there is not a crash log that appeared from this. 
Right before I opened MC, I used Modmenu Modmanager to update several mods

**Comment by MESLewis** [comment]
Sodium 0.3.3 is released now, you can download the update from the usual places, or directly from https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.3https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.17.1-0.3.3

If the problem persists after updating Sodium and all other mods, try removing mods that modify sodium such as sodium-extra and indium. Some changes were made in Sodium 0.3.3 and other mods will need to be updated if they modify sodium.

**Comment by LucilleTea** [comment]
This error means another mod is trying to be compatible with sodium, but you do not have the version of sodium it expects. Please update sodium and all mods that interact with it as MESLewis said.
