### ISSUE TITLE
Minecraft crashes when using newest version of Sodium (0.3.3). Fixed by using 0.3.2.

### ISSUE THREAD

**Issue by eclipseowo** [jellysquid3/Sodium#989]
### Version information

sodium-fabric-mc1.17.1-0.3.3+build.8

### Reproduction Steps

I simply opened Minecraft, selected multiplayer, joined my server and after a few seconds of loading my game crashes.
![image](https://user-images.githubusercontent.com/94932691/143117740-68b1fb38-cd37-41ae-887f-381a904cc778.png)

I do have other mods installed, but the this crash was fixed after switching to the previous version of Sodium, so I doubt they have anything to do with it.

Just in case, my mod list:
- AntiGhost
- Continuity
- Enhanced Block Entities
- FerriteCore
- Indium
- MaLiLib
- MiniHUD
- Starlight

### Crash Report file

[crash-2021-11-23_22.31.35-client.txt](https://github.com/CaffeineMC/sodium-fabric/files/7590969/crash-2021-11-23_22.31.35-client.txt)

**Comment by MESLewis** [comment]
Indium is having issues with the latest sodium. Uninstall indium until they have a compatible release.

**Comment by eclipseowo** [comment]
Yes, after further testing it was Indium, works now! Thanks a lot.

**Comment by TacoTheDank** [comment]
It seems this has been fixed in Indium 1.0.1 https://github.com/comp500/Indium/issues/92

https://github.com/comp500/Indium/releases
