### ISSUE TITLE
Internationalize this mod

### ISSUE THREAD

**Issue by squid233** [jellysquid3/Sodium#99]
Can you add other lang?
你能添加其它语言吗？
I'm always distressed when I can't understand English.
当我看不懂英语时，我总是很苦恼。

If you internationalize this mod, more player will be play it. Some player don't play this mod because they can't understand English.
如果你国际化这个模组，将会有更多的玩家来玩。有些玩家不玩这个模组是因为他们看不懂英语。

I try alternatives, for example: Google Translate. But press <kbd>Alt + Tab</kbd> frequently inconvenient.
我尝试过其它方法，比如谷歌翻译。但是频繁按下<kbd>Alt + Tab</kbd>并不方便。

I hope you will take this suggestion. Thanks!
我希望你能采纳这个建议。不管怎样，感谢你的支持！
> English is not my native language; please excuse typing errors.
> I've posted my question in Chinese and English.
> I'll be glad to translate responses, if you only use one or the other.

**Comment by ghost** [comment]
sodium has plans to allow for translation in 0.2

**Comment by Kroppeb** [comment]
Yes, it's planned to have this mod fully translatable in 0.2 (as tracked in #44). There is no idea of when this would be but hopefully, it won't take too long.
