### ISSUE TITLE
Flicker when the camera moves after teleporting to higher coordinates

### ISSUE THREAD

**Issue by mllightitup** [jellysquid3/Sodium#990]
### Version information

0.3.3
1.18-pre8-0.4.0alpha4

### Expected Behavior

No flicker

### Actual Behavior

Just go to any world and write "/tp 5151515 ~ 2515151515" or any other large coordinates and you will see flashing every time the camera moves

### Reproduction Steps

Go to any world 
write "/tp 5151515 ~ 2515151515" or any other large coordinates

### Java version

Java 17

### CPU

i5 9600K

### GPU

GTX 1060 3Gb

### Additional information

I already wrote about it in discord when the branch 0.4-Experiments first appeared. Now the same thing happened again. In 0.3.2 everything works fine.
This also happens with this version: "sodium-fabric-mc1.18-pre8-0.4.0alpha4"

_No response_

**Comment by LucilleTea** [comment]
Confirmed.
Some footage (heavy photosensitivity warning!)
https://cdn.discordapp.com/attachments/622089187809820672/913267661851488347/2021-11-25_13-47-39.mp4

**Comment by themrrobert** [comment]
Some additional info:
The flicker scales as you go farther, getting worse the farther out you go.

There is noticeable flicker at 500,000 x 500,000. When you reach 1,000,000 x 1,000,000 the flicker is worse: at an annoying level, but mostly playable; by 5,000,000 x 5,000,000 the flicker is so bad its practically unplayable. 

Tested with multiple seeds.

It also seems to flicker [mostly] at chunk borders but not 100% sure on that. 

Tested versions:  
MC 1.17.1
fabric-loader-0.11.7-1.17.1
sodium-fabric-mc1.17.1-0.3.3+build.8

Also compared with:
Vanilla 1.17.1 
Fabric 0.11.7-1.17.1 with all mods listed below.
Neither of these exhibit the flickering.

Additional mods installed:
fabric-api-0.40.0+1.17
fabric-carpet-1.17.1-1.4.52+v211104
lithium-fabric-mc1.17.1-0.7.5
malilib-fabric-1.17.1-0.10.0-dev.26
minihud-fabric-1.17.1-0.19.0-dev.20210707.150016
litematica-fabric-1.17.1-0.0.0-dev.20210906.183617

PC Specs:
Nvidia Titan-X
i7-5960x
64gb ddr4-ram
