### ISSUE TITLE
Settings not visible when switching macOS half retina resolution off.

### ISSUE THREAD

**Issue by DeerEchoes** [jellysquid3/Sodium#995]
### Version information

iris-and-sodium-mc1.17-1.1.2+build.9.jar

### Expected Behavior

When I turned the setting "Use half the resolution on retina displays, vastly improving performance on macOS. Modifying this option will require a game restart" to off and reopened Minecraft, I would expect everything to be the same but just more resolution.

### Actual Behavior

Instead after quitting and opening the game, the settings page seems to be blocked by something, I am still able to hover over each item and it will show me what the settings are, but something isn't allowing the actual page to render, like there is some box over it, because none of the toggles show until the composter one on the Particles page. The setting selections are still visible (General, Quality, Advanced, Animations, Particles, etc.) and the "Shader Packs...", "Buy us a coffee!", and exit button are visible as well.
<img width="1440" alt="Screen Shot 2021-11-25 at 8 19 09 AM" src="https://user-images.githubusercontent.com/95042567/143475180-31a37659-a12b-4da2-b26e-e7a54eb8db74.png">
<img width="1440" alt="Screen Shot 2021-11-25 at 8 19 35 AM" src="https://user-images.githubusercontent.com/95042567/143475230-6516f214-249d-4318-a052-786782ddd535.png">

### Reproduction Steps

1. open the mods in the pictures below with Fabric 0.12.5 on a MacbookAir 2018
2. the setting for having half resolution is already enabled for some reason, so turn it off
3. quit and reopen Minecraft
4. now you cant see your video settings

### Java version

Java 16.0.1

### CPU

Intel Core i5-1030NG7

### GPU

Intel UHD Graphics 617

**Comment by IMS212** [comment]
Sodium Extra is not supported, does this happen without?

**Comment by DeerEchoes** [comment]
> Sodium Extra is not supported, does this happen without?

So I removed Sodium Extra, and the problem is still there.

**Comment by DeerEchoes** [comment]
Sorry nevermind I don't know why I filed this as a sodium bug it was an issue with "Reese's Sodium Options"
