### ISSUE TITLE
Water not visible in fabulous graphics! 

### ISSUE THREAD

**Issue by Endstarky** [jellysquid3/Sodium#996]
### Version information

0..3.3

### Expected Behavior

Water must be visible in fabulous graphics.

### Actual Behavior

Water is not visible in fabulous graphics.

### Reproduction Steps

Go to video settings and turn on fabulous graphics standing near wate

https://user-images.githubusercontent.com/67501470/143532759-7cd7f7dc-80b2-4048-9d4c-f5f469d218d5.mp4

[latest.log](https://github.com/CaffeineMC/sodium-fabric/files/7606546/latest.log)
r.

### Java version

Java 16

### CPU

Intel core TM i3-7100 @ 3.90 ghz

### GPU

Intel HD graphics 630

### Additional information

And just asking if u can unban me in discord, I didnt even break any rule and what I said was a minor stuff.
And I really like to be with the caffine community.

**Comment by qwert0p** [comment]
I think issue explained a bit wrong, can reproduce in experiments branch, not in the dev.

**Comment by Endstarky** [comment]
Nvm can close this issue as it was due to any other mod, I tried with only sodium, lithium and phosphor and it works fine.
:)

**Comment by Aurumaker72** [comment]
This issue is caused partially by Krypton
