### ISSUE TITLE
Game crashes when going fullscreen on macOS

### ISSUE THREAD

**Issue by theRookieCoder** [jellysquid3/Sodium#997]
### Version information

mc1.17.1-0.3.3+build.8

### Reproduction Steps

1. Launch Fabric on macOS with Sodium installed
2. If fullscreen was already on in the `options.txt`, the game might crash
3. If it wasn't, and you enable it in settings, the game might crash

### Crash Report file

[minecraft.log](https://github.com/CaffeineMC/sodium-fabric/files/7607997/minecraft.log)
[macos-crash-report.txt](https://github.com/CaffeineMC/sodium-fabric/files/7607998/macos-crash-report.txt)
I do have other mods installed, however I've tested this with only Sodium and it still crashes. I've had this issue for a _long_ time

### Additional information

The crashes seem to be intermittent. About 80% of the time the game will crash if the fullscreen was already enabled. About 30% of the time, the game will crash when enabling fullscreen in settings

**Comment by ghost** [comment]
Vanilla bug: https://bugs.mojang.com/browse/MC-170545

**Comment by theRookieCoder** [comment]
Huh. I never encountered this in vanilla. Doesn't seem to be Sodium's problem either way, sorry for the disturbance!
