### ISSUE TITLE
Sodium-Starlight incompatiblity on 1.18

### ISSUE THREAD

**Issue by DioEgizio** [jellysquid3/Sodium#998]
### Version information

mc1.18-pre8-0.4.0+alpha4

### Expected Behavior

No rendering issues, like it was on 1.17.x and 1.16.x

### Actual Behavior

![IMG_20211127_083522_083](https://user-images.githubusercontent.com/83089242/143672984-bd9bc442-f4b6-4731-b8e8-723204ddf407.png)

Sodium without starlight works and Starlight without Sodium works so I think it's an incompatibility

Error: [error.txt](https://github.com/CaffeineMC/sodium-fabric/files/7611414/error.txt)

### Reproduction Steps

1. Install fabric for 1.18 rc3
2. Install both starlight and sodium
3. Open a World and you'll see

### Java version

Java 17 (Termurin Build)

### CPU

AMD Ryzen 5 3500u

### GPU

AMD Radeon Vega 8

**Comment by jellysquid3** [comment]
Original text:

> It seems like Starlight [tried to implement a workaround for an unofficial port](https://github.com/PaperMC/Starlight/commit/9f82e79ac425916168d12657c9a4fd805a10d716) of our own mod, and that the workaround causes a sanity check to fail and crash the game with the official version.

> They should revert this change, and preferably not implement fixes for our mod just because of a bug in another person's fork...

---
**Edit**: This is not correct. See Spottedleaf's response below.

**Comment by Spottedleaf** [comment]
I'm not reverting it. It's fixing a Starlight bug, not a Sodium bug.
The actual fix was making sure starlight initialised the emptiness maps (what sections are empty), which are required for the generic get NibbleArray from sectionpos to even work (which is what sodium does on many different versions to get light data)
it just so happens only sodium reads the NibbleArray, and so the actual problem on vanilla was never seen. **_This was noted in the commit message_**, and why Sodium was **_mentioned_** at all.

**Comment by jellysquid3** [comment]
@Spottedleaf Apologies. My understanding of the issue seems to have been clearly incorrect. I will re-open the issue and edit my original statement.

**Comment by Spottedleaf** [comment]
We should sort out what both projects are doing in this area (the load hook) and figure out something that isn't broken...

Starlight is making the runnable they queue in the packet handler immediately execute. However, it's not executing before the chunk is loaded into the client, just immediately after. So I'm not really sure what the errors in the log suggest (perhaps I am clobbering one of your hooks?)

You can find the hooks here:
https://github.com/PaperMC/Starlight/blob/fabric-dev/1.18/src/main/java/ca/spottedleaf/starlight/mixin/client/multiplayer/ClientPacketListenerMixin.java

**Comment by Spottedleaf** [comment]
The problem is a mixin order. Sodium injects the load callback at the end of the packet handler, and I call setLightReady before it. I've set the mixin priority for Starlight to be lower so that Sodium's callback runs first.
I didn't see any other clean way of doing it either.

**Comment by DioEgizio** [comment]
issue has been fixed on [starlight side](https://github.com/PaperMC/Starlight/commit/f8d15947dbaddc6deac8470802919e42ac000129), so closing this issue
